### ISSUE TITLE
Component Filtering returns no results due to Component grid forcing lower case

### ISSUE THREAD

**Issue by blueboxes** [backstage/backstage#10029]
## Expected Behavior

Viewing the Catalog Component grid should allow filter on owner values in the case entered in the yaml file.

## Actual Behavior

It renders in lowercase which may not sound like an issue but adds bugs in filtering.

If you click on the system you are taken to the system screen. If you then click on the link to show all components with that system it filters the component grid using an upper case value. This then shows no results.

### 1. Add a component and system with the TitleCase System Name.
 
```yaml
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: SampleSystem
  description: Sample System with Title Case Name
spec:
  owner: SampleTeam

---

apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: SampleTeam
  description: Sample Team with Title Case Name
spec:
  type: business-unit
  profile:
    displayName: Sample Team
  children: []
  members: []

---

apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: SampleComponent
  description: Sample Component with Title Case Name
spec:
  type: service
  lifecycle: production
  owner: SampleTeam
  system: SampleSystem
```

### 2. View the component grid and Click on the system name
You can see the Team and System names are shown in lower case.

![TitleCaseComponant](https://user-images.githubusercontent.com/985852/160563381-299e1e77-0137-4cc3-bdda-30d2bdb9fbc4.png)

### 3. After selecting the system click on Owned link
![Team](https://user-images.githubusercontent.com/985852/160563409-066a0258-8f4e-4af5-9b1a-c8752953d9a3.png)

### 4. View the results
This passes the name across in uppercase and filters the result however as the filter is case sensitive nothing is shown.
![Filter](https://user-images.githubusercontent.com/985852/160563454-f60e1ced-4b5c-447f-829f-6c4a2b5e9a88.png)
 
**Result:** It filters the component grid using a mixed case value. This then shows no results as all items in the grid are in lower case. 

If you filter using the dropdown it is ok.

![Option](https://user-images.githubusercontent.com/985852/160564521-f8140ab1-6bbb-4cae-8f36-931635a047f9.png)
