### ISSUE TITLE
Backstage running in EKS returns HTTP 500 on the Kubernetes tab while using IRSA

### ISSUE THREAD

**Issue by ccodreanu** [backstage/backstage#10035]
## Expected Behavior

Get app information running in Kubernetes (clusters, pods)

## Actual Behavior

An error is returned, HTTP 500

```
Errors: Request failed with 500 , {"error":"HTTP request failed"}
```

## Steps to Reproduce

1. Have a Kubernetes app in Backstage
2. Navigate to the Kubernetes tab
3. Observe error described above

## Context

```
2022-03-07T12:21:53.745Z backstage info ::ffff:10.10.10.10 - - [07/Mar/2022:12:21:53 +0000] "GET /api/kubernetes/clusters HTTP/1.1" 304 - "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.
36 (KHTML, like Gecko) Chrome/98.0.4758.109 Safari/537.36" type=incomingRequest
2022-03-07T12:21:53.804Z kubernetes info entity.metadata.name=access clusterDetails=[cluster1, cluster2, cluster3] type=plugin
2022-03-07T12:21:54.252Z backstage info ::ffff:10.10.10.11 - - [07/Mar/2022:12:21:54 +0000] "GET / HTTP/1.1" 200 2438 "-" "kube-probe/1.20+" type=incomingRequest
2022-03-07T12:21:54.273Z kubernetes error action=retrieveObjectsByServiceId service=access, error=HttpError: HTTP request failed type=plugin
2022-03-07T12:21:54.275Z backstage info ::ffff:10.10.10.10 - - [07/Mar/2022:12:21:54 +0000] "POST /api/kubernetes/services/access HTTP/1.1" 500 31 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWe
bKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.109 Safari/537.36" type=incomingRequest
```

## Your Environment

- Env:

1. Have a Backstage deployment in EKS using IRSA
2. Have this Kubernetes configurations:
```
kubernetes:
  apiVersionOverrides:
    cronjobs: 'v1beta1'
  serviceLocatorMethod:
    type: 'multiTenant'
  clusterLocatorMethods:
    - type: 'config'
      clusters:
        - url: https://random-id-1.xxx.aws-region-1.eks.amazonaws.com
          name: cluster1
          skipTLSVerify: true
          authProvider: 'aws'
        - url: https://random-id-2.xxx.aws-region-1.eks.amazonaws.com
          name: cluster2
          skipTLSVerify: true
          authProvider: 'aws'
        - url: https://random-id-3.xxx.aws-region-1.eks.amazonaws.com
          name: cluster3
          skipTLSVerify: true
          authProvider: 'aws'
```
3. Have cluster1 through 3 configured with the aws-auth configmap that maps the IRSA role to a group that is allowed to:
```
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: backstage-cross-account
rules:
- apiGroups:
  - ""
  - apps
  - autoscaling
  - batch
  - networking.k8s.io
  resources:
  - configmaps
  - cronjobs
  - deployments
  - horizontalpodautoscalers
  - ingresses
  - jobs
  - pods
  - replicasets
  - services
  verbs:
  - get
  - watch
```

- Browser Information: all browsers

- Output of `yarn backstage-cli info`: 

```text
OS:   Darwin 21.1.0 - darwin/x64
node: v16.13.2
yarn: 1.22.15
cli:  0.14.1 (installed)

Dependencies:
  @backstage/app-defaults                                  0.1.9
  @backstage/backend-common                                0.11.0
  @backstage/backend-tasks                                 0.1.9
  @backstage/catalog-client                                0.5.3, 0.7.2
  @backstage/catalog-model                                 0.10.1, 0.11.0, 0.9.8
  @backstage/cli-common                                    0.1.8
  @backstage/cli                                           0.14.1
  @backstage/config-loader                                 0.9.6
  @backstage/config                                        0.1.15
  @backstage/core-app-api                                  0.5.4
  @backstage/core-components                               0.8.10
  @backstage/core-plugin-api                               0.4.1, 0.6.1, 0.7.0
  @backstage/errors                                        0.1.5, 0.2.2
  @backstage/integration-react                             0.1.23
  @backstage/integration                                   0.7.5
  @backstage/plugin-api-docs                               0.8.0
  @backstage/plugin-app-backend                            0.3.27
  @backstage/plugin-auth-backend                           0.11.0
  @backstage/plugin-auth-node                              0.1.3
  @backstage/plugin-catalog-backend                        0.22.0
  @backstage/plugin-catalog-common                         0.1.4
  @backstage/plugin-catalog-graph                          0.2.12
  @backstage/plugin-catalog-import                         0.8.3
  @backstage/plugin-catalog-react                          0.6.10, 0.7.0
  @backstage/plugin-catalog                                0.9.0
  @backstage/plugin-circleci                               0.3.0
  @backstage/plugin-github-actions                         0.5.0
  @backstage/plugin-kubernetes-backend                     0.4.10
  @backstage/plugin-kubernetes-common                      0.2.5
  @backstage/plugin-kubernetes                             0.6.0
  @backstage/plugin-org                                    0.5.0
  @backstage/plugin-permission-common                      0.5.1
  @backstage/plugin-permission-node                        0.5.2
  @backstage/plugin-permission-react                       0.3.2
  @backstage/plugin-proxy-backend                          0.2.21
  @backstage/plugin-scaffolder-backend-module-cookiecutter 0.2.2
  @backstage/plugin-scaffolder-backend                     0.17.2
  @backstage/plugin-scaffolder-common                      0.2.2
  @backstage/plugin-scaffolder                             0.13.0
  @backstage/plugin-search-backend-node                    0.4.7
  @backstage/plugin-search-backend                         0.4.5
  @backstage/plugin-search                                 0.7.1
  @backstage/plugin-shortcuts                              0.2.1
  @backstage/plugin-sonarqube                              0.3.0
  @backstage/plugin-tech-radar                             0.5.7
  @backstage/plugin-techdocs-backend                       0.14.0
  @backstage/plugin-techdocs                               0.14.0
  @backstage/plugin-user-settings                          0.3.21
  @backstage/release-manifests                             0.0.2
  @backstage/search-common                                 0.2.4
  @backstage/techdocs-common                               0.11.10
  @backstage/test-utils                                    0.2.6
  @backstage/theme                                         0.2.15
  @backstage/types                                         0.1.3
  @backstage/version-bridge                                0.1.2
✨  Done in 2.10s.
```

**Comment by SelfhostedPro** [comment]
I'm also running into this issue if anyone has any ideas.

**Comment by SelfhostedPro** [comment]
Found a possible solution. Found out that I could resolve this by removing the label that tells backstage a pod is part of a component, I couldn't tell how many pods were running or their status if I did that though. I added `skipMetricsLookup: true` to my cluster config and it's working correctly now, minus seeing performance metrics. 

*as a note, I do have resource limits enabled so I don't think this is related to that*

**Comment by lucasteligioridis** [comment]
I have also run into this issue, figured there was some permission issue that wasn't presenting itself or badly handled... 🤷🏼

**Comment by lucasteligioridis** [comment]
So coming back to this, I tweaked my permissions to look like below and it works correctly now, no more errors or 500s and the metrics are loading great:

```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: backstage-read-only
rules:
- apiGroups:
  - '*'
  resources:
  - pods
  - configmaps
  - services
  - deployments
  - replicasets
  - horizontalpodautoscalers
  - ingresses
  - statefulsets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - batch
  resources:
  - jobs
  - cronjobs
  verbs:
  - get
  - list
  - watch
 ```

I added a wildcard in the `apiGroups` for the main resources, so obviously there is something there that was causing an issue previously, but this at least indicates that it was a permission issue?

Would be good if the backstage documentation provided a complete best practice `ClusteRole` like above that should be applied on the backstage service account and is tested / working. 

I'm running backstage version `1.3`.

**Comment by benjdlambert** [comment]
> Would be good if the backstage documentation provided a complete best practice ClusteRole like above that should be applied on the backstage service account and is tested / working. 

Would you like to raise a PR to the documentation for the k8s plugin to show your `ClusterRole`?

**Comment by lucasteligioridis** [comment]
@benjdlambert more than happy to, I'm not familiar enough with the codebase, where is the documentation for this plugin exactly?

**Comment by benjdlambert** [comment]
@ccodreanu can you try with the ammended `ClusterRole` and see if it works?

**Comment by matteosilv** [comment]
Can anybody walk us through the right aws conf? 
The aws role has been mapped in the aws-auth configmap and set on the serviceAccount with IRSA, but we are getting 401 responses

**Comment by matteosilv** [comment]
ok... solved. It's probably worth mentioning that the cluster name must be the exact name on aws, otherwise the oidc credential won't be translated

**Comment by pcneo83** [comment]
@matteosilv any chance you could post your aws related config in backstage app-config please?

Our backstage deployment is on EKS using IRSA and I had problems with the techdocs S3 integration until I added the below and only `aws` auth configuration

```
aws:
  accountDefaults:
    region: ${AWS_REGION}
    roleName: ${AWS_ROLE_NAME} # IRSA role name only, not the ARN
```

Kubernetes config in app-config.yaml
```
kubernetes:
  serviceLocatorMethod:
    type: 'multiTenant'
  clusterLocatorMethods:
    - type: 'config'
      clusters:
      - url: https://******
        name: $EKS_CLUSTER_NAME # same as EKS cluster name
        authProvider: 'aws'
        caData: ****
```

However, Kubernetes plugin integration gives a 401 and I can't seem to get anything in the backstage debug log level. The EKS API server audit log seems to show the requests coming through without any auth for some reason
