### ISSUE TITLE
Enable multiple integrations of the same provider

### ISSUE THREAD

**Issue by LvffY** [backstage/backstage#10402]
## Feature Suggestion

It would be great to be able to have multiples integrations for the same provider. For exemple to be able to define : 

```yaml
integrations:
  github:
    - host: github.com/myOrg
      token: ${GITHUB_MYORG_TOKEN}
  github:
    - host: github.com/myOtherOrg
      token: ${GITHUB_MYOTHERORG_TOKEN}
```

## Context

My team is working with multiple azure devops organisation and, AFAIK, we can't define multiple times a same integration type (in my case **dev.azure.com**.

It would be great to add this feature to allow organizations with multiple clients on the same providers to be able to define a token by client.

**Comment by jhaals** [comment]
Hi! Multiple integrations for the same host is not supported but we have something similar for Github where a single integration can have multiple Github apps and we need to use the correct GitHub app for the corresponding organization. We have abstracted that with a [CredentialsProvider](https://github.com/backstage/backstage/blob/master/packages/integration/src/github/SingleInstanceGithubCredentialsProvider.ts) which might be something that could be used to draw inspiration from.
There's currently logic that relies on `host` for lookups so adding a `/org` will probably cause issues for existing code.

**Comment by LvffY** [comment]
Hi @jhaals 

Thanks for your reply :)

What I understand is that this could be quite long to implement, right ? 

I don't know if this could help but I will explain a bit more my context : my team is working with multiple clients. Because we work on our client architecture, we don't decide which git provider to use. So right now, we have 2 gitlab instances and 2 Azure devops organizations.

Another use case that I imagine is that multiple teams are working on the same Backstage instance but they don't know each others. So we could imagine that the backstage team would have to deal with one token to access code of the team A and another token to access code of the team B.

I don't know if it changes something but Github is not my personnal priority. 

Last but not least, this problem is linked to https://github.com/backstage/backstage/issues/10431

**Comment by jhaals** [comment]
But in your first example with Gitlab the two instances have different hostnames, Backstage should be able to handle that without any additional features. Or is something not working as expected with just this configuration?

```
integrations:
  gitlab:
    - host: my.gitlab.provider.com
      token: ${GITLAB_A_TOKEN}
    - host: my.othergitlab.provider.com
      token: ${GITLAB_B_TOKEN}
```

For the azure config example there is currently no support for having different tokens for authentication to the same host. It feels like this is something that needs supporting. I don't know if you can reuse the same token between orgs. @awanlin do you know how this works today with Backstage and multiple orgs? 

I understand that Github is not your personal priority. I brought that up as prior art since GitHub support one integration section containing multiple apps for authentication :)

**Comment by LvffY** [comment]
@jhaals Thanks for the clarification :)

To be honest, I wasn't able to try it for now (because one of my gitlab is in a private network and we didn't call the network team), so I don't know if it's working right now. *But you're right, because it's two separate hostnames, it should work*.

But actually, I also have the same request for gitlab : be able to connect to the same gitlab host with multiple tokens (i.e to access multiple groups which don't have common developers and so can't see the code of each others).

To be explicit, I could have the following integrations : 

```yaml
integrations:
  gitlab:
    - host: my.gitlab.provider.com/teamA
      token: ${GITLAB_A_TOKEN}
    - host: my.gitlab.provider.com/teamB
      token: ${GITLAB_B_TOKEN}
    ## As you said previously, this should work out-of-the-box, because hostname is different
    - host: my.othergitlab.provider.com/teamC
      token: ${GITLAB_C_TOKEN}
  azure:
    - host: dev.azure.com/orgA
      token: ${AZDO_A_TOKEN}
    - host: dev.azure.com/orgB
      token: ${AZDO_B_TOKEN}
```

**Comment by benjdlambert** [comment]
Yep, I think we're going to want to take a little step back here and think about adding `CredentialProviders` for other integration types, so that we can do some additional logic when acting with the integrations depending on the URL's. @Rugvip or @freben do you have any other ideas on how we could support this>?

**Comment by freben** [comment]
yeah, we probably want to shield this all behind credential providers, and the tricky part of course being that it's all host based in the config now rather than baseUrl based - so we'll have to come up with some transition plan there

**Comment by LvffY** [comment]
@freben @benjdlambert is there any update on this point ?

**Comment by LvffY** [comment]
@Rugvip do we have any update on this issue ?

**Comment by Rugvip** [comment]
@LvffY nothing except that figuring out a pattern for `GithubCredentialsProvider`-like things in general is in scope for #13082

**Comment by FreshlyBrewedCode** [comment]
Hi! We are currently running a Backstage PoC in our team and not having the ability to import from multiple Azure DevOps organizations is a major deal breaker for us. I am currently looking through the code and evaluating if it would be possible for me to come up with a basic implementation. 

I would consider contributing but it looks like you are already considering a more general approach (similar to `GitHubCredentialsProvider` as @Rugvip mentioned). I don't have the time and overview of the codebase to contribute a generalized approach but I would rather focus specifically on the Azure integration (there is also an open issue related to multiple orgs in Azure #10431). 

Would you consider accepting a PR that focuses on solving the problem for a single integration or are you already set on going with a more generalized approach?

**Comment by benjdlambert** [comment]
I think that we're going to head down the credential provider router either way, so I think go ahead and try to implement. Let's try to make it as similar as possible to the `GithubCredentialsProvider` something small like `getCredentials({ url: string })` or whatever and see where we get to. :pray:

**Comment by awanlin** [comment]
@FreshlyBrewedCode if you do move forward with this please tag me in the PR as I'll gladly test this with Azure DevOps Server 2020, the on-prem version. Most of the time it's fine but never hurts to double check. I'll also help out with review 👍

**Comment by FreshlyBrewedCode** [comment]
I already have a basic implementation to support multiple Azure DevOps Orgs in my fork. Just did not have time for further testing or to draft a PR during the last weeks. I hope I can look back into it in the coming weeks.

**Comment by Mercanuis** [comment]
Hi there.

My organization is also starting to explore Backstage and I was coming across this conversation via searching for "Backstage multiple repositories"

The context is that my team recently integrated with GH and is using the Discovery Tool to have Backstage scrape the repository for `catalog-info` YAML and host our documents. We would like to extend this to other teams in the same company but under separate organizations, repos, etc.

Similar to @LvffY 's prior comment, we have a GH App, and an Oauth App for the purposes of leveraging software templates, and have set up our integration secrets for Kubernetes deployment like so
```
integrations:
  github:
    - host: <MY_HOST>
      apiBaseUrl: https://<MY_HOST>/api/v3
      rawBaseUrl: https://<MY_HOST>/raw
      apps:
      - $include: ../secrets/secret-github-credentials.yaml
      
 ...

auth:
  providers: 
    github:
      $include: ../secrets/secret-github-oauth-credentials.yaml

catalog:
  readonly: true
  locations:
    - type: github-discovery
      target: https://<MY_HOST>/<ORG>/<REPO>/blob/main/catalog-info.yaml
    - type: github-org
      target: https://<MY_HOST>/<ORG>
      rules:
        - allow: [Group, User]
```

We are trying to solve the following use cases
* Can we scrape from a separate organization? `<ORG>`
* Do we need to provide separate credentials per organization?

I'm just trying to understand the nature of what's possible currently with Backstage. For what its worth, this would be a feature the company would be interested in for sure 

Thanks! :)
