### ISSUE TITLE
Azure Devops plugin: Unable to import catalog-info.yaml from app-config.yaml

### ISSUE THREAD

**Issue by LvffY** [backstage/backstage#10432]
## Expected Behavior

My `catalog-info.yaml` file stored in my Azure Devops repository should be imported.

When I'm importing my `catalog-info.yaml` directly through the Web UI backstage is able to import it : 

![Sans titre](https://user-images.githubusercontent.com/37327656/159981265-69da9ad1-3785-4629-b769-a8b9c6fc7afc.png)

## Actual Behavior

I got a 404 error with the following logs

![Sans titre](https://user-images.githubusercontent.com/37327656/159980253-1e563c98-7468-4af1-9c37-e1b8055569c4.png)

## Steps to Reproduce

1. Have the following `app-config.yaml`

```yaml
## Onyly pertinents parts are showed
integrations:
  azure:
    - host: dev.azure.com
      token: ${AZURE_TOKEN}

azureDevOps:
  host: dev.azure.com
  token: ${AZURE_TOKEN}
  organization: myOrg

catalog:
  rules:
    - allow: [Component, System, API, Group, User, Resource, Location]
  locations:
    - type: azure-discovery
      target: https://dev.azure.com/myOrg/myProj/_git/myRepo?path=/catalog-info.yaml
```

2. Deploy the app at start the app showing the error logs.

## Your Environment

- Browser Information: Using Google Chrome 99.0.4844.82

- My backstage app is executing in an Azure Web App based on a docker image stored in an Azure Container Registry.

My docker file is the following : 

```dockerfile
FROM node:16-bullseye-slim

WORKDIR /app

# Copy repo skeleton first, to avoid unnecessary docker cache invalidation.
# The skeleton contains the package.json of each package in the monorepo,
# and along with yarn.lock and the root package.json, that's enough to run yarn install.
COPY yarn.lock package.json packages/backend/dist/skeleton.tar.gz ./
RUN tar xzf skeleton.tar.gz && rm skeleton.tar.gz

# install sqlite3 dependencies
RUN apt-get update && \
    apt-get install -y libsqlite3-dev python3 cmake g++ && \
    rm -rf /var/lib/apt/lists/* && \
    yarn config set python /usr/bin/python3

RUN yarn install --frozen-lockfile --production --network-timeout 300000 && rm -rf "$(yarn cache dir)"

# Then copy the rest of the backend bundle, along with any other files we might want.
COPY packages/backend/dist/bundle.tar.gz app-config*.yaml catalog-info.yaml ./
RUN tar xzf bundle.tar.gz && rm bundle.tar.gz

CMD ["node", "packages/backend", "--config", "app-config.yaml", "--config", "app-config.production.yaml"]
```

**Comment by awanlin** [comment]
Can you check to make sure that Search has been turned on? I saw that recently as an issue for someone. Also, can you post the Scopes used for your PAT, please?

**Comment by LvffY** [comment]
@awanlin I use my own PAT which has full access and I'm the owner of the organization.

I regenerate it for the test, and I have the same issue.

What do you mean by "Search has been turned on" ? Is there any doc on this ? *I'm not aware of such a feature"

**Comment by xente** [comment]
Hi, In the https://backstage.io/docs/integrations/azure/discovery you can read 
Note: the path parameter follows the same rules as the search on Azure DevOps web interface. For more details visit the [official search documentation](https://docs.microsoft.com/en-us/azure/devops/project/search/get-started-search?view=azure-devops)

You need to install https://marketplace.visualstudio.com/items?itemName=ms.vss-code-search&targetId=f9352dac-ba6e-434e-9241-a848a510ce3f&utm_source=vstsproduct&utm_medium=SearchExtStatus into your organisation and it has to work.

Can you check with it?

**Comment by awanlin** [comment]
@xente thanks for this ^

@LvffY could you also try this:

```yaml
locations:
    - type: url
      target: https://dev.azure.com/myOrg/myProj/_git/myRepo?path=%2Fcatalog-info.yaml
```

This would be a static location but would tell if it's just that `azure-discovery` isn't working or something more

**Comment by LvffY** [comment]
@awanlin For now I manually import locations from one catalog file. 

I mean I have something like that 

```yaml
---
apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: demo-data
  description: Component to be used as demonstration tool
  displayName: DEMO
spec:
  type: url
  targets:
    - https://dev.azure.com/group/subGroup/_git/project?version=GBmisc/backstage&path=/catalog-info.yaml
    - https://dev.azure.com/group2/subGroup2/_git/project2?version=GBmisc/backstage&path=/catalog-info.yaml
    - https://dev.azure.com//group3/subGroup3/_git/project3?version=GBmisc/backstage&path=/catalog-info.yaml
```

and it's working. 

@xente I'll give it a try. *But clearly, it it works, I didn't understand that we need some additional plugin to make it work ^^'*
