### ISSUE TITLE
Unable to map users with users connected 

### ISSUE THREAD

**Issue by LvffY** [backstage/backstage#10478]
## Expected Behavior

I could add any user connected through any auth provider to backstage groups. 

## Actual Behavior

My user connected through my gitlab provider could not be added to any backstage group. 

## Steps to Reproduce

1. Create users and groups : 

```yaml
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: a-team
spec:
  type: team
  children: []
  members: [ 'LvffY', 'user1' ] ## LvffY is my user connected through Gitlab authentification
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: b-team
spec:
  type: team
  children: [ ]
  members: ['LvffY', 'user1'] ## LvffY is my user connected through Gitlab authentification
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: user1
  description: This is a test user
  title: User Test
spec:
  profile:
    displayName: User TEST
    email: user.test@backstage.io
  memberOf: []
```

2. Deploy your app
3. Your connected user shouldn't be in any group while the user `user1` should be in both team. 

## Context

I have multiple auth providers set up and I'd like to be able to map my users from my authentications system to map them into local groups that would have been created in backstage. Because of my multiple auth providers could be differents, we'd like to mix both imported groups/users and local groups to ensure to be consistent through our multiple auth providers.

## Your Environment

```text
yarn run v1.22.18
OS:   Linux 5.10.16.3-microsoft-standard-WSL2 - linux/x64
node: v16.14.2
yarn: 1.22.18
cli:  0.16.1-next.0 (installed)

Dependencies:
  @backstage/app-defaults                          1.0.1-next.0
  @backstage/backend-common                        0.13.1, 0.13.2-next.0
  @backstage/backend-tasks                         0.2.2-next.0
  @backstage/catalog-client                        1.0.0, 1.0.1-next.0
  @backstage/catalog-model                         1.0.0, 1.0.1-next.0
  @backstage/cli-common                            0.1.8
  @backstage/cli                                   0.16.1-next.0
  @backstage/config-loader                         1.0.0, 1.0.1-next.0
  @backstage/config                                1.0.0
  @backstage/core-app-api                          1.0.1-next.0
  @backstage/core-components                       0.9.2, 0.9.3-next.0
  @backstage/core-plugin-api                       1.0.0
  @backstage/errors                                1.0.0
  @backstage/integration-react                     1.0.1-next.0
  @backstage/integration                           1.0.0, 1.0.1-next.0
  @backstage/plugin-api-docs                       0.8.4-next.0
  @backstage/plugin-app-backend                    0.3.31-next.0
  @backstage/plugin-auth-backend                   0.13.0-next.0
  @backstage/plugin-auth-node                      0.1.6, 0.2.0-next.0
  @backstage/plugin-azure-devops-backend           0.3.10-next.0
  @backstage/plugin-azure-devops-common            0.2.2
  @backstage/plugin-azure-devops                   0.1.20-next.0
  @backstage/plugin-catalog-backend-module-azure   0.1.2-next.0
  @backstage/plugin-catalog-backend-module-gitlab  0.1.1
  @backstage/plugin-catalog-backend-module-msgraph 0.3.1-next.0
  @backstage/plugin-catalog-backend                1.0.0, 1.0.1-next.0
  @backstage/plugin-catalog-common                 1.0.0, 1.0.1-next.0
  @backstage/plugin-catalog-graph                  0.2.16-next.0
  @backstage/plugin-catalog-import                 0.8.7-next.0
  @backstage/plugin-catalog-react                  1.0.0, 1.0.1-next.0
  @backstage/plugin-catalog                        1.0.1-next.0
  @backstage/plugin-github-actions                 0.5.4-next.0
  @backstage/plugin-org                            0.5.4-next.0
  @backstage/plugin-permission-common              0.5.3
  @backstage/plugin-permission-node                0.5.5, 0.5.6-next.0
  @backstage/plugin-permission-react               0.3.4
  @backstage/plugin-proxy-backend                  0.2.25-next.0
  @backstage/plugin-scaffolder-backend             1.0.1-next.0
  @backstage/plugin-scaffolder-common              1.0.0, 1.0.1-next.0
  @backstage/plugin-scaffolder                     1.0.1-next.0
  @backstage/plugin-search-backend-module-pg       0.3.2-next.0
  @backstage/plugin-search-backend-node            0.5.3-next.0
  @backstage/plugin-search-backend                 0.5.0-next.0
  @backstage/plugin-search-common                  0.3.2, 0.3.3-next.0
  @backstage/plugin-search                         0.7.5-next.0
  @backstage/plugin-tech-radar                     0.5.11-next.0
  @backstage/plugin-techdocs-backend               1.0.1-next.0
  @backstage/plugin-techdocs-node                  1.0.1-next.0
  @backstage/plugin-techdocs                       1.0.1-next.0
  @backstage/plugin-user-settings                  0.4.3-next.0
  @backstage/release-manifests                     0.0.2
  @backstage/search-common                         0.3.2, 0.3.3-next.0
  @backstage/test-utils                            1.0.1-next.0
  @backstage/theme                                 0.2.15
  @backstage/types                                 1.0.0
  @backstage/version-bridge                        1.0.0
```
