### ISSUE TITLE
[Kubernetes Plugin] CRDs are configurable per cluster

### ISSUE THREAD

**Issue by mstergianis** [backstage/backstage#10513]
## Feature Suggestion

Currently adopters are required to specify the set of CRDs they want to observe for all clusters. However in practice not all k8s clusters are homogeneous. This can lead to error messages that are confusing for end users of backstage and wasted network requests. This proposal is to allow the set of CRDs queried by `kubernetes-backend` to be configurable on a per-cluster basis.

## Possible Implementation

In an effort to remain backwards compatible and to reduce the amount of yaml users need to write, I'm proposing that the current `customResources` block continue to function as is. The differences would begin at a per-cluster `customResources` block that would merge with the set of globally defined CRDs. Thus

```yaml
---
kubernetes:
  customResources:
  - group: 'some-crd.example.com'
    apiVersion: 'v1'
    plural: 'all-cluster-crds'
  # ...
  clusterLocatorMethods:
    - type: config
      clusters:
        - name: my-more-advanced-cluster
          # ...
          customResources:
            - group: 'some-other-crd.example.com'
              apiVersion: 'v1alpha1'
              plural: 'some-crd-only-on-this-cluster'
        - name: my-basic-cluster
          # ...
```

In this example `my-more-advanced-cluster` would query for an extra CRD when compared to `my-basic-cluster`

## Context

I work with clusters where some are used for standard deployments, whereas others are used for build pipelines. The set of CRDs is not necessarily shared between the two types.
