### ISSUE TITLE
Have the scaffolder take input values to select certain files or directories that will not be templated/created in the resulting repository

### ISSUE THREAD

**Issue by farhan-triplelift** [backstage/backstage#10514]
I'm wanting a way to conditionally template files. i.e. given some input values, certain files would be created and be templated, or perhaps not be created at all. This is for the fetch:template action

It seems like there was a method for achieving this with [cookiecutter](https://cookiecutter.readthedocs.io/en/latest/advanced/hooks.html#example-conditional-files-directories), but there is no way to do this in nunjucks.

## Feature Suggestion

I am trying to exclude files & directories from being in the resulting template repo after using the scaffolder based on form fields. 

## Possible Implementation

Have some kind of mechanism in the scaffolder to see If the filename of the folder or file is "" or falsy, and if so then don't template it & exclude it from the resulting repo.

**Comment by benjdlambert** [comment]
I think that what we want to do here, is check what https://github.com/backstage/backstage/blob/ccc649a4087c338b2b8d618dc8022026d0dea231/plugins/scaffolder-backend/src/scaffolder/actions/builtin/fetch/template.ts#L199 returns, and if it's a falsy value then `continue;` in the for loop.

**Comment by karlhaworth** [comment]
We ran into something similar where cookiecutter helped us but now that betav2 templates are deprecated its no longer possible.

We're currently using the below. I didn't like using conditionals in file names with cookiecutter but it worked. The below method works, but not sure it's 100% ideal.

These are samples and do not reflect the all steps involved.

```
    - name: Delete files if not orchestrator
      if: ${{ parameters.cluster_type !== 'orchestrator' }}
      action: fs:delete
      input:
        files:
          - settings.gradle
          - index.html
          - _config.yml
```

```
    - name: Rename file if templatemapper
      if: ${{ parameters.cluster_type === 'templatemapper' }}
      action: fs:rename
      input:
        files:
          - from: helm/${{parameters.param1}}-${{parameters.app_name}}/templates/templatemapper_deployment.yaml
            to: helm/${{parameters.param1}}-${{parameters.app_name}}/templates/deployment.yaml
            overwrite: true
```

**Comment by farhan-triplelift** [comment]
> We ran into something similar where cookiecutter helped us but now that betav2 templates are deprecated its no longer possible.
> 
> We're currently using the below. I didn't like using conditionals in file names with cookiecutter but it worked. The below method works, but not sure it's 100% ideal.
> 
> These are samples and do not reflect the all steps involved.
> 
> ```
>     - name: Delete files if not orchestrator
>       if: ${{ parameters.cluster_type !== 'orchestrator' }}
>       action: fs:delete
>       input:
>         files:
>           - settings.gradle
>           - index.html
>           - _config.yml
> ```
> 
> ```
>     - name: Rename file if templatemapper
>       if: ${{ parameters.cluster_type === 'templatemapper' }}
>       action: fs:rename
>       input:
>         files:
>           - from: helm/${{parameters.param1}}-${{parameters.app_name}}/templates/templatemapper_deployment.yaml
>             to: helm/${{parameters.param1}}-${{parameters.app_name}}/templates/deployment.yaml
>             overwrite: true
> ```

So does file deletion work with the most recent version of the scaffolder api? Or does this method not work anymore?

**Comment by farhan-triplelift** [comment]
@karlhaworth Do you know if you're able to delete placeholder value directories through the fs:delete action? When I try doing it I get a `Relative path is not allowed to refer to a directory outside its parent` error

**Comment by karlhaworth** [comment]
> @karlhaworth Do you know if you're able to delete placeholder value directories through the fs:delete action? When I try the scaffolder says it deleted the directory that I pass in through ${{}} placeholder values but the generated repo still has the directory.

In our case we are. We're using the v3 beta version.

**Comment by farhan-triplelift** [comment]
@karlhaworth we're also using scaffolder.backstage.io/v1beta3 version. Can you send me an example of how you're accomplishing this? 

This is how i'm formatting my fs:delete step

```
    - id: delete-files
      name: Delete files
      action: fs:delete
      input:
        files:
          - ${{parameters.name}}/${{parameters.name}}-sdk'
```

The scaffolder tells me that the directory was deleted, but when i see the resulting repo the directory is still there?

**Comment by farhan-triplelift** [comment]
Actually looks like it was a syntax error on my part, i was able to get the directory to delete

**Comment by Rugvip** [comment]
Looks like following up with `fs:delete` or `fs:rename` actions is very similar to the recommended cookiecutter solution and solves the issue. Will also add that you should be able to use a templated file path as well, for example something like a file in the template directory called `{% if values.name == "expected" %}extra.yaml{% endif %}`.

Will close the issue either way, since it appears solved.

**Comment by anarafaelagomes** [comment]
> Actually looks like it was a syntax error on my part, i was able to get the directory to delete

@farhan-triplelift could you help me with an example that worked to deleting the folder. I'm trying but it's not working.

**Comment by farhan-triplelift** [comment]
Sure, here is my example: 

`    - id: deleteFilesSdkPublishing
      if: ${{ 'sdk_publishing' not in parameters.dependencies }}
      name: Delete SDK Publising files
      action: fs:delete
      input:
        files:
          - ${{parameters.name}}/${{parameters.name}}-sdk
          - .github/workflows/publish-sdk.yml
          - ${{parameters.name}}/package.json`

**Comment by brandonphan** [comment]
Leaving this here because I was wondering if this was possible as well. While the above works as well, I found that you can name filenames with template syntax to conditionally create files. For example, naming a file `${{ 'mkdocs.yml' if values.use_techdocs }}` would create mkdocs.yml if the use_techdocs parameter were set to true.
```
- id: fetch-base
      name: Fetch Base
      action: fetch:template
      input:
        url: ./some-template
        values:
          use_techdocs: '${{ parameters.use_techdocs }}'
```
Kind of funky with source control but I think in our use case it ended up being better instead of having a ton of delete and rename steps.
