### ISSUE TITLE
Unable to Sign-In post upgrade to v1.1.1

### ISSUE THREAD

**Issue by NishkarshRaj** [backstage/backstage#10983]
## Expected Behavior

A user is able to sign in with supported auth mechanisms.

For our Portal, we support auth with GitLab (Only Dev Environments) & Ping for All environments.

## Actual Behavior

Post upgrading Backstage to v1.1.1, we get an error and are unable to sign in.

Most probably we missed something on our end during the upgrade process but would love to understand the root cause.

It states that the provider is not configured which is not true as it was working earlier and we haven't changed the app-config recently. Attaching the app-config for reference.

```yaml
auth:
  environment: production
  session:
    secret: ${AUTH_SESSION_SECRET}
  providers:
    gitlab:
      production:
        clientId: ${AUTH_GITLAB_CLIENT_ID} 
        clientSecret: ${AUTH_GITLAB_CLIENT_SECRET} 
    oidc:
      production:
        metadataUrl: ${AUTH_OIDC_METADATA_URL}
        clientId: ${AUTH_OIDC_CLIENT_ID}
        clientSecret: ${AUTH_OIDC_CLIENT_SECRET}
        authorizationUrl: ${AUTH_OIDC_AUTH_URL}
        tokenUrl: ${AUTH_OIDC_TOKEN_URL}
        tokenSignedResponseAlg: ${AUTH_OIDC_TOKEN_SIGNED_RESPONSE_ALG}
        scope: ${AUTH_OIDC_SCOPE} 
        prompt: ${AUTH_OIDC_PROMPT} 
```

<img width="766" alt="Screenshot 2022-04-21 at 10 14 50 AM" src="https://user-images.githubusercontent.com/35298207/164375147-b019be50-06ab-46c9-984a-803e49090491.png">

<img width="1440" alt="Screenshot 2022-04-21 at 10 20 31 AM" src="https://user-images.githubusercontent.com/35298207/164375164-5ea50750-1eb5-4d30-9633-65c75d4f866e.png">

## Steps to Reproduce

1. Upgrade Backstage to v1.1.1

## Context

No longer able to Sign-In to the Portal experience.

## Your Environment

- Browser Information: Google Chrome 97.0.4692.99
