### ISSUE TITLE
Metatemplating

### ISSUE THREAD

**Issue by joel-vasiliev** [backstage/backstage#11040]
## Feature Suggestion

My suggestion is to implement the possibility of creating pieces of a template at a separated repo (example: one repo that contains a terraform.yaml file with one "page" of actual template (example: https://github.com/joel-vasiliev/metatemplating/blob/main/terraform.yaml) and point to this url in template.yaml (example below). I call this metatemplating.

## Context

Currently, if we have three templates that are using Terraform, we will have to copy and paste the Terraform part in all templates, but if Terraform updates the sintax, we will have to change the three templates manually. The idea of metatemplating is to have this Terraform part in another repo (or file) and just call it into the template, so when we need to change any part of it, we will have to change it only in one location.

Example:

```yaml
apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
name: infra-base-template
title: Template base de infraestrutura
description: Criar infraestrutura base
spec:
owner: web@example.com
type: infra



parameters:
// calls the metatemplate (https://github.com/joel-vasiliev/metatemplating/blob/main/terraform.yaml)
- title: Any title // here it should be the second page of template

```
