### ISSUE TITLE
backend-common: discovery implementation that supports split backends

### ISSUE THREAD

**Issue by Rugvip** [backstage/backstage#11064]
## Feature Suggestion

The `PluginEndpointDiscovery` interface in the backend currently has a single implementation, `SingleHostDiscovery`. This implementation results in all communication happening internally with each deployed backend instead. It does support horizontal scaling of the catalog in that you can have multiple instances without issues, but the load may not be as well distributed as if all requests were routed to all instances.

The `SingleHostDiscovery` does not support splitting up the backend plugin deployments in any way. Every instance must have each plugin present for the intra-plugin communication. As a part of making it easier to do these kind of backend split, we propose to add a new `PluginEndpointDiscovery` implementation that falls back to the `PluginEndpointDiscovery` implementation, but that can also be configured to support split backend deployments.

## Possible Implementation

The routing could be driven either through code or static configuration, but most likely it's best if the primary method is through static configuration, since that's a bit easier to share between instances.

The configuration might look for example like this:

```yaml
backend:
  routing:
    hosts:
    - baseUrl: http://backstage-charm.internal
      plugins:
      - catalog
      - search
    - baseUrl: http://backstage-strange.internal
      plugins:
      - techdocs
      - scaffolder
    - baseUrl: http://backstage-higgs.internal
      plugins:
      - auth
    fallback:
      baseUrl: http://backstage-tau.internal
```

Want to stress that this is just an example to get discussions going, it's not necessarily the way I suggest we implement it. In this example the configured `baseUrl` of each hosts entry would be used whenever one wants to communicate with any of the listed plugins, with the fallback configuration being used if no other hosts match.

We may also allow configuration of the external base URL, but generally it's something we'd recommend agains and instead make sure you have a proxy in front that takes care of the routing. On that topic we could potentially power up the proxy plugin to allow it to consume this configuration to handle routing of API paths, but likely a future thing in that case.

Naming of the implementation is very much TBD, but I suggest that we make it the new default implementation and let it handle the current single host use-case too. Couple of ideas:

- `HostDiscovery`
- `EndpointDiscovery`
- `PluginRouting`
- `PluginEndpointDiscoveries.fromConfig`
- `EndpointRouting`

## Context

Split plugin deployments is something we want to make a lot easier than it is today. In our view it is an important feature that improves security and makes it easier to scale things independently, distribute load, and split up ownership and lifecycles of the various backend plugins.

- [PluginEndpointDiscovery ](https://backstage.io/docs/reference/backend-common.pluginendpointdiscovery)
- [SingleHostDiscovery ](https://backstage.io/docs/reference/backend-common.singlehostdiscovery)
