### ISSUE TITLE
NotAllowedError when trying to fetch OpenApi definition from external URL

### ISSUE THREAD

**Issue by autoamator** [backstage/backstage#11149]
## Expected Behavior

I'm trying to import the OpenApi json file to backstage. Here's my definition:
```
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: another-api
  description: API added by url
spec:
  type: openapi
  lifecycle: production
  owner: platform
  definition:
    $text: http://backend.company.com:8080/service/v2/api-docs
---
```
 I expect the above description of API appears in backstage same as it does for petstore example:

```
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: petstore-api
  description: petstore test API
spec:
  type: openapi
  lifecycle: production
  owner: platform
  definition:
    $text: https://petstore.swagger.io/v2/swagger.json
---
```

## Actual Behavior

Instead I get the following error:

```backstage_1  | 2022-04-28T09:57:47.286Z catalog warn Processor PlaceholderProcessor threw an error while preprocessing; caused by Error: Placeholder $text could not read location http://backend.company.com:8080/service/v2/api-docs, NotAllowedError: Reading from 'http://backend.company.com:8080/service/v2/api-docs' is not allowed type=plugin entity=api:default/another-api```

## Context

My suspicion is that the address http://backend.company.com:8080 needs to be whitelisted somewhere, but I don't see where or how exactly. What I tried was editing app-config.yaml:

```backend:
  baseUrl: ${BASE_URL}
(...)
  cache:
    store: memory
  reading:
    allow:
      #- host: petstore.swagger.io
      - host: bitbucket.company.com
      - host: backend.company.com:8080
      - host: backend.company.com
 ```
No success.
 I even commented out the petstore line and the petstore example is still working.

Also I tried with Catalog settings in app-config.yaml:
```
catalog:
  rules:
    - allow: [ Component, System, API, Group, User, Resource, Location ]
  locations:
    - type: url
      target: http://backend.company.com:8080/service/v2/api-docs
    - type: bitbucket-discovery
      target: https://bitbucket.company.com/projects/*/repos/*/catalog-info.yaml
```

Didn't work as well.

Both petstore and my api-docs are in the same version ("swagger":"2.0").

## Your Environment

Windows, backstage run via docker-compose.

- Browser Information: <Edge, Chrome>

- Output of `yarn backstage-cli info`: 

```
it's a dockerized version, not sure how to execute the above

```
