### ISSUE TITLE
EntityOwnershipCard card should show owned systems

### ISSUE THREAD

**Issue by dtuite** [backstage/backstage#11182]
## Feature Suggestion

The `EntityOwnershipCard` should show owned systems.

Given the following YAML in the catalog (plus some other stuff which I won't reproduce here).

```
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  title: Sample System
  name: sample-system
  description: Sample things which are good for demoing.
spec:
  owner: sample-team

---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: sample-team
  title: Sample team
  description: A team!
spec:
  type: team
  profile:
    displayName: Sample team
    email: team-sample@example.com
    picture: https://avatars.dicebear.com/api/identicon/team-alpha@example.com.svg?background=%23fff&margin=25
  children: []
```

When I visit the Group entity page, I see this:

![Screenshot 2022-04-29 at 22 01 24](https://user-images.githubusercontent.com/562403/166068642-7485d41f-4caf-4f28-a967-17ae3cd2c6bc.png)

I expect to see the owned system there too.

## Possible Implementation

Not sure.

## Context

In an org with a big enough fleet of services, systems are an important way to understand the remit of teams. They should be represented.
