### ISSUE TITLE
Send arbitrary headers with requests to backend integrations

### ISSUE THREAD

**Issue by jpeach** [backstage/backstage#11233]
## Feature Suggestion

I have an internal bitbucket server and I need the backend to add extra headers to all the HTTP requests that it makes.

## Possible Implementation

AFAICT there's no good way to do this at the `node-fetch` level and I don't see a way to hook into the headers that `getBitbucketServerRequestOptions` returns. I could register a customized `BitbucketServerUrlReader` with the `UrlReader` factory, but I don't think that capture all the places where the bitbucket integration is used.

I was thinking that it might be worth establishing a pattern of allowing the user to add headers into the integrations configuration (in general).

So it would look a bit like this:

```yaml
        integrations:
          bitbucket:
            - host: bitbucket.example.com
              apiBaseUrl: https://bitbucket.example.com/api/1.0
              username: backstage
              appPassword: backstage
              token: foo
              headers:
                some-header: foo
                some-other-header: bar
```

I'd be happy with suggestions for other approaches, or a way to keep this local to my Backstage app, but I don't really see a way to inject headers.
