### ISSUE TITLE
SSL Connectivity to Postgres

### ISSUE THREAD

**Issue by thunder7s** [backstage/backstage#11297]
I am getting an error when starting up the backend whilst attempting to connect to postgres database in Azure. 
I have tried setting ssl to both "require" and "true" in app-config.yaml file: 

```
  database:
    client: pg
    connection:
      host: ${POSTGRES_HOST}
      port: ${POSTGRES_PORT}
      user: ${POSTGRES_USER}
      password: ${POSTGRES_PASSWORD}
      ssl: true
```

Logs for the pod state:

Backend failed to start up, error: no pg_hba.conf entry for host "nn.nnn.n.nnn", user "jarvis", database "postgres", SSL off.

When connecting directly to postgres db from local dev machine sslmode must be "require" or I receive the same error as the pod returns
