### ISSUE TITLE
Mismatch between Entity schema and TS type in `@backstage/catalog-model` 

### ISSUE THREAD

**Issue by sqdk** [backstage/backstage#11565]
## Expected Behavior
The Entity type defined in `@backstage/catalog-model` does not match the schema that is used when validating entities. It is expecting the deprecated field `target` to be used instead of `targetRef`.

The Entity type is defined here:
https://github.com/backstage/backstage/blob/165cabfeb61a04108b7ee5160e67adfe23e5dd1c/packages/catalog-model/src/entity/Entity.ts#L182-L199

The schema is defined here:
https://github.com/backstage/backstage/blob/165cabfeb61a04108b7ee5160e67adfe23e5dd1c/packages/catalog-model/src/schema/shared/common.schema.json#L31-L48

## Actual Behavior
When importing entites that uses `targetRef` as defined in the type, I am seeing this policy check failure which results in none of the entities being imported: 
```
2022-05-18T06:01:10.141Z catalog warn Policy check failed; caused by Error: Malformed envelope, /relations/0 must have required property 'target' type=plugin entity=component:default/xxxxx
```

## Steps to Reproduce
Create the file `./test.yaml` with the contents:
```
apiVersion: backstage.io/v1beta1
kind: Component
metadata:
  name: xxx
  description: ''
  annotations:
    github.com/project-slug: https://github.com/xx/xx
spec:
  lifecycle: production
  owner: xxx
  type: service
relations:
  - type: ownedBy
    targetRef: group:xx
```

Configure `app-config.yaml` so that the `catalog.locations` block has an entry like this:
```
catalog:
  location:
    - type: file
      target: <path to test yaml file>
```

Start the backend:
`yarn start`

Observe that the following errors are logged to the console:
```
2022-05-18T06:15:50.200Z catalog warn Policy check failed; caused by Error: Malformed envelope, /relations/0 must have required property 'target' type=plugin entity=component:default/xxx
```

Also note that the entity is not imported.
## Context
It is confusing that the types don't match the validation schema. 

## Your Environment
This is not environment specific.
