### ISSUE TITLE
Improve the documentation to explain how to create the container image of the frontend

### ISSUE THREAD

**Issue by cmoulliard** [backstage/backstage#11598]
## Feature Suggestion

The existing backstage Helm chart to deploy the frontend uses an old image (2years old) build by @martina-if  
```
frontend:
  enabled: false
  replicaCount: 1
  image:
    repository: martinaif/backstage-k8s-demo-frontend
    tag: test1
    pullPolicy: IfNotPresent
```

As the following section of the documentation explains how to build a backstage image but do not explain how to build the frontend, I think that it would be good to improve the documentation to explain:
- How to build the frontend image 
- How to build both front and backend
- How maybe to build the backstage image BUT explains how we can override the entrypoints to start either the front or the backend

https://backstage.io/docs/deployment/docker#host-build
