### ISSUE TITLE
Scaffolder - GithubResponseError: Pull request creation failed; caused by HttpError: Not Found

### ISSUE THREAD

**Issue by voodooGQ** [backstage/backstage#11657]
## Expected Behavior

I'm able to scaffold without error

## Actual Behavior

Receiving `GithubResponseError: Pull request creation failed; caused by HttpError: Not Found` consistently with my build. Have tried upgrading. Have tried giving more permissions to the token. Unfortunately, the error message doesn't give a whole lot of info on what's actually going wrong.

https://github.com/backstage/backstage/issues/8263 seems related, but this is not intermitent.

## Steps to Reproduce

Hard to say, I've never been able to get it working in my local or staging instances.

## Context

We currently can't do any kind of scaffolding.

## Your Environment

- Browser Information: Firefox 100.0 (64-bit)

- Output of `yarn backstage-cli info`: 

```text
OS:   Linux 5.4.0-110-generic - linux/x64
node: v14.18.3
yarn: 1.22.18
cli:  0.17.1 (installed)

Dependencies:
  @backstage/app-defaults                               1.0.2
  @backstage/backend-common                             0.13.5
  @backstage/backend-tasks                              0.3.1
  @backstage/catalog-client                             0.8.0, 0.9.0, 1.0.2
  @backstage/catalog-model                              0.12.1, 0.13.0, 1.0.2
  @backstage/cli-common                                 0.1.9
  @backstage/cli                                        0.17.1
  @backstage/config-loader                              1.1.1
  @backstage/config                                     0.1.15, 1.0.1
  @backstage/core-api                                   0.2.23
  @backstage/core-app-api                               1.0.2
  @backstage/core-components                            0.9.4
  @backstage/core-plugin-api                            0.1.13, 0.8.0, 1.0.2
  @backstage/core                                       0.7.14
  @backstage/dev-utils                                  1.0.2
  @backstage/errors                                     0.1.5, 0.2.2, 1.0.0
  @backstage/integration-react                          0.1.25, 1.1.0
  @backstage/integration                                0.8.0, 1.2.0
  @backstage/plugin-api-docs                            0.8.5
  @backstage/plugin-app-backend                         0.3.32
  @backstage/plugin-auth-backend                        0.14.0
  @backstage/plugin-auth-node                           0.2.1
  @backstage/plugin-catalog-backend                     1.1.2
  @backstage/plugin-catalog-common                      1.0.2
  @backstage/plugin-catalog-graph                       0.2.17
  @backstage/plugin-catalog-import                      0.8.8
  @backstage/plugin-catalog-react                       0.8.1, 0.9.0, 1.1.0
  @backstage/plugin-catalog                             1.2.0
  @backstage/plugin-circleci                            0.3.5
  @backstage/plugin-github-actions                      0.5.5
  @backstage/plugin-org                                 0.5.5
  @backstage/plugin-permission-common                   0.5.3, 0.6.1
  @backstage/plugin-permission-node                     0.6.1
  @backstage/plugin-permission-react                    0.3.4, 0.4.1
  @backstage/plugin-proxy-backend                       0.2.26
  @backstage/plugin-scaffolder-backend                  1.2.0
  @backstage/plugin-scaffolder-common                   1.1.0
  @backstage/plugin-scaffolder                          1.2.0
  @backstage/plugin-search-backend-module-elasticsearch 0.1.4
  @backstage/plugin-search-backend-module-pg            0.3.3
  @backstage/plugin-search-backend-node                 0.6.1
  @backstage/plugin-search-backend                      0.5.2
  @backstage/plugin-search-common                       0.3.4
  @backstage/plugin-search-react                        0.2.0
  @backstage/plugin-search                              0.8.1
  @backstage/plugin-shortcuts                           0.2.6
  @backstage/plugin-tech-radar                          0.5.12
  @backstage/plugin-techdocs-backend                    1.1.1
  @backstage/plugin-techdocs-module-addons-contrib      1.0.0
  @backstage/plugin-techdocs-node                       1.1.1
  @backstage/plugin-techdocs-react                      1.0.0
  @backstage/plugin-techdocs                            1.1.1
  @backstage/plugin-user-settings                       0.4.4
  @backstage/release-manifests                          0.0.3
  @backstage/search-common                              0.3.4
  @backstage/test-utils                                 1.1.0
  @backstage/theme                                      0.2.15
  @backstage/types                                      0.1.3, 1.0.0
  @backstage/version-bridge                             0.1.2, 1.0.1
```

**Comment by voodooGQ** [comment]
Ok sorry about that, now that I have the access I need I can verify that we're not using OAuth but are just using the basic token integrations:

```yaml
integrations:
  github:
    - host: github.com
      token: ${GITHUB_TOKEN}
```

I'll try elevating the permissions of the token to see if that alleviates the issues we're having and report back.

**Comment by voodooGQ** [comment]
Alright, I added the following perms and it fixed the issue. I'm assuming the org_hooks are what's important here. Is there documentation that goes over any of this that I may have missed?

![image](https://user-images.githubusercontent.com/1512028/170370695-1cae747e-bd3a-44cc-9e91-8bb8369167be.png)

**Comment by benjdlambert** [comment]
Can we see the `template.yaml` that you're trying to use? Have you tried using any of the example ones. What do you fill in for the `RepoUrlPicker` field where it says `owner` and `name`?

**Comment by voodooGQ** [comment]
@benjdlambert as mentioned the problem was fixed with the permissions change. If you have docs that go over what permissions to set in GitHub I wasnt able to find them. I did follow other examples out there, but none of them go over the perms needed for the token.

**Comment by jhaals** [comment]
Hi
There is mentions of permissions for the token at https://backstage.io/docs/getting-started/configuration#setting-up-a-github-integration and some in this section which the getting started guide links to https://backstage.io/docs/integrations/github/github-apps

@voodooGQ I'm sure we can do better and if you have some suggestions please suggest them in a PR 🙏 

I'm going to close this issue as the problem seems to be fixed, feel free to reopen if there are outstanding issues :)

**Comment by LegendSebastianoL** [comment]
I have the same issue, I posted in [Discord](https://discord.com/channels/687207715902193673/687235481154617364/1209778436156166174)

I think that before when we were using the GitHub token it was working but now with the GitHub APP is broken and I have this error
```
GithubResponseError: Pull request creation failed; caused by HttpError: Not Found
15    at Object.handler (/app/node_modules/@backstage/plugin-scaffolder-backend-module-github/dist/index.cjs.js:2175:15)
```

This is our app-config
```
integrations:
  bitbucketCloud:
    - username: ${BITBUCKET_CLOUD_USERNAME}
      appPassword: ${BITBUCKET_CLOUD_PASSWORD}
  okta:
    apiToken: ${OKTA_API_TOKEN}
  awsS3:
    - accessKeyId: ${AWS_ACCESS_KEY_ID}
      secretAccessKey: ${AWS_SECRET_ACCESS_KEY}
  github:
    - host: github.com
      apps:
        - $include: backstage-app-credentials.yaml

...
catalog:
  import:
    entityFilename: catalog-info.yaml
    pullRequestBranchName: backstage-integration
  providers:
    github:
      mainOrg:
        organization: 'ORG_NAME'
        catalogPath: '**/catalog-info.yaml'
        validateLocationsExist: false
        filters:
          branch: 'main'
          repository: '.*'
```
