### ISSUE TITLE
System Model: Inter-System (and inter-domain) relationships for the System Landscape View.

### ISSUE THREAD

**Issue by kiranpatel11** [backstage/backstage#11671]
The system model in Backstage catalog does have `part-of` relationship for `Component`s with the `System`. but the `System`s themselves do not have any peer/inter relationships as defined by the [C4 Model](https://c4model.com/).

## Feature Suggestion

Define the inter-system (and probably inter-domain) relationship for Backstage System Model to cover the recommended modeling by [System Landscape Diagram](https://c4model.com/#SystemLandscapeDiagram) in C4 Model.

## Possible Implementation
It would nice to allow the custom name for the relationship between the systems (and domains if we decide to pursue that)

## Context

The context is pretty much explained here : https://c4model.com/#SystemLandscapeDiagram

**Comment by kiranpatel11** [comment]
https://github.com/backstage/backstage/issues/4394

**Comment by benjdlambert** [comment]
Is this something you would like to contribute? :pray:

**Comment by kiranpatel11** [comment]
sure @benjdlambert, you can assign to me.

**Comment by kiranpatel11** [comment]
Does it make sense to make use of the existing `dependsOn` and `dependencyOf` relations

Refering to the [C4 System Landscape Diagram](https://c4model.com/#SystemLandscapeDiagram), these relations can be defined as below.
```
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: atm-system
  title: ATM
  description: Allows customers to withdraw cash.
spec:
  owner: atm-team
  domain: customer-services
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: email-system
  title: E-mail System
  description: The internal Microsoft Exchange e-mail system.
spec:
  owner: customer-interactions-team
  domain: customer-interactions
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: internet-banking-system
  title: Internet Banking System
  description: Allows customers to view information about their bank accounts, and make payments.
spec:
  owner: core-banking-team
  domain: personal-banking
  dependsOn: 
    - system:atm-system
    - system:email-system
```

If this sounds OK, I can raise a PR to make changes [here](https://github.com/backstage/backstage/blob/211b7203f0ad407545eebb48ca6ad706fd4df5e5/plugins/catalog-backend/src/modules/core/BuiltinKindsEntityProcessor.ts#L273)

Also, does it make sense to use the `metadata` field defined in `relation` (reserved for future) for further describing the relation as per C4 model ? Reference [here](https://backstage.io/docs/features/software-catalog/descriptor-format#common-to-all-kinds-relations)
