### ISSUE TITLE
Adding environment variables to docker

### ISSUE THREAD

**Issue by amfchef** [backstage/backstage#11718]
I have created a CICD with Gihub action, to deploy it to ECR. But Docker is unable to access the app-config.yaml, which I have saved in the GHA secrets. Is it possible to access the secrets like AUTH_GITHUB_CLIENT_ID, AUTH_GITHUB_CLIENT_SECRET?

## Expected Behavior

Backstage should access my secret variables when I deploy it with Docker

## Actual Behavior

Unable to find the credentials, when I deploy it. It is working when I test it locally.
Im getting:
Error: Failed to initialize github auth provider, Missing required config value at 'auth.providers.github.development.clientId' 

## Steps to Reproduce

1. Create app, follow instruction from https://backstage.io/docs/deployment/docker
2 Adding secrets in GHA
3. deploy with docker

## Context
The cicd chain is working, except for accessing the secrets

app-config.yaml
```
auth:
  # see https://backstage.io/docs/auth/ to learn about auth providers
  environment: development
  providers:
    github:
      development:
        clientId:  ${AUTH_GITHUB_CLIENT_ID}
        clientSecret:  ${AUTH_GITHUB_CLIENT_SECRET}
```
workflow
```
      - name: Build docker images
        env:
          DOCKER_REGISTRY: ${{ env.AWS_ECR_DEFAULT }}
          AUTH_GITHUB_CLIENT_ID: ${{ secrets.AUTH_GITHUB_CLIENT_ID }}
          AUTH_GITHUB_CLIENT_SECRET: ${{ secrets.AUTH_GITHUB_CLIENT_SECRET }}
```

## Your Environment

- Browser Information: 
Google Chrome Version 94.0.4606.61 (Official Build) (x86_64)
- Output of `yarn backstage-cli info`: 

```
 @backstage/app-defaults               1.0.1
  @backstage/backend-common             0.13.2
  @backstage/backend-tasks              0.3.0
  @backstage/catalog-client             1.0.1
  @backstage/catalog-model              1.0.1
  @backstage/cli-common                 0.1.8
  @backstage/cli                        0.17.0
  @backstage/config-loader              1.1.0
  @backstage/config                     1.0.0
  @backstage/core-app-api               1.0.1
  @backstage/core-components            0.9.3
  @backstage/core-plugin-api            1.0.1
  @backstage/errors                     1.0.0
  @backstage/integration-react          1.0.1
  @backstage/integration                1.1.0
  @backstage/plugin-api-docs            0.8.4
  @backstage/plugin-app-backend         0.3.31
  @backstage/plugin-auth-backend        0.13.0
  @backstage/plugin-auth-node           0.2.0
  @backstage/plugin-catalog-backend     1.1.1
  @backstage/plugin-catalog-common      1.0.1
  @backstage/plugin-catalog-graph       0.2.16
  @backstage/plugin-catalog-import      0.8.7
  @backstage/plugin-catalog-react       1.0.1
  @backstage/plugin-catalog             1.1.0
  @backstage/plugin-circleci            0.3.4
  @backstage/plugin-github-actions      0.5.4
  @backstage/plugin-org                 0.5.4
  @backstage/plugin-permission-common   0.6.0
  @backstage/plugin-permission-node     0.6.0
  @backstage/plugin-permission-react    0.4.0
  @backstage/plugin-proxy-backend       0.2.25
  @backstage/plugin-scaffolder-backend  1.1.0
  @backstage/plugin-scaffolder-common   1.0.1
  @backstage/plugin-scaffolder          1.1.0
  @backstage/plugin-search-backend-node 0.6.0
  @backstage/plugin-search-backend      0.5.1
  @backstage/plugin-search-common       0.3.3
  @backstage/plugin-search-react        0.1.0
  @backstage/plugin-search              0.8.0
  @backstage/plugin-tech-radar          0.5.11
  @backstage/plugin-techdocs-backend    1.1.0
  @backstage/plugin-techdocs-node       1.1.0
  @backstage/plugin-techdocs-react      0.1.0
  @backstage/plugin-techdocs            1.1.0
  @backstage/plugin-user-settings       0.4.3
  @backstage/release-manifests          0.0.2
  @backstage/search-common              0.3.3
  @backstage/test-utils                 1.0.1
  @backstage/theme                      0.2.15
  @backstage/types                      1.0.0
  @backstage/version-bridge             1.0.1

```
