### ISSUE TITLE
helm chart: nil pointer evaluating interface {}.port

### ISSUE THREAD

**Issue by masonhuemmer** [backstage/backstage#11852]
https://github.com/backstage/backstage/blob/b5e056f3124a2c0fd23fc94a5d42f1d54d158c0a/contrib/chart/backstage/values.yaml#L79

**Helm version**
```
version.BuildInfo{Version:"v3.9.0", GitCommit:"7ceeda6c585217a19a1131663d8cd1f7d641b2a7", GitTreeState:"clean", GoVersion:"go1.17.5"}
```

**Receiving the following error**
```
<.Values.postgresql.service.port>: nil pointer evaluating interface {}.port
```

**To resolve this issue, I had to populate the tree with an empty value for .Values.postgresql.service.port.**

```
postgresql:
  enabled: true
  service:
    port: {}
  nameOverride: postgresql
  tls:
    enabled: true
    certificatesSecret: backstage-postgresql-certs
    certFilename: tls.crt
    certKeyFilename: tls.key
  volumePermissions:
    enabled: true
  initdbScriptsSecret: backstage-postgresql-initdb
```
