### ISSUE TITLE
[Scaffolder] White Button Text on White Button Background.

### ISSUE THREAD

**Issue by kim5566** [backstage/backstage#11872]
## Expected Behavior

![Screen Shot 2022-06-06 at 3 58 47 pm](https://user-images.githubusercontent.com/28945404/172103843-62ecc19f-4d80-4880-a693-e3557f7ffa19.png)

Same button style as above.

## Actual Behavior

![Screen Shot 2022-06-06 at 3 58 11 pm](https://user-images.githubusercontent.com/28945404/172103788-6f41bd76-f382-4447-ac44-57b5a133cb40.png)

## Steps to Reproduce

1. theme color:     
```   
       primary: {main: bue},
       secondary: {main: white},
```
2. Define an array field in scaffolder template.yaml
```
properties:
  listOfStrings:
    type: array
    title: A list of strings
    items:
      type: string
      default: bazinga
```
4. use this template at /create

## Your Environment

- Browser Information: 

- Output of `yarn backstage-cli info`: 

```text

```
