### ISSUE TITLE
Azure AD organizational data doesn't appear after following the readme guide and no logs in pod to show errors

### ISSUE THREAD

**Issue by bourbonfgiles** [backstage/backstage#11900]
I have followed this README guide to configure backstage to integrate Azure AD organizational data.
https://github.com/backstage/backstage/tree/master/plugins/catalog-backend-module-msgraph

My catalog.ts is as follows

```
import { CatalogBuilder } from '@backstage/plugin-catalog-backend';
import { ScaffolderEntitiesProcessor } from '@backstage/plugin-scaffolder-backend';
import { Router } from 'express';
import { PluginEnvironment } from '../types';
import { Duration } from 'luxon';
import { MicrosoftGraphOrgEntityProvider } from '@backstage/plugin-catalog-backend-module-msgraph';

export default async function createPlugin(
  env: PluginEnvironment,
): Promise<Router> {
  const builder = await CatalogBuilder.create(env);
  builder.addProcessor(new ScaffolderEntitiesProcessor());
  const { processingEngine, router } = await builder.build();
  await processingEngine.start();
  return router;
}

// The target parameter below needs to match one of the providers' target
// value specified in your app-config (see above).
builder.addEntityProvider(
  MicrosoftGraphOrgEntityProvider.fromConfig(env.config, {
    id: 'production',
    target: 'https://graph.microsoft.com/v1.0',
    logger: env.logger,
    schedule: env.scheduler.createScheduledTaskRunner({
      frequency: Duration.fromObject({ minutes: 5 }),
      timeout: Duration.fromObject({ minutes: 3 }),
    }),
  }),
);

builder.addProcessor(
  MicrosoftGraphOrgReaderProcessor.fromConfig(env.config, {
    logger: env.logger,
  }),
);
```

My catalog-info.yaml is as follows

```
---

apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: MicrosoftGraphOrgEntityProvider 
  description: Ingesting Azure AD users
spec:
  type: service
  lifecycle: production
  owner: infra and tooling

```
The app-config is as follows

```

                  catalog:
                    locations:
                      - target: https://github.com/organisation/*/blob/-/.backstage/catalog-info.yaml
                        type: github-discovery
                        rules:
                          - allow: [Component, API, System]
                      - type: microsoft-graph-org
                        target: https://graph.microsoft.com/v1.0
                        rules:
                        - allow: [Group, User]
                    processors:
                      microsoftGraphOrg:
                        providers:
                        - target: https://graph.microsoft.com/v1.0
                          authority: https://login.microsoftonline.com
                          tenantId: "#{AzureTenantId}"
                          clientId: #{AzureAuthClientId}
                          clientSecret: ${AUTH_MICROSOFT_CLIENT_SECRET}
                          userFilter: 'accountEnabled eq true'

```

Where the secrets are filled in by Octopus deploy with a well known group.

So after following the above, I don't see any users in the backstage portal.

Equally I don't have any logs on the pod to say anything went wrong

```
2022-06-07T15:49:57.820Z search info Collating documents for software-catalog succeeded type=plugin
```

Any suggestions of next steps to troubleshoot this? Thanks.

**Comment by mustafazeya** [comment]
@bourbonfgiles was this issue fixed?

**Comment by bourbonfgiles** [comment]
@mustafazeya Yes it was! Thanks for checking in.

**Comment by padupe** [comment]
@bourbonfgiles I'm having trouble viewing users and groups from Azure. GitHub with it normally.

How did you solve?

**Comment by bourbonfgiles** [comment]
I think what `afscrome` pointed out worked for me. Your specific needs will be different but I in the end used

```
  processors:
    microsoftGraphOrg:
      providers:
        - authority: "https://login.microsoftonline.com"
          clientId: "${AUTH_MICROSOFT_CLIENT_ID}"
          clientSecret: "${AUTH_MICROSOFT_CLIENT_SECRET}"
          target: "https://graph.microsoft.com/v1.0"
          tenantId: "${AUTH_MICROSOFT_TENANT_ID}"
          userGroupMemberFilter: "displayName eq '${NAME AZURE AD GROUP}'"
          
```
where ${} is a variable in our pipelines. Hope that helps.
