### ISSUE TITLE
S3 discovery with default region does not work in 1.2.2

### ISSUE THREAD

**Issue by jcarres-mdsol** [backstage/backstage#11913]
## Expected Behavior

We are using S3 catalog provider to get some of our entities.
We deploy backstage to us-east-1 so we leave the region out in the configuration as that's the default.
```
 providers:
    awsS3:
      users: 
        bucketName: ...
        prefix: ...
```

The url then becomes `https://s3.amazonaws.com/<bucket>...`

This works well in 1.1 but in 1.2 that URL without a region is not allowed.

```
warn Unable to read url, Error: Could not retrieve file from S3; caused by Error: Invalid AWS S3 URL
```

We have worked around this by adding a region that is not `us-east-1` as that's the default and in that case backstage does not put the region in the url.

This:
```
 providers:
    awsS3:
      users: 
        bucketName: ...
        prefix: ...
        region: us-east-2
```

AND by truncating the `refresh_state` table. Without truncating that table backstage keeps using the previous URL independently of configuraiton changes.

After both actions, backstage retries now with urls that have the region and there are no complains and everything works.
