### ISSUE TITLE
Scaffolder encodes relative bitbucket URL twice

### ISSUE THREAD

**Issue by dschwank** [backstage/backstage#11988]
## Expected Behavior

The scaffolder should be able to fetch cookiecutter templates from URLs containing special characters.

Example: `https://github.com/backstage/foo/{{ nested }}`

## Actual Behavior

The scaffolder is able to fetch cookiecutter templates from absolute URLs containing special characters, but has problems when using Bitbucket + relative URLs.

The reason for that are the following two issues:

1. The scaffolder treats relative URLs differently than absolute URLs (see [here](https://github.com/backstage/backstage/blob/master/plugins/scaffolder-backend/src/scaffolder/actions/builtin/fetch/helpers.ts#L60))
2. The bitbucket integration encodes the given path (see [here](https://github.com/backstage/backstage/blob/master/packages/integration/src/bitbucketServer/core.ts#L86))

Both can easily be fixed separately, but in combination it's quite annoying.

Let me give you some more context to the issues ...

### 1. The scaffolder treats relative URLs differently than absolute URLs

When fetching cookiecutter templates, the scaffolder uses the [`fetchContents()`](https://github.com/backstage/backstage/blob/master/plugins/scaffolder-backend/src/scaffolder/actions/builtin/fetch/helpers.ts#L29) method, which supports `files`, `relative URLs` and `absolute URLs`. Relative & absolute URLs are treated differently - absolute URLs are not encoded, but relative URLs are do to using the [`resolveUrl()`](https://github.com/backstage/backstage/blob/master/plugins/scaffolder-backend/src/scaffolder/actions/builtin/fetch/helpers.ts#L67) method.

```ts
// relative URL
// will fetch from: https://github.com/backstage/foo/%7B%7B%20nested%20%7D%7D
await fetchContents({
  baseUrl: 'https://github.com/backstage/foo/',
  fetchUrl: '{{ nested }}',
});

// absolute URL
// will fetch from: https://github.com/backstage/foo/{{ nested }}
await fetchContents({
  fetchUrl: `https://github.com/backstage/foo/{{ nested }}`,
});
```

I created this example to highlight the issue: https://github.com/backstage/backstage/pull/11989/files#diff-e0d19aab8d950f00e19d66c0d4381e7474f6039fcf1744a2487a90aeb1d428f4

### 2. The bitbucket integration encodes the given path

In contrast to other integrations, the bitbucket integration will encode the custom path when using the [`getBitbucketServerDownloadUrl()`](https://github.com/backstage/backstage/blob/master/packages/integration/src/bitbucketServer/core.ts#L86). That's correct, but when having issue 1 in mind, that leads to some trouble. When using relative URLs it will lead to a URL which is encoded twice.

When we use the input from the example above, will we end up with the following path attributes:

**Relative URL**
Input: `https://github.com/backstage/foo/%7B%7B%20nested%20%7D%7D`
Path: `%257B%257B%2520nested%2520%257D%257D`

**Absolute URL**
Input: `https://github.com/backstage/foo/{{ nested }}`
Path: `%7B%7B%20nested%20%7D%7D`

## Steps to Reproduce

- Check the provided test case: https://github.com/SDA-SE/backstage/commit/a8fededf5c20215c561a2d1f831b33342cb49ea5
- Use a cookiecutter template with a relative path to a bitbucket server

Example:

```yaml
apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: bitbucket-issue-example
  title: Bitbucket issue example
  description: Short bitbucket issue example
  tags:
    - techdocs
spec:
  type: documentation
  parameters:
    - title: Example
      required:
        - name
      properties:
        name:
          type: string
          title: Name
          description: Name
          ui:field: EntityNamePicker

  steps:
    - name: Render Docs Template
      action: fetch:cookiecutter
      input:
        url: "{{ cookiecutter.name }}"
        values:
          name: ${{ parameters.name }}
```

## Context

We noticed the issue while using one of our default cookiecutter templates which works fine for GitHub, but doesn't work with Bitbucket. We tracked it down to the mentioned issue, but were not sure what the best solution is.

## Possible solutions

**1. Remove `encodeURIComponent()` from bitbucket integration**
That would solve our issue for relative URLs, but will cause issues for absolute URLs. Furthermore the path needs to be encoded, so it's the right place to do it.

**2. Avoid encoding in the `fetchContents()` method**
Relative and absolute URLs should be treated the same way. So the `fetchContents` needs to be touched. Question is, if both should be encoded - or not.

To fix our problem, the best would be to decode the URL. See #11989
