### ISSUE TITLE
[RFC] Relative paths for catalog file locations

### ISSUE THREAD

**Issue by jhaals** [backstage/backstage#11993]
**Status:** Open for comments

## Need

We are looking for the most intuitive way to handle relative paths for catalog file locations referenced in app-config.
The current setup is perhaps not the most intuitive as the base path resolves to the backend itself(`packages/backend`).

With the following directory structure:

```
my-backstage/
    app-config.yaml
    packages/backend/
    examples/entities.yaml
```

Loading files from the `examples` directory will result in the following target path:

```yaml
# app-config.yaml
catalog:
  locations:
   - type: file
     target: ../../examples/entities.yaml
```

This is slightly confusing for the integrator and might cause friction, especially when reusing the same configuration file for both development and productions scenarios where backend path might be different in a container for example.

#### Make the base path the repository root

This would mean that the above example would result in a path like this:

```yaml
  locations:
   - type: file
     target: examples/entities.yaml
```

We believe this is the most intuitive and might work similarly as file locations in other tools.

#### Relative to the configuration file itself

This would result in the same configuration file with the example above.
However as the base path would be based of the configuration file which might be confusing as soon as you start working with multiple configuration files or move the configuration file to another directory.

##### Do nothing

Keep the existing behavior.

## Risks

The base path is less intuitive than today

#### Strategies for migration
These are some options for migrating roughly ranked by the likelihood of being used. Feel free to add suggestions

- Check both new and old style location paths and warn if file exists in both
- Explicit option to toggle the new file behaviour
- Hard breakage with a flag to keep the old behaviour

**Comment by kuangp** [comment]
Perhaps provide a special key eg. `$PROJ_ROOT` => `target: $PROJ_ROOT/examples/entities.yaml` so integrators can be explicit about when they want to use the project root as the base path?

**Comment by Rugvip** [comment]
Tbh, could even just make that an environment variable that is available when running a backend or frontend builds, something like `BACKSTAGE_ROOT`. Then just use it in config with the usual syntax: `${BACKSTAGE_ROOT}/examples/entities.yaml`. Might be a little bit tricky to get it set early on in the backend entrypoint right now though.

**Comment by kissmikijr** [comment]
I love this! 

I think the cleanest would be without the env variable though, like in the RFC.
```yaml
  locations:
   - type: file
     target: examples/entities.yaml
```

But using an env variable would be a huge improvement also! 

Now that I am typing this, could we make it resolve to the `app-config.yaml` file instead of the root? I think it would be more intuitive in that case wouldn't require a hidden knowledge that these paths are resolved to the root. So if I put my app-config into a folder I'd need to step backwards, but I think it makes sense.

.backstage/app-config.yaml
```yaml
  locations:
   - type: file
     target: ../examples/entities.yaml
```
