### ISSUE TITLE
[Scaffolder] OwnerPicker accepts empty values even when required

### ISSUE THREAD

**Issue by omerfarukdogan** [backstage/backstage#12037]
## Expected Behavior

OwnerPicker should reject empty values if the parameter is required.

## Actual Behavior

Empty values are accepted for required parameters.

## Steps to Reproduce

1. Create a template which uses OwnerPicker

```
spec:
  parameters:
    - title: Owner
      required:
        - ownerGroup
      properties:
        ownerGroup:
          title: Owner Group
          type: string
          ui:field: OwnerPicker
          ui:options:
            allowedKinds:
              - Group
```

2. Go to component creation page
3. Enter a value to the field
4. Remove the value entered in step 3
5. Click NEXT or CREATE
6. Progression is not blocked due to missing parameter
