### ISSUE TITLE
Allow customization for default catalog-info.yaml file in PR if not exists

### ISSUE THREAD

**Issue by ctoestreich** [backstage/backstage#12032]
## Feature Suggestion

When a catalog-info.yaml does not exists it would be nice if a template could be provided in the app config to use as the default.  The default appears hard-coded with the exception of the slug injection

```yaml
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: repo
  annotations:
    github.com/project-slug: org/repo
spec:
  type: other
  lifecycle: unknown
```

I do not currently see a way to customize this template if we want to add additional default annotations or properties to the PR'd file.

## Possible Implementation

Allow a default file OR template yaml to be provided in the app-config.yaml for the content of the PR'd catalog-info file.
