### ISSUE TITLE
Kubernetes plugin: Service locator implementation based on the cluster "archetype"

### ISSUE THREAD

**Issue by mclarke47** [backstage/backstage#12095]
## Feature Suggestion

A typical pattern in Kubernetes clusters is to have some clusters where workloads run (deployments/cronjobs etc...) and other clusters where Custom Resources (CRs) are defined (with their supporting controllers). Currently, this separation is not well managed by the Kubernetes plugin as there is only one `serviceLocator` implementation `multiTenant`, which looks for all resources on all configured clusters. The `multiTenant`   `serviceLocator` can result in unnecessary calls when combining resource and CR clusters.

To support this case, we should introduce a new `serviceLocator` implementation `resourceApiLookup`.

`resourceApiLookup` should filter out clusters where requested resources (CRs or workloads) do not exist. 

```yaml
kubernetes:
  serviceLocatorMethod:
    type: 'resourceApiLookup'
  clusterLocatorMethods:
    - type: 'config'
      clusters:
        - url: https://127.0.0.1:53759
          name: workloadCluster
...
```

## Discussion points
a
This feature might require a sever-side Kubernetes service account per cluster to fetch the API resources on startup (and presumably when the clusters refresh). Auth will work out of the box only for server-side authProviders serviceAccount/GKE/AWS/etc. However, client-side auth providers would need a way to configure this too.

Additionally, it might be helpful if users can denyList (via configuration) resources they want to avoid fetching on specific clusters. How do we configure this and make it not verbose?
