### ISSUE TITLE
Empty Owned Section in the Catalog Entity Page

### ISSUE THREAD

**Issue by NishkarshRaj** [backstage/backstage#12107]
## Expected Behavior

The Catalog Entity page defaults `/catalog/?filters%5Bkind%5D=component&filters%5Buser%5D=owned` and showcases the catalogs owned by the signed-in user (assuming the Resolver is set correctly for Identity Resolution and Ownership mapping).

For Example: https://demo.backstage.io/catalog?filters%5Bkind%5D=component&filters%5Buser%5D=owned 

<img width="1440" alt="Screenshot 2022-06-17 at 10 56 59 AM" src="https://user-images.githubusercontent.com/35298207/174231367-67810ee3-9deb-42a6-b5e4-bd874f13159f.png">

## Actual Behavior

When we land on the Catalog page, we are directly routed to the All catalog page `/catalog?filters%5Bkind%5D=component&filters%5Buser%5D=all`

This didn't happen before we upgraded to `v1.2.0`  of Backstage. Our App-Config and Auth.ts file is shared below.

If we try to invoke the route to `owned` instead of `all` via the browser, it redirects to `all` again.

<img width="215" alt="2" src="https://user-images.githubusercontent.com/35298207/174235154-429737e3-0966-4355-9181-d4e3777e539d.png">

The Setting Page suggests that Identity Resolution is happening correctly.

![1](https://user-images.githubusercontent.com/35298207/174235355-bcaa6d64-a0ca-4791-b296-2c6817cc6bda.png)

My User Page:

![3](https://user-images.githubusercontent.com/35298207/174235385-7ee7c052-019e-4efa-8a66-18e8e8ac6c1b.png)

My Group Page:

![4](https://user-images.githubusercontent.com/35298207/174235413-cc92f60f-36ca-4dd9-a6b5-46f54a3ff293.png)

Both of them suggest that my user whose identity is resolved correctly owns a few catalogs.

Also, I tried invoking the API `/api/catalog/entities/by-name/user/default/nishkarsh.raj` via the browser:

![5](https://user-images.githubusercontent.com/35298207/174235425-351fef79-b70e-4d5b-9f62-c0f367a9f1b5.png)

I've tried to search for similar issues in Backstage but couldn't resolve it.

https://github.com/backstage/backstage/issues/10387 
https://github.com/backstage/backstage/pull/9538 

## Steps to Reproduce

- `app-config.yaml`

```yaml
auth:
  environment: production
  session:
    secret: ${AUTH_SESSION_SECRET}
  providers:
    oidc:
      production:
        metadataUrl: ${AUTH_OIDC_METADATA_URL}
        clientId: ${AUTH_OIDC_CLIENT_ID}
        clientSecret: ${AUTH_OIDC_CLIENT_SECRET}
        authorizationUrl: ${AUTH_OIDC_AUTH_URL}
        tokenUrl: ${AUTH_OIDC_TOKEN_URL}
        tokenSignedResponseAlg: ${AUTH_OIDC_TOKEN_SIGNED_RESPONSE_ALG}
        scope: ${AUTH_OIDC_SCOPE}
        prompt: ${AUTH_OIDC_PROMPT}
```

- `packages/backend/src/plugins/auth.ts`

```ts
...
oidc: providers.oidc.create({
        signIn: {
          resolver: async ({ profile: { email } }, ctx) => {
            const [id] = email?.split('@') ?? '';
            const userEntityRef = stringifyEntityRef({
              kind: 'User',
              namespace: DEFAULT_NAMESPACE,
              name: id,
            });

            return ctx.issueToken({
              claims: {
                sub: userEntityRef,
                ent: [userEntityRef],
              },
            });
          },
        },
      }),
```

## Your Environment

- Backstage App v1.3.0
- OIDC Auth (with Ping Identity)
- macOS Monterey (v12.4) - M1 Macbook Pro (Local instance)
- Managed K8s (EKS) for Live environment(s)
