### ISSUE TITLE
helm chart: postgresql-password-lighthouse-secret.yaml" at <b64enc>: invalid value; expected string

### ISSUE THREAD

**Issue by cmoulliard** [backstage/backstage#12110]
## Expected Behavior

The helm chart should be installed without error 

## Actual Behavior

helm reports the following error
```
helm install --create-namespace  -f $HOME/code/backstage/my-values.yml -n backstage backstage .
Error: INSTALLATION FAILED: template: backstage/templates/postgresql-password-lighthouse-secret.yaml:15:76: 
executing "backstage/templates/postgresql-password-lighthouse-secret.yaml" 
at <b64enc>: invalid value; expected string
```

## Steps to Reproduce

```
git clone https://github.com/backstage/backstage.git
cd contrib/chart/backstage
helm dependency update

DOMAIN_NAME="192.168.1.90.nip.io"
cat <<EOF > $HOME/code/backstage/my-values.yml
backend:
  image:
    repository: backstage
    tag: dev
postgresql:
  enabled: false 
appConfig:
  app:
    baseUrl: https://backstage.$DOMAIN_NAME
    title: Backstage
  backend:
    baseUrl: https://backstage.$DOMAIN_NAME
    cors:
      origin: https://backstage.$DOMAIN_NAME
  lighthouse:
    enabled: false
    baseUrl: https://backstage.$DOMAIN_NAME/lighthouse-api
  techdocs:
    storageUrl: https://backstage.$DOMAIN_NAME/api/techdocs/static/docs
    requestUrl: https://backstage.$DOMAIN_NAME/api/techdocs
EOF

helm install --create-namespace  -f $HOME/code/backstage/my-values.yml -n backstage backstage .
```
