### ISSUE TITLE
Hard coded projectUrl in Fossa plugin

### ISSUE THREAD

**Issue by lnavarette** [backstage/backstage#12262]
## Expected Behavior

configurable projectUrl, akin to `sonarqube.baseUrl`

## Actual Behavior

`projectUrl` is hard coded

https://github.com/backstage/backstage/blob/f9e2ec25513ec8b746338b30ef3518b04e08d96c/plugins/fossa/src/api/FossaClient.ts#L107

## Steps to Reproduce

1. add fossa configuration for target other than `https://app.fossa.io/api`, eg
      ```yaml
      proxy:
        '/fossa':
          target: https://mycompany.fossa.com/api
          allowedMethods: ['GET']
          headers:
            Authorization: token ${FOSSA_API_TOKEN}
      ```
2. add a component with fossa annotation
3. click the "view more" button on the component

## Context

links from the backstage component page are broken

## Your Environment

- Browser Information: 

- Output of `yarn backstage-cli info`: 

```text

```
