### ISSUE TITLE
[Scaffoder] Validation of customExtensionField not working when using customExtensionField in dependencies - oneOf

### ISSUE THREAD

**Issue by tritri251214** [backstage/backstage#12378]
I use **RepoUrlPicker** of default customExtensionField supported.

https://user-images.githubusercontent.com/32475934/176807042-ff8a3032-db45-494a-a0eb-3c7a7eb96c0b.mov

```yaml
- title: Choose a location
      required:
        - generation
      properties:
        generation:
          title: Generate Type
          type: string
          enum:
            - Export to zip
            - Publish to Azure Repository
          defaut: Publish to Azure Repository
      dependencies:
        generation:
          oneOf:
            - properties:
                generation:
                  const: Export to zip
            - required:
                - repoUrl
              properties:
                generation:
                  const: Publish to Azure Repository
                repoUrl:
                  title: Repository Location
                  type: string
                  ui:field: RepoUrlPicker
                  ui:options:
                    allowedHosts:
                      - github.com
```

## Expected Behavior

Validation of customExtensionField **RepoUrlPicker** working

## Actual Behavior

Validation of customExtensionField **RepoUrlPicker** not working

## Steps to Reproduce

1. Choose option "Public to Azure Respository"
2. Click **Next Step** => Not validation **RepoUrlPicker**, Still go to next step

## Context

As a user, I want export this project to zip file or pubish to Azure repository.
So, When user select publish to azure repository will display form RepoUrlPicker, then input information.

## Your Environment

- Browser Information: all browser

- Output of `yarn backstage-cli info`: 

```text
OS:   Darwin 21.5.0 - darwin/x64
node: v14.18.2
yarn: 1.22.17
cli:  0.17.2 (installed)

Dependencies:
  @backstage/app-defaults                          1.0.3
  @backstage/backend-common                        0.14.0
  @backstage/backend-tasks                         0.3.2
  @backstage/catalog-client                        1.0.3
  @backstage/catalog-model                         1.0.3
  @backstage/cli-common                            0.1.9
  @backstage/cli                                   0.17.2
  @backstage/config-loader                         1.1.2
  @backstage/config                                1.0.1
  @backstage/core-app-api                          1.0.3
  @backstage/core-components                       0.9.5
  @backstage/core-plugin-api                       1.0.3
  @backstage/errors                                1.0.0
  @backstage/integration-react                     1.1.1
  @backstage/integration                           1.2.1
  @backstage/plugin-api-docs                       0.8.6
  @backstage/plugin-app-backend                    0.3.33
  @backstage/plugin-auth-backend                   0.14.1
  @backstage/plugin-auth-node                      0.2.2
  @backstage/plugin-catalog-backend                1.2.0
  @backstage/plugin-catalog-common                 1.0.3
  @backstage/plugin-catalog-graph                  0.2.18
  @backstage/plugin-catalog-import                 0.8.9
  @backstage/plugin-catalog-react                  1.1.1
  @backstage/plugin-catalog                        1.3.0
  @backstage/plugin-github-actions                 0.5.6
  @backstage/plugin-org                            0.5.6
  @backstage/plugin-permission-common              0.6.2
  @backstage/plugin-permission-node                0.6.2
  @backstage/plugin-permission-react               0.4.2
  @backstage/plugin-proxy-backend                  0.2.27
  @backstage/plugin-scaffolder-backend             1.3.0
  @backstage/plugin-scaffolder-common              1.1.1
  @backstage/plugin-scaffolder                     1.3.0
  @backstage/plugin-search-backend-module-pg       0.3.4
  @backstage/plugin-search-backend-node            0.6.2
  @backstage/plugin-search-backend                 0.5.3
  @backstage/plugin-search-common                  0.3.5
  @backstage/plugin-search-react                   0.2.1
  @backstage/plugin-search                         0.9.0
  @backstage/plugin-tech-radar                     0.5.13
  @backstage/plugin-techdocs-backend               1.1.2
  @backstage/plugin-techdocs-module-addons-contrib 1.0.1
  @backstage/plugin-techdocs-node                  1.1.2
  @backstage/plugin-techdocs-react                 1.0.1
  @backstage/plugin-techdocs                       1.2.0
  @backstage/plugin-user-settings                  0.4.5
  @backstage/release-manifests                     0.0.4
  @backstage/test-utils                            1.1.1
  @backstage/theme                                 0.2.15
  @backstage/types                                 1.0.0
  @backstage/version-bridge                        1.0.1
```
