### ISSUE TITLE
Multiple Scaffolder templates

### ISSUE THREAD

**Issue by ale-conekta** [backstage/backstage#12464]
I am not able to create multiple repositories using one temple, and then from it invoking another template to create the secondary repository. 
My intention is to create multiple repositories.

## Expected Behavior

Create multiple repositories based on 2 templates.

## Actual Behavior

Sometimes I get:
`instance is not exactly one from [subschema 0],[subschema 1]`

 Other times ,if only leave one **catalog:register** the both repository are created, but one of them empty and I get the following error:
 
 `
AlreadyExistsError: Failed to create remote at origin because it already exists. (Hint: use 'force: true' parameter to overwrite existing remote.)`

## Steps to Reproduce

Here is the template:

`
-
apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: python-fastapi-template
  title: Python FastAPI Service
  description: Create a simple microservice using Python FastAPI
  tags:
    - recommended
    - python
    - fastapi
spec:
  owner: xx@xx.com
  type: service
  parameters:
    - title: Provide some simple information
      required:
        - component_id
        - owner
        - services_app_port
      properties:
        component_id:
        .....
  steps:
    - id: app-template
      name: Fetch Skeleton + Template
      action: fetch:template
      input:
        url: ./skeleton
        copyWithoutRender:
          - .github/*
        values:
          component_id: ${{ parameters.component_id }}
          description: ${{ parameters.description }}
          services_app_port: ${{ parameters.services_app_port }}
          owner: ${{ parameters.owner }}
          destination: ${{ parameters.repoUrl | parseRepoUrl }}
    - id: publish-app
      name: Publish-App
      action: publish:github
      input:
        allowedHosts: ["github.com"]
        description: This is ${{ parameters.component_id }}
        repoUrl: ${{ parameters.repoUrl }}
    - id: register-app
      name: Register Application
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps.publish-app.output.repoContentsUrl }}
        catalogInfoPath: "/catalog-info.yaml"
    - id: app-service-config-template
      name: Fetch App Servcie Config. Skeleton + Template
      action: fetch:template
      input:
        url: https://github.com/my-org/helm-values-template
        targetPath: .
        copyWithoutRender:
          - .github/*

`

## Your Environment

- Browser Information: 

- Output of `yarn backstage-cli info`: 

```text

```

**Comment by benjdlambert** [comment]
So, if I understand correctly, and you want to create two repositories from one template you can do something like the following.

You'll need to collect two `repoUrl`'s for the two repositories that you want to create, and then you'll create two directories in your workspace with the templated skeletons, and then run `publish:github` with the two different source paths.


```yaml
...
  parameters:
    ...
    - name: Repositories
      description: Some repo
      properties:
        appRepoUrl:
          type: string
          title: First Repository
          ui:field: RepoUrlPicker
        serviceRepoUrl:
          type: string
          title: First Repository
          ui:field: RepoUrlPicker
  steps:
    # First get the app template folder, and template into ./app
    - id: app_template
      name: Fetch Skeleton + Template
      action: fetch:template
      input:
        url: ./skeleton
        targetPath: ./app
        copyWithoutRender:
          - .github/*
        values:
          component_id: ${{ parameters.component_id }}
          description: ${{ parameters.description }}
          services_app_port: ${{ parameters.services_app_port }}
          owner: ${{ parameters.owner }}
          destination: ${{ parameters.appRepoUrl | parseRepoUrl }}

    # First then service into ./service
    - id: app_service_config_template
      name: Fetch App Service Config. Skeleton + Template
      action: fetch:template
      input:
        url: https://github.com/my-org/helm-values-template
        targetPath: ./service
        copyWithoutRender:
          - .github/*
        values:
          component_id: ${{ parameters.component_id }}
          description: ${{ parameters.description }}
          services_app_port: ${{ parameters.services_app_port }}
          owner: ${{ parameters.owner }}
          destination: ${{ parameters.serviceRepoUrl | parseRepoUrl }}

    # Publish the app
    - id: publish_app
      name: Publish App
      action: publish:github
      input:
        sourcePath: ./app
        allowedHosts: ['github.com']
        description: This is ${{ parameters.component_id }}
        repoUrl: ${{ parameters.appRepoUrl }}

    # Publish the service
    - id: publish_service
      name: Publish Service
      action: publish:github
      input:
        sourcePath: ./service
        allowedHosts: ['github.com']
        description: This is ${{ parameters.component_id }}
        repoUrl: ${{ parameters.serviceRepoUrl }}

    # Register the app
    - id: register_app
      name: Register Application
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps.publish_app.output.repoContentsUrl }}
        catalogInfoPath: '/catalog-info.yaml'

    # Register the service
    - id: register_service
      name: Register Application
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps.publish_service.output.repoContentsUrl }}
        catalogInfoPath: '/catalog-info.yaml'
```

Something like this should work I think?

**Comment by benjdlambert** [comment]
Ah, so yeah unfortunately the `repoUrl` is a string for now, but we've been thinking about making it an object to make this sort of use case easier.  What you could do however is something like this:

You could have two inputs instead of one for `repoUrlPicker` which are both `strings`. One called `owner` and one called `repo` and then use something like:

```yaml
  input:
    sourcePath: ./service
    allowedHosts: ['github.com']
    description: This is ${{ parameters.component_id }}
    repoUrl: ${{ parameters.appRepoUrl }}
    repoUrl: github.com?owner=${{parameters.owner}}&repo=${{parameters.repo}}
```

and then for the other one:

```yaml

  input:
    ...
    repoUrl: github.com?owner=${{parameters.owner}}&repo=${{parameters.repo}}-service-config
```

>Second, Is there a link, where can I learn how to work with thing like string concatenation, loops, if, maps, etc inside Backstage Template?

https://mozilla.github.io/nunjucks/ is probably a good start as that's what we use as the template language. You can't remplate into the parameters section though, only in the actions, so you wont be able to set the value of one form based on another unless you can use jsonschema in the playground but I think it could be hard.

**Comment by ale-conekta** [comment]
@benjdlambert Thank you for your feedback, I am using **fetch:template** to create a repository from a template repository.
In general works find, the main problem happens when I want to clone a repository with git submodules, the **fetch:template** does not clone the dependency, perhaps because Backstage clones it without recursive git option.

**Comment by ale-conekta** [comment]
@benjdlambert 
Thank you for your feedback.
We can create another and close it.

**Comment by josecosta-shell** [comment]
Hi everyone! I was trying to achieve something similar here with 2 `RepoUrlPicker` and 2 separate repos being instantiated on the same template but it seems the scaffolder ended up trying to create the same one twice. I have given the `RepoUrlPicker`s different names (repoUrl and repoUrl2) and referenced them correctly in the `publish` actions. Here is a screenshot of my `template.yaml` file. Forgive me, it's a bit messy as I'm experimenting with many different things.

![image](https://github.com/backstage/backstage/assets/129780729/afb8ee76-3452-4cc4-aa34-0c05085ad837)

Also, the result on the scaffolder UI:

<img width="1260" alt="image" src="https://github.com/backstage/backstage/assets/129780729/f696d45b-2e38-408f-8278-21e33e3a6d3d">

The first template actually was properly instantiated, it's just the second one that failed. The UI doesn't reflect that either. The fact that both fetch actions ran at the same time, rather than sequentially, is probably a clue as to what is happening.

**Comment by deamicis** [comment]
Facing the same issue. My use case is to have input parameter of `type: array` and then have a `each: ${{ parameters.myvar }}` within the `action: publish:github` to create multiple repos based on values provided as input.

**Comment by AlNedorezov** [comment]
Hello! 

I am facing a similar issue.

When I use 2 steps with `publish:gitlab` action in the same template, the second action results in error to create a repository, while I expect that 2 repositories with specified files will be created.


I have the following steps in my template:

```
  steps:
    - id: fetch-base-for-backstage
      name: Fetch Base For Backstage
      action: fetch:template
      input:
        url: ./backstage-content
        values:
          name: ${{ parameters.name }}

    - id: publish-backstage
      name: Publish Backstage Manifest
      action: publish:gitlab
      input:
        allowedHosts: ['gitlab.tools.company.ru']
        description: This is ${{ parameters.name }}
        repoUrl: 'gitlab.tools.company.ru?owner=internal-dev-platform/test-zone&repo=${{ parameters.name }}'

    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps['publish-backstage'].output.repoContentsUrl }}
        catalogInfoPath: '/catalog-info.yaml'

    - id: clear-workspace
      name: Clear Workspace
      action: fs:delete
      input:
        files: 
          - 'catalog-info.yaml'

    - id: fetch-base-for-idp-config
      name: Fetch Base For IDP Config
      action: fetch:template
      input:
        url: ./idp-config-content
        values:
          name: ${{ parameters.name }}

    - id: publish-idp-config
      name: Publish IDP Config
      action: publish:gitlab
      input:
        allowedHosts: ['gitlab.tools.company.ru']
        description: This is ${{ parameters.name }}
        repoUrl: 'gitlab.tools.company.ru?owner=internal-dev-platform/test-zone&repo=${{ parameters.name }}-idp-config'
```

with which I want to create 2 repositories, first with data from `./backstage-content` directory, which contains `catalog-info.yaml`, аnd second one with data from `./idp-config-content` directory.

first repository is created during `publish-backstage` step without any problems.

During `publish-idp-config` step second repository is created, but without any data, and template step fails with the following logs: 

![image](https://github.com/backstage/backstage/assets/2508992/29e8f56d-b4d5-436d-8e74-96e0f194c41d)

I.e. repository is created, and then it is attempted to be created once again and this operation fails.



**Reproduction steps:**

1. In a backstage instace with gitlab integration and templates enabled create a template with the following template directory structure 

![image](https://github.com/backstage/backstage/assets/2508992/ea538fb0-c943-4ac6-93e0-9ff817ff84ee)

and steps specified above.

2. register the template

3. run newly registered template


**Environment:**

`yarn backstage-cli info` results in

```
OS:   Linux 6.5.0-26-generic - linux/x64
node: v18.19.1
yarn: 4.1.1
cli:  0.26.0 (installed)
backstage:  1.24.0

Dependencies:
  @backstage/app-defaults                                          1.5.1
  @backstage/backend-app-api                                       0.5.14, 0.6.0
  @backstage/backend-common                                        0.19.10, 0.21.4
  @backstage/backend-dev-utils                                     0.1.4
  @backstage/backend-openapi-utils                                 0.1.7
  @backstage/backend-plugin-api                                    0.6.14
  @backstage/backend-tasks                                         0.5.19
  @backstage/catalog-client                                        1.6.1
  @backstage/catalog-model                                         1.4.5
  @backstage/cli-common                                            0.1.13
  @backstage/cli-node                                              0.2.4
  @backstage/cli                                                   0.26.0
  @backstage/config-loader                                         1.7.0
  @backstage/config                                                1.2.0
  @backstage/core-app-api                                          1.12.1
  @backstage/core-compat-api                                       0.2.1
  @backstage/core-components                                       0.12.5, 0.13.10, 0.14.1
  @backstage/core-plugin-api                                       1.9.1
  @backstage/errors                                                1.2.4
  @backstage/eslint-plugin                                         0.1.6
  @backstage/frontend-plugin-api                                   0.6.1
  @backstage/integration-aws-node                                  0.1.10
  @backstage/integration-react                                     1.1.25
  @backstage/integration                                           1.9.1
  @backstage/plugin-api-docs                                       0.11.1
  @backstage/plugin-app-backend                                    0.3.62
  @backstage/plugin-app-node                                       0.1.14
  @backstage/plugin-auth-backend-module-atlassian-provider         0.1.6
  @backstage/plugin-auth-backend-module-aws-alb-provider           0.1.5
  @backstage/plugin-auth-backend-module-gcp-iap-provider           0.2.9
  @backstage/plugin-auth-backend-module-github-provider            0.1.11
  @backstage/plugin-auth-backend-module-gitlab-provider            0.1.11
  @backstage/plugin-auth-backend-module-google-provider            0.1.11
  @backstage/plugin-auth-backend-module-microsoft-provider         0.1.9
  @backstage/plugin-auth-backend-module-oauth2-provider            0.1.11
  @backstage/plugin-auth-backend-module-oauth2-proxy-provider      0.1.7
  @backstage/plugin-auth-backend-module-oidc-provider              0.1.4
  @backstage/plugin-auth-backend-module-okta-provider              0.0.7
  @backstage/plugin-auth-backend                                   0.22.0
  @backstage/plugin-auth-node                                      0.4.9
  @backstage/plugin-auth-react                                     0.0.1
  @backstage/plugin-catalog-backend-module-gitlab                  0.3.11
  @backstage/plugin-catalog-backend-module-ldap                    0.5.29
  @backstage/plugin-catalog-backend-module-openapi                 0.1.31
  @backstage/plugin-catalog-backend-module-scaffolder-entity-model 0.1.11
  @backstage/plugin-catalog-backend                                1.18.0
  @backstage/plugin-catalog-common                                 1.0.22
  @backstage/plugin-catalog-graph                                  0.4.1
  @backstage/plugin-catalog-import                                 0.10.7
  @backstage/plugin-catalog-node                                   1.8.0
  @backstage/plugin-catalog-react                                  1.11.0
  @backstage/plugin-catalog                                        1.18.0
  @backstage/plugin-cicd-statistics-module-gitlab                  0.1.27
  @backstage/plugin-cicd-statistics                                0.1.33
  @backstage/plugin-code-coverage-backend                          0.2.28
  @backstage/plugin-code-coverage                                  0.2.24
  @backstage/plugin-entity-validation                              0.1.16
  @backstage/plugin-events-node                                    0.3.0
  @backstage/plugin-home-react                                     0.1.9
  @backstage/plugin-home                                           0.7.0
  @backstage/plugin-org                                            0.6.21
  @backstage/plugin-permission-backend                             0.5.37
  @backstage/plugin-permission-common                              0.7.13
  @backstage/plugin-permission-node                                0.7.25
  @backstage/plugin-permission-react                               0.4.21
  @backstage/plugin-proxy-backend                                  0.4.12
  @backstage/plugin-scaffolder-backend-module-azure                0.1.6
  @backstage/plugin-scaffolder-backend-module-bitbucket-cloud      0.1.4
  @backstage/plugin-scaffolder-backend-module-bitbucket-server     0.1.4
  @backstage/plugin-scaffolder-backend-module-bitbucket            0.2.4
  @backstage/plugin-scaffolder-backend-module-gerrit               0.1.6
  @backstage/plugin-scaffolder-backend-module-gitea                0.1.4
  @backstage/plugin-scaffolder-backend-module-github               0.2.4
  @backstage/plugin-scaffolder-backend-module-gitlab               0.3.0
  @backstage/plugin-scaffolder-backend                             1.22.0
  @backstage/plugin-scaffolder-common                              1.5.1
  @backstage/plugin-scaffolder-node                                0.4.0
  @backstage/plugin-scaffolder-react                               1.8.1
  @backstage/plugin-scaffolder                                     1.19.0
  @backstage/plugin-search-backend-module-catalog                  0.1.18
  @backstage/plugin-search-backend-module-pg                       0.5.23
  @backstage/plugin-search-backend-module-techdocs                 0.1.18
  @backstage/plugin-search-backend-node                            1.2.18
  @backstage/plugin-search-backend                                 1.5.4
  @backstage/plugin-search-common                                  1.2.11
  @backstage/plugin-search-react                                   1.7.7
  @backstage/plugin-search                                         1.4.7
  @backstage/plugin-sentry                                         0.5.16
  @backstage/plugin-sonarqube-backend                              0.2.16
  @backstage/plugin-sonarqube-react                                0.1.14
  @backstage/plugin-sonarqube                                      0.7.13
  @backstage/plugin-tech-radar                                     0.7.0
  @backstage/plugin-techdocs-backend                               1.10.0
  @backstage/plugin-techdocs-module-addons-contrib                 1.1.6
  @backstage/plugin-techdocs-node                                  1.12.0
  @backstage/plugin-techdocs-react                                 1.2.0
  @backstage/plugin-techdocs                                       1.10.1
  @backstage/plugin-user-settings                                  0.8.2
  @backstage/release-manifests                                     0.0.11
  @backstage/test-utils                                            1.5.1
  @backstage/theme                                                 0.2.19, 0.5.2
  @backstage/types                                                 1.1.1
  @backstage/version-bridge                                        1.0.7
  ```

**Comment by AlNedorezov** [comment]
Calling `fs:delete` action with `.git` in files parameter before the second publish:gitlab step fixes the issue.

E.g. to fix the issue described in my post above we just need to change 

```
    - id: clear-workspace
      name: Clear Workspace
      action: fs:delete
      input:
        files: 
          - 'catalog-info.yaml'
```

to 

```
    - id: clear-workspace
      name: Clear Workspace
      action: fs:delete
      input:
        files: 
          - 'catalog-info.yaml'
          - '.git'
```

i.e. '.git' to the files list, add and the second repository will be created without a problem.
