### ISSUE TITLE
Templating - Default value of field dependent of drop down not updating as expected

### ISSUE THREAD

**Issue by IanTurtle** [backstage/backstage#12562]
## Expected Behavior

In a template with two fields, where one is a dropdown of different options and a second is dependent on the other. The second field changes values depending on the option second. If you then select a different option from the dropdown menu, the value of the second field would change to the different value.

## Actual Behavior

When selecting an initial option from the dropdown, the value of the dependent field changes as expected. When selecting a different option from the dropdown, the value of the dependent field does not change. 

## Steps to Reproduce

Create a template, with the following properties: 

```
parameters:
  - title: Optional Components
    required:
      - component
    properties:
      component:
        title: Component
        type: object
        properties:
          component:
            title: Component
            type: string
            enum:
              - value1
              - value2
        required:
          - component
        dependencies:
          component:
            oneOf:
              - properties:
                  component:
                    enum:
                      - value1
                  template:
                    type: string
                    default: abc
              - properties:
                  component:
                    enum:
                      - value2
                  template:
                    type: string
                    default: def
```

Now select value1 from the component dropdown and the value of the template field changes to abc.

![value1](https://user-images.githubusercontent.com/13857557/178232923-5f37bff4-00f9-4fa6-845b-cad6b28efac6.JPG)

Then select value2 from the component dropdown, the value of the template field does not change to def.

![value2](https://user-images.githubusercontent.com/13857557/178233035-0434931f-fe61-437e-a429-f54baf8160cd.JPG)
