### ISSUE TITLE
Additional UI elements to Software Templates

### ISSUE THREAD

**Issue by szajcz** [backstage/backstage#12694]
## Feature Suggestion

Initially Backstage gives quite limited freedom when it comes to changes to the UI elements of its Software Templates. When a Software Template is successfully executed, the related links (listed in the output of the Software Template) are displayed. An additional primary button after the execution of the Template (besides the 'Start over' button) could emphasize the action that the user can perform to carry on with the desired flow.

Current interface:
![Screenshot 2022-07-18 at 13 45 35](https://user-images.githubusercontent.com/34402062/179504471-e86abd1c-b41d-4378-89c3-34e82a1936b3.png)

Suggested interface:
![Screenshot 2022-07-18 at 13 43 46](https://user-images.githubusercontent.com/34402062/179504179-9565a233-8127-4b9c-8e0c-3ac7643b9e2e.png)

## Possible Implementation

The output of Software Templates could contain and additional element besides link, for example a linkedButton element, with a title and a url to navigate to after the button press:
```yaml
  output:
    links:
      - url: 'https://link.to.feedback.form/'
        title: 'Give us feedback on this template flow'
    linkedButton:
      url: ${{steps.publish.output.remoteUrl}}
      title: 'Go to pull request'
```

Then, in the <code>TaskPage.tsx</code> file the presence of the linkedButton element could be checked and utilized:
```js
{output && output.linkedButton && (
  <Button
  className={classes.button}
  href={output.linkedButton.url}
  target="_blank"
  disabled={!completed}
  variant="contained"
  color="primary"
  >
    {output.linkedButton.title}
  </Button>
)}
<Button
  className={classes.button}
  onClick={handleStartOver}
  disabled={!completed}
  variant={output && output.linkedButton ? "outlined" : "contained"}
  color="primary"
>
  Start Over
</Button>
```

## Context

The current implementation with the primary 'Start over' button suggests that starting over is the next step in the desired flow.
