### ISSUE TITLE
Backstage.io Backend not connecting on deploying on EKS(kubernetes) cluster

### ISSUE THREAD

**Issue by bcamishrapr** [backstage/backstage#12691]
## Expected Behavior

On Deployment of Backstage on kubernetes , Frontend should connect to backend to fetch the entities.

## Actual Behavior

Frontend is not able to connect to backend for fetching the entities getting **"could not fetch catalog entities"**

![image](https://user-images.githubusercontent.com/43287406/179499153-8c9d4afd-aa6c-47bd-9f3e-2f89e891e01c.png)

## Steps to Reproduce

-- Create the repo with ```npx @backstage/create-app```
-- Build the Dockerfile and push it to Container repository
-- Deploy the backstage in k8s cluster and access it using k8s-svc or ingress.

Dockerfile:
```
# Stage 1 - Create yarn install skeleton layer
FROM node:16-bullseye-slim AS packages

WORKDIR /app
COPY package.json yarn.lock ./

COPY packages packages

COPY catalog-info.yaml ./
COPY examples examples

# Comment this out if you don't have any internal plugins
#COPY plugins plugins

RUN find packages \! -name "package.json" -mindepth 2 -maxdepth 2 -exec rm -rf {} \+

# Stage 2 - Install dependencies and build packages
FROM node:16-bullseye-slim AS build

WORKDIR /app
COPY --from=packages /app .

# install sqlite3 dependencies
#RUN apt-get update && \
#    apt-get install -y --no-install-recommends libsqlite3-dev python3 build-essential && \
#    yarn config set python /usr/bin/python3

RUN yarn install --frozen-lockfile --network-timeout 600000 && rm -rf "$(yarn cache dir)"

COPY . .

RUN yarn tsc
RUN yarn --cwd packages/backend build
# If you have not yet migrated to package roles, use the following command instead:
#RUN yarn --cwd packages/backend backstage-cli backend:bundle --build-dependencies

# Stage 3 - Build the actual backend image and install production dependencies
FROM node:16-bullseye-slim

WORKDIR /app

# install sqlite3 dependencies, you can skip this if you don't use sqlite3 in the image
#RUN apt-get update && \
#    apt-get install -y --no-install-recommends libsqlite3-dev python3 build-essential && \
#    rm -rf /var/lib/apt/lists/* && \
#    yarn config set python /usr/bin/python3

# Copy the install dependencies from the build stage and context
COPY --from=build /app/yarn.lock /app/package.json /app/packages/backend/dist/skeleton.tar.gz ./
RUN tar xzf skeleton.tar.gz && rm skeleton.tar.gz

RUN yarn install --frozen-lockfile --production --network-timeout 600000 && rm -rf "$(yarn cache dir)"

# Copy the built packages from the build stage
COPY --from=build /app/packages/backend/dist/bundle.tar.gz .
RUN tar xzf bundle.tar.gz && rm bundle.tar.gz

# Copy any other files that we need at runtime
COPY app-config.yaml ./

CMD ["node", "packages/backend", "--config", "app-config.yaml"]
```

------------------------------------------------------
**app-config.yaml:**
```
app:
  title: My Backstage App
  baseUrl: http://localhost:3000

organization:
  name: MYORG

backend:
  # auth:
  #   keys:
  #     - secret: ${BACKEND_SECRET}
  baseUrl: http://localhost:7007
  listen:
    port: 7007
    #host: 0.0.0.0
  csp:
    connect-src: ["'self'", 'http:', 'https:']
  
  cors:
    origin: http://localhost:3000
    methods: [GET, POST, PUT, DELETE]
    credentials: true

  database:
   
    client: pg
    connection:
       host: ${POSTGRES_HOST}
       port: ${POSTGRES_PORT}
       user: ${POSTGRES_USER}
       password: ${POSTGRES_PASSWORD}

  # workingDirectory: /tmp # Use this to configure a working directory for the scaffolder, defaults to the OS temp-dir

integrations:
  github:
    - host: github.com
     
      token: ${GITHUB_TOKEN}


proxy:
  '/test':
    target: 'https://example.com'
    changeOrigin: true


techdocs:
  builder: 'local' # Alternatives - 'external'
  generator:
    runIn: 'docker' # Alternatives - 'local'
  publisher:
    type: 'local' # Alternatives - 'googleGcs' or 'awsS3'. Read documentation for using alternatives.

#auth:
  # see https://backstage.io/docs/auth/ to learn about auth providers
  #providers:
    #github:
      #development:
        #clientId: ${AUTH_GITHUB_CLIENT_ID}
        #clientSecret: ${AUTH_GITHUB_CLIENT_SECRET}

scaffolder:
  # see https://backstage.io/docs/features/software-templates/configuration for software template options

catalog:
  import:
    entityFilename: catalog-info.yaml
    #pullRequestBranchName: backstage-integration
  rules:
    - allow: [Component, System, API, Resource, Location, Template]
  locations:
    # Local example data, file locations are relative to the backend process, typically `packages/backend`
    - type: file
      target: ../../examples/entities.yaml

    # Local example template
    #- type: file
      #target: ../../examples/template/template.yaml
      #target: examples/template/template.yaml
      #rules:
        #- allow: [Template]
    #- type: file
      #target: ../../examples/template1/template.yaml
      #target: examples/template/template.yaml
      #rules:
        #- allow: [Template]

    # Local example organizational data
    #- type: file
      #target: ../../examples/org.yaml
      #rules:
        #- allow: [User, Group]

    ## Uncomment these lines to add more example data
    - type: url
      target: https://github.com/backstage/backstage/blob/master/packages/catalog-model/examples/all.yaml

    ## Uncomment these lines to add an example org
    #- type: url
      #target: https://github.com/backstage/backstage/blob/master/packages/catalog-model/examples/acme-corp.yaml
      #rules:
        #- allow: [User, Group]

```

## Context

--> I am trying to deploy Backstage.io in kubernetes cluster with RDS as a data persistent solution

REF:
https://backstage.io/docs/deployment/k8s
https://backstage.io/docs/deployment/docker

## Your Environment

EKS
RDS(For Data Persistent)
DockerHub (for Repo)

- Browser Information: 

- Output of `yarn backstage-cli info`: 

```
$ /root/ty/node_modules/.bin/backstage-cli info
OS:   Linux 3.10.0-1127.el7.x86_64 - linux/x64
node: v14.19.3
yarn: 1.22.19
cli:  0.17.2 (installed)

Dependencies:
  @backstage/app-defaults                          1.0.3
  @backstage/backend-common                        0.14.0
  @backstage/backend-tasks                         0.3.2
  @backstage/catalog-client                        1.0.3
  @backstage/catalog-model                         1.0.3
  @backstage/cli-common                            0.1.9
  @backstage/cli                                   0.17.2
  @backstage/config-loader                         1.1.2
  @backstage/config                                1.0.1
  @backstage/core-app-api                          1.0.3
  @backstage/core-components                       0.9.5
  @backstage/core-plugin-api                       1.0.3
  @backstage/errors                                1.0.0
  @backstage/integration-react                     1.1.1
  @backstage/integration                           1.2.1
  @backstage/plugin-api-docs                       0.8.6
  @backstage/plugin-app-backend                    0.3.33
  @backstage/plugin-auth-backend                   0.14.1
  @backstage/plugin-auth-node                      0.2.2
  @backstage/plugin-catalog-backend                1.2.0
  @backstage/plugin-catalog-common                 1.0.3
  @backstage/plugin-catalog-graph                  0.2.18
  @backstage/plugin-catalog-import                 0.8.9
  @backstage/plugin-catalog-react                  1.1.1
  @backstage/plugin-catalog                        1.3.0
  @backstage/plugin-github-actions                 0.5.6
  @backstage/plugin-home                           0.4.22
  @backstage/plugin-org                            0.5.6
  @backstage/plugin-permission-common              0.6.2
  @backstage/plugin-permission-node                0.6.2
  @backstage/plugin-permission-react               0.4.2
  @backstage/plugin-proxy-backend                  0.2.27
  @backstage/plugin-scaffolder-backend             1.3.0
  @backstage/plugin-scaffolder-common              1.1.1
  @backstage/plugin-scaffolder                     1.3.0
  @backstage/plugin-search-backend-module-pg       0.3.4
  @backstage/plugin-search-backend-node            0.6.2
  @backstage/plugin-search-backend                 0.5.3
  @backstage/plugin-search-common                  0.3.5
  @backstage/plugin-search-react                   0.2.1
  @backstage/plugin-search                         0.9.0
  @backstage/plugin-stack-overflow                 0.1.2
  @backstage/plugin-tech-radar                     0.5.13
  @backstage/plugin-techdocs-backend               1.1.2
  @backstage/plugin-techdocs-module-addons-contrib 1.0.1
  @backstage/plugin-techdocs-node                  1.1.2
  @backstage/plugin-techdocs-react                 1.0.1
  @backstage/plugin-techdocs                       1.2.0
  @backstage/plugin-user-settings                  0.4.5
  @backstage/release-manifests                     0.0.4
  @backstage/test-utils                            1.1.1
  @backstage/theme                                 0.2.15
  @backstage/types                                 1.0.0
  @backstage/version-bridge                        1.0.1


```
