### ISSUE TITLE
[Scaffolder] Action to set custom variables to reuse in the template

### ISSUE THREAD

**Issue by stichiboi** [backstage/backstage#12767]
## Feature Suggestion

Dummy action `dummy:variables` that takes anything as input and provides it as output

## Context

I'm using `fs:rename` to modify the path and name of my skeleton files. This requires a bit of concatenation and replacing

Since I need to provide links to the files in several places, it's a hassle and I will make mistakes sooner or later

I tried using [Nunjucks variables](https://mozilla.github.io/nunjucks/templating.html#variables)
```yaml
... some stuff...
steps:
  ${% set catalogInfoPath = "catalog/" + parameters.component_id | replace("[ -\s. ]", "_") + "_catalog-info.yaml" %}
  ${% set dagPath = "dags/" + parameters.component_id | replace("[ -\s. ]", "_") + "_dag.py" %}
    - id: fetch-template
      name: Fetch Catalog Info
      action: fetch:template
      input:
        url: ./skeleton
        values:
... some other stuff...
```

But I was getting this warning from the catalog
```
YAML error at url:[path to my gitlab repo]/template.yaml, YAMLSyntaxError: All collection items must
 start at the same column
```

**Comment by benjdlambert** [comment]
So to give some reasoning why the `nunjucks` variables don't work, it's only the values in the steps that are templated. Not the entire `yaml` document, so it's why you were getting that error as the `yaml` is not longer valid.

I'm wondering if it makes sense to have another option for this instead and treat this as first class. But it needs some more thought.


Something like:


```yaml
context:
  variables:
    catalogInfoPath: catalog/${{ parameters.component_id| replace("[ -\s. ]", "_") }}_catalog-info.yaml

steps:
    - id: fetch-template
      name: Fetch Catalog Info
      action: fetch:template
      input:
        url: ./skeleton
        values:
          catalogInfoPath: ${{ context.variables.catalogInfoPath  }}
```

It's kind of similar to https://github.com/backstage/backstage/issues/9461 in a way.


Overall I prefer an action, because you can execute arbitrary code in there to populate an environment, but then it's up to every company to implement their own version of an action that can have outputs that can take inputs and do whatever with them, so not sure that theres a use for `dummy:variables` in this case.
