### ISSUE TITLE
[RFC] Standardize AWS authentication in Backstage

### ISSUE THREAD

**Issue by clareliguori** [backstage/backstage#12844]
**Status:** Open for comments

# RFC: Standardizing AWS authentication in Backstage

I'm considering building a common library for Backstage backend plugins to source AWS credentials used for calling AWS APIs.  I've noticed that different plugins related to AWS are sourcing credentials in different ways (see last section below for examples), and with varying support for features like cross-account roles, using IRSA credentials when running in EKS, and sourcing credentials from other AWS partitions like China.

Would love some feedback from other integration/plugin developers on whether this would be useful.

cc @niallthomson @nimakaviani @marcus-crane @FilipPyrek @punkle @backjo

## Proposal

I propose migrating to a single unified configuration section for AWS account and credential information in the Backstage configuration.  Example:

```yaml
integrations:
  aws:
    default:   # Optional: falls back to default credential provider chain
      accessKeyId: ${AWS_ACCESS_KEY_ID}
      secretAccessKey: ${AWS_SECRET_ACCESS_KEY}
      assumeRole: arn:aws:iam::123456789012:role/backstage-main-role
      externalId: 'some-id'
    accounts:  # Optional: if no accounts are specified, falls back to default creds
    - accountId: '111111111111'
      assumeRole: arn:aws:iam::111111111111:role/backstage-role
      externalId: 'hello'
    - accountId: '222222222222'
      assumeRole: arn:aws:iam::222222222222:role/backstage-role
      externalId: 'world'
```

A common library would provide standard methods for retrieving a credentials provider that takes care of reading the above configuration.  Then, each plugin can use the credential provider directly with their AWS service client:
```typescript
    // Example constructing an AWS Proton client with credentials from the standard library
    const client = new ProtonClient({
      region,
      credentialDefaultProvider: () => AwsCredentialsForBackstage.getCredentialProvider({region, accountId}),
    });

    // Example retrieving a credential provider using an ARN.
    // Region and account ID are automatically parsed from the ARN
    AwsCredentialsForBackstage.getCredentialProvider({arn});

    // Example retrieving credential provider using the "default" config section,
    // not providing any information like an account ID
    AwsCredentialsForBackstage.getCredentialProvider();
```

The logic for the credential provider would be as follows:
* When `assumeRole` is provided in the Backstage config, the credential provider would use the Javascript SDK's [`fromTemporaryCredentials`](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/modules/_aws_sdk_credential_providers.html#fromtemporarycredentials) method to return credentials from an STS AssumeRole call.  The region parameter would be used to call that region's STS endpoint.
* When access key ID and secret access key ID are provided, the credential provider would use those static credentials.
* If neither are provided, the credential provider would use the [default credential chain for Node](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/modules/_aws_sdk_credential_providers.html#fromnodeproviderchain):
  * Environment variables
  * SSO credentials from token cache
  * Web identity token credentials (include EKS service account credentials)
  * Shared credentials and config ini files
  * The EC2/ECS Instance Metadata Service

**Notes**
* This would be based on AWS SDK for Javascript V3, so plugins using the V2 SDK would need to migrate to V3.  For example: https://github.com/backstage/backstage/issues/12066
* This is not intended to be an API that front-end plugins can call to retrieve credentials.  This is intended to be a common library for backend plugins and integrations to retrieve credentials and make AWS API calls.
* This is not intended to retrieve AWS credentials based on the identity of the Backstage user.  Plugins would use the same credentials for all AWS API calls, regardless of the Backstage user using the plugin.
* This may require breaking changes in some plugins to migrate to using this library.  For example, a breaking change in how the plugin is configured, like moving from `integrations.awsS3` to `integrations.aws`.

**Open questions:**
* Should this be contributed somewhere in the Backstage core repo?  Then it can be used by the built-in integrations like S3, TechDocs, Kubernetes auth providers, etc without a new external dependency.  Or should this be published as a separate repo and npm package?
* Is support needed for any other method for sourcing AWS credentials?  Cognito identities, web identities like Facebook Login, non-default web identity token files, or non-default profiles from AWS config files?

## Future enhancements

The format of the configuration above seems extensible for more use cases in the future.

**Supporting plugin-specific configuration**

Some integrations (like the AWS Kubernetes auth provider) currently have AWS auth config deeply integrated into the plugin's configuration, and it may be difficult to migrate entirely to the `integrations.aws` config.  For example, the AWS Kubernetes auth provider allows the user to associate a different IAM role per EKS cluster, not just per account like in the `integrations.aws` config.
```yaml
kubernetes:
  clusterLocatorMethods:
    - type: 'config'
      clusters:
        - url: https://xxxxxxxxxxxxxx.xx1.us-west-2.eks.amazonaws.com
          name: my-eks-cluster
          authProvider: 'aws'
          assumeRole: 'arn:aws:iam::xxxxxxxxxxxx:role/example-role'
          externalId: 'some-id'
```

In a future enhancement, we could export a type for the unified AWS config that could be used by a plugin to use the same format for account configuration, but inside their own plugin configuration.  For example:
```typescript
// AWS Kubernetes auth provider can use this type to define the possible fields for AWS cluster configuration.
export interface AwsCredentialsConfig {
  accessKeyId?: string;
  secretAccessKey?: string;
  assumeRole?: string;
  externalId?: string;
}

// Then it can use a method to pass the parsed config as an AwsCredentialsConfig object and get back a credential provider
AwsCredentialsForBackstage.getCredentialProviderFromConfig(parsedConfig);
```

**Supporting plugin overrides in the unified configuration**

Backstage users may want to scope down the permissions that individual plugins have by defining an IAM role per plugin.  The unified configuration could support plugin overrides to let users specify roles per account per plugin.

For example:
```yaml
integrations:
  aws:
    accounts: # Accounts used by default if no plugin overrides are specified for the calling plugin
    - accountId: '111111111111'
      assumeRole: arn:aws:iam::111111111111:role/backstage-role
    pluginOverrides:
      proton: # Assume a different role in these accounts when retrieving creds for the Proton plugin
        accounts:
        - accountId: '111111111111'
          assumeRole: arn:aws:iam::111111111111:role/role-for-proton-plugin
```

The plugins would need to declare to the common library which plugin overrides to retrieve if they are specified in the Backstage config:

```typescript
    // Example constructing an AWS Proton client with credentials from the standard library, specifying the 'proton' plugin overrides
    const client = new ProtonClient({
      region,
      credentialDefaultProvider: () => AwsCredentialsForBackstage.getCredentialProvider({
        region, 
        accountId, 
        plugin: 'proton'
      }),
    });
```

## Examples of current AWS auth integrations for Backstage

Examples of the various AWS integrations and plugins I found for Backstage, along with how they each source AWS credentials for authenticating to AWS APIs.

**Proton plugin**

https://github.com/awslabs/aws-proton-plugins-for-backstage/

Sources credentials from the environment (default credential provider chain). Can only be used with one AWS account; does not assume any roles in other accounts.

**CloudFormation plugin**

https://github.com/purple-technology/backstage-aws-cloudformation-plugin

Sources credentials from an AWS config file on disk.  A default profile name can be specified in Backstage config for the AWS config file, and catalog locations can also include a profile name.

Example configuration:
```yaml
integrations:
  aws:
    profile: purple-technology
    
catalog:
  locations:
    - type: aws:cloudformation:stack
      target: myCustomProfile@arn:aws:cloudformation:ap-southeast-1:123456789000:stack/some-stack/123-345-12-1235-123123
```

**AWS Auth plugin (and Lambda plugin)**

AWS Auth plugin: https://www.npmjs.com/package/@roadiehq/backstage-plugin-aws-auth

Lambda plugin: https://www.npmjs.com/package/@roadiehq/backstage-plugin-aws-lambda

The AWS Auth backend plugin is geared towards use by front-end plugins like the Lambda plugin.  The front-end retrieves session credentials from a backend API, and then the front-end makes AWS API calls directly from the browser using those credentials.  The backend sources credentials from the environment (it tries env vars first, then falls back to default credential provider chain), and optionally assumes a role in another account.

**AWS Backend plugin**

https://www.npmjs.com/package/@roadiehq/backstage-plugin-aws-backend

Sources credentials from the environment (default credential provider chain), then assumes a role in a given account.

Example configuration:
```yaml
integrations:
  aws:
    - accountId: '9999999999'
      roleArn: arn:aws:iam::9999999999:role/ops
      region: eu-west-1
      externalId: 'blah'
```

**S3 Locations and Discovery**

https://backstage.io/docs/integrations/aws-s3/locations

https://backstage.io/docs/integrations/aws-s3/discovery

Sources credentials from the Backstage configuration, and falls back to sourcing credentials from the environment (default credential provider chain).  Then it optionally assumes a role into another account.

Example configuration:
```yaml
integrations:
  awsS3:
    - accessKeyId: ${AWS_ACCESS_KEY_ID}
      secretAccessKey: ${AWS_SECRET_ACCESS_KEY}
      roleArn: 'arn:aws:iam::xxxxxxxxxxxx:role/example-role'
      externalId: 'some-id'
```
(Falls back to sourcing credentials from the environment?)

**TechDocs S3 Publisher**

https://backstage.io/docs/features/techdocs/configuration

Sources credentials from the Backstage configuration, and falls back to sourcing credentials from the environment (default credential provider chain).

Example configuration:
```yaml
techdocs:
  publisher:
    type: 'awsS3'
    awsS3:
      bucketName: 'techdocs-storage'
      credentials:
        accessKeyId: ${TECHDOCS_AWSS3_ACCESS_KEY_ID_CREDENTIAL}
        secretAccessKey: ${TECHDOCS_AWSS3_SECRET_ACCESS_KEY_CREDENTIAL}
```

**Kubernetes AWS Auth Provider**

https://backstage.io/docs/features/kubernetes/configuration#clustersauthprovider

Sources credentials from the environment (default credential provider chain), then optionally assumes a role into another account.

Example configuration:
```yaml
kubernetes:
  clusterLocatorMethods:
    - type: 'config'
      clusters:
        - url: https://xxxxxxxxxxxxxx.xx1.us-west-2.eks.amazonaws.com
          name: my-eks-cluster
          authProvider: 'aws'
          assumeRole: 'arn:aws:iam::xxxxxxxxxxxx:role/example-role'
          externalId: 'some-id'
```

**OpenSearch/ElasticSearch search engine**

https://backstage.io/docs/features/search/search-engines#aws

Sources credentials from the environment (default credential provider chain). Can only be used with one AWS account; does not assume any roles in other accounts.

Example configuration:
```yaml
search:
  elasticsearch:
    provider: aws
    node: https://my-backstage-search-asdfqwerty.eu-west-1.es.amazonaws.com
```

**Comment by marcus-crane** [comment]
Ah yes!

This is something that has bugged me for a bit. It's true across Backstage plugins in general that a third party plugin may implement credential configuration differently than the monorepo does for the same service and even then, plugins within the monorepo differ too as you've demonstrated so there's a bit of duplication that can be tidied up.

This RFC looks like a really nice step towards tidying up how Backstage handles AWS roles 🙂

In the case of awsS3, I even ended up stubbing out the configuration block (with an empty array) in order to force the plugin to fall back to the default credential chain available to the underlying EC2 instance

**Comment by benjdlambert** [comment]
This is a great suggestion. It's only going to get more and more complex as we add more support for more AWS products in the future, so I think this is a good initiative.  Thinking that adding it to the integrations feels like a reasonable place to put it, although I think it might go against the current pattern of using host resolution for these things, but I think that's fine.

The rest of the maintainers are starting to come back from vacations next week, so would be good to get their input too to see how we can move this forward :pray:

**Comment by clareliguori** [comment]
@fabbazon, thinking through the CodePipeline / CodeSuite plugin case:

I don't think it's scalable to have the pipeline ARN -> profile mapping in the static Backstage config, as you have here:
```
integrations:
  aws_codepipeline:
    - arn: arn:aws:iam::111111111111:pipeline/one
      aws_profle:  pipeline_a
    - arn: arn:aws:iam::111111111111:pipeline/two
      aws_profile: pipeline_b
```
The scaffolder could create a bunch of new pipelines, and then some admin person would need to go and map each of those new pipelines to a profile in the Backstage config.

So you would need to specify the pipeline ARN and the profile in the component annotations:
```
metadata:
  annotations:
    aws.amazon.com/codepipeline-arn: [YOUR_PIPELINE_ARN]
    aws.amazon.com/codepipeline-aws-profile: my_teams_dev_tools_account
    aws.amazon.com/aws-proton-service: [YOUR PROTON SERVICE ARN]
    aws.amazon.com/aws-proton-aws-profile: my_teams_proton_account
    aws.amazon.com/some-other-aws-service-annotation: [AN ARN]
    aws.amazon.com/some-other-aws-service-aws-profile: my_teams_prod_account
```
And then each backend plugin would need to query the catalog for the entity annotations and get the profile credentials:
```
AwsCredentialsForBackstage.getCredentialProvider(
  entity.metadata.annotations?.['aws.amazon.com/codepipeline-aws-profile']
)
```

A few questions come to mind, probably some input from maintainers:
* Is this a common pattern in Backstage - having devs effectively specify how to resolve the credentials to use in their component's annotations?
* How would developers know which profile string to put in their component's annotations?
* What are the security implications of letting developers choose which AWS profile is used to retrieve information about their component's AWS resources, by having them put it in the component's annotations?  Could they choose a role that has more permissions than intended?

**Comment by backjo** [comment]
Excited for this RFC - this is long overdue :) 

One additional use case to consider here (as @fabbazon touches upon) is dynamically-created accounts in the Catalog. In our Backstage implementation, we use the AWS Organizations APIs (using a role in the master AWS account) to source catalog entries for all other AWS accounts we own. For this type of usage (which IMO will be more prevalent in enterprise type users), we'd want to support credential configuration on the entity in the Catalog itself, rather than via the Backstage configuration .

**Comment by clareliguori** [comment]
@backjo Can you describe more about this?
> we'd want to support credential configuration on the entity in the Catalog itself, rather than via the Backstage configuration
If I'm understanding correctly, you have catalog entities that represent the AWS accounts themselves.  And you would want the "AWS Account" entity in the catalog to have accessKey and secretKey annotations, such that other plugins could look up the "AWS Account" catalog entity for a given account ID and retrieve the credentials to make their API calls?

**Comment by Rugvip** [comment]
Thank you, great writeup! 👏 Sorry that this slipped under the radar as we came back from vacations, had a proper read of it now though.

https://github.com/backstage/backstage/issues/12844#issue-1318813890:

> Should this be contributed somewhere in the Backstage core repo? Then it can be used by the built-in integrations like S3, TechDocs, Kubernetes auth providers, etc without a new external dependency. Or should this be published as a separate repo and npm package?

Happy to have this in the core repo if you want to contribute! I think it's good to keep something like this close to the core as it's a quite integral part. There are middle grounds to consider as well though. For example, while we might define an interface and default implementation as part of the core, it's possible to have more elaborate implementations live in separate packages.

> Is support needed for any other method for sourcing AWS credentials? Cognito identities, web identities like Facebook Login, non-default web identity token files, or non-default profiles from AWS config files?

Most likely that's something that can be added later, with the exception of using user credentials from the client, that might need a bit of consideration upfront. The main precedent for that is GitHub auth, for which the decision to use server or user credentials happens before reaching the credential provider.

https://github.com/backstage/backstage/issues/12844#issuecomment-1205447571:

> Is this a common pattern in Backstage - having devs effectively specify how to resolve the credentials to use in their component's annotations?

No. Where something similar happens there's generally a level on indirection where developers (or hopefully catalog automation) specify a real property of their service, like for example an EKS cluster. In the backend there might then be configuration or logic that is able to resolve the cluster -> credentials relationsship.

> How would developers know which profile string to put in their component's annotations?

Right? 😅 Better let developers put something more concrete, or best case, nothing at all. I think we should always leave things open for customizations that let organizations automate away these kind of tasks.

> What are the security implications of letting developers choose which AWS profile is used to retrieve information about their component's AWS resources, by having them put it in the component's annotations? Could they choose a role that has more permissions than intended?
mazonaws.com

Yep, if there are multiple profiles to choose from and it doesn't matter which one they choose, than why is there not just a single profile? If it does matter which one they choose then there's gotta be some logic to validate that, in which case that logic should be able to automatically select the profile in the first place? 🤷

---

Couple of tips on moving this forward: What we most likely want to end up with an interface similar to [`GithubCredentialsProvider`](https://github.com/backstage/backstage/blob/b8b2d4ab04da2e683b80dfa8d720c65c765f421f/packages/integration/src/github/types.ts#L41-L43) for plugins to use. That one seems very simple, but tbh an AWS equivalent doesn't need to be that much complex. The main thing to figure out is what information we need plugins to pass for us to accurately be able to hand over credentials, and what they get in return. The interface ends up being the core of the solution and what all plugins consume, and it's important that it is stable over time. It might be good to discuss some options here first, but pretty quickly I think a draft PR with a partial implementation is needed, just to try things out in practice. It's important for the interface to convey enough information to the implementation for it to be possible to implement the use-cases we want, but it must also be clear from the consumers point of view what information they should pass on.

With an interface in place, we can really switch out and iterate on the implementation quite a lot. This is the bit I'm referring to in the first question above ^, you can have complete separate implementations living outside the main repo. You can add more features, lookup patterns, credential sources, customizations points, what have you. It's just important that the initial implementation has reasonable coverage of the possible use-cases so that we don't end up missing something crucial in the interface.

A side note is that the credential provider currently needs to be depended on and injected very manually by plugins, which is fine for now. Once #11611 is shipped that'll be a lot simpler, all plugins will essentially have access to the credential provider without any additional setup needed.

**Comment by Rugvip** [comment]
Just wanna chime in and say that this is still very much something we're interested in if it's something you want to drive. We're a bit swamped up until BackstageCon + KubeCon, but happy to hop on a call sometime after to discuss ways forward.

**Comment by clareliguori** [comment]
Yep, I'm planning on putting up a draft PR soon, just finding the time to put it together :smile:

**Comment by clareliguori** [comment]
I put up a PR with my proposed library (https://github.com/backstage/backstage/pull/14125), and would love feedback from users and plugin authors on the API + config format.

For users, the behavior and config format is slightly different from what I described in the RFC.  Examples:
```yaml
integrations:
  aws:
    # Used for assume-role calls into other accounts
    # Can be omitted to fall back to the AWS SDK's default creds chain
    mainAccount:
      accessKeyId: ${MY_ACCESS_KEY_ID}
      secretAccessKey: ${MY_SECRET_ACCESS_KEY}

    # Account credentials can be configured individually per account
    accounts:
      # Credentials can come from a role in the account
      - accountId: '111111111111'
        roleName: 'my-iam-role-name'
        externalId: 'my-external-id'

      # Credentials can come from other AWS partitions
      - accountId: '222222222222'
        partition: 'aws-other',
        roleName: 'my-iam-role-name'
        # The STS region to use for the AssumeRole call
        region: 'not-us-east-1'
        # The creds to use when calling AssumeRole
        accessKeyId: ${MY_ACCESS_KEY_ID_FOR_ANOTHER_PARTITION},
        secretAccessKey: ${MY_SECRET_ACCESS_KEY_FOR_ANOTHER_PARTITION}

      # Credentials can come from static credentials
      - accountId: '333333333333'
        accessKeyId: ${MY_OTHER_ACCESS_KEY_ID}
        secretAccessKey: ${MY_OTHER_SECRET_ACCESS_KEY}

      # Credentials can come from the AWS SDK's default creds chain
      - accountId: '444444444444'

    # Credentials for accounts can fall back to a common role name
    # This is useful for account discovery use cases where the account IDs may not be known when writing the static config
    # If all accounts have a role with the same name, the "accounts" section can be omitted entirely
    accountDefaults:
      roleName: 'my-backstage-role'
      externalId: 'my-id'
```

If all accounts have the same role name, the `accounts` section can be entirely omitted and accounts do not need to be added individually to the config.
```yaml
integrations:
  aws:
    accountDefaults:
      roleName: 'my-backstage-role'
      externalId: 'my-id'
```

If the configuration is missing (i.e. anyone's current Backstage config), the cred provider will fall back to the AWS SDKs default cred chain for resources in the same account:
```yaml
integrations:
  aws: {}
```

For plugin authors, I have not added any logic around per-plugin overrides (this can likely be added later if needed).  The main method can use account ID or ARN to determine the creds to load.
```typescript
const awsCredentialsProvider = DefaultAwsCredentialsProvider.fromConfig(config);

// provide the account ID explicitly
const creds = await awsCredentialsProvider.getCredentials({ arn });
// OR extract the account ID from the ARN
const creds = await awsCredentialsProvider.getCredentials({ accountId });
// OR provide neither to get main account's credentials
const creds = await awsCredentialsProvider.getCredentials({});

// Example constructing an AWS Proton client with credentials from the standard library
const client = new ProtonClient({
  region,
  credentialDefaultProvider: () => creds.provider,
});
```
There is a fuller example of integrating the creds provider into a plugin here: https://github.com/awslabs/aws-proton-plugins-for-backstage/commit/ace2729591e9891382ed9a512c265b8dc6c9c684

**Comment by webark** [comment]
I like this direction!!

Two notes of feedback. `mainAccount` is a little odd. Is there any other backstage configs that has a similar fallback pattern to use shared terminology?

This is more of a question, but should each account be given a key/name? If you wanted two roles for the same account, would you just put two records in? Can there be two records with the same account id?

Great progress. 👍

**Comment by clareliguori** [comment]
@webark 

> mainAccount is a little odd. Is there any other backstage configs that has a similar fallback pattern to use shared terminology?

I think this is the only integration that has a hierarchy of accounts, where the "main" account is used to assume a role into the "child" accounts.  Some other terms I considered: root account, primary account.  Spinnaker uses the term "managing account" for the main account, and "managed account" for the child accounts, which I've always found confusing.  But otherwise, I don't feel strongly about main vs root vs primary vs something else.

> This is more of a question, but should each account be given a key/name? If you wanted two roles for the same account, would you just put two records in? Can there be two records with the same account id?

Based on the other integrations, it is not typical to assign a name to an account or to have multiple records for the same account, so I have not supported either here.  This is where something like plugin-specific overrides would come in, perhaps in the future.  If you want to set up a specific role for a specific plugin, you would have a separate section for that plugin.  See the original post in this RFC for examples.  Again, in the future and not part of this initial implementation.

**Comment by andrewthauer** [comment]
Question - with this design how do you envision something like `fromIni` working for local testing (eg. with SSO)? Meaning locally you use ini but in prod it's using the integration accounts.

**Comment by clareliguori** [comment]
@andrewthauer the default chain includes fromIni, so leaving the configuration blank when locally testing will pick up the default profile in `~/.aws/credentials` and `~/.aws/config`.
https://github.com/aws/aws-sdk-js-v3/blob/731cbbf549e354d5dd103109ae679ba38ada4de7/packages/credential-provider-node/src/defaultProvider.ts#L49-L64

**Comment by andrewthauer** [comment]
@clareliguori - Thanks for confirming! I'm still getting used to the v3 API changes. I also realized recently that the SSO flow works better in v3 and not really at all in v2 hence the reason I'm asking.

We currently have a use case for 2 different accounts. One for techdocs and another for a custom internal plugin. A follow up to this would be if it's possible to target a specific profile with the fallback ini approach? In production we can just use an assumeRole, but locally we might want leverage SSO and target different accounts based on a profile by name. For our internal plugin we could definitely build in a custom flow for this. However, it might be nice to have a documented and supported standard for all plugins. I apologize if this is in your proposal and I just overlooked it.

**Comment by clareliguori** [comment]
@andrewthauer makes sense.  I added profile support to the PR, so you'll be able to do:
```yaml
integrations:
  aws:
    mainAccount:
      profile: my-main-account-profile-name
    accounts:
      - accountId: '111111111111'
         profile: my-other-account-profile-name
```
