### ISSUE TITLE
Running Backstage with only one Database

### ISSUE THREAD

**Issue by SEETechWolf** [backstage/backstage#12853]
Hello, 

we are evaluating Backstage for our Company. As we are in a very regulated Environment it is not possible for our technical Database Useres to create Databases. 
So we get a Database from our DBAs and have to use this specific one.

Is there a way to setup Backstage to run with only one Database for all Plugins and Data?
And how can we configure this?

If this is not jet possible:
- Is there some place that documents all DBs needed for the core implementation? So we can setup the corresponding amount of DBs
- Please make it a feature request.
In stead of having a DB per Plugin the Tablenames could be prefixed with the Pluginnames.

Thanks for your help

**Comment by benjdlambert** [comment]
Hmm, table names are not configurable unfortunately. However you can configure each plugin to use a different connection string here? https://backstage.io/docs/tutorials/configuring-plugin-databases so maybe they could also use the same db.

You can also use schemas instead of database by providing config in the `app-config.yaml` if that would help you instead?

**Comment by regicsolutions** [comment]
@benjdlambert are there any docs or examples your aware of on the usage of schemas?

**Comment by benjdlambert** [comment]
Hmm - I don't think that there is explicit docs on this unfortunately. But it's just config you can set in your `app-config.yaml` when using the `pg` client.

https://github.com/backstage/backstage/blob/master/packages/backend-common/config.d.ts#L86-L98

**Comment by benjdlambert** [comment]
So your `app-config.production.yaml` or wherever you setup `client: pg` under the `database` key would look something like this:


```yaml
  database:
    client: pg
    pluginDivisionMode: schema
    connection:
      host: ${POSTGRES_HOST}
      port: ${POSTGRES_PORT}
      user: ${POSTGRES_USER}
      password: ${POSTGRES_PASSWORD}
   ...
```
