### ISSUE TITLE
[RFC] Redirecting to the login page on refresh or open links in the new tab 

### ISSUE THREAD

**Issue by Ahampa07** [backstage/backstage#12917]
**Status:** Open for comments

The current system may ask you to log in again if you refresh the page(trigger refresh real quick multiple times) or open a few links in new tabs.
The intention behind this RFC is to identify the exact cause of losing user authentication on refresh or opening a few links in new tabs.

## Need

This might be because of a race that happens when the backing authentication provider invalidates refresh tokens on use. So if you for example make two parallel refresh requests, both are going to trigger an auth refresh, and if the second one is opened before the first one has had time to do a refresh, it will use the same refresh token and then fail to sign-in as the refresh token has been invalidated

## Proposal

If the logged-in user refreshes the page(trigger refresh real quick multiple times), the user gets the login screen again, and in the Developer tools network tab, they get Refresh failed; caused by OPError: invalid_grant (unknown, invalid, or expired refresh token)" as a response for the API /api/auth/oidc/refresh?optional&env=development
On each refresh, we generate a new access token using the refresh token rotation technique to enhance the access token security against malicious attacks.  
If we trigger the refresh real quick(parallel refresh requests) means both are going to trigger an auth refresh, and if the second one is opened before the first one has had time to do a refresh, it will use the same refresh token and then fail to sign-in as the refresh token has been invalidated
As discussed in https://github.com/backstage/backstage/issues/11160 this RFC, moving to a persistent server-side session store could solve the issue. 

As a persistent session store, we can think of Memcached or Redis, these two are compatible with Backstage and works with our existing DB infra and that is configured through our app-config. These caches are better suited for the production environment.

**Comment by webark** [comment]
🤔Which auth provider are you using? I haven't run into this issue before.

**Comment by Ahampa07** [comment]
> 🤔Which auth provider are you using? I haven't run into this issue before.

@webark we are using GitLab as auth provider.

**Comment by NishkarshRaj** [comment]
👍 - also, the in-memory session store is not ideal anyways given it blocks our ability to scale out in the EKS eco-system unless we force a user to the dedicated pods with sticky sessions, etc. as highlighted in #12757

**Comment by benjdlambert** [comment]
@Ahampa07 it's normally due to refresh not being configured correctly, is that setup for your provider?

**Comment by Ahampa07** [comment]
@benjdlambert could you please elaborate more, give some references around it?

**Comment by NishkarshRaj** [comment]
@benjdlambert we are using Ping Identity.

Here's the snippet we use in App Config

```yaml
auth:
  environment: production
  session:
    secret: ${AUTH_SESSION_SECRET}
  providers:
    oidc:
      production:
        metadataUrl: ${AUTH_OIDC_METADATA_URL}
        clientId: ${AUTH_OIDC_CLIENT_ID}
        clientSecret: ${AUTH_OIDC_CLIENT_SECRET}
        authorizationUrl: ${AUTH_OIDC_AUTH_URL}
        tokenUrl: ${AUTH_OIDC_TOKEN_URL}
        tokenSignedResponseAlg: ${AUTH_OIDC_TOKEN_SIGNED_RESPONSE_ALG}
        scope: ${AUTH_OIDC_SCOPE}
        prompt: ${AUTH_OIDC_PROMPT}
```
