### ISSUE TITLE
[Scaffolder] Review and create didn't hide when change options

### ISSUE THREAD

**Issue by tritri251214** [backstage/backstage#12948]
https://user-images.githubusercontent.com/32475934/182557014-035c5d01-0290-4948-99f0-d245ef47a4b7.mp4

```yaml
apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: custom-field-2-example
  title: Custom Field 2 Template
  description: An example template for the scaffolder that creates a simple Node.js service
spec:
  owner: user:guest
  type: service
  parameters:
    - title: Fill in some steps
      required:
        - name
      properties:
        name:
          title: Name
          type: string
          description: Unique name of the component
          ui:autofocus: true
          ui:options:
            rows: 5
        generation:
          type: string
          title: Generation Method
          enum:
            - Option 1
            - Option 2
          default: Option 1
      dependencies:
        generation:
          oneOf:
            - properties:
                generation:
                  const: Option 1
            - required:
                - customField
              properties:
                generation:
                  const: Option 2
                customField:
                  title: Custom Field
                  type: string
                  ui:field: CustomField

    - title: Choose a location
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com

  steps:
    - id: fetch-base
      name: Fetch Base
      action: fetch:template
      input:
        url: ./content
        values:
          name: ${{ parameters.name }}

    - id: publish
      name: Publish
      action: publish:github
      input:
        allowedHosts: ['github.com']
        description: This is ${{ parameters.name }}
        repoUrl: ${{ parameters.repoUrl }}

    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps.publish.output.repoContentsUrl }}
        catalogInfoPath: '/catalog-info.yaml'

  output:
    links:
      - title: Repository
        url: ${{ steps.publish.output.remoteUrl }}
      - title: Open in catalog
        icon: catalog
        entityRef: ${{ steps.register.output.entityRef }}
```

**Custom Field Extension file:**

![image](https://user-images.githubusercontent.com/32475934/182557419-a0d8bc65-5b2f-4bde-a405-740e81d3e7c9.png)

## Expected Behavior

Hide **Custom Field** in _**Review and create**_

## Actual Behavior

**Custom Field** displayed in **_Review and create_**

## Steps to Reproduce

1. Input Name
2. Select **Generation Method** is _Option 2_
3. Input **Custom Field**
4. Click button **Next**
5. Input **RepoUrl** field
6. Click button **Next** => Displayed value of **Custom Field** in **_Review and create_**
7. Click button **Back**
8. Click button **Back** => => Back to Step **_Fill in some steps_**
9. Select **Generation Method** is _Option 1_
10. Click button **Next**
11. Click button **Next** => **Custom Field** still display in  **_Review and create_**

## Your Environment

- Browser Information: 

- Output of `yarn backstage-cli info`: 

```text
OS:   Windows_NT 10.0.18363 - win32/x64
node: v16.14.0
yarn: 1.22.19
cli:  0.18.1-next.0 (local)
backstage:  N/A

Dependencies:
  @backstage/core-components         0.10.0
  @backstage/core-plugin-api         1.0.4
  @backstage/integration-react       1.1.2
  @backstage/integration             1.2.2
  @backstage/plugin-catalog-common   1.0.4
  @backstage/plugin-catalog-react    1.1.2
  @backstage/plugin-home             0.4.23
  @backstage/plugin-permission-react 0.4.3
  @backstage/plugin-stack-overflow   0.1.3
```
