### ISSUE TITLE
Catalog: 403 When using non SSL connection with Postgres DB

### ISSUE THREAD

**Issue by gabrielucido** [backstage/backstage#12956]
## Expected Behavior
The catalog should keep working when I use Postgres as my DB provider without SSL.

## Actual Behavior

In running a backstage 1.4.0 instance on @Via (early adopters since 2020) and since the update to 1.3.1 I noticed that my catalog has some errors which I didn't know the cause.

![image](https://user-images.githubusercontent.com/36337762/182641130-a04a77e4-6959-4e5c-904e-d1cd79fce7e5.png)

The error occurs because the github-org reference was getting a 403, so any locations to my org components like the image above would have a 404 error.

So I think that the main issue here should be this Github Org integration error 403 that I mentioned before and will give more details below:

![image](https://user-images.githubusercontent.com/36337762/182642275-fba906d2-6e6a-47bc-bf20-2f9145a9abd6.png)
> Processor GithubOrgReaderProcessor threw an error while reading github-org:https://github.com/viavarejo-internal; caused by GraphqlError: Your token has not been granted the required scopes to execute this query. The 'slug' field requires one of the following scopes: ['read:org', 'read:discussion'], but your token has only been granted the: ['repo', 'user'] scopes. Please modify your token's scopes at: https://github.com/settings/tokens.

I don't think that the message pointing out the token scope as a cause really means something to me because when I try to run with SQLITE or Postgres on localhost(no SSL config required) this error won't happen and my catalog works just fine.

## Steps to Reproduce
Just run the project with config down below and access or try adding any catalog item.

## Context

I using an HLG/SIT nonproductive database that accepts non-SSL connections.

This error is also blocking me from going v1 update for production which is around now v0.37, pretty damn old.

## Your Environment

Backstage v1.3.1 or above (maybe the older versions also have the issue).

1. Github Org Integration
2. Github Authentication with Github Apps(don't know if with GH Tokens the error also occurs).´
3. Use Postgres DB with this configuration with a DB that has SSL

```
database:
    client: pg
    connection:
      host:
        $env: POSTGRES_HOST
      port:
        $env: POSTGRES_PORT
      user:
        $env: POSTGRES_USER
      password:
        $env: POSTGRES_PASSWORD
      ssl:
        rejectUnauthorized: false # I think here is the problem
```

```
integrations:
  github:
    - host: github.com
      apps:
        - $include: github-app-backstage-viaops-credentials.yaml

catalog:
  locations:
    - type: github-org
      target:
        $env: GITHUB_ORG_URL
```
