### ISSUE TITLE
GitHub Entity Provider - catalogPath does not support wildcards

### ISSUE THREAD

**Issue by awanlin** [backstage/backstage#12992]
## Expected Behavior

The GitHub Entity Provider should support all the same features as the GitHub Discovery Processor (before the Processor is removed as deprecated). In this case specifically supporting wildcard in the `catalogPath`

## Actual Behavior

While attempting to move from the GitHub Discovery Processor to the new GitHub Entity Provider we ran into a regression where the `catalogPath` does not support wildcards.

## Steps to Reproduce

1. Create a repo with a `user` folder that has many YMAL files with the proper definition for User Kind in each file
2. Install the GitHub Entity Provider as per the documentation: https://backstage.io/docs/integrations/github/discovery#installation
3. Configure your `app-config.yaml` like this:

```yaml
providers:
    github:
      userEntities:
        organization: 'my-org'
        catalogPath: '/users/*.yaml'
        filters:
          branch: 'main'
          repository: 'my-entities'
```

4. Run `yarn dev`

Notice that the GitHub Entity Provider will find the repo as it's mentioned in the logs but then nothing happens from there

**Note:** a variant of this that should be supported as well is if the is a folder structure for the YAML files like this:

```text
groups
    product
       product.yaml
       product-teams
           team-a.yaml
           team-b.yaml
    engineering
        engineering.yaml
        engineering-teams
           team-c.yaml
           team-d.yaml
```

And the provider YAML would look like this:

```yaml
providers:
    github:
      groupEntities:
        organization: 'my-org'
        catalogPath: '/groups/**/*.yaml'
        filters:
          branch: 'main'
          repository: 'my-entities'
```

## Context

We currently store Users and Groups as individual YAML files in a single repo. Users are all in one single folder and Groups have a folder structure to them that matches the Org chart more or less.

We are using these URLs with the GitHub Discovery Processor and they work perfectly:

```yaml
- type: github-discovery # Users
   target: https://github.com/my-org/my-entities/tree/main/users/*.yaml
- type: github-discovery # Groups
   target: https://github.com/my-org/my-entities/tree/main/groups/**/*.yaml
```    

Because wildcard are not supported we can't use the new GitHub Entity Provider and with the GitHub Discovery Processor being marked as deprecated it's worrisome that we may lose functionality that we previously had

## Your Environment

This is not an environment specific issue more how we have our YAML files organized
