### ISSUE TITLE
Allow explicitly setting project ID in techdocs GCS publisher

### ISSUE THREAD

**Issue by tragiclifestories** [backstage/backstage#13049]
## Feature Suggestion

Add a `projectId` field to the `googleGcs` publisher config object, and use that to initialise the storage client if present.

## Possible Implementation

```yaml
techdocs:
  publisher:
    type: 'googleGcs'
    googleGcs:
      bucketName: 'my-bucket-1'
      credentials: $GOOGLE_CREDENTIALS
      projectId: 'my-project-1'
```

Then, when initialising the storage client, you would set the `projectId` from the config.

## Context

Currently the publisher grabs the project ID willy-nilly from the credentials blob it uses. CF 
https://github.com/backstage/backstage/blob/master/plugins/techdocs-node/src/stages/publish/googleStorage.ts#L97-L102

If no credentials are provided, no arguments are passed to the storage client.

This leads to a problem in cases where:
1. the credentials provided are for a service account in a different project to the bucket
2. the credentials are end user credentials, which don't have a project associated with them.

Backstage will not be able to read the docs (so to speak 🥁 ) in these cases.

In these cases, it would be better to be able to just explicitly set the project with the bucket in it.
