### ISSUE TITLE
Restrict catalog-import visibility to GitHub App Owner only

### ISSUE THREAD

**Issue by digogid** [backstage/backstage#13055]
## Feature Suggestion

Backstage should have an option to restrict sources of templates to a specific organization (rather be GitHub App owner). So Backstage will avoid when someone tries to import a new template from outisde that organization.

## Possible Implementation

Looking at Backstage's source code, we found this as a possible ways to do so:

At plugins/catalog-import the CatalogImportApi.analyzeUrl function should read the specified organization from app-config.yaml and check if the received URL came from within this organization.

## Context

We want it, because nowadays it is possible to import a GitHub public repo template. Our security team is looking deep inside Backstage's functionality and it is considered a big issue as a evil minded developer could import a template with any kinds of malicious code and exploit it.

**Comment by jhaals** [comment]
Hi @digogid! You're right that there's a risk of evil minded users doing bad things if they can edit the template source.
That's why it's recommended to not allow importing of custom templates using catalog import. This is already the default if you create a new backstage app and is controlled by the `rules` section in the configuration file.

Most users lock down their templates repositories with tight access control or configure a static path in this example below. 

```
catalog:
  import:
    entityFilename: catalog-info.yaml
    pullRequestBranchName: backstage-integration
  rules:
    - allow: [Component, System, API, Resource, Location]
  locations:
    - type: file
      target: path/to/my/trusted/templates/yaml
      rules:
        - allow: [Template]
```
