### ISSUE TITLE
ghcr.io/backstage/backstage fails to build techdocs

### ISSUE THREAD

**Issue by bittrance** [backstage/backstage#13099]
## Expected Behavior

I'm trying out Backstage by running the container image built by the [deploy Docker image pipeline](https://github.com/backstage/backstage/blob/master/.github/workflows/deploy_docker-image.yml). Since the techdocs plugin is included and visible in the UI (via the "View Techdocs" icon), I had assumed that a registered API repository would get its included techdocs built and presented. Admittedly, this image is not very well documented or exposed, so it is not quite clear what it is supposed to be used for, but according to https://github.com/backstage/backstage/blob/a9b1d7bf99df15a8fca484153d566e2b2bc8774a/.github/workflows/deploy_docker-image.yml#L91 it would seem reasonable to assume Techdocs should be generated.

## Actual Behavior

Alas, it seems not. With the default configuration in the image (i.e. `techdocs.generator.runIn==docker`), it complains that it cannot find `mkdocs.yml`.
```
[1]info: Step 1 of 3: Preparing docs for entity api:default/url-shortener {"timestamp":"2022-08-10T19:47:45.537Z"}
[2](http://localhost:7007/docs/default/API/url-shortener#line-2)info: Prepare step completed for entity api:default/url-shortener, stored at /tmp/backstage-eZ2OCi {"timestamp":"2022-08-10T19:47:46.690Z"}
[3](http://localhost:7007/docs/default/API/url-shortener#line-3)info: Step 2 of 3: Generating docs for entity api:default/url-shortener {"timestamp":"2022-08-10T19:47:46.690Z"}
[4](http://localhost:7007/docs/default/API/url-shortener#line-4)info: Set {"repo_url":"https://github.com/bittrance/url-shortener/tree/backstage-issue-1/","edit_uri":"https://github.com/bittrance/url-shortener/edit/backstage-issue-1/docs"}. You can disable this feature by manually setting 'repo_url' or 'edit_uri' according to the MkDocs documentation at https://www.mkdocs.org/user-guide/configuration/#repo_url {"timestamp":"2022-08-10T19:47:46.693Z"}
[5](http://localhost:7007/docs/default/API/url-shortener#line-5){"status":"Pulling from spotify/techdocs","id":"v1.0.3"}
[6](http://localhost:7007/docs/default/API/url-shortener#line-6){"status":"Digest: sha256:289c9779c510cda032af05221fd3f4dece5f30fadbe7838dd30268a4c7677318"}
[7](http://localhost:7007/docs/default/API/url-shortener#line-7){"status":"Status: Image is up to date for spotify/techdocs:v1.0.3"}
[8](http://localhost:7007/docs/default/API/url-shortener#line-8)Error: Config file 'mkdocs.yml' does not exist.
```

With `techdocs.generator.runIn==local` it complains that it cannot find the `mkdocs` binary since indeed, the container image does not container it:
```
[1](http://localhost:7007/docs/default/API/url-shortener#line-1)info: Step 1 of 3: Preparing docs for entity api:default/url-shortener {"timestamp":"2022-08-10T19:54:40.282Z"}
[2](http://localhost:7007/docs/default/API/url-shortener#line-2)info: Prepare step completed for entity api:default/url-shortener, stored at /tmp/backstage-ZQC3pj {"timestamp":"2022-08-10T19:54:41.380Z"}
[3](http://localhost:7007/docs/default/API/url-shortener#line-3)info: Step 2 of 3: Generating docs for entity api:default/url-shortener {"timestamp":"2022-08-10T19:54:41.380Z"}
[4](http://localhost:7007/docs/default/API/url-shortener#line-4)info: Set {"repo_url":"https://github.com/bittrance/url-shortener/tree/backstage-issue-1/","edit_uri":"https://github.com/bittrance/url-shortener/edit/backstage-issue-1/docs"}. You can disable this feature by manually setting 'repo_url' or 'edit_uri' according to the MkDocs documentation at https://www.mkdocs.org/user-guide/configuration/#repo_url {"timestamp":"2022-08-10T19:54:41.384Z"}
[5](http://localhost:7007/docs/default/API/url-shortener#line-5)error: Failed to build the docs page: Failed to generate docs from /tmp/backstage-ZQC3pj into /tmp/techdocs-tmp-l0G1Gf; caused by Error: spawn mkdocs ENOENT {"timestamp":"2022-08-10T19:54:41.411Z"}
```

With `docker exec` I can manually install `mkdocs-techdocs-core` and get a working setup.

## Steps to Reproduce

1. Run `docker-compose up` with below yaml
1. Navigate to http://localhost:7007/catalog-import
1. Import https://github.com/bittrance/url-shortener/tree/backstage-issue-1/catalog-info.yaml
2. Navigate to http://localhost:7007/docs/default/API/url-shortener
3. Observe build error

## Your Environment

I'm importing this repo as a test: https://github.com/bittrance/url-shortener/tree/backstage-issue-1

docker-compose.yaml:
```yaml
version: '3'
services:
  backstage:
    image: ghcr.io/backstage/backstage:latest
    environment:
      POSTGRES_HOST: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: verrahsecret
    ports:
      - '127.0.0.1:7007:7007'
    volumes:
      - ./app-config.production.yaml:/app/app-config.production.yaml
      - /var/run/docker.sock:/var/run/docker.sock
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: verrahsecret
```

app-config.production.yaml
```yaml
app:
  baseUrl: http://localhost:7007
backend:
  baseUrl: http://localhost:7007
  listen:
    port: 7007
    host: 0.0.0.0
  database:
    client: pg
    connection:
      host: ${POSTGRES_HOST}
      port: ${POSTGRES_PORT}
      user: ${POSTGRES_USER}
      password: ${POSTGRES_PASSWORD}
catalog:
  rules:
    - allow: [Component, System, API, Resource, Location, Domain]
  locations: []
```
