### ISSUE TITLE
Default initial build fails to fetch catalog

### ISSUE THREAD

**Issue by mefuller** [backstage/backstage#13194]
## Expected Behavior

Following, https://backstage.io/docs/getting-started/, it is expected that the template/example catalog will display at 

## Actual Behavior

Catalog doe snot display, instead `Error: Could not fetch catalog entries.`

## Steps to Reproduce

1. Create initial backstage application per https://backstage.io/docs/getting-started/ (npx @backstage/create-app; cd <name> && yarn dev)
2. Go to http://127.0.0.1:3000/
3. See error message where catalog is expected

## Context

I am aware of issues #10323 #12049 and #11987 , but none of these provided a solution for me.
My application has no modifications from the defaults.

## Your Environment

- Browser Information: Google Chrome Version 104.0.5112.81

- Output of `yarn backstage-cli info`: 

```text
yarn run v1.22.19
$ /homes/markedwardf/repos/OBJX/mxinfra/samcro/deployments/backstage/sddc/backstage-0/node_modules/.bin/backstage-cli info
OS:   Linux 5.3.0-28-generic - linux/x64
node: v16.14.2
yarn: 1.22.19
cli:  0.18.1 (installed)
backstage:  1.5.0

Dependencies:
  @backstage/app-defaults                          1.0.5
  @backstage/backend-common                        0.15.0
  @backstage/backend-plugin-api                    0.1.1
  @backstage/backend-tasks                         0.3.4
  @backstage/catalog-client                        1.0.4
  @backstage/catalog-model                         1.1.0
  @backstage/cli-common                            0.1.9
  @backstage/cli                                   0.18.1
  @backstage/config-loader                         1.1.3
  @backstage/config                                1.0.1
  @backstage/core-app-api                          1.0.5
  @backstage/core-components                       0.11.0
  @backstage/core-plugin-api                       1.0.5
  @backstage/errors                                1.1.0
  @backstage/integration-react                     1.1.3
  @backstage/integration                           1.3.0
  @backstage/plugin-api-docs                       0.8.8
  @backstage/plugin-app-backend                    0.3.35
  @backstage/plugin-auth-backend                   0.15.1
  @backstage/plugin-auth-node                      0.2.4
  @backstage/plugin-catalog-backend                1.3.1
  @backstage/plugin-catalog-common                 1.0.5
  @backstage/plugin-catalog-graph                  0.2.20
  @backstage/plugin-catalog-import                 0.8.11
  @backstage/plugin-catalog-node                   1.0.1
  @backstage/plugin-catalog-react                  1.1.3
  @backstage/plugin-catalog                        1.5.0
  @backstage/plugin-github-actions                 0.5.8
  @backstage/plugin-org                            0.5.8
  @backstage/plugin-permission-common              0.6.3
  @backstage/plugin-permission-node                0.6.4
  @backstage/plugin-permission-react               0.4.4
  @backstage/plugin-proxy-backend                  0.2.29
  @backstage/plugin-scaffolder-backend             1.5.0
  @backstage/plugin-scaffolder-common              1.1.2
  @backstage/plugin-scaffolder                     1.5.0
  @backstage/plugin-search-backend-module-pg       0.3.6
  @backstage/plugin-search-backend-node            1.0.1
  @backstage/plugin-search-backend                 1.0.1
  @backstage/plugin-search-common                  1.0.0
  @backstage/plugin-search-react                   1.0.1
  @backstage/plugin-search                         1.0.1
  @backstage/plugin-tech-radar                     0.5.15
  @backstage/plugin-techdocs-backend               1.2.1
  @backstage/plugin-techdocs-module-addons-contrib 1.0.3
  @backstage/plugin-techdocs-node                  1.3.0
  @backstage/plugin-techdocs-react                 1.0.3
  @backstage/plugin-techdocs                       1.3.1
  @backstage/plugin-user-settings                  0.4.7
  @backstage/release-manifests                     0.0.5
  @backstage/test-utils                            1.1.3
  @backstage/theme                                 0.2.16
  @backstage/types                                 1.0.0
  @backstage/version-bridge                        1.0.1
Done in 3.51s.
```

- terminal messages from `yarn dev`
```
yarn run v1.22.19
$ concurrently "yarn start" "yarn start-backend"
$ yarn workspace backend start
$ yarn workspace app start
$ backstage-cli package start
$ backstage-cli package start
[1] Build succeeded
[0] Loaded config from app-config.yaml
[0] <w> [webpack-dev-server] "hot: true" automatically applies HMR plugin, you don't have to add it manually to your webpack configuration.
[0] <i> [webpack-dev-server] Project is running at:
[0] <i> [webpack-dev-server] Loopback: http://localhost:3000/, http://127.0.0.1:3000/
[0] <i> [webpack-dev-server] Content not from webpack is served from '/homes/markedwardf/repos/OBJX/mxinfra/samcro/deployments/backstage/sddc/backstage-0/packages/app/public' directory
[0] <i> [webpack-dev-server] 404s will fallback to '/index.html'
[0] <i> [webpack-dev-middleware] wait until bundle finished: /
[0] webpack compiled successfully
[1] 2022-08-17T14:11:48.133Z backstage info Loaded config from app-config.yaml 
[1] 2022-08-17T14:11:48.146Z backstage info 1 secret found in the config which will be redacted 
[1] 2022-08-17T14:11:48.169Z backstage info Created UrlReader predicateMux{readers=azure{host=dev.azure.com,authed=false},bitbucketCloud{host=bitbucket.org,authed=false},github{host=github.com,authed=false},gitlab{host=gitlab.com,authed=false},awsS3{host=amazonaws.com,authed=false},fetch{} 
[1] 2022-08-17T14:11:48.375Z catalog info Performing database migration type=plugin
[1] 2022-08-17T14:11:48.619Z auth info Configuring "database" as KeyStore provider type=plugin
[1] 2022-08-17T14:11:48.653Z techdocs info Creating Local publisher for TechDocs type=plugin
[1] 2022-08-17T14:11:48.687Z proxy info [HPM] Proxy created: /test  -> https://example.com type=plugin
[1] 2022-08-17T14:11:48.687Z proxy info [HPM] Proxy rewrite rule created: "^/api/proxy/test/?" ~> "/" type=plugin
[1] 2022-08-17T14:11:48.688Z search info Added DefaultCatalogCollatorFactory collator factory for type software-catalog type=plugin
[1] 2022-08-17T14:11:48.688Z search info Added DefaultTechDocsCollatorFactory collator factory for type techdocs type=plugin
[1] 2022-08-17T14:11:48.689Z search info Starting all scheduled search tasks. type=plugin
[1] 2022-08-17T14:11:48.707Z app warn Can't serve static app content from /homes/markedwardf/repos/OBJX/mxinfra/samcro/deployments/backstage/sddc/backstage-0/packages/app/dist/static, directory doesn't exist type=plugin
[1] 2022-08-17T14:11:48.709Z backstage info Initializing http server 
[1] 2022-08-17T14:11:48.713Z backstage info Listening on :7007 
[1] 2022-08-17T14:11:48.723Z search info Task worker starting: search_index_software_catalog, {"version":2,"cadence":"PT10M","initialDelayDuration":"PT3S","timeoutAfterDuration":"PT15M"} type=taskManager task=search_index_software_catalog
[1] 2022-08-17T14:11:48.724Z search info Task worker starting: search_index_techdocs, {"version":2,"cadence":"PT10M","initialDelayDuration":"PT3S","timeoutAfterDuration":"PT15M"} type=taskManager task=search_index_techdocs
[1] 2022-08-17T14:11:51.726Z search info Collating documents for software-catalog via DefaultCatalogCollatorFactory type=plugin
[1] 2022-08-17T14:11:51.741Z search info Collating documents for techdocs via DefaultTechDocsCollatorFactory type=plugin
[1] 2022-08-17T14:11:51.788Z backstage info ::ffff:127.0.0.1 - - [17/Aug/2022:14:11:51 +0000] "GET /api/catalog/entities?filter=metadata.annotations.backstage.io%2Ftechdocs-ref&fields=kind,namespace,metadata.annotations,metadata.name,metadata.title,metadata.namespace,spec.type,spec.lifecycle,relations&offset=0&limit=500 HTTP/1.1" 200 2 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)" type=incomingRequest
[1] 2022-08-17T14:11:51.810Z search info Collating documents for techdocs succeeded type=plugin
[1] 2022-08-17T14:11:51.822Z backstage info ::ffff:127.0.0.1 - - [17/Aug/2022:14:11:51 +0000] "GET /api/catalog/entities?offset=0&limit=500 HTTP/1.1" 200 - "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)" type=incomingRequest
[1] 2022-08-17T14:11:51.843Z search info Collating documents for software-catalog succeeded type=plugin
```

**Comment by awanlin** [comment]
@mefuller, I've just tried to reproduce this but it works for me - fresh run of `npx @backstage/create-app` using the name `demo-app`, then `cd demo-app`, and finally `yarn dev`. 

Can you post any errors/messages in your browser console? Maybe there might be something helpful in there

**Comment by mefuller** [comment]
@awanlin I'm not using/don't have a browser console. I posted all output messages from my terminal in the original report.
For additional context, I'm developing on a remote machine and port-forwarding in VS Code to view the site locally, but I don't know that this is necessarily the issue as I am experiencing the same problem when I make a minimal k8s deployment as well.

I'll try some other approaches to see if I can better isolate the problematic elements.

**Comment by benjdlambert** [comment]
This looks like is some CORS error or something if you're port forwarding to a remote host. Make sure that the `app-config.yaml` `app.baseUrl` and `backend.baseUrl` are set to the URL that you would type in the address bar in your browser. Probably something like the port forwarded domain or whatnot.

**Comment by mefuller** [comment]
Closing - I went through a default setup in a VM and there was no issue, so whatever the problem is, it hasn't been described in a relevant way here
Thanks for the input @benjdlambert and @awanlin

**Comment by andrealmar** [comment]
@benjdlambert I have my `app-config.yaml` set to: 

```yaml
baseUrl: http://localhost:7007
  listen:
    port: 7007
    # Uncomment the following host directive to bind to all IPv4 interfaces and
    # not just the baseUrl hostname.
    # host: 0.0.0.0
  csp:
    connect-src: ["'self'", 'http:', 'https:']
    # Content-Security-Policy directives follow the Helmet format: https://helmetjs.github.io/#reference
    # Default Helmet Content-Security-Policy values can be removed by setting the key to false
  cors:
    origin: http://localhost:3000
    methods: [GET, HEAD, PATCH, POST, PUT, DELETE]
    credentials: true
```

then in my `app-config.production.yaml` I have:

```yaml
baseUrl: https://backstage.i.mydomain.com:7007
  listen:
    port: 7007
    # The following host directive binds to all IPv4 interfaces when its value
    # is "0.0.0.0". This is the most permissive setting. The right value depends
    # on your specific deployment. If you remove the host line entirely, the
    # backend will bind on the interface that corresponds to the backend.baseUrl
    # hostname.
    host: 0.0.0.0
  cors:
    origin: https://backstage.i.mydomain.com
    methods: [GET, HEAD, PATCH, POST, PUT, DELETE]
    credentials: true
```

But I'm still seeing CORS errors and the `Error: Could not fetch catalog entries` message. 

Any ideas?

Thank you

**Comment by p-kamath** [comment]
@andrealmar - I faced the same issue, but in my case the issue was because of misconfiguration in the yaml (typo in the url). Also, I would try with app-config-production.yaml as follows where DOMAIN_URL is the URL that you need
`app:
  baseUrl: ${DOMAIN_URL}

backend:
  baseUrl: ${DOMAIN_URL}
  listen:
    port: 7007
    host: 0.0.0.0
  cors:
    origin: ${DOMAIN_URL}`

**Comment by MekkyMayata** [comment]
@andrealmar were you able to get it resolved? I'm also running into a similar issue. somehow, requests for the backstage frontend (ec2) are still getting routed to localhost on the browser.
```
app:
  # Should be the same as backend.baseUrl when using the `app-backend` plugin.
  baseUrl: https://url

backend:
  # Note that the baseUrl should be the URL that the browser and other clients
  # should use when communicating with the backend, i.e. it needs to be
  # reachable not just from within the backend host, but from all of your
  # callers. When its value is "http://localhost:7007", it's strictly private
  # and can't be reached by others.
  baseUrl: https://[url]
  listen:
    port: 443
    # The following host directive binds to all IPv4 interfaces when its value
    # is "0.0.0.0". This is the most permissive setting. The right value depends
    # on your specific deployment. If you remove the host line entirely, the
    # backend will bind on the interface that corresponds to the backend.baseUrl
    # hostname.
    host: 0.0.0.0
  cors:
    origin: https://[url]
    #methods: [GET, HEAD, PATCH, POST, PUT, DELETE]
    #credentials: true


  # config options: https://node-postgres.com/api/client
  database:
    client: pg
    connection:
      host: ${POSTGRES_HOST}
      port: ${POSTGRES_PORT}
      user: ${POSTGRES_USER}
      password: ${POSTGRES_PASSWORD}
      # https://node-postgres.com/features/ssl
      # you can set the sslmode configuration option via the `PGSSLMODE` environment variable
      # see https://www.postgresql.org/docs/current/libpq-ssl.html Table 33.1. SSL Mode Descriptions (e.g. require)
      # ssl:
      #   ca: # if you have a CA file and want to verify it you can uncomment this section
      #     $file: <file-path>/ca/server.crt

catalog:
  # Overrides the default list locations from app-config.yaml as these contain example data.
  # See https://backstage.io/docs/features/software-catalog/software-catalog-overview#adding-components-to-the-catalog for more details
  # on how to get entities into the catalog.
  locations: []
```

<img width="1391" alt="Screenshot 2022-09-28 at 00 19 41" src="https://user-images.githubusercontent.com/54307445/192694070-3c54608d-4d8a-4848-bf2b-bd2ffd1cc3b5.png">

**Comment by p-kamath** [comment]
> ://url

The app-config.production.yaml must have valid backend URL. Did you try to replace the URL variables with fixed urls and check if that is working?
Also, if I am not wrong, the order of --config yaml in the final command has a significance. The production yaml should appear in the end

**Comment by andrealmar** [comment]
@MekkyMayata here is how I configured my `app-config.yaml`: 

```yaml
app:
  title: My Backstage
  baseUrl: https://mydomain.com
backend:
  baseUrl: "http://localhost:7007"
  listen:
    port: 7007
    # Uncomment the following host directive to bind to all IPv4 interfaces and
    # not just the baseUrl hostname.
    host: 0.0.0.0
cors:
    origin: https://mydomain.com
    methods: [GET, HEAD, PATCH, POST, PUT, DELETE]
    credentials: true
```

and here is my `app-config.production.yaml`:

```yaml
app:
  baseUrl: https://mydomain.com
backend:
  baseUrl: https://mydomain.com
  listen:
    port: 7007
    host: 0.0.0.0
  cors:
    origin: https://mydomain.com
    methods: [GET, HEAD, PATCH, POST, PUT, DELETE]
    credentials: true
```

after I did the above things started to work for me.
