### ISSUE TITLE
[Plugin] Toolbox Plugin (Tools Catalog)

### ISSUE THREAD

**Issue by gabriel-dantas98** [backstage/backstage#13227]
## Summary

A page that lists the tools used in engineering so that all engineers can access them.

## Project website (if applicable)

We developed this plugin in QuintoAndar and received a lot of feedback that would be useful for other companies.

![img](https://miro.medium.com/max/1400/1*_nKZ1RQ-2FcfSytVAY0YoA.gif)

## Context

Basically, it's a frontend plugin that reads a data structure with tool links separated by environment and subject.

```yaml
categories:
  - name: monitoring
    tools:
      - name: grafana
        description: >-
          Grafana is the open source analytics & monitoring solution for every
          database.
        environments:
          - name: development
            url: 'https://grafana.development.company.com.br'
          - name: production
            url: 'https://grafana.company.com.br'

      - name: prometheus
        description: 'Prometheus is a free software application used for event monitoring and alerting. It records real-time metrics in a time series database (allowing for high dimensionality) built using a HTTP pull model, with flexible queries and real-time alerting.'
        environments:
          - name: development
            url: 'https://prometheus.development.company.com.br'
          - name: production
            url: 'https://prometheus.company.com.br'

      - name: kibana
        description: >-
          Kibana is an free and open frontend application that sits on top of
          the Elastic Stack, providing search and data visualization
          capabilities for data indexed in Elasticsearch.
        environments:
          - name: development
            url: 'https://kibana.development.company.com.br'
          - name: production
            url: 'https://kibana.company.com.br'

  - name: CI/CD
    tools:
      - name: drone-ci
        description: >-
          Drone is a Continuous Delivery system built on container technology.
          Drone uses a simple YAML configuration file, a superset of
          docker-compose, to define and execute Pipelines inside Docker
          containers.
        environments:
          - name: production
            url: 'https://drone.company.com.br'

      - name: argo-CD
        description: >-
          Argo CD is a declarative, GitOps continuous delivery tool for
          Kubernetes.
        environments:
          - name: development
            url: 'https://argocd.development.company.com.br'
          - name: staging
            url: 'https://argocd.development.company.com.br'
          - name: production
            url: 'https://argocd.production.company.com.br'

      - name: argo-rollouts
        description: >-
          Argo Rollouts is a Kubernetes controller and set of CRDs which 
          provide advanced deployment capabilities such as blue-green, canary, 
          canary analysis, experimentation, and progressive delivery features 
          to Kubernetes.
        environments:
          - name: development
            url: 'https://rollouts.development.company.com.br'
 
  - name: data
    tools:
      - name: airflow
        description: >-
          Airflow is a platform created by the community to 
          programmatically author, schedule and monitor workflows.
        environments:
          - name: production
            url: 'https://airflow.company.com.br/'
          - name: development
            url: 'https://airflow.development.company.com.br/'
```
