### ISSUE TITLE
Missing support for LDAP searchReference results

### ISSUE THREAD

**Issue by debojitkakoti** [backstage/backstage#13280]
## Expected Behavior

Return groups.
Same search filter works on ldapsearch.

## Actual Behavior

 ``catalog warn Received unsupported search referral type=plugin target=ldaps://ld.abc.net:636``

## Steps to Reproduce

ldap config I used
```
ldap:
  providers:
    - target: ldaps://ld.abc.net:636
      bind:
        dn: CN=abc service account,OU=system,OU=abc,DC=abc,DC=net
        secret: abcdef
      users:
        dn: DC=abc,DC=net
        options:
          filter: (objectClass=user)
        map:
          description: l
      groups:
        dn: DC=abc,DC=net
        options:
          filter: (&(objectClass=group)(!(groupType=email)))
          paged: false
        map:
          # The name of the attribute that holds the relative
          # distinguished name of each entry. This value is copied into a
          # well known annotation to be able to query by it later.
          rdn: cn
          # The name of the attribute that shall be used for the value of
          # the metadata.name field of the entity.
          name: cn
          # The name of the attribute that shall be used for the value of
          # the metadata.description field of the entity.
          description: description
          # The name of the attribute that shall be used for the value of
          # the spec.type field of the entity.
          type: groupType
          # The name of the attribute that shall be used for the value of
          # the spec.profile.displayName field of the entity.
          displayName: cn
          # The name of the attribute that shall be used for the value of
          # the spec.profile.email field of the entity.
          email: <nothing, left out>
          # The name of the attribute that shall be used for the value of
          # the spec.profile.picture field of the entity.
          picture: <nothing, left out>
          # The name of the attribute that shall be used for the values of
          # the spec.parent field of the entity.
          memberOf: memberOf
          # The name of the attribute that shall be used for the values of
          # the spec.children field of the entity.
          members: member
```

## Your Environment

- Browser Information: 

- Output of `yarn backstage-cli info`: 

```text
yarn run v1.22.18
$ /Users/debojit/Code/backstage/node_modules/.bin/backstage-cli info
OS:   Darwin 21.6.0 - darwin/x64
node: v14.17.0
yarn: 1.22.18
cli:  0.18.0 (installed)

Dependencies:
  @backstage/app-defaults                                   1.0.4
  @backstage/backend-common                                 0.14.1, 0.15.0
  @backstage/backend-plugin-api                             0.1.0, 0.1.1
  @backstage/backend-tasks                                  0.3.3, 0.3.4
  @backstage/catalog-client                                 1.0.4
  @backstage/catalog-model                                  1.1.0
  @backstage/cli-common                                     0.1.9
  @backstage/cli                                            0.18.0
  @backstage/config-loader                                  1.1.3
  @backstage/config                                         1.0.1
  @backstage/core-app-api                                   1.0.4
  @backstage/core-components                                0.10.0
  @backstage/core-plugin-api                                1.0.4
  @backstage/errors                                         1.1.0
  @backstage/integration-react                              1.1.2
  @backstage/integration                                    1.2.2, 1.3.0
  @backstage/plugin-api-docs                                0.8.7
  @backstage/plugin-app-backend                             0.3.34
  @backstage/plugin-auth-backend                            0.15.0
  @backstage/plugin-auth-node                               0.2.3, 0.2.4
  @backstage/plugin-bitbucket-cloud-common                  0.1.1
  @backstage/plugin-catalog-backend-module-bitbucket-server 0.1.0
  @backstage/plugin-catalog-backend-module-bitbucket        0.2.1
  @backstage/plugin-catalog-backend-module-gerrit           0.1.2
  @backstage/plugin-catalog-backend-module-ldap             0.5.2
  @backstage/plugin-catalog-backend                         1.3.0, 1.3.1
  @backstage/plugin-catalog-common                          1.0.4, 1.0.5
  @backstage/plugin-catalog-graph                           0.2.19
  @backstage/plugin-catalog-import                          0.8.10
  @backstage/plugin-catalog-node                            1.0.0, 1.0.1
  @backstage/plugin-catalog-react                           1.1.2
  @backstage/plugin-catalog                                 1.4.0
  @backstage/plugin-github-actions                          0.5.7
  @backstage/plugin-org                                     0.5.7
  @backstage/plugin-permission-common                       0.6.3
  @backstage/plugin-permission-node                         0.6.3, 0.6.4
  @backstage/plugin-permission-react                        0.4.3
  @backstage/plugin-proxy-backend                           0.2.28
  @backstage/plugin-scaffolder-backend                      1.4.0
  @backstage/plugin-scaffolder-common                       1.1.2
  @backstage/plugin-scaffolder                              1.4.0
  @backstage/plugin-search-backend-module-pg                0.3.5
  @backstage/plugin-search-backend-node                     1.0.0
  @backstage/plugin-search-backend                          1.0.0
  @backstage/plugin-search-common                           1.0.0
  @backstage/plugin-search-react                            1.0.0
  @backstage/plugin-search                                  1.0.0
  @backstage/plugin-techdocs-backend                        1.2.0
  @backstage/plugin-techdocs-module-addons-contrib          1.0.2
  @backstage/plugin-techdocs-node                           1.2.0
  @backstage/plugin-techdocs-react                          1.0.2
  @backstage/plugin-techdocs                                1.3.0
  @backstage/plugin-user-settings                           0.4.6
  @backstage/release-manifests                              0.0.5
  @backstage/test-utils                                     1.1.2
  @backstage/theme                                          0.2.16
  @backstage/types                                          1.0.0
  @backstage/version-bridge                                 1.0.1
```
