### ISSUE TITLE
ms-graph plugin: expand not working on MicrosoftGraphOrgEntityProvider

### ISSUE THREAD

**Issue by gtestault** [backstage/backstage#13298]
## Expected Behavior

Documented configuration features userExpand and groupExpand should expand the requested properties

```yaml
user:
  # Optional parameter to include the expanded resource or collection referenced
  # by a single relationship (navigation property) in your results.
  # Only one relationship can be expanded in a single request.
  # See https://docs.microsoft.com/en-us/graph/query-parameters#expand-parameter
  # Can be combined with userGroupMember[...] instead of userFilter.
  expand: manager
```

## Actual Behavior

Does not work. New MicrosoftGraphOrgEntityProvider doesn't pass configuration in main ingestion loop:
```javascript
async read(options?: { logger?: Logger }) {
    if (!this.connection) {
      throw new Error('Not initialized');
    }

    const logger = options?.logger ?? this.options.logger;
    const provider = this.options.provider;
    const { markReadComplete } = trackProgress(logger);
    const client = MicrosoftGraphClient.create(this.options.provider);
    const { users, groups } = await readMicrosoftGraphOrg(
      client,
      provider.tenantId,
      {
        userFilter: provider.userFilter,
        userGroupMemberFilter: provider.userGroupMemberFilter,
        userGroupMemberSearch: provider.userGroupMemberSearch,
        groupFilter: provider.groupFilter,
        groupSearch: provider.groupSearch,
        groupSelect: provider.groupSelect,
        queryMode: provider.queryMode,
        groupTransformer: this.options.groupTransformer,
        userTransformer: this.options.userTransformer,
        organizationTransformer: this.options.organizationTransformer,
        logger: logger,
      },
    );
```

## Steps to Reproduce

1. Set userExpand configuration to "memberOf"
2. Use new ingestor MicrosoftGraphOrgEntityProvider
3. New ingestor does not expand property (view in debugger or in transformer)

## Context

I am trying to add custom information to user entities via the userExpand configuration parameter

## Your Environment

Latest Backstage, Latest plugin version
