### ISSUE TITLE
Allow multiple owners for components

### ISSUE THREAD

**Issue by JordiPolo** [backstage/backstage#1329]
Currently a `kind: Component` needs to specify an `owner` inside `spec`. But this information may depend of who you ask! 
Is the owner the lead engineer, the team, the guy paying , the manager.... Depends!

So I propose that:
```yaml
spec:
  owner: team@company.com
```

Becomes:
```yaml
spec:
  owners: 
    team: team@company.com
```

Which now allows:
```yaml
spec:
  owners: 
    team: team@company.com
    manager: xx
    architecture: xx
    documentation: yyy
    quality: zzzz
    sales: yyy
    consumer_service: ddd
```

The change would not limit the owner keys to the above, it is just an example.

**Comment by Rugvip** [comment]
Good feedback! 👍 

For now we've just gone with a simple dumb string as the owner, as we haven't really tied it to any kind of identities yet, and we still need to figure out exactly how we want to do that. I do think we're going to have to extend the schema to allow for different types of owners later on.

In the internal version we do have a rule that some team should be **the** owner of a service, and it might be a model that we would want to encourage through the schema, but not enforce.

**Comment by Fox32** [comment]
We are also interested into having multiple owners. Here is an inspiration from one of the Demo videos:

![image](https://user-images.githubusercontent.com/648527/101139048-3ff07800-3611-11eb-934d-fd628f8edf7f.png)

Now that the relationships and basic ownership is in place, we should have a look at this again. I wonder how such a feature can be implemented, some ideas:

### Having multiple distinct owner fields or a complex structure in the entity as Jordi suggested:

```yaml
spec:
  owners: 
    technical: team@company.com
    product: xx
    ...
```

or

```yaml
spec:
  technicalOwner: team@company.com
  productOwner: xx
```

In that case we have multiple options for storing it internally:
* Having a new `technicalOwnerOf` relationship and some more relationships following the same pattern. This might get out of hand fast. But would be extensible by following [Adding a new relation](https://backstage.io/docs/features/software-catalog/extending-the-model#adding-a-new-relation-type). One advantage is, that this might be introduced as a non breaking change as the ownership relationship isn't polluted with additional relationships. Code that can't handle other ownership relationships just ignores them.
* Another option is to use the [metadata on relationships](https://backstage.io/docs/features/software-catalog/descriptor-format#common-to-all-kinds-relations). In the `metadata` of an `ownerOf` relationship could be an additional field like `responsibility` that marks what kind of an owner the user/group is. Consumers therefore has to filter which `responsibility` they want to display. This can be an advantage and a disadvantage: Existing code will just display the additional ownerships, but might not make clear which responsibility they have.

### Responsibilities as an attribute of the the owning group/users:

Instead of adding the additional responsibilities to the components, we could also add them to groups. So it can be derived from the group which ownerships applies. However this might not be desired if the responsibilities differ between different components owned by the same group.

Here are also multiple implementations possible:
* Users have an explicit role attribute. We filter the members of the group by their role and can therefor extract the additional ownerships. This more or less expects that each team has one product owner and so on.
* Having different memberOf relationships OR having the metadata as in the solution above.
I think this is quite limiting.



We would be interested to help with the implementation. If we have a goal we can start with an implementation at the beginning of the year.

**Comment by freben** [comment]
For what it's worth, internally we have a variant of the second solution above. Groups have a number of extra attributes (in the actual backing systems - not just Backstage) - who's the `productManager`, `designOwner`, and `techOwner`. These map to a user, and are completely detached from the concept of being a member or not of the group. This is the data that we display in the screenshot.

**Comment by freben** [comment]
I think that the input model does not necessarily have to map 1:1 to the output model, by the way. Even if we used our source data, we could still emit a `hasTechOwner` relation on each Component that is owned by the group with that `techOwner` attribute, if that was what the end result model turned out to be.

**Comment by Fox32** [comment]
Yeah, you are right. The models don't to match, we can rewrite that in a processor. So it's kind of a question about the internal model:
* Having separate relations `techOwnerOf`, `productOwnerOf` or
* Adding a responsibility to the metadata of the existing `ownerOf` relationship.

**Comment by freben** [comment]
Yep. We're more and more starting to think in terms of the relations first. And then, the `spec` just "follows along" and is one of many ways for people to express things that ultimately end up being relations.

**Comment by Fox32** [comment]
I thought a little bit about this. Having a ownerOf relationship with an additional metadata "responsibility" (technical, product, ...) has the advantage that all code that is working with the ownerOf relationship will continue to work. One example would be the ownership filter of the catalog. If every adopter implements their own relationship it would be hard to still filter by ownership of the user as every instance might have different relations for that. That could be solved if `techOwnerOf` would be in addition to `ownerOf` instead of replacing it.

**Comment by JordiPolo** [comment]
If it is of any use, as we wait for the format here to stabilize we are adding a few sections to metadata and we find it extensible and useful to have `role`. For instance:
```yaml
  people:
    - role: "engineering manager"
      email: xxxx@mdsol.com
    - role: architect
      email: xxxx@mdsol.com
```
or in a different section:
```yaml
  channels:
    - url: https://xxxx.slack.com/messages/....
      automated_messaging: false
      role: slack
    - role: email
      automated_messaging: true
      url: yyy-alerts@xxx.com
```

This has been working pretty well, we have 120 services now described by this and no issues. So I'd encourage here also to go for something like that
```yaml
owner: x
scope: y
```

Scope or role or responsibility. Not sure. But something which values can be extended in the future.

**Comment by freben** [comment]
@JordiPolo If we formalise this, I think we'd probably want to make the owner to be a [ref](https://backstage.io/docs/features/software-catalog/references) to a User rather than an email. But yea, to be determined.

**Comment by JordiPolo** [comment]
Totally makes sense, our format out there predates the definition of User. 
Just wanted to make a case for a format that allows to use values to extend it for future usage. 

We have not adopted User because we have tons of people working on multiple projects and we do not know where to put their User, in one project, in all, in a different repo just forthis? etc

**Comment by Fox32** [comment]
Would be still interested in this, we want two owners, a technical and a product one. We could already archive this by extending the model on our end, but I wonder if this is something that is part of the core Backstage experience.

@Rugvip @benjdlambert @freben Is this something we should reopen?

**Comment by nicorikken** [comment]
I came here via a question I put on Discord. We're looking into using Backstage, and having a Product Owner listed per product is important to us, to have a main point of contacts. A lot of project/repositories are ownership of larger groups of people, but it can be unclear who to contact. Of course we could hack it by adding `metadata` properties like labels or annotations, but making it part of the `spec` is preferred.

I like the idea of defining a single owner to prevent having teams passing on responsibility: more owners == no owner, so I wouldn't touch that.

So that leads me to think about the idea of @JordiPolo where an addition list of related Groups or Users can be linked to a Component. Just to get the discussion going, something like:

```yaml
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: artist-web
  description: The place to be, for great artists
spec:
  type: website
  lifecycle: production
  owner: artist-relations-team
  system: artist-engagement-portal
  organization:  # could be a different term
    - contact: group:the-ops-team
      role: operational-support
    - contact: group:artists-solution-architects
      role: architect
    - contact: user:john-doe
      role: product-owner
```

I'm quite new to the standard, so feel free to point out errors or inconsistencies. And please provide feedback.
