### ISSUE TITLE
Unifi Azure Devops Configuration

### ISSUE THREAD

**Issue by afscrome** [backstage/backstage#13331]
Currently there are two separate configuration sections for Azure Devops.  It be nice if these were consolidated into one.

```yaml
# `catalog-backend-module-azure`
integrations:
  azure:
    - host: dev.azure.com
      token: ${AZURE_TOKEN}
# `azure-devops`, `azure-devops-common` & `azure-devops-backend`
azureDevOps:
  host: dev.azure.com
  token: ${AZURE_TOKEN}
  organization: ${AZURE_DEVOPS_ORGANISATION}
```

## Feature Suggestion

These two bits of configuration have a lot of overlap so it would simplify things if the config could be unified.

## Possible Implementation

Sharing hte configuration is fairly easy with the exception that `integration.azure` supports multiple hosts / orgs, whilst `azuredevops` section only supports a single organisation.  I suspect the bulk of the effort to unify this config will come from reworking these plugins to support multiple hosts / organsiations.
