### ISSUE TITLE
Provide sourcePath for publish:gitlab:merge-request action

### ISSUE THREAD

**Issue by gavlyukovskiy** [backstage/backstage#13359]
## Feature Suggestion

Similar to `publish:github:pull-request` it would be nice to support ability to make MR to Gitlab from subfolder (`sourcePath`) of rendered template.

## Possible Implementation

Add parameter `sourcePath` for `gitlabMergeRequest.ts`, if not specified fallback to `targetPath` (currently works as both `sourcePath` and `targetPath`), change `serializeDirectoryContents` to use that.

I'd be happy to provide a PR for this functionality.

## Context

Main use-case is that on top of service code we also provide files intended for other repositories and with current approach it's a bit complicated to do that. In out case we are rendering template with similar structure:
```
|- src
|- external
|-- repo1
|---- some_file1
|-- repo2
|---- some_file2
```
I want `src` to be in the target repository using `publish:gitlab`, then `some_file1` to be created as MR to `repo1` and `some_file2` to be created as MR to `repo2`. Today I can achieve that with additional `fs:rename`/`fs:remove` actions:
```yaml
    - id: repo1_prepare
      name: Prepare files for repo1
      action: fs:rename
      input:
        files:
          - from: external/repo1/some_file1
            to: .

    - id: repo1_mr
      name: Create MR to repo1
      action: publish:gitlab:merge-request
      input:
        title: some_file1 for ${{ parameters.service_name }}
        removeSourceBranch: true
        branchName: ${{ parameters.service_name }}
        targetPath: some_file1
        repoUrl: gitlab.com?repo=repo1&owner=project

    - id: repo1_cleanup
      name: Cleanup repo1
      action: fs:delete
      input:
        files:
          - some_file1

    - id: repo2_prepare
      name: Prepare files for repo2
      action: fs:rename
      input:
        files:
          - from: external/repo2/some_file2
            to: .

    - id: repo2_mr
      name: Create MR to repo2
      action: publish:gitlab:merge-request
      input:
        title: some_file2 for ${{ parameters.service_name }}
        removeSourceBranch: true
        branchName: ${{ parameters.service_name }}
        targetPath: some_file2
        repoUrl: gitlab.com?repo=repo2&owner=project

    - id: repo2_cleanup
      name: Cleanup repo2
      action: fs:delete
      input:
        files:
          - some_file2

    - id: publish
      name: Publish
      action: publish:gitlab
      input:
        ...
```
Ideally I would like to have something like:
```yaml
    - id: repo1_mr
      name: Create MR to repo1
      action: publish:gitlab:merge-request
      input:
        title: some_file1 for ${{ parameters.service_name }}
        removeSourceBranch: true
        branchName: ${{ parameters.service_name }}
        sourcePath: external/repo1
        targetPath: .
        repoUrl: gitlab.com?repo=repo1&owner=project

    - id: repo2_mr
      name: Create MR to repo2
      action: publish:gitlab:merge-request
      input:
        title: some_file2 for ${{ parameters.service_name }}
        removeSourceBranch: true
        branchName: ${{ parameters.service_name }}
        sourcePath: external/repo2
        targetPath: .
        repoUrl: gitlab.com?repo=repo2&owner=project

    - id: external_cleanup
      name: Cleanup external files
      action: fs:delete
      input:
        files:
          - external

    - id: publish
      name: Publish
      action: publish:gitlab
      input:
        ...
```
