### ISSUE TITLE
[TECHDOCS] Failure at step "Generate docs site"

### ISSUE THREAD

**Issue by padupe** [backstage/backstage#13433]
## Expected Behavior

Documentation should be generated through the Github CI process.

## Actual Behavior

Error occurs in step "Generate docs site"

## Steps to Reproduce

[Video](https://user-images.githubusercontent.com/72894267/187554280-34f5c86a-e14b-4dcf-9586-c935c7cac1bd.webm)

1. Generate `techdocs.yaml` at `.github/workflows`
2. Change applied at `/docs` directory or `mkdocs.yaml`
3. Workflow run
4. At step **Generate docs site** ERROR

## Context

- I'm not able to use the workflow to generate the documentation.
- Project Structure:
```
.github
 └─── workflows
           └───techdocs.yaml 
docker
 └─── nodejs
 └─── python
docs
  └───README.md
packages
  └───app
  └───backend
plugins
app-config.yaml
catalog-info.yaml
mkdocs.yaml
package.json
```
- `.github/workflows/techdocs.yaml`
```yaml
name: Publish TechDocs Site

on:
  push:
    branches:
      - staging
    paths:
      - "docs/**"
      - "mkdocs.yaml"

jobs:
  publish-techdocs-site:
    runs-on: [staging]
    env:
      TECHDOCS_S3_BUCKET_NAME: ${{ secrets.GLOBALS_DX_TECHDOCS_STG }}
      AWS_ACCESS_KEY_ID: ${{ secrets.GLOBALS_DX_TECHDOCS_STG_AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.GLOBALS_DX_TECHDOCS_STG_AWS_SECRET_ACCESS_KEY }}
      ENTITY_NAMESPACE: 'default'
      ENTITY_KIND: 'Component'
      ENTITY_NAME: 'portaldx'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
      - uses: actions/setup-python@v3
        
      - name: Install gyp
        run: pip3 install git+https://chromium.googlesource.com/external/gyp

      - name: Install mkdocs and mkdocs plugins
        run: pip3 install mkdocs-techdocs-core==1.*
        
      - name: Generate docs site
        run: npx @techdocs/cli generate --no-docker --source-dir . --output-dir ./site/techdocs

      - name: Publish docs site
        run: techdocs-cli publish --publisher-type awsS3 --storage-name $TECHDOCS_S3_BUCKET_NAME --entity $ENTITY_NAMESPACE/$ENTITY_KIND/$ENTITY_NAME
```
- Error message at step **Generate docs site**:
```
In file included from ../src/binding.cc:1:
/usr/include/nodejs/src/node.h:573:43: warning: cast between incompatible function types from ‘void (*)(Nan::ADDON_REGISTER_FUNCTION_ARGS_TYPE)’ {aka ‘void (*)(v8::Local<v8::Object>)’} to ‘node::addon_register_func’ {aka ‘void (*)(v8::Local<v8::Object>, v8::Local<v8::Value>, void*)’} [-Wcast-function-type]
  573 |       (node::addon_register_func) (regfunc),                          \
      |                                           ^
/usr/include/nodejs/src/node.h:607:3: note: in expansion of macro ‘NODE_MODULE_X’
  607 |   NODE_MODULE_X(modname, regfunc, NULL, 0)  // NOLINT (readability/null_usage)
      |   ^~~~~~~~~~~~~
../src/binding.cc:[15](https://github.com/madeiramadeirabr/portaldx/runs/8102664170?check_suite_focus=true#step:8:15)2:1: note: in expansion of macro ‘NODE_MODULE’
  152 | NODE_MODULE(cpufeatures, init)
      | ^~~~~~~~~~~
In file included from /usr/include/nodejs/src/node.h:63,
                 from ../src/binding.cc:1:
/usr/include/nodejs/deps/v8/include/v8.h: In instantiation of ‘void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::WeakCallbackType) [with P = node::ObjectWrap; T = v8::Object; typename v8::WeakCallbackInfo<P>::Callback = void (*)(const v8::WeakCallbackInfo<node::ObjectWrap>&)]’:
/usr/include/nodejs/src/node_object_wrap.h:84:78:   required from here
/usr/include/nodejs/deps/v8/include/v8.h:9502:[16](https://github.com/madeiramadeirabr/portaldx/runs/8102664170?check_suite_focus=true#step:8:16): warning: cast between incompatible function types from ‘v8::WeakCallbackInfo<node::ObjectWrap>::Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<node::ObjectWrap>&)’} to ‘Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<void>&)’} [-Wcast-function-type]
 9502 |                reinterpret_cast<Callback>(callback), type);
      |                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/nodejs/deps/v8/include/v8.h: In instantiation of ‘void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::WeakCallbackType) [with P = Nan::ObjectWrap; T = v8::Object; typename v8::WeakCallbackInfo<P>::Callback = void (*)(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)]’:
../../nan/nan_object_wrap.h:65:61:   required from here
/usr/include/nodejs/deps/v8/include/v8.h:9502:16: warning: cast between incompatible function types from ‘v8::WeakCallbackInfo<Nan::ObjectWrap>::Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)’} to ‘Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<void>&)’} [-Wcast-function-type]
In file included from /usr/include/nodejs/src/node.h:63,
                 from ../src/binding.cc:13:
/usr/include/nodejs/deps/v8/include/v8.h: In instantiation of ‘void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::WeakCallbackType) [with P = node::ObjectWrap; T = v8::Object; typename v8::WeakCallbackInfo<P>::Callback = void (*)(const v8::WeakCallbackInfo<node::ObjectWrap>&)]’:
/usr/include/nodejs/src/node_object_wrap.h:84:78:   required from here
/usr/include/nodejs/deps/v8/include/v8.h:9502:16: warning: cast between incompatible function types from ‘v8::WeakCallbackInfo<node::ObjectWrap>::Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<node::ObjectWrap>&)’} to ‘Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<void>&)’} [-Wcast-function-type]
 9502 |                reinterpret_cast<Callback>(callback), type);
      |                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/nodejs/deps/v8/include/v8.h: In instantiation of ‘void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::WeakCallbackType) [with P = Nan::ObjectWrap; T = v8::Object; typename v8::WeakCallbackInfo<P>::Callback = void (*)(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)]’:
../../../../../nan/nan_object_wrap.h:65:61:   required from here
/usr/include/nodejs/deps/v8/include/v8.h:9502:16: warning: cast between incompatible function types from ‘v8::WeakCallbackInfo<Nan::ObjectWrap>::Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)’} to ‘Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<void>&)’} [-Wcast-function-type]
Unexpected token .
Error: Process completed with exit code 1.
```

## Environment Runner
-  ubuntu-latest
