### ISSUE TITLE
Kind:API cant use apiProvidedBy to attach to components

### ISSUE THREAD

**Issue by unixunion** [backstage/backstage#13535]
## Expected Behavior

The component should render in the graph view with a link to the API, via "providesApi/apiProvidedBy", when the API definition uses spec.apiProvidedBy to "back-ref" the component. ( without the component listing the API in spec.providesApi )

catalog view of the component / API also do not who it as being linked. 

## Actual Behavior

API are not linked by relationship in the graph view, nor in the component or API views. 

## Steps to Reproduce

Create a component, and a API, then link the API to the component in the API spec using apiProvidedBy field. 

```yaml
---
apiVersion: "backstage.io/v1alpha1"
kind: "Domain"
metadata:
  name: domainA
  description: a domain
  tags:
  - "domain"
spec:
  owner: groupA
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: groupA
  description: a test group
spec:
  type: team
  profile:
    displayName: groupA
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: systemA
  description: Some system
  tags:
    - system
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  owner: groupA
  domain: domainA
---
apiVersion: "backstage.io/v1alpha1"
kind: "Component"
metadata:
  name: componentA
  description: a component
  tags:
  - springboot
spec:
  owner: groupA
  lifecycle: "production"
  partOf: "domain:domainA"
  providesApis:
  - "something"
  # - componentA-api # uncomment and it works
  system: systemA
  dependsOn: []
  consumesApis: []
  type: "service"
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: componentA-api
  description: the API
spec:
  system: systemA
  type: openapi
  lifecycle: production
  owner: groupA
  apiProvidedBy: component:componentA # this does not work
  definition: |
    some thing here
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  system: systemA
  name: my-db
  description: some db
  tags:
    - mysql
spec:
  type: database
  lifecycle: production
  owner: groupA
  dependencyOf: component:systemA
````

## Context

API kinds are not linked to their components when done from the API perspective. 

## Your Environment

running locally with yarn dev stack

```text
OS:   Darwin 21.6.0 - darwin/x64
node: v16.16.0
yarn: 1.22.19
cli:  0.18.1 (installed)
backstage:  1.5.0

Dependencies:
  @backstage/app-defaults                            1.0.5
  @backstage/backend-common                          0.15.0
  @backstage/backend-plugin-api                      0.1.1
  @backstage/backend-tasks                           0.3.4
  @backstage/catalog-client                          1.0.4
  @backstage/catalog-model                           1.1.0
  @backstage/cli-common                              0.1.9
  @backstage/cli                                     0.18.1
  @backstage/config-loader                           1.1.3
  @backstage/config                                  1.0.1
  @backstage/core-app-api                            1.0.5
  @backstage/core-components                         0.11.0
  @backstage/core-plugin-api                         1.0.5
  @backstage/errors                                  1.1.0
  @backstage/integration-react                       1.1.3
  @backstage/integration                             1.3.0
  @backstage/plugin-api-docs                         0.8.8
  @backstage/plugin-app-backend                      0.3.35
  @backstage/plugin-auth-backend                     0.15.1
  @backstage/plugin-auth-node                        0.2.4
  @backstage/plugin-bitbucket-cloud-common           0.1.2
  @backstage/plugin-catalog-backend-module-bitbucket 0.2.2
  @backstage/plugin-catalog-backend                  1.3.1
  @backstage/plugin-catalog-common                   1.0.5
  @backstage/plugin-catalog-graph                    0.2.20
  @backstage/plugin-catalog-import                   0.8.11
  @backstage/plugin-catalog-node                     1.0.1
  @backstage/plugin-catalog-react                    1.1.3
  @backstage/plugin-catalog                          1.5.0
  @backstage/plugin-github-actions                   0.5.8
  @backstage/plugin-jenkins-backend                  0.1.25
  @backstage/plugin-jenkins-common                   0.1.7
  @backstage/plugin-jenkins                          0.7.7
  @backstage/plugin-kubernetes-backend               0.7.1
  @backstage/plugin-kubernetes-common                0.4.1
  @backstage/plugin-kubernetes                       0.7.1
  @backstage/plugin-lighthouse                       0.3.8
  @backstage/plugin-org                              0.5.8
  @backstage/plugin-permission-common                0.6.3
  @backstage/plugin-permission-node                  0.6.4
  @backstage/plugin-permission-react                 0.4.4
  @backstage/plugin-proxy-backend                    0.2.29
  @backstage/plugin-scaffolder-backend               1.5.0
  @backstage/plugin-scaffolder-common                1.1.2
  @backstage/plugin-scaffolder                       1.5.0
  @backstage/plugin-search-backend-module-pg         0.3.6
  @backstage/plugin-search-backend-node              1.0.1
  @backstage/plugin-search-backend                   1.0.1
  @backstage/plugin-search-common                    1.0.0
  @backstage/plugin-search-react                     1.0.1
  @backstage/plugin-search                           1.0.1
  @backstage/plugin-sonarqube                        0.4.0
  @backstage/plugin-tech-radar                       0.5.15
  @backstage/plugin-techdocs-backend                 1.2.1
  @backstage/plugin-techdocs-module-addons-contrib   1.0.3
  @backstage/plugin-techdocs-node                    1.3.0
  @backstage/plugin-techdocs-react                   1.0.3
  @backstage/plugin-techdocs                         1.3.1
  @backstage/plugin-user-settings                    0.4.7
  @backstage/release-manifests                       0.0.5
  @backstage/test-utils                              1.1.3
  @backstage/theme                                   0.2.16
  @backstage/types                                   1.0.0
  @backstage/version-bridge                          1.0.1
✨  Done in 1.23s.
```
