### ISSUE TITLE
Kubernetes cluster type 'gke' not respecting backend auth

### ISSUE THREAD

**Issue by jskarpe** [backstage/backstage#13648]
## Expected Behavior

Visible Kubernetes details when clicking the "Kubernetes" tab of the service, or an actual error message (in log or otherwise) detailing why it's not working. 

## Actual Behavior

Annotating service with kubernetes and accessing this tab in the UI results in "Please log in" dialogue box, listing Google as auth method
No GCP API requests seems to have been logged
Specifying a cluster through config option directly gets around the issue

## Steps to Reproduce

1. Set up Kubernetes as detailed in the documentation for GKE cluster discovery here: https://backstage.io/docs/features/kubernetes/overview
2. Annotate service with Kubernetes, to make the Kubernetes tab show up in the service catalogue
3. Access the Kubernetes tab in the UI

## Context

I am trying to connect Backstage backend to Kubernetes using googleServiceAccount credentials and cluster autodiscovery

Example config from documentation, with explicit authProvider added
```
kubernetes:
  serviceLocatorMethod:
    type: 'multiTenant'
  clusterLocatorMethods:
    - type: 'gke'
      projectId: 'gke-clusters'
      authProvider: 'googleServiceAccount'
      region: 'europe-west1'
      skipTLSVerify: true
      skipMetricsLookup: true
      exposeDashboard: true
```
Services in the service catalogue is annotated with Kubernetes
Google auth for frontend is not (and shall not be) configured. GOOGLE_APPLICATION_CREDENTIALS is defined and points to a valid credentials file. LOG_LEVEL set to 'debug'

Example log output:
```
[1] 2022-09-12T14:06:03.676Z kubernetes info action=loadClusterDetails numOfClustersLoaded=1 type=plugin
[1] 2022-09-12T14:06:03.681Z backstage info ::1 - - [12/Sep/2022:14:06:03 +0000] "GET /api/kubernetes/clusters HTTP/1.1" 304 - "http://localhost:3000/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36" type=incomingRequest
[1] 2022-09-12T14:06:03.701Z backstage info ::1 - - [12/Sep/2022:14:06:03 +0000] "GET /api/auth/google/refresh?optional&env=development HTTP/1.1" 404 - "http://localhost:3000/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36" type=incomingRequest
```
