### ISSUE TITLE
Unable to authorize app in development environment

### ISSUE THREAD

**Issue by miniengineer** [backstage/backstage#13656]
## Expected Behavior

We have two config files
- `app-config.yaml` - for production
- `app-config.local.yaml` - for development

Our auth setup in `app-config.yaml`

```yaml
auth:
  environment: production
  providers:
    github:
      production:
        clientId: ${AUTH_GITHUB_CLIENT_ID}
        clientSecret: ${AUTH_GITHUB_CLIENT_SECRET}
```

And in `app-config.local.yaml`

```yaml
auth:
  environment: development
  providers:
    github:
      development:
        clientId: ${AUTH_GITHUB_CLIENT_ID_DEV}
        clientSecret: ${AUTH_GITHUB_CLIENT_SECRET_DEV}
```

We assume that when we start in dev mode, it will use the credentials from `app-config.local.yaml` and authorize with github.

## Actual Behavior

Instead we see the following log

```
[1] 2022-09-12T01:49:55.438Z auth warn Skipping github auth provider, Missing required config value at 'auth.providers.github.production.clientId' type=plugin
```

Although the production configuration for github auth is empty, it's trying to read the empty values and completely ignores the development config values.

## Steps to Reproduce

1. Add an auth provider both into the development and production config
2. Include credentials only into the development config and leave the ones in production empty
3. Start backstage in development mode

## Context

Trying to make the auth work in development mode without providing credentials or random strings into production configuration.

## My Environment

- Output of `yarn backstage-cli info`: 

```text
OS:   Darwin 21.3.0 - darwin/x64
node: v16.17.0
yarn: 1.22.19
cli:  0.18.1 (installed)
backstage:  1.5.0

Dependencies:
  @backstage/app-defaults                         1.0.5
  @backstage/backend-common                       0.15.0
  @backstage/backend-plugin-api                   0.1.1
  @backstage/backend-tasks                        0.3.4
  @backstage/catalog-client                       1.0.4
  @backstage/catalog-model                        1.1.0
  @backstage/cli-common                           0.1.9
  @backstage/cli                                  0.18.1
  @backstage/config-loader                        1.1.3
  @backstage/config                               1.0.1
  @backstage/core-app-api                         1.0.5
  @backstage/core-components                      0.11.0, 0.9.5
  @backstage/core-plugin-api                      1.0.5
  @backstage/dev-utils                            1.0.5
  @backstage/errors                               1.1.0
  @backstage/integration-react                    1.1.3
  @backstage/integration                          1.3.0
  @backstage/plugin-adr-common                    0.2.0
  @backstage/plugin-adr                           0.2.0
  @backstage/plugin-api-docs                      0.8.8
  @backstage/plugin-app-backend                   0.3.35
  @backstage/plugin-auth-backend                  0.15.1
  @backstage/plugin-auth-node                     0.2.4
  @backstage/plugin-catalog-backend-module-aws    0.1.8
  @backstage/plugin-catalog-backend-module-github 0.1.6
  @backstage/plugin-catalog-backend               1.3.1
  @backstage/plugin-catalog-common                1.0.5
  @backstage/plugin-catalog-graph                 0.2.20
  @backstage/plugin-catalog-node                  1.0.1
  @backstage/plugin-catalog-react                 1.1.3
  @backstage/plugin-catalog                       1.5.0
  @backstage/plugin-fossa                         0.2.40
  @backstage/plugin-github-actions                0.5.8
  @backstage/plugin-github-pull-requests-board    0.1.2
  @backstage/plugin-home                          0.4.24
  @backstage/plugin-org                           0.5.8
  @backstage/plugin-permission-backend            0.5.10
  @backstage/plugin-permission-common             0.6.3
  @backstage/plugin-permission-node               0.6.4
  @backstage/plugin-permission-react              0.4.4
  @backstage/plugin-proxy-backend                 0.2.29
  @backstage/plugin-scaffolder-backend            1.5.0
  @backstage/plugin-scaffolder-common             1.1.2
  @backstage/plugin-scaffolder                    1.5.0
  @backstage/plugin-search-backend-node           1.0.1
  @backstage/plugin-search-backend                1.0.1
  @backstage/plugin-search-common                 1.0.0
  @backstage/plugin-search-react                  1.0.1
  @backstage/plugin-search                        1.0.1
  @backstage/plugin-stack-overflow                0.1.4
  @backstage/plugin-user-settings                 0.4.7
  @backstage/release-manifests                    0.0.5
  @backstage/test-utils                           1.1.3
  @backstage/theme                                0.2.16
  @backstage/types                                1.0.0
  @backstage/version-bridge                       1.0.1
✨  Done in 4.46s.
```

**Comment by Rugvip** [comment]
Does auth still work in development?

The two configs are merged together, so both the production and development provider should be installed, except of course the production vars are missing so it ends up empty.

I'd recommend using `app-config.yaml` as the base configuration file for local dev though, and a separate `app-config.production.yaml` for production. The `app-config.local.yaml` is a bit special in that it is typically gitignore'd, so you can put local development secrets there without needing to use separate env vars. You can read more about all of that over here: https://backstage.io/docs/conf/writing#configuration-files

**Comment by kamil-wojcik** [comment]
I have similar issue, however I got failure not just warn

```

6
2022-09-22T14:00:51.394Z auth info Configuring provider, github type=plugin
5
Backend failed to start up Error: Failed to initialize github auth provider, Missing required config value at 'auth.providers.github.production.clientId'
4
    at Object.createRouter (/app/node_modules/@backstage/plugin-auth-backend/dist/index.cjs.js:3192:17)
3
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
2
    at async createPlugin$6 (/app/packages/backend/dist/index.cjs.js:34:10
```

 
I put config in default app-config.yaml file, I tried using $env and env string interpolation.

```
auth:
  # see https://backstage.io/docs/auth/ to learn about auth providers
  environment: production
  providers:
    github:
      production:
        clientId: 
          $env: BACKSTAGE-AUTH-GITHUB-CLIENT-ID
        clientSecret: 
          $env: BACKSTAGE-AUTH-GITHUB-CLIENT-SECRET
        ## uncomment if using GitHub Enterprise
```
