### ISSUE TITLE
400 Error on publish:gitlab action to private gitlab instance

### ISSUE THREAD

**Issue by bb-k8** [backstage/backstage#13741]
Running into an error when trying to publish a template to a private gitlab server. The template is the default template provided with create-backstag-app. I've edited the publish action to publish to gitlab.

Relevant configs...

app-config.yml

```
integrations:
  gitlab:
    - host: MY_HOST
      token: MY_TOKEN
      apiBaseUrl: https://MY_HOST/api/v4
...
scaffolder:
  gitlab:
    visibility: private
```

template.yml
```
spec:
  steps:
    ...
    - id: publish
      name: Publish
      action: publish:gitlab
      input:
        allowedHosts: ['MY_HOST']
        token: MY_TOKEN
        description: This is ${{ parameters.name }}
        repoUrl: ${{ parameters.repoUrl }}
```
And the error message:
```
[1](http://localhost:3000/...) TIMESTAMP Beginning step Publish
[2](http://localhost:3000/...) TIMESTAMP HTTPError: Response code 400 (Bad Request)
    [3](http://localhost:3000/...)   at Request.<anonymous> (/Users/USERNAME/Desktop/projects/backstage/node_modules/got/dist/source/as-promise/index.js:118:42)
[4](http://localhost:3000/...)    at runMicrotasks (<anonymous>)
[5](http://localhost:3000/...)    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

MY_TOKEN is a gitlab private access token with the scopes api, read_api, read_registry, write_registry, read_repository, write_repository. It is used in the gitlab integration as well, and successfully pulls components from the server.

Figure it's gotta be something simple I'm missing, but error messaging hasn't been helpful. For repo url I've tried every combination of group name, repo, and adding .git on the end. None seem to work.

Node: v16.1.0
Backstage: 1.5.0
