### ISSUE TITLE
K8s Plugin Cluster 401 Error Still Shows Cluster With 0 Resources

### ISSUE THREAD

**Issue by asaf-erlich** [backstage/backstage#13792]
## Expected Behavior
When clusters are configured in backstage, but there are 401 errors because their permissions haven't been updated yet, I would expect those clusters to not appear on the page. Otherwise it's rather confusing to a user who's not familiar with the UI why they appear that way.

## Actual Behavior
When clusters are configured in backstage, but there are 401 errors because their permissions haven't been updated yet, those clusters still appear with cards in the UI showing 0 resources.  Example screenshot below shows one of the cluster lacking permission. I'm referring to the one named `archiver-k8s`, but we have a lot configured so if I were to scroll down it shows 90+ clusters on the page and most don't have permission. It's unexpected and confusing to see so many when most are not relevant for this component which only exists in 2 clusters.
<img width="758" alt="Screen Shot 2022-09-21 at 1 50 00 PM" src="https://user-images.githubusercontent.com/1738335/191575794-051dbf61-dbf8-4ce3-a687-621302791347.png">

I haven't dug into whether this would involve both the k8s frontend and backend plugins or whether it would only be handled by the frontend one.

## Steps to Reproduce
Screenshot above shows an example with clusters with resources and another cluster which has 401 errors and still shows the card but with `0 pods` even though the tool does not know about the resources in that cluster. Steps to somewhat reproduce below, will do my best to include configuration as well.

1. Install [k8s](https://backstage.io/docs/features/kubernetes/overview) backend and frontend plugin following [installation instructions](https://backstage.io/docs/features/kubernetes/installation).
2. [Configure](https://backstage.io/docs/features/kubernetes/configuration) clusters with a similar setup to the one below, not sure if the authentication method of aws in this case matters or not. Below is the kubernetes part of the app-config.yaml:
    ```yaml
    kubernetes:
      serviceLocatorMethod:
        type: 'multiTenant'
      clusterLocatorMethods:
        - type: 'config'
          clusters:
            - name: cluster-with-permissions
              url: https://cluster-with-permissions-url.amazonaws.com
              authProvider: 'aws'
              caData: ${CLUSTER_WITH_PERMISSIONS_K8S_CONFIG_CA_DATA}
            - name: cluster-missing-permissions
              url: https://cluster-missing-permissions-url.amazonaws.com
              authProvider: 'aws'
              caData: ${CLUSTER_MISSING_PERMISSIONS_K8S_CONFIG_CA_DATA}
    ```
4. Configure only one of the clusters, the `cluster-with-permission` to update its aws-auth map to have permission to query the cluster. While this is an AWS specific instruction I think it could be any cluster which would return 401 unauthorized if the permissions are not configured correctly.
5. Configure a component to have the appropriate annotations for the k8s plugin. Example catalog-info.yaml file:
    ```yaml
    apiVersion: backstage.io/v1alpha1
    kind: Component
    metadata:
      name: backstage
      description: The Backstage
      annotations:
        backstage.io/kubernetes-label-selector: 'app=backstage'
        backstage.io/kubernetes-namespace: backstage
    spec:
      type: website
      owner: owner
      lifecycle: experimental
    ```

## Context
This issue creates a bad UX for our users. I tried my best to include details above, but let me know if more information is needed.

## Your Environment

- Browser Information: Google Chrome Version 105.0.5195.102 (Official Build) (arm64)

- Output of `yarn backstage-cli info`: 

```bash
yarn backstage-cli info
yarn run v1.22.17
$ /Users/asaferlich/dev/src/github.com/segmentio/backstage-segment/node_modules/.bin/backstage-cli info
OS:   Darwin 21.6.0 - darwin/arm64
node: v16.14.2
yarn: 1.22.17
cli:  0.18.1 (installed)
backstage:  1.5.1

Dependencies:
  @backstage/app-defaults                          1.0.5
  @backstage/backend-common                        0.15.0
  @backstage/backend-plugin-api                    0.1.1
  @backstage/backend-tasks                         0.3.4
  @backstage/catalog-client                        1.0.4
  @backstage/catalog-model                         1.1.0
  @backstage/cli-common                            0.1.9
  @backstage/cli                                   0.18.1
  @backstage/config-loader                         1.1.3
  @backstage/config                                1.0.1
  @backstage/core-app-api                          1.0.5
  @backstage/core-components                       0.11.0
  @backstage/core-plugin-api                       1.0.5
  @backstage/dev-utils                             1.0.5
  @backstage/errors                                1.1.0
  @backstage/integration-react                     1.1.3
  @backstage/integration                           1.3.0
  @backstage/plugin-analytics-module-ga            0.1.19
  @backstage/plugin-api-docs                       0.8.8
  @backstage/plugin-app-backend                    0.3.35
  @backstage/plugin-auth-backend                   0.15.1
  @backstage/plugin-auth-node                      0.2.4
  @backstage/plugin-catalog-backend-module-github  0.1.6
  @backstage/plugin-catalog-backend                1.3.1
  @backstage/plugin-catalog-common                 1.0.5
  @backstage/plugin-catalog-graph                  0.2.20
  @backstage/plugin-catalog-node                   1.0.1
  @backstage/plugin-catalog-react                  1.1.3
  @backstage/plugin-catalog                        1.5.0
  @backstage/plugin-github-actions                 0.5.8
  @backstage/plugin-github-pull-requests-board     0.1.2
  @backstage/plugin-home                           0.4.24
  @backstage/plugin-kubernetes-backend             0.7.1
  @backstage/plugin-kubernetes-common              0.4.1
  @backstage/plugin-kubernetes                     0.7.1
  @backstage/plugin-org                            0.5.8
  @backstage/plugin-pagerduty                      0.5.1
  @backstage/plugin-permission-common              0.6.3
  @backstage/plugin-permission-node                0.6.4
  @backstage/plugin-permission-react               0.4.4
  @backstage/plugin-proxy-backend                  0.2.29
  @backstage/plugin-scaffolder-backend             1.5.1
  @backstage/plugin-scaffolder-common              1.1.2
  @backstage/plugin-scaffolder                     1.5.0
  @backstage/plugin-search-backend-module-pg       0.3.6
  @backstage/plugin-search-backend-node            1.0.1
  @backstage/plugin-search-backend                 1.0.1
  @backstage/plugin-search-common                  1.0.0
  @backstage/plugin-search-react                   1.0.1
  @backstage/plugin-search                         1.0.1
  @backstage/plugin-shortcuts                      0.3.0
  @backstage/plugin-stack-overflow                 0.1.4
  @backstage/plugin-techdocs-backend               1.2.1
  @backstage/plugin-techdocs-module-addons-contrib 1.0.3
  @backstage/plugin-techdocs-node                  1.3.0
  @backstage/plugin-techdocs-react                 1.0.3
  @backstage/plugin-techdocs                       1.3.1
  @backstage/plugin-user-settings                  0.4.7
  @backstage/release-manifests                     0.0.5
  @backstage/test-utils                            1.1.3
  @backstage/theme                                 0.2.16
  @backstage/types                                 1.0.0
  @backstage/version-bridge                        1.0.1
✨  Done in 0.96s.
```
