### ISSUE TITLE
not able to authenticate using auth0 authentication provider

### ISSUE THREAD

**Issue by imleozzito** [backstage/backstage#13797]
## Expected Behavior

When I'm logging in using an auth0 provider, the authentication popup must be displayed.

## Actual Behavior

I'm getting the following message:

```
{
    "error": {
        "name": "Error",
        "message": "Auth0Strategy requires you set state to false when no session is present",
        "level": "error"
    },
    "request": {
        "method": "GET",
        "url": "/api/auth/auth0/start?scope=openid%20email%20profile%20offline_access&origin=http%3A%2F%2Flocalhost%3A3000&env=development"
    },
    "response": {
        "statusCode": 500
    }
}
```
<img width="651" alt="3464F758-DC87-4077-9701-02CC6A781E71" src="https://user-images.githubusercontent.com/105804599/191603319-1ae20738-e7ef-43fc-a8d7-2dc5f9ef8cc3.png">

## Steps to Reproduce

1. Start backstage app and backend
2. Access SignIn Page

## Context

`app-config.yml` file:

```
auth:
  auth0:
      development:
        clientId: <client-id>
        clientSecret: <client-secret>
        domain: <domain>
        audience: <audience>
```

`packages/backend/src/plugins/auth.ts` file:

```
export default async function createPlugin(
  env: PluginEnvironment,
): Promise<Router> {
  return await createRouter({
    logger: env.logger,
    config: env.config,
    database: env.database,
    discovery: env.discovery,
    tokenManager: env.tokenManager,
    providerFactories: {
      auth0: providers.auth0.create({
        signIn: {
          resolver: async (info, ctx) => {
            const { profile: { email } } = info;

            if (!email) {
              throw new Error('User profile contained no email');
            }

            const [name] = email.split('@');

            return ctx.signInWithCatalogUser({
              entityRef: { name }
            });
          },
        },
      })
    },
  });
}
```

Also following the generic auth api ref documentation [available here](https://backstage.io/docs/api/deprecations#generic-auth-api-refs). Am I missing something? Thanks.

## Your Environment

```
"@backstage/plugin-auth-backend": "0.16.0"
```

**Comment by Rugvip** [comment]
Most likely related to #13586. @jrwpatterson, do you know what might be going on?

**Comment by Houssem-Esprit** [comment]
any update about this issue ??

**Comment by jrwpatterson** [comment]
Sorry missed this. I'm not sure whats going on there we already set the state to false 

However the first thing I would say is Auth0 doesn't sync to the catalogue so you must make sure your users are in the catalogue but https://github.com/jrwpatterson/backstage/blob/master/plugins/auth-backend/src/providers/auth0/provider.ts#L79 should be fixing your state. 

I would debug through the call and find that line because it could be a different error.

**Comment by cowboyd** [comment]
We're also encountering this. We can't actually get the login screen to render to get to the portion where we'd check that our users were in the catalog.

**Comment by jrwpatterson** [comment]
Does anybody have a repo I can use to reproduce this?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by jrwpatterson** [comment]
never mind worked it out! 

I  can at some point update the docs unless someone wants to but ultimately its because we need session support for Auth0

https://backstage.io/docs/auth/oidc#the-configuration

so in the app-config.yaml you need to add the session secret

```yaml
auth:
  # see https://backstage.io/docs/auth/ to learn about auth providers
  providers:
    auth0:
      development:
        clientId: ${AUTH0_CLIENT_ID}
        clientSecret: ${AUTH0_CLIENT_SECRET}
        domain: ${AUTH0_ISSUER_DOMAIN}
        audience: ${AUTH0_AUDIENCE}
    # github:
    #   development:
    #     clientId: ${AUTH_GITHUB_CLIENT_ID}
    #     clientSecret: ${AUTH_GITHUB_CLIENT_SECRET}
  session:
    secret: 
      'authsessionsecret'
```
