### ISSUE TITLE
Approvals for template steps

### ISSUE THREAD

**Issue by KatharinaSick** [backstage/backstage#13809]
## Feature Suggestion

When creating a new instance from a template, Backstage may need credentials to execute some steps. In our case, it needs Bitbucket credentials to create new repositories. We don't want that the user has to enter his/her Bitbucket credentials (or token) in any tool other than Bitbucket itself. Using global (mighty) credentials to create repositories may lead to privilege escalation. Therefore, we would like to suggest adding the following workflow via a built-in action to the scaffolder plugin:

- When the user creates a new instance from a template, it does not get created immediately but an approval request is made.
- When this approval request gets approved, all defined actions (e.g. publish) get executed. If it gets declined, nothing happens.

This could look like this in the YAML definition of a template:

```yaml
apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
...
spec:
  ...
  steps:
    - id: request-approval
      name: Request Approval
      action: approval:request
      input:
        onApprove:
          - id: fetch-base
            name: Fetch Base
            action: fetch:template
            input:
              ...
          - id: publish
            name: Publish
            action: publish:bitbucketServer
            input:
              ...
```

Approvals can be handled via an external service that can be defined in the Backstage config. Once an approval request gets approved or declined, the service could make a POST request to a predefined webhook. In our case, the approval service is creating pull requests on Bitbucket.

## Possible Implementation

We first wanted to create a new plugin that handles the above-described workflow. In this plugin, we wanted to utilize the scaffolder-backend plugin to execute the steps defined in the `onApprove` section of the approval:request action. Unfortunately, neither the API nor the provided ScaffolderClient support manipulating the defined actions in a template. We then found out, that somebody had already requested to make the scaffolder actions executable in other locations as well. This would have helped us, but the team decided against it, as it doesn't match the idea of the scaffolder plugin (which we totally agree with). Therefore, we would like to add the above-described action to the scaffolder plugin itself.

## Notes

If you accept this feature request, we would be open to contributing it.
