### ISSUE TITLE
/api/auth/github return timeout error in custom dns and 404 not found in local environment

### ISSUE THREAD

**Issue by jiawenh1** [backstage/backstage#13814]
When I set up backstage in local enviroment and try to log in to github when the sign-up button shown
backstage will return `404 /api/auth/github` not found
and when I enter /api it will return 404 as well

For my production environment, I am deploying backstage into eks
the sign-in popup will be stuck in about:blank
And the whole app will be stuck in refreshing state till  this error appear`GET https://domain:7007/api/auth/github/refresh?optional&env=development net::ERR_CONNECTION_TIMED_OUT`

I tried to ping the `https://domain:7007/api/auth/github` but it will just time out
## Actual Behavior

In localhost, when enter /api/auth/github it will return:
`{"error":{"name":"NotFoundError","message":"No auth provider registered for 'github'"},"request":{"method":"GET","url":"/api/auth/github"},"response":{"statusCode":404}}`

## Steps to Reproduce

This is my app-config.yaml
```
app:
  title: my-title
  baseUrl: https://mydomain:3000
backend:
  baseUrl: https://mydomain:7007
  listen:
    port: 7007

  # content security policy
  csp:
    connect-src: ["'self'", 'http:', 'https:']

  database:
    client: pg
    connection:
      host: ${POSTGRES_HOST}
      port: 5432
      user: ${POSTGRES_USER}
      password: ${POSTGRES_SECRET}

integrations:
  github:
    - host: github.com
      token: ${GITHUB_TOKEN}

techdocs:
  builder: 'local' # Alternatives - 'external'
  generator:
    runIn: 'docker' # Alternatives - 'local'
  publisher:
    type: 'local' # Alternatives - 'googleGcs' or 'awsS3'. Read documentation for using alternatives.

auth:
  # authenticate with github
  providers:
    github:
      development:
        clientId: ${AUTH_GITHUB_CLIENT_ID}
        clientSecret: ${AUTH_GITHUB_CLIENT_SECRET}
```

## Context

In the container, the refresh will causing hundreds of lines of
```
[2m2022-09-16T17:52:44.917Z[22m [34mbackstage[39m [32minfo[39m ::ffff:10.19.111.181 - - [16/Sep/2022:17:52:44 +0000] "GET / HTTP/1.1" 200 1924 "-" "kube-probe/1.21+" [36mtype[39m=incomingRequest
[2m2022-09-16T17:52:44.918Z[22m [34mbackstage[39m [32minfo[39m ::ffff:10.19.111.181 - - [16/Sep/2022:17:52:44 +0000] "GET / HTTP/1.1" 200 1924 "-" "kube-probe/1.21+" [36mtype[39m=incomingRequest
```

## Your Environment

- Browser Information: 105.0.5195.125 (Official Build) (arm64)

- Output of `yarn backstage-cli info`: 

```yarn run v1.22.19
OS:   Darwin 21.4.0 - darwin/arm64
node: v16.16.0
yarn: 1.22.19
cli:  0.19.0 (installed)
backstage:  1.5.0

Dependencies:
  @backstage/app-defaults                          1.0.6
  @backstage/backend-common                        0.15.1
  @backstage/backend-plugin-api                    0.1.2
  @backstage/backend-tasks                         0.3.5
  @backstage/catalog-client                        1.1.0
  @backstage/catalog-model                         1.1.1
  @backstage/cli-common                            0.1.10
  @backstage/cli                                   0.19.0
  @backstage/config-loader                         1.1.4
  @backstage/config                                1.0.2
  @backstage/core-app-api                          1.1.0
  @backstage/core-components                       0.11.1
  @backstage/core-plugin-api                       1.0.6
  @backstage/errors                                1.1.1
  @backstage/integration-react                     1.1.4
  @backstage/integration                           1.3.1
  @backstage/plugin-api-docs                       0.8.9
  @backstage/plugin-app-backend                    0.3.36
  @backstage/plugin-auth-backend                   0.16.0
  @backstage/plugin-auth-node                      0.2.5
  @backstage/plugin-catalog-backend-module-github  0.1.7
  @backstage/plugin-catalog-backend                1.4.0
  @backstage/plugin-catalog-common                 1.0.6
  @backstage/plugin-catalog-graph                  0.2.21
  @backstage/plugin-catalog-import                 0.8.12
  @backstage/plugin-catalog-node                   1.1.0
  @backstage/plugin-catalog-react                  1.1.4
  @backstage/plugin-catalog                        1.5.1
  @backstage/plugin-github-actions                 0.5.9
  @backstage/plugin-org                            0.5.9
  @backstage/plugin-permission-common              0.6.4
  @backstage/plugin-permission-node                0.6.5
  @backstage/plugin-permission-react               0.4.5
  @backstage/plugin-proxy-backend                  0.2.30
  @backstage/plugin-scaffolder-backend             1.6.0
  @backstage/plugin-scaffolder-common              1.2.0
  @backstage/plugin-scaffolder                     1.6.0
  @backstage/plugin-search-backend-module-pg       0.4.0
  @backstage/plugin-search-backend-node            1.0.2
  @backstage/plugin-search-backend                 1.0.2
  @backstage/plugin-search-common                  1.0.1
  @backstage/plugin-search-react                   1.1.0
  @backstage/plugin-search                         1.0.2
  @backstage/plugin-tech-radar                     0.5.16
  @backstage/plugin-techdocs-backend               1.3.0
  @backstage/plugin-techdocs-module-addons-contrib 1.0.4
  @backstage/plugin-techdocs-node                  1.4.0
  @backstage/plugin-techdocs-react                 1.0.4
  @backstage/plugin-techdocs                       1.3.2
  @backstage/plugin-user-settings                  0.4.8
  @backstage/release-manifests                     0.0.6
  @backstage/test-utils                            1.2.0
  @backstage/theme                                 0.2.16
  @backstage/types                                 1.0.0
  @backstage/version-bridge                        1.0.1

```
