### ISSUE TITLE
Unable to see online images in my techdocs

### ISSUE THREAD

**Issue by LvffY** [backstage/backstage#13939]
## Expected Behavior

The techdocs render should print my online images. In my case, they are some public images from lucidcharts.

## Actual Behavior

Any online image is loaded when I look at my techdocs inside my backstage instance.

![image](https://user-images.githubusercontent.com/37327656/193250693-6d8de4c0-f1b6-4c88-9517-cf2e961d6ff2.png)

## Steps to Reproduce

1. Generate a techdocs and deploy it on a remote storage (in my case, Azure Blob Storage)
2. Open the techdocs
3. Unable to see the images

My configuration files : 

- **app-config.production.yaml**

```yaml
backend:
  baseUrl: https://${CUSTOM_DOMAIN}
  listen:
    port: 80
  cors:
    origin: https://${CUSTOM_DOMAIN}

techdocs:
  builder: 'external'
  publisher:
    type: 'azureBlobStorage'
    azureBlobStorage:
      containerName: ${TECHDOCS_CONTAINER_NAME}
      credentials:
        accountName: ${TECHDOCS_STORAGE_ACCOUNT}
        accountKey: ${TECHDOCS_STORAGE_ACCOUNT_KEY}
``` 

- **app-config.yaml**

```yaml
backend:
  baseUrl: http://localhost:7007
  listen:
    port: 7007
  csp:
    connect-src: ["'self'", 'http:', 'https:']
  cors:
    origin: http://localhost:3000
    methods: [GET, HEAD, PATCH, POST, PUT, DELETE]
    credentials: true
  database:
    client: pg
    connection:
      host: ${POSTGRES_HOST}
      port: ${POSTGRES_PORT}
      user: ${POSTGRES_USER}
      password: ${POSTGRES_PASSWORD}
      ssl: true
  cache:
    store: memory
  reading:
    allow:
      # Try this, thought it would allow my images to be read. 
      - host: lucid.app 

techdocs:
  builder: 'local' # Alternatives - 'external'
  generator:
    runIn: 'docker' # Alternatives - 'local'
  publisher:
    type: 'local' # Alternatives - 'googleGcs' or 'awsS3'. Read documentation for using alternatives.
````

## Your Environment

- Browser Information: 

- Output of `yarn backstage-cli info`: 

```text
OS:   Linux 5.10.102.1-microsoft-standard-WSL2 - linux/x64
node: v16.15.1
yarn: 1.22.19
cli:  0.19.0 (installed)
backstage:  1.6.0

Dependencies:
  @backstage/app-defaults                               1.0.6
  @backstage/backend-common                             0.15.1
  @backstage/backend-plugin-api                         0.1.2
  @backstage/backend-tasks                              0.3.5
  @backstage/catalog-client                             1.1.0
  @backstage/catalog-model                              1.1.1
  @backstage/cli-common                                 0.1.10
  @backstage/cli                                        0.19.0
  @backstage/config-loader                              1.1.4
  @backstage/config                                     1.0.2
  @backstage/core-app-api                               1.1.0
  @backstage/core-components                            0.11.1, 0.9.5
  @backstage/core-plugin-api                            1.0.6
  @backstage/dev-utils                                  1.0.6
  @backstage/errors                                     1.1.1
  @backstage/integration-react                          1.1.4
  @backstage/integration                                1.3.1
  @backstage/plugin-api-docs                            0.8.9
  @backstage/plugin-app-backend                         0.3.36
  @backstage/plugin-auth-backend                        0.16.0
  @backstage/plugin-auth-node                           0.2.5
  @backstage/plugin-azure-devops-backend                0.3.15
  @backstage/plugin-azure-devops-common                 0.3.0
  @backstage/plugin-azure-devops                        0.2.0
  @backstage/plugin-catalog-backend-module-azure        0.1.7
  @backstage/plugin-catalog-backend-module-gitlab       0.1.7
  @backstage/plugin-catalog-backend-module-msgraph      0.4.2
  @backstage/plugin-catalog-backend                     1.4.0
  @backstage/plugin-catalog-common                      1.0.6
  @backstage/plugin-catalog-graph                       0.2.21
  @backstage/plugin-catalog-import                      0.8.12
  @backstage/plugin-catalog-node                        1.1.0
  @backstage/plugin-catalog-react                       1.1.4
  @backstage/plugin-catalog                             1.5.1
  @backstage/plugin-explore-react                       0.0.21
  @backstage/plugin-explore                             0.3.40
  @backstage/plugin-github-actions                      0.5.9
  @backstage/plugin-home                                0.4.25
  @backstage/plugin-kubernetes-backend                  0.7.2
  @backstage/plugin-kubernetes-common                   0.4.2
  @backstage/plugin-kubernetes                          0.7.2
  @backstage/plugin-org                                 0.5.9
  @backstage/plugin-permission-common                   0.6.4
  @backstage/plugin-permission-node                     0.6.5
  @backstage/plugin-permission-react                    0.4.5
  @backstage/plugin-proxy-backend                       0.2.30
  @backstage/plugin-scaffolder-backend                  1.6.0
  @backstage/plugin-scaffolder-common                   1.2.0
  @backstage/plugin-scaffolder                          1.6.0
  @backstage/plugin-search-backend-module-pg            0.4.0
  @backstage/plugin-search-backend-node                 1.0.2
  @backstage/plugin-search-backend                      1.0.2
  @backstage/plugin-search-common                       1.0.1
  @backstage/plugin-search-react                        1.1.0
  @backstage/plugin-search                              1.0.2
  @backstage/plugin-sonarqube-backend                   0.1.1
  @backstage/plugin-sonarqube                           0.4.1
  @backstage/plugin-stack-overflow                      0.1.5
  @backstage/plugin-tech-insights-backend-module-jsonfc 0.1.20
  @backstage/plugin-tech-insights-backend               0.5.2
  @backstage/plugin-tech-insights-common                0.2.6
  @backstage/plugin-tech-insights-node                  0.3.4
  @backstage/plugin-tech-insights                       0.3.0
  @backstage/plugin-tech-radar                          0.5.16
  @backstage/plugin-techdocs-backend                    1.3.0
  @backstage/plugin-techdocs-module-addons-contrib      1.0.4
  @backstage/plugin-techdocs-node                       1.4.0
  @backstage/plugin-techdocs-react                      1.0.4
  @backstage/plugin-techdocs                            1.3.2
  @backstage/plugin-todo-backend                        0.1.33
  @backstage/plugin-todo                                0.2.11
  @backstage/plugin-user-settings                       0.4.8
  @backstage/release-manifests                          0.0.6
  @backstage/test-utils                                 1.2.0
  @backstage/theme                                      0.2.16
  @backstage/types                                      1.0.0
  @backstage/version-bridge                             1.0.1
```

**Comment by OrkoHunter** [comment]
Hi @LvffY ! I guess this is a CORS issue which you can fix by updating the CORS config in `app-config.yaml`. May I ask you to check the browser console logs to confirm? Open the techdocs page, right click anywhere and open dev console to see error logs.

**Comment by LvffY** [comment]
@OrkoHunter thanks !

I'll try to check this out.

Do you have any idea how to configure this ? Because I see the cors section in my config file but I don't see a list ... Can I just put a list in it ?

**Comment by OrkoHunter** [comment]
Umm actually, this might just be an issue of CSP. Something like this can fix the image loading issue.
https://github.com/backstage/demo/blob/5909d76046d193d606e8f79f1fbb4bef72ff15bf/app-config.yaml#L14

Although, we can not be sure without those browser console logs.

**Comment by LvffY** [comment]
Hello

Thanks to @OrkoHunter in the console I found these lines : 

![image](https://user-images.githubusercontent.com/37327656/193762214-314e1b3d-3158-46c7-b196-dbc0602a8fff.png)

I tried to add the following line to my **app-config.yaml** : 

```yaml
backend:
  # ...
  csp:
    # ...
    img-src: ["'self'", 'data:', 'https://backstage.io', 'https://lucid.app']
```

But still have the same result.

Am I missing something ?
