### ISSUE TITLE
Unable to publish with publish:azure

### ISSUE THREAD

**Issue by SSKLCP** [backstage/backstage#13938]
Hi there, 

Just trying to spin up a demo version of Backstage and get it working with Azure DevOps but I can't seem to get publish working. 

I feel like it's something I'm doing wrong but I've tried to follow any advice (where possible) for it. 

This is the error message that I get: 
![image](https://user-images.githubusercontent.com/62546866/193249387-58585998-4a61-4fd1-a3a8-735c66631dfd.png)

For the properties I input: 
`Name`: Test 
`Host`: dev.azure.com
`Owner`: Platform *(This project exists)*
`Repository`: SSKTest *(This repo doesn't already exist)*

It then gives me a Repo URL string like this: *(I redacted the organization but it is there and correct)*
![image](https://user-images.githubusercontent.com/62546866/193250004-da20d370-5222-4ef0-96a5-ccdebf571de7.png)

I've added these to `app-config.local.yaml`:

```yaml
integrations:
  azure:
    - host: dev.azure.com
      token: [redacted]

azureDevOps:
  host: dev.azure.com
  token:  [redacted]
  organization: [redacted]
```

Running this `template.yaml`:

```template.yaml
apiVersion: scaffolder.backstage.io/v1beta3
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-template
kind: Template
metadata:
  name: example-vuejs-template
  title: Example Vue.js Template
  description: An example template for the scaffolder that creates a simple Vue.js site
spec:
  owner: user:guest
  type: service

  # These parameters are used to generate the input form in the frontend, and are
  # used to gather input data for the execution of the template.
  parameters:
    - title: Fill in some steps
      required:
        - name
      properties:
        name:
          title: Name
          type: string
          description: Unique name of the component
          ui:autofocus: true
          ui:options:
            rows: 5
    - title: Choose a location
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - dev.azure.com

  # These steps are executed in the scaffolder backend, using data that we gathered
  # via the parameters above.
  steps:
    # Each step executes an action, in this case one templates files into the working directory.
    - id: fetch-base
      name: Fetch Base
      action: fetch:template
      input:
        url: ./content
        values:
          name: ${{ parameters.name }}

    # This step publishes the contents of the working directory to GitHub.
    - id: azure_publish
      name: Publish
      action:  
      input:
        allowedHosts: ['dev.azure.com']
        description: This is ${{ parameters.name }}
        repoUrl: ${{ parameters.repoUrl }}

    # The final step is to register our new component in the catalog.
    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps.publish.output.repoContentsUrl }}
        catalogInfoPath: '/catalog-info.yaml'

  # Outputs are displayed to the user after a successful execution of the template.
  output:
    links:
      - title: Repository
        url: ${{ steps.publish.output.remoteUrl }}
      - title: Open in catalog
        icon: catalog
        entityRef: ${{ steps.register.output.entityRef }}
```

Not sure if this is a me problem or if it just doesn't work in Azure at the moment? Any help would be appreciated :)

**Comment by SSKLCP** [comment]
Thanks, I believe the issue in the end was to do with the token not having permissions to create a new repo. Corrected now and get past that step (with another error but I'll try and work through that one!)

Thanks again :)

**Comment by AndyMcKenna** [comment]
@SSKLCP what was your other error?  I got an error on repo creation and we fixed that but now we're getting a 401 on trying to push the commit to the new repo.  We can't figure out what permission is missing there.

**Comment by walderpinheiro** [comment]
@AndyMcKenna i'm with the same issue. I'm using cliendId, clientSecret and i cant finish push to repo. I have configured all permissions

Did you fixed in your project?

**Comment by ppiwow-apay** [comment]
any luck on that? same issue, 401 when using cliendId, clientSecret, have you found any solutions for that?

**Comment by mattemoore** [comment]
Bumping this.  We are using managed identity.  We can read from repo.  We can create a repo.  We cannot push the initial commit to the repo.
`[69](https://developers.dev.tc.gc.ca/create/tasks/7cce4f9f-18db-41d7-a822-5b7a2e3e3e30#line-69)2024-08-29T18:05:14.755Z info: Init git repository {dir=/tmp/7cce4f9f-18db-41d7-a822-5b7a2e3e3e30}[70](https://developers.dev.tc.gc.ca/create/tasks/7cce4f9f-18db-41d7-a822-5b7a2e3e3e30#line-70)2024-08-29T18:05:14.933Z info: Adding file {dir=/tmp/7cce4f9f-18db-41d7-a822-5b7a2e3e3e30,filepath=.}[71](https://developers.dev.tc.gc.ca/create/tasks/7cce4f9f-18db-41d7-a822-5b7a2e3e3e30#line-71)2024-08-29T18:05:17.484Z info: Committing file to repo {dir=/tmp/7cce4f9f-18db-41d7-a822-5b7a2e3e3e30,message=initial commit}[72](https://developers.dev.tc.gc.ca/create/tasks/7cce4f9f-18db-41d7-a822-5b7a2e3e3e30#line-72)2024-08-29T18:05:17.595Z info: Creating new remote {dir=/tmp/7cce4f9f-18db-41d7-a822-5b7a2e3e3e30,remote=origin,url=https://transport-canada@dev.azure.com/transport-canada/TACE/_git/foobar12345}[73](https://developers.dev.tc.gc.ca/create/tasks/7cce4f9f-18db-41d7-a822-5b7a2e3e3e30#line-73)2024-08-29T18:05:17.605Z info: Pushing directory to remote {dir=/tmp/7cce4f9f-18db-41d7-a822-5b7a2e3e3e30,remote=origin}[74](https://developers.dev.tc.gc.ca/create/tasks/7cce4f9f-18db-41d7-a822-5b7a2e3e3e30#line-74)2024-08-29T18:05:17.722Z error: Failed to push to repo {dir=/tmp/7cce4f9f-18db-41d7-a822-5b7a2e3e3e30, remote=origin}[75](https://developers.dev.tc.gc.ca/create/tasks/7cce4f9f-18db-41d7-a822-5b7a2e3e3e30#line-75)2024-08-29T18:05:17.725Z Error: HTTP Error: 401 Unauthorized {data={"statusCode":401,"statusMessage":"Unauthorized","response":""}}[76](https://developers.dev.tc.gc.ca/create/tasks/7cce4f9f-18db-41d7-a822-5b7a2e3e3e30#line-76)    at Git.push (/app/node_modules/@backstage/plugin-scaffolder-node/dist/index.cjs.js:289:15)[77](https://developers.dev.tc.gc.ca/create/tasks/7cce4f9f-18db-41d7-a822-5b7a2e3e3e30#line-77)    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)[78](https://developers.dev.tc.gc.ca/create/tasks/7cce4f9f-18db-41d7-a822-5b7a2e3e3e30#line-78)    at async Object.initRepoAndPush (/app/node_modules/@backstage/plugin-scaffolder-node/dist/index.cjs.js:377:3)[79](https://developers.dev.tc.gc.ca/create/tasks/7cce4f9f-18db-41d7-a822-5b7a2e3e3e30#line-79)`

**Comment by awanlin** [comment]
Hi @mattemoore, I would log a new issue as this is from 2022 well before support for managed identify was added. Please make sure to include the output from `yarn backstage-cli info` in the new issue as well. 

I'll also mention that the Azure DevOps plugin has nothing to do with this. You can run the Scaffolder with Azure DevOps without the Azure DevOps plugin being installed. 

Finally, as I don't use Azure DevOps myself day-to-day and have never used managed identity I will be of limited help on this. when you log the new issue I'll try and provide any suggestion but I won't be able to do more than that 👍

**Comment by mattemoore** [comment]
@awanlin thanks for the prompt rely @awanlin .  I'll create a new issue for this.  Didn't notice it was closed.

**Comment by mattemoore** [comment]
This is fixed here; https://github.com/backstage/backstage/pull/26661

**Comment by phil1234567891011** [comment]
Anyone knows how to install azure devops related actions ? I cannot find the info anywhere, not everyone is using github, and the whole doc is about cookiecutter and github, thanks for enlighting me on this

also why is there no action specified here ?

 ```
# This step publishes the contents of the working directory to GitHub.
    - id: azure_publish
      name: Publish
      action:  **?????????**
      input:
        allowedHosts: ['dev.azure.com']
        description: This is ${{ parameters.name }}
        repoUrl: ${{ parameters.repoUrl }}
```

**Comment by mattemoore** [comment]
> Anyone knows how to install azure devops related actions ? I cannot find the info anywhere, not everyone is using github, and the whole doc is about cookiecutter and github, thanks for enlighting me on this
> 
> also why is there no action specified in the OP's template?
> 
> ```
> # This step publishes the contents of the working directory to GitHub.
>    - id: azure_publish
>      name: Publish
>      action:  ?????????
>      input:
>        allowedHosts: ['dev.azure.com']
>        description: This is ${{ parameters.name }}
>        repoUrl: ${{ parameters.repoUrl }}
> ```

These docs will help you install the azure devops scaffolder actions: [https://backstage.io/docs/features/software-templates/builtin-actions/](https://backstage.io/docs/features/software-templates/builtin-actions/)

Here's what we use to publish:

```
steps:
    - id: fetch-base
      name: Fetch Base
      action: fetch:template
      input:
        url: ./skeleton
        values:
          component_id: ${{ parameters.name }}
          destination: ${{ parameters.repoUrl | parseRepoUrl }}
          owner: ${{ parameters.owner }}
          project: ${{ parameters.project }}
    - id: publish
      action: publish:azure
      name: Publish to Azure
      input:
        repoUrl: ${{ parameters.repoUrl }}
        defaultBranch: main
    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps['publish'].output.repoContentsUrl }}
        catalogInfoPath: '/catalog-info.yaml'
  output:
    links:
      - title: Repository
        url: ${{ steps['publish'].output.remoteUrl }}
      - title: Open in catalog
        icon: catalog
        entityRef: ${{ steps['register'].output.entityRef }}
```
