### ISSUE TITLE
$text substitutions in catalog descriptor files do not support local files

### ISSUE THREAD

**Issue by OrkoHunter** [backstage/backstage#14372]
## Expected Behavior

According to the documentation for `$text`, `$json` and `$yaml`, we should be able to use `$text: <local file path>` to substitute `catalog-info.yaml`. This is especially useful for `spec.definition` in API entities.

Example

```yaml
kind: API
...
spec:
  type: openapi
  definition:
    $text: ./api-definition.yaml
```

## Actual Behavior

Catalog throws an error when processing API entities where `$test` is either a relative local path or an absolute local path. It works only with URLs.

```
2022-10-28T12:16:01.069Z catalog warn Processor PlaceholderProcessor threw an error while preprocessing; caused by Error:
Placeholder $text could not form a URL out of /Users/himanshumishra/workspace/backstage/packages/catalog-
model/examples/apis/petstore-api.yaml and ./my-api-definition.yaml, Error: URL parsing failed. type=plugin entity=api:default/petstore
```

## Steps to Reproduce

Update an API definition where `$text` points to a local file path

## Context

Looking into the [processor code](https://github.com/backstage/backstage/blob/834a7d906b2c697a0bf07ff1e967f7e0cc59298e/plugins/catalog-backend/src/modules/core/PlaceholderProcessor.ts#L249-L252), there is a comment saying the support for relative file is not there.

## Your Environment

- Browser Information: 

- Output of `yarn backstage-cli info`: 

```text
master branch of this repository
```

**Comment by awanlin** [comment]
Hi @OrkoHunter, should it be `$yaml` because you are pointing to a YAML file? I recently helped someone on Discord with this and they reported it worked: https://discord.com/channels/687207715902193673/1035213554065883146

**Comment by OrkoHunter** [comment]
Oh thank you @awanlin ! I did indeed try $yaml as well. Although looking at the conversation you point at, I am missing a `-` for the definitions, didn't know they are supposed to be a list. I'll try that out!

**Comment by OrkoHunter** [comment]
Unfortunately all of the alternatives give the same error to me

```
kind: API
...
spec:
  type: openapi
  definition:
    $text: ./api-definition.yaml
```

```
kind: API
...
spec:
  type: openapi
  definition:
    $yaml: ./api-definition.yaml
```

```
kind: API
...
spec:
  type: openapi
  definition:
    - $text: ./api-definition.yaml
```

```
kind: API
...
spec:
  type: openapi
  definition:
    - $text: ./api-definition.yaml
```

```
kind: API
...
spec:
  type: openapi
  definition: ./api-definition.yaml
```

**Comment by Rugvip** [comment]
I think the code you linked to explains it well, we don't support this, but we could, as long as we implement it in a secure way.

Seeing as the source entity file is already stored on disk I don't see any huge issues tbh, since you'd need access to modifying the file to begin with. There might be some processors that could mess with things though, and open up for remote attacks. Limiting with `resolveSafeChildPath` is nice, but it's not enough as the only protection. That would give you access to this entire repo and config files, seeing as we have the catalog info file in the root.

I'm open to suggestions :grin:

**Comment by OrkoHunter** [comment]
Thanks for the response @Rugvip, I was going crazy :P

**Comment by doemEINS** [comment]
@OrkoHunter interestingly, I just had success with registering an API/Service with the following in `catalog-info.yaml`:
```
kind: API
[...]
spec:
  type: openapi
  definition:
    $text: ./src/main/resources/oas/swagger.yaml
```

**Comment by OrkoHunter** [comment]
@doemEINS Oh awesome! I wonder if that still works if the `catalog-info.yaml` is registered locally instead of from a URL? In my case, I have a local instance where my `catalog-info.yaml` is registered locally using `catalog.locations` in `app-config.yaml`.

**Comment by JefferoNW** [comment]
I am running into this same issue and have not been able to resolve it.

I have a local `app-config.yaml` file that references a local `catalog-info.yaml` file.
And I am trying to reference a local `MYswagger.yaml` file using the following:

```
spec:
  type: openapi
  ...
  definition:
    $yaml: ./MYswagger.yaml
```

But I recieve an error:

```
warn Processor PlaceholderProcessor threw an error while preprocessing; caused by Error: Placeholder $yaml could not form a URL out of /Users/xxx/backstage/my-backstage/my_entities/catalog-info.yaml and ./MYswagger.yaml, TypeError [ERR_INVALID_URL]: Invalid URL type=plugin entity=api:default/MYswagger location=file:/Users/xxx/backstage/my-backstage/my_entities/catalog-info.yaml
```
I tried most every permutation that I have seen ($text, $yaml, -, $file, $include, ...) but can't get arround this error.

Did anyone find a functional solution? @OrkoHunter, @doemEINS ?

Thanks - Jeff
