### ISSUE TITLE
AsyncApi $ref with local file not possible

### ISSUE THREAD

**Issue by benkeil** [backstage/backstage#14490]
### 📜 Description

When ii use an `$ref` to an local file I get an error

The specification is located at `docs/specifications/asyncapi.yaml` 

When I try with an absolute path

```yaml
components:
  messages:
    SearchVariationV1:
      name: SearchVariation.v1
      contentType: application/json
      payload:
        $ref: "/code/src/main/resources/json/search-variation.json"
```

When I try with a relative path

```yaml
components:
  messages:
    SearchVariationV1:
      name: SearchVariation.v1
      contentType: application/json
      payload:
        $ref: "../../code/src/main/resources/json/search-variation.json"
```

### 👍 Expected behavior

Should load the schema definition

### 👎 Actual Behavior with Screenshots

```
Error: This is not a valid AsyncAPI Schema Object.
65./components/messages/SearchVariationV1/payload should be object,boolean
```

### 👟 Reproduction steps

Upload a async api specification with a ref to a local file.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!
