### ISSUE TITLE
🐛 Bug Report: 

### ISSUE THREAD

**Issue by matteosilv** [backstage/backstage#14552]
### 📜 Description

Running the container with unpredictable uid and gid (the new node unprivileged user suggested in the documentation) can lead to inconsistent behavior, especially when mounting volumes. 

### 👍 Expected behavior

We should edit the documentation to create a predictable uid and gid for the container:

```
# Create user and group with predictable uid and gid
RUN groupadd --gid 1000 node && useradd --uid 1000 --gid 1000 node
```

### 👎 Actual Behavior with Screenshots

I run a job to fix permissions of a mounted volume and get:

```
k logs fix-permission-4chd5
chown: unknown user/group node:node
```

### 👟 Reproduction steps

1. Start with a previous deployment and a mounted folder with files created as root
2. Update the container as suggested in the backstage.io doc
3. try to run a job to let node user chown volume files

```yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: fix-permission
spec:
  template:
    spec:
      volumes:
      - name: my-volume
        persistentVolumeClaim:
          claimName: my-volume-claim
      containers:
      - command:
        - chown
        - -R
        - node:node
        - /workdir
        image: busybox
        name: fix-permission
        resources: {}
        volumeMounts:
        - mountPath: /workdir
          name: my-volume
      restartPolicy: Never
status: {}
``` 

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)
