### ISSUE TITLE
💬 RFC: Adding Overrides to `Kind:Location`

### ISSUE THREAD

**Issue by Sarabadu** [backstage/backstage#14596]
### 🔖 Need

Index external entities overriding some metadata

In some cases, we want to index external components and have proper ownership inside our company context.

#### Open Source components

We have a dedicated team in charge of collaborating on Open source project i.e. Backstage, we want to keep all the component references and docs, but we want to modify who own that inside our organization context

#### Managing "Client code" in Software factories

Inside a software factory we built software for a Client, if both parts have a backstage instance, the ownership could change depending on each instance 

in both cases, we have one unique entity that could be shared between two or more organizations 

### 🎉 Proposal

I propose to add a new field to the `Location` kind that allow overrides partial metadata on the final entity

example, let's say my team `cool-team` is the owner of `backstage` inside my organization. We want to ingest the [`catalog-info.yaml`](https://github.com/backstage/backstage/blob/master/catalog-info.yaml) but `owner:CNCF` is not really useful on our org

We can create a Location entity Inside our org looking like this:

```yml
apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: open-source-components
  description: Redirects to external open source components
spec:
  target: https://github.com/backstage/backstage/blob/master/catalog-info.yaml
  override:
    metadata:
      namespace: oss
    spec:
      owner: cool-team
```

Adding a new `override` that accepts an object of fields to override, in this case we want to change the final entity to have `metadata.namespace` equal to `oss` and `spec.owner` equal to `cool-team`

After ingestion we can end up with this entity inside our org:

```yml
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage
  namespace: oss
  description: |
    Backstage is an open-source developer portal that puts the developer experience first.
  links:
    - title: Website
      url: http://backstage.io
    - title: Documentation
      url: https://backstage.io/docs
    - title: Storybook
      url: https://backstage.io/storybook
    - title: Discord Chat
      url: https://discord.com/invite/EBHEGzX
  annotations:
    github.com/project-slug: backstage/backstage
    backstage.io/techdocs-ref: dir:.
    lighthouse.com/website-url: https://backstage.io
spec:
  type: library
  owner: cool-team
  lifecycle: experimental
```

Note that we only override some field but keep the original `catalog-info` as source of true for the annotations, links, etc..

### 〽️ Alternatives

- We can create a copy of the final `catalog-info` inside our org and modify the fields directly, this could reduce the complexity but requires manual updates to sync all the field that we want to keep from the original `catalog-info`
- We can create a custom Kind to have this override behavior instead of modifying the Location

### ❌ Risks

- This feature splits the source of truth of our entities, this could bring some confusion in understanding the final ingested entity 
- Overriding simple fields as `owner` or `namespace` can be easy, but some array fields could be tricker to implement or should have some "all or nothing" constraints
- Having Location of  multiple Locations has also constraints, the override will apply to all the ingested entities(i.e. ingesting [this](https://github.com/backstage/backstage/blob/master/packages/catalog-model/examples/all.yaml) with one owner override will apply the same override on all the components on that tree)
- The schema for the Override field should probably be limited to the "Common to all" fields to scope down the complexity

### 👀 Have you spent some time to check if this RFC has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)
