### ISSUE TITLE
🚀 Feature: AWS Cognito UserPool EntityProvider for OrgData

### ISSUE THREAD

**Issue by LukvonStrom** [backstage/backstage#14612]
### 🔖 Feature description

Creation of a Cognito UserPool Entity Provider, that imports OrgData like Users and Groups. The resulting Entity Provider would be fairly-standard and could be set up in `packages/backend/src/plugins/catalog.ts`.

### 🎤 Context

With Cognito UserPools, AWS offers its own OAuth2 compliant Identity Provider, with integrated User directory management functionality. 
Cognito User Pools expose their directory data in one consistent API, regardless of the origin (federated/created), while also offering different integrations for AWS Application Load Balancers, API Gateway, ...     
The consistent API makes Cognito a very interesting target for importing users and the org structure in Cognito (i.e. groups) into Backstage. Additionally Backstage already supports signing in via Cognito, by exposing the ALB Auth Proxy Provider ( [aws-alb provider](https://github.com/backstage/backstage/blob/master/plugins/auth-backend/src/providers/aws-alb/provider.ts) ).

### ✌️ Possible Implementation

For the reasons laid out above, an EntityProvider, calling `paginateListGroups`, `paginateListUsersInGroup` and `paginateListUsers` from the [Cognito JS SDK](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-cognito-identity-provider/index.html) and outputting correct `User` and `Group` Entities should be created.

### Considerations
There are several questions that arise with creating this provider:

#### Finding the correct package for the Entity Provider
At the moment I'm undecided, as to where the Entity Provider should live. These options could be feasible:
- As a separate plugin in the backstage repo (i.e. `catalog-backend-module-aws-cognito`)
- Under `catalog-backend-module-aws/src/providers` (provided, the documentation section is renamed from `https://backstage.io/docs/integrations/aws-s3` to `https://backstage.io/docs/integrations/aws`)

#### AWS Credentials
This proposed entity provider is a prime candidate for the mechanism described in #12844.

In case the `catalog-backend-module-aws` is chosen as the designated package for this entity provider, this would require a breaking re-write of the [AwsS3EntityProvider.ts](https://github.com/backstage/backstage/blob/master/plugins/catalog-backend-module-aws/src/providers/AwsS3EntityProvider.ts) at the very least, to provide a unified behaviour in the plugin.
With this hypothetical rewrite, corresponding documentation for @clareliguori 's Auth Provider could be moved to the then new `https://backstage.io/docs/integrations/aws` docs site.

#### Configuration
I would envision a simple setup in `packages/backend/src/plugins/catalog.ts`:
```
builder.addEntityProvider(
    ...CognitoUserPoolProvider.fromConfig(env.config, {
      logger: env.logger,
      // optional: alternatively, use scheduler in app-config.yaml
      schedule: env.scheduler.createScheduledTaskRunner({
        frequency: { minutes: 30 },
        timeout: { minutes: 3 },
      }),
      // optional: alternatively, use schedule
      scheduler: env.scheduler,
    }),
  );
```
The plugin should be able to support 1 or `n` User Pools, taking the ARN of the UserPool(s) and optionally a schedule as config.

Thus this single UserPool Config should be valid:
```yaml
catalog:
  providers:
    awsCognito:
      userPoolArn: 'arn:aws:cognito-idp:us-east-1:1234567890:userpool/us-east-1_UPID'
      schedule: # optional
        # supports cron, ISO duration, "human duration" as used in code
        frequency: { minutes: 30 }
        # supports ISO duration, "human duration" as used in code
        timeout: { minutes: 3 }
```

Multi Pool Config should be possible as well:
```yaml
catalog:
  providers:
    awsCognito:
      userPool1:
        userPoolArn: 'arn:aws:cognito-idp:us-east-1:1234567890:userpool/us-east-1_UPID'
        schedule: # optional
          frequency: { minutes: 30 }
          timeout: { minutes: 3 }
      userPool2:
        userPoolArn: 'arn:aws:cognito-idp:us-east-1:1234567890:userpool/us-east-1_UPID2'
        schedule: 
          frequency: { minutes: 15 }
          timeout: { minutes: 3 }
```

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!
