### ISSUE TITLE
🐛 Bug Report: Backend docker container doesn't start up with production environment

### ISSUE THREAD

**Issue by laxmaneppalagudem** [backstage/backstage#14694]
### 📜 Description

Hello. I've separated my frontend and backend into two different docker containers and am trying to start my backend container with a production environment but it always loads with development environment.
My backend container is built using a multi stage build as shown [here](https://github.com/backstage/backstage/blob/master/docs/deployment/docker.md#multi-stage-build) with the only difference being the final command executed as follows: CMD ["node", "packages/backend", "--config", "app-config.production.yaml"]
As per [this](https://github.com/backstage/backstage/issues/2889) issue mentioning the config file should load it in a production environment but it doesn't do so and all requests to backend still have a `env=development ` argument passed in the URL.

### 👍 Expected behavior

Building and running the backend container with the initiating command to use app-config.production.yaml should change the appEnv to `production` and should use production config mentioned in the yaml file.

### 👎 Actual Behavior with Screenshots

Instead it keeps trying to call the backend with `env=development`. In the screenshot below you can see the frontend calling http://localhost:7007/api/auth/okta/refresh?optional=&env=development even though the backend was loaded with production config file and fails as my app-config.production.yaml only has providers configured for production and not development
<img width="1926" alt="Screen Shot 2022-11-17 at 9 17 25 PM" src="https://user-images.githubusercontent.com/8762782/202630832-bcf70265-46af-4218-bae4-885365151b73.png">

### 👟 Reproduction steps

This is the contents of app-config.production.yaml that's loaded in the backend container:
```
app:
  title: test Backstage App
  baseUrl: http://localhost:3000

organization:
  name: test

backend:
  baseUrl: http://localhost:7007
  listen:
    port: 7007

  csp:
    default-src: ["'self'"]
    connect-src: ["'self'", 'http:', 'https:']
    image-src: ["'self'", "cloud.google.com", "storage.googleapis.com"]
    script-src: ["'self'"]

  cors:
    origin: http://localhost:3000
    methods: [GET, POST, PUT, DELETE]
    credentials: true

  database:
    client: pg
    connection:
      host: ${DB_HOST}
      port: ${DB_PORT}
      user: ${DB_USER}
      password: ${DB_PWD}
  cache:
    store: memory
  auth:
    keys:
      - secret: ${BACKEND_AUTH_KEY}
  # workingDirectory: /tmp # Use this to configure a working directory for the scaffolder, defaults to the OS temp-dir

integrations:
  github:
    - host: ${GITHUB_HOST}
      apps:
        - $include: github-app-creds.yaml

proxy:
  '/snyk':
    target: https://snyk.io/api/v1
    headers:
      User-Agent: tech-services/backstage-plugin/1.0
      Authorization: token ${SNYK_TOKEN}
  '/test':
    target: 'https://example.com'
    changeOrigin: true

techdocs:
  builder: 'local' # Alternatives - 'external'
  generator:
    runIn: 'docker' # Alternatives - 'local'
  publisher:
    type: 'local' # Alternatives - 'googleGcs' or 'awsS3'. Read documentation for using alternatives.

auth:
  # see https://backstage.io/docs/auth/ to learn about auth providers
  environment: production
  providers:
    okta:
      production:
        clientId: ${AUTH_OKTA_CLIENT_ID}
        clientSecret: ${AUTH_OKTA_CLIENT_SECRET}
        audience: ${AUTH_OKTA_DOMAIN}
    github:
      production:
        $include: github-app-creds.yaml

scaffolder:
  # see https://backstage.io/docs/features/software-templates/configuration for software template options

catalog:
  import:
    entityFilename: catalog-info.yaml
    pullRequestBranchName: backstage-integration
  rules:
    - allow: [Domain, Component, System, API, Resource, Location, Group, User]
  providers:
    okta:
      - orgUrl: 'https://company.okta.com'
        token: ${OKTA_TOKEN}
```
And my backend docker file is similar to [this](https://github.com/backstage/backstage/blob/master/docs/deployment/docker.md#multi-stage-build) with the only difference being the final command executed as follows: CMD ["node", "packages/backend", "--config", "app-config.production.yaml"]

Image build command:
docker image build -f Dockerfile.backend -t bkbe .

Container run command(.envdev has the values for env variable referenced in app-config.production.yaml):
docker run --net backstage-net -p 7007:7007 --env-file .envdev bkbe

### 📃 Provide the context for the Bug.

I'm trying to run the backend and frontend containers in a kubernetes production environment and would expect it to run with the production env.

### 🖥️ Your Environment

yarn backstage-cli info output:
yarn backstage-cli info
yarn run v1.22.19
$ /Users/laxmaneppalagudem/github_repos/backstage/backstage/node_modules/.bin/backstage-cli info
OS:   Darwin 21.6.0 - darwin/arm64
node: v16.16.0
yarn: 1.22.19
cli:  0.18.1 (installed)
backstage:  1.5.1

Dependencies:
  @backstage/app-defaults                          1.0.5
  @backstage/backend-common                        0.15.0
  @backstage/backend-plugin-api                    0.1.1
  @backstage/backend-tasks                         0.3.4
  @backstage/catalog-client                        1.0.4
  @backstage/catalog-model                         1.1.0
  @backstage/cli-common                            0.1.9
  @backstage/cli                                   0.18.1
  @backstage/config-loader                         1.1.3
  @backstage/config                                1.0.1
  @backstage/core-app-api                          1.0.5
  @backstage/core-components                       0.11.0, 0.9.5
  @backstage/core-plugin-api                       1.0.5
  @backstage/errors                                1.1.0
  @backstage/integration-react                     1.1.3
  @backstage/integration                           1.3.0
  @backstage/plugin-api-docs                       0.8.8
  @backstage/plugin-auth-backend                   0.15.1
  @backstage/plugin-auth-node                      0.2.4
  @backstage/plugin-catalog-backend                1.3.1
  @backstage/plugin-catalog-common                 1.0.5
  @backstage/plugin-catalog-graph                  0.2.20
  @backstage/plugin-catalog-import                 0.8.11
  @backstage/plugin-catalog-node                   1.0.1
  @backstage/plugin-catalog-react                  1.1.3
  @backstage/plugin-catalog                        1.5.0
  @backstage/plugin-explore-react                  0.0.20
  @backstage/plugin-explore                        0.3.39
  @backstage/plugin-github-actions                 0.5.8
  @backstage/plugin-org                            0.5.8
  @backstage/plugin-permission-common              0.6.3
  @backstage/plugin-permission-node                0.6.4
  @backstage/plugin-permission-react               0.4.4
  @backstage/plugin-proxy-backend                  0.2.29
  @backstage/plugin-scaffolder-backend             1.5.1
  @backstage/plugin-scaffolder-common              1.1.2
  @backstage/plugin-scaffolder                     1.5.0
  @backstage/plugin-search-backend-module-pg       0.3.6
  @backstage/plugin-search-backend-node            1.0.1
  @backstage/plugin-search-backend                 1.0.1
  @backstage/plugin-search-common                  1.0.0
  @backstage/plugin-search-react                   1.0.1
  @backstage/plugin-search                         1.0.1
  @backstage/plugin-tech-radar                     0.5.15
  @backstage/plugin-techdocs-backend               1.2.1
  @backstage/plugin-techdocs-module-addons-contrib 1.0.3
  @backstage/plugin-techdocs-node                  1.3.0
  @backstage/plugin-techdocs-react                 1.0.3
  @backstage/plugin-techdocs                       1.3.1
  @backstage/plugin-user-settings                  0.4.7
  @backstage/release-manifests                     0.0.5
  @backstage/test-utils                            1.1.3
  @backstage/theme                                 0.2.16
  @backstage/types                                 1.0.0
  @backstage/version-bridge                        1.0.1
✨  Done in 1.42s.

Browser info:
Google chrome: Version 107.0.5304.87 (Official Build) (arm64)
Firefox: Version 105.0.2

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)
