### ISSUE TITLE
🚀 Feature: Make the Azure DevOps Entity Provider multi project

### ISSUE THREAD

**Issue by MarcBruins** [backstage/backstage#14716]
### 🔖 Feature description

Right now for the Azure DevOps EntityProvider you need to specify a project like so:

```
catalog:
  providers:
  azureDevOps:
    someId: 
      organization: 'MyOrg'
      project: 'MyProjectName'
      repository: '*' 
      path: catalog-info.yaml
```

What would be useful for companies with multiple projects is to use a wildcard just as for the repository specification:

```
catalog:
  providers:
  azureDevOps:
    someId: 
      organization: 'MyOrg'
      project: '*'
      repository: '*' 
      path: catalog-info.yaml
```

### 🎤 Context

In my use-case we have over 30 projects that change dynamically and I have seen multiple users in the issues having the same issue.

Related: #10431 

### ✌️ Possible Implementation

It seems that the AzureDevOpsEntityProvider calls the codesearch API for Azure Devops here: https://github.com/backstage/backstage/blob/master/plugins/catalog-backend-module-azure/src/lib/azure.ts#L50

However, that call is opinionated towards a must-have project. That URL doesn't need a project as stated in the docs: https://learn.microsoft.com/en-us/rest/api/azure/devops/search/code-search-results/fetch-code-search-results?view=azure-devops-rest-7.1&tabs=HTTP#examples

I would suggest that we use the baseurl from the start without a project:

```
  const searchUrl = `${searchBaseUrl}/${org}/${project}/_apis/search/codesearchresults?api-version=6.0-preview.1`;

```

to 

```
  const searchUrl = `${searchBaseUrl}/${org}/_apis/search/codesearchresults?api-version=7.0-preview.1`;
```

And then, if there is a project specified, set the `filter` object on the post call:

```
 "filters": {
    "Project": [
      "MyProject"
    ]
  },
```

I tested these calls with postman, and they work. I'm uncertain if more things need to change.

I would love to contribute, but I don't know how to debug the plugin effectively and change things around. If somebody can help me get started, that would be great!

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!
