### ISSUE TITLE
🐛 Bug Report: deleting and importing a component results in a NotFoundError during re-import

### ISSUE THREAD

**Issue by derwasp** [backstage/backstage#14982]
### 📜 Description

Re-importing components doesn't work after they have been deleted from backstage.

### 👍 Expected behavior

Re-importing should just work.

### 👎 Actual Behavior with Screenshots

Re-import fails with the following message:
`The following locations already exist in the catalog`

And then after clicking refresh, this is the actual error:

```
{
   "error":{
      "name":"NotFoundError",
      "message":"Entity component:default/foo-bar not found"
   },
   "request":{
      "method":"POST",
      "url":"/refresh"
   },
   "response":{
      "statusCode":404
   }
}
```

## Screenshot
<img width="600" alt="image" src="https://user-images.githubusercontent.com/10754345/205259793-d53269c8-9407-41a1-8e90-7e3a1b666f28.png">

### 👟 Reproduction steps

To the best of my memory, this is what happened:

1) Create a few components: `catalog-info.yaml` and `rest-api-entity.yaml`
2) Upload these components to a *branch* of a repository
3) Import both components via `catalog-import` with URLs pointing to the repository
4) Merge the branch into `main`
5) Delete the existing entities in backstage
6) Try re-importing
7) When you see the "locations already exitst" message, try hitting refresh and observe the error message below:

<img width="600" alt="image" src="https://user-images.githubusercontent.com/10754345/205259793-d53269c8-9407-41a1-8e90-7e3a1b666f28.png">

I also tried manually deleting the locations, now they don't show in search. Yet, the message is still there and it is preventing me from re-importing the `catalog-info.yaml` file.

### catalog-info.yaml

```yml
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: foo-bar
spec:
  type: service
  owner: the-foo-bar-crew
  lifecycle: production
  providesApis:
    - foo-bar-api
```

### rest-api-entity.yaml

```yml
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: foo-bar-api
  description: An awesome foobar service, now in Backstage
spec:
  type: openapi
  lifecycle: production
  owner: the-foo-bar-crew
  definition:
    $text: ./../../src/foo-bar-openapi.yaml
```

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None
