### ISSUE TITLE
🐛 Bug Report: Scaffolder auth via `createDefaultApiFactory` fails with custom SCM hosts

### ISSUE THREAD

**Issue by nv-alaiacano** [backstage/backstage#15076]
### 📜 Description

I am doing SCM integration with both github.com and an internally hosted Gitlab. My ScmAuth configuration in `apis.ts` looks like this:

```typescript
export const apis: AnyApiFactory[] = [
  createApiFactory({
    api: scmIntegrationsApiRef,
    deps: { configApi: configApiRef },
    factory: ({ configApi }) => ScmIntegrationsApi.fromConfig(configApi),
  }),
  ScmAuth.createDefaultApiFactory(),
];
```

The issue that I am having is that `createDefaultApiFactory` does not provide the ability to pass the custom host for the domain here: https://github.com/backstage/backstage/blob/a929ef20d344cabfe639a43d75acaf0d26ed2831/packages/integration-react/src/api/ScmAuth.ts#L103-L108

**There is a reasonable workaround** which is to manually configure the Github and Gitlab auth like this, where I can pass the host. If this workaround is considered sufficient, is there a way for me to fetch this host from `app-config.yaml` (or elsewhere) so that I don't have to provide it manually again?

```typescript
export const apis: AnyApiFactory[] = [
  createApiFactory({
    api: scmIntegrationsApiRef,
    deps: { configApi: configApiRef },
    factory: ({ configApi }) => ScmIntegrationsApi.fromConfig(configApi),
  }),
  createApiFactory({
    api: scmAuthApiRef,
    deps: { gitlabAuthApi: gitlabAuthApiRef, githubAuthApi: githubAuthApiRef },
    factory: ({ gitlabAuthApi, githubAuthApi }) =>
      ScmAuth.merge(
        ScmAuth.forGithub(githubAuthApi),
        ScmAuth.forGitlab(gitlabAuthApi, {
          host: 'gitlab.mycompany.com',
        }),
      ),
  }),
];
```

### 👍 Expected behavior

I expected `createDefaultApiFactory` to pick up my custom Gitlab host that I defined in `app-config.yaml`:

```yaml
auth:
  providers:
    gitlab:
      development:
        clientId: ${AUTH_GITLAB_CLIENT_ID}
        clientSecret: ${AUTH_GITLAB_CLIENT_SECRET}
        audience: https://gitlab.mycompany.com
```

I also have this host configured in my `allowedHosts` field of the `RepoUrlPicker` Scaffolder template, which is a little confusing but I think I understand why it is in both places.

### 👎 Actual Behavior with Screenshots

This error comes up after I populate both the `Owner` and `Repository` fields of the `RepoUrlPicker`

<img width="1002" alt="Screen Shot 2022-12-07 at 6 24 17 AM" src="https://user-images.githubusercontent.com/108741458/206166966-b3a25906-b4cf-4c91-891f-a7468092d661.png">

### 👟 Reproduction steps

* Have a self-hosted SCM service. Mine is gitlab, but I think any of them would work to reproduce.
* Make a scaffolder template that uses `RepoUrlPicker` (mine is below)
* Try to create a new component.

Basic template I am using (replace `gitlab.mycompany.com` with your :

```yaml
apiVersion: scaffolder.backstage.io/v1beta3
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-template
kind: Template
metadata:
  name: example-template
  title: Basic Java Service
  description: A very basic Java service for internal prototypes.
spec:
  owner: user:guest
  type: service

  # These parameters are used to generate the input form in the frontend, and are
  # used to gather input data for the execution of the template.
  parameters:
    - title: Fill in some steps
      required:
        - name
      properties:
        name:
          title: Name
          type: string
          description: Unique name of the component
          ui:autofocus: true
          ui:options:
            rows: 5
    - title: Choose a destination location
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            # Here's the option you can pass to the RepoUrlPicker
            requestUserCredentials:
              secretsKey: USER_OAUTH_TOKEN
              additionalScopes:
                github:
                  - workflow
            allowedHosts:
              - gitlab.mycompany.com

  # These steps are executed in the scaffolder backend, using data that we gathered
  # via the parameters above.
  steps:
    # Each step executes an action, in this case one templates files into the working directory.
    - id: fetch-base
      name: Fetch Base
      action: fetch:template
      input:
        url: ./content
        values:
          name: ${{ parameters.name }}

    # This step publishes the contents of the working directory to GitHub.
    - id: publish
      name: Publish
      action: publish:gitlab
      input:
        allowedHosts:
          - gitlab.mycompany.com
        description: This is ${{ parameters.name }}
        repoUrl: ${{ parameters.repoUrl }}
        # here's where the secret can be used
        token: ${{ secrets.USER_OAUTH_TOKEN }}

    # The final step is to register our new component in the catalog.
    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps.publish.output.repoContentsUrl }}
        catalogInfoPath: '/catalog-info.yaml'

  # Outputs are displayed to the user after a successful execution of the template.
  output:
    links:
      - title: Repository
        url: ${{ steps.publish.output.remoteUrl }}
      - title: Open in catalog
        icon: catalog
        entityRef: ${{ steps.register.output.entityRef }}
```

Auth in `app-config.yaml`

```yaml
auth:
  providers:
    gitlab:
      development:
        clientId: ${AUTH_GITLAB_CLIENT_ID}
        clientSecret: ${AUTH_GITLAB_CLIENT_SECRET}
        audience: https://gitlab.mycompany.com
```

### 📃 Provide the context for the Bug.

I think I provided enough context above but am happy to answer more questions.

### 🖥️ Your Environment

```
OS:   Darwin 21.6.0 - darwin/arm64
node: v16.16.0
yarn: 1.22.19
cli:  0.19.0 (installed)
backstage:  1.6.0

Dependencies:
  @backstage/app-defaults                          1.0.7
  @backstage/backend-common                        0.15.1
  @backstage/backend-plugin-api                    0.1.2
  @backstage/backend-tasks                         0.3.5
  @backstage/catalog-client                        1.1.2
  @backstage/catalog-model                         1.1.3
  @backstage/cli-common                            0.1.10
  @backstage/cli                                   0.19.0
  @backstage/config-loader                         1.1.4
  @backstage/config                                1.0.4
  @backstage/core-app-api                          1.1.1
  @backstage/core-components                       0.11.2, 0.12.0
  @backstage/core-plugin-api                       1.1.0
  @backstage/dev-utils                             1.0.7
  @backstage/errors                                1.1.1, 1.1.3
  @backstage/integration-react                     1.1.5
  @backstage/integration                           1.4.0
  @backstage/plugin-api-docs                       0.8.9
  @backstage/plugin-app-backend                    0.3.36
  @backstage/plugin-auth-backend                   0.16.0
  @backstage/plugin-auth-node                      0.2.5
  @backstage/plugin-catalog-backend                1.4.0
  @backstage/plugin-catalog-common                 1.0.8
  @backstage/plugin-catalog-graph                  0.2.21
  @backstage/plugin-catalog-import                 0.8.12
  @backstage/plugin-catalog-node                   1.1.0
  @backstage/plugin-catalog-react                  1.2.1
  @backstage/plugin-catalog                        1.5.1
  @backstage/plugin-github-actions                 0.5.9
  @backstage/plugin-home                           0.4.26
  @backstage/plugin-jenkins-backend                0.1.26
  @backstage/plugin-jenkins-common                 0.1.8
  @backstage/plugin-jenkins                        0.7.8
  @backstage/plugin-org                            0.5.9
  @backstage/plugin-pagerduty                      0.5.2
  @backstage/plugin-permission-common              0.6.4, 0.7.1
  @backstage/plugin-permission-node                0.6.5
  @backstage/plugin-permission-react               0.4.7
  @backstage/plugin-proxy-backend                  0.2.30
  @backstage/plugin-scaffolder-backend             1.6.0
  @backstage/plugin-scaffolder-common              1.2.0
  @backstage/plugin-scaffolder                     1.6.0
  @backstage/plugin-search-backend-module-pg       0.4.0
  @backstage/plugin-search-backend-node            1.0.2
  @backstage/plugin-search-backend                 1.0.2
  @backstage/plugin-search-common                  1.1.1
  @backstage/plugin-search-react                   1.1.0
  @backstage/plugin-search                         1.0.2
  @backstage/plugin-stack-overflow                 0.1.6
  @backstage/plugin-tech-radar                     0.5.16
  @backstage/plugin-techdocs-backend               1.3.0
  @backstage/plugin-techdocs-module-addons-contrib 1.0.4
  @backstage/plugin-techdocs-node                  1.4.0
  @backstage/plugin-techdocs-react                 1.0.4
  @backstage/plugin-techdocs                       1.3.2
  @backstage/plugin-user-settings                  0.4.8
  @backstage/release-manifests                     0.0.6
  @backstage/test-utils                            1.2.1
  @backstage/theme                                 0.2.16
  @backstage/types                                 1.0.1
  @backstage/version-bridge                        1.0.2
```

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else
