### ISSUE TITLE
🚀 Feature: more cluster details in the catalog

### ISSUE THREAD

**Issue by jamieklassen** [backstage/backstage#15088]
### 🔖 Feature description

The `catalog` clusterLocator should support more `ClusterDetails` fields to make it a bit closer to the `config` clusterLocator in terms of features. As it stands, the `ClusterDetails` interface has many fields:

https://github.com/backstage/backstage/blob/1f5921be1461c947fe8e8518c2f8058c9ad8bac4/plugins/kubernetes-backend/src/types/types.ts#L147-L207

but the catalog clusterLocator only retrieves and surfaces four of them (`name`, `url`, `caData` and `authProvider`):

https://github.com/backstage/backstage/blob/1f5921be1461c947fe8e8518c2f8058c9ad8bac4/plugins/kubernetes-backend/src/cluster-locator/CatalogClusterLocator.ts#L53-L60

#### What works today

Here's my basic setup:

##### OIDC Authority

I create an azure AD app registration with

```console
$ export CLIENT_ID=$(az ad app create --display-name my-backstage --web-redirect-uris http://localhost:7007/api/auth/microsoft/handler/frame http://localhost:8000 | jq -r .appId)
$ export CLIENT_SECRET=$(az ad app credential reset --append --id $CLIENT_ID | jq -r .password)
```

##### OIDC-enabled K8s Cluster

I create a kind cluster with

```console
$ kind create cluster --config - <<EOF
apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
kubeadmConfigPatches:
- |-
  kind: ClusterConfiguration
  apiServer:
    extraArgs:
      oidc-client-id: CLIENT-ID
      oidc-issuer-url: https://login.microsoftonline.com/TENANT-ID/v2.0
      oidc-username-claim: email
EOF
```

where `CLIENT-ID` is the ID for the app registration I created previously, and `TENANT-ID` is the ID of my azure AD tenant.

Then I set up some RBAC on that cluster

```console
$ kubectl create clusterrolebinding me-admin --user EMAIL-ADDRESS --clusterrole cluster-admin
```

Where `EMAIL-ADDRESS` is the email of my Azure account. Then, just to verify, I set up my kubeconfig to use `kubelogin` by running

```console
$ kubectl config set-credentials kind-oidc \
  --exec-api-version=client.authentication.k8s.io/v1beta1 \
  --exec-command=kubectl \
  --exec-arg oidc-login \
  --exec-arg get-token \
  --exec-arg --oidc-issuer-url=https://login.microsoftonline.com/TENANT-ID/v2.0 \
  --exec-arg --oidc-client-id=$CLIENT_ID \
  --exec-arg --oidc-client-secret=$CLIENT_SECRET \
  --exec-arg --oidc-extra-scope=email
$ kubectl config set-context kind-kind --user kind-oidc
```

So that running `kubectl get ns` causes my browser to pop up an azure AD login before succesfully showing my namespaces.

##### Backstage

My app-config looks like

```yaml
auth:
  environment: development
  providers:
    microsoft:
      development:
        clientId: CLIENT-ID
        clientSecret: CLIENT-SECRET
        tenantId: TENANT-ID
kubernetes:
  serviceLocatorMethod:
    type: 'multiTenant'
  clusterLocatorMethods:
    - type: config
      clusters:
      - name: kind
        url: https://127.0.0.1:PORT
        caData: KIND-CA-DATA
        authProvider: oidc
        oidcTokenProvider: microsoft
        skipMetricsLookup: true
catalog:
  locations:
    - type: file
      target: ../../kubernetes.yaml
      rules:
        - allow: [User, Component, Resource]
```

where `CLIENT-ID`, `CLIENT-SECRET`, and `TENANT-ID` are as discussed above, and `PORT` is the port on which my kind apiserver is running, and `KIND-CA-DATA` is the base64-encoded CA bundle for the kind apiserver (pulled from my kubeconfig).

where `kubernetes.yaml` itself contains

```yaml
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: kube-dns
  annotations:
    'backstage.io/kubernetes-label-selector': 'k8s-app=kube-dns'
spec:
  type: service
  lifecycle: stable
  owner: user:guest
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: me
  annotations:
    'microsoft.com/email': EMAIL-ADDRESS
spec:
  memberOf: []
```

where `EMAIL-ADDRESS` is as discussed above. Following all these steps, I can run `yarn dev` and open http://localhost:3000/catalog/default/component/kube-dns/kubernetes, get prompted to sign in to Microsoft, and see the coredns pods in my kind cluster.

#### What I want

Instead of specifying all my cluster details in the app-config, I'd like some way of specifying them in the catalog, so that my app-config would become

```yaml
auth:
  environment: development
  providers:
    microsoft:
      development:
        clientId: CLIENT-ID
        clientSecret: CLIENT-SECRET
        tenantId: TENANT-ID
kubernetes:
  serviceLocatorMethod:
    type: 'multiTenant'
  clusterLocatorMethods:
    - type: catalog
catalog:
  locations:
    - type: file
      target: ../../kubernetes.yaml
      rules:
        - allow: [User, Component, Resource]
```

and `kubernetes.yaml` could looke something like

```yaml
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: kind
  annotations:
    'kubernetes.io/api-server': https://127.0.0.1:PORT
    'kubernetes.io/api-server-certificate-authority': KIND-CA-DATA
    'kubernetes.io/auth-provider': oidc
    'kubernetes.io/oidc-token-provider': microsoft
    'kubernetes.io/skip-metrics-lookup': 'true'
spec:
  type: kubernetes-cluster
  owner: user:guest
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: kube-dns
  annotations:
    'backstage.io/kubernetes-label-selector': 'k8s-app=kube-dns'
spec:
  type: service
  lifecycle: stable
  owner: user:guest
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: me
  annotations:
    'microsoft.com/email': EMAIL-ADDRESS
spec:
  memberOf: []
```	

and still get the same experience. As it happens, if you try to run these config files with the code on master, the page will simply contain the error panel with the message

```text
Errors: authProvider "oidc" has no KubernetesAuthProvider defined for it
```

### ✌️ Possible Implementation

What comes to mind is adding new annotations for other Kubernetes cluster details to [@backstage/catalog-model](https://github.com/backstage/backstage/blob/master/packages/catalog-model/src/entity/constants.ts), and then having the [`CatalogClusterLocator`](https://github.com/backstage/backstage/blob/master/plugins/kubernetes-backend/src/cluster-locator/CatalogClusterLocator.ts) read them in its `getClusters` method and surface them in the clusterDetails appropriately.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!
