### ISSUE TITLE
🐛 Bug Report: Could not get GitLab project ID

### ISSUE THREAD

**Issue by lpsm-dev** [backstage/backstage#15095]
### 📜 Description

When I run a task on Backstage that interacts with a private repository on GitLab, I always get an error, even though the Gitlab integration is done according to the documentation. (https://backstage.io/docs/integrations/gitlab/locations):

```
"Error: Unable to read url, Error: Could not get GitLab project ID for: <project-url>-/blob/main/catalog-info.yaml
```

### 👍 Expected behavior

Register my catalog in Backstage.

![Screenshot 2022-12-07 at 16 03 17](https://user-images.githubusercontent.com/58797390/206272545-f3de9a77-3e41-40b0-b2e5-18141a10ce79.png)

## Backstage UI

![Screenshot 2022-12-07 at 14 01 33](https://user-images.githubusercontent.com/58797390/206270899-9e0f9467-cd31-49bb-b2b5-4b6831f69584.png)

## Backstage Logs

![Screenshot 2022-12-07 at 15 56 30](https://user-images.githubusercontent.com/58797390/206271284-a4a449dc-5bcd-435f-9880-d0e2421d57ff.png)

### 👟 Reproduction steps

1. Create a New Component
2. Choose your template
3. Follow the steps
4. Check Activity for task

**Integration**

```yaml
integrations:
  gitlab:
    - host: gitab.com
      token: <GITLAB-TOKEN>
      apiBaseUrl: https://gitlab.com/api/v4
      baseUrl: https://gitlab.com
```

## Context

- I'm using GitLab SAAS.

## Environment

My Backstage app runs in a Kubernetes cluster:

- EKS v1.22.15

## Template

```yaml
---
# Notice the v1beta3 version
apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
# Some metadata about the template itself
metadata:
  name: kubernetes-generic-service
  title: Kubernetes Generic Service
  description: Create a generic project structure to run a NGINX container in Kubernetes
  tags:
    - kubernetes
    - gitlab
spec:
  owner: team-devops
  type: service
  # These parameters are used to generate the input form in the frontend, and are
  # used to gather input data for the execution of the template.
  parameters:
    - title: Provide the information
      required:
        - name
        - owner
      properties:
        name:
          title: Name
          type: string
          description: Unique name of the component
          ui:autofocus: true
          ui:options:
            rows: 5
        description:
          title: Description
          type: string
          description: Help others understand what this website is for.
        owner:
          title: Owner
          type: string
          description: Owner of the component
          ui:field: OwnerPicker
          ui:options:
            allowedKinds:
              - Group
    - title: Choose a location
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - gitlab.com
            requestUserCredentials:
              secretsKey: USER_OAUTH_TOKEN
        dryRun:
          title: Only perform a dry run, don't publish anything
          type: boolean
          default: false
  # These steps are executed in the scaffolder backend, using data that we gathered
  # via the parameters above.
  steps:
    # Each step executes an action, in this case one templates files into the working directory.
    - id: template
      name: Fetch Template
      action: fetch:template
      input:
        url: ./template
        values:
          name: '${{ parameters.name }}'
          description: '${{ parameters.description }}'
          owner: '${{ parameters.owner }}'
          destination: '${{ parameters.repoUrl | parseRepoUrl }}'
    # This step publishes the contents of the working directory to GitLab.
    - id: publish
      if: '{{ not parameters.dryRun }}'
      name: Publish
      action: publish:gitlab
      input:
        allowedHosts: ['gitlab.com']
        repoUrl: '${{ parameters.repoUrl }}'
        gitCommitMessage: 'chore: initial project commit [skip ci]'
        gitAuthorName: 'xpto-services'
        gitAuthorEmail: 'xpto-services@email.com'
        defaultBranch: 'main'
        repoVisibility: 'private'
        token: '${{ secrets.USER_OAUTH_TOKEN }}'
    # The final step is to register our new component in the catalog.
    - id: register
      if: '{{ not parameters.dryRun }}'
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: '${{ steps.publish.output.repoContentsUrl }}'
        catalogInfoPath: '/catalog-info.yaml'
    # Step to just log information.
    - name: Results
      if: '{{ parameters.dryRun }}'
      action: debug:log
      input:
        message: |
          # Information
          ---------------
          name: ${{ parameters.name }}
          description: ${{ parameters.description }}
          owner: ${{ parameters.owner }}
          destination: ${{ parameters.repoUrl | parseRepoUrl }}
        listWorkspace: true
  # Outputs are displayed to the user after a successful execution of the template.
  output:
    links:
      - title: Repository
        url: '${{ steps.publish.output.remoteUrl }}'
      - title: Open in catalog
        icon: 'catalog'
        entityRef: '${{ steps.register.output.entityRef }}'
```

### 🖥️ Your Environment

```
OS:   Darwin 22.1.0 - darwin/arm64
node: v18.12.1
yarn: 1.22.19
cli:  0.21.1 (installed)
backstage:  1.8.0

Dependencies:
  @backstage/app-defaults                          1.0.8
  @backstage/backend-common                        0.16.0
  @backstage/backend-plugin-api                    0.1.4
  @backstage/backend-tasks                         0.3.7
  @backstage/catalog-client                        1.1.2
  @backstage/catalog-model                         1.1.3
  @backstage/cli-common                            0.1.10
  @backstage/cli                                   0.21.1
  @backstage/config-loader                         1.1.6
  @backstage/config                                1.0.4
  @backstage/core-app-api                          1.2.0
  @backstage/core-components                       0.11.2, 0.12.0
  @backstage/core-plugin-api                       1.1.0
  @backstage/errors                                1.1.3
  @backstage/integration-react                     1.1.6
  @backstage/integration                           1.4.0
  @backstage/plugin-api-docs                       0.8.11
  @backstage/plugin-app-backend                    0.3.38
  @backstage/plugin-auth-backend                   0.17.1
  @backstage/plugin-auth-node                      0.2.7
  @backstage/plugin-badges-backend                 0.1.32
  @backstage/plugin-badges                         0.2.35
  @backstage/plugin-catalog-backend                1.5.1
  @backstage/plugin-catalog-common                 1.0.8
  @backstage/plugin-catalog-graph                  0.2.23
  @backstage/plugin-catalog-import                 0.9.1
  @backstage/plugin-catalog-node                   1.2.1
  @backstage/plugin-catalog-react                  1.2.1
  @backstage/plugin-catalog                        1.6.1
  @backstage/plugin-code-coverage-backend          0.2.4
  @backstage/plugin-code-coverage                  0.2.4
  @backstage/plugin-explore-react                  0.0.23
  @backstage/plugin-explore                        0.3.42
  @backstage/plugin-gcalendar                      0.3.7
  @backstage/plugin-github-actions                 0.5.11
  @backstage/plugin-home                           0.4.27
  @backstage/plugin-kubernetes-backend             0.8.0
  @backstage/plugin-kubernetes-common              0.4.4
  @backstage/plugin-kubernetes                     0.7.4
  @backstage/plugin-org                            0.6.1
  @backstage/plugin-permission-backend             0.5.13
  @backstage/plugin-permission-common              0.7.1
  @backstage/plugin-permission-node                0.7.1
  @backstage/plugin-permission-react               0.4.7
  @backstage/plugin-proxy-backend                  0.2.32
  @backstage/plugin-scaffolder-backend             1.8.0
  @backstage/plugin-scaffolder-common              1.2.2
  @backstage/plugin-scaffolder                     1.8.0
  @backstage/plugin-search-backend-module-pg       0.4.2
  @backstage/plugin-search-backend-node            1.0.4
  @backstage/plugin-search-backend                 1.1.1
  @backstage/plugin-search-common                  1.1.1
  @backstage/plugin-search-react                   1.2.1
  @backstage/plugin-search                         1.0.4
  @backstage/plugin-shortcuts                      0.3.3
  @backstage/plugin-sonarqube-backend              0.1.3
  @backstage/plugin-sonarqube                      0.5.0
  @backstage/plugin-stack-overflow                 0.1.7
  @backstage/plugin-tech-radar                     0.5.18
  @backstage/plugin-techdocs-backend               1.4.1
  @backstage/plugin-techdocs-module-addons-contrib 1.0.6
  @backstage/plugin-techdocs-node                  1.4.2
  @backstage/plugin-techdocs-react                 1.0.6
  @backstage/plugin-techdocs                       1.4.0
  @backstage/plugin-todo-backend                   0.1.35
  @backstage/plugin-todo                           0.2.13
  @backstage/plugin-user-settings                  0.5.1
  @backstage/release-manifests                     0.0.7
  @backstage/test-utils                            1.2.2
  @backstage/theme                                 0.2.16
  @backstage/types                                 1.0.1
  @backstage/version-bridge                        1.0.2
✨  Done in 1.89s.
```

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, I don't have time to work on this right now
