### ISSUE TITLE
🐛 Bug Report: Azure AD organizational data doesn't appear after following the readme guide and no logs in pod to show errors

### ISSUE THREAD

**Issue by padupe** [backstage/backstage#15180]
### 📜 Description

I'm following the documentation to export users and groups from Azure to Backstage. Unfortunately, no information is rendered.

### 👍 Expected behavior

List of users and groups integrated into Backstage.

### 👎 Actual Behavior with Screenshots

Only the GitHub integration is functional.

### 👟 Reproduction steps

My `app-config.yaml`

```yaml
[...]

integrations:
  github:
    - host: github.com
      apps:
        - $include: github-app-backstage-cred.yaml
  azure:
    - host: dev.azure.com
      token: ${AZUREAD_TOKEN}

[...]

auth:
  # see https://backstage.io/docs/auth/ to learn about auth providers
  environment: production
  providers:
    github:
      production:
        clientId: ${GITHUB_AUTH_CLIENT_ID}
        clientSecret: ${GITHUB_AUTH_CLIENT_SECRET}
    microsoft:
      production:
        clientId: ${AZUREAD_CLIENTID}
        clientSecret: ${AZUREAD_CLIENTSECRET}
        tenantId: ${AZUREAD_TENANTID}

[...]

catalog:
  rules:
    - allow: [Component, Group, User, Resource, Location, Template]
  locations:
    - type: url
      target: https://github.com/raizen-devops/templates-backstage/blob/main/all.yaml
      rules:
        - allow: [Template]
  providers:
    github:
      raizenDevOps:
        organization: 'raizen-devops'
        catalogPath: '/catalog-info.yaml'
      raizenIt:
        organization: 'raizen-it'
        catalogPath: '/catalog-info.yaml'
    microsoftGraphOrg:
      default:
        tenantId: ${AZUREAD_TENANTID}
        clientId: ${AZUREAD_CLIENTID}
        clientSecret: ${AZUREAD_CLIENTSECRET}
        user:
          filter: accountEnabled eq true and userType eq 'member'
        group:
          filter: >
            securityEnabled eq false
            and mailEnabled eq true
            and groupTypes/any(c:c+eq+'Unified')

[...]
```

My `catalog.ts`
```ts
// packages/backend/src/plugins/catalog.ts
import { CatalogBuilder } from '@backstage/plugin-catalog-backend';
import { ScaffolderEntitiesProcessor } from '@backstage/plugin-scaffolder-backend';
import { Router } from 'express';
import { PluginEnvironment } from '../types';
import { GithubEntityProvider, GithubOrgEntityProvider } from '@backstage/plugin-catalog-backend-module-github';
import { MicrosoftGraphOrgEntityProvider } from '@backstage/plugin-catalog-backend-module-msgraph';

export default async function createPlugin(
  env: PluginEnvironment,
): Promise<Router> {
  const builder = await CatalogBuilder.create(env);
  builder.addEntityProvider(
    GithubEntityProvider.fromConfig(env.config, {
      logger: env.logger,
      schedule: env.scheduler.createScheduledTaskRunner({
        frequency: { minutes: 35 },
        timeout: { minutes: 30 }
      })
    }),
    GithubOrgEntityProvider.fromConfig(env.config, {
      id: 'raizen-devops',
      orgUrl: 'https://github.com/raizen-devops',
      logger: env.logger,
      schedule: env.scheduler.createScheduledTaskRunner({
        frequency: { minutes: 60 },
        timeout: { minutes: 15 },
      }),
    }),
  );
  builder.addEntityProvider(
    GithubOrgEntityProvider.fromConfig(env.config, {
      id: 'raizen-it',
      orgUrl: 'https://github.com/raizen-it',
      logger: env.logger,
      schedule: env.scheduler.createScheduledTaskRunner({
        frequency: { minutes: 60 },
        timeout: { minutes: 15 },
      }),
    }),
  );
  builder.addEntityProvider(
    MicrosoftGraphOrgEntityProvider.fromConfig(env.config, {
      logger: env.logger,
      schedule: env.scheduler.createScheduledTaskRunner({
        frequency: { minutes: 30 },
        timeout: { minutes: 15 },
        initialDelay: { seconds: 45 }
      })
    })
  );
  builder.addProcessor(new ScaffolderEntitiesProcessor());
  const { processingEngine, router } = await builder.build();
  await processingEngine.start();
  return router;
}
```

### 📃 Provide the context for the Bug.

Supporting documentation followed for implementation:
- [Azure Locations](https://backstage.io/docs/integrations/azure/locations)
- [Azure Org Data](https://backstage.io/docs/integrations/azure/org)

### 🖥️ Your Environment

- Linux / Ubuntu v20.04.5 LTS
- Node.js v16.18.0
- Backstage v1.8.1

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by jhaals** [comment]
Sorry to hear that you're having issues, are there any logs available if try running the backend locally? I'd suggest you try to only with the provider in question. I don't have experience with the `MicrosoftGraphOrgEntityProvider` but if there are any error output that could be relevant I'm sure @pjungermann or others in the community can help out.

**Comment by afscrome** [comment]
How many users & groups are in your AAD  instance ?  Your filters are trying to load almost every user and every group from your isntance, and you've set a timeout of 15 minutes.  If you have a large number of users and groups, you may not be giving the job enough time to run.

Do you see a log entry like the below.  This entry indicates that the job is starting to load data.
> catalog info Reading msgraph users and groups type=plugin class=MicrosoftGraphOrgEntityProvider taskId=MicrosoftGraphOrgEntityProvider:default:refresh taskInstanceId=9bbd5342-ab2e-4dc1-ac12-4243df06c512

Try changing your filters to load a single user and a single group, if this loads that would confirm the problem is with the timeout not matching the volume of data being loaded.

```yaml
user:
  filter: displayName eq 'John Doe'
group:
  filter: displayName eq 'A group'
```

Entity providers don't load data incrementally, so if the job dies part way through, you'll get no data loaded.

**Comment by padupe** [comment]
I adopted the following strategy, and managed to return some users:

```yaml
# catalog-info.yaml
[...]
microsoftGraphOrg:
      default:
        tenantId: ${AZUREAD_TENANTID}
        clientId: ${AZUREAD_CLIENTID}
        clientSecret: ${AZUREAD_CLIENTSECRET}
        queryMode: basic
        user:
          expand: manager
        userGroupMember:
          filter: "displayName eq 'Team Admin' or displayName eq 'Team Reader'"
        group:
          expand: member
          filter: "displayName eq 'Team Admin' or displayName eq 'Team Reader'"

[...]
```
