### ISSUE TITLE
🚀 Feature: scaffolder template composability

### ISSUE THREAD

**Issue by arhill05** [backstage/backstage#15241]
### 🔖 Feature description

When creating templates, I would like to be able to create a template that includes/extends existing templates so I don't have to duplicate steps between multiple templates, but preserve the ability to perform identical steps.

### 🎤 Context

Example: I have a template for adding an application to my OAuth provider. I also have a template for scaffolding an API project using our language of choice. Instead of having to execute these templates separately, I would like to create another template that calls the actions of the two templates that already exist, without having to literally duplicate the steps in another YAML file.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by jhaals** [comment]
Hi Andrew and thanks for the suggestion, I feel like this is something that has come up as a suggestion previously however I did not manage to find a related issue. @benjdlambert can you speak to the feasibility of having this feature in scaffolder or prior discussions about it?

**Comment by benjdlambert** [comment]
Hey @arhill05, so this has come up before here https://github.com/backstage/backstage/issues/13288 but I kinda lost some traction. To be honest I'm not sure what it would look like as a complete solution, but happy for some suggestions as to where we want to take it. Maybe also @taras is pretty interested in getting involved here too and coming up with some suggestions on what we can do to make this possible and what the API looks like.

**Comment by arhill05** [comment]
@benjdlambert I searched for issues related to this but I didn't search for "inheritance." Sorry about that!

As for a suggested solution, I think Azure DevOps does this pretty well with their YAML pipeline templates. Here's their docs on them: https://learn.microsoft.com/en-us/azure/devops/pipelines/process/templates?view=azure-devops

My team has several templates that make use of this functionality... here's a simple example:
```yaml
# TaskTemplates/Npm/node-version.yml
parameters:
  NodeVersion: '14.17.6'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: ${{ parameters.NodeVersion }}
```
```yaml
# TemplateWrappers/ui-release.yml
parameters:
  # Build Parameters
  NodeVersion: ''

jobs:

 ...

  steps:
  - template: /BuildTemplates/TaskTemplates/Npm/node-version.yml
    ${{ if ne(parameters.NodeVersion, '') }}:
      parameters:
        NodeVersion: ${{ parameters.NodeVersion }}
```

Obviously this is slimmed down for brevity, but this approach allows us to have several small "task templates" that we use to compose the bigger template wrapper used to execute the entire build.

I could see Backstage implementing something similar where you could introduce the idea of "fragments" or "templates" that we could use in something like this maybe:

```yaml
# fragments/parameter-fragment.yaml
parameters:
  - title: Application metadata
    properties:
      property1:
          title: Property 1
          description: First prop
          type: string
      property2:
          title: Property 2
          description: Second prop
          type: boolean
```
```yaml
# templates/my-template.yaml
apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: my-template
  title: Sample template
  description: Sample
spec:
  owner: backstage
  type: service
  parameters:
    - template: ../fragments/parameter-fragment.yaml
```

I'm just spitballing ideas here and I have no idea about the feasibility of such an approach... but I think something like this would make the Scaffolder much more powerful.

**Comment by arhill05** [comment]
@taras That looks like it would solve for what I'm attempting.

Pardon my ignorance, but what is Frontside? Is this something that I could use now?

**Comment by taras** [comment]
@arhill05 Frontside is a consulting company - [frontside.com](https://frontside.com). We do Backstage Enterprise Support and develop DX tools. Since BackstageCon, we started working on a new project that we call PlatformScript. It's a unified YAML Interpreter designed to enable composition of different YAML syntaxes. 

We did a [demo of using it for building UI in Backstage at the last Backstage Contributor Sessions](https://www.youtube.com/watch?v=0wyeO9ZUoO4) I'm going to start working on a backend plugin while we build out the documentation for the project.

If you need something that you can use today, then you could try using Placeholders which are described in this PR https://github.com/backstage/backstage/pull/13690. You could even create a placeholder that can give you import like functionality. 

For example, you could something like this

```
apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: my-template
  title: Sample template
  description: Sample
spec:
  owner: backstage
  type: service
  parameters:
    - $template: fragments/parameter-fragment.yaml
```
In the template placeholder, you could resolve "fragments/parameter-fragment.yaml` and return it's content to replace the value of the placeholder. It might give you enough for now.

**Comment by rocha-bruno** [comment]
@arhill05 At [Swissquote](https://swissquote.com/), we have a lot of templates and leverage the issue you are facing using only Backstage existing features.
Basically we have a centralized templates repository with a defaults folder containing reusable parameters and steps yaml files, and another folder called templates with one sub-folder per template containing the template.yaml files and some specific steps or parameters if needed.

Here is an example of a possible template.yaml for a Python service:
`apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: create-python-service
...
spec:
...
  parameters:
    # Archetype information of your new application (specific to python apps)
    - $yaml: ../../defaults/python/snippets/parameters/archetype-info.yaml

    # Business and Maintainers information (same for all apps)
    - $yaml: ../../defaults/snippets/parameters/ownership.yaml

    # Deployment (specific to this application)
    - $yaml: ./snippets/parameters/cicd-info.yaml

  steps:
    # Create repo   
    # Featch API that creates the API entity file (same for all services)
    - $yaml: ../../defaults/snippets/steps/fetch-api.yaml

    # Fetch base that creates the entity for Backstage (same for all apps)
    - $yaml: ../../defaults/snippets/steps/fetch-base.yaml

    # Publish repo to github (same for all apps)
    - $yaml: ../../defaults/snippets/steps/publish.yaml

    # Register in Backstage catalog (same for all apps)
    - $yaml: ../../defaults/snippets/steps/register.yaml

  output:
    links:
      - $yaml: ../../defaults/snippets/output/publish.yaml
      - $yaml: ../../defaults/snippets/output/show-catalog.yaml
`

And here is the example of one of the parameters files (/defaults/snippets/parameters/ownership.yaml) used by all the templates:

`title: Business and Maintainers information
required:
  - owner
properties:
  owner:
    title: Owner
    type: string
    description: Owner of the component
    ui:field: OwnerPicker
    ui:options:
      allowedKinds:
        - Group
  system:
    title: System of this component
    type: string
    description: name of the system to which this application belongs.
    ui:field: EntityPicker
    ui:options:
      allowedKinds:
        - System
      defaultKind: System`

Hope that could help. If you guys have any idea of how to make it better or more usable, I'm all ears :)

**Comment by rocha-bruno** [comment]
If you think this is good enough to be documented somewhere, it will be a pleasure to do it!
If yes, should this be integrated in the documentation (where?) or in the contrib section of the repo ?

**Comment by cthtrifork** [comment]
@rocha-bruno 
I have tried to copy to your setup but I am getting an error:
```log
Processor PlaceholderProcessor threw an error while preprocessing; caused by Error: Placeholder $yaml could not form a URL out of [redacted]/templates/deploy-component-team/deploy-hello-team-guided/template.yaml and ../../snippets/parameters/snippets/parameters/ownership.yaml, TypeError [ERR_INVALID_URL]: Invalid URL type=plugin entity=template:default/deploy-hello-team location=file:[redacted]/templates/deploy-component-team/deploy-hello-team-guided/template.yaml
```

The error comes from here:
https://github.com/backstage/backstage/blob/master/plugins/catalog-backend/src/modules/core/PlaceholderProcessor.ts#L253

If I am reading the code correctly, relative paths are not supported. How are you bypassing this?

**Comment by taras** [comment]
@cthtrifork relative path should work, they're just weird. They're relative to the backend process. Do you have the file located in the path where it's looking?

**Comment by cthtrifork** [comment]
Odd.
Yes relative to the actual template.

So in:
`/templates/deploy-component-team/deploy-hello-team-guided/template.yaml`
```yaml
apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: deploy-hello-team
  title: 3.x Deploy an hello-world service
...
spec:
  owner: cheetah-team
  type: gitops

  parameters:
    # Business and Maintainers information (same for all apps)
    - $yaml: "../../snippets/parameters/snippets/parameters/ownership.yaml"
 ```

And in
`/templates/snippets/parameters/ownership.yaml`
```yaml
title: Business and Maintainers information
required:
  - magic
properties:
  magic:
    title: magic
    type: string
    description: Owner of the component
```

I also tried adding a relative url

```yaml
  parameters:
    # Business and Maintainers information (same for all apps)
    - $yaml: "./snippets/parameters/snippets/parameters/ownership.yaml"
 ```
And add the `snippets/` folder right next to `/templates/deploy-component-team/deploy-hello-team-guided/template.yaml`
e.g `/templates/deploy-component-team/deploy-hello-team-guided/snippets/parameters/ownership.yaml`

Which I thought would work - as it does in your example

**Comment by taras** [comment]
@cthtrifork it has to be relative to `packages/backend`. Have you tried that?

**Comment by cthtrifork** [comment]
@taras Yes, I will show you what I have done.

```yaml
....
spec:
  # These parameters are used to generate the input form in the frontend, and are
  # used to gather input data for the execution of the template.
  parameters:
    # Business and Maintainers information (same for all apps)
    - $yaml: ../../templates/snippets/parameters/ownership.yaml
```

```log
[1] 2023-02-02T07:48:00.944Z catalog warn Processor PlaceholderProcessor threw an error while preprocessing; caused by Error: Placeholder $yaml could not form a URL out of /workspaces/cheetah-backstage/templates/deploy-component-team/deploy-hello-team-guided/template.yaml and ../../templates/snippets/parameters/ownership.yaml, TypeError [ERR_INVALID_URL]: Invalid URL type=plugin entity=template:default/deploy-hello-team location=file:/workspaces/cheetah-backstage/templates/deploy-component-team/deploy-hello-team-guided/template.yaml
```

The odd thing is, in my app-config.config I am also using relative paths to the `packages/backend`
```yaml
  locations:
    - type: file
      target: ../../templates/deploy-component-team/deploy-hello-team-guided/template.yaml
```

**Comment by rocha-bruno** [comment]
@cthtrifork Do you still have the issue to replicate what I posted ?

Here is the tree of the my example files in my "idp-templates" repository:

```
├── ...
└── templates
    ├── cloud
    │   ├── python-webservice
    │   │   ├── snippets
    │   │   │   └── parameters
    │   │   │       └── cicd-info.yaml
    │   │   └── template.yaml
    └── defaults
        ├── python
        │   ├── skeletons
        │   │   └── ...
        │   └── snippets
        │       ├── parameters
        │       │   └── archetype-info.yaml
        │       └── ...
        ├── skeletons
        │   ├── base
        │   │   ├── catalog-info.yaml
        │   │   ├── docs
        │   │   │   ├── architecture-decisions
        │   │   │   │   ├── ...
        │   │   │   └── index.md
        │   │   ├── mkdocs.yml
        │   │   └── README.md
        │   ├── ...
        │   └── ...
        └── snippets
            ├── output
            |   ├── publish.yaml
            |   └── show-catalog.yaml
            ├── parameters
            │   └── ownership.yaml
            └── steps
                ├── fetch-api.yaml
                ├── fetch-base.yaml
                ├── publish.yaml
                └── register.yaml
```
I removed what was not necessary, I wish I didn't messed up the formatting too much.

The "$yaml" is really sensitive to the spacing and the relative paths are tricky sometimes :)
Hope it helps.

**Comment by cthtrifork** [comment]
Yes I am still having issues. 

Following your structure, how can your example of
```yaml
- $yaml: ../../defaults/snippets/steps/fetch-api.yaml
```
work? Should it not be:
```yaml
- $yaml: ../../templates/defaults/snippets/steps/fetch-api.yaml
```

Could there be some formatting issue in your example, that could also cause issues?
```yaml
title: Business and Maintainers information
required:
  - owner
properties:
  owner:
    title: Owner
    type: string
    description: Owner of the component
    ui:field: OwnerPicker
    ui:options:
      allowedKinds:
        - Group
  system:
    title: System of this component
    type: string
    description: name of the system to which this application belongs.
    ui:field: EntityPicker
    ui:options:
      allowedKinds:
        - System
      defaultKind: System
```

When I do a relativ path from the template, I am not getting any more errors - but the template won't show up untill I have remove the `- $yaml` placeholder.

**Comment by rocha-bruno** [comment]
No my path is correct as I have to go back 2 folder (python-webservice and cloud) to be in the templates folders and transition to the defaults folder.

Your ownership file seems to be ok for me.

**Comment by cthtrifork** [comment]
@rocha-bruno Okay, so it is relative to the template and not the backend process. I am able to write a path which does not throw the `PlaceholderProcessor` exception, but my templates using `$yaml` will still not load. No errors or relevant debug messages are logged.

I am guessing my issue is somewhere else, and I am kind of derailing this thread. So I will continue investigating on my own. 
Thanks for examples and validation of yaml.

**Comment by rzsita** [comment]
Hi @cthtrifork,
The described solution from @rocha-bruno worked for me 😄 👍 , but it doesn't work in the Template Editor.
![image](https://user-images.githubusercontent.com/46534804/217794815-a6aa2fd1-e758-443d-a145-e3924c032899.png)

@rocha-bruno Thanks again and I think this should be part of the documentation.

**Comment by Rugvip** [comment]
@rzsita yep we'd need some more advanced dry-run capabilities in the catalog for that to work really, so not gonna be supported yet at least

**Comment by cakeinpanic** [comment]
@rocha-bruno thank you for your example!
I'm trying to reproduce it, but I want to store template *in the same repo*
so in your exampl eI want it to look smth like
```
id: backstageTemplate
name: Generating Repository
action: fetch:template
input:
  url: ./tempalte
```

but when I run the scaffolder it finds 0 files. I tried it in defferent combinations but with no success.
I can't find any examples with relative path in this case, is there a chance you also tried it and it did not work for you, so you are using a full github url?

**Comment by cakeinpanic** [comment]
What about nested reusability?
When in `template.yaml` I provide 
`$yaml: some/path.yaml`

and `some/path.yaml` contains 
`$yaml: another/path.yaml`

At the moment I'm getting
<img width="568" alt="Screen Shot 2023-02-28 at 16 00 57" src="https://user-images.githubusercontent.com/588916/221876261-f0d23efa-c71c-41f4-b392-0322caa21d25.png">

**Comment by taras** [comment]
@cakeinpanic as far as I know, recursive templates are not supported.

**Comment by jizusun** [comment]
I'm also having the same error message with @cthtrifork 

```
[1] 2023-05-23T06:04:46.642Z catalog warn Processor PlaceholderProcessor threw an error while preprocessing; caused by Error: Placeholder $yaml could not form a URL out of <redacted>/templates/base-tfs.yaml and ./snippets/parameters/ownership.yaml, TypeError [ERR_INVALID_URL]: Invalid URL type=plugin entity=template:default/base-repository-template location=file:<redacted>/templates/base-tfs.yaml
```

Anybody know how to troubleshoot this?

**Comment by benjdlambert** [comment]
Hmm I think that this might be because you're using `type: file` as the location, we'd recommend using `type: url` for production use cases, can you try with that and pointing to a GitHub repo or something instead to see if it works accordingly?

**Comment by rocha-bruno** [comment]
Hey @Teemukoivumaa ,

I think this is due to the step.yaml file. 
Please try remove the "hyphen/dash" as the "- $yaml" already indicates a list item, so something like the following:
```
id: Preview
name: Preview
action: debug:log
input:
  test: "Hello World"
```

**Comment by Teemukoivumaa** [comment]
Very big thanks @rocha-bruno! I was sure that there was something that I had missed, but now my example is working😄

**Comment by arhill05** [comment]
This thread has been very helpful for my original request, thank you to everyone!

Now I have an additional use case: I want to put multiple steps into one snippet, but I get the `/spec/steps/0 must be object` error if I try this. Here's an example:

template.yaml:
```yaml
...

steps:
  - $yaml: ./snippets/steps/do-multiple-steps.yaml
```

snippets/steps/do-multiple-steps.yaml:
```yaml
- id: step1
  name: Step1
  action: debug:log
  input:
    test: 'hello world!
- id: step2
  name: Step2
  action: debug:log
  input:
    test: 'goodbye world!'
```

Any idea if this is possible and I'm just flubbing some syntax somewhere?

**Comment by benjdlambert** [comment]
so the issue that you might have here is that now it's an array that's returned so you'd have to set the entirety of the `steps` object instead of doing `- $yaml` you would have to do `steps: $yaml`. I wonder with some of the work that's been going into #18102 it might be possible to create a custom resolver that can be used for composing these steps together. so something like:

```yaml
steps: 
  $compose:
    -  $yaml: ./snippets/steps/do-multiple-steps.yaml
    -  id: step3
        name: Step3
        action: debug:log
        input:
          test: 'goodbye world!'
    -  $yaml: ./snippets/steps/do-some-other-steps.yaml
```

The `$compose` resolver would be in charge of resolving all the steps together and then flattening the array so that the steps are valid arrays with step schemas.

A possible idea if you're wanting to mix and match files that have different return values.

**Comment by arhill05** [comment]
I'll wait until 1.16 is shipped and see if I can come up with a solution using that. Is there/will there be any documentation on how to use the placeholder processors outlined in #18102?

Thanks for the pointers!

**Comment by benjdlambert** [comment]
Hmm I think that there might not be a great deal of documentation around at the minute for it as it's pretty new, @sennyeya do you think you can dump a quick example here? 

Also looking at this entire thread, there's a lot of good advice and examples on how to do composability, wondering if we should also make some documentation about that too out the back of this issue :tada:

**Comment by sennyeya** [comment]
https://github.com/backstage/backstage/pull/17535/files#diff-0cd5b7716652e87cb0c502de1a47897edbfc05eb3f36b8153de930f5b548e5f4R27, the readme is attached to #17535. By default it installs for both openapi and asyncapi, buts that's configurable.

**Comment by sennyeya** [comment]
From #17535, https://github.com/backstage/backstage/pull/17535/files#diff-381ed74ea3be62a9c2049083591ac0d97f7520b3e3533840c2211a0911cc8d8dR54. Each keyword gets to register a resolver, if there are multiple registered then it throws an error.

**Comment by nBerg** [comment]
> Hmm I think that this might be because you're using `type: file` as the location, we'd recommend using `type: url` for production use cases, can you try with that and pointing to a GitHub repo or something instead to see if it works accordingly?

Has anyone been able to get this `$yaml` resolver working with the `type: file` location?

**Comment by benjdlambert** [comment]
I think that there was some work towards this but it went stale? https://github.com/backstage/backstage/pull/18296

**Comment by sabinasiddiqi** [comment]
> @rocha-bruno Okay, so it is relative to the template and not the backend process. I am able to write a path which does not throw the `PlaceholderProcessor` exception, but my templates using `$yaml` will still not load. No errors or relevant debug messages are logged.
> 
> I am guessing my issue is somewhere else, and I am kind of derailing this thread. So I will continue investigating on my own. Thanks for examples and validation of yaml.

Did you ever figure out the issue? We are running into the same thing.

**Comment by 63070054** [comment]
Now we still can not nesting the template yet right ? If I understand correctly.

**Comment by seanpoulter-foci** [comment]
To follow up a year later, the resolvers will not work from a `file`. It needs a `url`. That means for development, you'd need to configure GitHub Discovery (or similar) to point at a branch.

**Comment by tfhartmann** [comment]
🤔  I just found this and was trying to follow @rocha-bruno example, and when I add

```Yaml
 steps:
...
    - $yaml: ./publish.yaml
    - id: register
```

My entire software template disappears from the "Available Templates" page entirely.  I believe I'm correctly following the [docs](https://backstage.io/docs/features/software-catalog/descriptor-format#substitutions-in-the-descriptor-format) and the above example, but getting a quite different result! 

If I could get this working, it would be pretty amazing!

**Comment by benjdlambert** [comment]
What does the contents of publish look like?

**Comment by tfhartmann** [comment]
> What does the contents of publish look like?

@benjdlambert  here ya go! :)

```Yaml
id: publish
name: Publish
action: publish:github
input:
  allowedHosts: ['github.com']
  description: ${{ parameters.description }}
  repoUrl: ${{ parameters.repoUrl }}
  repoVisibility: ${{ parameters.visibility }}
  access: >-
    ${{ parameters.repoUrl | parseRepoUrl | pick('owner') }}/${{ parameters.githubTeam | parseEntityRef | pick('name') }}
  defaultBranch: main
  requireCodeOwnerReviews: true
  allowMergeCommit: true
  allowSquashMerge: true
```

**Comment by seanpoulter-foci** [comment]
@tfhartmann, the behaviour you've reported with the template disappearing is expected as of a few months ago. If there's an invalid template it does not load and nothing is reported in the console.

At a glance it looks like you're missing the array item `- ` and indentation in **publish.yaml**. From what I remember from debugging the same symptoms, the `- $yaml: <path>` is replaced with the file contents so you'd end up with:

```
 steps:
    - id: publish
    - name: Publish
    - action: publish:github
    - input:
      - allowedHosts: ['github.com']
      - description: ${{ parameters.description }}
   ...
    - id: register
```

When I refer back to my [similar YAML file](https://github.com/PHACDataHub/sci-portal/blob/main/backstage/templates/project-create/template.steps.yaml#L9-L14), **publish.yaml** should look like this:

```yaml
- id: publish
  name: Publish
  action: publish:github
  input:
    allowedHosts: ['github.com']
    description: ${{ parameters.description }}
    repoUrl: ${{ parameters.repoUrl }}
    repoVisibility: ${{ parameters.visibility }}
    access: >-
      ${{ parameters.repoUrl | parseRepoUrl | pick('owner') }}/${{ parameters.githubTeam | parseEntityRef | pick('name') }}
    defaultBranch: main
    requireCodeOwnerReviews: true
    allowMergeCommit: true
    allowSquashMerge: true
```

**Comment by tfhartmann** [comment]
@seanpoulter-foci I thought that this [comment](https://github.com/backstage/backstage/issues/15241#issuecomment-1588689668) indicated that you were *not* supposed to add the dash/hyphen to the snippet file (i.e. publish.yaml) I did try it with the hyphen and indentation  in the snippet, but that didn't change the behavior for me.  Getting this working would be a bit of a game changer for us, and I'm at a loss for what I'm messing up! 🤦

**Comment by rocha-bruno** [comment]
> @seanpoulter-foci I thought that this [comment](https://github.com/backstage/backstage/issues/15241#issuecomment-1588689668) indicated that you were _not_ supposed to add the dash/hyphen to the snippet file (i.e. publish.yaml) I did try it with the hyphen and indentation in the snippet, but that didn't change the behavior for me. Getting this working would be a bit of a game changer for us, and I'm at a loss for what I'm messing up! 🤦

Hey @tfhartmann, do you still have issue with this ?
The comment you make reference to indicates that if you have a dash on the last line of the following file template.yaml:
```
apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: Test-yaml
  title: Test yaml
  description: Test
spec:
  owner: test
  type: request
  parameters:
    - title: Test
      properties:
        title:
          title: Title
          type: string
          description: Test
  steps:
    - $yaml: ./step.yaml
```
the step.yaml it makes reference to does need it:
```
id: Preview
name: Preview
action: debug:log
input:
  test: "Hello World"
```

If you share a complete example (doesn't need to be too complex) with the template.yaml and step.yaml code, I can have a look to see what's not working.

**Comment by tfhartmann** [comment]
> Hey @tfhartmann, do you still have issue with this ?
> The comment you make reference to indicates that if you have a dash on the last line of the following file template.yaml:

Hey @rocha-bruno  I am! But quick sanity check... I'm re-reading the docs, and see this 

>Local File (type: file) Configurations
In addition to url locations, you can use the file location type to bring in content from the local file system. You should only use this for local development, test setups, and example data, not for production data. You are also not able to use placeholders in them like $text, $json or $yaml.

[link](https://backstage.io/docs/features/software-catalog/configuration#static-location-configuration:~:text=You%20are%20also%20not%20able%20to%20use%20placeholders%20in%20them%20like%20%24text%2C%20%24json%20or%20%24yaml)

which makes me think that the problem I have is in my top level config?  meaning in `app-config.yaml`

this is wrong and will never work: 

```Yaml
    - type: file
      target: ../../templates/scaffolder/terraform-control-module/template.yaml
```
and instead I need something like this? 


```Yaml
    - type: url
      target: https://something.com/somebranch/templates/scaffolder/terraform-control-module/template.yaml
```

Am I getting that right? Maybe my problem is `file` vs `url`

**Comment by tfhartmann** [comment]
For anyone reading along,  `file` vs `url` in `app-config.yaml` was indeed part of my problem.  My templates now load, but I now get a `FetchUrlReader does not implement readTree` error when trying to run the `fetch:template` action 🤦   Thank you for anyone reading this and going on this journey with me 🤣   - eventually I'll get it all sorted! 

```
Beginning step fetch:template
info: Fetching template content from remote 
Error: FetchUrlReader does not implement readTree
```

**Comment by tfhartmann** [comment]
Ug, totally stuck.  This isn't even related to reusing bits of the template, all that now seems to work. At this point, when I change this 

```
    - type: url
       target: ../../templates/scaffolder/pr-with-catalog-entry/template.yaml
       rules:
         - allow: [Template]
```

to this

```
    - type: url
      target: "https://raw.githubusercontent.com/org/backstage/refs/heads/tfhartmann-scaffolder-templates/backstage/templates/scaffolder/pr-with-catalog-entry/template.yaml"
      rules:
        - allow: [Template]
```

I get this error when I hit "create"  - not sure what is up! 
```
Beginning step fetch:template
info: Fetching template content from remote URL
InputError: No integration found for location https://raw.githubusercontent.com/org/backstage/refs/heads/tfhartmann-scaffolder-templates/backstage/templates/scaffolder/pr-with-catalog-entry/template.yaml  at getReadUrl (/Users/me/git/path/to/backstage/node_modules/@backstage/plugin-scaffolder-node/src/actions/fetch.ts:125:13)
```

 I'm not doing anything with `$yaml` in that file, its the exact same file that runs as a `file` 

anyone have any ideas? @rocha-bruno ?

**Comment by ronballesteros** [comment]
> This thread has been very helpful for my original request, thank you to everyone!
> 
> Now I have an additional use case: I want to put multiple steps into one snippet, but I get the `/spec/steps/0 must be object` error if I try this. Here's an example:
> 
> template.yaml:
> 
> ```yaml
> ...
> 
> steps:
>   - $yaml: ./snippets/steps/do-multiple-steps.yaml
> ```
> 
> snippets/steps/do-multiple-steps.yaml:
> 
> ```yaml
> - id: step1
>   name: Step1
>   action: debug:log
>   input:
>     test: 'hello world!'
> - id: step2
>   name: Step2
>   action: debug:log
>   input:
>     test: 'goodbye world!'
> ```
> 
> Any idea if this is possible and I'm just flubbing some syntax somewhere?

Did anyone get this to work?  I'm trying to do multiple ids in one place holder file but can't seem to get it to work.

**Comment by ronballesteros** [comment]
> > Did anyone get this to work? I'm trying to do multiple ids in one place holder file but can't seem to get it to work.
> 
> I solved this by creating an additional Processor, which looks for overly-nested template steps and flattens them out (in the preprocess step, i.e. before the usual validation). It's not the best solution, but it got things working for me.
> 
> ```ts
> async preProcessEntity(entity: Entity, _location: LocationSpec, _emit: CatalogProcessorEmit): Promise<Entity> {
>         const selfRef = stringifyEntityRef(entity);
>         const logger = this.logger.child({ entity: selfRef })
> 
>         logger.debug(`Checking entity for unflattened steps`)
>         if (
>             entity.apiVersion === 'scaffolder.backstage.io/v1beta3' &&
>             entity.kind === 'Template'
>         ) {
>             if (entity.spec !== undefined) {
>                 logger.debug(`Flattening steps`)
>                 const oldSteps = entity.spec.steps as JsonArray;
>                 // Don't need to be any more careful about the type here
>                 // All I'd do is check for the presence of e.g. the `flat` method, and then throw. The below code does that just as well :)
>                 entity.spec.steps = oldSteps.flat();
>                 if (oldSteps.length === entity.spec.steps.length) {
>                     logger.debug(`Flattening had no effect on ${oldSteps.length} steps`)
>                 }
>                 else {
>                     logger.info(`Flattened steps. Was ${oldSteps.length}; now ${entity.spec.steps.length}`)
>                 }
>             } else {
>                 logger.debug('Skipping entity because it has no spec')
>             }
>         }
> 
>         return entity;
>     }
> ```
> 
> I was hoping this'd be a short-term fix until we got a "proper" solution built in, so:
> 
> * I've made some assumptions that might not apply to your case
> * It's logging somewhat aggressively
> * The entity kind / type checks could be improved
> 
> ...but hopefully it helps someone else.

Thank you!  Will try this and see if this works.

**Comment by ronballesteros** [comment]
> > > Did anyone get this to work? I'm trying to do multiple ids in one place holder file but can't seem to get it to work.
> > 
> > 
> > I solved this by creating an additional Processor, which looks for overly-nested template steps and flattens them out (in the preprocess step, i.e. before the usual validation). It's not the best solution, but it got things working for me.
> > ```ts
> > async preProcessEntity(entity: Entity, _location: LocationSpec, _emit: CatalogProcessorEmit): Promise<Entity> {
> >         const selfRef = stringifyEntityRef(entity);
> >         const logger = this.logger.child({ entity: selfRef })
> > 
> >         logger.debug(`Checking entity for unflattened steps`)
> >         if (
> >             entity.apiVersion === 'scaffolder.backstage.io/v1beta3' &&
> >             entity.kind === 'Template'
> >         ) {
> >             if (entity.spec !== undefined) {
> >                 logger.debug(`Flattening steps`)
> >                 const oldSteps = entity.spec.steps as JsonArray;
> >                 // Don't need to be any more careful about the type here
> >                 // All I'd do is check for the presence of e.g. the `flat` method, and then throw. The below code does that just as well :)
> >                 entity.spec.steps = oldSteps.flat();
> >                 if (oldSteps.length === entity.spec.steps.length) {
> >                     logger.debug(`Flattening had no effect on ${oldSteps.length} steps`)
> >                 }
> >                 else {
> >                     logger.info(`Flattened steps. Was ${oldSteps.length}; now ${entity.spec.steps.length}`)
> >                 }
> >             } else {
> >                 logger.debug('Skipping entity because it has no spec')
> >             }
> >         }
> > 
> >         return entity;
> >     }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I was hoping this'd be a short-term fix until we got a "proper" solution built in, so:
> > 
> > * I've made some assumptions that might not apply to your case
> > * It's logging somewhat aggressively
> > * The entity kind / type checks could be improved
> > 
> > ...but hopefully it helps someone else.
> 
> Thank you! Will try this and see if this works.

That worked for me and was able to create yaml place holders with multiple step ids.  Thanks!

**Comment by rdnkmrr** [comment]
Hello,

I am able to use external yaml references in my template.yaml, however I need to enable it based on certain conditions. Can someone provide insights if it is possible to combine if and $yaml ?

**Comment by rafalgalaw** [comment]
Hi @rdnkmrr,
i have implemented something similar, where only a set of parameters is shown to the user depending on the users choice with an $yaml anchor like so:

```yaml
apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: project-starter
  title: Project Starter for Platform XY
  description: "Generates a compliant project"

spec:
  owner: myorg
  type: service

  parameters:
    # common base template parameters
    - $yaml: ./base/parameters.yaml

    - title: Backend Settings
      properties:
        backendChoice:
          title: Choose your backend
          type: string
          enum:
            - kotlin-spring-boot
            - golang-http
            - python-fastapi
            - none
          default: kotlin-spring-boot
          description: 'Which backend technology do you want to use?'
      dependencies:
        backendChoice:
          allOf:
            - if:
                properties:
                  backendChoice:
                    const: kotlin-spring-boot
              then:
                $yaml: ./backend/kotlin-spring-boot/parameters.yaml
            - if:
                properties:
                  backendChoice:
                    const: golang-http
              then:
                $yaml: ./backend/golang-http/parameters.yaml
            - if:
                properties:
                  backendChoice:
                    const: python-fastapi
              then:
                $yaml: ./backend/python-fastapi/parameters.yaml
```

we basically have some wrapper templates for different platforms where users can choose different backend, frontend, cicd,... technologies, but with that pattern you could also provide the go  / python / kotlin template as a standalone template, because the parameters for each template are just referenced by the $yaml anchor.
