### ISSUE TITLE
🐛 Bug Report: Trying to access yaml files in bitbucket server with /browse instead of /raw

### ISSUE THREAD

**Issue by jerrybowman** [backstage/backstage#15259]
### 📜 Description

I have recently instaled the bitbucket server plugin as defined here:
https://backstage.io/docs/integrations/bitbucketServer/locations
https://backstage.io/docs/integrations/bitbucketServer/discovery

Using backstage, version 1.8.0

When accessing bitbucket to pull in the `catalog-info.yaml` file, the URL is using `/browse` which returns a web page instead of `/raw` which returns the content. This causes an error.

{"entity":"location:default/generated-3f082df25980c8f87992ceacff326319baca9256","level":"warn","location":"url:https://bitbucket.xxxx.com:8443/projects/DOS/repos/devbuilder/browse/.backstage/catalog-info.yaml","message":"Expected object at root, got string","plugin":"catalog","service":"backstage","type":"plugin"}

I have searched here and done google searches. I cannot find anyone who has had this problem. I have seen some other issues that all show that **/raw** is normally being used. 

I have also searched through all the @backstage plugin source and do not see anywhere that **/browse** would be used to build the URL. All the code I found builds the URL with **/raw**. So I am at a loss...

Also when I curl the URL with the correct **/raw** value, I get the raw catalog-info.yaml file I expected. 
```
curl --request GET \
  --url 'https://bitbucket.xxxx.com:8443/projects/DOS/repos/devbuilder/raw/.backstage/catalog-info.yaml' \
  --header 'Authorization: Bearer xxxxxxxxxxxxxxxxxxxxxxxxxx' 

apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Devbuilder-Api
  description: Testing bitbucket auto discovery
spec:
  type: service
  lifecycle: experimental
  owner: xxxxx
```

I added this in the locations list as a url type and it does pull in the file and registers it in backstage.
```
catalog:
  locations:
    - type: url
      target: https://bitbucket.xxx.com:8443/projects/DOS/repos/devbuilder/raw/.backstage/catalog-info.yaml
```

### 👍 Expected behavior

Expected the URL to be:

https://bitbucket.xxxx.com:8443/projects/DOS/repos/devbuilder/raw/.backstage/catalog-info.yaml

### 👎 Actual Behavior with Screenshots

The URL to access the catalog file:

https://bitbucket.xxxx.com:8443/projects/DOS/repos/devbuilder/browse/.backstage/catalog-info.yaml

### 👟 Reproduction steps

Add the integration to the config file:

```
integrations:
   bitbucketServer:
    - host: bitbucket.xxxx.com
      apiBaseUrl: https://bitbucket.xxxx.com:8443/rest/api/1.0
      token: ${BITBUCKET_LOCAL_SERVER_TOKEN}
```

Add the plugin:
```
yarn add --cwd packages/backend @backstage/plugin-catalog-backend-module-bitbucket-server
```

Add the provider:

```
catalog:
  providers:
    bitbucketServer:
      bitbucketLocalID: # identifies your ingested dataset
        host: bitbucket.xxxx.com
        catalogPath: /.backstage/catalog-info.yaml # default value
        filters: # optional
          projectKey: '^DOS|ITDB.*$' # optional; RegExp
        #   repoSlug: '^service-.*$' # optional; RegExp
        schedule: # optional; same options as in TaskScheduleDefinition
          # supports cron, ISO duration, "human duration" as used in code
          frequency: { minutes: 30 }
          # supports ISO duration, "human duration" as used in code
          timeout: { minutes: 3 }
```

Add the provider into the packages/backend/src/plugins/catalog.ts file:

```
import { BitbucketServerEntityProvider } from '@backstage/plugin-catalog-backend-module-bitbucket-server';
.
.
export default async function createPlugin(
  env: PluginEnvironment,
): Promise<Router> {
  const builder = await CatalogBuilder.create(env);
  builder.addProcessor(new ScaffolderEntitiesProcessor());
  builder.addEntityProvider(
    BitbucketServerEntityProvider.fromConfig(env.config, {
      logger: env.logger,
      // use scheduler with schedule defined in app-config.yaml
      scheduler: env.scheduler
    }),
  );
  const { processingEngine, router } = await builder.build();
  await processingEngine.start();
  return router;
}
```

### 📃 Provide the context for the Bug.

I am unable to pull in the catalog-info.yaml files dynamically from bitbucket server.

### 🖥️ Your Environment

yarn run v1.22.18
$ /home/bowmanj/git/openshift/alsac-backstage/node_modules/.bin/backstage-cli info
OS:   Linux 5.10.102.1-microsoft-standard-WSL2 - linux/x64
node: v16.15.1
yarn: 1.22.18
cli:  0.21.1 (installed)
backstage:  1.8.0

Dependencies:
  @backstage/app-defaults                                   1.0.8
  @backstage/backend-common                                 0.16.0
  @backstage/backend-plugin-api                             0.1.4
  @backstage/backend-tasks                                  0.3.7
  @backstage/catalog-client                                 1.1.2
  @backstage/catalog-model                                  1.1.3
  @backstage/cli-common                                     0.1.10
  @backstage/cli                                            0.21.1
  @backstage/config-loader                                  1.1.6
  @backstage/config                                         1.0.4
  @backstage/core-app-api                                   1.2.0
  @backstage/core-components                                0.12.0
  @backstage/core-plugin-api                                1.1.0
  @backstage/errors                                         1.1.3
  @backstage/integration-react                              1.1.6
  @backstage/integration                                    1.4.0
  @backstage/plugin-api-docs                                0.8.11
  @backstage/plugin-app-backend                             0.3.38
  @backstage/plugin-auth-backend                            0.17.1
  @backstage/plugin-auth-node                               0.2.7
  @backstage/plugin-catalog-backend-module-bitbucket-server 0.1.3
  @backstage/plugin-catalog-backend                         1.5.1
  @backstage/plugin-catalog-common                          1.0.8
  @backstage/plugin-catalog-graph                           0.2.23
  @backstage/plugin-catalog-import                          0.9.1
  @backstage/plugin-catalog-node                            1.2.1
  @backstage/plugin-catalog-react                           1.2.1
  @backstage/plugin-catalog                                 1.6.1
  @backstage/plugin-github-actions                          0.5.11
  @backstage/plugin-org                                     0.6.1
  @backstage/plugin-permission-common                       0.7.1
  @backstage/plugin-permission-node                         0.7.1
  @backstage/plugin-permission-react                        0.4.7
  @backstage/plugin-proxy-backend                           0.2.32
  @backstage/plugin-scaffolder-backend                      1.8.0
  @backstage/plugin-scaffolder-common                       1.2.2
  @backstage/plugin-scaffolder                              1.8.0
  @backstage/plugin-search-backend-module-pg                0.4.2
  @backstage/plugin-search-backend-node                     1.0.4
  @backstage/plugin-search-backend                          1.1.1
  @backstage/plugin-search-common                           1.1.1
  @backstage/plugin-search-react                            1.2.1
  @backstage/plugin-search                                  1.0.4
  @backstage/plugin-tech-radar                              0.5.18
  @backstage/plugin-techdocs-backend                        1.4.1
  @backstage/plugin-techdocs-module-addons-contrib          1.0.6
  @backstage/plugin-techdocs-node                           1.4.2
  @backstage/plugin-techdocs-react                          1.0.6
  @backstage/plugin-techdocs                                1.4.0
  @backstage/plugin-user-settings                           0.5.1
  @backstage/release-manifests                              0.0.7
  @backstage/test-utils                                     1.2.2
  @backstage/theme                                          0.2.16
  @backstage/types                                          1.0.1
  @backstage/version-bridge                                 1.0.2
Done in 0.48s.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by jhaals** [comment]
I lack enough knowledge about Bitbucket server to help you troubleshoot this, perhaps @pjungermann can help out which has contributed to the Bitbucket support in Backstage. 🙏

**Comment by pjungermann** [comment]
I'm more on the Bitbucket Cloud side myself :)

@ONordander was the one who contributed the provider for Bitbucket Server. And I know that @regicsolutions and @awanlin use Bitbucket Server, too.

The provider only emits Location entities:

```ts
target: `${repository.links.self[0].href}${this.config.catalogPath}`,
```
I assume that the `href` link it correct and also how you would register it as static location at the `app-config.yaml`. And I would assume that this is the origin of the `browse` URL you saw in the log message.

These then get read by the UrlReader; in this case `BitbucketServerUrlReader`. 

Inside of this reader, `getBitbucketServerFileFetchUrl` gets used which supports `browse` and `raw`. And it returns an API URL which contains `raw`. This URL is then used against the Bitbucket Server API. So, whether the original Location target contained `browse` or `raw` should play a role even.

```ts
return `${config.apiBaseUrl}/projects/${owner}/repos/${name}/raw/${pathWithoutSlash}?at=${ref}`;
```

Is there a full stacktrace anywhere?

**Comment by jerrybowman** [comment]
I saw that the `getBitbucketServerFileFetchUrl` always return `raw`. That is why I was confused. Maybe the error message above uses the original `browse` location URL value and it gets converted before the call internally. But is still not returning the requested bitbucket file. And when I take the URL in the message and change `browse` to `raw`, I can retrieve the file. I tried that by hard-coding the `raw` URL as a location in the app-config.properties file and it was retrieved and loaded into backstage.

I do not have a stack-trace on this. Just the error message above. How would I go about producing a stack-trace...

**Comment by ONordander** [comment]
@jerrybowman 
I guess most people are using a custom location parser utilizing the `BitbucketServerClient.getFile` that uses the raw endpoint. Could you try writing a very simple custom parser that changes `browse` to `raw` just to verify?

However I'm a bit confused that this hasn't shown earlier (perhaps there's some environmental differences in our Bitbucket instances), the default location parser worked fine for me earlier, but I don't really have the time right now to setup and test this.

**Comment by jerrybowman** [comment]
I will give that a try. Thanks.

**Comment by awanlin** [comment]
Hi, a little late to this. Just wanted to shared that we use a single static location like this which works fine:

```yaml
- type: url
      target: https://bitbucket.comapny.com/projects/PROJECT_NAME/repos/REPO_NAME/browse/catalog-info.yaml
```

We also use the Bitbucket server provider exactly as described in this issue and works fine. Our config looks like this:

```yaml
providers:
    bitbucketServer:
      bitbucketBackstageSystems: 
        host: bitbucket.company.com
        catalogPath: /definitions/products/**/system.*.yaml
        filters: 
          projectKey: 'PROJECT_NAME'
          repoSlug: '^REPO_NAME$'
```

Note that PROJECT_NAME and REPO_NAME have hard coded value just keeping that out for security sake.

@jerrybowman the one thing that is jumping out at me is the `.` dot before the `backstage` folder. I'm curious if removing that gets things working and perhaps there is a bug around that. That should totally work but given your issues it's the thing I would look at. Feel free to ignore this too just figured I would post seeing as I got pinged :)
