### ISSUE TITLE
🚀 Feature: Make `fetch:plain` to allow fetching a single file instead of directory

### ISSUE THREAD

**Issue by gavlyukovskiy** [backstage/backstage#15388]
### 🔖 Feature description

Currently `fetch:plain` only allows to fetch directories, but for some cases it's useful to fetch individual files.

### 🎤 Context

We are utilizing scaffolds to automate service creation and as part of that we also open few MRs to a separate repository. We have a `CODEOWNERS` file in that repository and ideally we want to reduce manual actions and update that file with the team that has created a service.
I'm looking for a workflow like this:
```
    - id: fetch_codeowners
      name: Fetch CODEOWNERS from IaC
      action: fetch:plain
      input:
        url: https://gitlab.com/.../-/blob/main/CODEOWNERS
        targetPath: external/iac

    - id: update_codeowners
      name: Update CODEOWNERS
      action: miro:update-codeowners
      input:
        path: external/iac/CODEOWNERS
```

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by samueljon** [comment]
I would love to have this enhancement to `fetch:plain` action.  I can also confirm that this action only works with directories and not single files. 

My use case for using `fetch:plain` is to allow the user to customise their TechDocs templates when going through the wizard and then use conditional steps for adding files from a central techdocs template repo. 

```yaml
    - id: fetchRunbook
      name: Adding Runbook that does work
      action: fetch:plain
      input:
        url: https://github.com/myorg/backstage-software-templates/blob/main/templates-documentation/runbook.md
        targetPath: ./docs
      if: ${{ parameters.includeRunbook }}

    - id: fetchArchDocs
      name: Adding Architectual documentation which does not work
      action: fetch:plain
      input:
        url: https://github.com/myorg//backstage-software-templates/blob/main/templates-documentation/system-architecture-template.md
        targetPath: ./docs
      if: ${{ parameters.includeArchDocs }}
```
