### ISSUE TITLE
Google Cloud Run Deployment

### ISSUE THREAD

**Issue by j** [backstage/backstage#1541]
Is GCR supported with Backstage?

PS. Backstage looks awesome.

**Comment by stefanalund** [comment]
@j Backstage can make requests towards Google's APIs (see example [in this plugin](https://github.com/spotify/backstage/pull/1612)) -- making it possible to build a plugin for pretty much any Google Cloud Platform product/feature.

This looks like the right place to start: https://cloud.google.com/run/docs/reference/rest

**Comment by paolomainardi** [comment]
I would like to contribute on this, can I claim this issue ?

**Comment by benjdlambert** [comment]
@paolomainardi assigned you!

**Comment by OrkoHunter** [comment]
Re-opening since plugin suggestion issues are now exempt from [stalebot](https://github.com/backstage/backstage/blob/18f7345a6c29dcfccef7df081b1708f2bf8f62ff/.github/stale.yml#L9).

**Comment by Jake-Mok-Nelson** [comment]
Is there a reason why this **wouldn't** work on Cloud Run?

**Comment by cc4i** [comment]
Any update for this issue?

**Comment by Jake-Mok-Nelson** [comment]
I looked into this a little and it seems like there's some long running polling services that run in the backend and the plugins seem to support that which means it can't really be stateless, starting only with HTTP calls. Would run well on AppEngine though but it's more expensive.

**Comment by mharrvic** [comment]
Hello guys, I made a step-by-step instruction guide on how to deploy backstage with Cloud Run via Terraform 
Notes: https://mharrvic.com/notes/backstage-deploy-with-cloudrun-via-terraform
Repo: https://github.com/mharrvic/backstage-cloudrun-terraform
Feel free to raise any issues you might encounter. Hope this helps!

**Comment by miguelpuiggarcia** [comment]
Hello @mharrvic, thanks for your cloud run tutorial, I got all working and deployed now, 
What is the configuration you use to import catalog entities from github?
Mine seem not to be working in cloud run properly when making changes in GH and clicking refresh...
All works locally though. This is my config:

```
catalog:
  providers:
    github:
      nandosUk:
        organization: 'NandosUK' # string
        catalogPath: '/catalog-info.yaml' # string
        filters:
          branch: '(main|master)' # regex to match main or master branches
          repository: '.*' # Regex to match any repository
        schedule: # optional; same options as in TaskScheduleDefinition
          # supports cron, ISO duration, "human duration" as used in code
          frequency: { minutes: 10 }
          # supports ISO duration, "human duration" as used in code
          timeout: { minutes: 15 }
```
