### ISSUE TITLE
🐛 Bug Report: Cannot Build App on GitHub Actions / ADO

### ISSUE THREAD

**Issue by orcaman** [backstage/backstage#15421]
### 📜 Description

I have a backstage app scaffolded with the CLI.

To build the app, I run the following:

```
yarn install
yarn build
yarn build-image
```

This works on my machine (Mac, node v16.13.0), and also works on my peer's computer (Windows). 

But when using the following GitHub Actions yaml (or the equivalent build pipeline on Microsoft ADO):

```
name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: 'npm'
    - run: yarn install
    - run: yarn build
    - run: yarn build-image
```

The build-image step fails at the tar command:
```
Step 7/11 : RUN tar xzf skeleton.tar.gz && rm skeleton.tar.gz
 ---> Running in b20314a0495a
tar: packages: Cannot mkdir: Permission denied
tar: packages/app/package.json: Cannot open: No such file or directory
tar: packages: Cannot mkdir: Permission denied
tar: packages/backend/package.json: Cannot open: No such file or directory
tar: Exiting with failure status due to previous errors
```

Any idea?

### 👍 Expected behavior

The build should succeed on GitHub Actions as it does locally. 

### 👎 Actual Behavior with Screenshots

The build fails in the part of building the docker image in the tar command
![image](https://user-images.githubusercontent.com/4884073/209463920-2b976c68-f032-40ee-a5a5-a2ba44270198.png)

```
Step 7/11 : RUN tar xzf skeleton.tar.gz && rm skeleton.tar.gz
 ---> Running in b20314a0495a
tar: packages: Cannot mkdir: Permission denied
tar: packages/app/package.json: Cannot open: No such file or directory
tar: packages: Cannot mkdir: Permission denied
tar: packages/backend/package.json: Cannot open: No such file or directory
tar: Exiting with failure status due to previous errors
```

### 👟 Reproduction steps

Scaffold a new backstage app with the backstage CLI and try to build the docker image with the following GitHub Actions yaml:

```


name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: 'npm'
    - run: yarn install
    - run: yarn build
    - run: yarn build-image
```

### 🖥️ Your Environment

yarn run v1.22.17
$ /Users/or.hiltch/github/backstage/temp/Backstage/node_modules/.bin/backstage-cli info
OS:   Darwin 21.6.0 - darwin/x64
node: v16.13.0
yarn: 1.22.17
cli:  0.19.0 (installed)
backstage:  1.6.0

Dependencies:
  @backstage/app-defaults                          1.0.6
  @backstage/backend-common                        0.15.1, 0.16.0, 0.17.0
  @backstage/backend-plugin-api                    0.1.2, 0.1.4, 0.2.0
  @backstage/backend-tasks                         0.3.5, 0.3.7, 0.4.0
  @backstage/catalog-client                        1.1.0, 1.2.0
  @backstage/catalog-model                         1.1.1, 1.1.4
  @backstage/cli-common                            0.1.10, 0.1.11
  @backstage/cli                                   0.19.0
  @backstage/config-loader                         1.1.4, 1.1.6, 1.1.7
  @backstage/config                                1.0.2, 1.0.4, 1.0.5
  @backstage/core-app-api                          1.1.0
  @backstage/core-components                       0.11.1, 0.12.1
  @backstage/core-plugin-api                       1.0.6, 1.2.0
  @backstage/errors                                1.1.1, 1.1.3, 1.1.4
  @backstage/integration-react                     1.1.4
  @backstage/integration                           1.3.1, 1.4.0, 1.4.1
  @backstage/plugin-api-docs                       0.8.9
  @backstage/plugin-app-backend                    0.3.36
  @backstage/plugin-auth-backend                   0.16.0
  @backstage/plugin-auth-node                      0.2.5, 0.2.8
  @backstage/plugin-azure-devops-backend           0.3.18
  @backstage/plugin-azure-devops-common            0.3.0
  @backstage/plugin-azure-devops                   0.2.3
  @backstage/plugin-catalog-backend-module-azure   0.1.10
  @backstage/plugin-catalog-backend-module-github  0.1.7
  @backstage/plugin-catalog-backend                1.4.0, 1.6.0
  @backstage/plugin-catalog-common                 1.0.6, 1.0.9
  @backstage/plugin-catalog-graph                  0.2.21
  @backstage/plugin-catalog-import                 0.8.12
  @backstage/plugin-catalog-node                   1.1.0, 1.3.0
  @backstage/plugin-catalog-react                  1.1.4, 1.2.2
  @backstage/plugin-catalog                        1.5.1
  @backstage/plugin-circleci                       0.3.9
  @backstage/plugin-events-backend                 0.1.0
  @backstage/plugin-events-node                    0.1.0
  @backstage/plugin-github-actions                 0.5.9
  @backstage/plugin-github-issues                  0.1.1
  @backstage/plugin-github-pull-requests-board     0.1.3
  @backstage/plugin-home                           0.4.25
  @backstage/plugin-org                            0.5.9
  @backstage/plugin-permission-common              0.6.4, 0.7.1, 0.7.2
  @backstage/plugin-permission-node                0.6.5, 0.7.2
  @backstage/plugin-permission-react               0.4.5, 0.4.8
  @backstage/plugin-proxy-backend                  0.2.30
  @backstage/plugin-scaffolder-backend             1.6.0
  @backstage/plugin-scaffolder-common              1.2.0, 1.2.3
  @backstage/plugin-scaffolder                     1.6.0
  @backstage/plugin-search-backend-module-pg       0.4.0
  @backstage/plugin-search-backend-node            1.0.2
  @backstage/plugin-search-backend                 1.0.2
  @backstage/plugin-search-common                  1.0.1, 1.2.0
  @backstage/plugin-search-react                   1.1.0
  @backstage/plugin-search                         1.0.2
  @backstage/plugin-sentry                         0.4.2
  @backstage/plugin-sonarqube-backend              0.1.4
  @backstage/plugin-sonarqube                      0.5.0
  @backstage/plugin-stack-overflow                 0.1.5
  @backstage/plugin-tech-radar                     0.5.16
  @backstage/plugin-techdocs-backend               1.3.0
  @backstage/plugin-techdocs-module-addons-contrib 1.0.4
  @backstage/plugin-techdocs-node                  1.4.0
  @backstage/plugin-techdocs-react                 1.0.4
  @backstage/plugin-techdocs                       1.3.2
  @backstage/plugin-user-settings                  0.4.8
  @backstage/release-manifests                     0.0.6
  @backstage/test-utils                            1.2.0
  @backstage/theme                                 0.2.16
  @backstage/types                                 1.0.0, 1.0.1, 1.0.2
  @backstage/version-bridge                        1.0.1, 1.0.3
✨  Done in 1.29s.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None
