### ISSUE TITLE
🚀 Feature: Ability to refer to an entity property for templating

### ISSUE THREAD

**Issue by gaurav517** [backstage/backstage#15604]
### 🔖 Feature description

While creating a template, if we ask user for an input, we should be able to use that input to get some property of an entity and pass that as template variable for scaffolding.

### 🎤 Context

While scaffolding, I get `System` input (using `EntityPicker`) and I would like to pass corresponding domain (`${{ values.domain }}`) , to use in templating.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by benjdlambert** [comment]
I think that this should now be possible using https://github.com/backstage/backstage/pull/15682.

You can pass in the `entityRef` from the `EntityPicker` into this action, and then use the `output` from this action into other `actions`.

Going to close this ticket, but feel free to reply if there's anything else we can help with! :pray:

**Comment by gaurav517** [comment]
Its not really working for me:
```
   parameters:
    - title: Fill in basic details
      required:
        - name
        - description
        - system
      properties:
        name:
          title: Name
          type: string
          description: Unique name of the component
          ui:field: EntityNamePicker
          ui:autofocus: true
        description:
          title: Description
          type: string
          description: A description for the component
        system:
          title: System
          type: string
          description: System for the service
          ui:field: EntityPicker
          ui:options:
            allowedKinds:
              - System
            defaultKind: System
  steps:
    - id: fetchSystem
      name: Fetch System
      action: catalog:fetch
      input:
        entityRef: system:default/${{ parameters.system }}
    - id: fetchTemplate
      name: Template Java Microservice Skeleton
      action: fetch:template
      input:
        url: ./skeleton
        templateFileExtension: true
        values:
          system: ${{ parameters.system }}
          domain: ${{ steps['fetchSystem'].output.spec.domain }}
          owner: ${{ steps['fetchSystem'].output.spec.owner }}
```
Both `domain` and `owner` are empty in generated files. I am using latest `scaffolder-backend:1.10.1`.  Anything I am doing wrong? Thanks.
