### ISSUE TITLE
🐛 Bug Report: `/api/proxy` can be accessed without authentication

### ISSUE THREAD

**Issue by gaurav517** [backstage/backstage#15616]
### 📜 Description

If a proxy is configured. e.g. 
```
'/my-data':
    target: https://my-ghe/api/v3/repos/my-org/my-repo/contents
    headers:
      Authorization: Bearer ${GHE_TOKEN}
```
As `/my-data` fetches a protected resource using token, I would expect only logged in users to be able to get data from that endpoint.

### 👍 Expected behavior

`/api/proxy/my-data` shouldn't be accessible without authentication

### 👎 Actual Behavior with Screenshots

`/api/proxy/my-data` can be accessed without authentication 

### 👟 Reproduction steps

Create a proxy configuration (that fetches some protected data) and try to reach that proxy endpoint without being logged in.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else
