### ISSUE TITLE
🐛 Bug Report: Kubernetes plugin asks to login even if already logged in using google auth

### ISSUE THREAD

**Issue by gaurav517** [backstage/backstage#15638]
### 📜 Description

Trying to see kubernetes plugins page, after logging in using google auth provider.

### 👍 Expected behavior

Kubernetes plugin should not ask to reauthenticate as user is already authenticated with google.

### 👎 Actual Behavior with Screenshots

Kubernetes plugin asks to reauthenticate.

<img width="674" alt="image" src="https://user-images.githubusercontent.com/15346341/211345143-d7faad2b-0bb5-48c0-8428-ddd5d82e61ea.png">

### 👟 Reproduction steps

- Login using google auth
- Go to kubernetes plugin page
- A pop up is thrown to login using Google

### 🖥️ Your Environment

**Configuration**:
```
kubernetes:
  serviceLocatorMethod:
    type: 'multiTenant'
  clusterLocatorMethods:
    - type: 'gke'
      projectId: 'my-project-id'
      region: 'australia-southeast1'
      skipTLSVerify: true
  customResources:
    - group: 'argoproj.io'
      apiVersion: 'v1alpha1'
      plural: 'rollouts'
```

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else
