### ISSUE TITLE
🐛 Bug Report: ENOSPC Error occurs due to lack of clean up by Techdocs

### ISSUE THREAD

**Issue by Mercanuis** [backstage/backstage#15649]
### 📜 Description

Backstage and Techdocs seem to have an issue with temporary storage when it comes to cleaning up afterward. 

We're using Backstage 1.7 and deploying it to a Kubernetes environment on an EKS cluster on AWS. We deploy the image and have it set up to use the GitHub Discovery tools that allow Backstage to scrape our team's repo for "Documentation as Code" behavior. 

We noticed that recently we've been using a lot of space, and we reached an issue despite giving the Backstage pods a volume mount with 5GB of space. We don't have reason to suspect at this time that we are producing so much documentation to fill that up so quickly, but we're noticing the following error when Backstage attempts to refresh:

```
Building a newer version of this documentation failed. Error: "ENOSPC: no space left on device, mkdtemp '/tmp/backstage-4Cro8e'"
```

To remedy this, we went into the backstage pod and performed the following clean up
```
cd /tmp
ls -rt | grep -v "lost+found" | head -n 1600 | xargs rm -rf
```

This reduced disk usage from 80% to approximately 10% immediately. 

This leads us to think the following behavior is happening

* A folder is generated under /tmp almost every time a user opens a document
* Nothing deletes the contents in /tmp folder once something has been rendered by Backstage

We want to continue to use the GH discovery tool because it helps us to automate updates to documents. However, there is likely a workaround to adopt the recommended setup for the cloud by [Backstage Documents](https://backstage.io/docs/features/techdocs/architecture#recommended-deployment). Still this seems to be an issue that should be addressed.

Thanks for your consideration!

### 👍 Expected behavior

Backstage should be able to render the new documents upon update, and any old or deprecated documentation should be cleared out to maintain space. /tmp should be able to clear out any files after they've been rendered and stored by Backstage to avoid this

### 👎 Actual Behavior with Screenshots

/tmp never gets cleaned out by Backstage, and so every page that a user opens up is given a new folder, and anything changed never gets cleared out, making space fill up too quickly. 

### 👟 Reproduction steps

1. Deploy Backstage via container to a Kubernetes environment
2. Perform various operations on the site such as opening pages, refreshing pages, etc.
3. Perform updates on linked code in GH repository and trigger changes in the documents that Backstage is listening to to enable it to pull in changes
4. Open changed pages; Backstage will usually prompt you by saying near the top of a page "A new version of this documentation is available" and you can then click the 'Refresh' button to trigger it. 

### 📃 Provide the context for the Bug.

This issue is mostly just a potential issue for space and given the nature of ENOSPC being an OS-level bug, this seems quite serious. There are workarounds (see description for more) but this does limit the usability of Backstage currently if there is only one way to do documentation. Documentation as Code is a handy idea and we would like to encourage it, but then the tools need to be smart enough to handle cleanup

### 🖥️ Your Environment

```
 ~/backstage/app/ yarn backstage-cli info
yarn run v1.22.19
$ ~/backstage/app/node_modules/.bin/backstage-cli info
node: v16.19.0
yarn: 1.22.19
cli:  0.21.1 (installed)
backstage:  1.7.1

Dependencies:
  @backstage/app-defaults                          1.0.7
  @backstage/backend-common                        0.15.2
  @backstage/backend-plugin-api                    0.1.3
  @backstage/backend-tasks                         0.3.6
  @backstage/catalog-client                        1.1.1
  @backstage/catalog-model                         1.1.2
  @backstage/cli-common                            0.1.10
  @backstage/cli                                   0.20.0
  @backstage/config-loader                         1.1.5
  @backstage/config                                1.0.3
  @backstage/core-app-api                          1.1.1
  @backstage/core-components                       0.11.2
  @backstage/core-plugin-api                       1.0.7
  @backstage/dev-utils                             1.0.7
  @backstage/errors                                1.1.2
  @backstage/integration-react                     1.1.5
  @backstage/integration                           1.3.2
  @backstage/plugin-api-docs                       0.8.10
  @backstage/plugin-app-backend                    0.3.37
  @backstage/plugin-auth-backend                   0.17.0
  @backstage/plugin-auth-node                      0.2.6
  @backstage/plugin-catalog-backend-module-github  0.1.8
  @backstage/plugin-catalog-backend                1.5.0
  @backstage/plugin-catalog-common                 1.0.7
  @backstage/plugin-catalog-graph                  0.2.22
  @backstage/plugin-catalog-import                 0.9.0
  @backstage/plugin-catalog-node                   1.2.0
  @backstage/plugin-catalog-react                  1.2.0
  @backstage/plugin-catalog                        1.6.0
  @backstage/plugin-github-actions                 0.5.10
  @backstage/plugin-home                           0.4.26
  @backstage/plugin-org                            0.5.10
  @backstage/plugin-permission-common              0.7.0
  @backstage/plugin-permission-node                0.7.0
  @backstage/plugin-permission-react               0.4.6
  @backstage/plugin-proxy-backend                  0.2.31
  @backstage/plugin-scaffolder-backend             1.7.0
  @backstage/plugin-scaffolder-common              1.2.1
  @backstage/plugin-scaffolder                     1.7.0
  @backstage/plugin-search-backend-module-pg       0.4.1
  @backstage/plugin-search-backend-node            1.0.3
  @backstage/plugin-search-backend                 1.1.0
  @backstage/plugin-search-common                  1.1.0
  @backstage/plugin-search-react                   1.2.0
  @backstage/plugin-search                         1.0.3
  @backstage/plugin-stack-overflow                 0.1.6
  @backstage/plugin-tech-radar                     0.5.17
  @backstage/plugin-techdocs-backend               1.4.0
  @backstage/plugin-techdocs-module-addons-contrib 1.0.5
  @backstage/plugin-techdocs-node                  1.4.1
  @backstage/plugin-techdocs-react                 1.0.5
  @backstage/plugin-techdocs                       1.3.3
  @backstage/plugin-user-settings                  0.5.0
  @backstage/release-manifests                     0.0.6
  @backstage/test-utils                            1.2.1
  @backstage/theme                                 0.2.16
  @backstage/types                                 1.0.0
  @backstage/version-bridge                        1.0.1
```

Because we're using GH Discovery Tools, we don't have a separate database setup and choose to let the DB be in memory using the Scratch volume for storage. 

```
Name:          developer-portal-scratch-pvc
Namespace:     developer-portal
StorageClass:  developer-portal-ebs-sc
Status:        Bound
Volume:        ...
Labels:        app=developer-portal
               component=developer-portal
               kustomize.toolkit.fluxcd.io/name=developer-portal
               kustomize.toolkit.fluxcd.io/namespace=flux-system
Annotations:   pv.kubernetes.io/bind-completed: yes
               pv.kubernetes.io/bound-by-controller: yes
               volume.beta.kubernetes.io/storage-provisioner: ebs.csi.aws.com
               volume.kubernetes.io/selected-node: ip-10-13-130-147.ap-northeast-1.compute.internal
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      5Gi
Access Modes:  RWO
VolumeMode:    Filesystem
Used By:       ...
Events:        <none>
```

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, I don't have time to work on this right now

**Comment by Mercanuis** [comment]
I wanted to provide a little more context for this Issue I'm seeing in Backstage. I noticed that the disk was getting full so I had to perform a cleanup, but while I was doing that I was seeing a pattern of the following running `du . -a`

```
backstage-7gsM0f/dirA/README.md
...
backstage-y8y1Mf/dirA/README.md
```

This suggests to me this is happening every time the GH plugin determines there's a new change, and then Backstage suggests refreshing the page (per this screenshot of the top of a page in the Dev Portal):

![Screenshot 2023-01-19 at 8 43 12 (2)](https://user-images.githubusercontent.com/35368863/213319459-7fbe2ae6-0b8c-4dad-a521-108616119e6a.png)

What I don't understand is why the prior copy is kept by Backstage if it knows there's a new version, or if there's a flag or something in the configuration that needs to be told to Backstage/Techdocs to destroy or wipe the previous version

**Comment by agentbellnorm** [comment]
@Mercanuis As you have pointed out, this setup is really not recommended in production, but yeah - it seems wasteful to keep creating directories.

I gave it some time to try to reproduce the issue locally, but i didn't manage. Could you guide me on how to reproduce locally?

Or at least, can you share relevant parts of your `app-config.yaml`?

Thanks!

**Comment by Mercanuis** [comment]
@agentbellnorm, thanks for reaching out to me on this. I appreciate it. 

I just wanted to elaborate on why we chose this setup: our organization has multiple teams, and we have an idea of "self-service'. that the GH discovery tool allows us to scrape multiple repos and host teams without them needing to be in our CI/CD pipelines themselves to host documents on the portal our team is providing. 

So the idea is that we'd have multiple repos set up for teams that all get collected onto the same Backstage, separated by Domain, System, etc 

The relevant portions I can provide: will the`integrations` and `catalog` sections of `app-config.yaml` be enough? Please let me know

```

integrations:
  github:
    - host: XXX
      apiBaseUrl: https://XXX/api/v3
      rawBaseUrl: https://XXX/raw
      apps:
      - $include: ../secrets/secret-github-credentials.yaml

catalog:
  # Used to make the catalog read only and prevent any unwanted updates
  # Ref: https://backstage.io/docs/features/software-catalog/configuration#readonly-mode
  readonly: true
  locations:
    # Our Team
    - type: github-discovery
      target: https://XXX/XXX/XXX/blob/main/catalog-info.yaml
    - type: github-org
      target: https://XXXX/XXXXX
      rules:
        - allow: [Group, User]
    # Backend Team
    #TODO: Disabled for now, will re-enable upon the completion of the investigation and application of https://xxx.monday.com/boards/111111/pulses/111111
#    - type: github-discovery
#      target: https://XXX/XXX/XXX-backend-monorepo/blob/main/catalog-info.yaml
```

And for a local setup we just use a GitHub Personal Token that is set up to be read by backstage via an `app-config.local-override.yaml` file

```
# Add local-env-specific overrides to app-config.yaml here
integrations:
  github:
    - host: XXX
      apiBaseUrl: https://XXX/api/v3
      rawBaseUrl: https://XXX/raw
      token:
        $include: ../secrets/secret-github-credentials.yaml#token
auth:
  providers:
    github:
      $include: ../secrets/secret-github-oauth-credentials.yaml
```
