### ISSUE TITLE
🐛 Bug Report: [TechDocs] - Error: Docker container returned a non-zero exit code (1)

### ISSUE THREAD

**Issue by padupe** [backstage/backstage#15796]
### 📜 Description

We are in the validation (MVP) stage of the TechDocs plugin in our organization.
In the validation step in the local environment we are receiving the error:
`Building a newer version of this documentation failed. Error: "Failed to generate documents from /tmp/backstage-Od152m to /tmp/techdocs-tmp-4MYBfq; caused by error: Docker container returned a non-zero (1) exit code"`

The displayed logs:
```bash
1info: Step 1 of 3: Preparing documents for entity component:default/techdocs-api {"timestamp":"2023-01-17T12:36:28.168Z"}
2info: Completed preparation step for entity component: default/techdocs-api , stored in /tmp/backstage-Hfde10 {"timestamp":"2023-01-17T12:36:29.472Z"}
3info: Step 2 of 3: Generating documents for the entity component:default/techdocs -api {"timestamp": "2023-01-17T12:36:29.472Z"}
4{"status":"Pulling from spotify/techdocs","id":"v1.1.0"}
5{"status": "Summary: sha256:79ff0ca98454e7e8dbcc908af2a9e85ccda08e56213ff21c15507a7781"a7781"a7781 }
6{"status":"Status: Image is updated for spotify/techdocs:v1.1.0"}7Error: Configuration file 'mkdocs.yml' does not exist.
```

### 👍 Expected behavior

Documentation successfully rendered.

### 👎 Actual Behavior with Screenshots

![image](https://user-images.githubusercontent.com/72894267/212901219-ff6ad4e2-317d-4106-a1aa-b8f0d9271ce1.png)

![image](https://user-images.githubusercontent.com/72894267/212901296-c3f0cc12-da9e-42fe-9ed4-68a6a8d0fa90.png)

![image](https://user-images.githubusercontent.com/72894267/212901399-3669e171-fc22-42cf-9495-0e1e2411764a.png)

![image](https://user-images.githubusercontent.com/72894267/212901530-33e8cc64-9d5b-4c5d-9601-4990a49c6c68.png)

## Backstage Instance

**app-config.local.yaml**
```yaml
[...]
techdocs:
  builder: 'local' # Alternatives - 'external'
  generator:
    runIn: docker # Alternatives - 'local'
  publisher:
    type: 'local' # Alternatives - 'googleGcs' or 'awsS3'. Read documentation for using alternatives.
[...]
```

**docker-compose.yaml**
```yaml
version: '3.7'
services:
  techdocs:
    build:
      context: ./techdocs-local
      dockerfile: Dockerfile
  postgresql:
    image: postgres:alpine
    restart: always
    container_name: tech-hub
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - pgdata:/data/postgres
volumes:
  pgdata:
    driver: local
```

**techdocs-local/Dockerfile**
```yaml
FROM python:3.8-alpine

RUN apk update && apk --no-cache add gcc musl-dev openjdk17-jdk curl graphviz ttf-dejavu fontconfig

# Download plantuml file, Validate checksum & Move plantuml file
RUN curl -o plantuml.jar -L http://sourceforge.net/projects/plantuml/files/plantuml.1.2022.4.jar/download && echo "246d1ed561ebbcac14b2798b45712a9d018024c0  plantuml.jar" | sha1sum -c - && mv plantuml.jar /opt/plantuml.jar

RUN pip install --upgrade pip && pip install mkdocs-techdocs-core==1.1.7

# Create script to call plantuml.jar from a location in path
#   When adding TechDocs to the Backstage Backend container, avoid this
#   error (OSError: [Errno 8] Exec format error: 'plantuml') by using the
#   following RUN command instead:
#   RUN echo '#!/bin/sh\n\njava -jar '/opt/plantuml.jar' ${@}' >> /usr/local/bin/plantuml
RUN echo $'#!/bin/sh\n\njava -jar '/opt/plantuml.jar' ${@}' >> /usr/local/bin/plantuml
RUN chmod 755 /usr/local/bin/plantuml

ENTRYPOINT [ "mkdocs" ]
```

## Example Component

**Structure**
```
docs
  └── dynatrace.md
  └── index.md
  └── local-development.md
catalog-info.yaml
mkdocs.yml
README.md
```

**catalog-info.yaml**
```yaml
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: techdocs-api
  description: Test.
  annotations:
    github.com/project-slug: acme-org/techdocs-api
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  owner: group:owner
  system: example-system
  lifecycle: development
```

**mkdocs.yml**
```yaml
site_name: 'Component Test'
site_description: 'Tech Docs Example'
repo_url: https://github.com/acme-org/component-test
edit_uri: edit/main/docs

plugins:
  - techdocs-core

nav:
  - Desenvolvimento Local: local-development.md
  - Integração com Dynatrace: dynatrace.md
```

### 📃 Provide the context for the Bug.

# Step 1
- Starting services through Docker with the `docker-compose up` command

# Step 2
I start my Backstage application with the `yarn dev` command

# Step 3
Access the [Docs](http://localhost:3000/docs?filters%5Buser%5D=all) tab in my environment.

# Step 4
I select the component I want to view the rendered documentation.

# Step 5
The process to generate the documentation starts automatically, as it doesn't find a "healthy" version to display.

# Step 6
I get the error.

---

When running `docker ps -a` I get the following output:
![image](https://user-images.githubusercontent.com/72894267/212903008-cd9b8061-2e48-4aa1-92cd-c3217cda04fa.png)

Container logs dedicated to TechDocs:
![image](https://user-images.githubusercontent.com/72894267/212903131-3be7e2de-855d-40cb-8e45-daea8eecf36a.png)

### 🖥️ Your Environment

OS:   Linux 5.14.0-1055-oem - linux/x64
node: v16.19.0
yarn: 1.22.19
cli:  0.22.0 (installed)
backstage:  1.9.1

Dependencies:
  @backstage/app-defaults                          1.0.10
  @backstage/backend-common                        0.16.0, 0.17.0
  @backstage/backend-plugin-api                    0.2.0
  @backstage/backend-tasks                         0.4.0
  @backstage/catalog-client                        1.2.0
  @backstage/catalog-model                         1.1.4
  @backstage/cli-common                            0.1.11
  @backstage/cli                                   0.22.0
  @backstage/config-loader                         1.1.7
  @backstage/config                                1.0.5
  @backstage/core-app-api                          1.3.0
  @backstage/core-components                       0.10.0, 0.11.2, 0.12.2
  @backstage/core-plugin-api                       1.2.0
  @backstage/errors                                1.1.4
  @backstage/integration-aws-node                  0.1.0
  @backstage/integration-react                     1.1.8
  @backstage/integration                           1.4.1
  @backstage/plugin-api-docs                       0.8.13
  @backstage/plugin-app-backend                    0.3.39
  @backstage/plugin-auth-backend                   0.17.2
  @backstage/plugin-auth-node                      0.2.8
  @backstage/plugin-catalog-backend-module-github  0.2.2
  @backstage/plugin-catalog-backend-module-msgraph 0.4.5
  @backstage/plugin-catalog-backend                1.6.0
  @backstage/plugin-catalog-common                 1.0.9
  @backstage/plugin-catalog-graph                  0.2.25
  @backstage/plugin-catalog-import                 0.9.3
  @backstage/plugin-catalog-node                   1.3.0
  @backstage/plugin-catalog-react                  1.2.3
  @backstage/plugin-catalog                        1.7.1
  @backstage/plugin-dynatrace                      1.0.3
  @backstage/plugin-events-node                    0.2.0
  @backstage/plugin-github-actions                 0.5.13
  @backstage/plugin-home                           0.4.29
  @backstage/plugin-org                            0.6.3
  @backstage/plugin-permission-backend             0.5.14
  @backstage/plugin-permission-common              0.7.2
  @backstage/plugin-permission-node                0.7.2
  @backstage/plugin-permission-react               0.4.8
  @backstage/plugin-proxy-backend                  0.2.33
  @backstage/plugin-scaffolder-backend             1.9.0
  @backstage/plugin-scaffolder-common              1.2.3
  @backstage/plugin-scaffolder                     1.9.1
  @backstage/plugin-search-backend-module-pg       0.5.0
  @backstage/plugin-search-backend-node            1.1.0
  @backstage/plugin-search-backend                 1.2.0
  @backstage/plugin-search-common                  1.2.0
  @backstage/plugin-search-react                   1.3.1
  @backstage/plugin-search                         1.0.6
  @backstage/plugin-sonarqube-backend              0.1.4
  @backstage/plugin-sonarqube-react                0.1.0
  @backstage/plugin-sonarqube                      0.6.1
  @backstage/plugin-stack-overflow                 0.1.9
  @backstage/plugin-tech-radar                     0.5.20
  @backstage/plugin-techdocs-backend               1.5.0
  @backstage/plugin-techdocs-module-addons-contrib 1.0.8
  @backstage/plugin-techdocs-node                  1.4.3
  @backstage/plugin-techdocs-react                 1.1.1
  @backstage/plugin-techdocs                       1.4.2
  @backstage/plugin-user-settings                  0.6.1
  @backstage/release-manifests                     0.0.8
  @backstage/test-utils                            1.2.3
  @backstage/theme                                 0.2.16
  @backstage/types                                 1.0.2
  @backstage/version-bridge                        1.0.3
Done in 0.70s.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else
