### ISSUE TITLE
🐛 Bug Report: Accessing data from other fields in scaffolder/next doesn't work

### ISSUE THREAD

**Issue by Pike** [backstage/backstage#15830]
### 📜 Description

I'm creating a custom input field that's reading data from previous fields, following https://backstage.io/docs/features/software-templates/writing-custom-field-extensions#access-data-from-other-fields.

They work in scaffolder, but don't work in scaffolder/next.

When looking at the react components in devtools, the formContext.formData has the previous field, but with an empty object as data.

Side note, also, formData in undefined on first render, which is a change of behavior to being an empty object on the old one, I think.

### 👍 Expected behavior

scaffolder/next should have data in `formContext.formData` from previous fields.

### 👎 Actual Behavior with Screenshots

The formContext.formData has the previous field, but with an empty object as data.

### 👟 Reproduction steps

Write a custom input field that uses the formContext to access previous input fields output data.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, I don't have time to work on this right now

**Comment by benjdlambert** [comment]
@Pike is this with field extensions for `type: object` values?

**Comment by benjdlambert** [comment]
If so I think that this is related to https://github.com/rjsf-team/react-jsonschema-form/issues/3305#issuecomment-1399325728 in which it could be `undefined` and maybe we need to update the type for that as it comes from the upstream library.

**Comment by Pike** [comment]
I tested things a bit more, and there seems to be some state timing happening.

After clicking "Next", the formContext doesn't have the data from the previous field, but going back and forth fixes it.

As I'm using the formContext to fill the default state of my inputs, that makes them only pick this up on the second time.

**Comment by benjdlambert** [comment]
@Pike ah ok so this could just be some state bug that we have - just to confirm this happens in a simple `FieldExtension` right that returns a simple string or something?

**Comment by Pike** [comment]
Yeah, a simple text field on the first page and a control like this on the second. This isn't the full code, as there's some internal business logic, but I guess you get the idea that we're trying to get the component name defaulted from a good human-readable title, for example.

```
export const InferredNames = (props: InferredNamesProps) => {
  const {
    onChange,
    formData,
    formContext,
    rawErrors,
    uiSchema: { 'ui:options': uiOptions },
  } = props;
  const title = !uiOptions?.title
    ? (formContext?.formData?.title as string)
    : uiOptions.title;
  const defaultState =
    formData?.componentName ? formData : inferName({ title });
  const [state, setState] = useState<InferredNamesData>(defaultState);

  return (
    <>
      <FormControl
        margin="normal"
        required
        error={rawErrors?.length > 0 && !formData}
      >
        <InputLabel>Component Name</InputLabel>
        <Input
          value={state.componentName}
          onChange={event => {
            const newName = String(event.target.value);
            if (newName) {
              setState(prevState => {
                const newState = { ...prevState, componentName: newName };
                onChange(newState);
                return newState;
              });
            }
          }}
        />
      </FormControl>
    </>
  );
};
```

**Comment by benjdlambert** [comment]
Is the `title` property on the same `jsonschema` step as the this `FieldExtension`?

**Comment by Pike** [comment]
It's in the previous step.

```
    - title: General information
      required:
        - title
        - description
      properties:
        title:
          title: Name
          type: string
          description: Name of the App
        description:
          title: Description
          type: string
          description: Help others understand what this app is for
          ui:widget: textarea
    - title: Component name
      properties:
        names:
          type: object
          ui:field: InferredNames
```
