### ISSUE TITLE
🐛 Bug Report: ambiguously-named clusters cannot be targeted with the proxy endpoint

### ISSUE THREAD

**Issue by jamieklassen** [backstage/backstage#15901]
### 📜 Description

If two clusters located by Backstage have the same name, proxy requests targeting that name will always be routed to the first one -- there's no way to target the second one!

### 👍 Expected behavior

Well, depends on what you know. If you're only aware of the second cluster you might expect to see namespaces. If you know there are two ambiguously-named clusters, you might expect to see an error about this.

### 👎 Actual Behavior with Screenshots

console prints
```text
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {

  },
  "status": "Failure",
  "message": "Unauthorized",
  "reason": "Unauthorized",
  "code": 401
}
```
This indicates that only the first cluster got queried -- since we never set up a token for it.

### 👟 Reproduction steps

1. Create two kind clusters: `kind create cluster --name kind-1 && kind create cluster --name kind-2`
1. Grab their server URLs: `export KIND_1_URL=$(kubectl config view -o jsonpath='{.clusters[?(@.name == "kind-kind-1")].cluster.server}') && export KIND_2_URL=$(kubectl config view -o jsonpath='{.clusters[?(@.name == "kind-kind-2")].cluster.server}')`
1. Get a high-powered bearer token for the second cluster: `kubectl config use-context kind-kind-2 && kubectl create clusterrolebinding default-sa-admin --serviceaccount default:default --clusterrole cluster-admin && export TOKEN=$(kubectl get secret -o go-template='{{(index .items 0).data.token | base64decode}}')`
1. Set up an app-config to target these clusters, but with both having the same name:
```yaml
kubernetes:
  serviceLocatorMethod:
    type: 'multiTenant'
  clusterLocatorMethods:
    - type: config
      clusters:
        - name: kind
          url: ${KIND_1_URL}
          skipTLSVerify: true
          skipMetricsLookup: true
          authProvider: serviceAccount
        - name: kind
          url: ${KIND_2_URL}
          skipTLSVerify: true
          skipMetricsLookup: true
          authProvider: serviceAccount
```
1. Run the backend: `yarn start-backend`
1. In a separate process, try to fetch namespaces specifying the ambiguous cluster name, using the token for the second cluster: `curl -H "Authorization: Bearer $TOKEN" -H 'X-Kubernetes-Cluster: kind' -s localhost:7007/api/kubernetes/proxy/api/v1/namespaces`

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!
