### ISSUE TITLE
feature: ability to change the schema name for postgres

### ISSUE THREAD

**Issue by ajithshah** [backstage/backstage#15914]
### 🔖 Summary

change schema from public to something else 

### ✌️ Context

<img width="811" alt="Screenshot 2023-01-24 at 8 52 57 AM" src="https://user-images.githubusercontent.com/76985845/214289682-70f173fe-af40-4c97-a895-8152675f2d82.png">

Change schema name from public to something else

### 👀 Have you spent some time to check if this plugin request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by benjdlambert** [comment]
Unfortunately I don't think that this is configurable yet. What's the use case, what do you want to change the schema name to?

**Comment by benjdlambert** [comment]
Hey :wave: So I had a little dig into this a little further, and it's looking a little tricky. 

I though it would be possible to supply config like this:

```yaml
# app-config.yaml
...
backend:
  database:
    client: pg
    knexConfig:
      searchPaths: ['knex', 'backstage'] # backstage in this case would be the schema name
```

But unfortunately we get greeted with this error when running migrations:

`[1] Backend failed to start up error: create table "knex_migrations" ("id" serial primary key, "name" varchar(255), "batch" integer, "migration_time" timestamptz) - no schema has been selected to create in`

This is because we need to provide an explicit `schemaName` in the `client.migrations?.skip` calls in all the plugins. This is pretty problematic, but I think that with our new backend system work, it might be possible for us to configure the clients are that being used everywhere and add these options to the client already potentially.

Otherwise we would have to update all the usages which seems unfortunate.

https://github.com/knex/knex/issues/1897#issuecomment-605871185 for reference.

Thoughts @backstage/maintainers?

**Comment by benjdlambert** [comment]
Actually scrap that. I think I've worked it out.

You can do this:


```yaml
backend:
  database:
    client: pg
    knexConfig:
      searchPath: ['knex', 'backstage']
      migrations:
        schemaName: 'backstage'
```

And that seems to get the migrations running in the right place. Although it looks like you will need to create the `schema`s for each environment first as the migrations wont do that and they asssume that the schema is available and writable.
