### ISSUE TITLE
🚀 Feature: EntityPicker should use entity title if available

### ISSUE THREAD

**Issue by drodil** [backstage/backstage#15987]
### 🔖 Feature description

Currently, EntityPicker shows available options by their stringified entity name. Instead metadata.title should be used if it's available. This is not the only place where for some reason the stringified entity name is used. For example, on catalog pages, the owner is formatted similarly.

### 🎤 Context

Especially when talking about users or groups, the stringified entity name does not make sense to most users. In dropdown I would like to see `John Doe` instead `user:john.doe_mydomain.com`

### ✌️ Possible Implementation

Add getOptionLabel to the AutoComplete at https://github.com/backstage/backstage/blob/cee85776a4df73d918d8b538eef67fbdd60bda94/plugins/scaffolder/src/components/fields/EntityPicker/EntityPicker.tsx#L93 

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by sennyeya** [comment]
I took a quick look at this and it doesn't seem as simple as I thought it would be, see https://github.com/backstage/backstage/compare/master...sennyeya:backstage:humanize. The form data is tied to the `TextField` input which changes the form data. Basically, if I update the team owner to `Team A` the actual form data also updates to `Team A` and then pressing Next causes everything to freak out.

Feel free to take a stab at it from my branch, I think it's going to be a bit of a pain though.

**Comment by ltdonner** [comment]
Unstale, please

**Comment by drodil** [comment]
Relates to #17474

**Comment by regicsolutions** [comment]
@drodil were you able to come up with a workaround on this one?

**Comment by drodil** [comment]
@regicsolutions nope. I think we should wait for #17474 to easily get the names of entities without unnecessary requests to the backend.

**Comment by drodil** [comment]
Not stale

**Comment by drodil** [comment]
not stale

**Comment by drodil** [comment]
Not stale

**Comment by twanbeeren** [comment]
Not sure if this is the same but when I use the OwnerPicker I also get a similar issue. It tries to use the metadata.name from my group instead of the title.

While the documentation says that the UI should be prioritising the metadata.title if its there. https://backstage.io/docs/features/software-catalog/descriptor-format/#title-optional

**My template**

```
parameters:
    - title: Component information
      required:
        - name
        - description
        - owner
      properties:
        name:
          title: Name
          type: string
          description: Name for the service (-project is automatically appended)
          ui:field: EntityNamePicker
        description:
          title: Description
          type: string
          description: Description fit for the service
        owner:
          title: Owner
          type: string
          description: Owner team of the service
          ui:field: OwnerPicker
          ui:options:
            allowArbitraryValues: false
            catalogFilter:
              - kind: Group
                spec.type: team
```

**My groups**

```
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
   namespace: default
   title: Argus
   name: argus
spec:
   type: team
   profile:
      displayName: Argus
   children: []
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
   namespace: default
   title: BO&O
   name: bo-and-o
spec:
   type: team
   profile:
      displayName: BO&O
   children: []
```

Here you an see that my template still uses the metadata.name instead of the metadata.title
