### ISSUE TITLE
🚀 Feature: improve the ADR plugin navigation

### ISSUE THREAD

**Issue by dweber019** [backstage/backstage#15995]
### 🔖 Feature description

Love the ADR plugin.
I would like to propose the following changes to the navigation.

- Use date as order, newer top
- Use the title in file content and not the file name
- Display the status in the navigation

### 🎤 Context

It would enhance user experience, specially if there are a lot of ADR's.

### ✌️ Possible Implementation

I would suggest the implementation of log4brains

<img width="258" alt="2023-01-26 22_10_24-Next js persistent layout pattern ADR - Architecture knowledge base of Log4brain" src="https://user-images.githubusercontent.com/1021324/214951691-c5f28d29-1bca-488f-9a28-10f6a1c3bff7.png">

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by dweber019** [comment]
What do you think of this? I think it's simple, clean and just adds the missing information required.

<img width="1003" alt="CleanShot 2023-01-29 at 01 01 53@2x" src="https://user-images.githubusercontent.com/1021324/215296686-0f637792-c516-42a7-83b3-5af9834e72f9.png">

regarding the order, I just reversed it because we can't rely on the fact that everyone is using madr with a date. But I think it's common to either use a date like 20230101-<file-name>.md or 00001-<file-name>.md, so reversing the order would make sense in most cases.

**Comment by Silthus** [comment]
How about parsing the frontmatter from the template and display some basic information on the right sight about the status, date, involved people and so on?

```yaml
---
# These are optional elements. Feel free to remove any of them.
status: {proposed | rejected | accepted | deprecated | … | superseded by ADR-0005 <0005-example.md>}
date: {YYYY-MM-DD when the decision was last updated}
deciders: {list everyone involved in the decision}
consulted: {list everyone whose opinions are sought (typically subject-matter experts); and with whom there is a two-way communication}
informed: {list everyone who is kept up-to-date on progress; and with whom there is a one-way communication}
---
```
