### ISSUE TITLE
🐛 Bug Report: Azure remote url output for software template does not work

### ISSUE THREAD

**Issue by JetteBke** [backstage/backstage#16008]
### 📜 Description

I have a custom software template that publishes a repository in Azure DevOps. All steps are working fine and I can see the repository in my project in Azure DevOps. Now I click on the repository link from the screenshot.
<img width="326" alt="Screen Shot 2023-01-27 at 13 46 43" src="https://user-images.githubusercontent.com/47563816/215090749-7e6169fe-4761-45b3-aae3-e17520d160c0.png">
the template.yaml:

```
   - id: publish
      name: Publish the repo
      action: publish:azure
      input:
        description: 'This is ${{ (parameters.repoUrl | parseRepoUrl).repo }}'
        repoUrl: ${{ parameters.repoUrl }}

    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps['publish'].output.repoContentsUrl }}
        catalogInfoPath: '/catalog-info.yaml'

 output:
    links:
      - title: Repository
        icon: code
        url: ${{ steps['publish'].output.remoteUrl }}
      - title: Open in catalog
        icon: catalog
        entityRef: ${{ steps['register'].output.entityRef }}
```

I copied this directly from the docs

### 👍 Expected behavior

I can see my new repository and the files.
Forwards to https://dev.azure.com/my-org/my-project/_git/my-repo

### 👎 Actual Behavior with Screenshots

I can see a white page and a console error: `Uncaught DOMException: Failed to execute 'replaceState' on 'History':...`
Forwards to https://my-org@dev.azure.com/my-org/my-project/_git/my-repo

### 👟 Reproduction steps

Create a software template that publishes an azure devops repository.
Use the template to create a project.
Click on the output repo link (see screenshot above)

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else
