### ISSUE TITLE
🐛 Bug Report: review field order is inconsistent

### ISSUE THREAD

**Issue by mbenson** [backstage/backstage#16062]
### 📜 Description

When a template includes a property of array type, that property is displayed before others during the review step.

### 👍 Expected behavior

Array template properties should be presented in order of declaration as are "normal" properties.

### 👎 Actual Behavior with Screenshots

<img width="1382" alt="image" src="https://user-images.githubusercontent.com/487462/215607918-33b759c6-5ffe-43eb-ba32-b45df56c0e11.png">

### 👟 Reproduction steps

* Go to `Create...`
* Select "Template Editor" from upper right menu
* Select "Edit Template Form"
* Paste below parameter content [1]
* Fill out form and click "NEXT STEP"

1.

```
parameters:
  - title: Target
    required:
      - name
    properties:
      name:
        type: string
        ui:autofocus: true
      token:
        type: string
        ui:widget: password
      jokin:
        type: string
        ui:backstage:
          review:
            mask: '[REDACTED]'
      smokin:
        type: string
        ui:backstage:
          review:
            show: false
      pokin:
        type: string
        ui:backstage:
          review:
            show: true
      array:
        type: array
        minItems: 1
        items:
          type: string
          enum:
            - foo
            - bar
            - baz
        uniqueItems: true
        ui:widget: checkboxes
        ui:options:
          inline: true
```

### 📃 Provide the context for the Bug.

I want to present templates that conform to a sensible order of presented options. I will note that there is a discussion item for this issue (https://github.com/backstage/backstage/discussions/15756) but seemingly no bug has been opened. I do have a patch for this issue.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!
