### ISSUE TITLE
🐛 Bug Report: Catalog entities not updated properly when location is moved in github

### ISSUE THREAD

**Issue by danangarbansa** [backstage/backstage#16128]
### 📜 Description

When the catalog-info files are moved and renamed to a different location, seems like backstage failed to pick it up automatically, for example we move `/service/catalog-info.service.yaml` to `/top-level/service/catalog-info.yaml` while adding some more information into it.

The said entity are marked as orphan, which is expected. We added a scheduled task in our backend to automatically clean them up. We thought backstage failed to pick up the new location because of the existence of those orphaned entities (they shared the same name, hence the entityRef would be the same). However, after cleaning up the orphaned entities seems like backstage still failed to pick up the new locations.

Worth to mention that we use the Github provider for the catalog.

### 👍 Expected behavior

Backstage should be able to pick up the new locations and ingest the catalog files in the new location.

### 👎 Actual Behavior with Screenshots

The actual behaviour is that no new entities are displayed that originated from the new location.

### 👟 Reproduction steps

- Configure the catalog to use the github provider in the app-config file
```
  providers:
    github:
      org:
        organization: 'Org'
        catalogPath: '**/catalog-info*.yaml'
        filters:
          branch: 'master'
          repository: 'repo-a'
```
- Add `catalog-info.my-service.yaml` file into the repo-a 
```
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  description: desc
  name: my-service
spec:
  lifecycle: production
  owner: owner
```
- You should be able to see the entity coming from `catalog-info.my-service.yaml` in the catalog table.
- Move and rename the `catalog-info.test.yaml` into different dir, for example `my-service/catalog.yaml` while adding new metadata to it while keeping the same `metadata.name` field.
```
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  description: desc
  name: my-service
spec:
  lifecycle: production
  owner: owner
  system: my-system
```
- The entity will be marked as "orphan"
- Delete the orphaned entity
- The is no new ingested entity that comes from the new location `my-service/catalog.yaml`

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!
