### ISSUE TITLE
🚀 Feature: publish:<git>:push action

### ISSUE THREAD

**Issue by yesmanmx** [backstage/backstage#16153]
### 🔖 Feature description

add publish:\<git>:push to the list of built-in action

### 🎤 Context

As a user who adding API (or any other component) to my service catalogue  - I want to have the option to do this via UI.
Creating a new git repository for each new entity seems wasteful, so I want to have a single repository for all configs. 
Creating yaml files manually and registering them via a direct link is tiring.
I want to push a new yaml file directly to the branch and be able to register entity in catalog immediately after creation.

template example:
```
  steps:
    - id: fetch-base
      name: Fetch Base
      action: fetch:template
      input:
        url: ./content
        values:
          name: ${{ parameters.name }}

    - id: publish
      name: Publish
      action: publish:github:push
      input:
        branch: master
        targetPath: some/path
        repoUrl: ${{ parameters.repoUrl }}

    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps['publish'].output.repoContentsUrl }}
        catalogInfoPath: 'some/path/catalog-info.yaml'
```

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None
