### ISSUE TITLE
🐛 Bug Report: Can't import files that have lead with a dot when catalog pattern is applied in catalog rules

### ISSUE THREAD

**Issue by jpdeburgo** [backstage/backstage#16167]
### 📜 Description

I can't import files that lead with a dot or have a folder that leads with a dot into my catalog after adding a pattern into catalog rules. For example, if my catalog rules look like this:
```
catalog:
  rules:
    - allow: [Component, System, API, Resource, Location, Template, Groups, Observability]
      locations:
        - type: url
          pattern: https://github.com/organization/**
```
I cannot import these files:
https://github.com/organization/.path/catalog-info.yaml
https://github.com/organization/path/.catalog-info.yaml

This is because I forgot to add the [dot option](https://github.com/isaacs/minimatch#dot) in [my last PR to backstage](https://github.com/backstage/backstage/pull/14584/files#diff-b46619603ba7526e4674f18caf9984a567ea659b512563ab53c401e9c2f33c09R189)

### 👍 Expected behavior

It should import files that fit the patterns successfully

### 👎 Actual Behavior with Screenshots

It actually does not successfully import files that have a leading dot

### 👟 Reproduction steps

1. Go to your app-config.yaml
2. Add the following rule:
```
catalog:
  rules:
    - allow: [Component, System, API, Resource, Location, Template, Groups, Observability]
      locations:
        - type: url
          pattern: https://github.com/organization/**
```
3. Try to import https://github.com/organization/.path/catalog-info.yaml

### 📃 Provide the context for the Bug.

Someone in my organization tried to import a file that was in a folder that let with a dot. The file had a similar path to this, https://github.com/organization/.path/catalog-info.yaml. When he tried, Catalog Import threw an error.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!
