### ISSUE TITLE
Can docker in docker be offloaded to another server?

### ISSUE THREAD

**Issue by hybridx** [backstage/backstage#16163]
### 🔖 Need

The docker in docker situation is hogging a lot of resources which can potentially run externally outside the backstage backend deployment

```
techdocs:
  builder: 'local' 
  generator:
    runIn: 'docker' 
    dockerImage: 'spotify/techdocs'
    pullImage: true
  publisher:
    type: 'local' # Alternatives - 'googleGcs' or 'awsS3'. Read documentation for using alternatives.
    local:
      publishDirectory: '/Users/username/backstage_docs/'
```

### 🎉 Proposal

Can the docker be deploy outside the container where the backend is running? 

```
techdocs:
  builder: 'external' 
  generator:
    externalURL: 'https://url-for-the-pod-to-receive-data'
    runIn: 'docker' 
    dockerImage: 'spotify/techdocs'
    pullImage: true
  publisher:
    type: 'local' # Alternatives - 'googleGcs' or 'awsS3'. Read documentation for using alternatives.
    local:
      publishDirectory: '/Users/username/backstage_docs/'
```

### 〽️ Alternatives

None

### ❌ Risks

N/A

### 👀 Have you spent some time to check if this RFC has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)
