### ISSUE TITLE
🔌 Plugin: Azure sites

### ISSUE THREAD

**Issue by burak-create** [backstage/backstage#16346]
### 🔖 Summary

Hello,

I keep getting TypeError:

<img width="1083" alt="Screenshot 2023-02-14 at 20 59 03" src="https://user-images.githubusercontent.com/70510104/218848012-97270be1-97d3-4147-ab17-5837dfcc691f.png">

I have no problem pulling the data because `http://localhost:7007/api/azure-sites/list/func` gives me a proper json blob on the backend.

my config:

```
azureSites:
  domain: sample.se
  clientId: ${AZURE_CLIENT_ID}
  clientSecret: ${AZURE_CLIENT_SECRET}
  tenantId: ${AZURE_TENANT_ID}
```

```
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: developer-docs
  description: An example of a Backstage application.
  annotations:
    backstage.io/techdocs-ref: dir:.
    dev.azure.com/project-repo: backstage_proj/backstage_demo
    azure.com/tag-selector: environment/production
    azure.com/microsoft-web-sites: func
spec:
  type: service
  owner: MrKebab
  lifecycle: experimental
```

thank you in advance!

### 👀 Have you spent some time to check if this plugin request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None
