### ISSUE TITLE
🐛 Bug Report: Markdown in plugin-catalog does not adhere to theme

### ISSUE THREAD

**Issue by elizabeth-a-hobbs** [backstage/backstage#16404]
### 📜 Description

The Markdown support that was added to the `AboutCard` description section does not adhere to the theme when rendering links.

### 👍 Expected behavior

Use defined theme when rendering links.

### 👎 Actual Behavior with Screenshots

Theme is not used when rendering links.

![image](https://user-images.githubusercontent.com/107500314/219484481-e9aace74-276e-4c15-b74a-a44e4a3b7d93.png)

### 👟 Reproduction steps

```yaml
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: debug-user-permissions
  description: A tool for viewing the permissions associated with a [user](https://www.google.com/).
```

### 🖥️ Your Environment

@backstage/plugin-catalog@1.8.0

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!
