### ISSUE TITLE
🐛 Bug Report: `catalog:fetch` does not respect `optional: false` flag

### ISSUE THREAD

**Issue by amadkinnon** [backstage/backstage#16447]
### 📜 Description

The scaffolder plugin `catalog:fetch` does not respect the `optional` flag.

### 👍 Expected behavior

When giving the `optional: false` flag, it should throw an error when the entity does not exit.

### 👎 Actual Behavior with Screenshots

It actually returns a null entity and proceed to the next step.


### 👟 Reproduction steps

Given the following template
```yaml
apiVersion: scaffolder.backstage.io/v1beta3                                                                                           
kind: Template                                                                                                                        
metadata:                                                                                                                             
  name: "example-template"                                                                                                  
  title: "Catalog Fetch - optional:false"                                                                                                        
  description: "Reproduces the catalog:fetch bug"                                            
  annotations:                                                                                                                        
    github.com/project-slug: Owner/repo                                                                                                                                                                                                                                                                                                                                                                                                                       
                                                                                                                                        
    parameters:                                                                                                                         
      - title: Repository Information                                                                                                   
        required:                                                                                                                       
          - repoName                                                                                                                    
        properties:                                                                                                                     
          repoName: 
            title: Repository Name                                                                                                      
            type: string
            description: The name of the non-existent repository. 
            ui:field: EntityNamePicker                                                                                                  
            ui:autofocus: true                                                                                                                                                                                                    
    steps:
     - id: fetch-entity-ref                                                                                                                    
        name: Fetching Catalog Entity                                                                                                   
        action: catalog:fetch
        input:
          entityRef: 'component:default/${{ parameters.repoName }}'                                                                     
          optional: false 
                                                                                                                                                                                                                                                           - id: debug-log                                                                                                                   
        name: Debug Entity
        action: debug:log
        input:                                                                                                                          
          message: ${{ steps['fetch-entity-ref'].output | dump }}
```

Returns
```
1 2023-02-20T02:09:30.000Z Beginning step Debug Entity
2 2023-02-20T02:09:30.000Z info: {
3      "message": "{\"entity\":null}"
4 }
5 2023-02-20T02:09:30.000Z {"entity":null}
6 2023-02-20T02:09:30.000Z Finished step Debug Entity
```

### 📃 Provide the context for the Bug.

Trying to use this in a template where I would like it to fail immediately if the entity does not exist.

### 🖥️ Your Environment

```
$ /backstage/node_modules/.bin/backstage-cli info
OS:   Linux 5.4.0-126-generic - linux/x64
node: v16.19.0
yarn: 1.22.17
cli:  0.22.3 (installed)
backstage:  1.11.1

Dependencies:
  @backstage/app-defaults                          1.2.0
  @backstage/backend-app-api                       0.4.0
  @backstage/backend-common                        0.18.2
  @backstage/backend-dev-utils                     0.1.0
  @backstage/backend-plugin-api                    0.4.0
  @backstage/backend-tasks                         0.4.3
  @backstage/catalog-client                        1.3.1
  @backstage/catalog-model                         1.2.0
  @backstage/cli-common                            0.1.11
  @backstage/cli                                   0.22.3
  @backstage/config-loader                         1.1.8
  @backstage/config                                1.0.6
  @backstage/core-app-api                          1.5.0
  @backstage/core-components                       0.12.4
  @backstage/core-plugin-api                       1.4.0
  @backstage/dev-utils                             1.0.12
  @backstage/errors                                1.1.4
  @backstage/eslint-plugin                         0.1.1
  @backstage/integration-aws-node                  0.1.1
  @backstage/integration-react                     1.1.10
  @backstage/integration                           1.4.2
  @backstage/plugin-analytics-module-ga            0.1.26
  @backstage/plugin-api-docs                       0.9.0
  @backstage/plugin-app-backend                    0.3.42
  @backstage/plugin-auth-backend                   0.18.0
  @backstage/plugin-auth-node                      0.2.11
  @backstage/plugin-catalog-backend-module-github  0.2.5
  @backstage/plugin-catalog-backend                1.7.2
  @backstage/plugin-catalog-common                 1.0.11
  @backstage/plugin-catalog-graph                  0.2.27
  @backstage/plugin-catalog-import                 0.9.5
  @backstage/plugin-catalog-node                   1.3.3
  @backstage/plugin-catalog-react                  1.3.0
  @backstage/plugin-catalog                        1.8.0
  @backstage/plugin-events-node                    0.2.3
  @backstage/plugin-explore-common                 0.0.1
  @backstage/plugin-explore-react                  0.0.26
  @backstage/plugin-explore                        0.4.0
  @backstage/plugin-github-actions                 0.5.15
  @backstage/plugin-home                           0.4.31
  @backstage/plugin-org                            0.6.5
  @backstage/plugin-permission-backend             0.5.17
  @backstage/plugin-permission-common              0.7.3
  @backstage/plugin-permission-node                0.7.5
  @backstage/plugin-permission-react               0.4.10
  @backstage/plugin-playlist-backend               0.2.5
  @backstage/plugin-playlist-common                0.1.4
  @backstage/plugin-playlist                       0.1.6
  @backstage/plugin-proxy-backend                  0.2.36
  @backstage/plugin-scaffolder-backend             1.11.0
  @backstage/plugin-scaffolder-common              1.2.5
  @backstage/plugin-scaffolder-node                0.1.0
  @backstage/plugin-scaffolder-react               1.1.0
  @backstage/plugin-scaffolder                     1.11.0
  @backstage/plugin-search-backend-node            1.1.3
  @backstage/plugin-search-backend                 1.2.3
  @backstage/plugin-search-common                  1.2.1
  @backstage/plugin-search-react                   1.5.0
  @backstage/plugin-search                         1.1.0
  @backstage/plugin-sentry                         0.5.0
  @backstage/plugin-shortcuts                      0.3.7
  @backstage/plugin-sonarqube-backend              0.1.7
  @backstage/plugin-sonarqube-react                0.1.3
  @backstage/plugin-sonarqube                      0.6.4
  @backstage/plugin-tech-radar                     0.6.1
  @backstage/plugin-techdocs-backend               1.5.3
  @backstage/plugin-techdocs-module-addons-contrib 1.0.10
  @backstage/plugin-techdocs-node                  1.5.0
  @backstage/plugin-techdocs-react                 1.1.3
  @backstage/plugin-techdocs                       1.5.0
  @backstage/plugin-todo-backend                   0.1.39
  @backstage/plugin-todo                           0.2.17
  @backstage/plugin-user-settings                  0.7.0
  @backstage/release-manifests                     0.0.8
  @backstage/test-utils                            1.2.5
  @backstage/theme                                 0.2.17
  @backstage/types                                 1.0.2
  @backstage/version-bridge                        1.0.3
```

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else
