### ISSUE TITLE
🐛 Bug Report: Search bar in techdocs reader page doesn't use baseUrl

### ISSUE THREAD

**Issue by benabineri** [backstage/backstage#16544]
### 📜 Description

We have backstage deployed with a URL prefix/sub path, e.g. https://example.com/our-backstage

Setting `backend.baseUrl` and `app.baseUrl` is enough to make links work correctly in most places, but the results from the search bar at the top of the techdocs reader page don't include the prefix.

### 👍 Expected behavior

Links in the techdocs reader page search should go to `https://example.com/our-backstage/docs/...`

### 👎 Actual Behavior with Screenshots

They go to `https://example.com/docs/...`

### 👟 Reproduction steps

Enable techdocs and search.

Configure `baseUrl` to include a prefix.

### 📃 Provide the context for the Bug.

This may be specific to our setup - I had a look through our techdocs setup (collators, config etc.) but couldn't find how the location is constructed. Essentially, I am not sure whether this is something that should work "out of the box" or whether this is something that I need to configure, in which case documentation/guidance would be very useful!

### 🖥️ Your Environment

Backstage 1.10.1

```
    "@backstage/plugin-search-backend": "^1.2.2",
    "@backstage/plugin-search-backend-module-pg": "^0.5.3",
    "@backstage/plugin-search-backend-node": "^1.1.2",
    "@backstage/plugin-techdocs-backend": "^1.1.1",
```

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by sennyeya** [comment]
Can you share a little bit more about your set up? I tried to test this locally with the `master` branch demo app and a basic `app.baseUrl: http://localhost:3000/backstage` but not able to reproduce.

The relevant lines are https://github.com/sennyeya/backstage/blob/4e5891524ca57f0cb7a787e91aa7966a67f83782/plugins/techdocs/src/search/components/TechDocsSearch.tsx#L114 and https://github.com/sennyeya/backstage/blob/4e5891524ca57f0cb7a787e91aa7966a67f83782/plugins/techdocs-backend/src/search/DefaultTechDocsCollatorFactory.ts#L199, but those were working as expected in my tests. The `navigate` hook should handle any resolution of `baseUrl` as needed, and the values produced by the `DefaultTechDocsCollatorFactory` or any other collator can just use an absolute `/docs/...` instead of `${app.baseUrl}/docs/...`.

**Comment by benabineri** [comment]
Thanks for taking a look!

I will share anything I can find that might be relevant...

We have this route in App.tsx:
```
    <Route path="/docs" element={<TechDocsIndexPage />} />
    <Route
      path="/docs/:namespace/:kind/:name/*"
      element={<TechDocsReaderPage />}
    >
      <TechDocsAddons>
        <ReportIssue />
      </TechDocsAddons>
    </Route>
```

We have a `packages/backend/src/plugins/techdocs.ts` file that matches the one in the docs (https://backstage.io/docs/features/techdocs/getting-started#adding-techdocs-backend-plugin). We also have the import and `apiRouter.use` calls in `packages/backend/src/index.ts`

In `packages/backend/src/plugins/search.ts`:

```
import { DefaultTechDocsCollatorFactory } from '@backstage/plugin-techdocs-backend';

  indexBuilder.addCollator({
    schedule,
    factory: DefaultTechDocsCollatorFactory.fromConfig(env.config, {
      discovery: env.discovery,
      logger: env.logger,
      tokenManager: env.tokenManager,
    }),
  });
```


Here are the relevant parts of our config:

```
app:
  title: <org-name> Backstage
  baseUrl: https://<our-admin-domain>.com/<org-name>-backstage/

organization:
  name: <org-name>

backend:
  baseUrl: https://<our-admin-domain>.com/<org-name>-backstage/
  listen:
    port: 7007
techdocs:
  builder: 'local' # Alternatives - 'external'
  generator:
    runIn: 'local' # Alternatives - 'local'
    mkdocs:
       legacyCopyReadmeMdToIndexMd: true 
  publisher:
    type: 'local' # Alternatives - 'googleGcs' or 'awsS3'. Read documentation for using alternatives.
    local:
      # (Optional). Set this to specify where the generated documentation is stored.
      publishDirectory: '/backstage/docs'
```
