### ISSUE TITLE
🐛 Bug Report: GitHub Discovery is bound to the default branch

### ISSUE THREAD

**Issue by marcobjorge** [backstage/backstage#16650]
### 📜 Description

The GitHub Discovery is bound to the default branch:

* If the catalog file exists only on a non-default branch then it's never discovered
* If the catalog file exists only in the default branch then it's assumed it also exists in the non-default branch

Consider the following sample configuration (`main` is the default branch, `backstage` is a non-default branch):

### 👍 Expected behavior

The discovery finds catalog files in any branch, even non-default branches and even if the default branch has no catalog file.

### 👎 Actual Behavior with Screenshots

If the catalog file exists only on a non-default branch then it's never discovered. 
If the catalog file exists only in the default branch then it's assumed it also exists in the non-default branch.

### 👟 Reproduction steps

1. Create a github provider configuration as follows:

```
catalog:
  providers:
    github:
      fMain:
        host: github.com
        organization: '<organization>'
        catalogPath: '/catalog-info.yaml'
        validateLocationsExist: true
        filters:
          branch: 'main'
        schedule:
          frequency: { minutes: 60 }
          timeout: { minutes: 3 }
      fBackstage:
        host: github.com
        organization: '<organization>'
        catalogPath: '/catalog-info.yaml'
        validateLocationsExist: true
        filters:
          branch: 'backstage'
        schedule:
          frequency: { minutes: 60 }
          timeout: { minutes: 3 }
```

2. In the `backstage` branch create, commit and push a `catalog-info.yaml`. You will see that it's not picked up by backstage.
3. In the `main` branch create, commit and push a `catalog-info.yaml`. You will see that both branches are suddenly picked up by backstage.

### 📃 Provide the context for the Bug.

On some projects the catalog file is being generated as part of CI and is never committed to the main/default branch. The generated file is committed to a well defined branch instead (e.g. `backstage`). Backstage should be able to pickup the generated file from a well know location.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by Rugvip** [comment]
Are you able to reliably reproduce this regardless of how long you wait between step 2 and 3? I'm feeling that it might simply be down to catalog processing delays.

**Comment by marcobjorge** [comment]
> Are you able to reliably reproduce this regardless of how long you wait between step 2 and 3? I'm feeling that it might simply be down to catalog processing delays.

Correct. But if you are asking I'm wondering if I did something wrong - I hope not and it would be great if someone could confirm. Looking at the code it did seem the bug was there as well...

**Comment by jenil-harness** [comment]
We are also facing the same issue.
When we use `validateLocationsExist: true` in config, it always checks if the file exists in the default branch only.

```
catalog:
  providers:
    github:
      fMain:
        host: github.com
        organization: '<organization>'
        catalogPath: '/catalog-info.yaml'
        validateLocationsExist: true
        filters:
          branch: 'backstage'
        schedule:
          frequency: { minutes: 60 }
          timeout: { minutes: 3 
```

For the above config, if `catalog-info.yaml` is present in the default branch, then it ingests the location even when `catalog-info.yaml` is not present in the `backstage` branch.
