### ISSUE TITLE
🐛 Bug Report: Missing docs - Kubernetes authentication (AWS)

### ISSUE THREAD

**Issue by askmeegs** [backstage/backstage#16677]
### 📜 Description

The [Kubernetes Authentication doc](https://backstage.io/docs/features/kubernetes/authentication#server-side-providers) is missing details or a configuration example for the AWS integration. 

### 👍 Expected behavior

The Kubernetes Authentication doc should have sample configuration (or link out to Github-hosted samples) for each existing auth integration, including AWS.

### 👎 Actual Behavior with Screenshots

This doc -- https://backstage.io/docs/features/kubernetes/authentication#server-side-providers 

has no AWS examples.

<img width="1460" alt="Screenshot 2023-03-02 at 11 22 27 AM" src="https://user-images.githubusercontent.com/3137106/222488672-b0e89094-6631-4955-9ff8-7d89d0604a6b.png">

### 👟 Reproduction steps

What we were trying to do: connect an EKS-hosted Backstage instance to another EKS cluster running our applications. 

We tried looking into the source code to figure out the configuration fields - we ultimately relied on this StackOverflow post for an example:  https://stackoverflow.com/questions/74629572/how-to-connect-backstage-to-kubernetes-cluster-to-discover-pods

To produce a working Backstage configuration - 

```
kubernetes:
  serviceLocatorMethod:
    type: 'multiTenant'
  clusterLocatorMethods:
    - type: 'config'
      clusters:
        - url: https://<redacted>.<region>.eks.amazonaws.com
          name: <redacted> 
          authProvider: 'aws'
          skipTLSVerify: true
          skipMetricsLookup: true
auth:
  environment: 'production'
  providers:
    aws:
      development:
        accessKeyId: ${AWS_ACCESS_KEY_ID}
        secretAccessKey: ${AWS_SECRET_ACCESS_KEY}
```

### 🖥️ Your Environment

Backstage and Postgres running on AWS EKS.  A second EKS cluster hosts our applications. 

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!
