### ISSUE TITLE
🐛 Bug Report: Software Catalog import - Support/document fine-grained Github personal access tokens 

### ISSUE THREAD

**Issue by askmeegs** [backstage/backstage#16679]
### 📜 Description

The current Github integration docs (for Software Catalog entity import) are unclear as to whether [fine grained](https://github.blog/2022-10-18-introducing-fine-grained-personal-access-tokens-for-github/) Github personal access tokens (PATs) are supported. When we used a fine grained token, Github auth did not work. When we switched to a legacy token, auth worked, and we could import our catalog entities successfully. 

### 👍 Expected behavior

We ask that if fine grained tokens aren't currently supported, that docs are added to reflect that.

### 👎 Actual Behavior with Screenshots

During Backstage setup, we followed [these instructions](https://backstage.io/docs/getting-started/configuration/#setting-up-a-github-integration) to manually load existing Catalog entities from a private Github repo. 

We created a fine grained token (not a classic token) -- 

<img width="376" alt="Screenshot 2023-03-02 at 11 33 51 AM" src="https://user-images.githubusercontent.com/3137106/222492421-04f2a5ae-2b60-4e19-a0bb-ce8c2d462c2d.png">

Then mounted the token as a Kubernetes Secret, imported at runtime via Backstage app.config - 

```
integrations:
  github:
    - host: github.com
      # This is a Personal Access Token or PAT from GitHub. You can find out how to generate this token, and more information
      # about setting up the GitHub integration here: https://backstage.io/docs/getting-started/configuration#setting-up-a-github-integration
      token: ${GITHUB_TOKEN}
```

Then, we opened the Backstage UI and tried to import an entity to our software catalog, but got this 404 error.

<img width="1199" alt="Screenshot 2023-03-02 at 11 38 21 AM" src="https://user-images.githubusercontent.com/3137106/222493662-2604c69b-1000-4163-a7be-76d9e19e5e2d.png">

We then created a classic token, re-configured our Secret, restarted Backstage, and successfully authed to Github: 

<img width="854" alt="Screenshot 2023-03-02 at 11 38 55 AM" src="https://user-images.githubusercontent.com/3137106/222493796-f489c5b3-37c7-4da2-85bd-30d76f4030b6.png">

### 👟 Reproduction steps

Following instructions at: https://backstage.io/docs/getting-started/configuration/#setting-up-a-github-integration

### 🖥️ Your Environment

Backstage on AWS EKS

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!
