### ISSUE TITLE
🐛 Bug Report: empty alert message after 60+ seconds

### ISSUE THREAD

**Issue by jmcvea** [backstage/backstage#16702]
### 📜 Description

When a scaffolder action is running and doesn't provide a message to display in the UI for more than 60 seconds, then an empty alert message will be displayed and no further progress for the task activity will be reported in the UI.

### 👍 Expected behavior

There should be no empty alert messages displayed in the UI.

### 👎 Actual Behavior with Screenshots

Although the UI no longer reports any task activity messages or progress, the task does actually continue running in the background and subsequent scaffolder actions will be executed.

UI showing a blank alert message:
<img width="1203" alt="image" src="https://user-images.githubusercontent.com/2395088/222929576-eaedf2b8-3604-4cf6-b6f7-e4324130b107.png">

### 👟 Reproduction steps

A testcase to reproduce the behavior is described below.  Using this testcase, execute the template and specify input parameters for interval and delaySeconds to ensure that an info message is not sent to the UI for 60 seconds or more (e.g. delaySeconds=10 and interval=6)
❗ This behavior has not been reproducible when running Backstage locally, nor when running the built container locally.  This behavior has only been observed, so far,  with the built container deployed to AWS running behind an ALB:

1. In `backstage/packages/backend/src/plugins/scaffolder.ts`:
```ts
import { createTestLoggerAction } from './scaffolder/actions/create-testlogger.ts';
...
const actions = [
   ...builtInActions,
   createTestLoggerAction(),
];
```
2. Create a `backstage/packages/backend/src/plugins/scaffolder/actions/create-testlogger.ts` file with the following content:
```ts
import { createTemplateAction } from "@backstage/plugin-scaffolder-backend";

export function createTestLoggerAction() {

  return createTemplateAction<{ interval: number; maxSeconds: number, delaySeconds: number }>({
    id: 'test:slowAction',
    schema: {
      input: {
        required: ['interval', 'maxSeconds', 'delaySeconds'],
        type: 'object',
        properties: {
          delaySeconds: {
            type: 'number',
            title: 'Delay time',
            description: 'The number of seconds a "setTimeout" should run',
          },
          interval: {
            type: 'number',
            title: 'Interval',
            description: 'The number of setTimeouts to run in between info log messages.',
          },
          maxSeconds: {
            type: 'number',
            title: 'Maximum',
            description: 'The maximum number of seconds that this action should run',
          },
        }
      },
    },
    async handler(ctx) {
      const { interval, maxSeconds, delaySeconds } = ctx.input;
      ctx.logger.info("Entering the slow action with delayed logger.");
      ctx.logger.info(`Interval between "Status" info log messages is ${interval * delaySeconds} seconds.`);
      ctx.logger.info(`The amount for a timeout is ${delaySeconds} seconds.`);

      let index = 0;
      let status: string | undefined = 'RUNNING';
      while (status === 'RUNNING') {
        if (index % interval === 0) {
          ctx.logger.info(`Status: ${status}`);
        }
        await new Promise(resolve => setTimeout(resolve, delaySeconds * 1000));
        if ((index * delaySeconds) >= maxSeconds) {
          status = 'DONE';
        }
        index++;
      }
      ctx.logger.info("Action is completed.");
    },
  });
}
```
3. Create a `test-logger-template.yaml` file with the following content and make it available to Backstage through app-config.yaml or host it somewhere and import via URL.
```yaml
apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: slow-action-template
  title: Slow Action Template
  description: An example template to reproduce delayed logging behavior due to a long action
spec:
  owner: group:everyone
  type: service
  parameters:
    - title: Provide some test parameter information
      required:
        - delaySeconds
        - interval
        - maxSeconds
      properties:
        delaySeconds:
          title: Seconds to delay
          type: number
          description: The number of seconds to run a setTimeout delay
        interval:
          title: Interval
          type: number
          description: Number of setTimeouts between issuing an info-level log message
        maxSeconds:
          title: Maximum Seconds
          type: number
          description: The maximum number of seconds to run the test

  steps:
    - id: slowactiontest
      name: Slow Action Logging test
      action: test:slowAction
      input:
        delaySeconds: ${{ parameters.delaySeconds }}
        interval: ${{ parameters.interval }} 
        maxSeconds: ${{ parameters.maxSeconds }}
```
<img width="484" alt="image" src="https://user-images.githubusercontent.com/2395088/222930078-4030f1a2-09f8-4587-8f42-ad3884b3d10a.png">

### 📃 Provide the context for the Bug.

A custom scaffolder action may have justification to run for several minutes between meaningful updates to the UI.  For example, it may invoke an external API which needs to be restricted due to cost reasons or throttling by the 3rd party.

Workarounds are easy to implement by ensuring that some information is sent to the UI at least once every <60 seconds; however, without knowing about this behavior, it is difficult to debug.

### 🖥️ Your Environment

tested with Chrome browser Version 110.0.5481.177 (Official Build) (arm64)

`yarn backstage-cli info` output:
```
yarn run v1.22.19
$ /backstage/node_modules/.bin/backstage-cli info
OS:   Darwin 22.3.0 - darwin/arm64
node: v18.14.2
yarn: 1.22.19
cli:  0.22.1 (installed)
backstage:  1.10.0

Dependencies:
  @backstage/app-defaults                          1.1.0
  @backstage/backend-app-api                       0.3.1
  @backstage/backend-common                        0.18.1
  @backstage/backend-plugin-api                    0.3.1
  @backstage/backend-tasks                         0.4.2
  @backstage/catalog-client                        1.3.0, 1.3.1
  @backstage/catalog-model                         1.1.5, 1.2.0
  @backstage/cli-common                            0.1.11
  @backstage/cli                                   0.21.1, 0.22.1
  @backstage/config-loader                         1.1.8
  @backstage/config                                1.0.6
  @backstage/core-app-api                          1.4.0
  @backstage/core-components                       0.12.3, 0.12.4
  @backstage/core-plugin-api                       1.3.0, 1.4.0
  @backstage/dev-utils                             1.0.11
  @backstage/errors                                1.1.4
  @backstage/integration-aws-node                  0.1.1
  @backstage/integration-react                     1.1.9
  @backstage/integration                           1.4.2
  @backstage/plugin-api-docs                       0.8.14
  @backstage/plugin-app-backend                    0.3.41
  @backstage/plugin-auth-backend                   0.17.4
  @backstage/plugin-auth-node                      0.2.10
  @backstage/plugin-catalog-backend                1.7.1
  @backstage/plugin-catalog-common                 1.0.10, 1.0.11
  @backstage/plugin-catalog-graph                  0.2.26
  @backstage/plugin-catalog-import                 0.9.4
  @backstage/plugin-catalog-node                   1.3.2
  @backstage/plugin-catalog-react                  1.2.4, 1.3.0
  @backstage/plugin-catalog                        1.7.2
  @backstage/plugin-github-actions                 0.5.14
  @backstage/plugin-org                            0.6.4
  @backstage/plugin-permission-common              0.7.3
  @backstage/plugin-permission-node                0.7.4
  @backstage/plugin-permission-react               0.4.10, 0.4.9
  @backstage/plugin-proxy-backend                  0.2.35
  @backstage/plugin-scaffolder-backend             1.10.1
  @backstage/plugin-scaffolder-common              1.2.4
  @backstage/plugin-scaffolder-react               1.0.1
  @backstage/plugin-scaffolder                     1.10.1
  @backstage/plugin-search-backend-module-pg       0.5.2
  @backstage/plugin-search-backend-node            1.1.2
  @backstage/plugin-search-backend                 1.2.2
  @backstage/plugin-search-common                  1.2.1
  @backstage/plugin-search-react                   1.4.0
  @backstage/plugin-search                         1.0.7
  @backstage/plugin-tech-radar                     0.6.0
  @backstage/plugin-techdocs-backend               1.5.2
  @backstage/plugin-techdocs-module-addons-contrib 1.0.9
  @backstage/plugin-techdocs-node                  1.4.5
  @backstage/plugin-techdocs-react                 1.1.2
  @backstage/plugin-techdocs                       1.4.3
  @backstage/plugin-user-settings                  0.6.2
  @backstage/release-manifests                     0.0.7, 0.0.8
  @backstage/test-utils                            1.2.4
  @backstage/theme                                 0.2.16, 0.2.17
  @backstage/types                                 1.0.2
  @backstage/version-bridge                        1.0.3
Done in 0.67s.
```

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None
