### ISSUE TITLE
🐛 Bug Report: Badly configured aws k8s cluster credentials causes failed promise to crash backend

### ISSUE THREAD

**Issue by punkle** [backstage/backstage#16846]
### 📜 Description

You can configure the k8s backend plugin with an aws eks cluster that results in the backend crashing. The backend ideally [wouldnt crash](https://github.com/backstage/backstage/issues/16841), however the k8s plugin should also handle errors correctly so that unhandled promises do not surface to the top.

### 👍 Expected behavior

It should handle all of its promises in a way that does not leave it without resolving or rejecting.

### 👎 Actual Behavior with Screenshots

It does not and the exception causes the backend to fail.

### 👟 Reproduction steps

The following config is a little contrived however if you have the following config, where the first cluster is configured correctly and the second is configured with an invalid role, then you visit the kubernetes tab, the backend will crash.

```
kubernetes:
  objectTypes:
    - pods
    - services
  serviceLocatorMethod:
    type: 'multiTenant'
  clusterLocatorMethods:
    - type: 'config'
      clusters:
        - skipMetricsLookup: true
          name: "dev"
          url: "https://dev.kubernetes.cluster"
          authProvider: "aws"
          skipTLSVerify: true
          assumeRole: "arn:aws:iam::111111111111:role/role-for-external-kube-access"
          externalId: "dev"
        - skipMetricsLookup: true
          name: "prod"
          url: "https://prod.kubernetes.cluster"
          authProvider: "aws"
          skipTLSVerify: true
          assumeRole: "arn:aws:iam::22222222222:role/i-am-the-wrong-role"
          externalId: "prod"
```

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!
