### ISSUE TITLE
Ability to have template definition for templates outside of the Skeleton Source

### ISSUE THREAD

**Issue by benjdlambert** [backstage/backstage#1693]
## Feature Suggestion
- Currently, the skeleton for the template must live in the same repository as the `template.yaml` definition.
- You can currently only change the `path` which is relative to the `template.yaml` directory in the same repo.
- This means that if something from the existing ecosystem doesn't support backstage, you might have to fork the repo to add the definition there.
- Would be good if we could support absolute references to different repositories and the template location.

## Possible Implementation
- We change the `path` attribute to accept both relative locations from the current `template.yaml`  to accept absolute locations like the `managed-by-location` format.
- Or we add a new attribute which can reference a different location and use the `path` attribute to navigate the new location rather than the parent repo.

```yaml
apiVersion: backstage.io/v1alpha1
kind: Template
metadata:
  name: golang-starter
  title: Golang Microservice
  description: A template that scaffolds a microservice written in go
  tags:
    - Experimental
    - Go
spec:
  owner: web@example.com
  templater: cookiecutter
  type: service
  path: github:https://github.com/spotify/backstage/blob/master/templates/go-lang-starter/cookiecutter
  schema:
    #...
```
or 

```yaml
apiVersion: backstage.io/v1alpha1
kind: Template
metadata:
  name: golang-starter
  title: Golang Microservice
  description: A template that scaffolds a microservice written in go
  tags:
    - Experimental
    - Go
spec:
  owner: web@example.com
  templater: cookiecutter
  type: service
  location: github:https://github.com/spotify/backstage
  path: templates/go-lang-starter/cookiecutter
  schema:
    #...
```

Would be interested in feedback from @spotify/backstage-core and the community on which approach feels better.
