### ISSUE TITLE
🚀 Feature: Allow discovering all organisations in GitHub integration

### ISSUE THREAD

**Issue by deimantastumas** [backstage/backstage#16932]
### 🔖 Feature description

Support discovering repositories in all organisations without needing to maintain a static organisations list.

### 🎤 Context

While the feature wouldn't work on public GitHub, this feature is especially handy on GitHub Enterprise where descriptors need to be scraped from all company repositories.

### ✌️ Possible Implementation

If GitHub integration is configured with enterprise instance, allow omitting the `organisations` field and then list all organisations on the go.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by deimantastumas** [comment]
Regarding the entire world - this is the reason why I suggest supporting such a feature only on GitHub Enterprise since the organizations count will be limited to only what the company is using.

As for how it could be implemented, I suggest making `organization` field optional, e.g.:
```
catalog:
  providers:
    github:
      allOrgs:
        catalogPath: '/catalog-info.yaml' # string
```
Or support regex, e.g.:
```
catalog:
  providers:
    github:
      allOrgs:
        organization: ".*"
        catalogPath: '/catalog-info.yaml' # string
```
And then when the plugin processes the config, it would check if the GitHub instance is enterprise, only then the optional organization field and/or regex would be allowed.
