### ISSUE TITLE
🐛 Bug Report: Github authentication provider doesn't support environment variables

### ISSUE THREAD

**Issue by wanisfahmyDE** [backstage/backstage#16981]
### 📜 Description

environment variables are not caught when passed to the auth block in `app-config.production.yaml`

**non working examples:**

```yaml
auth:
  environment: production
  providers:
    github:
      production:
        clientId: ${AUTH_GITHUB_CLIENT_ID}
        clientSecret: ${AUTH_GITHUB_CLIENT_SECRET}
```

```yaml
auth:
  environment: production
  providers:
    github:
      production:
        clientId: 
           $env:  ${AUTH_GITHUB_CLIENT_ID}
        clientSecret: 
           $env: ${AUTH_GITHUB_CLIENT_SECRET}
```

What works is mounting a file with the credentials and using an include like this (documented my findings here https://github.com/backstage/backstage/discussions/16900) :

```yaml
auth:
  environment: production
  providers:
    github:
      production:
         $include: /tmp/github-backstage-credentials.yaml
```

Additionally, using the integration block with environment variables are working fine, which is confusing because the auth block doesn't seem to accept env variables but the integrations does.

working example from same deployment for integrations block using env variables
```yaml
integrations:
  github:
    - host: github.com
      apps:
        - appId:
            $env: APP_ID
          webhookUrl:
            $env: WEBHOOK_URL
          clientId:
            $env: AUTH_GITHUB_CLIENT_ID
          clientSecret:
            $env: AUTH_GITHUB_CLIENT_SECRET
          webhookSecret:
            $env: WEBHOOK_SECRET
          privateKey:
            $env: PRIVATE_KEY
```

### 👍 Expected behavior

passing environment variables to the auth block works like other blocks (integration, database, etc)

### 👎 Actual Behavior with Screenshots

the entire auth block configuration just doesn't get caught up when passing the environment variables, as if the block is not defined. The error says: "unknown auth provider github" 

### 👟 Reproduction steps

* define and auth block in `app-config.production.yaml` and pass environment variables for the Github Client ID and secret
* deploy the application
* attempt to login with Github on backstage
* response in github browser window is 404
* redirect_uri leads to "unknown auth provider github"

### 🖥️ Your Environment

```
OS:   Darwin 21.6.0 - darwin/arm64
node: v18.14.1
yarn: 1.22.19
cli:  0.22.3 (installed)
backstage:  1.11.0

Dependencies:
  @backstage/app-defaults                          1.2.0
  @backstage/backend-app-api                       0.4.0
  @backstage/backend-common                        0.18.2
  @backstage/backend-dev-utils                     0.1.0
  @backstage/backend-plugin-api                    0.4.0
  @backstage/backend-tasks                         0.4.3
  @backstage/catalog-client                        1.3.1
  @backstage/catalog-model                         1.2.0
  @backstage/cli-common                            0.1.11
  @backstage/cli                                   0.22.3
  @backstage/config-loader                         1.1.8
  @backstage/config                                1.0.6
  @backstage/core-app-api                          1.5.0
  @backstage/core-components                       0.12.4
  @backstage/core-plugin-api                       1.4.0
  @backstage/errors                                1.1.4
  @backstage/eslint-plugin                         0.1.1
  @backstage/integration-aws-node                  0.1.1
  @backstage/integration-react                     1.1.10
  @backstage/integration                           1.4.2
  @backstage/plugin-adr-backend                    0.3.0
  @backstage/plugin-adr-common                     0.2.6
  @backstage/plugin-adr                            0.4.0
  @backstage/plugin-api-docs                       0.9.0
  @backstage/plugin-app-backend                    0.3.42
  @backstage/plugin-auth-backend                   0.18.0
  @backstage/plugin-auth-node                      0.2.11
  @backstage/plugin-catalog-backend-module-github  0.2.5
  @backstage/plugin-catalog-backend                1.7.2
  @backstage/plugin-catalog-common                 1.0.11
  @backstage/plugin-catalog-graph                  0.2.27
  @backstage/plugin-catalog-import                 0.9.5
  @backstage/plugin-catalog-node                   1.3.3
  @backstage/plugin-catalog-react                  1.3.0
  @backstage/plugin-catalog                        1.8.0
  @backstage/plugin-events-node                    0.2.3
  @backstage/plugin-github-actions                 0.5.15
  @backstage/plugin-github-pull-requests-board     0.1.9
  @backstage/plugin-org                            0.6.5
  @backstage/plugin-permission-common              0.7.3
  @backstage/plugin-permission-node                0.7.5
  @backstage/plugin-permission-react               0.4.10
  @backstage/plugin-proxy-backend                  0.2.36
  @backstage/plugin-scaffolder-backend             1.11.0
  @backstage/plugin-scaffolder-common              1.2.5
  @backstage/plugin-scaffolder-node                0.1.0
  @backstage/plugin-scaffolder-react               1.1.0
  @backstage/plugin-scaffolder                     1.11.0
  @backstage/plugin-search-backend-module-pg       0.5.3
  @backstage/plugin-search-backend-node            1.1.3
  @backstage/plugin-search-backend                 1.2.3
  @backstage/plugin-search-common                  1.2.1
  @backstage/plugin-search-react                   1.5.0
  @backstage/plugin-search                         1.1.0
  @backstage/plugin-tech-radar                     0.6.1
  @backstage/plugin-techdocs-backend               1.5.3
  @backstage/plugin-techdocs-module-addons-contrib 1.0.10
  @backstage/plugin-techdocs-node                  1.5.0
  @backstage/plugin-techdocs-react                 1.1.3
  @backstage/plugin-techdocs                       1.5.0
  @backstage/plugin-user-settings                  0.7.0
  @backstage/release-manifests                     0.0.8
  @backstage/test-utils                            1.2.5
  @backstage/theme                                 0.2.17
  @backstage/types                                 1.0.2
  @backstage/version-bridge                        1.0.3
✨  Done in 3.50s.
```

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by Rugvip** [comment]
I'm not able to reproduce this, the following works for me:

```yaml
auth:
  environment: production
  providers:
    github:
      production:
        clientId: ${AUTH_GITHUB_CLIENT_ID}
        clientSecret: ${AUTH_GITHUB_CLIENT_SECRET}
```

Are you sure you have `AUTH_GITHUB_CLIENT_ID` and `AUTH_GITHUB_CLIENT_SECRET` set in your environment?
