### ISSUE TITLE
🐛 Bug Report: Unclear dependency versions for `@backstage/plugin-scaffolder-react`

### ISSUE THREAD

**Issue by seanblonien** [backstage/backstage#16982]
### 📜 Description

The `@backstage/plugin-scaffolder-react` package has an ambiguous dependency on the `@rjsf/core` dependency which somehow requires 2 versions of the same package -- therefore producing a yarn install warning about the ambiguity 

### 👍 Expected behavior

There should be no yarn install warning for the `@backstage/plugin-scaffolder-react` package

### 👎 Actual Behavior with Screenshots

![image](https://user-images.githubusercontent.com/33133478/226456742-89aa0b7f-4ff6-413d-bae3-6a00fb14b524.png)

### 👟 Reproduction steps

1. Have a backstage v1.12.0 repo setup using [installation steps](https://backstage.io/docs/getting-started/), following the [Migration to Yarn 3](https://backstage.io/docs/tutorials/yarn-migration/) steps to upgrade to yarn 3.5
2. Run `yarn install`
3. See the long list of warnings, but specifically, the warnings related to the `@backstage/plugin-scaffolder-react` package

### 📃 Provide the context for the Bug.

When upgrading to Yarn 3 (which is supposedly supported by Backstage), there are a lot of missing peer dependency packages in `@backstage` packages. I have been able to resolve the missing peer dependencies (related to `react`, `react-dom`, and `react-router-dom` by using the `packageExtensions` property in the `.yarnrc.yml` file, but there is a bug that yarn cannot seem to resolve via either `resolutions` or `packageExtensions`

From what I can tell, this plugin has this conflict because there are two versions of the `@rjsf/core` package, as seen in the `yarn./lock`
![image](https://user-images.githubusercontent.com/33133478/226456403-737bec67-7974-4296-aa63-832a11bb1dc4.png)

Here is the `resolutions` field used by yarn in the `package.json`:
```
"resolutions": {
  "@date-io/core": "^1.3.13",
  "graphql-ws": "^5.4.1",
  "@types/react": "^17",
  "@types/react-dom": "^17"
},
```
and my `.yarnrc.yml` file
```
nmMode: classic
nodeLinker: node-modules
pnpEnableEsmLoader: true
pnpFallbackMode: 'all'
enableGlobalCache: true

yarnPath: .yarn/releases/yarn-3.5.0.cjs

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: '@yarnpkg/plugin-typescript'

packageExtensions:
  '@backstage/plugin-user-settings@*':
    dependencies:
      react-dom: ^17.0.2
  '@backstage/plugin-techdocs-react@*':
    dependencies:
      react-dom: ^17.0.2
  '@backstage/plugin-api-docs@*':
    dependencies:
      react-dom: ^17.0.2
  '@backstage/integration-react@*':
    dependencies:
      react-dom: ^17.0.2
      react-router-dom: '6.9.0'
  '@backstage/theme@*':
    dependencies:
      react: ^17.0.2
      react-dom: ^17.0.2
  'codemirror-graphql@*':
    dependencies:
      '@codemirror/language': '^0.20.0'
  '@graphiql/react@*':
    dependencies:
      'graphql-ws': '^5.4.1'
  'graphiql@*':
    dependencies:
      'graphql-ws': '^5.4.1'
  '@backstage/plugin-scaffolder-react@*':
    dependencies:
      react-dom: ^17.0.2
  '@backstage/plugin-scaffolder@*':
    dependencies:
      react-dom: ^17.0.2
  '@backstage/plugin-techdocs-module-addons-contrib@*':
    dependencies:
      react-dom: ^17.0.2
      react-router-dom: '6.9.0'
  '@backstage/plugin-tech-radar@*':
    dependencies:
      react-dom: ^17.0.2
      react-router-dom: '6.9.0'
  '@backstage/plugin-search@*':
    dependencies:
      react-dom: ^17.0.2
  '@backstage/plugin-search-react@*':
    dependencies:
      react-dom: ^17.0.2
  '@backstage/plugin-permission-react@*':
    dependencies:
      react-dom: ^17.0.2
  '@backstage/plugin-github-actions@*':
    dependencies:
      react-dom: ^17.0.2
  '@backstage/plugin-org@*':
    dependencies:
      react-dom: ^17.0.2
  '@backstage/plugin-catalog@*':
    dependencies:
      react-dom: ^17.0.2
  '@backstage/plugin-catalog-react@*':
    dependencies:
      react-dom: ^17.0.2
  '@backstage/plugin-catalog-import@*':
    dependencies:
      react-dom: ^17.0.2
  '@backstage/plugin-catalog-graph@*':
    dependencies:
      react-dom: ^17.0.2
  '@backstage/core-components@*':
    dependencies:
      '@date-io/core': '*'
  '@backstage/cli@*':
    dependencies:
      '@svgr/core': '^6.5.1'
    peerDependenciesMeta:
      typescript:
        optional: true
  '@backstage/core-app-api@*':
    dependencies:
      react-dom: ^17.0.2
  '@backstage/test-utils@*':
    dependencies:
      '@testing-library/dom': '^8.0.0'
  '@backstage/plugin-techdocs-node@*':
    dependencies:
      '@aws-sdk/abort-controller': '*'
```

### 🖥️ Your Environment

```
OS:   Linux 5.15.90.1-microsoft-standard-WSL2 - linux/x64
node: v18.14.2
yarn: 3.5.0
cli:  0.22.4 (installed)
backstage:  1.12.0

Dependencies:
  @backstage/app-defaults                                  1.2.1
  @backstage/backend-app-api                               0.4.1
  @backstage/backend-common                                0.18.3
  @backstage/backend-dev-utils                             0.1.1
  @backstage/backend-plugin-api                            0.5.0
  @backstage/backend-tasks                                 0.5.0
  @backstage/catalog-client                                1.4.0
  @backstage/catalog-model                                 1.2.1
  @backstage/cli-common                                    0.1.12
  @backstage/cli                                           0.22.4
  @backstage/config-loader                                 1.1.9
  @backstage/config                                        1.0.7
  @backstage/core-app-api                                  1.6.0
  @backstage/core-components                               0.12.5
  @backstage/core-plugin-api                               1.5.0
  @backstage/errors                                        1.1.5
  @backstage/eslint-plugin                                 0.1.2
  @backstage/integration-aws-node                          0.1.2
  @backstage/integration-react                             1.1.11
  @backstage/integration                                   1.4.3
  @backstage/plugin-api-docs                               0.9.1
  @backstage/plugin-app-backend                            0.3.43
  @backstage/plugin-auth-backend                           0.18.1
  @backstage/plugin-auth-node                              0.2.12
  @backstage/plugin-bitbucket-cloud-common                 0.2.4
  @backstage/plugin-catalog-backend-module-bitbucket-cloud 0.1.10
  @backstage/plugin-catalog-backend-module-bitbucket       0.2.10
  @backstage/plugin-catalog-backend                        1.8.0
  @backstage/plugin-catalog-common                         1.0.12
  @backstage/plugin-catalog-graph                          0.2.28
  @backstage/plugin-catalog-import                         0.9.6
  @backstage/plugin-catalog-node                           1.3.4
  @backstage/plugin-catalog-react                          1.4.0
  @backstage/plugin-catalog                                1.9.0
  @backstage/plugin-events-node                            0.2.4
  @backstage/plugin-github-actions                         0.5.16
  @backstage/plugin-org                                    0.6.6
  @backstage/plugin-permission-common                      0.7.4
  @backstage/plugin-permission-node                        0.7.6
  @backstage/plugin-permission-react                       0.4.11
  @backstage/plugin-proxy-backend                          0.2.37
  @backstage/plugin-scaffolder-backend                     1.12.0
  @backstage/plugin-scaffolder-common                      1.2.6
  @backstage/plugin-scaffolder-node                        0.1.1
  @backstage/plugin-scaffolder-react                       1.2.0
  @backstage/plugin-scaffolder                             1.12.0
  @backstage/plugin-search-backend-module-pg               0.5.4
  @backstage/plugin-search-backend-node                    1.1.4
  @backstage/plugin-search-backend                         1.2.4
  @backstage/plugin-search-common                          1.2.2
  @backstage/plugin-search-react                           1.5.1
  @backstage/plugin-search                                 1.1.1
  @backstage/plugin-tech-radar                             0.6.2
  @backstage/plugin-techdocs-backend                       1.6.0
  @backstage/plugin-techdocs-module-addons-contrib         1.0.11
  @backstage/plugin-techdocs-node                          1.6.0
  @backstage/plugin-techdocs-react                         1.1.4
  @backstage/plugin-techdocs                               1.6.0
  @backstage/plugin-user-settings                          0.7.1
  @backstage/release-manifests                             0.0.9
  @backstage/test-utils                                    1.2.6
  @backstage/theme                                         0.2.18
  @backstage/types                                         1.0.2
  @backstage/version-bridge                                1.0.3
```

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else
