### ISSUE TITLE
🐛 Bug Report: OwnedEntityPicker allows user to clear value and continue when required

### ISSUE THREAD

**Issue by ltdonner** [backstage/backstage#16993]
### 📜 Description

The OwnedEntityPicker works fine if you have it required and a user just never touches the field, but if a user goes in and fills out the field, then clears it, it will let them continue without filling in a value when it's required. 

### 👍 Expected behavior

When users clear the value in the field, it should prevent them from continuing if the field is required

### 👎 Actual Behavior with Screenshots

When users clear the value in the field, it allows them to continue when the field is required

### 👟 Reproduction steps

1. Set up a template that uses the OwnedEntityPicker as a required field.
```
- title: General Information
  required:
    - system
  properties:
    system:
      title: System
      type: string
      description: The System this component belongs to. 
      ui:field: OwnedEntityPicker
      ui:options:
        allowArbitraryValues: false
        allowedKinds:
          - System
 ```
2. Register the template in Backstage
3. Go to Create > Choose the template
4. Fill out the required field, then click the 'x' to clear it
5. Note you can go to the next section without a validation error

### 🖥️ Your Environment

OS:   Darwin 21.6.0 - darwin/x64
node: v16.16.0
yarn: 1.22.19
cli:  0.22.0 (installed)
backstage:  1.9.1

Dependencies:
  @backstage/app-defaults                                  1.0.10, 1.1.0
  @backstage/backend-common                                0.17.0
  @backstage/backend-plugin-api                            0.2.0
  @backstage/backend-tasks                                 0.4.0
  @backstage/catalog-client                                1.2.0, 1.3.0
  @backstage/catalog-model                                 1.1.5, 1.1.4
  @backstage/cli-common                                    0.1.11
  @backstage/cli                                           0.20.0, 0.22.0
  @backstage/config-loader                                 1.1.8, 1.1.7
  @backstage/config                                        1.0.5, 1.0.6
  @backstage/core-app-api                                  1.4.0, 1.3.0
  @backstage/core-components                               0.11.2, 0.12.2, 0.12.3, 0.9.3
  @backstage/core-plugin-api                               1.2.0, 1.3.0
  @backstage/dev-utils                                     1.0.11, 1.0.10
  @backstage/errors                                        1.1.4
  @backstage/integration-aws-node                          0.1.0
  @backstage/integration-react                             1.1.9, 1.1.8
  @backstage/integration                                   1.4.1, 1.4.2
  @backstage/plugin-api-docs                               0.8.13
  @backstage/plugin-auth-backend                           0.17.2
  @backstage/plugin-auth-node                              0.2.8
  @backstage/plugin-catalog-backend-module-github          0.2.2
  @backstage/plugin-catalog-backend-module-gitlab          0.1.10
  @backstage/plugin-catalog-backend                        1.6.0
  @backstage/plugin-catalog-common                         1.0.10, 1.0.9
  @backstage/plugin-catalog-graph                          0.2.25
  @backstage/plugin-catalog-import                         0.9.3
  @backstage/plugin-catalog-node                           1.3.0
  @backstage/plugin-catalog-react                          1.2.3, 1.2.4
  @backstage/plugin-catalog                                1.7.1
  @backstage/plugin-circleci                               0.3.13
  @backstage/plugin-events-node                            0.2.0
  @backstage/plugin-github-actions                         0.5.13
  @backstage/plugin-home                                   0.4.29
  @backstage/plugin-org                                    0.6.3
  @backstage/plugin-permission-backend                     0.5.14
  @backstage/plugin-permission-common                      0.7.2, 0.7.3
  @backstage/plugin-permission-node                        0.7.2
  @backstage/plugin-permission-react                       0.4.8, 0.4.9
  @backstage/plugin-proxy-backend                          0.2.33
  @backstage/plugin-scaffolder-backend-module-cookiecutter 0.2.14
  @backstage/plugin-scaffolder-backend                     1.9.0
  @backstage/plugin-scaffolder-common                      1.2.3, 1.2.4
  @backstage/plugin-scaffolder-react                       1.0.1
  @backstage/plugin-scaffolder                             1.9.1
  @backstage/plugin-search-backend-node                    1.1.0
  @backstage/plugin-search-backend                         1.2.0
  @backstage/plugin-search-common                          1.2.0, 1.2.1
  @backstage/plugin-search-react                           1.3.1
  @backstage/plugin-search                                 1.0.6
  @backstage/plugin-sonarqube-backend                      0.1.4
  @backstage/plugin-sonarqube-react                        0.1.0
  @backstage/plugin-sonarqube                              0.6.1
  @backstage/plugin-stack-overflow                         0.1.9
  @backstage/plugin-techdocs-backend                       1.5.0
  @backstage/plugin-techdocs-node                          1.4.3
  @backstage/plugin-techdocs-react                         1.1.1
  @backstage/plugin-techdocs                               1.4.2
  @backstage/plugin-user-settings                          0.6.1
  @backstage/release-manifests                             0.0.6, 0.0.8
  @backstage/test-utils                                    1.2.4, 1.2.3
  @backstage/theme                                         0.2.16
  @backstage/types                                         1.0.2
  @backstage/version-bridge                                1.0.3

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, I don't have time to work on this right now

**Comment by morales-martin** [comment]
Hi - I tried reproducing the bug but didn't seem to run into any issues with validation after filling out and emptying the entity picker using 'X'; the expected validation error was raised. Not sure if I am missing something here?

This is the template I used:
```
  apiVersion: scaffolder.backstage.io/v1beta3
  kind: Template
  metadata:
    name: general-information
    title: General Information
    description: Inquire general information
    tags:
      - recommended
      - techdocs
  spec:
    owner: backstage/techdocs-core
    type: documentation
    parameters:
    - title: Fill in some steps
      required:
        - system
      properties:
        name:
          title: Name
          type: string
          description: Unique name of the component
          ui:field: EntityNamePicker
          ui:autofocus: true
        description:
          title: Description
          type: string
          description: A description for the component
        system:
          title: System
          type: string
          description: The System this component belongs to. 
          ui:field: OwnedEntityPicker
          ui:options:
            allowArbitraryValues: false
            allowedKinds:
              - System
    steps:
      - name: Dummy step
        action: debug:log
        input:
          listWorkspace: true
```
