### ISSUE TITLE
🚀 Feature: Add a filter to the scaffolder to parse full entity refs

### ISSUE THREAD

**Issue by jmadureira** [backstage/backstage#17053]
### 🔖 Feature description

Provide a new `TemplateFilter` (called `parseEntityRef` for instance) that receives a full entity ref in the format `kind:namespace/name` and parses it returning an object with each attribute read

```js
{
  kind: 'kind',
  namespace: 'namespace',
  name: 'name'
}
```

### 🎤 Context

This is a follow-up from #16577 where the `EntityPicker` component no longer uses the `humanizeEntityRef` to return the entity selected and instead returns the full entity ref in the format `kind:namespace/name`.

This change pretty much broke template rendering.
For an user `EntityPicker` component that selected the user `John` the scaffolder previously would render the name whereas now it will render something like `user:default/John`.

### ✌️ Possible Implementation

A couple of options were discussed on the Backstage Discord channel:

### Create a `parseEntityRef` filter

This will allow us to write have something like:

```yaml
  steps:
    - id: fetch-base
      ...
      action: fetch:template
      input:
        ...
        values:
          ...
          ownerEntity: ${{ parameters.ownerEntity | parseEntityRef }}
          ...
```

This has the consequence of having things like this.

```
${{ (parameters.ownerEntity | parseEntityRef).name }}
```

### Add another filter to pick attributes by key

Something like `pick(key)` which would allow us to have a cleaner description.

```
${{ parameters.ownerEntity | parseEntityRef | pick('name') }}
```

### `parseEntityRef` with default attributes

A variation of the previous `pick` filter where the `parseEntityRef` accepts an optional attribute we want to fetch.

```
${{ parameters.ownerEntity | parseEntityRef('name) }}
```

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by regicsolutions** [comment]
@jmadureira is it possible to pick the value of a specific annotation? tried this but it didnt work - 

`${{ parameters.awsAccount | parseEntityRef | pick('amazonaws.com/account-id') }}`

**Comment by jmadureira** [comment]
@regicsolutions I don't think you're using this correctly.

The `parseEntityRef` is for values provided by `EntityPicker`s in the format `kind:namespace/name` (actually anything that provides a string in that format will work).

The `pick` (if I understood the implementation correctly) simply returns the value associated with a key.

I don't know exactly what that `parameters.awsAccount` has but assuming it returns the annotations of an entity you can try

```
${{ parameters.awsAccount | pick('amazonaws.com/account-id') }}
```

or even something more extreme

```
${{ parameters.awsAccount | pick('annotations') | pick('amazonaws.com/account-id') }}
```

but ... again ... this depends on what the `parameters.awsAccount` contains.

Hope this helps.

**Comment by jmadureira** [comment]
@regicsolutions is that what you're passing on the `parameters.awsAccount`?

- If yes then it's probably a string so you will need to parse it before using the `pick` filters
- If no then you need to know exactly what is being passed. `${{ parameters.awsAccount | dump }}` is useful for troubleshooting these things

**Comment by regicsolutions** [comment]
@jmadureira Here is what i am using as a parameter:

```
    - title: AWS Information
      properties:
        awsAccount:
          type: string
          title: Select a AWS Account
          ui:field: OwnedEntityPicker
          ui:options:
            catalogFilter: 
              - kind: Resource
                spec.type: cloud-account
```
Here is what i pass to the action:

```
    - id: fetch-template
      name: Generate CI/CD Files
      action: fetch:template 
      input:
        url: ./skeleton
        values:
          awsAccount: ${{ parameters.awsAccount | pick('annotations') | pick('amazonaws.com/account-id') }}
```

Trying to print the value of this annotation into a file which is `123456789`

**Comment by jmadureira** [comment]
@regicsolutions the `OwnedEntityPicker` is a extension of the `EntityPicker` that returns an entity ref string in the format of `kind:namespace/name` and not the full entity object that you expect i.e.; it won't provide the annotations you're looking for.

There is however a `catalog:fetch` built-in action that you might want to try out. I haven't used it myself but the idea is that you pass the `parameters.awsAccount` to it and then use the output on your `fetch:template` action. Something like

```yaml
- id: catalogFetch
  name: Fetch entity
  action: catalog:fetch
  input:
    entityRef: ${{ parameters.awsAccount }}
- id: fetch-template
  name: Generate CI/CD Files
  action: fetch:template 
  input:
    url: ./skeleton
    values:
      awsAccount: ${{ steps.catalogFetch.entity.metadata.annotations | pick('amazonaws.com/account-id') }}
```

**Comment by regicsolutions** [comment]
Thanks for the tip @jmadureira !

This ended up working for me:

```
    - id: catalogFetch
      name: Fetch Context
      action: catalog:fetch
      input:
        entityRef: ${{ parameters.awsAccount }}
        
   - id: fetchTemplate
      name: Generate CI/CD Files
      action: fetch:template 
      input:
        url: ./skeleton
        values:
          awsAccount: ${{ steps['catalogFetch'].output.entity.metadata.annotations | pick('amazonaws.com/account-id') }}
```

**Comment by regicsolutions** [comment]
@jmadureira have you had any luck getting the picker to work for more than one entityRef?

I tried the following but no luck - 

```
  steps: 
    - id: fetch
      name: Fetch Multiple Entity Refs
      action: catalog:fetch 
      input:
        entityRefs:
        - ${{ parameters.system }}
        - ${{ parameters.awsAccount }}

    - id: log
      name: Debug Multi Entity Ref
      action: debug:log 
      input:   
        listWorkspace: true
        extra: ${{ parameters.awsAccount | dump }}                                                                                                                
        awsAccount: ${{ steps['fetch'].output.entities }}  # Prints both refs
        meta: ${{ steps['fetch'].output.entities | parseEntityRef | pick('annotations') | pick('amazonaws.com/account-id') }} # Not able to parse
```
