### ISSUE TITLE
🐛 Bug Report: Unable to create table knex_migration - no schema selected

### ISSUE THREAD

**Issue by guimilleo** [backstage/backstage#17051]
### 📜 Description

I'm trying to setup the backstage with the following configuration

```
app:
  baseUrl: <my_url>

backend:
  baseUrl: <my_url>
  listen:
    port: 7007
    host: 0.0.0.0

  database:
    client: pg
    pluginDivisionMode: schema
    ensureExists: false
    connection:
      connectionString: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
      knexConfig:
        searchPath: ['knex', 'public' ]
        migrations:
          schemaName: 'backstage'

catalog:
  locations: []
```
But when I run docker-compose up -d, I'm getting a database error to create the knex_migration table.

I tried putting knexConfig in the template but didn't work. 

If I remove `ensureExists: false`works, but I need this configuration.

Does anybody know if this is the right config to specify the schema?
```
knexConfig:
        searchPath: ['knex', 'public' ]
        migrations:
          schemaName: 'backstage'
```
### 👍 Expected behavior

Docker should start properly

### 👎 Actual Behavior with Screenshots

knex migration is failing to create table

`2023-03-23 10:33:55 Backend failed to start up error: create table "knex_migrations" ("id" serial primary key, "name" varchar(255), "batch" integer, "migration_time" timestamptz) - no schema has been selected to create in`

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by padupe** [comment]
Hello @guimilleo!
Have you tried to follow the example that the [documentation](https://backstage.io/docs/tutorials/switching-sqlite-postgres) presents?

```yaml
[...]

database:
    client: pg
    connection:
      host: ${POSTGRES_HOST}
      port: ${POSTGRES_PORT}
      user: ${POSTGRES_USER}
      password: ${POSTGRES_PASSWORD}
    knexConfig:
      pool:
        min: 3
        max: 12
        acquireTimeoutMillis: 60000
        idleTimeoutMillis: 60000

[...]
```

I used this configuration model in the company where I worked previously, as well as in the current one without any problems.
What is, in fact, the need to follow the configuration you presented?

**Comment by Rugvip** [comment]
The `knexConfig` section is a bit of a black box where you can pass options that effectively break the DB setup, use it with caution. In this case I think the `schemaName` setting isn't supported. If you want to split DBs by schema, see this bit: https://backstage.io/docs/tutorials/switching-sqlite-postgres/#using-a-single-database

**Comment by skolv-lintom** [comment]
For me to get it to work I had to add

```
knexConfig:
        searchPath: ['knex', 'public' ]
        migrations:
          schemaName: 'backstage'
```

Just using "pluginDivisionMode: schema" did not do it
