### ISSUE TITLE
[WIP] 💬 RFC: Dynamic microservice plugins for front-end

### ISSUE THREAD

**Issue by tumido** [backstage/backstage#17054]
### 🔖 Need

We want to be able to manage a plugin lifecycle separately from the main backstage core application. This includes installing new plugins and removing and upgrading them. Plugins should be able to communicate with other Backstage APIs and services while being individually scalable, deployable, and pluggable through configuration. Adding or removing a plugin from Backstage should not require NPM package installation and Backstage image rebuilds and redeployments. Instead, we want to be able to add plugins as dynamic content. 

This RFC is limited to front-end plugins only. Frontend plugins should not be restricted to specific packaging and deployment types but should be mountable from any HTTP service provider or CDN directly.

### 🎉 Proposal

We would like to use the Webpack module federation for most of the heavy lifting. In Red Hat, we’ve successfully used this approach for a multitude of products and we would like to donate this user experience to Backstage as well. Red Hat is currently in process of decoupling this federation codebase into a standalone pluggable framework:

https://github.com/scalprum/scaffloding

This framework has minimal dependencies and serves as a wrapper on top of the Webpack module federation providing a unified API.

#### Plugin side changes

We don’t want users to do extensive plugin rewrites or major disruptive code changes. We also want all the plugins to be backward compatible. Currently, plugins are built by Rollup. We propose to extend the build pipeline in `@backstage/cli` with an additional build task, that would invoke Webpack instead (in order to use Webpack module federation, we need to use Webpack instead of Rollup). This additional build task is used only in case the plugin is compatible with this RFC and produces an additional set of assets. As a result, the plugins feature 2 sets of assets, one for the standard plugin build via Rollup (in `dist` folder) and one extra for Webpack module federation (in `dist-scalprum`). If the additional set of assets will be built is decided based on the plugin’s `package.json` content via the addition of:

```
  "scalprum": {
    # Webpack module name, same as used later in the Scalprum registry
    "name": "backstage.plugin-github-actions",
    # Modules exposed through Webpack module federation
    "exposedModules": {
      "./EntityGithubActionsContent": "./src/EntityGithubActionsContent",
      "./EntityRecentGithubActionsRunsCard": "./src/EntityRecentGithubActionsRunsCard"
    }
  },
```

Once built, this additional set of assets contains built JS bundle + a `plugin-manifest.json` for Scalprum.

#### Backstage instance changes

We propose that the plugin discovery should be handled statically through Backstage configuration file:

```
# app-config.yaml
app:
  dynamicPlugins:
    # list all remote plugins
    registry:
      backstage.plugin-entity-feedback:
        # manifest location can refer to either an absolute location or relative location proxied through backstage proxy 
        manifestLocation: '/api/proxy/scalprum/backstage.plugin-entity-feedback/plugin-manifest.json'
        # manifestLocation: 'http://localhost:8003/plugin-manifest.json'

proxy:
  '/scalprum/backstage.plugin-entity-feedback':
    target: 'http://127.0.0.1:8003'
    changeOrigin: true
    secure: false

```

Caveat: Webpack requires packages to define `basePath`. It can be an absolute path containing the host or it can be a relative path. While the relative paths provide us with more flexibility (the package can be built once and hosted multiple times), it poses a challenge for module federation. When module federation is used, Webpack naturally fetches resources with the relative path from the same host as the rest of the bundle. In the case of the local setup of Backstage this defaults to `http://localhost:3000/`. This creates a problem for our proxied approach - backstage needs to proxy requests from frontend to the backend (since backstage proxy is served on the backend). This can be achieved by extending the `package.json` in `packages/app` with WebpackDevServer proxy:

```
  "proxy": {
    "/api": {
      "target": "http://localhost:7007"
    }
```

A remote package declared in the app-config `app.dynamicPlugins.registry` is consumed by Backstage’s `AppManager` and passed to `ScalprumContext`. This makes the remote plugin globally available and consumable from within Backstage front-end.

Simple remote components can be used via:

```
<ScalprumComponent
  scope="backstage.plugin-github-actions"
  module="./EntityGithubActionsContent"
/>
```

While this component is loaded from a remote location, this approach still requires manual code changes to mount it in DOM. That is not desirable, the end goal is to do so through configuration changes. This can be achieved by a set of helper components and config values that define user-configurable mount points:

(This is WIP):
```
app:
  dynamicPlugins:
    mounts:
      # mount point name referenced in a helper React component which pulls in all relevant remote plugins
      catalog.entity-page.tab:
          # name from the plugin registry
        - name: 'backstage.plugin-github-actions'
          module: './EntityGithubActionsContent'
          # additional entity filter
          filter:
            kind: Component
            spec.type: service
          # subroute
          path: /ci-cd-external
          # additional props
          title: 'CI/CD (Scalprum)'
```

These endpoints are used by the Backstage instance frontend code and instance maintainers decide where and how to use these mount points. This addresses the need to support diverse Backstage instances, where each instance can be totally different from the other ones. To explain this in simple terms:

- **WHAT** is mounted is defined in `app-config.yaml` (therefore extensible without code changes)
- **WHERE** are the components mounted is decided by the Backstage instance maintainer through code changes.

WIP example:

```
# EntityLayout.tsc

<EntityLayoutWrapper>
  <DymanicPluginsMount mount="catalog.entity-page.tab">
</EntityLayout.Route>
```

#### Common changes

Since Backstage builder/bundler is defined in `@backstage/cli` we need to adjust this builder. This includes sharing/adding all the shared/singleton packages that need to be shared between the Backstage frontend (host) and the external plugin - packages like `react`, `react-dom`, etc. This may pose a risk that if a plugin requires a singleton package on host, this needs to be adjusted on both sides - in the host app build as well as in the plugin build.

### 〽️ Alternatives

TBD

### ❌ Risks

This introduces changes to the way how `packages/app` and individual plugins are being built. Changes are minimal (adding one Webpack plugin to the `packages/app`) on the host side. On the other hand, on the plugin side, we're adding a brand-new build strategy that requires to be supported. However, it is still an additional strategy - it preserves the current package build, therefore current packages should not be affected.

### 👀 Have you spent some time to check if this RFC has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)
