### ISSUE TITLE
🐛 Bug Report: fetch:plain:file fails with stream is not readable 

### ISSUE THREAD

**Issue by punkle** [backstage/backstage#17072]
### 📜 Description

When I created the following template step it fails with an error:

```
steps:
    - id: fetch-gitignore
      name: Fetch gitignore
      action: fetch:plain:file
      input:
        url: "https://github.com/AcmeInc/test123/blob/main/.gitignore"
        targetPath: '.gitignore'
```

### 👍 Expected behavior

i expect it to fetch the file and write it to the workspace directory at the targetPath

### 👎 Actual Behavior with Screenshots

It fails with the folling error:

```
2023-03-24T09:10:24.000Z Beginning step Fetch Repo
2023-03-24T09:10:24.000Z info: Fetching plain content from remote URL
2023-03-24T09:10:25.000Z InternalServerError: stream is not readable
    at readStream (/Users/brianfletcher/git-repos/backstage/node_modules/raw-body/index.js:185:17)
    at executor (/Users/brianfletcher/git-repos/backstage/node_modules/raw-body/index.js:120:5)
    at new Promise (<anonymous>)
    at getRawBody (/Users/brianfletcher/git-repos/backstage/node_modules/raw-body/index.js:119:10)
    at Object.buffer (webpack-internal:///../backend-common/src/reading/ReadUrlResponseFactory.ts:48:73)
    at fetchFile (webpack-internal:///../../plugins/scaffolder-backend/src/scaffolder/actions/builtin/fetch/helpers.ts:67:34)
    at async Object.handler (webpack-internal:///../../plugins/scaffolder-backend/src/scaffolder/actions/builtin/fetch/plainFile.ts:61:13)
    at async NunjucksWorkflowRunner.executeStep (webpack-internal:///../../plugins/scaffolder-backend/src/scaffolder/tasks/NunjucksWorkflowRunner.ts:196:13)
    at async NunjucksWorkflowRunner.execute (webpack-internal:///../../plugins/scaffolder-backend/src/scaffolder/tasks/NunjucksWorkflowRunner.ts:258:17)
    at async TaskWorker.runOneTask (webpack-internal:///../../plugins/scaffolder-backend/src/scaffolder/tasks/TaskWorker.ts:88:33)
```

### 👟 Reproduction steps

Create a template with the step shown above and run it.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by punkle** [comment]
Im happy to provide a PR, but I wouldnt know where to start with this.

**Comment by punkle** [comment]
@gavlyukovskiy are you find it works for you?

**Comment by gavlyukovskiy** [comment]
@punkle It does work for me:
```
    - id: fetch-plain
      name: Fetch Plain
      action: fetch:plain:file
      input:
        url: https://github.com/gavlyukovskiy/spring-boot-data-source-decorator/blob/master/.gitignore
        targetPath: .gitignore
```
I can't access your repository, but for mine it works well.
