### ISSUE TITLE
🐛 Bug Report: custom field validation not working when custom field is in array

### ISSUE THREAD

**Issue by hspitzley-czi** [backstage/backstage#17161]
### 📜 Description

I noticed an issue with custom field validation. Previously it looks like validation was not running when it is in an array (https://github.com/backstage/backstage/pull/16670 addressed that) and now the value passed to the validator appears incorrect.

Given a template like this:
```yaml
apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: my-automation
  title: My automation
  description: '...'
spec:
  owner: team
  type: service
  parameters:
    - title: Please provide some details about the app you are setting up
      properties:
        environments:
          title: What environments will this organization support?
          type: array
          items:
            type: object
            required:
              - envName
              - picker
            properties:
              envName:
                title: Environment Name
                type: string
                pattern: ^[a-z][0-9a-z-]+$
              picker:
                type: object
                ui:field: CustomPicker
                ui:widget: password
                ui:options:
                  title: Pick your AWS account you need for this environment
  steps: []
```

Suppose my CustomPicker returns a type like `{name: string, id: string}`

I created a react component to gather inputs and return the expected type. A validator which takes the value returned from CustomPicker is triggered when the `Next` button is clicked but the validator receives a value like:
```
[
  {
    envName: 'prod',
    picker: {
      name: 'foo',
      id: 12345
    }
  }
]
```

### 👍 Expected behavior

Value passed to the validator should be just
```
{
  name: 'foo',
  id: 12345
}
```

### 👎 Actual Behavior with Screenshots

When CustomPicker is used within an array it receives the whole array as the value to validate
eg:
```
[
  {
    envName: 'prod',
    picker: {
      name: 'foo',
      id: 12345
    }
  }
]
```

### 👟 Reproduction steps

1. Make a custom field extension with validation
2. Use the custom field extension within an array in a software template
3. Log the value passed to the validation and see that it receives the whole array value from the software template instead of just the values that the custom field extension produces

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None
