### ISSUE TITLE
🐛 Bug Report: not able to start a new backstage project using Docker tutorial

### ISSUE THREAD

**Issue by guimilleo** [backstage/backstage#17160]
### 📜 Description

I'm not able to start a new backstage project with Docker.

### 👍 Expected behavior

Containers should run smoothly 

### 👎 Actual Behavior with Screenshots

Error:

```
➜  backstage-test git:(main) ✗ docker run -it -p 7007:7007 backstage
Loaded config from app-config.yaml, app-config.production.yaml
{"level":"info","message":"Found 1 new secrets in config that will be redacted","service":"backstage"}
{"level":"info","message":"Created UrlReader predicateMux{readers=azure{host=dev.azure.com,authed=false},bitbucketCloud{host=bitbucket.org,authed=false},github{host=github.com,authed=false},gitlab{host=gitlab.com,authed=false},awsS3{host=amazonaws.com,authed=false},fetch{}","service":"backstage"}
Backend failed to start up Error: Failed to connect to the database to make sure that 'backstage_plugin_catalog' exists, Error: connect ECONNREFUSED 127.0.0.1:5432
    at /app/node_modules/@backstage/backend-common/dist/index.cjs.js:985:17
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async CatalogBuilder.build (/app/node_modules/@backstage/plugin-catalog-backend/dist/index.cjs.js:4952:22)
    at async createPlugin$4 (/app/packages/backend/dist/index.cjs.js:82:40)
    at async main (/app/packages/backend/dist/index.cjs.js:228:29)
```

### 👟 Reproduction steps

I'm following this tutorial here

https://backstage.io/docs/deployment/docker

and using this Dockerfile (also from the tutorial)

```
FROM node:16-bullseye-slim

# Install sqlite3 dependencies. You can skip this if you don't use sqlite3 in the image,
# in which case you should also move better-sqlite3 to "devDependencies" in package.json.
RUN --mount=type=cache,target=/var/cache/apt,sharing=locked \
    --mount=type=cache,target=/var/lib/apt,sharing=locked \
    apt-get update && \
    apt-get install -y --no-install-recommends libsqlite3-dev python3 build-essential && \
    yarn config set python /usr/bin/python3

# From here on we use the least-privileged `node` user to run the backend.
USER node

# This should create the app dir as `node`.
# If it is instead created as `root` then the `tar` command below will fail: `can't create directory 'packages/': Permission denied`.
# If this occurs, then ensure BuildKit is enabled (`DOCKER_BUILDKIT=1`) so the app dir is correctly created as `node`.
WORKDIR /app

# This switches many Node.js dependencies to production mode.
ENV NODE_ENV production

# Copy repo skeleton first, to avoid unnecessary docker cache invalidation.
# The skeleton contains the package.json of each package in the monorepo,
# and along with yarn.lock and the root package.json, that's enough to run yarn install.
COPY --chown=node:node yarn.lock package.json packages/backend/dist/skeleton.tar.gz ./
RUN tar xzf skeleton.tar.gz && rm skeleton.tar.gz

RUN --mount=type=cache,target=/home/node/.cache/yarn,sharing=locked,uid=1000,gid=1000 \
    yarn install --frozen-lockfile --production --network-timeout 300000

# Then copy the rest of the backend bundle, along with any other files we might want.
COPY --chown=node:node packages/backend/dist/bundle.tar.gz app-config*.yaml ./
RUN tar xzf bundle.tar.gz && rm bundle.tar.gz

CMD ["node", "packages/backend", "--config", "app-config.yaml"]
```

```
nvm use node 16

npx @backstage/plugin-app-backend

yarn install --frozen-lockfile

yarn tsc

yarn build:backend

docker image build . -f packages/backend/Dockerfile --tag backstage

docker run -it -p 7007:7007 backstage
```

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by benjdlambert** [comment]
This line is pretty interesting: `Backend failed to start up Error: Failed to connect to the database to make sure that 'backstage_plugin_catalog' exists, Error: connect ECONNREFUSED 127.0.0.1:5432` looks like one of the `app-config.yaml` files looks like it's trying to connect to `postgres` instead of sqlite. Is that something that you expected?

**Comment by Fuglen** [comment]
I'm currently looking into running Backstage in Docker at my company and I solved this issue by either setting `ENV NODE_ENV` to `development` instead of `production`, so its like this `ENV NODE_ENV development`, if you want to use Docker for local development.

You can also fill in the details for a PostgreSQL database in your `app-config.production.yaml` and it should be able to startup.
If you dont want to use a database I assume you could use SQLite instead of PostgreSQL in `app-config.production.yaml`.

**Comment by floriannr24** [comment]
I had the same issue that it was trying to connect to localhost:5432.
For me, the `app-config.**production**.yaml` still had the postgres-database in the `database` section for some reason? I changed it to `better-sqlite3` (like in hte app-config.yaml) and then it worked!

**Comment by Rugvip** [comment]
If you run into the `Failed to connect to the database to make sure that '...' exists` error it means that your Backstage instance is configured to use PostgreSQL but it's not able to connect to it.

Configuration is selected via the command line args, by default `app-config.yaml` and `app-config.local.yaml` will be loaded if present. The recommended docker setup explicitly sets this to only `--config app-config.yaml` though. If you want to use additional or different config files, you'd use for example `--config app-config.yaml --config app-config.production.yaml`. More on all of that here: https://backstage.io/docs/conf/writing#configuration-files

The `NODE_ENV` is used to select the behavior of many Node.js packages at runtime, but it will **not** select the config that is used. For example, setting `NODE_ENV=production` will cause certain Backstage backend startup failures to be reported as errors that halt the startup, instead of warnings.

SQLite is not recommended for use in production as it does not persist your data and does not perform well once you go beyond a small deployment.

**Comment by Umoren** [comment]
It's crazy i still have this problem.

Here's my app-config.yaml

```yaml
app:
  title: Test Backstage
  baseUrl: http://localhost:3000

organization:
  name: testorg

backend:
  # Used for enabling authentication, secret is shared by all backend plugins
  # See https://backstage.io/docs/auth/service-to-service-auth for
  # information on the format
  # auth:
  #   keys:
  #     - secret: ${BACKEND_SECRET}
  baseUrl: http://localhost:7007
  listen:
    port: 7007
    # Uncomment the following host directive to bind to specific interfaces
    # host: 127.0.0.1
  reading:
    allow:
      - host: raw.githubusercontent.com
  csp:
    connect-src: ["'self'", 'http:', 'https:']
    # Content-Security-Policy directives follow the Helmet format: https://helmetjs.github.io/#reference
    # Default Helmet Content-Security-Policy values can be removed by setting the key to false
  cors:
    origin: http://localhost:3000
    methods: [GET, HEAD, PATCH, POST, PUT, DELETE]
    credentials: true
  # This is for local development only, it is not recommended to use this in production
  # The production database configuration is stored in app-config.production.yaml
  database:
    client: pg
    connection:
      host: localhost
      port: 5432
      user: postgres
      password: secret
  # workingDirectory: /tmp # Use this to configure a working directory for the scaffolder, defaults to the OS temp-dir

proxy:
  ### Example for how to add a proxy endpoint for the frontend.
  ### A typical reason to do this is to handle HTTPS and CORS for internal services.
  # '/test':
  #   target: 'https://example.com'
  #   changeOrigin: true

# Reference documentation http://backstage.io/docs/features/techdocs/configuration
# Note: After experimenting with basic setup, use CI/CD to generate docs
# and an external cloud storage when deploying TechDocs for production use-case.
# https://backstage.io/docs/features/techdocs/how-to-guides#how-to-migrate-from-techdocs-basic-to-recommended-deployment-approach
techdocs:
  builder: 'local' # Alternatives - 'external'
  generator:
    runIn: 'docker' # Alternatives - 'local'
  publisher:
    type: 'local' # Alternatives - 'googleGcs' or 'awsS3'. Read documentation for using alternatives.

scaffolder:
  # see https://backstage.io/docs/features/software-templates/configuration for software template options

catalog:
  import:
    entityFilename: catalog-info.yaml
    pullRequestBranchName: backstage-integration
  rules:
    - allow: [Component, System, API, Resource, Location]
  locations:
    # Local example data, file locations are relative to the backend process, typically `packages/backend`
    - type: file
      target: ../../examples/entities.yaml

    # Local example template
    - type: file
      target: ../../examples/template/template.yaml
      rules:
        - allow: [Template]

    # Local example organizational data
    - type: file
      target: ../../examples/org.yaml
      rules:
        - allow: [User, Group]

    ## Uncomment these lines to add more example data
    # - type: url
    #   target: https://github.com/backstage/backstage/blob/master/packages/catalog-model/examples/all.yaml

    ## Uncomment these lines to add an example org
    # - type: url
    #   target: https://github.com/backstage/backstage/blob/master/packages/catalog-model/examples/acme-corp.yaml
    #   rules:
    #     - allow: [User, Group]
```
My Dockerfile

```docker
# This dockerfile builds an image for the backend package.
# It should be executed with the root of the repo as docker context.
#
# Before building this image, be sure to have run the following commands in the repo root:
#
# yarn install
# yarn tsc
# yarn build:backend
#
# Once the commands have been run, you can build the image using `yarn build-image`

FROM node:16-bullseye-slim

# Install sqlite3 dependencies. You can skip this if you don't use sqlite3 in the image,
# in which case you should also move better-sqlite3 to "devDependencies" in package.json.
RUN --mount=type=cache,target=/var/cache/apt,sharing=locked \
    --mount=type=cache,target=/var/lib/apt,sharing=locked \
    apt-get update && \
    apt-get install -y --no-install-recommends libsqlite3-dev python3 build-essential python3-pip && \
    pip3 install mkdocs-techdocs-core==1.1.7 && \
    yarn config set python /usr/bin/python3

# From here on we use the least-privileged `node` user to run the backend.
USER node

# This should create the app dir as `node`.
# If it is instead created as `root` then the `tar` command below will fail: `can't create directory 'packages/': Permission denied`.
# If this occurs, then ensure BuildKit is enabled (`DOCKER_BUILDKIT=1`) so the app dir is correctly created as `node`.
WORKDIR /app

# This switches many Node.js dependencies to production mode.
ENV NODE_ENV development

# Copy repo skeleton first, to avoid unnecessary docker cache invalidation.
# The skeleton contains the package.json of each package in the monorepo,
# and along with yarn.lock and the root package.json, that's enough to run yarn install.
COPY --chown=node:node yarn.lock package.json packages/backend/dist/skeleton.tar.gz ./
RUN tar xzf skeleton.tar.gz && rm skeleton.tar.gz


RUN --mount=type=cache,target=/home/node/.cache/yarn,sharing=locked,uid=1000,gid=1000 \
    yarn install --frozen-lockfile --production --network-timeout 300000

# Then copy the rest of the backend bundle, along with any other files we might want.
COPY packages/backend/dist/bundle.tar.gz app-config.yaml app-config.production.yaml ./
RUN tar xzf bundle.tar.gz && rm bundle.tar.gz

CMD ["node", "packages/backend", "--config", "app-config.yaml", "--config", "app-config.production.yaml"]
```
I run `yarn build:backend` then `docker image build . -f packages/backend/Dockerfile --tag backstage` and ` docker run -it -p 7008:7008 backstage`

I still end up with this error:
```sh
2023-07-04 19:36:46 Loaded config from app-config.yaml, app-config.production.yaml
2023-07-04 19:36:46 2023-07-04T18:36:46.075Z backstage info Found 4 new secrets in config that will be redacted 
2023-07-04 19:36:46 2023-07-04T18:36:46.092Z backstage info Created UrlReader predicateMux{readers=azure{host=dev.azure.com,authed=false},bitbucketCloud{host=bitbucket.org,authed=false},github{host=github.com,authed=true},gitlab{host=gitlab.com,authed=false},awsS3{host=amazonaws.com,authed=false},fetch{} 
2023-07-04 19:36:46 Backend failed to start up Error: Failed to connect to the database to make sure that 'backstage_plugin_catalog' exists, Error: connect ECONNREFUSED 127.0.0.1:5432
2023-07-04 19:36:46     at /app/node_modules/@backstage/backend-common/dist/index.cjs.js:963:17
2023-07-04 19:36:46     at processTicksAndRejections (node:internal/process/task_queues:96:5)
2023-07-04 19:36:46     at async CatalogBuilder.build (/app/node_modules/@backstage/plugin-catalog-backend/dist/cjs/CatalogBuilder-26406e82.cjs.js:4829:22)
2023-07-04 19:36:46     at async createPlugin$4 (/app/packages/backend/dist/index.cjs.js:82:40)
2023-07-04 19:36:46     at async main (/app/packages/backend/dist/index.cjs.js:229:29) 
```
I am trying to demo techdocs to my company but this has dragged me back for some days. I tried the external builder option with awsS3 but strangely enough, i'm stuck with a path problem.

**Comment by benjdlambert** [comment]
@Umoren you'll need to setup your docker container with some production config that points to a postgres instance. Right now it's looking for postgres on localhost, and postgres isn't going to be running inside the container. You'll need to inject some environment variables into a container which would get used in the `app-config.production.yaml` to point at a running postgres instance somewhere.


Something like:

```yaml
backend:
  database:
    client: pg
    connection:
      host: ${POSTGRES_HOST}
      port: ${POSTGRES_PORT}
      user: ${POSTGRES_USER}
      password: ${POSTGRES_PASSWORD}
```

Inside `app-config.production.yaml` and make sure that those env vars are set when running the container somewhere.

**Comment by Fuglen** [comment]
Where is your postgres running?
I like to use Docker Compose for devoping backstage with a postgres container next to it like this.

```
version: '3'
services:
  postgres:
    image: postgres:13.9-alpine
    container_name: postgresql
    environment:
      - POSTGRES_DB=backstage
      - POSTGRES_USER=backstage
      - POSTGRES_PASSWORD=backstage123
    ports:
      - 5432:5432
    volumes:
      - backstage_data:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    restart: always
    network_mode: host
  backstage:
    image: registry.theflyingbirds.net/backstage:latest
    container_name: tfb_backstage
    ports:
      - 7007:7007
      - 3000:3000
    environment:
      - POSTGRES_HOST=127.0.0.1
      - POSTGRES_PORT=5432
      - POSTGRES_USER=backstage
      - POSTGRES_PASSWORD=backstage123
    network_mode: host
volumes:
  backstage_data:
```
If you can't use host network, then you would type "postgres" as the POSTGRESS_HOST for Backstage.

I also had problems connecting to my postgres in Docker if I had postgres running locally in Windows as a service.

**Comment by snow6oy** [comment]
Through trial and error I found that running a docker image without app-config.production.yaml in the build throws an error. But it does run with this minimal configuration.
```
bash-3.2$ cat app-config.production.yaml 
backend:
  database:
    client: better-sqlite3
    connection: ':memory:'
```
I want to use a dockerised backstage in a local environment and hope the in-memory database will work ok 🤞

**Comment by VGerris** [comment]
I can't believe I have to find this info here.  I followed the exact same steps and got an auth error first and then the database one.

I got it to work by doing the following before building the docker image: 
`node -p 'require("crypto").randomBytes(24).toString("base64")'`

use that output ( say bla123bla) in the auth snippet ( root of file : ) :
Also comment out the database and replace with the above so the snippet becomes :
```
backend:
  database:
    client: better-sqlite3
    connection: ':memory:'
  auth:
    keys:
      - secret: 5o7UMI5xPDBxC5SgknGINtXirTkR8LUd
auth:
  providers:
    guest: null
```
Then build the container and start it. 
I get errors then about the guest user, which given the config is not surprising.

I suggest adding the above with a working admin user config to the docs so one gets it to work and then hints to config for production being in a deployed or local setup.
I was just looking to run it as a local app.

If anyone can update the snippet to have an admin user, that would be great.
