### ISSUE TITLE
🐛 Bug Report: Gitlab merge request action, `output.mergeRequestURL` is not working

### ISSUE THREAD

**Issue by artemptushkin** [backstage/backstage#17166]
### 📜 Description

`${{ steps['merge_request'].output.mergeRequestURL }}` returns empty string though MR exists

### 👍 Expected behavior

The URL is rendered below after the steps on UI

### 👎 Actual Behavior with Screenshots

![image](https://user-images.githubusercontent.com/22632802/228835906-9937cb33-c99e-4bc2-9ca7-1ff4b44e32dc.png)

### 👟 Reproduction steps

Having:

```yaml
    - id: merge_request
      name: Open merge request
      action: publish:gitlab:merge-request
      input:
        description: This is ${{ parameters.name }}
        title: ${{ parameters.jiraTicket }} initial commit of ${{ parameters.name }}
        repoUrl: ${{ parameters.repoUrl }}
        branchName: feature/${{ parameters.jiraTicket }}-initial

  output:
    links:
      - title: Merge request URL
        url: ${{ steps['merge_request'].output.mergeRequestURL }}
```

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, I don't have time to work on this right now
