### ISSUE TITLE
🐛 Bug Report: Unable to create merge request for software template with GitLab

### ISSUE THREAD

**Issue by dschaaff** [backstage/backstage#17189]
### 📜 Description

I am attempting to configure software templates to open a merge request against an existing repo in our organizations private GitLab org on gitlab.com. We have the gitlab provider configuration and oauth configuration in place.

```
integrations:
  github:
    - host: github.com
      # This is a Personal Access Token or PAT from GitHub. You can find out how to generate this token, and more information
      # about setting up the GitHub integration here: https://backstage.io/docs/getting-started/configuration#setting-up-a-github-integration
      token: ${GITHUB_TOKEN}
    ### Example for how to add your GitHub Enterprise instance using the API:
  gitlab:
    - host: gitlab.com
      token: ${GITLAB_TOKEN}
```

```
auth:
  # see https://backstage.io/docs/auth/ to learn about auth providers
  providers:
    gitlab:
      production:
        clientId: ${AUTH_GITLAB_CLIENT_ID}
        clientSecret: ${AUTH_GITLAB_CLIENT_SECRET}
      development:
        clientId: ${AUTH_GITLAB_CLIENT_ID}
        clientSecret: ${AUTH_GITLAB_CLIENT_SECRET}
    # google is used for signin
    google:
      production:
        clientId: ${AUTH_GOOGLE_CLIENT_ID}
        clientSecret: ${AUTH_GOOGLE_CLIENT_SECRET}
      development:
        clientId: ${AUTH_GOOGLE_CLIENT_ID}
        clientSecret: ${AUTH_GOOGLE_CLIENT_SECRET}
```

Backstage is successfully pulling catalog data from our repos in GitLab. I can also successfully auth with GitLab by going to settings -> authentication provider and then selecting sign in next to GitLab.

This is the content of our template item

```apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: gitlab-merge-request
  title: GitLab Merge Request Action template
  description: Scaffolder template demo publishing a Merge Request on existing GitLab repository
spec:
  owner: backstage/techdocs-core
  type: service

  parameters:
    - title: Fill in some steps
      required:
        - name
      properties:
        name:
          title: Name
          type: string
          description: Unique name of the component
          ui:autofocus: true
          ui:options:
            rows: 5
        description:
          title: Description
          type: string
          description: Description of the component
        targetPath:
          title: Target Path in repo
          type: string
          description: Name of the directory to create in the repository
        branchName:
          title: Destination Branch Name
          type: string
          description: Name of the branch to create in the repository
        assignee:
          title: MR Assignee
          type: string
          description: GitLab Handle of the Assignee
    - title: Choose a location
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - gitlab.com
            requestUserCredentials:
              secretsKey: USER_OAUTH_TOKEN

  steps:
    - id: template
      name: Fetch Skeleton + Template
      action: fetch:template
      input:
        url: ./template
        targetPath: ${{ parameters.targetPath }}
        values:
          name: ${{parameters.name}}
    - id: publish
      name: Publish
      action: publish:gitlab:merge-request
      input:
        repoUrl: ${{ parameters.repoUrl }}
        title: Creating catalog-info.yaml ${{ parameters.name }} for backstage
        branchName: ${{ parameters.branchName }}
        description: |
          # New project: ${{ parameters.name }}
          ${{ parameters.description if parameters.description }}
        targetPath: ${{ parameters.targetPath if parameters.targetPath else '.' }}
        token: ${{ secrets.USER_OAUTH_TOKEN }}
        commitAction: create
        removeSourceBranch: true
        assignee: ${{ parameters.assignee }}

  output:
    links:
      - url: ${{ steps.publish.output.mergeRequestUrl }}
        title: 'Go to Gitlab MR'
```

### 👍 Expected behavior

I expect to be able run through the creation flow and have backstage open a merge request in the repository for the changes.

### 👎 Actual Behavior with Screenshots

While on the RepoUrlPicker screen I am prompted to sign in to GitLab
<img width="725" alt="image" src="https://user-images.githubusercontent.com/12867428/229242056-21c96ae9-0c35-49f7-bb78-42f69f1702ff.png">
After clicking sign I get the error "The requested scope is invalid, unknown, or malformed".
<img width="766" alt="image" src="https://user-images.githubusercontent.com/12867428/229242135-fb738fc1-c66b-40e4-bf49-bb3ee3f50fbd.png">
I see a request to https://gitlab.com/oauth/undefined in the browsers dev tools.

### 👟 Reproduction steps

Follow the prompts to create a template using gitlab. Notice the error when signing in.

### 🖥️ Your Environment

OS:   Darwin 22.4.0 - darwin/arm64
node: v18.15.0
yarn: 1.22.19
cli:  0.22.5 (installed)
backstage:  1.12.1

Dependencies:
  @backstage/app-defaults                          1.2.1
  @backstage/backend-app-api                       0.4.1
  @backstage/backend-common                        0.18.3
  @backstage/backend-dev-utils                     0.1.1
  @backstage/backend-plugin-api                    0.5.0
  @backstage/backend-tasks                         0.5.0
  @backstage/catalog-client                        1.4.0
  @backstage/catalog-model                         1.2.1
  @backstage/cli-common                            0.1.12
  @backstage/cli                                   0.22.5
  @backstage/config-loader                         1.1.9
  @backstage/config                                1.0.7
  @backstage/core-app-api                          1.6.0
  @backstage/core-components                       0.12.5
  @backstage/core-plugin-api                       1.5.0
  @backstage/errors                                1.1.5
  @backstage/eslint-plugin                         0.1.2
  @backstage/integration-aws-node                  0.1.2
  @backstage/integration-react                     1.1.11
  @backstage/integration                           1.4.3
  @backstage/plugin-api-docs                       0.9.1
  @backstage/plugin-app-backend                    0.3.43
  @backstage/plugin-auth-backend                   0.18.1
  @backstage/plugin-auth-node                      0.2.12
  @backstage/plugin-catalog-backend-module-gitlab  0.1.14
  @backstage/plugin-catalog-backend                1.8.0
  @backstage/plugin-catalog-common                 1.0.12
  @backstage/plugin-catalog-graph                  0.2.28
  @backstage/plugin-catalog-import                 0.9.6
  @backstage/plugin-catalog-node                   1.3.4
  @backstage/plugin-catalog-react                  1.4.0
  @backstage/plugin-catalog                        1.9.0
  @backstage/plugin-github-actions                 0.5.16
  @backstage/plugin-kubernetes-backend             0.9.4
  @backstage/plugin-kubernetes-common              0.6.1
  @backstage/plugin-kubernetes                     0.7.9
  @backstage/plugin-org                            0.6.6
  @backstage/plugin-permission-common              0.7.4
  @backstage/plugin-permission-node                0.7.6
  @backstage/plugin-permission-react               0.4.11
  @backstage/plugin-proxy-backend                  0.2.37
  @backstage/plugin-scaffolder-backend             1.12.0
  @backstage/plugin-scaffolder-common              1.2.6
  @backstage/plugin-scaffolder-node                0.1.1
  @backstage/plugin-scaffolder-react               1.2.0
  @backstage/plugin-scaffolder                     1.12.0
  @backstage/plugin-search-backend-module-pg       0.5.4
  @backstage/plugin-search-backend-node            1.1.4
  @backstage/plugin-search-backend                 1.2.4
  @backstage/plugin-search-common                  1.2.2
  @backstage/plugin-search-react                   1.5.1
  @backstage/plugin-search                         1.1.1
  @backstage/plugin-tech-radar                     0.6.2
  @backstage/plugin-techdocs-backend               1.6.0
  @backstage/plugin-techdocs-module-addons-contrib 1.0.11
  @backstage/plugin-techdocs-node                  1.6.0
  @backstage/plugin-techdocs-react                 1.1.4
  @backstage/plugin-techdocs                       1.6.0
  @backstage/plugin-user-settings                  0.7.1
  @backstage/release-manifests                     0.0.9
  @backstage/test-utils                            1.2.6
  @backstage/theme                                 0.2.18
  @backstage/types                                 1.0.2
  @backstage/version-bridge                        1.0.3

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by benjdlambert** [comment]
Hmm this looks like something to do with the scopes for the `scmAuthApi`. Quite interesting that these are the default scopes: https://github.com/backstage/backstage/blob/2d63d04743a53cce754c2ec5e729aace40428180/packages/integration-react/src/api/ScmAuth.ts#L175

Not seen this error before, and it looks like you're not passing in any `additionalScopes` either?

**Comment by bigkevmcd** [comment]
The error message from GitLab isn't very useful, but, the URL will include the requested scopes.

I'd check the app against the documented scopes here https://github.com/backstage/backstage/tree/master/plugins/auth-backend#gitlab I was able to get an authentication token against GitLab with an app configured with just these allowed scopes.

 * api (Access the authenticated user's API)
 * read_api (Read Api)
 * read_user (Read the authenticated user's personal information)
 * read_repository (Allows read-only access to the repository)
 * write_repository (Allows read-write access to the repository)

**Comment by jhaals** [comment]
@dschaaff Would you be willing to contribute a fix to the docs? :)

**Comment by dschaaff** [comment]
sure thing

**Comment by kenzliang** [comment]
Hi @dschaaff sorry to ping you on a year old issue - I'm struggling to get past the malformed scopes issue you encountered. 

QQ - Is your `apis.ts` using the default scm api factory? ex.

```
export const apis: AnyApiFactory[] = [
  createApiFactory({
    api: scmIntegrationsApiRef,
    deps: { configApi: configApiRef },
    factory: ({ configApi }) => ScmIntegrationsApi.fromConfig(configApi),
  }),
  ScmAuth.createDefaultApiFactory(),
];
```

I did have to create a custom `auth.ts` to parse my org data and log in, so I suspect that is also causing problems with how the apis are interfacing with gitlab.

**Comment by dschaaff** [comment]
Yes, I am using the default api.ts setup.

**Comment by kenzliang** [comment]
For those who end up stumbling into issues with their self hosted instance, this is what worked for me:

```
gitlab: providers.gitlab.create({
        signIn: {
          resolver(info, ctx) {
            console.log(info.profile)
            const email = info.profile.email ?? ''; // Handle undefined case
            const [id] = email.split('@');
            const userEntityRef = stringifyEntityRef({
              kind: 'User',
              namespace: DEFAULT_NAMESPACE,
              name: id,
            });
            return ctx.signInWithCatalogUser({
              entityRef: userEntityRef,
            });
          },
        },
      })
```

This is largely because of the IDs being imported into backstage from our self hosted instances were not emails. 

Additionally, I _HAD_ to have additional scopes in my template for oauth to work.

```yaml
    - title: Choose a location
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            requestUserCredentials:
              secretsKey: USER_OAUTH_TOKEN
              additionalScopes:
                gitlab:
                  - api
                  - openid
                  - profile
                  - email
            allowedHosts:
              - gitlab.internal
```
