### ISSUE TITLE
🚀 Feature: Implement new Service Locator for K8s-Plugin based on relationships

### ISSUE THREAD

**Issue by dlaird-ovo** [backstage/backstage#17185]
### 🔖 Feature description

It would be really good to use relationships (uses/usedBy) as an alternative to the current MultiTenant locator.
This would allow the Catalog Users to provide precise detail - i.e this workload is running on this Cluster - instead of searching all available clusters

### 🎤 Context

We have 100s of clusters and when using the current locator it is very slow as it check all of them for workloads. 
However the Catalog owners - can specify with a high level of confidence which `kubernetes-clusters` are running their workload.

Therefore avoiding the expensive 'search' operation and just displaying the related statistics.

### ✌️ Possible Implementation

For a given entity - if the 'RelationshipLocator' is selected - it would follow 'uses' links or another relationship type and just return the clusters that are at the end of the link.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by jamieklassen** [comment]
To flesh this out a bit:
1. Assume your catalog contains a kubernetes cluster called `cluster` -- consistent with the behaviour of the [`CatalogClusterLocator`](https://github.com/backstage/backstage/blob/master/plugins/kubernetes-backend/src/cluster-locator/CatalogClusterLocator.ts#L47-L48) and the [`AwsEKSClusterProcessor`](https://github.com/backstage/backstage/blob/master/plugins/catalog-backend-module-aws/src/processors/AwsEKSClusterProcessor.ts#L110), this would be an entity of kind `Resource` with `type: kubernetes-cluster`:
    ```yaml
    apiVersion: backstage.io/v1alpha1
    kind: Resource
    metadata:
      name: cluster
      annotations:
        'kubernetes.io/api-server': https://my.k8s.cluster
        'kubernetes.io/auth-provider': aws
    spec:
      type: kubernetes-cluster
      owner: me
    ```
1. Assume your catalog contains a service called `service` which is related to `cluster` -- for illustration purposes let's assume the [`dependsOn`](https://backstage.io/docs/features/software-catalog/descriptor-format/#specdependson-optional)/[`dependencyOf`](https://backstage.io/docs/features/software-catalog/descriptor-format/#specdependencyof-optional) relation which is idiomatic for Components and Resources, but a new `uses`/`usedBy` could also be introduced for this purpose:
    ```yaml
    apiVersion: backstage.io/v1alpha1
    kind: Component
    metadata:
      name: service
      annotations:
        'backstage.io/kubernetes-id': service
    spec:
      type: service
      lifecycle: experimental
      owner: user:default/guest
      dependsOn: [resource:default/cluster]
    ```
1. Assume the `kubernetes` stanza in your app-config looks something like
    ```yaml
    kubernetes:
      serviceLocatorMethod:
        type: catalogRelationship
      clusterLocatorMethods:
        - type: catalog
    ```
1. Run backstage with `yarn start-backend`
1. Then a request like
    ```bash
    curl -H 'content-type: application/json' localhost:7007/api/kubernetes/services/service -d \
      '{
        "entity": {
          "metadata": {
            "name": "service",
            "annotations": {
              "backstage.io/kubernetes-id": "service"
            }
          },
          "spec": {
            "dependsOn": [
              "resource:default/cluster"
            ]
          }
        }
      }'
    ```
    should only include objects from `cluster`, regardless of what other clusters might be in the catalog

There are some edge case decisions to make around:

* services which are not related to any clusters in the catalog
* services which are deployed -- at least in part -- on clusters which are not in the catalog at all, but which come from other clusterLocators like `config` or `gke` or others

 But I figured it'd be helpful to lay out the happy path here in a bunch of detail regardless.
 
 While I'm here, I'm inclined to mention the option that integrators could use the `setServiceLocator` method on `KubernetesBuilder`:
 
 https://github.com/backstage/backstage/blob/d7f955f300893f50c4882ea8f5c09aa42dfaacfd/plugins/kubernetes-backend/src/service/KubernetesBuilder.ts#L168-L171
 
and try out writing and using a serviceLocator like this without necessarily committing it to the core repo and dealing with how it interacts with the non-catalog clusterLocators. It could even get added to [the `/contrib` folder](https://github.com/backstage/backstage/tree/master/contrib)!
