### ISSUE TITLE
🐛 Bug Report: Techdocs generation fails for local static configured locations with remote source-location annotations

### ISSUE THREAD

**Issue by bforbis** [backstage/backstage#17193]
### 📜 Description

Backstage is unable to build techdocs within a local folder if the catalog entry for that techdocs is local but provides a remote "backstage.io/source-location" annotation.

### 👍 Expected behavior

We expect techdocs generation to succeed because it has the following info:

- The catalog entity is managed by a location which is a local file location
- The "backstage.io/techdocs-ref" tells it to look in the same dir as the catalog file using `dir:.`

### 👎 Actual Behavior with Screenshots

Techdocs generation fails
```
Building a newer version of this documentation failed.
Error: "Failed to retrieve branch list from https://bitbucket.mycompany.com/rest/api/1.0/projects/my-project/repos//branches/default, 404 Not Found"
```

### 👟 Reproduction steps

Start off with a local setup of statically configured catalog files

```yaml
catalog:
  locations:
    type: file
    target: ../../locations/catalog-file1.yaml
```

For the catalog file, add in a set of techdocs and also set the a source-location repo

**/locations/catalog-file1**
```yaml
---
kind: Component:
metadata:
  names: test-service
  annotations:
    backstage.io/techdocs-ref: dir:.
    backstage.io/source-location: https://bitbucket.mycompany.com/project/my-project/repos/my-repo
```

Include a basic `/docs` folder and `mkdocs.yml` next to the catalog file.

### 📃 Provide the context for the Bug.

I am running backstage as a proof of concept in a single repo. All catalog files for now are local to the same repo as backstage itself and are statically configured locations. I would also like to link out to the actual repo URLs of my components using source-location annotations. This seems to work well until I start trying to build local techdocs as well to those compoents.

It seems for now with this setup, the option is to either have source location annotations or techdocs, but not both.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else
