### ISSUE TITLE
🐛 Bug Report: Using wildcards in fs builtin actions doesn't work.

### ISSUE THREAD

**Issue by ruben-chainalysis** [backstage/backstage#17207]
### 📜 Description

Using `fs:delete` and `fs:move` built-in actions with a wildcard doesn't behave as expected.

### 👍 Expected behavior

Using a wildcard for globbing should (as nothing clearly points to the opposite) remove files matching the pattern.

### 👎 Actual Behavior with Screenshots

Files matching the pattern given with a wildcard are not deleted, but they are reported as if they were.

![Screenshot 2023-04-03 at 12 38 59](https://user-images.githubusercontent.com/111376369/229501074-af531b38-1082-4e9f-8080-b3ed99d9b052.png)

### 👟 Reproduction steps

Have a `fs:delete` step in a Scaffolder template:
```
    - id: remove-unused-helm
      name: Delete unused helm templates
      action: fs:delete
      input:
        files:
          - "base/helm_*"
 ```
To see that they weren't deleted, a step like a PR publish will show the files:

```
    - id: publish
      name: Raise PR
      action: publish:github:pull-request
      input:
        repoUrl: ${{ parameters.repoUrl }}
        title: "A PR title here"
        branchName: backstage/reproduce-delete-behaviour
        description:  A description here
```

### 📃 Provide the context for the Bug.

I understand that this is expected, as the upstream `fs-extra` library used doesn't allow globbing and [it doesn't look like it ever will](https://github.com/jprichardson/node-fs-extra/issues/318).

The `remove` [function docs from that library](https://github.com/jprichardson/node-fs-extra/blob/cc7b3b22a984de5124131c7897574091c9df00e1/docs/remove.md) state that `If the path does not exist, silently does nothing`, so the `deleted successfully` message will be shown for non existent paths.

If fixing this spirals into a lot of work or is not a priority at all, adding a note about wildcards not working in the documentation would really help saving some time. 

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!
