### ISSUE TITLE
🚀 Feature: Allow using env variables in scaffolder 

### ISSUE THREAD

**Issue by drodil** [backstage/backstage#17208]
### 🔖 Feature description

Sometimes URLs or some other information is stored in env variables in the application. These should be made available to be used in scaffolder actions as input for example:

```yaml
steps:
  - id: myAction
    name: My action run
    action: my:action 
    input:
      location: ${{ env.MY_ENV_VARIABLE }}
```

### 🎤 Context

Running the application in different environments can also have different input requirements for templates and thus environment variables should be allowed to be used in the scaffolder steps.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, I don't have time to work on this right now
