### ISSUE TITLE
🐛 Bug Report: Scaffolder Plugin and Array Parameter not working for me

### ISSUE THREAD

**Issue by dlaird-ovo** [backstage/backstage#17217]
### 📜 Description

I am trying to use an array parameter:
```
- title: Fill in some steps
      properties:
        name:
          title: Select environments
          type: array
          items:
            type: string
            enum:
              - production
              - staging
              - development
          uniqueItems: true
          ui:widget: checkboxes
 ```
 
 However when I select an option I get a stack trace in the Front End Code:
 
 ```
 TypeError
updated.sort is not a function
```

### 👍 Expected behavior

I think I should be able to select multiple choices from the list of available options and use them later in the template.

### 👎 Actual Behavior with Screenshots

I see this:
![image](https://user-images.githubusercontent.com/111744423/229580499-9dca10a1-ee65-4439-b4ca-a406b3aed4f2.png)

followed by:
![image](https://user-images.githubusercontent.com/111744423/229580579-faf12615-5791-4af7-9ea5-64b063be35e6.png)

### 👟 Reproduction steps

I have used a software template and this code block:

```
    - title: Fill in some steps
      properties:
        name:
          title: Select environments
          type: array
          items:
            type: string
            enum: ['push', 'pull', 'admin', 'maintain', 'triage']
          uniqueItems: true
          ui:widget: checkboxes
  ```
  
 After running the action.
          
          

### 📃 Provide the context for the Bug.

Struggling to understand what I have done wrong (and as its a standard example I fully expect user error)

### 🖥️ Your Environment

OS:   Linux 5.15.90.1-microsoft-standard-WSL2 - linux/x64
node: v18.14.2
yarn: 1.22.19
cli:  0.22.5 (installed)
backstage:  1.12.1

Dependencies:
  @backstage/app-defaults                          1.2.1
  @backstage/backend-app-api                       0.4.1
  @backstage/backend-common                        0.18.3
  @backstage/backend-dev-utils                     0.1.1
  @backstage/backend-plugin-api                    0.5.0
  @backstage/backend-tasks                         0.5.0
  @backstage/backend-test-utils                    0.1.35
  @backstage/catalog-client                        1.4.0
  @backstage/catalog-model                         1.2.1
  @backstage/cli-common                            0.1.12
  @backstage/cli                                   0.22.5
  @backstage/config-loader                         1.1.9
  @backstage/config                                1.0.7
  @backstage/core-app-api                          1.6.0
  @backstage/core-components                       0.12.5
  @backstage/core-plugin-api                       1.5.0
  @backstage/errors                                1.1.5
  @backstage/eslint-plugin                         0.1.2
  @backstage/integration-aws-node                  0.1.2
  @backstage/integration-react                     1.1.11
  @backstage/integration                           1.4.3
  @backstage/plugin-api-docs                       0.9.1
  @backstage/plugin-app-backend                    0.3.43
  @backstage/plugin-auth-backend                   0.18.1
  @backstage/plugin-auth-node                      0.2.12
  @backstage/plugin-catalog-backend-module-github  0.2.6
  @backstage/plugin-catalog-backend                1.8.0
  @backstage/plugin-catalog-common                 1.0.12
  @backstage/plugin-catalog-graph                  0.2.28
  @backstage/plugin-catalog-import                 0.9.6
  @backstage/plugin-catalog-node                   1.3.4
  @backstage/plugin-catalog-react                  1.4.0
  @backstage/plugin-catalog                        1.9.0
  @backstage/plugin-circleci                       0.3.16
  @backstage/plugin-events-node                    0.2.4
  @backstage/plugin-explore-common                 0.0.1
  @backstage/plugin-explore-react                  0.0.27
  @backstage/plugin-explore                        0.4.1
  @backstage/plugin-github-actions                 0.5.16
  @backstage/plugin-github-issues                  0.2.5
  @backstage/plugin-github-pull-requests-board     0.1.10
  @backstage/plugin-home                           0.4.32
  @backstage/plugin-kubernetes-backend             0.9.4
  @backstage/plugin-kubernetes-common              0.6.1
  @backstage/plugin-kubernetes                     0.7.9
  @backstage/plugin-org                            0.6.6
  @backstage/plugin-permission-backend             0.5.18
  @backstage/plugin-permission-common              0.7.4
  @backstage/plugin-permission-node                0.7.6
  @backstage/plugin-permission-react               0.4.11
  @backstage/plugin-proxy-backend                  0.2.37
  @backstage/plugin-scaffolder-backend             1.12.0
  @backstage/plugin-scaffolder-common              1.2.6
  @backstage/plugin-scaffolder-node                0.1.1
  @backstage/plugin-scaffolder-react               1.2.0
  @backstage/plugin-scaffolder                     1.12.0
  @backstage/plugin-search-backend-node            1.1.4
  @backstage/plugin-search-backend                 1.2.4
  @backstage/plugin-search-common                  1.2.2
  @backstage/plugin-search-react                   1.5.1
  @backstage/plugin-search                         1.1.1
  @backstage/plugin-tech-radar                     0.6.2
  @backstage/plugin-techdocs-backend               1.6.0
  @backstage/plugin-techdocs-module-addons-contrib 1.0.11
  @backstage/plugin-techdocs-node                  1.6.0
  @backstage/plugin-techdocs-react                 1.1.4
  @backstage/plugin-techdocs                       1.6.0
  @backstage/plugin-user-settings                  0.7.1
  @backstage/release-manifests                     0.0.9
  @backstage/test-utils                            1.2.6
  @backstage/theme                                 0.2.18
  @backstage/types                                 1.0.2
  @backstage/version-bridge                        1.0.3

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by dlaird-ovo** [comment]
Evening - some clear space and I finally realised the issue.
If you have 2 (or more) paramater like this:
```
  parameters:
    - title: Please enter a Repository Name
      required:
        - name
      properties:
        name:
          title: Name
          type: string
          description: Name of new repository
          ui:autofocus: true

    - title: Please choose an Owner
      properties:
        owner:
          title: Repository Owner
          type: string
          description: Owner of the repository (selected from known Groups)
          ui:field: OwnerPicker
          ui:options:
            catalogFilter:
              - kind: Group
                metadata.annotations.github.com/team-slug: { exists: true }
```
You have to ensure the field under properties is unique (i.e name and owner) above.  If not you can get very cryptic errors (like above) as the it tries to perform operations based on incorrect types.

Hopefully useful for others - and perhaps in the future some parsing could check the templates for duplicate parameter names and give a warning that highlights it.  But for now this can be closed :-)
