### ISSUE TITLE
🐛 Bug Report: <title>

### ISSUE THREAD

**Issue by sohanlon07** [backstage/backstage#17214]
### 📜 Description

I am trying to show / hide fields based on the selection in a previous field. This works fine using a dependencies block in the template.yaml if the field i want to show or hide is just of enum / string type:

Example One - works
```yaml
    - title: What Infrastructure is required?
      properties:
        cloud:
          title: Cloud
          type: string
          description: Which Cloud are you selecting
          default: azure
          ui:autofocus: true
          enum:
            - none
            - azure
            - aws
            - gcp
          default: none
          enumNames:
            - 'None'
            - 'Azure'
            - 'AWS'
            - 'GCP'
      dependencies:
        cloud:
          oneOf:
            - properties:
                cloud:
                  enum:
                    - azure
                modules:
                    type: "string"
                    enum:
                      - vm
                      - rds
                      - lb
                    enumNames:
                      - Virtual Machine
                      - Database
                      - Load Balancer
```

However, if I try to make the dependency field a multi-select (this type of field works fine outside of it being a dependency field) the template does not load at all. Code that doesnt work:

Example two: Doesnt work
```yaml
    - title: What Infrastructure is required?
      properties:
        cloud:
          title: Cloud
          type: string
          description: Which Cloud are you targetting (Select "None" if no IAC is needed)?
          default: azure
          ui:autofocus: true
          enum:
            - none
            - azure
            - aws
            - gcp
          default: none
          enumNames:
            - 'None'
            - 'Azure'
            - 'AWS'
            - 'GCP'
      dependencies:
        cloud:
          oneOf:
            - properties:
                cloud:
                  enum:
                    - azure
                modules:
                  title: Azure TF Modules
                  type: array
                  description: Select the AWS Modules you need for IAC, for example, "EC2", "ALB"
                  ui:autofocus: true
                  items:   
                    type: "string"
                    enum:
                      - vm
                      - rds
                      - lb
                    enumNames:
                      - Virtual Machine
                      - Database
                      - Load Balancer
                  uniqueitems: true
                  ui:widget: checkboxes
```

How do i show/hide a field of type "array" as a dependency. BAsically how do i get the functionality of example one field type to work for example two field type.

### 👍 Expected behavior

Fields show/hide regardless of field type.

### 👎 Actual Behavior with Screenshots

With example two, template does not even load.

### 👟 Reproduction steps

Implement this code in a template.yaml:

Example two: Doesnt work
```yaml
    - title: What Infrastructure is required?
      properties:
        cloud:
          title: Cloud
          type: string
          description: Which Cloud are you targetting (Select "None" if no IAC is needed)?
          default: azure
          ui:autofocus: true
          enum:
            - none
            - azure
            - aws
            - gcp
          default: none
          enumNames:
            - 'None'
            - 'Azure'
            - 'AWS'
            - 'GCP'
      dependencies:
        cloud:
          oneOf:
            - properties:
                cloud:
                  enum:
                    - azure
                modules:
                  title: Azure TF Modules
                  type: array
                  description: Select the AWS Modules you need for IAC, for example, "EC2", "ALB"
                  ui:autofocus: true
                  items:   
                    type: "string"
                    enum:
                      - vm
                      - rds
                      - lb
                    enumNames:
                      - Virtual Machine
                      - Database
                      - Load Balancer
                  uniqueitems: true
                  ui:widget: checkboxes
```

### 🖥️ Your Environment

PS C:\Users\shane.ohanlon\workspace-syn\cloudpractice-backstage> yarn backstage-cli info
yarn run v1.22.19
$ C:\Users\shane.ohanlon\workspace-syn\cloudpractice-backstage\node_modules\.bin\backstage-cli info
OS:   Windows_NT 10.0.22621 - win32/x64
node: v16.19.1
yarn: 1.22.19
cli:  0.22.5 (installed)
backstage:  1.12.1

Dependencies:
  @backstage/app-defaults                               1.2.1
  @backstage/backend-app-api                            0.4.1
  @backstage/backend-common                             0.18.3
  @backstage/backend-dev-utils                          0.1.1
  @backstage/backend-plugin-api                         0.5.0
  @backstage/backend-tasks                              0.5.0
  @backstage/catalog-client                             1.4.0
  @backstage/catalog-model                              1.2.1
  @backstage/cli-common                                 0.1.12
  @backstage/cli                                        0.22.5
  @backstage/config-loader                              1.1.9
  @backstage/config                                     1.0.7
  @backstage/core-app-api                               1.6.0
  @backstage/core-components                            0.12.5
  @backstage/core-plugin-api                            1.5.0
  @backstage/dev-utils                                  1.0.13
  @backstage/errors                                     1.1.5
  @backstage/eslint-plugin                              0.1.2
  @backstage/integration-aws-node                       0.1.2
  @backstage/integration-react                          1.1.11
  @backstage/integration                                1.4.3
  @backstage/plugin-adr-backend                         0.3.1
  @backstage/plugin-adr-common                          0.2.7
  @backstage/plugin-adr                                 0.4.1
  @backstage/plugin-api-docs                            0.9.1
  @backstage/plugin-app-backend                         0.3.43
  @backstage/plugin-auth-backend                        0.18.1
  @backstage/plugin-auth-node                           0.2.12
  @backstage/plugin-catalog-backend                     1.8.0
  @backstage/plugin-catalog-common                      1.0.12
  @backstage/plugin-catalog-graph                       0.2.28
  @backstage/plugin-catalog-import                      0.9.6
  @backstage/plugin-catalog-node                        1.3.4
  @backstage/plugin-catalog-react                       1.4.0
  @backstage/plugin-catalog                             1.9.0
  @backstage/plugin-cicd-statistics                     0.1.18
  @backstage/plugin-github-actions                      0.5.16
  @backstage/plugin-home                                0.4.32
  @backstage/plugin-org                                 0.6.6
  @backstage/plugin-permission-common                   0.7.4
  @backstage/plugin-permission-node                     0.7.6
  @backstage/plugin-permission-react                    0.4.11
  @backstage/plugin-proxy-backend                       0.2.37
  @backstage/plugin-scaffolder-backend                  1.12.0
  @backstage/plugin-scaffolder-common                   1.2.6
  @backstage/plugin-scaffolder-node                     0.1.1
  @backstage/plugin-scaffolder-react                    1.2.0
  @backstage/plugin-scaffolder                          1.12.0
  @backstage/plugin-search-backend-module-pg            0.5.4
  @backstage/plugin-search-backend-node                 1.1.4
  @backstage/plugin-search-backend                      1.2.4
  @backstage/plugin-search-common                       1.2.2
  @backstage/plugin-search-react                        1.5.1
  @backstage/plugin-search                              1.1.1
  @backstage/plugin-tech-insights-backend-module-jsonfc 0.1.27
  @backstage/plugin-tech-insights-backend               0.5.9
  @backstage/plugin-tech-insights-common                0.2.10
  @backstage/plugin-tech-insights-node                  0.4.1
  @backstage/plugin-tech-insights                       0.3.8
  @backstage/plugin-tech-radar                          0.6.2
  @backstage/plugin-techdocs-backend                    1.6.0
  @backstage/plugin-techdocs-module-addons-contrib      1.0.11
  @backstage/plugin-techdocs-node                       1.6.0
  @backstage/plugin-techdocs-react                      1.1.4
  @backstage/plugin-techdocs                            1.6.0
  @backstage/plugin-user-settings                       0.7.1
  @backstage/release-manifests                          0.0.9
  @backstage/test-utils                                 1.2.6
  @backstage/theme                                      0.2.18
  @backstage/types                                      1.0.2
  @backstage/version-bridge                             1.0.3

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, I don't have time to work on this right now
