### ISSUE TITLE
🐛 Bug Report: Unable to access external-built tech doc pages using URL reader

### ISSUE THREAD

**Issue by viet-ng304** [backstage/backstage#17243]
### 📜 Description

I recently switched from Basic to Recommended techdoc architecture as outlined on https://backstage.io/docs/features/techdocs/architecture. But I encountered an issue and was unable to solve it.

So basically, I set `builder` to `external`, configured a CI/CD pipeline to generate techdoc pages in a directory on a Git repo. I then modified the catalog-info.yaml to add a reference to the generated docs using URL reader (url:https://githubhost.com/org/repo/tree/<branch_name>). When viewing the doc in backstage UI, I was shown an error (please see attached screenshot). Looking at the error in the back-end log, it appears that Backstage attempts to fetch a non-existent `techdocs_metadata.json` file locally.

<img width="1117" alt="Screen Shot 2023-04-04 at 20 52 51" src="https://user-images.githubusercontent.com/112675907/229797727-44ae6dd6-db63-41b9-b059-0152693c3e80.png">

My backstage config
```
techdocs:
  builder: 'external' # Alternatives - 'external'
  cache:
    ttl: 360000
```
My catalog info:
```
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: vendor-auth-service
  description: Authenticate and authorise vendor users and requests
  labels:
    release: mvp
    version: "0.1"
    tier: auth
    internal-reference: 4A
    appType: saas
  annotations:
    backstage.io/techdocs-ref: url:<url-has-been-replaced>
```

The generated docs render correctly using a local browser and there was no error during the doc generation.

### 👍 Expected behavior

The doc rendered correctly with no error.

### 👎 Actual Behavior with Screenshots

```
{"level":"info","message":"Unable to get metadata for 'component:default/svendor-auth-service' with error Error: Unable to read techdocs_metadata.json at /app/node_modules/@backstage/plugin-techdocs-backend/static/docs/default/component/vendor-auth-service/techdocs_metadata.json. Error: Error: ENOENT: no such file or directory, open '/app/node_modules/@backstage/plugin-techdocs-backend/static/docs/default/component/vendor-auth-service/techdocs_metadata.json'; caused by Error: ENOENT: no such file or directory, open '/app/node_modules/@backstage/plugin-techdocs-backend/static/docs/default/component/vendor-auth-service/techdocs_metadata.json'","plugin":"techdocs","service":"backstage","type":"plugin"}
```

### 👟 Reproduction steps

Build doc using the CI/CD pipeline and then access the generated doc in Backstage UI.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by awanlin** [comment]
@viet-ng304, can you include the details on what Cloud storage you are using? I don't see that mentioned and that's where your CI/CD should be publishing the files

Related documentation: https://backstage.io/docs/features/techdocs/using-cloud-storage

**Comment by viet-ng304** [comment]
Hi @awanlin , sorry for late reply.

The output doc are generated and stored on Github. Backstage is running on another server pulling the output doc from Github.

**Comment by manurawat** [comment]
@viet-ng304  @awanlin @OrkoHunter any suggestion? I have similar doubt.. I am using **builder: external** and I am getting below error when I load docs:

```
techdocs:
  generator:
    runIn: 'local' # Alternatives - 'local'
  builder: 'external'
  publisher:
    type: 'awsS3'
```

`Building a newer version of this documentation failed. Error: "Failed to generate docs from /tmp/backstage-iuvaMh into /tmp/techdocs-tmp-7rMaQi; caused by Error: This operation requires Docker. Docker does not appear to be available. Docker.ping() failed with; caused by Error: connect ENOENT /var/run/docker.sock"`

I have included below install of mkdocs as part of Dockerfile as well as per documentation but still getting error.

```
RUN apt-get update && apt-get install -y python3 python3-pip
RUN pip3 install mkdocs-techdocs-core==1.2.0
```

also, I think **backstage.io/techdocs-ref:** value becomes obsolete, when using **builder: external**.

Do you have any suggestion

- How to get get rid of that docker error. (why backstage is not recognizing builder: external)?
- what should be the value of **backstage.io/techdocs-ref:** when **builder: external**?
