### ISSUE TITLE
🐛 Bug Report: Backstage CLI config:check doesn't error on "extra" keys

### ISSUE THREAD

**Issue by adamdmharvey** [backstage/backstage#17412]
### 📜 Description

When running the Backstage CLI `config:check` validation, it doesn't validate if there are extraneous keys in the config.

### 👍 Expected behavior

I believe if there is an extraneous key beyond the defined configuration, there should be a failure.  I suppose this could be added as a separate `--strict` requirement, though simply defaulting to this behavior would be OK with me (though some may feel that's a breaking change in behavior to the CLI).

### 👎 Actual Behavior with Screenshots

We had a PR which added an `integrations` config to our `app-config.production.yaml`, which mistakenly looked like this:

```
auth:
  environment: production
  providers:
    github:
      production:
        clientId: ${AUTH_GITHUB_CLIENT_ID}
        clientSecret: ${AUTH_GITHUB_CLIENT_SECRET}

  integrations:
    github:
      - host: github.com
        apps:
          - appId: 123456
            webhookUrl: "https://smee.io/randomvalue"
            clientId: ${AUTH_GITHUB_CLIENT_ID}
            clientSecret: ${AUTH_GITHUB_CLIENT_SECRET}
            webhookSecret: ${AUTH_GITHUB_WEBHOOK_SECRET}
            privateKey: |
              ${AUTH_GITHUB_PRIVATE_KEY}
```

We have a lint check in our CI which does this:

```
      - run:
          name: "Validate Backstage default configuration"
          command: yarn backstage-cli config:check --config app-config.yaml --lax
      - run:
          name: "Validate Backstage production configuration"
          # combine the default + production config file
          command: yarn backstage-cli config:check --config app-config.yaml --config app-config.production.yaml --lax
```

And these stages went green.

But upon deployment, our startup failed with:

```
Loaded config from app-config.yaml, app-config.production.yaml
{"level":"info","message":"Found 2 new secrets in config that will be redacted","service":"backstage"}
Backend failed to start up TypeError: Invalid type in config for key 'integrations.github[0].token' in 'app-config.production.yaml', got empty-string, wanted string
    at ConfigReader.readConfigValue (/app/node_modules/@backstage/config/dist/index.cjs.js:304:13)
    at ConfigReader.getOptionalString (/app/node_modules/@backstage/config/dist/index.cjs.js:246:17)
    at readGithubIntegrationConfig (/app/node_modules/@backstage/integration/dist/index.cjs.js:1148:24)
```

This is because in fact we still had a root `integrations` key expecting a local token, while our prod config was going to use the GitHub App but couldn't find it, as it was now at `auth.integrations`.  I believe this should not have passed a `config:check`.

### 👟 Reproduction steps

1. Use an `app-config.yaml` with an `integrations.github` key which uses only Token authentication
2. Use an `app-config.production.yaml` configuration, where the `integrations.github` key for a GitHub app is mistakenly placed as a child key to `auth`, i.e. you end up with `auth.integrations.github.apps.appId`
3. Run a config check: `yarn backstage-cli config:check --config app-config.yaml --config app-config.production.yaml --lax`

This currently indicates a successful deployment, even though there is no such `auth.integrations` key defined by 

### 📃 Provide the context for the Bug.

We were adding a new configuration, and expected our linting  heck on validating the schema should have caught if we put an entire section of keys in too deep under another key.

I can appreciate that potentially today by being loose, any other root key may be possible, but I feel like it should still error because say I'm creating a new plugin that requires a root key, I should be setting that in a `config.d.ts` file in my plugin, so the validation properly picks it up.

### 🖥️ Your Environment

yarn run v1.22.10
OS:   Darwin 22.4.0 - darwin/x64
node: v18.15.0
yarn: 1.22.10
cli:  0.22.4 (installed)
backstage:  1.12.0

Dependencies:
  @backstage/app-defaults                          1.2.1
  @backstage/backend-app-api                       0.4.1
  @backstage/backend-common                        0.18.3
  @backstage/backend-dev-utils                     0.1.1
  @backstage/backend-plugin-api                    0.5.0
  @backstage/backend-tasks                         0.5.0
  @backstage/catalog-client                        1.4.0
  @backstage/catalog-model                         1.2.1
  @backstage/cli-common                            0.1.12
  @backstage/cli                                   0.22.4
  @backstage/config-loader                         1.1.9
  @backstage/config                                1.0.7
  @backstage/core-app-api                          1.6.0
  @backstage/core-components                       0.12.5
  @backstage/core-plugin-api                       1.5.0
  @backstage/errors                                1.1.5
  @backstage/eslint-plugin                         0.1.2
  @backstage/integration-aws-node                  0.1.2
  @backstage/integration-react                     1.1.11
  @backstage/integration                           1.4.3
  @backstage/plugin-api-docs                       0.9.1
  @backstage/plugin-app-backend                    0.3.43
  @backstage/plugin-auth-backend                   0.18.1
  @backstage/plugin-auth-node                      0.2.12
  @backstage/plugin-catalog-backend-module-github  0.2.6
  @backstage/plugin-catalog-backend                1.8.0
  @backstage/plugin-catalog-common                 1.0.12
  @backstage/plugin-catalog-graph                  0.2.28
  @backstage/plugin-catalog-import                 0.9.6
  @backstage/plugin-catalog-node                   1.3.4
  @backstage/plugin-catalog-react                  1.4.0
  @backstage/plugin-catalog                        1.9.0
  @backstage/plugin-circleci                       0.3.16
  @backstage/plugin-events-node                    0.2.4
  @backstage/plugin-explore-backend                0.0.5
  @backstage/plugin-explore-common                 0.0.1
  @backstage/plugin-explore-react                  0.0.27
  @backstage/plugin-explore                        0.4.1
  @backstage/plugin-github-actions                 0.5.16
  @backstage/plugin-home                           0.4.32
  @backstage/plugin-org                            0.6.6
  @backstage/plugin-permission-common              0.7.4
  @backstage/plugin-permission-node                0.7.6
  @backstage/plugin-permission-react               0.4.11
  @backstage/plugin-proxy-backend                  0.2.37
  @backstage/plugin-scaffolder-backend             1.12.0
  @backstage/plugin-scaffolder-common              1.2.6
  @backstage/plugin-scaffolder-node                0.1.1
  @backstage/plugin-scaffolder-react               1.2.0
  @backstage/plugin-scaffolder                     1.12.0
  @backstage/plugin-search-backend-module-pg       0.5.4
  @backstage/plugin-search-backend-node            1.1.4
  @backstage/plugin-search-backend                 1.2.4
  @backstage/plugin-search-common                  1.2.2
  @backstage/plugin-search-react                   1.5.1
  @backstage/plugin-search                         1.1.1
  @backstage/plugin-tech-radar                     0.6.2
  @backstage/plugin-techdocs-backend               1.6.0
  @backstage/plugin-techdocs-module-addons-contrib 1.0.11
  @backstage/plugin-techdocs-node                  1.6.0
  @backstage/plugin-techdocs-react                 1.1.4
  @backstage/plugin-techdocs                       1.6.0
  @backstage/plugin-user-settings                  0.7.1
  @backstage/release-manifests                     0.0.9
  @backstage/test-utils                            1.2.6
  @backstage/theme                                 0.2.18
  @backstage/types                                 1.0.2
  @backstage/version-bridge                        1.0.3
✨  Done in 1.32s.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else
