### ISSUE TITLE
🚀 Feature: Set application_name knex property on db connection

### ISSUE THREAD

**Issue by bforbis** [backstage/backstage#17416]
### 🔖 Feature description

Currently there is no "application_name" assigned to the db connection sessions created by the backstage backend. This can be overridden by forcing this property in `app-config.yaml` using the following:
```
backend:
  database:
    client: pg
    connection:
      host: ${POSTGRES_HOST}
      port: ${POSTGRES_PORT}
      user: ${POSTGRES_USER}
      password: ${POSTGRES_PASSWORD}
      application_name: backstage_backend
```

However, since the backstage backend creates multiple connections to the database, it may be useful to default this to something with a little more application context, like the plugin ID of the connection.

### 🎤 Context

As a database administrator, this will give you more context to what is connecting to the underlying database.

### ✌️ Possible Implementation

Default the application_name within `DatabaseManager.getDatabase()` or `connection.createDatabaseClient()`

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None
