### ISSUE TITLE
🐛 Bug Report: Gitlab discovery broken in 1.13 release

### ISSUE THREAD

**Issue by dschaaff** [backstage/backstage#17442]
### 📜 Description

After updating backstage to 1.13 and renaming `branch` to `fallbackBranch` in the config, GitLab discovery is now longer working. 

### 👍 Expected behavior

GitLab discovery should successfully read catalog info from GitLab.

### 👎 Actual Behavior with Screenshots

```catalog warn Unable to read url, Error: Could not get GitLab project ID for: https://gitlab.com/redacted/apps/backstage/-/blob/main/cordial-catalog/all.yaml, Error: GitLab Error 'undefined', undefined type=plugin entity=location:default/generated-9d093286c76662af553b4d073a23b414bc59f62e location=url:https://gitlab.com/redacted/apps/backstage/-/blob/main/cordial-catalog/all.yaml```

### 👟 Reproduction steps

Setup a backstage installation using 1.13 and configure GitLab discovery. Load a location previously discovered from GitLab and observe the error.

### 📃 Provide the context for the Bug.

```yaml
catalog:
  import:
    entityFilename: catalog-info.yaml
    pullRequestBranchName: backstage-integration
  rules:
    - allow: [Component, System, API, Group, Resource, Location, Template]
  providers:
    gitlab:
      cordial:
        host: gitlab.com # Identifies one of the hosts set up in the integrations
        fallbackBranch: master
        group: redacted # Optional. Group and subgroup (if needed) to look for repositories. If not present the whole project will be scanned
        entityFilename: catalog-info.yaml # Optional. Defaults to `catalog-info.yaml`
        projectPattern: '[\s\S]*' # Optional. Filters found projects based on provided patter. Defaults to `/[\s\S]*/`, what means to not filter anything
        schedule: # optional; same options as in TaskScheduleDefinition
          # supports cron, ISO duration, "human duration" as used in code
          frequency: { minutes: 30 }
          # supports ISO duration, "human duration" as used in code
          timeout: { minutes: 3 }
```

### 🖥️ Your Environment

```yarn run v1.22.19
$ /Users/danielschaaff/development/work/backstage/node_modules/.bin/backstage-cli info
OS:   Darwin 22.4.0 - darwin/arm64
node: v18.16.0
yarn: 1.22.19
cli:  0.22.5 (installed)
backstage:  1.12.1

Dependencies:
  @backstage/app-defaults                          1.2.1
  @backstage/backend-app-api                       0.4.1, 0.4.2
  @backstage/backend-common                        0.18.3, 0.18.4
  @backstage/backend-dev-utils                     0.1.1
  @backstage/backend-plugin-api                    0.5.0, 0.5.1
  @backstage/backend-tasks                         0.5.0, 0.5.1
  @backstage/catalog-client                        1.4.0, 1.4.1
  @backstage/catalog-model                         1.2.1, 1.3.0
  @backstage/cli-common                            0.1.12
  @backstage/cli                                   0.22.5
  @backstage/config-loader                         1.1.9, 1.2.0
  @backstage/config                                1.0.7
  @backstage/core-app-api                          1.6.0
  @backstage/core-components                       0.12.5
  @backstage/core-plugin-api                       1.5.0
  @backstage/errors                                1.1.5
  @backstage/eslint-plugin                         0.1.2
  @backstage/integration-aws-node                  0.1.2
  @backstage/integration-react                     1.1.11
  @backstage/integration                           1.4.3, 1.4.4
  @backstage/plugin-api-docs                       0.9.1
  @backstage/plugin-app-backend                    0.3.43
  @backstage/plugin-auth-backend                   0.18.1
  @backstage/plugin-auth-node                      0.2.12, 0.2.13
  @backstage/plugin-catalog-backend-module-gitlab  0.2.0
  @backstage/plugin-catalog-backend                1.8.0
  @backstage/plugin-catalog-common                 1.0.12, 1.0.13
  @backstage/plugin-catalog-graph                  0.2.28
  @backstage/plugin-catalog-import                 0.9.6
  @backstage/plugin-catalog-node                   1.3.4, 1.3.5
  @backstage/plugin-catalog-react                  1.4.0
  @backstage/plugin-catalog                        1.9.0
  @backstage/plugin-github-actions                 0.5.16
  @backstage/plugin-kubernetes-backend             0.9.4
  @backstage/plugin-kubernetes-common              0.6.1
  @backstage/plugin-kubernetes                     0.7.9
  @backstage/plugin-org                            0.6.6
  @backstage/plugin-permission-common              0.7.4, 0.7.5
  @backstage/plugin-permission-node                0.7.6, 0.7.7
  @backstage/plugin-permission-react               0.4.11
  @backstage/plugin-proxy-backend                  0.2.37
  @backstage/plugin-scaffolder-backend             1.12.0
  @backstage/plugin-scaffolder-common              1.2.6
  @backstage/plugin-scaffolder-node                0.1.1
  @backstage/plugin-scaffolder-react               1.2.0
  @backstage/plugin-scaffolder                     1.12.0
  @backstage/plugin-search-backend-module-pg       0.5.4
  @backstage/plugin-search-backend-node            1.1.4
  @backstage/plugin-search-backend                 1.2.4
  @backstage/plugin-search-common                  1.2.2, 1.2.3
  @backstage/plugin-search-react                   1.5.1
  @backstage/plugin-search                         1.1.1
  @backstage/plugin-tech-radar                     0.6.2
  @backstage/plugin-techdocs-backend               1.6.0
  @backstage/plugin-techdocs-module-addons-contrib 1.0.11
  @backstage/plugin-techdocs-node                  1.6.0
  @backstage/plugin-techdocs-react                 1.1.4
  @backstage/plugin-techdocs                       1.6.0
  @backstage/plugin-user-settings                  0.7.1
  @backstage/release-manifests                     0.0.9
  @backstage/test-utils                            1.2.6
  @backstage/theme                                 0.2.18
  @backstage/types                                 1.0.2
  @backstage/version-bridge                        1.0.3
Done in 0.65s.
```

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else
