### ISSUE TITLE
🚀 Feature: Scaffold action for Azure to create a pull request on an existing repository

### ISSUE THREAD

**Issue by fosterm-mw** [backstage/backstage#17533]
### 🔖 Feature description

There is a lot of support for GitHub actions with the scaffolder. In the scaffold template object, you can create steps. I noticed one of these actions in the steps is the `publish:github:pull-request` that will make a pull request to an existing repository. I am wondering if we can develop an action to create a pull request with an ado repository.

### 🎤 Context

In my case, I am writing a template to create a new repository. I want to create the new repository and at the same time make a pull request to different repository in my organization in the same template creation. This would allow me to create a new repository of an application and make a pull request to a deployment repository that will create infrastructure for my software. The pull request will prevent infrastructure sprawl and make this process streamlined. Is this possible? 

### ✌️ Possible Implementation

This is what I envision the steps in the template spec would look like:
```
steps:
    - id: fetch
      name: Template Repo
      action: fetch:template
      input:
        url: ./skeleton
        values:
          name: ${{ parameters.name }}
          description: ${{ parameters.description }}
          owner: ${{ parameters.user }}
          destination: ${{ parameters.repoUrl | parseRepoUrl }}
    
    - id: publish
      name: Publish
      action: publish:azure
      input:
        allowedHosts: ['azure.com']
        description: This is ${{ parameters.name }}
        repoUrl: ${{ parameters.repoUrl }}

# New Functionality
    - id: pull-request
      name: Pull Request
      action: pull-request:azure
      input:
        repoUrl: ${{ parameters.adminRepo }}
        branchName: ${{ parameters.user }}-infra
        title: ${{ parameters.name }}
        description: ${{ parameters.description }}
    
    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps.publish.output.repoContentsUrl }}
        catalogInfoPath: '/catalog-info.yaml'
```
 I am looking to this piece of documentation to write a custom action https://backstage.io/docs/features/software-templates/writing-custom-actions. Wanting to post this here if someone with better typescript skills or if this feature already exists.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!
