### ISSUE TITLE
🚀 Feature: simplify multicluster kafka consumer configuration

### ISSUE THREAD

**Issue by vanyakosmos** [backstage/backstage#17598]
### 🔖 Feature description

Annotation for kafka consumers can be greatly simplified:

```yaml
kafka.apache.org/consumer-groups: */foo-consumer
# or
kafka.apache.org/consumer-groups: foo-consumer
```

### 🎤 Context

In my case there is many production kafka cluster and it is really inconvenient to describe the same consumer for all of them:

```yaml
kafka.apache.org/consumer-groups: test/foo-consumer,ua/foo-consumer,us/foo-consumer,uk/foo-consumer,...,test/bar-consumer,ua/bar-consumer,us/bar-consumer,uk/bar-consumer,...
# instead of...
kafka.apache.org/consumer-groups: foo-consumer,bar-consumer
``` 

### ✌️ Possible Implementation

Allow to specify "any cluster" with `*/` or just by omitting it.

Inside `useConsumerGroupsOffsetsForEntity` check if `clusterId` is `*` or `null` and if so - get all available clusters and retrieve offset for all of them (with some fallback for 404 responses).

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else
