### ISSUE TITLE
🐛 Bug Report: Kubernetes proxy endpoint doesn't work with google auth

### ISSUE THREAD

**Issue by mclarke47** [backstage/backstage#17604]
### 📜 Description

Using the Kubernetes proxy endpoint with `google` authProvider results in a 500 and error message.

With config:

```
kubernetes:
  serviceLocatorMethod:
    type: 'multiTenant'
  clusterLocatorMethods:
    - type: 'gke'
      projectId: 'some-project'
      skipTLSVerify: true # Fix this
      skipMetricsLookup: true
```

I'm seeing the following error when requesting pod logs on the main branch

### 👍 Expected behavior

It should authenticate correctly and return the logs

### 👎 Actual Behavior with Screenshots

<img width="1614" alt="Screenshot 2023-05-01 at 9 10 28 PM" src="https://user-images.githubusercontent.com/6514980/235558929-b36c92fa-8d6c-41c7-a69f-32613186d586.png">

### 👟 Reproduction steps

I suspect this might be for any client side auth provider for example:
1. starting the backend with:
```
kubernetes:
  serviceLocatorMethod:
    type: 'multiTenant'
  clusterLocatorMethods:
    - type: 'gke'
      projectId: 'some-project'
      skipTLSVerify: true # Fix this
      skipMetricsLookup: true
```

2. apply the dice roller manifests

3. navigate to http://localhost:3000/catalog/default/component/dice-roller/kubernetes

4. Click a cluster > deployment > pod > get logs

5. see the error

### 📃 Provide the context for the Bug.

I suspect it is at [this line](https://github.com/backstage/backstage/blob/master/plugins/kubernetes-backend/src/kubernetes-auth-translator/GoogleKubernetesAuthTranslator.ts#L42) as the empty object is being pass in when it should be an auth object with the client side token

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!
