### ISSUE TITLE
🐛 Bug Report: [Scaffolder] defaultBranch parameter ignored in publish gitlab step

### ISSUE THREAD

**Issue by cperreaut** [backstage/backstage#17628]
### 📜 Description

On anapplication template, in the step using `action: publish:gitlab` , the parameter `defaultBranch` is ignored when the parameter `sourcePath` is also set.

Example where the default branch is taken into account : 
```
 - id: publish
      name: Publish
      action: publish:gitlab
      input:
        description: This is ${{ parameters.name }}
        defaultBranch: main
        sourcePath: ${{ parameters.name }}
        repoUrl: ${{ parameters.repoUrl }}
        token: ${{ secrets.USER_OAUTH_TOKEN }}
```

Almost same example where a sourcePath is added and the gitlab repo only creates a master branch, so ignores the 
defaultBranch parameter :  
```
 - id: publish
      name: Publish
      action: publish:gitlab
      input:
        description: This is ${{ parameters.name }}
        defaultBranch: main
        repoUrl: ${{ parameters.repoUrl }}
        token: ${{ secrets.USER_OAUTH_TOKEN }}
```

### 👍 Expected behavior

The parameter defaultBranch should never be ignored and determine which branch the code is pushed to.

### 👎 Actual Behavior with Screenshots

If the sourcePath is not set, the branch created respects the "defaultBranch", set as main : 
![Capture d’écran 2023-05-03 à 11 51 27](https://user-images.githubusercontent.com/104975441/235885250-b6a8d33b-e8ca-4651-9bdd-74963586366b.png)

If the sourcePath is set, the defaultBranch main is ignored and everything is pushed to master: 
![Capture d’écran 2023-05-03 à 11 51 05](https://user-images.githubusercontent.com/104975441/235885505-49f24927-2937-413d-b400-918a9f0b4926.png)

### 👟 Reproduction steps

1. Create a very simple template
2. Add a step that publishes to gitlab using `action: publish:gitlab` and giving a defaultBranch input other than master
3. Test it out : the publishing should happen as expected on given branch
4. Add a value for sourcePath in the inputs of the publish step
5. Retest it out : the given branch is not used, code is pushed to master.

### 🖥️ Your Environment

Version of Backstage : 1.10.0
"@backstage/plugin-scaffolder-backend": "^1.10.0" (but also tested with latest version)

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None
