### ISSUE TITLE
🚀 Feature: API definitions for different environments

### ISSUE THREAD

**Issue by vanyakosmos** [backstage/backstage#17736]
### 🔖 Feature description

Allow to specify different API definitions for different environments.

### 🎤 Context

APIs have different release timing for different environments. For example developers from one team might release their service into test env and then wait a week or so for manual testing to complete. Mean time some another team would like to integrate with existing API and it would be incorrect to show them in backstage "experimental" test API docs.

Found somewhat related issue: https://github.com/backstage/backstage/issues/627

And also docs that says "yeah, keep info about different envs in one component" but doesn't show how to do it: https://backstage.io/docs/features/software-catalog/extending-the-model/#referencing-different-environments-with-the-model

### ✌️ Possible Implementation

```yaml
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: commerce-async-api
  title: Commerce Async API
spec:
  type: asyncapi
  owner: solaris-team
  lifecycle: production
  definition:
    - env: test
      $text: https://schema-registry.test.company.ua/asyncapi.json?project=commerce-service
    - env: production
      $text: https://schema-registry.company.ua/asyncapi.json?project=commerce-service
```

and in UI it will be displayed as separate tabs:

```
| AsyncAPI test | Raw test | AsyncAPI production | Raw production |

# or multilevel tabs

|=test=====| production |
| AsyncAPI |=Raw========|
```

Right now tabs looks like this:

```
| AsyncAPI | Raw |
```

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, I don't have time to work on this right now
