### ISSUE TITLE
🐛 Bug Report: Missing required config value at 'dynatrace.baseUrl

### ISSUE THREAD

**Issue by MHoinkaBS** [backstage/backstage#17859]
### 📜 Description

Hi 
I have installed and configured Dynatrace plugin for Backstage. 
Now when I click on a Dynatrace tab in my test component I get: 
`Error: Missing required config value at 'dynatrace.baseUrl' `  
instead of getting DT dashboard. 

My app-config.yaml:

 ```yaml
app:
  baseUrl: http://localhost:7007
[...]
dynatrace:
  baseUrl: https://dynatrace.my
[...]
proxy:
  [...]
  '/dynatrace':
    target: https://dynatrace.my/api/v2
    headers:
      Authorization: 'Api-Token {token}'
``` 

plugin-dynatrace/package.json looks fine for me: 
```yaml
{
  "name": "@backstage/plugin-dynatrace",
  "version": "4.0.0",
  "main": "dist/index.esm.js",
  "types": "dist/index.d.ts",
  "license": "Apache-2.0",
  "publishConfig": {
    "access": "public",
    "main": "dist/index.esm.js",
    "types": "dist/index.d.ts"
  },
  "backstage": {
    "role": "frontend-plugin"
  },
  "repository": {
    "type": "git",
    "url": "https://github.com/backstage/backstage",
    "directory": "plugins/dynatrace"
  },
  "scripts": {
    "start": "backstage-cli package start",
    "build": "backstage-cli package build",
    "lint": "backstage-cli package lint",
    "test": "backstage-cli package test",
    "clean": "backstage-cli package clean",
    "prepack": "backstage-cli package prepack",
    "postpack": "backstage-cli package postpack"
  },
  "dependencies": {
    "@backstage/catalog-model": "^1.3.0",
    "@backstage/core-components": "^0.13.0",
    "@backstage/core-plugin-api": "^1.5.1",
    "@backstage/theme": "^0.2.19",
    "@material-ui/core": "^4.12.2",
    "@material-ui/icons": "^4.9.1",
    "@material-ui/lab": "4.0.0-alpha.61",
    "react-use": "^17.2.4"
  },
  "peerDependencies": {
    "@backstage/plugin-catalog-react": "^1.5.0",
    "react": "^16.13.1 || ^17.0.0",
    "react-dom": "^16.13.1 || ^17.0.0",
    "react-router-dom": "6.0.0-beta.0 || ^6.3.0"
  },
  "devDependencies": {
    "@backstage/cli": "^0.22.6",
    "@backstage/core-app-api": "^1.7.0",
    "@backstage/dev-utils": "^1.0.14",
    "@backstage/test-utils": "^1.3.0",
    "@testing-library/dom": "^8.0.0",
    "@testing-library/jest-dom": "^5.10.1",
    "@testing-library/react": "^12.1.3",
    "@testing-library/user-event": "^14.0.0",
    "@types/node": "*",
    "@types/react": "^16.13.1 || ^17.0.0",
    "express": "^4.18.1",
    "msw": "^1.0.0"
  },
  "files": [
    "dist",
    "config.d.ts"
  ],
  "configSchema": "config.d.ts",
  "module": "./dist/index.esm.js"
}
```

as well as config.d.ts : 
```
export interface Config {
  /**
   * dynatrace config
   * @visibility frontend
   */
  dynatrace?: {
    /**
     * base url for links
     * @visibility frontend
     */
    baseUrl: string;
  };
}
``` 

I also tried to use in configSchema (in package.json): 
```yaml
    "$schema": "https://backstage.io/schema/config-v1",
    "title": "@backstage/dynatrace",
    "type": "object",
    "properties": {
      "dynatrace": {
        "type": "object",
        "properties": {
          "baseUrl": {
            "type": "tring",
          }
        }
      }
    }
``` 
as described here: https://backstage.io/docs/conf/defining/ (and mentioned here: https://github.com/backstage/backstage/issues/16064) but it also failed. 

### 👍 Expected behavior

Dynatrace tab should show Dynatrace dashboard 

### 👎 Actual Behavior with Screenshots

I'm getting following error: 
```
Error: Missing required config value at 'dynatrace.baseUrl'
    at I.getString (http://localhost:7007/static/module-backstage.9a3e9ca4.js:9:31881)
    at C (http://localhost:7007/static/1760.0f074c9b.chunk.js:1:1578)
    at Gl (http://localhost:7007/static/module-react-dom.cde93b43.js:12:52799)
    at hs (http://localhost:7007/static/module-react-dom.cde93b43.js:16:8596)
    at cs (http://localhost:7007/static/module-react-dom.cde93b43.js:16:930)
    at Za (http://localhost:7007/static/module-react-dom.cde93b43.js:16:861)
    at Ct (http://localhost:7007/static/module-react-dom.cde93b43.js:16:721)
    at Si (http://localhost:7007/static/module-react-dom.cde93b43.js:14:10768)
    at http://localhost:7007/static/module-react-dom.cde93b43.js:12:38633
    at A.unstable_runWithPriority (http://localhost:7007/static/vendor.824b8abf.js:147:3891)
```
![dt_error](https://github.com/backstage/backstage/assets/48984979/301ab0ca-0ef7-4359-9857-4911dd61aec2)

### 👟 Reproduction steps

Set up Dynatrace integration as described in the plugin documentation:  https://github.com/backstage/backstage/tree/master/plugins/dynatrace

### 📃 Provide the context for the Bug.

I don't see any new logs (and especially about missing baseUrl value) when I'm trying to open dynatrace tab.

### 🖥️ Your Environment

I'm testing Backstage in Docker container locally. 

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, I don't have time to work on this right now
