### ISSUE TITLE
🚀 Feature: Use Concurrency for Microsite Deployment Workflow

### ISSUE THREAD

**Issue by awanlin** [backstage/backstage#17893]
### 🔖 Feature description

We should use concurrency for the Microsite Deployment workflow, something like this would work:

```yaml
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
 ``` 

And would just need to be added to this: https://github.com/backstage/backstage/blob/master/.github/workflows/deploy_microsite.yml

### 🎤 Context

Right now the Microsite takes about 90 minutes to run, if multiple PRs are merged with changes to the site they get piled up and all run like this:

![image](https://github.com/backstage/backstage/assets/67169551/38956664-0bdc-4155-913a-98e3a3e83bfe)

With concurrency in place only the most recent would run

### ✌️ Possible Implementation

Adding this:

```yaml
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
 ``` 

To this workflow is all that needs to be done: https://github.com/backstage/backstage/blob/master/.github/workflows/deploy_microsite.yml

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, I don't have time to work on this right now
