### ISSUE TITLE
🐛 Bug Report: Database Password visible in DevTools

### ISSUE THREAD

**Issue by awanlin** [backstage/backstage#17955]
### 📜 Description

When using the DevTools plugin, on the Config tab we can see the database password in clear text when we use the following in our `app-config.yaml`:

```yaml
connection:
       host: 127.0.0.1
       user: postgres
       password: postgres
       port: 5432
``` 

### 👍 Expected behavior

When using the Config tab in the DevTools plugin the database password should be replaced by the text `<secret>` like other sensitive configuration data

### 👎 Actual Behavior with Screenshots

When using the DevTools plugin, on the Config tab we can see the database password in clear text when we use the following in our `app-config.yaml`:

```yaml
connection:
       host: 127.0.0.1
       user: postgres
       password: postgres
       port: 5432
``` 

Which results in this on the Config tab of the DevTools plugin:
![image](https://github.com/backstage/backstage/assets/67169551/4cb9c82c-88cc-4772-a691-50452b7cfc78)

### 👟 Reproduction steps

1. Install the DevTools plugin: https://github.com/backstage/backstage/tree/master/plugins/devtools
2. Update the `backend.database.connection` section in your `app-config.yaml` to look like this (ideally with valid config for your environment):

```yaml
connection:
       host: 127.0.0.1
       user: postgres
       password: postgres
       port: 5432
``` 

3. Start up Backstage: `yarn dev`
4. Navigate to the Config tab in the DevTools plugin: http://localhost:3000/devtools/config
5. Scroll down to the `backend.database.connection` section

**Notice:** You can see the password in clear text

### 📃 Provide the context for the Bug.

From a security perspective we should not be able to see this information in clear text as they could be exploited

### 🖥️ Your Environment

Not really applicable, this isn't an environment specific bug. 

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!
