### ISSUE TITLE
💬 RFC: Add versioning and dependency scope to Entities and Entity References

### ISSUE THREAD

**Issue by rampadc** [backstage/backstage#17969]
### 🔖 Need

Backstage's Component currently does not have a versioning mechanism. When a dependency is added to a Backstage entity (component, system, etc.), there is no built-in way to explain whether that dependency is required to be up-and-running for the component to work. 

For example, a piece of software could run on various environments (VM, Docker, K8s, etc.). These environments can be added as dependencies, but there is no way to indicate which environment is the preferred environment, which version its dependency should be at (say OS version).

### Entity versioning

For versioning, two types of versions could be provided: the entity's version and the actual asset's version the Component is describing (similar to [Helm chart versioning](https://helm.sh/docs/topics/charts/#charts-and-versioning)). These could be implemented as labels, or as spec fields.

Version labels

```yaml
metadata:
  labels:
    backstage.io/version: "2022.4.1" # type string to let users use the versioning scheme inherent to their system
    backstage.io/entity-version: 1.10 # semver versioning for Backstage's entity versioning
```

Spec labels

```
spec:
  # type string to let users use the versioning scheme inherent to their system
  version: "2022.4.1"
  # semver versioning for Backstage entity's versioning
  entityVersion: 1.10
```

### Dependency scoping and versioning
  
For entity references, I'm proposing that we extend the Backstage's entity reference strings to become similar to the [purl spec](https://github.com/package-url/purl-spec) with additional fields added for versioning, using [purl-spec version range spec](https://github.com/package-url/purl-spec/blob/version-range-spec/VERSION-RANGE-SPEC.rst) and [CycloneDX's component scope](https://cyclonedx.org/docs/1.4/json/#components_items_scope).

At the moment, the Backstage entity reference has the following form: `[<kind>:][<namespace>/]<name>`. 

Following the purl spec, we can extend this to be `[<kind>:][<namespace>/]<name>@<default-version>`. 

For additional fields, we could present them as URL parameters.

Using the purl versioning spec, we can extend this to be 
`[<kind>:][<namespace>/]<name>@<default-version>?vers=">=(min_ver)|<=(max_ver)"` (`min_ver` and `max_ver` wrapped in brackets to make things easier to read). The versions here are the software/library/etc. that the entity refers to. They don't necessarily need to be semver and could be whatever existing versioning system the user is using.

To indicate whether a dependency is required/optional, the format could be extended to `[<kind>:][<namespace>/]<name>@<default-version>?scope=<scope>&default_scope=<default_scope>`. The scope values could be `required`, `optional` and `excluded`. If the scope is not defined, `required` is assumed. ([CycloneDX's component scope](https://cyclonedx.org/docs/1.4/json/#components_items_scope))

These fields can be combined. An example of a full Component could be

```yaml
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: app-connect-runtime
  title: App Connect Runtime
  labels:
    backstage.io/version: "11.0.1.0"
    backstage.io/entity-version: "0.1.0"
  namespace: cp4i
spec:
  type: application
  lifecycle: production
  owner: group:integration-team
  dependsOn:
    - component:cp4i/foundational-services@22.0.1.2?scope=optional&default_scope=required&vers=">=22.0.0|<=22.0.2"
```

In block form, these entity references could look like

```yaml
- name: foundational-services
  kind: component
  namespace: cp4i
  version: "22.0.1.2"   
  scope: optional
  default_scope: required
  vers: ">=22.0.0|<=22.0.2"
```

### ❌ Risks

An entity dependency can have the same name but different versions. The resolved entity name in Backstage UI can contain the default version `entity-name@default-version`. 

### 👀 Have you spent some time to check if this RFC has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)
