### ISSUE TITLE
🐛 Bug Report: 403 error while registering location in catalog

### ISSUE THREAD

**Issue by pklenovic** [backstage/backstage#18022]
### 📜 Description

When registering a new location in the catalog plugin, I encounter a 403 Forbidden error. This issue began after upgrading from backstage version 1.11.0 to 1.15.0-next.1. The configuration for our GitHub integration remains unchanged, including the token and its permissions. Additionally, the catalog configuration remains the same. 
Interestingly, when attempting to register a single component referenced in the location YAML, everything works fine.

Location yaml:
```
apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: ecosystems
  description: A collection of all domains and systems
spec:
  targets:
    - ./domains/*.yaml
    - ./systems/*/*.yaml
```

Catalog configuration:
```
catalog:
  import:
    entityFilename: catalog-info.yaml
    pullRequestBranchName: backstage-integration
  rules:
    - allow:
        - Component
        - API
        - Domain
        - System
        - Resource
        - Location
        - User
        - Group
        - Template

  locations:
    - type: url
      target: ${BACKSTAGE_ECOSYSTEMS_GITHUB_PATH}
      rules:
        - allow: [Domain, System, Location]
    - type: url
      target: ${BACKSTAGE_RESOURCES_GITHUB_PATH}
      rules:
        - allow: [Resource, Location]
    - type: url
      target: ${BACKSTAGE_TEMPLATES_GITHUB_PATH}
      rules:
        - allow: [Template]

  providers:
    github:
      superologyApps:
        organization: superology-backend
        filters:
          branch: develop
        catalogPath: "/catalog-info.yaml"
        validateLocationsExist: true
      superbetApps:
        organization: superbet-group
        filters:
          branch: develop
        catalogPath: "/catalog-info.yaml"
        validateLocationsExist: true
```
I tried playing with configuration, token permissions etc. but nothing worked. While debugging I found that function `runSpecialLocationStep` to be only difference when registering single component opposed to location component, but I couldn't figure out what is exactly happening.

### 👍 Expected behavior

Registering location should register all components that are referenced in that location.

### 👎 Actual Behavior with Screenshots

403 error:
`{"error":{"name":"InputError","message":"Error: Unable to read url, Error: Request failed for https://api.github.com/repos/superbet-group/engprod.backstage-ecosystems/commits/master/status?per_page=0, 403 Forbidden, Error: Unable to read url, Error: Request failed for https://api.github.com/repos/superbet-group/engprod.backstage-ecosystems/commits/master/status?per_page=0, 403 Forbidden","stack":"InputError: Error: Unable to read url, Error: Request failed for https://api.github.com/repos/superbet-group/engprod.backstage-ecosystems/commits/master/status?per_page=0, 403 Forbidden, Error: Unable to read url, Error: Request failed for https://api.github.com/repos/superbet-group/engprod.backstage-ecosystems/commits/master/status?per_page=0, 403 Forbidden\n at DefaultLocationService.processEntities (/Users/petarklenovic/Work/engprod.backstage-happening/node_modules/@backstage/plugin-catalog-backend/dist/cjs/CatalogBuilder-99a535c6.cjs.js:1896:15)\n at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n at async DefaultLocationService.dryRunCreateLocation (/Users/petarklenovic/Work/engprod.backstage-happening/node_modules/@backstage/plugin-catalog-backend/dist/cjs/CatalogBuilder-99a535c6.cjs.js:1927:22)\n at async /Users/petarklenovic/Work/engprod.backstage-happening/node_modules/@backstage/plugin-catalog-backend/dist/cjs/CatalogBuilder-99a535c6.cjs.js:3532:22"},"request":{"method":"POST","url":"/locations?dryRun=true"},"response":{"statusCode":400}}`

### 👟 Reproduction steps

1. Go to software catalog
2. Click on "CREATE"
3. "REGISTER A NEW COMPONENT"
4. Enter full url to location yaml
5. Click on "ANALYZE"

### 📃 Provide the context for the Bug.

The only difference between when this was working and is not is backstage version.  It works fine on version 1.11.0 but I get 403 error on version 1.15.0-next.1.

### 🖥️ Your Environment

```
OS:   Darwin 22.2.0 - darwin/arm64
node: v18.14.2
yarn: 1.22.19
cli:  0.22.8-next.1 (installed)
backstage:  1.15.0-next.1

Dependencies:
  @backstage/app-defaults                          1.3.1, 1.4.0-next.1
  @backstage/backend-app-api                       0.4.3, 0.4.4-next.1
  @backstage/backend-common                        0.18.5, 0.19.0-next.1
  @backstage/backend-dev-utils                     0.1.1
  @backstage/backend-plugin-api                    0.5.2, 0.5.3-next.1
  @backstage/backend-tasks                         0.5.2, 0.5.3-next.1
  @backstage/catalog-client                        1.4.1, 1.4.2-next.1
  @backstage/catalog-model                         1.3.0, 1.4.0-next.0
  @backstage/cli-common                            0.1.12
  @backstage/cli-node                              0.1.0, 0.1.1-next.0
  @backstage/cli                                   0.22.7, 0.22.8-next.1
  @backstage/config-loader                         1.3.0, 1.3.1-next.1
  @backstage/config                                1.0.7
  @backstage/core-app-api                          1.8.0, 1.8.1-next.0
  @backstage/core-components                       0.12.5, 0.13.1, 0.13.2-next.1
  @backstage/core-plugin-api                       1.5.1, 1.5.2-next.0
  @backstage/dev-utils                             1.0.15
  @backstage/errors                                1.1.5, 1.2.0-next.0
  @backstage/eslint-plugin                         0.1.3
  @backstage/integration-aws-node                  0.1.3, 0.1.4-next.0
  @backstage/integration-react                     1.1.13, 1.1.14-next.1
  @backstage/integration                           1.4.5, 1.5.0-next.0
  @backstage/plugin-api-docs                       0.9.4-next.1
  @backstage/plugin-app-backend                    0.3.46-next.1
  @backstage/plugin-auth-backend                   0.18.4-next.1
  @backstage/plugin-auth-node                      0.2.14, 0.2.15-next.1
  @backstage/plugin-catalog-backend-module-github  0.2.7
  @backstage/plugin-catalog-backend                1.9.1, 1.9.2-next.1
  @backstage/plugin-catalog-common                 1.0.13, 1.0.14-next.0
  @backstage/plugin-catalog-graph                  0.2.31-next.1
  @backstage/plugin-catalog-import                 0.9.9-next.1
  @backstage/plugin-catalog-node                   1.3.6, 1.3.7-next.1
  @backstage/plugin-catalog-react                  1.6.0, 1.7.0-next.1
  @backstage/plugin-catalog                        1.11.1-next.1
  @backstage/plugin-events-node                    0.2.6
  @backstage/plugin-github-actions                 0.6.0-next.1
  @backstage/plugin-org                            0.6.9-next.1
  @backstage/plugin-permission-backend             0.5.20
  @backstage/plugin-permission-common              0.7.5, 0.7.6-next.0
  @backstage/plugin-permission-node                0.7.8, 0.7.9-next.1
  @backstage/plugin-permission-react               0.4.12, 0.4.13-next.0
  @backstage/plugin-proxy-backend                  0.2.40-next.1
  @backstage/plugin-scaffolder-backend             1.15.0-next.1
  @backstage/plugin-scaffolder-common              1.3.0, 1.3.1-next.0
  @backstage/plugin-scaffolder-node                0.1.4-next.1
  @backstage/plugin-scaffolder-react               1.5.0-next.1
  @backstage/plugin-scaffolder                     1.13.2-next.1
  @backstage/plugin-search-backend-module-catalog  0.1.1, 0.1.2-next.1
  @backstage/plugin-search-backend-module-pg       0.5.7-next.1
  @backstage/plugin-search-backend-module-techdocs 0.1.2-next.1
  @backstage/plugin-search-backend-node            1.2.1, 1.2.2-next.1
  @backstage/plugin-search-backend                 1.3.2-next.1
  @backstage/plugin-search-common                  1.2.3, 1.2.4-next.0
  @backstage/plugin-search-react                   1.6.1-next.1
  @backstage/plugin-search                         1.3.1-next.1
  @backstage/plugin-tech-radar                     0.6.5-next.1
  @backstage/plugin-techdocs-backend               1.6.3-next.1
  @backstage/plugin-techdocs-module-addons-contrib 1.0.14-next.1
  @backstage/plugin-techdocs-node                  1.7.2-next.1
  @backstage/plugin-techdocs-react                 1.1.7-next.1
  @backstage/plugin-techdocs                       1.6.3-next.1
  @backstage/plugin-user-settings                  0.7.4-next.1
  @backstage/release-manifests                     0.0.9
  @backstage/test-utils                            1.3.1, 1.4.0-next.1
  @backstage/theme                                 0.2.19, 0.3.0, 0.4.0-next.0
  @backstage/types                                 1.0.2
  @backstage/version-bridge                        1.0.4
```

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None
