### ISSUE TITLE
🐛 Bug Report: 500 error fetching pod logs from LKE cluster

### ISSUE THREAD

**Issue by hritikch24** [backstage/backstage#18036]
### 📜 Description

Pod logs component not working and still throwing error 500. Below is the screenshot attached. If some proxy changes are needed in app-config.yml then what are those?
<img width="1324" alt="image" src="https://github.com/backstage/backstage/assets/69822624/0b3b5095-3486-4428-a646-dedb69092d4d">

### 👍 Expected behavior

It should show pod logs.

### 👎 Actual Behavior with Screenshots

It should show pod logs.

### 👟 Reproduction steps

1). Go to backstage application.
2). Add application to backstage.
3). Goto kubernetes for existing ref in  backstage .
4). Click on pod.
5).Click on logs and see the result.

### 🖥️ Your Environment

I tried to pull these logs on latest code with yarn run command.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by ivangonzalezacuna** [comment]
Maybe it helps to find a solution/fix for this.

We are also trying to upgrade to the latest version, but in our case the logs where making backstage to crash because "localhost" was being used instead of the correct Hostname (which is being used in the backend), so I was getting a `ERR_TLS_CERT_ALTNAME_INVALID`. To fix it, we added the `skipTLSVerify: true` to the kubernetes config. This makes the proxy to set the field `secure: false`, and then the logs are displayed as expected.

**Comment by jamieklassen** [comment]
This may be tough to reproduce without more details -- @hritikch24 can you provide the actual app config you're using (redacting any explicit secrets)? It seems relevant to understand what cluster locator you are using, how/where your cluster is deployed (did you use a cloud provider? bare metal? etc), what authentication strategy is in play, and any other network configuration that might be relevant.

**Comment by jamieklassen** [comment]
For posterity, when I extract the `kubernetes` stanza from that attachment, I see:
```yaml
kubernetes:
  logging:
    enabled: true
  serviceLocatorMethod:
    type: 'multiTenant'
  clusterLocatorMethods:
    - type: 'config'
      clusters:
        - url: https://7b5b06da-1bb2-43f1-b3e8-2c8ae98f10d2.ap-west-1.linodelke.net:443
          name: lke80509
          authProvider: 'serviceAccount'
          skipTLSVerify: true
          skipMetricsLookup: false
          caData: ERGdnRxxcdcs
          serviceAccountToken: xxxxxxxxxxxx
```
