### ISSUE TITLE
🐛 Bug Report: Profile Picture String /spec/profile/picture must be string

### ISSUE THREAD

**Issue by hghtwr** [backstage/backstage#18035]
### 📜 Description

We have connected our self-hosted GitLab instance with Backstage and we have setup automatic discovery. It works fine except for users without profile picture.

I go to the Catalog and select Users I will only see users that have a profile picture set.

### 👍 Expected behavior

It should synchronize all users regardless if they have a profile picture set or not

### 👎 Actual Behavior with Screenshots

It actually only synchronizes users with profile pictures and prints a warning for every other user: 

`[1] 2023-05-31T09:25:04.661Z catalog warn Processor BuiltinKindsEntityProcessor threw an error while validating the entity user:default/<name>; caused by TypeError: /spec/profile/picture must be string - type: string type=plugin entity=user:default/<name> location=url:https://<URL>/<name>
`

### 👟 Reproduction steps

1. Setup backstage
2. Define the integration in ```app-config.yaml```
```
catalog:
  providers:
    gitlab:
      yourProviderId:
        host: ${GITLAB_HOST}
        orgEnabled: true
        group: <our-group>
        schedule: # optional; same options as in TaskScheduleDefinition
          # supports cron, ISO duration, "human duration" as used in code
          frequency: { minutes: 2 }
          # supports ISO duration, "human duration" as used in code
          timeout: { minutes: 1 }
```
3. Run ```yarn dev```

### 📃 Provide the context for the Bug.

I bumped to the latest release to make sure no update fixed this already but no help :( 

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else
