### ISSUE TITLE
🐛 Bug Report: GitLab latest artefact locations are not updated

### ISSUE THREAD

**Issue by garryod** [backstage/backstage#18123]
### 📜 Description

When the catalog is configured with a URL pointing to the latest instance of a GitLab artefact (e.g. `https://gitlab.diamond.ac.uk/sscc-docs/groups/-/jobs/artifacts/main/raw/all-groups.yaml?job=collate`), refreshes of the location do not update the ingested entities.

### 👍 Expected behavior

Entities should be re-ingested whenever a refresh is requested

### 👎 Actual Behavior with Screenshots

Entities are not re-ingested whenever a refresh is requested

### 👟 Reproduction steps

1. Create a new backstage app as per https://backstage.io/docs/getting-started/
2. Add the GitLab integration as per https://backstage.io/docs/integrations/gitlab/discovery
3. Create a GitLab workflow which produces an entity descriptor as an artefact#
4. Execute the workflow - generating an initial artefact
5. Add the "latest" artefact location to the catalog locations
6. Run up backstage
7. View ingested entities
8. Execute the workflow - generating another (different) artefact
9. Request a refresh of the location in backstage
10. View ingested entities - will be unchanged

### 📃 Provide the context for the Bug.

Repository: https://github.com/DiamondLightSource/developer-portal
- Entity provider configuration:
  ```typescript
  GitlabDiscoveryEntityProvider.fromConfig(env.config, {
    logger: env.logger,
    scheduler: env.scheduler,
  }),
  ```
  with:
  ```yaml
  integrations:
    gitlab:
      - host: gitlab.diamond.ac.uk
        apiBaseUrl: https://gitlab.diamond.ac.uk/api/v4
        token: ${GITLAB_TOKEN}
  ```
- Location configuration:
  ```yaml
  catalog:
    locations:
      - type: url
        target: https://gitlab.diamond.ac.uk/sscc-docs/groups/-/jobs/artifacts/main/raw/all-groups.yaml?job=collate
        rules:
          - allow: [Group]
  ```

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!
( Will require some expert assistance with finding the source of the issue )
