### ISSUE TITLE
🐛 Bug Report: Processor BuiltinKindsEntityProcessor threw an error while validating the entity user caused by TypeError: /spec/profile/picture must be string - type: string when using GitLab Organizational Data

### ISSUE THREAD

**Issue by freed-git** [backstage/backstage#18131]
### 📜 Description

When using the GitLab Organizational Data integration with a self hosted Gitlab, I received the following error.

`[1] 2023-06-05T14:01:10.320Z catalog warn Processor BuiltinKindsEntityProcessor threw an error while validating the entity user:default/firstname.lastname; caused by TypeError: /spec/profile/picture must be string - type: string type=plugin entity=user:default/firstname.lastname location=url:https://git.example.org/firstname.lastname`

I'm looking for a way to fix this issue. Most likely not all gitlab users will have profile pictures. Is it possible to ignore this error and still ingest the user? Possibly by detecting that the profile picture is null, and converting to empty string? Or making the profile picture optional ?

All help is welcome

### 👍 Expected behavior

When using GitLab Organizational Data integration, user and groups entities should be ingested from a self hosted instance of gitlab.

### 👎 Actual Behavior with Screenshots

Gitlab users with profile pictures defined get successfully ingested. Gitlab users with no profile picture defined do not get ingested into backstage when using the GitLab Organizational Data integration.

### 👟 Reproduction steps

Create a new backstage app as per https://backstage.io/docs/getting-started/
Add the GitLab Org Data integration as per https://backstage.io/docs/integrations/gitlab/org
Run backstage using yarn dev
View ingested user entities
View logs errors

### 📃 Provide the context for the Bug.

Gitlab Integration

/backstage-local/packages/backend/src/plugins/catalog.ts

```
import { CatalogBuilder } from '@backstage/plugin-catalog-backend';
import { ScaffolderEntitiesProcessor } from '@backstage/plugin-scaffolder-backend';
import { Router } from 'express';
import { PluginEnvironment } from '../types';
import { GitlabDiscoveryEntityProvider, GitlabOrgDiscoveryEntityProvider } from '@backstage/plugin-catalog-backend-module-gitlab';

export default async function createPlugin(
  env: PluginEnvironment,
): Promise<Router> {
  const builder = await CatalogBuilder.create(env);
  builder.addProcessor(new ScaffolderEntitiesProcessor());

  builder.addEntityProvider(
    ...GitlabDiscoveryEntityProvider.fromConfig(env.config, {
      logger: env.logger,
      scheduler: env.scheduler,
    }),
  );

  builder.addEntityProvider(
    ...GitlabOrgDiscoveryEntityProvider.fromConfig(env.config, {
      logger: env.logger,
      scheduler: env.scheduler,
    }),
  );

  const { processingEngine, router } = await builder.build();
  await processingEngine.start();
  return router;
}
```

app-config.local.yaml

```
integrations:
  gitlab:
    - host: git.example.org
      token: *** token ***
      apiBaseUrl: https://git.example.org/api/v4
      baseUrl: https://git.example.org

catalog:
  rules:
    - allow:
      - Component
      - System
      - API
      - Resource
      - Location
      - Template
      - Group
      - User
      - Domain
  providers:
    gitlab:
      yourProviderId:
        host: git.example.org # Identifies one of the hosts set up in the integrations
        branch: main # Optional. Used to discover on a specific branch
        fallbackBranch: main # Optional. Fallback to be used if there is no default branch configured at the Gitlab repository. It is only used, if `branch` is undefined. Uses `master` as default
        group: mygroup # Optional. Group and subgroup (if needed) to look for repositories. If not present the whole instance will be scanned
        entityFilename: catalog-info.yaml # Optional. Defaults to `catalog-info.yaml`
        projectPattern: '[\s\S]*' # Optional. Filters found projects based on provided patter. Defaults to `[\s\S]*`, which means to not filter anything
        schedule: # optional; same options as in TaskScheduleDefinition
          # supports cron, ISO duration, "human duration" as used in code
          frequency: { minutes: 5 }
          # supports ISO duration, "human duration" as used in code
          timeout: { minutes: 3 }
        groupPattern: '[\s\S]*'
        orgEnabled: true
```
     

### 🖥️ Your Environment

local dev environment using ubuntu

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!
