### ISSUE TITLE
🐛 Bug Report: Can't fetch template from private Gitlab repository

### ISSUE THREAD

**Issue by nlamirault** [backstage/backstage#18226]
### 📜 Description

I try to create a new template for a Component.
this is the template:

``` yaml
---
apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: system-template
  title: New System
  description: Create a System from template
  tags:
    - system
spec:
  owner: group:team-infra
  type: system

  parameters:
    - title: Provide System simple information
      required:
        - system
        - description
        - owner
        - domain
        - lifecycle
      properties:
        system:
          title: Name
          type: string
          description: Unique name of the System
          ui:field: EntityNamePicker
          ui:autofocus: true

        description:
          title: Description
          type: string
          description: Help others understand what this website is for.

        owner:
          title: Owner
          type: string
          description: Owner of the component
          ui:field: OwnerPicker
          ui:options:
            allowedKinds:
              - Group

        domain:
          title: Domain
          type: string
          description: Domain of the System
          ui:field: EntityPicker
          ui:options:
            allowedKinds:
              - Domain
            defaultKind: Domain

        lifecycle:
          title: Lifecycle
          description: 'Application lifecycle'
          type: string
          default: experimental
          enum:
            - deprecated
            - experimental
            - production

        dryRun:
          title: Only perform a dry run, don't publish anything
          type: boolean
          default: false

  steps:
    - id: fetch-template
      name: Fetch System Template
      action: fetch:template
      if: ${{ parameters.dryRun == false }}
      input:
        targetPath: ./systems
        # url: https://gitlab.com/xxxxxxxxx/deploy-tools/-/blob/feat/backstage-app/backstage/backstage/dev/skeleton/infrastructure/system
        url: ./skeleton/infrastructure/system
        values:
          system: ${{ parameters.system }}
          description: ${{ parameters.description }}
          owner: ${{ parameters.owner }}
          domain: ${{ parameters.domain }}
          lifecycle: ${{ parameters.lifecycle }}

    - id: publish
      name: Publish
      action: publish:gitlab:merge-request
      if: ${{ parameters.dryRun == false }}
      input:
        repoUrl: gitlab.com?repo=deploy-tools&owner=xxxxxxxx
        title: "[Backstage] Creating catalog-info.yaml for ${{ parameters.component }}"
        branchName: backstage/create-${{ parameters.component }}
        description: |
          # New project: ${{ parameters.component }}
          ${{ parameters.description if parameters.description }}
        targetPath: backstage/backstage/dev/components/${{ parameters.component }}
        token: ${{ secrets.GITLAB_TOKEN }}
        commitAction: create
        removeSourceBranch: true
        # assignee: ${{ parameters.assignee }}

    # - id: register
    #   name: Register Application in Catalog
    #   action: catalog:register
    #   if: ${{ parameters.dryRun !== true }}
    #   input:
    #     repoContentsUrl: ${{ steps.publish.output.repoContentsUrl }}
    #     catalogInfoPath: "/catalog-info.yaml"


    - name: Results
      if: ${{ parameters.dryRun }}
      action: debug:log
      input:
        listWorkspace: true

  output:
    links:
      - title: Go to GitOps Pull Request
        url: ${{ steps.open-pr.output.remoteUrl }}
      - title: Open in catalog
        icon: catalog
        entityRef: ${{ steps.register.output.entityRef }}
```

### 👍 Expected behavior

download the template.

### 👎 Actual Behavior with Screenshots

```
12023-06-13T09:23:28.146Z Beginning step Fetch System Template
22023-06-13T09:23:28.174Z info: Fetching template content from remote URL3
2023-06-13T09:23:29.102Z NotFoundError: Failed to read tree (archive) from https://gitlab.com/xxx/deploy-tools/-/blob/feat%2Fbackstage-app/backstage/backstage/dev/templates/skeleton/infrastructure/system, Opens in a new window, 404 Not Found4   
at _GitlabUrlReader.readTree (/app/node_modules/@backstage/backend-common/dist/index.cjs.js:2580:15)5
at runMicrotasks (<anonymous>)6
at processTicksAndRejections (node:internal/process/task_queues:96:5)7
at async UrlReaderPredicateMux.readTree (/app/node_modules/@backstage/backend-common/dist/index.cjs.js:3170:16)8
at async fetchContents (/app/node_modules/@backstage/plugin-scaffolder-backend/dist/cjs/ScaffolderEntitiesProcessor-021c5dcb.cjs.js:579:17)9
at async Object.handler (/app/node_modules/@backstage/plugin-scaffolder-backend/dist/cjs/ScaffolderEntitiesProcessor-021c5dcb.cjs.js:1020:7)10
at async NunjucksWorkflowRunner.executeStep (/app/node_modules/@backstage/plugin-scaffolder-backend/dist/cjs/ScaffolderEntitiesProcessor-021c5dcb.cjs.js:5201:7)11
at async NunjucksWorkflowRunner.execute (/app/node_modules/@backstage/plugin-scaffolder-backend/dist/cjs/ScaffolderEntitiesProcessor-021c5dcb.cjs.js:5266:9)12
at async TaskWorker.runOneTask (/app/node_modules/@backstage/plugin-scaffolder-backend/dist/cjs/ScaffolderEntitiesProcessor-021c5dcb.cjs.js:5481:26)13
at async run (/app/node_modules/p-queue/dist/index.js:163:29)
```

### 👟 Reproduction steps

Try to create a new component

### 📃 Provide the context for the Bug.

but if i open in a browser the URL from the console log (https://gitlab.com/xxx/deploy-tools/-/blob/feat%2Fbackstage-app/backstage/backstage/dev/templates/skeleton/infrastructure/system), it works fine

My Kubernetes pod have an environment variable `GITLAB_TOKEN` 

### 🖥️ Your Environment

Backstage deployed in a Kubernetes cluster using the Helm chart.
The application works fine.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None
