### ISSUE TITLE
🐛 Bug Report: `pick` scaffolder filter doesn't work as expected

### ISSUE THREAD

**Issue by jmadureira** [backstage/backstage#18227]
### 📜 Description

The `pick` scaffolder filter introduced in `v1.13.0` doesn't work as expected when used for instance on entities retrieved from the catalog.

### 👍 Expected behavior

When using the following `steps`:

```yaml
steps:
    - id: catalogFetch
      name: Fetch Context
      action: catalog:fetch
      input:
        entityRef: ${{ parameters.api }}
    - name: Debug definition
      action: debug:log
      input:
        message: ${{ steps.catalogFetch.output | pick('spec') | pick('definition') }}
```

It is expected for the `debug:log` action to be given the `spec.definition` attribute of the (in this case) API definition.

### 👎 Actual Behavior with Screenshots

The snippet isn't interpreted that the `debug:log` outputs `${{ steps.catalogFetch.output | pick('spec') | pick('definition') }}` instead of the contents of the `definition` attribute.

> Check the **Reproduction steps** for more context.

### 👟 Reproduction steps

Create a template similar to the following

```yaml
apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: test-api-template
  title: Test pick filter
  tags: []
  links: []
spec:
  type: configuration
  parameters:
    - title: Initial configuration
      required:
        - api
      properties:
        api:
          title: API
          type: string
          description: The API you want to test
          ui:field: EntityPicker
          ui:options:
            defaultKind: API
            catalogFilter:
              - kind:
                  - API
                spec.type: openapi
            allowArbitraryValues: false
  steps:
    - id: catalogFetch
      name: Fetch Context
      action: catalog:fetch
      input:
        entityRef: ${{ parameters.api }}
    - name: Debug definition
      action: debug:log
      input:
        message: ${{ steps.catalogFetch.output | pick('spec') | pick('definition') }}
    - name: Debug spec
      action: debug:log
      input:
        message: ${{ steps.catalogFetch.output | pick('spec') }}
    - name: Debug output
      action: debug:log
      input:
        message: ${{ steps.catalogFetch.output }}
```

And register an `API resource` on the catalog for testing purposes:

```yaml
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: test-openapi-api
spec:
  type: openapi
  lifecycle: test
  definition:
    $text: the path to some openapi spec
```

When the scaffolder runs the `test-api-template` it will output each step something like:

**Fetch Content**

```
[1](http://localhost:3000/create/tasks/90954478-b868-4a9c-b4e4-135c7bfbff94#line-1)2023-06-13T10:13:58.000Z Beginning step Fetch Context
[2](http://localhost:3000/create/tasks/90954478-b868-4a9c-b4e4-135c7bfbff94#line-2)2023-06-13T10:13:58.000Z Finished step Fetch Context
```

**Debug definition**

```
[1](http://localhost:3000/create/tasks/90954478-b868-4a9c-b4e4-135c7bfbff94#line-1)2023-06-13T10:13:58.000Z Beginning step Debug definition
[2](http://localhost:3000/create/tasks/90954478-b868-4a9c-b4e4-135c7bfbff94#line-2)2023-06-13T10:13:58.000Z info: {
[3](http://localhost:3000/create/tasks/90954478-b868-4a9c-b4e4-135c7bfbff94#line-3)  "message": "${{ steps.catalogFetch.output | pick('spec') | pick('definition') }}"
[4](http://localhost:3000/create/tasks/90954478-b868-4a9c-b4e4-135c7bfbff94#line-4)}
[5](http://localhost:3000/create/tasks/90954478-b868-4a9c-b4e4-135c7bfbff94#line-5)2023-06-13T10:13:58.000Z ${{ steps.catalogFetch.output | pick('spec') | pick('definition') }}
[6](http://localhost:3000/create/tasks/90954478-b868-4a9c-b4e4-135c7bfbff94#line-6)2023-06-13T10:13:58.000Z Finished step Debug definition
```

**Debug spec**

```
[1](http://localhost:3000/create/tasks/90954478-b868-4a9c-b4e4-135c7bfbff94#line-1)2023-06-13T10:13:58.000Z Beginning step Debug spec
[2](http://localhost:3000/create/tasks/90954478-b868-4a9c-b4e4-135c7bfbff94#line-2)2023-06-13T10:13:58.000Z info: {
[3](http://localhost:3000/create/tasks/90954478-b868-4a9c-b4e4-135c7bfbff94#line-3)  "message": "${{ steps.catalogFetch.output | pick('spec') }}"
[4](http://localhost:3000/create/tasks/90954478-b868-4a9c-b4e4-135c7bfbff94#line-4)}
[5](http://localhost:3000/create/tasks/90954478-b868-4a9c-b4e4-135c7bfbff94#line-5)2023-06-13T10:13:58.000Z ${{ steps.catalogFetch.output | pick('spec') }}
[6](http://localhost:3000/create/tasks/90954478-b868-4a9c-b4e4-135c7bfbff94#line-6)2023-06-13T10:13:58.000Z Finished step Debug spec
```

**Debug output** 🟥 

```
[1](http://localhost:3000/create/tasks/90954478-b868-4a9c-b4e4-135c7bfbff94#line-1)2023-06-13T10:13:58.000Z Beginning step Debug output
[2](http://localhost:3000/create/tasks/90954478-b868-4a9c-b4e4-135c7bfbff94#line-2)2023-06-13T10:13:58.000Z InputError: Invalid input passed to action debug:log, instance.message is not of a type(s) string
...
```

The **Debug output** step fails because the input provided isn't a string. If the `pick` filter worked as expected then the **Debug spec** step should have failed as well because it should have also been given an object.

### 🖥️ Your Environment

```
OS:   Darwin 22.5.0 - darwin/arm64
node: v16.14.0
yarn: 1.22.17
cli:  0.22.7 (installed)
backstage:  1.14.1

Dependencies:
  @backstage/app-defaults                               1.3.1
  @backstage/backend-app-api                            0.4.3
  @backstage/backend-common                             0.18.5
  @backstage/backend-dev-utils                          0.1.1
  @backstage/backend-plugin-api                         0.5.2
  @backstage/backend-tasks                              0.5.2
  @backstage/catalog-client                             1.4.1
  @backstage/catalog-model                              1.3.0
  @backstage/cli-common                                 0.1.12
  @backstage/cli-node                                   0.1.0
  @backstage/cli                                        0.22.7
  @backstage/config-loader                              1.3.0
  @backstage/config                                     1.0.7
  @backstage/core-app-api                               1.8.0
  @backstage/core-components                            0.13.1
  @backstage/core-plugin-api                            1.5.1
  @backstage/dev-utils                                  1.0.15
  @backstage/errors                                     1.1.5
  @backstage/eslint-plugin                              0.1.3
  @backstage/integration-aws-node                       0.1.3
  @backstage/integration-react                          1.1.13
  @backstage/integration                                1.4.5
  @backstage/plugin-api-docs                            0.9.3
  @backstage/plugin-app-backend                         0.3.45
  @backstage/plugin-auth-backend                        0.18.3
  @backstage/plugin-auth-node                           0.2.14
  @backstage/plugin-catalog-backend-module-github       0.3.0
  @backstage/plugin-catalog-backend                     1.9.1
  @backstage/plugin-catalog-common                      1.0.13
  @backstage/plugin-catalog-graph                       0.2.30
  @backstage/plugin-catalog-import                      0.9.8
  @backstage/plugin-catalog-node                        1.3.6
  @backstage/plugin-catalog-react                       1.6.0
  @backstage/plugin-catalog                             1.11.0
  @backstage/plugin-events-node                         0.2.6
  @backstage/plugin-github-actions                      0.5.18
  @backstage/plugin-graphiql                            0.2.50
  @backstage/plugin-org                                 0.6.8
  @backstage/plugin-permission-backend                  0.5.20
  @backstage/plugin-permission-common                   0.7.5
  @backstage/plugin-permission-node                     0.7.8
  @backstage/plugin-permission-react                    0.4.12
  @backstage/plugin-proxy-backend                       0.2.39
  @backstage/plugin-scaffolder-backend                  1.14.0
  @backstage/plugin-scaffolder-common                   1.3.0
  @backstage/plugin-scaffolder-node                     0.1.3
  @backstage/plugin-scaffolder-react                    1.4.0
  @backstage/plugin-scaffolder                          1.13.1
  @backstage/plugin-search-backend-module-catalog       0.1.1
  @backstage/plugin-search-backend-module-pg            0.5.6
  @backstage/plugin-search-backend-module-techdocs      0.1.1
  @backstage/plugin-search-backend-node                 1.2.1
  @backstage/plugin-search-backend                      1.3.1
  @backstage/plugin-search-common                       1.2.3
  @backstage/plugin-search-react                        1.6.0
  @backstage/plugin-search                              1.3.0
  @backstage/plugin-tech-insights-backend-module-jsonfc 0.1.29
  @backstage/plugin-tech-insights-backend               0.5.11
  @backstage/plugin-tech-insights-common                0.2.10
  @backstage/plugin-tech-insights-node                  0.4.3
  @backstage/plugin-tech-insights                       0.3.10
  @backstage/plugin-techdocs-backend                    1.6.2
  @backstage/plugin-techdocs-module-addons-contrib      1.0.13
  @backstage/plugin-techdocs-node                       1.7.1
  @backstage/plugin-techdocs-react                      1.1.6
  @backstage/plugin-techdocs                            1.6.2
  @backstage/plugin-user-settings                       0.7.3
  @backstage/release-manifests                          0.0.9
  @backstage/test-utils                                 1.3.1
  @backstage/theme                                      0.2.19, 0.3.0
  @backstage/types                                      1.0.2
  @backstage/version-bridge                             1.0.4
```

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else
