### ISSUE TITLE
🐛 Bug Report: k8s-plugin doesn't show up the resources

### ISSUE THREAD

**Issue by jihed** [backstage/backstage#18246]
### 📜 Description

I configured the k8s-plugin with my EKS clusters. When, I check my component, I don't see my pods and got an empty page. I follow up the documentation and when I run the curl from the [troubleshooting](https://backstage.io/docs/features/kubernetes/troubleshooting), I got response for my curl command. 
```
{
  "items": [
    {
      "cluster": {
        "name": "ex-autoscaling-abis"
      },
      "podMetrics": [],
      "resources": [
        {
          "type": "pods",
          "resources": [
            {
              "metadata": {
                "name": "annotations-demo",
                "namespace": "default",
                "uid": "dc4d4711-14cf-4411-84da-30615e955d68",
                "resourceVersion": "1841668",
                "creationTimestamp": "2023-06-14T01:06:55Z",
                "labels": {
                  "backstage.io/kubernetes-id": "Pods"
                },
                "managedFields": [
                  {
                    "manager": "kubectl-create",
                    "operation": "Update",
                    "apiVersion": "v1",
                    "time": "2023-06-14T01:06:54Z",
                    "fieldsType": "FieldsV1",
                    "fieldsV1": {
                      "f:metadata": {
                        "f:labels": {
                          ".": {},
                          "f:backstage.io/kubernetes-id": {}
                        }
                      },
                      "f:spec": {
                        "f:containers": {
                          "k:{\"name\":\"nginx\"}": {
                            ".": {},
                            "f:image": {},
                            "f:imagePullPolicy": {},
                            "f:name": {},
                            "f:ports": {
                              ".": {},
                              "k:{\"containerPort\":80,\"protocol\":\"TCP\"}": {
                                ".": {},
                                "f:containerPort": {},
                                "f:protocol": {}
                              }
                            },
                            "f:resources": {},
                            "f:terminationMessagePath": {},
                            "f:terminationMessagePolicy": {}
                          }
                        },
                        "f:dnsPolicy": {},
                        "f:enableServiceLinks": {},
                        "f:restartPolicy": {},
                        "f:schedulerName": {},
                        "f:securityContext": {},
                        "f:terminationGracePeriodSeconds": {}
                      }
                    }
                  },
                  {
                    "manager": "kubelet",
                    "operation": "Update",
                    "apiVersion": "v1",
                    "time": "2023-06-14T01:06:56Z",
                    "fieldsType": "FieldsV1",
                    "fieldsV1": {
                      "f:status": {
                        "f:conditions": {
                          "k:{\"type\":\"ContainersReady\"}": {
                            ".": {},
                            "f:lastProbeTime": {},
                            "f:lastTransitionTime": {},
                            "f:status": {},
                            "f:type": {}
                          },
                          "k:{\"type\":\"Initialized\"}": {
                            ".": {},
                            "f:lastProbeTime": {},
                            "f:lastTransitionTime": {},
                            "f:status": {},
                            "f:type": {}
                          },
                          "k:{\"type\":\"Ready\"}": {
                            ".": {},
                            "f:lastProbeTime": {},
                            "f:lastTransitionTime": {},
                            "f:status": {},
                            "f:type": {}
                          }
                        },
                        "f:containerStatuses": {},
                        "f:hostIP": {},
                        "f:phase": {},
                        "f:podIP": {},
                        "f:podIPs": {
                          ".": {},
                          "k:{\"ip\":\"10.0.31.92\"}": {
                            ".": {},
                            "f:ip": {}
                          }
                        },
                        "f:startTime": {}
                      }
                    },
                    "subresource": "status"
                  }
                ]
              },
              "spec": {
                "volumes": [
                  {
                    "name": "kube-api-access-vgdlg",
                    "projected": {
                      "sources": [
                        {
                          "serviceAccountToken": {
                            "expirationSeconds": 3607,
                            "path": "token"
                          }
                        },
                        {
                          "configMap": {
                            "name": "kube-root-ca.crt",
                            "items": [
                              {
                                "key": "ca.crt",
                                "path": "ca.crt"
                              }
                            ]
                          }
                        },
                        {
                          "downwardAPI": {
                            "items": [
                              {
                                "path": "namespace",
                                "fieldRef": {
                                  "apiVersion": "v1",
                                  "fieldPath": "metadata.namespace"
                                }
                              }
                            ]
                          }
                        }
                      ],
                      "defaultMode": 420
                    }
                  }
                ],
                "containers": [
                  {
                    "name": "nginx",
                    "image": "nginx:1.14.2",
                    "ports": [
                      {
                        "containerPort": 80,
                        "protocol": "TCP"
                      }
                    ],
                    "resources": {},
                    "volumeMounts": [
                      {
                        "name": "kube-api-access-vgdlg",
                        "readOnly": true,
                        "mountPath": "/var/run/secrets/kubernetes.io/serviceaccount"
                      }
                    ],
                    "terminationMessagePath": "/dev/termination-log",
                    "terminationMessagePolicy": "File",
                    "imagePullPolicy": "IfNotPresent"
                  }
                ],
                "restartPolicy": "Always",
                "terminationGracePeriodSeconds": 30,
                "dnsPolicy": "ClusterFirst",
                "serviceAccountName": "default",
                "serviceAccount": "default",
                "nodeName": "ip-10-0-26-102.eu-west-1.compute.internal",
                "securityContext": {},
                "schedulerName": "default-scheduler",
                "tolerations": [
                  {
                    "key": "node.kubernetes.io/not-ready",
                    "operator": "Exists",
                    "effect": "NoExecute",
                    "tolerationSeconds": 300
                  },
                  {
                    "key": "node.kubernetes.io/unreachable",
                    "operator": "Exists",
                    "effect": "NoExecute",
                    "tolerationSeconds": 300
                  }
                ],
                "priority": 0,
                "enableServiceLinks": true,
                "preemptionPolicy": "PreemptLowerPriority"
              },
              "status": {
                "phase": "Running",
                "conditions": [
                  {
                    "type": "Initialized",
                    "status": "True",
                    "lastProbeTime": null,
                    "lastTransitionTime": "2023-06-14T01:06:55Z"
                  },
                  {
                    "type": "Ready",
                    "status": "True",
                    "lastProbeTime": null,
                    "lastTransitionTime": "2023-06-14T01:06:56Z"
                  },
                  {
                    "type": "ContainersReady",
                    "status": "True",
                    "lastProbeTime": null,
                    "lastTransitionTime": "2023-06-14T01:06:56Z"
                  },
                  {
                    "type": "PodScheduled",
                    "status": "True",
                    "lastProbeTime": null,
                    "lastTransitionTime": "2023-06-14T01:06:55Z"
                  }
                ],
                "hostIP": "10.0.26.102",
                "podIP": "10.0.31.92",
                "podIPs": [
                  {
                    "ip": "10.0.31.92"
                  }
                ],
                "startTime": "2023-06-14T01:06:55Z",
                "containerStatuses": [
                  {
                    "name": "nginx",
                    "state": {
                      "running": {
                        "startedAt": "2023-06-14T01:06:55Z"
                      }
                    },
                    "lastState": {},
                    "ready": true,
                    "restartCount": 0,
                    "image": "docker.io/library/nginx:1.14.2",
                    "imageID": "docker.io/library/nginx@sha256:f7988fb6c02e0ce69257d9bd9cf37ae20a60f1df7563c3a2a6abe24160306b8d",
                    "containerID": "containerd://6ef9272537947b5ae9c1339c30e8772c72573593f6b7957c15e6b5d9f5cc682d",
                    "started": true
                  }
                ],
                "qosClass": "BestEffort"
              }
            }
          ]
        },
        {
          "type": "services",
          "resources": []
        },
        {
          "type": "configmaps",
          "resources": []
        },
        {
          "type": "limitranges",
          "resources": []
        },
        {
          "type": "deployments",
          "resources": []
        },
        {
          "type": "replicasets",
          "resources": []
        },
        {
          "type": "horizontalpodautoscalers",
          "resources": []
        },
        {
          "type": "jobs",
          "resources": []
        },
        {
          "type": "cronjobs",
          "resources": []
        },
        {
          "type": "ingresses",
          "resources": []
        },
        {
          "type": "statefulsets",
          "resources": []
        },
        {
          "type": "daemonsets",
          "resources": []
        }
      ],
      "errors": []
    }
  ]
}```

### 👍 Expected behavior

I see one pod with labels.

### 👎 Actual Behavior with Screenshots

Empty page with this message: 
```
Your Clusters
No resources on any known clusters for Pods
```

### 👟 Reproduction steps

https://backstage.io/docs/features/kubernetes/authentication

### 📃 Provide the context for the Bug.

[catalog-info](https://github.com/jihed/tutorial/blob/master/catalog-info.yaml)

```apiVersion: v1
kind: Pod
metadata:
  name: annotations-demo
  labels:
    backstage.io/kubernetes-id: Pods
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80```

### 🖥️ Your Environment

arn backstage-cli info
yarn run v1.22.19
$ /Users/mselj/idp/backstage/node_modules/.bin/backstage-cli info
OS:   Darwin 22.5.0 - darwin/x64
node: v18.16.0
yarn: 1.22.19
cli:  0.22.7 (installed)
backstage:  1.14.0

Dependencies:
  @backstage/app-defaults                          1.3.1
  @backstage/backend-app-api                       0.4.3
  @backstage/backend-common                        0.18.5
  @backstage/backend-dev-utils                     0.1.1
  @backstage/backend-plugin-api                    0.5.2
  @backstage/backend-tasks                         0.5.2
  @backstage/catalog-client                        1.4.1
  @backstage/catalog-model                         1.3.0
  @backstage/cli-common                            0.1.12
  @backstage/cli-node                              0.1.0
  @backstage/cli                                   0.22.7
  @backstage/config-loader                         1.3.0
  @backstage/config                                1.0.7
  @backstage/core-app-api                          1.8.0
  @backstage/core-components                       0.13.1
  @backstage/core-plugin-api                       1.5.1
  @backstage/errors                                1.1.5
  @backstage/eslint-plugin                         0.1.3
  @backstage/integration-aws-node                  0.1.3
  @backstage/integration-react                     1.1.13
  @backstage/integration                           1.4.5
  @backstage/plugin-api-docs                       0.9.4
  @backstage/plugin-app-backend                    0.3.45
  @backstage/plugin-auth-backend                   0.18.3
  @backstage/plugin-auth-node                      0.2.14
  @backstage/plugin-catalog-backend                1.9.1
  @backstage/plugin-catalog-common                 1.0.13
  @backstage/plugin-catalog-graph                  0.2.30
  @backstage/plugin-catalog-import                 0.9.8
  @backstage/plugin-catalog-node                   1.3.6
  @backstage/plugin-catalog-react                  1.6.0
  @backstage/plugin-catalog                        1.11.1
  @backstage/plugin-github-actions                 0.5.18
  @backstage/plugin-kubernetes-backend             0.11.0
  @backstage/plugin-kubernetes-common              0.6.3
  @backstage/plugin-kubernetes                     0.9.1
  @backstage/plugin-org                            0.6.8
  @backstage/plugin-permission-common              0.7.5
  @backstage/plugin-permission-node                0.7.8
  @backstage/plugin-permission-react               0.4.12
  @backstage/plugin-proxy-backend                  0.2.39
  @backstage/plugin-scaffolder-backend             1.14.0
  @backstage/plugin-scaffolder-common              1.3.0
  @backstage/plugin-scaffolder-node                0.1.3
  @backstage/plugin-scaffolder-react               1.4.0
  @backstage/plugin-scaffolder                     1.13.1
  @backstage/plugin-search-backend-module-catalog  0.1.1
  @backstage/plugin-search-backend-module-pg       0.5.6
  @backstage/plugin-search-backend-module-techdocs 0.1.1
  @backstage/plugin-search-backend-node            1.2.1
  @backstage/plugin-search-backend                 1.3.1
  @backstage/plugin-search-common                  1.2.3
  @backstage/plugin-search-react                   1.6.1
  @backstage/plugin-search                         1.3.1
  @backstage/plugin-tech-radar                     0.6.4
  @backstage/plugin-techdocs-backend               1.6.2
  @backstage/plugin-techdocs-module-addons-contrib 1.0.13
  @backstage/plugin-techdocs-node                  1.7.1
  @backstage/plugin-techdocs-react                 1.1.6
  @backstage/plugin-techdocs                       1.6.3
  @backstage/plugin-user-settings                  0.7.3
  @backstage/release-manifests                     0.0.9
  @backstage/test-utils                            1.3.1
  @backstage/theme                                 0.3.0
  @backstage/types                                 1.0.2
  @backstage/version-bridge                        1.0.4
✨  Done in 2.11s.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by jamieklassen** [comment]
Can we get a few more details to see about reproducing this? I'm particularly interested in seeing the configuration on your catalog entity.
* I'm not able to read your catalog-info link -- maybe `jihed/tutorial` is a private repository?
* Can you post a screenshot of the exact page you're looking at?

One thing that stands out to me based on the curl response (and k8s manifest) you shared is that you do seem to have a correctly-labeled Pod, but it is ["naked"](https://kubernetes.io/docs/concepts/configuration/overview/#naked-pods-vs-replicasets-deployments-and-jobs) -- i.e., not managed by a higher-level workload resource like a Deployment/Job/DaemonSet/etc. You can see here:

https://github.com/backstage/backstage/blob/77d59204854e92ff23209b90737f87b677cc9f38/plugins/kubernetes/src/components/Cluster/Cluster.tsx#L137-L168

that, within a cluster, an accordion will only be shown for particular types like custom resources, Deployments, StatefulSets, Ingresses, Services and CronJobs. So an empty cluster accordion wouldn't surprise me here. That said, from the available information (excepting some issue with your catalog config) I still would expect to see a cluster summary mentioning your single pod:

https://github.com/backstage/backstage/blob/77d59204854e92ff23209b90737f87b677cc9f38/plugins/kubernetes/src/components/Cluster/Cluster.tsx#L92

so we'll have to do a bit more digging.

**Comment by jihed** [comment]
Thanks for your reply,

Here is my catalog-info.yaml

```
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "allpods"
  annotations:
    backstage.io/kubernetes-label-selector: demo
spec:
  type: service
  owner: user:guest
  lifecycle: experimental
``` 

To reproduce, I just follow up the documentation to setup k8s-plugin: 1/ I added frontend and backend plugin [steps](https://backstage.io/docs/features/kubernetes/installation) 2/ [I configured](https://backstage.io/docs/features/kubernetes/configuration) 3/ I used aws authentication based on this [link](https://backstage.io/docs/features/kubernetes/authentication): 
```
app:
  title: Your Backstage App
  baseUrl: http://localhost:3000

organization:
  name: Your Company

backend:
  baseUrl: http://localhost:7007
  listen:
    port: 7007
    # Uncomment the following host directive to bind to specific interfaces
    # host: 127.0.0.1
  csp:
    connect-src: ["'self'", "http:", "https:"]
  cors:
    origin: http://localhost:3000
    methods: [GET, HEAD, PATCH, POST, PUT, DELETE]
    credentials: true
  database:
    client: pg
    connection:
      host: ${POSTGRES_HOST}
      port: ${POSTGRES_PORT}
      user: ${POSTGRES_USER}
      password: ${POSTGRES_PASSWORD}
    # client: better-sqlite3
    # connection: ":memory:"
  cache:
    store: memory
  # workingDirectory: /tmp # Use this to configure a working directory for the scaffolder, defaults to the OS temp-dir

integrations:
  github:
    - host: github.com
      token: ${GITHUB_TOKEN_PS}

proxy:

techdocs:
  builder: "local" # Alternatives - 'external'
  generator:
    runIn: "docker" # Alternatives - 'local'
  publisher:
    type: "local" # Alternatives - 'googleGcs' or 'awsS3'. Read documentation for using alternatives.

auth:
  # see https://backstage.io/docs/auth/ to learn about auth providers
  environment: development
  providers:
    github:
      development:
        clientId: ${GITHUB_CLIENT_ID}
        clientSecret: ${GITHUB_CLIENT_SECRET}

scaffolder:

catalog:
  import:
    entityFilename: catalog-info.yaml
    pullRequestBranchName: backstage-integration
  rules:
    - allow: [Component, System, API, Resource, Location]
  locations:
    # Local example data, file locations are relative to the backend process, typically `packages/backend`
    - type: file
      target: ../../examples/entities.yaml

    # Local example template
    - type: file
      target: ../../examples/template/template.yaml
      rules:
        - allow: [Template]

    # Local example organizational data
    - type: file
      target: ../../examples/org.yaml
      rules:
        - allow: [User, Group]


kubernetes:
  serviceLocatorMethod:
    type: "multiTenant"
  clusterLocatorMethods:
    - type: "config"
      clusters:
        - url: ${EKS_CLUSTER_ENDPOINT}
          name: ex-autoscaling-abis
          authProvider: "aws"
          skipTLSVerify: true
          skipMetricsLookup: true

```
This is the screenshot: 
<img width="1782" alt="Screenshot 2023-06-14 at 23 14 10" src="https://github.com/backstage/backstage/assets/273401/916c3312-1832-4dd8-bd94-b2f5a9639a87">

**Comment by jihed** [comment]
I tried to label one deployment and still got an empty page (same one like the above).

```kubectl get deployments.apps --show-labels
NAME                  READY   UP-TO-DATE   AVAILABLE   AGE    LABELS
demo                  1/1     1            1           28s    app=demo,backstage.io/kubernetes-id=Pods```

**Comment by jamieklassen** [comment]
I can't help but notice a discrepancy between the name of the service in your `catalog-info.yaml` -- `Pods` -- and the name of the service in your screenshot -- `allpods`.

Setting that aside, I also see your service has the [`backstage.io/kubernetes-id ` annotation](https://backstage.io/docs/features/kubernetes/configuration/#common-backstageiokubernetes-id-label) set to the value `cluster-1`. Effectively this means that only Kubernetes objects matching the label selector `backstage.io/kubernetes-id=cluster-1` will be considered associated to this service. If you add that label to your pod, I suspect the Kubernetes tab will start showing something different, e.g. using a k8s manifest more like

```yaml
kind: Pod
metadata:
  name: annotations-demo
  labels:
    backstage.io/kubernetes-id: cluster-1
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
```

can you give that a try?
