### ISSUE TITLE
🐛 Bug Report: MicrosoftGraphOrgEntityProvider not able to commit back to Backstage

### ISSUE THREAD

**Issue by grvpandey11** [backstage/backstage#18256]
### 📜 Description

Following the documentation [here](https://backstage.io/docs/integrations/azure/org/)

I am using plugin-catalog-backend-module-msgraph 
MicrosoftGraphOrgEntityProvider is not able to commit back to Backstage

### 👍 Expected behavior

Users should be visible in Backstage from Azure

### 👎 Actual Behavior with Screenshots

Follow the documentation [here](https://backstage.io/docs/integrations/azure/org/)
I am getting below message
```
catalog info Reading msgraph users and groups type=plugin class=MicrosoftGraphOrgEntityProvider taskId=MicrosoftGraphOrgEntityProvider:default:refresh taskInstanceId=xxxxxx
[1] 2023-06-14T13:16:17.216Z catalog info Read users from group membership type=plugin class=MicrosoftGraphOrgEntityProvider taskId=MicrosoftGraphOrgEntityProvider:default:refresh taskInstanceId=xxxxxxx groupCount=1 userCount=7
```

But Users are not getting commited back to backstage

app-config.yaml
```
catalog:
  import:
    entityFilename: catalog-info.yaml
    pullRequestBranchName: backstage-integration
  rules:
    - allow: [Component, Location, Template, System, API, Group, User]
  providers:
    microsoftGraphOrg:
      providerId:
        target: https://graph.microsoft.com/v1.0
        authority: https://login.microsoftonline.com
        tenantId: xxxxxxx
        clientId: xxxxx
        clientSecret: xxxxxxx
        userGroupMember:
          filter: "displayName eq 'xxxxxxx'"
```

catalog.ts
```
import { CatalogBuilder } from '@backstage/plugin-catalog-backend';
import { ScaffolderEntitiesProcessor } from '@backstage/plugin-scaffolder-backend';
import { Router } from 'express';
import { PluginEnvironment } from '../types';
import { GithubOrgEntityProvider } from '@backstage/plugin-catalog-backend-module-github';
import { MicrosoftGraphOrgEntityProvider } from '@backstage/plugin-catalog-backend-module-msgraph';

export default async function createPlugin(
  env: PluginEnvironment,
): Promise<Router> {
  const builder = await CatalogBuilder.create(env);
  // The org URL below needs to match a configured integrations.github entry
  // specified in your app-config.
  builder.addEntityProvider(
    MicrosoftGraphOrgEntityProvider.fromConfig(env.config, {
      logger: env.logger,
      schedule: env.scheduler.createScheduledTaskRunner({
        frequency: { hours: 1 },
        timeout: { minutes: 50 },
      }),
    }),
  );
  builder.addEntityProvider(
    GithubOrgEntityProvider.fromConfig(env.config, {
      id: 'production',
      orgUrl: 'xxxxxxx',
      logger: env.logger,
      schedule: env.scheduler.createScheduledTaskRunner({
        frequency: { minutes: 60 },
        timeout: { minutes: 15 },
      }),
    }),
  );
  builder.addProcessor(new ScaffolderEntitiesProcessor());
  const { processingEngine, router } = await builder.build();
  await processingEngine.start();
  return router;
}
```

I am using App Registration with below permissions

- GroupMember.Read.All (Application)
- User.Read.All (Application)

### 👟 Reproduction steps

1. yarn add --cwd packages/backend @backstage/plugin-catalog-backend-module-msgraph
2. Make below changes in app-config
```
catalog:
  import:
    entityFilename: catalog-info.yaml
    pullRequestBranchName: backstage-integration
  rules:
    - allow: [Component, Location, Template, System, API, Group, User]
  providers:
    microsoftGraphOrg:
      providerId:
        target: https://graph.microsoft.com/v1.0
        authority: https://login.microsoftonline.com
        tenantId: xxxxxxx
        clientId: xxxxx
        clientSecret: xxxxxxx
        userGroupMember:
          filter: "displayName eq 'xxxxxxx'"
```
3. Add below in catalog.ts
```
  builder.addEntityProvider(
    MicrosoftGraphOrgEntityProvider.fromConfig(env.config, {
      logger: env.logger,
      schedule: env.scheduler.createScheduledTaskRunner({
        frequency: { hours: 1 },
        timeout: { minutes: 50 },
        initialDelay: { seconds: 15 },
      }),
    }),
  );
```

### 🖥️ Your Environment

```
node: v18.16.0
yarn: 1.22.19
cli:  0.22.7 (installed)
backstage:  1.14.2

Dependencies:
  @backstage/app-defaults                               1.3.1
  @backstage/backend-app-api                            0.4.3
  @backstage/backend-common                             0.18.5
  @backstage/backend-dev-utils                          0.1.1
  @backstage/backend-plugin-api                         0.5.2
  @backstage/backend-tasks                              0.5.2
  @backstage/catalog-client                             1.4.1
  @backstage/catalog-model                              1.3.0
  @backstage/cli-common                                 0.1.12
  @backstage/cli-node                                   0.1.0
  @backstage/cli                                        0.22.7
  @backstage/config-loader                              1.3.0
  @backstage/config                                     1.0.7
  @backstage/core-app-api                               1.8.0
  @backstage/core-components                            0.12.5, 0.13.1
  @backstage/core-plugin-api                            1.5.1
  @backstage/dev-utils                                  1.0.15
  @backstage/errors                                     1.1.5
  @backstage/eslint-plugin                              0.1.3
  @backstage/integration-aws-node                       0.1.3
  @backstage/integration-react                          1.1.13
  @backstage/integration                                1.4.5
  @backstage/plugin-adr-backend                         0.3.3
  @backstage/plugin-adr-common                          0.2.9
  @backstage/plugin-adr                                 0.6.1
  @backstage/plugin-api-docs                            0.9.4
  @backstage/plugin-app-backend                         0.3.45
  @backstage/plugin-auth-backend                        0.18.3
  @backstage/plugin-auth-node                           0.2.14
  @backstage/plugin-catalog-backend-module-github       0.3.0
  @backstage/plugin-catalog-backend-module-msgraph      0.5.4
  @backstage/plugin-catalog-backend                     1.9.1
  @backstage/plugin-catalog-common                      1.0.13
  @backstage/plugin-catalog-graph                       0.2.30
  @backstage/plugin-catalog-import                      0.9.8
  @backstage/plugin-catalog-node                        1.3.6
  @backstage/plugin-catalog-react                       1.6.0
  @backstage/plugin-catalog                             1.11.1
  @backstage/plugin-entity-feedback-backend             0.1.3
  @backstage/plugin-entity-feedback-common              0.1.1
  @backstage/plugin-entity-feedback                     0.2.1
  @backstage/plugin-events-node                         0.2.6
  @backstage/plugin-github-actions                      0.5.18
  @backstage/plugin-github-deployments                  0.1.49
  @backstage/plugin-github-pull-requests-board          0.1.12
  @backstage/plugin-home                                0.5.2
  @backstage/plugin-org                                 0.6.8
  @backstage/plugin-permission-common                   0.7.5
  @backstage/plugin-permission-node                     0.7.8
  @backstage/plugin-permission-react                    0.4.12
  @backstage/plugin-proxy-backend                       0.2.39
  @backstage/plugin-scaffolder-backend                  1.14.0
  @backstage/plugin-scaffolder-common                   1.3.0
  @backstage/plugin-scaffolder-node                     0.1.3
  @backstage/plugin-scaffolder-react                    1.4.0
  @backstage/plugin-scaffolder                          1.13.1
  @backstage/plugin-search-backend-module-catalog       0.1.1
  @backstage/plugin-search-backend-module-pg            0.5.6
  @backstage/plugin-search-backend-module-techdocs      0.1.1
  @backstage/plugin-search-backend-node                 1.2.1
  @backstage/plugin-search-backend                      1.3.1
  @backstage/plugin-search-common                       1.2.3
  @backstage/plugin-search-react                        1.6.1
  @backstage/plugin-search                              1.3.1
  @backstage/plugin-sentry                              0.5.3
  @backstage/plugin-stack-overflow-backend              0.2.1
  @backstage/plugin-stack-overflow                      0.1.16
  @backstage/plugin-tech-insights-backend-module-jsonfc 0.1.29
  @backstage/plugin-tech-insights-backend               0.5.11
  @backstage/plugin-tech-insights-common                0.2.10
  @backstage/plugin-tech-insights-node                  0.4.3
  @backstage/plugin-tech-insights                       0.3.10
  @backstage/plugin-tech-radar                          0.6.4
  @backstage/plugin-techdocs-backend                    1.6.2
  @backstage/plugin-techdocs-module-addons-contrib      1.0.13
  @backstage/plugin-techdocs-node                       1.7.1
  @backstage/plugin-techdocs-react                      1.1.6
  @backstage/plugin-techdocs                            1.6.3
  @backstage/plugin-user-settings                       0.7.3
  @backstage/release-manifests                          0.0.9
  @backstage/test-utils                                 1.3.1
  @backstage/theme                                      0.2.19, 0.3.0
  @backstage/types                                      1.0.2
  @backstage/version-bridge                             1.0.4
```

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, I don't have time to work on this right now
