### ISSUE TITLE
🚀 Feature: MissingAnnotationEmptyState should allow customized entity template

### ISSUE THREAD

**Issue by bforbis** [backstage/backstage#18264]
### 🔖 Feature description

Update the COMPONENT_YAML_TEMPLATE for `<MissingAnnotationEmptyState>` so that it can set the Entity kind and type based on the entity that is currently being viewed.

### 🎤 Context

When utilizing this react component to alert the user that they should add an annotation, it uses a baked in template to represent the entity that should be modified.

```
const COMPONENT_YAML_TEMPLATE = `apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: example
  description: example.com
  annotations:
    ANNOTATION: value
spec:
  type: website
  lifecycle: production
  owner: user:guest`;
```

This ends up looking odd if you are viewing a page that is not a component of type website, and can confuse or mislead users.

<img width="673" alt="image" src="https://github.com/backstage/backstage/assets/16994570/4d5f4892-2cd4-42a7-9b86-a63eaca8bda0">

### ✌️ Possible Implementation

A few options:

1. Allow for just entity kind and type to be optionally passed in and override the template
2. Base the template dynamically on the entity being viewed using the `useEntity()` hook

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!
