### ISSUE TITLE
🚀 Feature: System and Component entities can have many-to-many relationships with other Systems and Components

### ISSUE THREAD

**Issue by rampadc** [backstage/backstage#18268]
### 🔖 Feature description

In Component and System's specs, we can add string arrays of `partOf` and `hasParts` to allow a single component/system to be part of multiple components/systems.

Examples:

```yaml
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: system-name
  description: Description of system-name
spec:
  owner: group:group-name
  domain: domain-name
  partOf:
    - component:default/test
    - component:default/test2
    - system:default/test-system
    - system:default/test-system2
  hasParts:
    - component:default/test3
    - component:default/test4
```

### 🎤 Context

I have a software component that is used in multiple systems. Similarly, multiple systems that uses multiple of the same components. The current YAML does not allow for this many-to-many relationship.

### ✌️ Possible Implementation

No implementations in Backstage. A custom processor extension plugin can be built to enable this functionality, or a part of the Backstage core itself.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!
