### ISSUE TITLE
🚀 Feature: Optionally specify LDAP filters as YAML

### ISSUE THREAD

**Issue by cowboyd** [backstage/backstage#18270]
### 🔖 Feature description

Have the option to express LDAP filters used by the LDAP entity provider as YAML rather than a single string. So for example, the following LDAP provider config:

```yaml
ldap:
  providers:
    - target: ldaps://ds.example.net
      bind:
        dn: uid=ldap-reader-user,ou=people,ou=example,dc=example,dc=net
        secret: ${LDAP_SECRET}
      groups:
        dn: ou=access,ou=groups,ou=example,dc=example,dc=net
        options:
          filter: (&(objectClass=group)(!(groupType=email))(|(cn=devx-users)(cn=users-preview)(cn=exlib-users-bb)))
```

Could be rewritten as

```yaml
ldap:
  providers:
    - target: ldaps://ds.example.net
      bind:
        dn: uid=ldap-reader-user,ou=people,ou=example,dc=example,dc=net
        secret: ${LDAP_SECRET}
      groups:
        dn: ou=access,ou=groups,ou=example,dc=example,dc=net
        options:
          filter:
            and:
              - objectClass=group
              - not: {groupType: email }
              - or:
                - cn: dev-users
                - cn: users-preview
                - cn: exlib-users-bb
```

If the provider sees a string in its config, then it uses it as the ldap filter, otherwise, it uses the data structure to build the filter before passing it in.

### 🎤 Context

Organizations with very large, very mature LDAP installations may want to be very selective about which entities they ingest from their LDAP directory. As a result, the `filter` parameter provided by the LDAP entity provider config can very quickly become unwieldy. The snippet I've shown above is actually tame by comparison to some of the real world scenarios we've seen.

For example Let's say that we wanted to add another group to ingest to the list. If we have to first mentally parse the filter expression to figure out where to insert it, and then add our new expression hoping that we balance it correctly in the tree. It becomes exponentially more difficult as the size and complexity of the expression increases.

By contrast, adding another group name to select is trivial if the tree represented by the filter expression is reflected directly in the configuration. It's as simple as adding another name to the list.

### ✌️ Possible Implementation

The `ldapjs` library already has a [builder syntax](http://ldapjs.org/filters.html) for programmatically constructing filters and then serializing them into a filter string. It seems to me the simplest implementation would be if the `filter` parameter could take either a string or filter structure. If it's a string, that's the current behavior, and it just passes the string directly. Otherwise, if it's a record, it will use the ldapjs filter builders to construct the filter and generate the string.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by freben** [comment]
I don't feel it's very tempting to invent a custom format for this. I'm envisioning that this query format is copy pasted across systems anyway, where it's tested out for sanity elsewhere etc.

Are these white space insensitive? If so, you could use yaml block strings.

```yaml
options:
  filter: >
    &
       ( objectClass = group )
       ! ( groupType = email )
       |
          ( cn = dev-users )
          ...
```

**Comment by cowboyd** [comment]
Unfortunately not https://runkit.com/cowboyd/ldap-filters-are-one-line-only

**Comment by freben** [comment]
Maybe we could be helpful and strip whitespace? 🤔

**Comment by cowboyd** [comment]
Incidentally, this would be another use-case for the YAML interpreter we demo'd last October. In that case, we were using it to extend the UI safely and without JavaScript, but here it would allow folks to extend their own configuration syntax without any need to change backstage itself.

```yaml
$import:
  makeLdapFilter: ./config-helpers.yaml
ldap:
  providers:
    - target: ldaps://ds.example.net
      bind:
        dn: uid=ldap-reader-user,ou=people,ou=example,dc=example,dc=net
        secret: ${LDAP_SECRET}
      groups:
        dn: ou=access,ou=groups,ou=example,dc=example,dc=net
        options:
          filter:
            $makeLdapFilter:
              and:
              - objectClass=group
              - not: {groupType: email }
              - or:
                - cn: dev-users
                - cn: users-preview
                - cn: exlib-users-bb
  ```
