### ISSUE TITLE
🐛 Bug Report: PG ssl connect issue

### ISSUE THREAD

**Issue by gongshishao** [backstage/backstage#18275]
### 📜 Description

I was trying to access PG in cloud server while backstage instance deployed.
refer to this doc: [https://backstage.io/docs/tutorials/switching-sqlite-postgres/#override-default-postgresql-database-pool-configuration](url)
but get stuck with it.

I try with connection string(which base on **pg-connecting-string** parser), same error

### 👍 Expected behavior

PG connected successful and initial database successful

### 👎 Actual Behavior with Screenshots

<img width="1735" alt="截屏2023-06-15 18 15 39" src="https://github.com/backstage/backstage/assets/43381611/5af98843-06ae-4829-b684-2788fe840b54">

### 👟 Reproduction steps

yarn dev, database config as below

```
 database:
    client: pg
    # connection: 'postgresql:root:Root123@$localhost:5432/global?ssl=true&sslkey=/Users/renhuazhang/ssl/client.key&sslrootcert=/Users/renhuazhang/ssl/ca.crt&sslcert=/Users/renhuazhang/ssl/newclient.crt'
    connection:
      host: localhost
      port: 5432
      user: root
      password: Root123
      ssl:
        ca:
          $file: /Users/renhuazhang/ssl/ca.crt
        cert:
          $file: /Users/renhuazhang/ssl/client.crt
        key:
          $file: /Users/renhuazhang/ssl/client.key
```

### 🖥️ Your Environment

```
OS:   Darwin 22.3.0 - darwin/x64
node: v16.14.2
yarn: 1.22.19
cli:  0.22.7 (installed)
backstage:  1.11.0

Dependencies:
  @backstage/app-defaults                                   1.3.1
  @backstage/backend-app-api                                0.4.3
  @backstage/backend-common                                 0.15.2, 0.18.5
  @backstage/backend-dev-utils                              0.1.1
  @backstage/backend-plugin-api                             0.5.2
  @backstage/backend-tasks                                  0.4.3, 0.5.2
  @backstage/catalog-client                                 1.4.1
  @backstage/catalog-model                                  1.3.0
  @backstage/cli-common                                     0.1.12
  @backstage/cli-node                                       0.1.0
  @backstage/cli                                            0.22.7
  @backstage/config-loader                                  1.3.0
  @backstage/config                                         1.0.7
  @backstage/core-app-api                                   1.8.0
  @backstage/core-components                                0.12.5, 0.13.1
  @backstage/core-plugin-api                                1.5.1
  @backstage/errors                                         1.1.5
  @backstage/eslint-plugin                                  0.1.3
  @backstage/integration-aws-node                           0.1.3
  @backstage/integration-react                              1.1.13
  @backstage/integration                                    1.4.5
  @backstage/plugin-api-docs                                0.9.0
  @backstage/plugin-app-backend                             0.3.45
  @backstage/plugin-auth-backend                            0.18.3
  @backstage/plugin-auth-node                               0.2.14
  @backstage/plugin-catalog-backend-module-bitbucket-server 0.1.10
  @backstage/plugin-catalog-backend                         1.9.1
  @backstage/plugin-catalog-common                          1.0.13
  @backstage/plugin-catalog-graph                           0.2.30
  @backstage/plugin-catalog-import                          0.9.8
  @backstage/plugin-catalog-node                            1.3.6
  @backstage/plugin-catalog-react                           1.6.0
  @backstage/plugin-catalog                                 1.11.1
  @backstage/plugin-cost-insights-common                    0.1.1
  @backstage/plugin-cost-insights                           0.12.7
  @backstage/plugin-github-actions                          0.5.18
  @backstage/plugin-jenkins-backend                         0.1.34
  @backstage/plugin-jenkins-common                          0.1.15
  @backstage/plugin-jenkins                                 0.7.16
  @backstage/plugin-org                                     0.6.8
  @backstage/plugin-permission-backend                      0.5.20
  @backstage/plugin-permission-common                       0.7.5
  @backstage/plugin-permission-node                         0.7.8
  @backstage/plugin-permission-react                        0.4.12
  @backstage/plugin-proxy-backend                           0.2.39
  @backstage/plugin-scaffolder-backend                      1.14.0
  @backstage/plugin-scaffolder-common                       1.3.0
  @backstage/plugin-scaffolder-node                         0.1.3
  @backstage/plugin-scaffolder-react                        1.4.0
  @backstage/plugin-scaffolder                              1.13.1
  @backstage/plugin-search-backend-module-catalog           0.1.1
  @backstage/plugin-search-backend-module-pg                0.5.6
  @backstage/plugin-search-backend-module-techdocs          0.1.1
  @backstage/plugin-search-backend-node                     1.2.1
  @backstage/plugin-search-backend                          1.3.1
  @backstage/plugin-search-common                           1.2.3
  @backstage/plugin-search-react                            1.6.1
  @backstage/plugin-search                                  1.3.1
  @backstage/plugin-tech-radar                              0.6.4
  @backstage/plugin-techdocs-backend                        1.6.2
  @backstage/plugin-techdocs-module-addons-contrib          1.0.13
  @backstage/plugin-techdocs-node                           1.7.1
  @backstage/plugin-techdocs-react                          1.1.6
  @backstage/plugin-techdocs                                1.6.3
  @backstage/plugin-user-settings                           0.7.3
  @backstage/release-manifests                              0.0.9
  @backstage/test-utils                                     1.3.1
  @backstage/theme                                          0.2.19, 0.3.0
  @backstage/types                                          1.0.2
  @backstage/version-bridge                                 1.0.4
```

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by craigtracey** [comment]
Hi @gongshishao,

This does not appear to be a bug in Backstage, but, rather, an issue with the certificates you are using when connecting to the postgres database. Specifically, the error is indicating that the hostname (in your case `localhost`) is not found within the cert's Common Name (CN) or Subject Alt Name (SAN) fields. Therefore, the connection cannot be validated as secure.

To test this correctly, you will need create a new certificate that matches the hostname you intend to use to connect to postgres. [This](https://raymii.org/s/tutorials/OpenSSL_generate_self_signed_cert_with_Subject_Alternative_name_oneliner.html) provides a good reference for how you can create a cert with a SAN.

If you would like to test this without creating a new certificate, I believe that you have two options:
- First, since you appear to have a certificate with a CN of `cd`, you should be able to add an entry to your `/etc/hosts` file for hostname `cd`. Should look something like:
`127.0.0.1    cd`
Then you would need to modify your Backstage database connection string to use `cd` instead of `localhost`.
- The second option is **INSECURE, and should not be used for production use cases**, but I believe that you should be able to set an environment variable of `NODE_TLS_REJECT_UNAUTHORIZED=0` to workaround this certificate problem. This will circumvent TLS certificate validation, which may help you test this in a development environment but, again, is **insecure**.

**Comment by gongshishao** [comment]
@craigtracey Hi, thank you so much for provide the solutions. And option 1 really does work !
But it's only works for me at default database mode, which means will create many database by plugin.
Test works from my local machine, yaml config as below:
```
  database:
    client: pg
    connection:
      host: cd
      port: 5432
      user: root
      password: Root123
      ssl:
        ca:
          $file: /Users/renhuazhang/ssl/ca.crt
        cert:
          $file: /Users/renhuazhang/ssl/client.crt
        key:
          $file: /Users/renhuazhang/ssl/client.key
```

But as for my company's DB policy, we need to use schema mode in PG, i try as doc mentioned but seems not mentioned that much [https://backstage.io/docs/tutorials/switching-sqlite-postgres/#using-a-single-database](url)
**could'u help to provide any suggestions on this, thanks again:**
```
database:
    client: pg
    pluginDivisionMode: schema
    connection: 'postgresql://${POSTGRES_USERNAME}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}?${PG_CONNECTION_STRING}'
    plugin:
      auth:
        connection: 'postgresql://${POSTGRES_USERNAME}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}?${PG_CONNECTION_STRING}'
      catalog:
        connection: 'postgresql://${POSTGRES_USERNAME}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}?${PG_CONNECTION_STRING}'
      scaffolder:
        connection: 'postgresql://${POSTGRES_USERNAME}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}?${PG_CONNECTION_STRING}'
      search:
        connection: 'postgresql://${POSTGRES_USERNAME}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}?${PG_CONNECTION_STRING}'
      app:
        connection: 'postgresql://${POSTGRES_USERNAME}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}?${PG_CONNECTION_STRING}'
```
