### ISSUE TITLE
🐛 Bug Report: Gitlab Merge Request empty

### ISSUE THREAD

**Issue by nlamirault** [backstage/backstage#18283]
### 📜 Description

I create a new system from a custom template. Gitlab Merge Request is created, but commit is empty.

Template:

```yaml
---
apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: system-template
  title: New System
  description: Create a new System
  tags:
    - system
spec:
  owner: group:team-infra
  type: system

  parameters:
    - title: Provide System simple information
      required:
        - system
        - description
        - owner
        - domain
        - lifecycle
      properties:
        system:
          title: Name
          type: string
          description: Unique name of the System
          ui:field: EntityNamePicker
          ui:autofocus: true

        description:
          title: Description
          type: string
          description: Help others understand what this website is for.

        owner:
          title: Owner
          type: string
          description: Owner of the component
          ui:field: OwnerPicker
          ui:options:
            allowedKinds:
              - Group

        domain:
          title: Domain
          type: string
          description: Domain of the System
          ui:field: EntityPicker
          ui:options:
            allowedKinds:
              - Domain
            defaultKind: Domain

        lifecycle:
          title: Lifecycle
          description: 'Application lifecycle'
          type: string
          default: experimental
          enum:
            - deprecated
            - experimental
            - production

        dryRun:
          title: Only perform a dry run, don't publish anything
          type: boolean
          default: false

  steps:
    - id: log-message
      name: Log Message
      action: debug:log
      input:
        message: Creating system ${{ parameters.system }}

    - id: fetch-template
      name: Fetch System Template
      action: fetch:template
      if: ${{ parameters.dryRun == false }}
      input:
        url: ./skeleton
        values:
          system: ${{ parameters.system }}
          description: ${{ parameters.description }}
          owner: ${{ parameters.owner }}
          domain: ${{ parameters.domain }}
          lifecycle: ${{ parameters.lifecycle }}

    - id: publish
      name: Publish
      action: publish:gitlab:merge-request
      if: ${{ parameters.dryRun == false }}
      input:
        repoUrl: gitlab.com?repo=infrastructure/deploy-tools&owner=xxxxxx
        title: "[Backstage] New system: ${{ parameters.system }}"
        branchName: backstage-create-${{ parameters.system | lower }}
        description: |
          # ${{ parameters.system }}

          ## Description

          ${{ parameters.description if parameters.description }}
        targetPath: backstage/backstage/dev/components/${{ parameters.system | lower }}
        token: ${{ secrets.GITLAB_TOKEN }}
        commitAction: create
        removeSourceBranch: true
        # assignee: ${{ parameters.assignee }}

  output:
    links:
      - title: Go to Gitlab MR
        url: ${{ steps.publish.output.mergeRequestUrl }}
      - title: Open in catalog
        icon: catalog
        entityRef: ${{ steps.register.output.entityRef }}
```

Skeleton:

```
tree system
 system
├──  skeleton
│   └──  catalog-info.yaml
└──  template.yaml
```

the template file used:

```yaml
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: ${{values.system | lower }}
  description: ${{ values.description }}
  tags:
    - ${{values.system | lower }}
    - ${{values.domain }}
  links:
    - url: https://${{ values.system | lower }}}.services.oina.ws
      title: System
      icon: dashboard
  annotations:
    gitlab.com/project-slug: xxxx/infrastructure/service-catalog/systems/${{ values.system | lower }}}
spec:
  owner: group:${{ values.owner }}}
  domain: ${{ values.domain }}}
```

### 👍 Expected behavior

A MergeRequest with code.

### 👎 Actual Behavior with Screenshots

![Task-6f565acd-49b6-4c12-b68d-b5bb8da90c8d-Backstage-Swan](https://github.com/backstage/backstage/assets/29233/e29c29f9-12b5-4d97-be85-0c980797f672)
![Task-6f565acd-49b6-4c12-b68d-b5bb8da90c8d-Backstage-Swan (1)](https://github.com/backstage/backstage/assets/29233/0d0bba36-fed3-4dd6-844e-de50fdd9c038)
![Task-6f565acd-49b6-4c12-b68d-b5bb8da90c8d-Backstage-Swan (2)](https://github.com/backstage/backstage/assets/29233/e096a632-f979-4bfa-8d97-593c72694c3d)
![-Backstage-New-system-Foo-511-·-Merge-requests-·-Swan-io-Infrastructure-deploy-tools-·-GitLab](https://github.com/backstage/backstage/assets/29233/80133599-b348-4390-afec-865cdfa41446)

### 👟 Reproduction steps

Create a new system from a template.

### 📃 Provide the context for the Bug.

Try to create a new system from a custom template.

### 🖥️ Your Environment

Backstage deployed in a Kubernetes cluster using the Helm chart.
The application works fine.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by nlamirault** [comment]
Hi i change the template using `targetPath` it works, the Gitlab merge request contains code, but at the root of the folder.

```yaml
- id: fetch-template
      name: Fetch System Template
      action: fetch:template
      if: ${{ parameters.dryRun == false }}
      input:
        url: ./skeleton
        targetPath: ${{ parameters.system  | lower }}
        values:
          system: ${{ parameters.system }}
          description: ${{ parameters.description }}
          owner: ${{ parameters.owner }}
          domain: ${{ parameters.domain }}
          lifecycle: ${{ parameters.lifecycle }}

    - id: publish
      name: Publish
      action: publish:gitlab:merge-request
      if: ${{ parameters.dryRun == false }}
      input:
        repoUrl: gitlab.com?repo=infrastructure/deploy-tools&owner=xxxxxxxxx
        title: "[Backstage] New system: ${{ parameters.system }}"
        branchName: feat/backstage-create-${{ parameters.system | lower }}
        description: |
          # ${{ parameters.system }}

          ## Description

          ${{ parameters.description if parameters.description }}
        targetPath: ${{ parameters.system  | lower }}
        # sourcePath: backstage/service-catalog/dev/systems
        token: ${{ secrets.GITLAB_TOKEN }}
        commutation: create
        removeSourceBranch: true
```

If i try to add `sourcePath` into the `publish:gitlab:merge-request`, the Merge Request is empty.
