### ISSUE TITLE
How to dynamically delete the files based on the user input using fs:delete action

### ISSUE THREAD

**Issue by aravindMylsamy** [backstage/backstage#18346]
### 📜 Description

Currently we are having the `fs:delete` action which will delete the files/folder but we need the action dynamically to delete the files based on the user input given as **checkboxes** in the backstage localhost.

Our current setup is 

```
      - id: delete-fields
        action: fs:delete
        name: Delete files
        input:
         files:
           - ./demo.txt
```

### 👍 Expected behavior

We need like

   ```
 steps:
  - name: Delete files
    action: fs:delete
    input:
      files:
        # Iterate through the array of files to be deleted
          # Delete each file.
```

### 👎 Actual Behavior with Screenshots

.

### 👟 Reproduction steps

.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, I don't have time to work on this right now
