### ISSUE TITLE
🐛 Bug Report: Azure AD integration with catalog is failing 

### ISSUE THREAD

**Issue by jiyo86** [backstage/backstage#18353]
### 📜 Description

Hi team,
I have configured the azure ad to backstage project as per the documentation https://backstage.io/docs/integrations/azure/org/ but it is not working properly. 

In log it showing catalog info Reading msgraph users and groups type=plugin class=MicrosoftGraphOrgEntityProvider taskId=MicrosoftGraphOrgEntityProvider:providerId:refresh taskInstanceId=xxxxx
after above error getting this warning and not importing any users or groups

catalog warn Unable to load user photo for type=plugin class=MicrosoftGraphOrgEntityProvider taskId=MicrosoftGraphOrgEntityProvider:providerId:refresh taskInstanceId=xxxx user=xxxx error=Error: Error while reading photo from Microsoft Graph: GatewayTimeout - Timed out on external dependency

### 👍 Expected behavior

users and groups should be imported 
ead X msgraph users and Y msgraph groups

### 👎 Actual Behavior with Screenshots

catalog warn Unable to load user photo for type=plugin class=MicrosoftGraphOrgEntityProvider taskId=MicrosoftGraphOrgEntityProvider:providerId:refresh taskInstanceId=xxxxx user=9xxxx error=Error: Error while reading users photos from Microsoft Graph: GatewayTimeout - Timed out on external dependency
[1] 2023-06-20T14:51:40.053Z catalog warn Unable to load user photo for type=plugin class=MicrosoftGraphOrgEntityProvider taskId=MicrosoftGraphOrgEntityProvider:providerId:refresh taskInstanceId=xxxxx user=xxxx error=Error: Error while reading users photos from Microsoft Graph: GatewayTimeout - Timed out on external dependency
[1] 2023-06-20T14:54:07.237Z catalog warn Unable to load user photo for type=plugin class=MicrosoftGraphOrgEntityProvider taskId=MicrosoftGraphOrgEntityProvider:providerId:refresh taskInstanceId=xxxxx user=xxxxx  error=Error: Error while reading users photos from Microsoft Graph: GatewayTimeout - Timed out on external dependency
[1] 2023-06-20T14:57:18.221Z catalog warn Unable to load user photo for type=plugin class=MicrosoftGraphOrgEntityProvider taskId=MicrosoftGraphOrgEntityProvider:providerId:refresh taskInstanceId=xxxxx user=xxxxx error=Error: Error while reading photo from Microsoft Graph: GatewayTimeout - Timed out on external dependency
[1] 2023-06-20T14:57:34.444Z catalog warn Unable to load user photo for type=plugin class=MicrosoftGraphOrgEntityProvider taskId=MicrosoftGraphO

### 👟 Reproduction steps

yarn dev

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by steff-petro** [comment]
@jiyo86 I faced the same issue at one point. It most likely relates to your org and the filters you have specified. If you are using the provided config in the documentation and your org has a bunch of groups and users then that could cause an issue. I recommend importing a small subset of users and groups to make sure that it works properly before trying it on a larger set.

**Comment by ezephillips** [comment]
> I faced the same issue at one point. It most likely relates to your org and the filters you have specified. If you are using the provided config in the documentation and your org has a bunch of groups and users then that could cause an issue. I recommend importing a small subset of users and groups to make sure that it works properly before trying it on a larger set. I am planning to submit a pr on some doc changes as our team noticed the explanation on how the importer works could be improved a little bit and I think importing all users and groups from an org is not a good place to start when using the integration for the first time.

Hi Stefan, 
I'm currently importing a group that contains 680 direct members, it does fine (although sometimes I get the error that it couldn't import a random user's photo)
But I need to import another group, which contains the real users of my organization and these are 13500 users approx.
This is my configuration:

``` YAML

  providers:
    microsoftGraphOrg:
      default:
        pooling:
          frequency:
            minutes: ${MICROSOFT_GRAPH_POOLING_FREQUENCY}
          timeout:
            minutes: ${MICROSOFT_GRAPH_POOLING_TIMEOUT}
        tenantId: ${AZURE_TENANT_ID}
        userGroupMember:
          filter: displayName eq '${MICROSOFT_GRAPH_USERS_FROM_GROUP_FILTER}'
        group:
          filter: ${MICROSOFT_GRAPH_GOC_MANAGED_GROUP_PROPERTY_ID}/isManagedByGoc eq 'true'
          expand: members

```
as MICROSOFT_GRAPH_POOLING_FREQUENCY= **1** 
as MICROSOFT_GRAPH_POOLING_TIMEOUT= **5**


After changing the group to the one that contains these 13k, I see very often in the log, this gateway timeout and after an hour, it doesn't seem that the import is going to finish.
How do you think I could do it?
Thank you so much
