### ISSUE TITLE
🚀 Feature: Relations for Template Kinds

### ISSUE THREAD

**Issue by phaakmat** [backstage/backstage#18368]
### 🔖 Feature description

Extend the `Template` Kind to describe relations between templates and group them into larger collections. Idealized example:

`github-repo/template.yml`:
```yaml
apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: create-repo
  title: Create Repo
  description: Create an empty repository with org defaults.
spec:
  owner: team-platform
  type: generic
  system: backstage-templates # creates hasPart, partOf relations
```

`add-dotnet-project/template.yml`:
```yaml
apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: add-dotnet-project
  title: Add .NET Project
  description: Add a .NET project to an empty repository.
spec:
  owner: team-platform
  type: generic
  system: backstage-templates # creates hasPart, partOf relations
  dependsOn: # creates dependsOn, dependencyOf relations
    - github-repo
```

This is an idealized example. It wouldn't actually work for the following reasons:
- `system` expects the entity to be a `Component`, not a `Template`
- `dependsOn` expects a `Component`, not a `Template`

I can imagine the following solution directions, ordered more-or-less from 'least worst' to 'most worst' (the ordering is quite subjective):
1. Modify the Template ingestor/processor to emit an associated `Component` for the Template, and apply the relations to that Component, and finally (somehow) link the Component <=> Template.
2. Modify `System` and `dependsOn` to allow `Template` Kinds.
3. Introduce extra fields with `template` prefix, like `templateSystem` and `templateDependsOn` and introduce a new Kind `TemplateSystem`.
4. Remove the `Template` Kind and subsume its functionality under a `Component` with type `template`.

### 🎤 Context

We've found that "modular" templates are much easier to maintain, explain, and increase developer understanding. Modular templates are small templates, which add/create/setup one specific resource or feature. A full solution can be made by applying multiple templates in sequence.

Using modular templates increases the total number of templates however, so that it would be handy to have a way to organize them into subsystems, and to graph the relationships/dependencies between them.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!
