### ISSUE TITLE
🚀 Feature: Add an option to create computable intermediate variables in a software template

### ISSUE THREAD

**Issue by SayakMukhopadhyay** [backstage/backstage#18396]
### 🔖 Feature description

Allows the creation of computed intermediate values from `parameters` but using nunjucks. This helps in keeping templates DRY and helps in some cases where you want to generate a random (or random-like) value  and use it in multiple places.

### 🎤 Context

In my scaffolder `template.yaml`, I have a case wherein I want to modify an input parameter in a certain way and want to use it in multiple steps. For eg.
```yaml
# nonk8s
apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: my-template
spec:
  owner: user:sayak
  parameters:
    - title: Enter Basic Information
      required:
        - name
        - owner
      properties:
        name:
          title: Name
          type: string
          description: Unique name of the component. Should be in the form of 'Component Name'.
          ui:autofocus: true
        description:
          title: Description
          type: string
          description: Description of the component
        owner:
          title: Owner
          type: string
          description: Owner of the component
          ui:field: OwnerPicker
          ui:options:
            catalogFilter:
              kind:
                - Group
                - User

  steps:
    - id: template
      name: Fetch Skeleton
      action: fetch:template
      input:
        url: ./skeleton
        values:
          name: ${{ parameters.name }}
          projectName: ${{ parameters.name| replace(' ', '') }}${{ parameters.description | replace(' ', '') }}${{ parameters.name | replace(' ', '') }}
          rand: ${{ randGen() }}

    - id: move-classes-to-package
      name: Move Classes to Correct Package
      action: fs:rename
      input:
        files:
          - from: somefile
            to: ${{ parameters.name| replace(' ', '') }}${{ parameters.description | replace(' ', '') }}${{ parameters.name | replace(' ', '') }}
            overwrite: true
          - from: otherfile
            to: ${{ randGen() }}
```
As you can see in the above, I am making the exact same modifications to the `name` and `description` parameters in the 2 steps. I want to keep my template DRY. As far as I can see by inspecting the source code, there is no way I can do it. Moreover, imagine I want to generate a random value, in this case, using a custom global `randGen`, and want to use the same value in 2 steps as in the above YAML. But this will create 2 different random values.

### ✌️ Possible Implementation

My idea is to update the template schema as follows
```diff
# nonk8s
apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: my-template
spec:
  owner: user:sayak
  parameters:
    - title: Enter Basic Information
      required:
        - name
        - owner
      properties:
        name:
          title: Name
          type: string
          description: Unique name of the component. Should be in the form of 'Component Name'.
          ui:autofocus: true
        description:
          title: Description
          type: string
          description: Description of the component
        owner:
          title: Owner
          type: string
          description: Owner of the component
          ui:field: OwnerPicker
          ui:options:
            catalogFilter:
              kind:
                - Group
                - User

+ computed:
+   projectName: ${{ parameters.name| replace(' ', '') }}${{ parameters.description | replace(' ', '') }}${{ parameters.name | replace(' ', '') }}
+   rand: ${{ randGen() }}

  steps:
    - id: template
      name: Fetch Skeleton
      action: fetch:template
      input:
        url: ./skeleton
        values:
          name: ${{ parameters.name }}
-         projectName: ${{ parameters.name| replace(' ', '') }}${{ parameters.description | replace(' ', '') }}${{ parameters.name | replace(' ', '') }}
+         projectName: ${{ computed.projectName }}
-         rand: ${{ randGen() }}
+         rand: ${{ computed.rand }}

    - id: move-classes-to-package
      name: Move Classes to Correct Package
      action: fs:rename
      input:
        files:
          - from: somefile
-           to: ${{ parameters.name| replace(' ', '') }}${{ parameters.description | replace(' ', '') }}${{ parameters.name | replace(' ', '') }}
+           to: ${{ computed.projectName }}
            overwrite: true
          - from: otherfile
-           to: ${{ randGen() }}
+           to: ${{ computed.rand }}
```
This gives the possibility of rendering the the `computed` property using nunjucks and then using the computed value for further templating.

I feel like this can be done somewhere before the inputs are templated at https://github.com/backstage/backstage/blob/3b68b09fc2d87fbed1f6aa2714207113c5ad4476/plugins/scaffolder-backend/src/scaffolder/tasks/NunjucksWorkflowRunner.ts#L280-L287

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!
