### ISSUE TITLE
🐛 Bug Report:  Date parsing is broken in the ADR plugin

### ISSUE THREAD

**Issue by Nidafjoll** [backstage/backstage#18413]
### 📜 Description

The https://github.com/backstage/backstage/pull/17954 pull request introduced the usage of [front-matter](https://github.com/jxson/front-matter) to parse the markdown header. 

Putting a date in the header doesn't show up in rendered output, which seems to be caused by front-matter parsing the date string to a date object which is than transformed to string again. The [front-matter](https://github.com/jxson/front-matter) repository also has an old issue open regarding this issue https://github.com/jxson/front-matter/issues/78 but without a fix or workaround.

The header values in my markdown file:
```yaml
---
status: accepted
date: 2023-06-23
---
```

The parsed values:

![image](https://github.com/backstage/backstage/assets/17978572/9738d350-4708-4f1e-a401-7c14c2d7b407)

This will then not pass the datetime valid check in madrParser.ts and end up returning undefined, because we still expect the original date string (yyyy-MM-dd).

![image](https://github.com/backstage/backstage/assets/17978572/bf61dea2-c48b-4262-8d26-ab4640f98a55)

The rendering of the list seems to be broken in general, the layout of the chip is misaligned without the date value. Which should be an optional element according to the [template](https://github.com/adr/madr/blob/develop/template/adr-template.md).

A possible solution might be changing the parseMadrWithFrontmatter function to parse the date object back to its original format (yyyy-MM-dd), but I'm not sure if this is the way to go. 

### 👍 Expected behavior

The ADR list should be rendered properly like the example in the documentation

![image from doc](https://raw.githubusercontent.com/backstage/backstage/91ca8b38434d89eb8412a9fa7e5bff2fda215073/plugins/adr/docs/adr-tab.png)

### 👎 Actual Behavior with Screenshots

The layout of the list is broken and the date is missing:

![image](https://github.com/backstage/backstage/assets/17978572/ec8dada3-f61a-4cf1-8027-e85cb7c387ee)

### 👟 Reproduction steps

1. Follow the getting started for contributors: https://backstage.io/docs/getting-started/contributors
2. Change the example adr-location annotation in /plugins/adr/examples/component/catelog-info.yaml to point to https://github.com/Nidafjoll/pastebin/blob/main/decisions
```yaml
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: component-with-adrs
  title: Component With ADRs
  description: A Service with ADRs registerd
  annotations:
    backstage.io/adr-location: https://github.com/Nidafjoll/pastebin/blob/main/decisions
spec:
  type: service
  lifecycle: experimental
  owner: user:guest
```
3. Navigate to http://localhost:3000/catalog/default/component/component-with-adrs/adrs

### 🖥️ Your Environment

node: v18.13.0      
yarn: 3.2.3
cli:  0.22.8 (local)

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else
