### ISSUE TITLE
🚀 Feature: Method to debug catalog refresh and filter matching

### ISSUE THREAD

**Issue by LeoQuote** [backstage/backstage#18426]
### 🔖 Feature description

We should provide a detailed task log , providing scan process , matching and filtering process , it can help to thoubleshoot problems like catelog not shown in backstage or something.

### 🎤 Context

I'm trying to intergrate github discovery in backstage, but I found it found nothing if I enable visibility filter like:

```
catalog:
  providers:
    github:
      # the provider ID can be any camelCase string
      myOrg:
        host: github.intra.xxx.com
        organization: 'my-org' # string
        catalogPath: '/catalog-info.yaml' # string
        filters:
          repository: '.*' # Regex
          allowForks: false
          visibility:
            - "public"
            - "internal"
```

the log would be like:

```
[1] 2023-06-26T08:18:31.703Z catalog info Read 201 GitHub repositories (0 matching the pattern) type=plugin target=github-provider:sa class=GithubEntityProvider taskId=github-provider:sa:refresh taskInstanceId=3a6bb08e-1601-4757-9462-d4067e0054f7
```

I found nowhere I can find detailed log for each repository info, why no repo is matched.

### ✌️ Possible Implementation

use another logger to log detailed log info to a file or console, with task id in it. developers can use it to debug this.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else
