### ISSUE TITLE
🐛 Bug Report: Sonarqube config failing config check

### ISSUE THREAD

**Issue by ScottGuymer** [backstage/backstage#18477]
### 📜 Description

App startup fails when following the config in the readme.

https://github.com/backstage/backstage/tree/master/plugins/sonarqube-backend#example---multiple-global-instance

This config only has the instances values configured and not the default value

```
sonarqube:
  instances:
    - name: default
      baseUrl: https://default-sonarqube.example.com
      apiKey: 123456789abcdef0123456789abcedf012
    - name: specialProject
      baseUrl: https://special-project-sonarqube.example.com
      apiKey: abcdef0123456789abcedf0123456789ab
```

### 👍 Expected behavior

This config should work as expected and pass validation on startup.

This config does actually pass cli validation without erroring, it is only on startup that this seems to be an issue

### 👎 Actual Behavior with Screenshots

It fails the configuration check because `baseUrl` is required in the config.d.ts

```
 Backend failed to start up, Error: Invalid app bundle schema. If this error is unexpected you need to run `yarn build` in the app. If that doesn't help you should make sure your config schema is correct and rebuild the app bundle again. Caused by the following schema error, Error: Config validation failed, Config must have required property 'baseUrl' { missingProperty=baseUrl } at /sonarqube
```

### 👟 Reproduction steps

Add config as above for sonarqube and try to start the app

(it only seems to break on a built version and not in dev mode)

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!
