### ISSUE TITLE
🐛 Bug Report: workflowInputs of github:actions:dispatch are empty

### ISSUE THREAD

**Issue by guimilleo** [backstage/backstage#18511]
### 📜 Description

Hi all, I'm trying to use `github:actions:dispatch` like this:
````
steps:
  - id: workflow
    name: Run Github Action
    action: github:actions:dispatch
    input:
      repoUrl: github.com?repo=***&owner=***
      workflowId: 'create-plugin.yml'
      branchOrTagName: main
      token: ***
      worfklowInputs:
        branch_name: "${{ parameters.branch_name }}"
        plugin_name: "${{ parameters.plugin_name }}"
        plugin_type: "${{ parameters.plugin_type }}"
````

but it turns out I'm getting this error

`2023-06-30T12:08:51.251Z HttpError: Required input 'branch_name' not provided`

But I have the parameter `branch_name` and I filled in this field in the UI. Not sure what is happening.
