### ISSUE TITLE
🐛 Bug Report: Documentation is wrong, Entity References require (sometimes) the kind.

### ISSUE THREAD

**Issue by joslat** [backstage/backstage#18526]
### 📜 Description

If I add a system with some components it "depends on", the name should be enough, according to the documentation.
But if I add a component and make another component "depends on" then it fails with an exception

the exception:
`{"error":{"name":"InputError","message":"InputError: Processor BuiltinKindsEntityProcessor threw an error while postprocessing; caused by Error: Entity reference \"One-More\" had missing or empty kind (e.g. did not start with \"component:\" or similar)","stack":"InputError: InputError: Processor BuiltinKindsEntityProcessor threw an error while postprocessing; caused by Error: Entity reference \"One-More\" had missing or empty kind (e.g. did not start with \"component:\" or similar)\n at DefaultLocationService.processEntities (C:\\backstage\\backstage-app02\\node_modules\\@backstage\\plugin-catalog-backend\\dist\\cjs\\CatalogBuilder-ecfd2db6.cjs.js:1890:15)\n at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n at async DefaultLocationService.dryRunCreateLocation (C:\\backstage\\backstage-app02\\node_modules\\@backstage\\plugin-catalog-backend\\dist\\cjs\\CatalogBuilder-ecfd2db6.cjs.js:1921:22)\n at async C:\\backstage\\backstage-app02\\node_modules\\@backstage\\plugin-catalog-backend\\dist\\cjs\\CatalogBuilder-ecfd2db6.cjs.js:3512:22"},"request":{"method":"POST","url":"/locations?dryRun=true"},"response":{"statusCode":400}}`

### 👍 Expected behavior

Either the documentation is corrected to state the mandatory specification of the kind in the right or a component should be able to accept other components as dependson without specifying the kind on its entity reference.
On [Entity Reference](https://backstage.io/docs/features/software-catalog/references/#string-references)
it says: 
> The string is on the form [<kind>:][<namespace>/]<name>, that is, it is composed of between one and three parts in this specific order, without any additional encoding:
> Optionally, the kind, followed by a colon
> Optionally, the namespace, followed by a forward slash
> The name

But a component with a [dependsOn](https://backstage.io/docs/features/software-catalog/descriptor-format/#specdependson-optional) without the kind, throws an exception.

### 👎 Actual Behavior with Screenshots

If I add the following catalog-info.yaml:
```
# System
apiVersion: backstage.io/v1alpha1
kind: System
metadata: 
  name: One
  description: Sample system
  tags:
    - dotnet
    - aspnet
  links:
  - url: https://www.sample.com/
    title: sample
    icon: dashboard
spec:
  type: service
  owner: me
  lifecycle: production
  dependsOn:  
    - One-1
    - One-2
    - One-3
# sub-systems (components)
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata: 
  name: One-1
  description: sample.
  tags:
    - dotnet
    - aspnet
spec:
  type: service
  owner: me
  system: One
  lifecycle: production
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata: 
  name: One-2
  description: sample.
  tags:
    - dotnet
    - aspnet
spec:
  type: service
  owner: me
  system: One
  lifecycle: production
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata: 
  name: One-3
  description: sample..
  tags:
    - dotnet
    - aspnet
spec:
  type: service
  owner: me
  system: One
  lifecycle: production
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata: 
  name: One-More
  description: sample
  tags:
    - dotnet
spec:
  type: service
  owner: me
  system: One
  lifecycle: production
```

all is good. But then I add a `dependsOn` like:
```
# System
apiVersion: backstage.io/v1alpha1
kind: System
metadata: 
  name: One
  description: Sample system
  tags:
    - dotnet
    - aspnet
  links:
  - url: https://www.sample.com/
    title: sample
    icon: dashboard
spec:
  type: service
  owner: me
  lifecycle: production
  dependsOn:  
    - One-1
    - One-2
    - One-3
# sub-systems (components)
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata: 
  name: One-1
  description: sample.
  tags:
    - dotnet
    - aspnet
spec:
  type: service
  owner: me
  system: One
  lifecycle: production
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata: 
  name: One-2
  description: sample.
  tags:
    - dotnet
    - aspnet
spec:
  type: service
  owner: me
  system: One
  lifecycle: production
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata: 
  name: One-3
  description: sample..
  tags:
    - dotnet
    - aspnet
spec:
  type: service
  owner: me
  system: One
  lifecycle: production
  dependsOn:  
    - One-More  
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata: 
  name: One-More
  description: sample
  tags:
    - dotnet
spec:
  type: service
  owner: me
  system: One
  lifecycle: production
```

it fails with exception:
<img width="923" alt="issue" src="https://github.com/backstage/backstage/assets/9831011/067b0867-aa78-4bac-af18-3ac5942106ae">

```
{"error":{"name":"InputError","message":"InputError: Processor BuiltinKindsEntityProcessor threw an error while postprocessing; caused by Error: Entity reference \"One-More\" had missing or empty kind (e.g. did not start with \"component:\" or similar)","stack":"InputError: InputError: Processor BuiltinKindsEntityProcessor threw an error while postprocessing; caused by Error: Entity reference \"One-More\" had missing or empty kind (e.g. did not start with \"component:\" or similar)\n at DefaultLocationService.processEntities (C:\\backstage\\backstage-app02\\node_modules\\@backstage\\plugin-catalog-backend\\dist\\cjs\\CatalogBuilder-ecfd2db6.cjs.js:1890:15)\n at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n at async DefaultLocationService.dryRunCreateLocation (C:\\backstage\\backstage-app02\\node_modules\\@backstage\\plugin-catalog-backend\\dist\\cjs\\CatalogBuilder-ecfd2db6.cjs.js:1921:22)\n at async C:\\backstage\\backstage-app02\\node_modules\\@backstage\\plugin-catalog-backend\\dist\\cjs\\CatalogBuilder-ecfd2db6.cjs.js:3512:22"},"request":{"method":"POST","url":"/locations?dryRun=true"},"response":{"statusCode":400}}
```

If I do it specifying the kind such as:
```
spec:
  ...
  dependsOn:  
    - component:One-More  
```
  
 It works well.

### 👟 Reproduction steps

1. Read [string references documentation](https://backstage.io/docs/features/software-catalog/references/#string-references)
  - it states the kind is optional.
2. Register a component with a file containing:
```
# System
apiVersion: backstage.io/v1alpha1
kind: System
metadata: 
  name: One
  description: Sample system
  tags:
    - dotnet
    - aspnet
  links:
  - url: https://www.sample.com/
    title: sample
    icon: dashboard
spec:
  type: service
  owner: me
  lifecycle: production
  dependsOn:  
    - One-1
    - One-2
    - One-3
# sub-systems (components)
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata: 
  name: One-1
  description: sample.
  tags:
    - dotnet
    - aspnet
spec:
  type: service
  owner: me
  system: One
  lifecycle: production
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata: 
  name: One-2
  description: sample.
  tags:
    - dotnet
    - aspnet
spec:
  type: service
  owner: me
  system: One
  lifecycle: production
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata: 
  name: One-3
  description: sample..
  tags:
    - dotnet
    - aspnet
spec:
  type: service
  owner: me
  system: One
  lifecycle: production
  dependsOn:  
    - One-More  
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata: 
  name: One-More
  description: sample
  tags:
    - dotnet
spec:
  type: service
  owner: me
  system: One
  lifecycle: production
```
  
It fails.

Chage the last dependsOn: to:
```
  dependsOn:  
    - component:One-More  
 ```
    
And it works.
So, it is not optional, either the documentation is wrong or the implementation has a bug.

### 📃 Provide the context for the Bug.

Creating a vanilla Backstage following the [getting started](https://backstage.io/docs/getting-started/) steps.
trying to register a component with a catalog yaml file.

### 🖥️ Your Environment

windows 11 with docker, installed locally but postgress in a docker container.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None
