### ISSUE TITLE
🐛 Bug Report: publish:github action does not respect collaborators

### ISSUE THREAD

**Issue by sp71** [backstage/backstage#18522]
### 📜 Description

Utilizing catalog templates, the action github:repo:create ignores the collaborators field. See following example:

```
    - id: publish
      name: Publish
      action: publish:github
      input:
        allowedHosts: ['github.com']
        description: ${{ parameters.description }}
        repoUrl: ${{ parameters.repoUrl }}
        defaultBranch: main
        gitAuthorName: John Doe
        gitAuthorEmail: john@company.com
        collaborators:
          - team: company/foo
            access: maintain
        access: sp71
        gitCommitMessage: 'hello world'
        token: ${{ secrets.GITHUB_TOKEN }}
```

### 👍 Expected behavior

When setting the field `collaborators`, it should create the repo according to the [spec](https://backstage.io/docs/reference/plugin-scaffolder-backend.createpublishgithubaction/) and respect the team flag.

### 👎 Actual Behavior with Screenshots

Repository is created where only `sp71` is listed as admin due to `access` level setting but `collaborators` was ignored where the team is not listed at all in published github repo

### 👟 Reproduction steps

Run the action `publish:github` to publish a github repo and use the collaborators field. It will be ignored

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, I don't have time to work on this right now
