### ISSUE TITLE
🐛 Bug Report: Split Monorepo projects as an individual backstage entity

### ISSUE THREAD

**Issue by poonamgp14** [backstage/backstage#18597]
### 📜 Description

I would like to split monorepos and treat each component of the monorepo as an individual Backstage entity and  added below mentioned catalog-info.yaml file at the root of the monorepo project
```
---
apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: "Dauntless Unified Experience - TEST"
spec:
  type: url
  targets:
    - ./apps/claims-finder-snapshot/backstage.yaml
    - ./apps/claims-viewer/backstage.yaml
    - ./apps/ui-kds-angular-sandbox/backstage.yaml
```

and below mentioned yml at the root of the individual project inside `./apps/` directory
```
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: claims-finder-snapshot
  title: Claims Finder Snapshot
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: library
  lifecycle: experimental
  owner: unknown
```

However, I am not yet seeing the individual projects as separate entities under Catalog. 

Can somebody please help me how can I split monorepo project as individual entities in Backstage?

### 👍 Expected behavior

I would like to split monorepos and treat each component of the monorepo as an individual Backstage entity. A split monorepo will have multiple associated catalog entries, one for each sub-component within the monorepo. It will contain many Backstage metadata files and many sets of TechDocs.

### 👎 Actual Behavior with Screenshots

I am not seeing the individual projects as separate entities under Catalog and not even monorepo as single entry under Catalog

### 👟 Reproduction steps

Please see description for the code
Steps:
1. Take any monorepo project.
2. Add below mentioned catalog-info.yaml file at the root of the project
 ```
---
apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: <name of the monorepo>
spec:
  type: url
  targets:
    - <list of inidividual yaml file for Component entities>
```
3. Add below mentioned catalog-info.yaml file at the root of the individual project
```
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: claims-finder-snapshot
  title: Claims Finder Snapshot
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: library
  lifecycle: experimental
  owner: unknown
```
4. Start the server and go to /catalog.

### 🖥️ Your Environment

```
cn330348@CNCL4M9DWFH99 devx-backstage % yarn backstage-cli info
OS:   Darwin 22.5.0 - darwin/arm64
node: v16.20.0
yarn: 3.5.1
cli:  0.22.7 (installed)
backstage:  1.14.1

Dependencies:
  @backstage/app-defaults                            1.3.1
  @backstage/backend-app-api                         0.4.2, 0.4.3
  @backstage/backend-common                          0.18.4, 0.18.5
  @backstage/backend-dev-utils                       0.1.1
  @backstage/backend-plugin-api                      0.5.1, 0.5.2
  @backstage/backend-tasks                           0.5.1, 0.5.2
  @backstage/backend-test-utils                      0.1.37
  @backstage/catalog-client                          1.4.1
  @backstage/catalog-model                           1.3.0
  @backstage/cli-common                              0.1.12
  @backstage/cli-node                                0.1.0
  @backstage/cli                                     0.22.7
  @backstage/config-loader                           1.3.0
  @backstage/config                                  1.0.7
  @backstage/core-app-api                            1.8.0
  @backstage/core-components                         0.12.5, 0.13.1
  @backstage/core-plugin-api                         1.5.1
  @backstage/dev-utils                               1.0.15
  @backstage/errors                                  1.1.5
  @backstage/eslint-plugin                           0.1.3
  @backstage/integration-aws-node                    0.1.2, 0.1.3
  @backstage/integration-react                       1.1.13
  @backstage/integration                             1.4.5
  @backstage/plugin-api-docs                         0.9.3
  @backstage/plugin-app-backend                      0.3.45
  @backstage/plugin-auth-backend                     0.18.3
  @backstage/plugin-auth-node                        0.2.13, 0.2.14
  @backstage/plugin-catalog-backend-module-gitlab    0.0.0-use.local
  @backstage/plugin-catalog-backend-module-ldap      0.5.12
  @backstage/plugin-catalog-backend                  1.9.1
  @backstage/plugin-catalog-common                   1.0.13
  @backstage/plugin-catalog-graph                    0.2.30
  @backstage/plugin-catalog-import                   0.9.8
  @backstage/plugin-catalog-node                     1.3.6
  @backstage/plugin-catalog-react                    1.6.0
  @backstage/plugin-catalog                          1.11.0, 1.11.1
  @backstage/plugin-cicd-statistics-module-gitlab    0.0.0-use.local
  @backstage/plugin-cicd-statistics                  0.1.20
  @backstage/plugin-github-actions                   0.5.18
  @backstage/plugin-kubernetes-backend               0.11.0
  @backstage/plugin-kubernetes-common                0.6.3
  @backstage/plugin-kubernetes                       0.9.1
  @backstage/plugin-org                              0.6.8
  @backstage/plugin-permission-common                0.7.5
  @backstage/plugin-permission-node                  0.7.7, 0.7.8
  @backstage/plugin-permission-react                 0.4.12
  @backstage/plugin-proxy-backend                    0.2.39
  @backstage/plugin-scaffolder-backend-module-gitlab 0.0.0-use.local
  @backstage/plugin-scaffolder-backend               1.14.0
  @backstage/plugin-scaffolder-common                1.3.0
  @backstage/plugin-scaffolder-node                  0.1.3
  @backstage/plugin-scaffolder-react                 1.4.0
  @backstage/plugin-scaffolder                       1.13.1
  @backstage/plugin-search-backend-module-catalog    0.1.1
  @backstage/plugin-search-backend-module-pg         0.5.6
  @backstage/plugin-search-backend-module-techdocs   0.1.1
  @backstage/plugin-search-backend-node              1.2.1
  @backstage/plugin-search-backend                   1.3.1
  @backstage/plugin-search-common                    1.2.3
  @backstage/plugin-search-react                     1.6.0, 1.6.1
  @backstage/plugin-search                           1.3.0
  @backstage/plugin-tech-radar                       0.6.4
  @backstage/plugin-techdocs-addons-test-utils       1.0.14
  @backstage/plugin-techdocs-backend                 1.6.2
  @backstage/plugin-techdocs-module-addons-contrib   1.0.13
  @backstage/plugin-techdocs-node                    1.7.1
  @backstage/plugin-techdocs-react                   1.1.6
  @backstage/plugin-techdocs                         1.6.2, 1.6.3
  @backstage/plugin-user-settings                    0.7.3
  @backstage/release-manifests                       0.0.9
  @backstage/test-utils                              1.3.1
  @backstage/theme                                   0.2.19, 0.3.0
  @backstage/types                                   1.0.2
  @backstage/version-bridge                          1.0.4
```

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by benjdlambert** [comment]
Is there any logs in the backend that can help us here? I have a feeling that it's probably because Location entities might not be allowed to be registered and you will need to enable that for that particular host. Should be some more information in the logs.

**Comment by grvpandey11** [comment]
@poonamgp14  

Check this config file
```
---
apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: "Dauntless Unified Experience - TEST"
spec:
  type: url
  targets:
    - ./apps/claims-finder-snapshot/backstage.yaml
    - ./apps/claims-viewer/backstage.yaml
    - ./apps/ui-kds-angular-sandbox/backstage.yaml
```

I think this is not a valid 

Please use entity validator to check.
I get this error while doing the same

`Error: "metadata.name" is not valid; expected a string that is sequences of [a-zA-Z0-9] separated by any of [-_.], at most 63 characters in total but found "Dauntless Unified Experience - TEST". `
