### ISSUE TITLE
💬 RFC: Standardise Annotations for K8s resources to populate Entities

### ISSUE THREAD

**Issue by bigkevmcd** [backstage/backstage#18617]
### 🔖 Need

Sometimes we want to present Kubernetes resources inside Backstage, and ideally we'd populate as many of the Entity fields as possible.

Things like:
 - lifecycle
 - owner
 - description
 - system
 - tags

For example creating `kubernetes-cluster` resources for the [CatalogClusterLocator](https://github.com/backstage/backstage/blob/master/plugins/kubernetes-backend/src/cluster-locator/CatalogClusterLocator.ts) it'd be good to populate the fields.

### 🎉 Proposal

This is proposing a standard set of Kubernetes _annotations_ and not _labels_ because label [values](https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#syntax-and-characte) can't have some characters that are useful when describing resources.

```yaml
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: test-cluster
  namespace: default
  annotations:
    backstage.io/kubernetes-lifecycle: production
    backstage.io/kubernetes-owner: team:eu-cluster-admins
    backstage.io/kubernetes-description: This is the production cluster
    backstage.io/kubernetes-system: test-system
    backstage.io/kubernetes-tags: 'eu,production,aws' # these are split on commas and trimmed
```

### 〽️ Alternatives

We don't need to standardise this at all, and we don't need to populate all the fields, so we could do nothing.

This would effectively mean that each component that was providing Kubernetes resources as Backstage entities would find their own schema.

But as exposing Kubernetes resources can be useful, it feels like there's an opportunity to define some standard annotations and how they work (the tags) to simplify things for users.

### ❌ Risks

This is low risk, consumers of the annotations are free to support them or not.

### 👀 Have you spent some time to check if this RFC has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

**Comment by tumido** [comment]
I like this idea. We're also working on a plugin ingesting Kubernetes resources as catalog entities (`kind:Resource`, `spec.type:kubernetes-cluster`). This would allow us to have a standard notation like the Kubernetes plugin already has with:

```yaml
kind: Pod
metadata:
  annotations:
    backstage.io/kubernetes-id: <value>
```

This is an analogy, but instead of tapping into Backstage Kubernetes plugin, we would allow the same annotation to be reused by different catalog backend plugins. This would make the annotations easily recognizable as something that belongs to Backstage catalog mapping compared to the current situation where each plugin may introduce their own distinct set of annotations, which purpose may not be apparent to Kubernetes users who are probably unaware of custom Backstage plugin-specific annotation namespaces.

**Comment by mclarke47** [comment]
I think I'm a bit confused, I'm wondering if these Entity fields shouldn't just be sourced from the Entity that owns the kubernetes resources? 

Example:

Entity `my-service` owns a bunch of k8s resources: deployment, hpa etc..

We retrieve it's deployment and hpa and they all share the same owner/lifecycle as the entity that was used to fetch them.

Then surely the entity fields for `lifecycle`/`owner` etc should come from the Entity in the catalog, not annotations on the Kubernetes resources?

Am I misunderstanding?

**Comment by bigkevmcd** [comment]
@mclarke47 Yes, https://github.com/bigkevmcd/backstage-plugins/tree/main/plugins/catalog-backend-module-capi#annotating-capi-resources (this is pre-standardisation).

You'll also see the configuration in the provider:

```yaml
catalog:
  providers:
    capi:
      hubClusterName: production-cluster # this name is looked up in the list of clusters
      # You can configure the scheduling centrally above, or via the individual providers like this
      schedule:
        frequency: { minutes: 5 }
        timeout: { minutes: 1 }
      # All these fields are optional - annotations on the Cluster resources will override them
      defaults:
        clusterOwner: group:cluster-admins
        system: testing
        lifecycle: dev
        tags:
          - imported
          - capi
          - cluster
```
I know the github.com/janus-idp project is doing something similar in their`ocm-backend` plugin, so this is really a proposal for a generic "here are some annotations for Kubernetes resources that can be reused across several plugins" suggestion.

I'd be open to contributing something to the kubernetes-common plugin `extractEntityDataFromAnnotations` (naming is hard) along with the annotations to make it even simpler, perhaps with a type for the description that I used in the provider implementation, I'm happy to do this once I get my code out-the-door with the standardised annotations.
