### ISSUE TITLE
🚀 Feature: Support local file substitutions 

### ISSUE THREAD

**Issue by nabuskey** [backstage/backstage#18671]
### 🔖 Feature description

Scaffolder templates [support substitutions](https://backstage.io/docs/features/software-catalog/descriptor-format/#substitutions-in-the-descriptor-format). However this is currently limited to fetching from http endpoints. It would be great if it supported local files as well. 

### 🎤 Context

When developing scaffolder templates, it is sometimes necessary to reference other files in a template to keep things clean. For example, consider a local setup like this. 

```yaml
# app-config.yaml
locations:
  - type: file
    target: /path/to/template.yaml
```

```yaml
# /path/to/template.yaml
apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
spec:
  parameters:
    - resource:
          type: string
          enum:
            - MySQL
            - Postgresql
            - MariaDB
      dependencies:
        resource:
          oneOf:
            - $yaml: ./resources/mysql.yaml 
            - $yaml: ./resources/postgresql.yaml
            - $yaml: ./resources/mariadb.yaml
```

Here, we are allowing users to select a db type from a list. Actual templates for DB types are stored in a separate directory. This allows for logical separation of templates and reuse them when necessary. This works fine if templates are pushed to a remote repository or served from a web server, but does not work if templates are stored locally. It fails with `could not form a URL out of <PATH>`

When developing templates locally, this becomes a pain point because you either have to push everything to a git repository or spin up a web server to test a change. 

This also makes testing templates in CI jobs cumbersome because we need to create a local web server just for this purpose in every run. 

cc: @jessesanford @nimakaviani

### ✌️ Possible Implementation

Although I haven't looked into this deeply yet, @Rugvip 's [comment](https://github.com/backstage/backstage/issues/14372#issuecomment-1298319349) suggests this is possible. For local file URLs, is only allowing access to sub directories acceptable? 

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by jessesanford** [comment]
There is an abundance of precedent in other frameworks and tooling that can be used as an example to mitigate potential threats like directory traversal. I would like to throw my +1 behind this.

**Comment by Rugvip** [comment]
See [this comment](https://github.com/backstage/backstage/pull/18296#pullrequestreview-1485795051) for what our concerns are with this capability.

We'd love to add this feature, just need to do it in a safe way. We're open to suggestions.

**Comment by jessesanford** [comment]
What if we simply started with a configurable white list of locations that are allowed to be included from. We could make use of the existing backend: reading: key in the app-config. Something like:

```
backend:
  reading:
    allow:
      # The following would be relative to the backstage root and allow files within it
      - file: ./foo/*
      # The following would allow files below bar recursively
      - file: ./bar/**/*
      # The following would allow files within the absolute path
      - /var/app/backstage/baz/
```
