### ISSUE TITLE
🚀 Feature: Upload Files through Software Templates 

### ISSUE THREAD

**Issue by aswathysen** [backstage/backstage#18704]
### 🔖 Feature description

Enable a requestor to upload a file through software template, 

### 🎤 Context

is it possible using reactJson Schema that enables uploading a file.

### ✌️ Possible Implementation

Depends on feasibilty

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by benjdlambert** [comment]
see #12912

**Comment by CarlosPet** [comment]
> see #12912

Hi! the page for discussion 12912 now results in 404. could someone help out with where to read about file uploads through software templates?
https://github.com/backstage/backstage/discussions/12912

**Comment by benjdlambert** [comment]
@CarlosPet, There's some examples here: https://rjsf-team.github.io/react-jsonschema-form/ under `Files`.

In short, you'd need to do something like:

```yaml
parameters:
  myYamlFile:
    type: string
    format: data-url
    title: Pick a yaml file
    ui:options:
      accept: .yaml
```
  
And then you will get a `base64` `dataUrl` that you should parse in the the action with the file contents.

**Comment by CarlosPet** [comment]
> @CarlosPet, There's some examples here: https://rjsf-team.github.io/react-jsonschema-form/ under `Files`.
> 
> In short, you'd need to do something like:
> 
> ```yaml
> parameters:
>   myYamlFile:
>     type: string
>     format: data-url
>     title: Pick a yaml file
>     ui:options:
>       accept: .yaml
> ```
> 
> And then you will get a `base64` `dataUrl` that you should parse in the the action with the file contents.

thanks, in case anyone else comes to this page from google (like I did) to handle multiple files you can use an array like this:
```yaml
        docs:
          title: Docs
          type: array
          description: ''
          items:
            type: string
            format: data-url
          ui:backstage:
            review:
              show: false
```

I published this on the discord too but this is causing a follow up issue: it cannot handle more than 10MB or so, when I upload two 10MB files it breaks with a `Backend request failed, 413 Payload Too Large` error.

Is there any standard/accepted way to make it handle bigger files?
