### ISSUE TITLE
🐛 Bug Report: Search module - ElasticSearch - does not replace ENV variables in config for auth.user and auth.password

### ISSUE THREAD

**Issue by Vity01** [backstage/backstage#18722]
### 📜 Description

If I define username&password using auth section, the variables are not replaced with their values (`ELASTICSEARCH_INDEX_PREFIX` and `ELASTICSEARCH_HOST` works correctly). 
```
search:
  elasticsearch:
    indexPrefix: ${ELASTICSEARCH_INDEX_PREFIX}
    node: ${ELASTICSEARCH_HOST}
    auth:
      username: ${ELASTICSEARCH_USER)
      password: ${ELASTICSEARCH_PASSWORD) 
```
This set up works - I had to use ELASTICSEARCH_HOST with username and password included (https://username:password@host:9200) format:
```
search:
  elasticsearch:
    indexPrefix: ${ELASTICSEARCH_INDEX_PREFIX}
    node: ${ELASTICSEARCH_HOST}

```

### 👍 Expected behavior

Env variables under `auth` section should be replaced first before value is used.

### 👎 Actual Behavior with Screenshots

Env variables are not used/replaced before first connection.

### 👟 Reproduction steps

Define search Elastic configuration as mentioned in the description. Username and password is not used.

### 🖥️ Your Environment

1.15

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!
