### ISSUE TITLE
🚀 Feature: Recursive placeholder substitution

### ISSUE THREAD

**Issue by joanayma** [backstage/backstage#18768]
### 🔖 Feature description

I have a template.yaml file that has references to another yaml:
```yaml
apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: template-test
spec:
  type: service
  parameters:
    - title: parameters test
      properties:
        test_object:
          type: object
          anyOf:
            - $yaml: ./template.d/test_object_1.yaml
            - $yaml: ./template.d/test_object_2.yaml
# [TRUNCATED]
```
In `./template.d/test_object_1.yaml` contents has a also a `$yaml` placeholder:
```yaml
title: Object 1
properties:
  feature_1_options:
    title: feature options for object 1
    type: object
    anyOf:
      - $yaml: ./template.d/test_object_1.d/feature_1/option_1.yaml
      - $yaml: ./template.d/test_object_1.d/feature_1/option_2.yaml
# [TRUNCATED]
```
In `./template.d/test_object_1.d/feature_1/option_1.yaml` contents are:
```yaml
title: Object 1 feature 1 option 1
properties:
  name:
    type: string
  another_value_example:
    type: string
# [ TRUNCATED]
```

The `./template.d/test_object_1.yaml` is properly read and rendered, but `./template.d/test_object_1.d/feature_1/option_1.yaml` is not. Backstage returns an schema similar to:
```json
{
  "steps": [
    {
        "title": "parameters test",
        "schema": {
          "title": "parameters test",
          "properties": {
             "Object 1": {
                "title": "Object 1",
                "type": "object",
                "anyOf": [
                   {
                      "$yaml": "./template.d/test_object_1.d/feature_1/option_1.yaml"
                   },
                   {
                      "$yaml": "./template.d/test_object_1.d/feature_1/option_2.yaml"
                   }
                ]
             }
          }
       }
    }
  ]
}
```
The second `$yaml` placeholder is not processed. I would need to process all the subreferences.

### 🎤 Context

It's not impeding anything, but we have several service options for example deployment. Allowing to separate it by files will be clearer to understand the templates.

### ✌️ Possible Implementation

I understand that this need to implemented in `yamlPlaceholderResolver` in `plugins/catalog-backend/src/modules/core/PlaceholderProcessor.ts` but I will need to check further if a PR is requested. Help here is wielcome :)

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!
