### ISSUE TITLE
🐛 Bug Report: publish:gitlab Produces an empty repository on self hosted gitlab

### ISSUE THREAD

**Issue by klmmmv** [backstage/backstage#18807]
### 📜 Description

The template step publish:gitlab creates an empty repository on our on premise gitlab instance.

I found a similar issues:
- #18283 
but the provided solution did not help for the publish:gitlab action.

This bug report seems to be the same issue with a merged PR, but I still get the issue:
- #4133 

### 👍 Expected behavior

A repository on our on premise gitlab instance is created with the rendered content of a skeleton repository which we define in the fetch:template step in the template.

### 👎 Actual Behavior with Screenshots

The repository is created, but it is empty.
While the fetch step gives me this output:
```
[1](http://localhost:7007/create/tasks/1be8e798-bf17-41ee-ba0e-3337f9d07fa8#line-1)2023-07-26T12:31:46.810Z Beginning step Fetch Jenkins Template
[2](http://localhost:7007/create/tasks/1be8e798-bf17-41ee-ba0e-3337f9d07fa8#line-2)2023-07-26T12:31:46.817Z info: Fetching template content from remote URL
[3](http://localhost:7007/create/tasks/1be8e798-bf17-41ee-ba0e-3337f9d07fa8#line-3)2023-07-26T12:31:47.196Z info: Listing files and directories in template
[4](http://localhost:7007/create/tasks/1be8e798-bf17-41ee-ba0e-3337f9d07fa8#line-4)2023-07-26T12:31:47.201Z info: Processing 3 template files/directories with input values {"descriptiveName":"Best Jenkins in Town","repoUrl":"http://gitlab.example.com?owner=idp&repo=mytest-jenkinsssss"}
[5](http://localhost:7007/create/tasks/1be8e798-bf17-41ee-ba0e-3337f9d07fa8#line-5)2023-07-26T12:31:47.213Z info: Writing file README.md to template output path with mode 33188.
[6](http://localhost:7007/create/tasks/1be8e798-bf17-41ee-ba0e-3337f9d07fa8#line-6)2023-07-26T12:31:47.217Z info: Writing file jenkins-application.yml to template output path with mode 33188.
[7](http://localhost:7007/create/tasks/1be8e798-bf17-41ee-ba0e-3337f9d07fa8#line-7)2023-07-26T12:31:47.218Z info: Writing file jenkins-values.yml to template output path with mode 33188.
[8](http://localhost:7007/create/tasks/1be8e798-bf17-41ee-ba0e-3337f9d07fa8#line-8)2023-07-26T12:31:47.219Z info: Template result written to /tmp/1be8e798-bf17-41ee-ba0e-3337f9d07fa8
[9](http://localhost:7007/create/tasks/1be8e798-bf17-41ee-ba0e-3337f9d07fa8#line-9)2023-07-26T12:31:47.221Z Finished step Fetch Jenkins Template
```
Where I can see my three files, which are in the specified path provided in the fetch step.

The debug step which should list my workspace, gives an empty response:
```
[1](http://localhost:7007/create/tasks/1be8e798-bf17-41ee-ba0e-3337f9d07fa8#line-1)2023-07-26T12:31:47.222Z Beginning step List workspace
[2](http://localhost:7007/create/tasks/1be8e798-bf17-41ee-ba0e-3337f9d07fa8#line-2)2023-07-26T12:31:47.223Z info: {}
[3](http://localhost:7007/create/tasks/1be8e798-bf17-41ee-ba0e-3337f9d07fa8#line-3)2023-07-26T12:31:47.223Z Finished step List workspace
```

The actual publish:gitlab step produces the following output and gives a 404 error:
```
12023-07-27T12:16:29.834Z Beginning step Publish
22023-07-27T12:16:30.816Z info: Init git repository {dir=/tmp/a498f2c8-3f6f-4145-858a-f0e669da3162/}
32023-07-27T12:16:30.822Z info: Adding file {dir=/tmp/a498f2c8-3f6f-4145-858a-f0e669da3162/,filepath=.}
42023-07-27T12:16:30.837Z info: Committing file to repo {dir=/tmp/a498f2c8-3f6f-4145-858a-f0e669da3162/,message=Setup project from Backstage}
52023-07-27T12:16:30.846Z info: Creating new remote {dir=/tmp/a498f2c8-3f6f-4145-858a-f0e669da3162/,remote=origin,url=http://gitlab.example.com/idp/mytest-jenkins.git}
62023-07-27T12:16:30.849Z info: Pushing directory to remote {dir=/tmp/a498f2c8-3f6f-4145-858a-f0e669da3162/,remote=origin}
72023-07-27T12:16:31.236Z error: Failed to push to repo {dir=/tmp/a498f2c8-3f6f-4145-858a-f0e669da3162/, remote=origin}
82023-07-27T12:16:31.236Z Error: HTTP Error: 404 Not Found {data={"statusCode":404,"statusMessage":"Not Found"}}
9    at _Git.push (/app/node_modules/@backstage/backend-common/dist/index.cjs.js:2034:15)
10    at processTicksAndRejections (node:internal/process/task_queues:96:5)
11    at async initRepoAndPush (/app/node_modules/@backstage/plugin-scaffolder-backend/dist/cjs/ScaffolderEntitiesProcessor-d9bc7a90.cjs.js:1332:3)
12    at async Object.handler (/app/node_modules/@backstage/plugin-scaffolder-backend/dist/cjs/ScaffolderEntitiesProcessor-d9bc7a90.cjs.js:4638:28)
13    at async NunjucksWorkflowRunner.executeStep (/app/node_modules/@backstage/plugin-scaffolder-backend/dist/cjs/ScaffolderEntitiesProcessor-d9bc7a90.cjs.js:5789:7)
14    at async NunjucksWorkflowRunner.execute (/app/node_modules/@backstage/plugin-scaffolder-backend/dist/cjs/ScaffolderEntitiesProcessor-d9bc7a90.cjs.js:5854:9)
15    at async TaskWorker.runOneTask (/app/node_modules/@backstage/plugin-scaffolder-backend/dist/cjs/ScaffolderEntitiesProcessor-d9bc7a90.cjs.js:6069:26)
16    at async run (/app/node_modules/p-queue/dist/index.js:163:29)
```

### 👟 Reproduction steps

app-config.yml:
```
     integrations:
      gitlab:
        - host: gitlab.example.com
          token: a-token
          apiBaseUrl: https://gitlab.example.com/api/v4
          baseUrl: https://gitlab.example.com/

```

template.yml:
```
   parameters:
    - title: Setup your Jenkins Instance
      required:
        - descriptiveName
        - repoUrl
      properties:
        descriptiveName:
          type: string
        repoUrl:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - gitlab.example.com

  steps:
    - id: fetch-template
      name: Fetch Jenkins Template
      action: fetch:template
      input:
        url: https://gitlab.example.com/group/project/-/tree/main/
        targetPath: ./
        values:
          repoUrl: ${{ parameters.repoUrl }}
          descriptiveName: ${{ parameters.descriptiveName }}

    - id: debug
      name: List workspace
      action: debug:log
      listWorkspace: true

    - id: publish
      name: Publish
      action: publish:gitlab
      input:
        allowedHosts: ['gitlab.example.com']
        repoUrl: "${{ parameters.repoUrl }}"
        repoVisibility: public
        sourcePath: ./
        targetPath: ./
        gitCommitMessage: "Setup project from Backstage"
        defaultBranch: "main"
        gitAuthorName: "my-technical-user"
        gitAuthorEmail: "my-technical-user@bearingpoint.com"
```

### 📃 Provide the context for the Bug.

I am using the official backstage:latest container image.

### 👀 Have you spent some time to check if this bug has been raised before?

- [x] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, I don't have time to work on this right now

**Comment by klmmmv** [comment]
Thanks for your feedback. I tried that with the same result. The following is the structure of my repository where my backstage template ist located. Where `jenkins-template.yml` is obviously my backstage template file and the `jenkins-skeleton` is the to be fetched template/skeleton directory which shall be fetched and rendered by the templating engine.

```
└── backstage
    ├── README.md
    └── templates
        ├── jenkins-skeleton
        │   ├── README.md
        │   ├── jenkins-application.yml
        │   └── jenkins-values.yml
        └── jenkins_template.yml
```

I tried it as you suggested with the updated fetch step:
```
  steps:
    - id: fetch-template
      name: Fetch Jenkins Template
      action: fetch:template
      input:
        url: ./jenkins-skeleton
        values:
          repoUrl: ${{ parameters.repoUrl }}
          descriptiveName: ${{ parameters.descriptiveName }}
```
which again gives me a positive feedback, that all three files from the `jenkins-skeleton` directory have been fetched.

```
info: Writing file [README.md, Opens in a new window](http://readme.md/) to template output path with mode 33188.
info: Writing file jenkins-application.yml to template output path with mode 33188.
info: Writing file jenkins-values.yml to template output path with mode 33188.
```

But in the debug step I can see that nothing is in the workspace.

**Comment by Rugvip** [comment]
Ah, the debug step needs to have it's input passed in through `input`:

```yaml
    - id: debug
      name: List workspace
      action: debug:log
      input:
        listWorkspace: true
```

If you're using `gitlab.example.com` as the actual GitLab host that's gonna explain the 404
