### ISSUE TITLE
🐛 Bug Report: Sentry plugin fails "Missing required config value at 'sentry.organization'"

### ISSUE THREAD

**Issue by ichasco-heytrade** [backstage/backstage#18879]
### 📜 Description

Sentry plugin doesn't find the organization. I have added it in `app-config.yaml` following this [tutorial](https://github.com/backstage/backstage/tree/master/plugins/sentry)

The error:

```
Error: Missing required config value at 'sentry.organization'
    at E.getString (https://backstage.XXXXX/static/module-backstage.aa1cee7f.js:9:32359)
    at Object.factory (https://backstage.XXXXX/static/module-backstage.aa1cee7f.js:61:38234)
    at rt.load (https://backstage.XXXXX/static/module-backstage.aa1cee7f.js:9:35074)
    at rt.get (https://backstage.XXXXX/static/module-backstage.aa1cee7f.js:9:34829)
    at t (https://backstage.XXXXX/static/module-backstage.aa1cee7f.js:40:86333)
    at tt (https://backstage.XXXXX/static/module-backstage.aa1cee7f.js:61:37418)
    at Gl (https://backstage.XXXXX/static/module-react-dom.d69a898f.js:12:52799)
    at hs (https://backstage.XXXXX/static/module-react-dom.d69a898f.js:16:8596)
    at cs (https://backstage.XXXXX/static/module-react-dom.d69a898f.js:16:930)
    at Za (https://backstage.XXXXX/static/module-react-dom.d69a898f.js:16:861)
```

### 👍 Expected behavior

It should work following the plugin tutorial

### 👎 Actual Behavior with Screenshots

It actually doesn't work. It complains about the missing organization

### 👟 Reproduction steps

Follow all the steps of the tutorial

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by adamdmharvey** [comment]
In the read me, step 3 says "add the proxy config" but the example adds both a proxy config *and* the sentry.organization config key. Just to triple check, Can you confirm you've added it ? Wonder if the instructions could use a bit of improvement.

**Comment by ichasco-heytrade** [comment]
Hi @adamdmharvey 

Yes, I have configured the proxy and the organization. And also I have tested adding the organization in the annotations of the component.

```
      sentry:
        organization: XXXXXXXX

      proxy:
        '/sentry/api':
          target: https://sentry.io/api/
          allowedMethods: ['GET']
          headers:
            Authorization: Bearer ${SENTRY_TOKEN}
```

Also I have tested the token doing a curl to sentry's API to get the info of the project.

I have run the `config:check` with the strict mode I have several errors, but most of them are in plugins that are working.

```
Error: Configuration does not match schema

  Config must NOT have additional properties { additionalProperty=organization } at 
  Config must NOT have additional properties { additionalProperty=sentry } at 
  Config must NOT have additional properties { additionalProperty=sonarqube } at 
  Config must NOT have additional properties { additionalProperty=argocd } at 
  Config must NOT have additional properties { additionalProperty=host } at /backend/database/connection
  Config must NOT have additional properties { additionalProperty=port } at /backend/database/connection
  Config must NOT have additional properties { additionalProperty=user } at /backend/database/connection
  Config must be string { type=string } at /backend/database/connection
  Config must match a schema in anyOf {  } at /backend/database/connection
  Config must NOT have additional properties { additionalProperty=providers } at /catalog
  Config must NOT have additional properties { additionalProperty=PRIVATE-TOKEN } at /proxy//gitlabci/headers
  Config must be string { type=string } at /proxy//gitlabci
  Config must match a schema in anyOf {  } at /proxy//gitlabci
  Config must NOT have additional properties { additionalProperty=secure } at /proxy//argocd/api
  Config must be string { type=string } at /proxy//argocd/api
  Config must match a schema in anyOf {  } at /proxy//argocd/api
  Config must NOT have additional properties { additionalProperty=auth } at /proxy//sonarqube
  Config must be string { type=string } at /proxy//sonarqube
  Config must match a schema in anyOf {  } at /proxy//sonarqube

```

**Comment by ichasco-heytrade** [comment]
I am having the same issue in all plugins that don't have backend config.
* Sentry
* Grafana
* Opsgenie

My configuration 
```
Loaded config from app-config-from-configmap.yaml, env
app:
  title: xxxxx Backstage
  baseUrl: https://backstage.xxxxx
backend:
  baseUrl: https://backstage.xxxxx
  listen:
    port: 7007
  csp:
    connect-src:
      - "'self'"
      - "http:"
      - "https:"
  database:
    client: pg
    connection:
      host: postgresql.xxxxx
      port: "5432"
      user: xxxxx
      password: <secret>
    plugin:
      auth:
        connection:
          database: backstage_auth
      catalog:
        connection:
          database: backstage_plugin_catalog
organization:
  name: xxxxx
sentry:
  organization: xxxxx
sonarqube:
  baseUrl: https://sonar.xxxxx
  apiKey: xxxxx
proxy:
  /sentry/api:
    target: https://sentry.io/api/
    allowedMethods:
      - GET
    headers:
      Authorization: <secret>
  /gitlabci:
    target: https://gitlab.com/api/v4
    allowedMethods:
      - GET
    headers:
      PRIVATE-TOKEN: xxxxx
  /argocd/api:
    target: https://argocd.xxxxx/api/v1/
    changeOrigin: true
    secure: false
    headers:
      Authorization: <secret>
  /sonarqube:
    target: https://sonar.xxxxx/api
    allowedMethods:
      - GET
    auth: xxxxx
  /grafana/api:
    target: https://grafana.xxxxx/
    headers:
      Authorization: <secret>
  /opsgenie/api:
    target: https://api.eu.opsgenie.com
    headers:
      Authorization: <secret>
opsgenie:
  domain: https://xxxxx.app.eu.opsgenie.com
argocd:
  appLocatorMethods:
    - type: config
      instances:
        - name: devops
          url: https://argocd.xxxxx
          token: xxxxx
grafana:
  domain: https://grafana.xxxxx/
  unifiedAlerting: "false"
techdocs:
  builder: local
  generator:
    runIn: local
  publisher:
    type: local
integrations:
  gitlab:
    - host: gitlab.com
      token: <secret>
auth:
  environment: production
  providers:
    google:
      production:
        clientId: xxxxx
        clientSecret: <secret>
catalog:
  rules:
    - allow:
        - Component
        - API
        - Location
        - Template
  providers:
    gitlab:
      gitlab_xxxxx_catalog:
        host: gitlab.com
        orgEnabled: true
        group: xxxxx
        groupPattern: "[\\s\\S]*"
        branch: main
        fallbackBranch: master
        entityFilename: catalog-info.yaml
        schedule:
          frequency:
            minutes: 30
          timeout:
            minutes: 3
      gitlab_xxxxx_api:
        host: gitlab.com
        orgEnabled: true
        group: xxxxx/backend
        groupPattern: "[\\s\\S]*"
        branch: main
        fallbackBranch: master
        entityFilename: api-info.yaml
        schedule:
          frequency:
            minutes: 30
          timeout:
            minutes: 3
  locations:
    - type: url
      target: https://gitlab.com/xxxxx/devops/backstage/-/blob/main/groups.yaml
      rules:
        - allow:
            - Group
```
I am deploying it in kubernetes cluster

Thanks!
