### ISSUE TITLE
🚀 Feature: support multiple instances of the same authentication provider

### ISSUE THREAD

**Issue by ConnorDY** [backstage/backstage#18887]
### 🔖 Feature description

Currently, Backstage only supports 1 authentication provider of each type.
For example, you can't register 2 GitHub auth providers to allow users to login using both GitHub.com and an enterprise GitHub instance.

It would be nice if we could register 2 auth providers of the same type, such as GitHub or Azure.

### 🎤 Context

Right now there's no way to authenticate using both GitHub.com and a GitHub Enterprise instance.

In our Backstage instance, we have components registered in the catalog coming from both GitHub.com and our GitHub Enterprise instance.

We have components on the component entity page that use `githubAuthApi.getAccessToken()` to grab an OAuth token for fetching information about the GitHub repo to display.

Because Backstage does not currently support multiple GitHub authentication providers, this functionality breaks for components that come from a GitHub instance that does not have a corresponding auth provider.

### ✌️ Possible Implementation

If you try to register multiple auth providers of the same type (by giving each one a unique key in the YAML and JS object), the frontend defaults to using the first matching auth provider of the same type from the list of `ProviderFactories` supplied in `auth.ts`.

Currently the key used for the `ProviderFactories` object is only used by the backend for determining where in the config to look for the given auth provider's config. I'd suggest adding an optional way to specify this key from the frontend side.

Additionally, GitHub Auth API's `getAccessToken()` method would need to be updated to support using the right auth provider based on the source location for a given component entity.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by ConnorDY** [comment]
> You could make one of your own perhaps, like a class + interface that accepts a URL and chooses among several underlying OAuthApi implementations based on that URL. Then have your components consume that one instead of just one single ref

Could you point me at some docs and/or code to help me get started with this?
I'd be happy to contribute this back once I get it working. 🙂

**Comment by freben** [comment]
We talked a bit about this ticket. There's the [`scmAuthApiRef`](https://github.com/backstage/backstage/blob/e2cff79671cbc4e9c439c2447d4844d154f9432c/packages/integration-react/src/api/ScmAuthApi.ts#L97) which can be used, that I should have remembered already in the first comment. Its API accepts a target URL of the resource to access, so it's able to pick among all the registered integrations to find the right one.

Not many plugins leverage it at this point. But if they do, they will automatically get access to all of the existing integrations, including both your public and private github ones.

**Comment by regicsolutions** [comment]
@ConnorDY we were looking to also do the same thing, wondering if you had any luck?

**Comment by SuperCoolAlan** [comment]
I just spent some time showing myself that we can't work around this with a forward proxy. While employing the forward proxy _did_ allow the auth provider to be aware of different tokens for the same domain name, not all plugins become aware of the reverse proxy and thus populating catalog items sourced from two organizations hosted on GitHub was not successful. Instead, the repository discovery plugin was able to create a Location in the catalog but following processing was still linked to use `github.com` via its [`spec.target` field](https://github.com/backstage/backstage/blob/890e98344099d809b3c0b1005a79e2f4dba98b0a/plugins/catalog-backend-module-github/src/processors/GithubDiscoveryProcessor.ts#L154).

Here's a diagram of the forward proxy config I used to test this:
![image](https://github.com/user-attachments/assets/23b3f80a-efe4-48e3-aa1a-9550d9c8afdf)

And the app-config.yaml I used to test it with
```yaml
    integrations:
      github:
        - host: nginx:3400 #forward-proxy for FIRST org
          apiBaseUrl: http://nginx:3500 # forward-proxy for api.github.com
          token: ${GITHUB_FIRST_PAT_TOKEN}
        - host: nginx:3401 #forward-proxy for SECOND org
          apiBaseUrl: http://nginx:3500 # forward-proxy for api.github.com
          token: ${GITHUB_SECOND_PAT_TOKEN}
    catalog:
      providers:
        github:
          firstOrgRepos:
            host: nginx:3400
            organization: 'firstorg' 
            catalogPath: '/catalog-info.yaml' 
            filters:
              branch: 'main'
              repository: '.*' # Regex
            schedule:
              frequency: { minutes: 5 }
              timeout: { minutes: 4 }
              initialDelay: { seconds: 8 }
          secondOrgRepos:
            host: nginx:3401
            organization: 'secondorg' 
            catalogPath: '/catalog-info.yaml' 
            filters:  
              branch: 'main'
              repository: '.*' # Regex
            schedule:
              frequency: { minutes: 5 }
              timeout: { minutes: 4 }
              initialDelay: { seconds: 7 }
```
