### ISSUE TITLE
🚀 Feature: ability to specify provided and consumed API endpoints

### ISSUE THREAD

**Issue by igord** [backstage/backstage#18893]
### 🔖 Feature description

A standard way to specify API endpoints that are provided or consumed by components.

### 🎤 Context

Software components rarely consume all endpoints declared in API spec.
Sometimes service components provide only subset of endpoints from the whole API spec.

If API spec contains many endpoints, it is useful to know which subset is needed for a consumer of API to function.

### ✌️ Possible Implementation

```yaml
spec:
  providesApis:
    - name: wayback-search
      path: /search
      verb: get
  consumesApis:
    - name: wayback-archive
      path: /article/{id}
      verb: get
```

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!
