### ISSUE TITLE
🐛 Bug Report: Backend failed to start up Error: Invalid configuration schema in node_modules/@backstage/plugin-proxy-backend/config.d.ts

### ISSUE THREAD

**Issue by shoeletz** [backstage/backstage#19463]
### 📜 Description

Recently (without changes) I've been unable to start backstage with a proxy configured.

```
Backend failed to start up Error: Invalid configuration schema in node_modules/@backstage/plugin-proxy-backend/config.d.ts, the following definitions are not supported:                                                                                                                                                 
│                                                                                                                                                                                                                                                                                                                          
│   Partial<{[key:string]:string;Authorization:string;authorization:string;'X-Api-Key':string;'x-api-key':string;}>                                                                                                                                                                                                        
│     at /app/node_modules/@backstage/config-loader/dist/index.cjs.js:348:15                                                                                                                                                                                                                                               
│     at Array.map (<anonymous>)                                                                                                                                                                                                                                                                                           
│     at compileTsSchemas (/app/node_modules/@backstage/config-loader/dist/index.cjs.js:322:27)                                                                                                                                                                                                                            
│     at async collectConfigSchemas (/app/node_modules/@backstage/config-loader/dist/index.cjs.js:299:21)                                                                                                                                                                                                                  
│     at async Object.loadConfigSchema (/app/node_modules/@backstage/config-loader/dist/index.cjs.js:481:15)                                                                                                                                                                                                               
│     at async Object.createConfigSecretEnumerator (/app/node_modules/@backstage/backend-app-api/dist/index.cjs.js:195:18)                                                                                                                                                                                                 
│     at async Object.loadBackendConfig (/app/node_modules/@backstage/backend-common/dist/index.cjs.js:400:28)                                                                                                                                                                                                             
│     at async main (/app/packages/backend/dist/index.cjs.js:540:18)
```

Found related comments:
- https://github.com/backstage/backstage/issues/19443#issuecomment-1682596745
- https://stackoverflow.com/questions/76923143/backstage-failing-to-start-with-schema-error

### 👍 Expected behavior

Backstage should start.

### 👎 Actual Behavior with Screenshots

See description for startup error.

### 👟 Reproduction steps

No changes made, see context. Removing proxy config allows for app startup locally.

### 📃 Provide the context for the Bug.

The linked issue thread hinted it was due proxy configuration, although this has remained unchanged between builds:
```
proxy:
  "/firehydrant/api/services/":
    target: "https://api.firehydrant.io/v1/services/"
    changeOrigin: true
    headers:
      Authorization: ${BACKSTAGE_FIREHYDRANT_AUTH}
    allowedMethods: ["GET"]
    pathRewrite:
      "^/api/proxy/firehydrant/api/services/?": "/"
  "/firehydrant/api/incidents":
    target: "https://api.firehydrant.io/v1/incidents/"
    changeOrigin: true
    headers:
      Authorization: ${BACKSTAGE_FIREHYDRANT_AUTH}
    allowedMethods: ["GET"]
    pathRewrite:
      "^/api/proxy/firehydrant/api/incidents/?": "/"
  "/firehydrant/api/metrics":
    target: "https://api.firehydrant.io/v1/metrics/"
    changeOrigin: true
    headers:
      Authorization: ${BACKSTAGE_FIREHYDRANT_AUTH}
    allowedMethods: ["GET"]
    pathRewrite:
      "^/api/proxy/firehydrant/api/metrics/?": "/"
  "/pagerduty/services":
    target: https://api.pagerduty.com/services/
    headers:
      Authorization: ${BACKSTAGE_PAGERDUTY_AUTH}
    allowedMethods: ["GET"]
    pathRewrite:
      "^/api/proxy/pagerduty/services/?": "/"
  "/pagerduty/incidents":
    target: https://api.pagerduty.com/incidents/
    headers:
      Authorization: ${BACKSTAGE_PAGERDUTY_AUTH}
    allowedMethods: ["GET"]
    pathRewrite:
      "^/api/proxy/pagerduty/incidents/?": "/"
  "/pagerduty/oncalls":
    target: https://api.pagerduty.com/oncalls/
    headers:
      Authorization: ${BACKSTAGE_PAGERDUTY_AUTH}
    allowedMethods: ["GET"]
    pathRewrite:
      "^/api/proxy/pagerduty/oncalls/?": "/"
```

### 🖥️ Your Environment

```
node: v18.17.0
yarn: 1.22.19
cli:  0.22.9 (installed)
backstage:  1.15.0

Dependencies:
  @backstage/app-defaults                          1.4.1
  @backstage/backend-app-api                       0.4.5
  @backstage/backend-common                        0.19.1
  @backstage/backend-dev-utils                     0.1.1
  @backstage/backend-plugin-api                    0.5.4
  @backstage/backend-tasks                         0.5.4
  @backstage/catalog-client                        1.4.3
  @backstage/catalog-model                         1.4.1
  @backstage/cli-common                            0.1.12
  @backstage/cli-node                              0.1.2
  @backstage/cli                                   0.22.9
  @backstage/config-loader                         1.3.2
  @backstage/config                                1.0.8
  @backstage/core-app-api                          1.9.0
  @backstage/core-components                       0.13.3
  @backstage/core-plugin-api                       1.5.3
  @backstage/dev-utils                             1.0.17
  @backstage/errors                                1.2.1
  @backstage/eslint-plugin                         0.1.3
  @backstage/integration-aws-node                  0.1.5
  @backstage/integration-react                     1.1.15
  @backstage/integration                           1.5.1
  @backstage/plugin-api-docs                       0.9.6
  @backstage/plugin-app-backend                    0.3.47
  @backstage/plugin-auth-backend                   0.18.5
  @backstage/plugin-auth-node                      0.2.16
  @backstage/plugin-catalog-backend-module-github  0.3.2
  @backstage/plugin-catalog-backend                1.11.0
  @backstage/plugin-catalog-common                 1.0.15
  @backstage/plugin-catalog-graph                  0.2.32
  @backstage/plugin-catalog-import                 0.9.10
  @backstage/plugin-catalog-node                   1.4.0
  @backstage/plugin-catalog-react                  1.8.0
  @backstage/plugin-catalog                        1.12.0
  @backstage/plugin-events-node                    0.2.8
  @backstage/plugin-firehydrant                    0.2.4
  @backstage/plugin-github-actions                 0.6.1
  @backstage/plugin-home-react                     0.1.1
  @backstage/plugin-org                            0.6.10
  @backstage/plugin-pagerduty                      0.6.1
  @backstage/plugin-permission-common              0.7.7
  @backstage/plugin-permission-node                0.7.10
  @backstage/plugin-permission-react               0.4.14
  @backstage/plugin-proxy-backend                  0.2.41
  @backstage/plugin-scaffolder-backend             1.15.1
  @backstage/plugin-scaffolder-common              1.3.2
  @backstage/plugin-scaffolder-node                0.1.5
  @backstage/plugin-scaffolder-react               1.5.1
  @backstage/plugin-scaffolder                     1.14.1
  @backstage/plugin-search-backend-module-catalog  0.1.3
  @backstage/plugin-search-backend-module-pg       0.5.8
  @backstage/plugin-search-backend-module-techdocs 0.1.3
  @backstage/plugin-search-backend-node            1.2.3
  @backstage/plugin-search-backend                 1.3.3
  @backstage/plugin-search-common                  1.2.5
  @backstage/plugin-search-react                   1.6.3
  @backstage/plugin-search                         1.3.3
  @backstage/plugin-tech-radar                     0.6.6
  @backstage/plugin-techdocs-backend               1.6.4
  @backstage/plugin-techdocs-module-addons-contrib 1.0.15
  @backstage/plugin-techdocs-node                  1.7.3
  @backstage/plugin-techdocs-react                 1.1.8
  @backstage/plugin-techdocs                       1.6.5
  @backstage/plugin-user-settings                  0.7.5
  @backstage/release-manifests                     0.0.9
  @backstage/test-utils                            1.4.1
  @backstage/theme                                 0.4.1
  @backstage/types                                 1.1.0
  @backstage/version-bridge                        1.0.4
```

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!
