### ISSUE TITLE
🐛 Bug Report:  CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource

### ISSUE THREAD

**Issue by bharatnainani** [backstage/backstage#19503]
### 🔖 Need

I have deployed Backstage on an Amazon Ubuntu machine, Website is loading but it is giving an Error:**Could not fetch catalog entities**

and When I check the network tab it is giving cores ERROR
Access to fetch at 'http://<ec2-public-ip>/api/catalog/entity-facets?facet=metadata.tags' from origin 'http://<ec2-public-ip>:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

Below is my  **app-config.yaml** 

```
app:
  title: Scaffolded Backstage App
  baseUrl: http://0.0.0.0:3000

organization:
  name: My Company

backend:
  database:
    #auth:
    #keys:
    #   - secret: ${BACKEND_SECRET}
    # config options: https://node-postgres.com/apis/client
    client: pg
    connection:
      host: 127.0.0.1
      port: 5432
      user: postgres
      password: secret
      # https://node-postgres.com/features/ssl
      # ssl:
      #   host is only needed if the connection name differs from the certificate name.
      #   This is for example the case with CloudSQL.
      #   host: servername in the certificate
      #   ca:
      #     $file: <file-path>/server.pem
      #   key:
      #     $file: <file-path>/client.key
      #   cert:
      #     $file: <file-path>/client-cert.pem
  # Used for enabling authentication, secret is shared by all backend plugins
  # See https://backstage.io/docs/auth/service-to-service-auth for
  # information on the format
  # auth:
  #   keys:
  #     - secret: ${BACKEND_SECRET}
  baseUrl: http://<ec2-public-ip>:80
  listen:
    port: 80
    # Uncomment the following host directive to bind to specific interfaces
    # host: 127.0.0.1
    csp:
      connect-src: ["'self'", 'http:', 'https:']
    # Content-Security-Policy directives follow the Helmet format: https://helmetjs.github.io/#reference
    # Default Helmet Content-Security-Policy values can be removed by setting the key to false
    cors:
      origin: http://<ec2-public-ip>:3000
      methods: [GET, HEAD, PATCH, POST, PUT, DELETE]
      credentials: true
      Access-Control-Allow-Origin: '*'
  # This is for local development only, it is not recommended to use this in production
  # The production database configuration is stored in app-config.production.yaml
  #database:
  # client: better-sqlite3
  # connection: ':memory:'
  # workingDirectory: /tmp # Use this to configure a working directory for the scaffolder, defaults to the OS temp-dir

integrations:
  github:
    - host: github.com
      # This is a Personal Access Token or PAT from GitHub. You can find out how to generate this token, and more information
      # about setting up the GitHub integration here: https://backstage.io/docs/getting-started/configuration#setting-up-a-github-integration
      token: <github-token>
    ### Example for how to add your GitHub Enterprise instance using the API:
    # - host: ghe.example.net
    #   apiBaseUrl: https://ghe.example.net/api/v3
    #   token: ${GHE_TOKEN}
auth:
  experimentalExtraAllowedOrigins:
    - 'http://<ec2-public-ip>:3000'
  # see https://backstage.io/docs/auth/ to learn about auth providers
  providers:
    github:
      development:
        clientId: <client-id>
        clientSecret: <client-secret>

```

[
<img width="1476" alt="Screenshot 2023-08-22 at 7 05 29 PM" src="https://github.com/backstage/backstage/assets/51225875/04e3dc8a-154d-412c-b992-198f4b5d5423">
](url)

### 🎉 Proposal

I need help to solve this issue. I have tried multiple ways but nothing worked can you help me with this issue

### 👀 Have you spent some time to check if this RFC has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)
