### ISSUE TITLE
🐛 Bug Report: Unexpected form behaviour when using custom field extension for dynamic fields

### ISSUE THREAD

**Issue by lshwayne96** [backstage/backstage#19597]
### 📜 Description

I'm trying to build a custom field extension for dynamic fields in templates, such that a field can be auto-filled based on values in other fields while still being user-editable. Sample template below:
```
apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: dynamic-field
  title: Dynamic Field
  description: Dynamic Field extension test
spec:
  owner: test
  type: service
  parameters:
    - title: Step 1
      required:
        - field1
      properties:
        field1:
          title: Field 1
          type: string
          description: Field 1
        field2:
          title: Field 2
          type: string
          description: Depends on Field 1
          ui:field: DynamicField
          ui:options:
            template: ${{ field1 }}-hello
        field3:
          title: Field 3
          type: string
          description: Depends on Field 1
          ui:field: DynamicField
          ui:options:
            template: ${{ field1 }}-goodbye
  steps:
    - id: fetch
      name: Fetch
      action: fetch:template
      input:
        url: ./content
        values:
          name: ${{ parameters.field2 }}
```
This is my `DynamicField` component:
```
nunjucks.configure({
  autoescape: false,
  tags: {
    variableStart: '${{',
    variableEnd: '}}',
  },
});

export const DynamicField = (props: DynamicFieldProps) => {
  const {
    onChange,
    schema: { title = 'Dynamic Field', description = 'A dynamic field' },
    required,
    uiSchema,
    rawErrors,
    formData,
    formContext,
    idSchema,
  } = props;

  const template = uiSchema['ui:options']?.template ?? '';
  const formContextData = formContext.formData;
  const fieldValue = nunjucks.renderString(template, formContextData);

  useEffect(() => {
    onChange(fieldValue);
  }, [fieldValue]);

  return (
    <FormControl
      required={required}
      error={rawErrors?.length > 0 && !formData}
    >
      <TextField
        id={idSchema?.$id}
        label={title}
        helperText={description}
        required={required}
        value={formData ?? ''}
        onChange={e => onChange(e.target.value)}
      />
    </FormControl>
  );
};
```
The extension works fine when each field has at most one dependent. However, if a field has more than one dependent (as in the sample template above), only the last dependent gets updated to the correct value.

### 👍 Expected behavior

All dependent fields should be updated to their respective templated values.

### 👎 Actual Behavior with Screenshots

Only the last dependent field is updated to its templated value.

<img width="551" alt="image" src="https://github.com/backstage/backstage/assets/46807469/6936ed90-1b5a-441f-811b-d194ed991a3f">

### 👟 Reproduction steps

1. Select the Dynamic Field template in the Create page.
2. Input any value in Field 1.

### 📃 Provide the context for the Bug.

Some debugging findings:
1. The `useEffect` is triggered in both `field2` and `field3` with the correct `fieldValue` by any change in `field1`.
2. However, as each `onChange` is propagated upwards, the old `formData` is being used to set the new state. I suspect this causes all changes in the dependent fields to be erased except for the last one. Could this be related to https://github.com/rjsf-team/react-jsonschema-form/issues/513?

I apologise if this is not considered a bug or I should be using another approach instead.

### 🖥️ Your Environment
```
OS:   Linux 5.15.90.1-microsoft-standard-WSL2 - linux/x64
node: v18.16.1
yarn: 1.22.19
cli:  0.22.9 (installed)
backstage:  1.15.0

Dependencies:
  @backstage/app-defaults                            1.4.1
  @backstage/backend-app-api                         0.4.5
  @backstage/backend-common                          0.18.5, 0.19.1
  @backstage/backend-dev-utils                       0.1.1
  @backstage/backend-plugin-api                      0.5.4
  @backstage/backend-tasks                           0.5.4
  @backstage/catalog-client                          1.4.3
  @backstage/catalog-model                           1.4.1
  @backstage/cli-common                              0.1.12
  @backstage/cli-node                                0.1.2
  @backstage/cli                                     0.22.9
  @backstage/config-loader                           1.3.2
  @backstage/config                                  1.0.8
  @backstage/core-app-api                            1.9.0
  @backstage/core-components                         0.12.5, 0.13.3
  @backstage/core-plugin-api                         1.5.3
  @backstage/dev-utils                               1.0.17
  @backstage/errors                                  1.2.1
  @backstage/eslint-plugin                           0.1.3
  @backstage/integration-aws-node                    0.1.5
  @backstage/integration-react                       1.1.15
  @backstage/integration                             1.5.1
  @backstage/plugin-api-docs                         0.9.6
  @backstage/plugin-app-backend                      0.3.47
  @backstage/plugin-auth-backend                     0.17.4, 0.18.5
  @backstage/plugin-auth-node                        0.2.16
  @backstage/plugin-catalog-backend-module-gitlab    0.2.3
  @backstage/plugin-catalog-backend-module-ldap      0.5.14
  @backstage/plugin-catalog-backend                  1.11.0
  @backstage/plugin-catalog-common                   1.0.15
  @backstage/plugin-catalog-graph                    0.2.32
  @backstage/plugin-catalog-import                   0.9.10
  @backstage/plugin-catalog-node                     1.4.0
  @backstage/plugin-catalog-react                    1.8.0
  @backstage/plugin-catalog                          1.12.0
  @backstage/plugin-events-node                      0.2.8
  @backstage/plugin-github-actions                   0.6.1
  @backstage/plugin-org                              0.6.10
  @backstage/plugin-permission-backend               0.5.22
  @backstage/plugin-permission-common                0.7.7
  @backstage/plugin-permission-node                  0.7.10
  @backstage/plugin-permission-react                 0.4.14
  @backstage/plugin-proxy-backend                    0.2.41
  @backstage/plugin-scaffolder-backend-module-gitlab 0.2.2
  @backstage/plugin-scaffolder-backend               1.15.1
  @backstage/plugin-scaffolder-common                1.3.2
  @backstage/plugin-scaffolder-node                  0.1.5
  @backstage/plugin-scaffolder-react                 1.5.1
  @backstage/plugin-scaffolder                       1.14.1
  @backstage/plugin-search-backend-module-catalog    0.1.3
  @backstage/plugin-search-backend-module-pg         0.5.8
  @backstage/plugin-search-backend-module-techdocs   0.1.3
  @backstage/plugin-search-backend-node              1.2.3
  @backstage/plugin-search-backend                   1.3.3
  @backstage/plugin-search-common                    1.2.5
  @backstage/plugin-search-react                     1.6.3
  @backstage/plugin-search                           1.3.3
  @backstage/plugin-tech-radar                       0.6.6
  @backstage/plugin-techdocs-backend                 1.6.4
  @backstage/plugin-techdocs-module-addons-contrib   1.0.15
  @backstage/plugin-techdocs-node                    1.7.3
  @backstage/plugin-techdocs-react                   1.1.8
  @backstage/plugin-techdocs                         1.6.5
  @backstage/plugin-user-settings                    0.7.5
  @backstage/release-manifests                       0.0.9
  @backstage/test-utils                              1.4.1
  @backstage/theme                                   0.2.19, 0.4.1
  @backstage/types                                   1.1.0
  @backstage/version-bridge                          1.0.4
```
### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None
