### ISSUE TITLE
🐛 Bug Report: todo plugin - file url does not contain branch

### ISSUE THREAD

**Issue by joeunlog** [backstage/backstage#19894]
### 📜 Description

I set up todo plugin and add annotation to component about source-location.
todo plugin perfectly find todo object in source code, but the file link is not correct.
my source-location is dev branch, but file link is not dev.

### 👍 Expected behavior

`https://github.com/<org>/<repo>/tree/dev/<file>#L28`

### 👎 Actual Behavior with Screenshots

![Monosnap File not found 2023-09-12 13-52-14](https://github.com/backstage/backstage/assets/78069372/847220bc-3431-400f-9007-c15920da6e13)

### 👟 Reproduction steps

add annotation source-location like this.
```
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: demo
  annotations:
    backstage.io/kubernetes-label-selector: 'app=backstage'
    backstage.io/techdocs-ref: dir:.
    argocd/app-name: backstage
    github.com/project-slug: test/ttt
    backstage.io/source-location: url:https://github.com/test/ttt/tree/dev
spec:
  type: service # required
  lifecycle: experimental
  owner: test
  system: examples
  providesApis: [example-grpc-api]
```

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None
