### ISSUE TITLE
🚀 Feature: Possibility of using regex to filter catalog items

### ISSUE THREAD

**Issue by coutinhocaio** [backstage/backstage#19963]
### 🔖 Feature description

When using OwnerPicker or EntityPicker, it would be very useful to filter the result by the selected Kind. It is possible to do this using the catalogFilter property in ui:options, but currently only exactly what is in the text is returned. Using regex, you could further filter the options according to the needs of each template.

### 🎤 Context

In my case, for example, I would like to be able to filter only Groups that end with **"app"**
```yaml
parameters:
  - title: Fill in some steps
    required:
      - group
    properties:
      group:
        title: Group
        type: string
        description: user groups
        ui:field: OwnerPicker
        ui:options:
          defaultKind: Group
          catalogFilter:
            - kind: Group
              spec.type: team
              metadata.name: (app&)
          allowArbitraryValues: false
```
In **metadata.name** use the regex `(app&)` to return only those that end with **"app"**

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, I don't have time to work on this right now
