### ISSUE TITLE
🐛 Bug Report: LDAP integration errors do not log details with local running of Backstage

### ISSUE THREAD

**Issue by RochesterinNYC** [backstage/backstage#20003]
### 📜 Description

I run Backstage locally via:

```
LOG_LEVEL=debug yarn dev
```

with the following LDAP provider config set in my `app-config.yaml`:

```
ldap:
  providers:
    - target: ldaps://ldap.internalcompany.com
      bind:
        dn: uid=svc-internalcompany,ou=noemail,ou=service accounts,dc=internalcompany,dc=com
        secret: "stub"
      users:
        dn: ou=people,dc=internalcompany,dc=com
        options:
          filter: (uid=*)
        map:
          # The name of the attribute that holds the relative
          # distinguished name of each entry. This value is copied into a
          # well known annotation to be able to query by it later.
          rdn: uid
          # The name of the attribute that shall be used for the value of
          # the metadata.name field of the entity.
          name: uid
          # The name of the attribute that shall be used for the value of
          # the spec.profile.email field of the entity.
          email: mail
        set:
          metadata.customField: 'hello'
      groups:
        dn: ou=groups,dc=internalcompany,dc=com
        map:
          # The name of the attribute that holds the relative
          # distinguished name of each entry. This value is copied into a
          # well known annotation to be able to query by it later.
          rdn: cn
          # The name of the attribute that shall be used for the value of
          # the metadata.name field of the entity.
          name: cn
          # The name of the attribute that shall be used for the value of
          # the spec.profile.displayName field of the entity.
          displayName: cn
          # The name of the attribute that shall be used for the values of
          # the spec.children field of the entity.
          members: member
        set:
          metadata.customField: 'hello'
```

And the correct LDAP target set in `packages/backend/src/plugins/catalog.ts`.

I get an error with the LDAP integration provider, but no logged details as to the nature of the error.

```
[1] 2023-09-18T20:24:22.090Z backstage debug task: LdapOrgEntityProvider:our-ldap-master:refresh configured to run at: CURRENT_TIMESTAMP type=taskManager task=LdapOrgEntityProvider:our-ldap-master:refresh
[1] 2023-09-18T20:24:22.090Z backstage info Task worker starting: LdapOrgEntityProvider:our-ldap-master:refresh, {"version":2,"cadence":"PT60M","timeoutAfterDuration":"PT15M"} type=taskManager task=LdapOrgEntityProvider:our-ldap-master:refresh
[1] 2023-09-18T20:24:22.092Z catalog info Reading LDAP users and groups type=plugin target=ldaps://ldap.pinadmin.com class=LdapOrgEntityProvider taskId=LdapOrgEntityProvider:our-ldap-master:refresh taskInstanceId=fc3d0bdf-e730-46df-9f22-75ffab5502da
[1] 2023-09-18T20:24:22.266Z catalog error LdapOrgEntityProvider:our-ldap-master refresh failed type=plugin target=ldaps://ldap.internalcompany.com class=LdapOrgEntityProvider taskId=LdapOrgEntityProvider:our-ldap-master:refresh taskInstanceId=fc3d0bdf-e730-46df-9f22-75ffab5502da
[1] 2023-09-18T20:24:22.267Z backstage debug task: LdapOrgEntityProvider:our-ldap-master:refresh will next occur around 2023-09-18T17:24:22.266-04:00 type=taskManager task=LdapOrgEntityProvider:our-ldap-master:refresh
```

### 👍 Expected behavior

More details about the error should be logged for debugging purposes.

The password is "stub" because our internal LDAP server does not require a secret or auth to be passed through when querying. If this is the issue though, I would expect the error logs to reflect that (it's also worth noting that `bind.secret` is a required field and cannot be empty).

### 👎 Actual Behavior with Screenshots

Relevant local run logs:

```
[1] 2023-09-18T20:24:22.090Z backstage debug task: LdapOrgEntityProvider:our-ldap-master:refresh configured to run at: CURRENT_TIMESTAMP type=taskManager task=LdapOrgEntityProvider:our-ldap-master:refresh
[1] 2023-09-18T20:24:22.090Z backstage info Task worker starting: LdapOrgEntityProvider:our-ldap-master:refresh, {"version":2,"cadence":"PT60M","timeoutAfterDuration":"PT15M"} type=taskManager task=LdapOrgEntityProvider:our-ldap-master:refresh
[1] 2023-09-18T20:24:22.092Z catalog info Reading LDAP users and groups type=plugin target=ldaps://ldap.pinadmin.com class=LdapOrgEntityProvider taskId=LdapOrgEntityProvider:our-ldap-master:refresh taskInstanceId=fc3d0bdf-e730-46df-9f22-75ffab5502da
[1] 2023-09-18T20:24:22.266Z catalog error LdapOrgEntityProvider:our-ldap-master refresh failed type=plugin target=ldaps://ldap.internalcompany.com class=LdapOrgEntityProvider taskId=LdapOrgEntityProvider:our-ldap-master:refresh taskInstanceId=fc3d0bdf-e730-46df-9f22-75ffab5502da
[1] 2023-09-18T20:24:22.267Z backstage debug task: LdapOrgEntityProvider:our-ldap-master:refresh will next occur around 2023-09-18T17:24:22.266-04:00 type=taskManager task=LdapOrgEntityProvider:our-ldap-master:refresh
```

### 👟 Reproduction steps

Follow guidelines at https://backstage.io/docs/integrations/ldap/org/ to set up LDAP integration.

Run locally via `LOG_LEVEL=debug yarn dev`.

### 📃 Provide the context for the Bug.

It's not possible to tell from these current error logs why the LDAP integration isn't working.

### 🖥️ Your Environment

```
% yarn backstage-cli info                                                                                              ✹
OS:   Darwin 22.6.0 - darwin/arm64
node: v16.16.0
yarn: 3.6.3
cli:  0.22.12 (installed)
backstage:  1.17.5

Dependencies:
  @backstage/app-defaults                          1.4.2
  @backstage/backend-app-api                       0.5.2
  @backstage/backend-common                        0.19.4
  @backstage/backend-dev-utils                     0.1.1
  @backstage/backend-openapi-utils                 0.0.3
  @backstage/backend-plugin-api                    0.6.2
  @backstage/backend-tasks                         0.5.7
  @backstage/catalog-client                        1.4.3
  @backstage/catalog-model                         1.4.1
  @backstage/cli-common                            0.1.12
  @backstage/cli-node                              0.1.3
  @backstage/cli                                   0.22.12
  @backstage/config-loader                         1.4.0
  @backstage/config                                1.0.8, 1.1.0-next.0
  @backstage/core-app-api                          1.10.0-next.1, 1.9.1, 1.10.0-next.0
  @backstage/core-components                       0.13.4, 0.13.5-next.0
  @backstage/core-plugin-api                       1.5.3, 1.6.0-next.1, 1.6.0-next.0
  @backstage/dev-utils                             1.0.20
  @backstage/errors                                1.2.1
  @backstage/eslint-plugin                         0.1.3
  @backstage/integration-aws-node                  0.1.5
  @backstage/integration-react                     1.1.18
  @backstage/integration                           1.6.2
  @backstage/plugin-api-docs                       0.9.10
  @backstage/plugin-app-backend                    0.3.50
  @backstage/plugin-app-node                       0.1.2
  @backstage/plugin-auth-backend                   0.18.8
  @backstage/plugin-auth-node                      0.2.19
  @backstage/plugin-catalog-backend-module-ldap    0.5.17
  @backstage/plugin-catalog-backend                1.12.4
  @backstage/plugin-catalog-common                 1.0.15
  @backstage/plugin-catalog-graph                  0.2.35
  @backstage/plugin-catalog-import                 0.9.13
  @backstage/plugin-catalog-node                   1.4.3
  @backstage/plugin-catalog-react                  1.8.3
  @backstage/plugin-catalog-unprocessed-entities   0.1.2
  @backstage/plugin-catalog                        1.12.4
  @backstage/plugin-devtools-backend               0.1.5
  @backstage/plugin-devtools-common                0.1.3
  @backstage/plugin-devtools                       0.1.3
  @backstage/plugin-events-node                    0.2.11
  @backstage/plugin-github-actions                 0.6.4
  @backstage/plugin-org                            0.6.13
  @backstage/plugin-permission-common              0.7.7, 0.7.8-next.0
  @backstage/plugin-permission-node                0.7.13
  @backstage/plugin-permission-react               0.4.14, 0.4.15-next.1
  @backstage/plugin-proxy-backend                  0.3.2
  @backstage/plugin-scaffolder-backend             1.16.5
  @backstage/plugin-scaffolder-common              1.4.0
  @backstage/plugin-scaffolder-node                0.2.2
  @backstage/plugin-scaffolder-react               1.5.4
  @backstage/plugin-scaffolder                     1.14.4
  @backstage/plugin-search-backend-module-catalog  0.1.6
  @backstage/plugin-search-backend-module-pg       0.5.11
  @backstage/plugin-search-backend-module-techdocs 0.1.6
  @backstage/plugin-search-backend-node            1.2.6
  @backstage/plugin-search-backend                 1.4.2
  @backstage/plugin-search-common                  1.2.5
  @backstage/plugin-search-react                   1.6.4
  @backstage/plugin-search                         1.3.6
  @backstage/plugin-tech-radar                     0.6.7
  @backstage/plugin-techdocs-backend               1.6.7
  @backstage/plugin-techdocs-module-addons-contrib 1.0.18
  @backstage/plugin-techdocs-node                  1.7.6
  @backstage/plugin-techdocs-react                 1.1.9
  @backstage/plugin-techdocs                       1.6.8
  @backstage/plugin-user-settings                  0.7.8
  @backstage/release-manifests                     0.0.9
  @backstage/test-utils                            1.4.2, 1.4.3-next.0
  @backstage/theme                                 0.4.1, 0.4.1-next.1
  @backstage/types                                 1.1.0
  @backstage/version-bridge                        1.0.4
```

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!
