### ISSUE TITLE
🐛 Bug Report: Unexpected form behavior when having multiple EntityPicker fields in the same form step

### ISSUE THREAD

**Issue by lshwayne96** [backstage/backstage#20008]
### 📜 Description

When multiple `EntityPicker` fields (or their derivatives, e.g. `OwnerPicker`) are defined in the same step of a form template, and each of the fields has only one possible value such that the dropdown becomes disabled, at least one of the fields will not get populated.

### 👍 Expected behavior

All of the `EntityPicker` fields should be populated upon rendering if they have only one possible value, since the dropdown automatically becomes disabled.

### 👎 Actual Behavior with Screenshots

At least one of the `EntityPicker` fields does not get populated and remains disabled.
In the following test, 4 `EntityPicker` fields were defined in the same step and there is always exactly one random field which does not get populated.

![image](https://github.com/backstage/backstage/assets/46807469/2900d843-4308-4bed-b31f-27fa8a7c0462)

### 👟 Reproduction steps

1. Ensure that there is only one group in the catalog (e.g. the default group `guests`).
2. Use the following template (`steps` portion is irrelevant):

```
apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: test-template
  title: Test template
  description: test template
spec:
  owner: test
  type: service
  parameters:
    - title: Step 1
      properties:
        field1:
          title: Field 1
          type: string
          description: field 1
        group1:
          title: Group 1
          type: string
          description: group 1
          ui:field: EntityPicker
          ui:options:
            catalogFilter: 
              - kind: Group
        group2:
          title: Group 2
          type: string
          description: group 2
          ui:field: EntityPicker
          ui:options:
            catalogFilter: 
              - kind: Group
        group3:
          title: Group 3
          type: string
          description: group 3
          ui:field: EntityPicker
          ui:options:
            catalogFilter: 
              - kind: Group
        group4:
          title: Group 4
          type: string
          description: group 4
          ui:field: EntityPicker
          ui:options:
            catalogFilter: 
              - kind: Group
  steps:
    - id: fetch-base
      name: Fetch Base
      action: fetch:template
      input:
        url: ./content
        values:
          name: ${{ parameters.name }}
    - id: publish
      name: Publish
      action: publish:github
      input:        allowedHosts: ['github.com']
        description: This is ${{ parameters.name }}
        repoUrl: ${{ parameters.repoUrl }}
    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps['publish'].output.repoContentsUrl }}
        catalogInfoPath: '/catalog-info.yaml'
  output:
    links:
      - title: Repository
        url: ${{ steps['publish'].output.remoteUrl }}
      - title: Open in catalog
        icon: catalog
        entityRef: ${{ steps['register'].output.entityRef }}
```

### 📃 Provide the context for the Bug.

We have use cases for templates where multiple `EntityPicker` fields are defined in the same step of the form and all of them are facing the same issue. The workaround so far is to place them into separate steps so that they do not all render at the same time.

### 🖥️ Your Environment

```
OS:   Linux 5.15.90.1-microsoft-standard-WSL2 - linux/x64
node: v18.16.1
yarn: 1.22.19
cli:  0.22.9 (installed)
backstage:  1.15.0

Dependencies:
  @backstage/app-defaults                            1.4.1
  @backstage/backend-app-api                         0.4.5
  @backstage/backend-common                          0.18.5, 0.19.1
  @backstage/backend-dev-utils                       0.1.1
  @backstage/backend-plugin-api                      0.5.4
  @backstage/backend-tasks                           0.5.4
  @backstage/catalog-client                          1.4.3
  @backstage/catalog-model                           1.4.1
  @backstage/cli-common                              0.1.12
  @backstage/cli-node                                0.1.2
  @backstage/cli                                     0.22.9
  @backstage/config-loader                           1.3.2
  @backstage/config                                  1.0.8
  @backstage/core-app-api                            1.9.0
  @backstage/core-components                         0.12.5, 0.13.3
  @backstage/core-plugin-api                         1.5.3
  @backstage/dev-utils                               1.0.17
  @backstage/errors                                  1.2.1
  @backstage/eslint-plugin                           0.1.3
  @backstage/integration-aws-node                    0.1.5
  @backstage/integration-react                       1.1.15
  @backstage/integration                             1.5.1
  @backstage/plugin-api-docs                         0.9.6
  @backstage/plugin-app-backend                      0.3.47
  @backstage/plugin-auth-backend                     0.17.4, 0.18.5
  @backstage/plugin-auth-node                        0.2.16
  @backstage/plugin-catalog-backend-module-gitlab    0.2.3
  @backstage/plugin-catalog-backend-module-ldap      0.5.14
  @backstage/plugin-catalog-backend                  1.11.0
  @backstage/plugin-catalog-common                   1.0.15
  @backstage/plugin-catalog-graph                    0.2.32
  @backstage/plugin-catalog-import                   0.9.10
  @backstage/plugin-catalog-node                     1.4.0
  @backstage/plugin-catalog-react                    1.8.0
  @backstage/plugin-catalog                          1.12.0
  @backstage/plugin-events-node                      0.2.8
  @backstage/plugin-github-actions                   0.6.1
  @backstage/plugin-org                              0.6.10
  @backstage/plugin-permission-backend               0.5.22
  @backstage/plugin-permission-common                0.7.7
  @backstage/plugin-permission-node                  0.7.10
  @backstage/plugin-permission-react                 0.4.14
  @backstage/plugin-proxy-backend                    0.2.41
  @backstage/plugin-scaffolder-backend-module-gitlab 0.2.2
  @backstage/plugin-scaffolder-backend               1.15.1
  @backstage/plugin-scaffolder-common                1.3.2
  @backstage/plugin-scaffolder-node                  0.1.5
  @backstage/plugin-scaffolder-react                 1.5.1
  @backstage/plugin-scaffolder                       1.14.1
  @backstage/plugin-search-backend-module-catalog    0.1.3
  @backstage/plugin-search-backend-module-pg         0.5.8
  @backstage/plugin-search-backend-module-techdocs   0.1.3
  @backstage/plugin-search-backend-node              1.2.3
  @backstage/plugin-search-backend                   1.3.3
  @backstage/plugin-search-common                    1.2.5
  @backstage/plugin-search-react                     1.6.3
  @backstage/plugin-search                           1.3.3
  @backstage/plugin-tech-radar                       0.6.6
  @backstage/plugin-techdocs-backend                 1.6.4
  @backstage/plugin-techdocs-module-addons-contrib   1.0.15
  @backstage/plugin-techdocs-node                    1.7.3
  @backstage/plugin-techdocs-react                   1.1.8
  @backstage/plugin-techdocs                         1.6.5
  @backstage/plugin-user-settings                    0.7.5
  @backstage/release-manifests                       0.0.9
  @backstage/test-utils                              1.4.1
  @backstage/theme                                   0.2.19, 0.4.1
  @backstage/types                                   1.1.0
  @backstage/version-bridge                          1.0.4
```

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None
