### ISSUE TITLE
🐛 Bug Report: scaffolder/next setting defaults doesn't always work

### ISSUE THREAD

**Issue by nBerg** [backstage/backstage#20055]
### 📜 Description

I'm looking into switching over to scaffolder/next specifically to use the if/then syntax, but running into an issue where defaults are not respected for properties in the "then" block.

### 👍 Expected behavior

Defaults for properties in the "then" block should be set

### 👎 Actual Behavior with Screenshots

Default was not set as expected:
<img width="1402" alt="Screenshot 2023-09-20 at 12 59 30 PM" src="https://github.com/backstage/backstage/assets/2374174/c8d1507c-73fe-4bcc-a882-f464ebadd9e2">

### 👟 Reproduction steps

[Here is an example of this working in the RJSF playground](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJhbmltYWwiOiJDYXQiLCJmb29kIjoibWVhdCJ9LCJzY2hlbWEiOnsidHlwZSI6Im9iamVjdCIsInByb3BlcnRpZXMiOnsiYW5pbWFsIjp7InR5cGUiOiJzdHJpbmciLCJkZWZhdWx0IjoiQ2F0IiwiZW51bSI6WyJDYXQiLCJGaXNoIl19fSwiYWxsT2YiOlt7ImlmIjp7InByb3BlcnRpZXMiOnsiYW5pbWFsIjp7ImNvbnN0IjoiQ2F0In19fSwidGhlbiI6eyJwcm9wZXJ0aWVzIjp7ImZvb2QiOnsidHlwZSI6InN0cmluZyIsImRlZmF1bHQiOiJtZWF0IiwiZW51bSI6WyJtZWF0IiwiZ3Jhc3MiLCJmaXNoIl19fSwicmVxdWlyZWQiOlsiZm9vZCJdfX0seyJpZiI6eyJwcm9wZXJ0aWVzIjp7ImFuaW1hbCI6eyJjb25zdCI6IkZpc2gifX19LCJ0aGVuIjp7InByb3BlcnRpZXMiOnsiZm9vZCI6eyJ0eXBlIjoic3RyaW5nIiwiZW51bSI6WyJpbnNlY3QiLCJ3b3JtcyJdfSwid2F0ZXIiOnsidHlwZSI6InN0cmluZyIsImVudW0iOlsibGFrZSIsInNlYSJdfX0sInJlcXVpcmVkIjpbImZvb2QiLCJ3YXRlciJdfX0seyJyZXF1aXJlZCI6WyJhbmltYWwiXX1dfSwidWlTY2hlbWEiOnt9LCJ0aGVtZSI6ImRlZmF1bHQiLCJsaXZlU2V0dGluZ3MiOnsic2hvd0Vycm9yTGlzdCI6InRvcCIsImV4cGVyaW1lbnRhbF9kZWZhdWx0Rm9ybVN0YXRlQmVoYXZpb3IiOnsiYXJyYXlNaW5JdGVtcyI6eyJwb3B1bGF0ZSI6InBvcHVsYXRlIiwibWVyZ2VFeHRyYURlZmF1bHRzIjpmYWxzZX0sImVtcHR5T2JqZWN0RmllbGRzIjoicG9wdWxhdGVBbGxEZWZhdWx0cyJ9fX0=)

Here is an example of a scaffolder template that does not work as expected:
```yaml
apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: example-if-then
  title: example-if-then
spec:
  type: service
  parameters:
    - title: Example
      type: object
      properties:
        animalInfo: # This is unrelated, but for some reason this is needed in scaffolder, but not RJSF?
          properties:
            animal:
              type: string
              default: Cat # This default works as expected
              enum:
              - Cat
              - Fish
          allOf:
            - if:
                properties:
                  animal:
                    const: Cat
              then:
                properties:
                  food:
                    type: string
                    default: meat # This default does not work as expected
                    enum:
                    - meat
                    - grass
                    - fish
                required:
                - food
            - if:
                properties:
                  animal:
                    const: Fish
              then:
                properties:
                  food:
                    type: string
                    enum:
                    - insect
                    - worms
                  water:
                    type: string
                    enum:
                    - lake
                    - sea
                required:
                - food
                - water
            - required:
              - animal
  steps: []

```

### 📃 Provide the context for the Bug.

I'm trying to use the if/then syntax with defaults for some of the "then" properties. This works today using the "oneOf" syntax as described [here](https://react-jsonschema-form.readthedocs.io/en/v1.8.1/dependencies/#dynamic). I'm looking into switching to scaffolder/next and using the if/else syntax for a few reasons, but primarily to fix [this bug with duplicate validation errors](https://github.com/rjsf-team/react-jsonschema-form/issues/1590).

### 🖥️ Your Environment

browser: Chrome Version 116.0.5845.187

```
❯ yarn backstage-cli info
yarn run v1.22.19
$ /Users/berg/code/flex/developer-home/node_modules/.bin/backstage-cli info
OS:   Darwin 22.6.0 - darwin/arm64
node: v18.14.2
yarn: 1.22.19
cli:  0.22.12 (installed)
backstage:  1.17.5

Dependencies:
  @backstage/app-defaults                                        1.4.2
  @backstage/backend-app-api                                     0.5.2
  @backstage/backend-common                                      0.19.4
  @backstage/backend-dev-utils                                   0.1.1
  @backstage/backend-openapi-utils                               0.0.3
  @backstage/backend-plugin-api                                  0.6.2
  @backstage/backend-tasks                                       0.5.7
  @backstage/catalog-client                                      1.4.3
  @backstage/catalog-model                                       1.4.1
  @backstage/cli-common                                          0.1.12
  @backstage/cli-node                                            0.1.3
  @backstage/cli                                                 0.22.12
  @backstage/config-loader                                       1.4.0
  @backstage/config                                              1.0.8
  @backstage/core-app-api                                        1.9.1
  @backstage/core-components                                     0.13.4
  @backstage/core-plugin-api                                     1.5.3
  @backstage/dev-utils                                           1.0.20
  @backstage/errors                                              1.2.1
  @backstage/eslint-plugin                                       0.1.3
  @backstage/integration-aws-node                                0.1.5
  @backstage/integration-react                                   1.1.18
  @backstage/integration                                         1.6.2
  @backstage/plugin-app-backend                                  0.3.50
  @backstage/plugin-app-node                                     0.1.2
  @backstage/plugin-auth-backend                                 0.18.8
  @backstage/plugin-auth-node                                    0.2.19
  @backstage/plugin-catalog-backend-module-incremental-ingestion 0.4.5
  @backstage/plugin-catalog-backend-module-msgraph               0.5.9
  @backstage/plugin-catalog-backend                              1.12.4
  @backstage/plugin-catalog-common                               1.0.15
  @backstage/plugin-catalog-graph                                0.2.35
  @backstage/plugin-catalog-import                               0.9.13
  @backstage/plugin-catalog-node                                 1.4.3
  @backstage/plugin-catalog-react                                1.8.3
  @backstage/plugin-catalog                                      1.12.4
  @backstage/plugin-events-node                                  0.2.11
  @backstage/plugin-github-actions                               0.6.4
  @backstage/plugin-home-react                                   0.1.2
  @backstage/plugin-home                                         0.5.7
  @backstage/plugin-org                                          0.6.13
  @backstage/plugin-permission-common                            0.7.7
  @backstage/plugin-permission-node                              0.7.13
  @backstage/plugin-permission-react                             0.4.14
  @backstage/plugin-proxy-backend                                0.3.2
  @backstage/plugin-scaffolder-backend                           1.16.5
  @backstage/plugin-scaffolder-common                            1.4.0
  @backstage/plugin-scaffolder-node                              0.2.2
  @backstage/plugin-scaffolder-react                             1.5.4
  @backstage/plugin-scaffolder                                   1.14.4
  @backstage/plugin-search-backend-module-catalog                0.1.6
  @backstage/plugin-search-backend-module-pg                     0.5.11
  @backstage/plugin-search-backend-node                          1.2.6
  @backstage/plugin-search-backend                               1.4.2
  @backstage/plugin-search-common                                1.2.5
  @backstage/plugin-search-react                                 1.6.4
  @backstage/plugin-search                                       1.3.6
  @backstage/plugin-user-settings                                0.7.8
  @backstage/release-manifests                                   0.0.9
  @backstage/test-utils                                          1.4.2
  @backstage/theme                                               0.4.1
  @backstage/types                                               1.1.0
  @backstage/version-bridge                                      1.0.4
✨  Done in 0.83s.
```

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None
