### ISSUE TITLE
🚀 Feature: Make the append action able to read from one file and merge it with another.

### ISSUE THREAD

**Issue by alejandraRamos** [backstage/backstage#20062]
### 🔖 Feature description

We need the capability to utilize the `roadiehq:utils:fs:append` action for merging an existing file into another by providing a path.
Something similar to this:
```
- id: mergeMonitors
  name: Merge monitors
  action: roadiehq:utils:fs:append
  input:
    path: "./monitoring/${{ parameters.teamOwner.split('/') | last() }}.tf"
    anotherPath: "skeletons/terraform/resource/main.tf"
```

Because currently, `content` field only allows text content, not the path to another file.

### 🎤 Context

I'm building a Backstage component that creates **Datadog alarms** based on the service and some specified parameters. These monitors will be grouped into a file representing the team's name.

I need to be able to add multiple Terraform resources associated with different services in the same file, considering a skeleton where I define the resource to create the alarm using the parameters exported by the Backstage component through `fetch:template`.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None
