### ISSUE TITLE
🐛 Bug Report: Scaffolder string inputs aren't prefilled with the default value

### ISSUE THREAD

**Issue by fyyyyy** [backstage/backstage#20215]
### 📜 Description

Scaffolder string form fields are not prefilled with the default value. Instead the input field is blank, while the value is present when you submit the form. So the **required** condition is fulfilled even though the input field is blank.
```yaml
  parameters:
      required:
        - name
        - scope
        - owner
     properties:
        name:
          title: Name
          type: string
          default: 'prefix-'
 ```

### 👍 Expected behavior

If a default is set for a string input, the default should be set as value for the input tag.

### 👎 Actual Behavior with Screenshots

<img width="1172" alt="image" src="https://github.com/backstage/backstage/assets/3744048/1e41c23f-d72e-4661-a668-f5edfa4c1734">

### 👟 Reproduction steps

Create a scaffolder template
Add a string input
Add a default value
Check the rendered form

### 🖥️ Your Environment

backstage 1.18.1, Chrome (latest)

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None
