### ISSUE TITLE
🐛 Bug Report: GitlabOrgDiscoveryEntityProvider only supports one group since 1.18.0

### ISSUE THREAD

**Issue by bakito** [backstage/backstage#20274]
### 📜 Description

In [v1.18.0](https://github.com/backstage/backstage/releases/tag/v1.18.0) the group turned required in the GitlabOrgDiscoveryEntityProvider.

As I use a self hosted gitlab instance I would like to be able to import all / most of the groups from my instance.
Unfortunately only one group is supported.

### 👍 Expected behavior

For self hosted instances It should be possible to import all, or at least multiple groups with subgroups into backstage.

### 👎 Actual Behavior with Screenshots

When not configuring a group the sync fails.

`
{"class":"GitlabOrgDiscoveryEntityProvider","level":"error","message":"GitlabOrgDiscoveryEntityProvider:gitlabBisdevdomCH refresh failed GraphQL errors: [{\"message\":\"Internal server error\"}]","plugin":"catalog","service":"backstage","stack":"Error: GraphQL errors: [{\"message\":\"Internal server error\"}]\n    at GitLabClient.getGroupMembers (/app/node_modules/@backstage/plugin-catalog-backend-module-gitlab/dist/cjs/GitlabDiscoveryEntityProvider-8ed2153b.cjs.js:197:15)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async GitlabOrgDiscoveryEntityProvider.refresh (/app/node_modules/@backstage/plugin-catalog-backend-module-gitlab/dist/index.cjs.js:307:26)\n    at async TaskWorker.fn (/app/node_modules/@backstage/plugin-catalog-backend-module-gitlab/dist/index.cjs.js:240:13)\n    at async TaskWorker.runOnce (/app/node_modules/@backstage/backend-tasks/dist/index.cjs.js:349:7)\n    at async /app/node_modules/@backstage/backend-tasks/dist/index.cjs.js:297:31","target":"GitlabOrgDiscoveryEntityProvider:gitlabBisdevdomCH","taskId":"GitlabOrgDiscoveryEntityProvider:gitlabBisdevdomCH:refresh","taskInstanceId":"4931fee3-2407-4fd2-9ce8-d88414aff514","type":"plugin"}
`

If I define a group, only this one and it's members are imported.

### 👟 Reproduction steps

configure the GitlabOrgDiscoveryEntityProvider as documented in https://backstage.io/docs/integrations/gitlab/org

### 📃 Provide the context for the Bug.

```
  providers:
   
    gitlab:
      my-instance:
        host: gitlab.my.com
        orgEnabled: true
        schedule: # optional; same options as in TaskScheduleDefinition
          # supports cron, ISO duration, "human duration" as used in code
          frequency: { minutes: 30 }
          # supports ISO duration, "human duration" as used in code
          timeout: { minutes: 3 }
```

### 🖥️ Your Environment

Backstage 1.18.3

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by jamieklassen** [comment]
Sounds like this behaviour was probably introduced by #18889 -- however it was only supposed to make the group parameter required for `gitlab.com` and self-hosted installations weren't supposed to be affected. I don't really know what's going on here and don't have the bandwidth to properly investigate, but I'll take a long shot -- @matteosilv you think this could be a similar type of problem to the one solved in #20145?

**Comment by matteosilv** [comment]
Hi guys. No @jamieklassen it's a different problem (not related to #20145). However, seems weird log, since it seems the instance is recognized as SaaS. As you can see from the code below it only looks at group members for gitlab.com:

    if (client.isSelfManaged()) {
      groups = paginated<GitLabGroup>(options => client.listGroups(options), {
        page: 1,
        per_page: 100,
      });

      users = paginated<GitLabUser>(options => client.listUsers(options), {
        page: 1,
        per_page: 100,
        active: true,
      });
    } else {
      groups = (await client.listDescendantGroups(this.config.group)).items;
      users = (
        await client.getGroupMembers(this.config.group.split('/')[0], [
          'DIRECT',
          'DESCENDANTS',
        ])
      ).items;
    }

**Comment by matteosilv** [comment]
I just tested in my local instance updated to 1.18 and I am able to parse all groups starting from the root.

Can you verify also the `integrations` field in the conf yaml?

```yaml
integrations:
  gitlab:
    - host: gitlab.my.com
      token: ${GITLAB_ACCESS_TOKEN}
      apiBaseUrl: https:/gitlab.my.com/api/v4
```
