### ISSUE TITLE
🐛 Bug Report: Azure integration

### ISSUE THREAD

**Issue by detox3r** [backstage/backstage#20320]
### 📜 Description

When I create a new app with `npx @backstage/create-app@latest` and attempt to integrate with azure using PAT token or service principal auth I get the following error message in the browser:

```
index.esm.js:232 Failed to read configuration array at 'credentials' as it does not have any visible elements. 
See https://backstage.io/docs/conf/defining#visibility for instructions on how to make it visible.
```

app.config.yaml

```yaml
integrations:
  azure:
    - host: dev.azure.com
      credentials:
        - clientId: xxxxxxxxxxxxxx
          clientSecret: xxxxxxxxxxxxxxxx
          tenantId: xxxxxxxxxxxxxxx
```

or

```yaml
integrations:
  azure:
    - host: dev.azure.com
      credentials:
        -  personalAccessToken: xxxxxxxxxxxxxxxxxx
```

Issue is probably related to [this](https://github.com/backstage/backstage/issues/20174)

### 👍 Expected behavior

message should not appear, possibly blocking the azureDevOps plugin where I can see builds and pipelines

### 👎 Actual Behavior with Screenshots

<img width="1422" alt="image" src="https://github.com/backstage/backstage/assets/76015484/83ecd227-cf63-45c1-9d82-0ea09f5431de">

### 👟 Reproduction steps

`npx @backstage/create-app@latest`

replace you app-config.yaml with the values above or just try to integrate it with azure devops and a PAT token or SP

### 📃 Provide the context for the Bug.

I think is blocking my azure devops plugin where Im trying to see builds and pipelines

### 🖥️ Your Environment

OS: MacOS Ventura
node: v18.14.1
yarn: v1.22.19
backstage: 1.18.3

### 👀 Have you spent some time to check if this bug has been raised before?

- [ ] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by awanlin** [comment]
Hi @detox3r, just a heads up this won't block the Azure DevOps plugin as it hasn't been migrated to use the values from the `integration.azure` section of the `app-config.yaml` file yet, docs to set it up are here: https://github.com/backstage/backstage/tree/master/plugins/azure-devops-backend#configuration. 

The catalog DOES use this so if you are trying to pull in `catalog-info.yaml` files from Azure Repos that will be an issue. Still trying to figure out why this isn't working for you though, what you posted does look correct to me

**Comment by detox3r** [comment]
Thanks for the quick response @awanlin. Yes there is no issues with the azure-devops-backend plugin. but there is definitely an issue with the [azure-devops-app](https://github.com/backstage/backstage/tree/master/plugins/azure-devops) plugin  which in fact uses catalog-info.yaml

I've essentially followed their instructions [here](https://github.com/backstage/backstage/tree/master/plugins/azure-devops) and its plugin in backstage just doesnt show at all.

<img width="648" alt="image" src="https://github.com/backstage/backstage/assets/76015484/7d739a7f-ece2-44e5-8629-1be5d7223327">

**Comment by awanlin** [comment]
To get to the root of your issue, I think we are both saying the same thing, just in a different way. You are correct to say the Azure DevOps plugin does use the `catalog-info.yaml` files but that's via the Catalog. The Catalog DOES use the values from the `integration.azure` section. Until that is resolved you won't be able to actually use the Azure DevOps plugin.

The Azure DevOps plugin doesn't have a sidebar options (well technically there is an Azure DevOps Pull Request dashboard but it's not documented currently) and you view its features from within entities in the Catalog. The entities need to also have the proper annotations in place. This is all documented at the link you shared here: https://github.com/backstage/backstage/tree/master/plugins/azure-devops#setup

I won't have time to look into this more closely until my work day has ended, sorry.

**Comment by detox3r** [comment]
not in a rush. thanks for even looking at it, appreciate the help

**Comment by awanlin** [comment]
Got some time to look into this. I did a fresh `npx @backstage/create-app@latest` then in my `app-config.local.yaml` added the `intergation.azure` like this:

```yaml
integrations:
  azure:
    - host: dev.azure.com
      credentials:
        - personalAccessToken: ${ADOS_CLOUD}
```

And I also added a test catalog location like this:

```yaml
catalog:
  rules:
    - allow:
        - Component
  locations:
    - type: url
      target: https://dev.azure.com/exampl-org/_git/example-repo?path=/catalog-info.yaml
```

That works, no errors, the component shows up in the UI as expected
