### ISSUE TITLE
🐛 Bug Report:  The Okta provider is not configured to support sign-in

### ISSUE THREAD

**Issue by melissakw** [backstage/backstage#20391]
### 📜 Description

Encountering unexpected error upon successful Okta authentication (Okta logs are showing successful sign-in): "The Okta provider is not configured to support sign-in".

<img width="1013" alt="Screenshot 2023-10-05 at 9 08 47 AM" src="https://github.com/backstage/backstage/assets/64169245/6294722d-ce75-4a4d-bcf4-322ceb42d492">

[This](https://backstage.io/docs/auth/okta/provider/#:~:text=audience%3A%20The%20Okta%20domain%20shown%20for%20the%20Application%2C%20e.g.%20https%3A//company.okta.com) Backstage doc asks for audience: ${AUTH_OKTA_DOMAIN} in the format of https://company.okta.com/ when my okta access_token shows:
```
"aud": "api://default",
"iss": "https://xyz.okta.com/oauth2/default",
"scp": [
  "email",
  "openid",
  "profile",
  "offline_access"
 ]
```

Can this misalignment between okta’s `aud` ("api://default") and the Backstage expected `aud` (AUTH_OKTA_DOMAIN) cause the error above when we use a custom auth server?

We first tried using `api://default` as the audience value in `app-config.yaml` but this caused our deployment to fail.
```
auth:
  environment: dev
  providers:
    okta:
      dev:
        clientId: ${AUTH_OKTA_CLIENT_ID}
        clientSecret: ${AUTH_OKTA_CLIENT_SECRET}
        audience: api://default
        authServerId: ${AUTH_OKTA_AUTH_SERVER_ID} # using default for value
        # idp: ${AUTH_OKTA_IDP} # omitted since it's optional; same error when idp was provided
```

We then tried using  `https://xyz.okta.com/` as the value for `audience` in `app-config.yaml` and got the error shown in the screenshot above. Does Backstage not support `api://default` for `aud` value?

Really appreciate it if you can point out why we might be getting "The Okta provider is not configured to support sign-in" despite successful authentication.

### 👍 Expected behavior

User should be redirected to Backstage app's home page when pop-up closes upon successful authentication

### 👎 Actual Behavior with Screenshots

1. Pop-up appears to prompt user to complete okta sign-in flow
2. Pop-up closes upon successful authentication (Okta logs confirms success)
3. Main screen shows error: "The Okta provider is not configured to support sign-in"

### 👟 Reproduction steps

I have the following configs in `app-config.yaml`:

```
app:
  title: Scaffolded Backstage App
  baseUrl: https://xyz.dev-abc.com
...
auth:
  environment: dev
  providers:
    okta:
      dev:
        clientId: ${AUTH_OKTA_CLIENT_ID}
        clientSecret: ${AUTH_OKTA_CLIENT_SECRET}
        audience: ${AUTH_OKTA_DOMAIN} # using https://xyz.okta.com/ for value as suggested by doc
        authServerId: ${AUTH_OKTA_AUTH_SERVER_ID} # using default for value
        # idp: ${AUTH_OKTA_IDP} # omitted since it's optional; same error when idp was provided
```

For frontend sign-in config, I followed [this doc](https://backstage.io/docs/auth/#:~:text=The%20following%20example%20for%20GitHub%20shows%20the%20additions%20needed%20to%20packages/app/src/App.tsx%2C%20and%20can%20be%20adapted%20to%20any%20of%20the%20built%2Din%20providers%3A) and added the following in `app/src/App.tsx`:
```
import { oktaAuthApiRef } from '@backstage/core-plugin-api';
import { SignInPage } from '@backstage/core-components';

const app = createApp({
  components: {
    SignInPage: props => (
      <SignInPage
        {...props}
        auto
        provider={{
          id: 'okta-auth-provider',
          title: 'Okta',
          message: 'Sign in using Okta',
          apiRef: oktaAuthApiRef,
        }}
      />
    ),
  },
...
```

### 🖥️ Your Environment

MacOS with node 16.0.0, npm 7.10.0, using these dependencies:
```
"@backstage/cli": "0.22.7",
"@spotify/prettier-config": "12.0.0",
"concurrently": "6.0.0",
"lerna": "4.0.0",
"node-gyp": "9.0.0",
"prettier": "2.3.2",
"typescript": "~5.0.0"
```

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!
