### ISSUE TITLE
🐛 Bug Report: Google Cloud Run Hosted Backstage Service Doesn't Authenticate with GitHub

### ISSUE THREAD

**Issue by hs14428** [backstage/backstage#20483]
### 📜 Description

I am in the process of moving my localhost version of Backstage onto a Cloud Run hosted web offering. I have updated the `app-config.yaml` to reflect these changes, but whenever I try and authenticate to GitHub via the `requestUserCredentials` section of `ui:field: RepoUrlPicker` in a software template, the process hangs and fails with the following error:

`Authentication failed, Failed to obtain access token`

### 👍 Expected behavior

GitHub should authenticate nice and easily, like it does on the localhost version.

### 👎 Actual Behavior with Screenshots

Github Auth hangs and then fails with 'Authentication failed, Failed to obtain access token' error.
<img width="447" alt="Screenshot 2023-10-09 at 13 00 46" src="https://github.com/backstage/backstage/assets/57953964/fb0092d0-58c3-4c05-88ef-dc0143e1b973">
<img width="447" alt="Screenshot 2023-10-09 at 15 06 19" src="https://github.com/backstage/backstage/assets/57953964/e4b0328a-ea83-4141-8943-a85f998d6a08">

### 👟 Reproduction steps

1. Enter repo details into the `ui:field: RepoUrlPicker` section of a software template
2. Login with GitHub account details
3. Wait....
4. Fail

I even receive the email saying a 'A third-party OAuth application (Hosted Backstage Demo) with gist, read:org, read:user, repo, and workflow scopes was recently authorized to access your account', but it stays on the redirect page, hangs and doesn't work, failing eventually.

### 📃 Provide the context for the Bug.

app.config.yaml
```
app:
  title: Backstage Software Catalog
  baseUrl: ${BACKSTAGE_BASE_URL}

organization:
  name: Company name

backend:
  baseUrl: ${BACKSTAGE_BASE_URL}
  listen:
    port: ${PORT}
  csp:
    connect-src: ["'self'", 'http:', 'https:']
    img-src: ["'self'", 'data:', 'https://avatars.githubusercontent.com']
  cors:
    origin: ${BACKSTAGE_BASE_URL}
    methods: [GET, HEAD, PATCH, POST, PUT, DELETE]
    credentials: true
  database:
    client: pg
    connection:
      host: ${POSTGRES_HOST}
      port: ${POSTGRES_PORT}
      user: ${POSTGRES_USER}
      password: ${POSTGRES_PASSWORD}

integrations:
  github:
    - host: github.com
      token: ${GITHUB_TOKEN}

proxy:
  '/test':
    target: 'https://example.com'
    changeOrigin: true

techdocs:
  builder: 'local' # Alternatives - 'external'
  generator:
    runIn: 'local' # Alternatives - 'local'
  publisher:
    type: 'local' # Alternatives - 'googleGcs' or 'awsS3'. Read documentation for using alternatives.

auth:
  # see https://backstage.io/docs/auth/ to learn about auth providers
  enviroment: development
  providers:
    github:
      development:
        clientId: ${GITHUB_AUTH_CLIENT_ID}
        clientSecret: ${GITHUB_AUTH_CLIENT_SECRET}
    google:
      development:
        clientId: ${AUTH_GOOGLE_CLIENT_ID}
        clientSecret: ${AUTH_GOOGLE_CLIENT_SECRET}
```
Where `BACKSTAGE_BASE_URL` is the Cloud Run or Custom Domain url for the hosted web app.

I recently created a new `GITHUB_TOKEN` and GitHub OAuth app for the new hosted version of the (to keep it separate from the localhost deployment), and since then it has stopped working. I have updated the GitHub Client IDs and Client Secrets in my Cloud Run Deployment accordingly, however.

My GitHub OAuth app has the following Urls:
`Homepage URL: https://BACKSTAGE_BASE_URL`
`Authorization callback URL: https://BACKSTAGE_BASE_URL/api/auth/github/handler/frame`

Do I need to specify the port in the BACKSTAGE_BASE_URL if it follows the form of a normal URL? e.g. https://backstage-company_name.com?

I can't seem to find a solution to why it doesn't complete the authentication.

Thanks in advance.

### 🖥️ Your Environment

OS:   Darwin 21.6.0 - darwin/arm64
node: v18.17.1
yarn: 1.22.19
cli:  0.22.13 (installed)
backstage:  1.18.3

Dependencies:
  @backstage/app-defaults                                          1.4.3
  @backstage/backend-app-api                                       0.5.4
  @backstage/backend-common                                        0.19.6
  @backstage/backend-dev-utils                                     0.1.1
  @backstage/backend-openapi-utils                                 0.0.4
  @backstage/backend-plugin-api                                    0.6.4
  @backstage/backend-tasks                                         0.5.9
  @backstage/catalog-client                                        1.4.4
  @backstage/catalog-model                                         1.4.2
  @backstage/cli-common                                            0.1.12
  @backstage/cli-node                                              0.1.4
  @backstage/cli                                                   0.22.13
  @backstage/config-loader                                         1.5.0
  @backstage/config                                                1.1.0
  @backstage/core-app-api                                          1.10.0
  @backstage/core-components                                       0.13.5
  @backstage/core-plugin-api                                       1.6.0
  @backstage/errors                                                1.2.2
  @backstage/eslint-plugin                                         0.1.3
  @backstage/integration-aws-node                                  0.1.6
  @backstage/integration-react                                     1.1.19
  @backstage/integration                                           1.7.0
  @backstage/plugin-api-docs                                       0.9.11
  @backstage/plugin-app-backend                                    0.3.52
  @backstage/plugin-app-node                                       0.1.4
  @backstage/plugin-auth-backend-module-gcp-iap-provider           0.1.1
  @backstage/plugin-auth-backend-module-github-provider            0.1.1
  @backstage/plugin-auth-backend-module-gitlab-provider            0.1.1
  @backstage/plugin-auth-backend-module-google-provider            0.1.1
  @backstage/plugin-auth-backend-module-oauth2-provider            0.1.1
  @backstage/plugin-auth-backend                                   0.19.1
  @backstage/plugin-auth-node                                      0.3.1
  @backstage/plugin-catalog-backend-module-scaffolder-entity-model 0.1.1
  @backstage/plugin-catalog-backend                                1.13.2
  @backstage/plugin-catalog-common                                 1.0.16
  @backstage/plugin-catalog-graph                                  0.2.36
  @backstage/plugin-catalog-import                                 0.10.0
  @backstage/plugin-catalog-node                                   1.4.5
  @backstage/plugin-catalog-react                                  1.8.4
  @backstage/plugin-catalog                                        1.13.0
  @backstage/plugin-events-node                                    0.2.13
  @backstage/plugin-github-actions                                 0.6.5
  @backstage/plugin-home-react                                     0.1.3
  @backstage/plugin-home                                           0.5.8
  @backstage/plugin-org                                            0.6.14
  @backstage/plugin-permission-common                              0.7.8
  @backstage/plugin-permission-node                                0.7.15
  @backstage/plugin-permission-react                               0.4.15
  @backstage/plugin-proxy-backend                                  0.4.1
  @backstage/plugin-scaffolder-backend                             1.17.2
  @backstage/plugin-scaffolder-common                              1.4.1
  @backstage/plugin-scaffolder-node                                0.2.4
  @backstage/plugin-scaffolder-react                               1.5.5
  @backstage/plugin-scaffolder                                     1.15.0
  @backstage/plugin-search-backend-module-catalog                  0.1.8
  @backstage/plugin-search-backend-module-pg                       0.5.13
  @backstage/plugin-search-backend-module-techdocs                 0.1.8
  @backstage/plugin-search-backend-node                            1.2.8
  @backstage/plugin-search-backend                                 1.4.4
  @backstage/plugin-search-common                                  1.2.6
  @backstage/plugin-search-react                                   1.7.0
  @backstage/plugin-search                                         1.4.0
  @backstage/plugin-stack-overflow                                 0.1.20
  @backstage/plugin-tech-radar                                     0.6.8
  @backstage/plugin-techdocs-backend                               1.7.1
  @backstage/plugin-techdocs-module-addons-contrib                 1.1.0
  @backstage/plugin-techdocs-node                                  1.8.1
  @backstage/plugin-techdocs-react                                 1.1.11
  @backstage/plugin-techdocs                                       1.7.0
  @backstage/plugin-user-settings                                  0.7.10
  @backstage/release-manifests                                     0.0.10
  @backstage/test-utils                                            1.4.3
  @backstage/theme                                                 0.4.2
  @backstage/types                                                 1.1.1
  @backstage/version-bridge                                        1.0.5

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!
