### ISSUE TITLE
🚀 Feature: scaffolder multi select list of owner and entities 

### ISSUE THREAD

**Issue by punkle** [backstage/backstage#20589]
### 🔖 Feature description

It would be great if there was a way to configure the EntityPicker and OwnerPicker fields in scaffolder to allow them to be multiselect lists returning arrays rather than a single select of a string.

### 🎤 Context

In order to make this work, you can specify properties to include an array of owner/entity pickers. However the UI results in a clunky experience:

```
  parameters:
    - title: parameters
      properties:
        listOfOwners:
          type: "array"
          title: "A list of owners"
          items:
            type: string
            description: Select an owner
            ui:field: OwnerPicker
```
       

### ✌️ Possible Implementation

It would be fantasitc if owner picker and entity picker allowed multiselect.

```
  parameters:
    - title: parameters
      properties:
        listOfOwners:
            type: array
            description: Select owners
            ui:field: OwnerPicker
            ui:options:
              multiselect: true
```

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else
