### ISSUE TITLE
🐛 Bug Report: K8s plugin with AKS strategy and Entra ID (Azure AD) as login provider

### ISSUE THREAD

**Issue by Gholie** [backstage/backstage#20608]
### 📜 Description

Using Azure Auth provider with AKS strategy for Kubernetes plugin:
I am seeing an issue where whenever I am visiting the Kubernetes tab on a Component the `microsoft-refresh-token` seems to be overwritten. This only happens on that specific tab from what I can see.

### 👍 Expected behavior

Backstage should not redirect to a login page after visiting the Kubernetes tab when you refresh

### 👎 Actual Behavior with Screenshots

This causes an error whenever the site is refreshed with the following error:
`The Login provider is not configured to support sign-in`

### 👟 Reproduction steps

1. Login as normal
2. Visit a catalog entry with a registered Kubernetes component
3. Visit the Kubernetes tab
    a.  When visiting the tab the `microsoft-refresh-token` is changed
4. Refresh the page

### 📃 Provide the context for the Bug.

Kubernetes app config:
```yaml
kubernetes:
          serviceLocatorMethod:
            type: "multiTenant"
          clusterLocatorMethods:
            - type: "config"
              clusters:
                - url: ${AZURE_CLUSTER_API_SERVER_ADDRESS} #! Change me##  The base URL to the Kubernetes control plane. Can be found by using the "Kubernetes master" result from running the kubectl cluster-info command.
                  name: Sandbox-Cluster # A name for the cluster in the backstage catalog.
                  authProvider: "aks" # This determines how the Kubernetes client authenticates with the Kubernetes cluster. Valid values are:  Will use Microsoft Auth
                  skipTLSVerify: true #This determines whether the Kubernetes client verifies the TLS certificate presented by the API server. Defaults to false.
                  skipMetricsLookup: false # This determines whether the Kubernetes client looks up resource metrics CPU/Memory for pods returned by the API server. Defaults to false.
```

Kubernetes integration in code is the same as documentation describes

### 🖥️ Your Environment

Output from my local PC. Backstage is running with the same version on Kubernetes with the node18-slim base image.
OS:   Darwin 22.6.0 - darwin/arm64
node: v18.17.1
yarn: 3.6.3
cli:  0.22.13 (installed)
backstage:  1.18.3

Dependencies:
  @backstage/app-defaults                                          1.4.3
  @backstage/backend-app-api                                       0.5.4, 0.5.5
  @backstage/backend-common                                        0.19.6, 0.19.7
  @backstage/backend-dev-utils                                     0.1.1
  @backstage/backend-openapi-utils                                 0.0.4
  @backstage/backend-plugin-api                                    0.6.4, 0.6.5
  @backstage/backend-tasks                                         0.5.10, 0.5.9
  @backstage/catalog-client                                        1.4.4
  @backstage/catalog-model                                         1.4.2
  @backstage/cli-common                                            0.1.12
  @backstage/cli-node                                              0.1.4
  @backstage/cli                                                   0.22.13
  @backstage/config-loader                                         1.5.0
  @backstage/config                                                1.1.0
  @backstage/core-app-api                                          1.10.0
  @backstage/core-components                                       0.13.5
  @backstage/core-plugin-api                                       1.6.0
  @backstage/errors                                                1.2.2
  @backstage/eslint-plugin                                         0.1.3
  @backstage/integration-aws-node                                  0.1.6
  @backstage/integration-react                                     1.1.19
  @backstage/integration                                           1.7.0
  @backstage/plugin-api-docs                                       0.9.11
  @backstage/plugin-app-backend                                    0.3.52
  @backstage/plugin-app-node                                       0.1.4
  @backstage/plugin-auth-backend-module-gcp-iap-provider           0.1.1
  @backstage/plugin-auth-backend-module-github-provider            0.1.1
  @backstage/plugin-auth-backend-module-gitlab-provider            0.1.1
  @backstage/plugin-auth-backend-module-google-provider            0.1.1
  @backstage/plugin-auth-backend-module-oauth2-provider            0.1.1
  @backstage/plugin-auth-backend                                   0.19.1
  @backstage/plugin-auth-node                                      0.3.1, 0.3.2
  @backstage/plugin-catalog-backend-module-github                  0.4.2
  @backstage/plugin-catalog-backend-module-scaffolder-entity-model 0.1.1
  @backstage/plugin-catalog-backend                                1.13.2
  @backstage/plugin-catalog-common                                 1.0.16
  @backstage/plugin-catalog-graph                                  0.2.36
  @backstage/plugin-catalog-import                                 0.10.0
  @backstage/plugin-catalog-node                                   1.4.5
  @backstage/plugin-catalog-react                                  1.8.4
  @backstage/plugin-catalog                                        1.13.0
  @backstage/plugin-cost-insights-common                           0.1.2
  @backstage/plugin-cost-insights                                  0.12.13
  @backstage/plugin-events-node                                    0.2.13
  @backstage/plugin-github-actions                                 0.6.5
  @backstage/plugin-kubernetes-backend                             0.12.1
  @backstage/plugin-kubernetes-common                              0.6.6
  @backstage/plugin-kubernetes                                     0.10.3
  @backstage/plugin-org                                            0.6.14
  @backstage/plugin-permission-common                              0.7.8
  @backstage/plugin-permission-node                                0.7.15, 0.7.16
  @backstage/plugin-permission-react                               0.4.15
  @backstage/plugin-proxy-backend                                  0.4.1
  @backstage/plugin-scaffolder-backend                             1.17.2
  @backstage/plugin-scaffolder-common                              1.4.1
  @backstage/plugin-scaffolder-node                                0.2.4, 0.2.5
  @backstage/plugin-scaffolder-react                               1.5.5
  @backstage/plugin-scaffolder                                     1.15.0
  @backstage/plugin-search-backend-module-catalog                  0.1.8
  @backstage/plugin-search-backend-module-pg                       0.5.13
  @backstage/plugin-search-backend-module-techdocs                 0.1.8
  @backstage/plugin-search-backend-node                            1.2.8
  @backstage/plugin-search-backend                                 1.4.4
  @backstage/plugin-search-common                                  1.2.6
  @backstage/plugin-search-react                                   1.7.0
  @backstage/plugin-search                                         1.4.0
  @backstage/plugin-tech-radar                                     0.6.8
  @backstage/plugin-techdocs-backend                               1.7.1
  @backstage/plugin-techdocs-module-addons-contrib                 1.1.0
  @backstage/plugin-techdocs-node                                  1.8.1
  @backstage/plugin-techdocs-react                                 1.1.11
  @backstage/plugin-techdocs                                       1.7.0
  @backstage/plugin-user-settings                                  0.7.10
  @backstage/release-manifests                                     0.0.10
  @backstage/test-utils                                            1.4.3
  @backstage/theme                                                 0.4.2
  @backstage/types                                                 1.1.1
  @backstage/version-bridge                                        1.0.5

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None
