### ISSUE TITLE
🐛 Bug Report: Connect to remout DB PSQL

### ISSUE THREAD

**Issue by Andrei101Ru** [backstage/backstage#20702]
### 📜 Description

I can't set up a connection to a remote database with ssl.
There is an error in the backend logs:
```
Backend failed to start up Error: Failed to connect to the database to make sure that 'backstage_plugin_catalog' exists, error: odyssey: c9da4157ae029: route for 'postgres.backstagedb' is not found
    at /opt/test/node_modules/@backstage/backend-common/dist/index.cjs.js:1035:17
    at async CatalogBuilder.build (/opt/test/node_modules/@backstage/plugin-catalog-backend/dist/cjs/CatalogBuilder-60d67596.cjs.js:6513:22)
    at async createPlugin (webpack-internal:///./src/plugins/catalog.ts:14:42)
    at async main (webpack-internal:///./src/index.ts:98:31)
```

### 👍 Expected behavior

Be able to conneck to remoute DB with SSL.

### 👎 Actual Behavior with Screenshots

```
Backend failed to start up Error: Failed to connect to the database to make sure that 'backstage_plugin_catalog' exists, error: odyssey: c9da4157ae029: route for 'postgres.backstagedb' is not found
    at /opt/test/node_modules/@backstage/backend-common/dist/index.cjs.js:1035:17
    at async CatalogBuilder.build (/opt/test/node_modules/@backstage/plugin-catalog-backend/dist/cjs/CatalogBuilder-60d67596.cjs.js:6513:22)
    at async createPlugin (webpack-internal:///./src/plugins/catalog.ts:14:42)
    at async main (webpack-internal:///./src/index.ts:98:31)
```

### 👟 Reproduction steps

Follow documentation steps: https://backstage.io/docs/getting-started/configuration

### 🖥️ Your Environment

/opt/test/app-config.yaml
```
  database:
    client: pg
    pluginDivisionMode: schema
    connection:
      host: rc1b-59545tk2dwr7z32y.mdb.yandexcloud.net
      port: 6432
      database: backstagedb
      user: backstagedb.
      password: <PASS>
      ssl:
        rejectUnauthorized: false
        ca:
          $file: /root/.postgresql/root.crt
```

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!
