### ISSUE TITLE
🐛 Bug Report: scaffolder iteration feature erroneously invalidates single-value expression inputs for schema-defined actions

### ISSUE THREAD

**Issue by mbenson** [backstage/backstage#20749]
### 📜 Description

Attempting to specify `each` on a scaffolder step where a required input property is fully specified by a Nunjucks template e.g. `${{ each.value }}` or even `${{ each.value.some.nested['property'] }}` will cause the workflow runner to invalidate the entire action (due to the validation taking place at a point in time during which there is no `each` value in the evaluation context).

### 👍 Expected behavior

Because validation and action authorization consider the action input, the workflow runner should perform these tasks on a per-iteration basis rather than once in ignorance of these parts of the context.

### 👎 Actual Behavior with Screenshots

The released code actually fails the entire step execution with a schema validation error.

### 👟 Reproduction steps

Example template that triggers the bug:
```
apiVersion: scaffolder.backstage.io/v1beta3
kind: Template

metadata:
  name: eachx
  title: each example
  description: TODO

spec:
  type: example

  parameters:
    - title: Fill in some steps
      required:
        - whatever
      properties:
        whatever:
          title: Whatever
          type: string
  steps:
    - id: fetch-base
      name: Fetch Base
      each:
        - ./template
      action: fetch:template
      input:
        url: ${{each.value}}
        values:
          name: ${{parameters.whatever}}
```

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!
