### ISSUE TITLE
🐛 Bug Report: Scaffolder breaks on $text variable in catalog-info.yaml

### ISSUE THREAD

**Issue by TheDukeDK** [backstage/backstage#20831]
### 📜 Description

We are trying to scaffold the following flow.

1. Template and publish a Python FastAPI repo
2. Trigger a build of the newly create repo and build a container
3. Deploy the container which has a working swagger endpoint

This all works until we add the following to the catalog-info.yaml of the newly created repo.

```
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: ${{ values.name }}
  description: Generated API definition for ${{ values.name }}.
  links:
    - url: https://${{ values.repoUrl.host }}/projects/${{ values.repoUrl.project }}/repos/${{ values.repoUrl.repo }}/browse
      title: Repository
    - url: https://${{ values.repoUrl.host }}/projects/${{ values.repoUrl.project }}/repos/${{ values.repoUrl.repo }}/pull-requests
      title: Pull Requests
spec:
  type: openapi
  lifecycle: experimental
  owner: ${{ values.owner }}
  system: ${{ values.system }}
  definition:
    $text: https://${{ values.name }}.test.k8s.nemlig/openapi.json
```
The scaffolder breaks when templating the API because of the `$text` variable with the error message.

```
{"error":{"name":"InputError","message":"InputError: Processor PlaceholderProcessor threw an error while preprocessing; caused by Error: Placeholder $text could not read location [https://no-way.test.k8s.nemlig/openapi.json, Opens in a new window](https://no-way.test.k8s.nemlig/openapi.json), Error: Unable to read [https://no-way.test.k8s.nemlig/openapi.json, Opens in a new window](https://no-way.test.k8s.nemlig/openapi.json), FetchError: request to [https://no-way.test.k8s.nemlig/openapi.json, Opens in a new window](https://new-service.test.k8s.nemlig/openapi.json) failed, reason: getaddrinfo EAI_AGAIN new-service.test.k8s.nemlig"},"request":{"method":"POST","url":"/locations?dryRun=true"},"response":{"statusCode":400}}
```

### 👍 Expected behavior

The scaffolder should continue and ignore the placeholder variable `$text`. It's a placeholder the scaffolder should not make a decision as to when it should be valid. If it is empty then let it be empty. Don't break the whole process and it's a pretty standard flow for scaffolding a new component. 

### 👎 Actual Behavior with Screenshots

The scaffolder fails when templating the API because of a placeholder variable `$text`.
![image](https://github.com/backstage/backstage/assets/8044990/93d1bada-62ff-4217-ae0b-8ca87e8f0b7f)

### 👟 Reproduction steps

Create a scaffolder run with a templated repository that has the following defined in the catalog-info.yaml.
```
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: ${{ values.name }}
  description: Generated API definition.
spec:
  type: openapi
  lifecycle: experimental
  owner: ${{ values.owner }}
  system: ${{ values.system }}
  definition:
    $text: https://${{ values.name }}.not-yet-running.com/openapi.json
```
Run the scaffolder.

### 📃 Provide the context for the Bug.

Trying to template a small Python Fast API which has swagger endpoint built in, which will be deployed and available as last step in scaffolding template.

### 🖥️ Your Environment

Scaffolder plugin version 1.17.3
 

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else
