### ISSUE TITLE
🚀 Feature: Cloudflare Service Token support for Cloudflare Access Auth Provider

### ISSUE THREAD

**Issue by tylerd-canva** [backstage/backstage#20924]
### 🔖 Feature description

I would like to extend the `cfaccess` auth provider to support Cloudflare Service Tokens. As Service Tokens do not have an identity associated with them, there would need to be some additional configuration added so the auth provider knows what to return.

### 🎤 Context

My team has a couple of uses cases for accessing our Cloudflare Access-secured Backstage instance with Cloudflare Service Tokens in addition to normal JWTs which represent humans. Unfortunately the `cfaccess` auth provider does not support this as the [get-identity](https://github.com/backstage/backstage/blob/master/plugins/auth-backend/src/providers/cloudflare-access/provider.ts#L226) check for a Service Token returns an error.

### ✌️ Possible Implementation

I have a quick/dirty POC here: https://github.com/backstage/backstage/compare/master...tylerd-canva:backstage:tylerd/cfaccess-token-poc

Here's a sample of the config I'm introducing:

```
auth:
  # see https://backstage.io/docs/auth/ to learn about auth providers
  providers:
    cfaccess:
      teamName: 'cloudflare-team-name'
      tokenIdentities:
        'some-cf-access-token-id.access': 'some-user@canva.com'
```

However this is not strictly necessary -- the `CloudflareIdentity` response could be filled out with data purely from the JWT, for example:

```
cfIdentity = {
  id: subject,
  name: 'Bot User',
  email: `${subject}@${this.teamName}.com`,
  groups: [],
};
```

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!
