### ISSUE TITLE
🚀 Feature: Auto discovery Backstage templates in a repository

### ISSUE THREAD

**Issue by twanbeeren** [backstage/backstage#20959]
### 🔖 Feature description

I would like to add a mechanism where it's possible to discover all templates that are created within a repository so I don't have to create an extra static catalog.location for each template that I'm building.

```
catalog:
  locations:
    - type: url
      target: https://github.com/backstage/software-templates/blob/main/scaffolder-templates/react-ssr-template/template.yaml
      rules:
        - allow: [Template]
```

Instead I expect something like this, where every template in this directory is picked up by backstage.

```
catalog:
  locations:
    - type: url
      target: https://github.com/backstage/software-templates/blob/main/scaffolder-templates
      rules:
        - allow: [Template]
```

### 🎤 Context

Right now we're using backstage to provide our customers who have developers to use existing templates but also let them create their own templates. 

They won't get access to the configuration of backstage since we (Ops team) are responsible for maintaining the tool. 

Right now if a developer want to use their own created templates to create components (microservices) there is a manual action required. 

### ✌️ Possible Implementation

Maybe there is a way to add an annotation to the kind Template, like we do with Components. And if files in a directory have this annotation the file can be considered as template?

backstage.io/template

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by efenner-cambia** [comment]
@twanbeeren There are a few existing patterns you might be able to use make it more self service within the current model:

In app-config provide a static location for an `all-templates.yml` in your templates repo that allows Locations and Templates. In that file, you provide another location with multiple targets, using relative links to point to each of the `template.yml` files that you want to import. See the [catalog-model](https://github.com/backstage/backstage/blob/03b9c28159c5e229639e9d492b5f21150d473588/packages/catalog-model/examples/all-apis.yaml) for an example of how this works.

Since the `all-templates.yml` file is co-located with the template files, your contributors should be able to add their template there for discovery. You could even add a template for creating templates that would add the created template to `all-templates` during the scaffolding process.

Another option if you are using a discovery entity provider like [GithubEntityProvider](https://backstage.io/docs/integrations/github/discovery#configuration) is to configure an instance of the provider to search for all files matching the desired pattern in your repo like this.

```yaml
templateProvider:
        organization: 'your-org' # string
        catalogPath: '/templates/**/*template.yaml' # this will search all folders for files that end in template.yaml
        filters: # optional filters
          branch: 'main' # optional string
          repository: 'template-repo' # optional Regex
```

With the appropriate regex filters and wildcards in the path, I think you could achieve your desired behavior.
