### ISSUE TITLE
🐛 Bug Report: Cannot host catalog on S3, nor get Techdocs on S3

### ISSUE THREAD

**Issue by Vinzz** [backstage/backstage#21103]
### 📜 Description

We are currently struggling with Backstage Software Catalog on S3

we have both configurations pointing to S3, for techdocs and for catalog:

On the S3 root, we have a catalog-info.yaml file and a /docs folder with htlm rendered mkdocs

```
techdocs:
  builder: external # Alternatives - 'local'
  generator:
    runIn: 'local' # Alternatives - 'local'
  publisher:
    type: awsS3 # Alternatives - 'googleGcs' or 'local'. Read documentation for using alternatives.
    awsS3:
      bucketName: xx
      region: xx
      endpoint: xx
      s3ForcePathStyle: true
      credentials:
        accessKeyId: ${S3_ACCESS_KEY_ID}
        secretAccessKey: ${S3_SECRET_ACCESS_KEY}
catalog:
  providers:
    awsS3:
      bucketName: xx
      region: xx
      endpoint: xx
      s3ForcePathStyle: true
      credentials:
        accessKeyId: ${S3_ACCESS_KEY_ID}
        secretAccessKey: ${S3_SECRET_ACCESS_KEY}
      schedule: # optional; same options as in TaskScheduleDefinition
        # supports cron, ISO duration, "human duration" as used in code
        frequency: { minutes: 30 }
        # supports ISO duration, "human duration" as used in code
        timeout: { minutes: 3 }
```

catalog-info.yaml is at the root of the S3 bucket

```
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: component-name
  description: |
    Build and run your Apps
  links:
    - title: Website
      url: https://www.site.com
    - title: Documentation
      url: https://documentation.com/
  annotations: 
    backstage.io/techdocs-ref: dir:./docs
spec:
  type: tool
  owner: owner
  lifecycle: production
```

### 👍 Expected behavior

The software catalog should appear on our backstage webApp, with the corresponding techdoc

### 👎 Actual Behavior with Screenshots

Connection to the S3 bucket is OK:

`│ {"level":"info","message":"Successfully connected to the AWS S3 bucket xxxxxx.","plugin":"techdocs","service":"backstage","type":"plugin"}       ` 

and actually there's no component in our catalog

`All components (0)`

### 👟 Reproduction steps

Install backstage from the default helm template, and configure access to an S3 bucket as described above.

### 📃 Provide the context for the Bug.

We failed to find a complete doc for S3 based Software catalog, or missed it. Did we miss something?

### 🖥️ Your Environment

Browser: Firefox, is it relevant in that context?

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else
