### ISSUE TITLE
🐛 Bug Report: org.yaml load failed but no error when the user's name is purely numerical

### ISSUE THREAD

**Issue by DiyuanZhang** [backstage/backstage#21242]
### 📜 Description

When I tried to add a new user to my Backstage App the name was purely numerical in org.yaml file. The User and Group kind disappeared from my UI. It seems like the whole org.yaml file loaded failed.

### 👍 Expected behavior

The org.yaml should be loaded successfully or at least an error message showed the name can not be purely numerical

### 👎 Actual Behavior with Screenshots

The org.yaml file loaded failed without any error message

## Step to reproduce this issue
- Start a new Backstage App npx @backstage/create-app@latest
![image](https://github.com/backstage/backstage/assets/34833040/0c65e850-734f-4551-849d-300842c579c2)
- Add a new User to org.yaml
```
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: 123456789
spec:
  profile:
    displayName: "123456789"
    email: 123456789@fakeemail.com
  memberOf: [guests]
```
- All the entities in the org.yaml disappeared (User and Group)
![image](https://github.com/backstage/backstage/assets/34833040/cca06c8c-83b7-4a0b-a166-c115552e94b4)

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None
