### ISSUE TITLE
Github MultiOrgEntity Provider using Github App Authentication type does not pull emails from Github

### ISSUE THREAD

**Issue by joshua-obasaju-sky** [backstage/backstage#21359]
### 📜 Description

Both GithubMultiOrgProvider and GithubOrgProvider while using Github App Authentication type do not pull emails from Github.

From this logic https://github.com/backstage/backstage/blob/af3c08e6607f3e9e486bb9958744982eb056d625/plugins/catalog-backend-module-github/src/lib/github.ts#L171 

and here 
https://github.com/backstage/backstage/blob/af3c08e6607f3e9e486bb9958744982eb056d625/plugins/catalog-backend-module-github/src/lib/github.ts#L151

obviously, you are ignoring the email whenever the token type is app. 

### 👍 Expected behavior

emails should not be ignored when the token type is app

### 👎 Actual Behavior with Screenshots

Email is ignored when token type is app

this is one example of githubUser coming in from the GithubMultiOrgProvider

```
 user pulled in  {
   avatarUrl: 'https://avatars.githubusercontent.com/u/132474028?v=4',
   bio: '',
   login: 'joshua-obasaju-sky',
   name: 'Joshua Obasaju',
   organizationVerifiedDomainEmails: []
 }

```
email is not pulled in. 

### 👟 Reproduction steps

This configuration is in app-config.yaml

```
integrations:
  github:
    - host: github.com
      apps:
        - appId: ${GITHUB_APP_ID}
          webhookUrl: ${GITHUB_APP_WEBHOOK_URL}
          clientId: ${GITHUB_APP_CLIENT_ID}
          clientSecret: ${GITHUB_APP_CLIENT_SECRET}
          webhookSecret: ${GITHUB_APP_WEBHOOK_SECRET}
          privateKey: ${GITHUB_APP_CLIENT_PRIVATE_KEY}
```

```
In user transformer here 

  userTransformer: async (user, ctx): Promise<UserEntity | undefined> => {
        const entity = await defaultUserTransformer(user, ctx);

        console.log('user pulled in ', user);

        if (entity && user.organizationVerifiedDomainEmails?.length) {
          entity.spec.profile!.email = user.email;
        }

        return entity;
      },
```

Print looks this way 

```
 user pulled in  {
   avatarUrl: 'https://avatars.githubusercontent.com/u/132474028?v=4',
   bio: '',
   login: 'joshua-obasaju-sky',
   name: 'Joshua Obasaju',
   organizationVerifiedDomainEmails: []
 }
```

### 📃 Provide the context for the Bug.

Our Authentication source of truth is Azure AD, we want to use Github as our teams and Group's source of truth.

In order to achieve ownership and groups each user belongs to, we want to use email as a way of connecting logged-in AD Users with GitHub Users.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None
