### ISSUE TITLE
🐛 Bug Report: Backstage executeShellCommand function error

### ISSUE THREAD

**Issue by ronballesteros** [backstage/backstage#21369]
### 📜 Description

Using the Backstage action function [executeShellCommand](https://backstage.io/docs/reference/plugin-scaffolder-backend.executeshellcommand/), I created a simple custom action (not a typescript expert) to run a shell command with added optional parameters.  

When trying to run it via software templates, I get this error message:

[2](http://localhost:7007/create/tasks/c9dd73ad-ae89-4379-9ef0-00d5a5e08363#line-2)2023-11-17T07:28:33.935Z Error: spawn ././github/[codeowners.sh, Opens in a new window](http://codeowners.sh/) ENOENT[3](http://localhost:7007/create/tasks/c9dd73ad-ae89-4379-9ef0-00d5a5e08363#line-3)    at Process.ChildProcess._handle.onexit (node:internal/child_process:285:19)[4](http://localhost:7007/create/tasks/c9dd73ad-ae89-4379-9ef0-00d5a5e08363#line-4)    at onErrorNT (node:internal/child_process:485:16)[5](http://localhost:7007/create/tasks/c9dd73ad-ae89-4379-9ef0-00d5a5e08363#line-5)    at processTicksAndRejections (node:internal/process/task_queues:83:21)

Has anyone created a custom action for executing shell commands or know what could be the issue here?

Reason why I wanted to test this was to "transform" files with different file formats (other than yaml or json) or yaml files that are sort of complex. 

Here is the custom action for reference:
```
import { createTemplateAction } from '@backstage/plugin-scaffolder-node';
import {executeShellCommand} from '@backstage/plugin-scaffolder-node';
import { z } from 'zod';

export const bashScript = () => {
  return createTemplateAction({
    id: 'custom:run:bashScript',
    schema: {
      input: z.object({
        scriptPath: z.string().describe('The path to the bash script'),
        additionalParams: z.array(z.string()).optional().describe('Additional parameters for the bash script'),
      }),
    },
    async handler(ctx) {
      const scriptPath = ctx.input.scriptPath;
      const additionalParams = ctx.input.additionalParams || [];

      if (!scriptPath) {
        throw new Error('The script path must be provided.');
      }

      // Execute the shell command with optional additional parameters
      await executeShellCommand({
        command: `./${scriptPath}`,
        args: additionalParams,
        logStream: ctx.logStream,
      });

      ctx.logger.info(`${scriptPath} script executed with optional parameters successfully`);
    },
  });
};
```

### 👍 Expected behavior

Just execute the shell command with no errors.

### 👎 Actual Behavior with Screenshots

Gave me an error below:
<img width="679" alt="Screenshot 2023-11-16 at 9 34 28 PM" src="https://github.com/backstage/backstage/assets/97519591/046a4511-1247-4dc5-b093-e4fbe5e4166e">

### 👟 Reproduction steps

1. Created a custom action in `packages/backend/src/plugins
2. Imported it into `packages/backend/src/plugins/scaffolder.ts`
3. Created a software template
4. Ran the software template

### 📃 Provide the context for the Bug.

Just the error message provided 

### 🖥️ Your Environment

yarn run v1.22.19
OS:   Darwin 23.1.0 - darwin/arm64
node: v16.3.0
yarn: 1.22.19
cli:  0.22.13 (installed)
backstage:  1.18.0

Dependencies:
  @backstage/app-defaults                                          1.4.3
  @backstage/backend-app-api                                       0.5.3, 0.5.4
  @backstage/backend-common                                        0.19.5, 0.19.6
  @backstage/backend-dev-utils                                     0.1.1
  @backstage/backend-openapi-utils                                 0.0.4
  @backstage/backend-plugin-api                                    0.6.3, 0.6.4
  @backstage/backend-tasks                                         0.5.8, 0.5.9
  @backstage/catalog-client                                        1.4.4
  @backstage/catalog-model                                         1.4.2
  @backstage/cli-common                                            0.1.12
  @backstage/cli-node                                              0.1.4
  @backstage/cli                                                   0.22.13
  @backstage/config-loader                                         1.5.0
  @backstage/config                                                1.1.0
  @backstage/core-app-api                                          1.10.0
  @backstage/core-components                                       0.12.5, 0.13.5
  @backstage/core-plugin-api                                       1.6.0
  @backstage/errors                                                1.2.2
  @backstage/eslint-plugin                                         0.1.3
  @backstage/integration-aws-node                                  0.1.6
  @backstage/integration-react                                     1.1.19
  @backstage/integration                                           1.7.0
  @backstage/plugin-api-docs                                       0.9.11
  @backstage/plugin-app-backend                                    0.3.51
  @backstage/plugin-app-node                                       0.1.3
  @backstage/plugin-auth-backend-module-gcp-iap-provider           0.1.0
  @backstage/plugin-auth-backend-module-github-provider            0.1.0
  @backstage/plugin-auth-backend-module-gitlab-provider            0.1.0
  @backstage/plugin-auth-backend-module-google-provider            0.1.0
  @backstage/plugin-auth-backend-module-oauth2-provider            0.1.0
  @backstage/plugin-auth-backend                                   0.19.0
  @backstage/plugin-auth-node                                      0.3.0, 0.3.1
  @backstage/plugin-catalog-backend-module-github                  0.4.0
  @backstage/plugin-catalog-backend-module-scaffolder-entity-model 0.1.0
  @backstage/plugin-catalog-backend-module-unprocessed             0.3.1
  @backstage/plugin-catalog-backend                                1.13.0
  @backstage/plugin-catalog-common                                 1.0.16
  @backstage/plugin-catalog-graph                                  0.2.36
  @backstage/plugin-catalog-import                                 0.10.0
  @backstage/plugin-catalog-node                                   1.4.4
  @backstage/plugin-catalog-react                                  1.8.4
  @backstage/plugin-catalog-unprocessed-entities                   0.1.3
  @backstage/plugin-catalog                                        1.13.0
  @backstage/plugin-events-node                                    0.2.12
  @backstage/plugin-github-actions                                 0.6.5
  @backstage/plugin-kubernetes-backend                             0.12.0
  @backstage/plugin-kubernetes-common                              0.6.6
  @backstage/plugin-kubernetes                                     0.10.3
  @backstage/plugin-org                                            0.6.14
  @backstage/plugin-permission-backend                             0.5.26
  @backstage/plugin-permission-common                              0.7.8
  @backstage/plugin-permission-node                                0.7.14, 0.7.15
  @backstage/plugin-permission-react                               0.4.15
  @backstage/plugin-proxy-backend                                  0.4.0
  @backstage/plugin-scaffolder-backend                             1.17.0
  @backstage/plugin-scaffolder-common                              1.4.1
  @backstage/plugin-scaffolder-node                                0.2.3
  @backstage/plugin-scaffolder-react                               1.5.5
  @backstage/plugin-scaffolder                                     1.15.0
  @backstage/plugin-search-backend-module-catalog                  0.1.7
  @backstage/plugin-search-backend-module-pg                       0.5.12
  @backstage/plugin-search-backend-module-techdocs                 0.1.7
  @backstage/plugin-search-backend-node                            1.2.7
  @backstage/plugin-search-backend                                 1.4.3
  @backstage/plugin-search-common                                  1.2.6
  @backstage/plugin-search-react                                   1.7.0
  @backstage/plugin-search                                         1.4.0
  @backstage/plugin-tech-radar                                     0.6.8
  @backstage/plugin-techdocs-backend                               1.7.0
  @backstage/plugin-techdocs-module-addons-contrib                 1.1.0
  @backstage/plugin-techdocs-node                                  1.8.0
  @backstage/plugin-techdocs-react                                 1.1.11
  @backstage/plugin-techdocs                                       1.7.0
  @backstage/plugin-user-settings                                  0.7.10
  @backstage/release-manifests                                     0.0.10
  @backstage/test-utils                                            1.4.3
  @backstage/theme                                                 0.2.19, 0.4.2
  @backstage/types                                                 1.1.1
  @backstage/version-bridge                                        1.0.5
Done in 2.17s.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by benjdlambert** [comment]
Hmm, can we see the full `template.yaml` definition? It looks like something could be weird with the paths maybe, or that the files doesn't exist in the working directory.

**Comment by ronballesteros** [comment]
thanks @benjdlambert here is the test template.yaml:

```
apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: test-shell
  title: TEST Shell
  description: Test execute shell function
spec:
  owner: sre
  type: service
  parameters:
    - title: Bash Script Execution
      required:
        - scriptPath
      properties:
        scriptPath:
          type: string
          title: Path to Bash Script
          description: The relative or absolute path to the bash script to execute
        additionalParams:
          type: array
          title: Additional Parameters
          description: Optional additional parameters for the bash script
          items:
            type: string
  steps:
    - id: fetch-template
      name: Fetch 
      action: fetch:plain
      input:
        url: omitted
        targetPath: ./github

    - id: run-bash-script
      name: Run Custom Bash Script
      action: custom:run:bashScript
      input:
        scriptPath: ${{ parameters.scriptPath }}
        additionalParams: ${{ parameters.additionalParams }}

    - id: publish
      name: Publish PR
      action: publish:github:pull-request
      input:
        repoUrl: omitted
        branchName: test-shell-execution
        gitCommitMessage: test-shell-execution
        title: test-shell-execution-initial-commit
        requiredCommitSigning: true
```
