### ISSUE TITLE
🚀 Feature: authenticate to clusters with mTLS x509 client certs

### ISSUE THREAD

**Issue by jamieklassen** [backstage/backstage#21486]
### 🔖 Feature description

Kubernetes has supported [mTLS auth](https://kubernetes.io/docs/reference/access-authn-authz/authentication/#x509-client-certificates) for ages -- let's add support for it to Backstage.

### 🎤 Context

I'm mainly thinking of the Pinniped Concierge, which uses very short-lived x509 client certs. But I do know that for a time, AKS clusters would use client certs in their default kubeconfigs, and `kind` also uses a client cert for its super-admin user. In general, I'd like integrators to be able to write a custom `AuthenticationStrategy` whose `getCredential` method returns something like `{cert: '<PEM-encoded cert>', key: '<RSA key string>'}` and have the usual kubernetes-backend APIs work seamlessly.

To help illustrate, maybe an enterprising integrator could write a `clientCert` authStrategy allowing for clusters like this (ignoring the security problems with storing certs and keys in entity annotations...):

```yaml
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata: 
  name: kind-cluster
  annotations: 
    kubernetes.io/api-server: https://127.0.0.1:62017 # or whatever port kind is running on
    kubernetes.io/api-server-certificate-authority: # $(kubectl config view --raw -o jsonpath='{.clusters[?(@.name=="kind-kind")].cluster.certificate-authority-data}')
    kubernetes.io/auth-provider: clientCert
    kubernetes.io/client-certificate-data: # $(kubectl config view --raw -o jsonpath='{.users[?(@.name=="kind-kind")].user.client-certificate-data}')
    kubernetes.io/client-key-data: # $(kubectl config view --raw -o jsonpath='{.users[?(@.name=="kind-kind")].user.client-key-data}')
spec: 
  type: kubernetes-cluster
  owner: user:guest
```

### ✌️ Possible Implementation

In #19903 I refactored the kubernetes-backend to use the `KubernetesCredential` type, specifically anticipating adding a new member for x509 client certs:

https://github.com/backstage/backstage/blob/85330a5a49fd810f03e92064716a779bb3a33d38/plugins/kubernetes-backend/src/auth/types.ts#L20-L26

Once that is done, two places will need to be updated separately:
1. The proxy, here-ish:
    https://github.com/backstage/backstage/blob/85330a5a49fd810f03e92064716a779bb3a33d38/plugins/kubernetes-backend/src/service/KubernetesProxy.ts#L125-L131
1. The fetcher:
    https://github.com/backstage/backstage/blob/85330a5a49fd810f03e92064716a779bb3a33d38/plugins/kubernetes-backend/src/service/KubernetesFetcher.ts#L249-L276

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!
