### ISSUE TITLE
🚀 Feature: Allow Setting a Callback for the onProxyReq Event in the Proxy-Backend Plugin

### ISSUE THREAD

**Issue by zeshanziya** [backstage/backstage#21528]
### 🔖 Feature description

Currently, the proxy-backend plugin lacks the ability to set a custom callback for the onProxyReq event. This feature would provide users with more flexibility and control over the proxy request process. Enabling a callback would allow for custom logic and modifications to be applied to the outgoing proxy requests.

### 🎤 Context

As each proxy endpoint is associated with a single API Key or Authorization, posing a limitation when we need to override the Authorization header on a per-component basis. Consider the scenario of a New Relic dashboard plugin where multiple New Relic accounts are in use, each corresponding to a specific component. Unfortunately, the current architecture does not support this customization.

A key challenge arises from the fact that proxy requests lack awareness of the current component involved. To address this, I plan to implement a middleware for the Fetch API wrapper. This middleware will set the correct component in the context, utilizing the 'X-Current-Entity-Ref' header. The proxy-override backend plugin will then leverage this header to identify and adapt to the current entity in context, enabling a more granular and flexible approach to proxying requests based on the specific requirements of each component.

### ✌️ Possible Implementation

To address the need for overriding headers based on components, I propose the implementation of a proxy-override plugin, comprising both frontend and backend plugins.

- Frontend Plugin:
   - Provides a user-friendly interface for defining API Keys associated with specific components.
- Backend Plugin:
   - Manages the storage of API Keys in the database.
   - Overrides the proxy request header based on the component and associated API Key.

```yaml
# Default setting for New Relic proxy
'/newrelic/api':
  target: https://api.newrelic.com
  headers:
    X-Api-Key: ${NEWRELIC_API_KEY}

# Proxy Override setting
'/newrelic/api':
  target: https://api.newrelic.com
  headers:
    X-Api-Key: ${NEWRELIC_API_KEY}
  proxyOverride:
    X-Api-Key: '[NEWRELIC_API_KEY]'

```

Workflow:

- On the onProxyReq event, the system checks if proxyOverride is configured for the endpoint.
- It identifies the key to check against the component associated with the current request.
- If an API Key is set for the given component, the header is overridden; otherwise, the default header is used.

This flexible approach allows seamless customization of proxy headers for various components, enhancing the adaptability of the system.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!
