### ISSUE TITLE
🚀 Feature: More Scaffolder Output Possibilities

### ISSUE THREAD

**Issue by raphaelbp12** [backstage/backstage#21607]
### 🔖 Feature description

Currently, the only way of showing info after a Scaffolder creation depends on the user being eager to press a button (`link` or `text`).

Sometimes, it is essential to give more instructions to our users. It can make a difference between a success and a failure usage.

Backstage could provide more tools to customize this screen. We could have always opened `text` panel or `alert boxes`.

This could be a expansion of this issue: [Feature: Scaffolder Text Output #17596](https://github.com/backstage/backstage/issues/17596)

### 🎤 Context

Here in the LEGO Group, we did some user research and discovered that many of our user journeys are affected by needing to be more evident about the next step. The developer skips or closes the output screen without even considering clicking the buttons. And it creates some friction in our processes.

Then, talking to our UX Designer, we agreed that it would be a significant improvement to have the ability to show some text in the Output Screen.

### ✌️ Possible Implementation

I found [this PR](https://github.com/backstage/backstage/pull/17641) as a guideline for contributing to this component, and I would like to follow the same idea/philosophy.

* Alert Box - types: info, success, warning, alert
```yml
output:
  alert:
    - title: Test Text
      type: info
      content: |
        Hello, world! This is some markdown!

        ```
        console.log("Hello, world!");
        ```
```
* Fixed text panel
```yml
output:
  text-panel:
    - title: Test Text
      content: |
        Hello, world! This is some markdown!

        ```
        console.log("Hello, world!");
        ```
```

Or even, the current `text` field could be changed to have a new `opened` property to change the default state to "opened". Then, the user could interact with the button and close it.
```yml
output:
  text:
    - title: Test Text
      opened: true
      content: |
        Hello, world! This is some markdown!

        ```
        console.log("Hello, world!");
        ```
```

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!
