### ISSUE TITLE
🐛 Bug Report: hidden parameters aren't accessible 

### ISSUE THREAD

**Issue by ayeletdeRoos** [backstage/backstage#21634]
### 📜 Description

Hi, we just migrated to backstage v1.20.2 (from backstage v1.16)

we used in hidden parameters in scaffolder yaml templates and accessed it later on.

e.g.
```
        hiddenAuthHeader:
          title: okta Authorization header (hidden)
          type: string
          ui:field: AuthHeaderResolver
          ui:backstage:
            review:
              show: false # won't print any info about 'hidden' property on Review Step
              
```
              and then accessed like this:
              
```
                  - id: create_service_request
      name: Creating Service
      action:generate-service
      input:
        token: 'Bearer ${{ parameters.hiddenAuthHeader }}'
```

after the upgrading to v1.20.2 this stopped working and hidden params result in an empty string.

### 👍 Expected behavior

hidden variables are accessible via the scaffolder template

### 👎 Actual Behavior with Screenshots

empty

### 👟 Reproduction steps

try accessing hidden params in your template

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None
