### ISSUE TITLE
🚀 Feature: Support AWS IRSA for Kubernetes Plugin

### ISSUE THREAD

**Issue by clementblaise** [backstage/backstage#21695]
### 🔖 Feature description

Currently, the kubernetes-backend can authenticate with AWS using an assume role as such:
```yaml
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: demo
  annotations:
    kubernetes.io/api-server: 'https://CLUSTER.xx.region.eks.amazonaws.com'
    kubernetes.io/auth-provider: 'aws'
    kubernetes.io/aws-assume-role: 'arn:aws:iam::0000002:role/my-role'
spec:
  type: kubernetes-cluster
  system: demo
  owner: demo
```

Setting `kubernetes.io/auth-provider: 'aws'` will initiate the authentication as a Node. I had the following error, which mentions the Role attached to the NodeGroup:
```
Errors: Request failed with 500 , {"error":"User: arn:aws:sts::0000001:assumed-role/my-cluster-my-nodegroug is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam::0000002:role/my-role"}
```

The feature adds the option to use Kubernetes `ServiceAccount` to authenticate with AWS, an end user would be able to use the feature with either:
- an annotation on `type=kubernetes-cluster` Component: ` kubernetes.io/aws-irsa: 'true'`
- a parameter on `config` clusterLocatorMethods

### 🎤 Context

The feature allows authenticating using IAM roles for service accounts (IRSA) for the Kubernetes plugin.

IRSA usage is pretty common as it simplifies configuration and provides more granular control over permissions given in the cluster. The current method allows all workloads in the cluster to use the Role. Introducing the feature will enable allowing a specific service account with a Role, for example :
```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Principal": {
                "Federated": "arn:aws:iam::0000001:oidc-provider/oidc.region.amazonaws.com/id/CLUSTER"
            },
            "Action": [
                "sts:AssumeRole"
            ],
            "Condition": {
                "StringLike": {
                    "oidc.eks.region.amazonaws.com/id/CLUSTER:sub": "system:serviceaccount:backstage:backstage"
                }
            }
        }
    ]
}
```

### ✌️ Possible Implementation

Looking at the implementation in upbound/provider-aws, the AWS SDK v2 has the `NewWebIdentityRoleProvider` function:
https://github.com/upbound/provider-aws/blob/9e21d5986261210ecf4c2e794aead35fe9cb8140/internal/clients/provider_config.go#L300-L319

Looking at the documentation, the previous method is deprecated; we could implement [NewWebIdentityRoleProviderWithOptions](https://pkg.go.dev/github.com/aws/aws-sdk-go@v1.48.10/aws/credentials/stscreds#NewWebIdentityRoleProviderWithOptions) instead.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!
