### ISSUE TITLE
🐛 Bug Report: Validation Failed when adding a team collaborator - action: publish:github

### ISSUE THREAD

**Issue by msoranno** [backstage/backstage#21722]
### 📜 Description

I'm very new to backstage :(.  
Publishing a private github repo, I'm getting a **Validation Failed** error when team collaborators are trying to be added to the repo:

```
warn: Skipping Admin access for myOrg/admins_all_dg, Validation Failed
warn: Skipping Read access for myOrg/archts_all_dg, Validation Failed
```

The Team format is: **githubOrg/githubTeam**

Here is the code block:

```
- id: publish-k8s-d
      if: ${{ parameters.k8s and parameters.apptype === "d" }}
      name: Publish K8s (d) Type.
      action: publish:github
      input:
        allowedHosts: ['github.company.net']
        description: This is ${{ parameters.name }}
        repoUrl: ${{ parameters.ghHost }}?owner=${{ parameters.org }}&repo=iscp-${{ parameters.apptype }}-${{ parameters.name }}-k8s-tmpl
        requireCodeOwnerReviews: true
        defaultBranch: main
        gitCommitMessage: "Template created by backstage"
        gitAuthorName: "myself"
        allowMergeCommit: true
        allowSquashMerge: true
        repoVisibility: private
        requiredApprovingReviewCount: 1
        protectDefaultBranch: true
        collaborators:
          - team: "${{ parameters.org }}/admins_all_dg"
            access: Admin
          - team: "${{ parameters.org }}/archts_all_dg"
            access: Read
          - team: "${{ parameters.org }}/devops_all_dg"
            access: Read
          - team: "${{ parameters.org }}/devops_tst01"
            access: Write
          - team: "${{ parameters.org }}/obsrvs_all_dg"
            access: Read
```

Any clue will be appreciated :)

### 👍 Expected behavior

All teams specified be added as the repository collaborators. 

### 👎 Actual Behavior with Screenshots

Publishing a private github repo, I'm getting a **Validation Failed** error when team collaborators are trying to be added to the repo:

```
warn: Skipping Admin access for myOrg/admins_all_dg, Validation Failed
warn: Skipping Read access for myOrg/archts_all_dg, Validation Failed
```

### 👟 Reproduction steps

Use this block on the Kind: Template

```
- id: publish-k8s-d
      if: ${{ parameters.k8s and parameters.apptype === "d" }}
      name: Publish K8s (d) Type.
      action: publish:github
      input:
        allowedHosts: ['github.company.net']
        description: This is ${{ parameters.name }}
        repoUrl: ${{ parameters.ghHost }}?owner=${{ parameters.org }}&repo=iscp-${{ parameters.apptype }}-${{ parameters.name }}-k8s-tmpl
        requireCodeOwnerReviews: true
        defaultBranch: main
        gitCommitMessage: "Template created by backstage"
        gitAuthorName: "myself"
        allowMergeCommit: true
        allowSquashMerge: true
        repoVisibility: private
        requiredApprovingReviewCount: 1
        protectDefaultBranch: true
        collaborators:
          - team: "${{ parameters.org }}/admins_all_dg"
            access: Admin
          - team: "${{ parameters.org }}/archts_all_dg"
            access: Read
          - team: "${{ parameters.org }}/devops_all_dg"
            access: Read
          - team: "${{ parameters.org }}/devops_tst01"
            access: Write
          - team: "${{ parameters.org }}/obsrvs_all_dg"
            access: Read
```

### 📃 Provide the context for the Bug.

- Local environment: LOG_LEVEL=debug yarn dev
- Github PAT token configured with full scope.

### 🖥️ Your Environment

OS: WSL Ubuntu
backstage: v1.19.6

```
yarn run v1.22.19
$ concurrently "yarn start" "yarn start-backend"
$ yarn workspace backend start
$ yarn workspace app start
$ backstage-cli package start
$ backstage-cli package start
```

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None
