### ISSUE TITLE
🐛 Bug Report: publish:bitbucketServer:pull-request is not adding new contents to PR

### ISSUE THREAD

**Issue by nightzero** [backstage/backstage#21762]
### 📜 Description

When using the action "publish:bitbucketServer:pull-request" the source-branch is not created and files in my workspace are not added to the pull-request.

It seems this action is only creating the PR, and expects both source and destination branch to exist and the new code already pushed to the PR-branch. I think some important functionality is missing for this feature to be useful.

### 👍 Expected behavior

When using the action "publish:bitbucketServer:pull-request"I expected the source-branch to be created, and files in the workspace (generated by template) are pushed to Bitbucket and added to the PR.

### 👎 Actual Behavior with Screenshots

First I get an error complaining about the fromRef is missing. After manually creating the PR-branch i get the following:
`Unable to create pull requests, 409 Conflict, {"errors":[{"context":null,"message":"Branch \"main\" is already up-to-date with branch \"feature/add-ci-pipeline\" in repository \"yadayada-backend\".","exceptionName":"com.atlassian.bitbucket.pull.EmptyPullRequestException"}]}`

This is because there is no changes in the PR-branch, as new code is not pushed by this action.

### 👟 Reproduction steps

Create a template that creates some files, e.g. with **fetch:template**-action.

First I get an error complaining about the fromRef is missing.

I create the PR-branch (sourceBranch) manually in Bitbucket.

Run the template again. Now I get:
`Unable to create pull requests, 409 Conflict, {"errors":[{"context":null,"message":"Branch \"main\" is already up-to-date with branch \"feature/add-ci-pipeline\" in repository \"yadayada-backend\".","exceptionName":"com.atlassian.bitbucket.pull.EmptyPullRequestException"}]}`

### 📃 Provide the context for the Bug.

This is my template step:
```
- id: publishPR
      name: Publish PR
      action: publish:bitbucketServer:pull-request
      input:
        repoUrl: scm.test.xxx.se?repo=${{ parameters.repoName }}&project=${{ parameters.projectName }}
        sourceBranch: ${{ parameters.prBranch }}
        targetBranch: ${{ parameters.targetBranch }}
        title: Add CI Helm chart
        description: This PR was created by a Backstage scaffolder task to add CI-pipeline to the project.
        token: ${{ parameters.token }}
```

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else
