### ISSUE TITLE
🐛 Bug Report: unable to get local issuer certificate error& socket hang up from techdoc api/catalog request

### ISSUE THREAD

**Issue by imyixiao** [backstage/backstage#21813]
### 📜 Description

We are hosting our backstage website with our corporate certificate and https host. Everything works fine. but when we open the tech doc, the backstage will send out request`/api/catalog/entities/by-name/component/default/` and error out. 

**unable to get local issuer certificate error** 
```
//api-config.yaml
app:
  baseUrl: https://company_domain.com

backend:
  baseUrl: https://company_domain.com
  listen:
    port: 7007
  csp:
    connect-src: ["'self'", "http:", "https:"]
  cors:
    origin: https://company_domain.com
    methods: [GET, HEAD, PATCH, POST, PUT, DELETE]
    credentials: true
  https:
    certificate:
      cert:
        $file: ./sslcert.pem
      key:
        $file: ./sslkey.pem
```
```
//api-config.production.yaml
app:
  baseUrl: https://company_domain

backend:
  baseUrl: https://company_domain
  listen: ':7007'
```
```
//docker container, we have 443:7007 port mapping
docker run  -p 443:7007 backstage 
```
the first error we get is unable to get local issuer certificate error. Then I read this comment https://github.com/backstage/backstage/issues/20518#issuecomment-1832446498 and figure we probably could use http to bypass the certificate error, so i add discovery to our app-config

**socket hang up**
```
//api-config.yaml
app:
  baseUrl: https://company_domain.com

backend:
  baseUrl: https://company_domain.com
  listen:
    port: 7007
  csp:
    connect-src: ["'self'", "http:", "https:"]
  cors:
    origin: https://company_domain.com
    methods: [GET, HEAD, PATCH, POST, PUT, DELETE]
    credentials: true
  https:
    certificate:
      cert:
        $file: ./sslcert.pem
      key:
        $file: ./sslkey.pem
discovery:
  endpoints:
    - target: http://localhost:7007/api/catalog
      plugins: [catalog] 
```
```
//docker container, we have 443:7007 port mapping
docker run  -p 443:7007 7007:7007 backstage 
```
then we will get the socket hang up error

### 👍 Expected behavior

we want the backstage backend to consume the request without going through company firewall

### 👎 Actual Behavior with Screenshots

we get the unable to get local issuer certificate error or socket hang up issue
<img width="1220" alt="Screenshot 2023-12-11 at 11 59 52 AM" src="https://github.com/backstage/backstage/assets/24985717/aac5b221-7f1e-4ba7-8c78-6ebf24142572">

### 👟 Reproduction steps

click on any techdoc

### 🖥️ Your Environment

yarn run v1.22.19
$ /Users/yxiao207/python/src/https/bbgithub.dev.bloomberg.com/backstage/node_modules/.bin/backstage-cli info
OS:   Darwin 23.1.0 - darwin/x64
node: v16.20.0
yarn: 1.22.19
cli:  0.24.0 (installed)
backstage:  1.20.3

Dependencies:
  @backstage/app-defaults                                          1.4.5
  @backstage/backend-app-api                                       0.5.8
  @backstage/backend-common                                        0.19.9
  @backstage/backend-dev-utils                                     0.1.2
  @backstage/backend-openapi-utils                                 0.1.0
  @backstage/backend-plugin-api                                    0.6.7
  @backstage/backend-tasks                                         0.5.12
  @backstage/catalog-client                                        1.4.6
  @backstage/catalog-model                                         1.4.3
  @backstage/cli-common                                            0.1.13
  @backstage/cli-node                                              0.2.0
  @backstage/cli                                                   0.24.0
  @backstage/config-loader                                         1.5.3
  @backstage/config                                                1.1.1
  @backstage/core-app-api                                          1.11.1
  @backstage/core-components                                       0.13.8
  @backstage/core-plugin-api                                       1.8.0
  @backstage/dev-utils                                             1.0.24
  @backstage/errors                                                1.2.3
  @backstage/eslint-plugin                                         0.1.3
  @backstage/frontend-plugin-api                                   0.3.0
  @backstage/integration-aws-node                                  0.1.8
  @backstage/integration-react                                     1.1.21
  @backstage/integration                                           1.7.2
  @backstage/plugin-api-docs                                       0.10.1
  @backstage/plugin-app-backend                                    0.3.55
  @backstage/plugin-app-node                                       0.1.7
  @backstage/plugin-auth-backend-module-gcp-iap-provider           0.2.1
  @backstage/plugin-auth-backend-module-github-provider            0.1.4
  @backstage/plugin-auth-backend-module-gitlab-provider            0.1.4
  @backstage/plugin-auth-backend-module-google-provider            0.1.4
  @backstage/plugin-auth-backend-module-oauth2-provider            0.1.4
  @backstage/plugin-auth-backend                                   0.20.0
  @backstage/plugin-auth-node                                      0.4.1
  @backstage/plugin-catalog-backend-module-github                  0.4.5
  @backstage/plugin-catalog-backend-module-scaffolder-entity-model 0.1.4
  @backstage/plugin-catalog-backend                                1.15.0
  @backstage/plugin-catalog-common                                 1.0.18
  @backstage/plugin-catalog-graph                                  0.3.1
  @backstage/plugin-catalog-import                                 0.10.3
  @backstage/plugin-catalog-node                                   1.5.0
  @backstage/plugin-catalog-react                                  1.9.1
  @backstage/plugin-catalog                                        1.15.1
  @backstage/plugin-events-node                                    0.2.16
  @backstage/plugin-github-actions                                 0.6.8
  @backstage/plugin-graphiql                                       0.3.0
  @backstage/plugin-org                                            0.6.17
  @backstage/plugin-permission-common                              0.7.10
  @backstage/plugin-permission-node                                0.7.18
  @backstage/plugin-permission-react                               0.4.17
  @backstage/plugin-proxy-backend                                  0.4.5
  @backstage/plugin-scaffolder-backend                             1.19.1
  @backstage/plugin-scaffolder-common                              1.4.3
  @backstage/plugin-scaffolder-node                                0.2.8
  @backstage/plugin-scaffolder-react                               1.6.1
  @backstage/plugin-scaffolder                                     1.16.1
  @backstage/plugin-search-backend-module-catalog                  0.1.11
  @backstage/plugin-search-backend-module-pg                       0.5.16
  @backstage/plugin-search-backend-module-techdocs                 0.1.11
  @backstage/plugin-search-backend-node                            1.2.11
  @backstage/plugin-search-backend                                 1.4.7
  @backstage/plugin-search-common                                  1.2.8
  @backstage/plugin-search-react                                   1.7.3
  @backstage/plugin-search                                         1.4.3
  @backstage/plugin-tech-radar                                     0.6.10
  @backstage/plugin-techdocs-backend                               1.9.0
  @backstage/plugin-techdocs-module-addons-contrib                 1.1.2
  @backstage/plugin-techdocs-node                                  1.10.0
  @backstage/plugin-techdocs-react                                 1.1.13
  @backstage/plugin-techdocs                                       1.9.1
  @backstage/plugin-user-settings                                  0.7.13
  @backstage/release-manifests                                     0.0.11
  @backstage/test-utils                                            1.4.5
  @backstage/theme                                                 0.4.4
  @backstage/types                                                 1.1.1
  @backstage/version-bridge                                        1.0.7
✨  Done in 1.18s.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None
