### ISSUE TITLE
🐛 Bug Report: Issue with Kubernetes Core, serviceLocatorMethod: type: 'singleTenant'

### ISSUE THREAD

**Issue by js278** [backstage/backstage#21831]
### 📜 Description
-need help
-area backstage core: kubernetes
I want to show a single cluster in each component assigned..
how can I add multiple clusters but just show one cluster in a designated component

### 👍 Expected behavior

error 
serviceLocatorMethod:
    type: 'singleTenant'
<img width="242" alt="Screen Shot 2023-12-14 at 8 10 41 AM" src="https://github.com/backstage/backstage/assets/143053505/af5b8c4d-8157-4470-97cb-69cbedf08a6b">

### 👎 Actual Behavior with Screenshots

<img width="839" alt="Screen Shot 2023-12-13 at 10 01 20 AM" src="https://github.com/backstage/backstage/assets/143053505/6ca913a4-4d25-454d-991b-753879f11c67">

### 👟 Reproduction steps

  serviceLocatorMethod:
    type: 'multiTenant'

change type to 'singleTenant'

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by jamieklassen** [comment]
In your screenshot the error message mentions `clusterLocatorMethod` rather than `serviceLocatorMethod`. This feels like it might be a configuration issue; maybe you can share a more complete app-config? As described in [the docs](https://backstage.io/docs/features/kubernetes/configuration#cluster-selection-annotation), you can specify the cluster on which a service runs by setting the `backstage.io/kubernetes-cluster` annotation on the corresponding entity.

In my case I can see this working with an `app-config.local.yaml` like:

```yaml
catalog:
  locations:
    - target: ../../dice-roller-single-cluster.yaml
      type: file
kubernetes:
  serviceLocatorMethod:
    type: singleTenant
  clusterLocatorMethods:
    - type: config
      clusters:
        - name: my-cluster # note the name here...
          url: ${URL}
          authProvider: serviceAccount
          serviceAccountToken: ${SERVICEACCOUNT_TOKEN}
```

where `dice-roller-single-cluster.yaml` looks like:

```yaml
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: dice-roller
  description: It rolls dice
  tags:
    - go
  annotations:
    'backstage.io/kubernetes-id': dice-roller
    'backstage.io/kubernetes-cluster': my-cluster # ...the name above appears here
spec:
  type: service
  lifecycle: production
  owner: user:guest
```

**Comment by js278** [comment]
How about the catalog-info.yaml of the file that will need the kubernetes?

**Comment by jamieklassen** [comment]
that's my `dice-roller-single-cluster.yaml`. FWIW files containing entities don't strictly need to be named `catalog-info.yaml`

**Comment by js278** [comment]
<img width="863" alt="Screen Shot 2023-12-14 at 8 30 31 AM" src="https://github.com/backstage/backstage/assets/143053505/d06985fb-2c53-4e79-a078-e64d6c84b4e9">
I update the app config above, here's the result

**Comment by js278** [comment]
I updated the configuration above, here's the result
<img width="863" alt="Screen Shot 2023-12-14 at 8 32 20 AM" src="https://github.com/backstage/backstage/assets/143053505/9782dccc-8144-43b7-9bc5-7dede318bc97">

**Comment by js278** [comment]
I have multiple clusters, and I want to assign them to different components, 1 cluster = 1 componet

**Comment by jamieklassen** [comment]
### error message

Responding to my own comment that

> In your screenshot the error message mentions `clusterLocatorMethod` rather than `serviceLocatorMethod` 

it turns out the error message is just wrong and mistakenly mentions `clusterLocatorMethod` when the `serviceLocatorMethod` is unknown:

https://github.com/backstage/backstage/blob/7b0199f2876c9d5417a954ea28271ce94d6c0fc7/plugins/kubernetes-backend/src/service/KubernetesBuilder.ts#L287-L290

### maybe the feature isn't available in your version of Backstage?

So what version of Backstage are you running (you can run `yarn backstage-cli info` -- this is the purpose of the "Your Environment" heading in the issue template)? The singleTenant serviceLocator wasn't available until [v1.21.0-next.0](https://github.com/backstage/backstage/blob/master/docs/releases/v1.21.0-next.0-changelog.md#minor-changes-7) so probably isn't really considered "released" until [next week](https://github.com/backstage/backstage/pull/20954#issuecomment-1813171833):

> Thank you for contributing to Backstage! The changes in this pull request will be part of the `1.21.0` release, scheduled for Tue, 19 Dec 2023.

### cluster-per-component vs component-per-cluster

I may be over-explaining here, forgive me. As for

> I have multiple clusters, and I want to assign them to different components, 1 cluster = 1 component

that's clear -- but if you're expecting to mark a _cluster_ as being dedicated to a _component_ you'll be confused, as the relationship goes the other way. "single tenant" doesn't mean "exactly one service resides on this cluster", it means "this service resides on exactly one cluster". If this is confusing, maybe there's a better name...

**Comment by js278** [comment]
it's nice. you can explain it as much as you can. I appreciate your help. Do you have any suggestion on how can I do the the assigning of clusters? 

ex. 
list of clusters:
cluster1
cluster2
cluster3

component1 , when going to kubernetes plugin, i will only see cluster 1
component2 , when going to kubernetes plugin, i will only see cluster 2

**Comment by jamieklassen** [comment]
If you want to assign `component1` to `cluster1`, the entity needs an annotation like `backstage.io/kubernetes-cluster: cluster1`, e.g. something like

```yaml
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: component1
  annotations:
    'backstage.io/kubernetes-cluster': cluster1
spec:
  ...
```
