### ISSUE TITLE
🐛 Bug Report: Error while reading users photos from Microsoft Graph

### ISSUE THREAD

**Issue by Tomelin** [backstage/backstage#21879]
### 📜 Description

I'm using the '@backstage/plugin-catalog-backend-module-msgraph' library to load users and team and import in Backstage but returned this error:

I get the following error:
```
[1] 2023-12-15T10:17:20.801Z catalog warn Unable to load user photo for type=plugin user=xxxxx-xxxx-xxxx-xxxx-xxxxxxxx error=Error: Error while reading users photos from Microsoft Graph: UnknownError - 
[1] 2023-12-15T10:17:20.932Z catalog warn Unable to load user photo for type=plugin user=xxxxx-xxxx-xxxx-xxxx-xxxxxxxx  error=Error: Error while reading users photos from Microsoft Graph: UnknownError - 
[1] 2023-12-15T10:17:20.946Z catalog warn Unable to load user photo for type=plugin user=xxxxx-xxxx-xxxx-xxxx-xxxxxxxx  error=Error: Error while reading users photos from Microsoft Graph: UnknownError - 
```

My catalog config is:
```
catalog:
  processingInterval: { minutes: 15 }
  providers:
    microsoftGraphOrg:
      providerId:
          target: https://graph.microsoft.com/v1.0
          authority: https://login.microsoftonline.com
          tenantId: xxxxx-xxxx-xxxx-xxxx-xxxxxxxx
          clientId: xxxxx-xxxx-xxxx-xxxx-xxxxxxxx
          clientSecret: mySecret
          user:
            filter: accountEnabled eq true and userType eq 'member'
            select: [id,mail,displayName,givenName,mobilePhone]
          groupFilter: securityEnabled eq false and mailEnabled eq true and groupTypes/any(c:c+eq+'Unified')
```

My location config is:
```
  import:
    entityFilename: catalog-info.yaml
    pullRequestBranchName: backstage-integration
  rules:
    - allow: [Component, Group, User, System, API, Doamin, Resource, Location, Template]
  locations:
    - type: microsoft-graph-org
      target: https://graph.microsoft.com/v1.0
      rules:
        - allow: [Group, User]
```

My catalog.tsconfig is:
```
import { CatalogBuilder } from '@backstage/plugin-catalog-backend';
import { ScaffolderEntitiesProcessor } from '@backstage/plugin-scaffolder-backend';
import { MicrosoftGraphOrgEntityProvider } from '@backstage/plugin-catalog-backend-module-msgraph';

import { Router } from 'express';
import { PluginEnvironment } from '../types';

export default async function createPlugin(
  env: PluginEnvironment,
): Promise<Router> {
  const builder = await CatalogBuilder.create(env);
  builder.addProcessor(new ScaffolderEntitiesProcessor());
  builder.addEntityProvider(
    MicrosoftGraphOrgEntityProvider.fromConfig(env.config, {
      logger: env.logger,
      schedule: env.scheduler.createScheduledTaskRunner({
        frequency: { minutes: 30 },
        timeout: { minutes: 3 },
      }),
      scheduler: env.scheduler,
    }),
  );
  const { processingEngine, router } = await builder.build();
  await processingEngine.start();
  return router;
}

```

### 👍 Expected behavior

Imported the users and groups/team to Backstage

### 👎 Actual Behavior with Screenshots

I get the following error:
```
[1] 2023-12-15T10:17:20.801Z catalog warn Unable to load user photo for type=plugin user=xxxxx-xxxx-xxxx-xxxx-xxxxxxxx error=Error: Error while reading users photos from Microsoft Graph: UnknownError - 
[1] 2023-12-15T10:17:20.932Z catalog warn Unable to load user photo for type=plugin user=xxxxx-xxxx-xxxx-xxxx-xxxxxxxx  error=Error: Error while reading users photos from Microsoft Graph: UnknownError - 
[1] 2023-12-15T10:17:20.946Z catalog warn Unable to load user photo for type=plugin user=xxxxx-xxxx-xxxx-xxxx-xxxxxxxx  error=Error: Error while reading users photos from Microsoft Graph: UnknownError - 
```

### 👟 Reproduction steps

![image](https://github.com/backstage/backstage/assets/7714663/0fd05c38-3b4c-4bfc-a2e9-9155f4c40fa8)

"@backstage/plugin-catalog-backend-module-msgraph": "^0.5.14",
"@backstage/backend-common": "^0.19.5-next.1",
"@backstage/plugin-catalog-backend": "^1.13.0-next.1",

### 🖥️ Your Environment

OS: Ubuntu 20.04 LTS
Kernel: Linux GS08714N412180P 5.10.16.3-microsoft-standard-WSL2 #1 SMP x86_64 x86_64 x86_64 GNU/Linux
yarn --version 1.22.19
info Current version: 1.0.0
backstage/cli: "^0.22.13-next.1",

Backend dependencies:
    "@backstage/backend-common": "^0.19.5-next.1",
    "@backstage/backend-tasks": "^0.5.8-next.1",
    "@backstage/catalog-client": "^1.4.4-next.0",
    "@backstage/catalog-model": "^1.4.2-next.0",
    "@backstage/config": "^1.1.0-next.0",
    "@backstage/integration": "^1.7.0-next.1",
    "@backstage/plugin-app-backend": "^0.3.51-next.1",
    "@backstage/plugin-auth-backend": "^0.18.9-next.1",
    "@backstage/plugin-auth-node": "^0.3.0-next.1",
    "@backstage/plugin-catalog-backend": "^1.13.0-next.1",
    "@backstage/plugin-catalog-backend-module-azure": "^0.1.26",
    "@backstage/plugin-catalog-backend-module-msgraph": "^0.5.14",
    "@backstage/plugin-permission-backend": "^0.5.30",
    "@backstage/plugin-permission-common": "^0.7.8-next.0",
    "@backstage/plugin-permission-node": "^0.7.14-next.1",
    "@backstage/plugin-playlist-backend": "^0.3.11",
    "@backstage/plugin-proxy-backend": "^0.3.3-next.1",
    "@backstage/plugin-scaffolder-backend": "^1.16.6-next.1",
    "@backstage/plugin-search-backend": "^1.4.3-next.1",
    "@backstage/plugin-search-backend-module-pg": "^0.5.12-next.1",
    "@backstage/plugin-search-backend-node": "^1.2.7-next.1",
    "@backstage/plugin-techdocs-backend": "^1.7.0-next.1",
    "@microsoft/microsoft-graph-types": "^2.40.0",
    "app": "link:../app",
    "better-sqlite3": "^8.0.0",
    "dockerode": "^3.3.1",
    "express": "^4.17.1",
    "express-promise-router": "^4.1.0",
    "moment": "^2.29.4",
    "pg": "^8.3.0",
    "winston": "^3.2.1"

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None
