### ISSUE TITLE
🐛 Bug Report: oneOf operator inside template giving error "circular structure to JSON"

### ISSUE THREAD

**Issue by Nitinvonage** [backstage/backstage#21992]
### 📜 Description

while filling one of the scaffolding template we are getting error "_Converting circular structure to JSON --> starting at object with constructor 'Object' | property 'oneOfSchema' -> object with constructor 'Object' | property 'oneOf' -> object with constructor 'Array' --- index 1 closes the circle_". This was not coming with backstage v1.19, it all started when we switched to v1.20.3

### 👍 Expected behavior

it should work in v1.20.3

### 👎 Actual Behavior with Screenshots

![image](https://github.com/backstage/backstage/assets/110883891/396ce63a-4785-4d73-84f7-e0824b0bc6d3)
when you start filling a template which has oneOf operator it gives you error of circular dependency. looks like this has been fixed for other operators but not for onOf 

### 👟 Reproduction steps

1. Create a dummy template 
2. add oneOf operator inside it
```
title: Framework details
    required:
      - frameworkVersion
    properties:
      frameworkVersion:
        title: Framework Version
        type: string
        oneOf:
          - title: "7.0"
            const: net7.0
          - title: "6.0"
            const: net6.0
          - title: "5.0"
            const: net5.0
        default: net7.0
        description: Select .Net framework version
        
        ui:options:
          rows: 5

```
3. fill this template, after selecting the framework version from dropdown, once next is clicked you will get circular dependency error

### 📃 Provide the context for the Bug.

we are not able to release our new templates

### 🖥️ Your Environment

its not env specific, its coming in local as well
OS -Mac, 13
browser - chrome

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else
