### ISSUE TITLE
🚀 Feature: Add annotations to API consumers to attach contracts

### ISSUE THREAD

**Issue by samstitt** [backstage/backstage#22052]
### 🔖 Feature description

![Screenshot 2023-12-29 at 11 32 23](https://github.com/backstage/backstage/assets/145553195/431cbec0-e627-4ad6-a146-0b6a9f31d4bc)

I have not found a way to do this, so raising it as a feature request. when listing consumers of an API it would be good to have a way of being able to link an API contract to that individual consumer. 

### 🎤 Context

The only way I can see us doing this at the moment is by adding the metadata links to the component itself which does not really link to the API consumer section. adding it here would better manage discovery and change 

### ✌️ Possible Implementation

```
spec:
  consumesApis:
  metadata:
     name: Service-Service-API-Contract
     description: Contract for X
       links:
       - 'https://foo'
```

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!
