### ISSUE TITLE
🐛 Bug Report: template scaffolder secret not support array type

### ISSUE THREAD

**Issue by HoangViet144** [backstage/backstage#22238]
### 📜 Description

When I create a template like this:
```
password_list:
  title: List of password
  type: array
  ui:options:
    orderable: false
  items:
    type: object
    title: " "
    properties:
      password:
        title: Password
        type: string
        ui:field: Secret
```
Then in action step, ```{{ secrets }} ``` only contains the last secret item instead an array of secrets

### 👍 Expected behavior

Secret should be
```
password_list: [
   { 
        password: "abcd"
   },
   {
        password: "cdef"
   },
   ....
],
...
```

### 👎 Actual Behavior with Screenshots

![image](https://github.com/backstage/backstage/assets/54036989/8196f376-3f0d-4792-97e8-dc4a5233d7bc)

### 👟 Reproduction steps

1/ Create a scaffolder template with a list of secret
2/ Insert more than 1 secret item in array
3/ use action ```action: debug:log``` to log secret content to the screen

### 🖥️ Your Environment

Backstage version v1.21.1

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None
