### ISSUE TITLE
🚀 Feature: Utility API for VMware Cloud auth

### ISSUE THREAD

**Issue by jamieklassen** [backstage/backstage#22453]
### 🔖 Feature description

Let's make it easy for integrators to include VMware Cloud sign-in in their apps without writing any special client code.

### 🎤 Context

This requirement arose from discussion on #22392.

Suppose I set up my (old backend system) `packages/backend/src/plugins/auth.ts` like:
```ts
import { Router } from 'express';
import { createRouter } from '@backstage/plugin-auth-backend';
import { createOAuthProviderFactory } from '@backstage/plugin-auth-node';
import { vmwareCloudAuthenticator } from '@backstage/plugin-auth-backend-module-vmware-cloud-provider';
import { PluginEnvironment } from '../types';

export default async function createPlugin(
  env: PluginEnvironment,
): Promise<Router> {
  return await createRouter({
    providerFactories: {
      vmwareCloudServices: createOAuthProviderFactory({
        authenticator: vmwareCloudAuthenticator,
        signInResolver: async (_, ctx) =>
          ctx.issueToken({
            claims: { sub: 'user:guest', ent: ['user:guest'] },
          }),
      }),
    // ...
```

and I set up my (classic frontend system) `App.tsx` a bit like:
```tsx
import { createApp } from '@backstage/app-defaults';
import { vmwareCloudAuthApiRef } from '@backstage/core-plugin-api';

const app = createApp({
  components: {
    SignInPage: props => {
      return (
        <SignInPage
          {...props}
          provider={{
            id: 'vmware-cloud-auth-provider',
            title: 'VMware Cloud',
            message: 'Sign In using VMware Cloud',
            apiRef: vmwareCloudAuthApiRef,
          }}
          title="Select a sign-in method"
          align="center"
        />
      );
    },
  },
  // ...
```

and my app-config resembles:
```yaml
app:
  baseUrl: http://127.0.0.1:3000
backend:
  baseUrl: http://127.0.0.1:7007
  cors:
    origin: [http://127.0.0.1:3000]
auth:
  session:
    secret: mysecret
  environment: development
  providers:
    vmwareCloudServices:
      development:
        clientId: ${VMWARE_CLOUD_APP_ID}
        organizationId: ${VMWARE_CLOUD_ORG_ID}
```

Then I'd like to be able to run the app with `yarn dev`, visit `http://127.0.0.1:3000` in my browser, click 'Sign In', sign in with my VMware account, visit the User Settings page and see my full name and email.

### ✌️ Possible Implementation

As [suggested](https://github.com/backstage/backstage/pull/22392#discussion_r1460908350) by @Rugvip, it should be enough to:
* create API refs in `@backstage/core-plugin-api` and `@backstage/frontend-plugin-api`
* create an implementation in `@backstage/core-app-api`
* create an API factory in `@backstage/app-defaults`

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!
