### ISSUE TITLE
🐛 Bug Report: Scaffolder dependency is rendered as a drop down list instead of the specified type

### ISSUE THREAD

**Issue by Teemukoivumaa** [backstage/backstage#22506]
### 📜 Description

When you have a input parameter that will act as a dependency of other parameters, it will not be rendered as the type you have specified in the template code. It will be rendered as a drop down list instead

### 👍 Expected behavior

Fields should render as they are defined even tough they are used as dependencies

### 👎 Actual Behavior with Screenshots

![image](https://github.com/backstage/backstage/assets/35847478/bd0b8b08-b0e9-4038-89bb-e67230b77e27)

### 👟 Reproduction steps

Example template code:
```yaml
apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: brokenDependency
  title: Example of broken dependencies logic
  description: 'Broken dependencies'
spec:
  owner: ophub-developers
  type: example
  permissions:
    env:
      - local
  parameters:
    - title: Field 2 depend on field 1, field 1 is a radio button but it's visible as a field
      required:
        - exampleField1
      properties:
        exampleField0: # This will be rendered normally
          title: Radio button that is not a dependency
          type: string
          enum:
            - foo
            - bar
          ui:widget: radio
          ui:options:
            inline: true
        exampleField1: # This will be rendered as a drop down list
          title: Radio button input that is a dependency
          type: string
          enum:
            - visible
            - hidden
          ui:widget: radio
          ui:options:
            inline: true
      dependencies:
        exampleField1:
          oneOf:
            - properties:
                exampleField1:
                  enum: ['visible']
                exampleField2:
                  title: 'FIELD 2'
                  type: string
                  description: Explanation
            - properties:
                exampleField1:
                  enum: ['hidden']
  steps:
    - id: helloWorld
      if: ${{ parameters.exampleField1 === 'visible' }}
      name: Visible
      action: debug:log
      input:
        message: Hello, I am visible!
```

### 🖥️ Your Environment

OS:   Linux 5.15.133.1-microsoft-standard-WSL2 - linux/x64
node: v18.17.1
yarn: 1.22.21
cli:  0.25.1 (installed)
backstage:  1.22.1

Dependencies:
  @backstage/app-defaults                                          1.4.7
  @backstage/backend-app-api                                       0.5.10
  @backstage/backend-common                                        0.20.1
  @backstage/backend-dev-utils                                     0.1.3
  @backstage/backend-openapi-utils                                 0.1.2
  @backstage/backend-plugin-api                                    0.6.9
  @backstage/backend-tasks                                         0.5.14
  @backstage/catalog-client                                        1.5.2
  @backstage/catalog-model                                         1.4.3
  @backstage/cli-common                                            0.1.13
  @backstage/cli-node                                              0.2.2
  @backstage/cli                                                   0.25.1
  @backstage/config-loader                                         1.6.1
  @backstage/config                                                1.1.1
  @backstage/core-app-api                                          1.11.3
  @backstage/core-compat-api                                       0.1.1
  @backstage/core-components                                       0.13.10
  @backstage/core-plugin-api                                       1.8.2
  @backstage/e2e-test-utils                                        0.1.0
  @backstage/errors                                                1.2.3
  @backstage/eslint-plugin                                         0.1.4
  @backstage/frontend-plugin-api                                   0.5.0
  @backstage/integration-aws-node                                  0.1.8
  @backstage/integration-react                                     1.1.23
  @backstage/integration                                           1.8.0
  @backstage/plugin-api-docs                                       0.10.3
  @backstage/plugin-app-backend                                    0.3.57
  @backstage/plugin-app-node                                       0.1.9
  @backstage/plugin-auth-backend-module-atlassian-provider         0.1.1
  @backstage/plugin-auth-backend-module-gcp-iap-provider           0.2.3
  @backstage/plugin-auth-backend-module-github-provider            0.1.6
  @backstage/plugin-auth-backend-module-gitlab-provider            0.1.6
  @backstage/plugin-auth-backend-module-google-provider            0.1.6
  @backstage/plugin-auth-backend-module-oauth2-provider            0.1.6
  @backstage/plugin-auth-backend-module-oauth2-proxy-provider      0.1.1
  @backstage/plugin-auth-backend-module-okta-provider              0.0.2
  @backstage/plugin-auth-backend                                   0.20.3
  @backstage/plugin-auth-node                                      0.4.3
  @backstage/plugin-catalog-backend-module-scaffolder-entity-model 0.1.6
  @backstage/plugin-catalog-backend                                1.16.1
  @backstage/plugin-catalog-common                                 1.0.20
  @backstage/plugin-catalog-graph                                  0.3.3
  @backstage/plugin-catalog-import                                 0.10.5
  @backstage/plugin-catalog-node                                   1.6.1
  @backstage/plugin-catalog-react                                  1.9.3
  @backstage/plugin-catalog                                        1.16.1
  @backstage/plugin-events-node                                    0.2.18
  @backstage/plugin-github-actions                                 0.6.10
  @backstage/plugin-org                                            0.6.19
  @backstage/plugin-permission-common                              0.7.12
  @backstage/plugin-permission-node                                0.7.20
  @backstage/plugin-permission-react                               0.4.19
  @backstage/plugin-proxy-backend                                  0.4.7
  @backstage/plugin-scaffolder-backend-module-azure                0.1.1
  @backstage/plugin-scaffolder-backend-module-bitbucket            0.1.1
  @backstage/plugin-scaffolder-backend-module-gerrit               0.1.1
  @backstage/plugin-scaffolder-backend-module-github               0.1.1
  @backstage/plugin-scaffolder-backend-module-gitlab               0.2.12
  @backstage/plugin-scaffolder-backend                             1.20.0
  @backstage/plugin-scaffolder-common                              1.4.5
  @backstage/plugin-scaffolder-node                                0.2.10
  @backstage/plugin-scaffolder-react                               1.7.1
  @backstage/plugin-scaffolder                                     1.17.1
  @backstage/plugin-search-backend-module-catalog                  0.1.13
  @backstage/plugin-search-backend-module-pg                       0.5.18
  @backstage/plugin-search-backend-module-techdocs                 0.1.13
  @backstage/plugin-search-backend-node                            1.2.13
  @backstage/plugin-search-backend                                 1.4.9
  @backstage/plugin-search-common                                  1.2.10
  @backstage/plugin-search-react                                   1.7.5
  @backstage/plugin-search                                         1.4.5
  @backstage/plugin-tech-radar                                     0.6.12
  @backstage/plugin-techdocs-backend                               1.9.2
  @backstage/plugin-techdocs-module-addons-contrib                 1.1.4
  @backstage/plugin-techdocs-node                                  1.11.1
  @backstage/plugin-techdocs-react                                 1.1.15
  @backstage/plugin-techdocs                                       1.9.3
  @backstage/plugin-user-settings                                  0.8.0
  @backstage/release-manifests                                     0.0.11
  @backstage/test-utils                                            1.4.7
  @backstage/theme                                                 0.5.0
  @backstage/types                                                 1.1.1
  @backstage/version-bridge                                        1.0.7

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, I don't have time to work on this right now
