### ISSUE TITLE
🚀 Feature: Improper catalog import alert

### ISSUE THREAD

**Issue by NiklasDoyle** [backstage/backstage#22525]
### 🔖 Feature description

You should add an alert to let the user know when an entity was not imported properly into the catalog.

### 🎤 Context

In my use-case, I imported a `template.yaml` that had some incorrect formatting. The catalog import said it was imported successfully into the catalog, however, when we clicked on the generated catalog template URL, it displayed an "entity not found" warning. 

Successful import:
![Screenshot 2024-01-25 at 4 22 35 PM (1)](https://github.com/backstage/backstage/assets/72467374/31524cf7-6794-42e7-a4a2-e7734b559968)

Entity not found warning:
![Screenshot 2024-01-25 at 4 19 01 PM](https://github.com/backstage/backstage/assets/72467374/a24d96b0-c706-49e1-9d57-dc79145b560e)

### ✌️ Possible Implementation

If the import does not result in the expected entities being created, alert the user that there is an issue.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by vinzscam** [comment]
Hey! It looks like your entity contains an uppercase letter. Maybe that is the reason for the issue?

**Comment by alde** [comment]
if you inspect what is the actual URL it leads to? maybe it gets improperly encoded?

**Comment by jpdeburgo** [comment]
> Hey! It looks like your entity contains an uppercase letter. Maybe that is the reason for the issue?

No, I do not think so, we have been able to successfully import entities into the catalog with a capital letter



> if you inspect what is the actual URL it leads to? maybe it gets improperly encoded?

After inspecting, this is the URL that it leads to: `/catalog/default/template/Test-iast-action-template`. It does not look like it is incorrect. 


We had a user use our developer portal and they found this issue. They could import the template successfully when they changed the `workflowInputs` to have unique case-insensitive variable names. Before the `workflowInputs` looked like this:

```
workflowInputs:
          ...
          operatingSystem: ${{parameters.component.version.operatingSystem}} #java, PHP, Go, Python
          OperatingSystem: ${{parameters.component.OperatingSystem}} #Dotnetcore, DOTNETFramework, Nodejs
          projectName: ${{parameters.component.version.projectName}} #java, PHP, Go
          ProjectName: ${{parameters.component.ProjectName}} #Dotnetcore
          Projectname: ${{parameters.component.projectname}} #Nodejs
          PROJECTNAME: ${{parameters.component.version.operatingSystem.PROJECTNAME}} #Python
          deployment: ${{parameters.component.version.deployment}} #java
          Deployment: ${{parameters.component.Deployment}} #Nodejs
          email: ${{parameters.component.operatingSystem.version.email}} #java
          Email: ${{parameters.component.OperatingSystem.email}} #Dotnetcore
          ...
```

After making unique case-insensitive variable names, they could import the template successfully. The point of this issue however, is to show an alert saying that there was an issue with the `yaml` file attempting to be imported into the catalog since we did not realize it was not imported successfully until we tried to look for it in the catalog. Essentially, it was a false positive.

@alde @vinzscam
