### ISSUE TITLE
🚀 Feature: Multiple Options for allowedHosts

### ISSUE THREAD

**Issue by Awayah** [backstage/backstage#22581]
### 🔖 Feature description

Currently, the Backstage template system allows specifying only one repoUrl under allowedHosts for hosting the template repository, and the corresponding publish action is tightly coupled with that repository.

**Repository Picker Enhancement:**

I propose enhancing the repository picker to provide users with greater flexibility in selecting the name and location of a new repository. Users can choose from a variety of version control hosts such as GitHub, Bitbucket, GitLab..

### Multiple allowedHosts Support:
Allow users to select from a range of version control hosts (e.g., GitHub, Bitbucket, GitLab) during repository creation.
### Conditionally Execute Publish Actions:
Introduce conditional logic to execute a corresponding publish action based on the selected version control host.

### 🎤 Context

**Example Usage:**
```

parameters:
  properties:
    repoUrl:
      type: string
      ui:field: RepoUrlPicker
      ui:options:
        allowedHosts:
          - github.com
          - bitbucket.org
          - gitlab.com

```

Users can create repositories on different version control hosts directly from the Backstage platform.
It simplifies the repository selection process and I don't have to register multiple templates that have the same functionality, but just specify a different host. 

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by acierto** [comment]
@Awayah you can also achieve the same by using `if` conditions in actions, i.e.

```
    - id: publishGithub
      name: Publish GitHub
      action: publish:github
      if: ${{ parameters.repoUrl.includes('github.com') }}
      input:
        allowedHosts: [ "github.com" ]
        description: This is ${{ parameters.name }}
        repoUrl: ${{ parameters.repoUrl }}

    - id: publishGitlab
      name: Publish Gitlab
      action: publish:gitlab
      if: ${{ parameters.repoUrl.includes('gitlab.com') }}
      input:
        allowedHosts: [ "gitlab.com" ]
        description: This is ${{ parameters.name }}
        repoUrl: ${{ parameters.repoUrl }}

    - id: registerGithub
      name: Register
      action: catalog:register
      if: ${{ parameters.repoUrl.includes('github.com') }}
      input:
        repoContentsUrl: ${{ steps.publishGithub.output.repoContentsUrl }}
        catalogInfoPath: "/catalog-info.yaml"

    - id: registerGitlab
      name: Register
      action: catalog:register
      if: ${{ parameters.repoUrl.includes('gitlab.com') }}
      input:
        repoContentsUrl: ${{ steps.publishGitlab.output.repoContentsUrl }}
        catalogInfoPath: "/catalog-info.yaml"

```
