### ISSUE TITLE
🚀 Feature: Allow output for failed templates

### ISSUE THREAD

**Issue by drodil** [backstage/backstage#22660]
### 🔖 Feature description

When a template fails in scaffolder run for some reason, allow the template to output something like a link to reporting an issue or something else.

### 🎤 Context

When the template run fails, there's no information for the user on what to do and who to contact. Allowing output to be shown also for failed templates could help with this. 

### ✌️ Possible Implementation

Add new possibility to templates:

```yaml
failOutput:
  links:
    - ...
  text:
    - ...
```

or add new property to existing output 

```yaml
output:
  links:
    - title: Title
      url: https://github.com/issues
      onFailure: true
  text:
    - ...
```

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None
