### ISSUE TITLE
🚀 Feature(cloudbuild-plugin): should support multiple GCP projects. 

### ISSUE THREAD

**Issue by mugioka** [backstage/backstage#22672]
### 🔖 Feature description

Currently, cloudbuild-plugin only supports a single GCP project.
Therefore, it is not possible to view the cloudbuild history for each GCP project (development/staging).
We would like to support multiple GCP projects so that we can view all cloudbuild history related to a component.

### 🎤 Context

Assume that a user is managing services in multiple GCP Projects(development/staging/production) and is running CI/CD with cloudbuild in each project.
In that case, the user would want to view the cloudbuilds associated with that service on Backstage.

### ✌️ Possible Implementation

Add a new annotation (`google.com/cloudbuild-additional-project-slugs` ) for setting up additional projects.
The value of this annotation will be the slugs of the GCP Project, separated by comma.

ex.
```diff
metadata:
  name: example-website
  annotations:
    google.com/cloudbuild-project-slug: development
+   google.com/cloudbuild-additional-project-slugs: staging,production
    google.com/cloudbuild-repo-name: fensi-id
```

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by Rugvip** [comment]
Any opinions on this @PurseChicken or @ebarriosjr? as previous contributors

**Comment by PurseChicken** [comment]
@mugioka 

To clarify, you have a backstage component in which you would like to display Cloud Build "Build History" from multiple projects?

E.G.
Component Name: my-component
Repo Name: my-components-code
GCP Project: my-component-test and my-component-prod

Both GCP projects have builds associated with the repository my-components-code?

Out of curiosity, is there a reason why you are not separating your test / dev / stg / prod components in backstage?

**Comment by mugioka** [comment]
@PurseChicken 
> To clarify, you have a backstage component in which you would like to display Cloud Build "Build History" from multiple projects?

yes.

> Both GCP projects have builds associated with the repository my-components-code?

yes.

**Comment by PurseChicken** [comment]
@mugioka Thanks for the clarification. I will look into seeing what it will take to get this new feature implemented. I am pretty sure that it will require some significant changes, so It may take a little while.

**Comment by viglesiasce** [comment]
cc @mondragonda can you take a look at this one?

**Comment by mondragonda** [comment]
@PurseChicken @mugioka @Rugvip @viglesiasce  Possibly what could be done is to register a component by environment (e.g. `shuffle-api-development.yaml` and `shuffle-api-staging.yaml`) and use the currently implemented annotation support. This means kind of replicating the same yaml config but would solve linking different GCP projects. I think this would make more sense due to the nature of components description. 

Otherwise I guess it would be better to define the annotation config as an array of configs, perhaps defining it on the `spec` part of the component description. But I do not know if the `spec` key could be used as this:

```
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: shuffle-api
  description: Shuffle API
  labels:
    goVersion: go1.15.3
    category: music
  spec:
    google.com/cloudbuild:
     - project-slug: shuffle-api-dev-410617
       repo-name: shuffle-api-repo
     - project-slug: shuffle-api-staging-410617
       repo-name: shuffle-api-repo
```

If you guys want to leave here your opinions about, I could take the issue and do the necessary changes. Also I would like to know your opinions about enabling the filter by repo or trigger directly as a selection in the UI.

**Comment by mugioka** [comment]
@mondragonda 
Thank you for your response.
>  This means kind of replicating the same yaml config but would solve linking different GCP projects. I think this would make more sense due to the nature of components description.

I would like to avoid defining components for each environment if possible, as it would make the configuration files redundant.
However, I understand that whether a plugin's configuration is enabled or disabled should be toggled by annotation (it is not a good situation to have changes running in the definition under the spec each time a plugin is added).
For this reason, I think the following configuration is a good idea:
```yaml
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: shuffle-api
  description: Shuffle API
  labels:
    goVersion: go1.15.3
    category: music
  annotations:
    google.com/cloudbuild: |
      [
        {
          "project-slug": "shuffle-api-dev-410617",
          "repo-name": "shuffle-api-repo"
        },
        {
          "project-slug": "shuffle-api-staging-410617",
          "repo-name": "shuffle-api-repo"
        }
      ]
```
