### ISSUE TITLE
About card edit improvements

### ISSUE THREAD

**Issue by stefanalund** [backstage/backstage#2267]
![Screenshot 2020-09-03 at 15 07 38](https://user-images.githubusercontent.com/190856/92119154-bc4ba300-edf7-11ea-8ac1-815aeed12783.png)

## Feature Suggestion

Clicking the Edit button today sends you to:

https://github.com/spotify/backstage/blob/master/packages/catalog-model/examples/petstore-api.yaml

Should be a "edit" URL so that you get to GitHub's edit UI directly:

https://github.com/spotify/backstage/edit/master/packages/catalog-model/examples/queue-proxy-component.yaml

![Screenshot 2020-09-03 at 15 12 07](https://user-images.githubusercontent.com/190856/92119251-d6858100-edf7-11ea-9356-2f1395424712.png)

## Possible Implementation

Replace `blob` in URL with `edit`.

## Context

Ideally this should not be hardcoded to GitHub URL semantics, but should also GitLab and Bitbucket.

**Comment by shmidt-i** [comment]
+ in the dev mode after running `mock-data` script you get the `file:` type of locations instead of `github:` and they are being handled incorrectly

**Comment by NetPenguins** [comment]
What about a [Menu](https://material-ui.com/components/menus/#customized-menus) that houses Icon buttons for GitHub, GitLab and Bitbucket each opening the desired URL?

**Comment by freben** [comment]
@NetPenguins the entity has [an annotation](https://github.com/spotify/backstage/blob/master/docs/features/software-catalog/well-known-annotations.md#backstageiomanaged-by-location) that should be sufficient to learn which option is the right one.

**Comment by andrewthauer** [comment]
I'm wondering if it might be useful to separate the concepts of `managed-by-location` and editing. For instance, if a new annotation called `backstage.io/edit-location` was present the edit button would use that. Otherwise it would fall back to the `managed-by-location`. This would make it possible to have the entity generated / updated from say a REST endpoint of a custom catalog processor, but editing at a different location.

```yaml
metadata:
  annotations:
    backstage.io/managed-by-location: github:http://github.com/spotify/backstage/catalog-info.yaml
    backstage.io/edit-location: http://github.com/spotify/backstage/edit/master/catalog-info.yaml
```
