### ISSUE TITLE
🐛 Bug Report: ApiEntityV1alpha1 validation on 'definition' is string while json.schemastore.org and Backstage docs show otherwise

### ISSUE THREAD

**Issue by CiscoRob** [backstage/backstage#22885]
### 📜 Description

Background

In setting up a local system CLI to validate Backstage entity definitions I imported and am using many Backstage validators include the `apiEntityV1alpha1Validator` validator.

Checked the Backstage entity Api kind and its definition was using `{ $text }` as it had been doing without issue when Backstage is running. i hoped into the Backstage source and found the reason:

Path:
packages/catalog-model/src/kinds/ApiEntityV1alpha1.ts

Path: 
packages/catalog-model/src/schema/kinds/API.v1alpha1.schema.json

The ApiEntityV1alpha1 definition property is set to `string`. Checked the documentation and in the Backstage documentation it seems perfectly valid to have a substitution with an object `{ $text }` and it looked like the validators and its schema do not take this into consideration when running a validation.

---

Problem

It seems like a logic bug that the author expected to only ever validate against post-processed Api kind entities whereas it is perfectly valid to use the defined substitutions:

https://backstage.io/docs/features/software-catalog/descriptor-format/#substitutions-in-the-descriptor-format

I could understand this line of thinking but at the same time if it's doing schema validation it seems like this validation is making assumptions. It should support checking both conditions. This same schema expectation is even pushed up to the JSON Schemastore used by the VS Code IDE for schema checks:

https://json.schemastore.org/catalog-info.json

--- 

Proposed Solution

// Update schema used for validation to match published schema
![Screenshot 2024-02-12 at 12 59 37 PM](https://github.com/backstage/backstage/assets/133238823/5840fdef-1c2a-4fe4-a52a-f51817db1025)

// Define an 'ApitDefinition' type
![Screenshot 2024-02-12 at 1 08 15 PM](https://github.com/backstage/backstage/assets/133238823/20f9bc59-3fa9-4b61-8dc0-c90cef9eaef9)

// Update Api's `definition` property to be of type `ApiDefinition`
![Screenshot 2024-02-12 at 1 07 43 PM](https://github.com/backstage/backstage/assets/133238823/74026581-5674-4a1d-a569-8296b3d59147)

### 👍 Expected behavior

I expect that if I give an Api entity in both of these formats that they'd be seen as valid:

```yaml
      apiVersion: 'backstage.io/v1alpha1',
      kind: 'API',
      metadata: {
        name: 'test',
      },
      spec: {
        type: 'openapi',
        lifecycle: 'production',
        owner: 'me',
        definition: ' ... big string of data omitted .... ',
        system: 'system',
      },
```

```yaml
      apiVersion: 'backstage.io/v1alpha1',
      kind: 'API',
      metadata: {
        name: 'test',
      },
      spec: {
        type: 'openapi',
        lifecycle: 'production',
        owner: 'me',
        definition: { 
          $text: 'https://petstore.swagger.io/v2/swagger.json'
       },
        system: 'system',
      },
```

### 👎 Actual Behavior with Screenshots

![Screenshot 2024-02-12 at 1 04 45 PM](https://github.com/backstage/backstage/assets/133238823/5d2ade11-4540-49c2-a48b-a2dc583db59a)

### 👟 Reproduction steps

Use `apiEntityV1alpha1Validator` to validate an Entity of kind Api with a definition that uses the $text substitution property pointing to an external data source such as a json file.

Running the validation on static data stored in a file fails. Check would only pass post-stitching of the catalog.

This creates a bottleneck in attempting to use the same schema validation built into Backstage to validate the data at rest to ensure non-breaking fields, relationships, and such prior to being used in Backstage catalog.

### 🖥️ Your Environment

Node 18.18.0
MacOS

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!
