### ISSUE TITLE
🐛 Bug Report: Scaffolder `fetch:plain:file` Action Corrupts Binary Files

### ISSUE THREAD

**Issue by RedlineTriad** [backstage/backstage#22899]
### 📜 Description

When using `fetch:plain:file` to download a binary file from an HTTPS server the file gets mangled and corrupted.

### 👍 Expected behavior

The file should be saved to disk the same as it is sent, more specifically it should be identical to using `wget` or any other download tool.

### 👎 Actual Behavior with Screenshots

```sh
du -sb *
314576	fetch:plain:file.zip
205633	wget.zip
```
Data gets changed when using the scaffolder action instead of a normal tool like `wget`.

### 👟 Reproduction steps

1. Create Template that uses the `fetch:plain:file` action:
```yml
apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: file-downloader
  title: Download file
  description: |
    Download a file
spec:
  owner: someone
  type: service

  parameters: []

  steps:
    - id: fetch
      name: Fetch
      action: fetch:plain:file
      input:
        url: https://$YOUR_SERVER/test.zip
        targetPath: ./test.zip
```
2. Add your server domain to allowed hosts in `app-config.yml`:
```yml
backend:
  reading:
    allow:
      - host: $YOUR_SERVER
```
3. Run action and check the downloaded file on the filesystem and try to decompress it using `unzip`
4. Observe archive corruption:
```sh
unzip test.zip
```
```
Archive:  test.zip

caution:  zipfile comment truncated
error [test.zip]:  missing 6403264528 bytes in zipfile
  (attempting to process anyway)
error [test.zip]:  attempt to seek before beginning of zipfile
  (please check that you have transferred or created the zipfile in the
  appropriate BINARY mode and that you have compiled UnZip properly)
```

### 📃 Provide the context for the Bug.

I want to download a zip file for a software template using `fetch:plain:file` and then use a custom action to unzip it into the workspace.

The `fetch:plain:file` action calls `fetchFile`
https://github.com/backstage/backstage/blob/04547bc042cd3add23f67c320b960b78de54f860/plugins/scaffolder-backend/src/scaffolder/actions/builtin/fetch/plainFile.ts#L80-L87

`fetchFile` delegates it to the appropriate reader, in my case it would be `FetchUrlReader`, it takes the raw request buffer and converts it to a string using `.toString()` before saving to disk, this corrupts all non UTF-8 data such as zip archives.
https://github.com/backstage/backstage/blob/04547bc042cd3add23f67c320b960b78de54f860/plugins/scaffolder-node/src/actions/fetch.ts#L95-L98

From my minimal local testing setup this issue is fixed by just removing the `.toString()` call.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!
