### ISSUE TITLE
🐛 Bug Report: /api/techdocs/static/docs/ not protected by jwt authorization

### ISSUE THREAD

**Issue by Macbet** [backstage/backstage#22966]
### 📜 Description

Greetings!
In our company's backstage installation, we have enabled the validation of JWTs generated by backstage using istio

And step by step opening the istio paths rules (which do not need JWT validation)

I'm faced with the problem that if I don't open access to paths  `- /api/techdocs/static/docs/*` 
I can't view static from the techdocs plugin (which is logical) but here I ran into a strange problem.

UPD: techdocs located in awsS3 bucket ( it's private ) and backstage configured to render techdocs from it

### 👍 Expected behavior

it would be great if access to `- /api/techdocs/static/docs/*` was also behind the Bearer token and it could be protected by checking jwt from ISTIO

### 👎 Actual Behavior with Screenshots

if I make a request to the backstage server (protected by jwt verification on the istio side):
```bash
curl 'https://example.com/api/techdocs/metadata/techdocs/default/component/doc'

RBAC: access denied%   
```
which is also correct, because I did not provide a token. But if I make a request before the images
```bash
curl -i https://example.com/api/techdocs/static/docs/default/component/docs/example/test/images/example.png > png.png
```
then I will be able to download the image - which again is logical, but it is very unsafe, because any Internet user will be able to access images from the documentation.

### 👟 Reproduction steps

1. in cluster with istio create 2 entitys
```yaml
apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata:
 name: backstage-jwt
 namespace: backstage
spec:
  selector:
    matchLabels:
     app.kubernetes.io/name: backstage
  jwtRules:
  - issuer: "https://backstage.domain/api/auth"
    jwksUri: "https://backstage.domain/api/auth/.well-known/jwks.json"
    forwardOriginalToken: true
```
```yaml
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: backstage
spec:
  action: ALLOW
  rules:
    - from:
        - source:
            requestPrincipals: ["*"]
    - to: 
        - operation:
            paths: 
            - /
            - /settings
            - /settings/auth-providers
            - /settings/feature-flags
            - /create
            - /docs/*
            - /api-docs
            - /catalog/*
            - /catalog-graph
            - /catalog-import
            - /static/*
            - /api/auth
            - /api/auth/microsoft/*
            - /api/auth/gitlab/*
            - /api/auth/.well-known/openid-configuration
            - /api/auth/.well-known/jwks.json
            - /api/auth/v1/userinfo
            - /api/auth/v1/token
            - /api/techdocs/static/docs/*
            - /api/badges/*
            - /manifest.json
            - /tech-radar
            - /favicon*
  selector:
    matchLabels:
      app.kubernetes.io/name: backstage
```
2. 
```bash
curl 'https://backstage.domain/api/techdocs/metadata/techdocs/default/component/doc'

RBAC: access denied%   
```
3.  try to download static file from protected url
```bash
curl -i https://backstage.domain/api/techdocs/static/docs/default/component/docs/example/test/images/example.png > png.png
```

### 🖥️ Your Environment

yarn run v1.22.21
node: v18.19.0
yarn: 1.22.21
cli:  0.25.1 (installed)
backstage:  1.22.2

Dependencies:
  @backstage/app-defaults                                          1.4.7
  @backstage/backend-app-api                                       0.4.5, 0.5.10
  @backstage/backend-common                                        0.18.5, 0.19.9, 0.20.1
  @backstage/backend-dev-utils                                     0.1.3
  @backstage/backend-openapi-utils                                 0.1.2
  @backstage/backend-plugin-api                                    0.5.4, 0.6.9
  @backstage/backend-tasks                                         0.5.14
  @backstage/backend-test-utils                                    0.2.10
  @backstage/catalog-client                                        1.5.2
  @backstage/catalog-model                                         1.4.3
  @backstage/cli-common                                            0.1.13
  @backstage/cli-node                                              0.2.2
  @backstage/cli                                                   0.25.1
  @backstage/config-loader                                         1.6.1
  @backstage/config                                                1.1.1
  @backstage/core-app-api                                          1.11.3
  @backstage/core-compat-api                                       0.1.1
  @backstage/core-components                                       0.12.5, 0.13.10
  @backstage/core-plugin-api                                       1.8.2
  @backstage/e2e-test-utils                                        0.1.0
  @backstage/errors                                                1.2.3
  @backstage/eslint-plugin                                         0.1.4
  @backstage/frontend-plugin-api                                   0.5.0
  @backstage/integration-aws-node                                  0.1.8
  @backstage/integration-react                                     1.1.23
  @backstage/integration                                           1.8.0
  @backstage/plugin-allure                                         0.1.45
  @backstage/plugin-api-docs                                       0.10.3
  @backstage/plugin-app-backend                                    0.3.57
  @backstage/plugin-app-node                                       0.1.9
  @backstage/plugin-auth-backend-module-atlassian-provider         0.1.1
  @backstage/plugin-auth-backend-module-gcp-iap-provider           0.2.3
  @backstage/plugin-auth-backend-module-github-provider            0.1.6
  @backstage/plugin-auth-backend-module-gitlab-provider            0.1.6
  @backstage/plugin-auth-backend-module-google-provider            0.1.6
  @backstage/plugin-auth-backend-module-oauth2-provider            0.1.6
  @backstage/plugin-auth-backend-module-oauth2-proxy-provider      0.1.1
  @backstage/plugin-auth-backend-module-okta-provider              0.0.2
  @backstage/plugin-auth-backend                                   0.20.3
  @backstage/plugin-auth-node                                      0.2.19, 0.4.3
  @backstage/plugin-badges-backend                                 0.3.6
  @backstage/plugin-badges                                         0.2.53
  @backstage/plugin-catalog-backend-module-msgraph                 0.5.16
  @backstage/plugin-catalog-backend-module-scaffolder-entity-model 0.1.6
  @backstage/plugin-catalog-backend                                1.16.2
  @backstage/plugin-catalog-common                                 1.0.20
  @backstage/plugin-catalog-graph                                  0.3.3
  @backstage/plugin-catalog-import                                 0.10.5
  @backstage/plugin-catalog-node                                   1.6.1
  @backstage/plugin-catalog-react                                  1.9.3
  @backstage/plugin-catalog                                        1.16.1
  @backstage/plugin-events-node                                    0.2.18
  @backstage/plugin-github-actions                                 0.6.10
  @backstage/plugin-home-react                                     0.1.7
  @backstage/plugin-home                                           0.6.1
  @backstage/plugin-kubernetes-backend                             0.14.1
  @backstage/plugin-kubernetes-common                              0.7.3
  @backstage/plugin-kubernetes-node                                0.1.3
  @backstage/plugin-kubernetes-react                               0.2.1
  @backstage/plugin-kubernetes                                     0.11.4
  @backstage/plugin-org                                            0.6.19
  @backstage/plugin-permission-common                              0.7.12
  @backstage/plugin-permission-node                                0.7.20
  @backstage/plugin-permission-react                               0.4.19
  @backstage/plugin-proxy-backend                                  0.4.7
  @backstage/plugin-scaffolder-backend-module-azure                0.1.1
  @backstage/plugin-scaffolder-backend-module-bitbucket            0.1.1
  @backstage/plugin-scaffolder-backend-module-gerrit               0.1.1
  @backstage/plugin-scaffolder-backend-module-github               0.1.1
  @backstage/plugin-scaffolder-backend-module-gitlab               0.2.12
  @backstage/plugin-scaffolder-backend                             1.20.0
  @backstage/plugin-scaffolder-common                              1.4.5
  @backstage/plugin-scaffolder-node                                0.2.10
  @backstage/plugin-scaffolder-react                               1.7.1
  @backstage/plugin-scaffolder                                     1.17.1
  @backstage/plugin-search-backend-module-catalog                  0.1.13
  @backstage/plugin-search-backend-module-pg                       0.5.18
  @backstage/plugin-search-backend-module-techdocs                 0.1.13
  @backstage/plugin-search-backend-node                            1.2.13
  @backstage/plugin-search-backend                                 1.4.9
  @backstage/plugin-search-common                                  1.2.10
  @backstage/plugin-search-react                                   1.7.5
  @backstage/plugin-search                                         1.4.5
  @backstage/plugin-shortcuts                                      0.3.18
  @backstage/plugin-tech-radar                                     0.6.12
  @backstage/plugin-techdocs-backend                               1.9.2
  @backstage/plugin-techdocs-module-addons-contrib                 1.1.4
  @backstage/plugin-techdocs-node                                  1.11.1
  @backstage/plugin-techdocs-react                                 1.1.15
  @backstage/plugin-techdocs                                       1.9.3
  @backstage/plugin-user-settings                                  0.8.0
  @backstage/release-manifests                                     0.0.11
  @backstage/test-utils                                            1.4.7
  @backstage/theme                                                 0.2.19, 0.4.4, 0.5.0
  @backstage/types                                                 1.1.1
  @backstage/version-bridge                                        1.0.7
✨  Done in 3.45s.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None
