### ISSUE TITLE
🐛 Bug Report: GitHub provider not filtering

### ISSUE THREAD

**Issue by agardnerIT** [backstage/backstage#23197]
### 📜 Description

I have access to both `org1/someRepoName` and my personal account: `agardnerIT/someRepoName`.

I have `catalog-info.yaml` set up like this:

```
  catalog:
    rules:
      - allow: [Component, Template, User, Group]
    import:
      entityFilename: catalog-info.yaml
    locations: []
    providers:
      github:
        backstage:
          organization: 'agardnerIT'
          catalogPath: '/catalog-info.yaml'
          filters:
            branch: 'codespace'
            repository: '^someRepoName$'
          schedule:
            frequency: { minutes: 1 }
            timeout: { minutes: 1 }
```

O

### 👍 Expected behavior

I'm expecting it to look through **only** `agardnerIT/someRepoName` but instead it seems to still be scanning my entire GitHub account and every other org I have access to:

```
{"class":"GithubEntityProvider","level":"info","message":"Read 59 GitHub repositories (2 matching the pattern)","plugin":"catalog","service":"backstage","target":"github-provider:backstage","taskId":"github-provider:backstage:refresh","taskInstanceId":"9072e194-1de3-4145-a1e1-dc7166237e1c","type":"plugin"}
{"level":"warn","message":"Detected conflicting entityRef template:default/app-creator already referenced by url:https://github.com/org1/someRepoName/tree/codespace/catalog-info.yaml and now also url:https://github.com/agardnerIT/someRepoName/tree/codespace/catalog-info.yaml","plugin":"catalog","service":"backstage","type":"plugin"}
{"level":"warn","message":"Detected conflicting entityRef template:default/gather-feedback already referenced by url:https://github.com/org1/someRepoName/tree/codespace/catalog-info.yaml and now also url:https://github.com/agardnerIT/someRepoName/tree/codespace/catalog-info.yaml","plugin":"catalog","service":"backstage","type":"plugin"}
```

### 👎 Actual Behavior with Screenshots

So it picks up the wrong catalog-info.yaml from the "parent" repo and not my repo.

### 👟 Reproduction steps

As above

### 🖥️ Your Environment

Backstage v1.22.1

Github codespaces. "parent" repo is a template which I cre

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else
