### ISSUE TITLE
🐛 Bug Report: Some github users getting error 401 (Unauthorized) or 403 Forbidden (rate limit exceeded) when registering component

### ISSUE THREAD

**Issue by bernaxa** [backstage/backstage#23410]
### 📜 Description

We have this sample template 

```
apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: java-healenium-template # name of the template
  title: Java Framework with Healenium
  description: Create a Java Freamework with Healenium implemented
  tags: # you can configure tags for the service
    - java
    - healenium
    - testing

spec:
  owner: group:team
  type: service # backstage type of this template

  # these are the steps which are rendered in the frontend with the form input
  parameters:
    - title: Provide some simple information
      required:
        - component_id
        - owner
      properties:
        website_name:
          title: Website name
          type: string
          description: This will be displayed prominantly on your website and in the title tag.      
        component_id:
          title: Name
          type: string
          description: Unique name of the component
          ui:field: EntityNamePicker
        description:
          title: Description
          type: string
          description: Help others understand what this website is for.          
        owner:
          title: Owner
          type: string
          description: Owner of the component
          ui:field: OwnerPicker
          ui:options:
            catalogFilter:
              kind: [Group, User]         
    - title: Choose a location
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            requestUserCredentials:
              secretsKey: USER_OAUTH_TOKEN
              additionalScopes:
                github: 
                  - workflow
                  - user
            allowedHosts:
              - github.ourcompany.com
  # here are the steps that are executed in series in the scaffolder backend
  steps:
    - id: template
      name: Fetch Skeleton + Template
      action: fetch:template
      input:
        url: ./skeleton
        values:
          website_name: ${{ parameters.website_name }}
          repo_name: ${{ (parameters.repoUrl | parseRepoUrl)["repo"] }}
          repo_owner: ${{ (parameters.repoUrl | parseRepoUrl)["owner"] }}          
          component_id: ${{ parameters.component_id }}
          description: ${{ parameters.description }}
          owner: ${{ parameters.owner }}

    - id: publish
      name: Publish
      action: publish:github
      input:
        allowedHosts: ["github.ourcompany.com"]
        description: This is ${{ parameters.component_id  }}
        repoUrl: ${{ parameters.repoUrl }}
        defaultBranch: main
        token: ${{ secrets.USER_OAUTH_TOKEN }}        

    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps.publish.output.repoContentsUrl }}
        catalogInfoPath: "/catalog-info.yaml"
        token: ${{ secrets.USER_OAUTH_TOKEN }}  

  output:
    links:
      - title: Repository
        url: ${{ steps.publish.output.remoteUrl }}
      - title: Open in catalog
        icon: catalog
        entityRef: ${{ steps.register.output.entityRef }}    
```

and some users are getting this error in the "Register" step

`[18](https://backstage-domain/create/tasks/c529a69b-0c9d-4cef-8e69-1dfa9e6f788c#line-18)2024-03-06T05:21:59.000Z Error: {"error":{"name":"InputError","message":"Error: Unable to read url, Error: Request failed for [https://github.ourcompany.com/api/v3/repos/user/java-heal/contents/catalog-info.yaml?ref=main, Opens in a new window](https://github.ourcompany.com/api/v3/repos/user/java-heal/contents/catalog-info.yaml?ref=main), 401 Unauthorized"},"request":{"method":"POST","url":"/locations?dryRun=true"},"response":{"statusCode":400}}`

sometimes the user received this error

`Error: Unable to read url, Error: Request failed for [https://github.ourcompany.com/api/v3/repos/user/java-heal/contents/catalog-info.yaml?ref=main, Opens in a new window](https://github.ourcompany.com/api/v3/repos/user/java-heal/contents/catalog-info.yaml?ref=main), 403 Forbidden (rate limit exceeded)`

The repo is correctly created in the personal GHE account, but they receive that error. For other users, the repo and component registration is completed correctly.

We are using Github App for integrations and OAuth App for authentication

### 👍 Expected behavior

The expected behaviour is that the component creation from the template finishes correctly, creating a repo in the personal GHE account and registering the component in backstage.

### 👎 Actual Behavior with Screenshots

`[18](https://backstage-domain/create/tasks/c529a69b-0c9d-4cef-8e69-1dfa9e6f788c#line-18)2024-03-06T05:21:59.000Z Error: {"error":{"name":"InputError","message":"Error: Unable to read url, Error: Request failed for [https://github.ourcompany.com/api/v3/repos/user/java-heal/contents/catalog-info.yaml?ref=main, Opens in a new window](https://github.ourcompany.com/api/v3/repos/user/java-heal/contents/catalog-info.yaml?ref=main), 401 Unauthorized"},"request":{"method":"POST","url":"/locations?dryRun=true"},"response":{"statusCode":400}}`

sometimes the user received this error

`Error: Unable to read url, Error: Request failed for [https://github.ourcompany.com/api/v3/repos/user/java-heal/contents/catalog-info.yaml?ref=main, Opens in a new window](https://github.ourcompany.com/api/v3/repos/user/java-heal/contents/catalog-info.yaml?ref=main), 403 Forbidden (rate limit exceeded)`

### 👟 Reproduction steps

Trying to create a component from template

### 🖥️ Your Environment

backstage v1.22.2

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by vinzscam** [comment]
hey @bernaxa, could you check whether the issue is connected to users creating new repositories under their namespace, which might not be accessible using the token provided to Backstage?

**Comment by bernaxa** [comment]
Hi @vinzscam, do you mean if the user can create the repo in their personal GHE account? Yes, the repo is published from backstage but the register step fails. 

Or what do you mean with "namespace" ?

Regards

**Comment by vinzscam** [comment]
> Hi @vinzscam, do you mean if the user can create the repo in their personal GHE account? Yes, the repo is published from backstage but the register step fails.

yeah exactly. My thought is that the user register a repository under `name-of-the-user/new-repository`, but the token  provided to Backstage (used for registering a new entity to the catalog) don't have permission to access `name-of-the-user/*`.

**Comment by bernaxa** [comment]
> yeah exactly. My thought is that the user register a repository under `name-of-the-user/new-repository`, but the token provided to Backstage (used for registering a new entity to the catalog) doesn't have permission to access `name-of-the-user/*`.

This is the permission/scope requested by OAuth when the user logins to backstage

![image](https://github.com/backstage/backstage/assets/5736472/542c903a-9812-4a86-9498-5d19ef96a7a7)

And those are the new permissions/scopes when the user writes his GHE user as the  "owner" for the RepoUrlPicker 

![image](https://github.com/backstage/backstage/assets/5736472/06ae69b7-adf3-4b44-b59b-43e8583ece4a)

So, the token with those permissions allows to create the repo in the personal GHE account ( https://github.company.com/name-of-the-user/new-repository ) but not to read from ( https://github.company.com/name-of-the-user/* )? Why? 

Do we need to ask for more scopes in the RepoUrlPicker ?

```
              additionalScopes:
                github: 
                  - workflow  
```  

Thanks!

**Comment by vinzscam** [comment]
So in order to register an entity to the catalog the user's token isn't used. The catalog has its own token for reaching out to the catalog, register the component and get updates from the component in case something changes.

The token is usually set in your `app-config.yaml` under:

```yaml
integrations:
  github:
    - host: github.com
      token: ${GITHUB_TOKEN}
```

https://backstage.io/docs/integrations/github/locations/

So I would look into the permissions of that token
