### ISSUE TITLE
🚀 Feature: OpenCost allow to connect to multiple opencost instances

### ISSUE THREAD

**Issue by levanvunam** [backstage/backstage#23506]
### 🔖 Feature description

I would like to ask if we could have a way to configure multiple opencost instances. My company has a lot of cluster to monitor and now they are setup it separately:
- opencost-1.com
- opencost-2.com
- etc

I would be great if the open cost page can allow me to select the correct instance to view the data

### 🎤 Context

When clicking on OpenCost, either it will:
- Show full page with dropdown to select the opencost instance, point to default instance. Url /opencost/default
- Select dropdown to switch to another instance, url: /opencost/instance-1
- View the report

or:
- Show a index page with all available instances
- Select the instance to load and go to OpenCost for that instance, eg: /opencost/instance-1
- View the report

### ✌️ Possible Implementation

in config we allow to config multiple instances:

```yaml
opencost:
  default:
     baseUrl: http://localhost:9001
  instance-1:
     baseUrl: http://localhost:9002
  instance-2:
     baseUrl: http://localhost:9003
```

Adjust the OpenCost page to load the instance from url, eg: opencost/default/...

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None
