### ISSUE TITLE
🐛 Bug Report: Authentication failed, failed to fetch user profile

### ISSUE THREAD

**Issue by twanbeeren** [backstage/backstage#23722]
### 📜 Description

At this moment I'm following the documentation on implementing sign in using Azure authentication:

https://backstage.io/docs/auth/microsoft/provider#adding-the-provider-to-the-backstage-frontend

My code is as follows:

packages\app\src\App.tsx
```
 components: {
    SignInPage: props => (
      <SignInPage
        {...props}
        auto
        provider={{
          id: 'azure-auth-provider',
          title: 'Azure',
          message: 'Sign in using Azure',
          apiRef: microsoftAuthApiRef,
        }}
      />
    ),
  },
```

I also added an identity resolver to the backend

Also followed the docs here: 
https://backstage.io/docs/auth/identity-resolver/#sign-in-resolvers

My code for this is also as follows

packages\backend\src\plugins\auth.ts
```
      microsoft: providers.microsoft.create({
        signIn: {
          resolver: providers.microsoft.resolvers.emailLocalPartMatchingUserEntityName()
        }
      })
```

My app.config is as follows:
```
app:
      title: <title>
      baseUrl: https://myownurl.com

backend:
      # Used for enabling authentication, secret is shared by all backend plugins
      # See https://backstage.io/docs/tutorials/backend-to-backend-auth for
      # information on the format
      # auth:
      #   keys:
      #     - secret: ${BACKEND_SECRET}
      baseUrl: https://myownurl.com
      listen:
        port: 30307
        # Uncomment the following host directive to bind to specific interfaces
        # host: 127.0.0.1
      csp:
        connect-src: ["'self'", 'http:', 'https:']
        # Content-Security-Policy directives follow the Helmet format: https://helmetjs.github.io/#reference
        # Default Helmet Content-Security-Policy values can be removed by setting the key to false
      cors:
        origin: https://myownurl.com
        methods: [GET, HEAD, PATCH, POST, PUT, DELETE]
        credentials: true

auth:
      environment: development
      providers:
        microsoft:
          development:
            clientId: ${AZURE_CLIENT_ID}
            clientSecret: ${AZURE_CLIENT_SECRET}
            tenantId: ${AZURE_TENANT_ID}
            domainHint: ${AZURE_TENANT_ID}
```

I have backstage running in kubernetes cluster behind an nginx ingress

### 👍 Expected behavior

After clicking on Sign In I should be redirected to the Azure login page. After a succesful login I should be able to login to backstage

### 👎 Actual Behavior with Screenshots

![image](https://github.com/backstage/backstage/assets/36261352/4ac7f8aa-45f8-477a-9f5c-d2372011d927)

I immediately get this response after it attempts to open the login page from Azure. 

![image](https://github.com/backstage/backstage/assets/36261352/1680701f-97ac-4c7d-81c6-dd18dd875a2e)

This error message doesn't seem to be known in the https://backstage.io/docs/auth/troubleshooting documentation.

We have verified connectivity from our cluster to graph.microsoft.com like stated as a possible error here:
https://backstage.io/docs/auth/microsoft/provider#outbound-network-access

### 👟 Reproduction steps

If you are able to set the same configuration I used in the Description section I would expect you to face the same issues. My backstage environment is a bit outdated so that might also be an issue. Look at the "Your environment"section for more info on this 

### 📃 Provide the context for the Bug.

I would like to login with my azure account into backstage and that my backstage user is populated with the same info from my Azure profile. I believe backstage uses Passport for this

### 🖥️ Your Environment

```
OS:   Linux 5.10.16.3-microsoft-standard-WSL2 - linux/x64
node: v18.16.0
yarn: 1.22.19
cli:  0.22.14 (installed)
backstage:  1.10.0

Dependencies:
  @backstage/app-defaults                              1.1.0
  @backstage/backend-app-api                           0.3.1, 0.4.0, 0.4.1, 0.4.2, 0.5.14
  @backstage/backend-common                            0.18.1, 0.18.2, 0.18.3, 0.18.4, 0.21.3
  @backstage/backend-dev-utils                         0.1.0, 0.1.1, 0.1.4
  @backstage/backend-plugin-api                        0.3.1, 0.4.0, 0.5.0, 0.5.1, 0.6.13
  @backstage/backend-tasks                             0.4.2, 0.4.3, 0.5.0, 0.5.1, 0.5.18
  @backstage/catalog-client                            1.3.0, 1.3.1, 1.4.0, 1.6.0
  @backstage/catalog-model                             1.1.5, 1.2.0, 1.2.1, 1.3.0, 1.4.4, 1.4.5-next.0
  @backstage/cli-common                                0.1.11, 0.1.12, 0.1.13
  @backstage/cli-node                                  0.2.3
  @backstage/cli                                       0.22.1
  @backstage/config-loader                             1.1.8, 1.1.9, 1.2.0, 1.6.2
  @backstage/config                                    1.0.6, 1.0.7, 1.1.1
  @backstage/core-app-api                              1.4.0
  @backstage/core-components                           0.12.3, 0.12.4, 0.12.5
  @backstage/core-plugin-api                           1.3.0, 1.4.0, 1.5.0
  @backstage/errors                                    1.1.4, 1.1.5, 1.2.3, 1.2.4-next.0
  @backstage/integration-aws-node                      0.1.1, 0.1.2, 0.1.9
  @backstage/integration-react                         1.1.9
  @backstage/integration                               1.4.2, 1.4.3, 1.4.4, 1.9.0
  @backstage/plugin-api-docs                           0.8.14
  @backstage/plugin-app-backend                        0.3.41
  @backstage/plugin-auth-backend-module-guest-provider 0.1.0-next.0
  @backstage/plugin-auth-backend                       0.17.4
  @backstage/plugin-auth-node                          0.2.10, 0.2.11, 0.2.12, 0.2.13, 0.4.8
  @backstage/plugin-azure-devops-backend               0.3.22
  @backstage/plugin-azure-devops-common                0.3.0
  @backstage/plugin-azure-devops                       0.2.7
  @backstage/plugin-catalog-backend                    1.7.1
  @backstage/plugin-catalog-common                     1.0.10, 1.0.11, 1.0.12
  @backstage/plugin-catalog-graph                      0.2.26
  @backstage/plugin-catalog-import                     0.9.4
  @backstage/plugin-catalog-node                       1.3.2
  @backstage/plugin-catalog-react                      1.2.4, 1.3.0, 1.4.0
  @backstage/plugin-catalog                            1.7.2
  @backstage/plugin-github-actions                     0.5.14
  @backstage/plugin-kubernetes-backend                 0.9.3
  @backstage/plugin-kubernetes-common                  0.6.0
  @backstage/plugin-kubernetes                         0.7.8
  @backstage/plugin-org                                0.6.4
  @backstage/plugin-permission-common                  0.7.12, 0.7.3, 0.7.4, 0.7.5
  @backstage/plugin-permission-node                    0.7.24, 0.7.4, 0.7.5, 0.7.6, 0.7.7
  @backstage/plugin-permission-react                   0.4.10, 0.4.11, 0.4.9
  @backstage/plugin-proxy-backend                      0.2.35
  @backstage/plugin-scaffolder-backend                 1.10.1
  @backstage/plugin-scaffolder-common                  1.2.4, 1.2.7
  @backstage/plugin-scaffolder-node                    0.1.2
  @backstage/plugin-scaffolder-react                   1.0.1
  @backstage/plugin-scaffolder                         1.10.1
  @backstage/plugin-search-backend-module-pg           0.5.2
  @backstage/plugin-search-backend-node                1.1.2
  @backstage/plugin-search-backend                     1.2.2
  @backstage/plugin-search-common                      1.2.1, 1.2.2
  @backstage/plugin-search-react                       1.4.0
  @backstage/plugin-search                             1.0.7
  @backstage/plugin-tech-radar                         0.6.0
  @backstage/plugin-techdocs-backend                   1.5.2
  @backstage/plugin-techdocs-module-addons-contrib     1.0.9
  @backstage/plugin-techdocs-node                      1.4.5
  @backstage/plugin-techdocs-react                     1.1.2
  @backstage/plugin-techdocs                           1.4.3
  @backstage/plugin-user-settings                      0.6.2
  @backstage/release-manifests                         0.0.8
  @backstage/test-utils                                1.2.4
  @backstage/theme                                     0.2.16, 0.2.17, 0.2.18
  @backstage/types                                     1.0.2, 1.1.1
  @backstage/version-bridge                            1.0.3
```

### 👀 Have you spent some time to check if this bug has been raised before?

- [x] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, I don't have time to work on this right now
