### ISSUE TITLE
🚀 Feature: Port the `GitlabOrgDiscoveryEntityProvider` to the new backend system

### ISSUE THREAD

**Issue by swnia** [backstage/backstage#23762]
### 🔖 Feature description

The `GitlabDiscoveryEntityProvider` was exposed for the new backend system but the `GitlabOrgDiscoveryEntityProvider` was not.
It would be great to have both of them available.

### 🎤 Context

Being able to move from the old backend to the new one as cleanly as possible, it would be great to have the module export the `GitlabOrgDiscoveryEntityProvider` directly, instead of having to write custom code.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, I don't have time to work on this right now

**Comment by davidfestal** [comment]
I (or a colleague) would be willing to help for this one, but, as I mentioned in the duplicated issue I opened, there are 2 options to fix this: the `GitlabOrgDiscoveryEntityProvider` provider should:
- either be added along with `GitlabDiscoveryEntityProvider` in the `@backstage/plugin-catalog-backend-module-gitlab/alpha` package (in the `module.ts`).
- or be exposed in dedicated distinct package (probably named `@backstage/plugin-catalog-backend-module-gitlab-org`), as it is [done for Github catalog providers](https://github.com/backstage/backstage/tree/master/plugins/catalog-backend-module-github-org).

@camilaibs Could you provide us with the option you would prefer ?

**Comment by elaine-mattos** [comment]
This PR addresses the problem https://github.com/backstage/backstage/pull/23373

**Comment by ahna92** [comment]
Facing issue with `GitlabOrgDiscoveryEntityProvider` with new backend and backstage `1.25.2` not loading the org data

I'm using the new backend with legacy plugin like so 

plugin.ts

```ts
import { CatalogBuilder } from '@backstage/plugin-catalog-backend';
import { Router } from 'express';
import { PluginEnvironment } from '../types';
import {
    GitlabDiscoveryEntityProvider,
    GitlabOrgDiscoveryEntityProvider,
} from '@backstage/plugin-catalog-backend-module-gitlab';

export default async function createPlugin(
    env: PluginEnvironment,
): Promise<Router> {
    const builder = await CatalogBuilder.create(env);
    builder.addEntityProvider(
        ...GitlabDiscoveryEntityProvider.fromConfig(env.config, {
            logger: env.logger,
            scheduler: env.scheduler,
        }),
    );
    builder.addEntityProvider(
        ...GitlabOrgDiscoveryEntityProvider.fromConfig(env.config, {
            logger: env.logger,
            scheduler: env.scheduler,
        }),
    );

    const { processingEngine, router } = await builder.build();
    await processingEngine.start();
    return router;
}
```

index.ts
```ts
backend.add(import('@backstage/plugin-catalog-backend-module-gitlab/alpha'));
backend.add(legacyPlugin('catalog-gitlab', import('./plugins/catalog')));
```

app-config.yaml
```
catalog:
  providers:
    gitlab:
      gitlabSaasOrgData:
        host: gitlab.com # Identifies one of the hosts set up in the integrations
        orgEnabled: true
        branch: main # Optional. Used to discover on a specific branch
        fallbackBranch: main # Optional. Fallback to be used if there is no default branch configured at the Gitlab repository. It is only used, if `branch` is undefined. Uses `master` as default
        skipForkedRepos: false # Optional. If the project is a fork, skip repository
        group: airasia-superapp/travel/mobile # Optional. Group and subgroup (if needed) to look for repositories. If not present the whole instance will be scanned
        groupPattern: '[\s\S]*'
        entityFilename: catalog-info.yaml # Optional. Defaults to `catalog-info.yaml`
        projectPattern: '[\s\S]*' # Optional. Filters found projects based on provided patter. Defaults to `[\s\S]*`, which means to not filter anything
        schedule: # optional; same options as in TaskScheduleDefinition
          # supports cron, ISO duration, "human duration" as used in code
          frequency: { minutes: 30 }
          # supports ISO duration, "human duration" as used in code
          timeout: { minutes: 3 }
        rules:
          - allow: [ Component, System, API, Group, User, Resource, Location, Domain, Template ]
  locations:
    - type: url
      target: <cusotm-url>
      rules:
        - allow: [User, Group]
```

But the users and groups are not imported , is this issue due to mixing legacy + new backend ? 


I'm kinda sure that gitlab token used is correct bc i'm getting this error 
```
Detected conflicting entityRef user:default/<user1> already referenced by GitlabOrgDiscoveryEntityProvider:gitlabSaasOrgData and now also url:<custom-url>
```

So the user is resolved just not add as an entity
