### ISSUE TITLE
🚀 Feature: Use parameters as conditional for fields of a different parameter list item

### ISSUE THREAD

**Issue by ma-ble** [backstage/backstage#23844]
### 🔖 Feature description

I would like to be able to use parameters from the first page in the following parameters as input / dependency.
Having this dependency resolution only within one parameter page limits the possibility of splitting the parameters into groups on several pages. 

### 🎤 Context

The following example shows schematically how I would like to set further conditions etc. from parameters already entered by the user on the page.

```
parameters:
  - title: Fill in some steps
    properties:
      env:
         title: name
         type: string
         enum:
           - iat
           -  prod
 
 - title: Fill in some further steps
    properties:
      hosts:
        title: select hosts
        type: string
        if:
          parameters:
            env:
              const: iat
        then:
          enum:
            - host-iat
            - host-iat-2  

```

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None
