### ISSUE TITLE
🐛 Bug Report: 401 Unauthorized Kubernetes Plugin

### ISSUE THREAD

**Issue by echalegre** [backstage/backstage#23856]
### 📜 Description

I am configuring the Kubernetes plugin (https://backstage.io/docs/features/kubernetes/). When I access the component in Backstage, the system shows the error below:

```
Errors: Request failed with 401 Unauthorized, {"error":{"name":"AuthenticationError","message":"Cannot read properties of undefined (reading 'getBaseUrl')","stack":"AuthenticationError: Cannot read properties of undefined (reading 'getBaseUrl')\n at DefaultIdentityClient.getIdentity (/Users/backstage/node_modules/@backstage/plugin-auth-node/src/identity/DefaultIdentityClient.ts:90:13)\n at AuthCompat.authenticate ( /Users/backstage/node_modules/@backstage/backend-common/src/auth/createLegacyAuthAdapters.ts:89:24)\n at HttpAuthCompat.credentials (/Users/backstage/node_modules/@backstage/backend-common/src/auth /createLegacyAuthAdapters.ts:218:25)\n at <anonymous> (/Users/backstage/node_modules/@backstage/plugin-kubernetes-backend/src/service/KubernetesBuilder.ts:403:27)"},"request" :{"method":"GET","url":"/api/kubernetes/clusters"},"response":{"statusCode":401}}
```

### 👍 Expected behavior

List cluster and pod details as per documentation

### 👎 Actual Behavior with Screenshots

![Screenshot 2024-03-26 at 16 33 36](https://github.com/backstage/backstage/assets/159057542/67ca6fcd-b54a-46f0-8449-fea85ba520a4)

### 👟 Reproduction steps

1. Install de plugin

```yaml
kubectl create clusterrolebinding backstage-ingestion --clusterrole=cluster-admin --serviceaccount=kube-system:backstage-ingestion
kubectl apply -f - <<EOF
apiVersion: v1
kind: Secret
metadata:
  name: backstage-ingestion
  namespace: kube-system
  annotations:
    kubernetes.io/service-account.name: backstage-ingestion
type: kubernetes.io/service-account-token
EOF

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: backstage-service-account
  namespace: backstage
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: backstage-cluster-ro
subjects:
- namespace: backstage
  kind: ServiceAccount
  name: backstage-service-account
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:aggregate-to-view
---
apiVersion: v1
kind: Secret
metadata:
  name: eks-secrets
  namespace: backstage
type: Opaque
data:
  SA_TOKEN: ${SA_TOKEN} #base64
  CA_DATA: ${CA_DATA} #base64
```

```yaml
integrations:
  aws:
    mainAccount:
    accounts:
    - accountId: ${AWS_ACCOUNT_ID}
      accessKeyId: ${AWS_ACCESS_KEY_ID}
      secretAccessKey: ${AWS_SECRET_ACCESS_KEY}
      region: ${AWS_REGION}
      
 kubernetes:
  serviceLocatorMethod:
    type: 'multiTenant'
  clusterLocatorMethods:
    - type: 'config'
      clusters:
        - name: 'eks-production'
          url: https://${APISERVER_ENDPOINT}.gr7.${AWS_REGION}.eks.amazonaws.com
          authProvider: 'serviceAccount'
          serviceAccountToken: ${SA_TOKEN}
          caData: ${CA_DATA}
          skipMetricsLookup: true
          skipTLSVerify: false
```

I had try with AWS Access Key and Assume Role, but all the options returning the same error message.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None
