### ISSUE TITLE
Remove alpha label from catalog version API

### ISSUE THREAD

**Issue by stefanalund** [backstage/backstage#2391]
The current [entity descriptor](https://backstage.io/docs/features/software-catalog/descriptor-format) `apiVersion` is set to `backstage.io/v1alpha1`.

While the API is in alpha, adopters of Backstage are cautious with starting the process of adding these YAML files into repos across their organisations. 

This issue is meant to track the progress towards stabilising the API and remove the alpha label. 

```yaml
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: artist-lookup
  description: Artist Lookup
  tags:
    - java
    - data
spec:
  type: service
  lifecycle: experimental
  owner: artists@example.com
```

**Open question:** would we move to a `beta` naming scheme or simply `apiVersion: backstage.io/v1`?
