### ISSUE TITLE
🚀 Feature: Scaffolder - clustering of actions

### ISSUE THREAD

**Issue by waldi** [backstage/backstage#23949]
### 🔖 Feature description

It would be nice to be able to cluster actions. 

Example of current implementation:

```yaml
steps:
  - id: fooOne
    action: foo-action

  - id: barOne
    action: bar-action

  - id: barTwo
    action: bar-action

  - id: barThree
    action: bar-action

  - id: fooBarOne
    action: foo-bar-action
```

Example of preferred implementation: 

```
jobs:
  - title: Foo Job
    steps:
      - id: fooOne
        action: foo-action

  - title: Bar Job
    steps:
      - id: barOne
        action: bar-action

      - id: barTwo
        action: bar-action

      - id: barThree
        action: bar-action

  - title: Foo Bar Job
    steps:
      - id: fooBarOne
        action: foo-bar-action
```

Both options of implementing the template should be possible to be backwards compatible.

### 🎤 Context

In my use-case, we write templates with a lot of small atomic actions that could be grouped. This could partially be a solution for large action lists. Instead of showing all the actions we could display the job titles only. 

Related issue:
https://github.com/backstage/backstage/issues/23948

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None
