### ISSUE TITLE
🐛 Bug Report: Users added to github org are not being ingested into Backstage

### ISSUE THREAD

**Issue by luananegreiros** [backstage/backstage#23968]
### 📜 Description

The new users added to the organization's github are not being ingested into Backstage. All groups "team members" pages display fewer members than those listed on github.

We are on version 1.20.3 of Backstage and version 18 of Node.

### 👍 Expected behavior

Backstage should be synchronizing changes made in the organization GitHub. New users added to the organization should be reflected in Backstage, and the number of team members displayed in the Backstage UI should match that on GitHub.

### 👎 Actual Behavior with Screenshots

Backstage displays fewer team members than listed on GitHub.

### 👟 Reproduction steps

Not relevant. 

### 📃 Provide the context for the Bug.

Recently, we started migrating the backend plugins of Backstage following [this documentation](https://backstage.io/docs/backend-system/building-backends/migrating/#the-catalog-plugin) and one of the migrated plugins is the catalog. We think the ingestion problem we are facing might be related to something incorrect we made in the migration. Currently, our catalog plugin file, catalog.ts, looks like this:

```
import { createBackendModule } from '@backstage/backend-plugin-api';
import { catalogProcessingExtensionPoint } from '@backstage/plugin-catalog-node/alpha';
import { coreServices } from '@backstage/backend-plugin-api';
import { ScaffolderEntitiesProcessor } from '@backstage/plugin-catalog-backend-module-scaffolder-entity-model';
import { GroupMetadataProcessor } from '../processors/group-metadata/processor';


export const catalogModuleCustomExtensions = createBackendModule({
    pluginId: 'catalog',
    moduleId: 'custom-extensions',
    register(env) {
      env.registerInit({
        deps: {
          catalog: catalogProcessingExtensionPoint,
          config: coreServices.rootConfig,
        },
        async init({ catalog, config }) {
          catalog.addProcessor(new GroupMetadataProcessor(config)); 
          catalog.addProcessor(new ScaffolderEntitiesProcessor());
        },
      });
    },
  });

```

And the configuration of the GitHub provider is as follows:

```
  providers:
    github:
      providerMain:
        organization: 'myOrg'
        catalogPath: '/catalog-info.yaml'
        validateLocationsExist: true
        filters:
          branch: 'main'
          repository: '.*'
        schedule:
          frequency: PT60M
          timeout: PT15M
      providerMaster:
        organization: 'myOrg'
        catalogPath: '/catalog-info.yaml'
        validateLocationsExist: true
        filters:
          branch: 'master'
          repository: '.*'
        schedule:
          frequency: PT60M
          timeout: PT15M
```

We need help understanding if we did something during the migration that may have caused the github ingestion problem.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by awanlin** [comment]
Hi @luananegreiros, just a small point of clarification your code is adding processors:

```
catalog.addProcessor(new GroupMetadataProcessor(config)); 
catalog.addProcessor(new ScaffolderEntitiesProcessor());
```

But your config is for `providers`. Did you maybe not include the right config here?

The other option is to upgrade to the latest Backstage version and use the open source providers. Examples of how to use those with the new backend system are here: https://backstage.io/docs/backend-system/building-backends/migrating#github

**Comment by daniadamatti** [comment]
Hi @awanlin, I'm a teammate of @luananegreiros. Thanks for the quick response. We are slowly migrating to the new backend but got stuck in this github ingestion issue after trying to migrate catalog plugin. We read the documentation again and we added githubOrg configs, as shown in the code below, and removed that `catalogModuleCustomExtensions` you saw in the code above.
```
catalog:  
  providers:
    githubOrg:
      id: 'production'
      githubUrl: 'https://github.com/my-org-name'
      schedule:
        frequency: 'P1M'
        timeout: 'PT3M'
```
Now we can even see the team members matching with github but the EntityRef is different than before. It used to be `group:default/team-name` and it is now `group:default/team-name`. So we ended up with duplicated entities. Is there a way to avoid this? Do you have any suggestions so we can reestablish github ingestion? We intend to update backstage to the latest version but it would be important for us to make github ingestion work as new people added to the organization are not being able to access the platform.
