### ISSUE TITLE
🚀 Feature: Add missing docs for implementing custom filters in templates

### ISSUE THREAD

**Issue by dariozachow** [backstage/backstage#24002]
### 🔖 Feature description

You should be able to find out how to implement custom filters yourself as the new backend system changed how to implement them.

### 🎤 Context

Some time ago I wanted to have a filter which converts a string into a base64 encoded version of the string.
Writing the code is no problem but I could not find out how to implement a custom filter with the new backend system as the docs did not show how to migrate those.

I've created this Issue here after a request in this pull request I initially asked this question https://github.com/backstage/backstage/pull/9065

### ✌️ Possible Implementation

Update the docs on the writing a template section to show how to implement custom filters.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by cmoulliard** [comment]
Here is based on the discussion with @dariozachow what we could describe using new backend system:

If a user would like to create some filters to be used within their templates such as `${{ parameters.name | base64 | filter1 | filter2 }}`, here is what you can do using backstage >= 1.23

1.  Add a new module extending the scaffold plugin and import the templateFilters
```
// backstage backend app => index.ts file
import { createBackend } from '@backstage/backend-defaults';
import {coreServices, createBackendModule} from '@backstage/backend-plugin-api';
import {scaffolderTemplatingExtensionPoint} from '@backstage/plugin-scaffolder-node/alpha';
import {JsonValue} from '@backstage/types';

export const myModule = createBackendModule({
    pluginId: 'scaffolder',
    moduleId: 'my-custom-filter',
    register(env) {
      env.registerInit({
        deps: {
          config: coreServices.rootConfig,
          scaffolderTemplating: scaffolderTemplatingExtensionPoint,
        },
        async init({scaffolderTemplating}) {
          scaffolderTemplating.addTemplateFilters(
            { base64: (...args: JsonValue[]) => btoa(args.join(""))}
          );
        },
      });
    },
  });

const backend = createBackend();

backend.add(import('@backstage/plugin-auth-backend'));
...
backend.add(myModule);
backend.start();
```
2. Create a dummy/test template

```
apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: dummy
  title: Dummy template
  description: Dummy template to test fields
spec:
  owner: guests
  type: service

  # These parameters are used to generate the input form in the frontend, and are
  # used to gather input data for the execution of the template.
  parameters:
    - title: input
      required:
        - myInput
      properties:
        myInput:
          title: Input
          type: string
          description: Input
  steps:
    - id: debug
      name: debug
      action: debug:log
      input:
        message: ${{ parameters.myInput | base64 }}
```
4. Launch the front + backend and check the backend log
```
type=incomingRequest
2024-04-05T12:14:34.973Z rootHttpRouter info ::1 - - [05/Apr/2024:12:14:34 +0000] "POST /api/scaffolder/v2/tasks HTTP/1.1" 201 45 "http://localhost:3000/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36" type=incomingRequest
info: {
  "message": "Q2hhcmxlcw=="
}
info: Q2hhcmxlcw==
```
