### ISSUE TITLE
🐛 Bug Report (catalog): spurious warnings

### ISSUE THREAD

**Issue by novellat** [backstage/backstage#24076]
### 📜 Description

The catalog plugin, when parsing, throws warnings in files that are valid. In fact the problem is in one of the files these valid files point to.

### 👍 Expected behavior

It should mention exactly the problematic file

### 👎 Actual Behavior with Screenshots

```
[1] 2024-04-08T11:20:48.424Z catalog warn /metadata/name must be string - type: string entity=location:default/users-and-groups-locator location=file://examples/bdp-backstage-catalog-items/locations.yaml
```

so allegedly you'd think that this locations.yaml is missing the name attribute.
What actually happened was that one of the files the locations indirectly pointed to looked like this:

```
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: 2001
  description: Project 2001 created using the backstage catalog
  annotations:
spec:
  type: SomeProject
  lifecycle: Staging
  owner: something
```
(name was a number)

### 👟 Reproduction steps

1. make a good Location file. 
2. Corrupt some of the files the locator points to (such as shown above)
3. see this spurious error

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else
