### ISSUE TITLE
🐛 Bug Report: OKTA auth broken in the new Backend

### ISSUE THREAD

**Issue by LegendSebastianoL** [backstage/backstage#24291]
### 📜 Description

I was trying to upgrade Backstage to the new backend but I couldn't pass from the auth step, we currently use this custom OKTA auth in the `backend/src/plugins` folder

```
import { createRouter, providers } from '@backstage/plugin-auth-backend';
import { Router } from 'express';
import { PluginEnvironment } from '../types';

export default async function createPlugin(
  env: PluginEnvironment,
): Promise<Router> {
  return await createRouter({
    logger: env.logger,
    config: env.config,
    database: env.database,
    discovery: env.discovery,
    tokenManager: env.tokenManager,
    providerFactories: {
      okta: providers.okta.create({
        signIn: {
          resolver:
            providers.okta.resolvers.emailMatchingUserEntityProfileEmail(),
        },
      }),
    },
  });
}
```

which then in the `index.ts` is set up in the usual way.
```
const authEnv = createEnv('auth');
...
apiRouter.use('/auth', await auth(authEnv));
...
```

and this is the app-config.yaml config
```
auth:
  providers:
    okta:
      development:
        clientId: ${OKTA_CLIENT_ID}
        clientSecret: ${OKTA_CLIENT_SECRET}
        audience: https://xxx.okta.com
      production:
        clientId: ${OKTA_CLIENT_ID}
        clientSecret: ${OKTA_CLIENT_SECRET}
        audience: https://xxx.okta.com
```

are there any instructions on how to migrate this kind of auth to the new backend system?

### 👍 Expected behavior

The OKTA auth plugin should work in the same way as the old backend system.

### 👎 Actual Behavior with Screenshots

I don't have screenshots but this is the error I have when I click on the login button.

```
{
error: {
name: "NotFoundError",
message: "Unknown auth provider 'okta'",
stack: "NotFoundError: Unknown auth provider 'okta'
    at <anonymous> (/path/backstage/app/node_modules/@backstage/plugin-auth-backend/src/service/router.ts:161:11)
    at handleReturn (/path/backstage/app/node_modules/express-promise-router/lib/express-promise-router.js:24:23)
    at /path/backstage/app/node_modules/express-promise-router/lib/express-promise-router.js:64:7
    at Layer.handle [as handle_request] (/path/backstage/app/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/path/backstage/app/node_modules/express/lib/router/index.js:328:13)
    at /path/backstage/app/node_modules/express/lib/router/index.js:286:9
    at param (/path/backstage/app/node_modules/express/lib/router/index.js:365:14)
    at param (/path/backstage/app/node_modules/express/lib/router/index.js:376:14)
    at Function.process_params (/path/backstage/app/node_modules/express/lib/router/index.js:421:3)
    at next (/path/backstage/app/node_modules/express/lib/router/index.js:280:10)
    at /path/backstage/app/node_modules/express/lib/router/index.js:646:15
    at next (/path/backstage/app/node_modules/express/lib/router/index.js:265:14)
    at Function.handle (/path/backstage/app/node_modules/express/lib/router/index.js:175:3)
    at router (/path/backstage/app/node_modules/express/lib/router/index.js:47:12)
    at handleReturn (/path/backstage/app/node_modules/express-promise-router/lib/express-promise-router.js:24:23)
    at router (/path/backstage/app/node_modules/express-promise-router/lib/express-promise-router.js:64:7)"
},
request: {
method: "GET",
url: "/api/auth/okta/start?scope=openid%20email%20profile%20offline_access&origin=http%3A%2F%2Flocalhost%3A3000&flow=popup&env=development"
},
response: {
statusCode: 404
}
}
```

### 👟 Reproduction steps

once migrated to the new backend system, in the new index add this code:

```
// auth plugin
backend.add(import('@backstage/plugin-auth-backend'));
backend.add(legacyPlugin('oktaAuth', import('./plugins/auth')));
```

where the `./plugins/auth` is as follow:
```
export default async function createPlugin(
  env: PluginEnvironment,
): Promise<Router> {
  return await createRouter({
    logger: env.logger,
    config: env.config,
    database: env.database,
    discovery: env.discovery,
    tokenManager: env.tokenManager,
    providerFactories: {
      okta: providers.okta.create({
        signIn: {
          resolver:
            providers.okta.resolvers.emailMatchingUserEntityProfileEmail(),
        },
      }),
    },
  });
}
```

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by freben** [comment]
General migration guide for auth: https://backstage.io/docs/backend-system/building-backends/migrating#the-auth-plugin

Updated auth docs regarding identities etc https://backstage.io/docs/auth/identity-resolver

The okta provider does seem to have new-backend-system support too https://github.com/backstage/backstage/pull/21325

**Comment by LegendSebastianoL** [comment]
hey @freben TY, I was looking into the doc but couldn't find anything about it.

I think I might miss this one in the OKTA integration in the app-config
```
...
        signIn:
          resolvers:
            - resolver: emailMatchingUserEntityProfileEmail
```

Which I didn't see when looking into the OKTA integration, at some point I tried the OKTA integration but maybe without the above config was still failing. let me try and I'll report back :)

**Comment by Antrakos** [comment]
Hey, I also missed the part where I needed to explicitly define resolvers in `app-config.yaml`. Moreover error message was very ambiguous - `NotFoundError: Unknown auth provider 'okta'`.

Is it the expected behaviour though? Shouldn't auth backend fallback to the full list of resolver factories available? If not, maybe it makes sense to update docs for each provider and add explicit resolvers configuration to the example yaml

**Comment by LegendSebastianoL** [comment]
hey @Antrakos look like the doc is now a bit more explicit https://backstage.io/docs/backend-system/building-backends/migrating#the-auth-plugin

A basic installation of the auth plugin with a Microsoft provider will look as follows.
```
packages/backend/src/index.ts
const backend = createBackend();
backend.add(import('@backstage/plugin-auth-backend'));
backend.add(import('@backstage/plugin-auth-backend-module-microsoft-provider'));
```

An additional step you'll need to take is to add the resolvers to your configuration, here's an example:
```
auth:
  environment: development
  providers:
    microsoft:
      development:
        clientId: ${AZURE_CLIENT_ID}
        clientSecret: ${AZURE_CLIENT_SECRET}
        tenantId: ${AZURE_TENANT_ID}
        signIn:
          resolvers:
            - resolver: emailMatchingUserEntityAnnotation
            - resolver: emailMatchingUserEntityProfileEmail
            - resolver: emailLocalPartMatchingUserEntityName
```

Note: the resolvers will be tried in order, but will only be skipped if they throw a NotFoundError.

#### Auth Plugin Modules and Their Resolvers

As you may have noticed in the above example you'll need to import the auth-backend and an auth-backend-module. The following sections outline each of them and their resolvers.

All of the following modules include the following common resolvers:

emailMatchingUserEntityProfileEmail
emailLocalPartMatchingUserEntityName
