### ISSUE TITLE
🐛 Bug Report:  How to handle 429 Too Many requests issue in Backstage catalog using Bitbucket cloud.

### ISSUE THREAD

**Issue by Durgakanna** [backstage/backstage#24497]
### 📜 Description

While listing the catalog in backstage from Bitbucket Cloud, I frequently experience error 429. Despite setting the discovery provider interval as 24 hours, And my server restarts often, which may cause the error. How can I handle this issue?

```json
{
  "entity": "location:default/services",
  "level": "warn",
  "location": "url:https://bitbucket.org/prod/system/src/master/temp/temp.yaml",
  "message": "Unable to read url, Error: https://bitbucket.org/prod/system/src/master/temp/temp.yaml could not be read as https://api.bitbucket.org/2.0/repositories/prod/system/src/master/temp/temp.yaml, 429 Too Many Requests",
  "plugin": "catalog",
  "service": "backstage",
  "type": "plugin"
}
```

I have configured interval of 24 hrs in `app-config.yaml`
```
catalog:
  providers:
    bitbucketCloud:
      default: 
        catalogPath: /temp/temp.yaml 
        schedule: # optional; same options as in TaskScheduleDefinition
          frequency: { minutes: 1440 }
          timeout: { minutes: 15 }
        workspace: XXX
``` 

### 👍 Expected behavior

I have increased the time interval, so the 429 won't happen

### 👎 Actual Behavior with Screenshots

<img width="913" alt="image" src="https://github.com/backstage/backstage/assets/97653855/84bbf858-4bc3-48db-87cd-e7a353b2e93f">

### 👟 Reproduction steps

1. Run the server
2. If bitbucket api rate limit reaches then this issue came

### 📃 Provide the context for the Bug.

http://localhost:3000/catalog/default/system/taste-online

### 🖥️ Your Environment

Development

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, I don't have time to work on this right now
