### ISSUE TITLE
Backstage Auth (Microsoft) Error: Failed to sign-in, unable to resolve user identity

### ISSUE THREAD

**Issue by guppyfish123** [backstage/backstage#24572]
### 📜 Description

I'm trying to setup Azure AD Auth (Microsoft) for backstage, though after countless hours reading thru docs and experimenting, I'm still unable to get it to work. The error that I'm running into is:
`Failed to sign-in, unable to resolve user identity`
![msedge_Wp8Q9DwfH7](https://github.com/backstage/backstage/assets/27799164/c3624061-750c-4e05-9715-e8fb045f98ef)

### 👍 Expected behavior

From the debug logs the msgraghorg is finding the group. 
`Committed 0 msgraph users and 2 msgraph groups in 0.0 seconds.`
If might be that its not pulling the members from it.
I'm using a Security group called `Backstage Users` in Azure which the the user is apart of. And following the docs have ensure that app registration has correct permissions.
https://backstage.io/docs/auth/microsoft/provider/#configure-app-registration-on-azure
https://backstage.io/docs/integrations/azure/org/#app-registration

### 👎 Actual Behavior with Screenshots

![Code_ujF1srDsD1](https://github.com/backstage/backstage/assets/27799164/9fd8209c-4ce6-483c-9ee5-bfe3802ce810)

### 👟 Reproduction steps

```yaml
# app-config.local.yaml
auth:
  environment: development
  providers:
    microsoft:
      development:
        clientId: **REDACTED**
        clientSecret: **REDACTED**
        tenantId: **REDACTED**
        domainHint: **REDACTED**
        signIn:
          resolvers:
            - resolver: emailMatchingUserEntityAnnotation
            - resolver: emailMatchingUserEntityProfileEmail
            - resolver: emailLocalPartMatchingUserEntityName

catalog:
  providers:
    microsoftGraphOrg:
      default:
          clientId: **REDACTED**
          clientSecret: **REDACTED**
          tenantId: **REDACTED**
          user:
            filter: accountEnabled eq true and userType eq 'member'
          group:
            filter: >
              displayName eq '**REDACTED**'
          schedule:
            frequency: PT1H
            timeout: PT50M
            retry: PT5M

```

```ts
# Backstage/sec/index.ts
// ...
backend.add(import('@backstage/plugin-app-backend/alpha'));
backend.add(import('@backstage/plugin-proxy-backend/alpha'));
backend.add(import('@backstage/plugin-scaffolder-backend/alpha'));
backend.add(import('@backstage/plugin-techdocs-backend/alpha'));

// auth plugin
backend.add(import('@backstage/plugin-auth-backend'));
// See https://backstage.io/docs/backend-system/building-backends/migrating#the-auth-plugin
backend.add(import('@backstage/plugin-auth-backend-module-guest-provider'));
backend.add(import('@backstage/plugin-auth-backend-module-microsoft-provider'));
// See https://backstage.io/docs/auth/guest/provider

// catalog plugin
backend.add(import('@backstage/plugin-catalog-backend-module-msgraph/alpha'));
backend.add(import('@backstage/plugin-catalog-backend/alpha'));
backend.add(
  import('@backstage/plugin-catalog-backend-module-scaffolder-entity-model'),
);

// permission plugin
backend.add(import('@backstage/plugin-permission-backend/alpha'));
backend.add(import('@backstage/plugin-permission-backend-module-allow-all-policy'));

// search plugin
backend.add(import('@backstage/plugin-search-backend/alpha'));
backend.add(import('@backstage/plugin-search-backend-module-catalog/alpha'));
backend.add(import('@backstage/plugin-search-backend-module-techdocs/alpha'));
// ...
```

All other configs are set and default and has not been changed.
Following - 
https://backstage.io/docs/backend-system/building-backends/migrating/
https://backstage.io/docs/integrations/azure/org

### 📃 Provide the context for the Bug.

Any Help would be great as the docs are still a bit confusing with the backend migration causing a bit of a mess. I understand that the team is still working on perfecting the docs and pouring and sweat and tears with the community on updating them.  Happy to assist with updating the docs to make a more clear path with authentication and azure integration. 

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by GuptaNavdeep1983** [comment]
I am sure that you are not interested in disabling the authentication but just to check that its just an authentication issue, you can disable the authentication like documented here, https://backstage.io/docs/tutorials/auth-service-migration#disabling-the-default-auth-policy

I think your issue is related to this one https://github.com/backstage/backstage/issues/24569

**Comment by benjdlambert** [comment]
It looks like there's no users being ingested which would probably lead to this issue that you're seeing.

> Committed 0 msgraph users and 2 msgraph groups in 0.0 seconds.

**Comment by guppyfish123** [comment]
@GuptaNavdeep1983  Yes that does work. I can also use guest access with no issues. 
```tsx
  components: {
    SignInPage: props => (
      <SignInPage
        {...props}
        providers={[
          'guest',
          {
            id: 'microsoft-auth-provider',
            title: 'Microsoft',
            message: 'Sign in using Microsoft',
            apiRef: microsoftAuthApiRef,
          }
        ]}
      />
    ),
  },
 ```
 
 Yeah you might be right with it not pulling any users @benjdlambert. Though I'm following whats the docs are saying to use 
 https://backstage.io/docs/integrations/azure/org/#customizing-transformation
 and if even I query the users directly it doesn't work. 
 ```yaml
          user:
            filter: displayName eq 'Backstage'
```
 Confirmed that it works fine though on msgragh explorer
 https://developer.microsoft.com/en-us/graph/graph-explorer
 Any ideas if I'm doing the query wrong in the yaml configs?

**Comment by jagexjake** [comment]
We are experiencing the same problem, and currently only getting this to work with a custom resolver also.
But, doing so without the `isUserInBackstageGroup` step aswell.
Would much rather use the builtin resolver and msgraph integration

**Comment by benjdlambert** [comment]
So to clarify you should be able to use the built-in resolvers if the users are in the catalog, so it looks like there's something gone wrong here and the users aren't in the catalog. Have the users been in the catalog before and then on upgrading they're no longer being populated? I think we're going to need some help from the community here to understand what's going on with `msgraph` and why it's not ingesting users properly, if it's something that's been broken in the code we own, or if something else has changed.

**Comment by cliffAtOsaic** [comment]
I am experiencing the same issue.

**Comment by benjdlambert** [comment]
@pjungermann can you take a look at some of the config here and maybe help troubleshoot why we can't get any users in the catalog from the `msgraphProvider` :pray:

**Comment by pjungermann** [comment]
We have it in place with built-in resolvers on the latest release version, and it works just fine. Ingestion of users as well as sign in.

I agree with @benjdlambert that the underlying issue is that no user gets ingested. At least for the author of this issue and based on the details and logs shared above.

The easiest way without debugging the code is to try calling the Graph API directly using the same credentials and query. Also, ensure that you use the same query mode, etc.

I see that you use query mode basic. E.g., our user.filter requires query mode advanced.

You could also check with the yaml reader like yq whether the value is as you intended.

I'm not sure whether the user.filter is the same in your actual setup.

It doesn't seem like you have a custom transformer that might cause user entities to get invalid, etc.

**Comment by guppyfish123** [comment]
I DID IT!!!!

Soooo for everyone facing the issue, after a couple of hours of debugging here's what you need to do. @pjungermann was right with there technically not being anything wrong with the code. It's more of a config issue that isn't very well documented, which is understandable with the team trying to update all the docs for the new backend. 

Basically the defaultUserTransformer() Function needs three parameters from a users in msgragh to be enter in as a catalog user in backstage, which is: ID, DisplayName, & **Mail**. Mail is the key point that you need to add to your select config, that is missing from the docs.
```yaml
[...]
        queryMode: advanced
        user:
          filter: displayName eq '**User***'
          loadPhotos: true
          select: ['id', 'displayName', 'mail']
        schedule: 
          frequency: PT1H
          timeout: PT3M
[...]
```

You also need to make sure that in azure that your user has the Email Parameter set. Which if your creating a cloud user usually has to be done manually and isn't auto populated like the User principal name. The reason why backstage doesn't pull the User principal name instead of the email parameter is bc the User principal name isn't always going to a email in some rare cases. You can change this manually function to use the User principal name instead of the email. We could also make a PR to add to the function to pickup if the email if Null and the User principal name is a email to use User principal name instead.

**Comment by vinzscam** [comment]
Amazing @guppyfish123! 👏
Closing the issue, feel free to re-open it in case more help is needed. 🙏

**Comment by twanbeeren** [comment]
Just to clarify here:

It is only necessary to make changes in the app-config.yaml?

My app-config.yaml
```
    catalog:
      providers:
        microsoftGraphOrg:
          providerId:
              target: https://graph.microsoft.com/v1.0
              authority: https://login.microsoftonline.com
              clientId: ${AZURE_CLIENT_ID}
              clientSecret: ${AZURE_CLIENT_SECRET}
              tenantId: ${AZURE_TENANT_ID}
              queryMode: advanced
              user:
                filter: displayName eq '**Users**'
                loadPhotos: true
                select: ['id', 'displayName', 'mail']
              schedule:
                frequency: PT1H
                timeout: PT3M
```

Or are there also changes needed in the backend?
