### ISSUE TITLE
🚀 Feature: Clarity on GitHub Org Provider Single Org vs. Multi Org

### ISSUE THREAD

**Issue by awanlin** [backstage/backstage#24576]
### 🔖 Feature description

It would be great to have some clarity around the recommend path for using GitHub Org Data in Single and Multi Org contexts. 

### 🎤 Context

Currently with the new backend system being the default you can only setup the Single Org provider following the easy install path with a single line. If you want to use the Multi Org provider there's a lot more steps involved. 

I ran into this while trying to update the [GitHub Org Integration documentation](https://github.com/backstage/backstage/pull/24573) to better reflect the new backend system.

### ✌️ Possible Implementation

Would it make sense to merge these and have a single provider that handles both via configuration? As I'm not a user of these I'm unsure of the best solution.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by awanlin** [comment]
@djamaile @kuangp I feel like the two of you might have some ideas here, could use your feedback on this one when you have time, please?

**Comment by kuangp** [comment]
The `GithubMultiOrgEntityProvider` was implemented to be a superset of the `GithubOrgEntityProvider` and I believe can be configured to accomplish the single org use-case as I noted here: https://github.com/backstage/backstage/pull/17565

I think it would be a good idea to merge/deprecate one in favor of the other but not sure if there has been any divergence in behavior since my PR above.

**Comment by benjdlambert** [comment]
> I think it would be a good idea to merge/deprecate one in favor of the other 

Agree with @kuangp here, maybe we could have a config option that toggles the behaviour or something?

**Comment by awanlin** [comment]
I'm super sorry, for the new backend system we created - @backstage/plugin-catalog-backend-module-github-org - which does use the `GithubMultiOrgEntityProvider`: 

https://github.com/backstage/backstage/blob/9910c6babc104d8b765c9646ee89604b09dc15de/plugins/catalog-backend-module-github-org/src/module.ts#L102-L119

I think I got lost a little in the module and that the code wasn't in there as I tried writing the docs.

Pretty sure the `orgs` option is the solition:

```yaml
catalog:
  providers: 
    githubOrg:
      id: production
      githubUrl: https://github.com
      orgs: ['Org1', 'Org2']
      schedule:
        frequency: PT1H
        timeout: PT50M
```

Will update my PR and close this as part of that. Thanks @kuangp and @benjdlambert

**Comment by 0GiS0** [comment]
Hi,

I'm trying to get my org data from my `returngis` org but I couldn't find the way :( I installed this module:

`yarn --cwd packages/backend add @backstage/plugin-catalog-backend-module-github-org
`

Registered it in `index.ts` in my backend package:

```
// github discovery
backend.add(import('@backstage/plugin-catalog-backend-module-github/alpha'));

// github org data
backend.add(import('@backstage/plugin-catalog-backend-module-github-org'));
```

and also this is my config:

```
catalog:
  orphanStrategy: delete
  providers:
    github:
      githubOrg:
        id: returngis
        organization: returngis
        orgs: [returngis]
        githubUrl: https://github.com/
        schedule:
          frequency: PT30M
          timeout: PT30S
```

And I have a PAT in place for my integrations config:

```
integrations:
  github:
    - host: github.com
      token: myPAT
```

But It does nothing... 

Did I miss something?

Thanks

**Comment by awanlin** [comment]
Hi @0GiS0, you have:

```yaml
providers:
    github:
      githubOrg:
```

When it should be:

```yaml
providers:
    githubOrg:
```

Try that and see how it goes?

**Comment by 0GiS0** [comment]
> Hi [@0GiS0](https://github.com/0GiS0), you have:
> 
> providers:
>     github:
>       githubOrg:
> When it should be:
> 
> providers:
>     githubOrg:
> Try that and see how it goes?

Thank you so much @awanlin! Now It works! I also reduced the frequency to 1 minute to test it. Also I noticed that If I want to fetch the rest of the entities I need a second provider:

```
catalog:
  orphanStrategy: delete
  providers:
    githubOrg:
      id: dragonstone-org
      organization: dragonstone-org
      orgs: [dragonstone-org]
      githubUrl: https://github.com/
      catalogPath: '/catalog-info.yaml'
      filters:
        branch: main
      schedule:
        frequency: PT1M
        timeout: PT30S
    github:
      organization: dragonstone-org
      catalogPath: '/catalog-info.yaml'
      filters:
        branch: main
      schedule:
          frequency: { minutes: 1 }
          timeout: { minutes: 3 }
```

I thought githubOrg was just an identifier like when you have more than one provider for the rest of the entities, but I've realized no, it's a keyword for this kind of configuration isn't it?

Thanks again!
