### ISSUE TITLE
🚀 Feature: Allow defining allow rules for catalog providers

### ISSUE THREAD

**Issue by drodil** [backstage/backstage#24721]
### 🔖 Feature description

There's already support for `rules` for catalog locations:

```yaml
catalog:
  rules:
    - allow: [Component, API, Location, Template]

  locations:
    - type: url
      target: https://github.com/org/example/blob/master/org-data.yaml
      rules:
        - allow: [Group]
```

However, this is not possible to be defined for providers separately.

### 🎤 Context

To be able to have more fine-grained control over what kind of entities each provider can produce, the config should allow rules to be defined for providers:

```yaml
catalog:
  providers:
    github:
      providerId:
        organization: 'backstage'
        catalogPath: '/catalog-info.yaml' 
        filters:
          branch: 'main' 
          repository: '.*' 
        schedule:
          frequency: { minutes: 30 }
          timeout: { minutes: 3 }
      rules:
        - allow: [Component]
    githubOrg:
      id: github
      githubUrl: https://github.com
      orgs: ['organization-1', 'organization-2', 'organization-3']
      schedule:
        initialDelay: { seconds: 30 }
        frequency: { hours: 1 }
        timeout: { minutes: 50 }
      rules:
        - allow: [Group]
```

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by drodil** [comment]
Related #4977 and #5014

**Comment by Rugvip** [comment]
Generally I agree that this could be good to have in some form, perhaps by just giving access to the standardized rule config and logic to entity providers.

These examples are perhaps not the best though, org data providers are fairly hardcoded to just ingest users and groups. If we don't trust them enough to do that there's a bigger problem than what can be solved in code, we'd need to sandbox them somehow at that point. If what we're looking for is filtering I'm thinking it's better to implement it as such.

The GitHub discovery provider doesn't actually ingest these entities directly. It emits `Location` entities that are then later read by the catalog, which means you'd need to be forwarding these rules to those locations somehow, or something like that. Lot more discussion around that in #12880, where we ultimately landed on #14584 as the solution.

**Comment by drodil** [comment]
Yeah, the locations are a bit hard for this. The main reason for this was that I would only like to get groups from Github org data and as the users are coming already from Azure. Of course, it could be possible to add a specific config for the `GithubOrgDataProvider` but thinking here again more generic way for all (even custom) providers to limit the entity types.

**Comment by Rugvip** [comment]
@drodil yep thinking it's probably best to keep that behind more explicit config to exclude users tbh. Using rules you might want to trigger an alert if someone tries to ingest a disallowed entity, so it could be good to avoid using it for deliberate filtering.

**Comment by mbmcmullen27** [comment]
I would love to have this feature for github discovery. Just as an example, say I have two providers, one to ingest templates from a specific repo and one to ingest components from repos in my org:

```yaml
catalog:
  providers:
    github:
      components:
        organization: 'backstage-org'
        catalogPath: '/catalog-info.yaml'
        host: github.com
        filters:
          branch: 'main'
          repository: '.*' 
      templates:
        organization: 'backstage-org'
        catalogPath: '**/template.yaml'
        host: github.com
        filters:
          branch: 'main' 
          repository: 'backstage-templates'
```

If I want to ensure that end users are not sneaking Template definitions into their catalog-info.yaml files, and I don't want to have to make a static location for each template I don't really have a mechanism for doing that with the current setup.

**Comment by grvn** [comment]
I would like to have this feature for Bitbucket discovery.
My use case is very similiar to @mbmcmullen27 

The function used to exist (~3 years ago) but in the [changelog](https://github.com/backstage/backstage/blob/master/plugins/catalog-backend-module-bitbucket-server/CHANGELOG.md) for 0.1.0 it was removed...

Before 0.1.0 we could do:
```yaml
      locations:
        - type: bitbucket-discovery
          target: https://bitbucket.mycompany/projects/BACKSTAGE/repos/backstage-templates/**/template.yaml
          rules:
            - allow: [Template]
```

After 0.1.0 it became a `catalog.provider` an lost the ability to use rules.
