### ISSUE TITLE
🐛 Bug Report: Frontend not available after upgrading to yarn3

### ISSUE THREAD

**Issue by KatharinaSick** [backstage/backstage#24740]
### 📜 Description

I just followed the [Yarn 3 Migration guide](https://backstage.io/docs/tutorials/yarn-migration/) to update from yarn v1 to v3. Locally, everything works like a charm but when deploying the newly built Docker image to Kubernetes, the frontend is not available anymore. The backend is working fine. 

I don't really think that this is a Backstage bug, but I'm stuck since ~2 weeks now and would be very thankful for your help 🙏

### 👍 Expected behavior

Frontend & backend should be available

### 👎 Actual Behavior with Screenshots

When running the newly built Docker image, only the backend seems to be running. When forwarding port `8080` to the pod and opening `http://localhost:8080` in my browser, I just get a 404 error. When connecting to `http://localhost:8080/api/catalog/entities`, it results all entities as JSON. 

I checked the Backstage logs and there everything looks good.

In addition to that we have one dev instance per branch and the yarn3 branch uses exaclty the same secrets, configuration, deployment,... as all the other branch instances that are working. 

### 👟 Reproduction steps

I don't have clear reproduction steps but here is what I did:

- Migrated to yarn3
- Built a new Docker image
- Tried to deploy it

Here are some resources that might be helpful:

Dockerfile (`CONFIG_YAML` points to `app-config.dev.yaml` in this case & `NPM_AUTH_TOKEN` is the auth token for an internal npm registry):
```Dockerfile
# This dockerfile builds an image for the backend package.
# It should be executed with the root of the repo as docker context.
#
# Before building this image, be sure to have run the following commands in the repo root:
#
# yarn install
# yarn tsc
# yarn build
#
# Once the commands have been run, you can build the image using `yarn build-image`

FROM node:20.10.0-bullseye-slim
ARG CONFIG_YAML
ARG NPM_AUTH_TOKEN

# Set Python interpreter for `node-gyp` to use
ENV PYTHON /usr/bin/python3

RUN apt-get update && \
    apt-get install -y --no-install-recommends libsqlite3-dev \
    python3 python3-pip \
    build-essential g++ curl musl-dev \
    openjdk-17-jre-headless graphviz fonts-dejavu fontconfig && \
    rm -rf /var/lib/apt/lists/*

# TechDocs addons & plugins
# See https://github.com/backstage/techdocs-container/blob/main/Dockerfile
RUN curl -o plantuml.jar -L https://github.com/plantuml/plantuml/releases/download/v1.2023.10/plantuml-1.2023.10.jar && echo "527d28af080ae91a455e7023e1a726c7714dc98e plantuml.jar" | sha1sum -c - && mv plantuml.jar /opt/plantuml.jar
RUN pip install --upgrade pip && pip install mkdocs-techdocs-core
RUN echo '#!/bin/sh\n\njava -jar '/opt/plantuml.jar' ${@}' >> /usr/local/bin/plantuml
RUN chmod 755 /usr/local/bin/plantuml

WORKDIR /app

# This switches many Node.js dependencies to production mode.
ENV NODE_ENV production

# Copy over Yarn 3 configuration, release, and plugins
COPY .yarn ./.yarn
COPY .yarnrc.yml ./

# Copy repo skeleton first, to avoid unnecessary docker cache invalidation.
# The skeleton contains the package.json of each package in the monorepo,
# and along with yarn.lock and the root package.json, that's enough to run yarn install.
COPY yarn.lock package.json packages/backend/dist/skeleton.tar.gz ./
RUN tar xzf skeleton.tar.gz && rm skeleton.tar.gz

RUN yarn workspaces focus --all --production && rm -rf "$(yarn cache clean)"

# Then copy the rest of the backend bundle, along with any other files we might want.
COPY packages/backend/dist/bundle.tar.gz app-config*.yaml ./
# Copy catalog-info & documentation
COPY catalog-info.yaml mkdocs.yaml ./
COPY docs ./docs

RUN tar xzf bundle.tar.gz && rm bundle.tar.gz

ENV CONFIG_YAML=${CONFIG_YAML}

CMD ["sh", "-c", "node packages/backend --config app-config.yaml --config ${CONFIG_YAML}"]
```

.yarnrc.yaml:
```yaml
enableGlobalCache: true
httpTimeout: 300000
nodeLinker: node-modules

npmRegistryServer: 'https://registry.yarnpkg.com/'

npmScopes:
  bestsellerit:
    npmRegistryServer: 'https://artifactory.xxx'
  dynatrace:
    npmAlwaysAuth: true
    npmAuthToken: '${NPM_AUTH_TOKEN}'
    npmRegistryServer: 'https://npm.pkg.github.com'

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'

yarnPath: .yarn/releases/yarn-3.8.1.cjs
```

app-config.dev.yaml (most important parts):
```yaml
app:
  baseUrl: ${BACKSTAGE_BASE_URL}

backend:
  baseUrl: ${BACKSTAGE_BASE_URL}
  listen:
    port: 80
    host: 0.0.0.0
  database:
    client: better-sqlite3
    connection: ':memory:'
```

### 📃 Provide the context for the Bug.

I am trying to update to yarn3 and can't get it working.

### 🖥️ Your Environment

```
OS:   Linux 6.8.5-201.fc39.x86_64 - linux/x64
node: v20.10.0
yarn: 3.8.1
cli:  0.25.2 (installed)
backstage:  1.23.4
```

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None
