### ISSUE TITLE
🐛 Bug Report: Links in mardown description content do not open in new tab

### ISSUE THREAD

**Issue by erik-adsk** [backstage/backstage#24753]
### 📜 Description

When [links](https://github.github.com/gfm/#links) are included in a template yaml definition these are not opened in a new tab.  There is precedence for this being the intent of the application in [github issue #9146](https://github.com/backstage/backstage/issues/9146).  The related PR #9148 provided a linkTarget property that can be passed in.

### 👍 Expected behavior

A github flavored markdown link provided in the description of a scaffolder field should open in a new tab.

### 👎 Actual Behavior with Screenshots

The link is actually opened in the current tab.

<img width="363" alt="image" src="https://github.com/backstage/backstage/assets/143032411/1bd8d7c6-8f77-467c-8313-544b6bd37b55">

![image](https://github.com/backstage/backstage/assets/143032411/7823fa7c-c1c4-4329-bfee-a2f717978f9c)

### 👟 Reproduction steps

1. Create a local-template file local-template.yaml in the [plugins/scaffolder-backend/sample-templates folder](https://github.com/backstage/backstage/tree/master/plugins/scaffolder-backend/sample-templates) e.g. 
```
apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: test-form
  title: Test Form
  description: This is a test form
spec:
  owner: guest@example.com
  type: test
  parameters:
    - title: Provide some simple information
      properties:
        prop:
          title: A property with links
          type: string
          description: 'A github flavored markdown formatted [link](https://www.google.com) in the description'
  steps:
    - id: debug
      name: debug
      action: debug:log
      input:
        message: message
  output:
    links:
    - title: Google
      url: https://www.google.com/

```
2. Add `    - ./local-template.yaml` to as defined in [plugins/scaffolder-backend/sample-templates/all-templates.yaml](https://github.com/backstage/backstage/blob/master/plugins/scaffolder-backend/sample-templates/all-templates.yaml)
3. Run the application locally
4. Route or navigate to http://localhost:3000/create
5. Choose the created form e.g. http://localhost:3000/create/templates/default/test-form
6. Select the github formatted link
7. Observe the link is opened in the current tab

### 📃 Provide the context for the Bug.

When a user clicks a link in the markdown of the description of a template field the link is opened in the current tab.  This causes users to lose progress on current template submissions which is especially frustrating for multi-step templates.

### 🖥️ Your Environment

OS:   Windows_NT 10.0.19045 - win32/x64
node: v18.20.0
yarn: 3.8.1
cli:  0.26.5-next.1 (local)
backstage:  N/A

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!
