### ISSUE TITLE
🚀 Feature: Use user gitlab token for register existing component (catalog import)

### ISSUE THREAD

**Issue by Yghore** [backstage/backstage#24764]
### 🔖 Feature description

You should add possibility of use user token for get yaml file into repository for registing existing component. 

### 🎤 Context

-  Avoid a static gitlab token
- Use user repository permission for allow/deny add a component

### ✌️ Possible Implementation

> app-config.production.yaml

```
catalog:
  rules:
    - allow: ["Component", "User", "Group"]
      useUserToken: true # true = user token, false = global token
      locations:
        - type: url
          pattern: https://gitlab.example.com/**
```

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else
