### ISSUE TITLE
🐛 Bug Report: Scaffolder template - If statement in output spec no applied

### ISSUE THREAD

**Issue by gabriel-farache** [backstage/backstage#24805]
### 📜 Description

In the `output` field of the template `spec`, `if` statement are not applied:
```
output:
    links:
      - if: ${{ parameters.CI === "Yes" }}
        title: Title
        url: URL
```

With the above spec, the link is always displayed even if CI is not equal to `Yes`

### 👍 Expected behavior

THe `if` statement should be matched and the `link` should only be applied/displayed if the condition matches

### 👎 Actual Behavior with Screenshots

The `link` is displayed no matter if the condition is matched.

### 👟 Reproduction steps

Create a template with the following or similar `output` spec:
```
output:
    links:
      - if: ${{ parameters.CI === "Yes" }}
        title: Title
        url: URL
```

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by benjdlambert** [comment]
Hey :wave:  Thanks for raising this!

Unfortunately this isn't a bug, more of a feature request as the `if` option isn't supported on the outputs yet. Think it seems like a good idea though to be able to implement this.

**Comment by joshua-reddish** [comment]
+1 This would be nice

**Comment by awanlin** [comment]
Reopening, we'd very much appreciate contributions from the Community to help support this! 🚀

**Comment by solimant** [comment]
Hi @benjdlambert, @awanlin - I'm interested in contributing this :) Is [here](https://github.com/backstage/backstage/blob/07c3f296de9190efe39845fcbba6d5b4d7c754c2/plugins/scaffolder-common/src/api.ts#L154-L159) a good starting point?

I suppose this should apply for both the `links` and `text` objects:
```yaml
output:
  links:
    - if: ${{ parameters.CI === "Yes" }}
      title: Open in CI
      url: ${{ steps['publish'].output.remoteUrl }}
  text:
    - if: ${{ parameters.CI === "Yes" }}
      title: More CI information
      content: |
        **CI URL:** `${{ steps['publish'].output.remoteUrl }}`
```
