### ISSUE TITLE
🚀 Feature: enable environment variables or appConfig.yaml properties to be referred to from template.yaml files.

### ISSUE THREAD

**Issue by monkeyhandz** [backstage/backstage#24812]
### 🔖 Feature description

In template.yaml I would like to be able to refer to variables that are in appConfig.yaml and/or an environment variable.

### 🎤 Context

I want to avoid hard coding values, especially api tokens and secrets, into template.yaml files.

### ✌️ Possible Implementation

Similar to template `parameters`, I was thinking the `${{ env.name }}` and `${{ appConfig.name }}` format, such as:

```yaml
-  id: fetchAPISpec
    name: Fetch API yaml from SwaggerHub
    action: fetch:plain:file
    input:
        url: ${{ parameters.url }}
        targetPath: ${{ parameters.target }}
        token: ${{ env.MY_API_TOKEN }}
```

Or from appConfig:

```yaml
-  id: fetchAPISpec
    name: Fetch API yaml from SwaggerHub
    action: fetch:plain:file
    input:
        url: ${{ parameters.url }}
        targetPath: ${{ parameters.target }}
        token: ${{ appConfig.myApiToken }}
```

An custom action is another possible solution, but I don't have details of how that would work. I raised this [question on the support discord channel](https://discord.com/channels/687207715902193673/687235481154617364/1239564133863784499), and a user @drodil answered they had made their own action. 

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else
