### ISSUE TITLE
🐛 Bug Report: Issues when Backstage is run in devcontainer

### ISSUE THREAD

**Issue by AnasSahel** [backstage/backstage#24888]
### 📜 Description

When I run `Backstage` in `docker` and expose ports `3000` and `7007`, the application doesn't show up in my browser.
However, when I install it locally, it works just fine.

### 👍 Expected behavior

When I run `yarn dev` inside the `docker` image with `3000` and `7007` ports exposed, the `Backstage` app should appears in my browser.

### 👎 Actual Behavior with Screenshots

I have a blank screen with the loading bar
<img width="1240" alt="image" src="https://github.com/backstage/backstage/assets/1083643/3e79ccb0-378e-4ac8-a2c2-c4f419c6ffb6">

### 👟 Reproduction steps

To reproduire the issue:
1. Create a `Nodejs` devcontainer in vscode
2. Run `npx @backstage/create-app@latest`
3. cd to the directory where the app was created
4. Run `yarn dev`
5. The browser opens automatically and it keeps trying to load the page

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by vinzscam** [comment]
@sonikro do you see anything wrong here in regard to devcontainers? 🤔

**Comment by darylgraham** [comment]
I've been fighting this exact problem for a few weeks now. If I use the dev tools in Firefox I can see that only the first 2 network requests succeed, the others never start at all. I suspect it's an issue between React and Firefox, because I switched to using Safari and it works every time. I can also switch to a new container in Firefox (like a Chrome profile) and get the bundle to load, but that would also mean logging into my OAuth provider every time I had to switch so I went with using Safari instead.

I did also move my config over to http://127.0.0.1 as the baseUrl in case it was something to do with the container attempting DNS resolution, but that did not solve the problem. I also hit an issue early on where VSCode stopped automatically exposing port 7007 and only 3000 was open, which I resolved by adding both ports to the config in devcontainer.json.

**Comment by sonikro** [comment]
Can you share what DevContainer specification are you using? Are you using the one available in the Contrib folder? https://github.com/backstage/backstage/tree/master/contrib/.devcontainer

I work on Backstage inside of a DevContainer pretty much every day with no problems, but there are some settings you might want to setup in your devcontainer specification to make sure you are forwarding the ports from the container to your host machine.

Also, what is your environment? Are you using Windows + WSL2 + Docker Desktop, or Macbook with Docker Desktop? All of that information might change how the docker layer is exposing the ports to your host computer.

**Comment by darylgraham** [comment]
I haven't reported this (until I saw this issue and wanted to share my experience with @AnasSahel) because I assumed it was an interaction between React and Firefox. The HTTP request never actually starts in my case, so logically I can't blame the Backstage backend for not serving the file when requested. Switching browser without touching the devcontainer let me launch immediately. So I blamed the Firefox cache, but I have little to no experience with React or JS in general, so I don't know if there is something in how Backstage interacts with it that may contribute to the problem.

**Comment by AnasSahel** [comment]
Hello all,
Thanks for your answer. I tried switching between browsers but the result is the same.
I'm under MacOS, with Docker Desktop.
Here are my configurations:
File: `devcontainer.json`
```json
// For format details, see https://aka.ms/devcontainer.json. For config options, see the
// README at: https://github.com/devcontainers/templates/tree/main/src/javascript-node-postgres
{
  "name": "backstage-lab01",
  "dockerComposeFile": "docker-compose.yml",
  "service": "app",
  "workspaceFolder": "/workspaces/${localWorkspaceFolderBasename}",
  "forwardPorts": [3000, 7007]

  // Features to add to the dev container. More info: https://containers.dev/features.
  // "features": {},

  // Use 'forwardPorts' to make a list of ports inside the container available locally.
  // This can be used to network with other containers or with the host.
  // "forwardPorts": [3000, 5432],

  // Use 'postCreateCommand' to run commands after the container is created.
  // "postCreateCommand": "yarn install",

  // Configure tool-specific properties.
  // "customizations": {},

  // Uncomment to connect as root instead. More info: https://aka.ms/dev-containers-non-root.
  // "remoteUser": "root"
}
```

File: `docker-compose.yml`
```yaml
version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile

    volumes:
      - ../..:/workspaces:cached
      
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
    env_file:
      - .env

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:db

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally. 
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}

    # Add "forwardPorts": ["5432"] to **devcontainer.json** to forward PostgreSQL locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

volumes:
  postgres-data:
```

File: `Dockerfile`
```dockerfile
FROM mcr.microsoft.com/devcontainers/javascript-node:1-20-bookworm

# [Optional] Uncomment this section to install additional OS packages.
# RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
#     && apt-get -y install --no-install-recommends <your-package-list-here>

# [Optional] Uncomment if you want to install an additional version of node using nvm
# ARG EXTRA_NODE_VERSION=10
# RUN su node -c "source /usr/local/share/nvm/nvm.sh && nvm install ${EXTRA_NODE_VERSION}"

# [Optional] Uncomment if you want to install more global node modules
# RUN su node -c "npm install -g <your-package-list-here>"
```

And here is the structure of my project in `vscode`
<img width="540" alt="image" src="https://github.com/backstage/backstage/assets/1083643/044a151c-50b8-4ba2-bef3-6c06a6e212f8">
Thanks all for your help

**Comment by AnasSahel** [comment]
Hello all,
I fixed it. The `app` uses ipv6, thus the port is not forwarded correctly.
I changed the `app-config.yaml` to force ipv4 and now it's working
```yaml
app:
  title: Scaffolded Backstage App
  baseUrl: http://localhost:3000
  listen:
    host: 0.0.0.0 # Added line, and now it's working
```
