### ISSUE TITLE
🐛 Bug Report: by using static token, I can call any APIs

### ISSUE THREAD

**Issue by Noro07** [backstage/backstage#24989]
### 📜 Description

Hi team,
I'm glad to see this feature is evolving rapidly, but I encountered some issues while using it. I hope you can help clarify whether it's a misuse or an actual bug. In the [documentation](https://backstage.io/docs/auth/service-to-service-auth/), I chose to use the method of static token, where I provide a token for external API calls, allowing external entities to trigger certain actions within Backstage. However, during usage, I found that this token can access other APIs without restriction, as shown in the screenshot below. This behavior is both dangerous and not allowed. I noticed the `externalAccess.option.subject` field, but I tried using the corresponding plugin ID or a specific user, and it did not restrict the token as expected. Additionally, the code mentions `Sets the subject of the principal`, but there is no corresponding documentation for it. 
I see that most of the related features are contributed by you, I'm sorry to bother you, but I hope to get your reply. Thank you in advance. @freben 

### 👍 Expected behavior

the static token should only be used with the target API

### 👎 Actual Behavior with Screenshots

for example, I can use the static token to visit the catalog API
![image](https://github.com/backstage/backstage/assets/40136071/54408812-53e2-4198-96e2-83e05eec95f2)

### 👟 Reproduction steps

set the following config in `app-config.yaml`

```
backend:
  auth:
    externalAccess:
      - type: static
        options:
          token: ${TOKEN}
          subject: PLUGIN-ID
```

or

```
backend:
  auth:
    externalAccess:
      - type: static
        options:
          token: ${TOKEN}
          subject: user:devTeam/developer1
```

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None
