### ISSUE TITLE
Github provider is not configured to sign in on backstage version 1.27.0

### ISSUE THREAD

**Issue by SreeHarshithaGaddam** [backstage/backstage#25043]
### 📜 Description

I have setup new backstage instance locally following this [doc](https://backstage.io/docs/getting-started/) and now trying to configure the authentication part following these [steps](https://backstage.io/docs/getting-started/config/authentication)
Made the below changes to the app-config.yaml , I have set the CLIENT_ID and CLIENT_SECRET environment variables in the .env file in the root directory of the backstage app
 ````
auth:`
  enviroment: development
  providers:
    github:
      development:
        clientId: ${CLIENT_ID}
        clientSecret: ${CLIENT_SECRET} 
        signIn:
        resolvers:
          - resolver: usernameMatchingUserEntityName 

``````
the changes made to packages/app/src/App.tsx

```
import {  SignInPage} from '@backstage/core-components';
import { githubAuthApiRef } from '@backstage/core-plugin-api';
components: {
    SignInPage: props => (
      <SignInPage 
        {...props} 
        auto 
        provider={{
          id: 'github-auth-provider',
          title: 'GitHub',
          message: 'Sign in using GitHub',
          apiRef: githubAuthApiRef,
        }} 
     />
    ),
  },
```

added  `  backend.add(import('@backstage/plugin-auth-backend-module-github-provider'));` in `packages/backend/src/index.ts`

### 👍 Expected behavior

It should allow to sign in using github

### 👎 Actual Behavior with Screenshots

It's giving The GitHub provider is not configured to support sign-in
![image](https://github.com/backstage/backstage/assets/127414715/f0334d19-6566-4bbb-8171-c834867af6d0)

### 👟 Reproduction steps

Create an instance of backstage app using the command :  `npx @backstage/create-app@latest`
configure the authentication part following these :   [steps
](https://backstage.io/docs/getting-started/config/authentication)
`
add the sign in resolver in auth in app-config.yaml

```
auth:
  # see https://backstage.io/docs/auth/ to learn about auth providers
  enviroment: development
  providers:
    github:
      development:
        clientId: ${CLIENT_ID}
        clientSecret: ${CLIENT_SECRET} 
        signIn:
        resolvers:
          - resolver: usernameMatchingUserEntityName 

```

also add the `  backend.add(import('@backstage/plugin-auth-backend-module-github-provider'));` in `packages/backend/src/index.ts`

### 🖥️ Your Environment

```
yarn run v1.22.22
$ /home/sreeharshithag/mybackstageapp/node_modules/.bin/backstage-cli info
OS:   Linux 6.6.21-01327-gc9107f2d4947 - linux/x64
node: v20.14.0
yarn: 1.22.22
cli:  0.26.6 (installed)
backstage:  1.27.0

Dependencies:
  @backstage/app-defaults                                          1.5.5
  @backstage/backend-app-api                                       0.7.5
  @backstage/backend-common                                        0.22.0
  @backstage/backend-defaults                                      0.2.18
  @backstage/backend-dev-utils                                     0.1.4
  @backstage/backend-openapi-utils                                 0.1.11
  @backstage/backend-plugin-api                                    0.6.18
  @backstage/backend-tasks                                         0.5.23
  @backstage/catalog-client                                        1.6.5
  @backstage/catalog-model                                         1.5.0
  @backstage/cli-common                                            0.1.13
  @backstage/cli-node                                              0.2.5
  @backstage/cli                                                   0.26.6
  @backstage/config-loader                                         1.8.0
  @backstage/config                                                1.2.0
  @backstage/core-app-api                                          1.12.5
  @backstage/core-compat-api                                       0.2.5
  @backstage/core-components                                       0.14.7
  @backstage/core-plugin-api                                       1.9.2
  @backstage/e2e-test-utils                                        0.1.1
  @backstage/errors                                                1.2.4
  @backstage/eslint-plugin                                         0.1.8
  @backstage/frontend-plugin-api                                   0.6.5
  @backstage/integration-aws-node                                  0.1.12
  @backstage/integration-react                                     1.1.27
  @backstage/integration                                           1.11.0
  @backstage/plugin-api-docs                                       0.11.5
  @backstage/plugin-app-backend                                    0.3.67
  @backstage/plugin-app-node                                       0.1.18
  @backstage/plugin-auth-backend-module-atlassian-provider         0.1.10
  @backstage/plugin-auth-backend-module-aws-alb-provider           0.1.10
  @backstage/plugin-auth-backend-module-azure-easyauth-provider    0.1.1
  @backstage/plugin-auth-backend-module-bitbucket-provider         0.1.1
  @backstage/plugin-auth-backend-module-cloudflare-access-provider 0.1.1
  @backstage/plugin-auth-backend-module-gcp-iap-provider           0.2.13
  @backstage/plugin-auth-backend-module-github-provider            0.1.15
  @backstage/plugin-auth-backend-module-gitlab-provider            0.1.15
  @backstage/plugin-auth-backend-module-google-provider            0.1.15
  @backstage/plugin-auth-backend-module-guest-provider             0.1.4
  @backstage/plugin-auth-backend-module-microsoft-provider         0.1.13
  @backstage/plugin-auth-backend-module-oauth2-provider            0.1.15
  @backstage/plugin-auth-backend-module-oauth2-proxy-provider      0.1.11
  @backstage/plugin-auth-backend-module-oidc-provider              0.1.9
  @backstage/plugin-auth-backend-module-okta-provider              0.0.11
  @backstage/plugin-auth-backend                                   0.22.5
  @backstage/plugin-auth-node                                      0.4.13
  @backstage/plugin-auth-react                                     0.1.2
  @backstage/plugin-catalog-backend-module-scaffolder-entity-model 0.1.16
  @backstage/plugin-catalog-backend                                1.22.0
  @backstage/plugin-catalog-common                                 1.0.23
  @backstage/plugin-catalog-graph                                  0.4.5
  @backstage/plugin-catalog-import                                 0.11.0
  @backstage/plugin-catalog-node                                   1.12.0
  @backstage/plugin-catalog-react                                  1.12.0
  @backstage/plugin-catalog                                        1.20.0
  @backstage/plugin-events-node                                    0.3.4
  @backstage/plugin-org                                            0.6.25
  @backstage/plugin-permission-backend-module-allow-all-policy     0.1.15
  @backstage/plugin-permission-backend                             0.5.42
  @backstage/plugin-permission-common                              0.7.13
  @backstage/plugin-permission-node                                0.7.29
  @backstage/plugin-permission-react                               0.4.22
  @backstage/plugin-proxy-backend                                  0.4.16
  @backstage/plugin-scaffolder-backend-module-azure                0.1.10
  @backstage/plugin-scaffolder-backend-module-bitbucket-cloud      0.1.8
  @backstage/plugin-scaffolder-backend-module-bitbucket-server     0.1.8
  @backstage/plugin-scaffolder-backend-module-bitbucket            0.2.8
  @backstage/plugin-scaffolder-backend-module-gerrit               0.1.10
  @backstage/plugin-scaffolder-backend-module-gitea                0.1.8
  @backstage/plugin-scaffolder-backend-module-github               0.2.8
  @backstage/plugin-scaffolder-backend-module-gitlab               0.4.0
  @backstage/plugin-scaffolder-backend                             1.22.7
  @backstage/plugin-scaffolder-common                              1.5.2
  @backstage/plugin-scaffolder-node                                0.4.4
  @backstage/plugin-scaffolder-react                               1.8.6
  @backstage/plugin-scaffolder                                     1.20.1
  @backstage/plugin-search-backend-module-catalog                  0.1.24
  @backstage/plugin-search-backend-module-techdocs                 0.1.23
  @backstage/plugin-search-backend-node                            1.2.23
  @backstage/plugin-search-backend                                 1.5.9
  @backstage/plugin-search-common                                  1.2.11
  @backstage/plugin-search-react                                   1.7.11
  @backstage/plugin-search                                         1.4.11
  @backstage/plugin-techdocs-backend                               1.10.5
  @backstage/plugin-techdocs-module-addons-contrib                 1.1.10
  @backstage/plugin-techdocs-node                                  1.12.4
  @backstage/plugin-techdocs-react                                 1.2.4
  @backstage/plugin-techdocs                                       1.10.5
  @backstage/plugin-user-settings                                  0.8.6
  @backstage/release-manifests                                     0.0.11
  @backstage/repo-tools                                            0.9.0
  @backstage/test-utils                                            1.5.5
  @backstage/theme                                                 0.5.5
  @backstage/types                                                 1.1.1
  @backstage/version-bridge                                        1.0.8
Done in 0.94s.
```

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by awanlin** [comment]
Hi @SreeHarshithaGaddam, Backstage doesn't support `.env` files, can you confirm the results if you hard code the token just as a test, please?

Also, can you confirm that you have `resolvers` tabbed under `signIn` what you have here is not correct:

```yaml
auth:`
 enviroment: development
 providers:
   github:
     development:
       clientId: ${CLIENT_ID}
       clientSecret: ${CLIENT_SECRET} 
       signIn:
       resolvers:
         - resolver: usernameMatchingUserEntityName 
```

It should be:

```yaml
auth:`
 enviroment: development
 providers:
   github:
     development:
       clientId: ${CLIENT_ID}
       clientSecret: ${CLIENT_SECRET} 
       signIn:
         resolvers:
           - resolver: usernameMatchingUserEntityName 
```

**Comment by SreeHarshithaGaddam** [comment]
Now I getting the below error after using tab![image](https://github.com/backstage/backstage/assets/127414715/eafce8a1-321f-4b25-b22e-4a04763626c0)

**Comment by SreeHarshithaGaddam** [comment]
I used  the following command for starting the backstage `dotenv -e file.env -- yarn dev `  
[here](https://backstage.io/docs/getting-started/config/database) it's mentioned that we can use environment variable injector dotenc-cli

**Comment by SreeHarshithaGaddam** [comment]
I have given tab in the resolver line
```
auth:
  # see https://backstage.io/docs/auth/ to learn about auth providers
  enviroment: development
  providers:
    github:
      development:
        clientId: ${CLIENT_ID}
        clientSecret: ${CLIENT_SECRET} 
        signIn:
          resolvers:
            - resolver: usernameMatchingUserEntityName 
```

after this I am getting this error


![Screenshot 2024-06-03 10 47 08 PM](https://github.com/backstage/backstage/assets/127414715/67a0b38b-ff38-49bf-914d-cbba4be43f73)
