### ISSUE TITLE
🐛 Bug Report: GCP IAP Provider has wrong provider name in documentation

### ISSUE THREAD

**Issue by AdamHansrod** [backstage/backstage#25087]
### 📜 Description

The docs refer to 'gcp-iap' as the provider string to use in config and on the proxied sign-in page. However, using that will result in a 404 result from the auth-backend. Using 'gcpIap' will succesfully work.

### 👍 Expected behavior

It should refer to 'gcpIap' as the provider id

### 👎 Actual Behavior with Screenshots

<img width="1785" alt="Screenshot 2024-06-06 at 10 36 53" src="https://github.com/backstage/backstage/assets/5097992/0913d782-7c39-4704-97d3-597d8a6d4715">
<img width="1812" alt="Screenshot 2024-06-06 at 10 37 00" src="https://github.com/backstage/backstage/assets/5097992/714b693a-5d2d-45b6-b148-3baa2cbc81fb">

### 👟 Reproduction steps

Include this in your backend index.ts
`backend.add(import('@backstage/plugin-auth-backend-module-gcp-iap-provider'));`
Spin up backend locally
Visit `http://localhost:8080/api/auth/gcp-iap/refresh` locally, it will return a 404. 
Visit `http://localhost:8080/api/auth/gcpIap/refresh` locally, it will return a 401 as it finds the auth plugin

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by nagyv** [comment]
The issue seems bigger than a simple docs fix.

Following the [plugin config schema](https://github.com/backstage/backstage/blob/master/plugins/auth-backend-module-gcp-iap-provider/config.d.ts) I tried this config

```yaml
auth:
  environment: production
  providers:
    gcpIap:
      production:
        audience: ${GCP_IAP_AUDIENCE_CODE}
        signIn:
          resolvers:
            # typically you would pick one of these
            - resolver: emailMatchingUserEntityProfileEmail
            - resolver: emailMatchingUserEntityAnnotation
```

Backstage fails to start with "ForwardedError: Plugin 'auth' startup failed; caused by Error: Failed to initialize gcpIap auth provider, No sign-in resolver configured for proxy auth provider 'gcpIap'".

The following seems to work, despite not being ok with the schema

```yaml
auth:
  environment: production
  providers:
    gcpIap:
      production:
        audience: ${GCP_IAP_AUDIENCE_CODE}
        signIn:
          resolvers:
            # typically you would pick one of these
            - resolver: emailMatchingUserEntityProfileEmail
            - resolver: emailMatchingUserEntityAnnotation
      audience: ${GCP_IAP_AUDIENCE_CODE}
      signIn:
        resolvers:
          # typically you would pick one of these
          - resolver: emailMatchingUserEntityProfileEmail
          - resolver: emailMatchingUserEntityAnnotation
```

This gives a 401 error, ""Google IAP token verification failed, Error: Wrong recipient, payload audience != requiredAudience"" - I guess this will be an error on my end.

I tried to figure out where the issue might be, and tested

```yaml
auth:
  environment: production
  providers:
    gcpIap:
      audience: ${GCP_IAP_AUDIENCE_CODE}
      signIn:
        resolvers:
          # typically you would pick one of these
          - resolver: emailMatchingUserEntityProfileEmail
          - resolver: emailMatchingUserEntityAnnotation
```

This failed as well with 404 error. (If I remember correctly)

I checked out the codebase, and it seems to be too complex for me to come up with a fix.
