### ISSUE TITLE
🐛 Bug Report: pymdownx.snippets `base_path` setting does not work for base directory of repository

### ISSUE THREAD

**Issue by farn-dawg** [backstage/backstage#25089]
### 📜 Description

I can only use snippets from files that are in my `/docs` directory, but I want to grab snippets from files that are one level up in my Git repository.  This configuration works for a local build of MkDocs, but doesn't work in Backstage:

```
markdown_extensions:
  - pymdownx.snippets:
        base_path:
          - ".."
        check_paths: true
```

For the above configuration, I just specify something like this in my Markdown file and it will grab the content from the Readme.md one level up from the `/docs` directory where my `mkdocs.yml` file is stored:

--8<-- "Readme.md"

### 👍 Expected behavior

It should support `base_path: ".."`

### 👎 Actual Behavior with Screenshots

The Backstage build throws an error when building the TechDoc.

### 👟 Reproduction steps

Here is the mkdocs.yml file that I used:

```
# This file is used for the downloadable starter files for TechDocs
# This file is used by Backstage to build your TechDocs

# This is the title of your TechDocs in Backstage
site_name: Your-TechDocs

# https://www.mkdocs.org/user-guide/configuration/#docs_dir
# The directory containing the documentation source markdown files.
docs_dir: 'docs-content'

# Specify your repo URL in GitLab. Update this value so you can edit the files in GitLab.
# https://www.mkdocs.org/user-guide/configuration/#repo_url
repo_url: https://gitlab.com/dematic/devex/techdoc-starter-files-testing

# Update this value if you publish your documentation to GitLab Pages
#site_url: https://dematic.gitlab.io/devex/techdocs-documentation

# https://www.mkdocs.org/user-guide/configuration/#edit_uri
# The path from the base repo_url to the docs directory when directly viewing a page, 
# accounting for specifics of the repository host of GitLab, the branch, and the docs directory itself.
# This setting enables the "Edit this page" functionality in BackStage.
edit_uri: blob/main/docs-for-backstage/docs-content

# https://www.mkdocs.org/user-guide/configuration/#repo_name
repo_name: put-your-repo-name-here

# DO NOT MODIFY the plugin values
plugins:
  # Core MkDocs plugin for Spotify's Backstage.
  - techdocs-core
  # Required for Mermaid-Kroki diagrams in Backstage.
  - kroki
  - monorepo
  - search:
    # https://squidfunk.github.io/mkdocs-material/plugins/search/#config.separator
      separator: '[\s\-,:!=\[\]()"/]+|(?!\b)(?=[A-Z][a-z])|\.(?!\d)|&[lg]t;'
      lang: en
markdown_extensions:
  - pymdownx.snippets:
        base_path:
          - ".."
        check_paths: true
theme:
        name: 'material'
        features:
          # https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-search/?h=searc#setting-up-site-search
          - search.share
          # https://github.com/squidfunk/mkdocs-material/issues/3409, the search highlighting will fade after 30 seconds as per this custom CSS—See  the extra.css file for the
          # customization details.
          - search.highlight
          - search.suggest

###### Table of Content/navigation for your docs inserted here ##############
### These files are examples only, feel free to delete or repurpose ####
### Always use forward slashes '/' in the file paths.  Do not use backslashes '\'. ###
#### Refer to this page for the latest on how to use TechDocs: https://backstage.private.gcp.dematic.dev/catalog/default/component/techdocs-example/docs/getting-started-techdocs/
nav:
  # index.md is the home page of the documentation. It is a requirement of MkDocs to name the file 'index.md'
  - First heading example: index.md
  # Heading only, no content associated with 'Second heading example' title.
  - Second heading example:
      -  Subtopic example: subtopic.md
        # Remember to use forward slashes '/' in the file paths.  DO NOT USE backslashes '\' which do not work on Backstage.
      -  Sub-directory example: doc-sub-directory/sub-directory-doc.md

#######################




```

### 📃 Provide the context for the Bug.

Here is the build logs.  Line 35 shows the base_path being set and line 111 shows the error.

[1](https://backstage.public.ops.dematic.dev/docs/default/component/testing-techdocs-geoff/#line-1)info: Step 1 of 3: Preparing docs for entity component:default/testing-techdocs-geoff {"timestamp":"2024-06-06T13:36:22.522Z"}
[2](https://backstage.public.ops.dematic.dev/docs/default/component/testing-techdocs-geoff/#line-2)info: Prepare step completed for entity component:default/testing-techdocs-geoff, stored at /tmp/backstage-grz4Pj {"timestamp":"2024-06-06T13:36:23.736Z"}
[3](https://backstage.public.ops.dematic.dev/docs/default/component/testing-techdocs-geoff/#line-3)info: Step 2 of 3: Generating docs for entity component:default/testing-techdocs-geoff {"timestamp":"2024-06-06T13:36:23.736Z"}
[4](https://backstage.public.ops.dematic.dev/docs/default/component/testing-techdocs-geoff/#line-4)DEBUG   -  Loading configuration file: /tmp/backstage-grz4Pj/mkdocs.yml
[5](https://backstage.public.ops.dematic.dev/docs/default/component/testing-techdocs-geoff/#line-5)DEBUG   -  Loaded theme configuration for 'material' from '/usr/local/lib/python3.10/dist-packages/material/templates/mkdocs_theme.yml': {'language': 'en', 'direction': None, 'features': [], 'font': {'text': 'Roboto', 'code': 'Roboto Mono'}, 'icon': None, 'favicon': 'assets/images/favicon.png', 'static_templates': ['404.html']}
[6](https://backstage.public.ops.dematic.dev/docs/default/component/testing-techdocs-geoff/#line-6)INFO    -  DeprecationWarning: warning_filter doesn't do anything since MkDocs 1.2 and will be removed soon. All messages on the `mkdocs` logger get counted automatically.
[7](https://backstage.public.ops.dematic.dev/docs/default/component/testing-techdocs-geoff/#line-7)  File "/usr/local/lib/python3.10/dist-packages/mkdocs_monorepo_plugin/[parser.py, Opens in a new window](http://parser.py/)", line 22, in <module>
[8](https://backstage.public.ops.dematic.dev/docs/default/component/testing-techdocs-geoff/#line-8)    from mkdocs.utils import yaml_load, warning_filter, dirname_to_title, get_markdown_title
[9](https://backstage.public.ops.dematic.dev/docs/default/component/testing-techdocs-geoff/#line-9)  File "/usr/local/lib/python3.10/dist-packages/mkdocs/utils/__init__.py", line 453, in __getattr__
[10](https://backstage.public.ops.dematic.dev/docs/default/component/testing-techdocs-geoff/#line-10)    warnings.warn(
[11](https://backstage.public.ops.dematic.dev/docs/default/component/testing-techdocs-geoff/#line-11)DEBUG   -  Config value 'config_file_path' = '/tmp/backstage-grz4Pj/mkdocs.yml'
[12](https://backstage.public.ops.dematic.dev/docs/default/component/testing-techdocs-geoff/#line-12)DEBUG   -  Config value 'site_name' = 'Your-TechDocs'
[13](https://backstage.public.ops.dematic.dev/docs/default/component/testing-techdocs-geoff/#line-13)DEBUG   -  Config value 'nav' = [{'First heading example': '[index.md, Opens in a new window](http://index.md/)'}, {'Second heading example': [{'Subtopic example': '[subtopic.md, Opens in a new window](http://subtopic.md/)'}, {'Sub-directory example': 'doc-sub-directory/[sub-directory-doc.md, Opens in a new window](http://sub-directory-doc.md/)'}]}]
[14](https://backstage.public.ops.dematic.dev/docs/default/component/testing-techdocs-geoff/#line-14)DEBUG   -  Config value 'pages' = None
[15](https://backstage.public.ops.dematic.dev/docs/default/component/testing-techdocs-geoff/#line-15)DEBUG   -  Config value 'exclude_docs' = None
[16](https://backstage.public.ops.dematic.dev/docs/default/component/testing-techdocs-geoff/#line-16)DEBUG   -  Config value 'not_in_nav' = None
[17](https://backstage.public.ops.dematic.dev/docs/default/component/testing-techdocs-geoff/#line-17)DEBUG   -  Config value 'site_url' = None
[18](https://backstage.public.ops.dematic.dev/docs/default/component/testing-techdocs-geoff/#line-18)DEBUG   -  Config value 'site_description' = None
[19](https://backstage.public.ops.dematic.dev/docs/default/component/testing-techdocs-geoff/#line-19)DEBUG   -  Config value 'site_author' = None
[20](https://backstage.public.ops.dematic.dev/docs/default/component/testing-techdocs-geoff/#line-20)DEBUG   -  Config value 'theme' = Theme(name='material', dirs=['/usr/local/lib/python3.10/dist-packages/material/templates', '/usr/local/lib/python3.10/dist-packages/mkdocs/templates'], static_templates={'sitemap.xml', '404.html'}, name='material', locale=Locale('en'), language='en', direction=None, features=['search.share', 'search.highlight', 'search.suggest'], font={'text': 'Roboto', 'code': 'Roboto Mono'}, icon=None, favicon='assets/images/favicon.png')
[21](https://backstage.public.ops.dematic.dev/docs/default/component/testing-techdocs-geoff/#line-21)DEBUG   -  Config value 'docs_dir' = '/tmp/backstage-grz4Pj/docs-content'
[22](https://backstage.public.ops.dematic.dev/docs/default/component/testing-techdocs-geoff/#line-22)DEBUG   -  Config value 'site_dir' = '/tmp/techdocs-tmp-T7pMd0'
[23](https://backstage.public.ops.dematic.dev/docs/default/component/testing-techdocs-geoff/#line-23)DEBUG   -  Config value 'copyright' = None
[24](https://backstage.public.ops.dematic.dev/docs/default/component/testing-techdocs-geoff/#line-24)DEBUG   -  Config value 'google_analytics' = None
[25](https://backstage.public.ops.dematic.dev/docs/default/component/testing-techdocs-geoff/#line-25)DEBUG   -  Config value 'dev_addr' = _IpAddressValue(host='127.0.0.1', port=8000)
[26](https://backstage.public.ops.dematic.dev/docs/default/component/testing-techdocs-geoff/#line-26)DEBUG   -  Config value 'use_directory_urls' = True
[27](https://backstage.public.ops.dematic.dev/docs/default/component/testing-techdocs-geoff/#line-27)DEBUG   -  Config value 'repo_url' = '[https://gitlab.com/dematic/devex/techdoc-starter-files-testing, Opens in a new window](https://gitlab.com/dematic/devex/techdoc-starter-files-testing)'
[28](https://backstage.public.ops.dematic.dev/docs/default/component/testing-techdocs-geoff/#line-28)DEBUG   -  Config value 'repo_name' = 'put-your-repo-name-here'
[29](https://backstage.public.ops.dematic.dev/docs/default/component/testing-techdocs-geoff/#line-29)DEBUG   -  Config value 'edit_uri_template' = None
[30](https://backstage.public.ops.dematic.dev/docs/default/component/testing-techdocs-geoff/#line-30)DEBUG   -  Config value 'edit_uri' = 'blob/main/docs-for-backstage/docs-content/'
[31](https://backstage.public.ops.dematic.dev/docs/default/component/testing-techdocs-geoff/#line-31)DEBUG   -  Config value 'extra_css' = []
[32](https://backstage.public.ops.dematic.dev/docs/default/component/testing-techdocs-geoff/#line-32)DEBUG   -  Config value 'extra_javascript' = []
[33](https://backstage.public.ops.dematic.dev/docs/default/component/testing-techdocs-geoff/#line-33)DEBUG   -  Config value 'extra_templates' = []
[34](https://backstage.public.ops.dematic.dev/docs/default/component/testing-techdocs-geoff/#line-34)DEBUG   -  Config value 'markdown_extensions' = ['toc', 'tables', 'fenced_code', 'pymdownx.snippets']
**[35](https://backstage.public.ops.dematic.dev/docs/default/component/testing-techdocs-geoff/#line-35)DEBUG   -  Config value 'mdx_configs' = {'pymdownx.snippets': {'base_path': ['..'], 'check_paths': True}}**
[36](https://backstage.public.ops.dematic.dev/docs/default/component/testing-techdocs-geoff/#line-36)DEBUG   -  Config value 'strict' = False
[37](https://backstage.public.ops.dematic.dev/docs/default/component/testing-techdocs-geoff/#line-37)DEBUG   -  Config value 'remote_branch' = 'gh-pages'
[38](https://backstage.public.ops.dematic.dev/docs/default/component/testing-techdocs-geoff/#line-38)DEBUG   -  Config value 'remote_name' = 'origin'
[39](https://backstage.public.ops.dematic.dev/docs/default/component/testing-techdocs-geoff/#line-39)DEBUG   -  Config value 'extra' = {}
[40](https://backstage.public.ops.dematic.dev/docs/default/component/testing-techdocs-geoff/#line-40)DEBUG   -  Config value 'plugins' = {'techdocs-core': <src.core.TechDocsCore object at 0x7d8ee3773760>, 'kroki': <kroki.plugin.KrokiPlugin object at 0x7d8ee3695ba0>, 'monorepo': <mkdocs_monorepo_plugin.plugin.MonorepoPlugin object at 0x7d8ee2e63250>, 'material/search': <[material.plugins.search, Opens in a new window](http://material.plugins.search/).plugin.SearchPlugin object at 0x7d8ee2e63160>}
[41](https://backstage.public.ops.dematic.dev/docs/default/component/testing-techdocs-geoff/#line-41)DEBUG   -  Config value 'hooks' = {}
[42](https://backstage.public.ops.dematic.dev/docs/default/component/testing-techdocs-geoff/#line-42)DEBUG   -  Config value 'watch' = []
[42](https://backstage.public.ops.dematic.dev/docs/default/component/testing-techdocs-geoff/#line-42)DEBUG   -  Config value 'watch' = []
[43](https://backstage.public.ops.dematic.dev/docs/default/component/testing-techdocs-geoff/#line-43)DEBUG   -  Config value 'validation' = {'nav': {'omitted_files': 20, 'not_found': 30, 'absolute_links': 20}, 'links': {'not_found': 30, 'absolute_links': 20, 'unrecognized_links': 20}}
[44](https://backstage.public.ops.dematic.dev/docs/default/component/testing-techdocs-geoff/#line-44)DEBUG   -  Running 1 `startup` events
[45](https://backstage.public.ops.dematic.dev/docs/default/component/testing-techdocs-geoff/#line-45)DEBUG   -  Running 4 `config` events
[46](https://backstage.public.ops.dematic.dev/docs/default/component/testing-techdocs-geoff/#line-46)DEBUG   -  kroki: Configuring
[47](https://backstage.public.ops.dematic.dev/docs/default/component/testing-techdocs-geoff/#line-47)DEBUG   -  kroki: File and Diagram types configured: {'bytefield': 'svg', 'ditaa': 'svg', 'erd': 'svg', 'graphviz': 'svg', 'nomnoml': 'svg', 'plantuml': 'svg', 'structurizr': 'svg', 'c4plantuml': 'svg', 'svgbob': 'svg', 'vega': 'svg', 'vegalite': 'svg', 'wavedrom': 'svg', 'pikchr': 'svg', 'umlet': 'svg', 'd2': 'svg', 'dbml': 'svg', 'tikz': 'svg', 'symbolator': 'svg', 'wireviz': 'svg', 'blockdiag': 'svg', 'seqdiag': 'svg', 'actdiag': 'svg', 'nwdiag': 'svg', 'packetdiag': 'svg', 'rackdiag': 'svg', 'bpmn': 'svg', 'excalidraw': 'svg', 'mermaid': 'svg'}
[48](https://backstage.public.ops.dematic.dev/docs/default/component/testing-techdocs-geoff/#line-48)DEBUG   -  kroki: Client initialized
[49](https://backstage.public.ops.dematic.dev/docs/default/component/testing-techdocs-geoff/#line-49)DEBUG   -  Looking for translations for locale 'en'
[50](https://backstage.public.ops.dematic.dev/docs/default/component/testing-techdocs-geoff/#line-50)DEBUG   -  No translations found here: '/tmp/tmpviiszf4h/locales'
[51](https://backstage.public.ops.dematic.dev/docs/default/component/testing-techdocs-geoff/#line-51)DEBUG   -  No translations found here: '/usr/local/lib/python3.10/dist-packages/mkdocs/templates/locales'
[52](https://backstage.public.ops.dematic.dev/docs/default/component/testing-techdocs-geoff/#line-52)DEBUG   -  No translations found here: '/usr/local/lib/python3.10/dist-packages/material/templates/locales'
[53](https://backstage.public.ops.dematic.dev/docs/default/component/testing-techdocs-geoff/#line-53)DEBUG   -  Running 1 `pre_build` events
[54](https://backstage.public.ops.dematic.dev/docs/default/component/testing-techdocs-geoff/#line-54)INFO    -  Cleaning site directory
[55](https://backstage.public.ops.dematic.dev/docs/default/component/testing-techdocs-geoff/#line-55)INFO    -  Building documentation to directory: /tmp/techdocs-tmp-T7pMd0
[56](https://backstage.public.ops.dematic.dev/docs/default/component/testing-techdocs-geoff/#line-56)DEBUG   -  Looking for translations for locale 'en'
[57](https://backstage.public.ops.dematic.dev/docs/default/component/testing-techdocs-geoff/#line-57)DEBUG   -  No translations found here: '/usr/local/lib/python3.10/dist-packages/mkdocs/contrib/search/templates/locales'
[58](https://backstage.public.ops.dematic.dev/docs/default/component/testing-techdocs-geoff/#line-58)DEBUG   -  No translations found here: '/tmp/tmpviiszf4h/locales'
[59](https://backstage.public.ops.dematic.dev/docs/default/component/testing-techdocs-geoff/#line-59)DEBUG   -  No translations found here: '/usr/local/lib/python3.10/dist-packages/mkdocs/templates/locales'
[60](https://backstage.public.ops.dematic.dev/docs/default/component/testing-techdocs-geoff/#line-60)DEBUG   -  No translations found here: '/usr/local/lib/python3.10/dist-packages/material/templates/locales'
[61](https://backstage.public.ops.dematic.dev/docs/default/component/testing-techdocs-geoff/#line-61)DEBUG   -  Reading markdown pages.
[62](https://backstage.public.ops.dematic.dev/docs/default/component/testing-techdocs-geoff/#line-62)DEBUG   -  Reading: [index.md, Opens in a new window](http://index.md/)
[63](https://backstage.public.ops.dematic.dev/docs/default/component/testing-techdocs-geoff/#line-63)DEBUG   -  Running 2 `pre_page` events
[64](https://backstage.public.ops.dematic.dev/docs/default/component/testing-techdocs-geoff/#line-64)DEBUG   -  Running 1 `page_markdown` events
[65](https://backstage.public.ops.dematic.dev/docs/default/component/testing-techdocs-geoff/#line-65)DEBUG   -  kroki: on_page_markdown [page: Page(title='First heading example', url='./')]
[66](https://backstage.public.ops.dematic.dev/docs/default/component/testing-techdocs-geoff/#line-66)DEBUG   -  kroki: Image url: [https://kroki.io/blockdiag/svg/eNpdzEEKgzAQheG9p5hm7wlKexFxMeojBNOMTKQSSu-u0SKpy8f7-Dsv_Tg4tvSpiLpz1U-yCFCeEfMw-1XnT_kVzf2q3cHe0ETgmG4b-TNNL16UHmSsAiHBe1lMm0PXeGEnF8YfKtIFEOVgkcm3WgGbCEEb?no-transparency=false, Opens in a new window](https://kroki.io/blockdiag/svg/eNpdzEEKgzAQheG9p5hm7wlKexFxMeojBNOMTKQSSu-u0SKpy8f7-Dsv_Tg4tvSpiLpz1U-yCFCeEfMw-1XnT_kVzf2q3cHe0ETgmG4b-TNNL16UHmSsAiHBe1lMm0PXeGEnF8YfKtIFEOVgkcm3WgGbCEEb?no-transparency=false)
[67](https://backstage.public.ops.dematic.dev/docs/default/component/testing-techdocs-geoff/#line-67)DEBUG   -  kroki: KrokiResponse(err_msg=None, image_url='[https://kroki.io/blockdiag/svg/eNpdzEEKgzAQheG9p5hm7wlKexFxMeojBNOMTKQSSu-u0SKpy8f7-Dsv_Tg4tvSpiLpz1U-yCFCeEfMw-1XnT_kVzf2q3cHe0ETgmG4b-TNNL16UHmSsAiHBe1lMm0PXeGEnF8YfKtIFEOVgkcm3WgGbCEEb?no-transparency=false, Opens in a new window](https://kroki.io/blockdiag/svg/eNpdzEEKgzAQheG9p5hm7wlKexFxMeojBNOMTKQSSu-u0SKpy8f7-Dsv_Tg4tvSpiLpz1U-yCFCeEfMw-1XnT_kVzf2q3cHe0ETgmG4b-TNNL16UHmSsAiHBe1lMm0PXeGEnF8YfKtIFEOVgkcm3WgGbCEEb?no-transparency=false)')
[68](https://backstage.public.ops.dematic.dev/docs/default/component/testing-techdocs-geoff/#line-68)INFO    -  DeprecationWarning: Using the add method to register a processor or pattern is deprecated. Use the `register` method instead.
[69](https://backstage.public.ops.dematic.dev/docs/default/component/testing-techdocs-geoff/#line-69)  File "/usr/local/lib/python3.10/dist-packages/markdown_inline_[graphviz.py, Opens in a new window](http://graphviz.py/)", line 48, in extendMarkdown
[70](https://backstage.public.ops.dematic.dev/docs/default/component/testing-techdocs-geoff/#line-70)    md.preprocessors.add('graphviz_block',
[71](https://backstage.public.ops.dematic.dev/docs/default/component/testing-techdocs-geoff/#line-71)  File "/usr/local/lib/python3.10/dist-packages/markdown/[util.py, Opens in a new window](http://util.py/)", line 462, in add
[72](https://backstage.public.ops.dematic.dev/docs/default/component/testing-techdocs-geoff/#line-72)    warnings.warn(
[73](https://backstage.public.ops.dematic.dev/docs/default/component/testing-techdocs-geoff/#line-73)INFO    -  DeprecationWarning: The 'md_globals' parameter of 'markdown_inline_graphviz.InlineGraphvizExtension.extendMarkdown' is deprecated.
[74](https://backstage.public.ops.dematic.dev/docs/default/component/testing-techdocs-geoff/#line-74)  File "/usr/local/lib/python3.10/dist-packages/markdown/[core.py, Opens in a new window](http://core.py/)", line 125, in registerExtensions
[75](https://backstage.public.ops.dematic.dev/docs/default/component/testing-techdocs-geoff/#line-75)    ext._extendMarkdown(self)
[76](https://backstage.public.ops.dematic.dev/docs/default/component/testing-techdocs-geoff/#line-76)  File "/usr/local/lib/python3.10/dist-packages/markdown/extensions/__init__.py", line 82, in _extendMarkdown
[77](https://backstage.public.ops.dematic.dev/docs/default/component/testing-techdocs-geoff/#line-77)    warnings.warn(
[78](https://backstage.public.ops.dematic.dev/docs/default/component/testing-techdocs-geoff/#line-78)INFO    -  DeprecationWarning: 'version' is deprecated. Use '__version__' instead.
[79](https://backstage.public.ops.dematic.dev/docs/default/component/testing-techdocs-geoff/#line-79)  File "/usr/local/lib/python3.10/dist-packages/markdown/__init__.py", line 51, in __getattr__
[80](https://backstage.public.ops.dematic.dev/docs/default/component/testing-techdocs-geoff/#line-80)    warnings.warn(
[81](https://backstage.public.ops.dematic.dev/docs/default/component/testing-techdocs-geoff/#line-81)  File "/usr/local/lib/python3.10/dist-packages/mdx_truly_sane_lists/__init__.py", line 1, in 
[82](https://backstage.public.ops.dematic.dev/docs/default/component/testing-techdocs-geoff/#line-82)    from .mdx_truly_sane_lists import makeExtension
[83](https://backstage.public.ops.dematic.dev/docs/default/component/testing-techdocs-geoff/#line-83)ERROR   -  Error reading page '[index.md, Opens in a new window](http://index.md/)': Snippet at path '[Readme.md, Opens in a new window](http://readme.md/)' could not be found
[84](https://backstage.public.ops.dematic.dev/docs/default/component/testing-techdocs-geoff/#line-84)Traceback (most recent call last):
[85](https://backstage.public.ops.dematic.dev/docs/default/component/testing-techdocs-geoff/#line-85)  File "/usr/local/bin/mkdocs", line 8, in <module>
[86](https://backstage.public.ops.dematic.dev/docs/default/component/testing-techdocs-geoff/#line-86)    sys.exit(cli())
[87](https://backstage.public.ops.dematic.dev/docs/default/component/testing-techdocs-geoff/#line-87)  File "/usr/local/lib/python3.10/dist-packages/click/[core.py, Opens in a new window](http://core.py/)", line 1157, in __call__
[88](https://backstage.public.ops.dematic.dev/docs/default/component/testing-techdocs-geoff/#line-88)return self.main(*args, **kwargs)
[89](https://backstage.public.ops.dematic.dev/docs/default/component/testing-techdocs-geoff/#line-89)  File "/usr/local/lib/python3.10/dist-packages/click/[core.py, Opens in a new window](http://core.py/)", line 1078, in main
[90](https://backstage.public.ops.dematic.dev/docs/default/component/testing-techdocs-geoff/#line-90)rv = self.invoke(ctx)
[91](https://backstage.public.ops.dematic.dev/docs/default/component/testing-techdocs-geoff/#line-91)  File "/usr/local/lib/python3.10/dist-packages/click/[core.py, Opens in a new window](http://core.py/)", line 1688, in invoke
[92](https://backstage.public.ops.dematic.dev/docs/default/component/testing-techdocs-geoff/#line-92)return _process_result(sub_ctx.command.invoke(sub_ctx))
[93](https://backstage.public.ops.dematic.dev/docs/default/component/testing-techdocs-geoff/#line-93)  File "/usr/local/lib/python3.10/dist-packages/click/[core.py, Opens in a new window](http://core.py/)", line 1434, in invoke
[94](https://backstage.public.ops.dematic.dev/docs/default/component/testing-techdocs-geoff/#line-94)return ctx.invoke(self.callback, **ctx.params)
[95](https://backstage.public.ops.dematic.dev/docs/default/component/testing-techdocs-geoff/#line-95)  File "/usr/local/lib/python3.10/dist-packages/click/[core.py, Opens in a new window](http://core.py/)", line 783, in invoke
[96](https://backstage.public.ops.dematic.dev/docs/default/component/testing-techdocs-geoff/#line-96)return __callback(*args, **kwargs)
[97](https://backstage.public.ops.dematic.dev/docs/default/component/testing-techdocs-geoff/#line-97)  File "/usr/local/lib/python3.10/dist-packages/mkdocs/__main__.py", line 286, in build_command
[98](https://backstage.public.ops.dematic.dev/docs/default/component/testing-techdocs-geoff/#line-98)[build.build, Opens in a new window](http://build.build/)(cfg, dirty=not clean)
[99](https://backstage.public.ops.dematic.dev/docs/default/component/testing-techdocs-geoff/#line-99)  File "/usr/local/lib/python3.10/dist-packages/mkdocs/commands/[build.py, Opens in a new window](http://build.py/)", line 322, in build
[100](https://backstage.public.ops.dematic.dev/docs/default/component/testing-techdocs-geoff/#line-100)_populate_page([file.page, Opens in a new window](http://file.page/), config, files, dirty)
[101](https://backstage.public.ops.dematic.dev/docs/default/component/testing-techdocs-geoff/#line-101)  File "/usr/local/lib/python3.10/dist-packages/mkdocs/commands/[build.py, Opens in a new window](http://build.py/)", line 175, in _populate_page
[102](https://backstage.public.ops.dematic.dev/docs/default/component/testing-techdocs-geoff/#line-102)    page.render(config, files)
[103](https://backstage.public.ops.dematic.dev/docs/default/component/testing-techdocs-geoff/#line-103)  File "/usr/local/lib/python3.10/dist-packages/mkdocs/structure/[pages.py, Opens in a new window](http://pages.py/)", line 271, in render
[104](https://backstage.public.ops.dematic.dev/docs/default/component/testing-techdocs-geoff/#line-104)self.content = md.convert(self.markdown)
[105](https://backstage.public.ops.dematic.dev/docs/default/component/testing-techdocs-geoff/#line-105)  File "/usr/local/lib/python3.10/dist-packages/markdown/[core.py, Opens in a new window](http://core.py/)", line 261, in convert
[106](https://backstage.public.ops.dematic.dev/docs/default/component/testing-techdocs-geoff/#line-106)self.lines = [prep.run, Opens in a new window](http://prep.run/)(self.lines)
[107](https://backstage.public.ops.dematic.dev/docs/default/component/testing-techdocs-geoff/#line-107)  File "/usr/local/lib/python3.10/dist-packages/pymdownx/[snippets.py, Opens in a new window](http://snippets.py/)", line 366, in run
[108](https://backstage.public.ops.dematic.dev/docs/default/component/testing-techdocs-geoff/#line-108)return self.parse_snippets(lines)
[109](https://backstage.public.ops.dematic.dev/docs/default/component/testing-techdocs-geoff/#line-109)  File "/usr/local/lib/python3.10/dist-packages/pymdownx/[snippets.py, Opens in a new window](http://snippets.py/)", line 351, in parse_snippets
[110](https://backstage.public.ops.dematic.dev/docs/default/component/testing-techdocs-geoff/#line-110)raise SnippetMissingError("Snippet at path '{}' could not be found".format(path))
[111](https://backstage.public.ops.dematic.dev/docs/default/component/testing-techdocs-geoff/#line-**111)pymdownx.snippets.SnippetMissingError: Snippet at path '[Readme.md, Opens in a new window](http://readme.md/)' could not be found**
[112](https://backstage.public.ops.dematic.dev/docs/default/component/testing-techdocs-geoff/#line-112)error: Failed to build the docs page for entity component:default/testing-techdocs-geoff: Failed to generate docs from /tmp/backstage-grz4Pj into /tmp/techdocs-tmp-T7pMd0; caused by unknown error 'Command mkdocs failed, exit code: 1' {"timestamp":"2024-06-06T13:36:24.521Z"}

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None
