### ISSUE TITLE
🐛 Bug Report: Kubernetes plugin - cluster selection annotation doesn't work anymore

### ISSUE THREAD

**Issue by tasiorek27** [backstage/backstage#25135]
### 📜 Description

Cluster selection annotation doesn't work anymore although it used to work -> https://backstage.io/docs/features/kubernetes/configuration/#cluster-selection-annotation.

### 👍 Expected behavior

Backstage should show only the selected cluster instead of all clusters.

### 👎 Actual Behavior with Screenshots

Backstage show all the clusters on Kubernetes tab of component.

### 👟 Reproduction steps

1. Set up your clusters.

```
kubernetes:
  serviceLocatorMethod:
    type: 'multiTenant'
  clusterLocatorMethods:
    - type: 'config'
      clusters:
        - url: https://some_cluster1:6443/
          name: aro-delta
          authProvider: serviceAccount
          skipTLSVerify: true
          skipMetricsLookup: false
          serviceAccountToken: ${some_cluster1}
        - url: https://some_cluster2:6443/
          name: aro-echo
          authProvider: serviceAccount
          skipTLSVerify: true
          skipMetricsLookup: false
          serviceAccountToken: ${some_cluster2}
````

3. Add annotations to your component.

```
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "foobar"
  description: "test"
  annotations:
    backstage.io/kubernetes-id: foobar
    backstage.io/kubernetes-cluster: some_cluster1
    backstage.io/kubernetes-namespace: backstage-test
```

### 🖥️ Your Environment

- core version:
```
{
  "version": "1.27.4"
}
```

- plugins:
```
{
  "name": "backend",
  "version": "0.0.0",
  "main": "dist/index.cjs.js",
  "types": "src/index.ts",
  "private": true,
  "backstage": {
    "role": "backend"
  },
  "scripts": {
    "start": "backstage-cli package start",
    "build": "backstage-cli package build",
    "lint": "backstage-cli package lint",
    "test": "backstage-cli package test",
    "clean": "backstage-cli package clean",
    "build-image": "docker build ../.. -f Dockerfile --tag backstage"
  },
  "dependencies": {
    "@azure/msal-node": "^1.18.3",
    "@backstage-community/plugin-azure-devops-backend": "^0.6.5",
    "@backstage-community/plugin-sonarqube-backend": "^0.2.20",
    "@backstage/backend-app-api": "^0.7.5",
    "@backstage/backend-common": "^0.22.0",
    "@backstage/backend-defaults": "^0.2.18",
    "@backstage/backend-plugin-api": "^0.6.18",
    "@backstage/backend-tasks": "^0.5.23",
    "@backstage/catalog-client": "^1.6.5",
    "@backstage/catalog-model": "^1.5.0",
    "@backstage/config": "^1.2.0",
    "@backstage/core-components": "^0.14.7",
    "@backstage/core-plugin-api": "^1.9.2",
    "@backstage/integration": "^1.11.0",
    "@backstage/plugin-app-backend": "^0.3.67",
    "@backstage/plugin-auth-backend": "^0.22.5",
    "@backstage/plugin-auth-backend-module-github-provider": "^0.1.15",
    "@backstage/plugin-auth-backend-module-microsoft-provider": "^0.1.13",
    "@backstage/plugin-auth-node": "^0.4.13",
    "@backstage/plugin-catalog-backend": "^1.22.0",
    "@backstage/plugin-catalog-backend-module-azure": "^0.1.38",
    "@backstage/plugin-catalog-backend-module-github": "^0.6.1",
    "@backstage/plugin-catalog-backend-module-msgraph": "^0.5.26",
    "@backstage/plugin-catalog-backend-module-openapi": "^0.1.36",
    "@backstage/plugin-catalog-backend-module-scaffolder-entity-model": "^0.1.16",
    "@backstage/plugin-catalog-backend-module-unprocessed": "^0.4.5",
    "@backstage/plugin-catalog-common": "^1.0.23",
    "@backstage/plugin-catalog-node": "^1.12.0",
    "@backstage/plugin-kubernetes-backend": "^0.17.1",
    "@backstage/plugin-permission-backend": "^0.5.42",
    "@backstage/plugin-permission-common": "^0.7.13",
    "@backstage/plugin-permission-node": "^0.7.29",
    "@backstage/plugin-proxy-backend": "^0.4.16",
    "@backstage/plugin-scaffolder-backend": "^1.22.7",
    "@backstage/plugin-scaffolder-backend-module-azure": "^0.1.10",
    "@backstage/plugin-scaffolder-backend-module-confluence-to-markdown": "^0.2.19",
    "@backstage/plugin-scaffolder-backend-module-github": "^0.2.8",
    "@backstage/plugin-scaffolder-node": "^0.4.4",
    "@backstage/plugin-search-backend": "^1.5.9",
    "@backstage/plugin-search-backend-module-catalog": "^0.1.24",
    "@backstage/plugin-search-backend-module-pg": "^0.5.27",
    "@backstage/plugin-search-backend-module-techdocs": "^0.1.23",
    "@backstage/plugin-search-backend-node": "^1.2.23",
    "@backstage/plugin-techdocs-backend": "^1.10.5",
    "@internal/plugin-access-provisioning-backend": "^0.1.0",
    "@internal/plugin-access-provisioning-confirmation-backend": "^0.1.0",
    "@internal/plugin-build-version-backend": "^0.1.0",
    "@internal/plugin-catalog-backend-module-apic": "^0.1.0",
    "@internal/plugin-catalog-backend-module-apim": "^0.1.0",
    "@internal/plugin-common-node": "^0.1.1",
    "@internal/plugin-common-utils": "^0.1.0",
    "@internal/plugin-fortify-backend": "0.1.0",
    "@internal/plugin-github-adapter-backend": "^0.1.0",
    "@internal/plugin-interfaces-common": "^0.1.0",
    "@internal/plugin-planview-adapter-backend": "^0.1.0",
    "@internal/plugin-techradar-backend": "^0.1.0",
    "@internal/plugin-vear-adapter-backend": "^0.1.0",
    "@internal/scaffolder-backend-module-azure-repositories": "^0.3.0",
    "@procore-oss/backstage-plugin-announcements-backend": "^0.6.0",
    "@roadiehq/scaffolder-backend-module-http-request": "^4.0.12",
    "@spotify/backstage-plugin-insights-backend": "^0.2.13",
    "@spotify/backstage-plugin-permission-backend-module-rbac": "^0.1.3",
    "@spotify/backstage-plugin-rbac-backend": "^0.7.5",
    "@spotify/backstage-plugin-search-backend-module-skill-exchange": "^0.1.3",
    "@spotify/backstage-plugin-skill-exchange-backend": "^0.12.7",
    "@spotify/backstage-plugin-soundcheck-backend": "^0.16.4",
    "@spotify/backstage-plugin-soundcheck-backend-module-github": "^0.5.6",
    "@spotify/backstage-plugin-soundcheck-backend-module-scm": "^0.7.2",
    "@volvogroup-internal/backstage-descriptor-file-generator": "^1.4.1",
    "app": "link:../app",
    "applicationinsights": "^2.7.3",
    "axios": "^1.5.0",
    "backstage-plugin-entity-editor-backend": "^0.1.0",
    "cookie-parser": "^1.4.6",
    "cross-fetch": "^4.0.0",
    "dockerode": "^3.3.5",
    "dotenv": "^16.3.1",
    "express": "^4.18.2",
    "express-promise-router": "^4.1.1",
    "flatted": "^3.2.9",
    "fs-extra": "^11.1.1",
    "jose": "^4.14.6",
    "jsonwebtoken": "^9.0.2",
    "knex": "^3.0.0",
    "lz-string": "^1.5.0",
    "pg": "^8.11.3",
    "winston": "^3.10.0",
    "yaml": "^2.3.2"
  },
  "devDependencies": {
    "@azure/identity-vscode": "^1.0.0",
    "@babel/core": "^7.23.0",
    "@babel/preset-env": "^7.22.20",
    "@babel/preset-typescript": "^7.23.0",
    "@backstage/backend-test-utils": "^0.3.8",
    "@backstage/plugin-scaffolder-node-test-utils": "^0.1.4",
    "@jest/globals": "^29.7.0",
    "@microsoft/microsoft-graph-types": "^2.38.0",
    "@types/cookie-parser": "^1.4.4",
    "@types/dockerode": "^3.3.19",
    "@types/express": "^4.17.17",
    "@types/express-serve-static-core": "^4.17.36",
    "@types/jest": "^29.5.5",
    "@types/luxon": "^3.3.2",
    "babel-jest": "^29.7.0",
    "better-sqlite3": "^8.6.0",
    "jest": "^29.7.0",
    "ts-jest": "^29.1.1"
  },
  "files": [
    "dist"
  ],
  "jest": {
    "preset": "ts-jest",
    "testEnvironment": "node"
  }
}
```

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None
