### ISSUE TITLE
💬 RFC: Rework OAuth provider environment config

### ISSUE THREAD

**Issue by Rugvip** [backstage/backstage#25205]
### 🔖 Need

We currently require an environment to be specified for each OAuth configuration in `app-config.yaml`, see for example the Google provider: https://github.com/backstage/backstage/blob/8d5cdb5d536cc8eb444da4b57dca4e36716f4535/plugins/auth-backend-module-google-provider/config.d.ts#L22

This environment is a fairly advanced use-case where an auth backend is able to serve multiple different environments at once, such as production, staging, local dev, or even preview builds. It's unfortunate that the environment needs to be present even for all OAuth setups, and I think we should aim to restructure the config to make it optional. This also applies to the `env` query parameter that is currently required for the initial `/start` request.

### 🎉 Proposal

We shift the configuration for all auth providers to support and potentially always use an array at the `auth.providers.<providerId>` level. For example, given the following configuration:

```yaml
auth:
  providers:
    google:
      production:
        clientId: abc
        clientSecret: 123
```

It can now be expressed like this instead:

```yaml
auth:
  providers:
    google:
    - clientId: abc
      clientSecret: 123
```

If one wants to use the environments concept, that can be expressed like this instead:

```yaml
auth:
  providers:
    google:
    - clientId: abc
      clientSecret: 123
    - env: development
      clientId: def
      clientSecret: 456
```

The provider entry without an explicit `env` is treated as the default one and will be used for all requests without an explicit `env=development`, including if a different `env` is specified. If one wants a more strict setup then you can specify an `env` for every entry, and the auth backend will return an error for requests without a matching `env`. Listing multiple configs without an `env` config will lead to the auth provider throwing an error at startup.

### ❌ Risks

This is a breaking change and we'd need to take care rolling it out. In particular we can expect frontend implementations to be out of sync in their `auth.env` config, which is why I suggest we do not reject unknown `env`s if a provider config without an explicit env is present.

A potential downside of the proposed config format is that it does not allow for configuration merging due to the usage of an array, which is the reason we picked this format to begin with. This is actually more likely to be a benefit in practice though, ensuring that conflicting auth configurations don't get merged together by mistake.

### 👀 Have you spent some time to check if this RFC has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)
