### ISSUE TITLE
🚀 Feature: Support multiple dn's for users and/or groups in ldap organizational plugin

### ISSUE THREAD

**Issue by Jenson3210** [backstage/backstage#25256]
### 🔖 Feature description

In a less-structurized ldap existing setup, it might happen that profiles are accross multiple dn's.
In our organization, we might be interested in masks AND profiles, which are in a different dn.
Providing multiple dn's is possible by providing multiple entries under `catalog.providers.ldapOrg.[id]`. 
However, both users and groups are required in each of these AND linking memberOf is not happening for the second (and later) rediscovered users with links to group. 

### 🎤 Context

I want to be able to mention the following example yaml (also list for users?):

```yaml
catalog:
  providers:
    ldapOrg:
      default:
        target: ldap://host:port
        bind:
          dn: CN=...,DC=int
          secret: password
        schedule:
          frequency: { hours: 24 }
          timeout: { minutes: 10 }
        users:
          dn: OU=users,OU=users_and_groups,DC=org
          options:
            paged: { pageSize: 500, pagePause: true }
        groups:
          - dn: OU=masks,OU=users_and_groups,DC=org
             options:
               paged: { pageSize: 500, pagePause: true }
          - dn: OU=profiles,OU=users_and_groups,DC=org
             options:
               paged: { pageSize: 500, pagePause: true }
```

### ✌️ Possible Implementation

I think [this code](https://github.com/backstage/backstage/blob/master/plugins/catalog-backend-module-ldap/src/ldap/read.ts#L281-L294) could support by adapting the GroupConfig and UserConfig types to be either the current object or an array of them. 
It would also be required to adapt `readLdapUsers` and `readLdapGroups` to build their array of `Group/UserEntity` using all provided entries. 
The `resolveRelations` code would then link all the users AND the profiles AND the masks.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!
