### ISSUE TITLE
🐛 Bug Report: Templates: Using the RepoUrlPicker leads to a ".repoUrl Incomplete repository location provided, owner not provided" validation error for Azure DevOps repositories since v1.28.0

### ISSUE THREAD

**Issue by ckuijjer** [backstage/backstage#25347]
### 📜 Description

When using a Template that uses the RepoUrlPicker to scaffold code in an Azure DevOps repository an validation error is thrown when validation the RepoUrlPicker field.

The validation error ".repoUrl Incomplete repository location provided, owner not provided" is shown since version v1.28.0

### 👍 Expected behavior

The validation shouldn't require the _owner_ for repoUrls constructed by the AzureRepoPicker

### 👎 Actual Behavior with Screenshots

A ".repoUrl Incomplete repository location provided, owner not provided" validation error is shown

### 👟 Reproduction steps

Create a scaffolding template where the RepoUrlPicker is used to select an Azure DevOps repository, see e.g.

```
   - title: Choose the location for your code
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - dev.azure.com
```

Use the RepoUrlPicker to select an organization, project, and repo and validate the field by moving to the next step.

### 📃 Provide the context for the Bug.

This is due to #24798 where the AzureRepoPicker is changed to construct urls using the _project_ instead of _owner_ searchParam.

However the validation on the field requires the _owner_ searchParam to be present.

https://github.com/backstage/backstage/blob/a4cfe9d6f4d063bdb8d4e96a3470cf6dcae3e82b/plugins/scaffolder/src/components/fields/RepoUrlPicker/validation.ts#L59

Note that these changes made to the AzureRepoPicker where an url with _project_ instead of _owner_ is constructed is a breaking change, as these urls are used in, at least, the _scaffolder-node_ and _scaffolder-backend-module-azure_ plugins.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, I don't have time to work on this right now
