### ISSUE TITLE
🐛 Bug Report: Entity in wildcard subfolder not showing in catalog when fetched from GitLab

### ISSUE THREAD

**Issue by arvid-digg** [backstage/backstage#25402]
### 📜 Description

When I point the catalog location towards a local file with a wildcard subfolder, it fetches both `Domain` and `System`. However, if I point the catalog location towards a GitLab URL, it can't fetch `System`.

**Folder structure**
```
backstage-metadata
|-- import-all.yaml
`-- metadata
    |-- domain
    |   |-- domain1.yaml
    |   `-- domain2.yaml
    `-- system
        |-- domain1
        |   |-- system1.yaml
        |   `-- system2.yaml
        `-- domain2
            `-- system3.yaml
```

**Content of import-all.yaml**
```yaml
apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: import-all-from-metadatarepo
  description: A collection of all templates and metadata from backstage-metadata
spec:
  targets:
    - ./metadata/domain/*.yaml
    - ./metadata/system/*/*.yaml # Note the wildcard subfolder
```

**app-config.local.yaml**
```yaml
catalog:
  providers:
    gitlab:
      my_gitlab:
        host: <redacted>
        orgEnabled: true
        fallbackBranch: main
        skipForkedRepos: false
        entityFilename: catalog-info.yam
        schedule:
          frequency: { minutes: 3}
          timeout: { minutes: 3 }

  import:
    entityFilename: catalog-info.yaml
    pullRequestBranchName: backstage-integration
  rules:
    - allow: [Component, System, API, Resource, Location, Domain, User]
  locations:
    # This rule doens't work with subfolders
    - type: url
      target: https://<redacted>/backstage-metadata/-/blob/master/import-all.yaml
      rules:
        - allow: [Domain, Location, System]

    # This rule works with subfolders
    # - type: file
    #   target: ../../../../config/backstage-metadata/import-all.yaml
    #   rules:
    #     - allow: [Domain, Location, System]
```

Is it possible to fetch wildcard subfolder when using GitLab and URL? We have a workaround but then we need to specify each subfolder in `metadata/system`.

### 👍 Expected behavior

Would love if the GitLab URL could fetch wildcard subfolders. 

### 👎 Actual Behavior with Screenshots

GitLab can't deliver wildcard URLs. 
It throws error: `SendArchive: copy 'git archive' output: rpc error: code = FailedPrecondition desc = path doesn't exist`. 
Uri: `/api/v4/projects/<redacted>/repository/archive?sha=master\u0026path=metadata%2Fsystem%2F*`

### 👟 Reproduction steps

Curl GitLab with wildcard expression: `curl --header "PRIVATE-TOKEN: <redacted>" \
  --url "https://<redacted>/api/v4/projects/<redacted>/repository/archive?sha=master&path=metadata%2Fsystem%2F*"`

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else
