### ISSUE TITLE
🐛 Bug Report: addTemplateGlobals does not properly support callables

### ISSUE THREAD

**Issue by VeithBuergerhoff** [backstage/backstage#25445]
### 📜 Description

The addTemplateGlobals function appears to be bugged.
Static values work just fine, but callables are not executed properly. They are either reduced to empty strings or result in *broken* strings.

#13704 Added the functionality to configure globals and also added test for both constants and callables.

### 👍 Expected behavior

Given the following module:
```ts
import { createBackendModule } from '@backstage/backend-plugin-api';
import { scaffolderTemplatingExtensionPoint } from '@backstage/plugin-scaffolder-node/alpha';
import { randomUUID } from 'crypto';

export const scaffolderModuleGuidGenerator = createBackendModule({
  pluginId: 'scaffolder',
  moduleId: 'guid-generator',
  register(reg) {
    reg.registerInit({
      deps: {
        scaffolder: scaffolderTemplatingExtensionPoint,
      },
      async init({ scaffolder }) {
        scaffolder.addTemplateGlobals({          
          guid: () => 'randomUUID()',
          guidT: (typeof( () => randomUUID())),
          guidNonReserved: () => randomUUID(),
        });
      },
    });
  },
});
```

and this template:
```yaml
apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: test
  title: Test
  description: Test
spec:
  owner: user:guest
  type: service

  parameters: []
   
  steps:
    - id: fetch-base
      name: Fetch Base
      action: fetch:template
      input:
        url: ./src
        targetPath: .
        values:
          g1: ${{ guid }}
          g2: ${{ guidT }}
          g3: ${{ guidNonReserved }}

```

with a file in ./src containing:
```
${{ g1 }}
${{ g2 }}
${{ g3 }}
${{ guid }}
${{ guidT }}
${{ guidNonReserved }}
```

There should be (callable) globals accessible to the templater which return
`randomUUID()`
`function`
`<some random UUID>`

So the scaffolder should pass
```json
{
   "url": "./src",
   "targetPath": ".",
   "values": {
     "g1": "randomUUID()",
     "g2": "function",
     "g3": "<some random UUID>",
   }
 } 
```
to the fetch:template action.

The templated file should contain
```
randomUUID()
function
<some random UUID>
randomUUID()
function
<some other random UUID>
```

### 👎 Actual Behavior with Screenshots

```json
{
   "url": "./src",
   "targetPath": ".",
   "values": {
     "g2": "function"
   }
 } 
```
Is passed to the fetch:template action.

The templated file contains
```

function

(...args) => JSON.parse(callGlobal(name, args))
function
(...args) => JSON.parse(callGlobal(name, args))
```
```ts
scaffolder.addTemplateFilters({
  guid: () => randomUUID(),
});
```
works just fine with `${{ "" | guid }}` but does not declare intend and results in hideous templates.

### 👟 Reproduction steps

Refer to expected behavior.

- Add a module with the given code.
- Add a template with the given step.
- Add a file to the src subdir of the template with the given content.
- Use the Template Editor to load and execute the template.

### 📃 Provide the context for the Bug.

I wanted to extend the scaffolder with a guid generator to fill in some guids in the service template. They are referenced multiple times and need to therefore be assigned to a value.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by camilaibs** [comment]
I was able to call the function in the template:

```yaml
  steps:
    - id: fetch-base
      name: Fetch Base
      action: fetch:template
      input:
        url: ./src
        targetPath: .
        values:
          g1: ${{ guid() }} # 👈🏻 
          g2: ${{ guidT }}
          g3: ${{ guidNonReserved() }} # 👈🏻
```
But as you said, it resolves to an empty string when the function is not called before being passed as a values ​​entry:

```diff
  steps:
    - id: fetch-base
      name: Fetch Base
      action: fetch:template
      input:
        url: ./src
        targetPath: .
        values:
-          g1: ${{ guid }} # 👈🏻 
+          g1: ${{ guid() }} # 👈🏻 
          g2: ${{ guidT }}
-          g3: ${{ guidNonReserved() }} # 👈🏻
+          g3: ${{ guidNonReserved }} # 👈🏻
```
I couldn't find documentation for this, so I wanted to check with @kissmikijr and @backstage/scaffolder-maintainers if it is expected that global functions can only be called in template files.
