### ISSUE TITLE
🐛 Bug Report: Make `usernameMatchingUserEntityName` sign-in resolver in GitHub auth provider to look for a user entity in all namespaces

### ISSUE THREAD

**Issue by gusevda** [backstage/backstage#25491]
### 📜 Description

If a user entity in a software catalog has namespace that is different from the `default` namespace it can not be resolved by standard `usernameMatchingUserEntityName` sign-in resolver from the `auth-backend-module-github-provider` module.

### 👍 Expected behavior

If there is a user entity in a catalog with a name that matches GitHub identity's username, this user entity has to be resolved regardless of namespace.

### 👎 Actual Behavior with Screenshots

[The resolver](https://github.com/backstage/backstage/blob/master/plugins/auth-backend-module-github-provider/src/resolvers.ts#L46) uses `signInWithCatalogUser({ entityRef: { name: userId } })` method from AuthResolverContext which uses `default` namespace to look up catalog entities if namespace parameter is not provided.

### 👟 Reproduction steps

I have this user entity in my Backstage catalog (gusevda is my GitHub username):
```
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
    name: gusevda
    namespace: test
    title: Dmitry Gusev
spec:
    profile:
        displayName: Dmitry Gusev
        picture: https://avatars.githubusercontent.com/u/445309?v=4
    memberOf: []
```

When I try to sign in by using GitHub auth provider, I get the error:
```
Login failed; caused by Error: Failed to sign-in, unable to resolve user identity
```

If I delete `namespace: test` from the user entity, authentication works as expected.

### 📃 Provide the context for the Bug.

I guess if in [the resolver](https://github.com/backstage/backstage/blob/master/plugins/auth-backend-module-github-provider/src/resolvers.ts#L46) we use
```
return ctx.signInWithCatalogUser({ filter: { 'metadata.name': userId } });
```
instead of
```
return ctx.signInWithCatalogUser({ entityRef: { name: userId } });
```
the problem will go away. Do you see any problems with that?

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!
