### ISSUE TITLE
🚀 Feature: Add option to secure endpoints created by plugin-events-backend 

### ISSUE THREAD

**Issue by Julien-Hery** [backstage/backstage#25490]
### 🔖 Feature description

We should add an option in app-config.yaml to make endpoints created by plugin-events-backend secured like any other endpoints as described [here](https://backstage.io/docs/auth/service-to-service-auth#static-tokens)

### 🎤 Context

As discussed [here](https://discord.com/channels/687207715902193673/687235481154617364/1256246251960270888) on Discord these endpoints should at least have a configuration to make them secured like any others

### ✌️ Possible Implementation

I see two possibilities, either a global config to make all the endpoints secured or a per endpoint config like it's done in the proxy. 

Global config : 
```yaml
events:
  http:
    secure: true
    topics:
      - topic-test
```

Per endpoint config : 
```yaml
events:
  http:
    topics:
      topic-test:
        secure: true
```

Then the configuration declared here : 

```yaml
backend:
  auth:
    externalAccess:
      - type: static
        options:
          token: ${AUTH_TOKEN}
          subject: my-subject
        accessRestrictions:
          - plugin: events
          - plugin: catalog
      - ...
```
should be used to authenticate calls to these endpoints.

Another possibility could be to make them secured by default and have an option to disable it (with the same options as proposed above)

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!
