### ISSUE TITLE
🐛 Bug Report: Github Auth config is not working in production mode

### ISSUE THREAD

**Issue by 0GiS0** [backstage/backstage#25496]
### 📜 Description

I have configured the auth section in both the `app-config.yaml`:

```yaml
auth:  
  # see https://backstage.io/docs/auth/ to learn about auth providers
  environment: development
  providers:
    # See https://backstage.io/docs/auth/guest/provider
    github:
      development:
        clientId: ${LOCAL_GITHUB_CLIENT_ID}
        clientSecret: ${LOCAL_GITHUB_CLIENT_SECRET}
        signIn:
          resolvers:
            - resolver: usernameMatchingUserEntityName
```

and `app-config.production.yaml`:

```yaml
auth:
  environment: production
  # see https://backstage.io/docs/auth/ to learn about auth providers
  providers:
    # See https://backstage.io/docs/auth/guest/provider
    github:      
      production:
        clientId: ${GITHUB_APP_CLIENT_ID}
        clientSecret: ${GITHUB_APP_CLIENT_SECRET}
        signIn:
          resolvers:
            - resolver: usernameMatchingUserEntityName
```

When I run `yarn dev` locally everything works as expected: It uses `app-config.yaml` as configuration. However, when I run it in the production environment it keeps looking for the credentials in the deployment environment (this is `app-config.yaml` instead of `app-config.production.yaml`), as this information is not loaded with the same environment variables fails.

### 👍 Expected behavior

Using `yarn dev` should use `app-config.yaml` with `auth.environment: development` and with `NODE_ENV=production` should use app-`config.production.yaml` with `auth.environment: production`.

### 👎 Actual Behavior with Screenshots

I get this error when I built the Docker image and it's in production:

![Image](https://github.com/user-attachments/assets/ae30c760-c967-4fc3-b228-68044732118f)

I have both files in this environment:

![Image](https://github.com/user-attachments/assets/e2efaf37-d9ae-4891-846b-106f09d6bf51)

If I change the name of the env variables in order to match with the production ones It works. The only thing then is that it is never taking into account the environment configuration: production.

### 👟 Reproduction steps

Configure two GitHub Apps: one for development and a second one for production. Add this configuration in `app-config.yaml`:

```yaml
auth:  
  # see https://backstage.io/docs/auth/ to learn about auth providers
  environment: development
  providers:
    # See https://backstage.io/docs/auth/guest/provider
    github:
      development:
        clientId: ${LOCAL_GITHUB_CLIENT_ID}
        clientSecret: ${LOCAL_GITHUB_CLIENT_SECRET}
        signIn:
          resolvers:
            - resolver: usernameMatchingUserEntityName
```

Execute `yarn dev` and you can see that it works.

And this in `app-config.production.yaml`:

```yaml
auth:
  environment: production
  # see https://backstage.io/docs/auth/ to learn about auth providers
  providers:
    # See https://backstage.io/docs/auth/guest/provider
    github:      
      production:
        clientId: ${GITHUB_APP_CLIENT_ID}
        clientSecret: ${GITHUB_APP_CLIENT_SECRET}
        signIn:
          resolvers:
            - resolver: usernameMatchingUserEntityName
```

### 📃 Provide the context for the Bug.

I would like to have two different configurations for dev and prod. I can do it using the same env variables in both environments but then we should use environment: production/development at all .... and It's mandatory

### 🖥️ Your Environment

```
yarn run v1.22.22
$ /workspaces/backstage-demo/backstage/node_modules/.bin/backstage-cli info
OS:   Linux 6.6.31-linuxkit - linux/x64
node: v18.20.3
yarn: 1.22.22
cli:  0.26.10 (installed)
backstage:  1.28.3

Dependencies:
  @backstage/app-defaults                                          1.5.7
  @backstage/backend-app-api                                       0.7.9
  @backstage/backend-common                                        0.23.2
  @backstage/backend-defaults                                      0.3.3
  @backstage/backend-dev-utils                                     0.1.4
  @backstage/backend-openapi-utils                                 0.1.14
  @backstage/backend-plugin-api                                    0.6.21
  @backstage/backend-tasks                                         0.5.26
  @backstage/catalog-client                                        1.6.5
  @backstage/catalog-model                                         1.5.0
  @backstage/cli-common                                            0.1.14
  @backstage/cli-node                                              0.2.6
  @backstage/cli                                                   0.26.10
  @backstage/config-loader                                         1.8.1
  @backstage/config                                                1.2.0
  @backstage/core-app-api                                          1.13.0
  @backstage/core-compat-api                                       0.2.6
  @backstage/core-components                                       0.14.8
  @backstage/core-plugin-api                                       1.9.3
  @backstage/e2e-test-utils                                        0.1.1
  @backstage/errors                                                1.2.4
  @backstage/eslint-plugin                                         0.1.8
  @backstage/frontend-plugin-api                                   0.6.6
  @backstage/integration-aws-node                                  0.1.12
  @backstage/integration-react                                     1.1.28
  @backstage/integration                                           1.12.0
  @backstage/plugin-api-docs                                       0.11.6
  @backstage/plugin-app-backend                                    0.3.70
  @backstage/plugin-app-node                                       0.1.21
  @backstage/plugin-auth-backend-module-atlassian-provider         0.2.2
  @backstage/plugin-auth-backend-module-aws-alb-provider           0.1.13
  @backstage/plugin-auth-backend-module-azure-easyauth-provider    0.1.4
  @backstage/plugin-auth-backend-module-bitbucket-provider         0.1.4
  @backstage/plugin-auth-backend-module-cloudflare-access-provider 0.1.4
  @backstage/plugin-auth-backend-module-gcp-iap-provider           0.2.16
  @backstage/plugin-auth-backend-module-github-provider            0.1.18
  @backstage/plugin-auth-backend-module-gitlab-provider            0.1.18
  @backstage/plugin-auth-backend-module-google-provider            0.1.18
  @backstage/plugin-auth-backend-module-guest-provider             0.1.7
  @backstage/plugin-auth-backend-module-microsoft-provider         0.1.16
  @backstage/plugin-auth-backend-module-oauth2-provider            0.2.2
  @backstage/plugin-auth-backend-module-oauth2-proxy-provider      0.1.14
  @backstage/plugin-auth-backend-module-oidc-provider              0.2.2
  @backstage/plugin-auth-backend-module-okta-provider              0.0.14
  @backstage/plugin-auth-backend-module-onelogin-provider          0.1.2
  @backstage/plugin-auth-backend                                   0.22.8
  @backstage/plugin-auth-node                                      0.4.16
  @backstage/plugin-auth-react                                     0.1.3
  @backstage/plugin-catalog-backend-module-github-org              0.1.16
  @backstage/plugin-catalog-backend-module-github                  0.6.4
  @backstage/plugin-catalog-backend-module-scaffolder-entity-model 0.1.19
  @backstage/plugin-catalog-backend                                1.23.2
  @backstage/plugin-catalog-common                                 1.0.24
  @backstage/plugin-catalog-graph                                  0.4.6
  @backstage/plugin-catalog-import                                 0.12.0
  @backstage/plugin-catalog-node                                   1.12.3
  @backstage/plugin-catalog-react                                  1.12.1
  @backstage/plugin-catalog                                        1.21.0
  @backstage/plugin-events-node                                    0.3.7
  @backstage/plugin-github-actions                                 0.6.16
  @backstage/plugin-org                                            0.6.26
  @backstage/plugin-permission-backend-module-allow-all-policy     0.1.18
  @backstage/plugin-permission-backend                             0.5.45
  @backstage/plugin-permission-common                              0.7.14
  @backstage/plugin-permission-node                                0.7.32
  @backstage/plugin-permission-react                               0.4.23
  @backstage/plugin-proxy-backend                                  0.5.2
  @backstage/plugin-scaffolder-backend-module-azure                0.1.13
  @backstage/plugin-scaffolder-backend-module-bitbucket-cloud      0.1.11
  @backstage/plugin-scaffolder-backend-module-bitbucket-server     0.1.11
  @backstage/plugin-scaffolder-backend-module-bitbucket            0.2.11
  @backstage/plugin-scaffolder-backend-module-gerrit               0.1.13
  @backstage/plugin-scaffolder-backend-module-gitea                0.1.11
  @backstage/plugin-scaffolder-backend-module-github               0.3.2
  @backstage/plugin-scaffolder-backend-module-gitlab               0.4.3
  @backstage/plugin-scaffolder-backend                             1.22.11
  @backstage/plugin-scaffolder-common                              1.5.3
  @backstage/plugin-scaffolder-node                                0.4.7
  @backstage/plugin-scaffolder-react                               1.9.0
  @backstage/plugin-scaffolder                                     1.22.0
  @backstage/plugin-search-backend-module-catalog                  0.1.27
  @backstage/plugin-search-backend-module-techdocs                 0.1.26
  @backstage/plugin-search-backend-node                            1.2.26
  @backstage/plugin-search-backend                                 1.5.13
  @backstage/plugin-search-common                                  1.2.12
  @backstage/plugin-search-react                                   1.7.12
  @backstage/plugin-search                                         1.4.12
  @backstage/plugin-signals-react                                  0.0.4
  @backstage/plugin-tech-radar                                     0.7.4
  @backstage/plugin-techdocs-backend                               1.10.8
  @backstage/plugin-techdocs-module-addons-contrib                 1.1.11
  @backstage/plugin-techdocs-node                                  1.12.7
  @backstage/plugin-techdocs-react                                 1.2.5
  @backstage/plugin-techdocs                                       1.10.6
  @backstage/plugin-user-settings-common                           0.0.1
  @backstage/plugin-user-settings                                  0.8.8
  @backstage/release-manifests                                     0.0.11
  @backstage/test-utils                                            1.5.7
  @backstage/theme                                                 0.5.6
  @backstage/types                                                 1.1.1
  @backstage/version-bridge                                        1.0.8
Done in 0.59s.
```

### 👀 Have you spent some time to check if this bug has been raised before?

- [x] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [x] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else
