### ISSUE TITLE
🐛 Bug Report: catalog-backend-module-msgraph doesn't provide header ConsistencyLevel in advanced queries

### ISSUE THREAD

**Issue by OSfrog** [backstage/backstage#25517]
### 📜 Description

I'm trying to use the GroupSearch property to get a specific group and I have enabled `queryMode: advanced`, and this should automatically send the `ConsistencyLevel: eventual` header with the request, but I'm getting an error saying that it's not being sent.

This is my config: 

```yaml
    microsoftGraphOrg:
      default:
        clientId: ${CLIENT_ID}
        clientSecret: ${CLIENT_SECRET}
        tenantId: ${TENANT_ID}
        queryMode: advanced
        userGroupMember:
          filter: displayName eq 'groupName'
        group:
          search: '"displayName:groupName"'
          expand: members
```

### 👍 Expected behavior

`ConsistencyLevel: eventual` header should be sent with the request.

### 👎 Actual Behavior with Screenshots

```
2024-07-04T07:50:41.533Z catalog error MicrosoftGraphOrgEntityProvider:default refresh failed, Error: Error while reading groups from Microsoft Graph: Request_UnsupportedQuery - Request with $search query parameter only works through MSGraph with a special request header: 'ConsistencyLevel: eventual' Error while reading groups from Microsoft Graph: Request_UnsupportedQuery - Request with $search query parameter only works through MSGraph with a special request header: 'ConsistencyLevel: eventual' class=MicrosoftGraphOrgEntityProvider taskId=MicrosoftGraphOrgEntityProvider:default:refresh taskInstanceId=OMITTED stack=Error: Error while reading groups from Microsoft Graph: Request_UnsupportedQuery - Request with $search query parameter only works through MSGraph with a special request header: 'ConsistencyLevel: eventual'
```

### 👟 Reproduction steps

Add a working config for the MSGraph with a search property and set `queryMode: advanced`

### 👀 Have you spent some time to check if this bug has been raised before?

- [x] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [x] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!
