### ISSUE TITLE
🚀 Feature: Expose existing components from FieldExtensions to allow customization

### ISSUE THREAD

**Issue by Silthus** [backstage/backstage#25528]
### 🔖 Feature description

It would be great if the `@backstage/plugin-scaffolder` would expose the underlying components of the respective `FieldExtension` in its public API surface, exporting them in the `index.ts`.
For example the [`OwnerPicker`](https://github.com/backstage/backstage/blob/master/plugins/scaffolder/src/components/fields/OwnerPicker/OwnerPicker.tsx) component.

### 🎤 Context

Reusing steps and inputs across multiple templates is hard without losing access to the Template Editor. So it would be great if the underlying defaults of the basic inputs could be changed centrally, e.g.: pre-filtering the `OwnerPicker` with a set of allowed teams.

So instead of repeating this:

```yaml
owner:
  title: Github Owner
  type: string
  description: Github Owner team of the repository.
  ui:field: OwnerPicker
  ui:options:
    catalogFilter:
      kind: Group
      relations.childOf:
        - 'group:default/parent1'
        - 'group:default/parent2'
```

over and over again in many templates, and needing to update and maintain it across multiple repositories.

Exposing the underlying component would allow us to do this instead:

```tsx
import {
  OwnerPicker,
  OwnerPickerFieldSchema,
} from '@backstage/plugin-scaffolder';
import React from 'react';

type OwnerPickerProps = typeof OwnerPickerFieldSchema.type;

/**
 * The underlying component that is rendered in the form for the `OwnerPicker`
 * field extension.
 *
 * @public
 */
export const FilteredOwnerPicker = (props: OwnerPickerProps) => {
  const { uiSchema, ...restProps } = props;

  const defaultNamespace = uiSchema['ui:options']?.defaultNamespace;
  const allowedKinds = uiSchema['ui:options']?.allowedKinds;

  const catalogFilter = uiSchema['ui:options']?.catalogFilter || {
    kind: allowedKinds || ['Group'],
    relations.childOf: ['parent1', 'parent2']
  };

  const ownerUiSchema = {
    ...uiSchema,
    'ui:options': {
      catalogFilter,
      defaultKind: 'Group',
      allowArbitraryValues:
        uiSchema['ui:options']?.allowArbitraryValues ?? true,
      ...(defaultNamespace !== undefined ? { defaultNamespace } : {}),
    },
  };

  return <OwnerPicker {...restProps} uiSchema={ownerUiSchema} />;
};
```

And the simply use the custom extension instead:

```yaml
owner:
  title: Github Owner
  type: string
  description: Github Owner team of the repository.
  ui:field: PreFilteredOwnerPicker
```

### ✌️ Possible Implementation

Just re-export the components in the `index.ts`.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!
