### ISSUE TITLE
💬 RFC: Scaffolder Variables in Parameters 

### ISSUE THREAD

**Issue by pguppy** [backstage/backstage#25520]
### 🔖 Need

I am wanting to know if there is any ways of passing a value of one parameter to another parameter, in the form of variables. Like in steps how you can use `${{ parameters.name }}` to pass the value of field, is there any way of doing that in parameters. So that I can take a input of one parameters and use is as a option for anther one.

### 🎉 Proposal

```yaml
# Notice the v1beta3 version
apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
# some metadata about the template itself
metadata:
  name: v1beta3-demo
  title: Test Action template
  description: scaffolder v1beta3 template demo
spec:
  owner: backstage/techdocs-core
  type: service

  # these are the steps which are rendered in the frontend with the form input
  parameters:
    - title: Fill in some steps
      required:
        - name
      properties:
        name:
          title: Name
          type: string
          description: Unique name of the component
          ui:autofocus: true
        test:
          title: test
          type: string
          description: demoing
          ui:field: demoing
          ui:options:
            name:: ${{ parameters.name }}
  steps:
[...]
```

          

### 👀 Have you spent some time to check if this RFC has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)
