### ISSUE TITLE
🚀 Feature: Scaffolder action for Azure AD membership check

### ISSUE THREAD

**Issue by floresjma** [backstage/backstage#25530]
### 🔖 Feature description

A new scaffolder action that checks whether an Azure AD user (or service account) belongs to specified Azure AD groups.

Imagine a scenario where the outputs of a template is to create a pull request in a given repository and run a CI/CD pipeline against it. The pipeline associated with this service deploys resources (e.g., cloud infrastructure, databases).  The scaffolder action ensures that only authorised users (based on Azure AD group membership) have the right access to those resources created. 

### 🎤 Context

We have seen developers creating components through templates and then trying to figure out what access they should request for the CI/CD pipeline to run successfully. By providing them feedback at template creation, not only give them information on what they need but also increase the level of confidence once the template is created, they are ready to use the resources created.

Most of the time, these checks run as the first steps in a template. This is to make sure that once the CI/CD pipeline runs, the Azure AD user (or service account) passes all the access checks.

## How to use the action in software templates

```yaml
apiVersion: scaffolder.backstage.io/v1beta3

kind: Template
  ...
spec:
  ...
  steps:
    - id: check-microsoft-user-groups
      name: Checking if User is part of Microsoft groups
      action: 'azure:ad:users:membership:check'
      input:
        user: AdeleV@contoso.com
        groupList: ['HR Taskforce']
```

The action checks if an Azure AD (Microsoft) user is member of any of the Azure AD (Microsoft) groups provided.

There are two required variables for this step.

`user`: A Microsoft User's ID or userPrincipalName (Refer to this [page](https://learn.microsoft.com/en-us/graph/api/resources/users?view=graph-rest-1.0) for more info on user { id | userPrincipalName } )
`groupList`: List of displayName's of Microsoft group to check (Refer to this [page](https://learn.microsoft.com/en-us/graph/api/resources/group?view=graph-rest-1.0#:~:text=%24search.-,displayName,-String) to find more info on Microsoft groups)

This Step returns below one Output Variable.

`isMember`: A boolean response indicating whether the specified user is a member of any of the Microsoft groups provided.

## Sample config to be defined within the app-config.yml file

```yaml
  baseUrl: https://graph.microsoft.com/v1.0
  tokenUrl: https://login.microsoftonline.com/{tenant}/oauth2/v2.0/token
  msGraphUser: ${MSGRAPH_USER}
  msGraphPass: ${MSGRAPH_PASSWORD}
  clientId: {client_id}
```
The feature has already been successfully used internally, we would like to make it available to the community.

### ✌️ Possible Implementation

It utilises the [Azure AD identity and access management API in Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/resources/azure-ad-overview?view=graph-rest-1.0&preserve-view=true) under the hood.

The feature has already been successfully used internally, we would like to make it available to the community. We are not sure if this will be part of the new Community Plugins repository or can be added under plugins in the _backstage/backstage_ repo.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!
