### ISSUE TITLE
🚀 Feature: Make current task id available as a variable in templates

### ISSUE THREAD

**Issue by dariozachow** [backstage/backstage#25553]
### 🔖 Feature description

It would be nice to have a global variable in templates containing the current task-id for further usage.

### 🎤 Context

We want to use the id of the task, to create merge requests and have the traceback to the task created by backstage. Plus having the task id makes it possible to use it as a branch name and prevent duplication of branch names, when running a template multiple times.

### ✌️ Possible Implementation

The variable could be named `taskId` and be use like parameters e.g.:

```yaml
    - id: delete
      action: fs:delete
      name: Delete files
      input:
        files:
          -  ${{ paramters.myFile }}
          -  ${{ taskId }}
```

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else
