### ISSUE TITLE
🐛 Bug Report: github:environment:create fails to write secrets when creating environments

### ISSUE THREAD

**Issue by skyem** [backstage/backstage#25576]
### 📜 Description

After updating to 1.28.3 from 1.27.x, github:environment:create was failing to write environment secrets when creating environments. 

### 👍 Expected behavior

It should write secrets to the environment when they are provided. 

### 👎 Actual Behavior with Screenshots

I tried to use create an environment with an environment variable and a secret using this:
```yaml
    - id: setEnv
      name: Setup Environment
      action: github:environment:create
      input:
        repoUrl: github.com?repo=${{ parameters.repoName }}&owner=skyem
        name: ${{ parameters.env }}
        environmentVariables:
          var1: ${{ parameters.envValue }}
        secrets:
          secret1: ${{ parameters.secretValue }}
```
The run resulted in this.

<img width="1413" alt="Screenshot 2024-07-10 at 1 11 33 PM" src="https://github.com/backstage/backstage/assets/4563437/1bf66480-ed55-4c28-b0e1-9b1a4afded58">

I saw in the repo that the environment and its environment variable were both created successfully, but the secret was not.
 
When I looked at our instance using Dynatrace, I could see that the `getEnvironmentPublicKey` request was failing while preparing to send the secret, then it was just trying the whole thing again. As the environment variable was created successfully before it failed, it then reported the error: Variable already exists.

Pull request #25384 fixed most of the issue reported in #25042, but apparently missed this call.

### 👟 Reproduction steps

See above

### 📃 Provide the context for the Bug.

See above

### 🖥️ Your Environment

OS:   Darwin 23.5.0 - darwin/arm64
node: v20.11.1
yarn: 3.8.1
cli:  0.26.11-next.1 (local)
backstage:  N/A

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!
