### ISSUE TITLE
🐛 Bug Report: Scrolling on parameter on type integer in Template UI changes number

### ISSUE THREAD

**Issue by Jenson3210** [backstage/backstage#25698]
### 📜 Description

When you scroll on the input field generated by an integer number parameter and then scroll on the page/input field, the value changes due to input type being number

### 👍 Expected behavior

Number should be stable

### 👎 Actual Behavior with Screenshots

https://github.com/user-attachments/assets/0ea5ff6f-ab42-48ec-bfa1-1655ba424afe

### 👟 Reproduction steps

```yaml
  parameters:
  - title: Provide the details
    properties:
      projectIds:
        title: Projects
        type: array
        items:
          type: integer
        description: List of project ids.
```

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None
