### ISSUE TITLE
Bug Report: TechDocs with Private S3 and html files

### ISSUE THREAD

**Issue by kotowick** [backstage/backstage#25703]
### 🔖 Need

Has anyone found a way to get Backstage to use techdocs from a private s3 bucket using html files? Tried everything I could online. 

I checked discord group and didn't find any answers there.

We basically generate techdocs from Github repos and push them to an S3 bucket. We then want this s3 bucket to be used with Backstage.

I did also try adding the "backend.reading.allow'" as per recommendation. 

```
reading:
    allow:
      - host: localhost:3000
      - host: abc.prod.url
        paths:
          - /api/graphql/schema
          
techdocs:
  sanitizer:
    allowedIframeHosts:
      - www.youtube.com
  builder: 'external' # Alternatives - 'external'
  generator:
    runIn: 'local' # Alternatives - 'local'
  publisher:
    type: awsS3 # Alternatives - 'googleGcs' or 'awsS3'. Read documentation for using alternatives.
    awsS3:
        bucketName: 'abc-bucket'
        accountId: 'abcid'
        region: 'us-east-1'
        s3ForcePathStyle: true

aws:
  accounts:
    - accountId: 'abcid'

catalog:
  rules:
    providers:
      githubOrg:
        id: production
        githubUrl: https://github.com
        orgs: ['abc']
        schedule:
          initialDelay: { seconds: 30 }
          frequency: { hours: 1 }
          timeout: { minutes: 50 }
    backstage:
      enabled: false
      schedule:
        frequency: { hours: 12 }
        timeout: { minutes: 30 }
```

```
Error: Building a newer version of this documentation failed. Error: "Reading from 's3://abc/tech-docs/main/index.html' is not allowed. You may need to configure an integration for the target host, or add it to the configured list of allowed hosts at 'backend.reading.allow'"

ERROR 404: NotFoundError: Page not found. This could be because there is no index.md file in the root of the docs directory of this repository.
```

### 🎉 Proposal

It would be great to have better examples around config.

### 👀 Have you spent some time to check if this RFC has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

**Comment by PeaWarrior** [comment]
Hey, here are the [docs with examples](https://backstage.io/docs/features/techdocs/using-cloud-storage/#configuring-aws-s3-bucket-with-techdocs) for setting up AWS. Based off of your config, it seems you might be missing some credentials.

Another thing, it looks like your `reading.allow` config should be under `backend` like so:
```
backend:
  reading:
      allow:
        - host: localhost:3000
        - host: abc.prod.url
          paths:
            - /api/graphql/schema
```
