### ISSUE TITLE
🚀 Feature:  Allow customization of Parameters / Actions based on User Defaults

### ISSUE THREAD

**Issue by GeetaAhuja** [backstage/backstage#25717]
### 🔖 Feature description

Allow different list of enum values for a template parameter based on the logged in user. Allow template actions to pick code from a specific location based on the logged in user

### 🎤 Context

We have multiple lines of business and quite a few of them might have different requirements for same templates.
Line of Business might be restrictive in terms of the language used for a template. 
Template for Generating a scaffold for Lambda API Deployment.
The scaffold is generated  in a git repo. The scaffold comprises of  1) App Code in language of users choice 2) CDK Infra Code 3) Firm specific Settings

Eg: languages allowed for the template may vary based on line of business they belong to, so the enum in the example below needs to be dynamic. 

  

The If conditions on the dependency can be used to achieve this would make the template bulky, and make maintenance difficult.

```
parameters:
    - title: Fill in some steps
      required:
        - lob
      properties:
        lob:
          title: Line of Business
          type: string
          description: Unique Line of Business of the component
          ui:autofocus: true
          enum:
              - FS
              - Shared Tech
      dependencies:
        lob:
          oneOf:
            - properties:
                lob:
                  enum:
                    - Shared Tech
                language:
                  title: Language
                  type: string
                  enum:
                    - Python
                    - Typescript
                    - Go
                required:
                  - language                      
            - properties:
                lob:
                  enum:
                    - FS
                language:
                  title: Language
                  type: string
                  enum:
                    - Python
                    - Typescript                    
                required:
                  - language   
```

The thought process was  of having template level defaults for every template. which can be evaluated on click of launch template and can be used across for the template 
We could have defaults associated to the template be a object. That is either stored with template  

### ✌️ Possible Implementation

Template has default values loaded as a JSON Object based on a criteria of logged in User properties. This keys from the JSON Object is available through out the template for all values needed by parameters and steps.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else
