### ISSUE TITLE
🐛 Bug Report: Sign in using GitHub - Login failed, user profile does not contain an email

### ISSUE THREAD

**Issue by SzymonSt** [backstage/backstage#25762]
### 📜 Description

I cannot log in via GitHub provider which block my further development with Backstage. I follow all of the current docs steps and steps mentioned in similar issue: https://github.com/backstage/backstage/issues/24685 but it still doesn't work for me.

### 👍 Expected behavior

I should be able to log in.
My email on GitHub is seen as public: 
<img width="1070" alt="Zrzut ekranu 2024-07-24 o 13 52 31" src="https://github.com/user-attachments/assets/aa92d5de-1c84-4ea6-aff3-9f93c960224e">

### 👎 Actual Behavior with Screenshots

It fails to log me in despite having multiple resolvers queued:
<img width="544" alt="Zrzut ekranu 2024-07-24 o 13 28 33" src="https://github.com/user-attachments/assets/e3d345d3-2df6-41a0-a202-637a15f0d41c">

### 👟 Reproduction steps

1. Set up providers as mentioned in the context section below
2. Try to log in via Github provider

### 📃 Provide the context for the Bug.

`org.yaml`
```
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: SzymonSt
spec:
  profile:
    displayName: SzymonStawski
    email: szymonst2808@gmail.com
  memberOf: [quests]
---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-user
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: guest
spec:
  memberOf: [guests]
---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-group
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: guests
spec:
  type: team
  children: []
~                      
```

`app-config.yaml` - auth section
```
auth:
  environment: development
  # see https://backstage.io/docs/auth/ to learn about auth providers
  providers:
    # See https://backstage.io/docs/auth/guest/provider
    github:
      development:
        clientId: [REDUCTED]
        clientSecret: [REDUCTED]
        signIn:
          resolvers:
            # Matches the GitHub username with the Backstage user entity name.
            # See https://backstage.io/docs/auth/github/provider#resolvers for more resolvers.
            - resolver: usernameMatchingUserEntityName
            - resolver: emailLocalPartMatchingUserEntityName
            - resolver: emailMatchingUserEntityProfileEmail
```

`app-config.yaml` - catalog.providers section
```
catalog:
  providers:
    githubOrg:
      - id: github
        githubUrl: https://github.com
```

`packages/backend/src/index.ts` - auth section
```
// auth plugin
backend.add(import('@backstage/plugin-auth-backend'));
// See https://backstage.io/docs/backend-system/building-backends/migrating#the-auth-plugin
backend.add(import('@backstage/plugin-auth-backend-module-guest-provider'));
backend.add(import('@backstage/plugin-auth-backend-module-github-provider'));
```

`packages/app/src/App.tsx` - components section
```
  components: {
  SignInPage: props => (
    <SignInPage
      {...props}
      auto
      provider={{
        id: 'github-auth-provider',
        title: 'GitHub',
        message: 'Sign in using GitHub',
        apiRef: githubAuthApiRef,
      }}
    />
  ),
  }
```

### 🖥️ Your Environment

Docker container.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by SzymonSt** [comment]
@rghara according to doc they are executed in order provided that previous return `NotFound` https://backstage.io/docs/auth/github/provider#resolvers . I've tried that already - different error.

**Comment by SzymonSt** [comment]
Hi @rghara so I got back to it tonight and it turned out default path to org.yaml config wasn't correct - didn't work with docker I've changed them to absolute and it created user for me and worked just with `- resolver: usernameMatchingUserEntityName` not closing the issue yet. Let me know if you are still stuck and let's figure it out.

**Comment by SzymonSt** [comment]
Changed: 
```
    # Local example organizational data
    - type: file
      target: ../../examples/org.yaml
      rules:
        - allow: [User, Group]
```
to
```
    # Local example organizational data
    - type: file
      target: /app/examples/org.yaml
      rules:
        - allow: [User, Group]
```

**Comment by rghara** [comment]
@SzymonSt Sorry I got super busy. I will try this out and see if it works.

**Comment by Jetaldesai** [comment]
Did it work? I am running into same issue

**Comment by Jetaldesai** [comment]
Do you need to configure Github Auth under only Auth section or is that needs to be setup under catalog and other options too?

**Comment by rghara** [comment]
@Jetaldesai 
I adjusted configuration to what @SzymonSt posted under "Provide the context for the Bug".  It's working now. 
I did not have to do this change though:
```
    # Local example organizational data
    - type: file
      target: /app/examples/org.yaml
      rules:
        - allow: [User, Group]
```
