### ISSUE TITLE
Login failed; caused by Error: The GitHub provider is not configured to support sign-in 🐛 Bug Report: <Github SSO Error>

### ISSUE THREAD

**Issue by moali404** [backstage/backstage#25863]
### 📜 Description

Hi, I am trying to implement GitHub SSO on the Backstage boilerplate. I am getting the following error:

"Login failed; caused by Error: The GitHub provider is not configured to support sign-in"

July 2024

### 👍 Expected behavior

It should login without any problem and we can see the user's name and profile picture in the settings tab.

### 👎 Actual Behavior with Screenshots

My code and steps

I created an organisation and within that organisation created an OAuth application. 

`app-config.yaml
`
```
auth:
  # see https://backstage.io/docs/auth/ to learn about auth providers
  environment: development
  providers:
    github:
      development:
        clientId: xxxx
        clientSecret: xxxx
        signIn:
          resolvers:
           resolver: usernameMatchingUserEntityName

catalog:
  import:
    entityFilename: catalog-info.yaml
    pullRequestBranchName: backstage-integration
  rules:
    - allow: [Component, System, API, Resource, Location]
  providers:
    githubOrg:
      id: development 
      orgs: ['Backstage-I-O']
      githubUrl: https://github.com/Backstage-I-O
      schedule:
        initialDelay: { seconds: 30 }
        frequency: { hours: 1 }
        timeout: { minutes: 50 }

```
Tried with both .env variables and hardcoded variables.

`app-config.yaml
`
```
# Backstage override configuration for your local development environment
integrations:
  github:
    - host: github.com
       token: xxxx # this will use the environment variable GITHUB_TOKEN`
Tried with both .env variables and hardcoded variables.

```
My username as you can see on this profile as well is moali404 added in org.yaml as per suggestion of other issues

`org.yaml'

```
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-user
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: moali404
spec:
  memberOf: [guests]
---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-group
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: guests
spec:
  type: team
  children: []

```

`packages/backend/src/index.ts
`
```
backend.add(import('@backstage/plugin-app-backend/alpha'));
backend.add(import('@backstage/plugin-proxy-backend/alpha'));
backend.add(import('@backstage/plugin-scaffolder-backend/alpha'));
backend.add(import('@backstage/plugin-techdocs-backend/alpha'));

// auth plugin
backend.add(import('@backstage/plugin-auth-backend'));
// See https://backstage.io/docs/backend-system/building-backends/migrating#the-auth-plugin
backend.add(import('@backstage/plugin-auth-backend-module-guest-provider'));
// See https://backstage.io/docs/auth/guest/provider
backend.add(import('@backstage/plugin-auth-backend-module-github-provider'))  
// IMPORTANT for github error resolution
```
`
packages\app\src\App.tsx
`
```const githubAuthCfg = {
  id: 'github-auth-provider',
  title: 'GitHub',
  message: 'Sign in using GitHub',
  apiRef: githubAuthApiRef,
};

const app = createApp({
  apis,
  bindRoutes({ bind }) {
    bind(catalogPlugin.externalRoutes, {
      createComponent: scaffolderPlugin.routes.root,
      viewTechDoc: techdocsPlugin.routes.docRoot,
      createFromTemplate: scaffolderPlugin.routes.selectedTemplate,
    });
    bind(apiDocsPlugin.externalRoutes, {
      registerApi: catalogImportPlugin.routes.importPage,
    });
    bind(scaffolderPlugin.externalRoutes, {
      registerComponent: catalogImportPlugin.routes.importPage,
      viewTechDoc: techdocsPlugin.routes.docRoot,
    });
    bind(orgPlugin.externalRoutes, {
      catalogIndex: catalogPlugin.routes.catalogIndex,
    });
  },
  components: {
    SignInPage: props => (
      <SignInPage {...props} auto providers={['guest', githubAuthCfg]} />
    ),
  },
});
```

### 👟 Reproduction steps

I implemented solution and advices from the following threads (atleast all that were relevant)

Link1: [https://github.com/backstage/backstage/pull/13640]
Link2:[https://github.com/backstage/backstage/issues/23748]
Link3:[https://github.com/backstage/backstage/issues/11119]

Some Screenshots for your attention
<img width="944" alt="image" src="https://github.com/user-attachments/assets/ec5ab138-d846-42c5-9392-f729a35dc8bb">

### 🖥️ Your Environment

```
"devDependencies": {
    "@backstage/cli": "^0.26.11",
    "@backstage/e2e-test-utils": "^0.1.1",
    "@playwright/test": "^1.32.3",
    "@spotify/prettier-config": "^12.0.0",
    "concurrently": "^8.0.0",
    "lerna": "^7.3.0",
    "node-gyp": "^10.0.0",
    "prettier": "^2.3.2",
    "typescript": "~5.4.0"
  },
```

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by awanlin** [comment]
Hi @moali404, this error is related to incorrect config, looking at what you shared you are missing a `-` before `resolver:`

```yaml
auth:
  # see https://backstage.io/docs/auth/ to learn about auth providers
  environment: development
  providers:
    github:
      development:
        clientId: xxxx
        clientSecret: xxxx
        signIn:
          resolvers:
            - resolver: usernameMatchingUserEntityName
 ```
 
Can you try that, please?
