### ISSUE TITLE
🐛 Bug Report: Things not working after migrating to 1.29.2 from 1.23

### ISSUE THREAD

**Issue by toughthomas** [backstage/backstage#25887]
### 📜 Description

Hello, i am a bit lost after migrating from 1.23.3 to 1.29.2

Here are my config files : 

app.config.yaml : 

```
app:
  title: myApp
  baseUrl: http://localhost:3000

organization:
  name: myApp

backend:
  baseUrl: http://localhost:7007
  listen:
    port: 7007
  cors:
    origin: http://localhost:3000
    methods: [GET, HEAD, PATCH, POST, PUT, DELETE]
    credentials: true
  database:
    client: better-sqlite3
    connection: ':memory:'

proxy:
  endpoints:
    '/mysite':
      target: https://mysite.com
      headers:
        'API-Key': xxxxxx
      allowedHeaders: ['Username']

auth:
  environment: development
  providers:
    guest: {}
```

and my backend file : 

```
const backend = createBackend();

// Catalog
backend.add(catalogModuleCustomExtensions);
backend.add(import('@backstage/plugin-catalog-backend/alpha'));
backend.add(
  import('@backstage/plugin-catalog-backend-module-scaffolder-entity-model'),
);
backend.add(import('@backstage/plugin-catalog-backend-module-github/alpha'));
backend.add(import('@backstage/plugin-catalog-backend-module-github-org'));

// Search
backend.add(import('@backstage/plugin-search-backend/alpha'));
backend.add(
  import('@backstage/plugin-search-backend-module-elasticsearch/alpha'),
);
backend.add(import('@backstage-community/search-backend-module-adr'));

backend.add(import('@backstage-community/plugin-adr-backend'));
backend.add(import('@internal/backstage-plugin-health-backend'));
backend.add(import('@backstage-community/plugin-sonarqube-backend'));
backend.add(import('@backstage/plugin-techdocs-backend/alpha'));
backend.add(import('@backstage-community/plugin-tech-insights-backend'));
backend.add(import('@backstage/plugin-app-backend/alpha'));
backend.add(import('@backstage/plugin-proxy-backend/alpha'));
backend.add(import('@backstage/plugin-scaffolder-backend/alpha'));

backend.add(import('@backstage/plugin-auth-backend'));
backend.add(import('@backstage/plugin-auth-backend-module-guest-provider'));

backend.add(import('@internal/backstage-plugin-truc-backend'));
backend.start();
```

when i go to localhost:3000 backstage asks me to login with Github ?! there is no github configuration at all i dont even have the provider added to the backend so i dont really get why.

i tried to create backstage backend plugin like in the tutorial : https://backstage.io/docs/plugins/backend-plugin/ i cant reach the health endpoint of the tutorial, keep redirecting me to the homepage with the github login

and the proxy plugins is not working anymore, it not forwarding the header like it used to do before the migration.

### 👍 Expected behavior

i should be able to browse my backstage instance locally and reach the health endpoint and the proxy plugin should work

### 👎 Actual Behavior with Screenshots

its not working

### 👟 Reproduction steps

see description

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None
