### ISSUE TITLE
🐛 Bug Report: Backstage does not respects custom relations that i have in my yaml files

### ISSUE THREAD

**Issue by stripathix** [backstage/backstage#25931]
### 📜 Description

I want to add custom relationship data to catalog YAML file which looks like 

```
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: johndoe
  role: Director
spec:
  profile:
    displayName: John Doe
    email: johndoe@gmail.com
  memberOf:
    - group:scrum-design-research
  reporteeOf:
    - user:davidbeck
  managerOf:
    - user:braynbuser
```

But when i fetch this data the relations object in JSON only contains memberOf relation it ignores reporteeOf and managerOf relationship

### 👍 Expected behavior

I expect that those custom relations should be populated in relations object when data is fetched### 

### 👎 Actual Behavior with Screenshots

JSON only contains memberOf relation it ignores reporteeOf and managerOf relationship

### 👟 Reproduction steps

Its internal VPN application

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else
