### ISSUE TITLE
🐛 Bug Report: unable to register multiple components using one template

### ISSUE THREAD

**Issue by RobinMilissen** [backstage/backstage#25943]
### 📜 Description

I am unable to create and register multiple components (Gitlab repositories) using one template. 
`Invalid input passed to action catalog:register, instance is not exactly one from [subschema 0],[subschema 1]`

### 👍 Expected behavior

It should create multiple Gitlab repositories and register the repos as components in backstage.

### 👎 Actual Behavior with Screenshots

After creation of the repos the template fails on the catalog:register part with the following error.
`Invalid input passed to action catalog:register, instance is not exactly one from [subschema 0],[subschema 1]`

Even when registering only one repo using **catalog:register** the template still fails with the same error.

### 👟 Reproduction steps

Template below:

> Note: Even when removing 2 of the 3 catalog:register steps the template still fails with the same error.

```
apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: workshop-init-template
  title: Workshop Init Template
  description: |
    Template for setting up a workshop.
  tags:
  - template

spec:
  owner: user:xx@xx.com
  type: combo

  parameters:
  - title: Workshop details
    properties:
      workshopDescription:
      ...

# Fetch template for repository 1
  - id: fetch-base
    name: Fetch template
    action: fetch:template
    input:
      url: https://gitlab.com/xx/xx/-/tree/main/repo1
      targetPath: ./repo1
      values:
        description: ${{ parameters.workshopDescription }}
        owner: ${{ parameters.owner }}

# Fetch template for repository 2
  - id: fetch-base
    name: Fetch template
    action: fetch:template
    input:
      url: https://gitlab.com/xx/xx/-/tree/main/repo2
      targetPath: ./repo2
      values:
        description: ${{ parameters.workshopDescription }}
        owner: ${{ parameters.owner }}

# Fetch template for repository 3
  - id: fetch-base
    name: Fetch template
    action: fetch:template
    input:
      url: https://gitlab.com/xx/xx/-/tree/main/repo3
      targetPath: ./repo3
      values:
        description: ${{ parameters.workshopDescription }}
        owner: ${{ parameters.owner }}

# Publish repository 1
  - id: publish-repo1
    name: Create repo1 Gitlab
    action: publish:gitlab
    input:
      allowedHosts: ['gitlab.com']
      repoUrl: ${{ parameters.repo1 }}
      defaultBranch: ${{ parameters.repo_branch }}
      sourcePath: ./repo1

# Publish repository 2
  - id: publish-repo2
    name: Create repo2 Gitlab
    action: publish:gitlab
    input:
      allowedHosts: ['gitlab.com']
      repoUrl: ${{ parameters.repo2 }}
      defaultBranch: ${{ parameters.repo_branch }}
      sourcePath: ./repo2

# Publish repository 3
  - id: publish-repo3
    name: Create repo3 Gitlab
    action: publish:gitlab
    input:
      allowedHosts: ['gitlab.com']
      repoUrl: ${{ parameters.repo3 }}
      defaultBranch: ${{ parameters.repo_branch }}
      sourcePath: ./repo3

# Register repository 1 in Backstage
  - id: register-repo1
    name: Register Repository 1 in Backstage
    action: catalog:register
    input:
      repoContentsUrl: ${{ steps.publish-repo1.output.repoContentsUrl }}
      catalogInfoPath: '/catalog-info.yaml'

# Register repository 2 in Backstage
  - id: register-repo2
    name: Register Repository 2 in Backstage
    action: catalog:register
    input:
      repoContentsUrl: ${{ steps.publish-repo2.output.repoContentsUrl }}
      catalogInfoPath: '/catalog-info.yaml'

# Register repository 3 in Backstage
  - id: register-repo3
    name: Register Repository 3 in Backstage
    action: catalog:register
    input:
      repoContentsUrl: ${{ steps.publish-repo3.output.repoContentsUrl }}
      catalogInfoPath: '/catalog-info.yaml'
```

### 🖥️ Your Environment

Backstage is ran in Kubernetes.
yarn backstage-cli info
```
yarn run v1.22.22
$ /app/backstage/node_modules/.bin/backstage-cli info
OS:   Linux 6.1.0-18-amd64 - linux/x64
node: v18.19.0
yarn: 1.22.22
cli:  0.25.2 (installed)
backstage:  N/A

Dependencies:
  @backstage/app-defaults                                          1.5.5
  @backstage/backend-app-api                                       0.7.5
  @backstage/backend-common                                        0.21.7, 0.22.0
  @backstage/backend-dev-utils                                     0.1.4
  @backstage/backend-openapi-utils                                 0.1.11
  @backstage/backend-plugin-api                                    0.6.18
  @backstage/backend-tasks                                         0.5.23
  @backstage/catalog-client                                        1.6.5
  @backstage/catalog-model                                         1.5.0
  @backstage/cli-common                                            0.1.13
  @backstage/cli-node                                              0.2.5
  @backstage/cli                                                   0.25.2
  @backstage/config-loader                                         1.8.0
  @backstage/config                                                1.2.0
  @backstage/core-app-api                                          1.12.5
  @backstage/core-compat-api                                       0.2.5
  @backstage/core-components                                       0.14.7
  @backstage/core-plugin-api                                       1.9.2
  @backstage/errors                                                1.2.4
  @backstage/eslint-plugin                                         0.1.8
  @backstage/frontend-plugin-api                                   0.6.5
  @backstage/integration-aws-node                                  0.1.12
  @backstage/integration-react                                     1.1.27
  @backstage/integration                                           1.11.0
  @backstage/plugin-api-docs                                       0.11.5
  @backstage/plugin-app-backend                                    0.3.67
  @backstage/plugin-app-node                                       0.1.18
  @backstage/plugin-auth-backend-module-atlassian-provider         0.1.10
  @backstage/plugin-auth-backend-module-aws-alb-provider           0.1.10
  @backstage/plugin-auth-backend-module-azure-easyauth-provider    0.1.1
  @backstage/plugin-auth-backend-module-bitbucket-provider         0.1.1
  @backstage/plugin-auth-backend-module-cloudflare-access-provider 0.1.1
  @backstage/plugin-auth-backend-module-gcp-iap-provider           0.2.13
  @backstage/plugin-auth-backend-module-github-provider            0.1.15
  @backstage/plugin-auth-backend-module-gitlab-provider            0.1.15
  @backstage/plugin-auth-backend-module-google-provider            0.1.15
  @backstage/plugin-auth-backend-module-microsoft-provider         0.1.13
  @backstage/plugin-auth-backend-module-oauth2-provider            0.1.15
  @backstage/plugin-auth-backend-module-oauth2-proxy-provider      0.1.11
  @backstage/plugin-auth-backend-module-oidc-provider              0.1.9
  @backstage/plugin-auth-backend-module-okta-provider              0.0.11, 0.0.6
  @backstage/plugin-auth-backend                                   0.21.3, 0.22.5
  @backstage/plugin-auth-node                                      0.4.13
  @backstage/plugin-auth-react                                     0.1.2
  @backstage/plugin-catalog-backend-module-gitlab                  0.3.16
  @backstage/plugin-catalog-backend-module-msgraph                 0.5.26
  @backstage/plugin-catalog-backend-module-scaffolder-entity-model 0.1.16
  @backstage/plugin-catalog-backend                                1.22.0
  @backstage/plugin-catalog-common                                 1.0.23
  @backstage/plugin-catalog-graph                                  0.4.5
  @backstage/plugin-catalog-import                                 0.10.10
  @backstage/plugin-catalog-node                                   1.12.0
  @backstage/plugin-catalog-react                                  1.12.0
  @backstage/plugin-catalog                                        1.20.0
  @backstage/plugin-events-node                                    0.3.4
  @backstage/plugin-github-actions                                 0.6.16
  @backstage/plugin-org                                            0.6.25
  @backstage/plugin-permission-common                              0.7.13
  @backstage/plugin-permission-node                                0.7.29
  @backstage/plugin-permission-react                               0.4.22
  @backstage/plugin-proxy-backend                                  0.4.16
  @backstage/plugin-scaffolder-backend-module-azure                0.1.10
  @backstage/plugin-scaffolder-backend-module-bitbucket-cloud      0.1.8
  @backstage/plugin-scaffolder-backend-module-bitbucket-server     0.1.8
  @backstage/plugin-scaffolder-backend-module-bitbucket            0.2.8
  @backstage/plugin-scaffolder-backend-module-gerrit               0.1.10
  @backstage/plugin-scaffolder-backend-module-gitea                0.1.8
  @backstage/plugin-scaffolder-backend-module-github               0.2.8
  @backstage/plugin-scaffolder-backend-module-gitlab               0.2.16, 0.4.0
  @backstage/plugin-scaffolder-backend                             1.21.0, 1.22.7
  @backstage/plugin-scaffolder-common                              1.5.2
  @backstage/plugin-scaffolder-node                                0.3.3, 0.4.4
  @backstage/plugin-scaffolder-react                               1.8.5
  @backstage/plugin-scaffolder                                     1.20.0
  @backstage/plugin-search-backend-module-catalog                  0.1.24
  @backstage/plugin-search-backend-module-pg                       0.5.27
  @backstage/plugin-search-backend-module-techdocs                 0.1.23
  @backstage/plugin-search-backend-node                            1.2.23
  @backstage/plugin-search-backend                                 1.5.9
  @backstage/plugin-search-common                                  1.2.11
  @backstage/plugin-search-react                                   1.7.11
  @backstage/plugin-search                                         1.4.11
  @backstage/plugin-tech-radar                                     0.6.13
  @backstage/plugin-techdocs-backend                               1.10.5
  @backstage/plugin-techdocs-module-addons-contrib                 1.1.10
  @backstage/plugin-techdocs-node                                  1.12.4
  @backstage/plugin-techdocs-react                                 1.2.4
  @backstage/plugin-techdocs                                       1.10.5
  @backstage/plugin-user-settings                                  0.8.6
  @backstage/release-manifests                                     0.0.11
  @backstage/repo-tools                                            0.9.0
  @backstage/theme                                                 0.5.5
  @backstage/types                                                 1.1.1
  @backstage/version-bridge                                        1.0.8
```

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, I don't have time to work on this right now
