### ISSUE TITLE
🐛 Bug Report: Scaffolder template secrets are saved only using the name, not path

### ISSUE THREAD

**Issue by OW3902** [backstage/backstage#25966]
### 📜 Description

When using the `ui:field: Secret` option I expect the secret to be saved with the proper path to the parameter.
This is not a problem when you have a parameter in the root scope, but is one when using objects inside the template.

Imagine following scaffolder template spec:

```
spec:
  type: service
  parameters:
    - title: Foo
      properties:
        foo:
          title: 'Foo object'
          type: object
          properties:
            name:
              title: Foo name
              type: string
              ui:field: Secret
```

### 👍 Expected behavior

I should be able to access the secret with 

```
${{ secrets.foo.name }}
```

### 👎 Actual Behavior with Screenshots

I have to access the secret via:

```
${{ secrets.name }}
```

### 👟 Reproduction steps

1. Create a template with with parameters that are saved inside an object.
2. Try accessing the secrets inside your actions.

I can provide this:

```
apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: create-foo
  title: Create Foo
  description: Creates Foo
spec:
  type: service
  parameters:
    - title: Foo
      properties:
        foo:
          title: 'Foo object'
          type: object
          properties:
            name:
              title: Foo name
              type: string
              ui:field: Secret

  steps:
    - id: debug
      name: debug
      action: debug:log
      input:
        message: "Creating foo with name: ${{ secrets.name | lower }}"
```

But the debug:log action doesn't print secrets so you will need to have some action that uses the secret to reproduce.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None
