### ISSUE TITLE
🐛 Bug Report: Microsoft Entra Tenant Data Plugin is throwing AuthenticationRequiredError

### ISSUE THREAD

**Issue by Ajay-Syamaladevi** [backstage/backstage#26017]
### 📜 Description

We are getting AuthenticationRequiredError error on while trying to integrate Microsoft Entra Tenant Data Plugin to IDP.

Current Configuration:

```yaml
catalog:
  providers:
    microsoftGraphOrg:
      providerId:
        target: https://graph.microsoft.com/v1.0
        authority: https://login.microsoftonline.com
        tenantId: ${AZURE_TENANT_ID}
        clientId: ${AZURE_CLIENT_ID}
        clientSecret: ${AZURE_CLIENT_SECRET}
        user:
          expand: manager
          filter: accountEnabled eq true and userType eq 'member'
          loadPhotos: true
          select: ['id', 'displayName', 'description']
        group:
          expand: member
          filter: securityEnabled eq false and mailEnabled eq true and groupTypes/any(c:c+eq+'Unified')
          search: '"description:One" AND ("displayName:Video" OR "displayName:Drive")'
          select: ['id', 'displayName', 'description']
        schedule:
          frequency: { hours: 1 }
          timeout: { minutes: 50 }
```

### 👍 Expected behavior

Reading msgraph users and groups
Read 0 msgraph users and 0 msgraph groups

### 👎 Actual Behavior with Screenshots

```text
error MicrosoftGraphOrgEntityProvider:providerId refresh failed, AuthenticationRequiredError: network_error: Network request failed network_error: Network request failed class=MicrosoftGraphOrgEntityProvider taskId=MicrosoftGraphOrgEntityProvider:providerId:refresh taskInstanceId=150b1383-37f6-4b3f-808a-0caed5662197 scopes=https://graph.microsoft.com/.default getTokenOptions=[object Object] name=AuthenticationRequiredError stack=AuthenticationRequiredError: network_error: Network request failed
[1]     at handleMsalError (/Users/xqe035/Documents/projects/idp/backstage/node_modules/@azure/identity/src/msal/utils.ts:204:10)
[1]     at Object.getTokenByClientSecret (/Users/xqe035/Documents/projects/idp/backstage/node_modules/@azure/identity/src/msal/nodeFlows/msalClient.ts:495:13)
[1]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[1]     at Object.withSpan (/Users/xqe035/Documents/projects/idp/backstage/node_modules/@azure/core-tracing/src/tracingClient.ts:70:22)
[1]     at MicrosoftGraphClient.requestRaw (/Users/xqe035/Documents/projects/idp/backstage/node_modules/@backstage/plugin-catalog-backend-module-msgraph/src/microsoftGraph/client.ts:223:19)
[1]     at MicrosoftGraphClient.requestApi (/Users/xqe035/Documents/projects/idp/backstage/node_modules/@backstage/plugin-catalog-backend-module-msgraph/src/microsoftGraph/client.ts:204:12)
[1]     at MicrosoftGraphClient.requestCollection (/Users/xqe035/Documents/projects/idp/backstage/node_modules/@backstage/plugin-catalog-backend-module-msgraph/src/microsoftGraph/client.ts:152:20)
[1]     at MicrosoftGraphClient.getUsers (/Users/xqe035/Documents/projects/idp/backstage/node_modules/@backstage/plugin-catalog-backend-module-msgraph/src/microsoftGraph/client.ts:281:5)
[1]     at transformUsers (/Users/xqe035/Documents/projects/idp/backstage/node_modules/@backstage/plugin-catalog-backend-module-msgraph/src/microsoftGraph/read.ts:449:20)
[1]     at readMicrosoftGraphUsers (/Users/xqe035/Documents/projects/idp/backstage/node_modules/@backstage/plugin-catalog-backend-module-msgraph/src/microsoftGraph/read.ts:70:12)
[1]     at readMicrosoftGraphOrg (/Users/xqe035/Documents/projects/idp/backstage/node_modules/@backstage/plugin-catalog-backend-module-msgraph/src/microsoftGraph/read.ts:406:40)
[1]     at MicrosoftGraphOrgEntityProvider.read (/Users/xqe035/Documents/projects/idp/backstage/node_modules/@backstage/plugin-catalog-backend-module-msgraph/src/processors/MicrosoftGraphOrgEntityProvider.ts:327:31)
[1]     at fn (/Users/xqe035/Documents/projects/idp/backstage/node_modules/@backstage/plugin-catalog-backend-module-msgraph/src/processors/MicrosoftGraphOrgEntityProvider.ts:375:13)
[1]     at TaskWorker.fn (/Users/xqe035/Documents/projects/idp/backstage/node_modules/@backstage/backend-defaults/src/entrypoints/scheduler/lib/PluginTaskSchedulerImpl.ts:137:9)
[1]     at TaskWorker.runOnce (/Users/xqe035/Documents/projects/idp/backstage/node_modules/@backstage/backend-defaults/src/entrypoints/scheduler/lib/TaskWorker.ts:156:13)
[1]     at <anonymous> (/Users/xqe035/Documents/projects/idp/backstage/node_modules/@backstage/backend-defaults/src/entrypoints/scheduler/lib/TaskWorker.ts:76:31)
```

### 👟 Reproduction steps

N/A

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by Ajay-Syamaladevi** [comment]
![Uploading Screenshot 2024-08-15 at 12.25.32 AM.png…]()

**Comment by Ajay-Syamaladevi** [comment]
While debugging through the source code, we found the catalog-backend-module-msgraph is trying to generate the token based on the .default scope for graph.microsoft.com and getting below error

`{"error":"invalid_resource","error_description":"AADSTS500011: The resource principal named https://graph.microsoft.com/.default was not found in the tenant named Capital One Financial Corporation. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You might have sent your authentication request to the wrong tenant. Trace ID: 90f585b1-102c-47e5-964e-8fc9ef11c500 Correlation ID: f56d68d9-9d9e-4888-b5a6-8cedcdb9c850 Timestamp: 2024-08-14 12:24:35Z","error_codes":[500011],"timestamp":"2024-08-14 12:24:35Z","trace_id":"90f585b1-102c-47e5-964e-8fc9ef11c500","correlation_id":"f56d68d9-9d9e-4888-b5a6-8cedcdb9c850","error_uri":"https://login.microsoftonline.com/error?code=500011"}`

As per this stackoverflow thread: https://stackoverflow.com/questions/63275210/what-is-the-default-scope-for-graph-microsoft-com, For v1.0 endpoints, there is generally no need to use the /.default scope,you need to add the /.default scope only when you use the v2.0 endpoint to get the token.

**Comment by Ajay-Syamaladevi** [comment]
While debugging through the source code, we found the catalog-backend-module-msgraph is trying to generate the token based on the .default scope for graph.microsoft.com and getting below error

Code: https://github.com/backstage/backstage/commit/2c234a893256470ff19b0ac81e9c3c61eb6c51b9#diff-13cabf1304bdc942510538b070cc09e2d2875f5f9923f21dcb5614515d6bfd17R223

{"error":"invalid_resource","error_description":"AADSTS500011: The resource principal named https://graph.microsoft.com/.default was not found in the tenant named Capital One Financial Corporation. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You might have sent your authentication request to the wrong tenant. Trace ID: 90f585b1-102c-47e5-964e-8fc9ef11c500 Correlation ID: f56d68d9-9d9e-4888-b5a6-8cedcdb9c850 Timestamp: 2024-08-14 12:24:35Z","error_codes":[500011],"timestamp":"2024-08-14 12:24:35Z","trace_id":"90f585b1-102c-47e5-964e-8fc9ef11c500","correlation_id":"f56d68d9-9d9e-4888-b5a6-8cedcdb9c850","error_uri":"https://login.microsoftonline.com/error?code=500011"}

As per this stackoverflow thread: https://stackoverflow.com/questions/63275210/what-is-the-default-scope-for-graph-microsoft-com, For v1.0 endpoints, there is generally no need to use the /.default scope,you need to add the /.default scope only when you use the v2.0 endpoint to get the token.

**Comment by Ajay-Syamaladevi** [comment]
While debugging through the source code, we found the catalog-backend-module-msgraph is trying to generate the token based on the .default scope for graph.microsoft.com and getting below error

Code: https://github.com/backstage/backstage/commit/2c234a893256470ff19b0ac81e9c3c61eb6c51b9#diff-13cabf1304bdc942510538b070cc09e2d2875f5f9923f21dcb5614515d6bfd17R223

curl --location 'https://login.microsoftonline.com/${AZURE_TENANT_ID}/oauth2/token' \
--data-urlencode 'grant_type=client_credentials' \
--data-urlencode 'client_id=${AZURE_CLIENT_ID}' \
--data-urlencode 'client_secret=${AZURE_CLIENT_SECRET}' \
--data-urlencode 'resource=https://graph.microsoft.com/.default'

{"error":"invalid_resource","error_description":"AADSTS500011: The resource principal named https://graph.microsoft.com/.default was not found in the tenant named Capital One Financial Corporation. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You might have sent your authentication request to the wrong tenant. Trace ID: 90f585b1-102c-47e5-964e-8fc9ef11c500 Correlation ID: f56d68d9-9d9e-4888-b5a6-8cedcdb9c850 Timestamp: 2024-08-14 12:24:35Z","error_codes":[500011],"timestamp":"2024-08-14 12:24:35Z","trace_id":"90f585b1-102c-47e5-964e-8fc9ef11c500","correlation_id":"f56d68d9-9d9e-4888-b5a6-8cedcdb9c850","error_uri":"[https://login.microsoftonline.com/error?code=500011"}](https://login.microsoftonline.com/error?code=500011%22%7D)

As per this stackoverflow thread: https://stackoverflow.com/questions/63275210/what-is-the-default-scope-for-graph-microsoft-com, For v1.0 endpoints, there is generally no need to use the /.default scope,you need to add the /.default scope only when you use the v2.0 endpoint to get the token.

**Comment by Ajay-Syamaladevi** [comment]
Also, the exception message is kind of misleading, as there is no network or connectivity issue.

We were able to establish the connectivity and tested using below CLI command.

curl --location 'https://login.microsoftonline.com/${AZURE_TENANT_ID}/oauth2/token' \
--data-urlencode 'grant_type=client_credentials' \
--data-urlencode 'client_id=${AZURE_CLIENT_ID}' \
--data-urlencode 'client_secret=${AZURE_CLIENT_SECRET}' \
--data-urlencode 'resource=https://graph.microsoft.com'

**Comment by camilaibs** [comment]
Do you have any thoughts @pjungermann and @Fox32 🙏🏻 ?

**Comment by pjungermann** [comment]
@drodil FYI as you were the last who modified the related code line (not adding the scope)

**Comment by drodil** [comment]
The modification I made was to allow a custom target to be used (for mocking in our case). We have quite a similar configuration for this and it works just fine with the 1.29.1 Backstage:

```yaml
  providers:
    microsoftGraphOrg:
      target: https://graph.microsoft.com/v1.0
      authority: https://login.microsoftonline.com
      tenantId: ${AUTH_MICROSOFT_TENANT_ID}
      clientId: ${AUTH_MICROSOFT_CLIENT_ID}
      clientSecret: ${AUTH_MICROSOFT_CLIENT_SECRET}
      queryMode: basic
```

I wonder if there's something wrong with your tenant?
