### ISSUE TITLE
🐛 Bug Report: net::ERR_SSL_PROTOCOL_ERROR

### ISSUE THREAD

**Issue by rakeshreddyrg09** [backstage/backstage#26048]
### 📜 Description

Hi Team,
I have deployed backstage on top my k8s cluster and I'm seeing this error,
![image](https://github.com/user-attachments/assets/c711e87c-717f-48e1-a386-fd8874970cdb)

can anyone help me here. Thank you.
app-config.yaml
```yaml
app:
  title: Scaffolded Backstage App
  baseUrl: http://backstage.org-sample.com

organization:
  name: org

backend:
  title: TEST_TITLE
  baseUrl: http://backstage.org-sample.com
  listen:
    port: 7007
  csp:
    connect-src: ["'self'", 'http:',]
  cors:
    origin: http://backstage.org-sample.com
    methods: [GET, HEAD, PATCH, POST, PUT, DELETE]
    credentials: true
  database:
    client: better-sqlite3
    connection: ':memory:'
integrations:
  github:
    - host: github.com
      token: ${GITHUB_TOKEN}
techdocs:
  builder: 'local'
  publisher:
    type: 'local'
  generator:
    runIn: local
auth:
  environment: development
  providers:
    gitlab:
      development:
        clientId: backstage
        clientSecret: my_token
        audience: code.org.com

scaffolder:
  defaultAuthor:
    name: M.C. Hammer # Defaults to `Scaffolder`
    email: hammer@donthurtem.com # Defaults to `scaffolder@backstage.io`
  defaultCommitMessage: "U can't touch this" # Defaults to 'Initial commit'

catalog:
  import:
    entityFilename: catalog-info.yaml
    pullRequestBranchName: backstage-integration
  rules:
    - allow: [Component, System, API, Resource, Location]
  locations:
    # Local example data, file locations are relative to the backend process, typically `packages/backend`
    - type: file
      target: ../../examples/entities.yaml

    # Local example template
    - type: file
      target: ../../examples/template/template.yaml
      rules:
        - allow: [Template]

    # Local example organizational data
    - type: file
      target: ../../examples/org.yaml
      rules:
        - allow: [User, Group]
```
app-config.production.yaml
```yaml
app:
  baseUrl: http://backstage.org-sample.com

backend:
  baseUrl: http://backstage.org-sample.com
  listen: ':7007'
  csp:
    connect-src: ["'self'", 'http:', 'https:']
  database:
    client: pg
    connection:
      host: backstage-instance-admin-primary.backstage.svc
      port: 5432
      user: backstage-user
      password: 1TZ_nd{AQRA2b7w?ch(Rw5U=

auth:  
  environment: development
  providers:
    gitlab:
      development:
        clientId: backstage
        clientSecret: my_token
        audience: code.org.com

catalog:
  locations: []
```

I built the docker image out it and used in helm chart https://github.com/backstage/charts/blob/main/charts/backstage/values.yaml
and deployed the helm chart

### 👍 Expected behavior

I should be able to access the dashboard.

### 👎 Actual Behavior with Screenshots

NA

### 👟 Reproduction steps

NA

### 🖥️ Your Environment

k3d cluster
k8s deployment

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by camilaibs** [comment]
Hi @rakeshreddyrg09 👋🏻 , thanks for opening this issue.
Is your deployment behind a proxy? Could you update your app and backend "baseUrl" configs to the URL you see in the browser error message and let us know if it helps?

**Comment by rakeshreddyrg09** [comment]
Hi @camilaibs, thank you for the response.
I have deployed the same config in aws EKS cluster its started working.
but I see below error can you help me out
![image](https://github.com/user-attachments/assets/14b979f9-5db9-4022-9ac0-2f292512d3df)

**Comment by rakeshreddyrg09** [comment]
here is my values.yaml for backstage helm chart 
```yaml
ingress:
  enabled: true
  className: "prod-kong-ingress"
  host: "backstage.org.test.cloud"
backstage:
  # -- Number of deployment replicas
  replicas: 1
  revisionHistoryLimit: 10

  image:
    # -- Backstage image registry
    registry: cr.org.test.com

    # -- Backstage image repository
    repository: /backstage
    tag: 0.1.7
    pullPolicy: Always
    pullSecrets:
      - my-docker-secret
  appConfig:
    app:
      title: Scaffolded Backstage App
      baseUrl: https://backstage.org.test.cloud
      experimental:
        packages: all

    organization:
      name: test

    backend:
      baseUrl: https://backstage.org.test.cloud
      listen:
        port: 7007
      csp:
        connect-src: ["'self'", 'http:', 'https:']
      cors:
        origin: https://backstage.org.test.cloud
        methods: [GET, HEAD, PATCH, POST, PUT, DELETE]
        credentials: false
    integrations:
      github:
        - host: github.com
          token: github_pat
    techdocs:
      builder: 'local' # Alternatives - 'external'
      generator:
        runIn: 'docker'
      publisher:
        type: 'local'
    kubernetes:
      serviceLocatorMethod:
        type: 'multiTenant'
      clusterLocatorMethods:
        - type: 'config'
          clusters: []
    auth:
        environment: development
        github:
            development:
              clientId: test
              clientSecret: test
              callbackUrl: https://backstage.org.test.cloud/api/auth/github/handler/frame
    catalog:
      import:
        entityFilename: catalog-info.yaml
        pullRequestBranchName: backstage-integration
      rules:
        - allow: [Component, System, API, Resource, Location, Domain]
      providers:
        backstageOpenapi:
          plugins:
            - catalog
            - search
      locations:
        # Local example data, file locations are relative to the backend process, typically `packages/backend`
        - type: file
          target: catalog-info.yaml
```
