### ISSUE TITLE
💬 RFC: allow fetch template scaffolder action to refer to directory outside of parent

### ISSUE THREAD

**Issue by stephenglass** [backstage/backstage#26086]
### 🔖 Need

We are creating some templates that have common functionality. For example, creating a `CODEOWNERS` file would be common for any template creating a GitHub repository. I want to have a file structure like this:

```
/templates
  common
    .github
      - CODEOWNERS
  nodejs
    - template.yaml
```

Then in `nodejs/template.yaml` I can have the steps:
```yaml
- id: fetch-common
  name: Fetch Common
  action: fetch:template
  input:
    url: ../common # or '/templates/common'

- id: fetch-base
  name: Fetch Base
  action: fetch:template
  input:
    url: <github url to template content>
```

Currently this would give an error: `NotAllowedError: Relative path is not allowed to refer to a directory outside its parent`.  This proposal can give developers more flexibility in how they structure software templates and reduce duplications.

### 🎉 Proposal

Add config options:

```yaml
scaffolder:
  dangerouslyAllowRelativePath:
    - entityRef: template:default/create-react-app-template
      path: /template/common
```

In the `template:fetch` action it will check if combination of `ctx.templateInfo.entityRef` and `url` exists in the config.  If it exists, bypass `paths::resolveSafeChildPath` and call `path::resolve` directly. This can be safely enabled in the case where it's guaranteed the `url` path is constant i.e. not modifiable by user or from untrusted remote source. 

### 〽️ Alternatives

Alternative is duplicating common functionality in software template. You could also create a common repository to put these files but this wouldn't play nice with stuff like `CODEOWNERS`. I also prefer to keep some of this code tied to the main repository.

### ❌ Risks

Setting `dangerouslyAllowRelativePath` option and allowing user input to `fetch:template` url input could open up to security issue. However, this risk is partially mitigated by the naming convention of the option. Developers whom ignore this proceed at their own risk.

### 👀 Have you spent some time to check if this RFC has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)
