### ISSUE TITLE
🐛 Bug Report: ui:field RepoUrlPicker ui:options requestUserCredentials | Github Auth

### ISSUE THREAD

**Issue by ESmithaaS** [backstage/backstage#26083]
### 📜 Description

When using the ui:options of "[requestUserCredential](https://backstage.io/docs/features/software-templates/ui-options-examples/#requestusercredentials)" and parameter of additionalScopes, the token that is generated does not contain the additionalScopes

```
properties:
      repoUrl:
        ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com
            allowedOwners:
              - <org>
            requestUserCredentials:
              secretsKey: USER_OAUTH_TOKEN
              additionalScopes:
                github:
                  - repo:status
                  - repo_deployment
                  - public_repo
                  - repo:invite
                  - security_events
 ```

### 👍 Expected behavior

The token that is generated when the user is authenticated should contain the scopes that were in the additionalScope parameter.

### 👎 Actual Behavior with Screenshots

The token is generated, but no additional scopes are added to the x-oauth-scopes

### 👟 Reproduction steps

I use a custom action that takes a token input. 
In the template that uses this custom action, I use the RepoUrlPicker to request the credentials. 
For debugging purposes, I have the custom action log the token that is passed to it. Once I have grabbed the token from the logs, I then use a curl command to get the header info. The "x-oauth-scopes" are empty for the token that is generated.
If compared to a known working token, I see the scopes present.

#### curl command: 
```code 
curl -H "Authorization: Bearer <OAUTH_TOKEN>" https://api.github.com/users/codertocat -I
```

#### Example Token Output:
![image](https://github.com/user-attachments/assets/e971a4e1-aeca-40d4-9634-822de2381ba5)

### 📃 Provide the context for the Bug.

I'm using a custom action to add a GitHub repository to a GitHub App installation. The token used for the API call is required to have the "repo" scope.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None
