### ISSUE TITLE
💬 RFC: Domain should be generic and not system-related only.

### ISSUE THREAD

**Issue by rafaels88** [backstage/backstage#26105]
### 🔖 Need

I am working with a monolith system that divides itself into different bounded contexts - in practice they are one or a group of big encapsulated modules whereby other parts of the system can interact with. This means there is pretty much one system with multiple bounded contexts inside - almost as a monorepo arch. The organization goes like this: a bounded-context module is owned by one or multiple teams; a bounded context exists within a system; a bounded context is a definition that has one or multiple components.

The issue is basically assuming that a system belongs to one domain, and not something smaller. So, the need here is to allow a domain having a system but also a component.

### 🎉 Proposal

Being able to define a component like:

```yaml
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: MyComponentName
spec:
  type: service
  lifecycle: production
  owner: team
  system: system-name
  domain: domain-name
```

### 👀 Have you spent some time to check if this RFC has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)
