### ISSUE TITLE
🐛 Bug Report: scaffolder secrets `required` property doesn't work in nested objects

### ISSUE THREAD

**Issue by stephenglass** [backstage/backstage#26156]
### 📜 Description

A secret field that's in a nested object doesn't correctly set the `required` property.

### 👍 Expected behavior

Secret fields should be allowed to set as `required` even if they are in an object just like any other field type like a string.

### 👎 Actual Behavior with Screenshots

This schema has two secret fields `foo` and `bar` in an object `nest` which lists them as required properties.

```yaml
  parameters:
    - title: Choose a location
      required:
        - hello
      properties:
        hello:
          title: hello
          type: string
        nest:
          title: Nest
          type: object
          required:
            - foo
            - bar
          properties:
            foo:
              title: Test 1
              type: string
              ui:field: Secret
            bar:
              title: Test 2
              type: string
              ui:field: Secret
```

The secret fields are not a required property as they should be. You can proceed in the template without filling them out.

<img width="498" alt="image" src="https://github.com/user-attachments/assets/1693a104-890b-4220-913f-e1e8ad10edf8">

### 👟 Reproduction steps

Use schema properties above and view in the template UI.

### 📃 Provide the context for the Bug.

We use objects in our templates to better organize data. We cannot have secret fields in any of these objects. For example:

Artifactory -> Docker
Artifactory -> Maven

### 🖥️ Your Environment

v1.30.0

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!
