### ISSUE TITLE
[Plugin] Jira plugin 

### ISSUE THREAD

**Issue by Niraj-Fonseka** [backstage/backstage#2622]
## Summary

A plugin to visualize Jira data such as tickets open, closed , blocked , sprint progress etc 

## Project website 

https://www.atlassian.com/software/jira

## Context

Giving teams the visibility into how they are performing when it comes to feature delivery and tying that in with any service data can be pretty valuable.

**Comment by Niraj-Fonseka** [comment]
I'm happy to work on this and happy to work with anyone else if they are interested

**Comment by stefanalund** [comment]
Nice! I’ve assigned you. Looking forward to seeing this!

**Comment by adamdmharvey** [comment]
As feedback into this, a few ideas:

* the most simple alignment between the plugin and a component, being an annotation to align them to a single project, i.e.,
  ```yaml
  annotations:
    jira/projectKey: MYPROJ
  ```
* we have some squads who use a single Jira project for all of their work, but also some who manage multiple products and use components _per product_.  Ideally, if we were to add annotations into a `catalog-info.yaml`, it would be great to both identify a Jira projectKey, but potentially also identify a component?
  ```yaml
  annotations:
    jira/projectKey: MYPROJ
    jira/component: "Product X"
  ```
* a sprint health dashboard similar to the built in Jira Dashboard system would be ideal!
  ![image](https://user-images.githubusercontent.com/33203301/97474574-9f78ab00-1922-11eb-9334-6d7149200dc3.png)
* support for dedicated Atlassian Jira Data Center separate for Atlassian Jira Cloud (the SaaS solution), much in the same way as some of the plugins support GitHub.com vs. GitHub Enterprise with custom URLs
  ```yaml
  integrations:
    jira:
      host: jira.mycompany.com
      OAuth-Pem: keyname.pem
  ```
