### ISSUE TITLE
🐛 Bug Report: Impossible to list users from gitlab.com for public groups (not linked to a paid organization)

### ISSUE THREAD

**Issue by yodamad** [backstage/backstage#26438]
### 📜 Description

Trying to use gitlab.com as authentication provider for my backstage instance, it doesn't list users because they are not `using a seat`, which is a behavior link to license on GitLab.

Here i want to use public groups to authenticate users, but they keep beeing filtered.

This is due to this filter : https://github.com/backstage/backstage/blob/3c587ef7898bf7b584dc218419d2468b472e4e12/plugins/catalog-backend-module-gitlab/src/lib/client.ts#L143

This `show_seat_info` filter should optional in my opinion

### 👍 Expected behavior

Users in the groups are correctly listed and created into db

### 👎 Actual Behavior with Screenshots

Users are not processed at all

```bash
{"class":"GitlabOrgDiscoveryEntityProvider","level":"info","message":"Scanned 0 users and processed 0 users","plugin":"catalog","service":"backstage","target":"GitlabOrgDiscoveryEntityProvider:yourProviderId","taskId":"GitlabOrgDiscoveryEntityProvider:yourProviderId:refresh","taskInstanceId":"5c0ae6c3-6ea8-4f52-bfd1-8a2eb51d3725"}
```

### 👟 Reproduction steps

Configure gitlab as provider in your app (here is the relevant info only)

```yaml
integrations:
  gitlab:
    - host: gitlab.com
      token: <TOKEN>

auth:
  environment: local
  # see https://backstage.io/docs/auth/ to learn about auth providers
  providers:
    # See https://backstage.io/docs/auth/guest/provider
    gitlab:
      local:
        clientId: <ID>
        clientSecret: <SECRET>
        signIn:
          resolvers:
            - resolver: emailMatchingUserEntityProfileEmail
            - resolver: usernameMatchingUserEntityName

catalog:
  providers:
    gitlab:
      yourProviderId:
        host: gitlab.com
        orgEnabled: true
        group: <GROUP_PATH>
        allowInherited: true
        groupPattern: '[\s\S]*'
        schedule: # Same options as in SchedulerServiceTaskScheduleDefinition. Optional for the Legacy Backend System.
          # supports cron, ISO duration, "human duration" as used in code
          frequency: { minutes: 3 }
          # supports ISO duration, "human duration" as used in code
          timeout: { minutes: 3 }
```

### 🖥️ Your Environment

MacOS 14
Running backstage on Docker

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None
