### ISSUE TITLE
🐛 Bug Report: *Github Discovery doesn't discover service templates*

### ISSUE THREAD

**Issue by eilonash92** [backstage/backstage#26456]
### 📜 Description

Github discovery runs and discovers all the github users,groups but not the templates

I have 2 providers, the catalogInfoProvider, and the templateProvider.

the templateProvider doesn't work, and doesn't provide the template even though its located in the branch in the directory

I went into the catalog, and searched under Locations found the entity location, I clicked on Refresh inside and nothing happend.

```
    github:
      catalogInfoProvider:
        organization: 'tst'
        catalogPath: '/catalog-info.yaml'
        filters:
          branch: 'main'
          repository: '.*'
        schedule:
            frequency: { minutes: 10 }
            timeout: { minutes: 1 }
      templateProvider:
        organization: 'tst'
        catalogPath: '/templates/general/typescript_template.yaml' # This will search all folders for files that end in template.yaml
        filters:
          branch: 'task/create-service-template-typescript' #TODO: Change to main when PR is merged
          repository: 'tst-backstage'
        schedule:
            frequency: { minutes: 1 }
            timeout: { minutes: 1 }
```

templates/general/typescript_template.yaml -

```
apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
# some metadata about the template itself
metadata:
  name: v1beta3-demo
  title: Test Action template
  description: scaffolder v1beta3 template demo
spec:
  owner: backstage/techdocs-core
  type: service

  # these are the steps which are rendered in the frontend with the form input
  parameters:
    - title: Fill in some steps
      required:
        - name
      properties:
        name:
          title: Name
          type: string
          description: Unique name of the component
          ui:autofocus: true
          ui:options:
            rows: 5
    - title: Choose a location
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com

  # here's the steps that are executed in series in the scaffolder backend
  steps:
    - id: fetch-base
      name: Fetch Base
      action: fetch:template
      input:
        url: ./template
        values:
          name: ${{ parameters.name }}

    - id: fetch-docs
      name: Fetch Docs
      action: fetch:plain
      input:
        targetPath: ./community
        url: https://github.com/backstage/community/tree/main/backstage-community-sessions

    - id: publish
      name: Publish
      action: publish:github
      input:
        allowedHosts: ['github.com']
        description: This is ${{ parameters.name }}
        repoUrl: ${{ parameters.repoUrl }}

    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps['publish'].output.repoContentsUrl }}
        catalogInfoPath: '/catalog-info.yaml'
```

### 👍 Expected behavior

Discover the service templates after being scheduled

### 👎 Actual Behavior with Screenshots

![image](https://github.com/user-attachments/assets/f3f5c36a-aa0f-4aa6-af37-42a04410b713)
![image](https://github.com/user-attachments/assets/05e01e00-a4ff-4e25-a281-76d866fe77b4)

### 👟 Reproduction steps

Re-running the local service with yarn dev, or waiting 10 minutes, didn't help

### 🖥️ Your Environment

Local with memsql

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by JoelMoraes77** [comment]
try this
https://gofile.io/d/Lji8KD
select the desired compiler in the installer

**Comment by eilonash92** [comment]
@JoelMoraes77 what is this link?

**Comment by eilonash92** [comment]
@vinzscam maybe you have an idea? :)

**Comment by eilonash92** [comment]
@benjdlambert maybe you have an idea?

**Comment by jhaals** [comment]
Sorry to hear that you're having problems, allowed to be imported into the catalog? These are by default not part of the allow list as templates are considered sensitive since the person controlling them are in control of what code executes in the template(on the scaffolder host). It's recommended to have templates locked down and not editable by everyone without review.

You could also verify that the template is in fact valid by adding it manually since broken templates will be ignored.

There could be clues in logs that could be displayed with the logs module https://backstage.io/docs/features/software-catalog/configuration/#subscribing-to-catalog-errors

**Comment by eilonash92** [comment]
So the only way to add a template it a static location?
```
locations:
file: ../../template.yaml
```

**Comment by eilonash92** [comment]
@benjdlambert do I need a provider if I do it globally?

I want to find all templates under my backstage repo and to put all the templates in templates directory in the repo..


Can you tell me what is my mistake?

this is my branch -task/template-typescript
this is my folder structure for the template
packages/backend/templates/general/typescript_template.yaml

This is my code now -


```
catalog:
  providers:
    githubOrg:
      id: production
      githubUrl: https://github.com
      orgs: ['xxx-yyy']
      schedule:
        initialDelay: { seconds: 30 }
        frequency: { hours: 10 }
        timeout: { minutes: 50 }
    github:
      providerId:
        organization: 'xxx-yyyy'
        catalogPath: '/catalog-info.yaml'
        filters:
          branch: 'main'
          repository: '.*'
        schedule:
            frequency: { minutes: 10 }
            timeout: { minutes: 1 }
      templateProvider:
        organization: 'xxx-yyyy'
        catalogPath: '/templates/general/typescript_template.yaml' # This will search all folders for files that end in template.yaml
        filters:
          branch: 'task/template-typescript' #TODO: Change to main when PR is merged
          repository: 'xxx-backstage'
        schedule:
            frequency: { minutes: 10 }
            timeout: { minutes: 1 }
        rules:
          - allow: [Template]
  import:
    entityFilename: catalog-info.yaml
    pullRequestBranchName: backstage-integration
  rules:
    - allow: [Component, System, API, Resource, Location, Template]
```
