### ISSUE TITLE
🐛 Bug Report: scaffolder `ui:backstage` options can't be used for fields in `dependencies`

### ISSUE THREAD

**Issue by stephenglass** [backstage/backstage#26508]
### 📜 Description

The `ui:backstage` options have no effect when used in fields in a `dependencies` block.

Example template. The `ui:backstage.review.show` option has no effect.

```yaml
    - title: Configuration
      dependencies:
        projectType:
          oneOf:
            - properties:
                projectType:
                  enum:
                    - Java / Maven
                artifactId:
                  type: string
                  title: Artifact ID
                  description: The artifact ID for your Java/Maven project.
                  ui:backstage:
                    review:
                      show: false
            - properties:
                projectType:
                  enum:
                    - Node.js / Npm
```

### 👍 Expected behavior

The `ui:backstage` options should work the same for fields whether or not they are part of a dependency.

### 👎 Actual Behavior with Screenshots

The `ui:backstage` options have no effect

### 👟 Reproduction steps

Create a template using a field dependency (use  the example from above) and observe the `ui:backstage` options have no effect.

### 🖥️ Your Environment

Backstage v1.30.4

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!
