### ISSUE TITLE
🐛 Bug Report: Github event on delete won't generate the right location for deletion

### ISSUE THREAD

**Issue by jaysonsantos** [backstage/backstage#26528]
### 📜 Description

When a new project is registered by the scaffolder a subsequent delete event won't delete the resources registered.

### 👍 Expected behavior

The location should be deleted, and the orphan cleanup should kick in.

### 👎 Actual Behavior with Screenshots

On the log it says that 0 entities were removed
```
backstage-7c7d5f4677-bqnv5 backstage-production {"level":"debug","message":"Received event for topic github.repository","plugin":"catalog","service":"backstage","span_id":"4e117962f485e043","target":"github-provider:audibene","trace_flags":"01","trace_id":"adff3f5641efa8dff5dac519e0dbf89e"}
backstage-7c7d5f4677-bqnv5 backstage-production {"level":"debug","message":"removed, 0 entities: [\"location:default/generated-4e435bcea65ba7568ff7590efc06f2a6cfc44af4\"]","plugin":"catalog","service":"backstage","span_id":"4e117962f485e043","trace_flags":"01","trace_id":"adff3f5641efa8dff5dac519e0dbf89e"}
backstage-7c7d5f4677-bqnv5 backstage-production {"level":"debug","message":"Removed entities for deleted repository platform.test-backstage","plugin":"catalog","service":"backstage","span_id":"4e117962f485e043","target":"github-provider:audibene","trace_flags":"01","trace_id":"adff3f5641efa8dff5dac519e0dbf89e"}
backstage-7c7d5f4677-bqnv5 backstage-production {"level":"info","message":"[06/Sep/2024:09:13:49 +0000] \"POST /api/events/http/github.repository HTTP/1.1\" 202 21 \"-\" \"GitHub-Hookshot/1a50080\"","service":"rootHttpRouter","span_id":"4e117962f485e043","trace_flags":"01","trace_id":"adff3f5641efa8dff5dac519e0dbf89e","type":"incomingRequest"}
```

### 👟 Reproduction steps

Register a project with the scaffolder using this config:

```yaml
- id: publish
  name: Create Github repository
  action: publish:github
  input:
    allowedHosts: ['github.com']
    description: This is ${{ parameters.projectName }}
    repoUrl: ${{ parameters.repoUrl }}
    defaultBranch: 'develop'
    repoVisibility: 'private'
- id: register
  name: Register app on backstage's catalog
  action: catalog:register
  input:
    repoContentsUrl: ${{ steps.publish.output.repoContentsUrl }}
    catalogInfoPath: '/catalog-info.yaml'
```

then on github side (assuming webhook is already configured) trigger a deletion

### 📃 Provide the context for the Bug.

It seems that the code generate a location with the `blob` url https://github.com/Bonial-International-GmbH/backstage/blob/9112efc364d24f134881e9c09db1323fdfcc4165/plugins/catalog-backend-module-github/src/providers/GithubEntityProvider.ts#L284 but the location created by the scaffolder, uses the `tree` url https://github.com/Audibene-GMBH/platform.test-backstage/tree/develop/catalog-info.yaml
should the location method return a list with both urls or should tree always be used?

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!
