### ISSUE TITLE
🐛 Bug Report: Backstage Catalog – Groups – backstage is able to identify only child groups of gitlab, parent groups it’s not identifying

### ISSUE THREAD

**Issue by vinaykv23** [backstage/backstage#26554]
### 📜 Description

•	Backstage  - "version": "1.28.0" 
•	@backstage/plugin-catalog-backend-module-gitlab - "^0.3.20" 
•	@backstage/plugin-catalog-backend-module-gitlab-org - "^0.0.4" 

### 👍 Expected behavior

Backstage Catalog should identify/discover parent groups in gitlab

### 👎 Actual Behavior with Screenshots

Backstage Catalog is not identify/discover parent groups in gitlab

### 👟 Reproduction steps

Gitlab groups setup

"W1SC Platform" is parent group

![image](https://github.com/user-attachments/assets/62f36ed8-d609-415b-b9be-cb1bc45775ac)

"backstage-poc" is parent group

![image](https://github.com/user-attachments/assets/0813b303-f255-4442-b9a3-d20d8d86d67e)

Child Groups under "W1SC Platform"  we are able to see in backstage

![image](https://github.com/user-attachments/assets/ce548c8b-e635-43c7-9736-91d94af8b2ce)

![image](https://github.com/user-attachments/assets/4efd133b-a558-454a-9cee-a33bd9b6bfeb)

Parent group "W1SC Platform" its not listing

![image](https://github.com/user-attachments/assets/16492e59-4ff2-457a-b1b6-d1c4ffdd3bd5)

Parent group "backstage-poc" its not listing

![image](https://github.com/user-attachments/assets/b6f8e8cb-b493-4be8-bbd6-44bdff7b02e6)

For logged in user also its not able to assign the parent groups, for my user I have access to parent group

![image](https://github.com/user-attachments/assets/33873804-0610-4c3f-917c-e9b7ebd59324)

Below is the app-config.yaml

```yaml
integrations:
  gitlab:
    - host: gitlab.corp.org.com
      apiBaseUrl: https://gitlab.corp.org.com/api/v4
      token: ${GITLAB_TOKEN}
 
catalog:
  providers:
    gitlab:
      org-platform:
        host: gitlab.corp.org.com
        # branch: main # Optional. Used to discover on a specific branch
        # fallbackBranch: master
        allowInherited: true # Allow groups to be ingested even if there are no direct members.
        schedule: # Same options as in TaskScheduleDefinition. Optional for the Legacy Backend System.
          # supports cron, ISO duration, "human duration" as used in code
          frequency: { minutes: 30 }
          # supports ISO duration, "human duration" as used in code
          timeout: { minutes: 10 }
```

### 📃 Provide the context for the Bug.

Below is the app-config.yaml

```yaml
integrations:
  gitlab:
    - host: gitlab.corp.org.com
      apiBaseUrl: https://gitlab.corp.org.com/api/v4
      token: ${GITLAB_TOKEN}
 
catalog:
  providers:
    gitlab:
      org-platform:
        host: gitlab.corp.org.com
        # branch: main # Optional. Used to discover on a specific branch
        # fallbackBranch: master
        allowInherited: true # Allow groups to be ingested even if there are no direct members.
        schedule: # Same options as in TaskScheduleDefinition. Optional for the Legacy Backend System.
          # supports cron, ISO duration, "human duration" as used in code
          frequency: { minutes: 30 }
          # supports ISO duration, "human duration" as used in code
          timeout: { minutes: 10 }
```

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by hghtwr** [comment]
@vinaykv23 Can you doublecheck the app-config.yaml, I can see that there is no ```orgEnabled``` set? 
I might be completly wrong but I think the condition would prevent the ingestion of groups if not set: 

https://github.com/backstage/backstage/blob/fc24d9ebf042859ec437fd654f4d91ddb915e59b/plugins/catalog-backend-module-gitlab/src/providers/GitlabOrgDiscoveryEntityProvider.ts#L138

You can also search for "Org not enabled" in your logs to verify this.

This seems to be the app-config.yaml provided by you: 
```yaml
integrations:
gitlab:
- host: gitlab.corp.org.com
apiBaseUrl: https://gitlab.corp.org.com/api/v4
token: ${GITLAB_TOKEN}

catalog:
  providers:
    gitlab:
      org-platform:
        host: gitlab.corp.org.com
        # branch: main # Optional. Used to discover on a specific branch
        # fallbackBranch: master
        allowInherited: true # Allow groups to be ingested even if there are no direct members.
        schedule: # Same options as in TaskScheduleDefinition. Optional for the Legacy Backend System.
        # supports cron, ISO duration, "human duration" as used in code
        frequency: { minutes: 30 }
        # supports ISO duration, "human duration" as used in code
        timeout: { minutes: 10 }
```

Just let me know, I'm happy to check it further, then.

**Comment by vinaykv23** [comment]
hi @hghtwr 
I have tried by setting orgEnabled = true and group: xxx-platform where "xxx-platform" is parent group
its not finding parent group

**Comment by hghtwr** [comment]
This behavior is baked into this line

https://github.com/backstage/backstage/blob/35e0c680f19b302cb09c527837ab7af92c6f0571/plugins/catalog-backend-module-gitlab/src/providers/GitlabOrgDiscoveryEntityProvider.ts#L773

Generally, I did a quick test and it can be extended like this to also fetch the top-level-group.
```typescript
  shouldProcessGroup(group) {
    return this.config.groupPattern.test(group.full_path) && (!this.config.group || group.full_path.startsWith(`${this.config.group}/`) || group.full_path === this.config.group);
  }
```

@jhaals  I think the overall implementation could be improved. For self-hosted instances, the Provider fetches **all** groups of the instance and then interpretes if they should be processed. This only makes sense if ```config.group``` is not defined. But currently it always is applied for self-hosted, as long as `restrictUsersToGroups=false`. 

This leads to this situation where we fetch >7000 groups from the Gitlab API just to skip 99% of them: 
```
[1] 2024-09-12T06:19:55.101Z catalog info Scanned 7379 groups and processed 23 groups target=GitlabOrgDiscoveryEntityProvider:dot class=GitlabOrgDiscoveryEntityProvider taskId=GitlabOrgDiscoveryEntityProvider:dot:refresh taskInstanceId=73dde631-bd90-4a44-9cd9-9e56e295a6f9
```

So I can propose the following: 

1. ```selfHosted == true && this.config.orgEnabled && this.config.group``` --> Use ```listDescendantGroups``` instead of getting all groups. If `this.config.group` is `false`, we stick to the implementation that calls all groups of the instance.
2. Extend the filter for `shouldProcessGroup` with a condition ```group.full_path === this.config.group```

This should cover the problem in this issue and improve performance for larger instances.

**Comment by hghtwr** [comment]
Thx for that hint. I think it should be fine/compatible but we need to double-check if the all the groups have the correct relations set.

**Comment by vinaykv23** [comment]
Hi @hghtwr 
Please let me know if any updates

**Comment by vinaykv23** [comment]
hi @hghtwr @Rugvip 
any updates on this issue

**Comment by camilaibs** [comment]
Hi @hghtwr, would you be able to raise a pull request to help us fix this? It would be greatly appreciated if you find that time 🙏🏻 .

**Comment by hghtwr** [comment]
@vinaykv23 @camilaibs 

Hi, Im still having it in mind, I was just travelling alot and had other deadlines to meet. 

I would expect to focus on this again from beginning of November on.

**Comment by vinaykv23** [comment]
Hi @hghtwr below is one additional example of issue

https://gitlab.corp.org.com/org/architecture/internal-developer-platform
https://gitlab.corp.org.com/org-platform/reference_app

Below are the groups in the above gitlab link
org
architecture
internal-developer-platform
---
org-platform
reference_app

Backstage is only displaying below groups
architecture
reference_app

**Comment by rakeshreddyrg09** [comment]
can you help me out.!

here is my configuration.
```yaml
integrations:
  gitlab:
    - host: code.org.com
      apiBaseUrl: https://code.org.com/api/v4
      token: ${GITLAB_TOKEN}
```
```yaml      
catalog:
 providers:
   gitlab:
     org:
       host: code.org.com
       orgEnabled: true
       group: backstage-org
       groupPattern: '[\s\S]*'
       schedule: 
         frequency: { minutes: 30 }
         timeout: { minutes: 3 }
``` 
below is my pod logs
image
![image](https://github.com/user-attachments/assets/0316e49a-5272-4283-abf9-dff57e009aca)


under kind: Group or kind: User
I'm not able to see any group or any users

can you guide please.
