### ISSUE TITLE
🐛 Bug Report: (Scaffolder React) Enum Values and Structure Issues in `ReviewState` after Upgrading to v1.30.4

### ISSUE THREAD

**Issue by elaine-mattos** [backstage/backstage#26736]
### 📜 Description

Hi there,

After upgrading to Backstage v1.30.4, we noticed that the ReviewState now shows enum keys instead of enum values. Additionally, some structures have been flattened unexpectedly.

I have checked the code and as far as I understood there are 2 issues:
- Premature Exit in Schema Processing:
   The code iterates through `prop.schemas` (template steps) and calls `processSchema` within a loop. It exits after processing the first schema, not processing all template steps.
https://github.com/backstage/backstage/blob/v1.30.4/plugins/scaffolder-react/src/next/components/ReviewState/ReviewState.tsx#L89

- Always Defined definitionInSchema:
The `getSchema` method is using the `formState` as a fallback. In the end, even if the `processSchema` does loop through every template step, the reviewData gets re-written with the values from the `formState`, disregarding the enums.
https://github.com/backstage/backstage/blob/v1.30.4/plugins/scaffolder-react/src/next/components/ReviewState/ReviewState.tsx#L41

### 👍 Expected behavior

- Enum values should be displayed in the ReviewState, not their keys.
- Objects should not be flattened (or maybe shown with dot notation?)

<img width="814" alt="image" src="https://github.com/user-attachments/assets/b0509ad3-fc00-4aef-a40f-6c2bfd675341">

### 👎 Actual Behavior with Screenshots

<img width="832" alt="image" src="https://github.com/user-attachments/assets/d4b50eff-2fa8-48d3-a362-dde769001027">

### 👟 Reproduction steps

Write a template with enums and any object like anyOf, oneOf:
```yaml
- title: Define properties
  required:
    - displayName
    - license
  properties:
    displayName:
      title: Display Name
      type: string
      ui:help: Readable Name
    license:
      title: License
      type: string
      default: MIT
      enum:
        - MIT
        - Apache-2.0
        - GPL-3.0
      enumNames:
        - MIT License
        - Apache License 2.0
        - GNU General Public License v3.0
 - title: Add README.md
      properties:
        addReadme:
          title: Add README.md
          type: boolean
          default: true
          ui:help: Add a README.md file with some basic starting information
      dependencies:
        addReadme:
          allOf:
            - if:
                properties:
                  addReadme:
                    const: true
              then:
                required:
                  - readme
                properties:
                  readme:
                    type: object
                    title: Add README.md
                    required:
                      - description
                    properties:
                      description:
                        title: Description
                        type: string
                        ui:widget: textarea
                        ui:options:
                          rows: 10
                        ui:help: Explain the usage and content of the repository
                        default: |
                          This repository helps you to ...
``` 
Then check the review page.

### 🖥️ Your Environment

```bash
OS:   Darwin 23.6.0 - darwin/arm64
node: v18.19.1
yarn: 4.2.2
cli:  0.27.0 (installed)
backstage:  1.30.4

Dependencies:
  @backstage/app-defaults                                          1.5.10
  @backstage/backend-app-api                                       0.9.3
  @backstage/backend-common                                        0.23.3, 0.24.1
  @backstage/backend-defaults                                      0.4.4
  @backstage/backend-dev-utils                                     0.1.5
  @backstage/backend-openapi-utils                                 0.1.17
  @backstage/backend-plugin-api                                    0.7.0, 0.8.1
  @backstage/backend-tasks                                         0.6.1
  @backstage/backend-test-utils                                    0.5.1
  @backstage/catalog-client                                        1.6.6
  @backstage/catalog-model                                         1.6.0
  @backstage/cli-common                                            0.1.14
  @backstage/cli-node                                              0.2.7
  @backstage/cli                                                   0.27.0
  @backstage/config-loader                                         1.9.0
  @backstage/config                                                1.2.0
  @backstage/core-app-api                                          1.14.2
  @backstage/core-compat-api                                       0.2.8
  @backstage/core-components                                       0.14.10
  @backstage/core-plugin-api                                       1.9.3
  @backstage/dev-utils                                             1.0.37
  @backstage/errors                                                1.2.4
  @backstage/eslint-plugin                                         0.1.8
  @backstage/frontend-plugin-api                                   0.7.0
  @backstage/integration-aws-node                                  0.1.12
  @backstage/integration-react                                     1.1.30
  @backstage/integration                                           1.14.0
  @backstage/plugin-api-docs                                       0.11.8
  @backstage/plugin-app-backend                                    0.3.73
  @backstage/plugin-app-node                                       0.1.24
  @backstage/plugin-auth-backend-module-atlassian-provider         0.2.5
  @backstage/plugin-auth-backend-module-aws-alb-provider           0.1.17
  @backstage/plugin-auth-backend-module-azure-easyauth-provider    0.1.7
  @backstage/plugin-auth-backend-module-bitbucket-provider         0.1.7
  @backstage/plugin-auth-backend-module-cloudflare-access-provider 0.2.1
  @backstage/plugin-auth-backend-module-gcp-iap-provider           0.2.19
  @backstage/plugin-auth-backend-module-github-provider            0.1.21
  @backstage/plugin-auth-backend-module-gitlab-provider            0.1.21
  @backstage/plugin-auth-backend-module-google-provider            0.1.21
  @backstage/plugin-auth-backend-module-microsoft-provider         0.1.19
  @backstage/plugin-auth-backend-module-oauth2-provider            0.2.5
  @backstage/plugin-auth-backend-module-oauth2-proxy-provider      0.1.17
  @backstage/plugin-auth-backend-module-oidc-provider              0.2.6
  @backstage/plugin-auth-backend-module-okta-provider              0.0.17
  @backstage/plugin-auth-backend-module-onelogin-provider          0.1.5
  @backstage/plugin-auth-backend                                   0.22.12
  @backstage/plugin-auth-node                                      0.4.17, 0.5.1
  @backstage/plugin-auth-react                                     0.1.5
  @backstage/plugin-bitbucket-cloud-common                         0.2.22
  @backstage/plugin-catalog-backend-module-gitlab                  0.4.1
  @backstage/plugin-catalog-backend-module-openapi                 0.1.43
  @backstage/plugin-catalog-backend-module-scaffolder-entity-model 0.1.22
  @backstage/plugin-catalog-backend-module-unprocessed             0.4.11
  @backstage/plugin-catalog-backend                                1.25.2
  @backstage/plugin-catalog-common                                 1.0.26
  @backstage/plugin-catalog-graph                                  0.4.8
  @backstage/plugin-catalog-import                                 0.12.2
  @backstage/plugin-catalog-node                                   1.12.6
  @backstage/plugin-catalog-react                                  1.12.3
  @backstage/plugin-catalog-unprocessed-entities-common            0.0.4
  @backstage/plugin-catalog                                        1.22.0
  @backstage/plugin-events-backend-module-gitlab                   0.2.10
  @backstage/plugin-events-backend-test-utils                      0.1.34
  @backstage/plugin-events-backend                                 0.3.11
  @backstage/plugin-events-node                                    0.3.10
  @backstage/plugin-home-react                                     0.1.16
  @backstage/plugin-home                                           0.7.9
  @backstage/plugin-kubernetes-backend                             0.18.5
  @backstage/plugin-kubernetes-common                              0.8.2
  @backstage/plugin-kubernetes-node                                0.1.18
  @backstage/plugin-kubernetes-react                               0.4.2
  @backstage/plugin-kubernetes                                     0.11.13
  @backstage/plugin-org                                            0.6.28
  @backstage/plugin-permission-backend                             0.5.48
  @backstage/plugin-permission-common                              0.8.1
  @backstage/plugin-permission-node                                0.8.2
  @backstage/plugin-permission-react                               0.4.25
  @backstage/plugin-proxy-backend                                  0.5.5
  @backstage/plugin-scaffolder-backend-module-azure                0.1.16
  @backstage/plugin-scaffolder-backend-module-bitbucket-cloud      0.1.14
  @backstage/plugin-scaffolder-backend-module-bitbucket-server     0.1.14
  @backstage/plugin-scaffolder-backend-module-bitbucket            0.2.14
  @backstage/plugin-scaffolder-backend-module-gerrit               0.1.16
  @backstage/plugin-scaffolder-backend-module-gitea                0.1.14
  @backstage/plugin-scaffolder-backend-module-github               0.4.2
  @backstage/plugin-scaffolder-backend-module-gitlab               0.4.6
  @backstage/plugin-scaffolder-backend                             1.24.1
  @backstage/plugin-scaffolder-common                              1.5.5
  @backstage/plugin-scaffolder-node-test-utils                     0.1.11
  @backstage/plugin-scaffolder-node                                0.4.10
  @backstage/plugin-scaffolder-react                               1.11.0
  @backstage/plugin-scaffolder                                     1.24.0
  @backstage/plugin-search-backend-module-catalog                  0.2.1
  @backstage/plugin-search-backend-module-explore                  0.2.1
  @backstage/plugin-search-backend-module-pg                       0.5.34
  @backstage/plugin-search-backend-module-techdocs                 0.2.1
  @backstage/plugin-search-backend-node                            1.3.1
  @backstage/plugin-search-backend                                 1.5.16
  @backstage/plugin-search-common                                  1.2.14
  @backstage/plugin-search-react                                   1.7.14
  @backstage/plugin-search                                         1.4.15
  @backstage/plugin-signals-react                                  0.0.4
  @backstage/plugin-techdocs-backend                               1.10.12
  @backstage/plugin-techdocs-common                                0.1.0
  @backstage/plugin-techdocs-module-addons-contrib                 1.1.13
  @backstage/plugin-techdocs-node                                  1.12.10
  @backstage/plugin-techdocs-react                                 1.2.7
  @backstage/plugin-techdocs                                       1.10.8
  @backstage/plugin-user-settings-common                           0.0.1
  @backstage/plugin-user-settings                                  0.8.11
  @backstage/release-manifests                                     0.0.11
  @backstage/test-utils                                            1.5.10
  @backstage/theme                                                 0.5.6
  @backstage/types                                                 1.1.1
  @backstage/version-bridge                                        1.0.8
```

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by stephenglass** [comment]
Hi! Would you be able to check this using Backstage 1.31? The two issues you first mention should be addressed in #26542 . As for the object flattening, that is expected default behavior since 1.30 (see #25346 ) but can be disabled by setting the `ui:backstage:review.explode` option to `false`.

**Comment by elaine-mattos** [comment]
Great, 
I'll test it and let you know how it goes.

**Comment by elaine-mattos** [comment]
Hi @stephenglass ,

thanks for the tip, the enumName is working now with version 1.31.  :)

I have a question though...My template has an a boolean (`addReadme`) with an object dependency (`readme`). Whenever the boolean is false, the flatening works fine:

<img width="728" alt="image" src="https://github.com/user-attachments/assets/ec291b05-fec2-443f-ba0f-e4d1c065bed5">


Whenever I set the boolean to true, then the `readme` object is dismissed and the properties in this object get shown in the boolean level:

<img width="748" alt="image" src="https://github.com/user-attachments/assets/e85ac9c6-7725-43ca-9e54-b0faa0f33060">

Below are the template parameters. Am I doing something wrong? 

```yaml
parameters:
  - title: Define properties
    required:
      - displayName
      - license
    properties:
      displayName:
        title: Display Name
        type: string
        ui:help: Readable Name
      license:
        title: License
        type: string
        default: MIT
        enum:
          - MIT
          - Apache-2.0
          - GPL-3.0
        enumNames:
          - MIT License
          - Apache License 2.0
          - GNU General Public License v3.0
  - title: Add README.md
    required:
      - addReadme
    properties:
      addReadme:
        title: Add README.md
        type: boolean
        default: true
        ui:help: Add a README.md file with some basic starting information
    dependencies:
      addReadme:
        allOf:
          - if:
              properties:
                addReadme:
                  const: true
            then:
              required:
                - readme
              properties:
                readme:
                  type: object
                  title: Add README.md
                  ui:backstage:
                    review: 
                      explode: false
                  required:
                    - description
                  properties:
                    description:
                      title: Description
                      type: string
                      ui:widget: textarea
                      ui:options:
                        rows: 10
                      ui:help: Explain the usage and content of the repository
                      default: |
                        This repository helps you to ...
```

NOTE: this is not really super important for us/our clients right now, it is just a silly question :)
