### ISSUE TITLE
🐛 Bug Report: techdocs sending a 404 even tho the documentation exists 

### ISSUE THREAD

**Issue by GersonTrj** [backstage/backstage#26738]
### 📜 Description

I am starting with the techdocs. And I get the following errors when trying to access one of the docs that is inserted into the GCP bucket already:

`{"level":"info","message":"[17/Sep/2024:12:04:55 +0000] \"GET /api/techdocs/static/docs/default/component/myapp/index.html HTTP/1.1\" 404 - \"-\" \"Mozilla/5.0 │
│ {"level":"info","message":"Unable to get metadata for 'component:default/myapp' with error Error: Unable to read techdocs_metadata.json at /app/node_modules/@backstage...

but the files are in the bucket 
<img width="617" alt="image" src="https://github.com/user-attachments/assets/6e614d46-dfd3-43d1-b4a6-51e7b2b69236">

### 👍 Expected behavior

To be able to retrieve the techdocs from the GCP bucket

### 👎 Actual Behavior with Screenshots

<img width="1436" alt="image" src="https://github.com/user-attachments/assets/c6cb1b96-b910-45e1-ba14-37396b6b31ac">

### 👟 Reproduction steps

app config:
```
techdocs:
  builder: 'external'
  publisher:
    googleGcs:
      bucketName: 'name' # is the correct name of the dev bucket
      projectId: 'projectid' # is the correct gcp project that hosts the bucket
```

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else
