### ISSUE TITLE
🚀 Feature: filter for finding leaf group

### ISSUE THREAD

**Issue by jhdm** [backstage/backstage#26794]
### 🔖 Feature description

We need `OwnerPicker` `catalogFilter` to find leaf groups.

Note: The leaf group data has empty array as children like this:

```json
{
  ...
  "kind": "Group",
  "spec": {
    "type": "team",
    "children": [],
    ...
  }
}
```

### 🎤 Context

The reason is that the leaf groups are where the users are added as members.

### ✌️ Possible Implementation

The filter in the concept might look like this:

```yaml
        myGroupName:
          ui:field: OwnerPicker
          ui:options:
            catalogFilter:
              - kind: Group
                spec.type: team
                relations.hasChildren: 'false'
```

where `relations.hasChildren` set to `'false'` means no children.

> **Note**: optionally also support matching a child: `relations.hasChild: ['group:default/some-child-group']?

or,

```yaml
                spec.children: []
```

where empty array `[]` means "no children", but this is probably not desirable, as there is existing behavior that acts like there is no filtering on the children.

Or it could be some other syntax?

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None
