### ISSUE TITLE
🚀 Feature: ldapOrg - Add LLDAP settings/configuration information.

### ISSUE THREAD

**Issue by veenarm** [backstage/backstage#26888]
### 🔖 Feature description

After a bunch of testing I finally got backstage working locally with lldap

It seems the settings required were:

```yaml
vendor:
  dnAttributeName: dn
  uuidAttributeName: entryuuid
```

Full Example Config:

```yaml
catalog:
  providers:
    ldapOrg:
      default:
        target: ldap://lldap.mydomain.com.au:3890
        bind: 
          dn: uid=admin,ou=people,dc=lldap,dc=mydomain,dc=com,dc=au
          secret: ${LDAP_SECRET}
        vendor:
          dnAttributeName: dn
          uuidAttributeName: entryuuid
        users:
          dn: ou=people,dc=lldap,dc=mydomain,dc=com,dc=au
          options:
            filter: (&(objectClass=inetOrgPerson)(!(uid=lldap*)))
            attributes: ['*', '+', 'memberOf', 'dn']
            paged: false
          map:
            rdn: uid
            name: uid
            description: description
            displayName: cn
            email: mail
            memberOf: memberOf
          set:
            metadata.ldap_vendor: 'lldap'
        groups:
          dn: ou=groups,dc=lldap,dc=mydomain,dc=com,dc=au
          options:
            filter: (&(objectClass=groupOfUniqueNames)(!(uid=lldap*)))
            attributes: ['*', '+', 'member', 'memberOf', 'dn']
            paged: false
          map:
            description: description
            rdn: uid
            name: cn
            displayName: cn
            members: member
          set:
            metadata.ldap_vendor: 'lldap'
        schedule:
          frequency: { minutes: 5 }
          timeout: { minutes: 5 }
 ``` 

Noting schedule can be changed, this was just set low for testing purposes.

### 🎤 Context

In my home testing use-case of using LLDAP as a group/user ingestion method.

### ✌️ Possible Implementation

Add the vendor LLDAP to the common lists to detect.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by freben** [comment]
If that's truly the default field names for the vendor, then sure! Would be nice if you could double check, since many orgs seem to tweak these to custom names.

**Comment by veenarm** [comment]
I've confirmed that the values are `dn` and `uuid` although `entryuuid` works ootb as well, however they preferred people to use `uuid` although this requires a specific attribute filter so also include so `filters: [ '*', '+', 'uuid']`.

**Comment by benjdlambert** [comment]
Should we maybe add both a simple example an extended config to the docs then? :pray:

**Comment by veenarm** [comment]
Yeah, I'll add it and docs, just waiting on my other ldap MR first.

I'm going to add a full example to the lldap GitHub as-well. Just away at the moment, this weekend should be able to finish off the ldap work.

**Comment by veenarm** [comment]
Double checked with LLDAP, they're happy for the use of `dn` and `entryuuid` - This requires no extra 'filters' to be used on default configurations. @benjdlambert  - I'll be creating a 'how to config' guide on the LLDAP repository - not sure if you still want one somewhere on backstages?

**Comment by veenarm** [comment]
```yaml
catalog:
  providers:
    ldapOrg:
      default:
        target: ldap://lldap.mydomain.com.au:3890
        bind: 
          dn: uid=admin,ou=people,dc=lldap,dc=mydomain,dc=com,dc=au
          secret: ${LDAP_SECRET}
        users:
          dn: ou=people,dc=lldap,dc=mydomain,dc=com,dc=au
          options:
            filter: (&(objectClass=inetOrgPerson)(!(uid=lldap*)))
          set:
            metadata.ldap_vendor: 'lldap'
        groups:
          dn: ou=groups,dc=lldap,dc=mydomain,dc=com,dc=au
          options:
            filter: (&(objectClass=groupOfUniqueNames)(!(uid=lldap*)))
          set:
            metadata.ldap_vendor: 'lldap'
        schedule:
          frequency: { minutes: 5 }
          timeout: { minutes: 5 }
```

Minimalist configuration shown above.
