### ISSUE TITLE
🐛 Bug Report: Self-referencing in catalog-info.yaml leads to recursive loops and triggers GitHub secondary rate limit

### ISSUE THREAD

**Issue by Chris-Lee-Ca** [backstage/backstage#27063]
### 📜 Description

Currently, Backstage allows self-referencing in the catalog-info.yaml file (e.g., a group referencing itself as a child). This creates a logical inconsistency and leads to performance issues when using the GitHub integration. Specifically, if I have a GitHub app polling data, a self-referencing component causes a recursive loop where Backstage continually requests the same data from GitHub, ultimately triggering GitHub’s secondary rate limit.

### 👍 Expected behavior

Self-referencing should be disallowed in the catalog-info.yaml file to prevent logical inconsistencies and avoid rate limit issues when interacting with external services like GitHub.

### 👎 Actual Behavior with Screenshots

Self-referencing is currently allowed in the catalog-info.yaml file. This causes a recursive loop when polling data from GitHub, resulting in the following error due to hitting GitHub’s secondary rate limit

### 👟 Reproduction steps

1. Create a catalog-info.yaml file for a component that references itself.

``` yaml
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: testing-group
  title: Testing
spec:
  type: org
  profile:
    displayName: Testing Group
  children:
    - testing-group
```
2. Configure Backstage to integrate with GitHub using a GitHub app.
3. Trigger a catalog refresh that causes Backstage to poll GitHub for data related to this component.
4. Observe that the GitHub app remaining rate limit

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None
