### ISSUE TITLE
🐛 Bug Report: Gitlab discovery  of multiple nested catalog-info.yaml

### ISSUE THREAD

**Issue by jayachristina** [backstage/backstage#27233]
### 📜 Description

I am trying to setup gitlab discovery for this folder structure 

```
|..root 
|.....web
|..............docs
|..............catalog-info.yaml
|.....store
|..............docs
|..............catalog-info.yaml
```
Right now my gitlab discovery section in app-config reads like this
```
providers:
    gitlab:
      rhdh:
        branch: main
        catalogPath: /**/catalog-info.yaml
        excludeRepos: []
        host: mygithub.com
        projectPattern: '[\s\S]*'
        schedule:
          frequency:
            minutes: 2
          initialDelay:
            seconds: 15
          timeout:
            minutes: 3
        skipForkedRepos: true
```

### 👍 Expected behavior

The embedded catalog-info.yamls should also be auto-discovered - with multiple components being discovered

### 👎 Actual Behavior with Screenshots

With catalogPath: `/**/catalog-info.yaml` the system  could discover components which have catalog-info.yaml in the root folder.

### 👟 Reproduction steps

* Create a repo with the above described folder structure
* Update the app-config.yaml as described above with wildcarded catalogpath
* Only components which have catalog-info.yaml in the root folder are discovered and appear in the Components UI

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else
