### ISSUE TITLE
🐛 Bug Report: `DefaultCatalogCollator` doesn't support list as entity filter

### ISSUE THREAD

**Issue by Adibov** [backstage/backstage#27265]
### 📜 Description

`DefaultCatalogCollator`'s filter can be configured using `search.collators.catalog.filter` config key. But, although the filter type is `EntityFilterQuery` and it can be a list of records, when you pass a list to it, it raises the following error:
```
ForwardedError [TypeError]: Module 'catalog-collator' for plugin 'search' startup failed; caused by TypeError: Invalid type in config for key 'search.collators.catalog.filter' in 'app-config.yaml', got array, wanted object
```

### 👍 Expected behavior

It should accept a list as an input. A possible value would be like this:
```yaml
search:
  collators:
    catalog:
      filter:
        - kind: [System, API, Resource, Location, User, Group, Domain, Template]
          spec:
            lifecycle: experimental
        - kind: [Component]
           spec:
             type: service
```

### 👎 Actual Behavior with Screenshots

The following error will occur when passing a list as filter:
```
ForwardedError [TypeError]: Module 'catalog-collator' for plugin 'search' startup failed; caused by TypeError: Invalid type in config for key 'search.collators.catalog.filter' in 'app-config.yaml', got array, wanted object
```

### 👟 Reproduction steps

[ ] Enable search plugin
[ ] Pass a list as a filter in the `search.collators.catalog.filter` config field

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, I don't have time to work on this right now
