### ISSUE TITLE
💬 RFC: There was a problem retrieving some Kubernetes resources for the entity: gmx-app. This could mean that the Error Reporting card is not completely accurate.

### ISSUE THREAD

**Issue by MohammadAliYT** [backstage/backstage#27298]
### 🔖 Need

Here is the problem, I have the latest Backstage App and I am trying to make the Kubernetes Plugin discover the cluster, pods of my totally separate application "GMX-App".

**The Problem**
![Image of the Error](https://github.com/user-attachments/assets/0c9d4f0f-efc3-457f-bfa6-3c937b71d312)

**What am I doing ?**
I have created the docker-image of the GMX-App and is running it on K8 Minikube instance but the Kubernetes plugin is unable to detect anything

Backstage directory backend `package.json` `"@backstage/plugin-kubernetes-backend": "^0.18.6"`
`app-config.yaml`
```
kubernetes:
  serviceLocatorMethod:
    type: 'multiTenant'
  clusterLocatorMethods:
    - type: 'config'
      clusters:
        - url: http://127.0.0.1:59121
          name: minikube
          authProvider: 'serviceAccount'
          skipTLSVerify: true
          skipMetricsLookup: true
          serviceAccountToken: [[This is redacted but is copy/pasted as plain text]]
          dashboardUrl: http://127.0.0.1:59490
          dashboardApp: standard
```

Now diving into my project directory, GMX App.
I will mention all the files I have created in this project apart from the obvious files that make up the skeleton of any app.

`deployment.yaml`
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gmx-app
  namespace: gmx-app
  labels:
    app: gmx-app
    backstage.io/kubernetes-id: gmx-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gmx-app
  template:
    metadata:
      labels:
        app: gmx-app
    spec:
      serviceAccountName: my-service-account
      containers:
        - name: gmx-app
          image: gmx-app
          imagePullPolicy: IfNotPresent
          # imagePullPolicy: Never
          ports:
            - containerPort: 3000
      imagePullSecrets:
        - name: regcred
```

`catalog-info.yaml`
```
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  namespace: default
  annotations:
    github.com/project-slug: mohammad-ali_uics/gmx-app
    backstage.io/kubernetes-id: gmx-app-service
  name: gmx-app
  description: GMX App for user management
  tags:
    - app
    - gmx
  relations:
    - type: ownedBy
      targetRef: user:default/mohammad-ali_uics
      target:
        kind: user
        namespace: default
        name: mohammad-ali_uics
spec:
  type: website
  owner: user:mohammad-ali_uics
  lifecycle: experimental
```

`backstage-sa.yaml`

```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: backstage-sa
  namespace: default
```

`cluster-role-binding.yaml`

```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: full-access-role-binding
subjects:
  - kind: ServiceAccount
    name: my-service-account # Change this to your actual service account name
    namespace: gmx-service-account # Change this to your actual namespace
roleRef:
  kind: ClusterRole
  name: gmx-app-access-role
  apiGroup: rbac.authorization.k8s.io
```

`cluster-role.yaml`

```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gmx-app-access-role
rules:
  - apiGroups: [""]
    resources:
      - pods
      - services
      - configmaps
      - limitranges
      - resourcequotas
    verbs: ["get", "list", "watch", "create", "update", "delete"]

  - apiGroups: ["apps"]
    resources:
      - deployments
      - replicasets
      - statefulsets
      - daemonsets
    verbs: ["get", "list", "watch", "create", "update", "delete"]

  - apiGroups: ["autoscaling"]
    resources:
      - horizontalpodautoscalers
    verbs: ["get", "list", "watch", "create", "update", "delete"]

  - apiGroups: ["batch"]
    resources:
      - jobs
      - cronjobs
    verbs: ["get", "list", "watch", "create", "update", "delete"]

  - apiGroups: ["networking.k8s.io"]
    resources:
      - ingresses
    verbs: ["get", "list", "watch", "create", "update", "delete"] 
```

`role-binding-yaml`

```
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gmx-app-role-binding
  namespace: gmx-service-account
subjects:
  - kind: ServiceAccount
    name: my-service-account
    namespace: gmx-service-account
roleRef:
  kind: Role
  name: gmx-app-role
  apiGroup: rbac.authorization.k8s.io
```

`role.yaml`

```
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: gmx-service-account
  name: gmx-app-role
rules:
  - apiGroups: ["*"] # or specify specific api groups
    resources: ["pods"] # or other resources as needed
    verbs: ["get", "list", "watch"]

```

`service.,yaml`

```
apiVersion: v1
kind: Service
metadata:
  name: gmx-app-service
  namespace: gmx-service-account
spec:
  type: NodePort
  selector:
    app: gmx-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
```

I have done `kubectl apply -f <file-name.yaml>` to all files

### 🎉 Proposal

The documentation on Backstage is very confusing and is often not explicit in-terms of basic instruction. I have raised this concern several time on discord but to no result

### 👀 Have you spent some time to check if this RFC has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

**Comment by camilaibs** [comment]
@backstage/kubernetes-maintainers do have any thoughts about it 🙂 ?

**Comment by mclarke47** [comment]
Can you run `kubectl get --raw /apis/apps/v1/deployments -v 10` and post the logs to a gist (not the response), redacting any sensitive info for this cluster

**Comment by MohammadAliYT** [comment]
Apologies for the late response. Here is the log file. [gist link](https://gist.github.com/MohammadAliYT/eb7833b35c1331fb20c2ff4d215b2d4e)

I hope this answer any questions because I was unable to figure it out over the weekend.

**Comment by MohammadAliYT** [comment]
Awaiting feedback @mclarke47

**Comment by mclarke47** [comment]
Try changing the port in app-config to `52050` since that's what your kubectl is connecting to

**Comment by MohammadAliYT** [comment]
After running the command ` https://127.0.0.1:55142/apis/apps/v1/deployments ` in my `gmx-app` where my K8 Minikube instance is running. I am getting the following response.


```
kubectl get --raw /apis/apps/v1/deployments -v 10 > output.json
gent: kubectl.exe/v1.30.2 (windows/amd64) kubernetes/3968350" 'https://127.0.0.1:55142/apis/apps/v1/deployments'
I1106 10:01:21.733956   12932 round_trippers.go:510] HTTP Trace: Dial to tcp:127.0.0.1:55142 succeed
I1106 10:01:21.742699   12932 round_trippers.go:553] GET https://127.0.0.1:55142/apis/apps/v1/deployments 200 OK in 10 milliseconds
I1106 10:01:21.742699   12932 round_trippers.go:570] HTTP Statistics: DNSLookup 0 ms Dial 1 ms TLSHandshake 4 ms ServerProcessing 3 ms Duration 10 ms
I1106 10:01:21.742699   12932 round_trippers.go:577] Response Headers:
I1106 10:01:21.742699   12932 round_trippers.go:580]     Date: Wed, 06 Nov 2024 09:01:21 GMT
I1106 10:01:21.743209   12932 round_trippers.go:580]     Audit-Id: [redacted for no reason]
I1106 10:01:21.743209   12932 round_trippers.go:580]     Cache-Control: no-cache, private
I1106 10:01:21.743209   12932 round_trippers.go:580]     Content-Type: application/json
I1106 10:01:21.743209   12932 round_trippers.go:580]     X-Kubernetes-Pf-Flowschema-Uid: [redacted for no reason]
I1106 10:01:21.743753   12932 round_trippers.go:580]     X-Kubernetes-Pf-Prioritylevel-Uid: [redacted for no reason]

```

If I open up the URL `https://127.0.0.1:55142/apis/apps/v1/deployments` I am getting the following JSON response.

```
{
"kind": "Status",
"apiVersion": "v1",
"metadata": {},
"status": "Failure",
"message": "deployments.apps is forbidden: User \"system:anonymous\" cannot list resource \"deployments\" in API group \"apps\" at the cluster scope",
"reason": "Forbidden",
"details": {
"group": "apps",
"kind": "deployments"
},
"code": 403
}
```

My minikube cluster is currently running at 
```
minikube service gmx-app-service
|-----------|-----------------|-------------|---------------------------|
| NAMESPACE |      NAME       | TARGET PORT |            URL            |
|-----------|-----------------|-------------|---------------------------|
| default   | gmx-app-service |          80 | http://192.168.49.2:32156 |
|-----------|-----------------|-------------|---------------------------|
🏃  Starting tunnel for service gmx-app-service.
|-----------|-----------------|-------------|------------------------|
| NAMESPACE |      NAME       | TARGET PORT |          URL           |
|-----------|-----------------|-------------|------------------------|
| default   | gmx-app-service |             | http://127.0.0.1:55422 |
```

minikube dashboard

```
 minikube dashboard
🤔  Verifying dashboard health ...
🚀  Launching proxy ...
🤔  Verifying proxy health ...
🎉  Opening http://127.0.0.1:55509/api/v1/namespaces/kubernetes-dashboard/services/http:kubernetes-dashboard:/proxy/ in your default browser..
```

All of the above is response from gmx-app repository

below is the `app-config.yaml`

```
kubernetes:
  serviceLocatorMethod:
    type: 'multiTenant'
  clusterLocatorMethods:
    - type: 'config'
      clusters:
        - url: http://127.0.0.1:55142
          name: minikube
          authProvider: 'serviceAccount'
          skipTLSVerify: true
          skipMetricsLookup: true
          serviceAccountToken: [redacted]
          dashboardUrl: http://127.0.0.1:55509 # url copied from running the command: minikube service kubernetes-dashboard -n kubernetes-dashboard
          dashboardApp: standard
```
