### ISSUE TITLE
🚀 Feature: Implement Google LDAP service support

### ISSUE THREAD

**Issue by megatroom** [backstage/backstage#27323]
### 🔖 Feature description

I'm using the `@backstage/plugin-catalog-backend-module-ldap` plugin to connect to **Google Cloud LDAP**. I was able to load the users and groups from LDAP, but the connection between the users and groups is not being made.

### 🎤 Context

I configured the connection to Google Cloud LDAP as follows:

```yaml
catalog:
  providers:
    ldapOrg:
      default:
        target: ldaps://ldap.google.com:636
        tls:
          rejectUnauthorized: false
          keys: ${LDAP_TLS_KEYS}
          certs: ${LDAP_TLS_CERTS}
        schedule:
          frequency: PT1H
          timeout: PT15M
        users:
          dn: ou=Users,dc=example,dc=com
          map:
            rdn: uid
            name: uid
            displayName: displayName
            email: mail
            memberOf: memberOf
        groups:
          dn: ou=Groups,dc=example,dc=com
          map:
            rdn: cn
            name: cn
            description: description
            type: groupType
            displayName: displayName
            members: member
```

All users and groups are loaded when I launch Backstage, but users are not associated with the groups.

### Proposal 1

In `plugins/catalog-backend-module-ldap/src/ldap/vendors.ts`  there should be a vendor correctly mapping the `dnAttributeName` and `uuidAttributeName` fields, for example:

```ts
export const GoogleLdapVendor: LdapVendor = {
  dnAttributeName: 'dn',
  uuidAttributeName: 'uid',
  decodeStringAttribute: (entry, name) => {
    return decode(entry, name, value => {
      return value.toString();
    });
  },
};
```

And use it in `getVendor()` function in `ldap/client.ts`:

```diff
  async getVendor(): Promise<LdapVendor> {
    if (this.vendor) {
      return this.vendor;
    }
    this.vendor = this.getRootDSE()
      .then(root => {
        if (root && root.raw?.forestFunctionality) {
          return ActiveDirectoryVendor;
        } else if (root && root.raw?.ipaDomainLevel) {
          return FreeIpaVendor;
        } else if (root && 'aeRoot' in root.raw) {
          return AEDirVendor;
-       }
+       } else if (/** some logic to identify Google service here */) {
+         return GoogleLdapVendor;
+       }
        return DefaultLdapVendor;
      })
      .catch(err => {
        this.vendor = undefined;
        throw err;
      });
    return this.vendor;
  }
  ```

### Proposal 2

Provide a way to map these two fields in the YAML configuration, just like user and group fields.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!
