### ISSUE TITLE
Feature: Autologout's StillTherePrompt button to trigger token refresh on click?

### ISSUE THREAD

**Issue by lshwayne96** [backstage/backstage#27379]
### 🔖 Need

`StillTherePrompt`: https://github.com/backstage/backstage/blob/master/packages/core-components/src/components/AutoLogout/StillTherePrompt.tsx

**Configuration**

Using LDAP plugin: https://github.com/immobiliare/backstage-plugin-ldap-auth

Auth config:
```
auth:
  backstageTokenExpiration:
    minutes: 15
  autologout:
    enabled: true
    idleTimeoutMinutes: 15
    promptBeforeIdleSeconds: 60
    useWorkerTimers: true
    logoutIfDisconnected: true
```

**Scenario**

1. User idles for 14min causing `StillTherePrompt` to appear
2. User clicks on the "still here" button in the prompt
3. User continues to idle until just past 15min
4. User performs any action that calls the backend and gets `401 Unauthorized` error

### 🎉 Proposal

The "still here" button in `StillTherePrompt` can trigger a token refresh on click in case the token is about to expire, so that the user will not get a `401 Unauthorized` error shortly after clicking the button.

On a side note, is there a way for the user to be redirected to the login page if the token has expired, instead of showing 401 error?

### 👀 Have you spent some time to check if this RFC has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)
