### ISSUE TITLE
🐛 Bug Report: Disabling "register component" button doesn't work anymore

### ISSUE THREAD

**Issue by GersonTrj** [backstage/backstage#27399]
### 📜 Description

Following the [documentation](https://backstage.io/docs/features/software-templates/#disable-register-existing-component-button). I added this setting to my config file:
```yaml
app:
  routes:
    bindings:
      scaffolder.registerComponent: false
```

This used to work, and the register existing component button disappeared but not anymore.
<img width="1676" alt="image" src="https://github.com/user-attachments/assets/c4e3c514-dc97-460d-b194-c731e47b1992">

### 👍 Expected behavior

The register existing component button should disappear.

### 👎 Actual Behavior with Screenshots

<img width="1676" alt="image" src="https://github.com/user-attachments/assets/b8a049d8-f67b-4c6f-9035-9a3e9f89f6cf">

### 👟 Reproduction steps

Add this to your app-config file
```yaml
app:
  routes:
    bindings:
      scaffolder.registerComponent: false
```

And build the project locally.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else
