### ISSUE TITLE
🚀 Feature: Ability to merge additional properties after `$yaml` placeholder processor

### ISSUE THREAD

**Issue by michaelliav** [backstage/backstage#27634]
### 🔖 Feature description

Pulling dependencies in templates from remote

### 🎤 Context

I have read the documentation and I saw the possibility to pull properties from remote in a template like so:
properties:
  org:
    $yaml: ****

And I would like a feature to do the same with a dependency like so:
    dependencies:
      org:
        $yam: ***

It could really help if you have lists of orgs and teams and you want to show the dynamically across many templates

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by benjdlambert** [comment]
Hey :wave:

Thanks for raising this issue, but I'm going to need a little more information to help out here.

Can you list in a little more detail what you're trying to do and what your use case is, the example you provided is a bit bare and hard to understand what you mean.

Thanks!

**Comment by Michaell99** [comment]
apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: Create_SQS_FIFO
  title: Create SQS FIFO
  description: Workflow to create SQS Fifo
  tags:
    - infrastructue
    - aws
spec:
  owner: 123
  type: service
  parameters:
    - title: Harness Details
      required:
        - token
        - organization
        - team
        - name
        - repository
        - env
        - dlq
        - fifo_throughput_limit
        - visibility_timeout_seconds
        - message_retention_seconds
        - max_message_size
        - maxReceiveCount
        - publishers
        - subscribers
        - delay_seconds
        - receive_wait_time_seconds
        - deduplication_scope
        - content_based_deduplication

      properties:
        token:
          title: Harness Token
          type: string
          ui:widget: password
          ui:field: HarnessAuthToken
        organization:
          $yaml: https://github/ng/account/123/module/code/orgs/Platform/projects/IDP/repos/workflows/files/main/~/workflows/org.yaml
        team:
          title: Your Team Name
          type: string
          description: Your Team Name
          ui:widget: select
        
        repository:
          title: The name of your application repository
          type: string
          description: Name of your application repository
          pattern: "^[a-zA-Z][a-zA-Z\\d.-]{0,127}$"
        
        env:
          title: Enviorment
          type: string
          description: The environment  to which you want to deploy.
          enum:
            - dev-int
            - staging
            - prod
          ui:widget: select
        
        name:
          title: SQS Name
          type: string
          description: The name of the SQS Queue
          pattern: "^[a-z-]+$"

           
        dlq:
          title: Dead leater Queue
          type: string
          enum:
            - "true"
            - "false"
          description: Would you like to create a dead letter queue for your sqs
          default: "true"
        
        publishers:
          title: Publishers
          type: string
          description: Please provide a list of arn's for publishers
          default: ""
                
        subscribers:
          title: Subscribers
          type: string
          description: Please provide a list of arn's for subscribers
          default: ""
        delay_seconds:
          title: Message Delay in Seconds
          type: string
          description: Delay Seconds in SQS is a parameter that postpones the delivery of new messages to the queue's consumers for a specified duration, An Integer from 0 to 900
          default: "0"
          pattern: "^(?:900|[1-8][0-9]{2}|[1-9][0-9]|[0-9])$"

        max_message_size:
          title: Maximum Message Size
          type: string
          default: "262144"
          description: The maximum size of a message in bytes before Amazon SQS queue and DLQ rejects it, An Integer from 0 to 262144
          pattern: "^(?:262144|[1-9][0-9]{0,4}|0)$"

        message_retention_seconds:
          title: Message Retention Seconds
          type: string
          description: The number of seconds Amazon SQS queue and DLQ retains a message, An Integer from 0 to 86400
          default: "86400"
          pattern: "^(?:86400|8[0-5][0-9]{3}|[1-7][0-9]{4}|[1-9][0-9]{1,3}|[0-9])$"

        receive_wait_time_seconds:
          title: Receive Wait Time Seconds
          type: string
          description: The maximum amount of time, in seconds, that a ReceiveMessage action will wait for a message to arrive, An Integer from 0 to 20
          default: "0"
          pattern: "^(?:20|1[0-9]|[0-9])$"

        visibility_timeout_seconds:
          title: Visibility Timeout Seconds
          type: string
          description: The visibility timeout for the queue and the dead-letter queue, An Integer from 0 to 43200 .
          default: "30"
          pattern: "^(?:43200|4[0-2][0-9]{3}|[1-3][0-9]{4}|[1-9][0-9]{1,3}|[0-9])$"
        
        maxReceiveCount:
          title: Max Recive Count
          description: The number of times a message can be unsuccessfully dequeued before being moved to the dead-letter queue, An Integer from 0 to 1000
          default: "4"
          type: string
          pattern: "(1000|([1-9][0-9]{0,2}))$"

        fifo_throughput_limit:
          title: Fifo throughput limit
          description: Specifies whether the FIFO queue throughput quota applies to the entire queue or per message group. Valid values are perQueue and perMessageGroupId
          type: string
          default: "perQueue"
          enum:
            - perQueue
            - perMessageGroupId
        
        deduplication_scope:
          title: Deduplication Scope
          description: Specifies whether message deduplication occurs at the message group or queue level
          type: string
          default: "messageGroup"
          enum:
            - messageGroup
            - queue
        content_based_deduplication: 
          title: content based deduplication
          description: Enables content-based deduplication for FIFO queues.
          type: string
          default: "true"
          enum:
            - "true"
            - "false"

      **dependencies:** This is the part I want to import as yaml
        organization:
          oneOf:
            - properties:
                organization:
                  const: Digital
                team:
                  enum: [1, 2, 3]
            - properties:
                organization:
                  const: Data
                team:
                  enum: [7]
  steps:
    - id: trigger
      name: Creating SQS Fifo
      action: trigger
      input:
        url: "random"
        inputset:
          tf_resource_type: "sqs"
          only_update_irsa: "false"
          region: "eu-west-1"
          organization: ${{ parameters.organization }}
          team: ${{ parameters.team }}
          project_name: ${{ parameters.team }}
          repository: ${{ parameters.repository }}
          env: ${{ parameters.env }}
          fifo_queue: "true"
          enable_dlq: ${{ parameters.dlq }}
          fifo_throughput_limit: ${{ parameters.fifo_throughput_limit }}
          visibility_timeout_seconds: ${{ parameters.visibility_timeout_seconds }}
          message_retention_seconds: ${{ parameters.message_retention_seconds }}
          max_message_size: ${{ parameters.max_message_size }}
          maxReceiveCount: ${{ parameters.maxReceiveCount }}
          delay_seconds: ${{ parameters.delay_seconds }}
          receive_wait_time_seconds: ${{ parameters.receive_wait_time_seconds }}
          deduplication_scope: ${{ parameters.deduplication_scope }}
          sqs_name: ${{ parameters.name }}
          content_based_deduplication: ${{ parameters.content_based_deduplication }}
          publishers: ${{ parameters.publishers }}
          subscribers: ${{ parameters.subscribers }}

**Comment by Michaell99** [comment]
Hi, I have added a code snippet that should show how I want to do the import. Currently the organization is imported correctly and I want to do the same with the dependencies

**Comment by benjdlambert** [comment]
Ah, ok. Unfortunately this isn't possible right now.

I think that this is more of a catalog issue rather than scaffolder issue, as it's the catalog that's responsible for the `$yaml` placeholder resolvers.

Would you be willing to try and contribute this functionality?

**Comment by Michaell99** [comment]
Unfortunately I don't have capabilities to do so, But I can check if we can add one of our developers on the task.

**Comment by karthikeyanjp** [comment]
@michaelliav Trying to understand the usecase here. 

Will the below config solve your issue?

```yaml
apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: Create_SQS_FIFO
  title: Create SQS FIFO
  description: Workflow to create SQS Fifo
  tags:
    - infrastructue
    - aws
spec:
  owner: guest
  type: service
  parameters:
    - title: Harness Details
      required:
        - token
        - organization
        - team
      properties:
        token:
          title: Harness Token
          type: string
          ui:widget: password
          ui:field: Secret
        organization:
          $yaml: https://gist.githubusercontent.com/karthikeyanjp/fa1c9b28d99eaef30843a42c2caf8f19/raw/4489a73595f33bd7fde0bd04acef66135a207ce2/org.yaml
          # title: Organization
          # type: string
          # description: Name of the Organization
          # enum:
          #   - digital
          #   - data
      dependencies:
        organization:
          $yaml: https://gist.githubusercontent.com/karthikeyanjp/375600e6ac3d50ffac3d22270c2030c0/raw/6885773bece763c1a3b8d2827f645c3cf14eecda/org_deps.yaml
          # allOf:
          #   - if:
          #       properties:
          #         organization:
          #           const: digital
          #     then:
          #       properties:
          #         team:
          #           title: Team
          #           type: number
          #           enum: [1, 2, 3]

          #   - if:
          #       properties:
          #         organization:
          #           const: data
          #     then:
          #       properties:
          #         team:
          #           title: Team
          #           type: number
          #           enum: [7]
  steps:
    - id: trigger
      name: Creating SQS Fifo
      action: trigger
      input:
        url: "random"
        inputset:
          tf_resource_type: "sqs"
          only_update_irsa: "false"
          region: "eu-west-1"
          organization: ${{ parameters.organization }}
          team: ${{ parameters.team }}
```
