### ISSUE TITLE
🐛 Bug Report:  Auth login: target origin provided does not match the recipient window's origin

### ISSUE THREAD

**Issue by julzhe01** [backstage/backstage#27696]
### 📜 Description

hi there, I set up an backstage on my aws eks. and its url is https://eu-west-1.backstage.aw.arm.com, and I also asked for another domain like: backstage.arm.com in my company to be redirected to aws one. and meanwhile we enabled sso login, microsoft-auth-provider.
the issue is: 
so currently if I open https://eu-west-1.backstage.aw.arm.com, and click login in, I can successfully login.
but if I open https://backstage.arm.com, the login page is good, but if I click login, the popup window url starts with https://eu-west-1.backstage.aw.arm.com/api/auth/microsoft/handler/frame, and failed with Login failed: caused by PopupClosedError: Login failed, popup was closed.

error message: 
use web debug tools on the poped up window, more error messages are: 
Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://backstage.arm.com') does not match the recipient window's origin ('https://eu-west-1.backstage.aw.arm.com').

and my configs:
in app-config.yaml
```
backend:
  baseUrl: ${BACKEND_URL}
.....
  cors:
    origin:
      - ${FRONTEND_URL} #which is https://eu-west-1.backstage.aw.arm.com
      - https://backstage.arm.com
```
      
and output of "kubectl -n backstage get ingress backstage"
```
  rules:
  - host: eu-west-1.backstage.aws.arm.com
    http:
      paths:
      - backend:
          service:
            name: backstage
            port:
              number: 7007
        path: /
        pathType: Prefix
   - host: backstage.arm.com
    http:
      paths:
      - backend:
          service:
            name: backstage
            port:
              number: 7007
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - eu-west-1.backstage.aws.arm.com
    - backstage.arm.com
    secretName: backstage-ca-tls

ssl-passthrough =false
```

why the issue is still there, maybe it's a bug, and I need to changes codes in 
https://github.com/backstage/backstage/blob/master/plugins/auth-backend/src/lib/flow/authFlowHelpers.ts
or 
https://github.com/backstage/backstage/blob/994506952c20d7708c2f8a5f6498b19132157166/packages/core-app-api/src/lib/loginPopup.ts

### 👍 Expected behavior

if I click https://backstage.arm.com, I can not only see the login page, but also successfully login.

### 👎 Actual Behavior with Screenshots

all in the Description above.

### 👟 Reproduction steps

all in the Description above.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by julzhe01** [comment]
anyone can help on this? 
besides: backend.cors, i also added "experimentalExtraAllowedOrigins" today, 

auth:
  environment: production
  experimentalExtraAllowedOrigins:
    - ${FRONTEND_URL}
    - "https://backstage.arm.com"


but it doesn't work, still failed ti the same error.  if I tried login through https://backstage.arm.com, the pop up url still starts with app.baseurl and goes back to app.baseurl with message instead of https://backstage.arm.com

**Comment by julzhe01** [comment]
@Rugvip
do you have any idea on this, thanks
this issue has been blocking me for several weeks.

**Comment by julzhe01** [comment]
by the way, the auth provider I use is azure

**Comment by Rugvip** [comment]
Hmm, do you have `app.baseUrl` set in configuration to the url that the app is hosted at and applied to both the frontend and the backend?

**Comment by julzhe01** [comment]
yes, currently in my app config file:
${FRONTEND_URL} and ${BACKEND_URL}, they are set to be "https://eu-west-1.backstage.aw.arm.com/" which is app real url. and https://backstage.arm.com something I want let others to use which is easy to remember.
```
app:
  title: Engineering Portal
  baseUrl: ${FRONTEND_URL}

backend:
  baseUrl: ${BACKEND_URL}
  auth:
      dangerouslyDisableDefaultAuthPolicy: false
      keys:
      - secret: ${BACKEND_SECRET}
  cors:
    origin:
      - ${FRONTEND_URL}
      - "https://backstage.arm.com"
    methods: [GET, HEAD, PATCH, POST, PUT, DELETE]
    credentials: true
  csp:
    connect-src: ["'self'", "https:"]
    img-src: ["'self'", "https:", "data:"]
    style-src: ["'self'", "https:", "'unsafe-inline'", "https://fonts.googleapis.com"]
  reading:
    allow:
    - host: '*.arm.com'
  database:
    client: pg
    prefix: ${DB_PREFIX}
    connection:
      host: ${POSTGRES_HOST}
      port: ${POSTGRES_PORT}
      user: ${POSTGRES_USER}
      password: ${POSTGRES_PASSWORD}
      ssl: 
        require: true
        rejectUnauthorized: false

##### authentication
auth:
  environment: production
  experimentalExtraAllowedOrigins:
    - ${FRONTEND_URL}
    - "https://backstage.arm.com"
  providers:
    microsoft:
      production:
        clientId: ${AZURE_CLIENT_ID}
        tenantId: ${AZURE_TENANT_ID}
        clientSecret: ${AZURE_CLIENT_SECRET}
        signIn:
          resolvers:
            - resolver: emailMatchingUserEntityProfileEmail
```
