### ISSUE TITLE
🐛 Bug Report: ensure CRDs are installed first

### ISSUE THREAD

**Issue by MohammadAliYT** [backstage/backstage#27825]
### 📜 Description

I am using an organization's windows machine and there were a few issues with permissions of the service account token that were preventing the discovery of project's K8 cluster in Backstage I/O. 

So I migrated everything to WSL-2 running Ubuntu 24.04.01 instance.

Now the issue/error I am facing is two folds.

### 👍 Expected behavior

I was expecting it to be a smooth sail since I have shifted everything to Linux but unfortunately that is not the case.

### 👎 Actual Behavior with Screenshots

First issue is: (This error was not present before installing WSL-2)

`catalog-info.yaml`

```
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  namespace: gmx-app
  annotations:
    github.com/project-slug: mohammad-ali_uics/gmx-app
    backstage.io/kubernetes-id: gmx-app-service
  name: gmx-app
  description: GMX App for user management
  tags:
    - app
    - gmx
  relations:
    - type: ownedBy
      targetRef: user:default/mohammad-ali_uics
      target:
        kind: user
        namespace: gmx-app
        name: mohammad-ali_uics
spec:
  type: website
  owner: user:mohammad-ali_uics
  lifecycle: experimental

```
`kubectl apply -f catalog-info.yaml`
```
error: resource mapping not found for name: "gmx-app" namespace: "gmx-app" from "catalog-info.yaml": no matches for kind "Component" in version "backstage.io/v1alpha1"
ensure CRDs are installed first
```
I believe that it is not able to read this line `apiVersion: backstage.io/v1alpha1`

Second issue:

`deployment.yaml`

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gmx-app
  namespace: gmx-service-account
  labels:
    app: gmx-app
    backstage.io/kubernetes-id: gmx-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gmx-app
  template:
    metadata:
      labels:
        app: gmx-app
    spec:
      serviceAccountName: gmx-service-account
      containers:
        - name: gmx-app
          image: gmx-app
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
      imagePullSecrets:
        - name: regcred
```

The pods are not working, this issue was persistent before as well.

Behavior:

```
kubectl get pods -n gmx-service-account
NAME                       READY   STATUS              RESTARTS   AGE
gmx-app-6444dd44f6-6jrkp   0/1     ErrImageNeverPull   0          39m
gmx-app-6444dd44f6-cgrc6   0/1     ErrImageNeverPull   0          39m
gmx-app-6444dd44f6-qkq22   0/1     ErrImageNeverPull   0          39m
gmx-app-644dd949bc-5j7nf   0/1     ImagePullBackOff    0          46s
```

### 👟 Reproduction steps

my steps

1. `minikube status`
2. `minikube start`
3. `kubectl get namespace`
4. `kubectl create namespace gmx-service-app`
5. `kubectl apply -f service.yaml`
6. `kubectl apply -f service-account.yaml`
7. `kubectl get serviceaccount --all-namespaces`
8. `kubectl apply -f role.yaml`
9. `kubectl apply -f role-binding.yaml`
10. `kubectl apply -f cluster-role.yaml`
11. `kubectl apply -f cluster-role-binding.yaml`
12. `kubectl apply -f deployment.yaml`

When I do this and run the command
`minikube service gmx-service-account -n gmx-service-account` it works but the webpage is totally blank and says

```
This page isn’t working right now
127.0.0.1 didn’t send any data.
```

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None
