### ISSUE TITLE
🐛 Bug Report: Conditional options break in Template Editor after validation failure

### ISSUE THREAD

**Issue by kmikko** [backstage/backstage#27875]
### 📜 Description

Conditional options won't render in Template Editor after there's been validation error in template schema.
Might be related to #27872 but reporting this as a separate issue.

Minimal reproducible example:
```yaml
parameters:
  - title: Fill in some steps
    properties:
      condition:
        type: string
        enum:
          - A
          - B
        ui:widget: radio
        ui:options:
          inline: true
    dependencies:
      condition:
        allOf:
          - if:
              properties:
                condition:
                  const: A
            then:
              properties:
                extraOption:
                  title: Extra option for A
                  type: string
```

### 👍 Expected behavior

Template Editor should cope from schema validations errors and continue to render conditional steps as before.

### 👎 Actual Behavior with Screenshots

Conditional steps stop working after schema validation error (unknown field type, typo, etc.)  in Template Editor.

https://github.com/user-attachments/assets/8f040fb5-c67d-4c91-b858-0f29017f7842

### 👟 Reproduction steps

- Open Template Editor and paste in example from description.
- Toggling condition between `A` and `B` should work as expected: when `A` is selected `extraOption` is shown and when `B` is selected it's hidden 
- Introduce a schema validation error, e.g. by changing `type: string` -> `type: strin`
- Wait until change is reflected in UI and validation error is shown
- Toggling condition between `A` and `B` has no visible effect. Page refresh is needed to fix the issue.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else
