### ISSUE TITLE
🐛 Bug Report: Scaffolder template start over fails if big files submitted in template on Firefox

### ISSUE THREAD

**Issue by Teemukoivumaa** [backstage/backstage#27928]
### 📜 Description

If you try to 'Start over' a template where there is a file input and the user has added a big file, it will produce an error (See video) if you're using Firefox instead of Chrome. This has been tested on MacOS and Windows and works exactly the same.

### 👍 Expected behavior

You should be able to "Start over" templates regardless of the browser 

### 👎 Actual Behavior with Screenshots

See video (Top browser is firefox, bottom is Google Chrome):

https://github.com/user-attachments/assets/5afbeaae-f884-4f94-b8ff-425a6cfd2cc4

### 👟 Reproduction steps

1. Add a big file to a template input
2. Run the template
3. Try to press "Start over" with Firefox

Sample file generated with: `fallocate -l 5MB test.txt`
Sample template used:
```yaml
apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: confluence-to-markdown
  title: Confluence to Markdown
spec:
  owner: team-d
  type: service
  parameters:
    - title: Confluence and Github Repo Information
      properties:
        attachments:
          title: Choose attachments
          description: Maximum attachment size is 50 MB
          type: array
          items:
            type: string
            format: data-url
  steps:
    - id: log
      action: debug:log
      input:
        message: "Converting Confluence to Markdown"
```

### 📃 Provide the context for the Bug.

SyntaxError that is shown by backstage:
```
Location.assign: '/create/templates/default/confluence-to-markdown?formData=%7B%22attachments%22%3A%5B%22data%3Atext%2Fplain%3Bname%3Dtest.txt%3Bbase64%2CAAAAAAAAA...' is not a valid URL.
```
Error in firefox console: 
```
Uncaught DOMException: Location.assign: '/create/templates/default/confluence-to-markdown?formData=%7B%22attachments%22%3A%5B%22data%3Atext%2Fplain%3Bname%3Dtest.txt%3Bbase64%2CAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA…
    push router.js:388
    navigate index.js:245
    startOver OngoingTask.tsx:154
    React 32
    onClick ContextMenu.tsx:112
    React 23
    <anonymous> index.tsx:22
    tsx src_index_tsx-data_image_svg_xml_base64_PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciI-877ba6.chunk.js:282
    factory runtime.js:668
    __webpack_require__ runtime.js:34
    fn runtime.js:327
    promise callback*./src/index.tsx!lazy-compilation-proxy main.js:39
    factory runtime.js:668
    __webpack_require__ runtime.js:34
    __webpack_exec__ main.js:113
    <anonymous> main.js:114
    O runtime.js:79
    <anonymous> main.js:115
    webpackJsonpCallback runtime.js:1282
    <anonymous> main.js:9
router.js:388
```

### 🖥️ Your Environment

Not sure why backstage version is N/A but using the latest version 1.34.0-next.0
```sh
teemukoivumaa:~/backstage(master)$ yarn backstage-cli info
OS:   Linux 5.15.153.1-microsoft-standard-WSL2 - linux/x64
node: v18.20.2
yarn: 3.8.1
cli:  0.29.3-next.0 (local)
backstage:  N/A
```

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None
