### ISSUE TITLE
Gitlab - User groups are not displaying in User overview

### ISSUE THREAD

**Issue by vinaykv23** [backstage/backstage#27995]
### 📜 Description

In gitlab user belongs to different groups
Group1, Group2
the same is expected to display in User overview 

![image](https://github.com/user-attachments/assets/b7aa176f-f1a1-45af-a1d2-aa76e5f06123)

### 👍 Expected behavior

Groups should be listed in user overview

### 👎 Actual Behavior with Screenshots

Groups are not displaying in user overview

![image](https://github.com/user-attachments/assets/479391ab-23ae-4b31-8f8e-ec963f896cdc)

### 👟 Reproduction steps

app-config.yaml
```yaml
integrations:
  gitlab:
    - host: gitlab.corp.org.com
      apiBaseUrl: https://gitlab.corp.org.com/api/v4
      token: ${GITLAB_TOKEN}

catalog:
  providers:
    gitlab:
      app-platform:
        host: gitlab.corp.org.com
        orgEnabled: true
        group: org-platform
        allowInherited: true # Allow groups to be ingested even if there are no direct members.
        schedule: # Same options as in TaskScheduleDefinition. Optional for the Legacy Backend System.
          # supports cron, ISO duration, "human duration" as used in code
          frequency: { minutes: 20 }
          # supports ISO duration, "human duration" as used in code
          timeout: { minutes: 20 }
      backstage-poc:
        host: gitlab.corp.org.com
        orgEnabled: true
        group: backstage-poc 
        allowInherited: true 
        schedule: 
          frequency: { minutes: 20 }
          timeout: { minutes: 20 }
```

Got backstage application -> Settings menu -> General tab -> Backstage Identity ->User Entity -> click on user 

![image](https://github.com/user-attachments/assets/63658849-8556-4c1c-9ff7-ca99a813171c)

### 🖥️ Your Environment

Backstage "version": "1.33.4"

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None
