### ISSUE TITLE
🐛 Bug Report: publish:github:pull-request does not support deletion of files

### ISSUE THREAD

**Issue by Lock128** [backstage/backstage#28112]
### 📜 Description

When I use the scaffolder action 'publish:github:pull-request' in a template this does not support the "deletion" of files that where previously in the git repository

it should support that

### 👍 Expected behavior

If I checkout a repository, remove a file and then create a pull request the pull request should actually have a file deletion marker for this file and merging the PR should delete this.

### 👎 Actual Behavior with Screenshots

The created PR in Github is "empty" - no files are visible in it....

### 👟 Reproduction steps

Using this template

```
  steps:
    - action: fetch:plain
      id: fetch-plain
      name: Fetch plain
      input:
        url: https://${{ parameters.repoUrl | parseRepoUrl | pick('host') }}/${{ parameters.repoUrl | parseRepoUrl | pick('owner') }}/${{ parameters.repoUrl | parseRepoUrl | pick('repo') }}
    - id: log
      name: Current files in directory
      action: debug:log
      input:
        listWorkspace: true
    - action: fs:delete
      id: delete-file
      name: Delete files
      input:
        files:
          - "file-to-delete.yaml"
    - id: log2
      name: New files in directory
      action: debug:log
      input:
        listWorkspace: true
    - id: pullRequest
      name: Pull Request
      action: publish:github:pull-request
      input:
        repoUrl: ${{ parameters.repoUrl }}
        branchName: delete-dt-${{ parameters.name }}
        description: "Delete file"
        gitCommitMessage: "Delete file ${{ parameters.name }}"
        title: "Deletes a file"
```

### 📃 Provide the context for the Bug.

This is where the files are read
https://github.com/backstage/backstage/blob/a65f2d57149a9265c934c58b755fa7fd2c8cd936/plugins/scaffolder-backend-module-github/src/actions/githubPullRequest.ts#L335-L353

and then they are added to the PR here:
https://github.com/backstage/backstage/blob/a65f2d57149a9265c934c58b755fa7fd2c8cd936/plugins/scaffolder-backend-module-github/src/actions/githubPullRequest.ts#L370-L372

obviously, a file that was deleted will never be added as a "change set" :-( 

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else
