### ISSUE TITLE
🐛 Bug Report: GitHub Catalog Providers use namespaces inconsistently between Entity and Org data

### ISSUE THREAD

**Issue by StephenRobin** [backstage/backstage#28122]
### 📜 Description

We use the GitHub integration to import both entity and org data. At present we import only from one Github Enterprise Organisation but wish to extend this to two. I have changed our config yaml accordingly:

```
catalog:
  providers:
    github:
      foo:
        host: git.example.com
        organization: 'GitHubOrg1'
        catalogPath: '.backstage/catalog-info*.yaml'
      bar:
        host: git.mavensecurities.com
        organization: 'GitHubOrg2'
        catalogPath: '.backstage/catalog-info*.yaml'
    githubOrg:
      - id: blah
        githubUrl: 'https://git.example.com'
        orgs: ['GitHubOrg1', 'GitHubOrg2']
```

Unfortunately the two providers are inconsistent in how they put entities into namespaces.

- The github org provider will put users and teams it creates into namespaces matching the GitHub Organisation name. This feels correct, you can have groups with the same name in different orgs (we do this, but they're guaranteed to have the same membership).
- The github entities provider imports the catalog-info.yaml files as-is, unless they explicitly have a namespace entry in the yaml they will go into the default namespace.

Possible workarounds:
 - Add the namespace to every catalog-info.yaml file in our Github instance. Unfortunately this is a very large number (>1000 files). We'd also have to remember to set new ones up correctly.
 - Add user and team transformers to move them to the default namespace. We'd get into trouble if people created Teams with the same name but different members in the two organisations
 - Add a Custom Processor that adds the namespace to the entities based on where they've come from (it could also automatically set the github.com/project-slug annotation, another bugbear of mine).

Possible fixes in Backstage itself:
- Give the entity provider the same behaviour as the org provider: when importing from multiple github organisations, put the entities into namespaces. This seems to be tricky to implement as the github provider passes just a list of file locations back to the more generic code.
- Add a "namespace" option to the github provider config. Has the same implementation problem.
- Expose the option to put users/Teams into the default namespace - currently it's computed internally.

### 👍 Expected behavior

I'd expect the two providers to be consistent, and create the entities in different namespaces depending on the github org they have come from.

### 👎 Actual Behavior with Screenshots

The org provider puts users and teams into namespaces, the entities provider does not.

### 👟 Reproduction steps

Use a catalog configuration like above to import from two GitHub enterprise organisations. Note that the software components imported from catalog-info.yaml files are in the default namespace (unless they have explicitly stated one in the yaml) while the users / teams are in separate namespaces.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else
