### ISSUE TITLE
🐛 Bug Report: Database connection objects no longer pass schema validation

### ISSUE THREAD

**Issue by tylerd-canva** [backstage/backstage#28170]
### 📜 Description

Looks like this was caused by https://github.com/backstage/backstage/pull/27901

```

Error: Configuration does not match schema
--
  |  
  | Config must have required property 'instance' { missingProperty=instance } at /backend/database/connection
  | Config must have required property 'type' { missingProperty=type } at /backend/database/connection
  | Config must NOT have additional properties { additionalProperty=host } at /backend/database/connection
  | Config must NOT have additional properties { additionalProperty=port } at /backend/database/connection
  | Config must NOT have additional properties { additionalProperty=user } at /backend/database/connection
  | Config must NOT have additional properties { additionalProperty=host } at /backend/database/connection
  | Config must NOT have additional properties { additionalProperty=port } at /backend/database/connection
  | Config must NOT have additional properties { additionalProperty=user } at /backend/database/connection
  | Config must be string { type=string } at /backend/database/connection
  | Config must match a schema in anyOf {  } at /backend/database/connection


```

My config looks like this:

```
  database:
    client: pg
    connection:
      host: ${DB_HOST}
      port: ${DB_PORT}
      user: ${DB_USERNAME}
      password: ${DB_PASSWORD}
```
It's trying to validate it against the new CloudSQL schema:

```
          {
            /**
             * The specific config for cloudsql connections
             */
            type: 'cloudsql';
            /**
             * The instance connection name for the cloudsql instance, e.g. `project:region:instance`
             */
            instance: string;
          }
```

instead of the more flexible type:
```
          {
            /**
             * Password that belongs to the client User
             * @visibility secret
             */
            password?: string;
            /**
             * Other connection settings
             */
            [key: string]: unknown;
          }
```

### 👍 Expected behavior

`yarn backstage-cli config:check --strict` should pass. This was not listed as a breaking change so I'm assuming I shouldn't need to change my config at all. I'm happy to do so if it was simply mislabeled though.

### 👎 Actual Behavior with Screenshots

`yarn backstage-cli config:check --strict` fails with above description

### 👟 Reproduction steps

I assume: create a new backstage app and setup postgres then run `yarn backstage-cli config:check --strict`

### 📃 Provide the context for the Bug.

This is new in 1.34.0

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by tylerd-canva** [comment]
A simple test in pure TS seems to support the PR -- there are no issues with this code:

```typescript
type schema =
| string
| {
  type: 'cloudsql';
  instance: string;
}
| {
  password?: string;
  [key: string]: unknown;
};

const test1: schema = "hello";
const test2: schema = { type: 'cloudsql', instance: 'project:region:instance' };
const test3: schema = { host: 'test', port: 'test', user: 'test', password: 'password' };
```

I'm having a look at the `backstage-cli config:check` code to see what could be happening.

**Comment by benjdlambert** [comment]
Ah shiet, yeah, this is not meant to be a breaking change.

My guess is that the `jsonschema` is getting in the way when it's doing the validation based on the types and it's not validating properly. There's a chance that changing the order in the `config.d.ts` might work, but it's unfortunate. :(

**Comment by tylerd-canva** [comment]
Would you be open to changing the schema and the cloudsql parsing code? I don't have a proposal yet but my goal would be to make it less "ambiguous" to avoid the issue entirely.

**Comment by tylerd-canva** [comment]
Ok best idea I have so far is this:

```
          client?: 'better-sqlite3' | 'sqlite3' | 'pg' | 'cloudsql';
          /**
           * Database connection string or Knex object override
           * @visibility secret
           */
          connection?:
            | string
            | {
                /**
                 * Password that belongs to the client User
                 * @visibility secret
                 */
                password?: string;
                /**
                 * Other connection settings
                 */
                [key: string]: unknown;
              };
```

so to configure `cloudsql` you would do this:

```yaml
database:
  client: 'cloudsql'
  connection: 'myproject:myregion:myinstance'
```

or

```yaml
database:
  client: 'cloudsql'
  connection:
    project: 'myproject'
    region: 'myregion'
    instance: 'myinstance'
```

disclaimer: I have no experience with cloud SQL so I'm not sure if this is a good fit or not.

**Comment by tylerd-canva** [comment]
Ah that won't work perfectly, I see now from the tests you need to provide other parameters beyond `instance`, like `user` and `port`. Let me keep hacking at it.

**Comment by tylerd-canva** [comment]
I've got to head to bed but I wonder if this https://github.com/backstage/backstage/pull/28236 isn't the best option for the moment. I think the ideal fix is to dive into the config parsing/validation code and see if there's a way to handle these kinds of types correctly, otherwise I'm sure this will come up again in the future (I bet it's already come up in the past at some point, TBH).

**Comment by benjdlambert** [comment]
@tylerd-canva we've worked out what the issue is here.

The config schemas are actually merged when we parse them, which means that the config schemas get messed up when they're merged with the old `backend-common` schemas as `backend-defaults` is the successor.

We're working on a real fix for this, and will get it out in a patch hopefully today.

**Comment by tylerd-canva** [comment]
Awesome, thanks so much! I'll close my PR.

**Comment by tylerd-canva** [comment]
I'm still seeing this issue on Backstage 1.34.1 with `@backstage/backend-defaults@0.6.1` and `@backstage/config-loader@1.9.4` :(

**Comment by tylerd-canva** [comment]
I must be doing something wrong though, because I can't reproduce the issue when I copy my own app-config files over to a fresh create-app instance. Will keep digging.

**Comment by tylerd-canva** [comment]
The only clue I have is that `yarn backstage-cli config:schema` actually generates a different `backend.database.connection` block in my instance vs a fresh create-app.

### Mine
```yaml
          connection:
            description: Base database connection string, or object with individual
              connection properties
            visibility: secret
            anyOf:
              - type: object
                required:
                  - instance
                  - type
                properties:
                  password:
                    description: Password that belongs to the client User
                    visibility: secret
                    type: string
                  type:
                    description: The specific config for cloudsql connections
                    type: string
                    const: cloudsql
                  instance:
                    description: The instance connection name for the cloudsql instance, e.g.
                      `project:region:instance`
                    type: string
              - type: object
                properties:
                  password:
                    description: Password that belongs to the client User
                    visibility: secret
                    type: string
              - type: string
```

### Create-App
```yaml
          connection:
            description: Base database connection string, or object with individual
              connection properties
            visibility: secret
            anyOf:
              - type: object
                properties:
                  type:
                    description: The specific config for cloudsql connections
                    type: string
                    const: cloudsql
                  instance:
                    description: The instance connection name for the cloudsql instance, e.g.
                      `project:region:instance`
                    type: string
                required:
                  - instance
                  - type
              - type: object
                additionalProperties: {}
                properties:
                  password:
                    description: Password that belongs to the client User
                    visibility: secret
                    type: string
              - type: string
```
