### ISSUE TITLE
🐛 Bug Report: Scaffolder no longer passing secrets when creating tasks

### ISSUE THREAD

**Issue by koalaty-code** [backstage/backstage#28208]
### 📜 Description

When creating a new Scaffolder Task through the UI, `secrets` are not being sent to `POST /api/scaffolder/v2/tasks`.

I believe this is specific to the latest release of `@backstage/plugin-scaffolder` and `@backstage/plugin-scaffolder-react`.

I upgraded the Backstage yarn plugin to the latest release yesterday (v1.34.0) to get the fix for Windows path resolution. Upgrading the yarn plugin and running `yarn install` resulted in most of the `@backstage/*` packages being upgraded (this might be another issue?) even though `backstage.json` is still pinned to `1.33.3`. 

I also tried upgrading to Backstage v1.34.0 thinking I was in a weird state of being partially upgraded. The issue still persisted after fully upgrading to v1.34.0.

### 👍 Expected behavior

Secrets collected through the template parameters will be forwarded to the created task.

### 👎 Actual Behavior with Screenshots

`secrets: {}` is sent in the request body regardless of which secrets are collected by the template.

### 👟 Reproduction steps

In an environment with the following dependencies:

@backstage/plugin-scaffolder v1.27.2
@backstage/plugin-scaffolder-react v1.14.2
@backstage/plugin-scaffolder-common v1.5.8

Create and execute the following template:

```yaml
apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  namespace: default
  tags:
    - github
  name: test-template
  title: Test
  description: >
    Test Scaffolder Template
spec:
  owner: group:default/test
  type: service
  parameters:
    - title: Service Metadata
      description: Information related to the repository
      type: object
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            requestUserCredentials:
              secretsKey: USER_OAUTH_TOKEN
            allowedHosts:
              - github.com

  steps:
    - action: debug:log
      name: List all inputs
      input:
        message: |
          RepoUrl: ${{ parameters.repoUrl }}

```

Inspect the network request for `POST /api/scaffolder/v2/tasks` and notice `secrets: {}` is missing the `USER_OAUTH_TOKEN` secret set by the RepoUrlPicker.

### 🖥️ Your Environment

Backstage v1.33.3

@backstage/plugin-scaffolder v1.27.2
@backstage/plugin-scaffolder-react v1.14.2
@backstage/plugin-scaffolder-common v1.5.8

@yarnpkg/backstage-plugin v1.34.0

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None
