### ISSUE TITLE
How to read value from catalog file when using MultiEntityPicker

### ISSUE THREAD

**Issue by MaharaJothi** [backstage/backstage#28232]
### 📜 Description

I am trying to use **MultiEntityPicker** for my use case to be able to select multiple components.  But I also want to be able to read the spec values inside the selected component's catalog-info.yaml.

While using **EntityPicker**, I am able to achieve this using the below code:
``` yaml
parameters:
- title: Select dependency
   properties:
      component:
        type: string
        description: Component as dependency
        ui:field: EntityPicker
        ui:options:
          allowArbitraryValues: true
          catalogFilter:
            - kind: Component
steps:  
    - id: fetchdata
      name: Fetch Data
      action: catalog:fetch
      input:
        entityRefs: 
        - ${{ parameters.component }}
    - id: log-parameters
      name: Log Parameters
      action: debug:log
      input:
        message: |
          Component: ${{ steps['fetchdata'].output.entities[0].spec.lifecycle}}
```

To achieve something similar for **MultiEntityPicker**, I used below:
```yaml
parameters:
- title: Select dependency
   properties:
      component:
        type: array
        description: Component as dependency
        ui:field: MultiEntityPicker
        ui:options:
          allowArbitraryValues: true
          catalogFilter:
            - kind: Component
steps:  
    - id: fetchdata
      name: Fetch Data
      action: catalog:fetch
      input:
        entityRefs: ${{ parameters.component }}
    - id: log-parameters
      name: Log Parameters
      action: debug:log
      input:
        message: |
          Component: ${{ steps['fetchdata'].output}}  #### THIS IS WHERE I NEED INPUTS #####
```

I tried couple of different options, but I was not able to read the spec value or anything that I select.
It always prints _[object,object]_
Can someone help me here?  How can I read the values (catalog file data) from a **MultiEntityPicker** parameter.

### 👍 Expected behavior

   NA

### 👎 Actual Behavior with Screenshots

  NA

### 👟 Reproduction steps

NA

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None
