### ISSUE TITLE
🚀 Feature: Support multiple ids in placeholder remote files.

### ISSUE THREAD

**Issue by ronballesteros** [backstage/backstage#28248]
### 🔖 Feature description

Based on this [link](https://backstage.io/docs/features/software-templates/input-examples/#use-placeholders-to-reference-remote-files) we have the ability to use placeholders for remote yaml files.  It would be great if these remote files support more than one id.  I've tried multiple ways to get this to work, but don't think this is currently supported.

For example:
template.yaml:
```
spec:
  parameters:
    - $yaml: https://github.com/example/path/to/example.yaml
    - title: Fill in some steps
      properties:
        path:
          title: path
          type: string

  steps:
    - $yaml: https://github.com/example/path/to/action.yaml

    - id: fetch
      name: Fetch template
      action: fetch:template
      input:
        url: ${{ parameters.path if parameters.path else '/root' }}
```

action.yaml:
```
id: publish
name: Publish files
action: publish:github
input:
  repoUrl: ${{ parameters.url }}

id: publish2
name: Publish files2
action: publish:gitlab
input:
  repoUrl: ${{ parameters.url }}
```

### 🎤 Context

Our template is quite long where we templatize various helm, terraform files and I would like to just create a placeholder that involves the actions necessary for a particular topic.  For example, templatizing rabbitmq user k8s configuration, secrets, moving them to a certain directory, and creating a PR in one remote file than having to list them in the main template.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by ronballesteros** [comment]
Or is this even possible today?

**Comment by benjdlambert** [comment]
The issue here is that `action.yaml` is currently invalid yaml, so that's not going to work.

You could add `-` notation to each one, but then you wouldn't be able to merge that with additional `yaml`, as it would need to look like this:

```yaml
parameters: 
  $yaml: ../myfile.yaml
```

There is another issue about wanting to support something like that, and being able to then do something like this:


```yaml
parameters: 
  $yaml: ../myfile.yaml
  - id: something
    ...
```

Buut not sure how feasible that is either. We might just want to work out a nice way to express template composibility in the scaffolder instead.

**Comment by ronballesteros** [comment]
I was able to accomplish this as a work around thanks to the great help here as: https://github.com/backstage/backstage/issues/15241#issuecomment-2556724639.

Using that, I can have multiple steps in a yaml place holder which works out for me right now.  

Essentially I can do something like this:

```
steps:

    ################# LIVE BACKEND SERVICE #################

    # Templatize Live Helm
    - $yaml: https://github.com/acme/acme-infrastructure/tree/main/software-templates/snippets/steps/live/templatize-helm.yaml

    ## Templatize Live Helm RabbitMQ (if RabbitMQ is required)
    - $yaml: https://github.com/acme/acme-infrastructure/tree/main/software-templates/snippets/steps/live/templatize-helm-rabbitmq.yaml

    ## Templatize Live RabbitMQ User Resources (user info, secrets, password, etc)
    - $yaml: https://github.com/acme/acme-infrastructure/tree/main/software-templates/snippets/steps/live/generate-rabbitmq-user.yaml
```

And in each yaml, I can define multiple ids.
