### ISSUE TITLE
🐛 Bug Report: Error: No resolver found for key $defs.

### ISSUE THREAD

**Issue by hjoshi123** [backstage/backstage#28285]
### 📜 Description

As part of the backstage upgrade, I am trying to move to the new backend system. Removed all the default plugins that was part of the plugins folder and installed all the new packages and imported them. Cleaned up the package.json too. Once all of that was done tried starting up the frontend and backend but the backend errored out with a weird error message which doesn't help me debug at all. The frontend starts up fine though.

Stacktrace for the same is attached below

### 👍 Expected behavior

Backend should come up without any errors as part of the migration

### 👎 Actual Behavior with Screenshots

Errors out while starting the backend

### 👟 Reproduction steps

```
app:
  title: VIZIO Backstage Local Deployment
  # Should be the same as backend.baseUrl when using the `app-backend` plugin.
  baseUrl: http://localhost:3000
  extensions:
    - entity-card:announcements/announcements
    - nav-item:announcements
auth:
  environment: development
  providers:
    guest: {}
    github:
      development:
        clientId: ${GITHUB_CLIENT_ID}
        clientSecret: ${GITHUB_CLIENT_SECRET}
        signIn:
          resolvers:
            - resolver: usernameMatchingUserEntityName
            catalog:
  # Overrides the default list locations from app-config.yaml as these contain example data.
  # See https://backstage.io/docs/features/software-catalog/#adding-components-to-the-catalog for more details
  providers:
    githubOrg:
      - id: Vizio-Backstage
        githubUrl: 'https://github.com'
        orgs: ['BuddyTV', 'vizio-plat-svcs', 'vizio-ad-tech', 'CognitiveNetworks']
        schedule:
          frequency: PT60M
          timeout: PT15M

integrations:
  github:
    - host: github.com
      orgs:
        - BuddyTV
        - vizio-plat-svcs
        - vizio-ad-tech
        - CognitiveNetworks
      apps:
        - appId: ${GITHUB_APP_ID}
          privateKey: ${PRIV_KEY}
          clientId: ${GITHUB_CLIENT_ID}
          clientSecret: ${GITHUB_CLIENT_SECRET}
          webhookSecret: ${GITHUB_WEBHOOK_SECRET}
```

With the above app-catalog run `yarn dev`.

### 📃 Provide the context for the Bug.

Trying to migrate to new backend system. There are no custom plugins involved. 

```
backstage/node_modules/json-schema-merge-allof/src/index.js:314
[backend]:         if (!resolver) throw new Error('No resolver found for key ' + key + '. You can provide a resolver for this keyword in the options, or provide a default resolver.')
[backend]:                              ^
[backend]: 
[backend]: Error: No resolver found for key $defs. You can provide a resolver for this keyword in the options, or provide a default resolver.
[backend]:     at /Users/hemant.joshi/Documents/cpie-idp-backstage/backstage/node_modules/json-schema-merge-allof/src/index.js:314:30
[backend]:     at Array.forEach (<anonymous>)
[backend]:     at mergeSchemas (/Users/hemant.joshi/Documents/cpie-idp-backstage/backstage/node_modules/json-schema-merge-allof/src/index.js:301:13)
[backend]:     at Object.merger [as default] (/Users/hemant.joshi/Documents/cpie-idp-backstage/backstage/node_modules/json-schema-merge-allof/src/index.js:334:18)
[backend]:     at mergeConfigSchemas (/Users/hemant.joshi/Documents/cpie-idp-backstage/backstage/node_modules/@backstage/config-loader/src/schema/compile.ts:226:18)
[backend]:     at Object.compileConfigSchemas (/Users/hemant.joshi/Documents/cpie-idp-backstage/backstage/node_modules/@backstage/config-loader/src/schema/compile.ts:132:18)
[backend]:     at Object.loadConfigSchema (/Users/hemant.joshi/Documents/cpie-idp-backstage/backstage/node_modules/@backstage/config-loader/src/schema/load.ts:87:20)
[backend]:     at async Object.createConfigSecretEnumerator (/Users/hemant.joshi/Documents/cpie-idp-backstage/backstage/node_modules/@backstage/backend-defaults/src/entrypoints/rootConfig/createConfigSecretEnumerator.ts:32:6)
[backend]:     at async Object.factory (/Users/hemant.joshi/Documents/cpie-idp-backstage/backstage/node_modules/@backstage/backend-defaults/src/entrypoints/rootLogger/rootLoggerServiceFactory.ts:52:30)
[backend]:     at async Promise.all (index 0)
[backend]:     at async Promise.all (index 0)
[backend]:     at async Promise.all (index 0)
[backend]:     at async Promise.all (index 0)
[backend]:     at async Promise.all (index 0)
[backend]:     at async ServiceRegistry.initializeEagerServicesWithScope (/Users/hemant.joshi/Documents/cpie-idp-backstage/backstage/node_modules/@backstage/backend-app-api/src/wiring/ServiceRegistry.ts:242:11)
[backend]:     at async BackendInitializer.#doStart (/Users/hemant.joshi/Documents/cpie-idp-backstage/backstage/node_modules/@backstage/backend-app-api/src/wiring/BackendInitializer.ts:276:11)
[backend]: 
[backend]: Node.js v22.12.0
```

### 🖥️ Your Environment

Environment:

```
OS:   Darwin 23.6.0 - darwin/arm64
node: v22.12.0
yarn: 4.4.1
cli:  0.29.4 (installed)
backstage:  1.34.0
```

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by KangyiZengVizio** [comment]
I suspect this is yaml format problem, so I make sure there is no single quote in local.yaml file, but still could not resolve this error.

**Comment by benjdlambert** [comment]
Hmm, this looks like it's an issue with config as mentioned above.

I wanna call out this which looks a bit weird in your app config:

```
    github:
      development:
        clientId: ${GITHUB_CLIENT_ID}
        clientSecret: ${GITHUB_CLIENT_SECRET}
        signIn:
          resolvers:
            - resolver: usernameMatchingUserEntityName
            catalog:
```

The `catalog` at the bottom shouldn't be there, can you remove that and try again? 

That key should exist if you have any `catalog` config, but it's a root key and shouldn't be nested.

Alternatively, this could be something to do with config schema loading, but let's see if this works.
