### ISSUE TITLE
Simpler workflow for adding APIs to components

### ISSUE THREAD

**Issue by Fox32** [backstage/backstage#2834]
Creating a separate entity in your catalog-info.yaml is often more complicated than it should be. Especially as it might duplicate a lot of data from the component itself. And @stefanalund asked me to discuss this topic 😆 

## Feature Suggestion

After we removed the [`backstage.io/definition-at-location` annotation](https://backstage.io/docs/features/software-catalog/well-known-annotations#backstageiodefinition-at-location) that was responsible for embedding an API definition into a API entity, I propose a new annotation:

The new annotation works similar by specifying the location were the definition is located, however is not applied to the API entity, but to the component entity. The corresponding API entity is generated automatically with the details from the component and a relationship is added to the component.

## Possible Implementation

Let's have the following example component that has an `openapi.yaml` file in the same folder:

```yaml
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: petstore
  description: Petstore
  annotations:
    backstage.io/api-definition-openapi: ./openapi.yaml
spec:
  type: service
  lifecycle: experimental
  owner: pets@example.com
```

We could have a processor that generates the following output:

```yaml
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: petstore
  description: Petstore
  annotations:
    backstage.io/api-definition-openapi: ./openapi.yaml
spec:
  type: service
  lifecycle: experimental
  owner: pets@example.com
  implementsApis:
    - petstore-api
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: petstore-api
  description: Petstore
spec:
  type: openapi
  lifecycle: experimental
  owner: pets@example.com
  definition:
    $text: ./openapi.yaml
```

It copies the `description`, `lifecycle` and `owner` field. Not sure about annotations, I would skip them for now. The name is appended with an `-api` suffix. The `implementsApis` is added, or appended with the API name. The `definition` is added to the API entity using the substitution.

The big problem is the `type`: It depends of the format of the definition, but I can't really determine that. Sure we could build something, but it would have to operate on the content, as OpenAPI, AsyncAPI and other formats are using the `.yaml` extension. For that reason I name the annotation `backstage.io/api-definition-openapi`. The suffix at the end could either be a fixed (but configurable) set of suffixes (`backstage.io/api-definition-asyncapi`, `backstage.io/api-definition-grpc`, `backstage.io/api-definition-graphql`, ...) or we could match it against a regular expression and extract the `type` from the annotation name (`backstage.io/api-definition-(.*)`). I would be interested on your input here!

### Limits

This wouldn't work if a service implements multiple APIs, but I think that it's quite special. In that case one has to define a separate API entity. That is also required in cases were the API metadata should differ from the component (for example the API is defined by a different party than it is implemented by). 

## Context

While designing this I noticed that another kind of processor would be nice. Formats like AsyncAPI and OpenAPI already come with metadata like an API title. We could write a processor that extracts the title from these formats and writes it into the description of the API entity. This would be easy to implement, but is specific to the description format.

If that goes into the right direction, I'm open to contribute this.

**Comment by andrewthauer** [comment]
I was originally thinking having a generalized annotation key along with a type identifier in the value (e.g. `backstage.io/api-definition: openapi:./openapi.yaml`) might be an alternative. Although having multiple API's of the same type is unlikely, I think it might be more common to have both an `openapi` and `asyncapi` so having different annotation suffixes would allow for this. So this maybe having separate annotations for each API type makes the most sense.

**Comment by Rugvip** [comment]
Tbh I don't think multiple APIs from a single service is too uncommon? Wondering if there are some other ways to help out the yaml writer rather than adding the annotation.

In an ecosystem of catalog processors I think this makes sense as something to provide, but I think it's a bit too limited to build into the default catalog processors. Although to be fair at this stage of the project we can definitely add it and gauge usage, and perhaps move it away from the default set in the future. Still wanna dig a bit more to see if there's some other way to help out here, as it's far from an isolated request.

Couple of things that could help out:
1. If a `catalog-info.yaml` files contains more than one entity description, the `apiVersion` may be omitted on all entities but one. The first encountered `apiVersion` will be used for any entity that doesn't specify an explicit version.
2. `lifecycle`, `owner`, `system` etc. works similar to above. It may be omitted as long as it is specified in at least one of the entities.
3. APIs have a default description that reads "API exposed by the <name> service"
4. Any entity that is tied to a system will by default inherit the fields mentioned in (2) from the system

**Comment by Fox32** [comment]
> Tbh I don't think multiple APIs from a single service is too uncommon?

Yeah, thats probably right. I have at least one service in my team that implements even two APIs of the same type (two OpenAPI based descriptions). Having a service with different API types, like OpenAPI and AsyncAPI, is a very common pattern for us.
Sometimes I wish I could add more complicated constructs into annotation that just strings 😉, like a list. But as an alternative we could also extend the spec itself with such features. Like passing an object with name and url into the `implementsApis` array.

What I don't like about your points 1., 2. and 4. is that they feel like kind of magic. I think there has to be some kind of construct where the user understand why it behaves that way. Maybe an explicit section at the top of the YAML file that contains fields that are applied to all entities?

Btw, I did a quick implementation in #2840 as a basis for discussion.

**Comment by Rugvip** [comment]
> Sometimes I wish I could add more complicated constructs into annotation that just strings 😉, like a list. But as an alternative we could also extend the spec itself with such features. Like passing an object with name and url into the `implementsApis` array.

In k8s I a common way to do this is to serialize the more complex structure as JSON. That's obviously not nice to write by hand and could actually be something to investigate.

> What I don't like about your points 1., 2. and 4. is that they feel like kind of magic. I think there has to be some kind of construct where the user understand why it behaves that way. Maybe an explicit section at the top of the YAML file that contains fields that are applied to all entities?

Agreed, should not add anything like that without good reason and many other options being considered. Just wanna bring in the mindset of searching for broader solutions for these problems that are likely to pop up a lot. Especially the "this is too verbose" problem is very often something that shouldn't be solved at all, as it's often really not that bad and the extra information helps with discoverability.

Tbh the proposed annotation solution is also kind of magic right? Imagine a user browsing Backstage and finding the `petstore-api` and wanting to look that up. We can ofc add links and relations in the right places, but there's still some magic going on.

Regarding the things I mentioned (not suggestions), I'm somewhat intrigued by (1), as in having some way to not have to define the `apiVersion`. Tbh it could even be a Backstage-wide default but that'd have to be something that gets a bit of battle testing before we'd recommend it.

I don't like (2) much at all, and it feels way too magic. (3) is kinda meh, I think it's better to not be that level of lazy xP. (4) is something that has been specifically requested in out internal version and something we should investigate, but probably with a smaller set of fields, perhaps only `owner`.

**Comment by freben** [comment]
If we want some "less magic magic", I would prefer a default-values mechanism. Like having at the top of your file

```yaml
defaults:
  apiVersion: foo
  spec:
    owner: bar
----
# other entities 
```

or what if that top part was in a separate `backstage.yaml` file, possibly even higher in the folder structure, and it applies to everything below - kinda like codeowners but for any field

**Comment by Fox32** [comment]
> Tbh the proposed annotation solution is also kind of magic right?

Yeah that's right 😁

> If we want some "less magic magic", I would prefer a default-values mechanism

That's more what I thought about, instead of just comping from the first entity in a file.

**Comment by freben** [comment]
I've been thinking about this one.

There's already a field for linking to APIs that the component implements. That one was added pretty haphazardly. Now we reach for annotations to solve a lot of lacking expressivity. I think that maybe annotations aren't the way to go.

The ultimate reason for the existence of the `implementsApis` key, is as a generator for [relationships](https://github.com/spotify/backstage/issues/1964). That's all they are for; eventually, we will want people to read the new `relationships` key (whatever its name will be) to actually consume the list of relationships, not the `spec` key - because relationships may come into existence in any of a multitude of ways, including being auto-generated by ingesting third party resources, or by the very existence of an openapi spec file next to the catalog-info file. The spec keys may contain only a subset of the actual APIs it implements.

I am pondering a few options,

## Extend the expressivity of implementsApis

```yaml
spec:
  implementsApis:
    - location: ./openapi.yaml
      type: openapi
```

This could be made backwards compatible, by making the string form a shorthand for `{ type: ref, ref: <thestring>  }`. Or just using the string form, and detecting that it starts with `.` or contains `://` to interpret as a URL. The latter requires us to be able to autodetect the format.

## Add a purpose built sibling to implementsApis

```yaml
spec:
  implementsApis:
    - api:default/some-api
  generatesApis:
    - location: ./openapi.yaml
      type: openapi
```

## Design a general way of expressing relationships as a user

user entered yaml:

```yaml
relationships:
  - type: implementsApi
    file: ./openapi.yaml
```

output when querying the catalog:

```yaml
relationships:
  - from: <ref to me>
    type: implementsApi
    to: <ref to the generated entity>
  - from: <ref to the generated entity>
    type: apiIsImplementedBy
    to: <ref to me>
```

or maybe it's clearer to name the input key `generateRelationships`
