### ISSUE TITLE
🚀 Feature: Exclude certain entity kinds from search 

### ISSUE THREAD

**Issue by jcwang-domain** [backstage/backstage#28356]
### 🔖 Feature description

Do we have any new documentation on how to limit what can be searched in the Software Catalog?
https://backstage.io/docs/features/search/how-to-guides#how-to-limit-what-can-be-searched-in-the-software-catalog

### 🎤 Context

This page was created two years ago, and we've upgraded the backend. The file is now out of date. Do we have any new documentation for it?

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by camilaibs** [comment]
IIRC you can configure what entity kinds to index thorught the [Catalog search collator module](https://github.com/backstage/backstage/tree/master/plugins/search-backend-module-catalog). The value of the `search.collators.catalog.filter.kind` config is the same as the catalog query entities request:

```yaml
search:
  collators:
    catalog:
      batchSize: 5000
      filter:
        kind: ['API', 'Component', 'Subcomponent', 'Template', 'System', 'Domain']
```
The value of the `search.collators.catalog.filter.kind` config is the same as the catalog query entities request:

https://github.com/backstage/backstage/blob/master/plugins/search-backend-module-catalog/src/collators/DefaultCatalogCollatorFactory.ts#L107
