### ISSUE TITLE
🐛 Bug Report: Missing session cookie in Github Authentication

### ISSUE THREAD

**Issue by pragmaticivan** [backstage/backstage#28355]
### 📜 Description

Currently using both Github and Okta authentications.

Only the Okta one works.

The github one gives me:

```
{
    "error": {
        "name": "AuthenticationError",
        "message": "Refresh failed; caused by InputError: Missing session cookie",
        "cause": {
            "name": "InputError",
            "message": "Missing session cookie"
        }
    },
    "request": {
        "method": "GET",
        "url": "/api/auth/github/refresh?optional&scope=read%3Auser&env=staging"
    },
    "response": {
        "statusCode": 401
    }
}
```

This currently works on localhost, but fails in a custom deployment environment using the k8s helm chart.

### 👍 Expected behavior

Should be able to authenticate like it does with localhost.

### 👎 Actual Behavior with Screenshots

```
{
    "error": {
        "name": "AuthenticationError",
        "message": "Refresh failed; caused by InputError: Missing session cookie",
        "cause": {
            "name": "InputError",
            "message": "Missing session cookie"
        }
    },
    "request": {
        "method": "GET",
        "url": "/api/auth/github/refresh?optional&scope=read%3Auser&env=staging"
    },
    "response": {
        "statusCode": 401
    }
}
```

### 👟 Reproduction steps

Using the latest version of backstage and all other plugins.

Just configure auth like in the docs and it will fail.

### 🖥️ Your Environment

```yml
app:
  title: EverQuote Backstage - Staging
  baseUrl: https://backstage.redacted.redacted.redacted.redacted.redacted.redacted

backend:
  baseUrl: https://backstage.redacted.redacted.redacted.redacted.redacted.redacted
  # config options: https://node-postgres.com/apis/client
  database:
    client: pg
    connection:
      REDACTED
  cors:
    origin: https://backstage.redacted.redacted.redacted.redacted.redacted.redacted
    methods: [GET, HEAD, PATCH, POST, PUT, DELETE]
    credentials: true
auth:
  environment: staging
  providers:
    okta:
      staging:
        clientId: ${AUTH_OKTA_CLIENT_ID}
        clientSecret: ${AUTH_OKTA_CLIENT_SECRET}
        audience: ${AUTH_OKTA_AUDIENCE}
        # additionalScopes: githubUsername - https://github.com/backstage/backstage/issues/27994
    github:
      staging:
        clientId: ${GITHUB_APP_CLIENT_ID}
        clientSecret: ${GITHUB_CLIENT_SECRET}
        signIn:
          resolvers:
          - resolver: usernameMatchingUserEntityName

```

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else
