### ISSUE TITLE
🐛 Bug Report: Unable to register the catalog using gitlab auth user 

### ISSUE THREAD

**Issue by rakeshreddyrg09** [backstage/backstage#28357]
### 📜 Description

I have integrated backstage with GitLab for authentication. I am using `gitlab:group:ensureExists` to create a group and project.
```yaml
- id: ensure-gitlab-group
  name: Ensure GitLab Group Exists
  action: gitlab:group:ensureExists
  input:
    repoUrl: ${{ parameters.repoUrl }}
    token: ${{ secrets.USER_OAUTH_TOKEN }}
    path: ${{ parameters.groupPath }}
```
Once it is create we are trying to register the project back to the backstage, but the backstage integration token do not have access to this group. Also catalog register do not have option to pass the `USER_OAUTH_TOKEN`
```yaml
- id: register
  name: Register Component
  action: catalog:register
  input:
    repoContentsUrl: ${{ steps['publish'].output.repoContentsUrl }}
    catalogInfoPath: '/catalog-info.yaml'
    optional: true
```
right now we are giving access in the GitLab group manually, is there a way to achieve this automatically using the backstage?

### 👍 Expected behavior

NA

### 👎 Actual Behavior with Screenshots

NA

### 👟 Reproduction steps

NA

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None
