### ISSUE TITLE
🐛 Bug Report: My Squads sidebar shows the metadata name of the group, instead of the spec displayName

### ISSUE THREAD

**Issue by 03DhruvJoshi** [backstage/backstage#28363]
### 📜 Description

When accessing the squads the user is part of from the sidebar, the metadata name gets displayed for each squad. They should instead use the displayName - This approach makes it easier for the logged in user to switch between squads as the actual title of the group will be displayed in the sidebar instead of the metadata. 

### 👍 Expected behavior

It is expected/ideal for the sidebar squad titles to use the displayName of the group, as in group.spec.profile.displayName 

You can notice that in the webpage of a specific Group, the title belongs to the displayName of a Group, we would like to replicate this into the sidebar as well for conveniency. 
![image](https://github.com/user-attachments/assets/e90e228b-d2ec-4c87-b5ed-5f5b624a5df3)

### 👎 Actual Behavior with Screenshots

The sidebar list for My Squads displays the name of the squad from the metadata name like so 
![image](https://github.com/user-attachments/assets/ddfb54e9-cc67-4e69-9e0d-1216b40419c8)

### 👟 Reproduction steps

**Note: Only works if you are part of multiple squads**

1. Launch your Backstage IDP and hover onto the 'My Squads' from the sidebar
2. You will see the list of squads you are part in - however the title for each of these squads corresponds to the metadata instead of spec displayName 

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by awanlin** [comment]
Hi @03DhruvJoshi, currently it tries to use the `metadata.title` and then the `metadata.name` as seen here:

https://github.com/backstage/backstage/blob/41ab5cf4a08ea835e57c5bd482218a96eb068d0c/plugins/org/src/components/MyGroupsSidebarItem/MyGroupsSidebarItem.tsx#L99

There's two ways this could be fixed:

1. We update the above to use the `spec.profile.displayName` and then fall back to the current options
2. We update the above to use the Presentation API which would handle this and is intended as a somewhat universal solution for these cases. More details here: https://github.com/backstage/backstage/pull/17474

If we move forward I think option 2 should be the way forward 👍 


@freben, could you share your thoughts on direction for this one, please?

**Comment by 03DhruvJoshi** [comment]
> Hi @03DhruvJoshi, currently it tries to use the `metadata.title` and then the `metadata.name` as seen here:
> 
> https://github.com/backstage/backstage/blob/41ab5cf4a08ea835e57c5bd482218a96eb068d0c/plugins/org/src/components/MyGroupsSidebarItem/MyGroupsSidebarItem.tsx#L99
> 
> There's two ways this could be fixed:
> 
> 1. We update the above to use the `spec.profile.displayName` and then fall back to the current options
> 2. We update the above to use the Presentation API which would handle this and is intended as a somewhat universal solution for these cases. More details here: [An `entityPresentationApiRef`, for rendering rich entity refs #17474](https://github.com/backstage/backstage/pull/17474)
> 
> If we move forward I think option 2 should be the way forward 👍
> 
> @freben, could you share your thoughts on direction for this one, please?

Hi @awanlin, thank you for the suggestions. I had a bit of research over the two options and I confirm we should stick to the second option as such cases would be more centralized. I have implemented the second option and it is successfully showing up the displayName of the entities - if there is no displayName property for the entity then it returns the metadata.name which is exactly what we expect. 

Therefore, I would be creating a PR following the changes and I will appreciate your reviews 👍

**Comment by fabiojvalente** [comment]
I've noticed #28376 was merged but am still having this in the 1.36.0 release and also on 
commit `d3bb3570408d82f7db745b12f6275a4ba7789a16` (last on `master` at the time i've tested)

I have set team-a to include a display name as per the example shown below, but am still getting team.metadata.name in the sidebar

```yaml
---
## Group definition
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: team-a
  description: Team A
spec:
  type: team
  profile:
    displayName: Team A A A
    email: team-a@example.com
    picture: https://api.dicebear.com/7.x/identicon/svg?seed=Fluffy&backgroundType=solid,gradientLinear&backgroundColor=ffd5dc,b6e3f4
  parent: backstage
  children: []

---
# guest user definition
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: guest
  namespace: development
spec:
  profile:
    displayName: Guest User
    email: guest@example.com
  memberOf: [group:default/team-a, group:default/team-b]
```
