### ISSUE TITLE
🐛 Bug Report: Nunjucks not working as expected

### ISSUE THREAD

**Issue by elisecasey** [backstage/backstage#28382]
### 📜 Description

Trying to use additionalTemplateGlobals values to populate a template

### 👍 Expected behavior

When template.yaml contains this: 
```
serviceZone:
                title: Service Zone
                type: string
                description: "The event's service zone"
                # Add any additional partner zones here
                enum: 
                - ${{ serviceZones }}
                enumNames: 
                - ${{ serviceZoneNames }}
```
and scaffolder.ts contains this:
```
return await createRouter({
    actions: actions,
    logger: env.logger,
    config: env.config,
    database: env.database,
    reader: env.reader,
    catalogClient: catalogClient,
    identity: env.identity,
    additionalTemplateGlobals: {
      serviceZones: "hello world",
      serviceZoneNames: "Hello World",
    },
  });
```
The "Service Zone" dropdown should contain "Hello World" 

### 👎 Actual Behavior with Screenshots

The "Service Zone" dropdown contains ${{ serviceZoneNames }} as an option.
<img width="766" alt="image" src="https://github.com/user-attachments/assets/cdceeff3-a82f-421a-aef6-a7d49023b6ad" />

### 👟 Reproduction steps

Described in "Expected behavior" section

### 🖥️ Your Environment

Using apiVersion: scaffolder.backstage.io/v1beta3

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None
