### ISSUE TITLE
Addition of enumNames in a multiple choice list of software template , which will hiding the essential information

### ISSUE THREAD

**Issue by Shubhanshu777** [backstage/backstage#28459]
### 🔖 General

In Backstage, within the software template, we currently use **enum** and **enumNames** to define options for parameters. The enumNames are displayed to the user on the interface, while the corresponding enum values are sent to the backend for processing.

Additionally, on the review page, we want to ensure that users see only the enumNames instead of the enum values. This is because the enum values are backend-specific and not meant to be exposed to users.

For eg :
```
parameters:
  - title: Fill in some steps
    properties:
      volume_type:
        title: Volume Type
        type: string
        description: The volume type to be used
        default: gp2
        enum:
          - gp2
        enumNames:
          - 'General Purpose SSD `(gp2)'`
```

Currently, when we have a multiple-choice list, it displays only the **enum** values. However, I want to enhance this functionality so that the review page shows the **enumNames** as well. This way, users will only see the more descriptive and user-friendly enumNames, maintaining a clean and intuitive user experience while keeping backend details hidden

### 💻 Usage

```
parameters:
  - title: Fill in some steps
    properties:
      name:
        title: Select environments
        type: array
        items:
          type: string
          enum:
            - production
            - staging
            - development
        uniqueItems: true
        ui:widget: checkboxes
```

So if we have enumNames in this , that would be useful

### 📐 Specs

no sigma

### 👀 Have you spent some time to check if this UX Component request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)
