### ISSUE TITLE
Problem with Publish Step in Template using Docker

### ISSUE THREAD

**Issue by anja1997** [backstage/backstage#28473]
### 🔖 Need

# Problem with Publish Step in Template using Docker

We are experiencing issues with the **Publish** step in our Backstage portal when running it inside Docker. The template works fine when running `yarn dev` but fails in Docker. `TypeError: Cannot read properties of undefined (reading 'replace')`
Below are the details.

## Logs

```plaintext
[31](https://dev.backstage.devtest.gf.aws.company.com/#line-31)2025-01-14T14:22:56.000Z Finished step Fetch Skeleton + Template  
[32](https://dev.backstage.devtest.gf.aws.company.com/#line-32)2025-01-14T14:22:56.000Z Beginning step Publish  
[33](https://dev.backstage.devtest.gf.aws.company.com/#line-33)2025-01-14T14:22:58.000Z TypeError: Cannot read properties of undefined (reading 'replace')  
[34](https://dev.backstage.devtest.gf.aws.company.com/#line-34)    at Object.handler (/app/node_modules/@backstage/plugin-scaffolder-backend-module-gitlab/dist/actions/gitlab.cjs.js:306:42)  
[35](https://dev.backstage.devtest.gf.aws.company.com/#line-35)    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)  
[36](https://dev.backstage.devtest.gf.aws.company.com/#line-36)    at async NunjucksWorkflowRunner.executeStep (/app/node_modules/@backstage/plugin-scaffolder-backend/dist/scaffolder/tasks/NunjucksWorkflowRunner.cjs.js:234:9)  
[37](https://dev.backstage.devtest.gf.aws.company.com/#line-37)    at async NunjucksWorkflowRunner.execute (/app/node_modules/@backstage/plugin-scaffolder-backend/dist/scaffolder/tasks/NunjucksWorkflowRunner.cjs.js:340:9)  
[38](https://dev.backstage.devtest.gf.aws.company.com/#line-38)    at async TaskWorker.runOneTask (/app/node_modules/@backstage/plugin-scaffolder-backend/dist/scaffolder/tasks/TaskWorker.cjs.js:96:26)  
[39](https://dev.backstage.devtest.gf.aws.company.com/#line-39)    at async run (/app/node_modules/p-queue/dist/index.js:163:29)
```

## Template

```yaml
apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: create-react-app-template
  title: Create React App Template
  description: Create a new CRA website project
  tags:
    - react
    - cra
spec:
  owner: WEB@EXAMPLE.COM
  type: website

  parameters:
    - title: Provide some simple information
      required:
        - component_id
        - owner
      properties:
        component_id:
          title: Name
          type: string
          description: Unique name of the component
          ui:field: EntityNamePicker
        description:
          title: Description
          type: string
          description: Help others understand what this website is for.
        owner:
          title: Owner
          type: string
          description: Owner of the component
          ui:field: OwnerPicker
          ui:options:
            allowedKinds:
              - User
    - title: Choose a location
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - gitlab.company.com  # Change to your self-hosted GitLab domain
  steps:
    - id: template
      name: Fetch Skeleton + Template
      action: fetch:template
      input:
        url: ./resourcesTemplates/skeletonreact
        values:
          component_id: ${{ parameters.component_id }}
          description: ${{ parameters.description }}
          destination: ${{ parameters.repoUrl | parseRepoUrl }}
          owner: ${{ parameters.owner }}

    - id: publish
      name: Publish
      action: publish:gitlab
      input:
        description: This is a test
        repoUrl: gitlab.company.com?repo=${{ parameters.component_id }}&owner=devtools/labs/devex/examples

    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps.publish.output.repoContentsUrl }}
        catalogInfoPath: "/catalog-info.yaml"

  output:
    links:
      - title: Repository
        url: ${{ steps.publish.output.remoteUrl }}
      - title: Open in catalog
        icon: catalog
        entityRef: ${{ steps.register.output.entityRef }}
```

## Dockerfile

```dockerfile
FROM node:20-bookworm-slim AS packages

WORKDIR /app
COPY backstage.json package.json yarn.lock ./
COPY .yarn ./.yarn
COPY .yarnrc.yml ./

COPY packages packages

RUN find packages \! -name "package.json" -mindepth 2 -maxdepth 2 -exec rm -rf {} \+

FROM node:20-bookworm-slim AS build

ENV PYTHON=/usr/bin/python3

RUN --mount=type=cache,target=/var/cache/apt,sharing=locked     --mount=type=cache,target=/var/lib/apt,sharing=locked     apt-get update &&     apt-get install -y --no-install-recommends python3 g++ build-essential &&     rm -rf /var/lib/apt/lists/*

RUN --mount=type=cache,target=/var/cache/apt,sharing=locked     --mount=type=cache,target=/var/lib/apt,sharing=locked     apt-get update &&     apt-get install -y --no-install-recommends libsqlite3-dev &&     rm -rf /var/lib/apt/lists/*

USER node
WORKDIR /app

COPY --from=packages --chown=node:node /app .
COPY --from=packages --chown=node:node /app/.yarn ./.yarn
COPY --from=packages --chown=node:node /app/.yarnrc.yml  ./
COPY --from=packages --chown=node:node /app/backstage.json ./

RUN yarn cache clean

RUN --mount=type=cache,target=/home/node/.cache/yarn,sharing=locked,uid=1000,gid=1000     yarn install --immutable

COPY --chown=node:node . .

RUN yarn tsc
RUN yarn --cwd packages/backend build

RUN mkdir packages/backend/dist/skeleton packages/backend/dist/bundle     && tar xzf packages/backend/dist/skeleton.tar.gz -C packages/backend/dist/skeleton     && tar xzf packages/backend/dist/bundle.tar.gz -C packages/backend/dist/bundle

FROM node:20-bookworm-slim

ENV PYTHON=/usr/bin/python3

RUN --mount=type=cache,target=/var/cache/apt,sharing=locked     --mount=type=cache,target=/var/lib/apt,sharing=locked     apt-get update &&     apt-get install -y --no-install-recommends python3 g++ build-essential &&     rm -rf /var/lib/apt/lists/*

RUN --mount=type=cache,target=/var/cache/apt,sharing=locked     --mount=type=cache,target=/var/lib/apt,sharing=locked     apt-get update &&     apt-get install -y --no-install-recommends libsqlite3-dev &&     rm -rf /var/lib/apt/lists/*

USER node

WORKDIR /app

COPY --from=build --chown=node:node /app/.yarn ./.yarn
COPY --from=build --chown=node:node /app/.yarnrc.yml  ./
COPY --from=build --chown=node:node /app/backstage.json ./
COPY --from=build --chown=node:node /app/yarn.lock /app/package.json /app/packages/backend/dist/skeleton/ ./

RUN --mount=type=cache,target=/home/node/.cache/yarn,sharing=locked,uid=1000,gid=1000     yarn workspaces focus --all --production && rm -rf "$(yarn cache clean)"

COPY --from=build --chown=node:node /app/packages/backend/dist/bundle/ ./

COPY --from=build --chown=node:node /app/packages/templates /app/packages/templates

COPY --from=build --chown=node:node /app/packages/templates/resourcesTemplates /app/packages/templates/resourcesTemplates

COPY --chown=node:node app-config*.yaml ./

ENV NODE_ENV=production

ENV NODE_OPTIONS="--no-node-snapshot"

CMD ["node", "packages/backend", "--config", "app-config.yaml", "--config", "app-config.production.yaml"]
```

### 🎉 Proposal

We analyzed the publish:gitlab action in the Backstage Scaffolder plugin, focusing on how the repoUrl parameter was processed. This was compared to running locally.

We need to understand why the replace function fails when running in docker. 

### 👀 Have you spent some time to check if this RFC has been raised before?

- [x] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [x] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)
