### ISSUE TITLE
🐛 Bug Report: Kubernetes plugin certificate attachment and skipTlsverify not working

### ISSUE THREAD

**Issue by Nagaarjune** [backstage/backstage#28486]
### 📜 Description

As we installed and integrated Kubernetes plugins in our application , we tried connecting AKS from azure portal. And our application is deployed in internal network and  we connected Openshift clusters using service account token and its working. . But we have proper proxy for connecting external networks and its all are working. And we tried connecting aks from azure portal which is in internet(outside network from our application) using auth provider as azure and we got certificate and attached with our environment value of NODE_EXTRA_CA_CERTS and its working. Instead  we tried connecting azure AKS cluster which is in internet(outside network from our application) using caFile param as well as skipTLSVerify enabled

```
kubernetes:
  serviceLocatorMethod:
    type: multiTenant
  clusterLocatorMethods:
    - type: config
      clusters:
        - url: http://aks-api-url
          name:aksname
          authProvider: azure
          skipTLSVerify: "true"
          or
          caFile: path-to-certificate/ca.cert.cer
```

and we tried with curl request both adding certificate and with -k flag its working . so in application only not working

### 👍 Expected behavior

It should display the cluster and pod details like how its working for attached certificate

### 👎 Actual Behavior with Screenshots

It showing unable attach first certificate.
There was a problem retrieving some Kubernetes resources for the entity: bode-portal. This could mean that the Error Reporting card is not completely accurate.

Errors:
Cluster: aksname

Error communicating with Kubernetes: FETCH_ERROR, message: request to https://aksurl/api/v1/namespaces/kube-system/configmaps?labelSelector=labelvalue failed, reason: unable to verify the first certificate

### 👟 Reproduction steps

(We are connecting through proxy for connecting resources available in internet because our application is in local network)

1,In app-config.yaml in kubernetes section pls fill valid aks info(i shared my config values) and register catalog valid kubernetes annotation and go to kubernetes tab inside catalog component and it will display the above mentioned error.

```
kubernetes:
  serviceLocatorMethod:
    type: multiTenant
  clusterLocatorMethods:
    - type: config
      clusters:
        - url: http://aks-api-url
          name:aksname
          authProvider: azure
          skipTLSVerify: "true"
          or
          caFile: path-to-certificate/ca.cert.cer
```
### 📃 Provide the context for the Bug.

We tried to access Kubernetes details using Kubernetes plugin provided by backstage community

### 🖥️ Your Environment

node: v18.18.2
yarn: 1.22.22
cli: 0.26.11 (installed)
backstage: 1.26.3

### 👀 Have you spent some time to check if this bug has been raised before?

- [x] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [x] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, I don't have time to work on this right now
