### ISSUE TITLE
🐛 Bug Report: publish:gitlab into group doesn't work as documented

### ISSUE THREAD

**Issue by davidgiga1993** [backstage/backstage#28519]
### 📜 Description

Publishing a repo into a gitlab group that was created by the scaffolder does not work [as documented](https://github.com/backstage/backstage/tree/master/plugins/scaffolder-backend-module-gitlab):

From the docs:
```
    - id: publish
      name: Publish
      action: publish:gitlab
      input:
        description: This is ${{ parameters.name }}
        repoUrl: ${{ parameters.repoUrl }}?owner=${{ steps.createGitlabGroup.output.groupId }}
        sourcePath: pimcore
        defaultBranch: main
```

As the `parameters.repoUrl` from the `RepoUrlPicker` already contains a `owner` query parameter, the url will be invalid. Here is an example from my dev setup:

```
gitlab.com?owner=backstage-david-test&repo=test?owner=622510
```

### 👍 Expected behavior

The repo should be created in the specified group or the documentation should be updated to specify a different way to archive this.

### 👎 Actual Behavior with Screenshots

Gitlab responds (correctly) with bad request as the API is called incorrectly due to the two `owner` query parameters.

### 👟 Reproduction steps

1. Use the given template

```yaml
apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: test-golang
  title: Golang Bootstrap
  description: Golang bootstrap
spec:
  owner: user:guest
  type: service
  parameters:
    - title: Metadata
      required:
        - productName
        - serviceName
      properties:
        productName:
          title: Product Name
          type: string
          description: Name of the product, used as toplevel gitlab group name
          default: backstage-david-test

          ui:autofocus: true
          ui:options:
            rows: 5
        serviceName:
          title: Service Name
          type: string
          description: Name of the service, used as repo name
          default: go-service
          ui:options:
            rows: 5

    - title: Choose a location
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Location to create the group/repo structure
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - gitlab.com
            requestUserCredentials:
              secretsKey: USER_OAUTH_TOKEN

  steps:
    - id: fetch-base
      name: Fetch Base
      action: fetch:template
      input:
        url: ./content
        values:
          name: ${{ parameters.serviceName }}

    # Create gitlab hierarchy
    # We intentionally use separate steps to allow
    # further repo creation in the different subgroups
    - id: product-group
      name: Gitlab product group
      action: gitlab:group:ensureExists
      input:
        token: ${{ secrets.USER_OAUTH_TOKEN }}
        repoUrl: ${{ parameters.repoUrl }}
        path:
          - ${{ parameters.productName }}

    - id: sw-group
      name: Gitlab software components group
      action: gitlab:group:ensureExists
      input:
        token: ${{ secrets.USER_OAUTH_TOKEN }}
        repoUrl: ${{ parameters.repoUrl }}
        path:
          - ${{ parameters.productName }}
          - sw-components

    - id: env-group
      name: Gitlab environment group
      action: gitlab:group:ensureExists
      input:
        token: ${{ secrets.USER_OAUTH_TOKEN }}
        repoUrl: ${{ parameters.repoUrl }}
        path:
          - ${{ parameters.productName }}
          - environment

    - id: toolchain-group
      name: Gitlab toolchain group
      action: gitlab:group:ensureExists
      input:
        token: ${{ secrets.USER_OAUTH_TOKEN }}
        repoUrl: ${{ parameters.repoUrl }}
        path:
          - ${{ parameters.productName }}
          - environment
          - toolchain

    - id: publish
      name: Publish
      action: publish:gitlab
      input:
        allowedHosts: [ 'gitlab.com' ]
        description: ""
        repoUrl: ${{ parameters.repoUrl }}?owner=${{ steps['sw-group'].output.groupId }}
        token: ${{ secrets.USER_OAUTH_TOKEN }}

    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps['publish'].output.repoContentsUrl }}
        catalogInfoPath: '/catalog-info.yaml'

  output:
    links:
      - title: Repository
        url: ${{ steps['publish'].output.remoteUrl }}
      - title: Open in catalog
        icon: catalog
        entityRef: ${{ steps['register'].output.entityRef }}

```

### 📃 Provide the context for the Bug.

I'm trying to create a group hierarchy in gitlab and publish a repo into one of those groups.
As the group doesn't exist before the scaffolder run it can't be selected. However I still need the `RepoUrlPicker` UI component to get the authorization from the user.

Ideally there would be a separate UI component just for authorization, without a group/repo selection (as this will be created by the scaffolder).

### 🖥️ Your Environment

OS:   Windows_NT 10.0.19045 - win32/x64
node: v22.11.0
yarn: 4.4.1
cli:  0.29.4 (installed)
backstage:  1.34.2

Dependencies:
  @backstage/app-defaults                                          1.5.15
  @backstage/backend-app-api                                       1.1.0
  @backstage/backend-common                                        0.25.0
  @backstage/backend-defaults                                      0.6.0, 0.6.2
  @backstage/backend-dev-utils                                     0.1.5
  @backstage/backend-openapi-utils                                 0.4.0
  @backstage/backend-plugin-api                                    1.0.2, 1.1.0
  @backstage/backend-test-utils                                    1.2.0
  @backstage/catalog-client                                        1.8.0, 1.9.0
  @backstage/catalog-model                                         1.7.1, 1.7.2
  @backstage/cli-common                                            0.1.15
  @backstage/cli-node                                              0.2.11
  @backstage/cli                                                   0.29.4
  @backstage/config-loader                                         1.9.2, 1.9.3, 1.9.4
  @backstage/config                                                1.3.0, 1.3.1
  @backstage/core-app-api                                          1.15.3
  @backstage/core-compat-api                                       0.3.4
  @backstage/core-components                                       0.16.2
  @backstage/core-plugin-api                                       1.10.2
  @backstage/e2e-test-utils                                        0.1.1
  @backstage/errors                                                1.2.5, 1.2.6
  @backstage/eslint-plugin                                         0.1.10
  @backstage/frontend-app-api                                      0.10.3
  @backstage/frontend-defaults                                     0.1.4
  @backstage/frontend-plugin-api                                   0.9.3
  @backstage/frontend-test-utils                                   0.2.4
  @backstage/integration-aws-node                                  0.1.13, 0.1.14
  @backstage/integration-react                                     1.2.2
  @backstage/integration                                           1.15.2, 1.16.0
  @backstage/plugin-api-docs                                       0.12.2
  @backstage/plugin-app-backend                                    0.4.3
  @backstage/plugin-app-node                                       0.1.28
  @backstage/plugin-app                                            0.1.4
  @backstage/plugin-auth-backend-module-atlassian-provider         0.3.3
  @backstage/plugin-auth-backend-module-auth0-provider             0.1.3
  @backstage/plugin-auth-backend-module-aws-alb-provider           0.3.1
  @backstage/plugin-auth-backend-module-azure-easyauth-provider    0.2.3
  @backstage/plugin-auth-backend-module-bitbucket-provider         0.2.3
  @backstage/plugin-auth-backend-module-bitbucket-server-provider  0.1.3
  @backstage/plugin-auth-backend-module-cloudflare-access-provider 0.3.3
  @backstage/plugin-auth-backend-module-gcp-iap-provider           0.3.3
  @backstage/plugin-auth-backend-module-github-provider            0.2.3
  @backstage/plugin-auth-backend-module-gitlab-provider            0.2.3
  @backstage/plugin-auth-backend-module-google-provider            0.2.3
  @backstage/plugin-auth-backend-module-guest-provider             0.2.3
  @backstage/plugin-auth-backend-module-microsoft-provider         0.2.3
  @backstage/plugin-auth-backend-module-oauth2-provider            0.3.3
  @backstage/plugin-auth-backend-module-oauth2-proxy-provider      0.2.3
  @backstage/plugin-auth-backend-module-oidc-provider              0.3.3
  @backstage/plugin-auth-backend-module-okta-provider              0.1.3
  @backstage/plugin-auth-backend-module-onelogin-provider          0.2.3
  @backstage/plugin-auth-backend                                   0.24.1
  @backstage/plugin-auth-node                                      0.5.4, 0.5.5
  @backstage/plugin-auth-react                                     0.1.10
  @backstage/plugin-bitbucket-cloud-common                         0.2.26
  @backstage/plugin-catalog-backend-module-gitlab                  0.6.1
  @backstage/plugin-catalog-backend-module-logs                    0.1.5
  @backstage/plugin-catalog-backend-module-scaffolder-entity-model 0.2.3
  @backstage/plugin-catalog-backend                                1.29.0
  @backstage/plugin-catalog-common                                 1.1.2
  @backstage/plugin-catalog-graph                                  0.4.14
  @backstage/plugin-catalog-import                                 0.12.8
  @backstage/plugin-catalog-node                                   1.15.0
  @backstage/plugin-catalog-react                                  1.15.0
  @backstage/plugin-catalog                                        1.26.0
  @backstage/plugin-events-node                                    0.4.6
  @backstage/plugin-kubernetes-backend                             0.19.1
  @backstage/plugin-kubernetes-common                              0.9.1
  @backstage/plugin-kubernetes-node                                0.2.1
  @backstage/plugin-kubernetes-react                               0.5.2
  @backstage/plugin-kubernetes                                     0.12.2
  @backstage/plugin-org                                            0.6.34
  @backstage/plugin-permission-backend-module-allow-all-policy     0.2.3
  @backstage/plugin-permission-backend                             0.5.52
  @backstage/plugin-permission-common                              0.8.2, 0.8.3
  @backstage/plugin-signals-react                                  0.0.8
  @backstage/plugin-techdocs-backend                               1.11.4
  @backstage/plugin-techdocs-common                                0.1.0
  @backstage/plugin-techdocs-module-addons-contrib                 1.1.19
  @backstage/plugin-techdocs-node                                  1.12.15
  @backstage/plugin-techdocs-react                                 1.2.12
  @backstage/plugin-techdocs                                       1.12.0
  @backstage/plugin-user-settings-common                           0.0.1
  @backstage/plugin-user-settings                                  0.8.17
  @backstage/release-manifests                                     0.0.12
  @backstage/test-utils                                            1.7.3
  @backstage/theme                                                 0.6.3
  @backstage/types                                                 1.2.0
  @backstage/version-bridge                                        1.0.10

### 👀 Have you spent some time to check if this bug has been raised before?

- [x] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [x] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!
