### ISSUE TITLE
🐛 Bug Report:Azure Integration Uses Hardcoded API Version

### ISSUE THREAD

**Issue by subhanshu-shukla-ril** [backstage/backstage#28516]
### 📜 Description

The Azure Integration plugin currently uses a hardcoded API version (6.0) for all Azure DevOps API calls. This prevents users from configuring different API versions through the app-config.yml file, which is necessary for compatibility with different Azure DevOps environments and versions.

### 👍 Expected behavior

Azure API version should be configurable through app-config.yml
If no version is specified in config, default to 6.0 for backward compatibility
System should use the configured API version for all Azure DevOps API requests

### 👎 Actual Behavior with Screenshots

Azure API version is hardcoded to 6.0 in the codebase
Configuration in app-config.yml for api-version is ignored
All API requests use version 6.0 regardless of configuration

### 👟 Reproduction steps

Add Azure integration configuration to app-config.yml with a specific api-version:

```
yamlCopyintegrations:
  azure:
    - host: devops.jio.com
      api-version: 5.1
      credentials:
        personalAccessToken: [token]
      reader:
        agent:
          options:
            rejectUnauthorized: false
            secureOptions: 0
```

Make any API request to Azure DevOps through the integration
Observe that the request uses API version 6.0 instead of the configured 5.1

### 📃 Provide the context for the Bug.

Modify the Azure integration configuration reader to include api-version
Update the AzureDevOpsClient to use the configured version
Maintain backward compatibility by defaulting to 6.0 if no version is specified
Add documentation for the new configuration option

### 🖥️ Your Environment

backstage latest version

### 👀 Have you spent some time to check if this bug has been raised before?

- [x] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [x] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None
