### ISSUE TITLE
🐛 Bug Report: $text substition not working for azure integration

### ISSUE THREAD

**Issue by subhanshu-shukla-ril** [backstage/backstage#28515]
### 📜 Description

There is unclear documentation and behavior regarding the integration between Backstage API entities and Azure DevOps-hosted OpenAPI specifications. Specifically, it's unclear whether using $text in the API entity definition properly supports Azure DevOps URLs, even with Azure integration configured in app-config.yaml.

### 👍 Expected behavior

Documentation should clearly specify:

Whether $text supports Azure DevOps URLs for API definitions
If supported, the correct URL format and configuration required
If not supported, the recommended approach for referencing Azure DevOps-hosted OpenAPI specs

### 👎 Actual Behavior with Screenshots

Currently, there is no clear documentation or confirmation whether the following configuration pattern works:

```
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: example-api
  description: Example API
spec:
  type: openapi
  lifecycle: production
  owner: example-team
  definition:
    $text: https://dev.azure.com/organization/project/_apis/git/repositories/repository/items?path=/path/to/openapi.yaml&api-version=6.0
```

### 👟 Reproduction steps

1. Create a new API entity in Backstage
2. Configure Azure integration in app-config.yaml
3. Attempt to reference an OpenAPI spec hosted in Azure DevOps using $text
4. Observe unclear behavior/documentation about whether this is supported

### 📃 Provide the context for the Bug.

Is $text the correct way to reference Azure DevOps-hosted OpenAPI specs?
Are there any special considerations needed for Azure DevOps URLs?
What is the recommended pattern for integrating Azure DevOps-hosted OpenAPI specs?

This clarification is important for organizations using Azure DevOps as their primary source control and wanting to integrate their OpenAPI specifications with Backstage API entities.

### Impact
The lack of clear documentation/behavior:

Creates uncertainty in implementation
May lead to incorrect configurations
Hampers adoption of Backstage API catalog features in Azure DevOps environments

### Possible Solutions

Document explicit support/non-support for Azure DevOps URLs in $text
Provide clear examples of the correct pattern for Azure DevOps integration
If not supported, document alternative approaches

### 🖥️ Your Environment

Backstage Version: [Latest]
Azure DevOps Integration: Configured
API Entity Type: OpenAPI

### 👀 Have you spent some time to check if this bug has been raised before?

- [x] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [x] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by MihaiTabara** [comment]
@subhanshu-shukla-ril can you please share more of the backend logs to help troubleshoot this? Also just to clarify, have you used https://backstage.io/docs/integrations/azure/locations for this?

**Comment by greptail** [comment]
@MihaiTabara  there is no mention in the document that $text substitution will work for integrations too.
I found it by looking placeholder process code. My suggestion is add this in documentation

**Comment by MihaiTabara** [comment]
Good catch @greptail! 👍 Is this something you'd consider contributing to? I believe the issue is worth fixing in a generic way, not just Azure, might be a good fix for all integrations.

**Comment by camilaibs** [comment]
Hi @buuhsmead, do you have any extra information related to the error in the logs?

**Comment by buuhsmead** [comment]
Hi @camilaibs, I tried to test more of this. And after several different options, it worked for me.

```
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: echo-messages-api
  description: The Echo Messages API II
spec:
  type: openapi
  lifecycle: production
  owner: group:default/thio-org
  system: thio-system
  provideApis: component:default/quarkus-cicd
  definition:
    $text: http://example-apicurioregistry-kafkasql.apicurio-registry-operator.router-default.apps.west.jgmpn.gcp.redhatworkshops.io/apis/registry/v2/groups/rhdh-dev/artifacts/openapi
```

So no idead why this at first did not work. I have tried several other options. Also the '$json:' placeholder, putting all one line after the definition. 
The only difference between my tests and the last working was that I requested 'Schedule' from within the GUI.
