### ISSUE TITLE
🚀 Feature: Access Title/Description of parameters in template steps

### ISSUE THREAD

**Issue by defenestration** [backstage/backstage#28536]
### 🔖 Feature description

I have basically a Form created in backstage templates for users to fill out. 

I want to dynamically create a markdown file in a PR using the parameters title and description, however these values don't seem to be accessable when passing to an action, or if they are, i've been unable to find documentation around this.

I'm using this with fetch:template:file action but unsure if that matters.

### 🎤 Context

This would allow for more dynamic content created through templates, and probably makes the 'steps' easier to fill out when there are many variables involved.

Also might be good -  if all parameters could be accessed in a single object so it can be itereated over in the template.

### ✌️ Possible Implementation

Possibly could access the extra features under a different top level object in the template?

```yaml
..
  parameters
    - title: overview
      properties:
        name:
          type: string
          title: Normal param Name
        description:
          title: Item Description
          type: string
          description: Short description of your service
          ui:widget: textarea 
          ui:options:
            rows: 3
  steps:
    - id: form
      name: Render Form
      action: fetch:template:file
      input:
        url: ./checklist/checklist.md
        targetPath: ./checklist.md
        values:
          name: ${{ parameters.name }}
          description: ${{ parameters.description }}
```

checklist.md: 

```md
# ${{ values.name }}

** ${{ properties.description.title }} ** 

> ${{ properties.description.description }}

`${{ properties.description.value}}`

```

### 👀 Have you spent some time to check if this feature request has been raised before?

- [x] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [x] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, I don't have time to work on this right now
