### ISSUE TITLE
🐛 Bug Report: RepoUrlPicker Fails to Display Self-Hosted GitLab in Backstage Template

### ISSUE THREAD

**Issue by Francescatai** [backstage/backstage#28540]
## Issue
The RepoUrlPicker in the template's repoUrl configuration does not display gitlab.example.com as an available option; only github.com is shown. This limitation prevents the creation of projects in a self-hosted GitLab instance via Backstage templates.

### Current Configuration:
```
repoUrl:
  title: Repository Location
  type: string
  ui:field: RepoUrlPicker
  ui:options:
    allowedHosts:
      - github.com
      - gitlab.example.com
```
### Additional Configuration Files:

app-config.yaml:
```
integrations:
  gitlab:
    - host: ${GITLAB_HOST}
      token: ${GITLAB_TOKEN}
      apiBaseUrl: https://${GITLAB_HOST}/api/v4
```
index.ts:
```
backend.add(import('@backstage/plugin-scaffolder-backend-module-gitlab'));
```
package.json:
```
{
  "name": "backend",
  "version": "0.0.0",
  "main": "dist/index.cjs.js",
  "types": "src/index.ts",
  "private": true,
  "backstage": {
    "role": "backend"
  },
  "dependencies": {
    "@backstage/plugin-scaffolder-backend-module-gitlab": "^0.7.0"
  },
  "devDependencies": {
    "@backstage/cli": "^0.29.4"
  }
}
```

If there is any additional information required to help resolve the issue or to troubleshoot further, please feel free to reach out.

### 👍 Expected behavior

The RepoUrlPicker should display both github.com and gitlab.example.com as selectable options, allowing users to create projects in the self-hosted GitLab instance.

### 👎 Actual Behavior with Screenshots

<img width="1410" alt="Image" src="https://github.com/user-attachments/assets/96271daf-77f8-45c6-96ca-9549ec7e0430" />

### 👟 Reproduction steps

Configure the repoUrl in the template as shown above.
Ensure that the app-config.yaml includes the GitLab integration with the correct host and token.
Add the GitLab scaffolder module in index.ts.
Install the necessary dependencies as specified in package.json.
Attempt to create a new component using the template.

### 👀 Have you spent some time to check if this bug has been raised before?

- [x] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [x] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by Francescatai** [comment]
> Thanks for filing this [@Francescatai](https://github.com/Francescatai). If the integration host is properly set, you should be able to have it populated in there. Just to confirm, when you navigate to the aforementioned Backstage page, is the `GITLAB_HOST` reflected in the HTML block with the config?

Hi @MihaiTabara ,
First of all, thank you for your reply. I tried adding `github.com`, `gitlab.com`, and `gitlab.example.com` (self-managed GitLab) to `allowedHosts` to test if they could be displayed on the page. Based on the results, as shown in the screenshots below, only the `github.com` and `gitlab.com` domains are rendered correctly on the page:

<img width="1152" alt="Image" src="https://github.com/user-attachments/assets/6a13654f-698a-49c7-a60f-3d9c31d16f28" />

Below is the content of the `template.yaml` file used for testing, provided for your reference:
```yaml
apiVersion: scaffolder.backstage.io/v1beta3
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-template
kind: Template
metadata:
  name: example-nodejs-template
  title: Example Node.js Template
  description: An example template for the scaffolder that creates a simple Node.js service
spec:
  owner: demo
  type: service

  # These parameters are used to generate the input form in the frontend, and are
  # used to gather input data for the execution of the template.
  parameters:
  - title: Fill in the details
    required:
      - name
      - repoUrl
    properties:
      name:
        title: Name
        type: string
        description: Unique name of the component
        ui:autofocus: true
        ui:options:
          rows: 5
      owner:
        title: Owner
        type: string
        description: Owner of the component
        ui:field: OwnerPicker
        ui:options:
          catalogFilter:
            kind: [User]
      repoUrl:
        title: Repository Location
        type: string
        ui:field: RepoUrlPicker
        ui:options:
          allowedHosts:
            - github.com
            - gitlab.com
            - gitlab.example.com
  # These steps are executed in the scaffolder backend, using data that we gathered
  # via the parameters above.
  steps:
    # Each step executes an action, in this case one templates files into the working directory.
    - id: fetch-base
      name: Fetch Base
      action: fetch:template
      input:
        url: ./content/node
        values:
          name: ${{ parameters.name }}
          owner: ${{ parameters.owner }}

    # This step publishes the contents of the working directory to GitHub.
    #  https://github.com/backstage/backstage/issues/22581
    - id: publishGithub
      name: Publish GitHub
      action: publish:github
      if: ${{ parameters.repoUrl.includes('github.com') }}
      input:
        allowedHosts: ['github.com']
        description: This is ${{ parameters.name }}
        repoUrl: ${{ parameters.repoUrl }}

    # The final step is to register our new component in the catalog.
    - id: registerGithub
      name: Register
      action: catalog:register
      if: ${{ parameters.repoUrl.includes('github.com') }}
      input:
        repoContentsUrl: ${{ steps.publishGithub.output.repoContentsUrl }}
        catalogInfoPath: "/catalog-info.yaml"

  # Outputs are displayed to the user after a successful execution of the template.
  output:
    links:
      - title: Repository
        url: ${{ steps['publish'].output.remoteUrl }}
      - title: Open in catalog
        icon: catalog
        entityRef: ${{ steps['register'].output.entityRef }}
```
If there are any additional steps or information I can provide or try, please feel free to let me know. 
I really appreciate your assistance.

**Comment by camilaibs** [comment]
Thanks @Francescatai for sharing the HTML block, could you please share what you have in your `app-config.yaml` as well 🙂 ?

**Comment by benjdlambert** [comment]
Can you confirm that `GITLAB_HOST` is definitely set in `app-config.yaml` also? :pray:

**Comment by Francescatai** [comment]
Hi, @camilaibs @benjdlambert 

Thank you both for your replies. Below is the `app-config.yaml` content I am currently using. 
From what I understand, it is necessary to configure the GitLab-related information under `integrations` to integrate GitLab services (reference: https://backstage.io/docs/integrations/gitlab/locations). 

If there is any other information I might have missed, please kindly let me know. Thanks again for your assistance!

`app-config.yaml`:
```
app:
  title: Scaffolded Backstage App
  baseUrl: http://localhost:3000

organization:
  name: My Company

backend:
  baseUrl: http://localhost:7007
  listen:
    port: 7007
    # Uncomment the following host directive to bind to specific interfaces
    # host: 127.0.0.1
  csp:
    connect-src: ["'self'", 'http:', 'https:']
  cors:
    origin: http://localhost:3000
    methods: [GET, HEAD, PATCH, POST, PUT, DELETE]
    credentials: true
  database:
    client: better-sqlite3
    connection: ':memory:'


integrations:
  github:
    - host: github.com
      token: ${GITHUB_ACCESS_TOKEN}
  gitlab:
    - host: ${GITLAB_HOST}
      token: ${GITLAB_TOKEN}
      apiBaseUrl: https://${GITLAB_HOST}/api/v4

proxy:
  ### Example for how to add a proxy endpoint for the frontend.
  ### A typical reason to do this is to handle HTTPS and CORS for internal services.
  # endpoints:
  #   '/test':
  #     target: 'https://example.com'
  #     changeOrigin: true

# Reference documentation http://backstage.io/docs/features/techdocs/configuration
# Note: After experimenting with basic setup, use CI/CD to generate docs
# and an external cloud storage when deploying TechDocs for production use-case.
# https://backstage.io/docs/features/techdocs/how-to-guides#how-to-migrate-from-techdocs-basic-to-recommended-deployment-approach
techdocs:
  builder: 'local' # Alternatives - 'external'
  generator:
    runIn: 'docker' # Alternatives - 'local'
  publisher:
    type: 'local' # Alternatives - 'googleGcs' or 'awsS3'. Read documentation for using alternatives.

auth:
  environment: development
  providers:
    guest: {}
    github:
      development:
        clientId: ${GITHUB_CLIENT_ID}
        clientSecret: ${GITHUB_CLIENT_SECRET}
        signIn:
          resolvers:
            - resolver: usernameMatchingUserEntityName
    gitlab:
      development:
        clientId: ${GITLAB_CLIENT_ID}
        clientSecret: ${GITLAB_CLIENT_SECRET}
        ## uncomment if using self-hosted GitLab
        audience: https://${GITLAB_HOST}
        orgEnabled: true
        group: ai
        ## uncomment if using a custom redirect URI
        callbackUrl: http://localhost:7007/api/auth/gitlab/handler/frame
        signIn:
          resolvers:
            - resolver: emailMatchingUserEntityProfileEmail

scaffolder:
  # see https://backstage.io/docs/features/software-templates/configuration for software template options

catalog:
  import:
    entityFilename: catalog-info.yaml
    pullRequestBranchName: backstage-integration
  rules:
    - allow: [Component, System, API, Resource, Location]
  locations:
    # Local example data, file locations are relative to the backend process, typically `packages/backend`
    - type: file
      target: ../../examples/entities.yaml

    # Local example template
    - type: file
      target: ../../examples/template/*.yaml
      rules:
        - allow: [Template]

    # Local example organizational data
    - type: file
      target: ../../examples/org.yaml
      rules:
        - allow: [User, Group]

    - type: file
      target: ../../examples/temp-user.yaml
      rules:
        - allow: [User]

    ## Uncomment these lines to add more example data
    # - type: url
    #   target: https://github.com/backstage/backstage/blob/master/packages/catalog-model/examples/all.yaml

    ## Uncomment these lines to add an example org
    # - type: url
    #   target: https://github.com/backstage/backstage/blob/master/packages/catalog-model/examples/acme-corp.yaml
    #   rules:
    #     - allow: [User, Group]

kubernetes:
  # see https://backstage.io/docs/features/kubernetes/configuration for kubernetes configuration options

# see https://backstage.io/docs/permissions/getting-started for more on the permission framework
permission:
  # setting this to `false` will disable permissions
  enabled: true

```

**Comment by benjdlambert** [comment]
Can you try something like the following instead?:

```yaml
   - host: actual.domain.com  
      token: ${GITLAB_TOKEN}
      apiBaseUrl: https://actual.domain.com/api/v4
```

Basically replacing the ENV var with the raw string instead?
