### ISSUE TITLE
🐛 Bug Report: RepoUrlPicker is fetching the Project name instead of project path

### ISSUE THREAD

**Issue by Rajatkheterpal** [backstage/backstage#28565]
### 📜 Description

RepoUrlPicker is fetching the Project name instead of Project path due to which git project is not accessible. 

When I use the Gitlab naming -: 
https://gitlab.industrysoftware.automation.com/owner/something-stupid
Project Name: TeSt MiXed
Slug: something-stupid
Project ID: 39310
Namespace: owner

https://gitlab.industrysoftware.automation.com/cloud-operations/autobahn/backstage
Project Name: backstage
Slug: backstage
Project ID: 33768
Namespace: cloud-operations/autobahn
 
In the Backstage-Dialog I have 3 Boxes: Host,  Owner Available and Repository
When I type the values manually (or I use the Back button in the following step)
the resulting URL is 
**<host>?owner=<Owner Avilable>&repo=<Repository>**
 
When I use the autocompletion the Repository is set to the gitlab:ProjectName
the resulting URL is:
**<host>?owner=<Owner Avilable>&repo=<Repository>&id=<gitlab:Project ID>**

The autocompletion url is not reachable and failed to fetch the project. 

### 👍 Expected behavior

It should be able to fetch the gitlab project details. 

### 👎 Actual Behavior with Screenshots

It actually is generating the incorrect url which is not pointing to the project. 

![Image](https://github.com/user-attachments/assets/001a26ed-b09a-45c0-a06a-f0166e7428e4)

### 👟 Reproduction steps

   - id: regexUrl
      name: Transform Repository URL
      action: regex:replace
      input:
        regExps:
        - pattern: '^(.*)\?owner=([^&]*)&repo=(.*)$'
          replacement: 'https://$1/$2/$3'
          values: 
            - key: repoUrl
              value: ${{ parameters.repoUrl }}

### 👀 Have you spent some time to check if this bug has been raised before?

- [x] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [x] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by benjdlambert** [comment]
@swnia @hghtwr @mpsanchis you're experienced with Backstage and GitLab, could someone have a look at this please or any input greatly appreciated! :pray:

**Comment by swnia** [comment]
In the screenshot, it looks like the base URL already points to a repository and then the `&id=<gitlab:Project ID>` is appended without a `?`. What is the base URL you configured? Where (and when) do you apply that regexUrl in the **Reproduction steps**?

**Comment by Rajatkheterpal** [comment]
@swnia 
the regexUrl is used in next step to fetch the repository. 
```

  steps:
    - id: regexUrl
      name: Transform Repository URL
      action: regex:replace
      input:
        regExps:
        - pattern: '^(.*)\?owner=([^&]*)&repo=(.*)$'
          replacement: 'https://$1/$2/$3'
          values: 
            - key: repoUrl
              value: ${{ parameters.repoUrl }}

    - id: fetch-repo
      name: Fetch Repository
      action: fetch:plain
      input:
        url: ${{ steps.regexUrl.output.values.repoUrl }}
        targetPath: ./repo
```

Base URL is fetched from the input parameter as shown below -: 

```
repoUrl:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - gitlab.industrysoftware.automation.org.com
            requestUserCredentials:
              secretsKey: USER_OAUTH_TOKEN
              additionalScopes:
                gitlab:
                  - api
                  - read_api
```

**Comment by swnia** [comment]
You should not need to extract the URL after the `RepoUrlPicker`. If you want to, you might try
```
- id: regexUrl
      name: Transform Repository URL
      action: regex:replace
      input:
        regExps:
        - pattern: '^(.*)\?owner=([^&]*)&repo=(.*)&id=(\d+)$'
          replacement: 'https://$1/$2/$3'
          values: 
            - key: repoUrl
              value: ${{ parameters.repoUrl }}
```
As it seems that the `&id=<gitlab:Project ID>` is still there, it seems that the replacement is in-place. Dropping the additional parameter should then fix your issue.
