### ISSUE TITLE
🐛 Bug Report: Cannot use 'in' operator to search for 'ui:field' in undefined

### ISSUE THREAD

**Issue by drdkmkkr** [backstage/backstage#28598]
### 📜 Description

Parameters with enums, using object types as items, results in an error when navigating to the review page.
This happed after [this change](https://github.com/backstage/backstage/commit/91bb99ae2288e5046fa27e6cee9489aa6b1f2b77) was added.

The error thrown is: `Cannot use 'in' operator to search for 'ui:field' in undefined`, and is thrown from here:
https://github.com/backstage/backstage/blob/91bb99ae2288e5046fa27e6cee9489aa6b1f2b77/plugins/scaffolder-react/src/next/components/Stepper/createAsyncValidators.ts#L145

This happens because `itemUiSchema` is an empty object.

---

Possible fix:
```diff
+ if (itemUiSchema[pK] && 'ui:field' in itemUiSchema[pK]) {
- if ('ui:field' in itemUiSchema[pK]) {
```
Tested locally and works, for my case at least.

### 👍 Expected behavior

Should not result in an error

### 👎 Actual Behavior with Screenshots

![Image](https://github.com/user-attachments/assets/4708e733-6497-4db4-8c64-b47f255b1d57)

### 👟 Reproduction steps

Template input example
 ```yaml
apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
spec:
  type: resource
  parameters:
    - title: Destinations
      required:
        - destinations
      properties:
        destinations:
          type: array
          ui:widget: checkboxes
          items:
            type: object
            enumNames:
              - London
              - Berlin
              - Paris
            enum: # These seems to result in the error
              - location: london
                country: united-kingdom
              - location: berlin
                country: germany
              - location: paris
                country: france
```

### 👀 Have you spent some time to check if this bug has been raised before?

- [x] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [x] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None
