### ISSUE TITLE
🚀 Feature: Scaffolder - Support `each` iteration for `output` values

### ISSUE THREAD

**Issue by planeiii-te** [backstage/backstage#28622]
### 🔖 Feature description

Currently iterables are exclusively supported for inputs (#18157). However you cannot loop over outputs the same way. This makes it clunky to enumerate unknown numbers of output. 

### 🎤 Context

If I make N pull requests, I want to create links in the output to all of those pull requests. It's not always clear going in how many pull requests will be required/created, so enumerating them would be the most convenient way to handle this.

### ✌️ Possible Implementation

I'm anticipating the implementation will be similar to the linked input implementation.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [x] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [x] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by benjdlambert** [comment]
@planeiii-te can you provide example `template.yaml` so we can see what you're thinking?

**Comment by planeiii-te** [comment]
This is an excerpt from what we're currently using:

```yaml
output:
  text:
    - title: Pull Requests
      icon: summarize
      content: |
        **Deployment Repository Pull Requests:**
        ${{ steps['openPullRequest'].output.remoteUrl | dump(2) }}

        **ArgoCD Deployment Pull Requests:** 
        ${{ steps['openArgoPullRequest'].output.remoteUrl }}
```
