### ISSUE TITLE
💬 RFC: Extending the Catalog System Model to turn around System-Component relationship

### ISSUE THREAD

**Issue by stanislav-c** [backstage/backstage#28636]
### 🔖 Need

Our organization wants to rely on GitOps to establish owner-approved System↔Components relationships. We want a single repo containing all System entities definitions with [CODEOWNERS](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners) approving changes made to their systems. And we need to find a way for Systems to list repositories of the Components that belong to respective systems. This way when somebody wants to add a Component to a System a PR in the Systems repository would be created and corresponding CODEOWNERS would need to approve that PR to allow establishing the relationship.

By default Components living in other repositories can refer to Systems through [the `spec.system` field](https://backstage.io/docs/features/software-catalog/descriptor-format#specsystem-optional). However with this approach the owners of the Component repo decide which System their component belongs to. We want System owners to own/control this relationship.

### 🎉 Proposal

We are considering extending the System entity specification to address this. According to the docs there are several parts of the spec that can be used for this with their own pros and cons.

Below are the alternative implementations we consider. Note that all references are repo URLs, not entity refs. This is important due to two reasons:

1. Entity names can be reused. If original component owners decide to rename their component, that name can be later used by another repo. System repo in that case would be unaware of the fact that it now is a parent of a different component, not the one that was originally approved through a PR.
2. Repo URLs make it easier to navigate the repositories without looking up the Backstage Catalog.

### 〽️ Alternatives

1. Introduce a new `spec` field with an array of component repos belonging to the system. The biggest risk with this approach, [as described in the docs](https://backstage.io/docs/features/software-catalog/extending-the-model#adding-new-fields-to-the-spec-object-of-an-existing-kind), is that we _run the risk of colliding with future extensions to the model_. However, I wonder if we can minimize that risk by hosting our spec extensions under "company name" key? Also is this level of nesting allowed? E.g.:
   ```yaml
   apiVersion: backstage.io/v1alpha1
   kind: System
   metadata:
     name: system-a
   spec:
     owner: system-a-owner-group
     notSpotify:
       memberComponents:
         - https://github.com/not-spotify/component-x-repo/blob/main/catalog-info.yaml
         - https://github.com/not-spotify/component-y-repo/blob/main/catalog-info.yaml
   ```
2. Do something similar to 1 but directly under `metadata`. [Same risks](https://backstage.io/docs/features/software-catalog/extending-the-model#adding-new-fields-to-the-metadata-object).
   ```yaml
   apiVersion: backstage.io/v1alpha1
   kind: System
   metadata:
     name: system-a
     notSpotify:
       memberComponents:
         - https://github.com/not-spotify/component-x-repo/blob/main/catalog-info.yaml
         - https://github.com/not-spotify/component-y-repo/blob/main/catalog-info.yaml
   spec:
     owner: system-a-owner-group
   ```
3. Use metadata labels or annotations, as recommended in the docs, to avoid colliding with future model extensions. Both annotations and labels only allow string values, so using either would probably require comma-separated lists, which is error-prone and not very elegant, e.g.:
   ```yaml
   apiVersion: backstage.io/v1alpha1
   kind: System
   metadata:
     name: system-a
     labels:
       notSpotify.com/memberComponents: "https://github.com/not-spotify/component-x-repo/blob/main/catalog-info.yaml, https://github.com/not-spotify/component-y-repo/blob/main/catalog-info.yaml"
     # alternatively
     annotations:
       notSpotify.com/memberComponents: "https://github.com/not-spotify/component-x-repo/blob/main/catalog-info.yaml, https://github.com/not-spotify/component-y-repo/blob/main/catalog-info.yaml"
   spec:
     owner: system-a-owner-group
   ```
4. Rely on Location entities co-located next to System entities. This approach essentially changes the semantics of the Location entities, when they are found next to System entities in the systems repo. It also requires comparing Component and System `backstage.io/managed-by-origin-location` values in order to discover all relationships, as opposed to alternatives 1 and 2, where reading system's `spec` object is enough. Example:
   ```yaml
   apiVersion: backstage.io/v1alpha1
   kind: System
   metadata:
     name: system-a
   spec:
     owner: system-a-owner-group
   ---
   apiVersion: backstage.io/v1alpha1
   kind: Location
   metadata:
     name: system-a-components
   spec:
     type: url
     targets:
        - https://github.com/not-spotify/component-x-repo/blob/main/catalog-info.yaml
        - https://github.com/not-spotify/component-y-repo/blob/main/catalog-info.yaml
   ```

### ❌ Risks

As mentioned before, the primary risks with alternatives 1 and 2 are related to colliding with future extensions to the model. Backstage documentation cautions against extending the metadata excessively. However, is this a justified case to take those risks? Also adding a company-specific spec nesting might reduce the risk to practically none.

Alternative 4 has some support in our org, because it does not require us to take the aforementioned risk. But that is not [how Location entities are supposed to be used](https://backstage.io/docs/features/software-catalog/system-model#location) and might confuse users unaware of the hidden meaning of Location entities in the Systems repository.

Dear community members, all thoughts and feedback is very appreciated on the topic! Feel free to ask additional questions. Thank you all in advance.

### 👀 Have you spent some time to check if this RFC has been raised before?

- [x] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [x] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

**Comment by Parsifal-M** [comment]
Hey 👋 

Interesting! Just curious, in your setup, what stops me from doing this? 💭 

```yaml
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: artist-web
  description: The place to be, for great artists
spec:
  type: website
  lifecycle: production
  owner: artist-relations-team
  system: system-a # I just link my component to the system via the component relationship(s)
  dependsOn:
    - resource:default/artists-db
  dependencyOf:
    - component:default/artist-web-lookup
  providesApis:
    - artist-api
```

**Comment by stanislav-c** [comment]
> Hey 👋
> 
> Interesting! Just curious, because I know you mention it, but in your setup, what is it that stops me from doing this? 💭
> 

Nothing stops you from doing this and it must actually be done anyway in order to stay compliant with the default System Model. Most likely in our scenario `spec.system` can even be set automatically by a Catalog processor.
However `spec.system` is not enough for our use case. It is set on the component side, meaning that the component repo owners decide which system component belongs to. We want system owners to control that relationship via GitOps means.

**Comment by MihaiTabara** [comment]
Discussed this in today's triaging meeting.

@stanislav-c 
Your proposal makes sense but given its bespoke nature, we recommend implementing this as a customisation, rather than in the default Catalog behaviour.

**Comment by stanislav-c** [comment]
Yes, certainly. This is very much specific to our org. We are more concerned about the [_running the risk of colliding with future extensions to the model_](https://backstage.io/docs/features/software-catalog/extending-the-model/#adding-new-fields-to-the-spec-object-of-an-existing-kind). Let's say if we implement alternative 1 with an org-specific qualifier, the risk that upstream Backstage Catalog implementation would use it is negligible, right? Or is there more to it?

```yaml
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: system-a
spec:
  owner: system-a-owner-group
  ourCompany: # ← This should keep us safe, right?
    memberComponents:
      - https://github.com/not-spotify/component-x-repo/blob/main/catalog-info.yaml
      - https://github.com/not-spotify/component-y-repo/blob/main/catalog-info.yaml
```
