### ISSUE TITLE
🚀 Feature: Catalog: Enable eager deletion for nonexistent catalog entities

### ISSUE THREAD

**Issue by novellat** [backstage/backstage#28638]
### 🔖 Feature description

When currently a catalog gets regularly deleted from the repository (so the api requests return 404) the catalog entity stays in the database.
This leads to desynchronization between the source of truth and the catalog.

### 🎤 Context

In our case we have multiple actors editing the repository, which includes editing the entities and also deleting them.
However that doesn't reflect on the backstage catalog.

Another, even bigger problem is that those deleted entities are still being queries for and thus consuming github rate limits.

### ✌️ Possible Implementation

Add a flag in the app-config
catalog.enableDeletionOfNonExistentEntities or catalog.externalSourceOfTruth

so that when the API request returns 404, the entity gets deleted (or at least soft deleted...)

### 👀 Have you spent some time to check if this feature request has been raised before?

- [x] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [x] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by MihaiTabara** [comment]
Discussed this in today's triaging meeting. 
@novellat what's your method of ingestion? Asking as for manual registration this indeed may need it, but for Discovery it should automatically work because of 
https://backstage.io/docs/features/software-catalog/life-of-an-entity/#orphaning

**Comment by novellat** [comment]
@MihaiTabara thanks for the answer. Honestly I'm confused about the whole orphaning concept as it doesn't really work how I expect it to work ;-)

As for ingestion, we use the catalog key in app-config. Basically deleting any (leaf) entity in the repo keeps it in the catalog, only to keep calling the GH api periodically. And the orphanStrategy doesn't seem to take any effect on it.


```
catalog:
  rules:
    - allow: [Component, System, API, Group, User, Resource, Location, Template]
  locations:
    - type: url
      target: https://github.com/REPO1/blob/non-prod/locations.yaml
    - type: url
      target: https://github.com/REPO2/blob/bdp-dev/bdp/location.yaml
    - type: url
      target: https://github.com/REPO3/blob/bdx-dev/bdx/location.yaml
 orphanStrategy: delete
```
