### ISSUE TITLE
🐛 Bug Report: Azure Integration proxy support

### ISSUE THREAD

**Issue by greptail** [backstage/backstage#28646]
### 📜 Description

I my virtual machine azure devops is reachable via proxy
I tried with below settings.

```
catalog:
  providers:
    azureDevOps:
      host: dev.azure.com
      organization: your-organization
      project: your-project
      token: ${AZURE_TOKEN}
      # Proxy settings specific to this provider
      proxy:
        host: your-proxy-host
        port: your-proxy-port
```

### 👍 Expected behavior

It should work

### 👎 Actual Behavior with Screenshots

It is not working

### 👟 Reproduction steps

Set azure integration with proxy

### 📃 Provide the context for the Bug.

Azure integration to support proxy host and port

### 🖥️ Your Environment

ubunty

### 👀 Have you spent some time to check if this bug has been raised before?

- [x] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [x] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!
