### ISSUE TITLE
🐛 Bug Report: Unable to read url, NotFoundError - Failed to obtain an access token

### ISSUE THREAD

**Issue by phil1234567891011** [backstage/backstage#28640]
### 📜 Description

I try to run the Node JS example template
I follow this tutorial : cookiecutter demo from this video https://youtu.be/r46uFbu9wOs?t=9102

- please don not answer me just with yet another link to the documentation, I come from there
- I read this one too https://github.com/backstage/backstage/issues/11296 but no solution seems available

**How is it that backstage can create a repository (using my PAT) but cannot not read the YAML from that repository ???**

### 👍 Expected behavior

I expect the Register step not to fail

### 👎 Actual Behavior with Screenshots

![Image](https://github.com/user-attachments/assets/bfd143ca-59d4-4b4b-a71d-205fea58fbc5)

![Image](https://github.com/user-attachments/assets/5f4a3bef-1e3f-43fa-bbef-ef659047ef9d)

![Image](https://github.com/user-attachments/assets/f56aebe1-623c-471a-9794-368801a3e05c)

![Image](https://github.com/user-attachments/assets/10a09a1d-a7b6-4c70-980d-4f5d97b11d14)

### 👟 Reproduction steps

I first tried **with my Github user** where the register fails

```
export GITHUB_CLIENT_SECRET==[client_secret_generated_in_USER_settings]
export GITHUB_CLIENT_ID==[client_id_generated_in_USER_settings]
export GITHUB_TOKEN==[pat_generated_in_USER_settings]
```

Then, I created an **organization**, and added oAuth id/secrets.
But now that I use the organization secret/id I get **Failed to obtain access token** as I login

![Image](https://github.com/user-attachments/assets/ccef01c5-5727-4913-a8f5-b61e4b51062f)

I tried with and without the PAT from my github user (since there is no way to generate one in organization nor githubapp)

```
# git phil organization
export GITHUB_CLIENT_ID==[client_id_generated_in_ORGANIZATION_settings]
export GITHUB_CLIENT_SECRET==[client_secret_generated_in_ORGANIZATION_settings]
```

```
# git phil organization
export GITHUB_CLIENT_ID==[client_id_generated_in_ORGANIZATION_settings]
export GITHUB_CLIENT_SECRET==[client_secret_generated_in_ORGANIZATION_settings]
export GITHUB_TOKEN==[pat_generated_in_USER_settings]
```

I tried by creating a **GithubApp**, same issue

```
# github app 
export GITHUB_CLIENT_ID=[client_id_generated_in_GITHUB_APP_settings]
export GITHUB_CLIENT_SECRET=[client_secret_generated_in_GITHUB_APP_settings]
```

Now I use the same PAT 

```
# github app 
export GITHUB_CLIENT_ID=[client_id_generated_in_GITHUB_APP_settings]
export GITHUB_CLIENT_SECRET=[client_secret_generated_in_GITHUB_APP_settings]
export GITHUB_TOKEN=[pat_generated_in_USER_settings]
```

I finally can login but back to #1, **BACKSTAGE STILL CANNOT READ THE REPOSITORY YAML FILE**

Here is my config:

```
auth:
  environment: development
  providers:
    github:
      development:
        clientId: ${GITHUB_CLIENT_ID}
        clientSecret: ${GITHUB_CLIENT_SECRET}
        signIn:
          resolvers:
            - resolver: usernameMatchingUserEntityName
            - resolver: emailLocalPartMatchingUserEntityName
            - resolver: emailMatchingUserEntityProfileEmail
```

```
integrations:
  github:
    - host: github.com
       token: ${GITHUB_TOKEN}
```

```
catalog:
  providers:
    github:
      providerId:
        host: github.com
        organization: 'phil-organization'
        catalogPath: '/catalog-info.yaml'
        filters:
          branch: 'main' # string
          repository: '.*' # Regex
        schedule: 
          frequency: { minutes: 1 }
          timeout: { minutes: 3 }
```

### 📃 Provide the context for the Bug.

I try to have the github integration working for a demo to my colleagues, so we decide to go backstage or not

### 🖥️ Your Environment

ubuntu 22.04

### 👀 Have you spent some time to check if this bug has been raised before?

- [x] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [x] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by benjdlambert** [comment]
Can you paste the exact `template.yaml` you're using?

It looks like the repository is being created as `private` so either the PAT that the catalog is using does not have access to that private repository, or that there's no token being used at all.

**Comment by phil1234567891011** [comment]
well it is the one from the examples

![Image](https://github.com/user-attachments/assets/0d60210a-6b41-4161-9ca3-29977741516b)

**Comment by phil1234567891011** [comment]
ok I found out the url should be 

https://github.com/phil1234567891011/test6/blob/master/**test6/**catalog-info.yaml

so I changed the template as this, but it keeps asking the wrong url

```
    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps['publish'].output.repoContentsUrl }}
        catalogInfoPath: '**${{ parameters.name }}**/catalog-info.yaml'
```
