### ISSUE TITLE
[charts] Stop using NODE_ENV=development in Helm deployments

### ISSUE THREAD

**Issue by martina-if** [backstage/backstage#2867]
## Improvement Suggestion

The main reason NODE_ENV was set to development mode when running the example backend in Kubernetes with the helm charts was that the docker images contained the app-config.yaml file inside which in turn contained configuration that enabled things like the azure scaffolder.

From [app-config.yaml](https://github.com/spotify/backstage/blob/master/app-config.yaml#L156)

```
scaffolder:
  azure:
    baseUrl: https://dev.azure.com/{your-organization}
    api:
      token:
        $env: AZURE_TOKEN
```

By having this the backend application won't be able to start unless there are valid values for azure. Dummy values won't be enough like in another plugins because these are actually validated against the provided `baseUrl`.

The current workaround for this was to set NODE_ENV=development, so that these failures would be ignored.

## Possible Implementation

There are at least two other solutions to avoid this failure:

- remove anything that is not completely necessary not set any default configuration for scaffolder in `app-config.yaml` and only provide an example in `app-config.development.yaml`. Then in the kubernetes deployment mount a file called `app-config.kubernetes.yaml` or similar that has the specific configuration needed based on what helm values have been provided.
    ```
    - name: app-config
              mountPath: "/usr/src/app/app-config.kubernetes.yaml"
    ```
- override the `/usr/src/app/app-config.yaml` file in the kubernetes `deployment` via a file mount
    ```
    - name: app-config
              mountPath: "/usr/src/app/app-config.yaml"
              subPath: app-config.yaml
    ```

In both cases the configuration file that is mounted would selectively set the fields depending on whether the corresponding value is set in `.Values`. For example:

```
scaffolder:
{{- if .Values.auth.azure.api.token }}
  azure:
    baseUrl: https://dev.azure.com/{your-organization}
    api:
      token:
        $env: AZURE_TOKEN
{{- end }}
```
