### ISSUE TITLE
🐛 Bug Report: Scaffolder displays incorrect skipped status when multiple template steps have same name

### ISSUE THREAD

**Issue by gavinclarkeuk** [backstage/backstage#28690]
### 📜 Description

It is sometimes useful to have multiple template steps with the same id, but with different `if` conditions. This enables you to reference the output of whichever step was executed in later steps without needing to duplicate your conditional logic.

This works as expected in the execution of the template, but the status icon for all template steps that share an id is incorrect. It will always show the skipped status of the last step. Similarly, when working in the template editor and selecting one of the steps, you'll actually see the logs for both steps combined together.

Seems that the key for the skipped status and logs is the step id, when it should probably be the index in the steps array or a combination of the two.

### 👍 Expected behavior

The UI should reflect what was actually executed. The logs for only the selected step should be displayed in the template editor.

### 👎 Actual Behavior with Screenshots

The skipped status of the last job with the given id is displayed. Selecting any of the steps which share the id in the template editor shows the logs for both steps. Screenshots below are from the template editor, but the status issue is there in the main scaffolder page too.

![Image](https://github.com/user-attachments/assets/53afdc1c-5a70-4c13-b50f-b3fb97e9d57e)
![Image](https://github.com/user-attachments/assets/aff966ee-7f58-48e7-894b-4021dfc33bcf)

### 👟 Reproduction steps

Simple template to reproduce - for results see screenshots above

```yaml
apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: Bug Repro
  title: Bug Repro
spec:
  owner: abc
  type: test
  parameters:
    - title: Template Options
      required:
        - option
      properties:
        option:
          title: Option
          type: boolean

  steps:
    - id: debug-repro
      name: Option 1
      if: ${{ parameters.option }}
      action: debug:log
      input:
        message: Option is true

    - id: debug-repro
      name: Option 2
      if: ${{ not parameters.option }}
      action: debug:log
      input:
        message: Option is false

```

### 📃 Provide the context for the Bug.

Whilst my templates still work as expected, this make developing them trickier, as the UI can't be relied upon to clearly describe what is happening

### 👀 Have you spent some time to check if this bug has been raised before?

- [x] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [x] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None
