### ISSUE TITLE
🐛 Bug Report: Sometimes onChange handler in scaffolder field does not work properly

### ISSUE THREAD

**Issue by zcmander** [backstage/backstage#28729]
### 📜 Description

Sometimes `onChange` handler does not work properly and the field is left with the old value.
 
The video below has the following template:

```yaml
apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: custom-field-extensions
  title: Custom Field Extensions
spec:
  owner: user:default/john.doe
  type: example
  parameters:
    - title: Example
      properties:
        field1:
          title: Field 1
          type: string
          ui:field: ExamplePicker

        field2:
          title: Field 2
          type: string
          ui:field: ExamplePicker
          ui:options:
            parentFieldName: field1

        field3:
          title: Field 3
          type: string
          ui:field: ExamplePicker
          ui:options:
            parentFieldName: field2

        field4:
          title: Field 4
          type: string
          ui:field: ExamplePicker
          ui:options:
            parentFieldName: field2

  steps: []
```

`ExamplePicker` is a custom field extensions that can be configured so that it depends on some other field. In this case, dependecy tree looks like this:

- field1
  - field2
    - field3
    - field4   

Clearing `field1` clears out fields `field2` and `field4` but does not clear `field3` for some reason. It sounds like some kind of race-condition or wonky form state handling but I couldn't find any root cause for this behavior.

### 👍 Expected behavior

It should clear out all values in the template.

### 👎 Actual Behavior with Screenshots

https://github.com/user-attachments/assets/be4c499c-7c59-4073-9ee3-00da830edaef

### 👟 Reproduction steps

Check out my branch that has needed changes as shown in the video above:

https://github.com/backstage/backstage/compare/master...zcmander:backstage:bug/field-onchange

You can just start Backstage:

```
yarn dev
```

and opening browser: http://localhost:3000/create/templates/default/custom-field-extensions

### 📃 Provide the context for the Bug.

Accessing other fields in form should be possible, according documentation: https://backstage.io/docs/features/software-templates/writing-custom-field-extensions#access-data-from-other-fields
 although discouraged, but sometimes it's unavoidable.

### 🖥️ Your Environment

Tested with Firefox and Safari browsers.

### 👀 Have you spent some time to check if this bug has been raised before?

- [x] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [x] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, I don't have time to work on this right now
