### ISSUE TITLE
🚀 Feature: Add GitHub Repo Push Action to Existing Repo

### ISSUE THREAD

**Issue by fosterm-mw** [backstage/backstage#28749]
### 🔖 Feature description

There needs to be a feature apart of the GitHub scaffolder actions which will allow pushing to an existing branch of an existing repo.

### 🎤 Context

This feature would be helpful for many reasons. A main reason is having a specific catalog repo for all of the entities and being able to push to the existing repo of catalog entities and registering that entity as part of one Template. 

### ✌️ Possible Implementation

We just need to add an additional `github:branches:push` action to the existing GitHub scaffolder actions that will skip the `git.init` function. 
Something would look like this:
```
    - id: push-catalog-entry
      action: github:branch:push
      name: Publish Catalog Entry
      input:
        repoUrl: <repoURL>
        defaultBranch: main
        gitCommitMessage: 'Register ${{parameters.entityName}}'
        sourcePath: ./catalog
        allowedHosts: ['github.com']

```

### 👀 Have you spent some time to check if this feature request has been raised before?

- [x] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [x] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!
