### ISSUE TITLE
Support Multi-Tenancy in Backstage GitLab Integration

### ISSUE THREAD

**Issue by rakeshreddyrg09** [backstage/backstage#28763]
### 🔖 Need

Currently, our Backstage GitLab catalog integration is set up with multiple tenants using the following configuration:
```yaml
appConfig:
  catalog:
    providers:
      gitlab:
        test1:
          host: code.org.com
          orgEnabled: true
          group: test1
          restrictUsersToGroup: true
          rules:
            - allow: [Group, User]
          relations:
            - DESCENDANTS
            - SHARED_FROM_GROUPS
          schedule:
            frequency: { minutes: 720 }
            timeout: { minutes: 1140 }
        test2:
          host: code.org.com
          orgEnabled: true
          group: test2
          restrictUsersToGroup: true
          rules:
            - allow: [Group, User]
          relations:
            - DESCENDANTS
            - SHARED_FROM_GROUPS
          schedule:
            frequency: { minutes: 720 }
            timeout: { minutes: 1140 }

```

The expectation is that users from test1 should only see entities related to test1, and users from test2 should only see entities related to test2. However, currently, users from test1 are able to see test2 entities and vice versa.

**Root Cause Hypothesis**
Shared Authentication Scope:

  We are using a single GitLab Personal Access Token (PAT) for Backstage integration. This might be causing all users to inherit the same access level, allowing them to view everything the token has access to.

Backstage Access Control:

  The restrictUsersToGroup flag is set to true, but it seems ineffective in properly scoping user access.
The relations field includes SHARED_FROM_GROUPS, which might be allowing unintended visibility across groups.
User Authentication & Authorization:

Since authentication is based on GitLab, all authenticated users might be seeing all fetched catalog data due to improper access scoping.

### 🎉 Proposal

Need your input on how to achieve multitenancy.

### 👀 Have you spent some time to check if this RFC has been raised before?

- [x] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [x] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)
