### ISSUE TITLE
🐛 Bug Report: GitHub App for backend authentication gets "403 Forbidden" when polling wildcard provider.

### ISSUE THREAD

**Issue by tferrari92** [backstage/backstage#28794]
### 📜 Description

Getting `403 Forbidden` when using wildcard in catalog provider after switching backend authentication from GitHub Token to GitHub App .

GitHub App was created with intructions from documentation and tested to work fine if no wildcard is used.

### 👍 Expected behavior

When using this app-config with GITHUB_TOKEN I have no problems:
```
integrations:
  github:
    - host: github.com
      token: ${GITHUB_TOKEN}

catalog:
  providers:
    github:
      entitiesProvider:
        organization: 'org' # string
        catalogPath: '/**/*.yaml' # string
        filters:
          branch: 'main' # string
          repository: 'backstage-entities' # Regex
        schedule:
          frequency: { minutes: 10 }
          timeout: { minutes: 3 }
```

Expectation is to continue to work when switching to GitHub App

### 👎 Actual Behavior with Screenshots

When using to GitHub App integration:
```
integrations:
  github:
    - host: github.com
      apps:
        - $include: github-app-org-backstage-credentials.yaml
        
catalog:
  providers:
    github:
      entitiesProvider:
        organization: 'org' # string
        catalogPath: '/**/*.yaml' # string
        filters:
          branch: 'main' # string
          repository: 'backstage-entities' # Regex
        schedule:
          frequency: { minutes: 10 }
          timeout: { minutes: 3 }
```

I get:
`[backend]: 2025-02-10T18:54:05.960Z catalog warn Unable to read url, Error: Request failed for https://api.github.com/repos/org/backstage-entities/commits/main/status?per_page=0, 403 Forbidden entity=location:default/generated-74c36844224eb7577e5181cfb5ca1ad439525eb2 location=url:https://github.com/org/backstage-entities/blob/main/**/*.yaml`

I know it's not an authentication issue because if I specify path with no wildcard it works. Like this:
```
integrations:
  github:
    - host: github.com
      apps:
        - $include: github-app-org-backstage-credentials.yaml
        
catalog:
  providers:
    github:
      entitiesProvider:
        organization: 'org' # string
        catalogPath: '/some/path/file.yaml' # string
        filters:
          branch: 'main' # string
          repository: 'backstage-entities' # Regex
        schedule:
          frequency: { minutes: 10 }
          timeout: { minutes: 3 }
```

GitHub App was created with `yarn backstage-cli create-github-app <github org>`

### 👟 Reproduction steps

Use this app-config:
```
integrations:
  github:
    - host: github.com
      apps:
        - $include: github-app-org-backstage-credentials.yaml
        
catalog:
  providers:
    github:
      entitiesProvider:
        organization: 'org' # string
        catalogPath: '/**/*.yaml' # string
        filters:
          branch: 'main' # string
          repository: 'backstage-entities' # Regex
        schedule:
          frequency: { minutes: 10 }
          timeout: { minutes: 3 }
```

With a GitHub app created through:
`yarn backstage-cli create-github-app <github org>`

Test also using full path to check authentication actually works

### 👀 Have you spent some time to check if this bug has been raised before?

- [x] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [x] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None
