### ISSUE TITLE
🐛 Bug Report: ldapOrg will not map user-group relationships

### ISSUE THREAD

**Issue by neeraj-p2p** [backstage/backstage#28822]
### 📜 Description

I'm running a Backstage instance on a Kubernetes container, with the following integrations:

-> Google Gauth Sign-in for authentication.
-> Google Secure LDAP for fetching organization data (users and groups) using the catalog-backend-module-ldap plugin.

The LdapOrg plugin successfully fetches and creates User and Group entities in my Backstage catalog. However, the user-group relations array is empty. Below are the Group and User entities in YAML format, as seen in the Backstage UI:

1) Group Entity (YAML):
```
apiVersion: backstage.io/v1beta1
kind: Group
metadata:
  namespace: default
  annotations:
    backstage.io/managed-by-location: ldap://default/abc-group
    backstage.io/managed-by-origin-location: ldap://default/abc-group
    backstage.io/ldap-rdn: abc-group
  name: abc-group
  description: some desc here
relations: []
spec:
  type: unknown
  profile:
    displayName: abc-group
  children: []
```

2) User Entity (YAML):
```
apiVersion: backstage.io/v1beta1
kind: User
metadata:
  namespace: default
  annotations:
    backstage.io/managed-by-location: ldap://default/abc.user
    backstage.io/managed-by-origin-location: ldap://default/abc.user
    backstage.io/ldap-rdn: abc.user
  name: abc.user
relations: []
spec:
  profile:
    email: abc.user@xyz.org
  memberOf: []
```

### 👍 Expected behavior

The user (abc.user) should have a relationship with the group (abc-group), as indicated by the memberOf field in the User entity. Similarly, the group (abc-group) should list the user (abc.user) in the members field, as the user is part of the group.

Observed Issue:
The relations array in both User and Group entities is empty.
Even though the user abc.user is a member of the group abc-group (as verified via ldapsearch), the relationship isn't reflected in Backstage.

LDAP Search Results:
1) Fetching Group Details with ldapsearch: Command:
`LDAPTLS_CERT=Google.crt LDAPTLS_KEY=Google.key ldapsearch -H ldaps://ldap.google.com:636 -b cn=abc-group,ou=Groups,dc=xyz,dc=org`

Output:
```
# extended LDIF
#
# LDAPv3
# base <cn=abc-group,ou=Groups,dc=xyz,dc=org> with scope subtree
# filter: (objectclass=*)
# requesting: ALL
#
# abc-group, Groups, xyz.org
dn: cn=abc-group,ou=Groups,dc=xyz,dc=org
objectClass: top
objectClass: groupOfNames
objectClass: posixGroup
cn: abc-group
displayName: abc group
description: some desc here
gidNumber: 109574761
member: uid=abc.user,ou=Users,dc=xyz,dc=org
member: uid=mnb.user,ou=device_approval_required,ou=all_employes,ou=Users,dc=xyz,dc=org
memberUid: abc.user
memberUid: mnb.user
googleAdminCreated: FALSE
```

2) Fetching User Details with ldapsearch: Command:
`LDAPTLS_CERT=Google.crt LDAPTLS_KEY=Google.key ldapsearch -H ldaps://ldap.google.com:636 -b uid=abc.user,ou=Users,dc=xyz,dc=org`

Output:
```
# extended LDIF
#
# LDAPv3
# base <uid=abc.user,ou=Users,dc=xyz,dc=org> with scope subtree
# filter: (objectclass=*)
# requesting: ALL
#
# abc.user, Users, xyz.org
dn: uid=abc.user,ou=Users,dc=xyz,dc=org
objectClass: top
objectClass: person
objectClass: organizationalPerson
objectClass: inetOrgPerson
objectClass: posixAccount
uid: abc.user
googleUid: abc.user
posixUid: abc.user
cn: abc.user
cn: abc user
sn: user
displayName: abc user
givenName: abc
mail: abc.user@xyz.org
uidNumber: 2131047852
gidNumber: 2131047852
homeDirectory: /home/abc.user
loginShell: /bin/bash
gecos:
telephoneNumber: +684 826734652
suspended: false
apple-generateduid: 72C4F77A-745E-4D01-A1A0-F477FF136AAC
memberOf: cn=abc-group,ou=Groups,dc=xyz,dc=org
memberOf: cn=someother-group,ou=Groups,dc=xyz,dc=org
```

As you can see, abc.user is a member of abc-group in the LDAP search result. Hence, the user-to-group relation should be established in Backstage.

App Configuration:
Here is the relevant configuration from my app-config.yaml:

```
catalog:
  providers:
    ldapOrg:
      default:
        target: ldaps://ldap.google.com:636
        tls:
          rejectUnauthorized: false
          keys: /path-to/googleldapkey.pem
          certs: /path-to/googleldapcert.pem
        schedule:
          frequency: PT30M
          timeout: PT5M
        users:
          - dn: ou=Users,dc=xyz,dc=org
            options:
              scope: sub
              filter: (&(objectClass=person)(!(uid='')))
              paged: false
            map:
              rdn: uid
              name: uid
              displayName: cn
              email: mail
              memberOf: memberOf
        groups:
          - dn: ou=Groups,dc=xyz,dc=org
            options:
              scope: sub
              filter: (&(objectClass=groupOfNames)(!(cn='')))
            map:
              rdn: cn
              name: cn
              description: description
              displayName: cn
              type: groupType
              memberOf: memberOf
              members: member
```

### 👎 Actual Behavior with Screenshots

Both User and Group entities have empty relations arrays, even though the LDAP search clearly shows that the user is a member of the group.

Backstage container logs w.r.t ldap - 
```
{"class":"LdapOrgEntityProvider","level":"info","message":"Reading LDAP users and groups","plugin":"catalog","service":"backstage","taskId":"LdapOrgEntityProvider:default:refresh","taskInstanceId":"6cb68d9b-4eca-4cb1-a389-5d7d980be5fc"}

{"class":"LdapOrgEntityProvider","level":"info","message":"Read 411 LDAP users and 153 LDAP groups in 17.0 seconds. Committing...","plugin":"catalog","service":"backstage","taskId":"LdapOrgEntityProvider:default:refresh","taskInstanceId":"6cb68d9b-4eca-4cb1-a389-5d7d980be5fc"}

{"class":"LdapOrgEntityProvider","level":"info","message":"Committed 411 LDAP users and 153 LDAP groups in 2.3 seconds.","plugin":"catalog","service":"backstage","taskId":"LdapOrgEntityProvider:default:refresh","taskInstanceId":"6cb68d9b-4eca-4cb1-a389-5d7d980be5fc"}
```

<img width="1500" alt="Image" src="https://github.com/user-attachments/assets/19e25441-ce79-4e23-9f31-d177ff9f9f30" />

<img width="1482" alt="Image" src="https://github.com/user-attachments/assets/af7635f7-bfe5-44f1-a92a-27f090d2a629" />

### 👟 Reproduction steps

1) Setup a LDAP server
2) Ingest users and groups
3) Groups and users will not map for membership

### 🖥️ Your Environment

% yarn backstage-cli info               
OS:   Darwin 24.3.0 - darwin/arm64
node: v22.13.0
yarn: 4.4.1
cli:  0.29.6 (installed)
backstage:  1.35.1

Dependencies:
  @backstage/app-defaults                                          1.5.16
  @backstage/backend-app-api                                       1.1.1
  @backstage/backend-common                                        0.25.0
  @backstage/backend-defaults                                      0.7.0
  @backstage/backend-dev-utils                                     0.1.5
  @backstage/backend-openapi-utils                                 0.4.1
  @backstage/backend-plugin-api                                    1.1.1
  @backstage/catalog-client                                        1.9.1
  @backstage/catalog-model                                         1.7.3
  @backstage/cli-common                                            0.1.15
  @backstage/cli-node                                              0.2.12
  @backstage/cli                                                   0.29.6
  @backstage/config-loader                                         1.9.5
  @backstage/config                                                1.3.2
  @backstage/core-app-api                                          1.15.4
  @backstage/core-compat-api                                       0.3.5
  @backstage/core-components                                       0.16.3
  @backstage/core-plugin-api                                       1.10.3
  @backstage/e2e-test-utils                                        0.1.1
  @backstage/errors                                                1.2.7
  @backstage/eslint-plugin                                         0.1.10
  @backstage/frontend-app-api                                      0.10.4
  @backstage/frontend-defaults                                     0.1.5
  @backstage/frontend-plugin-api                                   0.9.4
  @backstage/frontend-test-utils                                   0.2.5
  @backstage/integration-aws-node                                  0.1.15
  @backstage/integration-react                                     1.2.3
  @backstage/integration                                           1.16.1
  @backstage/plugin-api-docs                                       0.12.3
  @backstage/plugin-app-backend                                    0.4.4
  @backstage/plugin-app-node                                       0.1.29
  @backstage/plugin-app                                            0.1.5
  @backstage/plugin-auth-backend-module-atlassian-provider         0.3.4
  @backstage/plugin-auth-backend-module-auth0-provider             0.1.4
  @backstage/plugin-auth-backend-module-aws-alb-provider           0.3.2
  @backstage/plugin-auth-backend-module-azure-easyauth-provider    0.2.4
  @backstage/plugin-auth-backend-module-bitbucket-provider         0.2.4
  @backstage/plugin-auth-backend-module-bitbucket-server-provider  0.1.4
  @backstage/plugin-auth-backend-module-cloudflare-access-provider 0.3.4
  @backstage/plugin-auth-backend-module-gcp-iap-provider           0.3.4
  @backstage/plugin-auth-backend-module-github-provider            0.2.4
  @backstage/plugin-auth-backend-module-gitlab-provider            0.2.4
  @backstage/plugin-auth-backend-module-google-provider            0.2.4
  @backstage/plugin-auth-backend-module-guest-provider             0.2.4
  @backstage/plugin-auth-backend-module-microsoft-provider         0.2.4
  @backstage/plugin-auth-backend-module-oauth2-provider            0.3.4
  @backstage/plugin-auth-backend-module-oauth2-proxy-provider      0.2.4
  @backstage/plugin-auth-backend-module-oidc-provider              0.3.4
  @backstage/plugin-auth-backend-module-okta-provider              0.1.4
  @backstage/plugin-auth-backend-module-onelogin-provider          0.2.4
  @backstage/plugin-auth-backend                                   0.24.2
  @backstage/plugin-auth-node                                      0.5.6
  @backstage/plugin-auth-react                                     0.1.11
  @backstage/plugin-bitbucket-cloud-common                         0.2.27
  @backstage/plugin-catalog-backend-module-github                  0.7.9
  @backstage/plugin-catalog-backend-module-ldap                    0.11.1
  @backstage/plugin-catalog-backend-module-logs                    0.1.6
  @backstage/plugin-catalog-backend-module-scaffolder-entity-model 0.2.4
  @backstage/plugin-catalog-backend                                1.30.0
  @backstage/plugin-catalog-common                                 1.1.3
  @backstage/plugin-catalog-graph                                  0.4.15
  @backstage/plugin-catalog-import                                 0.12.9
  @backstage/plugin-catalog-node                                   1.15.1
  @backstage/plugin-catalog-react                                  1.15.1
  @backstage/plugin-catalog                                        1.26.1
  @backstage/plugin-events-node                                    0.4.7
  @backstage/plugin-kubernetes-backend                             0.19.2
  @backstage/plugin-kubernetes-common                              0.9.2
  @backstage/plugin-kubernetes-node                                0.2.2
  @backstage/plugin-kubernetes-react                               0.5.3
  @backstage/plugin-kubernetes                                     0.12.3
  @backstage/plugin-org                                            0.6.35
  @backstage/plugin-permission-backend-module-allow-all-policy     0.2.4
  @backstage/plugin-permission-backend                             0.5.53
  @backstage/plugin-permission-common                              0.8.4
  @backstage/plugin-permission-node                                0.8.7
  @backstage/plugin-permission-react                               0.4.30
  @backstage/plugin-proxy-backend                                  0.5.10
  @backstage/plugin-proxy-node                                     0.1.0
  @backstage/plugin-scaffolder-backend-module-azure                0.2.5
  @backstage/plugin-scaffolder-backend-module-bitbucket-cloud      0.2.5
  @backstage/plugin-scaffolder-backend-module-bitbucket-server     0.2.5
  @backstage/plugin-scaffolder-backend-module-bitbucket            0.3.6
  @backstage/plugin-scaffolder-backend-module-gerrit               0.2.5
  @backstage/plugin-scaffolder-backend-module-gitea                0.2.5
  @backstage/plugin-scaffolder-backend-module-github               0.5.5
  @backstage/plugin-scaffolder-backend-module-gitlab               0.7.1
  @backstage/plugin-scaffolder-backend                             1.29.0
  @backstage/plugin-scaffolder-common                              1.5.9
  @backstage/plugin-scaffolder-node                                0.6.3
  @backstage/plugin-scaffolder-react                               1.14.4
  @backstage/plugin-scaffolder                                     1.27.5
  @backstage/plugin-search-backend-module-catalog                  0.3.0
  @backstage/plugin-search-backend-module-pg                       0.5.40
  @backstage/plugin-search-backend-module-techdocs                 0.3.5
  @backstage/plugin-search-backend-node                            1.3.7
  @backstage/plugin-search-backend                                 1.8.1
  @backstage/plugin-search-common                                  1.2.17
  @backstage/plugin-search-react                                   1.8.5
  @backstage/plugin-search                                         1.4.22
  @backstage/plugin-signals-react                                  0.0.9
  @backstage/plugin-techdocs-backend                               1.11.5
  @backstage/plugin-techdocs-common                                0.1.0
  @backstage/plugin-techdocs-module-addons-contrib                 1.1.20
  @backstage/plugin-techdocs-node                                  1.12.16
  @backstage/plugin-techdocs-react                                 1.2.13
  @backstage/plugin-techdocs                                       1.12.2
  @backstage/plugin-user-settings-common                           0.0.1
  @backstage/plugin-user-settings                                  0.8.18
  @backstage/release-manifests                                     0.0.12
  @backstage/test-utils                                            1.7.4
  @backstage/theme                                                 0.6.3
  @backstage/types                                                 1.2.1
  @backstage/version-bridge                                        1.0.10

### 👀 Have you spent some time to check if this bug has been raised before?

- [x] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [x] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by vinzscam** [comment]
I would have a look at https://backstage.io/docs/integrations/ldap/org. It might be caused by some misconfiguration

**Comment by neeraj-p2p** [comment]
I appreciate you looking into this issue, @vinzscam .

One important thing to note is that Google's LDAP service returns the output of the ldapsearch command with separate lines for member or memberOf results, rather than grouping them as an array of attributes. Could this cause any issues?

**Comment by vinzscam** [comment]
Linking this PR https://github.com/backstage/backstage/pull/27373 as it can hopefully help troubleshooting the issue

**Comment by rubennor** [comment]
I have the same issue as @neeraj-p2p but with Ping Directory.

**Comment by rubennor** [comment]
I was able to resolve the issue adding the vendor properties

```yaml
catalog:
  providers:
    ldapOrg:
      default:
        target: ....
        bind:
          dn: ...
          secret: ..
        users:
          ...
        groups:
          ...
        vendor:
          dnAttributeName: dn
          uuidAttributeName: uid
          dnCaseSensitive: false
```

**Comment by neeraj-p2p** [comment]
Thank you @rubennor . This worked.
I would like to share my configuration for reference.
```

          ldapOrg:
            default:
              target: ldaps://ldap.google.com:636
              tls:
                rejectUnauthorized: false
                keys: /app/secret-files/googleldapkey.pem
                certs: /app/secret-files/googleldapcert.pem
              schedule:
                frequency: PT5M
                timeout: PT1M
              users:
                - dn: ou=Users,dc=xyz,dc=org
                  options:
                    # One of 'base', 'one', or 'sub'.
                    scope: sub
                    filter: (&(objectClass=person)(uid=*)(!(uid=\'\')))
                    paged: false
                    attributes: ['*', '+']
                  map:
                    rdn: uid
                    name: uid
                    displayName: displayName
                    email: mail
                    memberOf: memberOf
              groups:
                - dn: ou=Groups,dc=xyz,dc=org
                  options:
                    scope: sub
                    filter: (&(objectClass=groupOfNames)(cn=*)(!(cn=\'\')))
                    attributes: ['*', '+']
                  map:
                    rdn: cn
                    name: cn
                    description: description
                    displayName: displayName
                    type: groupType
                    memberOf: memberOf
                    members: member
              vendor:
                dnAttributeName: dn
                uuidAttributeName: uid
                dnCaseSensitive: true
```

Closing this issue.
