### ISSUE TITLE
🚀 Feature: Return parsed data from EntityPicker

### ISSUE THREAD

**Issue by ddeath** [backstage/backstage#28852]
### 🔖 Feature description

It would be nice if `EntityPicker` would return something like:
```
kind: string
namespace: string
name: string
```

### 🎤 Context

Currently after user choose entity it will return string e.g.: `group:default/cards`

If we really need only `name` there is no easy way how to get it from that string since templates do not have `split()` function.

### ✌️ Possible Implementation

Alternative approach could be modify `EntityNamePicker` which would behave as `EntityPicker` (dropdown with search) but would return only name.

Both changes would be breaking changes so probably new component EntityInfoPicker could be a way

### 👀 Have you spent some time to check if this feature request has been raised before?

- [x] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [x] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by matdtr** [comment]
Hi, 

If you are using it in the scaffolder you can use the [parseEntityRef](https://backstage.io/docs/features/software-templates/writing-templates/#parseentityref ) in conjunction with `pick` filter.

**Comment by ddeath** [comment]
Yeah that works. For some reason I thought RepoUrlPicker was returning object but I see I used parseRepoUrl with pick there as well 😄

**Comment by amintong** [comment]
> Hi,
> 
> If you are using it in the scaffolder you can use the [parseEntityRef](https://backstage.io/docs/features/software-templates/writing-templates/#parseentityref) in conjunction with `pick` filter.

Could you provide a practical demo of parseEntityRef usage? I'm still unclear about its implementation

**Comment by ddeath** [comment]
@amintong here is small example, removed most part from our template and kept only parts to demostrate usage of it

```
apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: kotlin-spring-microservice
  title: Kotlin Spring Microservice
  description: Template for provisioning microservice
spec:
  owner: group:enablement
  type: service

  # These parameters are used to generate the input form in the frontend, and are
  # used to gather input data for the execution of the template.
  parameters:
    - title: Fill in some steps
      properties:
        squad:
          title: Owning Squad
          type: string
          description: Which squad is responsible for this service?
          ui:field: EntityPicker
          ui:options:
            allowArbitraryValues: false
            catalogFilter:
              - kind: Group
                spec.type: team


  # These steps are executed in the scaffolder backend, using data that we gathered
  # via the parameters above.
  steps:
    # Each step executes an action, in this case one templates files into the working directory.
    - id: fetch-template
      name: Fetch Template
      action: fetch:template
      input:
        url: https://github.com/xxxxx
        targetPath: 'microservices'
        values:
          squad: ${{ parameters.squad | parseEntityRef | pick('name') }} # app-services
```
