### ISSUE TITLE
🐛 Bug Report: Search is not displaying any TechDocs result

### ISSUE THREAD

**Issue by Ajay-Syamaladevi** [backstage/backstage#28856]
### 📜 Description

To test the performance and scalability of catalog and search in our backstage, we have created around 20k test component entities in our non-production backstage instance and uploaded a dummy single page documentation for all these component entities to a central AWS S3 buckets. And we created a brand new AWS OpenSearch cluster and configured it as Search Engine and restarted the backstage instance. It took around 40hrs to index those catalogs and its respective TechDocs to the Search Engine. Right now, we have 12,085,847 searchable documents in the AWS OpenSearch which is scattered across both Software Catalog and TechDocs index. (Attaching the screenshot).

After the cluster and instance are up and running to till now, the Search doesn't showing the TechDocs. Both Catalog and Docs pages are showing and rendering the TechDocs. Search both in home and documentation is not working.

### 👍 Expected behavior

All those documentation should properly indexed to OpenSearch and it should be searchable in both home page and documentation page.

### 👎 Actual Behavior with Screenshots

Right now, Software Catalog is searchable partially and Documentation is searchable anywhere. 

### 👟 Reproduction steps

1. Go to Search Page
2. Search for a Keyword and select Documentation filter condition.
3. Also, open a documentation and search within the page also.

### 👀 Have you spent some time to check if this bug has been raised before?

- [x] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [x] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by Ajay-Syamaladevi** [comment]
Also we are getting too many 4xx error in the cluster. My guess, it was due to Search reindexing part of scheduled collator execution.

**Comment by Ajay-Syamaladevi** [comment]
yarn backstage-cli info


OS:   Darwin 24.3.0 - darwin/arm64
node: v18.20.0
yarn: 1.22.22
cli:  0.1.0 (installed)
backstage:  1.35.0

Dependencies:
  @backstage/app-defaults                                          1.5.16
  @backstage/backend-app-api                                       1.1.1
  @backstage/backend-common                                        0.24.1, 0.25.0
  @backstage/backend-defaults                                      0.6.2, 0.7.0
  @backstage/backend-dev-utils                                     0.1.5
  @backstage/backend-dynamic-feature-service                       0.5.3
  @backstage/backend-openapi-utils                                 0.5.0-next.3, 0.4.1
  @backstage/backend-plugin-api                                    1.2.0-next.2, 0.8.1, 1.1.1
  @backstage/backend-tasks                                         0.6.1
  @backstage/backend-test-utils                                    1.2.1
  @backstage/catalog-client                                        1.9.1
  @backstage/catalog-model                                         1.7.3
  @backstage/cli-common                                            0.1.15
  @backstage/cli-node                                              0.2.12
  @backstage/config-loader                                         1.9.5
  @backstage/config                                                1.3.2
  @backstage/core-app-api                                          1.15.4
  @backstage/core-compat-api                                       0.3.5
  @backstage/core-components                                       0.13.10, 0.14.10, 0.15.1, 0.16.3
  @backstage/core-plugin-api                                       1.10.3
  @backstage/dev-utils                                             1.1.6
  @backstage/e2e-test-utils                                        0.1.1
  @backstage/errors                                                1.2.7
  @backstage/eslint-plugin                                         0.1.10
  @backstage/frontend-app-api                                      0.10.4
  @backstage/frontend-defaults                                     0.1.5
  @backstage/frontend-plugin-api                                   0.6.7, 0.9.4
  @backstage/frontend-test-utils                                   0.2.5
  @backstage/integration-aws-node                                  0.1.15
  @backstage/integration-react                                     1.2.3
  @backstage/integration                                           1.16.1
  @backstage/plugin-app-backend                                    0.4.4
  @backstage/plugin-app-node                                       0.1.29
  @backstage/plugin-app                                            0.1.5
  @backstage/plugin-auth-backend-module-atlassian-provider         0.3.4
  @backstage/plugin-auth-backend-module-auth0-provider             0.1.4
  @backstage/plugin-auth-backend-module-aws-alb-provider           0.3.2
  @backstage/plugin-auth-backend-module-azure-easyauth-provider    0.2.4
  @backstage/plugin-auth-backend-module-bitbucket-provider         0.2.4
  @backstage/plugin-auth-backend-module-bitbucket-server-provider  0.1.4
  @backstage/plugin-auth-backend-module-cloudflare-access-provider 0.3.4
  @backstage/plugin-auth-backend-module-gcp-iap-provider           0.3.4
  @backstage/plugin-auth-backend-module-github-provider            0.2.4
  @backstage/plugin-auth-backend-module-gitlab-provider            0.2.4
  @backstage/plugin-auth-backend-module-google-provider            0.2.4
  @backstage/plugin-auth-backend-module-guest-provider             0.2.4
  @backstage/plugin-auth-backend-module-microsoft-provider         0.2.4
  @backstage/plugin-auth-backend-module-oauth2-provider            0.3.4
  @backstage/plugin-auth-backend-module-oauth2-proxy-provider      0.2.4
  @backstage/plugin-auth-backend-module-oidc-provider              0.3.4
  @backstage/plugin-auth-backend-module-okta-provider              0.1.4
  @backstage/plugin-auth-backend-module-onelogin-provider          0.2.4
  @backstage/plugin-auth-backend                                   0.24.2
  @backstage/plugin-auth-node                                      0.6.0-next.2, 0.5.6
  @backstage/plugin-auth-react                                     0.1.11
  @backstage/plugin-bitbucket-cloud-common                         0.2.27
  @backstage/plugin-catalog-backend-module-aws                     0.4.7
  @backstage/plugin-catalog-backend-module-github                  0.7.9
  @backstage/plugin-catalog-backend-module-msgraph                 0.6.6
  @backstage/plugin-catalog-backend-module-scaffolder-entity-model 0.2.4
  @backstage/plugin-catalog-backend-module-unprocessed             0.5.4
  @backstage/plugin-catalog-backend                                1.30.0, 1.31.0-next.3
  @backstage/plugin-catalog-common                                 1.1.3
  @backstage/plugin-catalog-graph                                  0.4.15
  @backstage/plugin-catalog-import                                 0.12.9
  @backstage/plugin-catalog-node                                   1.16.0-next.3, 1.15.1
  @backstage/plugin-catalog-react                                  1.15.1
  @backstage/plugin-catalog-unprocessed-entities-common            0.0.7
  @backstage/plugin-catalog-unprocessed-entities                   0.2.13
  @backstage/plugin-catalog                                        1.26.1
  @backstage/plugin-devtools-backend                               0.4.2
  @backstage/plugin-devtools-common                                0.1.15
  @backstage/plugin-devtools                                       0.1.23
  @backstage/plugin-events-backend                                 0.4.1
  @backstage/plugin-events-node                                    0.4.8-next.2, 0.4.7
  @backstage/plugin-home-react                                     0.1.22
  @backstage/plugin-home                                           0.8.4
  @backstage/plugin-kubernetes-backend                             0.19.2
  @backstage/plugin-kubernetes-common                              0.9.2
  @backstage/plugin-kubernetes-node                                0.2.2
  @backstage/plugin-kubernetes-react                               0.5.3
  @backstage/plugin-kubernetes                                     0.12.3
  @backstage/plugin-org                                            0.6.35
  @backstage/plugin-permission-backend                             0.5.53
  @backstage/plugin-permission-common                              0.8.4
  @backstage/plugin-permission-node                                0.8.8-next.2, 0.8.7
  @backstage/plugin-permission-react                               0.4.30
  @backstage/plugin-proxy-backend                                  0.5.10
  @backstage/plugin-proxy-node                                     0.1.0
  @backstage/plugin-scaffolder-backend-module-azure                0.2.5
  @backstage/plugin-scaffolder-backend-module-bitbucket-cloud      0.2.5
  @backstage/plugin-scaffolder-backend-module-bitbucket-server     0.2.5
  @backstage/plugin-scaffolder-backend-module-bitbucket            0.3.6
  @backstage/plugin-scaffolder-backend-module-cookiecutter         0.3.6
  @backstage/plugin-scaffolder-backend-module-gerrit               0.2.5
  @backstage/plugin-scaffolder-backend-module-gitea                0.2.5
  @backstage/plugin-scaffolder-backend-module-github               0.5.5
  @backstage/plugin-scaffolder-backend-module-gitlab               0.7.1
  @backstage/plugin-scaffolder-backend                             1.29.0
  @backstage/plugin-scaffolder-common                              1.5.9
  @backstage/plugin-scaffolder-node-test-utils                     0.1.17
  @backstage/plugin-scaffolder-node                                0.6.3
  @backstage/plugin-scaffolder-react                               1.14.4
  @backstage/plugin-scaffolder                                     1.27.5
  @backstage/plugin-search-backend-module-catalog                  0.3.1-next.3, 0.3.0
  @backstage/plugin-search-backend-module-elasticsearch            1.6.4
  @backstage/plugin-search-backend-module-pg                       0.5.40
  @backstage/plugin-search-backend-module-techdocs                 0.3.5
  @backstage/plugin-search-backend-node                            1.3.8-next.2, 1.3.7
  @backstage/plugin-search-backend                                 1.8.1
  @backstage/plugin-search-common                                  1.2.17
  @backstage/plugin-search-react                                   1.8.5
  @backstage/plugin-search                                         1.4.22
  @backstage/plugin-signals-node                                   0.1.16
  @backstage/plugin-signals-react                                  0.0.8, 0.0.9
  @backstage/plugin-techdocs-backend                               1.11.5
  @backstage/plugin-techdocs-common                                0.1.0
  @backstage/plugin-techdocs-module-addons-contrib                 1.1.20
  @backstage/plugin-techdocs-node                                  1.12.16
  @backstage/plugin-techdocs-react                                 1.2.13
  @backstage/plugin-techdocs                                       1.12.2
  @backstage/plugin-user-settings-common                           0.0.1
  @backstage/plugin-user-settings                                  0.8.18
  @backstage/release-manifests                                     0.0.11
  @backstage/test-utils                                            1.7.4
  @backstage/theme                                                 0.6.3, 0.4.4, 0.5.7
  @backstage/types                                                 1.2.1
  @backstage/version-bridge                                        1.0.10
✨  Done in 1.86s.

**Comment by Ajay-Syamaladevi** [comment]
No error log as such. even I can see in the AWS OpenSearch, that the searchable document count is increasing. Also those techdocs index are getting created in AWS OpenSeach, but somehow the alias is not getting added. 

Regarding 4xx, I think it is due to the reindexing happening in AWS OpenSearch due to scheduled collator execution.
I will try to get more logs from CloudWatch log.

**Comment by alexlorenzi** [comment]
Hi @Ajay-Syamaladevi  - Yeah, you can share more about the 4xx errors that would be useful. Also, if you could share the directory structure of the dummy documentation that you have uploaded to your AWS bucket? It does sound like there might be an issue with the indexing, and it could be related to how you've set up the buckets.
Thanks

**Comment by Ajay-Syamaladevi** [comment]
@Ajay-Syamaladevi 4xx error is due to the reindexing happening due to multiple collators(in our case, it is catalog, documentation and announcements).

We tried the backstage default documentation and make simple modification on the content.

```YAML
site_name: 'DEVELOPER PORTAL'
site_description: 'Main documentation for Developer Portal features and framework APIs'

plugins:
  - techdocs-core
  - redirects:
      redirect_maps:
        'index.md': 'what-is-developer-portal.md'

nav:
  - Overview:
      - What is DevNav Hub?: 'what-is-developer-portal.md'
  - Core Features:
      - Software Catalog:
          - Overview: 'features/software-catalog/index.md'
      - Software Templates:
          - Overview: 'features/software-templates/index.md'
      - Global Search:
          - Overview: 'features/search/index.md'
      - TechDocs:
        - Overview: 'features/techdocs/index.md'
        - Getting Started:
            - Documentation Setup: 'features/techdocs/getting-started/doc_formats.md'
            - Git Repo Setup: 'features/techdocs/getting-started/getting_started.md'
            - More about MkDocs: 'features/techdocs/getting-started/mkdocs.md'
        - TechDocs-CLI:
            - SetUp: 'features/techdocs/TechDocs-CLI/setup.md'
            - Usage: 'features/techdocs/TechDocs-CLI/cli_commands.md'
        - Pilot Validation: 'features/techdocs/pilot_validation.md'
  - Plugins:
      - Release Plugin: 'plugins/release.md'
  - Contribute:
        - Overview: 'contribute/index.md'
        - Plugin Contribution Guide: 'contribute/plugin.md'
        - Template Contribution Guide: 'contribute/template.md'
  - FAQ:
        - Overview: 'faq/index.md'
        - Product FAQ: 'faq/product.md'
        - Technical FAQ: 'faq/technical.md'
```

I will try this option https://github.com/backstage/backstage/issues/29044. Thanks @[dfl-aeb](https://github.com/dfl-aeb)
