### ISSUE TITLE
🐛 Bug Report: gitlabRepoPush.ts issue creating a new branch in scaffolder-backend-module-gitlab

### ISSUE THREAD

**Issue by madsteer** [backstage/backstage#28851]
### 📜 Description

When running a template that tries to create a new branch on an existing gitlab project/repo, it errors and does not create the branch.

### 👍 Expected behavior

It should try to see if it already exists, and when getting a 404 then assume it's OK to create it.

I initially thought [this issue](#28587) was the same problem, but while similar, that issue's fix does not address this problem.

### 👎 Actual Behavior with Screenshots

in [gitlabRepoPush.ts, line 159](https://github.com/backstage/backstage/blob/b21d3034d0b083a75a489cafc9296fbd2bc11c7f/plugins/scaffolder-backend-module-gitlab/src/actions/gitlabRepoPush.ts#L159) you're checking
```javascript
if (e.response?.statusCode !== 404) {
```
but since you updated the @gitbeaker/rest version in the package.json it needs to now ask
```javascript
if (e.cause?.response?.status !== 404) {
```

### 👟 Reproduction steps

1. create a scaffolder template that among other things tries to create a new branch on an exisitng gitlb repo
  - yaml would look something like
     ```yaml
         - id: push
            name: Create branch on hub/backstage with starter code
           # this action allows the push if the branch exists but we should probably avoid that...
           action: gitlab:repo:push
           input:
             repoUrl: ${{ parameters.repoUrl }}
             branchName: ${{ parameters.workgroup.name }}-${{ parameters.name }}{% if parameters.wantDatabase %}-db{% endif %}
             commitAction: create
             commitMessage: Add new backend plugin ${{ parameters.name }} from template [skip ci]
             token: ${{ secrets.USER_OAUTH_TOKEN }}
     ``` 
2. run template
3. template errors with
    ```
     2025-02-13T21:41:42.257Z InputError: Failed to check status of branch 'wg113048-test-gitlab-branch-one-backend'. Please make sure that branch already exists or Backstage has permissions to create one. GitbeakerRequestError: Not Found
    at Object.handler (//dev/git/pde/backstage/node_modules/@backstage/plugin-scaffolder-backend-module- gitlab/src/actions/gitlabRepoPush.ts:160:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async NunjucksWorkflowRunner.executeStep (//dev/git/pde/backstage/node_modules/@backstage/plugin-scaffolder-backend/src/scaffolder/tasks/NunjucksWorkflowRunner.ts:373:9)
    at async NunjucksWorkflowRunner.execute (//dev/git/pde/backstage/node_modules/@backstage/plugin-scaffolder-backend/src/scaffolder/tasks/NunjucksWorkflowRunner.ts:517:9)
    at async TaskWorker.runOneTask (//dev/git/pde/backstage/node_modules/@backstage/plugin-scaffolder-backend/src/scaffolder/tasks/TaskWorker.ts:176:26)
   at async run (//dev/git/pde/backstage/node_modules/p-queue/dist/index.js:163:29)
   ```

you can also reproduce in a unit test by changing the mock in [this test](https://github.com/backstage/backstage/blob/b21d3034d0b083a75a489cafc9296fbd2bc11c7f/plugins/scaffolder-backend-module-gitlab/src/actions/gitlabRepoPush.test.ts#L337) to
```typescript
mockGitlabClient.Branches.show.mockRejectedValue({
        cause: {
          response: {
            status: 404,
          },
        },
      });
```

FYI ... not unwilling to create a PR, but I am super busy at work and I'm concerned I've oversimplified the fix.  Would like to get more seasoned eyes on this to confirm our findings.

### 🖥️ Your Environment

Using Gitlab (versus github etc.).  Nothing else unique comes to mind.

### 👀 Have you spent some time to check if this bug has been raised before?

- [x] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [x] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, I don't have time to work on this right now
