### ISSUE TITLE
🐛 Bug Report: UI throwing NotAllowedError for already created Domain entities

### ISSUE THREAD

**Issue by laimis9133** [backstage/backstage#28884]
### 📜 Description

This bug happens for Backstage catalog created Domain entities. Randomly (but often) the entities page gets prompted with the `NotAllowedError` leading all the way back to a entity location page. This location page is the initial catalog-info.yaml file set within a repository with pointers to remaining entity definition yamls including a separate yaml for domain creation. The domain itself gets created is already present within the Backstage catalog with fully built relations (and even techdocs generated for the domain entity) however seems the UI still randomly prompts the Location, Domain and all underlying child pages with the error:

```
Entity domain:default/your-created-domain at url:https://gitlab/repo/-/blob/main/catalog-info.yaml, originated at url:https://gitlab/repo/-/blob/main/catalog-info.yaml, is not of an allowed kind for that location
```

Backstage `app-config.yaml` has bee set to allow Domain entities within its rules block:
```
catalog:
  import:
    entityFilename: catalog-info.yaml
  rules:
    - allow: [ System, API, Component, Resource, Location, Group, User, Template, Domain ]
```

Backstage uses GitlabOrgDiscoveryEntityProvider for entity discovery within GitLab repositories and runs on a Kubernetes cluster as a pod. The pod logs do not contain any NotAllowedError traces.
The error itself is harmless and it takes a few Location and/or Domain refresh operations (through the same UI) for it to disappear. However it inevitably returns back after some usage.

### 👍 Expected behavior

Created Domain entities with their respective locations should not appear in the UI with NotAllowedError or the error should be captured with more detail to trace in the Backstage events log.

### 👎 Actual Behavior with Screenshots

A Location entity within a repostory is created with a `catalog-info.yaml` file:
```
apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: ceph
  description: A collection of all Ceph entities
spec:
  targets:
    - ./catalog/catalog-info.domain.yaml
    - ./catalog/catalog-info.system.yaml
    - ./catalog/catalog-info.rbd.yaml
    - ./catalog/catalog-info.s3.yaml
    - ./catalog/catalog-info.cephfs.yaml
    - ./catalog/catalog-info.sub.smaug.yaml
    - ./catalog/catalog-info.sub.warg.yaml
```

This Location entity contains a target for a Domain entity `./catalog/catalog-info.domain.yaml`:
```
apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
  name: ceph
  links:
    - url: https://ceph.infrahub.io
      title: Manager Dashboard
      icon: dashboard
  tags:
    - ceph
    - alpha-omega
  annotations:
    backstage.io/source-location: url:https://datacoin.infrahub.io/cosi/infra/ansible/collections/ceph/
    backstage.io/techdocs-ref: dir:.
spec:
  owner: infra
```

A Location and Domain entities get created succefully, however sometimes randomly the UI page promts with the NotAllowedError. This error does not make much sense since the Domain is already created and its relations built:
<img width="1555" alt="Image" src="https://github.com/user-attachments/assets/d9ac8d53-8ce1-4a19-8685-8159292ad99d" />

The error states that it originates from the Locaiton page:
<img width="1562" alt="Image" src="https://github.com/user-attachments/assets/7456c4c3-c6fa-4654-81c9-eba36c60a45d" />

Backstage logs do not show any signs of NotAllowedError. Only the usual processing messages for Location:
```
2025-02-17T20:45:11.885724205Z {"level":"debug","message":"Processing location:default/ceph","plugin":"catalog","service":"backstage"}
2025-02-17T20:46:59.722122609Z {"level":"debug","message":"Processing location:default/ceph","plugin":"catalog","service":"backstage"}
2025-02-17T20:50:14.077249447Z {"level":"debug","message":"Processing location:default/ceph","plugin":"catalog","service":"backstage"}
2025-02-17T20:50:15.613370687Z {"level":"debug","message":"Stitching location:default/ceph","plugin":"catalog","service":"backstage"}
```
And for the Domain entities:
```
2025-02-17T20:41:23.369233325Z {"level":"debug","message":"Processing domain:default/ceph","plugin":"catalog","service":"backstage"}
2025-02-17T20:42:11.823960158Z {"documentType":"techdocs","level":"debug","message":"Attempting to index the following entities: ... ... domain:default/ceph ... ...","plugin":"search","service":"backstage"}
2025-02-17T20:43:25.886975815Z {"level":"debug","message":"Processing domain:default/ceph","plugin":"catalog","service":"backstage"}
2025-02-17T20:50:02.256033133Z {"level":"debug","message":"Processing domain:default/ceph","plugin":"catalog","service":"backstage"}
2025-02-17T20:50:15.651967064Z {"level":"debug","message":"Processing domain:default/ceph","plugin":"catalog","service":"backstage"}
```

### 👟 Reproduction steps

I've explained the details in the actual behaviour, I'm not too sure if that can be easily replicated though.

### 📃 Provide the context for the Bug.

This plagues almost all of my entities that have a Domain entity at the top. It might be due to lack of knowledge setting up the relations but the fact that this error comes up randomly for already created entities is indicative of a UI(?) bug.

### 🖥️ Your Environment

Backstage version: `1.32.0`
Backstage built using: `helm.sh/chart: backstage-1.4.0`

```
  "@backstage/app-defaults@npm:1.5.12"
  "@backstage/backend-app-api@npm:1.0.1"
  "@backstage/backend-common@npm:0.25.0"
  "@backstage/backend-defaults@npm:0.5.2"
  "@backstage/backend-dev-utils@npm:0.1.5"
  "@backstage/backend-openapi-utils@npm:0.2.0"
  "@backstage/backend-plugin-api@npm:1.0.1"
  "@backstage/catalog-client@npm:1.7.1"
  "@backstage/catalog-model@npm:1.7.0"
  "@backstage/cli-common@npm:0.1.14"
  "@backstage/cli-node@npm:0.2.9"
  "@backstage/cli@npm:0.28.2"
  "@backstage/config-loader@npm:1.9.1"
  "@backstage/config@npm:1.2.0"
  "@backstage/core-app-api@npm:1.15.1"
  "@backstage/core-compat-api@npm:0.2.8"
  "@backstage/core-compat-api@npm:0.3.1"
  "@backstage/core-components@npm:0.13.10"
  "@backstage/core-components@npm:0.14.10"
  "@backstage/core-components@npm:0.15.1"
  "@backstage/core-plugin-api@npm:1.10.0"
  "@backstage/e2e-test-utils@npm:0.1.1"
  "@backstage/errors@npm:1.2.4"
  "@backstage/eslint-plugin@npm:0.1.10"
  "@backstage/frontend-app-api@npm:0.10.0"
  "@backstage/frontend-defaults@npm:0.1.1"
  "@backstage/frontend-plugin-api@npm:0.6.7"
  "@backstage/frontend-plugin-api@npm:0.7.0"
  "@backstage/frontend-plugin-api@npm:0.9.0"
  "@backstage/frontend-test-utils@npm:0.2.1"
  "@backstage/integration-aws-node@npm:0.1.12"
  "@backstage/integration-react@npm:1.2.0"
  "@backstage/integration@npm:1.15.1"
  "@backstage/plugin-api-docs@npm:0.11.11"
  "@backstage/plugin-app-backend@npm:0.3.76"
  "@backstage/plugin-app-node@npm:0.1.26"
  "@backstage/plugin-app@npm:0.1.1"
  "@backstage/plugin-auth-backend-module-atlassian-provider@npm:0.3.1"
  "@backstage/plugin-auth-backend-module-auth0-provider@npm:0.1.1"
  "@backstage/plugin-auth-backend-module-aws-alb-provider@npm:0.2.1"
  "@backstage/plugin-auth-backend-module-azure-easyauth-provider@npm:0.2.1"
  "@backstage/plugin-auth-backend-module-bitbucket-provider@npm:0.2.1"
  "@backstage/plugin-auth-backend-module-bitbucket-server-provider@npm:0.1.1"
  "@backstage/plugin-auth-backend-module-cloudflare-access-provider@npm:0.3.1"
  "@backstage/plugin-auth-backend-module-gcp-iap-provider@npm:0.3.1"
  "@backstage/plugin-auth-backend-module-github-provider@npm:0.2.1"
  "@backstage/plugin-auth-backend-module-gitlab-provider@npm:0.2.1"
  "@backstage/plugin-auth-backend-module-google-provider@npm:0.2.1"
  "@backstage/plugin-auth-backend-module-guest-provider@npm:0.2.1"
  "@backstage/plugin-auth-backend-module-microsoft-provider@npm:0.2.1"
  "@backstage/plugin-auth-backend-module-oauth2-provider@npm:0.3.1"
  "@backstage/plugin-auth-backend-module-oauth2-proxy-provider@npm:0.2.1"
  "@backstage/plugin-auth-backend-module-oidc-provider@npm:0.3.1"
  "@backstage/plugin-auth-backend-module-okta-provider@npm:0.1.1"
  "@backstage/plugin-auth-backend-module-onelogin-provider@npm:0.2.1"
  "@backstage/plugin-auth-backend@npm:0.23.1"
  "@backstage/plugin-auth-node@npm:0.5.3"
  "@backstage/plugin-auth-react@npm:0.1.7"
  "@backstage/plugin-bitbucket-cloud-common@npm:0.2.24"
  "@backstage/plugin-catalog-backend-module-gitlab-org@npm:0.2.2"
  "@backstage/plugin-catalog-backend-module-gitlab@npm:0.4.4"
  "@backstage/plugin-catalog-backend-module-logs@npm:0.1.3"
  "@backstage/plugin-catalog-backend-module-scaffolder-entity-model@npm:0.2.1"
  "@backstage/plugin-catalog-backend@npm:1.27.1"
  "@backstage/plugin-catalog-common@npm:1.1.0"
  "@backstage/plugin-catalog-graph@npm:0.4.11"
  "@backstage/plugin-catalog-import@npm:0.12.5"
  "@backstage/plugin-catalog-node@npm:1.13.1"
  "@backstage/plugin-catalog-react@npm:1.14.0"
  "@backstage/plugin-catalog@npm:1.24.0"
  "@backstage/plugin-events-node@npm:0.4.4"
  "@backstage/plugin-github-actions@npm:0.6.16"
  "@backstage/plugin-kubernetes-backend@npm:0.18.7"
  "@backstage/plugin-kubernetes-common@npm:0.8.3"
  "@backstage/plugin-kubernetes-node@npm:0.1.20"
  "@backstage/plugin-kubernetes-react@npm:0.4.4"
  "@backstage/plugin-kubernetes@npm:0.11.16"
  "@backstage/plugin-org@npm:0.6.31"
  "@backstage/plugin-permission-backend-module-allow-all-policy@npm:0.2.1"
  "@backstage/plugin-permission-backend@npm:0.5.50"
  "@backstage/plugin-permission-common@npm:0.8.1"
  "@backstage/plugin-permission-node@npm:0.8.4"
  "@backstage/plugin-permission-react@npm:0.4.27"
  "@backstage/plugin-proxy-backend@npm:0.5.7"
  "@backstage/plugin-scaffolder-backend-module-azure@npm:0.2.1"
  "@backstage/plugin-scaffolder-backend-module-bitbucket-cloud@npm:0.2.1"
  "@backstage/plugin-scaffolder-backend-module-bitbucket-server@npm:0.2.1"
  "@backstage/plugin-scaffolder-backend-module-bitbucket@npm:0.3.1"
  "@backstage/plugin-scaffolder-backend-module-gerrit@npm:0.2.1"
  "@backstage/plugin-scaffolder-backend-module-gitea@npm:0.2.1"
  "@backstage/plugin-scaffolder-backend-module-github@npm:0.5.1"
  "@backstage/plugin-scaffolder-backend-module-gitlab@npm:0.6.0"
  "@backstage/plugin-scaffolder-backend@npm:1.26.2"
  "@backstage/plugin-scaffolder-common@npm:1.5.6"
  "@backstage/plugin-scaffolder-node@npm:0.5.0"
  "@backstage/plugin-scaffolder-react@npm:1.13.2"
  "@backstage/plugin-scaffolder@npm:1.26.2"
  "@backstage/plugin-search-backend-module-catalog@npm:0.2.4"
  "@backstage/plugin-search-backend-module-pg@npm:0.5.37"
  "@backstage/plugin-search-backend-module-techdocs@npm:0.3.1"
  "@backstage/plugin-search-backend-node@npm:1.3.4"
  "@backstage/plugin-search-backend@npm:1.6.1"
  "@backstage/plugin-search-common@npm:1.2.14"
  "@backstage/plugin-search-react@npm:1.8.1"
  "@backstage/plugin-search@npm:1.4.18"
  "@backstage/plugin-signals-react@npm:0.0.6"
  "@backstage/plugin-tech-radar@npm:0.7.4"
  "@backstage/plugin-techdocs-backend@npm:1.11.1"
  "@backstage/plugin-techdocs-common@npm:0.1.0"
  "@backstage/plugin-techdocs-module-addons-contrib@npm:1.1.16"
  "@backstage/plugin-techdocs-node@npm:1.12.12"
  "@backstage/plugin-techdocs-react@npm:1.2.9"
  "@backstage/plugin-techdocs@npm:1.11.0"
  "@backstage/plugin-todo@npm:0.2.39"
  "@backstage/plugin-user-settings-common@npm:0.0.1"
  "@backstage/plugin-user-settings@npm:0.8.14"
  "@backstage/release-manifests@npm:0.0.11"
  "@backstage/test-utils@npm:1.7.0"
  "@backstage/theme@npm:0.4.4"
  "@backstage/theme@npm:0.5.7"
  "@backstage/theme@npm:0.6.0"
  "@backstage/types@npm:1.1.1"
  "@backstage/version-bridge@npm:1.0.10"
  "backstage-plugin-techdocs-addon-mermaid@npm:0.10.0"
```

### 👀 Have you spent some time to check if this bug has been raised before?

- [x] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [x] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by laimis9133** [comment]
One small but might be vital edition: I have a suspicion that this UI error gets throwed in during some processing or stiching operation with the location or domain entity involved. Will update if I manage to capture this.

**Comment by Rugvip** [comment]
How do you register the location in the catalog in the first place? Is it via config like `catalog.locations`, manually registered location in the UI, or with a discovery entity provider? Given the flakiness my hunch here is that you might be ingesting the domain entity using more than one method, but it's only allowed for some

**Comment by laimis9133** [comment]
> How do you register the location in the catalog in the first place? Is it via config like `catalog.locations`, manually registered location in the UI, or with a discovery entity provider? Given the flakiness my hunch here is that you might be ingesting the domain entity using more than one method, but it's only allowed for some

Hey. Its a **GitlabOrgDiscoveryEntityProvider** behind the hood. The `catalog.locations` have additional entries for application and library templates. We dont create anything manually through the UI.

```
catalog:
  import:
    entityFilename: catalog-info.yaml
    pullRequestBranchName: backstage-integration
  locations:
    - type: url
      target: https://.../blob/main/python/application/template.yml
    - type: url
      target: https://.../blob/main/python/library/template.yml
  rules:
    - allow: [ System, API, Component, Resource, Location, Group, User, Template, Domain ]
  providers:
    gitlab:
      datacoin:
        host: datacoin.infrahub.io
        orgEnabled: true
        schedule:
          frequency: { minutes: 2 }
          timeout: { minutes: 5 }
  orphanStrategy: delete
```

From a repository perspective location entity sits at the root of the repo in its `./catalog-info.yaml`. 
This location points to a domain entity at `.catalog/system-info.domain.yaml` in the same repository:

```text
├── catalog-info.yaml   <-- Location
├── catalog
│   ├── catalog-info.domain.yaml   <--- Domain
└── ...
```


Just adding (because missed) that this is on `1.32.0` Backstage btw.
