### ISSUE TITLE
🚀 Feature: Allow GithubRepoPicker to filter by repository permission

### ISSUE THREAD

**Issue by sonikro** [backstage/backstage#28907]
### 🔖 Feature description

- Add a new option to the GithubRepoPicker, such as **permissionsFilter** that receives one of the following options:  ['admin', 'push', 'pull']

This would allow template developers to filter down available options from the new auto-complete, to only repositories that users have a specific permission.

### 🎤 Context

In my use case, we have templates that can only be executed by users that have **admin** permissions on a repository. The current implementation with auto-complete will provide all repos the user can see as possible options. So a new option like this would allow for template developers to specify if they want to filter the selection of repositories.

This feature would not require any new API Calls, since the API Response from GitHub to list repositories already contain this object:

```json
   "permissions": {
      "admin": false,
      "push": false,
      "pull": true
    },
```

So we'd only have to filter results based on the parameter value.

### ✌️ Possible Implementation

Add a new **ui:option** specific for GithubRepoPicker to allow users to specify that filter:

```yaml
      RepoUrlPicker:
        type: string
        ui:field: RepoUrlPicker
        ui:options:
          github:
               permissionsFilter: admin # only show repositories user has admin access to for auto-complete

```

### 👀 Have you spent some time to check if this feature request has been raised before?

- [x] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [x] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!
