### ISSUE TITLE
Allow the user to decide the name of each database

### ISSUE THREAD

**Issue by martina-if** [backstage/backstage#2894]
## Feature Suggestion

This is something that Backstage had before but has been changed recently.

The name of the database that each plugin uses is now decided by the code. I think there should be a way to completely override the name of the database from the configuration. There are mainly two use cases for this:

- Testing: one may want to run several end to end tests agains the same postgresql in parallel. In this case the test suite would need to define a different db name for each test.
- some organizations may have strict requirements in how their resources are named. For example, there could be a rule that says that the db name has to be prefixed with a team or department name.

I believe in general it is common practice to allow the admin of an application to choose the name of the database from its configuration rather than having the code dictate it since this gives more flexibility for different environments.

## Possible Implementation

Ideally there could be a default db name like Backstage has today but one could also specify a different name via the config file:

```
backend:
  database:
    connection:
      database: "my-backstage-db"
pluginA:
  database:
    connection:
      database: "plugin-a-db"
```

and for lighthouse:

```
PGDATABASE: "my-lighthouse-db"
```

**Comment by Rugvip** [comment]
Agree that this would be something to support out of the box tbh. It's very much possible to implement your own `PluginDatabaseManager` using pieces from `@backstage/backend-common`, but this is likely common enough that we should provide a solution for it.

Another option is something along this:

```yaml
backend:
  database:
    connection:
      database: "my-backstage-db"

    forPlugin:
      a:
        connection:
          database: "plugin-a-db"
```

**Comment by andrewthauer** [comment]
Another use case for this would be 2 sets of databases for local development (which I've recently run into). An internal org instance and the other for the open source instance. Since migrations may be different across the 2 instances it makes sharing test databases problematic. I have some additional thoughts:

The current `createDatabaseClient` helper takes in a `database` config structure and is more or less passed along to the knex connection. So nesting this under `backend.database` would require any code that config block to omit `forPlugin` setting. It might be easier to add a `backend.pluginDatabases` key instead to avoid this.

```yaml
backend:
  database:
    connection:
      database: "my-backstage-db"

  pluginDatabases:
      a:
        connection:
          database: "plugin-a-db"
```

Are we suggesting to duplicate the entire connection settings or just the database name? I can see it being useful to allow a completely different connection per plugin. I suppose to keep it DRY in more simple cases yaml anchors could be used, but gets a little messy with the nested connection setting.

```yaml

backend:
  database: &default_database
    client: pg
    connection: &default_db_connection
      database: "my-backstage-db"

  pluginDatabases:
    catalog:
      <<: *default_database
      connection:
        <<: *default_db_connection
        database: "plugin-catalog-db"
```

Another option would be to "magically" inherit the `backend.database` config or have some way of configuring this.

**Comment by Rugvip** [comment]
@andrewthauer Yeah it's nice to not have to magically remove the `forPlugin` key. Regarding the behaviour I think a bit of copy-paste doesn't hurt too much. Yaml anchors can help out a bit, and if people end up with a hundred lines of db config yaml we can perhaps take another stab at it.

I'm not crazy about having both `database` and `pluginDatabase`, although it's just a naming thing. All databases are plugin databases, since the backend doesn't have its own database.

Another option, although it doesn't sit perfectly with me either tbh x)

```yaml
backend:
  database:
    default:
      connection:
        database: "my-backstage-db"

    a:
      connection:
        database: "plugin-a-db"
```

I think your suggestion is the most realistic one, could be something like `pluginDatabaseOverrides` too? Although I think I prefer `pluginDatabases` over that too ¯\\\_(ツ)\_/¯

**Comment by andrewthauer** [comment]
@Rugvip - That's a valid point that there isn't actually a `backend` database. Another minor variation could be something like this:

```yaml
backend:
  # deprecated (used for backwards compatibility for `default_database`
  database:
    default:
      connection:
        database: "my-backstage-db"
  
  # new key to replace `database`
  default_database: # add anchor if you like to use in `databases`
    connection: ....

  # new plural databases key (optional for overrides)
  databases:
    a:
      connection:
        database: "plugin-a-db"
```

**Comment by freben** [comment]
maybe with the addition that the default one has one more feature:

```yaml
backend:
  defaultDatabase: # should use camel casing
    connection:
      databaseNamePattern: backstage_plugin_%p
```

That one would obviously have to be deleted from the input structure and replaced with an actual database name.

Or maybe that doesn't help much more than just asking people to repeat their database connections in `database`.
