### ISSUE TITLE
🐛 Bug Report: Scaffolder Dependency does not update ui:options:catalogFilter

### ISSUE THREAD

**Issue by hghtwr** [backstage/backstage#29030]
### 📜 Description

When you set ```ui:options:catalogFilter``` in the dependencies a templates parameters, the filter values are not updated alongside the selected values. 

In general, I'm willing to work on this but I'm not familiar with the scaffolder frontend and need some help about the right direction to look into first. 

### 👍 Expected behavior

It should correctly update not only the description of the field but also the `ui:options:catalogFilter` value and rerender the field.

### 👎 Actual Behavior with Screenshots

If I select one of the non-prod entities, you can see it correctly shows only non-prod clusters.
![Image](https://github.com/user-attachments/assets/0fda82c5-8db5-4112-ac40-ea0baa765be9)

If I select the prod environment you can see it correctly updates the description of the field but it will not update the filter.
![Image](https://github.com/user-attachments/assets/6266f5fa-0566-4bf5-bc08-4a3dcb08b023)

My observation is that most of the time, the second item in the `dependencies.environment.oneOf` array is selected for the `catalogFilter`. It's not 100% reproducible like this, a few times, it also took the first item.

A workaround is, to name the fields differently, in this case, it works perfectly fine: 
```yaml
    dependencies:
      environment:
        oneOf:
          - properties:
              environment:
                enum:
                  - system:default/dev-env
              clusters:
                title: Clusters - NONPROD
                type: array
                ui:field: MultiEntityPicker
                ui:options:
                  catalogFilter:
                    - kind: Resource
                      spec.lifecycle: non-prod
                  allowedKinds:
                    - Resource
          - properties:
              environment:
                enum:
                  - system:default/prod-env
              clusters2:                                                         #### If I rename this, it works.
                title: Clusters - PROD
                type: array
```

### 👟 Reproduction steps

```yaml
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: workload-non-prod-0 
  description: Workload cluster non-prod-0
spec:
  type: cluster
  owner: john-doe
  lifecycle: non-prod
  system: system:default/whatever
```

```yaml
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: workload-prod-0 
  description: Workload cluster prod-0
spec:
  type: cluster
  owner: john-doe
  lifecycle: prod
  system: system:default/whatever
```

```yaml
parameters:
  - title: Provide some simple information
    required:
      - clusters
      - environment
    properties:
      environment:
        title: Environment
        type: string
        description: Logical environment
        ui:field: EntityPicker
        ui:options:
          allowedKinds:
            - System
          catalogFilter:
            - kind: System
              spec.type: environment
    dependencies:
      environment:
        oneOf:
          - properties:
              environment:
                enum:
                  - system:default/dev-env
              clusters:
                title: Clusters - NONPROD
                type: array
                description: Select the workload clusters that should be able to access the
                  ElastiCache Redis Replication.
                ui:field: MultiEntityPicker
                ui:options:
                  catalogFilter:
                    - kind: Resource
                      spec.lifecycle: non-prod
                  allowedKinds:
                    - Resource
          - properties:
              environment:
                enum:
                  - system:default/prod-env
              clusters:
                title: Clusters - PROD
                type: array
                description: Select the workload clusters that should be able to access the
                  ElastiCache Redis Replication.
                ui:field: MultiEntityPicker
                ui:options:
                  catalogFilter:
                    - kind: Resource
                      spec.lifecycle: prod
                  allowedKinds:
                    - Resource
```

### 📃 Provide the context for the Bug.

We have different `Resources` in our catalog, each one for our kubernetes clusters. They are separated into different environments by the `spec.lifecycle`. Our intention is to offer a field in the scaffolder with logical environments that map 1:1 to a prod or non-prod cluster. 

### 🖥️ Your Environment

```
OS:   Linux 5.15.167.4-microsoft-standard-WSL2 - linux/x64
node: v20.18.3
yarn: 4.4.1
cli:  0.29.6 (installed)
backstage:  1.35.1

Dependencies:
  @backstage/app-defaults                                          1.5.16
  @backstage/backend-app-api                                       0.7.5, 1.1.1
  @backstage/backend-common                                        0.22.0, 0.23.3, 0.24.1, 0.25.0
  @backstage/backend-defaults                                      0.7.0
  @backstage/backend-dev-utils                                     0.1.5
  @backstage/backend-openapi-utils                                 0.4.1
  @backstage/backend-plugin-api                                    0.6.18, 0.7.0, 0.8.1, 1.1.1
  @backstage/backend-tasks                                         0.5.27, 0.6.1
  @backstage/catalog-client                                        1.9.1
  @backstage/catalog-model                                         1.7.3
  @backstage/cli-common                                            0.1.15
  @backstage/cli-node                                              0.2.12
  @backstage/cli                                                   0.29.6
  @backstage/config-loader                                         1.9.5
  @backstage/config                                                1.3.2
  @backstage/core-app-api                                          1.15.4
  @backstage/core-compat-api                                       0.2.8, 0.3.5
  @backstage/core-components                                       0.13.10, 0.14.10, 0.16.3
  @backstage/core-plugin-api                                       1.10.3
  @backstage/errors                                                1.2.7
  @backstage/eslint-plugin                                         0.1.10
  @backstage/frontend-app-api                                      0.10.4
  @backstage/frontend-defaults                                     0.1.5
  @backstage/frontend-plugin-api                                   0.6.7, 0.7.0, 0.9.4
  @backstage/frontend-test-utils                                   0.2.5
  @backstage/integration-aws-node                                  0.1.15
  @backstage/integration-react                                     1.2.3
  @backstage/integration                                           1.16.1
  @backstage/plugin-api-docs                                       0.12.3
  @backstage/plugin-app                                            0.1.5
  @backstage/plugin-auth-backend-module-atlassian-provider         0.3.4
  @backstage/plugin-auth-backend-module-auth0-provider             0.1.4
  @backstage/plugin-auth-backend-module-aws-alb-provider           0.3.2
  @backstage/plugin-auth-backend-module-azure-easyauth-provider    0.2.4
  @backstage/plugin-auth-backend-module-bitbucket-provider         0.2.4
  @backstage/plugin-auth-backend-module-bitbucket-server-provider  0.1.4
  @backstage/plugin-auth-backend-module-cloudflare-access-provider 0.3.4
  @backstage/plugin-auth-backend-module-gcp-iap-provider           0.3.4
  @backstage/plugin-auth-backend-module-github-provider            0.2.4
  @backstage/plugin-auth-backend-module-gitlab-provider            0.2.4
  @backstage/plugin-auth-backend-module-google-provider            0.2.4
  @backstage/plugin-auth-backend-module-microsoft-provider         0.2.4
  @backstage/plugin-auth-backend-module-oauth2-provider            0.3.4
  @backstage/plugin-auth-backend-module-oauth2-proxy-provider      0.2.4
  @backstage/plugin-auth-backend-module-oidc-provider              0.3.4
  @backstage/plugin-auth-backend-module-okta-provider              0.1.4
  @backstage/plugin-auth-backend-module-onelogin-provider          0.2.4
  @backstage/plugin-auth-backend                                   0.24.2
  @backstage/plugin-auth-node                                      0.4.17, 0.5.6
  @backstage/plugin-auth-react                                     0.1.11
  @backstage/plugin-bitbucket-cloud-common                         0.2.27
  @backstage/plugin-catalog-backend-module-gitlab-org              0.2.5
  @backstage/plugin-catalog-backend-module-gitlab                  0.6.2
  @backstage/plugin-catalog-backend-module-scaffolder-entity-model 0.2.4
  @backstage/plugin-catalog-backend                                1.30.0
  @backstage/plugin-catalog-common                                 1.1.3
  @backstage/plugin-catalog-graph                                  0.4.15
  @backstage/plugin-catalog-import                                 0.12.9
  @backstage/plugin-catalog-node                                   1.15.1
  @backstage/plugin-catalog-react                                  1.15.1
  @backstage/plugin-catalog                                        1.26.1
  @backstage/plugin-events-node                                    0.4.7
  @backstage/plugin-home-react                                     0.1.22
  @backstage/plugin-home                                           0.8.4
  @backstage/plugin-org                                            0.6.35
  @backstage/plugin-permission-common                              0.7.13, 0.8.4
  @backstage/plugin-permission-node                                0.7.29, 0.8.7
  @backstage/plugin-permission-react                               0.4.30
  @backstage/plugin-proxy-backend                                  0.5.10
  @backstage/plugin-proxy-node                                     0.1.0
  @backstage/plugin-scaffolder-backend-module-azure                0.2.5
  @backstage/plugin-scaffolder-backend-module-bitbucket-cloud      0.2.5
  @backstage/plugin-scaffolder-backend-module-bitbucket-server     0.2.5
  @backstage/plugin-scaffolder-backend-module-bitbucket            0.3.6
  @backstage/plugin-scaffolder-backend-module-gerrit               0.2.5
  @backstage/plugin-scaffolder-backend-module-gitea                0.2.5
  @backstage/plugin-scaffolder-backend-module-github               0.5.5
  @backstage/plugin-scaffolder-backend-module-gitlab               0.7.1
  @backstage/plugin-scaffolder-backend                             1.29.0
  @backstage/plugin-scaffolder-common                              1.5.9
  @backstage/plugin-scaffolder-node                                0.4.11, 0.6.3
  @backstage/plugin-scaffolder-react                               1.14.4
  @backstage/plugin-scaffolder                                     1.27.5
  @backstage/plugin-search-backend-module-catalog                  0.3.0
  @backstage/plugin-search-backend-module-pg                       0.5.40
  @backstage/plugin-search-backend-module-techdocs                 0.3.5
  @backstage/plugin-search-backend-node                            1.3.7
  @backstage/plugin-search-backend                                 1.8.1
  @backstage/plugin-search-common                                  1.2.17
  @backstage/plugin-search-react                                   1.8.5
  @backstage/plugin-search                                         1.4.22
  @backstage/plugin-signals-react                                  0.0.9
  @backstage/plugin-techdocs-backend                               1.11.5
  @backstage/plugin-techdocs-common                                0.1.0
  @backstage/plugin-techdocs-module-addons-contrib                 1.1.20
  @backstage/plugin-techdocs-node                                  1.12.16
  @backstage/plugin-techdocs-react                                 1.2.13
  @backstage/plugin-techdocs                                       1.12.2
  @backstage/plugin-user-settings-common                           0.0.1
  @backstage/plugin-user-settings                                  0.8.18
  @backstage/release-manifests                                     0.0.12
  @backstage/test-utils                                            1.7.4
  @backstage/theme                                                 0.4.2, 0.5.6, 0.6.3
  @backstage/types                                                 1.2.1
  @backstage/version-bridge                                        1.0.10
```

### 👀 Have you spent some time to check if this bug has been raised before?

- [x] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [x] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!
