### ISSUE TITLE
gitlab.ts issue creating a new repository in scaffolder-backend-module-gitlab

### ISSUE THREAD

**Issue by madsteer** [backstage/backstage#29036]
### 📜 Description

Almost identical to #28851 but in a different section of code. When running a template that tries to create a new project in an existing gitlab namespace, it errors and does not create the project.

### 👍 Expected behavior

It should try to see if it already exists, and when getting a 404 then assume it's OK to create it.

### 👎 Actual Behavior with Screenshots

In [gitlab.ts](https://github.com/backstage/backstage/blob/563a7a534075722d2f1d77e22610c001b8a8cac9/plugins/scaffolder-backend-module-gitlab/src/actions/gitlab.ts#L390) you're checking
```javascript
if (e.response && e.response.statusCode === 404) {
```
but since you updated the @gitbeaker/rest version in the package.json it needs to now ask
```javascript
if (e.cause?.response?.status === 404) {
```

### 👟 Reproduction steps

1. Create a scaffolder template that among other things tries to create a new project in an exisitng gitlb namespace
   - yaml would look something like:
     ```yaml
     - id: publish
        name: Publish
        action: publish:gitlab
        input:
          allowedHosts: ["gitlab.com"]
          token: ${{ secrets.USER_OAUTH_TOKEN }}
          description: This is ${{ parameters.name }}
          repoUrl: ${{ parameters.repoUrl }}
          defaultBranch: main
          gitCommitMessage: "Initial Commit"
          settings:
            visibility: internal
            description: ${{ parameters.description }}
          branches:
            - name: main
              protected: true
            - name: draft
              create: true
              ref: "main"
              protected: true

     ```
2. run template
3. template errros with:
   ```shell
      2025-03-03T20:18:04.250Z Beginning step Publish[17](https://backstage-dev.hub.test.ic1.statefarm/create/tasks/484b79f7-e7dd-47e5-bb4c-4b1faa7a77a8#line-17)
      2025-03-03T20:18:04.694Z GitbeakerRequestError: Not Found[18](https://backstage-dev.hub.test.ic1.statefarm/create/tasks/484b79f7-e7dd-47e5-bb4c-4b1faa7a77a8#line-18)
         at throwFailedRequestError (/backstage/node_modules/@gitbeaker/rest/dist/index.js:63:9)[19](https://backstage-dev.hub.test.ic1.statefarm/create/tasks/484b79f7-e7dd-47e5-bb4c-4b1faa7a77a8#line-19)
         at process.processTicksAndRejections (node:internal/process/task_queues:95:5)[20](https://backstage-dev.hub.test.ic1.statefarm/create/tasks/484b79f7-e7dd-47e5-bb4c-4b1faa7a77a8#line-20)
         at async defaultRequestHandler (/backstage/node_modules/@gitbeaker/rest/dist/index.js:96:48)
   ```

you can also reproduce in a unit test by changing the mock in [this test](https://github.com/backstage/backstage/blob/563a7a534075722d2f1d77e22610c001b8a8cac9/plugins/scaffolder-backend-module-gitlab/src/actions/gitlab.test.ts#L644)
```javascript
mockGitlabClient.Namespaces.show.mockRejectedValue({
    response: {
      statusCode: 404,
   },
 });
```

Hope to have a PR built shortly

### 🖥️ Your Environment

Using Gitlab (versus Github).  

### 👀 Have you spent some time to check if this bug has been raised before?

- [x] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [x] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!
