### ISSUE TITLE
🐛 Bug Report: LDAP Provider unable to configure multiple user/group block for same provider

### ISSUE THREAD

**Issue by ivangonzalezacuna** [backstage/backstage#29041]
### 📜 Description

Until now, we were using the LDAP provider in our company to fetch users and groups within our Active Directory. but we were only defining 1 block for each. However, and due to some new requirements, we need to fetch more users that are part of our Active Directory and need to define 3 different user blocks with different filters.

However, and contrary to what the documentation at https://backstage.io/docs/integrations/ldap/org/#configuration, it seems impossible to us to configure an array of user blocks, since it keeps complaining and the backend never starts.

We have tested this is 2 different approaches:

- Using `yarn dev`, which worked totally fine and the different blocks of users are obtained as expected
- Using the docker setup, which crashes when starting the backend

### 👍 Expected behavior

We would expect that the `yarn dev` and the `docker` setups would work the same way and would allow us to inject more users into our Backstage instance.

### 👎 Actual Behavior with Screenshots

When running with `yarn dev`, the LDAP provider works as expected and all the data is loaded. But if we run it using the `docker` setup, then it crashes on the startup with the following error:

```sh
backstage-1     | node:internal/process/promises:394
backstage-1     |     triggerUncaughtException(err, true /* fromPromise */);
backstage-1     |     ^
backstage-1     | 
backstage-1     | ForwardedError: Plugin 'app' startup failed; caused by Error: Invalid app bundle schema. If this error is unexpected you need to run `yarn build` in the app. If that doesn't help you should make sure your config schema is correct and rebuild the app bundle again. Caused by the following schema error, Error: Config validation failed, Config must be object { type=object } at /catalog/providers/ldapOrg/our-ldap-provider/users; Config must be object { type=object } at /catalog/providers/ldapOrg/our-ldap-provider/groups
backstage-1     |     at /app/node_modules/@backstage/backend-app-api/dist/wiring/BackendInitializer.cjs.js:285:21
backstage-1     |     at async /app/node_modules/@backstage/backend-app-api/dist/wiring/BackendInitializer.cjs.js:284:13
backstage-1     |     ... 3 lines matching cause stack trace ...
backstage-1     |     at async BackstageBackend.start (/app/node_modules/@backstage/backend-app-api/dist/wiring/BackstageBackend.cjs.js:19:5) {
backstage-1     |   cause: Error: Invalid app bundle schema. If this error is unexpected you need to run `yarn build` in the app. If that doesn't help you should make sure your config schema is correct and rebuild the app bundle again. Caused by the following schema error, Error: Config validation failed, Config must be object { type=object } at /catalog/providers/ldapOrg/our-ldap-provider/users; Config must be object { type=object } at /catalog/providers/ldapOrg/our-ldap-provider/groups
backstage-1     |       at Object.readFrontendConfig (/app/node_modules/@backstage/plugin-app-backend/dist/lib/config/readFrontendConfig.cjs.js:26:13)
backstage-1     |       at async Object.createRouter (/app/node_modules/@backstage/plugin-app-backend/dist/service/router.cjs.js:49:56)
backstage-1     |       at async Object.init [as func] (/app/node_modules/@backstage/plugin-app-backend/dist/service/appPlugin.cjs.js:43:26)
backstage-1     |       at async /app/node_modules/@backstage/backend-app-api/dist/wiring/BackendInitializer.cjs.js:284:13
backstage-1     |       at async Promise.allSettled (index 0)
backstage-1     |       at async #doStart (/app/node_modules/@backstage/backend-app-api/dist/wiring/BackendInitializer.cjs.js:233:21)
backstage-1     |       at async BackendInitializer.start (/app/node_modules/@backstage/backend-app-api/dist/wiring/BackendInitializer.cjs.js:163:5)
backstage-1     |       at async BackstageBackend.start (/app/node_modules/@backstage/backend-app-api/dist/wiring/BackstageBackend.cjs.js:19:5)
backstage-1     | }
backstage-1     | 
backstage-1     | Node.js v22.13.1
```

### 👟 Reproduction steps

To reproduce it, do the following steps:

As a startup, have a similar block to this in your `app-config.yaml` to setup the ldap provider, inside `catalog.providers`:

    ```yaml
    ldapOrg:
      our-ldap-provider:
        target: ${LDAP_URL}
        bind:
          dn: ${LDAP_USER}
          secret: ${LDAP_PASSWORD}
        users:
            dn: <DN>
            options:
              filter: <FILTER>
              scope: sub
              paged: { pageSize: 1000, pagePause: true }
            map:
              rdn: cn
              name: sAMAccountName
              displayName: displayName
              description: title
              memberOf: memberOf
        groups:
            dn: <DN>
            options:
              filter: <FILTER>
              scope: one
              paged: { pageSize: 1000, pagePause: true }
            map:
              rdn: cn
              name: cn
              description: cn
              # type: groupType
              displayName: cn
              memberOf: memberOf
              members: member
        schedule:
          frequency: { hours: 1 }
          timeout: { hours: 1 }
          initialDelay: { seconds: 10 }
    ```

Also, make sure to have the backend initialized with the corresponding `backend.add(import('@backstage/plugin-catalog-backend-module-ldap'));` at your `packages/backend/src/index.ts`.

Also, and for reference, this is our `Dockerfile`:

```
# Stage 1 - Create yarn install skeleton layer
FROM node:22.13.1-alpine AS skeleton

WORKDIR /app
COPY package.json yarn.lock ./

COPY packages packages
COPY plugins plugins

RUN find packages plugins \! -name "package.json" -mindepth 2 -maxdepth 2 -exec rm -rf {} \+

# Stage 2 - Install dependencies and build packages
FROM node:22.13.1-bookworm-slim AS build

RUN --mount=type=cache,target=/var/cache/apt,sharing=locked \
    --mount=type=cache,target=/var/lib/apt,sharing=locked \
    apt-get update && \
    apt-get install -y --no-install-recommends python3 build-essential git && \
    rm -rf /var/lib/apt/lists/*

# Set Python interpreter for `node-gyp` to use
ENV PYTHON /usr/bin/python3

WORKDIR /app

COPY --from=skeleton /app .

# Copy yarn3 files
COPY .yarn ./.yarn
COPY .yarnrc.yml ./

# Stop cypress from downloading it's massive binary.
ENV CYPRESS_INSTALL_BINARY=0
RUN --mount=type=cache,target=/home/node/.cache/yarn,sharing=locked \
    yarn install --immutable --network-timeout 600000

COPY . .

RUN yarn tsc

RUN BACKSTAGE_BASE_URL=http://example.com GRAFANA_BASE_URL=http://example.com RELEASES_BASE_URL=http://example.com K8S_CLUSTER_ID=development yarn build:all

FROM node:22.13.1-alpine

WORKDIR /app

COPY --from=build /app/packages/backend/dist/skeleton.tar.gz ./
COPY --from=build /app/packages/backend/dist/bundle.tar.gz ./
COPY --from=build /app/.yarn ./.yarn
COPY --from=build /app/.yarnrc.yml ./

RUN apk --update --no-cache add python3 make g++

RUN tar xzf skeleton.tar.gz && rm skeleton.tar.gz

COPY app-config.yaml yarn.lock package.json ./

RUN --mount=type=cache,target=/home/node/.cache/yarn,sharing=locked \
    yarn workspaces focus --all --production && rm -rf "$(yarn cache clean)"

RUN tar xzf bundle.tar.gz && rm bundle.tar.gz

CMD ["node", "packages/backend", "--config", "app-config.yaml", "--config", "config/app-config.auth.yaml", "--config", "config/contact-points.yaml", "--config", "config/tech-insights.yaml"]
```

With this setup, if you run `yarn dev` it will work fine. If you build the docker image and then you start it, it will also work well.

Then, apply these changes to your `ldapOrg` block (basically, make the users and groups an array now, which is supported as the documentation says):

    ```yaml
    ldapOrg:
      our-ldap-provider:
        target: ${LDAP_URL}
        bind:
          dn: ${LDAP_USER}
          secret: ${LDAP_PASSWORD}
        users:
          - dn: <DN>
            options:
              filter: <FILTER>
              scope: sub
              paged: { pageSize: 1000, pagePause: true }
            map:
              rdn: cn
              name: sAMAccountName
              displayName: displayName
              description: title
              memberOf: memberOf
        groups:
          - dn: <DN>
            options:
              filter: <FILTER>
              scope: one
              paged: { pageSize: 1000, pagePause: true }
            map:
              rdn: cn
              name: cn
              description: cn
              # type: groupType
              displayName: cn
              memberOf: memberOf
              members: member
        schedule:
          frequency: { hours: 1 }
          timeout: { hours: 1 }
          initialDelay: { seconds: 10 }
    ```

Again, run the `yarn dev` (which will work). However, if you build the docker container and start it, then the backend will fail with the error mentioned above

### 📃 Provide the context for the Bug.

We want to make use of the same LDAP client to request 3 different user blocks and inject them into our catalog, and taking the chance to use the [`set` parameter](https://backstage.io/docs/integrations/ldap/org/#usersset) to inject custom labels depending on the group the user is found on.

According to the `config.d.ts`, it looks like the old `ldap` (still present for backward compatibility) supports the arrays, but the new one doesn't (https://github.com/backstage/backstage/blob/master/plugins/catalog-backend-module-ldap/config.d.ts). Is this something that might have get forgotten?

However, this doesn't seem to be the case at all.

### 🖥️ Your Environment

```sh
$ yarn backstage-cli info
OS:   Linux 6.8.0-54-generic - linux/x64
node: v22.12.0
yarn: 4.4.1
cli:  0.30.0 (installed)
backstage:  1.36.1

Dependencies:
  @backstage/app-defaults                                          1.5.17
  @backstage/backend-app-api                                       1.2.0
  @backstage/backend-common                                        0.24.1, 0.25.0
  @backstage/backend-defaults                                      0.5.3, 0.7.0, 0.8.1
  @backstage/backend-dev-utils                                     0.1.5
  @backstage/backend-openapi-utils                                 0.3.0, 0.4.1, 0.5.0
  @backstage/backend-plugin-api                                    0.8.1, 1.2.0
  @backstage/backend-tasks                                         0.6.1
  @backstage/backend-test-utils                                    1.3.0
  @backstage/catalog-client                                        1.9.1
  @backstage/catalog-model                                         1.7.3
  @backstage/cli-common                                            0.1.15
  @backstage/cli-node                                              0.2.13
  @backstage/cli                                                   0.30.0
  @backstage/config-loader                                         1.9.6
  @backstage/config                                                1.3.2
  @backstage/core-app-api                                          1.15.5
  @backstage/core-compat-api                                       0.3.6
  @backstage/core-components                                       0.14.10, 0.16.4
  @backstage/core-plugin-api                                       1.10.4
  @backstage/dev-utils                                             1.1.7
  @backstage/e2e-test-utils                                        0.1.1
  @backstage/errors                                                1.2.7
  @backstage/eslint-plugin                                         0.1.10
  @backstage/frontend-app-api                                      0.10.5
  @backstage/frontend-defaults                                     0.1.6
  @backstage/frontend-plugin-api                                   0.9.5
  @backstage/frontend-test-utils                                   0.2.6
  @backstage/integration-aws-node                                  0.1.15
  @backstage/integration-react                                     1.2.4
  @backstage/integration                                           1.16.1
  @backstage/plugin-api-docs                                       0.12.4
  @backstage/plugin-app-backend                                    0.4.5
  @backstage/plugin-app-node                                       0.1.30
  @backstage/plugin-app                                            0.1.6
  @backstage/plugin-auth-backend-module-atlassian-provider         0.4.0
  @backstage/plugin-auth-backend-module-auth0-provider             0.2.0
  @backstage/plugin-auth-backend-module-aws-alb-provider           0.4.0
  @backstage/plugin-auth-backend-module-azure-easyauth-provider    0.2.5
  @backstage/plugin-auth-backend-module-bitbucket-provider         0.3.0
  @backstage/plugin-auth-backend-module-bitbucket-server-provider  0.2.0
  @backstage/plugin-auth-backend-module-cloudflare-access-provider 0.4.0
  @backstage/plugin-auth-backend-module-gcp-iap-provider           0.4.0
  @backstage/plugin-auth-backend-module-github-provider            0.3.0
  @backstage/plugin-auth-backend-module-gitlab-provider            0.3.0
  @backstage/plugin-auth-backend-module-google-provider            0.3.0
  @backstage/plugin-auth-backend-module-guest-provider             0.2.5
  @backstage/plugin-auth-backend-module-microsoft-provider         0.3.0
  @backstage/plugin-auth-backend-module-oauth2-provider            0.4.0
  @backstage/plugin-auth-backend-module-oauth2-proxy-provider      0.2.5
  @backstage/plugin-auth-backend-module-oidc-provider              0.4.0
  @backstage/plugin-auth-backend-module-okta-provider              0.2.0
  @backstage/plugin-auth-backend-module-onelogin-provider          0.3.0
  @backstage/plugin-auth-backend                                   0.24.3
  @backstage/plugin-auth-node                                      0.5.6, 0.6.0
  @backstage/plugin-auth-react                                     0.1.12
  @backstage/plugin-bitbucket-cloud-common                         0.2.27
  @backstage/plugin-catalog-backend-module-gitlab                  0.6.3
  @backstage/plugin-catalog-backend-module-incremental-ingestion   0.6.3
  @backstage/plugin-catalog-backend-module-ldap                    0.11.2
  @backstage/plugin-catalog-backend-module-logs                    0.1.7
  @backstage/plugin-catalog-backend-module-scaffolder-entity-model 0.2.5
  @backstage/plugin-catalog-backend-module-unprocessed             0.5.5
  @backstage/plugin-catalog-backend                                1.31.0
  @backstage/plugin-catalog-common                                 1.1.3
  @backstage/plugin-catalog-graph                                  0.4.16
  @backstage/plugin-catalog-import                                 0.12.10
  @backstage/plugin-catalog-node                                   1.16.0
  @backstage/plugin-catalog-react                                  1.15.2
  @backstage/plugin-catalog-unprocessed-entities-common            0.0.7
  @backstage/plugin-catalog-unprocessed-entities                   0.2.14
  @backstage/plugin-catalog                                        1.27.0
  @backstage/plugin-events-backend                                 0.3.16, 0.4.3
  @backstage/plugin-events-node                                    0.4.8
  @backstage/plugin-home-react                                     0.1.23
  @backstage/plugin-home                                           0.8.5
  @backstage/plugin-kubernetes-backend                             0.19.3
  @backstage/plugin-kubernetes-common                              0.9.3
  @backstage/plugin-kubernetes-node                                0.2.3
  @backstage/plugin-kubernetes-react                               0.5.4
  @backstage/plugin-kubernetes                                     0.12.4
  @backstage/plugin-org                                            0.6.36
  @backstage/plugin-permission-backend                             0.5.54
  @backstage/plugin-permission-common                              0.8.4
  @backstage/plugin-permission-node                                0.8.8
  @backstage/plugin-permission-react                               0.4.31
  @backstage/plugin-proxy-backend                                  0.5.11
  @backstage/plugin-proxy-node                                     0.1.1
  @backstage/plugin-scaffolder-backend-module-azure                0.2.6
  @backstage/plugin-scaffolder-backend-module-bitbucket-cloud      0.2.6
  @backstage/plugin-scaffolder-backend-module-bitbucket-server     0.2.6
  @backstage/plugin-scaffolder-backend-module-bitbucket            0.3.7
  @backstage/plugin-scaffolder-backend-module-gerrit               0.2.6
  @backstage/plugin-scaffolder-backend-module-gitea                0.2.6
  @backstage/plugin-scaffolder-backend-module-github               0.6.0
  @backstage/plugin-scaffolder-backend-module-gitlab               0.8.0
  @backstage/plugin-scaffolder-backend                             1.30.0
  @backstage/plugin-scaffolder-common                              1.5.9
  @backstage/plugin-scaffolder-node                                0.6.3, 0.7.0
  @backstage/plugin-scaffolder-react                               1.14.5
  @backstage/plugin-scaffolder                                     1.28.0
  @backstage/plugin-search-backend-module-catalog                  0.3.1
  @backstage/plugin-search-backend-module-pg                       0.5.41
  @backstage/plugin-search-backend-module-techdocs                 0.3.6
  @backstage/plugin-search-backend-node                            1.3.8
  @backstage/plugin-search-backend                                 1.8.2
  @backstage/plugin-search-common                                  1.2.17
  @backstage/plugin-search-react                                   1.8.6
  @backstage/plugin-search                                         1.4.23
  @backstage/plugin-signals-node                                   0.1.17
  @backstage/plugin-signals-react                                  0.0.10, 0.0.9
  @backstage/plugin-techdocs-backend                               1.11.6
  @backstage/plugin-techdocs-common                                0.1.0
  @backstage/plugin-techdocs-module-addons-contrib                 1.1.21
  @backstage/plugin-techdocs-node                                  1.13.0
  @backstage/plugin-techdocs-react                                 1.2.14
  @backstage/plugin-techdocs                                       1.12.3
  @backstage/plugin-user-settings-backend                          0.2.30
  @backstage/plugin-user-settings-common                           0.0.1
  @backstage/plugin-user-settings                                  0.8.19
  @backstage/release-manifests                                     0.0.12
  @backstage/test-utils                                            1.7.5
  @backstage/theme                                                 0.5.7, 0.6.4
  @backstage/types                                                 1.2.1
  @backstage/version-bridge                                        1.0.11
```

### 👀 Have you spent some time to check if this bug has been raised before?

- [x] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [x] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else
