### ISSUE TITLE
Show `techdocs-entity` as links in Scaffolder, too

### ISSUE THREAD

**Issue by swnia** [backstage/backstage#29076]
It would be great if TechDocs could be linked to without generating one by also displaying the ones marked by `backstage.io/techdocs-entity`.

https://github.com/backstage/backstage/blob/391b7fbd28405d00b38769867b5cd4a7973ebcbf/plugins/scaffolder/src/next/TemplateListPage/TemplateListPage.tsx#L129

**Comment by awanlin** [comment]
Hi @swnia, can you give us more details and context? I'm not really following what you are asking for and you removed most of the form used for feature requests like this which would have really helped int this case.

**Comment by swnia** [comment]
When I create a template with the `backstage.io/techdocs-ref`, I get a link to the techdocs in the Template Overview Page within the card of the corresponding item.
It would be great to also see the link to the TechDocs if I reference the documentation of e.g. the service that I am creating an new instance of through `backstage.io/techdocs-entity`.

E.g. this shows a link to the techdocs but if I point it to the same documentation it will create another instance of the docs.
```
apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: my-template
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  owner: my-team
  parameters:
    - [REST]
```
But this shows no link in the card in the overview page (but does in the catalog entry as expected)
```
apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: my-template
  annotations:
    backstage.io/techdocs-entity: component:default/iam-wif-management
spec:
  type: service
  owner: my-team
  parameters:
    - [REST]
```

Oh, and I did not remove the form but created a new issue through the "reference this line in new issue" option of GitHub. Sorry about that.

**Comment by awanlin** [comment]
Thanks for the additional context, I'm still not totally following but getting there, I think I just need to mock this up in an environment so it's more a me thing than anything.

Ah, I didn't know that GitHub had a feature like that. 🤔

**Comment by swnia** [comment]
Maybe an example will help:
```
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: my-thing
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: production
  owner: team-a
---
apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: my-template
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  owner: team-a
  parameters:
    - title: Name
      properties:
        name:
          description: The name of the thing
          type: string
  steps:
    - id: fetch-base
      name: Fetch Base
      action: fetch:template
      input:
        url: ./template
        values:
          name: "{{ parameters.name }}"
---
apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: my-other-template
  annotations:
    backstage.io/techdocs-entity: component:my-thing
spec:
  type: service
  owner: team-a
  parameters:
    - title: Name
      properties:
        name:
          description: The name of the thing
          type: string
  steps:
    - id: fetch-base
      name: Fetch Base
      action: fetch:template
      input:
        url: ./template
        values:
          name: "{{ parameters.name }}"
```

This will create one component, two entries in docs ("my-thing", "my-template") and two templates. Within the catalog under Templates both will have a link to the techdocs.  
When looking at the template overview page (under "create"), one of those templates has a link to techdocs one has not. Ideally, both would have that link.
