### ISSUE TITLE
🚀 Feature(Scaffolder): Support gitAuthorName/gitAuthorEmail for publish:gitlab:merge-request

### ISSUE THREAD

**Issue by GabDug** [backstage/backstage#29131]
### 🔖 Feature description

Template authors should be able to choose the git user details when creating a Gitlab MR, just like when using `publish:gitlab` e.g.:

```yaml
teps:
  - id: createMergeRequest
    action: publish:gitlab:merge-request
    name: Create a Merge Request
    input:
      repoUrl: gitlab.com?repo=repo&owner=owner
      title: Create my new MR
      description: This MR is really good
      sourcePath: ./path/to/my/changes
      branchName: new-mr
      assignee: my-assignee
      # Add support for the following:
      gitAuthorName: ${{ user.entity.profile.displayName or user.entity.metadata.name }} (via Scaffolder)
      gitAuthorEmail: ${{ user.entity.spec.profile.email }}
```

### 🎤 Context

We would like to correctly assign authorship of the MRs to the users that triggered them, adding a `(via Scaffolder)` to the commit author, even for the cases where we have to use a global admin token, instead of the user token.

This would make it accept the same parameters as `publish:gitlab` 

### ✌️ Possible Implementation

The call to `api.Commits.create` takes additional `options` `authorEmail` and `authorName`.

We could also respect the config `scaffolder.defaultAuthor.email` and `scaffolder.defaultAuthor.name`, just like `publish:gitlab`

### 👀 Have you spent some time to check if this feature request has been raised before?

- [x] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [x] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!
