### ISSUE TITLE
🚀 Feature: Support list of groups in GitLab Discovery Plugin

### ISSUE THREAD

**Issue by vaceal** [backstage/backstage#29141]
### 🔖 Feature description

The feature will support a list of GitLab groups to lookup instead of single one.  At the moment, you need to choose between one group or GitLab entirely.

### 🎤 Context

The current implementation supports only a single group. I can create multiple providers with different groups, but they all share the same activity cache, as seen in the [code](https://github.com/backstage/backstage/blob/8aa63b60beaab4111f682ce8a21e1a1b7230ee85/plugins/catalog-backend-module-gitlab/src/GitLabDiscoveryProcessor.ts#L116C3-L116C66).

With more than 25k projects and a high rate of change, crawling our GitLab instance is not working well. The ability to pick and choose specific GitLab groups would help us gradually roll out Backstage within our organization.

### ✌️ Possible Implementation

I propose two options.

## Support a list of GitLab group in the configuration
The configuration could look like this:
```yaml
catalog:
  providers:
    gitlab:
      yourProviderId:
        host: gitlab-host 
        branch: main
        [...]
        group:
          - groupa
          - groupb/anothergroup
        entityFilename: catalog-info.yaml # Optional. Defaults to `catalog-info.yaml`
        [...]
```

It means we could add a for loop over [here](https://github.com/backstage/backstage/blob/8aa63b60beaab4111f682ce8a21e1a1b7230ee85/plugins/catalog-backend-module-gitlab/src/GitLabDiscoveryProcessor.ts#L111)

## Support many provider ID with their own cache

No need to support any changes in the configuation, what we would need is to return the name of the provider id over [here](https://github.com/backstage/backstage/blob/8aa63b60beaab4111f682ce8a21e1a1b7230ee85/plugins/catalog-backend-module-gitlab/src/GitLabDiscoveryProcessor.ts#L82)

### 👀 Have you spent some time to check if this feature request has been raised before?

- [x] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [x] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!
