### ISSUE TITLE
🐛 Bug Report: AwsOrganizationCloudAccountProcessor is failing BackstageBackend.start check when configured

### ISSUE THREAD

**Issue by adickinson72** [backstage/backstage#29235]
### 📜 Description

I have added the @backstage/plugin-catalog-backend-module-aws to the new backend by running:
```
yarn --cwd packages/backend add @backstage/plugin-catalog-backend-module-aws
```
and added to my packages/backend/src/index.ts:
```
backend.add(import('@backstage/plugin-catalog-backend-module-aws'));
```

In my app-config.yaml, I'm providing:
```
        catalog:      
          processors:
            awsOrganization:
              provider:
                accountId: "0123456789"
          locations:
            - target: <AWS ORG ID>
               type: aws-cloud-accounts
```

And the backend won't start with:
```
cause: Error: Your config contains a "catalog.locations" entry of type aws-cloud-accounts, but does not have the corresponding catalog processor AwsOrganizationCloudAccountProcessor installed. This processor used to be built into the catalog itself, but is now moved to an external module that has to be installed manually. Please follow the installation instructions at https://backstage.io/docs/integrations if you are using this ability, or remove the location from your app config if you do not. You can also silence this check entirely by setting the environment variable BACKSTAGE_CATALOG_SKIP_MISSING_PROCESSORS_CHECK to 'true'.
```

### 👍 Expected behavior

The backend should start and process all AWS accounts within specified org Id as Resources

### 👎 Actual Behavior with Screenshots

The backend won't start
```
cause: Error: Your config contains a "catalog.locations" entry of type aws-cloud-accounts, but does not have the corresponding catalog processor AwsOrganizationCloudAccountProcessor installed. This processor used to be built into the catalog itself, but is now moved to an external module that has to be installed manually. Please follow the installation instructions at https://backstage.io/docs/integrations if you are using this ability, or remove the location from your app config if you do not. You can also silence this check entirely by setting the environment variable BACKSTAGE_CATALOG_SKIP_MISSING_PROCESSORS_CHECK to 'true'.
```

### 👟 Reproduction steps

add the @backstage/plugin-catalog-backend-module-aws to backend via:
```
yarn --cwd packages/backend add @backstage/plugin-catalog-backend-module-aws
```
and add to packages/backend/src/index.ts:
```
backend.add(import('@backstage/plugin-catalog-backend-module-aws'));
```

In app-config.yaml, add:
```
        catalog:      
          processors:
            awsOrganization:
              provider:
                accountId: "012345678910"
          locations:
            - target: <AWS ORG ID>
               type: aws-cloud-accounts
        aws:
          accounts:
          - accountId:  "012345678910"
            roleName: <arn of role>
```

### 📃 Provide the context for the Bug.

There's very little documentation on configuring this - 
Gleaned proper config from here:
https://github.com/backstage/backstage/pull/19467/files
https://github.com/backstage/backstage/issues/18052

### 👀 Have you spent some time to check if this bug has been raised before?

- [x] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [x] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by freben** [comment]
Hm, it's a bit unfortunate that that processor still uses locations to do its work at all. It should have been re-implemented as a provider instead, which doesn't use locations in the first place.

Leaving this open for contributions to address that, since it's not on our immediate roadmap. In the mean time, to get rid of the error, you can set the env var `BACKSTAGE_CATALOG_SKIP_MISSING_PROCESSORS_CHECK=true` as instructed.

**Comment by Wirone** [comment]
I was struggling with setting up `AwsOrganizationCloudAccountProcessor` too. I wanted to import AWS accounts as `Resource` entities, but official documentation does not contain any information about doing this (it mentions `@backstage/plugin-catalog-backend-module-aws`, but describes only [how to import entities from S3 bucket](https://backstage.io/docs/integrations/aws-s3/discovery)). I had to dig the source code ([here](https://github.com/backstage/backstage/blob/99810880bd1cc45d007ceccc477d9191951b263c/plugins/catalog-backend-module-aws/src/processors/AwsOrganizationCloudAccountProcessor.ts#L59-L79), [here](https://github.com/backstage/backstage/blob/99810880bd1cc45d007ceccc477d9191951b263c/packages/integration-aws-node/src/DefaultAwsCredentialsManager.ts#L165-L193), [here](https://github.com/backstage/backstage/blob/99810880bd1cc45d007ceccc477d9191951b263c/packages/integration-aws-node/src/DefaultAwsCredentialsManager.ts#L106-L124)), comments like [this](https://github.com/backstage/backstage/issues/18052#issuecomment-1683982053) (unfortunately it refers to legacy backend), PRs like [this](https://github.com/backstage/backstage/pull/24994) (stale and closed without merging) or issues like this one. Still couldn't get it to work. I installed and registered module, provided config that corresponds to how module reads it, even tried importing AWS module with `/alpha` (ChatGPT told me to try it as this was supposed to solve new backend registration issue), but it still did not work. After few iterations with GPT and sharing my current setup, it finally figured out that AWS module does not register accounts processor out-of-the-box (which I find weird!), so I need to create this:

```ts
import { createBackendModule, coreServices } from '@backstage/backend-plugin-api';
import { catalogProcessingExtensionPoint } from '@backstage/plugin-catalog-node/alpha';
import { AwsOrganizationCloudAccountProcessor } from '@backstage/plugin-catalog-backend-module-aws';

export default createBackendModule({
  pluginId: 'catalog',
  moduleId: 'aws-organization-accounts-importer',
  register(env) {
    env.registerInit({
      deps: {
        catalog: catalogProcessingExtensionPoint,
        logger: coreServices.logger,
        config: coreServices.rootConfig,
      },
      async init({ catalog, logger, config }) {
        catalog.addProcessor(
          await AwsOrganizationCloudAccountProcessor.fromConfig(config, { logger }),
        );
      },
    });
  },
});

```

and obviously register it with `backend.add(import('./modules/catalog/awsOrganizationAccountsImporter'));` in `packages/backend/src/index.ts`. Still have issues with configuring AWS credentials with `accessKeyId` and `secretAccessKey`, but at least it works using a `profile`. Config for reference:

```yaml
aws:
  mainAccount:
    accountId: ${AWS_MANAGEMENT_ACCOUNT_ID}
    profile: ${AWS_PROFILE}

catalog:
  locations:
    - type: aws-cloud-accounts
      target: ${AWS_ORGANIZATION_ID}
```

Anyway, would be great it it was registered by default in module (so adding module would have enabled `AwsOrganizationCloudAccountProcessor`) and documented...
