### ISSUE TITLE
k8s-plugin: Allow fetching of resources with arbitrary labels

### ISSUE THREAD

**Issue by mclarke47** [backstage/backstage#2924]
From https://github.com/spotify/backstage/issues/2857#issuecomment-709753137

## Feature Suggestion

It should be possible to provide other labels, keys and values to look up resources by with a [label selector](https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/) like so `key=value`.

## Possible Implementation

I can see 2 ways of doing this:

### Entity driven

We could add another annotation which provides labels selectors to use for an entity such as:

```yaml
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: dice-roller
  description: It rolls dice
  tags:
    - go
  annotations:
    "backstage.io/kubernetes-id": "dice-roller"
spec:
  selector:
    matchLabels:
      name: dice-roller
      version: canary
  type: service
  lifecycle: production
  owner: guest

```

We would propagate this annotation from the frontend to the backend for each K8S fetch and construct a label selector like so:

`name=dice-roller&version=canary`

### Config Driven

Another option would be to provide config to the backend to tell it which field in the entity to use, for example:

For the Entity:

```yaml
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: dice-roller
  description: It rolls dice
  tags:
    - go
spec:
  type: service
  lifecycle: production
  owner: guest
```

and the backend config: 

```yaml
...
kubernetes:
  labelSelectors:
    - key: "name"
      valueFrom: "entity.metadata.name"
    - key: "version"
      value: "canary"
...
```

We would construct the label `name=dice-roller&version=canary`

## Context

Currently we only allow users to to look up kubernetes resources if:

* The entity has an annotation like so `"backstage.io/kubernetes-id": entity_name`
* The Kubernetes resources to fetch have labels which match this value 

We then [fetch the the resources with a label selector](https://github.com/spotify/backstage/blob/master/plugins/kubernetes-backend/src/service/KubernetesFetcher.ts#L232).

This is quite limiting as users with then have to re-label their resources.

**Comment by mclarke47** [comment]
@Rugvip @freben @moustafab any feedback would be great! ☝️ 

@moustafab has shown an interest in implementing this

**Comment by Rugvip** [comment]
@moustafab Does this align with your need for label selectors? As in was it tied to catalog entities or did you want to do it more free-form straight towards k8s, without it being tied to entities?

@mclarke47 I think your proposal is good in that it just adds another tool for orgs to use, without being in the way if you don't need it. I also like that it drives the move over from using just `serviceId`s to querying based on entities 😁 , so 👍. Regarding the exact format, I imagine we'd be fairly safe if we do something that is forwards-compatible with k8s selectors? `matchLabels` etc.

Bit more meta, but right now I'm firmly in the camp of wanting to allow annotation values to be any JSON value, and remove the ability to query by annotation value :grin:

**Comment by freben** [comment]
Haha what the actual hell, I edited the comment instead of just quoting it

**Comment by freben** [comment]
> Bit more meta, but right now I'm firmly in the camp of wanting to allow annotation values to be any JSON value, and remove the ability to query by annotation value 😁

That would probably mean that we should move some things that are currently annotations to not be annotations right?

**Comment by freben** [comment]
+1 for `matchLabels` and on key: value form, rather than `labelSelectors` as well

**Comment by mclarke47** [comment]
Sounds good I will update

**Comment by moustafab** [comment]
> @moustafab Does this align with your need for label selectors? As in was it tied to catalog entities or did you want to do it more free-form straight towards k8s, without it being tied to entities?
> 
> @mclarke47 I think your proposal is good in that it just adds another tool for orgs to use, without being in the way if you don't need it. I also like that it drives the move over from using just serviceIds to querying based on entities 😁 , so 👍. Regarding the exact format, I imagine we'd be fairly safe if we do something that is forwards-compatible with k8s selectors? matchLabels etc.
> 
> Bit more meta, but right now I'm firmly in the camp of wanting to allow annotation values to be any JSON value, and remove the ability to query by annotation value 😁

I think being able to use more of the kubernetes native way of declaring selectors is a plus for flexibility and could help with adoption. Perhaps being able to the second more standardized way makes sense as a follow up to allow for standardization and ease of use. But that would require a bit of an expression or path evaluation and can get pretty complicated.

My only suggestion is that we nest the entity driven approach in case of other Custom Resource Driven k8s based applications, for example tekton or prow for CI/CD. If the k8s plugin is designed to focus primarily on the existing base set of objects (deployments, services, pods, etc) then others may want to use the label-selector pattern to implement other backends. The type there should be https://github.com/kubernetes-client/javascript/blob/master/src/gen/model/v1LabelSelector.ts

Perhaps something like this could work:

```
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: dice-roller
  description: It rolls dice
  tags:
    - go
  annotations:
    "backstage.io/kubernetes-id": "dice-roller"
spec:
  kubernetes:
    selector:
      matchLabels:
        name: dice-roller
        version: canary
  type: service
  lifecycle: production
  owner: guest
```

@mclarke47 @freben @Rugvip
