### ISSUE TITLE
🐛 Bug Report: <title>Https configuration

### ISSUE THREAD

**Issue by sivaprasath2k** [backstage/backstage#29297]
### 📜 Description

While trying to configure ssl certificate , using openssl I have generated certificate.pem file , I have cross verified that certificate with some ssl checker , that was verified. But while adding that pem file will showing PEM ROUTINES::no start line ,
library: 'PEM routines',
reading: 'no start line',
code: 'ERR_OSSL_PEM_NO_START_LINE'

I'm using node js v20.18.1

### 👍 Expected behavior

Need to access backstage over https

### 👎 Actual Behavior with Screenshots

While trying to configure ssl certificate , using openssl I have generated certificate.pem file , I have cross verified that certificate with some ssl checker , that was verified. But while adding that pem file will showing PEM ROUTINES::no start line ,
library: 'PEM routines',
reading: 'no start line',
code: 'ERR_OSSL_PEM_NO_START_LINE'

I'm using node js v20.18.1

### 👟 Reproduction steps

.

### 📃 Provide the context for the Bug.

.

### 🖥️ Your Environment

.

### 👀 Have you spent some time to check if this bug has been raised before?

- [x] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [x] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by vinzscam** [comment]
Please double check that the certificate uses the following format in your app-config.yaml:

```yaml
backend:
  # stuff
  https:
    certificate:
      cert: |
        -----BEGIN CERTIFICATE-----
        MIIEYTCCAsm...................................
        ..........................................................
        ..........................................................
        ..........................................................
        z5jEEymAKXKNxUInmBGoVu0kIBN3
        -----END CERTIFICATE-----
      key:
        $file: ./certs/key.pem
```
