### ISSUE TITLE
🐛 Bug Report: publish:gitlab:merge-request fails when file exist - “Not Found” / “Bad Request” errors

### ISSUE THREAD

**Issue by Jona-Soerensen** [backstage/backstage#29358]
### 📜 Description

I am using the [publish:gitlab:merge-request](https://backstage.io/docs/features/software-templates/builtin-actions#publishgitlabmerge-request) action (version @backstage/plugin-scaffolder-backend-module-gitlab@0.8.0)

in my Scaffolder template, and I’m repeatedly encountering the following errors:

1. `warn: Could not retrieve the list of files for [mygroup/myproject] (branch: main): GitbeakerRequestError: Not Found`
2. Then while continue with the scaffolder: `Committing the changes to feature/... failed. Please check that none of the files created by the template already exists. GitbeakerRequestError: Bad Request`

In some scenarios, the files already exist in the repo and should be updated (which is supposed to work with commitAction: 'auto').
I think it's because the scaffolder can't read the existing files in the repo and then just uses the default commitAction ('create'). When I'm just adding new files to the MR it is working fine.

### 👍 Expected behavior

With commitAction: 'auto', repeated scaffolding runs should create or update files without throwing 400 errors (Bad Request).

### 👎 Actual Behavior with Screenshots

During template execution, the action fails in certain cases and produces a Bad Request or Not Found error.
The Scaffolder action doesn’t appear to properly handle existing files as updates when using commitAction: 'auto'.
I already tried to use a separate access token with read/write permissions etc..

<img width="1382" alt="Image" src="https://github.com/user-attachments/assets/f31c9e93-e2f4-4bd0-a961-445f64a332da" />

### 👟 Reproduction steps

1.	Create a new Scaffolder template, for example:
```
steps:
  - id: convert
    name: Convert Confluence → MD
    action: my:confluenceToMarkdown
    input:
      pageUrl: ${{ parameters.pageUrl }}
      bearerToken: ${{ secrets.bearerToken }}
      pythonScriptPath: './c2m.py'
  
  - id: publish
    name: Publish to GitLab
    action: publish:gitlab:merge-request
    input:
      repoUrl: ${{ steps.parseRepo.output.parsedRepoUrl }}
      branchName: feature/confluence-md-${{ steps.convert.output.pageTitle }}
      token: 'xxxxx-xxxxx'
      targetBranchName: main
      sourcePath: './content'
      targetPath: './docs'
      commitAction: 'auto'
      title: 'feat: [00000] Converted Confluence to Markdown'
      description: '...'
```

2.	Make sure that in the GitLab repository there is already a file with the same name (e.g., page.md).
3.	Run the scaffolder so that the action attempts to commit that file again (expected: an update).
4.	Observe the Bad Request or Not Found error.

### 📃 Provide the context for the Bug.

I'm trying to convert confluence pages into markdown and then publish them into our portal.
But when a markdown file with the same name already exists the scaffolder action will fail. 

### 🖥️ Your Environment

OS: fa1c85f9-dbba-4b7d-9f5e-4a4e8a782d71.fritz.box: Darwin 24.3.0 - darwin/arm64
Resources: Memory: 18313/18432MB - Load: 1.80/2.09/2.29
node: v20.18.1
backstage: 1.36.1
Dependencies:
    @backstage-community/plugin-adr-backend: 0.4.27
    @backstage-community/plugin-adr-common: 0.2.30
    @backstage-community/plugin-adr: 0.6.28
    @backstage-community/plugin-github-actions: 0.6.27
    @backstage-community/plugin-tech-radar-backend: 1.3.0
    @backstage-community/plugin-tech-radar-common: 1.3.0
    @backstage-community/plugin-tech-radar: 1.3.0
    @backstage-community/search-backend-module-adr: 0.1.4, 0.2.1
    @backstage/app-defaults: 1.5.17
    @backstage/backend-app-api: 1.2.0
    @backstage/backend-common: 0.23.3, 0.24.1, 0.25.0
    @backstage/backend-defaults: 0.5.3, 0.6.2, 0.8.1
    @backstage/backend-dev-utils: 0.1.5
    @backstage/backend-openapi-utils: 0.5.0
    @backstage/backend-plugin-api: 0.7.0, 0.8.1, 1.2.0, 1.2.1
    @backstage/backend-tasks: 0.6.1
    @backstage/backend-test-utils: 1.3.0
    @backstage/catalog-client: 1.9.1
    @backstage/catalog-model: 1.7.3
    @backstage/cli-common: 0.1.15
    @backstage/cli-node: 0.2.13
    @backstage/cli: 0.30.0
    @backstage/config-loader: 1.9.6
    @backstage/config: 1.3.2
    @backstage/core-app-api: 1.15.5
    @backstage/core-compat-api: 0.2.8, 0.3.6
    @backstage/core-components: 0.14.10, 0.15.1, 0.16.4
    @backstage/core-plugin-api: 1.10.4
    @backstage/dev-utils: 1.1.7
    @backstage/e2e-test-utils: 0.1.1
    @backstage/errors: 1.2.7
    @backstage/eslint-plugin: 0.1.10
    @backstage/frontend-app-api: 0.10.5
    @backstage/frontend-defaults: 0.1.6
    @backstage/frontend-plugin-api: 0.6.7, 0.7.0, 0.9.5
    @backstage/frontend-test-utils: 0.2.6
    @backstage/integration-aws-node: 0.1.15
    @backstage/integration-react: 1.2.4
    @backstage/integration: 1.16.1, 1.16.2
    @backstage/plugin-api-docs: 0.12.4
    @backstage/plugin-app-backend: 0.4.5
    @backstage/plugin-app-node: 0.1.30
    @backstage/plugin-app: 0.1.6
    @backstage/plugin-auth-backend-module-atlassian-provider: 0.4.0
    @backstage/plugin-auth-backend-module-auth0-provider: 0.2.0
    @backstage/plugin-auth-backend-module-aws-alb-provider: 0.4.0
    @backstage/plugin-auth-backend-module-azure-easyauth-provider: 0.2.5
    @backstage/plugin-auth-backend-module-bitbucket-provider: 0.3.0
    @backstage/plugin-auth-backend-module-bitbucket-server-provider: 0.2.0
    @backstage/plugin-auth-backend-module-cloudflare-access-provider: 0.4.0
    @backstage/plugin-auth-backend-module-gcp-iap-provider: 0.4.0
    @backstage/plugin-auth-backend-module-github-provider: 0.3.0
    @backstage/plugin-auth-backend-module-gitlab-provider: 0.3.0
    @backstage/plugin-auth-backend-module-google-provider: 0.3.0
    @backstage/plugin-auth-backend-module-guest-provider: 0.2.5
    @backstage/plugin-auth-backend-module-microsoft-provider: 0.3.0
    @backstage/plugin-auth-backend-module-oauth2-provider: 0.4.0
    @backstage/plugin-auth-backend-module-oauth2-proxy-provider: 0.2.5
    @backstage/plugin-auth-backend-module-oidc-provider: 0.4.0
    @backstage/plugin-auth-backend-module-okta-provider: 0.2.0
    @backstage/plugin-auth-backend-module-onelogin-provider: 0.3.0
    @backstage/plugin-auth-backend: 0.24.3
    @backstage/plugin-auth-node: 0.4.17, 0.5.6, 0.6.0, 0.6.1
    @backstage/plugin-auth-react: 0.1.12
    @backstage/plugin-bitbucket-cloud-common: 0.2.27
    @backstage/plugin-catalog-backend-module-azure: 0.3.2
    @backstage/plugin-catalog-backend-module-gitlab: 0.6.3
    @backstage/plugin-catalog-backend-module-scaffolder-entity-model: 0.2.5
    @backstage/plugin-catalog-backend-module-unprocessed: 0.5.5
    @backstage/plugin-catalog-backend: 1.31.0
    @backstage/plugin-catalog-common: 1.1.3
    @backstage/plugin-catalog-graph: 0.4.16
    @backstage/plugin-catalog-import: 0.12.10
    @backstage/plugin-catalog-node: 1.16.0
    @backstage/plugin-catalog-react: 1.15.2
    @backstage/plugin-catalog-unprocessed-entities-common: 0.0.7
    @backstage/plugin-catalog-unprocessed-entities: 0.2.14
    @backstage/plugin-catalog: 1.27.0
    @backstage/plugin-devtools-backend: 0.5.2
    @backstage/plugin-devtools-common: 0.1.15
    @backstage/plugin-devtools: 0.1.24
    @backstage/plugin-events-node: 0.4.8
    @backstage/plugin-home-react: 0.1.23
    @backstage/plugin-home: 0.8.5
    @backstage/plugin-org: 0.6.36
    @backstage/plugin-permission-backend: 0.5.54
    @backstage/plugin-permission-common: 0.7.14, 0.8.4
    @backstage/plugin-permission-node: 0.8.8, 0.9.0
    @backstage/plugin-permission-react: 0.4.31
    @backstage/plugin-proxy-backend: 0.5.11
    @backstage/plugin-proxy-node: 0.1.1
    @backstage/plugin-scaffolder-backend-module-azure: 0.2.6
    @backstage/plugin-scaffolder-backend-module-bitbucket-cloud: 0.2.6
    @backstage/plugin-scaffolder-backend-module-bitbucket-server: 0.2.6
    @backstage/plugin-scaffolder-backend-module-bitbucket: 0.3.7
    @backstage/plugin-scaffolder-backend-module-gerrit: 0.2.6
    @backstage/plugin-scaffolder-backend-module-gitea: 0.2.6
    @backstage/plugin-scaffolder-backend-module-github: 0.6.0
    @backstage/plugin-scaffolder-backend-module-gitlab: 0.8.0, 0.8.1
    @backstage/plugin-scaffolder-backend: 1.30.0
    @backstage/plugin-scaffolder-common: 1.5.10, 1.5.9
    @backstage/plugin-scaffolder-node: 0.7.0, 0.8.0
    @backstage/plugin-scaffolder-react: 1.14.5
    @backstage/plugin-scaffolder: 1.28.0
    @backstage/plugin-search-backend-module-catalog: 0.3.1
    @backstage/plugin-search-backend-module-pg: 0.5.41
    @backstage/plugin-search-backend-module-techdocs: 0.3.6
    @backstage/plugin-search-backend-node: 1.3.8
    @backstage/plugin-search-backend: 1.8.2
    @backstage/plugin-search-common: 1.2.17
    @backstage/plugin-search-react: 1.8.6
    @backstage/plugin-search: 1.4.23
    @backstage/plugin-signals-react: 0.0.10
    @backstage/plugin-techdocs-addons-test-utils: 1.0.45
    @backstage/plugin-techdocs-backend: 1.11.6
    @backstage/plugin-techdocs-common: 0.1.0
    @backstage/plugin-techdocs-module-addons-contrib: 1.1.21
    @backstage/plugin-techdocs-node: 1.13.0
    @backstage/plugin-techdocs-react: 1.2.14
    @backstage/plugin-techdocs: 1.12.3
    @backstage/plugin-user-settings-common: 0.0.1
    @backstage/plugin-user-settings: 0.8.19
    @backstage/release-manifests: 0.0.12
    @backstage/test-utils: 1.7.5
    @backstage/theme: 0.5.7, 0.6.4
    @backstage/types: 1.2.1
    @backstage/version-bridge: 1.0.11

### 👀 Have you spent some time to check if this bug has been raised before?

- [x] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [x] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by Parsifal-M** [comment]
Heya! 👋 

Just to better understand, if you specifically set the `commitAction` to `update`/`create` it works? So its only failing when `auto` is used?

**Comment by Jona-Soerensen** [comment]
Hey! Yes indeed.
If I use the update or create `commitAction` it works as expected. If I switch to `auto` I get the warning that the fetch is not possible and then I think it's falling back to the `create` action.

**Comment by marct83** [comment]
I'm running into 'warn: Could not retrieve the list of files for [mygroup/myproject] (branch: main): GitbeakerRequestError: Not Found' for all 'commitAction' values. I also can't get the update to work at all.  It always errors that the files already exist. Not sure what I'm doing wrong. Example Config:

```
    - id: createMergeRequest
      if: ${{ not parameters.dryRun }}
      name: Create a Merge Request
      action: publish:gitlab:merge-request
      input:
        repoUrl: ${{ parameters.repoUrl }}
        commitMessage: ${{ parameters.commitMessage }}
        gitAuthorName: ${{ user.entity.metadata.name }}
        gitAuthorEmail: ${{ user.entity.spec.profile.email }}
        title: "Adding docs and backstage config"
        removeSourceBranch: true
        description: "This is an auto-generated merge request to add docs and backstage config."
        sourcePath: ${{ steps.template.output.directory }}
        token: ${{ secrets.USER_OAUTH_TOKEN }}
        branchName: ${{ parameters.branchName }}
        targetPath: './'
        commitAction: 'update'
```
