### ISSUE TITLE
🚀 Feature: Make gitlab:group:ensureExists support complete paths

### ISSUE THREAD

**Issue by JohannesWill** [backstage/backstage#29399]
### 🔖 Feature description

In the input of the action, you can only specify an array of pathElements and not complete subpathes.

```yaml
 path: 
          - "my/sub/group"
```

This will also help, when used in combination with the RepoUrlPicker e.g.
````yaml
    - id: creategroup
      name: Create Group
      action: gitlab:group:ensureExists
      input:
        repoUrl: ${{ parameters.repoUrl | parseRepoUrl | pick('host') }}
        path: 
          - ${{ parameters.repoUrl | projectSlug }}
````

### 🎤 Context

It allows user to use the projectSlug directly from the RepoUrlPicker

### ✌️ Possible Implementation

This can be implemented introducing an Path Part iterator instead of iterating of the path here:
We've sucessfully tested this code in our own instance.

https://github.com/backstage/backstage/blob/a31a430c17526873f3dab54213238bb9f6f7ff89/plugins/scaffolder-backend-module-gitlab/src/actions/gitlabGroupEnsureExists.ts#L79

```ts
function* pathIterator(items: Any[]): Generator {
  for (const item of items) {
    if (typeof item === 'string') {
      const parts = item.split('/');
      for (const part of parts) {
        yield { name: part, slug: part };
      }
    } else {
      yield item;
    }
  }
}
```

I did not provide a PR immediatly as we first want to know if there would be value.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [x] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [x] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!
