### ISSUE TITLE
🐛 Bug Report: AWS integration docs are out of data

### ISSUE THREAD

**Issue by tplass-ias** [backstage/backstage#29404]
### 📜 Description

The AWS locations doc tells me I must use AWS env var creds chain: https://github.com/Maetis/backstage/blob/master/docs/integrations/aws-s3/locations.md

### 👍 Expected behavior

This doc should tell me I can skip adding it's config if I am supplying the creds some other way, e.g. ec2 instance profile or creds file, to be consistent with the plugin readme: https://github.com/clareliguori/backstage/tree/master/packages/integration-aws-node#readme

### 👎 Actual Behavior with Screenshots

When supplying the AWS_ACCESS_KEY as shown in the docs, I get errors in the db when discovering locations from s3 (in `backstage_plugin_catalog.refresh_state`):

```
[{"name":"Error","message":"Unable to read url, InvalidAccessKeyId: Could not retrieve file from S3; caused by InvalidAccessKeyId: The AWS Access Key Id you provided does not exist in our records."}]
```

### 👟 Reproduction steps

1. set up aws integration in `app-config.yaml`
```yaml
integrations:
  awsS3:
    - accessKeyId: ${AWS_ACCESS_KEY_ID}
      secretAccessKey: ${AWS_SECRET_ACCESS_KEY}
```
2. set up s3 discovery:
```yaml
catalog:
  providers:
    awsS3:
      databaseObjects: # identifies your dataset / provider independent of config changes
        bucketName: some-bucket
        prefix: some-prefix # optional
        region: us-east-1 # optional, uses the default region otherwise
        schedule: # same options as in SchedulerServiceTaskScheduleDefinition
          # supports cron, ISO duration, "human duration" as used in code
          frequency: { minutes: 30 }
          # supports ISO duration, "human duration" as used in code
          timeout: { minutes: 3 }
```
3. Run the app with `yarn dev`
4. Inspect the db, in `backstage_plugin_catalog.refresh_state`
5. --> s3 location entities are failing to get processed with error about invalid Access Key Id

### 👀 Have you spent some time to check if this bug has been raised before?

- [x] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [x] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else
