### ISSUE TITLE
🐛 Bug Report: Kubernetes integration UX issues

### ISSUE THREAD

**Issue by imbabamba** [backstage/backstage#29409]
### 📜 Description

In rendered 'Your Clusters' / Deployment the "rowSelect" and "DisplayedRows" in the table is missing proper labels. as well as in the pod view some things are stripped in the UI

### 👍 Expected behavior

It should not cap/strip the POD view. It should display the grid correctly. 

### 👎 Actual Behavior with Screenshots

![Image](https://github.com/user-attachments/assets/edcb3875-c719-4dc0-959d-9d769a00e539)
![Image](https://github.com/user-attachments/assets/b54d0e94-737a-4f6a-a1f0-307b87cc49bb)

### 👟 Reproduction steps

PODview: 
1. Go to component/kubernetes
2. Click on Deployment/POD
3. The popup displaying the pod, for example information: "Liveness Probe Set" is capped.

GridView:
1. Go to component/kubernetes
2. Click on Deployment
3. row selector and page selector is missing labels

### 📃 Provide the context for the Bug.

```
    kubernetes:
      serviceLocatorMethod:
        type: 'multiTenant'
      clusterLocatorMethods:
        - type: 'config'
          clusters:
            - name: devtrack-alpha
              url: https://URL
              authProvider: 'serviceAccount'
              skipTLSVerify: false
              skipMetricsLookup: true
              serviceAccount: backstage-devtrack
              serviceAccountToken: ${K8S_TOKEN}
```
"@backstage/plugin-kubernetes": "^0.12.5",
"@backstage/plugin-kubernetes-backend": "^0.19.4",
Backstage version": "1.36.1"

### 👀 Have you spent some time to check if this bug has been raised before?

- [x] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [x] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else
