### ISSUE TITLE
🐛 Bug Report: gitlab:repo:push fails when commitAction is 'update' and unclear documentation

### ISSUE THREAD

**Issue by the3dsandwich** [backstage/backstage#29405]
### 📜 Description

In scaffolding action `gitlab:repo:push`, when a file does not exist in the target branch and I set `commitAction` to update, it fails with message:

```
InputError: Committing the changes to main failed. Please check that none of the files created by the template already exists. GitbeakerRequestError: Bad Request[118](http://localhost:3000/create/tasks/bc14952b-ae47-46c0-b133-77371efd518c#line-118)
    at Object.handler (/.../node_modules/@backstage/plugin-scaffolder-backend-module-gitlab/src/actions/gitlabRepoPush.ts:206:15)
    ...omitted
```

step definition in template looks like the following

```     
    - id: update-gitlab-repo
      name: update file in gitlab
      action: gitlab:repo:push
      input:
        # omitted other info
        commitAction: update
```

### 👍 Expected behavior

1. the behavior for each of commitAction `'create' | 'delete' | 'update'` should be shown in "installed action"
2. update (or create) the existing file when executing `gitlab:repo:push` instead of failing
3. if update action should not create or update, have another action that "update or create"

### 👎 Actual Behavior with Screenshots

<img width="1184" alt="Image" src="https://github.com/user-attachments/assets/dbed0439-f9e4-4c03-bd9b-86306f4aa68d" />

<img width="1160" alt="Image" src="https://github.com/user-attachments/assets/8326f50d-73ce-4eaa-a403-62c44bc21373" />

### 👟 Reproduction steps

1. create a gitlab repository
2. create branch `main` and commit a file (for example `README.md`)
3. use template file to update a `TEST.md` by setting `commitAction: update`
4. since `TEST.md` does not exist, it should either fail by saying file does not exist, or succeed by creating. Instead, it failed by saying file exists.

template file step looks like the following

```     
    - id: update-gitlab-repo
      name: update file in gitlab
      action: gitlab:repo:push
      input:
        # omitted other info
        commitAction: update
```

### 📃 Provide the context for the Bug.

Ultimately, I want to create a workflow where users "create or update" catalog-info.yaml that I parsed/collected in this template.

If a repository does not exist, template creates repo and commits it in.
If repository exists, template updates the catalog-info.yaml.

I can create a repository by `publish:gitlab` and not fail existing repositories by setting `skipExisting: true`
But now I cannot determine whether I should create a file in branch or update the file.

### 👀 Have you spent some time to check if this bug has been raised before?

- [x] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [x] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!
