### ISSUE TITLE
🐛 Bug Report: OIDC provider requires the user to re-authenticate every time they reload the page

### ISSUE THREAD

**Issue by chriskilding-relx** [backstage/backstage#29455]
### 📜 Description

Given I am logged in to Backstage using the OIDC provider (configured with `prompt: auto` per the Backstage recommendations),
When I reload the page,
Then I am taken back to the sign-in page and must re-authenticate before I can keep using Backstage.

### 👍 Expected behavior

After initial sign-in, I should be able to keep browsing Backstage as a signed-in user no matter how many times I reload the page.

### 👎 Actual Behavior with Screenshots

If I reload the page while being signed in, it actually takes me back to the sign-in page, where I must re-authenticate to get back into Backstage. This happens every time I reload the page.

### 👟 Reproduction steps

1. Create a new vanilla Backstage app using the latest Backstage version.
2. Set up the OIDC Backstage authentication provider in your project. (In `app-config.yaml`, use `prompt: auto` for your OIDC provider.)
3. Start the Backstage backend and frontend.
4. Sign in (the first time).
5. After authenticating, you are logged in.
6. Browse around the app; this should work fine **as long as** you do not reload the page.
7. Reload the page.
8. You are taken back to the sign-in screen, and must sign in again.

### 📃 Provide the context for the Bug.

I am trying to provide an OIDC sign-in pathway on Backstage, using a Keycloak server as the identity provider.

### 🖥️ Your Environment

This happens on a vanilla Backstage app, with the Backstage OIDC provider configured to work with our Keycloak identity server using the following options:

```yaml
auth:
  environment: development
  session:
    secret: ${AUTH_SESSION_SECRET}
  providers:
    guest: {}
    keycloak:
      development:
        metadataUrl: https://<keycloak-server>/realms/<realm>/.well-known/openid-configuration
        clientId: ${KEYCLOAK_CLIENT_ID}
        clientSecret: ${KEYCLOAK_CLIENT_SECRET}
        prompt: auto
        tokenSignedResponseAlg: ES256
```

### 👀 Have you spent some time to check if this bug has been raised before?

- [x] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [x] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None
