### ISSUE TITLE
🐛 Bug Report: Login failed; caused by Error: Failed to sign-in, unable to resolve user identity. Please verify that your catalog contains the expected User entities that would match your configured sign-in resolver.

### ISSUE THREAD

**Issue by manishalankala** [backstage/backstage#29486]
### 📜 Description

Error message indicates : Login failed; caused by Error: Failed to sign-in, unable to resolve user identity. Please verify that your catalog contains the expected User entities that would match your configured sign-in resolver.

Encountering issue with the Microsoft Authentication provider in Backstage.

### 👍 Expected behavior

When a user enters valid credentials and clicks "Login," they should be redirected to their dashboard without errors.

### 👎 Actual Behavior with Screenshots

![Image](https://github.com/user-attachments/assets/0fe0ee69-9f71-48a7-ab9f-cafb1fa049ec)

### 👟 Reproduction steps

Mentioned below in Context for the bug : 

### 📃 Provide the context for the Bug.

auth-config.local.yaml

```
app:
  baseUrl: http://localhost:3000
  title: Backstage App

backend:
  baseUrl: http://localhost:7007
  listen:
    port: 7007
  database:
    client: better-sqlite3
    connection: ':memory:'

auth:
  environment: development
  providers:
    microsoft:
      development:
        clientId: ${AZURE_CLIENT_ID}
        clientSecret: ${AZURE_CLIENT_SECRET}
        tenantId: ${AZURE_TENANT_ID}
        domainHint: ${AZURE_TENANT_ID}
        scope: 'offline_access openid profile User.Read'
        tokenUrl: https://login.microsoftonline.com/${AZURE_TENANT_ID}/oauth2/v2.0/token
        signIn:
          resolvers:
          - resolver: emailMatchingUserEntityAnnotation 

    github:
      development:
        clientId: ${GITHUB_CLIENT_ID}
        clientSecret: ${GITHUB_CLIENT_SECRET}
        enterpriseInstanceUrl: https://github.com/
        signIn:
          resolvers:
            - type: usernameMatchingUserEntityName 

            logging:
            level: debug
          
catalog:
  locations:
    - type: file
      target: ./catalog-info.yaml
  rules:
    - allow: [Component, API, Resource]
    - allow: [Group, User]
    - allow: [Domain, DomainGroup]
    - allow: [System, SystemGroup]    
  integrations:
    microsoftGraphOrg:
      providerId: default
      target: https://graph.microsoft.com/v1.0
      authority: https://login.microsoftonline.com
      tenantId: ${AZURE_TENANT_ID}
      clientId: ${AZURE_CLIENT_ID}
      clientSecret: ${AZURE_CLIENT_SECRET}
      queryMode: advanced # Enables advanced queries for filtering and selecting fields
      user:
       filter: accountEnabled eq true  # Filters out users without a display name
       select: [id, displayName, mail, userPrincipalName]
      group:
       select: [id, displayName, description]
      schedule:
        frequency: PT1H # Sync every hour
        timeout: PT3M # Timeout after 3 minutes
        initialDelay: PT15S # Initial delay of 15 seconds before the first sync

techdocs:
  builder: 'local' # Mandatory: Specifies how documentation sites are built ('local' or 'external')
  generator:
    runIn: 'local' # Mandatory: Specifies whether MkDocs runs locally or in Docker
  publisher:
    type: 'local' # Mandatory: Specifies where TechDocs sites are stored ('local', 'googleGcs', or 'awsS3')

```

packages/app/src/App.tsx

```
import React from 'react';
import { createApp } from '@backstage/app-defaults';
import { SignInPage } from '@backstage/core-components';
import { AppRouter, FlatRoutes } from '@backstage/core-app-api';
import { Root } from './components/Root';
import { Route, Navigate } from 'react-router-dom';
import { entityPage } from './components/catalog/EntityPage';
import { searchPage } from './components/search/SearchPage';
import { authProviders } from './components/signin/identityProviders';
import { CatalogEntityPage,CatalogIndexPage,catalogPlugin } from '@backstage/plugin-catalog';
import { CatalogImportPage,catalogImportPlugin } from '@backstage/plugin-catalog-import';
import { catalogEntityCreatePermission } from '@backstage/plugin-catalog-common/alpha';
import { TechDocsIndexPage,techdocsPlugin,TechDocsReaderPage } from '@backstage/plugin-techdocs';
import { ScaffolderPage,scaffolderPlugin } from '@backstage/plugin-scaffolder';
import { ApiExplorerPage, apiDocsPlugin } from '@backstage/plugin-api-docs';
import { UserSettingsPage } from '@backstage/plugin-user-settings';
import { CatalogGraphPage } from '@backstage/plugin-catalog-graph';
import { RequirePermission } from '@backstage/plugin-permission-react';
import { AlertDisplay, OAuthRequestDialog } from '@backstage/core-components';

const app = createApp({
  components: {
    SignInPage: props => (
      <SignInPage
        {...props}
        auto
        providers={ authProviders }
      />
    ),
  },
  bindRoutes({ bind }) {
    bind(catalogPlugin.externalRoutes, {
      createComponent: scaffolderPlugin.routes.root,
      viewTechDoc: techdocsPlugin.routes.docRoot,
      createFromTemplate: scaffolderPlugin.routes.selectedTemplate,
    });
    bind(apiDocsPlugin.externalRoutes, {
      registerApi: catalogImportPlugin.routes.importPage,
    });
    bind(scaffolderPlugin.externalRoutes, {
      registerComponent: catalogImportPlugin.routes.importPage,
      viewTechDoc: techdocsPlugin.routes.docRoot,
    });
  },
});


// Define application routes
const routes = (
  <FlatRoutes>
    {/* Default redirect */}
    <Route path="/" element={<Navigate to="catalog" />} />

    {/* Catalog routes */}
    <Route path="/catalog" element={<CatalogIndexPage />} />
    <Route 
      path="/catalog/:namespace/:kind/:name" 
      element={<CatalogEntityPage />}
    >
      {entityPage}
    </Route>

    {/* TechDocs routes */}
    <Route path="/docs" element={<TechDocsIndexPage />} />
    <Route path="/docs/:namespace/:kind/:name/*" element={<TechDocsReaderPage />} />

    {/* Scaffolder route */}
    <Route path="/create" element={<ScaffolderPage />} />

    {/* API Explorer route */}
    <Route path="/api-docs" element={<ApiExplorerPage />} />

    {/* Catalog Import route */}
    <Route
      path="/catalog-import"
      element={
        <RequirePermission permission={catalogEntityCreatePermission}>
          <CatalogImportPage />
        </RequirePermission>
      }
    />

    {/* Search page route */}
    <Route path="/search" element={searchPage} />

    {/* User Settings route */}
    <Route path="/settings" element={<UserSettingsPage />} />

    {/* Catalog Graph route */}
    <Route path="/catalog-graph" element={<CatalogGraphPage />} />
  </FlatRoutes>
);

export default app.createRoot(
  <>
    {/* Global components like alerts and OAuth dialogs */}
    <AlertDisplay transientTimeoutMs={5000} />
    <OAuthRequestDialog />
    
    {/* Application Router */}
    <AppRouter>
      <Root>{routes}</Root>
    </AppRouter>
  </>
);


```

packages/app/src/signin/identityProviders.tsx

```
import { microsoftAuthApiRef, githubAuthApiRef } from '@backstage/core-plugin-api';
import { SignInProviderConfig } from '@backstage/core-components';
//import { guestAuthApiRef } from '@backstage/plugin-auth-backend-module-guest-provider';

export const authProviders: SignInProviderConfig[] = [
  {
    id: 'microsoft-auth-provider',
    title: 'Sign in using Microsoft',
    message: 'Microsoft login',
    apiRef: microsoftAuthApiRef,
    options: {
      env: 'development',
    },
  }as SignInProviderConfig,
  {
    id: 'github-auth-provider',
    title: 'Sign in using GitHub',
    message: 'GitHub login',
    apiRef: githubAuthApiRef,
  },
//   {
//     id: 'guest',
//     title: 'Sign in as Guest',
//     message: 'Continue as Guest',
//     apiRef: guestAuthApiRef, 
//   },
];

```

packages/backend/src/index.ts

```
import { createBackend } from '@backstage/backend-defaults';
const backend = createBackend();

// Core backend plugins
backend.add(import('@backstage/plugin-auth-backend'));
backend.add(import('@backstage/plugin-app-backend'));
backend.add(import('@backstage/plugin-catalog-backend'));
backend.add(import('@backstage/plugin-techdocs-backend'));
backend.add(import('@backstage/plugin-scaffolder-backend'));
backend.add(import('@backstage/plugin-search-backend'));
backend.add(import('@backstage/plugin-proxy-backend'));
backend.add(import('@backstage/plugin-auth-backend-module-microsoft-provider'));

// Start the backend
backend.start();

```

 catalog-info.yaml

```
apiVersion: backstage.io/v1alpha1  # Required for User entities 
kind: User                        # Core entity type for users
metadata:
  name: xxxx-xxxxxxxx-xxxxxxxx  # Object ID as unique identifier
  annotations:
    microsoft.com/email: xxxx@yyy.zzz
    graph.microsoft.com/user-id: xxxx-xxxxxxxx-xxxxxxxx  # Required for emailMatchingUserEntityProfileEmail
spec:
  profile:
    displayName: aaaa,bb #Full display name from Entra ID
    email: xxxx@yyy.zzz    # User Principal Name

```

### 🖥️ Your Environment

yarn backstage-cli info
OS:   Linux 5.15.146.1-microsoft-standard-WSL2 - linux/x64
node: v18.20.8
yarn: 4.4.1
cli:  0.31.1 (installed)
backstage:  1.37.0

Dependencies:
  @backstage/app-defaults                                          1.6.0
  @backstage/backend-app-api                                       0.8.0, 0.9.3, 1.2.1
  @backstage/backend-common                                        0.23.3, 0.24.1, 0.25.0
  @backstage/backend-defaults                                      0.4.4, 0.8.2
  @backstage/backend-dev-utils                                     0.1.5
  @backstage/backend-openapi-utils                                 0.5.1
  @backstage/backend-plugin-api                                    0.7.0, 0.8.1, 1.2.1
  @backstage/backend-tasks                                         0.5.27
  @backstage/backend-test-utils                                    0.4.4
  @backstage/canon                                                 0.2.0
  @backstage/catalog-client                                        1.9.1
  @backstage/catalog-model                                         1.7.3
  @backstage/cli-common                                            0.1.15
  @backstage/cli-node                                              0.2.13
  @backstage/cli                                                   0.31.1
  @backstage/config-loader                                         1.10.0
  @backstage/config                                                1.3.2
  @backstage/core-app-api                                          1.16.0
  @backstage/core-compat-api                                       0.4.0
  @backstage/core-components                                       0.17.0
  @backstage/core-plugin-api                                       1.10.5
  @backstage/e2e-test-utils                                        0.1.1
  @backstage/errors                                                1.2.7
  @backstage/eslint-plugin                                         0.1.10
  @backstage/frontend-app-api                                      0.11.0
  @backstage/frontend-defaults                                     0.2.0
  @backstage/frontend-plugin-api                                   0.10.0
  @backstage/frontend-test-utils                                   0.3.0
  @backstage/integration-aws-node                                  0.1.15
  @backstage/integration-react                                     1.2.5
  @backstage/integration                                           1.16.2
  @backstage/plugin-api-docs                                       0.12.5
  @backstage/plugin-app-backend                                    0.5.0
  @backstage/plugin-app-node                                       0.1.31
  @backstage/plugin-app                                            0.1.7
  @backstage/plugin-auth-backend-module-atlassian-provider         0.4.1
  @backstage/plugin-auth-backend-module-auth0-provider             0.2.1
  @backstage/plugin-auth-backend-module-aws-alb-provider           0.4.1
  @backstage/plugin-auth-backend-module-azure-easyauth-provider    0.2.6
  @backstage/plugin-auth-backend-module-bitbucket-provider         0.3.1
  @backstage/plugin-auth-backend-module-bitbucket-server-provider  0.2.1
  @backstage/plugin-auth-backend-module-cloudflare-access-provider 0.4.1
  @backstage/plugin-auth-backend-module-gcp-iap-provider           0.4.1
  @backstage/plugin-auth-backend-module-github-provider            0.3.1
  @backstage/plugin-auth-backend-module-gitlab-provider            0.3.1
  @backstage/plugin-auth-backend-module-google-provider            0.3.1
  @backstage/plugin-auth-backend-module-guest-provider             0.2.6
  @backstage/plugin-auth-backend-module-microsoft-provider         0.3.1
  @backstage/plugin-auth-backend-module-oauth2-provider            0.4.1
  @backstage/plugin-auth-backend-module-oauth2-proxy-provider      0.2.6
  @backstage/plugin-auth-backend-module-oidc-provider              0.4.1
  @backstage/plugin-auth-backend-module-okta-provider              0.2.1
  @backstage/plugin-auth-backend-module-onelogin-provider          0.3.1
  @backstage/plugin-auth-backend                                   0.24.4
  @backstage/plugin-auth-node                                      0.4.17, 0.5.6, 0.6.1
  @backstage/plugin-auth-react                                     0.1.13
  @backstage/plugin-bitbucket-cloud-common                         0.2.28
  @backstage/plugin-catalog-backend-module-logs                    0.1.8
  @backstage/plugin-catalog-backend-module-msgraph                 0.6.8
  @backstage/plugin-catalog-backend-module-scaffolder-entity-model 0.2.6
  @backstage/plugin-catalog-backend-module-unprocessed             0.5.6
  @backstage/plugin-catalog-backend                                1.32.0
  @backstage/plugin-catalog-common                                 1.1.3
  @backstage/plugin-catalog-graph                                  0.4.17
  @backstage/plugin-catalog-import                                 0.12.12
  @backstage/plugin-catalog-node                                   1.16.2
  @backstage/plugin-catalog-react                                  1.16.0
  @backstage/plugin-catalog-unprocessed-entities-common            0.0.7
  @backstage/plugin-catalog                                        1.28.0
  @backstage/plugin-events-node                                    0.3.10, 0.4.9
  @backstage/plugin-kubernetes-backend                             0.19.4
  @backstage/plugin-kubernetes-common                              0.9.4
  @backstage/plugin-kubernetes-node                                0.2.4
  @backstage/plugin-kubernetes-react                               0.5.5
  @backstage/plugin-kubernetes                                     0.12.5
  @backstage/plugin-org                                            0.6.37
  @backstage/plugin-permission-backend-module-allow-all-policy     0.2.6
  @backstage/plugin-permission-backend                             0.5.55
  @backstage/plugin-permission-common                              0.8.4
  @backstage/plugin-permission-node                                0.8.8, 0.9.0
  @backstage/plugin-permission-react                               0.4.32
  @backstage/plugin-proxy-backend                                  0.6.0
  @backstage/plugin-proxy-node                                     0.1.2
  @backstage/plugin-scaffolder-backend-module-azure                0.2.7
  @backstage/plugin-scaffolder-backend-module-bitbucket-cloud      0.2.7
  @backstage/plugin-scaffolder-backend-module-bitbucket-server     0.2.7
  @backstage/plugin-scaffolder-backend-module-bitbucket            0.3.8
  @backstage/plugin-scaffolder-backend-module-gerrit               0.2.7
  @backstage/plugin-scaffolder-backend-module-gitea                0.2.7
  @backstage/plugin-scaffolder-backend-module-github               0.6.1
  @backstage/plugin-scaffolder-backend-module-gitlab               0.8.1
  @backstage/plugin-scaffolder-backend                             1.31.0
  @backstage/plugin-scaffolder-common                              1.5.10
  @backstage/plugin-scaffolder-node                                0.8.0
  @backstage/plugin-scaffolder-react                               1.14.6
  @backstage/plugin-scaffolder                                     1.29.0
  @backstage/plugin-search-backend-module-catalog                  0.3.2
  @backstage/plugin-search-backend-module-pg                       0.5.42
  @backstage/plugin-search-backend-module-techdocs                 0.4.0
  @backstage/plugin-search-backend-node                            1.3.9
  @backstage/plugin-search-backend                                 2.0.0
  @backstage/plugin-search-common                                  1.2.17
  @backstage/plugin-search-react                                   1.8.7
  @backstage/plugin-search                                         1.4.24
  @backstage/plugin-signals-react                                  0.0.11
  @backstage/plugin-techdocs-backend                               2.0.0
  @backstage/plugin-techdocs-common                                0.1.0
  @backstage/plugin-techdocs-module-addons-contrib                 1.1.22
  @backstage/plugin-techdocs-node                                  1.13.1
  @backstage/plugin-techdocs-react                                 1.2.15
  @backstage/plugin-techdocs                                       1.12.4
  @backstage/plugin-user-settings-common                           0.0.1
  @backstage/plugin-user-settings                                  0.8.20
  @backstage/release-manifests                                     0.0.12
  @backstage/test-utils                                            1.7.6
  @backstage/theme                                                 0.6.4
  @backstage/types                                                 1.2.1
  @backstage/version-bridge                                        1.0.11

### 👀 Have you spent some time to check if this bug has been raised before?

- [x] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [x] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else
