### ISSUE TITLE
🐛 Bug Report: Missing credentials when accessing external api endpoint without authentication using the new backend

### ISSUE THREAD

**Issue by ronballesteros** [backstage/backstage#29481]
### 📜 Description

Sort of related to https://github.com/backstage/backstage/issues/28110 but I think its a bit different.  Adding this in case someone else is running into the same issue.

Say in my proxy endpoint configuration, I have this:
```
...
proxy:
  endpoints:
    /acmeservices/acmebalance/next: 'https://acmebalance.next.acme.io/'
    /acmeservices/acmebalance/dev: 'https://acmebalance.dev.acme.io/'
    /acmeservices/acmechannels/next: 'https://acmechannels.next.acme.io/'
    /acmeservices/acmechannels/dev: 'https://acmeexample.dev.acme.io'
    /randomuser: 'https://randomuser.me/api'
```

With the new backend, When I try to access the target api via the backstage gui, I get a 401 missing credentials:
```
{
  "error": {
    "name": "AuthenticationError",
    "message": "Missing credentials"
  },
  "request": {
    "method": "GET",
    "url": "/api/proxy/acmeservices/acmeinfocards/dev/v1/getting-started-cards/health-check"
  },
  "response": {
    "statusCode": 401
  }
}
```

Setting the endpoint like this will work, but I don't want to since this is a security concern.
```
...
/acmeservices/acmechannels/dev: 'https://acmeexample.dev.acme.io'
  target: 'https://acmeexample.dev.acme.io'
  credentials: dangerously-allow-unauthenticated
  changeOrigin: true
  /acmeservices/acmeexamp
```

Setting it like this still results in a 401 missing credentials error and setting credentials require/forward doesn't help at all...
```
/acmeservices/acmechannels/dev: 'https://acmeexample.dev.acme.io'
  target: 'https://acmeexample.dev.acme.io'
  changeOrigin: true
```
```
/acmeservices/acmechannels/dev: 'https://acmeexample.dev.acme.io'
  target: 'https://acmeexample.dev.acme.io'
  changeOrigin: true
  allowedHeaders: ['Authorization']
    headers:
      Authorization: "Bearer 12345"
```

It appears that there is no token being passed to the backend.  I don't really need backstage to forward the api token to the target endpoint.  All I need is for our users to be able to interact with our target api endpoints via the backstage ui.  

![Image](https://github.com/user-attachments/assets/5a102a3d-2a24-49c5-b472-419581b9277b)

Is there a way to pass a token from the frontend to the backend so that there is no 401 error?  Or what is the recommended way?  This sounds like its something really simple but haven't got this to work right.  

### 👍 Expected behavior

It should just execute the api proxy call to the endpoint and return with a successful response.

### 👎 Actual Behavior with Screenshots

In the backstage ui, when you try to execute the api call, we get something like this:

```
{
  "error": {
    "name": "AuthenticationError",
    "message": "Missing credentials"
  },
  "request": {
    "method": "GET",
    "url": "/api/proxy/acmeservices/acmeinfocards/dev/v1/getting-started-cards/health-check"
  },
  "response": {
    "statusCode": 401
  }
}
```

### 👟 Reproduction steps

Create an proxy endpoint similar to what is setup and try to execute.

```
proxy:
  endpoints:
    'randomuser':
      target: 'https://randomuser.me/api'
      changeOrigin: true
```

```
proxy:
  endpoints:
    'randomuser':
      target: 'https://randomuser.me/api'
      changeOrigin: true
      allowedHeaders: ['Authorization']
      headers:
        Authorization: "Bearer my-static-token-12345"
```

### 📃 Provide the context for the Bug.

Users cannot execute api calls to our target endpoints.

### 👀 Have you spent some time to check if this bug has been raised before?

- [x] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [x] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by ronballesteros** [comment]
Thanks @Rugvip - in my values.yaml proxy.endpoints config section, I can have anywhere from 10-20+ endpoints like so:
```
proxy:
  endpoints:
    /acmeservices/acmesheet/test: 'https://acmesheet.test.acme.io/'
    /acmeservices/acmesheet/qa: 'https://acmesheet.qa.acme.io/'
    /acmeservices/acmechannels/test: 'https://acmechannels.test.acme.io/'
   /acmeservices/acmenewservice/test: 'https://acmenewservices.test.acme.io/'
...
```

Each proxy target has a lot of endpoints and is there a way where we can wild card the call?  For example, I wanted to wild card anything after `/api/proxy/acmeservices/acmesheet/test/`.  I've been trying to write custom backend modules for this, but have not been having any luck.  Wondering if the community has done something similar?
```
export const useZapServiceData = () => {
  const identityApi = useApi(identityApiRef);
  const fetchApi = useApi(fetchApiRef);

  const getZapData = async () => {
    const { token } = await identityApi.getCredentials();

    const res = await fetchApi.fetch(
      '/api/proxy/acmeservices/acmesheet/test/v1/getting-started-cards/health-check',
      {
        headers: {
          Authorization: `Bearer ${token}`,
        },
      }
    );

```

**Comment by ronballesteros** [comment]
I define my apis via yaml like so:
```
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
    name: acmebuisness-api
    title: Business API
spec:
    type: openapi
    lifecycle: experimental
    owner: engineering
    system: integration
    definition:
        $text: https://acmebusiness.test.acme.io/swagger/1/swagger.json
```

In the backstage ui, it allows users to execute api calls and this is where backstage will proxy the request.  I'm just trying to figure out (without using the dangerously flag feature) how to make this work correctly.

![Image](https://github.com/user-attachments/assets/75b1e421-d007-4dc0-86b9-230e4ec2373a)

Our backstage requires auth via github and is proxied through some cloud waf.  So even if I were to take the proxy link and try to curl directly without having to authenticate to backstage, I get redirected to our sso/cloudwaf.  I guess there are some protections there even if I were to enable the dangerously auth flag feature, but trying to implement the recommended method of not having this flag enabled.
