### ISSUE TITLE
🚀 Feature: Rancher integration with kubernetes plugin

### ISSUE THREAD

**Issue by 0xts** [backstage/backstage#29493]
### 🔖 Feature description

[Rancher](https://ranchermanager.docs.rancher.com/) makes it easy to manage 100s -1000s of Kubernetes clusters and is pretty helpful. If one's looking to add their k8s clusters to Backstage, they need to configure each cluster separately, however, if one's using Rancher to manage their clusters already, they could just configure their Rancher with Backstage and all the downstream clusters (being managed by Rancher) will be discoverable and manageable without having to muddle oneself with myriads of k8s cluster configurations.

### 🎤 Context

Implementation of this feature would allow one to just configure Rancher instance(s) with Backstage and as the effect, they'll have all the k8s clusters managed by Rancher instance(s) available on Backstage, without having to configure each cluster individually. The configuration could look something like this -

```yaml
kubernetes:
  rancher:
    refreshInterval:
      minutes: 10
    instances:
      - name: "US East Rancher"
        url: <RANCHER SERVER URL>
        apiToken: <RANCHER SERVER API TOKEN>
```

### ✌️ Possible Implementation

Upon checking that the configuration for Rancher in the k8s plugin is provided, the k8s fetcher could fetch the clusters and other k8s resources from the Rancher instance(s). Even now it's possible to do this through extension points in the plugin (cluster discovery and fetcher extension points specifically), but it'd be great if this could be included in the plugin.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [x] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [x] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!
