### ISSUE TITLE
🐛 Registering component takes longer time to show up in Backstage catalog

### ISSUE THREAD

**Issue by MaharaJothi** [backstage/backstage#29491]
### 📜 Description

Hi , 

I am trying to register the created resources in backstage using below action/code block. It is observed that it takes 2-3 minutes to appear in backstage catalog and sometimes even more.

Is it possible to refresh from backend to load the registered resources immediately once registered?  
Is there any configuration that causes this delay?

```
- id: register
  name: Register Component
  action: catalog:register
  input:
    repoContentsUrl: ${{ steps['publish'].output.repoContentsUrl }}
    catalogInfoPath: '/catalog-info.yaml'
    optional: true
```

thanks in advance 

### 👍 Expected behavior

Registered component should come up in catalog immediately

### 👎 Actual Behavior with Screenshots

It takes atleast 2 minutes and sometimes even more to come up

### 👟 Reproduction steps

NA

### 👀 Have you spent some time to check if this bug has been raised before?

- [x] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [x] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None
