### ISSUE TITLE
🚀 Feature: Import only direct members for all subgroups on self hosted gitlab instance

### ISSUE THREAD

**Issue by zoby35** [backstage/backstage#29513]
### 🔖 Feature description

Import only direct members for all of the subgroups under a group path configured in app-config.yaml for a self hosted Gitlab instance.

### 🎤 Context

When we do not want to import all of the users from the whole instance, we must use the "restrictUsersToGroup" option. And if we want to import only direct members we must not configure the "relations" parameter.
But using that option, the only users ingested are the ones that are seen as direct members at "org/teams" group level.
If a user is a direct member on a subgroup "org/teams/team-a" but not displayed as member at "org/teams" level, he is not ingested.

```
catalog:
    provider:
        gitlab:
            ownInstanceProviderId:
                host: gitlab.example.com
                orgEnabled: true
                group: org/teams
                restrictUsersToGroup: true
                entityFilename: catalog-info.yml
                schedule:
                    frequency: {minutes: 5}
                    timeout: {minutes: 3}
```

### 👀 Have you spent some time to check if this feature request has been raised before?

- [x] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [x] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None
