### ISSUE TITLE
🚀 Feature: Add the possibility of having the assignees field in the scaffolder action github:pull-request

### ISSUE THREAD

**Issue by gabriel-dantas98** [backstage/backstage#29536]
### 🔖 Feature description

We are currently able to use the reviewers field, but it would be interesting to also be able to use the assignees field and improve the creation of pull requests using scaffolder.

How it is now:
```yaml
   - id: pull_request
      name: Create deployment PR
      action: publish:github:pull-request
      input:
        repoUrl: github.com?owner=sample&repo=deployments
        branchName: 'sw-template/${{ parameters.environment }}/${{ parameters.app_name }}'
        title: '🔩 Create Argo Workflows for ${{ parameters.app_name }} in ${{ parameters.environment }}'
        reviewers: ['${{ user.entity.spec.profile.github }}']
        description: Sample
        sourcePath: ./templates/outputs/
        targetPath: 'app-definitions/${{ parameters.app_name }}'
```

How i'd like it to be:
```yaml
   - id: pull_request
      name: Create deployment PR
      action: publish:github:pull-request
      input:
        repoUrl: github.com?owner=sample&repo=deployments
        branchName: 'sw-template/${{ parameters.environment }}/${{ parameters.app_name }}'
        title: '🔩 Create Argo Workflows for ${{ parameters.app_name }} in ${{ parameters.environment }}'
        reviewers: ['${{ user.entity.spec.profile.github }}']
        assignees: '${{ user.entity.spec.profile.github }}'
        description: Sample
        sourcePath: ./templates/outputs/
        targetPath: 'app-definitions/${{ parameters.app_name }}'
```

### 🎤 Context

It would be important for us to be able to better attribute the users who created the pull requests. It is also important for some metrics that we use internally.

### ✌️ Possible Implementation

Update: https://github.com/backstage/backstage/blob/master/plugins/scaffolder-backend-module-github/src/actions/githubPullRequest.ts#L131-L150

Example in API: https://docs.github.com/en/rest/issues/assignees?apiVersion=2022-11-28

### 👀 Have you spent some time to check if this feature request has been raised before?

- [x] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [x] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else
