### ISSUE TITLE
💬 RFC: Change `catalog.location.*` to resource permissions

### ISSUE THREAD

**Issue by stephenglass** [backstage/backstage#29694]
### 🔖 Need

I would like to use the catalog importer tool to register `Template` kinds to the catalog. However, to do this you must add `Template` kind to the allowed kind rules in config. When you do this, it opens up the possibility to run potentially unchecked and malicious code on your app via software templates. The `catalog.location.create` permission can permit who can add entities to the catalog but it's severely limited because the deny/approval equates to either "I can import any kind (even arbitrary code execution through software templates)" or "I can't import anything at all." Ideally, I want trusted "admins" to be able to import templates while still letting default users import components.

### 🎉 Proposal

Make the `catalog.location.*` permissions resource permissions. Then, through the permission framework you could create a policy where default users can import create kinds e.g. components but admins can create restricted kinds e.g. templates.

### 〽️ Alternatives

Adding templates via static configuration. There is some little flexibility that you can use globs in the target, but still it adds a burden. Example:

```
  locations:
    - type: url
      target: https://github.com/my-org/my-repo/templates/**.yaml
      rules:
        - allow: [Templates]
```

However, this still comes with a large burden. You can create a monorepo for your templates, and a glob pattern for that monorepo in static config, however now every developer needs to work within your monorepo and navigate your approval structure, setup governance, etc., which is extra hassle for platform team and development teams.

You can also just have software template creators place templates in their own repo, but now still it's added responsibility for platform team that has to maintain the static config to include all the targets.

### ❌ Risks

Changing the permissions to resource permissions could be a breaking change (unless there is a good way to deprecate old permission while introducing the new ones).

### 👀 Have you spent some time to check if this RFC has been raised before?

- [x] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [x] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

**Comment by vinzscam** [comment]
Unfortunately, 'create' permissions cannot be resource permissions because no existing resource is available to validate the conditions against.
One solution I can give you is to disallow importing templates and instead define a specific location in a repository where only a few designated actors have write access. This location would contain all the templates that should be ingested:

```
apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: org-data
spec:
  type: url
  targets:
    - http://github.com/myorg/myproject/mytemplate1/catalog-info.yaml
    - http://github.com/myorg/myproject/mytemplate2/template.yaml
```
