### ISSUE TITLE
Add `action.id` to scaffolder action context

### ISSUE THREAD

**Issue by stephenglass** [backstage/backstage#29724]
### 📜 Issue Labels

- [x] Please familiarize yourself with the issue labels used in this project: [LABELS.md](https://github.com/backstage/backstage/blob/master/LABELS.md)

### 🔎 Search Terms

```plain
"action id", "action context", "scaffolder"
```

### 🗃️ Project Area

Software Templates

### 🔖 Need

I have a custom plugin for adding manual approval steps in software templates. A software template can also technically have multiple approval request steps. For that reason, the primary key for an approval request is something like: `template_ref,action_id`. This way a request is linked to the specific step id that triggered the request creation in the template. In the approval backend, we will also use the action id as a lookup in the task `spec`.

### 📝 Proposal

Make the action id accessible from the action context handler e.g. `ctx.action.id`.

**Example** 

Template steps:
```yaml
  steps:
  - action: approvals:create-request
    id: create-request
    name: Create Request
    input:
       ....
```

In your action handler:
```ts
async handler(ctx) {
  const actionId = ctx.action.id; // = "create-request"
}
```

### 🔄 Alternatives

You can create an `id` input to the custom action but this is redundant.

```yaml
  steps:
  - action: approvals:create-request
    id: create-request
    name: Create Request
    input:
       id: create-request
```

### Have you read the Code of Conduct?

- [x] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit a PR?

Yes, and I have enough information to get started
