### ISSUE TITLE
Github Discovery Plugin: `validateLocationsExist` checks default branch instead of the one mentioned in config.

### ISSUE THREAD

**Issue by jenil-harness** [backstage/backstage#29735]
### 📜 Issue Labels

- [x] Please familiarize yourself with the issue labels used in this project: [LABELS.md](https://github.com/backstage/backstage/blob/master/LABELS.md)

### 🔎 Search Terms

```plain
"github discovery plugin", "validateLocationsExist"
```

### 🗃️ Project Area

Catalog

### 🔗 External Integration

GitHub

### 📝 Description & Context

When using validateLocationsExist: true in the config, it always checks if the file exists in the default branch only and not in the branch mentioned in the config.

```
catalog:
  providers:
    github:
      Main:
        host: github.com
        organization: '<organization>'
        catalogPath: '/catalog-info.yaml'
        validateLocationsExist: true
        filters:
          branch: 'backstage'
        schedule:
          frequency: { minutes: 60 }
          timeout: { minutes: 3 }
```

With the above configuration, the `catalog-info.yaml` file was ingested even when the repository did not have a `backstage` branch.

Similar issue have been reported here. https://github.com/backstage/backstage/issues/16650

### 👍 Expected Behavior

The `catalog-info.yaml` file should not have been ingested since the `backstage` branch is not present.

### 🥾 Reproduction steps

1. Add the following config for github discovery plugin
```
catalog:
  providers:
    github:
      Main:
        host: github.com
        organization: '<organization>'
        catalogPath: '/catalog-info.yaml'
        validateLocationsExist: true
        filters:
          branch: 'backstage'
        schedule:
          frequency: { minutes: 60 }
          timeout: { minutes: 3 }
```
2. Ensure that the repo doesn't have any `backstage` branch and the default branch does have `catalog-info.yaml`.
3. You will see that `catalog-info.yaml` from `backstage` branch has been ingested. 

### Have you read the Code of Conduct?

- [x] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Undecided
