### ISSUE TITLE
Feature: Add a parameter to the URL github picker to pull repositories only on demand

### ISSUE THREAD

**Issue by GersonTf** [backstage/backstage#29736]
### 📜 Issue Labels

- [x] Please familiarize yourself with the issue labels used in this project: [LABELS.md](https://github.com/backstage/backstage/blob/master/LABELS.md)

### 🔎 Search Terms

```plain
urlpicker, scaffolder.
```

### 🗃️ Project Area

Software Templates

### 🔖 Need

When you use the repository picker in the scaffolder, like this:
```
    properties:
       repoUrl:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            # Here's the option you can pass to the RepoUrlPicker
            requestUserCredentials:
              secretsKey: USER_OAUTH_TOKEN
              additionalScopes:
                github:
                  - workflow
            allowedHosts:
              - github.com
```
It pulls the repositories from your repo, to help with finding your repositories when you have a template that will write to an existing repo thanks to this feature: https://github.com/backstage/backstage/pull/28706

There is a small side-effect now which is that the repositories are always pulled to the dropdown but, when you have a template that creates a new repository, it is odd and counterintuitive to have the list of options. 

### 📝 Proposal

The RepoUrlPicker will have an optional boolean parameter like "pullExistingRepos". If it is false, we skip the unnecessary github call to fetch repositories. This change will not only make the picker more intuitive but also will save API calls to avoid rate limits. 

An optional an idea, if it is doable, would be to somehow check that your repository exists on github to avoid errors when creating a repo with an existing name. 

### Have you read the Code of Conduct?

- [x] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit a PR?

Yes, and I have enough information to get started
