### ISSUE TITLE
[Kubernetes] Add Microsoft Entra ID server-side kubernetes auth provider

### ISSUE THREAD

**Issue by fjudith** [backstage/backstage#29753]
### 📜 Issue Labels

- [x] Please familiarize yourself with the issue labels used in this project: [LABELS.md](https://github.com/backstage/backstage/blob/master/LABELS.md)

### 🔎 Search Terms

```plain
"kubernetes auth provider", "microsoft entra id", "custom scope", "enterprise app"
```

### 🗃️ Project Area

Kubernetes Plugin

### 🔖 Need

A pretty common Kubernetes deployment pattern consists to leverage a custom Microsoft Entra ID (ex-AzureAD) Enterprise App to enable single signon to Kubernetes clusters running outside of Azure Kubernetes Service (AKS).

Typical example, [Microsoft Entra ID authentication to Amazon EKS](https://aws.amazon.com/blogs/containers/using-azure-active-directory-to-authenticate-to-amazon-eks/).

In such case `azure` server-side kubernetes auth provider fails as it is locked to the AKS authorization scope.

https://github.com/backstage/backstage/blob/3551662f980d2dbbfd66e88efbc25c10cf6be8d4/plugins/kubernetes-backend/src/auth/AzureIdentityStrategy.ts#L29

### 📝 Proposal

1. Add a new `microsoft` kubernetes auth provider supporting the customization of the authorization scope associated to custom Microsoft Entra ID enterprise app. 
2. Document instructions on how to associate the Backstage auth Enterprise App with the Kubernetes dedicated one , to prevent requesting users to enter credentials twice.

example **app-config**

```diff
auth:
  providers:
    microsoft:
      <env>:
        clientId: ${AZURE_CLIENT_ID}
        clientSecret: ${AZURE_CLIENT_SECRET}
        tenantId: ${AZURE_TENANT_ID}
        domainHint: ${AZURE_TENANT_ID}
        signIn:
          resolvers:
            # See https://backstage.io/docs/auth/microsoft/provider#resolvers for more resolvers
            - resolver: emailMatchingUserEntityProfileEmail

kubernetes
+ auth:
+   providers:
+     microsoft:
+       <env>:
+         scope: custo-enterprise-app-id/scope
```

### 🔄 Alternatives

Document how to override existing `azure` server-side kubernetes auth provider using a backend module.

### Have you read the Code of Conduct?

- [x] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit a PR?

Yes, and I have enough information to get started

**Comment by Rugvip** [comment]
Yep makes sense to make that hardcoded scope configurable 👍

I wonder if this needs to support per-cluster scope or such? might be good to leave a bit of flexibility in the config schema so that more filters can be added down the line. Can figure out details in a PR though.

**Comment by fjudith** [comment]
> Yep makes sense to make that hardcoded scope configurable 👍
> 
> I wonder if this needs to support per-cluster scope or such? might be good to leave a bit of flexibility in the config schema so that more filters can be added down the line. Can figure out details in a PR though.

Good  catch ! it might be more consistent to get the `scope` close to `authProvider` app-config and ` kubernetes.io/auth-provider` annotations.

```yaml
auth:
  providers:
    microsoft:
      <env>:
        clientId: ${AZURE_CLIENT_ID}
        clientSecret: ${AZURE_CLIENT_SECRET}
        tenantId: ${AZURE_TENANT_ID}
        domainHint: ${AZURE_TENANT_ID}
        signIn:
          resolvers:
            # See https://backstage.io/docs/auth/microsoft/provider#resolvers for more resolvers
            - resolver: emailMatchingUserEntityProfileEmail

kubernetes
+ clusterLocatorMethods:
+   - type: config
+     clusters:
+       - url: https://k8s-cluster-prod.example.com
+         authProvider: microsoft
+         authScope: custo-enterprise-app-id/scope
```
