### ISSUE TITLE
[Kubernetes] Issue when cluster and component entities are not in the Namespace

### ISSUE THREAD

**Issue by fjudith** [backstage/backstage#29751]
### 📜 Issue Labels

- [x] Please familiarize yourself with the issue labels used in this project: [LABELS.md](https://github.com/backstage/backstage/blob/master/LABELS.md)

### 🔎 Search Terms

```plain
"org", "kubernetes", "resource", "locator", "namespace", "catalog entity locator"
```

### 🗃️ Project Area

Kubernetes Plugin

### 🔗 External Integration

N/A

### 📝 Description & Context

When users navigates to the Kubernetes tab, they gets the message "No resource found" if the `CatalogRelation` service locator is configured, and the component does not resides in the same namespace as the `kubernetes-cluster` resource in the catalog.

### 👍 Expected Behavior

Developers should be able to associate their components to `kubernetes-cluster` resources allocated to a different namespace, as most kubernetes cluster are shared accross teams and most entity processor are generating resources in the `default` namespace.

The following entity spec should allow users to observe their resources in the Kubernetes entity tab.

```yaml
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage
  namespace: platform-engineering
  annotations:
    'backstage.io/kubernetes-label-selector': 'app.kubernetes.io/instance=backstage'
spec:
  dependsOn:
    - resource:default/k8s-cluster-dev
    - resource:default/k8s-cluster-prod
``` 

### 🥾 Reproduction steps

**working**
1. Register a component in the  test namespace
   `kind: Component`, `metadata.namespace: test`
2. Register a `kubernetes-cluster` resource in the test namespace
  `kind: Resource`, `metadata.namespace: test`, `spec.type: kubernetes-cluster`
3. Add dependency to the component on the kubernetes-cluster resource
  `kind: Component`, `spec.dependsOn[0]: resource:test/k8s`
4. Navigate to the Kubernetes tab of the component in the test namespace

**not working**
1. Register a component in the  test namespace
   `kind: Component`, `metadata.namespace: test`
2. Register a `kubernetes-cluster` resource in the default namespace
  `kind: Resource`, `metadata.namespace: default`, `spec.type: kubernetes-cluster`
3. Add dependency to the component on the kubernetes-cluster resource
  `kind: Component`, `spec.dependsOn[0]: resource:default/k8s`
4. Navigate to the Kubernetes tab of the component in the test namespace

### Have you read the Code of Conduct?

- [x] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes, and I have enough information to get started
