### ISSUE TITLE
Migrate `mkdocs` to `rspress` or make the renderer customizable

### ISSUE THREAD

**Issue by JounQin** [backstage/backstage#29798]
### 📜 Issue Labels

- [x] Please familiarize yourself with the issue labels used in this project: [LABELS.md](https://github.com/backstage/backstage/blob/master/LABELS.md)

### 🔎 Search Terms

```plain
mkdocs rspress
```

### 🗃️ Project Area

Documentation

### 🔖 Need

`mkdocs` relies on Python heavily, as a Node.js project, we'd avoid Python requirement, in our experience at @alauda, it's painful to use `mkdocs` which **always** fails to build to document on Node backend.

### 📝 Proposal

In case we'll migrate to `rspack` eventually https://github.com/backstage/backstage/issues/29768, [`rspress`](https://github.com/web-infra-dev/rspress) should be taken into account for document generation tool, it's a pure Node project, with familiar `.md` and `.mdx` supports which is very promising.

### Have you read the Code of Conduct?

- [x] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit a PR?

Yes, but I would like some more guidance

**Comment by awanlin** [comment]
Hi @JounQin, MkDocs has been at the heart of TechDocs since it launched nearly 5 years ago. There's a massive number of Backstage Adopters that are currently using it without issues and very successfully. Looking at `rspress` in it's current form we would loose a lot more than we would gain. 

If you are having issues with MkDocs as it relates to TechDocs then I would log an issue or issues with details about them so that we can try and help resolve them as that seems like a better path forward.

**Comment by Rugvip** [comment]
I'll also throw in that if we consider making changes to TechDocs rendering we should also consider fully client-side or hybrid options imo

**Comment by JounQin** [comment]
> I'll also throw in that if we consider making changes to TechDocs rendering we should also consider fully client-side or hybrid options imo

`rspress` can be used with CSR or SSG at the same time.

**Comment by awanlin** [comment]
Hi @JounQin, would still like to better understand why TechDocs in it's current state doesn't work for you? Your experience is very much the opposite of mine which comes from helping people on Discord and working with Adopters as part of my day job. This information could also be helpful for potentially improving things in more easily actionable way than a large migration such as this. 👍

**Comment by awanlin** [comment]
Thanks for sharing this, can you also share your `mkdocs.yaml` as the error seems to indicate a problem with the config - "Aborted with a configuration error!". 

On the demo site we have [an example setup](https://demo.backstage.io/catalog/default/component/backstage-demo/docs) and I rarely see this documentation needing to reload unless we've done a new deployment of the site itself. We do use cloud storage, not sure if you are doing that as well? This aspect I think is less about the underlying tool and within TechDocs itself. Also contributing to this is if the docs never properly generated than it will keep wanting to do that until it's successful.

---

To help us make a decision like this we need data. What you have shared is very focused on you and your specific needs but we need to weigh that against the needs of the entire Backstage ecosystem of Adopters using TechDocs. The data that I have says that MkDocs has been working for Adopters. Having to install Python hasn't been a deal breaker the way it seems to be for you.

Here's the list of plugins currently available for MkDocs: https://github.com/mkdocs/catalog. These are already built and can be used by Adopters without having to write code. I mention this as the general feedback from Backstage adopters and potential adopters is they want to write less code to get value out of Backstage overall.

Taking a step back, I think part of the issue I have is around the focus in the title: Migrate `mkdocs` to `rspress`. We have so many migrations going on new backend system, new frontend system, React 19, React Router 7, MUI to something else. I know I'm personally getting a little worn down by that and I feel like others might be as well. Maybe this should really be focused on the idea of being able to plug in other tools so it's more complimentary. Those being successful with the current stack can continue to do so with this introducing other options for adopters like yourself. Also, for those who would rather use say Docusaurus, or Jekyll or Hugo or some other tool this could allow them to do that with rspress being an example of how they could implement support.

Sorry, I know that's a lot, this is an area I'm pretty passionate about and care deeply about it as it's one of the features that really drew me into Backstage years ago. 🚀

**Comment by JounQin** [comment]
@awanlin Here you are:

```yaml
site_name: Developer Portal
docs_dir: ./docs
theme:
  name: material
  font: false
plugins:
  - techdocs-core
nav:
  - 概述:
      - 'overview/overview.md'
      - 'overview/platform-engineering.md'
      - 'overview/user-story.md'
  - 快速入门:
      - 平台团队: 'getting-started/for-platform-team.md'
      - 业务团队管理员: 'getting-started/for-admin.md'
      - 业务团队开发者: 'getting-started/for-developers.md'
  - 平台管理指南:
      - Catalog:
          - 'for-platform-team/catalog/index.md'
          - 'for-platform-team/catalog/system-model.md'
          - 'for-platform-team/catalog/life-of-an-entity.md'
          - 'for-platform-team/catalog/configuration.md'
          - 'for-platform-team/catalog/usage.md'
          - 'for-platform-team/catalog/descriptor-format.md'
          - 'for-platform-team/catalog/references.md'
          - 'for-platform-team/catalog/well-known-annotations.md'
          - 'for-platform-team/catalog/well-known-relations.md'
          - 'for-platform-team/catalog/well-known-statuses.md'
          - 'for-platform-team/catalog/extending-the-model.md'
          - 'for-platform-team/catalog/external-integrations.md'
          - 'for-platform-team/catalog/catalog-customization.md'
          - 'for-platform-team/catalog/best-practice.md'
          - 'for-platform-team/catalog/api.md'
          - 'for-platform-team/catalog/creating-the-catalog-graph.md'
      - 插件:
          - 概览: 'for-platform-team/plugins/index.md'
          - 插件开发:
              - 'for-platform-team/plugins/create-a-plugin.md'
              - 'for-platform-team/plugins/plugin-development.md'
              - 'for-platform-team/plugins/structure-of-a-plugin.md'
              - 'for-platform-team/plugins/integrating-plugin-into-software-catalog.md'
              - 'for-platform-team/plugins/integrating-search-into-plugins.md'
              - 'for-platform-team/plugins/composability.md'
              - 'for-platform-team/plugins/analytics.md'
              - 'for-platform-team/plugins/feature-flags.md'
              - 后端插件:
                  - 'for-platform-team/plugins/proxying.md'
                  - 'for-platform-team/plugins/backend-plugin.md'
                  - 'for-platform-team/plugins/call-existing-api.md'
                  - 'for-platform-team/plugins/url-reader.md'
          - 动态插件:
              - 'for-platform-team/plugins/dynamic-plugins/intro.md'
              - 'for-platform-team/plugins/dynamic-plugins/frontend.md'
              - 'for-platform-team/plugins/dynamic-plugins/backend.md'
              - 'for-platform-team/plugins/dynamic-plugins/nginx-static-server.md'
          - 现有插件:
              - 'for-platform-team/plugins/existing-plugins/cicd.md'
              - 'for-platform-team/plugins/existing-plugins/harbor.md'
              - 'for-platform-team/plugins/existing-plugins/gitlab.md'
              - 'for-platform-team/plugins/existing-plugins/github.md'
              - 'for-platform-team/plugins/existing-plugins/runtime.md'
              - 'for-platform-team/plugins/existing-plugins/sonarqube.md'
              - 'for-platform-team/plugins/existing-plugins/tekton-pipeline.md'
              - 'for-platform-team/plugins/existing-plugins/notifications.md'
      - 集成:
          - Azure:
              - 'for-platform-team/integrations/azure/locations.md'
              - 'for-platform-team/integrations/azure/discovery.md'
              - 'for-platform-team/integrations/azure/org.md'
          - Bitbucket Cloud:
              - 'for-platform-team/integrations/bitbucketCloud/locations.md'
              - 'for-platform-team/integrations/bitbucketCloud/discovery.md'
          - Bitbucket Server:
              - 'for-platform-team/integrations/bitbucketServer/locations.md'
              - 'for-platform-team/integrations/bitbucketServer/discovery.md'
          - GitHub:
              - 'for-platform-team/integrations/github/locations.md'
              - 'for-platform-team/integrations/github/discovery.md'
              - 'for-platform-team/integrations/github/org.md'
              - 'for-platform-team/integrations/github/github-apps.md'
          - GitLab:
              - 'for-platform-team/integrations/gitlab/locations.md'
              - 'for-platform-team/integrations/gitlab/discovery.md'
              - 'for-platform-team/integrations/gitlab/org.md'
      - Docs:
          - 'for-platform-team/techdocs/README.md'
          - 'for-platform-team/techdocs/concepts.md'
          - 'for-platform-team/techdocs/getting-started.md'
          - 'for-platform-team/techdocs/architecture.md'
          - 'for-platform-team/techdocs/configuration.md'
          - 'for-platform-team/techdocs/addons.md'
          - 'for-platform-team/techdocs/using-cloud-storage.md'
          - 'for-platform-team/techdocs/configuring-ci-cd.md'
          - 'for-platform-team/techdocs/how-to-guides.md'
      - 模板:
          - 'for-platform-team/templates/index.md'
          - 'for-platform-team/templates/configuration.md'
          - 'for-platform-team/templates/adding-templates.md'
          - 'for-platform-team/templates/writing-templates.md'
          - 'for-platform-team/templates/input-examples.md'
          - 'for-platform-team/templates/builtin-actions.md'
          - 'for-platform-team/templates/writing-custom-actions.md'
          - 'for-platform-team/templates/writing-custom-field-extensions.md'
          - 'for-platform-team/templates/writing-custom-step-layouts.md'
          - 'for-platform-team/templates/authorizing-parameters-steps-and-actions.md'
          - 'for-platform-team/templates/best-practice.md'
          - 'for-platform-team/templates/testing-scaffolder-alpha.md'
          - 现有模板:
              - 'for-platform-team/templates/existing-templates/register-existing-component.md'
      - 搜索:
          - 'for-platform-team/search/README.md'
          - 'for-platform-team/search/concepts.md'
          - 'for-platform-team/search/search-engines.md'
          - 'for-platform-team/search/best-practice.md'
      - 配置:
          - 'for-platform-team/conf/index.md'
          - 'for-platform-team/conf/reading.md'
          - 'for-platform-team/conf/writing.md'
          - 'for-platform-team/conf/defining.md'
      - 权限:
          - 'for-platform-team/permission/rbac.md'
  - 用户指南:
      - Catalog:
          - 'user-guide/catalog/index.md'
          - 'user-guide/catalog/descriptor-format.md'
          - 'user-guide/catalog/best-practice.md'
      - Docs:
          - 'user-guide/techdocs/README.md'
          - 'user-guide/techdocs/enabling-docs.md'
          - 'user-guide/techdocs/cli.md'
          - 'user-guide/techdocs/creating-and-publishing.md'
      - 'user-guide/plugins.md'
  - FAQ:
      - 'faq/techdocs.md'
  - 故障处理:
      - 'troubleshooting/techdocs.md'

```

I believe it could be related to `mkdocs-techdocs-core`:

```console
pip install mkdocs-techdocs-core  
error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try brew install
    xyz, where xyz is the package you are trying to
    install.
    
    If you wish to install a Python library that isn't in Homebrew,
    use a virtual environment:
    
    python3 -m venv path/to/venv
    source path/to/venv/bin/activate
    python3 -m pip install xyz
    
    If you wish to install a Python application that isn't in Homebrew,
    it may be easiest to use 'pipx install xyz', which will manage a
    virtual environment for you. You can install pipx with
    
    brew install pipx
    
    You may restore the old behavior of pip by passing
    the '--break-system-packages' flag to pip, or by adding
    'break-system-packages = true' to your pip.conf file. The latter
    will permanently disable this error.
    
    If you disable this error, we STRONGLY recommend that you additionally
    pass the '--user' flag to pip, or set 'user = true' in your pip.conf
    file. Failure to do this can result in a broken Homebrew installation.
    
    Read more about this behavior here: <https://peps.python.org/pep-0668/>

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.
```

As a Node developer, I have absolutely no interest in Python, pip, or related tools.

> Here's the list of plugins currently available for MkDocs: [mkdocs/catalog](https://github.com/mkdocs/catalog?rgh-link-date=2025-05-01T14%3A01%3A15.000Z). These are already built and can be used by Adopters without having to write code. I mention this as the general feedback from Backstage adopters and potential adopters is they want to write less code to get value out of Backstage overall.

If we migrate to `rspress`, any function provided by `mkdocs` can be provided with `rspress` plugins, please point me which `mkdocs` plugin can not be implemented with `rspress`.

> I know I'm personally getting a little worn down by that and I feel like others might be as well.

Libraries upgrading and leveling up can not be skipped for any softwares which wants to grow and keep to be updated.

> Those being successful with the current stack can continue to do so with this introducing other options for adopters like yourself. Also, for those who would rather use say Docusaurus, or Jekyll or Hugo or some other tool this could allow them to do that with rspress being an example of how they could implement support.

Yeah, I have a discussion with my teammate yestoday, we agree that we should provide an adaptor for `techdocs` which can be used with `mkdocs`, `rspress`, `Docusaurus`, etc. or whatever the user wants to use.
