### ISSUE TITLE
Cookiecutter variables (`{{ cookiecutter.VAR }}`) not substituting in files fetched via `fetch:template`?

### ISSUE THREAD

**Issue by froyo-saif** [backstage/backstage#29801]
### 📝 Acknowledgement

- [x] I acknowledge that issues using this template may be closed without further explanation.

### Content

I'm encountering an issue where variables using the standard Cookiecutter syntax (`{{ cookiecutter.VARIABLE_NAME }}`) are not being substituted in files fetched using the `fetch:template` action, specifically in a `.gitlab-ci.yml` file within our internal GitLab instance. The literal `{{ cookiecutter.VARIABLE_NAME }}` strings are ending up in the final published repository, despite seemingly correct configuration in both the template and the source repository file.
 
**Background:**
 
We have a Backstage template designed to scaffold a new service, including setting up cloud infrastructure via GitLab CI. The template uses `fetch:template` to pull a skeleton repository containing configuration files, including a `.gitlab-ci.yml`. We pass parameters collected in the template form (like cloud account IDs, region, etc.) to the `fetch:template` action's `values` input, expecting them to be substituted into the skeleton files via Cookiecutter.
 
**Problem Details:**
 
*   **Expected Behavior:** When the template runs, the `.gitlab-ci.yml` file fetched from the source repository should be processed by the templating engine (Cookiecutter). Any instance of `{{ cookiecutter.VAR_NAME }}` within that file should be replaced with the corresponding value passed in the `fetch:template` step's `values`.
*   **Actual Behavior:** The `.gitlab-ci.yml` file is fetched and published to the new repository, but the `{{ cookiecutter.VAR_NAME }}` placeholders remain unsubstituted. The literal strings appear in the file.
 
**Relevant Configuration:**
 
1.  **`template.yaml` (Relevant Step):**
    ```yaml
    steps:
      - id: template
        name: Fetch Skeleton + Template
        action: fetch:template
        input:
          url: [internal-gitlab-url]/[source-repo-path] # Source Repo on internal GitLab
          # Note: copyWithoutTemplating section is *absent* or does *not* list .gitlab-ci.yml
          values:
            component_id: ${{ parameters.component_id }}
            description: ${{ parameters.description }}
            destination: ${{ parameters.repoUrl | parseRepoUrl }}
            owner: ${{ parameters.owner }}
            # Parameters passed to Cookiecutter (Using generic prefixes)
            VAR_PREFIX_WORK_GROUP: ${{ parameters.var_prefix_work_group }}
            VAR_PREFIX_ACCOUNT_DEV: ${{ parameters.var_prefix_account_dev }}
            VAR_PREFIX_ACCOUNT_TEST: ${{ parameters.var_prefix_account_test }}
            VAR_PREFIX_ACCOUNT_PROD: ${{ parameters.var_prefix_account_prod }}
            VAR_PREFIX_GITLAB_RUNNER_ACCOUNT: ${{ parameters.var_prefix_gitlab_runner_account }}
            VAR_PREFIX_CLOUD_REGION: ${{ parameters.var_prefix_cloud_region }}
            VAR_PREFIX_BASE_DEPLOY_ROLE: ${{ parameters.var_prefix_base_deploy_role }}
        # ... subsequent steps (create-catalog-info, publish, register)
    ```
 
2.  **Source Repository `.gitlab-ci.yml` (Relevant Snippet):**
    ```yaml
    variables:
      # Using generic prefixes
      VAR_PREFIX_WORK_GROUP: '{{ cookiecutter.VAR_PREFIX_WORK_GROUP }}'
      VAR_PREFIX_ACCOUNT_DEV: '{{ cookiecutter.VAR_PREFIX_ACCOUNT_DEV }}'
      VAR_PREFIX_ACCOUNT_TEST: '{{ cookiecutter.VAR_PREFIX_ACCOUNT_TEST }}'
      VAR_PREFIX_ACCOUNT_PROD: '{{ cookiecutter.VAR_PREFIX_ACCOUNT_PROD }}'
      VAR_PREFIX_GITLAB_RUNNER_ACCOUNT: '{{ cookiecutter.VAR_PREFIX_GITLAB_RUNNER_ACCOUNT }}'
      VAR_PREFIX_CLOUD_REGION: '{{ cookiecutter.VAR_PREFIX_CLOUD_REGION }}'
      VAR_PREFIX_BASE_DEPLOY_ROLE: '{{ cookiecutter.VAR_PREFIX_BASE_DEPLOY_ROLE }}'
 
    include:
      - project: "${MY_CICD_TEMPLATES_PROJECT_ENV_VAR}" # Env var pointing to CI templates
        ref: "${MY_CICD_TEMPLATES_VERSION_ENV_VAR}"
        file:
          - '/cloud/infra-cloud-account.gitlab-ci.yml' # Generic path
    ```
 
**Troubleshooting Steps Taken:**
 
We've gone through the standard checks:
 
1.  Confirmed the syntax in the source `.gitlab-ci.yml` is `{{ cookiecutter.VAR_NAME }}`.
2.  Confirmed the variables are correctly passed in the `values` section of the `fetch:template` step.
3.  Confirmed **explicitly** that the `.gitlab-ci.yml` file is **not** listed under `copyWithoutTemplating` in the `fetch:template` step (the entire section was removed to ensure default processing).
4.  Confirmed the filename in the source repository is exactly `.gitlab-ci.yml`.
5.  Confirmed file encoding seems standard (UTF-8).
6.  Confirmed Cookiecutter does not need separate installation.
7.  Considered caching, but the behavior is consistent even after ensuring template updates.
8.  [Optional: Add results of the simple `test-vars.txt` test if you performed it].
 
**Question / Request for Comments:**
 
Given that the standard configuration seems correct, this leads me to wonder:
 
*   Is there a known condition, configuration nuance, or limitation related to `fetch:template` or specific file types (like `.gitlab-ci.yml`) that would prevent Cookiecutter substitution even when `copyWithoutTemplating` isn't used, especially when fetching from an internal GitLab instance?
*   Could this potentially indicate an underlying issue or bug in the scaffolder's templating process for this scenario?
 
I wanted to file this RFC to see if the community or maintainers have encountered similar behavior or have insights into why these variables might not be substituting as expected. Any guidance or suggestions for further debugging would be greatly appreciated!

 
Thanks for your time and consideration!
