### ISSUE TITLE
Feature: Add Infinispan as a Backend Cache Store Option

### ISSUE THREAD

**Issue by gustavolira** [backstage/backstage#29846]
### 📜 Issue Labels

- [x] Please familiarize yourself with the issue labels used in this project: [LABELS.md](https://github.com/backstage/backstage/blob/master/LABELS.md)

### 🔎 Search Terms

```plain
cache infinispan performance
```

### 🗃️ Project Area

Unknown

### 🔖 Need

Currently, Backstage offers several caching backends. Adding Infinispan provides users with another robust, distributed caching option, particularly beneficial for those already utilizing Infinispan within their infrastructure or seeking features like advanced clustering, persistence options, and cross-site replication capabilities offered by Infinispan.

### 📝 Proposal

Distributed caching is crucial for scaling Backstage backends, reducing load on underlying services (like the Catalog or external APIs), and improving overall performance. While Redis and Memcached are popular choices, Infinispan offers a compelling alternative, especially in environments leveraging JBoss/WildFly or Kubernetes/OpenShift where Infinispan operators provide seamless deployment and management.
This implementation follows the established pattern within Backstage's CacheManager (@backstage/backend-defaults) by:
Introducing a new infinispan configuration section under backend.cache.
Adding a store factory (createInfinispanStoreFactory) that utilizes the official [infinispan Node.js client](https://www.npmjs.com/package/infinispan) (Hot Rod protocol).
Supporting configuration options for connection (host, port), authentication (username, password, SASL mechanism), TLS, and default cache name.
Implementing the CacheService interface (get, set, delete) with proper handling for TTL (lifespan in Infinispan terms) and JSON serialization/deserialization.
Integrating with @backstage/backend-test-utils using testcontainers to allow integration testing against a real Infinispan instance.

Example Configuration (app-config.yaml):
```
backend:
  cache:
    store: infinispan
    # Optional: Default TTL for all cache entries
    # defaultTtl: 3600000 # 1 hour in milliseconds or use ISO 8601 format e.g., PT1H
    infinispan:
      # Required: Host and port of your Infinispan server
      host: localhost
      port: 11222 # Default Hot Rod port
      # Optional: Authentication credentials
      # username: admin
      # password: yourpassword
      # Optional: SASL mechanism (e.g., PLAIN, DIGEST-MD5, SCRAM-SHA-1)
      # saslMechanism: DIGEST-MD5
      # Optional: Specify a default cache name on the server
      # cacheName: backstage_cache
      # Optional: Enable TLS/SSL
      # tls:
      #   enabled: true
```
Benefits:
Provides an additional choice for a distributed, scalable backend cache.
Leverages the official Infinispan Node.js client.
Integrates smoothly with Backstage's existing cache configuration and testing infrastructure.
Offers a familiar option for organizations already using Infinispan.

### Have you read the Code of Conduct?

- [x] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit a PR?

Yes, and I have enough information to get started
