### ISSUE TITLE
techdocs: fails with 401 error when loading static assets

### ISSUE THREAD

**Issue by tdabasinskas** [backstage/backstage#29903]
### 📜 Issue Labels

- [x] Please familiarize yourself with the issue labels used in this project: [LABELS.md](https://github.com/backstage/backstage/blob/master/LABELS.md)

### 🔎 Search Terms

```plain
"techdocs doesn't load", "techdocs empty"
```

### 🗃️ Project Area

TechDocs

### 🔗 External Integration

N/A

### 📝 Description & Context

Trying to use TechDocs with a `local` published, I we cannot get it working. The documentation doesn't load, and looking into Developer Console, the following is visible:

`Failed to load resource: the server responded with a status of 401 (Unauthorized)`
`http://localhost:7007/api/techdocs/static/docs/default/system/system_name/assets/stylesheets/main.8608ea7d.min.css`

The only way to get is working is to set `backend.auth.dangerouslyDisableDefaultAuthPolicy: true`.

There's already a similar issue reported - #25608, but it's closed as solved, even there are some comments still reporting the issue.

### 👍 Expected Behavior

The TechDocs shouldn't require `backend.auth.dangerouslyDisableDefaultAuthPolicy: true` and be able to load the documentation with default configuration.

### 🥾 Reproduction steps

1. Configure TechDocs:

```yaml
techdocs:
  builder: 'local'
  generator:
    runIn: 'local'
  publisher:
    type: 'local'
```

2. Start Backstage and open the TechDocs page.
3. The document never loads and 401 is visible in the Developer Console.

### Have you read the Code of Conduct?

- [x] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, but I'm happy to collaborate on a PR with someone else

**Comment by tdabasinskas** [comment]
Hi @Rugvip,

Thanks for a quick reply. I don't have a repo, but I was able to easily reproduce it doing the following:

1. Create a new Backstage app:

```sh
npx @backstage/create-app@latest
```

2. Update the default `app-config.yaml` with the following:

```yaml
techdocs:
  generator:
    runIn: 'local'
catalog:
  locations:
    - type: file
      target: ../../catalog-info.yaml
```

3. Create `catalog-info.yaml` file:

```yaml
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: idp
  title: IDP
  description: Internal Developer Portal
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  owner: guest
```

4. Create new `mkdocs.yaml` file:

```yaml
site_name: IDP Documentation
site_description: Documentation for the Internal Developer Portal (IDP)
nav:
  - 'Guides':
    - 'Creating a Microservice': backend_microservice.md
plugins:
  - techdocs-core
```

5. Create new docs files with some content:

  - `docs/index.md`
  - `docs/backend_microservice.md`

6. Start the app:

```bash
yarn start
```

7. Navigate to the documentation. The documentation doesn't load and the following is visible in the Console:

<img width="1512" alt="Image" src="https://github.com/user-attachments/assets/bde650ec-a419-44fb-ac87-5ff17ead24cd" />


Hope that helps.
