### ISSUE TITLE
publish:gitlab action fails with timeout after successful push on GitLab Enterprise

### ISSUE THREAD

**Issue by Aluush** [backstage/backstage#29957]
### 📜 Issue Labels

- [x] Please familiarize yourself with the issue labels used in this project: [LABELS.md](https://github.com/backstage/backstage/blob/master/LABELS.md)

### 🔎 Search Terms

```plain
publish:gitlab timeout
GitLab Enterprise push success but action fails"
simple-get/index.js request timed out
backstage template publish gitlab enterprise
```

### 🗃️ Project Area

Software Templates

### 🔗 External Integration

GitLab

### 📝 Description & Context

I'm encountering an issue while generating a template using the publish:gitlab action.

When using our GitLab Enterprise instance, the repository is created successfully, and the code is pushed, but the action still fails with the following error:

![Image](https://github.com/user-attachments/assets/c7fb5137-cba2-4770-b049-a71c28f18d04)

Interestingly, everything works fine when using gitlab.com, so the problem seems specific to the Enterprise GitLab instance.
template.yaml:

```
apiVersion: scaffolder.backstage.io/v1beta3
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-template
kind: Template
metadata:
  name: Java-template
  title: Java Template
  description: An example template for the scaffolder that creates a simple Java service
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  owner: user:aliatattou
  type: service

  # These parameters are used to generate the input form in the frontend, and are
  # used to gather input data for the execution of the template.
  parameters:
    - title: Fill in some steps
      required:
        - name
      properties:
        name:
          title: Name
          type: string
          description: Unique name of the component
          ui:autofocus: true
          ui:options:
            rows: 5
    - title: Choose a location
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - gitlab.my.company.com
            requestUserCredentials:
              secretsKey: USER_OAUTH_TOKEN
  # These steps are executed in the scaffolder backend, using data that we gathered
  # via the parameters above.
  steps:
    # Each step executes an action, in this case one templates files into the working directory.
    - id: fetch-base
      name: Fetch Base
      action: fetch:cookiecutter
      input:
        url: ./content
        values:
          project_name: ${{ parameters.name }}
          repo_url: ${{parameters.repoUrl}}
          destination: ${{ parameters.repoUrl | parseRepoUrl }}

    # This step publishes the contents of the working directory to Gitlab.
    - id: publish
      name: Publish
      action: publish:gitlab
      continueOnError: true
      input:
        allowedHosts: ['gitlab.my.company.com' ]
        description: This is ${{ parameters.name }}
        repoUrl: ${{ parameters.repoUrl }}
        token: ${{ secrets.USER_OAUTH_TOKEN }}
        destination: ${{ parameters.repoUrl | parseRepoUrl }}
        signCommit: true
        gitCommitMessage: sk8s TG
        gitAuthorName: Ali Atattou
        gitAuthorEmail: ali.atattou@mycompany.com

    # The final step is to register our new component in the catalog.
    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps['publish'].output.repoContentsUrl }}
        catalogInfoPath: '/catalog-info.yaml'

  # Outputs are displayed to the user after a successful execution of the template.
  output:
    links:
      - title: Repository
        url: ${{ steps['publish'].output.remoteUrl }}
      - title: Open in catalog
        icon: catalog
        entityRef: ${{ steps['register'].output.entityRef }}
      - title: Download ZIP
        icon: download
        url: ${{ steps['publish'].output.remoteUrl }}/-/archive/master/${{ parameters.name }}-master.zip
```

app.config.yaml:

```
integrations:
  gitlab:
    - host: gitlab.my.company.com
      apiBaseUrl: https://gitlab.my.company.com/
      token: ${ENG_GITLAB_TOKEN}
      commitSigningKey: ${ENG_GITLAB_SIGNING_KEY}
```

### 👍 Expected Behavior

The action should complete successfully if the repository is created and the push has succeeded — even if there's a timeout error after pushing. At the very least, it should fail gracefully or provide better diagnostics.

### 📦 Reproduction Repo

none

### 🥾 Reproduction steps

Configure a software template using publish:gitlab

Use a GitLab Enterprise instance as the target

Run the template

Observe that the repo is created and code is pushed

Action still fails with a timeout

### Have you read the Code of Conduct?

- [x] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes, but I would like some more guidance
