### ISSUE TITLE
Feature: Allow SubGroups to be excluded from Gitlab discovery

### ISSUE THREAD

**Issue by nabadger** [backstage/backstage#29958]
### 📜 Issue Labels

- [x] Please familiarize yourself with the issue labels used in this project: [LABELS.md](https://github.com/backstage/backstage/blob/master/LABELS.md)

### 🔎 Search Terms

```plain
- gitlab group exclude
- gitlab repo exclude
```

### 🗃️ Project Area

Catalog

### 🔖 Need

We have a use-case whereby we would like to exclude entire sub-groups from the Gitlab discovery plugin.

For example, everything under `gitlab.com/mycompany/personal-dev/*` 

This would build on the functionality introduced by https://github.com/backstage/backstage/pull/25796

### 📝 Proposal

Building on the existing functionality, we could introduce an `excludeGroups` list like so:

```
  providers:
    gitlab:
      our_org_gitlab:
        host: gitlab.myorg.co.uk
        branch: main
        fallbackBranch: master
        excludeRepositories:
          - foo/bar
          - foo/qux
          - group/subgroup/repo
        excludeGroups
          - group/subgroup1
          - group/subgroup2
          - group/subgroup3/subgroup4
```

This would exclude any repos that are in the sub-group, or a descendent of the sub-group (any number of levels below)

### 🔄 Alternatives

Currently we are making use of `excludeRepositories` , but we could end up having to build a rather last list - plus new repos that are created do not automatically make it into this exclusion list.

### Have you read the Code of Conduct?

- [x] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit a PR?

Undecided
