### ISSUE TITLE
Getting GitHub Repositories queries timing out

### ISSUE THREAD

**Issue by robertsa1-els** [backstage/backstage#29967]
### 📜 Issue Labels

- [x] Please familiarize yourself with the issue labels used in this project: [LABELS.md](https://github.com/backstage/backstage/blob/master/LABELS.md)

### 🔎 Search Terms

```plain
github timeout
```

### 🗃️ Project Area

Catalog

### 🔗 External Integration

GitHub

### 📝 Description & Context

We are using the GitHub entity provider to search our large GitHub Orgs for repos to ingest.
However we are seeing Errors with 502's Timeouts in the logs.

```
Unknown error: {
    "data": null,
    "errors": [
        {
            "message": "Something went wrong while executing your query on 2025-05-14T08:24:17+00:00. This may be the result of a timeout, or it could be a GitHub bug. Please include `8CE1:<REDACTED>:68245326` when reporting this issue."
        }
    ]
}
```

I have spoken to GitHub Enterprise support and they are saying the the requests being made to GitHub [here](https://github.com/backstage/backstage/blob/d1600abab178d761d1ace85809bc080044640ad9/plugins/catalog-backend-module-github/src/lib/github.ts#L468-L482) are too large and are hitting the [10-second](https://docs.github.com/en/rest/overview/troubleshooting#timeouts) hard timeouts.

> Hi Adam,
>
> I have an update to share. Engineering Team concluded that it is a legitimate query and unfortunately there isn't much that can be done from our end to improve this.
> 
> With 50 repositories, fetching 100 repository topics, it's what causes execution time to exceed the 10-second > timeout limit. Requesting from Backstage to make this configurable so do reduce the query size, it's going to > help.
> 
> I apologize for not having a more satisfactory solution to this issue.
>  
> Kind regards,

Sadly the values for how many repos and topics to get is not configurable in the Backstage providers config.

Unfortunately I do not posses the typescript skills to be able to submit a PR to fix this myself.

### 👍 Expected Behavior

The values for number of repos and topics to request in each call should be configurable in the provider config.
e.g

```
      providers:
        github:
          myOrg:
            organization: my-org
            catalogPath: /catalog-info.yaml
            validateLocationsExist: true
            queryConfig:
              repositories: 20
              topics: 50
            schedule:
              frequency:
                hours: 6
              timeout:
                hours: 1
```

### Have you read the Code of Conduct?

- [x] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, I don't have time to work on this right now
