### ISSUE TITLE
The MSgraph module not work as official doc illustrate in backstage

### ISSUE THREAD

**Issue by leezhihui** [backstage/backstage#30017]
### 📜 Issue Labels

- [x] Please familiarize yourself with the issue labels used in this project: [LABELS.md](https://github.com/backstage/backstage/blob/master/LABELS.md)

### 🔎 Search Terms

```plain
transitive import user and group
```

### 🗃️ Project Area

Catalog

### 🔗 External Integration

Azure

### 📝 Description & Context

when use this to import nested/transitive users and groups, the log show read user and group ok, but the ui didnot show the data.
```
microsoftGraphOrg:
  providerId:
    group:
      path: /groups/{someRootGroup id}/transitiveMembers/microsoft.graph.group
    user:
      path: /groups/{someRootGroup id}/transitiveMembers/microsoft.graph.user
```

### 👍 Expected Behavior

the user and group are imported, and can shown on backstage UI catalog user and group

### 📦 Reproduction Repo

https://github.com/backstage/backstage/tree/v1.29.0

### 🥾 Reproduction steps

1 use backstage 1.29.0
2 install the MSgraph and import user and group as indicate on official document
3 it will show up the situation

### Have you read the Code of Conduct?

- [x] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

No, I don't have time to work on this right now
