### ISSUE TITLE
Scaffolder: unable to use secrets within 'each' step

### ISSUE THREAD

**Issue by dzemanov** [backstage/backstage#30107]
### 📜 Issue Labels

- [x] Please familiarize yourself with the issue labels used in this project: [LABELS.md](https://github.com/backstage/backstage/blob/master/LABELS.md)

### 🔎 Search Terms

```plain
scaffolder secrets templates area:scaffolder
```

### 🗃️ Project Area

Software Templates

### 🔗 External Integration

N/A

### 📝 Description & Context

We are unable to use secrets in software templates within 'each' step. When we used them as parameters, everything worked correctly. This is important for us, because we don't want to repeat the same action, only with different secrets, because this makes the template long and unmanageable.

I suggest we can add secrets to the context [here](https://github.com/backstage/backstage/blob/master/plugins/scaffolder-backend/src/scaffolder/tasks/NunjucksWorkflowRunner.ts#L317):
```
      const resolvedEach =
        step.each &&
        this.render(
          step.each,
          { ...context, secrets: task.secrets ?? {} },
          renderTemplate,
        );
```

### 👍 Expected Behavior

Scaffolder task can use secrets within 'each' step.

### 🥾 Reproduction steps

You can register this dummy template to reproduce the bug:

```
apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: test-iteration
  title: Test iteration
  description: Test iteration

spec:
  type: service
  parameters:
    - title: Information
      required: [token1, token2]
      properties:
        token1:
          title: Token1
          ui:field: Secret
          description: Token to be used with case1
        token2:
          title: Token2
          ui:field: Secret
          description: Token to be used with case2
  steps:
    - id: log-info
      name: Log info
      each:
        [
          { name: "Service1", token: "${{ secrets.token1 }}" },
          { name: "Service2", token: "${{ secrets.token2 }}" },
        ]
      action: debug:log
      input:
        message: "Using information for ${{ each.value.name }}: ${{ each.value.token }}!"
```

### Have you read the Code of Conduct?

- [x] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes, and I have enough information to get started
