### ISSUE TITLE
Scaffolder: add a new ui field type for annotations

### ISSUE THREAD

**Issue by 0xts** [backstage/backstage#30126]
### 📜 Issue Labels

- [x] Please familiarize yourself with the issue labels used in this project: [LABELS.md](https://github.com/backstage/backstage/blob/master/LABELS.md)

### 🔎 Search Terms

```plain
"add annotations scaffolder", "annotations scaffolder", "scaffolder"
```

### 🗃️ Project Area

Software Templates

### 🔖 Need

Although backstage does allow one to [add custom fields](https://backstage.io/docs/features/software-templates/writing-custom-field-extensions) for usage in scaffolding process and Software Templates as a whole, making different plugins work by adding different annotations to a software components' `catalog-info.yaml` is pretty frequent/common task, and having the ability to provide those annotations right when one's registering their software component -- as opposed to editing the `catalog-info.yaml` file after the fact -- makes it easier to just register a component and have all the different plugins and integrations connected to the software component work readily.

### 📝 Proposal

I propose that a new UI field be added that allows one to add annotations while registering a software component, to make it easier to add annotations while registering a software component instead of editing the `catalog-info.yaml` file after the fact. This would make all the backstage integrations work right after registration.

A new UI element (called `MultiKeyValue`, maybe) could be added that allows one to add annotations while registering their software component. With this change, one could update their registration template like so -

```yaml4
...
properties:
  ...
  annotations:
    name: annotations
    type: array
    default: [{key: 'pagerduty.com/service-id', value: ''}, {key: 'sonarqube.org/project-key', value: ''}]
    ui:field: MultiKeyValue
    ui:options:
      properties:
        description: Annotations to add to your entity
    ...
...
```
Once done, the registration screen could look something like this -

![Image](https://github.com/user-attachments/assets/5a4dc2d8-5ae9-4bf3-a798-7c83fd49e017)

The user will also be able to add additional annotations per their requirement. This will in effect, will check if the annotations exist, and if they do, it'll add them to the `catalo-info.yaml` file created for the software component.

### Have you read the Code of Conduct?

- [x] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit a PR?

Yes, and I have enough information to get started
