### ISSUE TITLE
Gitlab discovery does not discover templates

### ISSUE THREAD

**Issue by kentwongg** [backstage/backstage#30149]
### 📜 Issue Labels

- [x] Please familiarize yourself with the issue labels used in this project: [LABELS.md](https://github.com/backstage/backstage/blob/master/LABELS.md)

### 🔎 Search Terms

```plain
gitlab discovery template, gitlab discovery and templates, gitlab template backstage
```

### 🗃️ Project Area

Catalog

### 🔗 External Integration

GitLab

### 📝 Description & Context

I have a Backstage portal with a self-hosted Gitlab that has integration, authentication, and some discovery working.

Gitlab is connected to an AD. From within Backstage, I see groups from my gitlab, users from my gitlab, authenticate and log in to backstage via my gitlab, and catalog components (from catalog-info.yaml files) from my gitlab group projects appearing in my Backstage.

However, I am not seeing templates automatically register. I can manually import the template so I know they are well formed. I house these templates side by side with catalog-info.yaml files so I know they are in the right spot with permissions able to access the files.

### 👍 Expected Behavior

See templates auto discovered and appear registered in the "Create" menu.

### 🥾 Reproduction steps

Backstage version:  "1.39.0" 

$ yarn backstage-cli info
```
  @backstage/app-defaults                                          1.6.2
  @backstage/backend-app-api                                       1.2.3
  @backstage/backend-common                                        0.25.0
  @backstage/backend-defaults                                      0.10.0
  @backstage/backend-dev-utils                                     0.1.5
  @backstage/backend-openapi-utils                                 0.5.3
  @backstage/backend-plugin-api                                    1.3.0, 1.3.1
  @backstage/catalog-client                                        1.10.0, 1.9.1
  @backstage/catalog-model                                         1.7.3, 1.7.4
  @backstage/cli-common                                            0.1.15
  @backstage/cli-node                                              0.2.13
  @backstage/cli                                                   0.32.1
  @backstage/config-loader                                         1.10.1, 1.10.0
  @backstage/config                                                1.3.2
  @backstage/core-app-api                                          1.17.0
  @backstage/core-compat-api                                       0.4.2
  @backstage/core-components                                       0.17.2
  @backstage/core-plugin-api                                       1.10.7
  @backstage/e2e-test-utils                                        0.1.1
  @backstage/errors                                                1.2.7
  @backstage/eslint-plugin                                         0.1.10
  @backstage/frontend-app-api                                      0.11.2
  @backstage/frontend-defaults                                     0.2.2
  @backstage/frontend-plugin-api                                   0.10.2
  @backstage/frontend-test-utils                                   0.3.2
  @backstage/integration-aws-node                                  0.1.15, 0.1.16
  @backstage/integration-react                                     1.2.7
  @backstage/integration                                           1.16.3, 1.17.0
  @backstage/plugin-api-docs                                       0.12.7
  @backstage/plugin-app-backend                                    0.5.2
  @backstage/plugin-app-node                                       0.1.33
  @backstage/plugin-app                                            0.1.9
  @backstage/plugin-auth-backend-module-github-provider            0.3.3
  @backstage/plugin-auth-backend-module-gitlab-provider            0.3.3
  @backstage/plugin-auth-backend-module-guest-provider             0.2.8
  @backstage/plugin-auth-backend                                   0.25.0
  @backstage/plugin-auth-node                                      0.5.6, 0.6.2, 0.6.3
  @backstage/plugin-auth-react                                     0.1.15
  @backstage/plugin-bitbucket-cloud-common                         0.3.0
  @backstage/plugin-catalog-backend-module-github-org              0.3.10
  @backstage/plugin-catalog-backend-module-github                  0.9.0
  @backstage/plugin-catalog-backend-module-gitlab-org              0.2.9
  @backstage/plugin-catalog-backend-module-gitlab                  0.6.6
  @backstage/plugin-catalog-backend-module-logs                    0.1.10
  @backstage/plugin-catalog-backend-module-scaffolder-entity-model 0.2.8
  @backstage/plugin-catalog-backend                                2.0.0
  @backstage/plugin-catalog-common                                 1.1.4
  @backstage/plugin-catalog-graph                                  0.4.19
  @backstage/plugin-catalog-import                                 0.13.0
  @backstage/plugin-catalog-node                                   1.17.0
  @backstage/plugin-catalog-react                                  1.18.0
  @backstage/plugin-catalog                                        1.30.0
  @backstage/plugin-events-backend-module-gitlab                   0.3.1
  @backstage/plugin-events-backend                                 0.5.2
  @backstage/plugin-events-node                                    0.4.11
  @backstage/plugin-org                                            0.6.39
  @backstage/plugin-permission-backend-module-allow-all-policy     0.2.8
  @backstage/plugin-permission-backend                             0.7.0
  @backstage/plugin-permission-common                              0.8.4, 0.9.0
  @backstage/plugin-permission-node                                0.10.0, 0.9.1
  @backstage/plugin-permission-react                               0.4.34
  @backstage/plugin-proxy-backend                                  0.6.2
  @backstage/plugin-proxy-node                                     0.1.4
  @backstage/plugin-scaffolder-backend-module-azure                0.2.9
  @backstage/plugin-scaffolder-backend-module-bitbucket-cloud      0.2.9
  @backstage/plugin-scaffolder-backend-module-bitbucket-server     0.2.9
  @backstage/plugin-scaffolder-backend-module-bitbucket            0.3.10
  @backstage/plugin-scaffolder-backend-module-gerrit               0.2.9
  @backstage/plugin-scaffolder-backend-module-gitea                0.2.9
  @backstage/plugin-scaffolder-backend-module-github               0.7.1
  @backstage/plugin-scaffolder-backend-module-gitlab               0.9.1
  @backstage/plugin-scaffolder-backend                             1.33.0
  @backstage/plugin-scaffolder-common                              1.5.11
  @backstage/plugin-scaffolder-node                                0.8.2
  @backstage/plugin-scaffolder-react                               1.16.0
  @backstage/plugin-scaffolder                                     1.31.0
  @backstage/plugin-search-backend-module-catalog                  0.3.4
  @backstage/plugin-search-backend-module-pg                       0.5.44
  @backstage/plugin-search-backend-module-techdocs                 0.4.2
  @backstage/plugin-search-backend-node                            1.3.11
  @backstage/plugin-search-backend                                 2.0.2
  @backstage/plugin-search-common                                  1.2.18
  @backstage/plugin-search-react                                   1.9.0
  @backstage/plugin-search                                         1.4.26
  @backstage/plugin-signals-react                                  0.0.13
  @backstage/plugin-techdocs-backend                               2.0.2
  @backstage/plugin-techdocs-common                                0.1.0
  @backstage/plugin-techdocs-module-addons-contrib                 1.1.24
  @backstage/plugin-techdocs-node                                  1.13.3
  @backstage/plugin-techdocs-react                                 1.2.17
  @backstage/plugin-techdocs                                       1.12.6
  @backstage/plugin-user-settings-common                           0.0.1
  @backstage/plugin-user-settings                                  0.8.22
  @backstage/release-manifests                                     0.0.13
  @backstage/test-utils                                            1.7.8
  @backstage/theme                                                 0.6.6
  @backstage/types                                                 1.2.1
  @backstage/version-bridge                                        1.0.11
```

This is my provider config that sits inside app-config.yaml, it is under catalog.providers.gitlab. I have another provider that deals with other entity kinds. For now, I've set the rule on catalog.rule as the following to troubleshoot.
```
catalog:
  rules:
    - allow: [Component, System, API, Resource, Location, Template, Group, Domain]
```

```
      templateGroup:
        host: git.example.com
        orgEnabled: true
        group: mygroup/templates
        entityFilename: catalog-info.yaml
        relations: # Optional
          - INHERITED 
          - DESCENDANTS 
          - SHARED_FROM_GROUPS 
        groupPattern: '[\s\S]*' # Optional. Filters found groups based on provided pattern. Defaults to `[\s\S]*`, which means to not filter anything
        branch: main
        fallbackBranch: master 
        skipForkedRepos: false
        includeArchivedRepos: false
        projectPattern: '[\s\S]*'
        schedule:
          frequency: { minutes: 2 }
          timeout: { minutes: 1 }
        rules:
          - allow: [Template]
```

I've taken the demo project's template here https://github.com/backstage/demo/blob/master/demo-template/template/template.yaml and put it inside a group project, and it does not auto discover this. I can import it and register it manually but it does not auto discover. It will auto discover a catalog-info.yaml that exists in the same repo.

### Have you read the Code of Conduct?

- [x] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Undecided

**Comment by MihaiTabara** [comment]
Found in team's triaging this morning.

Is there a mismatch on the `entityFilename` that could cause this to not be picked up?
Unrelated, not sure if `templateGroup` -> `rules` -> `allow: [Template]` has any effect. The overall `catalog -> rules -> allow` is what defines the configuration.

**Comment by awanlin** [comment]
Just wanted to plus 1 what was mentioned above. This config - `entityFilename: catalog-info.yaml` - means only look for files with that filename. You explicitly mention importing the Demo site example Template which is `template.yaml` and that does not match what you have configured so won't be picked up.

**Comment by kentwongg** [comment]
I changed my config to almost match the backstage documentation. Maybe I have this setup incorrectly or in a way its not meant to be. My intention is to have three providers. I am seeing the not allowed kind in both locations under `groupa` and `groupb/templates` for both catalog items and template items


```
# APP-CONFIG.YAML
catalog:
  providers:
    gitlab:
      teamsGroup:
        host: git.example.com
        orgEnabled: true
        group: teams 
        relations: 
          - DESCENDANTS 
          - SHARED_FROM_GROUPS 
        groupPattern: '[\s\S]*' 
        schedule: 
          frequency: { minutes: 2 }
          timeout: { minutes: 3 }
        rules:
          - allow: [Component, System, API, Resource, Domain, User, Group, Location]

# APP-CONFIG.PRODUCTION.YAML
catalog:
  providers:
    gitlab:
      workGroup:
        host: git.example.com 
        branch: main 
        fallbackBranch: master
        skipForkedRepos: false 
        includeArchivedRepos: false
        group: groupb 
        entityFilename: catalog-info.yaml 
        projectPattern: '[\s\S]*'
        excludeRepos: []
        schedule: 
          frequency: { minutes: 2 }
          timeout: { minutes: 3 }
        rules:
          - allow: [Component, System, API, Resource, Domain]
      templateGroup:
        host: git.example.com 
        branch: main 
        fallbackBranch: master 
        skipForkedRepos: false 
        includeArchivedRepos: false 
        group: groupa/templates 
        entityFilename: template.yaml 
        projectPattern: '[\s\S]*' 
        excludeRepos: [] 
        schedule: 
          frequency: { minutes: 2 }
          timeout: { minutes: 3 }
        rules:
          - allow: [Template]
```
