### ISSUE TITLE
GitHub Discovery via Events: Entity with Old metadata.name Remains in Catalog After Update

### ISSUE THREAD

**Issue by 04kash** [backstage/backstage#30279]
### 📜 Issue Labels

- [x] Please familiarize yourself with the issue labels used in this project: [LABELS.md](https://github.com/backstage/backstage/blob/master/LABELS.md)

### 🔎 Search Terms

```plain
"github events"
```

### 🗃️ Project Area

Events System

### 🔗 External Integration

GitHub

### 📝 Description & Context

When using the events system in the `@backstage/plugin-catalog-backend-module-github` plugin, updating the `metadata.name` field in an existing entity’s `catalog-info.yaml` file results in the creation of a new entity in the catalog. However, the original entity with the old name is not automatically removed from the catalog. As a result, both the old and new entities remain registered.

### 👍 Expected Behavior

The older version of the entity should be deleted and only the newer version should remain.

### 🥾 Reproduction steps

1.  Install and Configure Github discovery by following the docs [here](https://backstage.io/docs/integrations/github/discovery)
2. Create a webhook for the github org you want to ingest `catalog-info.yaml` files from.
3. Install and configure `@backstage/plugin-events-backend-module-github`
4. Add the following to your app-config.yaml to use http endpoint for events:
   ```
   events:
      http:
        topics:
          - github
   ```
5. Add a `catalog-info.yaml` file with the following content to a repo in your Github Org:
    ```
      apiVersion: backstage.io/v1alpha1
      kind: Component
      metadata:
        name: example-smtp-1
        description: Our deer-friendly example ensures regular comfort for your pets
      spec:
        owner: team-a
        type: website
        lifecycle: experimental
    ```
6. Confirm that `example-smtp-1` exists in your catalog
7. Now change the `metadata.name` field of the same `catalog-info.yaml` file to `example-smtp-2`.
8. Observe that the catalog now has both the entities: `example-smtp-1` and `example-smtp-2`

### Have you read the Code of Conduct?

- [x] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes, but I would like some more guidance
