### ISSUE TITLE
user entity is undefined when using scaffolder via REST API with static tokens

### ISSUE THREAD

**Issue by evanshortiss** [backstage/backstage#30299]
### 📜 Issue Labels

- [x] Please familiarize yourself with the issue labels used in this project: [LABELS.md](https://github.com/backstage/backstage/blob/master/LABELS.md)

### 🔎 Search Terms

```plain
user.entity undefined 
scaffolder api user undefined
```

### 🗃️ Project Area

Software Templates

### 🔗 External Integration

N/A

### 📝 Description & Context

Variables such as `user.entity.metadata.name` are undefined when a software template is run using the `POST /v2/scaffolder/tasks` endpoint with a static access token. 

### 👍 Expected Behavior

Realistically, I'm not sure what the preferred approach should be to resolve this. Maybe the task fails due to the undefined variables and a descriptive error is returned? 

### 📦 Reproduction Repo

https://github.com/redhat-pe-workshop/rhdh-template-quarkus-simple/

### 🥾 Reproduction steps

1. Import the template in the linked repository (or any template using the user.entity reference)
2. Enable static access to the Backstage API
    ```yaml
    backend:
      auth:
        externalAccess:
          - type: static
            options:
              # use this as the bearer token
              token: foobarbaz
              subject: software-template-trigger
    ```
3. Trigger the template using a HTTP request to `POST api/scaffolder/v2/tasks`

The template will run, but user related metadata is undefined which leads to errors. This is unsurprising when you consider how the template is being run, but it's a rough edge that could perhaps be handled gracefully.

### Have you read the Code of Conduct?

- [x] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Undecided
