### ISSUE TITLE
Avoid allocating database connection pool for plugins that don’t use the database

### ISSUE THREAD

**Issue by emre** [backstage/backstage#30412]
### 📜 Issue Labels

- [x] Please familiarize yourself with the issue labels used in this project: [LABELS.md](https://github.com/backstage/backstage/blob/master/LABELS.md)

### 🔎 Search Terms

```plain
"avoid db connection in plugins if plugins do not use db", "pluginDivisionMode: schema causes unused database connections"
```

### 🗃️ Project Area

Unknown

### 🔗 External Integration

N/A

### 📝 Description & Context

Backstage allocates a database schema and connection pool for every plugin registered via createBackendPlugin, when pluginDivisionMode set to schema, even if the plugin doesn’t explicitly request or use the database service.

This behavior leads to:

- Unnecessary PostgreSQL connection usage

- Idle connection bloat, especially in environments with many plugins

- Confusion for users (plugins like proxy, app, or internal no-op plugins showing up in pg_stat_activity)

I am not sure, but it might be related to the current [databaseServiceFactory implementation calling databaseManager.forPlugin(pluginId)](https://github.com/backstage/backstage/blob/v1.36.1/packages/backend-defaults/src/entrypoints/database/databaseServiceFactory.ts#L56) unconditionally for all plugins.

### 👍 Expected Behavior

If the plugin do not interact with database, do not create a connection pool for it.

### 🥾 Reproduction steps

1. Install backstage
2.  Use a database config like this.
```
  # The production database configuration is stored in app-config.k8s.yaml
  database:
    client: pg
    pluginDivisionMode: 'schema'
    connection:
      host: ${POSTGRES_HOST}
      port: ${POSTGRES_PORT}
      user: ${POSTGRES_USER}
      password: ${POSTGRES_PASSWORD}
    knexConfig:
      pool:
        min: 3
        max: 5
```
3. Run backstage backend
4. Check postgresql for idle connections

```
Select pid, usename, application_name, backend_start, state_change, state from pg_stat_activity where state='idle';
```

5. You will see plugins do no interact with db have a pool of db connections objects idling in the background.

### Have you read the Code of Conduct?

- [x] I have read the [Code of Conduct](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

Yes, but I would like some more guidance

**Comment by stephenglass** [comment]
Yes!! I found the same results just this week while working on scaling our Backstage app. This a huge issue, especially if you have large amount of plugins, as the max database connections are quickly reached. In my case, I couldn't even scale my Backstage beyond 1 instance with the default Postgres 100 max connections limit. You can increase max connections but there are absolutely side effects of this including higher resource usage and costs.

If it's possible to only establish the connection pool only when `getClient()` is called then could maybe fix the issue.

And for a question, does this issue only affect database in `schema` division mode or `database` as well? I'd really like to see a fix for this issue because I find schema division mode more sensible but it would help understand possible mitigation stategies.

**Comment by stephenglass** [comment]
At first glance, it already seems the database manager only creates a Knex client when the `getClient()` method is called. However, I see the `auth` service has a dependency on the `database` service. This is used to create the database plugin key source (this executes by default if static keys haven't been defined in config). Of course, the `auth` service is a dependency for several other services such as `httpRouter` and `httpAuth` and further upstream. So at minimum, every backend plugin that uses the http router (which is probably most plugins?) are instantiating a database client with a connection pool to the db.

This issue also relates to: https://github.com/backstage/backstage/issues/19863
As mentioned by @benjdlambert adding default pool config for plugins to `min: 0, max: 1` could help (same with `idleTimeoutMillis` too). Theoretically with pool min set to 0 there shouldn't be any idle connections (longer lived than `idleTimeoutMillis`) but even with this the behavior can be sort of weird and needs some more time to investigate.

**Comment by emre** [comment]
Thanks for the tip! I had actually tried using min: 0, max: 1, but since the default idle timeout on my end was 60 seconds, I assumed it wasn’t working. As a workaround, I’m now explicitly setting idleTimeoutMillis to a low value for each plugin that isn’t connected to the DB.

I’ve already noticed a drop in open connections, but honestly, this still feels like a bit of a hack.

**Comment by awanlin** [comment]
As already noted: since Backstage went secure by default last year most backend plugins will get a database created for the auth keys.

We don't generally recommend using `pluginDivisionMode` if you don't have specific reason to, thus it not being the default. You loose out on being able to fine tune the Knex settings and the [underlying tarn.js settings](https://github.com/Vincit/tarn.js) as everything is in a single database. 

@stephenglass, I'm curious to understand why you feel "schema division mode more sensible"?

**Comment by freben** [comment]
Also feel free to configure a static key store to get rid of the auth service behavior.

https://github.com/backstage/backstage/blob/9f67ede0651a187ed890df3de4caee941e078c95/packages/backend-defaults/config.d.ts#L171

That does force you to set it up the right way in every instance etc so it's more work (and less secure). But you can. We just don't recommend it.

There's still other services that might use the database besides the auth service - like the scheduler. So you're not entirely in the clear even if you do that, but it's a majority case at least.

**Comment by stephenglass** [comment]
> As already noted: since Backstage went secure by default last year most backend plugins will get a database created for the auth keys.
> 
> We don't generally recommend using `pluginDivisionMode` if you don't have specific reason to, thus it not being the default. You loose out on being able to fine tune the Knex settings and the [underlying tarn.js settings](https://github.com/Vincit/tarn.js) as everything is in a single database.
> 
> [@stephenglass](https://github.com/stephenglass), I'm curious to understand why you feel "schema division mode more sensible"?

I prefered schema division for the lower complexity in operational overhead. Having a single database is easier in my opinion for user management, backups, and restores. Also, I had originally assumed (before doing any investigation) that schema division would be less resource intensive since technically in this mode connections could be pooled for use in the whole database as opposed per plugin. However, this is not the current behavior and in either connection mode the connections are made per plugin and not per database. In that sense, it seems database and plugin division mode equally contribute to the server scoped max_connections parameter.

As for the ability to fine tune the Knex settings, could you expand on this @awanlin ? I'm currently using the `knexConfig` config while in schema mode and it seems to be working as expected?


```
  database:
    client: pg
    connection:
      host: ${PG_HOST}
      port: ${PG_PORT}
      user: ${PG_USER}
      password: ${PG_PASSWORD}
      database: ${PG_DATABASE}
    pluginDivisionMode: 'schema'
    knexConfig:
      pool:
        min: 0
        max: 4
        acquireTimeoutMillis: 30000
        createTimeoutMillis: 30000
        destroyTimeoutMillis: 5000
        idleTimeoutMillis: 10000
        reapIntervalMillis: 1000
        createRetryIntervalMillis: 200
        propagateCreateError: false
```
