### ISSUE TITLE
TechDocs doesn't serve static folder when using app-backend

### ISSUE THREAD

**Issue by taras** [backstage/backstage#3290]
When using TechDocs with app-backend, TechDocs writes generated output to `node_modules/@backstage/plugin-techdocs-backend/static/docs` directory instead of `packages/app/dist/static` which app-backend serves static content from. 

## Expected Behavior

TechDocs should use a directory that is being served or should serve the directory that it generates static content into.

## Current Behavior

when using `app-backend`, techdocs give a 404 because their content can not be found.

## Possible Solution

1. When app-backend is used, TechDocs could write to app's static directory
2. When app-backend is used, TechDocs could serve static content for `/techdocs/static/docs`

### Config

```
app:
  baseUrl: http://localhost:7000

backend:
  baseUrl: http://localhost:7000
  listen:
    port: 7000
  csp:
    connect-src: ["'self'", 'http:', 'https:']

techdocs:
  storageUrl: http://localhost:7000/api/techdocs/static/docs
  requestUrl: http://localhost:7000/api/techdocs
  generators:
    techdocs: local
```

1. Run the site locally using the above config
2. Add a documentation site
3. Access documentation site
4. You'll get a 404 when accessing the docs

## Your Environment

- NodeJS Version (v12): 12.19
- Operating System and Version (e.g. Ubuntu 14.04): 18.04
- Browser Information: All of them
