### ISSUE TITLE
[ServiceCatalog] Read only mode

### ISSUE THREAD

**Issue by Crevil** [backstage/backstage#3348]
We have created a GitHub scraping service that creates a `Location` resource based on all GitHub repositories in an organisation (closed source for now).
The scraper will detect if a repository contains documentation, API specifications etc. and set annotations on the generated `Component` resources accordingly while also generating eg `API` resources.

With this approach we don't need the write functionality of the service catalog, ie. `Create component`.
Currently it's still there, but on every restart of backstage we reset the catalog to the generated resources and the changes are lost.

## Feature Suggestion

Add a configuration option for making the catalog read-only.
When enabled all mutating functionality should be disabled, routes not registered, eg. `/create` and the backend should refuse write operations.

## Possible Implementation

Maybe just something in `app-config.yaml`:

```yaml
catalog:
  mode: readonly
```

In the components we should then have a simple way of detecting this to conditionally render them.

## Context

We use a GitOps approach in our infrastructure meaning that all resources for workloads are stored in Git.
We would like to keep this in the same pattern as this is what developers are used to.

Generated `Location`, `Component` and `API` resources:

```yaml
apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: lunar-components
spec:
  type: url
  targets:
    - https://github.com/lunarway/backstage-resources/blob/master/resources/components/service.component.yaml
    - https://github.com/lunarway/backstage-resources/blob/master/resources/components/service.api.yaml
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: service
  description: 'A description'
  annotations:
    backstage.io/managed-by-location: 'github:https://github.com/lunarway/service.git'
    jenkins.io/github-folder: 'lunarway/service/master'
    github.com/project-slug: 'lunarway/service'
spec:
  type: service
  lifecycle: dev
  owner: squad
  implementsApis:
    - service-http
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: service-http
  description: API for service.
spec:
  type: openapi
  lifecycle: dev
  owner: squad
  definition: |
    // omitted
```
