### ISSUE TITLE
SonarQube Plugin has same map keys as Jenkins Plugin

### ISSUE THREAD

**Issue by regicsolutions** [backstage/backstage#3519]
@dhenneke  i am getting an error when trying to add the SonarQube plugin along with the Jenkins plugin: 

`$ yarn build`
`yarn run v1.22.1`
`$ backstage-cli app:build`
`Error: Failed to read static configuration file: Map keys must be unique; "target" is repeated`
`error Command failed with exit code 1.`

**app-config.yaml:**

```
proxy:
   '/jenkins/api':
    target:
      $env: JENKINS_ENV
    changeOrigin: true
    headers:
      Authorization:
      env$: JENKINS_BASIC_AUTH_HEADER

   '/sonarqube':
    target: 
      $env: SONARQUBE_ENV
    allowedMethods: ['GET']
    headers:
      Authorization:
        $env: SONARQUBE_AUTH_HEADER
    
   sonarQube:
      baseUrl: 
        $env: SONARQUBE_BASE_ENV
```

**Comment by dhenneke** [comment]
The indentation of the file looks odd.

Can you try the following?

```yaml
proxy:
  '/jenkins/api':
    target:
      $env: JENKINS_ENV
    changeOrigin: true
    headers:
      Authorization:
        $env: JENKINS_BASIC_AUTH_HEADER

  '/sonarqube':
    target: 
      $env: SONARQUBE_ENV
    allowedMethods: ['GET']
    headers:
      Authorization:
        $env: SONARQUBE_AUTH_HEADER
    
sonarQube:
  baseUrl: 
    $env: SONARQUBE_BASE_ENV
```
