### ISSUE TITLE
Support string interpolation in config files

### ISSUE THREAD

**Issue by dhenneke** [backstage/backstage#3528]
_This is based on a recent discussion in Discord: https://discord.com/channels/687207715902193673/687207715902193679/771756713337946162_

We often use the proxy backend with authorization headers:

```yaml
proxy:
  '/target':
    target: ...
    headers:
      Authorization:
        $env: TOKEN # with TOKEN="Bearer asdf…"
```

Plugins often add additional documentation to tell the users what the variables must include (ex: https://github.com/backstage/backstage/tree/master/plugins/sonarqube#getting-started).

It would be easier to have some kind of string interpolation functions that could work like this:

```yaml
proxy:
  '/target':
    target: ...
    headers:
      Authorization: "Bearer ${env:TOKEN}" # with TOKEN="asdf…"
```

## Possible Implementation

One suggestion for a possible syntax was this:
> [**freben** 30.10.2020](https://discord.com/channels/687207715902193673/687207715902193679/771758353181179944)
> `"${env:THE_TOKEN}"`
> `"${file:./data.pem}"`

I'm not aware of other tools or existing syntax for this behavior so I'm not sure if there is an approach that can be borrowed.

It would also be cool to do more complex things such as `Authorization: 'Basic "${BASE64("${env:USERNAME}:${env:PASSWORD}")"}'`, but I doubt that we want to support that.

## Context

Make it more fail-safe to configure a new plugin.

**Comment by freben** [comment]
Yes for sure!

There's minutiae like whether to use `{{ }}` or `${ }`, whether it's `env.PATH` (like in github workflows) or just `PATH` or `env:PATH`, etc - but the feature as such is definitely desired.

Maybe there is something to say about synchronising this with other places in the solution where substitution is used. The scaffolder uses cookicutter syntax a lot, even though it's not the only supported solution. Entity yaml files support substitutions as well, and maybe the same exact syntax should be supported there too. So there's a unification aspect to this ticket.

**Comment by Rugvip** [comment]
Yep!

Some options:

Classic bash, only for env vars:

```yaml
myConfigKey: Token ${MY_ENV_VAR}
```

Cookiecutter variable access

```yaml
myConfigKey: Token {{env.MY_ENV_VAR}}
```

Cookiecutter function call

```yaml
myConfigKey: Token {{env("MY_ENV_VAR")}}
```

Would say that these are ordered in both increasing power and complexity.

A possibility with the function call style would be to deprecate and replace the existing `$env`, `$file`, `$data` keys in favor of

```yaml
backend:
  https:
    cert: {{load("cert.pem")}}
    key: {{load("key.pem")}}

integrations:
  github:
    - token: {{data("secrets.json", "github.token")}}
```

The place to implement all of this would likely be to hook into the config loading process just like the secrets do in the `config-loader`.

**Comment by freben** [comment]
I'd still give a bump for the `env:PORT` and `text:./ca.pem` format (within `{{}}` or `${}`, doesn't matter) as a middle ground that doesn't go full functions but leaves room both for env and urls and paths as the "parameter".

**Comment by Rugvip** [comment]
@freben Yep, +1. The downside is that we don't get a clean way to pass parameters, but in case we really want to be able to mix in multiple pieces of data we can do that in the passed in string itself. Similar to how data works for catalog yamls with `my-file.yaml#myKey1.myKey2`.

Tbh I think `${}` is probably better, I suspect cookiecutter uses `{{}}` because that will generally lead to less escaping when templating files, as `${}` flavors are more popular in other templating engines and cookicutter wants to be able to template those as well without excessive escaping.

Initial stab at this could then be to support the following?

```yaml
backend:
  https:
    cert: ${file:cert.pem}
    key: ${file:key.pem}

proxy:
  '/target':
    target: ...
    headers:
      Authorization: Bearer ${env:MY_TOKEN}

integrations:
  github:
    - token: ${data:secrets.json#github.token}
```

Could definitely drop data if we feel that complicates things. Either way I'm thinking we implement all of the existing `$` keys that we want to keep, so that we'd be able to deprecate and maybe remove them in the future.

Still an open question though, with this added, is it best to get rid of `$env` etc?
