### ISSUE TITLE
Multiple entities incorrectly show to be registered from a sample catalog info YAML

### ISSUE THREAD

**Issue by adamdmharvey** [backstage/backstage#3581]
When launching Backstage using all of the out-of-the-box unmodified `Locations:` in the `app-config.yaml` which gives me sample entities, if I try to manually register a sample component which has the component name `backstage`, which is actually the same as one of the sample `websites` buried in the Location's YAML tree, the validation on the catalog import page somehow walks the tree of examples and shows me all of them asking that I confirm them.

## Expected Behavior

I inadvertently added a component name for a component that was already in my SqlLite database and had been loaded from the examples loaded off `Locations`. I suppose I expect it should have warned me it already existed as part of the confirmation step.

## Current Behavior

Instead, it shows me a list of entities it will load, none of which were in my YAML file but seem to have been loaded either raw out of `Locations:` or maybe being displayed out of the database?

![image](https://user-images.githubusercontent.com/33203301/101214788-9a59fa80-364a-11eb-940d-b974713ffaa9.png)

## Steps to Reproduce

1. Load latest code from `master` branch
2. Define a custom `catalog-info.yaml` and put it in a repo like this:
    ```yaml
    apiVersion: backstage.io/v1alpha1
    kind: Component
    metadata:
      name: backstage
      description: A dupe to cause a bug?
    spec:
      type: service
      lifecycle: production
      owner: guest
    ```
3. Click register component, enter the URL, and click next
4. The confirmation screen shows you a bunch of components loaded from the `Locations` list

## Context

I was trying to register my sample PoC backstage to reflect itself, not knowing the sample data already logged a component named Backstage in the locations.

## Your Environment

- NodeJS Version (v12): v12.16.2
- Operating System and Version (e.g. Ubuntu 14.04): Windows 10 1901 WSL2 Ubuntu 18.04
- Browser Information: Microsoft Edge (Chrome engine)
