### ISSUE TITLE
Static location for processing a github-enterprise github-org not processed

### ISSUE THREAD

**Issue by O5ten** [backstage/backstage#3648]
When using githubOrg-processor to process github-org type locations from the static `catalog.locations[]` the type github-org is not being processed properly. 

## app-config.yaml
```yaml
catalog:
  locations:
  - type: github-org
    target: https://ghe.company.com/orgs/My-Organization
```

Also make sure you have the fix from https://github.com/backstage/backstage/pull/3647 to be able to target the for ingestion GHE at all. 

It works when ingested as a Location component however with YAML such as this one. 

```yaml
apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: org-data
spec:
  type: github-org
  targets:
    - https://ghe.some-company.com/My-Organization
```

## Expected Behavior

```
2020-12-09T11:38:20.824Z catalog info Reading GitHub users and groups
2020-12-09T11:38:22.182Z catalog info Read 244 entities from location url:https://ghe.some.company.com/My-Organization/backstage-config/blob/master/github-org-location.yml in 1.5s
```

## Current Behavior

Silence from the logs, println debugging from the GitHubOrgProcessor confirms that the static-location of type github-org never passes through that class. 

## Possible Solution

Perhaps static locations are checking for github.com in the url to pass it on to the GitHubOrgReader or something. 

## Steps to Reproduce

Add the config above and target a real github enterprise instance

## Context

It stops me from mirroring my users and teams from my GHE into backstage.

**Comment by benjdlambert** [comment]
Is this now fixed with your recent change @O5ten

**Comment by O5ten** [comment]
No, it is not. My static locations are not being processed properly. But that's fine with me, because the ones i add through existing components are. That's why i only created an issue and didn't look to resolve it myself. :)

**Comment by benjdlambert** [comment]
Hmm, ok. Think we need to investigate this a little further to see what's happening.

**Comment by freben** [comment]
Attempting to reproduce with public github for starters.

```yaml
# app-config.yaml
catalog:
  locations:
    - type: github-org
      target: https://github.com/spotify
  processors:
    githubOrg:
      providers:
        - target: https://github.com
          token: fffffffffffffffffffffffffff
```

Loads the org fine. Now trying as a Location entity:

```yaml
# location.yaml
apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: org-data
spec:
  type: github-org
  targets:
    - https://github.com/spotify

# app-config.yaml
catalog:
  locations:
    - type: file
      target: /path/to/location.yaml
  processors:
    githubOrg:
      providers:
        - target: https://github.com
          token: fffffffffffffffffffffffffff
```

This also works fine.

**Comment by freben** [comment]
Now tried the same but substituting the github targets for our GHE instance. Also works fine.

I'm on latest master.

Hmmm, can't reproduce it, it seems. If you check the configurations in the comment above, do you see anything that differs from yours?

**Comment by adamdmharvey** [comment]
I'll add in, at commit d7bb7bf39bbe1f14f6a822ae98d24f90db25da33 I too have loading a GHE org via a location value working well 👍 in my `app-config.local.yaml` against my local GHE :octocat: instance:

```yaml
  locations:
    - type: github-org
      target: https://github.myGHEinstance.com/my-favorite-org
```
