### ISSUE TITLE
feat: ability to subscribe to an API

### ISSUE THREAD

**Issue by n2ygk** [backstage/backstage#3656]
A mechanism to subscribe to an API via the API catalog would be really useful.

## Feature Suggestion

On the API page tile for a given API, add a button to subscribe to the API. For instance, request a new OAuth2 client_id/secret or an API key.

## Possible Implementation

Would need to minimally add some metadata to the API doc along with a plugin(?) to implement the request/approval workflow.

## Context

Trying to accomplish a developer portal where developers can subscribe to an API in order to use it. 

The Spotify API in the demo is an example which uses OAuth2 as documented in the OpenAPI spec: It wants a client_id and secret but the mechanism for obtaining those is elsewhere. Integrating that mechanism in the backstage portal would be really powerful.

**Comment by Fox32** [comment]
This would be a nice case for a plugin! We made the API entity customizable recently, so it's easy to show additional widgets.

**Comment by stefanalund** [comment]
+1 to what @Fox32 said -- I think this could be an excellent addition in the form of a plugin that is "connected" to the API entity page. More information about how a plugin can be connected up can be found here:

https://backstage.io/docs/plugins/integrating-plugin-into-service-catalog

**Comment by n2ygk** [comment]
@fox32 @stefanalund I'm thinking along these lines:
Name it plugin-oauth2-client-registration?

The plugin backend uses the [OAuth 2.0 Dynamic Client Registration Protocol, RFC 7591](https://tools.ietf.org/html/rfc7591) which is derived from the [OpenID Connect Dynamic Client Registration 1.0](https://openid.net/specs/openid-connect-registration-1_0.html) This should make it supported by a variety of commerical vendors ([PingFederate](https://docs.pingidentity.com/bundle/pingfederate-101/page/ook1564003025376.html), [Okta](https://developer.okta.com/docs/reference/api/oauth-clients/), [Auth0](https://auth0.com/docs/applications/dynamic-client-registration), ...) and FOSS implementations ([Gluu](https://gluu.org/docs/gluu-server/4.0/admin-guide/openid-connect/#dynamic-client-registration), [MITREid Connect](https://github.com/mitreid-connect/OpenID-Connect-Java-Spring-Server/wiki/Client-configuration#registered-client-service), ...)

It is configured with profiles that define specific requests like this example, perhaps using templating for user-entered fields like redirect URIs.
```yaml
clients:
  - client_name: example_client
    client_uri: https://example.com/example_client/about.html
    logo_uri: https://example.com/example_client/logo.png
    contacts:
      - mailto:support@example.com
    grant_types:
      - authorization_code
      - refresh_token
    redirect_uris:
      - https://www.getpostman.com/oauth2/callback
      - http://example.com/oauth2-redirect.html
      - http://localhost:8000/oauth2-redirect.html
    scope:
      - auth-columbia
      - demo-djt-sla-bronze
      - create
      - read
      - update
      - delete
      - openid
      - profile
      - email
      - https://api.columbia.edu/scope/group
```

The frontend presents the available client "profiles" for the user to select from perhaps with template values.
Upon successfully calling the backend API, the `client_id`, `client_secret`, etc. from the [client information response](https://tools.ietf.org/html/rfc7591#section-3.2.1) are presented.

Lots of details to be worked out, including:
- an authorization model so that some client credentials can be "automatically" issued while others may require an approval workflow....
- how the backend is authenticated/authorized to the OAuth2 server: with statically configured client credentials or passing along the end user's Access Token? 
- Maybe this can be done as a proxy.
- Maybe can leverage the [passportjs OIDC](http://www.passportjs.org/packages/openid-client/) integration.

I'd appreciate guidance.
