### ISSUE TITLE
Add parent/child relations to Component kind

### ISSUE THREAD

**Issue by tragiclifestories** [backstage/backstage#3726]
## Feature Suggestion

Add new parent/child relations to components. This will be used for modelling more complex ownership problems, for example for layers of monolithic applications. 

## Possible Implementation

As per https://github.com/backstage/backstage/issues/1964, this would mean adding new fields to the Component spec. Presumably this could be implemented in a very similar/identical way to the already-existing parent/child relations on groups. 

```yaml
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: majestic-monolith
  description: It's bigger and badder than ever
spec:
  type: service
  lifecycle: production
  owner: group:engineering
  children:
    - component:majestic-monolith-o11y # etc ... 
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: majestic-monolith-o11y
  description: Prometheus metrics collection and export
spec:
  type: service
  lifecycle: production
  owner: group:devops
  parent: component:majestic-monolith
```

There may be subtleties around what would be useful defaults (eg, should children inherit owners from parents unless specified?).

## Context

Example use case: we have a layer of our monolith that ships metrics for Prometheus. That layer belongs unambiguously to our team. But it's impossible to model as an API since it's a middleware that runs in literally every request. So we need some way to represent more 'abstract' parent/child relationships between components (and, ultimately, make them navigable in the UI).

This may possibly also be useful for APIs but I haven't found a need for it specifically.

PS: if this approach is acceptable (or there is a better idea out there in the hive-mind) then I'm happy to make time to contribute it.

**Comment by Fox32** [comment]
An alternativ to parent-child relationships could be [systems and domains](https://backstage.io/docs/features/software-catalog/system-model#ecosystem-modeling).

**Comment by tragiclifestories** [comment]
Interesting. I think I would still want at least a `parent` relation hanging off Component in that case to point to the system/domain.

**Comment by freben** [comment]
The relation (as in, the `relations` part of the entity API response) will for sure be modeled; that's the primary way we intend that these things should be consumed even though they may start their life in the `spec`.

We haven't gotten around to putting in the System and Domain kinds yet, but we will. The relation type used between them probably won't be a parent/child one, but rather something that rather conveys "is part of".

So for example (not set in stone, but for illustrative purposes):

```yaml
# input yaml file
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: playback-sdk
  description: Audio and video playback SDK
spec:
  type: library
  lifecycle: experimental
  owner: team-c
  system: playback
```

resulting in

```yaml
relations:
  - type: partOf
    target:
      kind: System
      namespace: default
      name: playback
kind: ...
```
