### ISSUE TITLE
Gitlab scaffolding not working

### ISSUE THREAD

**Issue by tsjnsn** [backstage/backstage#3755]
## Expected Behavior

When I configure the Gitlab settings in the scaffolding plugin, I expect to be able to target Gitlab for destination of scaffolding templates.

## Current Behavior

Scaffolding a project using a template that targets Gitlab fails at several points.
1. Utilizing the 'url' resource type results in the error:
2. If specifying 'gitlab' resource type (no longer supported, but hackable by setting the annotation on the template), the plugin fails with "no auth"
3. The config used by the Gitlab code is deprecated `catalog.processors.gitlabApi.privateToken`, and causes the backend to fail with error:
> Error: Using deprecated configuration for catalog.processors.gitlabApi, move to using integrations.gitlab instead

## Possible Solution

1. Update the Scaffolding to auto-detect gitlab resource type for `type: url`
2. Update the Scaffolding to use the non-deprecated config locations

## Steps to Reproduce

1. run the create-app
2. add gitlab config
3. try to create a template

```
integrations:
  gitlab:
    - host: gitlab.com
      token:
        $env: GITLAB_TOKEN
...
scaffolder:
  gitlab:
    api:
      baseUrl: https://gitlab.com
      token:
        $env: GITLAB_TOKEN
    visibility: internal # or 'internal' or 'private'
...
catalog:
  rules:
    - allow: [Component, API, Group, User, Template, Location]
  locations:
    - type: url
      target: https://gitlab.com/somegroup/somerepo/-/blob/master/template.yaml
      rules:
        - allow: [Template]
```

## Context

I'm trying to use Backstage with Gitlab.

## Your Environment

n/a

**Comment by adamdmharvey** [comment]
That error SHOULD mean in your app-config.yaml you still have:

```yaml
catalog:
  processors:
    gitLabApi:
```

And if you do, you should be able to comment it out/remove the `gitlabApi` section there - not sure if that helps remove some noise in your troubleshooting or not.
