### ISSUE TITLE
cost-insights: Allow the term "Project" to be customized

### ISSUE THREAD

**Issue by adamdmharvey** [backstage/backstage#3933]
## Feature Suggestion

For the most benefit, the cost insight plugin presentation of grouped costs would need to be specific _per cloud provider_ to drive the most understanding to the users.

It would be nice to be able to define by configuration the name of the cost grouping.  GCP uses Project, but AWS uses Account, and Azure uses Subscription, etc.

| Current | Proposed |
| --- | --- |
|  ![image](https://user-images.githubusercontent.com/33203301/103730363-b0900900-4fb0-11eb-835e-307c6d150ee3.png) |  ![image](https://user-images.githubusercontent.com/33203301/103730566-24caac80-4fb1-11eb-9940-8e030f1e5ee6.png) |

Descriptive:
>"Cost growth in Project example-project"
>"Cost growth in Account 12345"
>"Cost growth in Subscription 324838"

Alerts:
>"Investigate cost growth in Project example-project"
>"Investigate cost growth in Account 444322"
>"Investigate cost growth in Subscription 4393939"

## Possible Implementation

* Refactoring use of the term "project" to perhaps be slightly more generic, a la "costGrouping"
* `app-config.yaml` section under cost-insights such as:
    ```yaml
    cost-insights:
      grouping-term: project
      #grouping-term: account
      #grouping-term: subscription
    ```
* A helper method that anywhere the term is displayed, either a lower, proper case, or plural version of the relevant term is used

## Context

It's only recently occurred to me that "project" as it relates to the Cost Insights plugin, is the grouping mechanism used in GCP. (It's the one provider I'm least familiar with.)

It's referenced here:

https://github.com/backstage/backstage/blob/60f16c9cb57efdf9d1931517c82d6f5f7a2532f8/plugins/cost-insights/src/api/CostInsightsApi.ts#L67-L72

For AWS the rough equivalent is an "AWS Account".  In existing cost reports my group works with, we might have a dozen or more accounts, and we separately track the cost on each so it's a good parallel.  I believe Azure calls their equivalent a "subscription". For our purposes, each account has both an account number and we provide it a useful description, so it's always something like "DEV (11111111)" although in raw AWS they may only know it as 11111111.

Looking at some of the code, this could be customized by users, for sure - however, the term "project" at the moment is actually very pervasive, which I can appreciate why!  It's used for variables and methods and component names, but it's displayed in multiple places as well across multiple components. Any team who customizes the API to leverage their own API provider, would still have a lot of React changes necessary to refactor the term, enough such that (I'd suspect) applying future cost-insights code fixes for their custom fork would be very difficult.

It would potentially make sense to leave all "internal mechanism" referring to project, because clearly the team authoring it is most familiar with GCP, and then perhaps only the customization is on the UI side of things.

![image](https://user-images.githubusercontent.com/33203301/103729698-05328480-4faf-11eb-81e9-f872bfe87c3c.png)
![image](https://user-images.githubusercontent.com/33203301/103729748-1a0f1800-4faf-11eb-847e-b93abb813fd4.png)

## Additional Considerations

* Hybrid Cloud: An additional nuance, is I suppose it is more than possible some larger teams or companies may use multiple providers, and may connect their cost insights API to multiple providers.
* Products too? I gather GCP calls their things they sell "products", like compute or storage, etc. AWS calls them "Services". And Azure also calls them products. So products suits 2 of those 3 large ones, but would also be confusing to my teams, so a way to better define that would be great if an approach for the cost grouping was also pulled out.

**Comment by adamdmharvey** [comment]
As a note, there's a 3rd party vendor who does similar style reporting and they have some doco here:

https://success.cloudcheckr.com/article/00s3x310xa-cost-reporting

I don't know if they support only AWS or not, but they seem to have an ability to "define" your grouping.  Conceptually, my point above about doing that in YAML may be similar, and perhaps then even just the terminology used in the plugin itself could be made generic, and it's just the grouping that's changed "behind the scenes" via the API customization.

**Comment by timbonicus** [comment]
Great suggestion! We're aware of "project" being GCP-specific and filed a similar ticket #2644 with less detail and consideration than you've put in here. 😄  The same terminology complaint is true for GCP's "label" vs "tag" in AWS and Azure, though this is less prevalent in the UI.

I think your point of potential Hybrid Cloud is an important consideration; many companies operate in more than one cloud (including Spotify), or have a mix of on-prem and cloud resources. For that reason I think having the terminology data-driven rather than configuration-driven is the right solution.

## Possible implementation

The CostInsightsApi `getGroupProjects` method could be renamed to `getGroupBillingAccounts` and return `Promise<BillingAccount[]>` where BillingAccount is:

```
BillingAccount {
  provider: string,
  type: string,
  id: string,
  name: string,
}
```

The filter dropdown could have options grouped by provider, if multiple exist, and display the `name` rather than `id` for such useful descriptions as you mention. The "project growth" alert would use `BillingAccount.type` in place of hard-coded "project".

GCP actually calls their products "services" too, but we found the term confusingly overloaded with the notion of a _deployed service_ internally.

**Comment by adamdmharvey** [comment]
Ah sorry for the duplication; agree, we're on the same path there then.  I like your approach.  Could keep a `getGroupProjects()` perhaps with a deprecation WARN logger that then just calls the newer `getGroupBillingAccounts()` method.

So we might then be looking at something like the following you think?

```
costInsights:
  billingAccounts:
    - id: 123456789
      provider: aws          # aws | gcp | azure | other
      type: Account
      name: Engineering Dev
    - id: 123456789
      provider: azure        # aws | gcp | azure | other
      type: Subscription
      name: Sales App Prod
    - id: backend-uat
      provider: gcp        # aws | gcp | azure | other
      type: Project
      name: Backend Shared Functions UAT
    - id: experiment-esx
      provider: other      # aws | gcp | azure | other
      type: VMWare Farm
      name: Shared VMWare ESX farm for Experimental Projects
```
