### ISSUE TITLE
Ability to customize the "report an issue" link

### ISSUE THREAD

**Issue by adamdmharvey** [backstage/backstage#3962]
## Feature Suggestion

If a user hits a file not found, they're presented with an error page that lets them either a) go back or b) submit an issue. But the issue is submitted to the Backstage opensource GitHub project.

It would be nice for a Backstage integrator team to be able to define an issue reporting link, e.g. their own GitHub repository or Jira system or other ticketing system in use by their company or team, for submitting issues to the integrator team. They would be the ones to investigate if the instance of Backstage is misconfigured, or something else is going on.

![image](https://user-images.githubusercontent.com/33203301/103970909-50779f00-5137-11eb-9447-64a5d55095bb.png)

The file an issue link goes here: https://github.com/backstage/backstage/issues

## Possible Implementation

Provide an `app-config.yaml` customization field which is optional for this, sort of:

```yaml
app:
  title: My Company Software Catalog
  baseUrl: http://localhost:3000
  feedbackUrl: https://internal-jira.mycompany.net/projectx/create-new
```

The field could be optional, and the fall back would be the Backstage open source link.

## Context

Code is in the `@backstage/core` package here:

https://github.com/backstage/backstage/blob/722ad34067085ebedc190a77ded8a33ef614b4a6/packages/core/src/layout/ErrorPage/ErrorPage.tsx#L74-L80
