### ISSUE TITLE
SonarQube Plugin - Refused to execute inline script

### ISSUE THREAD

**Issue by regicsolutions** [backstage/backstage#3994]
Unable to retrieve a SonarQube card after registering an API with the following annotation:

```
  annotations:
    sonarqube.org/project-key: my-project-name
```

Card should be retrieved 

![2021-01-10_11-03-21](https://user-images.githubusercontent.com/6157895/104128370-31466080-5335-11eb-9d60-fc060c73e752.png)

## Your Environment

- NodeJS Version (v12):
- Windows 10
- Chrome/Edge

**Comment by adamdmharvey** [comment]
I don't have this plugin working myself, but check your `backend.csp` configuration sections - do they exist? If so, what are they  You're getting blocked by your browser with a security error and so it'll relate to one of those somehow.

If you search issues in this repo you'll see other people who had varying challenges, and what their results were (e.g., this one https://github.com/backstage/backstage/issues/3796).

**Comment by adamdmharvey** [comment]
I'd also say whatever you find, may be good to add to the plugin README in case you find something that helped!

**Comment by regicsolutions** [comment]
@adamdmharvey i have the default backend.csp in place:

```
  cors:
    origin: http://localhost:7000
    methods: [GET, POST, PUT, DELETE]
    credentials: true
  csp:
    connect-src: ["'self'", 'http:', 'https:']
```

**Comment by freben** [comment]
Hm. Yeah as it says it wants you to add `'unsafe-inline'` to the script sources. You can add a line like that to your config. Remember to add the other ones too, that the error message mentions.

So under the `connect-src` line, add something like

```yaml
script-src: ["'self'", "'unsafe-eval'", "'unsafe-inline'"]
```

**Comment by regicsolutions** [comment]
@freben i added this:

```
  csp:
    connect-src: ["'self'", 'http:', 'https:']
    script-src: ["'self'","'script-src-elem'", "'unsafe-eval'", "'unsafe-inline'"]
```
and now getting this:

```
Refused to load the script '<URL>' because it violates the following Content Security Policy directive: "script-src 'unsafe-eval' 'unsafe-inline'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.

code-quality:1 Refused to load the script 'http://localhost:7000/static/runtime.52630bfd.js' because it violates the following Content Security Policy directive: "script-src 'unsafe-eval' 'unsafe-inline'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.
```

**Comment by dhenneke** [comment]
Your first screenshot is strange, since it seems that you access the SonarQube User Interface through the backstage proxy which shouldn't (and wouldn't) work. Can you recheck your config against the [Getting Started guide](https://github.com/backstage/backstage/tree/master/plugins/sonarqube#getting-started)?

I suspect that you are missing the trailing `/api` in the proxy-configuration:
```yaml
proxy:
  '/sonarqube':
    target: https://your.sonarqube.instance.com/api # <-- here
    allowedMethods: ['GET']
    headers:
      Authorization:
        # Content: 'Basic base64("<api-key>:")' <-- note the trailing ':'
        # Example: Basic bXktYXBpLWtleTo=
        $env: SONARQUBE_AUTH_HEADER
```
