### ISSUE TITLE
String com diferente case in plugin org

### ISSUE THREAD

**Issue by gampeixoto** [backstage/backstage#4049]
## Expected Behavior
![image](https://user-images.githubusercontent.com/13747069/104404609-cc0f8c80-5539-11eb-80b7-95eba2e08815.png)

## Current Behavior
![image](https://user-images.githubusercontent.com/13747069/104404757-2d376000-553a-11eb-99b0-fc14695206b2.png)

## Possible Solution
https://github.com/backstage/backstage/blob/5032aa4bba5b3d3366066b1471f1b27ba3045b65/plugins/org/src/components/Cards/Group/MembersList/MembersListCard.tsx#L128

https://github.com/backstage/backstage/pull/4048
## Steps to Reproduce

1. Step 1 - Register a group with the following metadata 

```
apiVersion: backstage.io/v1alpha1

kind: Group
metadata:
  name: DEVOPS-RCHLO.cell-cac
  description: Cell cac 
spec:
  type: team
  profile:
    displayName: Cell - Cac
    email: infrastructure@example.com
    picture: https://pbs.twimg.com/profile_images/1295056629243817985/hI8hueZN.jpg
  children: [backstage]
```
2. Step 2 - Register a user with the following metadata
```
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: gabriel.peixoto
spec:
  profile:
    displayName: Gabriel Peixoto
    email: contato@myorg.com.br
    picture: https://exemplo.com.br/asdasda.jpg
  memberOf: [DEVOPS-RCHLO.cell-cac]
```

## Your Environment

- NodeJS Version (v12):
- Operating System and Version (e.g. Ubuntu 14.04):
- Browser Information:
