### ISSUE TITLE
FOSSA workflow in Pull Requests is flaky

### ISSUE THREAD

**Issue by OrkoHunter** [backstage/backstage#4240]
Looking at the [history of FOSSA workflow runs](https://github.com/backstage/backstage/actions?query=workflow%3AFOSSA), they sometimes fail due to server error.

[Example](https://github.com/backstage/backstage/runs/1760655356?check_suite_focus=true)
```
INFO Uploading analysis...
FATAL Error during upload: Error response from API: <html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

# Possible Solution

1. Few delayed retries when upload fails due to errors.

Previous discussion
https://github.com/backstage/backstage/pull/4077#issuecomment-764463876

**Comment by adamdmharvey** [comment]
There's something wrong with the FOSSA generation.  It creates the `.fossa.yml` file dyamically in the action. And you can see the output, but it generates 59 entries to scan. I looked at a few other open source repos, and they don't have nearly that many.

You can see in the action, but also try a fossa-cli init locally, our YAML ends up with lots of dupes like this:

```
- name: microsite
      type: npm
      target: microsite
      path: microsite
      options:
        strategy: yarn-list
    - name: microsite
      type: npm
      target: microsite
      path: microsite
      options:
        strategy: yarn-list
```

So I wonder if the gateway error is sort of us spamming/DDoS'ing whatever the gateway is (not sure if it's on the FOSSA side or coming out the GitHub Actions runner side).

Would suggest getting these dupes down, even if we have a mono repo, may help?
