### ISSUE TITLE
Onboarding Software Template: Introduce a Golden Path template pattern for new teams and engineers

### ISSUE THREAD

**Issue by regicsolutions** [backstage/backstage#4319]
## Feature Suggestion

To introduce a new common template spec type for onboarding use cases. Today, by default Backstage supports 3 common values for spec.type: service, website and library and i am suggesting we introduce a new type which is already an optional label:  `namespace` 

When the `namespace` is used as a spec.type for the Template kind, there would be a default rule to auto-populate the storePath to a common project or org space where onboarding requests are staged. 

**Use Case:**

Teams who do not have a namespace today typically have to go through an approval process that more than likely entails submitting an IAM request through another system. My goal was to solve this problem with Backstage by introducing an "Onboarding Template" where teams wouldn't have to go to another system, wait days to get approved, then wait for the infrastructure team to manually run there ansible scripts that actually get them onboarded but simply fill out an onboarding template that will land in a "common" project/org where those ansible scripts get staged, a post-hook is put in place to create a branch called "onboarding-approval" followed by a PR which if approved will be merged where the corresponding ansible scripts are fired to get the team onboarded.

Here is a diagram i put together that shows the end to end flow:

![onboard](https://user-images.githubusercontent.com/6157895/106364466-2f047000-62fd-11eb-93f0-026baf6603a2.png)

This idea was inspired by a great article i read on a [cookiecutter ansible kubernetes project](https://www.informaticsmatters.com/blog/2020/08/06/cookie-cutting-ansibe-kubernetes-projects.html)

**Comment by benjdlambert** [comment]
This is actually a super interesting use case for the scaffolder and it relates I think, very closely with our Golden Path templates. A new developer joins the company, and we want to give them a template which can scaffolder them a repo, and create them k8s namespaces, and gcp projects or whatever to get them setup and introduced to the dev stack and ecosystem. I know that this use case is not that, just had an interesting idea that maybe the golden path stuff could do something similar.

I'm also thinking however, that a lot of what you're trying to do here, could be solved with the new schema format for v2 scaffolder. The ticket is here: https://github.com/backstage/backstage/issues/3745 and although there's not so much in it it's based loosely off of this rfc #2771. 

We're moving away from the `spec.type` part in the `yaml`, and the categorisation will probably fall upon labels or something like that instead for the frontend. 

We're due to start the new schema stuff in the next week or so, and I'm thinking that there's a few ways to solve this feature request. We're going to start moving the steps into the template definition, so that each template you can configure what it will do and what actions it will run. Think something similar to github actions. You'll be able to configure the value that the `publisher` (or whatever we call it moving forward) has as the `storePath`.

Another solution is that we would by default provide a `storePath` component which would be a dropdown which could authenticate as the current user and see where this user is allowed to create repositories. once we've built this, I think it would be pretty easy to also make this configurable, and then you could choose to not even render anything on screen and autocompute the value from the template itself.

I think that the schema approach should work for you, so watch this space ⭐

**Comment by regicsolutions** [comment]
Thanks for the detailed reply! The drop down approach is 100% the way we should be going but with this use case where I need to be able to drive the destination for onboarding... there should be flexibility where I can lockdown the storePath to a specific
destination given I may have a staging project or org that has unique post-hooks in play that drive the approval of a PR. Just wanted to bring this up given we are in the middle of v2 😀

**Comment by regicsolutions** [comment]
@benjdlambert Are there plans to provide the ability to pull in different Kinds?

### Example:
_Following Template is used to create a namespace_ 

```
apiVersion: backstage.io/v1alpha1
kind: Template
metadata:
  name: kubernetes-onboarding
  title: Kubernetes Onboarding
  description: Creates a project namespace in Kubernetes
  tags:
    - onboarding
spec:
  owner: Team-A
  profile: 
    displayName: Team-A
    email: example@email.com
  system: PaaS
  lifecycle: experimental
  templater: cookiecutter
  type: namespace
  path: "."
  schema:
    required:
      - role_name
      - project_name
      - project_description
    properties:  
      role_name:
        title: Team Name
        type: string
        description: Team Name  
      project_name:
        title: Project Name
        type: string
        description: Project namespace name that best describes your project 
      project_description:
        title: Project Description
        type: string
        description: Short Description of your project
```
When this template is used by an engineer, a **Resource** Kind is registered to register the namespace:

```
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: new-team-namespace
  namespace: new-team-namespace
  description: Team A Namespace
  tags:
    - nodejs
  labels:
    channel: #team-a-slack-channel
  annotations:
    backstage.io/kubernetes-id: {{cookiecutter.project_name | jsonify}}
    backstage.io/kubernetes-label-selector: namespace=new-team-namespace
spec:
  type: namespace
  lifecycle: experimental
  owner: Team-A
  system:  System-A
```
Now i have another template to _create a react app_ that i want to map to that _new-team-namespace_ i just created by providing a drop down in this template of all available namespaces, is that in scope?
