### ISSUE TITLE
Scaffolder issues while creating document template

### ISSUE THREAD

**Issue by biancoda** [backstage/backstage#4330]
I cloned the project on the 01/31.
While testing testing the templates, I got error on different stages of the creation process.

Using the default document-template, I got an error on the "Run the templater" stage.

`error: Stage failed with error: ENOENT: no such file or directory, realpath '/tmp/b26c4b6a-b0f9-4391-91ee-dd93cc4add96/intermediate' {"id":"b26c4b6a-b0f9-4391-91ee-dd93cc4add96","stage":"Run the templater","timestamp":"2021-01-31T18:31:26.397Z"}`

With my own document-template, I got an error on the "Prepare the Skeleton" stage.

`error: Stage failed with error: EISDIR: illegal operation on a directory, unlink '/tmp/a683739f-864d-4b32-97fd-e15cea3c7849/checkout' {"id":"a683739f-864d-4b32-97fd-e15cea3c7849","stage":"Prepare the skeleton","timestamp":"2021-01-31T18:34:10.177Z"}`

## Expected Behavior

All the stages get completed successfully, the documents gets published and catalog entry gets created on Backstage

## Current Behavior

The process fails on the "Run the templater" and "Prepare the Skeleton"

## Possible Solution

Not solution, but workaround I went back to a previous clone of the project.
bf2dda31b HEAD@{2021-01-21 13:38:04 +0000}: pull origin master: Fast-forward

## Steps to Reproduce

Basically follow the getting started guide to run backstage locally.
https://github.com/backstage/backstage/blob/master/docs/getting-started/running-backstage-locally.md

1. git clone --depth 1 git@github.com:backstage/backstage.git
2. cd backstage
3. yarn install
4. yarn tsc
5. yarn build
6. cd /opt/backstage/packages/backend
7. yarn start
8. cd /opt/backstage
9. yarn start
10. Access backstage console
11. Go to "Create", select "Documentation Template"
12. Completed all the necessary information 
13. Create

## Context

At the moment, I'm not able to create any template based on tech-docs 
I was trying to get the latest version of the project

I'm using the standard configuration for the scaffolder and techdocs

```
techdocs:
  requestUrl: http://localhost:7000/api/techdocs
  storageUrl: http://localhost:7000/api/techdocs/static/docs
  builder: 'local' # Alternatives - 'external'
  generators:
    techdocs: 'docker' # Alternatives - 'local'
  publisher:
    type: 'local' # Alternatives - 'googleGcs' or 'awsS3'. Read documentation for using alternatives.

integrations:
  github:
    - host: github.com
      token:
        $env: GITHUB_TOKEN
		
  processors:
    githubOrg:
      providers:
        - target: https://github.com
          token:
            $env: GITHUB_TOKEN

scaffolder:
  github:
    token:
      $env: GITHUB_TOKEN
    visibility: public # or 'internal' or 'private'
```

I have tested the token and its working correctly.

## Your Environment

- NodeJS Version (v12): v14.15.3
- Operating System and Version (e.g. Ubuntu 14.04): Linux backstage-dev 5.4.0-1034-azure #35~18.04.1-Ubuntu SMP Thu Dec 10 09:13:52 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- Browser Information: Firefox 85.0 (64-bit)

**Comment by OrkoHunter** [comment]
cc'ing @jhaals @benjdlambert since it looks related to the new updates on using specified directories for checkout, intermediate, etc.

I tried on my local computer and things are working fine. We should also try on a new Linux instance.

**Comment by freben** [comment]
I'll try to reproduce when I get some time.

**Comment by biancoda** [comment]
I have create a new server and clone again the project with the same results.

- NodeJS Version (v12): v14.15.3
- Operating System and Version (e.g. Ubuntu 14.04): Linux backstage-dev 5.4.0-1034-azure #35~18.04.1-Ubuntu SMP Thu Dec 10 09:13:52 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- Browser Information: Firefox 85.0 (64-bit)
- yarn version: 1.22.10

While running the yarn install I got this error:

```
[5/5] Building fresh packages...
[11/19] ⠠ cypress
[2/19] ⠐ esbuild
[13/19] ⠐ bufferutil
[10/19] ⠐ keytar
warning Error running install script for optional dependency: "/opt/backstage/node_modules/keytar: Command failed.
Exit code: 1
Command: prebuild-install || node-gyp rebuild
Arguments:
Directory: /opt/backstage/node_modules/keytar
Output:
prebuild-install WARN install No prebuilt binaries found (target=14.15.4 runtime=node arch=x64 libc= platform=linux)
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@14.15.4 | linux | x64
gyp info spawn /usr/bin/python2
gyp info spawn args [
gyp info spawn args   '/opt/backstage/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/opt/backstage/node_modules/keytar/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/opt/backstage/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/root/.node-gyp/14.15.4/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/root/.node-gyp/14.15.4',
gyp info spawn args   '-Dnode_gyp_dir=/opt/backstage/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/root/.node-gyp/14.15.4/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/opt/backstage/node_modules/keytar',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
/bin/sh: 1: pkg-config: not found
gyp: Call to 'pkg-config --libs-only-l libsecret-1' returned exit status 127 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/opt/backstage/node_modules/node-gyp/lib/configure.js:345:16)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System Linux 5.4.0-1039-azure
gyp ERR! command \"/root/.nvm/versions/node/v14.15.4/bin/node\" \"/opt/backstage/node_modules/.bin/node-gyp\" \"rebuild\"
gyp ERR! cwd /opt/backstage/node_modules/keytar
Done in 842.29s.
```

To solve this issue:
 - Just to be sure, deleted the project/directory
 - installed pkg-config and libsecret-1-dev
 - Clone the project again

I tested a couple of the default templates. The default Documentation and React SSR templates failed on the  "Run the templater" stage.

`error: Stage failed with error: ENOENT: no such file or directory, realpath '/tmp/b26c4b6a-b0f9-4391-91ee-dd93cc4add96/intermediate' {"id":"b26c4b6a-b0f9-4391-91ee-dd93cc4add96","stage":"Run the templater","timestamp":"2021-01-31T18:31:26.397Z"}`

The templates that I created (a documentation and a kubernetes template ) failed on the "Prepare the Skeleton" stage.

`error: Stage failed with error: EISDIR: illegal operation on a directory, unlink '/tmp/a683739f-864d-4b32-97fd-e15cea3c7849/checkout' {"id":"a683739f-864d-4b32-97fd-e15cea3c7849","stage":"Prepare the skeleton","timestamp":"2021-01-31T18:34:10.177Z"}`

I have attached the kubernetes template and TemplatePage.tsx. 
Our documentation template require more steps to avoid having all the component information in the same page, so we modified the TemplatePage.tsx. 

[backstage.zip](https://github.com/backstage/backstage/files/5906321/backstage.zip)

**Comment by OrkoHunter** [comment]
Re-opening the issue as @biancoda reports that the problem is not solved. https://discord.com/channels/687207715902193673/714754240933003266/808687242533011507

My guess is that we should test with the template @biancoda has provided on a Linux environment.

**Comment by biancoda** [comment]
Originally, I set up my templates location as a file
```
  locations:
    # Runbook template
    - type: file
      target: /opt/<my_project>/backstage/templates/runbook-template/template.yaml
    # K8S template
    - type: file
      target: /opt/<my_project>/backstage/templates/k8s-template/template.yaml
```

Working with @jhaals, we found that there is possibly a bug when you define the location as a file.
I change it to use github as a source and all the templates started working again. So this could be used as a workaround.

```
    # K8S template
    - type: url
      target: https://<enterprise_github>/<my_project>/backstage/templates/k8s-template/template.yaml
    # Runbook template
    - type: url
      target: https://<enterprise_github>/<my_project>/backstage/templates/runbook-template/template.yaml
```
