### ISSUE TITLE
Location Entity in Azure DevOps

### ISSUE THREAD

**Issue by mfrinnstrom** [backstage/backstage#4351]
When trying to store a location entity in a repo in Azure DevOps to evaluate an organization structure I came across an issue with the handling of `targets`. The specification looks like the following:

```yaml
apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: test-organization
  description: A collection of users and groups used for evaluation
spec:
  targets:
    - ./department.yaml
```

Lets say the file is stored in the following location: 
`https://dev.azure.com/organization/project/_git/repository?path=%2Fcatalog-info.yaml`

## Expected Behavior

I expect the referenced files in `targets` to be handled correctly. That means that the `department.yaml` should be fetched using the following URL:
`https://dev.azure.com/organization/project/_git/repository?path=%2Fdepartment.yaml`

## Current Behavior

Right now the URL used when fetching that file becomes the following:
`https://dev.azure.com/organization/project/_git/department.yaml`

The logic for this is here as far as I can see: https://github.com/backstage/backstage/blob/bc18571b7a742863a770b2a54e785d6bbef7e184/plugins/catalog-backend/src/ingestion/processors/LocationEntityProcessor.ts#L22-L34

I guess this works for GitHub and perhaps others as well but for Azure DevOps this needs some extra handling.

## Possible Solution

I guess it would be good to have some central function to reference other files in a repo since it can be different depending on the provider. This would not only be useful for this use-case but I can see us using it in the future when we want to look up things in `package.json` or `build.gradle` files for example.

Maybe this already exist and I'm just not aware of it. I checked the AzureUrlReader but that doesn't seem to support referencing another file in the repo. 

I guess my question is if there already is some functionality like this and if not what would be the best way forward for adding that?
