### ISSUE TITLE
using the default frontend image in backstage/contrib/chart/backstage/values.yaml does not work

### ISSUE THREAD

**Issue by lironrisk** [backstage/backstage#4355]
when using the default image for the frontend in backstage/contrib/chart/backstage/values.yaml , I get the following errors:

![image](https://user-images.githubusercontent.com/55748498/106608142-b6a3e600-656c-11eb-8084-c7dc86326b68.png)

seems like for some reason it cannot find the static files, so the page does not load.

any advice will be appreciated.

**Comment by dtuite** [comment]
@lironrisk Those default images are quite a bit out of date. Backstage development has progressed quickly and unfortunately the Helm charts haven't kept up. 

For example, the charts refer to two images (frontend and backend) but the frontend can now be served from the backend so it's unnecessary (although it should still work).

You have a few options:

1. Build your own images. There is a [command provided](https://github.com/backstage/backstage/blob/master/package.json#L23) for building the backend docker image. There is also [a Dockerfile](https://github.com/backstage/backstage/blob/master/contrib/docker/frontend-with-nginx/Dockerfile) in `contrib` you can use to build a frontend image.
2. Use these up to date public images I have created (these are unofficial images): [frontend](https://hub.docker.com/repository/docker/roadiehq/backstage-sample-app-frontend) and [backend](https://hub.docker.com/repository/docker/roadiehq/backstage-sample-app-backend). I have successfully deployed these recently with the helm charts you are using. Sample values at the bottom.
3. If you just want to get started with Backstage on Kubernetes, you could try [this guide](https://roadie.io/blog/backstage-service-catalog-kubernetes/).

Hopefully that helps in some way. I will close this ticket but please get in touch if still stuck.

```yaml
frontend:
  image:
    repository: roadiehq/backstage-sample-app-frontend
    tag: v0.4.1-1217-g3bcad55de

backend:
  image:
    repository: roadiehq/backstage-sample-app-backend
    tag: v0.4.1-1217-g3bcad55de
```
