### ISSUE TITLE
configure OAuth2 provider scopes for login

### ISSUE THREAD

**Issue by n2ygk** [backstage/backstage#4430]
## Feature Suggestion

My OAuth2 AS requires certain scopes to enable user login via the Authorization Code flow. I would like to be able to configure those required scopes.

## Possible Implementation

I dunno, something like this:

```yaml
oauth2:
  development:
    clientId:
      $env: DEV_OAUTH2_CLIENT_ID
    clientSecret:
      $env: DEV_OAUTH2_CLIENT_SECRET
    authorizationUrl:
      $env: DEV_OAUTH2_AUTH_URL
    tokenUrl:
      $env: DEV_OAUTH2_TOKEN_URL
    scope:
      $env: DEV_OAUTH2_SCOPES
```

```diff
diff --git a/plugins/auth-backend/src/providers/oauth2/provider.ts b/plugins/auth-backend/src/providers/oauth2/provider.ts
index 04cb7670f..f9cfacf5c 100644
--- a/plugins/auth-backend/src/providers/oauth2/provider.ts
+++ b/plugins/auth-backend/src/providers/oauth2/provider.ts
@@ -44,6 +44,7 @@ type PrivateInfo = {
 export type OAuth2AuthProviderOptions = OAuthProviderOptions & {
   authorizationUrl: string;
   tokenUrl: string;
+  scope: string;
 };
 
 export class OAuth2AuthProvider implements OAuthHandlers {
@@ -58,6 +59,7 @@ export class OAuth2AuthProvider implements OAuthHandlers {
         authorizationURL: options.authorizationUrl,
         tokenURL: options.tokenUrl,
         passReqToCallback: false as true,
+       scope: options.scope,
       },
       (
         accessToken: any,
@@ -168,6 +170,7 @@ export const createOAuth2Provider: AuthProviderFactory = ({
     const callbackUrl = `${globalConfig.baseUrl}/${providerId}/handler/frame`;
     const authorizationUrl = envConfig.getString('authorizationUrl');
     const tokenUrl = envConfig.getString('tokenUrl');
+    const scope = envConfig.getString('scope');
 
     const provider = new OAuth2AuthProvider({
       clientId,
@@ -175,6 +178,7 @@ export const createOAuth2Provider: AuthProviderFactory = ({
       callbackUrl,
       authorizationUrl,
       tokenUrl,
+      scope,
     });
 
     return OAuthAdapter.fromConfig(globalConfig, provider, {
```

## Context

Enable OAuth2-based user login
