### ISSUE TITLE
links: Single link wraps oddly in the Links card

### ISSUE THREAD

**Issue by adamdmharvey** [backstage/backstage#4480]
Tried out links for the new entity Links card from https://github.com/backstage/backstage/pull/4279.

## Expected Behavior

A single link displays in the card.

## Current Behavior

Using the exact sample directly from the card's recommendation, resulted in what looks like a partially misaligned/formatted result.

| | |
| --- | --- |
|  ![image](https://user-images.githubusercontent.com/33203301/107598096-d41b2480-6bea-11eb-9c36-80ddc2532e7e.png) | ![image](https://user-images.githubusercontent.com/33203301/107598064-b51c9280-6bea-11eb-9bee-181a9395c4a6.png) |

## Possible Solution

I wonder if this is just some sort of CSS or width challenge for a single link, and it may look just fine for multiple links.

## Steps to Reproduce

1. Using the suggested metadata from the card, add it to an entity
2. View the entity in full screen browser

## Context

This seems to be related to the width.  At my full screen width of 1920x1080 , it shows as above.  If I make my window NOT full screen, and pull it to about 3/4 of the width of my screen, it DOES look correct.

![image](https://user-images.githubusercontent.com/33203301/107598376-8e129080-6beb-11eb-948c-9856db97ac2d.png)

![image](https://user-images.githubusercontent.com/33203301/107598423-a5517e00-6beb-11eb-8edc-7ef2d312e66f.png)

I also tried two different YAML values.

The raw straight from the card:

```yaml
links:
  - url: https://dashboard.example.com
    title: My Dashboard
    icon: dashboard
```

And a slightly tweaked one for the title with quotes:

```yaml
links:
  - url: https://dashboard.example.com
    title: 'My Dashboard'
    icon: dashboard
```

Both resulted in same behavior.

## Your Environment

- NodeJS Version (v12): Node v12
- Operating System and Version (e.g. Ubuntu 14.04): Windows 10 1909 WSL 2 Ubuntu 18.04
- Browser Information: Microsoft Edge (Chrome Engine v88)
