### ISSUE TITLE
[RFC] Support customization of intervals for cost-insights

### ISSUE THREAD

**Issue by Andrei-Predoiu** [backstage/backstage#4488]
**Status:** Open for comments

## Need

We need to customize the intervals that developers can chose in cost overview.

For example: We are a multi cloud organisation and use a 3rd party cost insights solution. We export `previous month total cost`, `current month day to day`, `current month so far` and `current month predicted total`. We also use euros.

There is only so much we can do in the cost-insight client implementation. It is impossible for use to map the above data to `Past 60 days`,`Past 6 Months`, `Q3 2020 - Q4 2020` etc

## Proposal

Create a new configuration option for cost-insights where intervals can be defined with the structure:
`<Interval Name>: <IntervalDevfinition>`

## Alternatives

Create a new method in the cost-insights api interface that returns the intervals that the ui should allow.

## Risks

Not sure at the moment.

**Comment by timbonicus** [comment]
I think this could make sense as configuration that replaces the default PeriodSelect options. 

```
costInsights:
  ...
  durations:
    P30D:
      name: Past 60 days
      default: true
    P7D:
      name: Past 2 weeks
```

The confusing part here is that the names appear to be typos since a repeated interval (R2) is implied. Maybe calling the config key `comparisonDurations` might help? Or maybe this is the wrong format.

@backstage/silver-lining Any thoughts?

**Comment by Andrei-Predoiu** [comment]
What about swapping name and interval in that case? Nevertheless, why is R2 implied?
```
costInsights:
  ...
  durations:
    name: Past 60 days
      interval: P30D
      default: true
    name: Past 2 weeks
      interval:P7D
```
