### ISSUE TITLE
Proxy doesn't forward POST body

### ISSUE THREAD

**Issue by Andrei-Predoiu** [backstage/backstage#4525]
I am using the proxy plugin to interact with our costs api and build a client for  cost-insights in backstage. I noticed that backstage was reaching the costs api but always returning 404.
Upon further investigation, it seems that the proxy is not forwarding the body of my POST Requests.

## Expected Behavior

When setting a post proxy, the body of post messages should be forwarded.

## Current Behavior

When setting a post proxy, the body of post messages is not forwarded.

## Possible Solution

I have just began to investigate the cause. Barring from some mistake in the proxy setup, It might be caused by some incompatible plugin interactions.

## Steps to Reproduce

1. Add a new proxy pointing to an endpoint you can verify, i pointed it back to backstage and created a debug route in my apis.:
 ``` '/my-proxy':
    target: http://localhost:7000/api/test-proxy
    allowedMethods: ['POST']
    headers:
      Content-Type: application/json
      x-api-key: <<API KEY>>
```

I created this route to test.
```
  apiRouter.use(`/test-proxy`, (req, res, next) => {
    res.end(`${JSON.stringify(req.method) }\n${ JSON.stringify(req.headers)}\n${ JSON.stringify(req.body)}`);
    return;
  })
```

2. Send a POST request to the proxy

## Your Environment

Local environment

- NodeJS 14.15 
- Operating System and Version: MacOs 10.15
- Browser Information: Chrome

**Comment by benjdlambert** [comment]
@Andrei-Predoiu and if you send the exact same CURL request or whatever to `/test-proxy` directly, you get the POST body?

**Comment by Andrei-Predoiu** [comment]
@benjdlambert 
Curl to `api/test-proxy` returns the body
Curl to `api/proxy/test-proxy` returns the header with the added `x-api-key` and `Content-Type` but the body is `undefined`

**Comment by dhenneke** [comment]
I tried to replicate the error with the following config:
```yaml
proxy:
  '/test':
    target: https://httpbin.org/anything
    allowedMethods: ['POST']
    headers:
      Content-Type: application/json
      x-api-key: <<API KEY>>
  '/test-proxy':
    target: http://localhost:7000/api/test-proxy
    allowedMethods: ['POST']
    headers:
      Content-Type: application/json
      x-api-key: <<API KEY>>
```

I get the following results for the first config: 
```bash
$ curl -d '{"key1":"value1", "key2":"value2"}' -H "Content-Type: application/json" -X POST http://localhost:7000/api/proxy/test
{
  "args": {}, 
  "data": "{\"key1\":\"value1\", \"key2\":\"value2\"}", 
  "files": {}, 
  "form": {}, 
  "headers": {
    "Accept": "*/*", 
    "Content-Length": "34", 
    "Content-Type": "application/json", 
    "Host": "httpbin.org", 
    "User-Agent": "curl/7.64.1", 
    "X-Amzn-Trace-Id": "Root=1-602a4943-7c400dac20a5ef637b6245a6", 
    "X-Api-Key": "<<API KEY>>"
  }, 
  "json": {
    "key1": "value1", 
    "key2": "value2"
  }, 
  "method": "POST", 
  "origin": "80.139.146.77", 
  "url": "https://httpbin.org/anything/api/proxy/test"
}
```

and for the second config:
```bash
$ curl -d '{"key1":"value1", "key2":"value2"}' -H "Content-Type: application/json" -X POST http://localhost:7000/api/proxy/test-proxy
"POST"
{"content-length":"34","content-type":"application/json","accept":"*/*","user-agent":"curl/7.64.1","host":"localhost:7000","x-api-key":"<<API KEY>>"}
```

Can you check if the `httpbin.org` config works for you? Do you have any special configurations in your backend?
