### ISSUE TITLE
Splunk On-Call plugin: Marketplace icon

### ISSUE THREAD

**Issue by ayshiff** [backstage/backstage#4550]
It seams that the Splunk On-Call plugin icon is too dark to display it correctly in the Marketplace.

## Expected Behavior

The Splunk On-Call icon must be correctly displayed and visible to the user.

## Current Behavior

<img width="331" alt="Capture d’écran 2021-02-16 à 16 33 02" src="https://user-images.githubusercontent.com/32459935/108085287-761c9000-7075-11eb-9b22-d8bec89a5c58.png">

## Possible Solution

We should provide a lighter version of the icon.

In `microsite/data/plugins/splunk-on-call.yaml`:

```yaml
---
title: Splunk On-Call
author: Spotify
authorUrl: https://github.com/spotify
category: Monitoring
description: Splunk On-Call offers a simple way to identify incidents and escalation policies.
documentation: https://github.com/backstage/backstage/tree/master/plugins/splunk-on-call
iconUrl: # Provide another icon
npmPackageName: '@backstage/plugin-splunk-on-call'
```

## Steps to Reproduce

Go to https://backstage.io/plugins and scroll down to the Splunk On-Call plugin.
