### ISSUE TITLE
Splunk On-Call plugin: REST endpoint

### ISSUE THREAD

**Issue by ayshiff** [backstage/backstage#4555]
As mentioned by @adamdmharvey [here](https://github.com/backstage/backstage/pull/4416#discussion_r573373010), we should use the Splunk On-Call recommended way (REST endpoint) to create, resolve and acknowledge incidents.

## Feature Suggestion

Implement the Splunk On-Call REST Endpoint.

## Possible Implementation

See the [REST Endpoint integration guide](https://help.victorops.com/knowledge-base/rest-endpoint-integration-guide/) for more information.

For the moment the plugin uses the api which is documented [here](https://portal.victorops.com/api-docs/).

Here are some of the points we need to do to implement this feature:

- Add the routing key and the integration url in the entity annotations:

    ```yaml
    annotations:
      splunk.com/integration-url': <SPLUNK_ON_CALL_URL_TO_NOTIFY>
      splunk.com/routing-key': <SPLUNK_ON_CALL_ROUTING_KEY>
    ```
- Updates the `acknowledgeIncident`, `resolveIncident` and `triggerAlarm` methods inside `plugins/splunk-on-call/src/api/client.ts` to use the integration url.
- Updates the README with the new guidelines to be followed.
- Update the `TriggerDialog` component accordingly ([glossary of fields table](https://help.victorops.com/knowledge-base/incident-fields-glossary/#glossary-of-fields))

## Context

PR which added Splunk On-Call plugin - #4416
