### ISSUE TITLE
Detection of component metadata based on code analysis

### ISSUE THREAD

**Issue by taras** [backstage/backstage#4582]
It would be helpful to have a generic way to detect information about components. 

## Context

I'm in the process of integrating techdocs-cli into our Jenkins pipeline. I want it to be very easy for developers to start using this functionality by having the platform automatically figure out how documentation should be built. We will provide an escape valve to allow developers to go off the beaten path but we want to provide convenient defaults for technologies in our ecosystem.

We're planning to have a Jenkins DLS job called `buildDocs` which will automatically select the mechanism based on information about the component. We'll modify the onboarding screen to explain how documentation will be built for each component, but I need to know what technologies are being used so I can determine how to build the documentation.

## Feature Request

It would be helpful if we had this information available inside of Backstage. I would imagine that the actual detection mechanism could be distributed as a library so it can be used in different environments.

## Possible Implementation

I don't know. This is why I created this issue. I tried to Google for a library that does the detection of technologies but I couldn't find anything. I know GitHub has information about code that's in the repo but it doesn't provide information about the root of that project. 

I would love your thoughts

**Comment by taras** [comment]
@Rugvip suggested that we could start with manually providing that metadata. I'm thinking that for now, I'll add some metadata to `catalog-info.yaml` where users can declare how they want to generate documentation. 

It'll have some metadata that'll look something like this, 
```yaml
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage
  description: |
    Backstage is an open-source developer portal that puts the developer experience first.
  links:
    - title: Website
      url: http://backstage.io
    - title: Documentation
      url: https://backstage.io/docs
    - title: Storybook
      url: https://backstage.io/storybook
    - title: Discord Chat
      url: https://discord.com/invite/EBHEGzX
  annotations:
    github.com/project-slug: backstage/backstage
    backstage.io/techdocs-ref: url:https://github.com/backstage/backstage
    lighthouse.com/website-url: https://backstage.io
    our-org.com/docs:
      - type: dartdoc
spec:
  type: library
  owner: CNCF
  lifecycle: experimental
```
