### ISSUE TITLE
github-discovery should only output repositories with relevant files

### ISSUE THREAD

**Issue by nirga** [backstage/backstage#4730]
Currently the way `github-discovery` is implemented is that it outputs all repositories that match a certain pattern, and leave it to a lower level to find the relevant catalog file within that repo. This causes a weird behavior if for example the following pattern is given:
```yaml
locations:
    - type: github-discovery
      target: https://github.com/backstage/*mkdocs/blob/master/catalog.yaml
```

And only some of the repos with `mkdocs` in their name contain a `catalog.yaml` file. All repos will be outputted, which will cause an error to be thrown for those repos where `catalog.yaml` file doesn't exist.

## Expected Behavior

Only relevant repos matching the **entire** filepattern should be outputted.

## Current Behavior

Errors are thrown when reading repositories that partially match the file pattern.

## Your Environment

- NodeJS Version (v12):
- Operating System and Version (e.g. Ubuntu 14.04):
- Browser Information:
