### ISSUE TITLE
Docs not autogenerating from avro schema 

### ISSUE THREAD

**Issue by ezvp4** [backstage/backstage#4812]
## Expected Behavior

Using the APIDoc plugin, I expect that I should be able to pass an asyncapi schema that references an .avsc file into my catalog-info.yaml and be able to see docs listing the fields in the schema.

## Current Behavior

The docs page loads, in the Payload box, I just see _Message Payload_, and in the "Example of payload" box, I just see two empty quotes: ""

## Possible Solution

I believe that the Avro schema is being found because I was getting an error when the reference path I was pointing to was incorrect. 

## Steps to Reproduce

Catalog-info.yaml
```
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: my-thing
  description: this is my project
spec:
  type: asyncapi
  lifecycle: experimental
  owner: my_team
  definition: |
    asyncapi: 2.0.0
    info:
      title: My Title
      version: '1.0.0'
    defaultContentType: application/json
    channels:
      my/channel:
        description: The topic on which cancellations can be consumed.
        publish:
          operationId: myOperation
          message:
            name: my thing
            title: my thing
            summary: etc etc
            schemaFormat: 'application/vnd.apache.avro+json;version=1.9.0'
            payload:
              $ref: 'path_to_schema_from_repo_root/cancel_schema.avsc#'
```

What cancel_schema.avsc looks like:
```
{
    "namespace": "my_namespace",
    "name": "myName",
    "type": "record",
    "doc": "blah blah",
    "fields": [
        {
            "name": "message_created_at",
            "type": "string",
            "default": ""
        },
        {
            "name": "my_other_field",
            "type": "string",
            "default": "",
            "doc": "my documentation."
        }
    ]
}
```

## Context

My theory was that my use of json pointer schema in the $ref was wrong, so I have tried a bunch of different varieties, like:
$ref: 'path_to_schema_from_repo_root/cancel_schema.avsc/#'
$ref: 'path_to_schema_from_repo_root/cancel_schema.avsc#/'
plus trying to reference fields in the json

I also tried referencing an absolute path to a schema registry or file uploaded to github but struggled with that due to how auth is set up at my company.

Thanks in advance for any help!

**Comment by benjdlambert** [comment]
@Fox32 what's the Avro support like for the APIDocs plugin?

**Comment by dhenneke** [comment]
Just a guess: We are using the [asyncapi-react](https://github.com/asyncapi/asyncapi-react) component but am not sure if it includes the avro features that the asyncapi-generator might support. It would be interesting to know if you get your schema working in https://asyncapi.github.io/asyncapi-react/ so it might be a problem of the Backstage integration.

We don't use `$ref`s in our schemas but request our teams to provide standalone files. Linking to other locations could always lead to authentication or CSP/CORS problems.

**Comment by freben** [comment]
I've also found that some systems use `$ref` as IDs and some as URLs - gets tricky when you need to explicitly pass in the contextual other schemas in the right way etc in order to help out the resolver.

**Comment by andrewthauer** [comment]
We are going to be looking closer at this exact use case soon so will probably stumble across this. I did some preliminary investigation into `asyncapi` + `avro` and am guessing you might need to pre-process the full `asyncapi` spec without refs before you import it. So probably an extra CI step or something.

**Comment by ezvp4** [comment]
Thanks for the responses, everyone.

I will definitely investigate the asyncapi-react component and see if avro is/isn't supported.

@andrewthauer, just to make sure I'm clear on what you're saying: you're saying it might be necessary to run a step to process the avro.avsc schema into an asyncapi specification and then pass that to backstage?

I would be happy to follow along with any planned work on this use case and potentially contribute as well as it's pretty important to my team.

**Comment by dhenneke** [comment]
I assume what @andrewthauer means is that they pre-process it and inline the avro schema into the asyncapi file. I tried your example on https://asyncapi.github.io/asyncapi-react/ and it worked:
```yaml
asyncapi: 2.0.0
info:
  title: My Title
  version: '1.0.0'
defaultContentType: application/json
channels:
  my/channel:
    description: The topic on which cancellations can be consumed.
    publish:
      operationId: myOperation
      message:
        name: my thing
        title: my thing
        summary: etc etc
        schemaFormat: 'application/vnd.apache.avro+json;version=1.9.0'
        payload: {
            "namespace": "my_namespace",
            "name": "myName",
            "type": "record",
            "doc": "blah blah",
            "fields": [
                {
                    "name": "message_created_at",
                    "type": "string",
                    "default": ""
                },
                {
                    "name": "my_other_field",
                    "type": "string",
                    "default": "",
                    "doc": "my documentation."
                }
            ]
          }
```

![image](https://user-images.githubusercontent.com/720821/110005658-05ce6980-7d19-11eb-9415-c318a8a0ac21.png)
