### ISSUE TITLE
[RFC] Validation of catalog definition via pipeline/github action (script)

### ISSUE THREAD

**Issue by jvilimek** [backstage/backstage#4834]
**Status:** Open for comments

## Need

**TL/DR**: looking for a way, how to validate backstage.yaml definition from a script.

We have partially generated and partially manually created definitions for backstage. We have backend services index, frontend components (spa, npm packages), manual entries.. all in git repositories. This is done as catalog-xxx/index.yaml of **kind=Location** with list of component definitions. Some of them are in the same (central) repository, many of them are references to respective service/spa/npm...repository. 
catalog-xxx/index.yaml is located in backstage definition and loaded at start + refreshed on a regular base:
```yaml
catalog:
  rules:
    - allow: [Component, API, Group, User, Template, Location]
  locations:
    # Backstage catalog index
    - type: url
      target: https://.../shared-repo/_git/backstage-catalog-components?path=%2Fcatalog-backend%2Findex.yaml
    - type: url
      target: https://.../shared-repo/_git/backstage-catalog-components?path=%2Fcatalog-frontend%2Findex.yaml
    - type: url
      target: https://.../shared-repo/_git/backstage-catalog-components?path=%2Fcatalog-manual-entries%2Findex.yaml
```

Example of one of the index file:
```
apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: backend-catalog-index
  description: A collection of all backend components
spec:
  type: url
  targets:
    - https://.../shared-repo/_git/backstage-catalog-components?path=%2Fcatalog-backend%2Fauto-generated%2FService01.yaml
    - https://.../service02-repo/_git/backend-service?path=%2Fbackstage.yaml #resource: Service02
```

Definition of Service01 is autogenerated, definition of Service02 is referenced to its repository. 

Now when the definition is changed manually by the team of Service02 and it is broken, the whole index import might be broken so we are looking for a way, how to prevent this..

Our need is to have a way (e.g. prepare some pipeline/action) to **validate during the pull request**, that the Service02 backstage.yaml config is valid.

## Proposal

Prepare a suggested implementation of Backstage including pipeline/github action templates to validat the backstage catalog YAML file definitions.

Can we e.g. call some backstage backend API to validate the url of current service? Should this be synchronous call? Asynchronous? Proposal is to build a working pipeline sample, full process how to develop/adjust backstage.yaml definitions in service repositories.

## Alternatives

Complete script solution without the call of the backstage API ...just read the definition, validate we have syntactically correct YAML, that we can read all locations, that the tags are in correct form, to validate just the schema...

## Enhancements

We can validate the schema, that it is OK. But what would be super uber cool is also having some semantic rules to check. E.g. that we have always sonarQube project definition for backend services (generates a warning), specific labels filled in, links (e.g. for DEV, STG, LIVE environments), that the name is unique or that the API components ends via "-api" etc.

## Risks

the API can be misused. We need to somehow authenticate/authorize the call. We need to have managed identity/API key passed so we can execute the API validation.
