### ISSUE TITLE
fetch:cookiecutter: take into account template-local cookiecutter.json

### ISSUE THREAD

**Issue by vinayvinay** [backstage/backstage#4920]
## Feature Suggestion

`cookiecutter` supports features that can be configured in `cookiecutter.json`, e.g. [copy without render](https://cookiecutter.readthedocs.io/en/1.7.2/advanced/copy_without_render.html).

The suggestion is that `fetch:cookiecutter` takes a template-local `cookiecutter.json` into account.

`values` passed to `fetch:cookiecutter` will override those in the template-local `cookiecutter.json`, e.g. `use_ci` passed in from the `scaffolder` (UI) will override the static `use_ci` configured in the template-local `cookiecutter.json`.

[Related discord chat](https://discord.com/channels/687207715902193673/687235481154617364/819523385745735710)

## Possible Implementation

In [`templater/cookiecutter.ts`](https://github.com/backstage/backstage/blob/b8f86caa7/plugins/scaffolder-backend/src/scaffolder/stages/templater/cookiecutter.ts#L51-L52), lookup `templateContentsDir/cookiecutter.json` and merge-in the auto-generated `templateDir/cookiecutter.json`.

## Context

I'd like to make use of `cookiecutter` templates already in use within our organisation (before scaffolder) and keep their current behaviour as far as possible.

**Comment by vinayvinay** [comment]
This conversation moved slightly ahead in discourse where @benjdlambert mentions:

> right now anything that's in the template folder is the template

That's a bit of a surprise as cookiecutter repos are typically structured as https://github.com/spotify/cookiecutter-golang is. I'd love to be able to clone that into the `workDir`, and finally publish the generated `{{cookiecutter.component_id}}` directory to a fresh repo. If this has been discussed before, please point me to the conversation so I can catch-up (a quick search didn't reveal anything).

**Comment by benjdlambert** [comment]
So https://github.com/spotify/cookiecutter-golang is a legacy template still, not in the new v2 format. You'll see that it actually has a `cookiecutter.json` in it too which is used. https://github.com/spotify/cookiecutter-golang/blob/master/cookiecutter.json. But unfortunately, this wont work for v2 as we build that file automatically, and there's no more `{{cookiecutter.component_Id}}` as `component_id` doesn't make sense anymore as you can template anything. So using v1 templates, or the legacy version I think would work, but we need to solve v2.


There's two approaches I can think to solve this, we can place the `cookiecutter.json` under the `./template` directory and just assume that if in the `template` directory there is a `cookiecutter` we should move that out of the skeleton and pass it to cookiecutter as config, or we can pass in the `cookiecutter.json` as options to publish action in v2 schema:

```yaml
  - id: fetch
     name: fetch
     action: fetch:cookiecutter
     input: 
       config:
         _copy_without_render: ["some/glob"]
```
 
Or something similar to this?

**Comment by vinayvinay** [comment]
I see. So for `v2` if we're staying with the decision that "`./template` contains only the template", then I'd vote for you suggestion to pass cookiecutter config as `config` to `fetch:cookiecutter`. That keeps it in sync with another design choice mentioned in (https://github.com/backstage/backstage/issues/4824#issuecomment-791045769, hooks as custom actions) where all config / hooks etc. will then be visible from the action config.

If there's more agreement, I'm happy to create a PR to keep moving this forward. In which case, let's head to the bike shed: do we want both `config` and `values`:

```
  - id: fetch
     name: fetch
     action: fetch:cookiecutter
     input: 
       config:
         _copy_without_render: ["some/glob"]
       values:
         name: '{{ parameters.name }}'
```

or, i'm guessing someone with little awareness of cookiecutter (e.g. myself) know that all these end up in a `cookiecutter.json`, shall we merge these and have:

```
  - id: fetch
     name: fetch
     action: fetch:cookiecutter
     input:
       config:  // (or explicitly call it cookiecutter.json) description: key-value pairs to be added to the generated cookiecutter.json
         name: '{{ parameters.name }}'
         _copy_without_render: ["some/glob"]
```

**Comment by benjdlambert** [comment]
Merging them all under config causes a backwards incompatible change, so i'd like not to do that if possible :) thoughts @freben  @Rugvip ?

**Comment by vinayvinay** [comment]
ah yes, fair point about backwards incompatible change.

**Comment by Rugvip** [comment]
@vinayvinay @benjdlambert I thinking that keeping config separate from the template content is bad because for example `_copy_without_render` is very coupled to the template contents. We're already setting values in the template definition though, so that point is a bit moot.

It seems like `_copy_without_render` is the only magic key that cookiecutter has atm, with the rest of the values just being used for the templating? I'd actually suggest the following:

```yaml
  - id: fetch
     name: fetch
     action: fetch:cookiecutter
     input: 
       copyWithoutRender: ["some/glob"]
       values:
         name: '{{ parameters.name }}'
```

Especially with #4869 I'd argue that this makes it even more discoverable and easy to use than if we send people over to the cookiecutter config docs. It ofc means we need to stay in sync with cookiecutter, but I'd also imagine there's not a lot going on there atm. It also lets us be a bit more explicit about which config options we forward and cookiecutter's way of doing things doesn't always fit well with a templating service from a security point of view.
