### ISSUE TITLE
Support multiple remote URLs in scaffolder TaskPage

### ISSUE THREAD

**Issue by tragiclifestories** [backstage/backstage#4955]
## Feature Suggestion

Support multiple onward links in the `TaskPage` component to handle cases where there are multiple subsequent actions.

## Possible Implementation

Add a further well-known annotation, `links`, with a type:

```ts
type Links {
  target: string; // ie, the href
  text: string; // the text to display
}
```

Template YAML would look like:

```yaml
spec:  
  output:
    links:
      - target: '{{ steps.publishNewRepo.output.remoteUrl }}'
        text: 'Repo'
      - target: '{{ steps.publishKubeConfig.output.remoteUrl }}'
        text: 'Kubernetes config PR'
```

## Context

At the moment, the `TaskPage` component which displays feedback from template repo runs supports two well-known `outputs`, `remoteUrl` and `entityRef`. These handle the most common cases; however, now that we support arbitrary numbers of actions in a scaffolder pipeline, we may have more than these two specific onward actions to deal with. EG, say you need to create a repo _and_ a PR to some other repo with config changes, the user is maybe going to want to visit both. (Also the text of `remoteURL` is hardcoded to "Repo", which may not be correct - I have a separate PR on this [here](https://github.com/backstage/backstage/pull/4921))

**Comment by freben** [comment]
So, a generalization of the user feedback mechanism, in a sense. Ping @benjdlambert 

Yeah this probably makes sense. I wonder if we should have this as just links, or if there's more that we want to do. At least a success text blob might make sense, right? Like informing the user about what has been done, where to go next, gotchas, who to contact about stuff ... I dunno, things like that, that are highly org specific but constitute valuable hand-holding.

**Comment by tragiclifestories** [comment]
If you'll forgive the hideous mockup (made by manually editing the DOM in dev tools 🙈 ) I guess you could have something like this? With configurable text all over the place.

![Screenshot 2021-03-15 at 11 02 58](https://user-images.githubusercontent.com/2285130/111143702-061efe00-857e-11eb-847c-ee82752ba2d8.png)

**Comment by benjdlambert** [comment]
Seems good, like the idea. Thinking though however we should follow the other `link` pattern that we have for `metadata.links` on entities?

```ts
interface Link {
  title: string;
  url: string;
}
```

And then we could make it backwards compatible using the presence of the `links` property.

```
  output:
    remoteUrl: '{{ steps.publish.output.remoteUrl }}'
    entityRef: '{{ steps.register.output.entityRef }}'
 ```

or 

```
  output:
    links:
      - title: PR
         url: '{{ steps.createPR.output.remoteUrl }}'
      - title: Entity
         url: '{{ steps.register.output.entityRef }}'
```

When the `links` property is there, loop over the returned URL's and create a button for each one with the title or something.

@Rugvip @jhaals too for visibility
