### ISSUE TITLE
Providide a mechanism to filter groups loaded by the githubOrg processor

### ISSUE THREAD

**Issue by punkle** [backstage/backstage#4977]
The githubOrg processor (aka GithubOrgReaderProcessor) can be configured to allow the teams from a github organization to be loaded as users and groups in backstage. This is powerful feature. In some cases, there might be additional teams in github that we are not interested in loading into backstage.

In this case, it would be great if we could provide an "allow" regex list or some other mechanism to load these groups.

## Feature Suggestion
One possible option is to add a new configuration option to the githubOrg processor called groupAllowLIst

```
processors:
    githubOrg:
      providers:
        - target: https://api.github.com
          apiBaseUrl: https://api.github.com
          groupAllowList: [ "^organization-.*$", "^team-.*$" ]
          token:
            $env: GITHUB_TOKEN
```

## Context
There are teams created by users in github that are not related to the main organization structure. e.g. a bots group
