### ISSUE TITLE
Kubernetes: AWS Ingress Controller readiness gates show up as errors on all pods. 

### ISSUE THREAD

**Issue by backjo** [backstage/backstage#5015]
## Expected Behavior
We currently use the AWS Load Balancer Controller to manage pod mappings to the AWS Application Load Balancer. As part of this setup, the AWS LB Controller manages a custom condition on our pods, which looks like:
```yaml
status:
  conditions:
    - lastProbeTime: null
      lastTransitionTime: null
      message: Target registration is in progress
      reason: Elb.RegistrationInProgress
      status: 'True'
      type: target-health.elbv2.k8s.aws/k8s-ssoproxy-ssoproxy-ff3a93a63d
```
This condition causes the Kubernetes plugin to report an error with the pods - though no actual error exists - this is expected behavior. 

The K8S plugin should not report custom conditions as errors by default.
## Current Behavior
The K8S plugin reports some custom conditions as errors by default.

**Comment by mclarke47** [comment]
I think this error mapper https://github.com/backstage/backstage/blob/master/plugins/kubernetes/src/error-detection/pods.ts#L23 needs a more robust implementation, it's very basic ATM.

**Comment by laurie-kepford** [comment]
I am having a similar issue.  Using LB controller 2.3
It seems that containers become unregistered, maybe because of a restart or a host gets terminated and the pod gets moved to the new host.
Result of the following command:

`kubectl get pod podname -o yaml -n namespace | grep -B7 'type: target-health'`

```
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: null
    message: Target registration is in progress
    reason: Elb.RegistrationInProgress
    status: "True"
    type: target-health.elbv2.k8s.aws/k8s-podname-f9dc5ec48e
```
The pod eventually registers but this status stays the same.
In another case, I manually added the container IP to the target group to bring the app back up. (this is a production system)

I have 200 applications on the system and I see this happening every 4 to 6 hours for different apps. If left alone most of them fix themselves after 5 or 10 minutes.

Even hours later it still says registration in progress.

My environment:
EKS - kubernetes version 1.19
Rancher - version 2.6.1
Namespace has label:
     labels:
       elbv2.k8s.aws/pod-readiness-gate-inject: enabled
 AWS LB controller 2.3
