### ISSUE TITLE
Catalog: Let a Group define its members (Users) in yaml

### ISSUE THREAD

**Issue by Peksa** [backstage/backstage#5072]
## Feature Suggestion

Let the catalog entity yaml-file of Kind `Group` contain a list of `Users` that belong to that group, instead of only the reverse (having the `User` define what `Groups` they are `memberOf`).

## Possible Implementation

```yaml
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: infrastructure
  description: The infra business unit
spec:
  type: business-unit
  profile:
    displayName: Infrastructure
    email: infrastructure@example.com
    picture: https://example.com/groups/bu-infrastructure.jpeg
  parent: ops
  children: [backstage, other]
  members: [jenny, george] # <---- suggestion

---

apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: jenny
spec:
  profile:
    displayName: Jenny Doe
    email: jenny-doe@example.com
    picture: https://example.com/staff/jenny-with-party-hat.jpeg
```

## Context

We have a good "source of truth" for ingesting `Users` into Backstage, but would like to hand-define groups/teams for owners of Components. This would allow us to hand-define `Groups` while still automatically ingesting `Users`.
