### ISSUE TITLE
Software template builtin action publish:azure provides wrong repo url

### ISSUE THREAD

**Issue by nadworny** [backstage/backstage#5119]
The `publish:azure` action  provides wrong output parameter of the published repo URL which leads to an error during `catalog:register` action

## Expected Behavior

A newly created component should be registered in the catalog.

## Current Behavior

Getting the following error during the register step.

```
2021-03-25T21:49:19.000Z InputError: No integration found for host https://xxx.visualstudio.com/test/_git/backstageexample
    at Object.handler (webpack-internal:///../../plugins/scaffolder-backend/src/scaffolder/actions/builtin/catalog/register.ts:90:17)
    at TaskWorker.runOneTask (webpack-internal:///../../plugins/scaffolder-backend/src/scaffolder/tasks/TaskWorker.ts:147:24)
    at async eval (webpack-internal:///../../plugins/scaffolder-backend/src/scaffolder/tasks/TaskWorker.ts:58:9)
```

## Possible Solution

The creation of the repoContentsUrl should consider the new Azure DevOps domain dev.azure.com. Currently, the legacy one (xxx.visualstudio.com) is being used despite providing the dev.azure.com as the host.

## Steps to Reproduce

Use the following template.yaml
```
apiVersion: backstage.io/v1beta2
kind: Template
metadata:
  name: pythonapi
  title: Create Python API
  description: scaffolder v1beta2 template
spec:
  type: service

  parameters:
    - title: Fill in needed information
      required:
        - name
      properties:
        name:
          title: Name
          type: string
          description: Unique name of the component
          ui:autofocus: true
          ui:options:
            rows: 5
    - title: Choose a location
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - dev.azure.com

  steps:
    - id: fetch-base
      name: Fetch Base
      action: fetch:cookiecutter
      input:
        url: ./template
        values:
          name: '{{ parameters.name }}'

    - id: publish
      name: Publish
      action: publish:azure
      input:
        allowedHosts: ['dev.azure.com']
        description: 'This is {{ parameters.name }}'
        repoUrl: '{{ parameters.repoUrl }}'

    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: '{{ steps.publish.output.repoContentsUrl }}'
        catalogInfoPath: '/backstage.yaml'
```

## Your Environment

- NodeJS Version (v12): v14.15.5
- Operating System and Version (e.g. Ubuntu 14.04): macOS 11.2.3 (20D91)
- Browser Information: Edge Version 89.0.774.57
