### ISSUE TITLE
Perform Environment Variable Substitution Prior to Other Transforms

### ISSUE THREAD

**Issue by JP-Dhabolt** [backstage/backstage#5142]
# Use Case
When using a tool like [mozilla/sops](https://github.com/mozilla/sops) to safely store your secrets in source control, each environment has its own secrets file.  In the base `app-config.yaml`, it would be convenient to be able to declare something like below, rather than having to have it duplicated in every single environment YAML file (i.e. `app-config.local.yaml`, `app-config.dev.yaml`, `app-config.prod.yaml`), with only the name of the file differing.

```yaml
integrations:
  github:
    - host: github.com
      apps:
        - $include: config/backstage.${BACKSTAGE_ENVIRONMENT}.secrets.yaml#githubApp

```

It would seem that adding a call to the substitution transformer at this point, and using the resulting value (if the transform returned `applied: true`) would work for this use case.
https://github.com/backstage/backstage/blob/95ac3cd52c36ec015d6a64936e5da3d4a13b8c17/packages/config-loader/src/lib/transform/include.ts#L56

This would require passing in the substitution transformer to the include transformer (or creating a new instance...the former seems like a better option).  If this seems like a reasonable approach, I don't mind tackling the change sometime in the next week or two.
