### ISSUE TITLE
GitHub Discovery filter out forks

### ISSUE THREAD

**Issue by axdotl** [backstage/backstage#5178]
## Feature Suggestion

Enhance the GitHub discovery to filter out forks.

## Possible Implementation

- GitHub API offers a `type` filter, see [List organization repositories](https://docs.github.com/en/rest/reference/repos#list-organization-repositories) - maybe the same values for param `type` can be used for this feature
- Extend configuration options for locations
  ```yaml
  catalog:
    locations:
      - type: github-discovery
        target: https://github.com/myorg/*/blob/main/catalog-info.yaml
        options:
          - type: [all, public, private, forks, sources, member, internal]
          - ignoreForks: true
  ``` 
- Adjust `GithubDiscoveryProcessor` to consider configuration options

## Context

The discovery feature is really useful and we use it to discover repos for the whole org, but we also have some forks which we do not want to track in our Backstage App. Therefor it would be great to filter out forked repos.
