### ISSUE TITLE
File descriptor substitution not invoked for annotations

### ISSUE THREAD

**Issue by andaziar** [backstage/backstage#5198]
## Expected Behavior

If I specify a Component in the following way:

```yaml
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: service-name
  annotations:
    $yaml: ./annotations.yaml
    github.com/project-slug: org/service-repo
    backstage.io/techdocs-ref: github:https://github.com/org/service-repo.git
spec:
  type: other
  owner: team-name
  lifecycle: unknown
```

with `annotations.yaml` being a bunch of K/V valid annotations:
```yaml
system1.company-name.dev/deployment-id: service-name
system2.company-name.dev/component-id: service-name
system3.company-name.dev/artifact-name: com.company.platform/service
...
```

It is expected that the processors should be able to resolve the placeholder and finally result in this kind of file:

```yaml
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: service-name
  annotations:
    system1.company-name.dev/deployment-id: service-name
    system2.company-name.dev/component-id: service-name
    system3.company-name.dev/artifact-name: com.company.platform/service
    github.com/project-slug: org/service-repo
    backstage.io/techdocs-ref: github:https://github.com/org/service-repo.git
    ...
spec:
  type: other
  owner: team-name
  lifecycle: unknown
```

## Current Behavior

Instead, when trying to ingest the file, we get an error message stating:

```
 \"annotations.$yaml\" is not valid; expected a valid prefix and/or suffix but found \"$yaml\"
```

which means that it tries to validate the annotations (in this case it's the `FieldFormatEntityPolicy`) before even considering processing the placeholders.

## Steps to Reproduce

1. Define a component in yaml format as seen above
2. Add a yaml placeholder in that component. The yaml placeholder should either point to a remote file reference or a local file that contains valid annotations.
3. Let Backstage ingest the component and you will see the error message in the logs

## Context

We're trying to use Components for defining our services but we have a lot of data that should reside in annotations as they reference to external sources/third party apps. However, to reduce clutter in the `catalog-info.yaml` files that will house our Components, we want to gather the annotations in a separate file and simply just reference to this file using the placeholder pattern described here: https://backstage.io/docs/features/software-catalog/descriptor-format#substitutions-in-the-descriptor-format
