### ISSUE TITLE
LDAP - AD Group mapping to user-readable names (for complicated orgs)

### ISSUE THREAD

**Issue by rmanny** [backstage/backstage#5221]
## Context
Where we are implementing Backstage, the org structure is quite complex, and seems to be escaping the typical use case of the existing LdapOrgProcessor.

The user integration is perfect, but the groups get complicated. For context, we have thousands of AD groups with very verbose names. The ones that control access to Backstage are called `Azure RBAC - <Platform Name> - <Internal Backstage Project Name> Eng` for development, and `Azure RBAC - <Platform Name> - <Internal Backstage Project Name> Prod` for production. Ingesting these as they are is not only pretty ugly, but becomes much more granular than our end users need. Listing ownership for services also becomes ambiguous.

We also can't ingest this information from GitHub, since not all of our developers use GitHub.

I imagine that most other orgs would just have one group called Backstage, so everything works perfectly out of the box.

## Feature Suggestion
Ideally, I want to map these two AD groups into a single Backstage group called just `backstage`. Every user in any of the AD groups will be counted as if they in the `backstage` group.

I have looked at creating a custom processor which does this, but that feature seems more engineered toward entity-types that don't already exist. Besides, it is massively hard to reuse the built-in LDAP ingestion code that's already written without a lot of copy-and-paste.

This seems like it will probably become a common problem.

### Stopgap - One-way group membership
I have tried a couple of simple workarounds, such as ingesting the users through LDAP, but creating the groups separately through a static location in the repo which references the users already populated through LDAP. This way, it is easy for users to add themselves to groups. However, this only gives the entities one side of the relationship (Group members), so nothing shows up on the Entity pages. There is no way to add memberOf to each user statically, since the catalog throws this warning:

`Rejecting write of entity User:default/rmanny from file:../../entities/org-data/groups.yaml because entity existed from <LDAP URL>`. So I'm stuck on that front unless I add a page dedicated solely to adding users to groups by manually manipulating the database.

Allowing us to define groups this way would be nice, but I think I have a better solution that would probably satisfy many orgs:

### Configuration
Here is the implementation I'm imagining:
```
processors:
    ldapOrg:
      providers:
        ...
        - groups:
            fold:
              - parent: backstage
                children:
                  - Azure RBAC - <Platform Name> - <Internal Backstage Project Name> Eng
                  - Azure RBAC - <Platform Name> - <Internal Backstage Project Name> Prod
      ... (or even REGEX)
           fold:
             - backstage: Azure RBAC - <Platform Name> - <Internal Backstage Project Name> *
```
This config then gets read into the readLdapOrg function in `plugins/catalog-backend/src/ingestion/processors/ldap/read.ts`. If the `fold` key is not present, it defaults to the old behavior.

Perhaps this could make use of a brand new entity type that can act as an intermediary between AD Group and Backstage Group, although I'm not sure if that's even necessary.

Would love to hear some thoughts on this, even if they involve some accusations that I'm crazy.
