### ISSUE TITLE
Support explicit parameter ordering in software templates

### ISSUE THREAD

**Issue by tragiclifestories** [backstage/backstage#5273]
## Feature Suggestion

Allow users to explitily define the order of appearance of fields within a form step in the scaffolder.

## Possible Implementation

Add an `index` field (or maybe `ui:index`?) to the property object in the template schema.

```yaml
spec:
  owner: backstage/techdocs-core
  type: service

  parameters:
    - title: Fill in some steps
      required:
        - name
        - owner
      properties:
        name:
          title: Name
          type: string
          description: Unique name of the component
          index: 0
          ui:autofocus: true
          ui:options:
            rows: 5
        owner:
          title: Owner
          type: string
          description: Owner of the component
          index: 1
          ui:field: OwnerPicker
          ui:options:
            allowedKinds: 
              - Group
```

Or add an `ordering` field to the parameter:

```yaml
spec:
  owner: backstage/techdocs-core
  type: service

  parameters:
    - title: Fill in some steps
      required:
        - name
        - owner
      ordering: ["name", "owner"]
```

## Context

Currently, the order of fields in a field set is determined by the order they appear in the YAML descriptor. This works in practice because Javascript preserves field ordering in its standard objects. However, this is not universally true of different platforms. 

For example, we use jsonnet to deduplicate descriptor boilerplate. This allows us to (for example) add common repository setup tasks to new templates with a single line of code. However, jsonnet forcibly alpabetises the key order of objects, so we lose the ordering. If we had a way to express the order explicitly, we could get around this problem.

**Comment by tragiclifestories** [comment]
After discussion in Discord with @timbonicus, it turns out that the UI schema in rjsf [actually defines a `ui:order` property](https://react-jsonschema-form.readthedocs.io/en/latest/usage/objects/#specifying-property-order), so the job would actually just be to 'honour' that part of the schema and hopefully not too complicated to implement.

**Comment by freben** [comment]
@tragiclifestories Shall I assign you to the issue? :) If you want to work on it

**Comment by tragiclifestories** [comment]
Yeah, go for it 👍

**Comment by pheresparza** [comment]
Hello, if I understand well, I see you guys add the ui:order option to build the form however, I am not getthin this working but I am not sure if this is my doing it bad or have to do anything else, any advise, this is an example of what I am trying:

parameters:
  - title: Fill in some steps
    required:
      - name
      - last_name
    properties:
      last_name:
        title: Last Name
        type: string
        ui:order: 2
      name:
        title: Name
        type: string
        ui:order: 1

**Comment by YCAD-pro** [comment]
Hello, just because I have trouble implementing this functionality, I post this message to put a working example:

```yaml
parameters:
  - title: Fill in some steps
    required:
      - name
    ui:order:
      - owner
      - name
    properties:
      name:
        title: Name
        type: string
        description: Unique name of the component
      owner:
        title: Owner
        type: string
        description: Owner of the component
```
