### ISSUE TITLE
OwnerPicker to support output options 

### ISSUE THREAD

**Issue by regicsolutions** [backstage/backstage#5286]
## Feature Suggestion

When selecting the User using the OwnerPicker that was recently contributed by @tragiclifestories, the output is `User: john.smith` 

There is no option to just output `john.smith` for the user and no way to add other fields that you would like to be shown in the dropdown.

## Possible Implementation

Introduce two new UI Options called allowedOutput to exclude the `User: ` by defining the field name you would like to output and allowedMetadata to include specific fields you would like shown in the dropdown such as displayName.

```
        owner:
          title: Component Owner
          type: string
          description: Owner of the component 
          ui:field: OwnerPicker
          ui:options:
            allowedKinds: 
              - User
            allowedMetadata:
              - name
              - displayName 
            allowedOutput:
              - name
```
