### ISSUE TITLE
Unable to connect to an external postgres that doesn't support SSL with Helm Chart package 

### ISSUE THREAD

**Issue by aamattos** [backstage/backstage#5331]
I'm trying to connect to an external postgresql db that doesn't support SSL
## Expected Behavior

I should be able to connect

## Current Behavior

I receive an error message saying that database doesn't support SSL

## Steps to Reproduce

1. Configure db connection on helm values yaml
2.. Install Helm Chart
3. Pods crashes with the above error.

## Your Environment

Helm Chart on Kubernetes Cluster.

**Comment by freben** [comment]
Could you provide the actual full error you saw?

I'm unfortunately not knowledgeable myself on helm and this is in the community contrib hierarchy. @martina-if , is this something you would know more about?

As far as I can see, `app-config.development.yaml.tpl` contains explicit SSL configuration, and it seems reasonable that the chart won't work for all variations of all kinds of situation. Can't you just copy the chart and remove that particular section (and possibly other related things) if it doesn't fit your situation?

**Comment by martina-if** [comment]
Hi @aamattos ,

I think SSL is even disabled by default in the chart. But perhaps the fact that the `ca` field is there makes knex enable it automatically. 

Can you give us more information? Is it the backend pod that is crashing or is it just lighthouse? Can you paste the error here? (make sure to redact any sensitive information).

**Comment by aamattos** [comment]
Hi @martina-if , thank you for your reply.
I'm trying to install backstage with helm on an openshift cluster with a remote postgresql database.

The error I'm getting on the lighthouse pod is:

```
yarn run v1.22.4
warning Skipping preferred cache folder "/.cache/yarn" because it is not writable.
warning Selected the next writable cache folder in the list, will be "/tmp/.yarn-cache-1000770000".
$ node ./cjs/run.js
warning Cannot find a suitable global folder. Tried these: "/usr/local, /.yarn"
[32minfo[39m: building express app... {"service":"lighthouse-audit-service","timestamp":"2021-04-19T15:30:26.735Z"}
[31merror[39m: The server does not support SSL connections {"service":"lighthouse-audit-service","timestamp":"2021-04-19T15:30:36.843Z"}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

This is the error on the backend pod:

```
Backend failed to start up Error: The server does not support SSL connections
    at Socket.<anonymous> (/usr/src/app/node_modules/pg/lib/connection.js:76:35)
    at Object.onceWrapper (events.js:422:26)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:271:9)
    at Socket.Readable.push (_stream_readable.js:212:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:186:23)
```

And this is my helm configuration:

```yml
appConfig:
  app:
    baseUrl: https://backstage.mydomain.corp
    title: Backstage
  backend:
    baseUrl: https://backstage.mydomain.corp
    cors:
      origin: https://backstage.mydomain.corp
    database:
      client: pg
      connection:
        database: backstage_plugin_catalog
        host: ****
        user: ****
        port: ****
        password: ****
  lighthouse:
    baseUrl: https://backstage.mydomain.corp/lighthouse-api
  techdocs:
    storageUrl: https://backstage.mydomain.corp/api/techdocs/static/docs
    requestUrl: https://backstage.mydomain.corp/api/techdocs

postgresql:
  enabled: false

lighthouse:
  database:
    connection:
      port: ****
      host: ****
      user: ****
      password: ****
      database: lighthouse_audit_service
```
