### ISSUE TITLE
Unable to get the config value of a proxy target in the frontend

### ISSUE THREAD

**Issue by rbideau** [backstage/backstage#5393]
## Expected Behavior

When the visibility for `target` is set to frontend, I should be able to get the value of a proxy target in the frontend.

## Current Behavior

1. `target`  is not visible to the frontend.

2. There is an error when trying to access the value: `Invalid config key 'proxy./path.target'`, because `/path` is not a valid config path key.

## Possible Solution

1. This looks like a bug in the [config-loader](https://github.com/backstage/backstage/tree/master/packages/config-loader) package

2. Allow config key to start with `/` => update the [`CONFIG_KEY_PART_PATTERN`](https://github.com/backstage/backstage/blob/master/packages/config/src/reader.ts#L22)

## Steps to Reproduce

1. In a plugin `package.json`, add `"configSchema": "config.d.ts"` and export a config:
```typescript
export interface Config {
  proxy?: {
    [key: string]:
      | string
      | {
          /**
           * @visibility frontend
           */
          target: string;
        };
  };
}
```

2. Add a proxy with a target string in your app-config.yaml
```yaml
proxy:
  '/path':
    target: 'https://example.org'
```

3. When running `yarn backstage-cli config:print --frontend`, `proxy` is not included in the output.

4. When running `yarn backstage-cli config:schema`, target has the correct visibility:
```
...
  proxy:
    type: object
    description: |-
      A list of forwarding-proxies. Each key is a route to match,
      below the prefix that the proxy plugin is mounted on. It must
      start with a '/'.
    additionalProperties:
      anyOf:
        - type: object
          required:
            - target
          properties:
            target:
              description: Target of the proxy. Url string to be parsed with the url module.
              type: string
              visibility: frontend
...
```

## Context

I need to rewrite the proxy url in an API response to make some following API call using the backend proxy.

Edit: To add more context, I'm using Artifactory to retrieve some data. In the response from artifactory, there is an url to get more information. In the frontend but I need to rewrite this url with the backend proxy url.

## Your Environment

- @backstage/config@0.1.4
- @backstage/config-loader@0.5.1
