### ISSUE TITLE
locations.[].rules.allow in app-config.yaml should works when location includes '*'

### ISSUE THREAD

**Issue by OldBlackJoe** [backstage/backstage#5557]
## Expected Behavior
in my `app-config.yaml'
```yaml
catalog:
  rules:
    - allow: [Component, API, Template, Location]
  locations:
    - type: url
      target: https://github.com/kykim138/backstage-catalogs/blob/master/domains/*
      rules:
        - allow: [Domain]
```

and in `https://github.com/kykim138/backstage-catalogs/blob/master/domains/`, there are 3 yaml files includes 3 domain entities.
For example, here is `https://github.com/kykim138/backstage-catalogs/blob/master/domains/domain-a.yaml`
``` yaml
apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
  name: domain-a
  description: Everything related to Domain-A.
spec:
  lifecycle: develop
  owner: kykim138
```

I expect that backstage backend will add 3 domains.

## Current Behavior

backstage backend occurs following WARNING, and reject to add 3 domain entities.

```
2021-05-03T04:20:19.358Z catalog warn Failed item in location url:https://github.com/kykim138/backstage-catalogs/blob/master/domains/domain-a.yaml, NotAllowedError: Entity of kind Domain is not allowed from location url:https://github.com/kykim138/backstage-catalogs/blob/master/domains/domain-a.yaml
    at LocationReaders.read (/Users/kykim138/workspace/backstage/node_modules/@backstage/plugin-catalog-backend/dist/index.cjs.js:1037:22)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async HigherOrderOperations.refreshSingleLocation (/Users/kykim138/workspace/backstage/node_modules/@backstage/plugin-catalog-backend/dist/index.cjs.js:939:26)
    at async HigherOrderOperations.refreshAllLocations (/Users/kykim138/workspace/backstage/node_modules/@backstage/plugin-catalog-backend/dist/index.cjs.js:927:9)
    at async startRefresh (/Users/kykim138/workspace/backstage/node_modules/@backstage/plugin-catalog-backend/dist/index.cjs.js:868:9) type=plugin component=catalog-all-locations-refresh
```

## Context

I think allow rules should works when location includes `*` path, because actually location includes `*` is working.
When I add 'Domain' in catalog.rules.allow, 3 domain entities is added successfully.

```yaml
in my `app-config.yaml'
```yaml
catalog:
  rules:
    - allow: [Component, API, Template, Location, Domain]
  locations:
    - type: url
      target: https://github.com/kykim138/backstage-catalogs/blob/master/domains/*
```

## Your Environment

- NodeJS Version (v12): v14.16.1
- Operating System and Version (e.g. Ubuntu 14.04): Mac OS X 10.15.7
- Browser Information: Google Chrome 89.0.4389.90
