### ISSUE TITLE
The `Template` `v1beta2` schema doesn't match the implementation

### ISSUE THREAD

**Issue by dhenneke** [backstage/backstage#5586]
The [Scaffolder documentation](https://backstage.io/docs/features/software-templates/writing-templates) gives the following examples (note the `$.spec.steps.input` property):

```yaml
apiVersion: backstage.io/v1beta2
kind: Template
metadata:
  name: v1beta2-demo
  title: Test Action template
  description: scaffolder v1beta2 template demo
spec:
  owner: backstage/techdocs-core
  type: service

  # these are the steps which are rendered in the frontend with the form input
  parameters:
  - title: Fill in some steps
    # ...

  steps:
  - id: fetch-base
    name: Fetch Base
    action: fetch:cookiecutter
    input:
      url: ./template
      values:
        name: '{{ parameters.name }}'
        owner: '{{ parameters.owner }}'
```

However, the schema of the `Template` entity, doesn't contain an `input` field, but instead specifies `$.spec.steps.parameters`:

https://github.com/backstage/backstage/blob/4ac335883bef655e4e6f97af5c923ffac1e8f9e5/packages/catalog-model/src/kinds/TemplateEntityV1beta2.ts#L41

https://github.com/backstage/backstage/blob/4ac335883bef655e4e6f97af5c923ffac1e8f9e5/packages/catalog-model/src/schema/kinds/Template.v1beta2.schema.json#L128-L131

Since `input` is the one that is also used in the implementation, the schema should be fixed so the entity validation works correctly.
