### ISSUE TITLE
Support using sqlite for app-config.local.yaml and postgres with database.ssl defined in app-config.yaml

### ISSUE THREAD

**Issue by heatheralee** [backstage/backstage#5663]
## Feature Suggestion

Hi there! We are currently experiencing an issue when using Backstage, where if in app-config.yaml we define:
```
  database:
    client: pg
    connection:
      host: ${PG_HOST}
      port: 5432
      user: ${PG_USER}
      password: ${PG_PW}
      ssl:
        ca:
          $file: file_location.pem
```

and in app-config.local.yaml we set our local instances to use sqlite3:
```
  database:
    client: sqlite3
    connection: ':memory:'
```

I would assume this would work, where we use sqlite3 for our local development and postgres for prod, but this throws an error:
```
Error: Failed to read static configuration file, error at .backend.database.connection.ssl.ca, failed to read file file_location.pem, Error: ENOENT: no such file or directory, open 'file_location.pem'
```

Is this behavior intended? 

## Possible Implementation

1. Update [createIncludeTransform](https://github.com/backstage/backstage/blob/cbfa75bf69da90961daae517f28a106327ceb5d0/packages/config-loader/src/lib/transform/include.ts#L78) to consider both config files. If a local app-config.yaml exists and the property does not need to exist in the local environment, like the database key, then only throw a warning, not an error which prevents the app from starting up.

## Context

The current workaround we have for this is to define app-config.local.yaml where it has all the variables defined for us, and we directly pass in app-config.local.yaml with the config option. Ideally, we could leverage the existing merging properties that exist for both app-config.local.yaml and app-config.yaml, though.

Thanks in advance!
