### ISSUE TITLE
TechDocs repo_url config breaks page render

### ISSUE THREAD

**Issue by Andrew-Wichmann** [backstage/backstage#5670]
## Expected Behavior

The page should render if a gitlab repo_url is provided.

## Current Behavior

The page crashes on load with the message:

```
react_devtools_backend.js:2557 Error: Missing required config value at 'integrations.github'
    at M.getConfigArray (index.esm.js:104)
    at index.esm.js:385
    at index.esm.js:1118
    at Array.forEach (<anonymous>)
    at K (index.esm.js:1117)
    at index.esm.js:1232
    at ro (react-dom.production.min.js:211)
    at gu (react-dom.production.min.js:257)
    at e.unstable_runWithPriority (scheduler.production.min.js:19)
    at Wl (react-dom.production.min.js:122)
 ```

## Steps to Reproduce

1. Setup Backstage without a github integration
2. Use mkdocs to create a techdocs site with a repo_url set.

## Context

We were able to use use techdocs before adding the repo_url, but we wanted to add the repo_url to get the "edit button" feature for faster editing.

We don't use GitHub at all, so we don't have a configuration.

## Your Environment

mkdocs.yml
```
site_name: "Mintel Event Bus"

site_url: https://backstage.int.everest-prod.aws.mintel.com/docs/default/System/event-bus

repo_url: https://gitlab.com/mintel/everest/event-bus/events/mintel-events-protobuf

nav:
  - Home: README.md

plugins:
  - techdocs-core
```

app-config.yaml
```
app:
  title: Mintel Backstage
  baseUrl: http://localhost:3000

organization:
  name: Mintel

backend:
  baseUrl: http://localhost:7000
  listen:
    port: 7000
  csp:
    connect-src: ["'self'", 'http:', 'https:']
  cors:
    origin: http://localhost:3000
    methods: [GET, POST, PUT, DELETE]
    credentials: true
  # config options: https://node-postgres.com/api/client
  database:
    client: pg
    connection:
      host: ${PG_HOST}
      database: ${PG_DATABASE}
      port: ${PG_PORT}
      user: ${PG_USER}
      password: ${PG_PASSWORD}
      # https://node-postgres.com/features/ssl
      #ssl: require # see https://www.postgresql.org/docs/current/libpq-ssl.html Table 33.1. SSL Mode Descriptions (e.g. require)
        #ca: # if you have a CA file and want to verify it you can uncomment this section
        #  $file: <file-path>/ca/server.crt
  # workingDirectory: /tmp # Use this to configure a working directory for the scaffolder, defaults to the OS temp-dir

integrations:
  gitlab:
    - host: gitlab.com
      token: ${GITLAB_TOKEN}

# proxy:
#   '/test':
#     target: 'https://example.com'
#     changeOrigin: true

techdocs:
  builder: 'external'
  publisher:
    type: 'awsS3'
    awsS3:
      bucketName: ${DOCS_S3_BUCKET}

auth:
  environment: ${STAGE}
  providers:
    gitlab:
      prod:
        clientId: ${GITLAB_APP_ID}
        clientSecret: ${GITLAB_APP_SECRET}
      development:
        clientId:<redacted>
        clientSecret: :<redacted>

catalog:
  rules:
    - allow: [Component, Resource, System, API, Group, User, Domain, Template, Location]
  locations:
    - type: url
      target: https://gitlab.com/mintel/everest/mintel-backstage-org-config/-/blob/master/catalog-info.yaml
```
