### ISSUE TITLE
Software template / Cookiecutter - support for templates in context values

### ISSUE THREAD

**Issue by nadworny** [backstage/backstage#5718]
I would like to be able to use the templates in context values from cookiecutter: https://cookiecutter.readthedocs.io/en/1.7.3/advanced/templates_in_context.html

Currently, if I provide something like this:
```yaml
steps: 
    - id: fetch-base
      name: Fetch Base
      action: fetch:cookiecutter
      input:
        url: .
        values:
          pipe_name: '{{ parameters.name }}'
          project_name: "{{ cookiecutter.pipe_name.replace('_',' ').title()}} spaCy Pipeline Component"
```
I'm getting the following error:
```
2021-05-18T14:22:43.863Z Error: Parse error on line 1:
...kiecutter.pipe_name.replace('_',' ').tit
-----------------------^
Expecting 'ID', got 'INVALID'
    at Parser.parseError (/app/node_modules/handlebars/dist/cjs/handlebars/compiler/parser.js:267:19)
    at Parser.parse (/app/node_modules/handlebars/dist/cjs/handlebars/compiler/parser.js:336:30)
    at parseWithoutProcessing (/app/node_modules/handlebars/dist/cjs/handlebars/compiler/base.js:46:33)
    at HandlebarsEnvironment.parse (/app/node_modules/handlebars/dist/cjs/handlebars/compiler/base.js:52:13)
    at compileInput (/app/node_modules/handlebars/dist/cjs/handlebars/compiler/compiler.js:508:19)
    at ret (/app/node_modules/handlebars/dist/cjs/handlebars/compiler/compiler.js:517:18)
    at Object.<anonymous> (/app/node_modules/@backstage/plugin-scaffolder-backend/dist/index.cjs.js:2448:17)
    at JSON.parse (<anonymous>)
    at TaskWorker.runOneTask (/app/node_modules/@backstage/plugin-scaffolder-backend/dist/index.cjs.js:2441:44)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async /app/node_modules/@backstage/plugin-scaffolder-backend/dist/index.cjs.js:2404:9
```

## Feature Suggestion
Support templates in context values

## Possible Implementation
1) I think the easiest solution would be to escape the values if you want to resolve them by cookiecutter itself, once the `cookiecutter.json` is created from the above configuration.
I can think of something like:
`          project_name: $${"{{ cookiecutter.pipe_name.replace('_',' ').title()}} spaCy Pipeline Component"}`

2) Or maybe just recognize the prefix `{{ cookiecutter...` and don't try to resolve it.

## Context
This can be really useful if you have a lot of context values and you don't want to bother the user to provide all of them while creating the software component. For example, I have one project with the following `cookiecutter.json` which is currently used when invoking manually the `cookiecutter %github_url%`:
```json
  "pipe_name": "mycustom",
  "project_name": "{{ cookiecutter.pipe_name.replace('_',' ').title()}} spaCy Pipeline Component",
  "project_slug": "nlp-comp-{{cookiecutter.pipe_name.replace('_','-')}}",
  "module_name": "{{ cookiecutter.pipe_name }}",
  "component_name": "{{ cookiecutter.pipe_name }}",
  "pipe_class": "{{ cookiecutter.pipe_name.title().replace('_', '') }}",
  "author_name": "John Doe",
  "author_email": "john@doe.com",
  "description": "{{ cookiecutter.pipe_name }} spaCy custom processing component",
  "repository_url": "https://dev.azure.com/xxx/xxx/_git/nlp-comp-{{ cookiecutter.pipe_name.replace('_', '-')} }",
  "homepage_url": "{{ cookiecutter.repository_url }}",
  "documentation_url": "{{ cookiecutter.repository_url }}"
```

Without this feature, one would need to provide all of the above as parameters in the software template.

**Comment by dhenneke** [comment]
The scaffolder uses handlebars to render the templates so you can use their [syntax to escape templates](https://handlebarsjs.com/guide/expressions.html#escaping-handlebars-expressions).

We use e.g. the following code to let cookiecutter derive the folder name from a java package:

```yaml
apiVersion: backstage.io/v1beta2
kind: Template
metadata:
  ...
spec:
  owner: ...
  type: service
  parameters:
    - title: Java details
      required:
        - package_name
      properties:
        package_name:
          type: string
          default: io.backstage.bla

  steps:
    - id: fetch-base
      name: Render Service Template
      action: fetch:cookiecutter
      input:
        url: "..."
        values:
          package_name: '{{ parameters.package_name }}'
          package_path: "\\{{ cookiecutter.package_name | replace('.', '/') }}"

```

**Comment by nadworny** [comment]
@dhenneke you're the best! It worked.

**Comment by nadworny** [comment]
@dhenneke a bit offtopic but were you able to exclude the hooks while generating the project?
I have something like this:
![image](https://user-images.githubusercontent.com/1425919/118675573-fc727a80-b7fa-11eb-92f1-ee5478f99755.png)

And unfortunately the `pre_gen_project.py` ends up in the generated project.

**Comment by dhenneke** [comment]
Yes. That's something I left out in the gist xD

The trick is that you point the template directly to the template folder and don't use the cookiecutter function that generates a new folder name. The scaffolder implementation does some special things to make it work and ignores the result folder either way (see [here](https://github.com/backstage/backstage/blob/a849802ab5e80a1f97ff21428b9de8fe220c85cf/plugins/scaffolder-backend/src/scaffolder/stages/templater/cookiecutter.ts#L97)).

```yaml
  steps:
    - id: fetch-base
      name: Render Service Template
      action: fetch:cookiecutter
      input:
        url: "\\{{ cookiecutter.project_slug }}"
        values:
```

The scaffolder implementation also won't execute any of the hooks for security reasons.

**Comment by nadworny** [comment]
haha I tried to do that before but of course without escaping it didn't work ;)

**Comment by nadworny** [comment]
@dhenneke hmm it doesn't seem to work with Azure DevOps. I'm getting:
```
2021-05-18T15:43:45.946Z NotFoundError: Failed to read tree from https://dev.azure.com/xxx/xxx/_git/template-nlp-comp?path=%2F%257B%257B%2520cookiecutter.project_slug%2520%257D%257D&version=GBfeature%2Fbackstage&_a=contents, 404 Not Found
```

As input I've tried both:
```
      input:
        url: "./\\{{ cookiecutter.project_slug }}"
```
and
```
      input:
        url: "\\{{ cookiecutter.project_slug }}"
```

It might be an issue with the branch that I'm currently working in... Sometimes backstage behaves strangely while referencing not a main branch...

**Comment by nadworny** [comment]
This is the actual URL that exists: 
`https://dev.azure.com/xxx/xxx/_git/template-nlp-comp?path=%2F%7B%7Bcookiecutter.project_slug%7D%7D&version=GBfeature%2Fbackstage&_a=contents`
vs non-existing one
`https://dev.azure.com/xxx/xxx/_git/template-nlp-comp?path=%2F%257B%257B%2520cookiecutter.project_slug%2520%257D%257D&version=GBfeature%2Fbackstage&_a=contents`

Some strange encoding happening...

**Comment by nadworny** [comment]
@dhenneke could you please explain a bit `You could try to register it locally as a file location and see if the template is correct`. Do you mean something like this?
```yaml
  steps: 
    - id: fetch-base
      name: Fetch Base
      action: fetch:cookiecutter
      input:
        file: "\\\\{{ cookiecutter.project_slug }}"
        values:
```
