### ISSUE TITLE
Conditionally invoke steps in scaffolder templates

### ISSUE THREAD

**Issue by tragiclifestories** [backstage/backstage#5742]
## Feature Suggestion

Allow scaffolder templates to have steps that run or not based on whether 

## Possible Implementation

Extend the template schema so that this works:

```yaml
spec:
  steps:
    - id: fetch-docs
      name: Fetch Docs
      action: fetch:plain
      runIf: 'parameters.docs'
      input:
        targetPath: ./community
        url: https://github.com/backstage/community/tree/main/backstage-community-sessions
```

And then check in the task object when we're running the steps (don't think this code would work but you get the idea)

```ts
// TaskWorker.ts
          if (step.runIf && _.get(task.spec, steps.runIf)) {
            return;
          }

          await action.handler({
          // ... 
          })
```

## Context

Something like this was proposed in the RFC: https://github.com/backstage/backstage/issues/2771

This would make feasible certain kinds of incremental templates. The case we have is conditionally adding docs to new repos, similar to https://github.com/backstage/backstage/issues/3719. You can _sort of_ do this with cookiecutter but [it's not pretty](https://github.com/backstage/backstage/issues/4824#issuecomment-791511306).

**Comment by Rugvip** [comment]
Yep! We cut this from the scaffolder work to move on to the catalog, but it's definitely something we want. There's a bit of discussion around the syntax to be had, but perhaps we can start off with simply relying on the same handlebars templating, and then using something like `yn` to convert it to a boolean? Probably wanna call it just `if` too, similar to GitHub actions

**Comment by Fox32** [comment]
I'm thinking about implementing this one and came across some things:

* Handlebars doesn't support any kind of expressions afaik, so a build in helper like `not` might be handy - or we need an `unless:` beside the `if:`.
* Handlebars has some [custom definition for `false`](https://handlebarsjs.com/guide/builtin-helpers.html#if), we could reuse this, use the JavaScript logic, or `yn` as @Rugvip suggested.
* In `TaskWorker`, handlebar templates are always executed in strict mode, but for condition it would be quite handy to support missing fields (e.g. falling back to `undefined` and therefore to `false`).
* How should the whole task worker system handle the skipped steps. Do they have a custom completion status like `skipped` or are they just `completed`? Do we want to visualize this in the UI?

**Comment by Abhay-soni-developer** [comment]
this would help a lot to create more versatile templating actions. would definitely love to have this

**Comment by tragiclifestories** [comment]
@Abhay-soni-developer this was implemented! for an action you can give it an `if:` property:

```yaml
steps:
  - action: fetch:template
    id: fetch_docs
    if: "${{ parameters.docs_enabled }}"
```
