### ISSUE TITLE
Techdocs ignores branch on Azure DevOps

### ISSUE THREAD

**Issue by rchrd** [backstage/backstage#5837]
## Expected Behavior

Specifying a branch on the `techdocs-ref` annotation builds the techdocs from that branch.

## Current Behavior

The specified branch is ignored and the main branch is used.

## Steps to Reproduce

Static configuration of the component in `app-config.yaml` (uses the correct branch):
```
catalog:
  locations:
    - type: url
      target: https://dev.azure.com/org/project/_git/repo?version=GBbackstage&path=%2Fcatalog-info.yaml
```

In the `catalog-info.yaml`:
```
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: component-name
  description: My awesome component
  tags:
    - kubernetes
  annotations:
    backstage.io/techdocs-ref: url:https://dev.azure.com/org/project/_git/repo?version=GBbackstage&path=%2F
```

The checkout of the repo in the Docker container in `/tmp/backstage-xyz` contains the main branch.

## Your Environment

- NodeJS Version (v12): v14.17.0
- Operating System and Version (e.g. Ubuntu 14.04): Docker, node:lts-alpine
