### ISSUE TITLE
Catalog `metadata.name` validation contradicts documentation

### ISSUE THREAD

**Issue by madtrick** [backstage/backstage#5886]
## Expected Behavior

After reading the [catalog file format documentation](https://github.com/backstage/backstage/blob/master/docs/architecture-decisions/adr002-default-catalog-file-format.md) I thought that I could set different validation rules for the `metada.name` property. As per the docs:

> Entities that do not follow those rules will not be accepted for registration in the catalog. The ruleset is configurable to fit your organization's needs,

From https://github.com/backstage/backstage/blob/master/docs/architecture-decisions/adr002-default-catalog-file-format.md#name

## Current Behavior

The code that validates the `metadata.name` property has a [hardcoded validation](https://github.com/backstage/backstage/blob/master/packages/catalog-model/src/validation/KubernetesValidatorFunctions.ts#L46-L53), making it impossible to configure a different format that suits my needs.

## Possible Solution

n/a. Not sure which behaviour is the one that the team had in mind: the code or the ard.

## Steps to Reproduce

n/a

## Context

I am trying to register a component with a catalog similar to this one:

```yaml
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: '@myorg/mypackage'
  annotations:
    circleci.com/project-slug: github/myorg/mypackage
    github.com/project-slug: myorg/mypackage
spec:
  type: library
  lifecycle: production
  owner: team-foo
```

## Your Environment

n/a

**Comment by benjdlambert** [comment]
@madtrick yep you're right we should probably update the docs for this, as we need to make sure that the name fits certain criteria that is not allowed to be overridden.

It looks however that you're trying to do namespacing in the name, which you can achieve by using the `metadata.namespace` property but not sure if that helps at all?

```yaml
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name:  mypackage
  namespace: myorg
  annotations:
    circleci.com/project-slug: github/myorg/mypackage
    github.com/project-slug: myorg/mypackage
spec:
  type: library
  lifecycle: production
  owner: team-foo
```
