### ISSUE TITLE
[Techdocs] - MIME type errors in the browser console

### ISSUE THREAD

**Issue by voodooGQ** [backstage/backstage#6015]
When accessing any Techdocs page I receive an error in the developer console stating that the CSS files `bootstrap.min.css`, `font-awesome.min.css`, `base.css` are not being loaded because of their MIME type being `"text/html"` instead of `"text/css"`. 

![image](https://user-images.githubusercontent.com/1512028/121697252-7dd3ca80-ca92-11eb-8a57-bb9551ed673a.png)

This feels like a red herring to me, because if I try to go to the actual url address of the CSS file nothing loads, it just goes to the main "Overview" tab of the Component. It's almost more like the CSS is missing or not being loaded from the backend plugin.

Even more strangely, the CSS "appears" to load when you go to the page. The styling for the MkDocs generated site looks identical to what you'd expect. However, The main navigation dropdown and search functionality do not work. Clicking on them produces no behavior and no console errors.

![image](https://user-images.githubusercontent.com/1512028/121698425-9abccd80-ca93-11eb-9a7d-30470e76cd12.png)

The Network tab states that they are loading in with 304 responses:

![image](https://user-images.githubusercontent.com/1512028/121701550-a1990f80-ca96-11eb-9966-087e62893fe5.png)

## Expected Behavior

Techdocs site loads and all functionality works as expected.

## Current Behavior

- Receiving errors about MIME type for CSS files
- Dropdown and Search functionality not working on MkDocs generated site

## Context

We're currently utilizing an s3 bucket to house our techdoc files. I have confirmed the css files are being created and pushed to the bucket:

![image](https://user-images.githubusercontent.com/1512028/121699120-46661d80-ca94-11eb-89a9-fcc99365d5ac.png)

Relevant pieces of my app-config.yaml

```yaml
app:
  baseUrl: http://localhost:3000

#...

backend:
  baseUrl: http://localhost:7000
  listen:
    port: 7000
  csp:
    connect-src:
      - "'self'"
      - 'http:'
      - 'https:'
    img-src:
      - "'self'"
      - 'data:'
      - ${JIRA_URL}
  cors:
    origin: "*"
    methods: [GET, POST, PUT, DELETE]
    credentials: true
  database:
    client: pg
    connection:
      host: ${POSTGRES_HOST}
      port: ${POSTGRES_PORT}
      user: ${POSTGRES_USER}
      password: ${POSTGRES_PASSWORD}
  reading:
    allow:
      - host: '*.githubusercontent.com'

# ...

techdocs:
  builder: 'external'
  generators:
    techdocs: 'local'
  publisher:
    type: 'awsS3'
    awsS3:
      bucketName: 'my-techdocs-bucket'
      credentials:
        accessKeyId: ${AWS_ACCESS_KEY_ID}
        secretAccessKey: ${AWS_SECRET_ACCESS_KEY}
# ...
```

## Your Environment

Docker Version: Docker version 20.10.2, build 20.10.2-0ubuntu1~20.04.2
Docker-Compose Version: docker-compose version 1.25.0, build unknown
BaseImage: nikolaik/python-nodejs:python3.8-nodejs14-alpine
Node Version: v14.17.0
Yarn Version: 1.22.10
@backstage Versions:
```
├─ @backstage/backend-common@0.8.0
├─ @backstage/catalog-client@0.3.11
├─ @backstage/catalog-model@0.7.9
├─ @backstage/cli-common@0.1.1
├─ @backstage/cli@0.6.11
├─ @backstage/config-loader@0.6.1
├─ @backstage/config@0.1.5
├─ @backstage/core-api@0.2.18
├─ @backstage/core@0.7.9
├─ @backstage/dev-utils@0.1.14
├─ @backstage/errors@0.1.1
├─ @backstage/integration-react@0.1.2
├─ @backstage/integration@0.5.2
├─ @backstage/plugin-api-docs@0.4.13
├─ @backstage/plugin-app-backend@0.3.13
├─ @backstage/plugin-auth-backend@0.3.10
├─ @backstage/plugin-catalog-backend@0.8.2
├─ @backstage/plugin-catalog-import@0.5.6
├─ @backstage/plugin-catalog-react@0.1.6
├─ @backstage/plugin-catalog@0.5.7
├─ @backstage/plugin-circleci@0.2.14
├─ @backstage/plugin-github-actions@0.4.6
├─ @backstage/plugin-org@0.3.13
├─ @backstage/plugin-proxy-backend@0.2.8
├─ @backstage/plugin-scaffolder-backend@0.10.1
├─ @backstage/plugin-scaffolder@0.9.4
├─ @backstage/plugin-search-backend-node@0.1.4
├─ @backstage/plugin-search@0.3.6
├─ @backstage/plugin-tech-radar@0.3.11
├─ @backstage/plugin-techdocs-backend@0.7.1
├─ @backstage/plugin-techdocs@0.9.2
├─ @backstage/plugin-user-settings@0.2.10
├─ @backstage/search-common@0.1.1
├─ @backstage/techdocs-common@0.5.1
├─ @backstage/test-utils-core@0.1.1
├─ @backstage/test-utils@0.1.11
├─ @backstage/theme@0.2.7
```

**Comment by OrkoHunter** [comment]
Based on [this discussion on Discord](https://discord.com/channels/687207715902193673/714754240933003266/853912438953213972), we can see that the resources error in the browser console are safe to ignore, since the files are eventually loaded so the users won't notice anything. It’s probably something to do with how TechDocs Reader transforms the URL of the assets so that they are loaded from the right place. By default the asset urls in the HTML page are generated by MkDocs assuming they will be loaded from the root of the site, but we modify the url to point to the techdocs-backend storage url.

I'll keep this issue open, and see if it's possible to avoid having those errors in the console somehow.

**Comment by voodooGQ** [comment]
@OrkoHunter I actually don't have access to that discussion on Discord so can't see how it unfolded. However, as mentioned above this isn't just a cosmetic error happening in the console, I have limited functionality of the TechDocs site, presumably due to this error. Essentially I have no way to interact with the navigation or the search form. I get no other errors when trying to interact with these elements, but they produce no change to the screen when clicking on them.

**Comment by OrkoHunter** [comment]
@voodooGQ Hmm, let us make sure that the site generated and stored in the S3 bucket looks "right" and when it gets loaded on Backstage/TechDocs frontend, it becomes "wrong". We can do this in few ways
- Try previewing the site locally by running `npx @techdocs/cli serve` using the [techdocs-cli](https://github.com/backstage/techdocs-cli) in the documentation repository.
- Try downloading the generated site from S3 and previewing it locally by a simple http server.
- Make sure you have

```
plugins:
  - techdocs-core
```

in the `mkdocs.yml` file of the documentation repository, because that is how the material theme is used while generating the site. [Example](https://github.com/backstage/backstage/blob/8b971480c0a0b83b1d6c406154022ccc1048aa1a/plugins/scaffolder-backend/sample-templates/docs-template/skeleton/mkdocs.yml#L7-L8)

**Comment by voodooGQ** [comment]
@OrkoHunter Thank you! It was the missing `techdocs-core` directive under plugins. As soon as I added that things started working as expected. Appreciate the help!

**Comment by OrkoHunter** [comment]
I'm glad! Will still leave this issue open because the errors in the console are misleading and should be avoided.

**Comment by brahimk** [comment]
Hello,

I have the same problem on my backstage: 
With the message : 

**/docs/default/component/sampleeeabcd:1 Refused to apply style from 'https://........../api/techdocs/static/docs/default/component/sampleeeabcd/assets/stylesheets/main.50e68009.min.css' because its MIME type ('application/json') is not a supported stylesheet MIME type, and strict MIME checking is enabled.**

Do you have a solution please ?


![image](https://user-images.githubusercontent.com/36490452/173460456-0cc727a9-1292-43c5-9ca6-b9136cb4b318.png)


Thanks.

**Comment by soapraj** [comment]
@brahimk - sometimes these errors in the console are misleading. Can you check the steps mentioned in one of the [comments](https://github.com/backstage/backstage/issues/6015#issuecomment-861447168) above if that solves the issue?

**Comment by gabriel-brotas** [comment]
same error

**Comment by petejespersqbe** [comment]
still an issue :)

**Comment by jocko-angi** [comment]
I'm having this same issue in my local Backstage.   Not sure how to get it to work.  I've tried the three suggestions from @OrkoHunter above:

1. Try previewing the site locally by running npx @techdocs/cli serve using the [techdocs-cli](https://github.com/backstage/techdocs-cli) in the documentation repository.

This brings me to a broken page:
http://localhost:3000/docs/default/component/local

```
Error
Error

Message
No implementation available for apiRef{plugin.search.queryservice}

Stack Trace
Error: No implementation available for apiRef{plugin.search.queryservice}
    at ne (http://localhost:3000/static/main.78e87b92.js:30:85915)
    at Se (http://localhost:3000/static/main.78e87b92.js:31:167399)
    at Ge (http://localhost:3000/static/main.78e87b92.js:31:168601)
    at ui (http://localhost:3000/static/module-react-dom.5abdac04.js:12:52896)
    at ws (http://localhost:3000/static/module-react-dom.5abdac04.js:16:8700)
    at hs (http://localhost:3000/static/module-react-dom.5abdac04.js:16:937)
    at Za (http://localhost:3000/static/module-react-dom.5abdac04.js:16:868)
    at $t (http://localhost:3000/static/module-react-dom.5abdac04.js:16:726)
    at Mi (http://localhost:3000/static/module-react-dom.5abdac04.js:14:10871)
    at http://localhost:3000/static/module-react-dom.5abdac04.js:12:38720
```

2. Try downloading the generated site from S3 and previewing it locally by a simple http server

I don't have S3 configured since its in my local, but I can see in the DOM tree in my browser that the page does have content generated but it can't access the CSS files.

3. Make sure you have the plugin

Yup ... In place.

---

Backstage Config:
```yaml
techdocs:
  builder: 'local' # Alternatives - 'external'
  generator:
    runIn: 'docker' # Alternatives - 'local'
  publisher:
    type: 'local' # Alternatives - 'googleGcs' or 'awsS3'. Read documentation for using alternatives.
    local:
      # (Optional). Set this to specify where the generated documentation is stored.
      publishDirectory: '/workspace/techdocs'
```


Documentation repository mkdocs.yml:

```yaml
site_name: 'Angi Keycloak'

repo_url: https://gitlab.com/[...]/-/tree/backstage-configuration
edit_uri: README.md

nav:
  - Home: README.md

plugins:
  - techdocs-core
 ```

Thoughts?
