### ISSUE TITLE
feature request: support field validation in template.yaml

### ISSUE THREAD

**Issue by missedone** [backstage/backstage#6051]
I'm authoring the `template.yaml` for our own templates, in `parameters.properties`, i'd like to define validation rule for the field so it gives the user quick feedback for the invalid input.
regex based validation should be sufficient enough.

## Feature Suggestion

```yaml
apiVersion: backstage.io/v1beta2
kind: Template
# some metadata about the template itself
metadata:
  name: v1beta2-demo
  title: Test Action template
  description: scaffolder v1beta2 template demo
spec:
  owner: backstage/techdocs-core
  type: service

  parameters:
    - title: Fill in some steps
      required:
        - name
      properties:
        name:
          title: Name
          type: string
          description: Unique name of the component
          ui:autofocus: true
# below are examples with regex validation
          ui:validation:
            regex: '[a-z0-9]+(-[a-z0-9]+)*'
        awsAccountId:
          title: awsAccountId
          type: string
          description: the 12 digital aws account id
          ui:validation:
            regex: '^\d{12}$'
```

**Comment by Fox32** [comment]
The `parameters` part of the template is based on JSON schema, this means you can use all features of JSON schema here. JSON schema [supports](https://cswr.github.io/JsonSchema/spec/basic_types/) `pattern` to define a regular expression that validates the input. It also supports other constrains like `minLength` and `maxLength` for strings or `min` and `max` for numbers..

```yaml
  parameters:
    - title: Configure Your Documentation
      required:
        - name
      properties:
        name:
          type: string
          pattern: '^[a-z0-9-]*$'
          title: Name
          description: The name of the documentation. This will be the unique name in the Service Catalog.
          ui:placeholder: my-docs
```

Btw., the properties prefixed with `ui:` come from `react-jsonschema-form`, which also [provides some ways of restricting values](https://react-jsonschema-form.readthedocs.io/en/latest/usage/widgets/).
