### ISSUE TITLE
Extending existing catalog entity with automatically generated definition

### ISSUE THREAD

**Issue by jvilimek** [backstage/backstage#6079]
This feature request is about the possibility to have a way to automatically generate enrich existing (manual) catalog entities via scripts/pipelines.

## Feature Suggestion

Let's have a manually created service entity "xxx" in the team's repository, e.g. in service-xxx-repo/backstage.yaml
Let's have automatically generated xxx.yaml in catalog-definitions repo, that would enrich the manually edited service definitions with e.g. sonarCloud project annotations `sonarqube.org/project-key: xxx`

## Possible Implementation

Manual definition:
```yaml
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage
  description: this is manually entered component
spec:
  type: library
  owner: CNCF
  lifecycle: experimental
```

Automatically generated propertied
```yaml
apiVersion: backstage.io/v1alpha1
kind: Component
extends: backstage
metadata:
  annotations:
    sonarqube.org/project-key: YOUR_PROJECT_KEY
```

Or vice versa, e.g. automatically generated definition with the possibility to overwrite it in the service repository…

## Context

Right now we are implementing the catalog in two ways: 
- automatically by generating some basic definition of our services from a list to our git repository (**catalog-definitions**)where it reads the catalog scaffolder...
- manually: each team may have a custom `backstage.yaml` entry to be defined in each service repository empowering the team to define whatever they need (e.g API definition -> backend, components, domains....).

And here comes the question: how can we join these two definitions origins together?
E.g. team defines a backend service with a name "xxx-backend" in **service repository** (manually). This file would be included in the catalog automatically and scaffolded = in case its updated, also catalog is updated.
Now will have several pipelines/processors outside of backstage to collect automatically things such as
- projects from SonarCloud
- existing documentation wikis
- platforms used in the repositories (e.g. .net core 3.1, .net 5, typescript, ...)
- ...
and we want to have this information to be in the catalog "automatically". E.g. team implements SonarCloud analysis, which btw. means they enable one parameter in shared pipeline = project is created for them, analysis starts to be being generated…and the team would need also manually adjust the catalog definition = this is what we want to avoid, this is, what we want to automatize.

E.g. we know we have "xxx" project in the **SonarCloud** ... so we want to add this annotation to this service... but from file located not in the service repository, but in the **catalog definitions** repository = other location? I.e. somehow extend existing catalog component?
