### ISSUE TITLE
kind: API definition with api URL

### ISSUE THREAD

**Issue by Jerry4013** [backstage/backstage#6117]
## Feature Suggestion

Currently, in the `spec.definition` of `kind: API`, we need to write a very long json or yaml definition for the API definition. It would be nice if we can simply provide a URL of this API.

Something like:

```yaml
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: 
  description: 
spec:
  type: openapi
  lifecycle: production
  owner: 
  definition: url: SOME_URL

```

Thanks!

**Comment by freben** [comment]
Hi!

What you can do is

```yaml
spec:
  definition:
    $text: https://example.com/openapi.json
```

That makes the definition be loaded in automatically from that url.

Does that help?
