### ISSUE TITLE
Template filter on resource type / system

### ISSUE THREAD

**Issue by wrighbr** [backstage/backstage#6160]
## Feature Suggestion
The ability to filter on a resource type / system within template

## Possible Implementation
resource type
```yaml
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: cluster1
spec:
  type: k8s-cluster
  owner: team1
  system: gke
```

template
```yaml
    - title: Choose your cluster
      required:
        - gke
      properties:
        gke:
          title: Cluster
          type: string
          description: Which cluster will your application be deployed.
          ui:autofocus: true
          ui:field: EntityPicker
          ui:options:
            allowedKinds:
              - Resource
            allowedType:
              - gke
```
