### ISSUE TITLE
Kakfa plugin error

### ISSUE THREAD

**Issue by satrox28** [backstage/backstage#6176]
Hi, 

We are trying to integrate Kafka plugin with Backstage and am getting below error when accessing Kafka tab.

```
{"error":{"name":"TypeError","message":"Cannot read property 'api' of undefined","level":"error","service":"backstage"},"request":{"method":"GET","url":"/api/kafka/consumers/kafka-test/test-group/offsets"},"response":{"statusCode":500}}

```

app-config.yaml
```
kafka:
  clientId: backstage
  clusters:
    - name: kakfa-test
      brokers:
        - kafka-test:9092
```
I have installed the frontend and backend plugin and made the required changes as per the github docs.

https://github.com/backstage/backstage/tree/master/plugins/kafka-backend
https://github.com/backstage/backstage/tree/master/plugins/kafka

Created the required consumer group and topic on the Kafka server.

Can you please help me, in fixing the issue.
