### ISSUE TITLE
Register step of Scaffolder for Gitlab repository error

### ISSUE THREAD

**Issue by biki0109** [backstage/backstage#6181]
Hi, I'm currently using Backstage for my Gitlab (and in the future for Gitlab Enterprise as well). I often experience the following error at the register step using some of the Backstage sample templates. For this example, I'm using the React SSR template for Gitlab.

## Expected Behavior

The register step should show no error and work just like the normal flow of Scaffolder

## Current Behavior
The register step instead show an error saying that `Type error: body used already for ...`
![image](https://user-images.githubusercontent.com/48164880/123104360-1427c900-d461-11eb-94f8-b8671acbca7b.png)
However, when I check my Gitlab again, the repo was still created, code was pushed and the entity had also been registered into the catalog. 

I'm not sure if this is a bug or has anything to do with the template.yaml or my code.

## Steps to Reproduce

1. Step 1
Create a repo on Gitlab containing the sample templates of Backstage (for this it will be the React SSR)
My new template.yaml is as follow
```yaml
apiVersion: backstage.io/v1beta2
kind: Template
metadata:
  name: react-ssr-template
  title: React SSR Template
  description: Create a website powered with Next.js
  tags:
    - recommended
    - react
spec:
  owner: web@example.com
  type: website
  parameters:
    - title: Provide some simple information
      required:
        - component_id
        - owner
      properties:
        component_id:
          title: Name
          type: string
          description: Unique name of the component
        description:
          title: Description
          type: string
          description: Help others understand what this website is for.
        owner:
          title: Owner
          type: string
          description: Owner of the component
          ui:field: OwnerPicker
          ui:options:
            allowedKinds: 
              - Group
    - title: Choose a location  
      required:
        - repoUrl
      properties: 
        repoUrl:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - gitlab.com
  steps:
    - id: template
      name: Fetch Skeleton + Template
      action: fetch:cookiecutter
      input:
        url: ./skeleton
        copyWithoutRender:
          - .github/workflows/*
        values:
          component_id: '{{ parameters.component_id }}'
          description: '{{ parameters.description }}'
          destination: '{{ parseRepoUrl parameters.repoUrl }}'
          owner: '{{ parameters.owner }}'

    - id: publish
      name: Publish
      action: publish:gitlab
      input:
        allowedHosts: ['gitlab.com']
        description: 'This is {{ parameters.component_id }}'
        repoUrl: '{{ parameters.repoUrl }}'

    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: '{{ steps.publish.output.repoContentsUrl }}'
        catalogInfoPath: '/catalog-info.yaml'

  output:
    remoteUrl: '{{ steps.publish.output.remoteUrl }}'
    entityRef: '{{ steps.register.output.entityRef }}'
```
Not sure if the github/workflow has anything to do with this.
2. Step 2
Put the link to the repo in the catalog section
```yaml
catalog:
  rules:
    - allow: [Component, System, API, Group, User, Resource, Location, Template]
  locations:
# Backstage example templates gitlab
    - type: url
    target: https://gitlab.com/my-name/backstage-entities/-/blob/main/sample-templates/react-ssr-template/template.yaml
    rules:
      - allow: [Template]
```
3. Step 3
Create a new component using the the React SSR template

## Context
- Local development
- Frontend port is on 3000, Backend is on 7000
- Database is using Postgres
- The token provided to the scaffolder has full access

## Your Environment

- NodeJS Version (v12.22.1):
- Operating System and Version (MacOS Catalina 10.15.7):
- Browser Information: Google Chrome
