### ISSUE TITLE
[Plugin] Lighthouse Basic Authentication Support

### ISSUE THREAD

**Issue by jamesrenaud** [backstage/backstage#6282]
## Summary

The lighthouse CI server supports setting a basic username and password combo to protect data viewing https://github.com/GoogleChrome/lighthouse-ci/blob/main/docs/server.md#security. The current plugin does not support specifying tokens for viewing the data.

## Context

It would be advantageous if in the `app-config` setup for the Lighthouse plugin if we could set some sort of authentication, even if it was simply hardcoding an Authorization header.

``` yaml
lighthouse:
  baseUrl: http://your-service-url
  authorization: Basic c29tZXVzZXI6c29tZXBhc3N3b3Jk
```

**Comment by pimperator** [comment]
Dear @jamesrenaud 
I had the same issue and it took a long time but for now I am using this solution:
in app-config.yaml
```yaml
proxy:
  # '/test':
  #   target: 'https://example.com'
  #   changeOrigin: true
  '/lighthouse-app-sec':
    target: 'http://localhost:8080'
    allowedMethods: ['GET','POST','DELETE']
lighthouse:
  baseUrl: https://${BASE_URL}/api/proxy/lighthouse-app-sec
```

The lighthouse-application-security container is a sidecar container of the application itself.

Here you have the benefit that the lighthouse-container itself, which has no authentication support is protected by your backstage's authentication and you dont have to implement something additionally.

Cheers

**Comment by freben** [comment]
@pimperator Would it be possible to just set the baseUrl to directly point at the sec container instead? Without using the proxy at all?

But adding the auth support directly to the `lighthouse` config key would be good too if that's a sensible method to use, for those who may not want to or are unable to run that extra sidecar. Hook us up with a PR for that if you can. Maybe like

```yaml
lighthouse:
  baseUrl: ...
  auth:
    username: a
    password: b
```

or so could be helpful to the user. Then we declare those keys as `@visibility secret` in the config schema of course.
