### ISSUE TITLE
Download tar.gz archive getting 403 Forbidden for Bitbucket

### ISSUE THREAD

**Issue by camilaibs** [backstage/backstage#6298]
According to this [message on Discord](https://discord.com/channels/687207715902193673/714754240933003266/859610554338770975), we are getting an error with the Bitbucket URL reader on techdocs generation:
```
error Failed to read tree from https://bitbucket.org/accountname/reponame/, 403 Forbidden type=errorHandler
```

Thanks **@matt** for reporting and @iamEAP , @OrkoHunter for debugging help 🙌🏻 !

## Expected Behavior

Be able to generate documentation for an entity fetching the source markdown files from the Bitbucket and passes the files to the generator for the next steps.

## Current Behavior

Works with `.zip` format reverting these [changes](https://github.com/backstage/backstage/commit/eda9dbd5fa9e25a25f9c4794daddeab8f0a5f7af), but fails with 403 Forbidden error using `.tar` when try to read the tree.

## Steps to Reproduce

1. Create a [repository](https://backstage.io/docs/features/techdocs/creating-and-publishing) on Bitbucket for the documentation component containing the [techdocs-ref](https://backstage.io/docs/features/techdocs/how-to-guides#how-to-use-url-reader-in-techdocs-prepare-step) url on the `catalog-info.yml` file:
```yml
metadata:
  annotations:
    backstage.io/techdocs-ref: url:https://bitbucket.org/{workspace}/{repository}/src/{branch}/
```
2. Generate a `appPassword`  with `repository:read` permission (follow this [tutorial](https://support.atlassian.com/bitbucket-cloud/docs/app-passwords/))
3. Configure Bitbucket integration and add its documentation to the catalog in the `app-config.yaml` file of your backstage instance project:
```yml
integrations:
  bitbucket:
    - host: bitbucket.org
      username: {your normal Bitbucket username}
      appPassword: {the app password}
```
4. Start your backstage instance and access the documentation page using the browser (`http://localhost:3000/docs/default/Component/:componentId`):
```node
yarn dev
```

## Your Environment

- NodeJS Version: v14.16.0
- Operating System and Version: macOs Big Sur Version 11.4
- Browser Information:
Chrome Version 91.0.4472.114 (Official Build) (x86_64)
