### ISSUE TITLE
OIDC Configuration is somehow expecting `metadataUrl` to be an object

### ISSUE THREAD

**Issue by Erog38** [backstage/backstage#6348]
## Expected Behavior

When creating an oidc provider for backstage, the following configuration fails: 
```yaml
auth:
  # see https://backstage.io/docs/auth/ to learn about auth providers
  providers:
    oidc:
      clientId: XXX
      clientSecret: XXX
      metadataUrl: https://<oidc-endpoint>/.well-known/openid-configuration
```

The Url is confirmed to return the configuration as expected.

## Current Behavior

metadataUrl should be treated as a string if I'm reading this PR appropriately #33

## Steps to Reproduce

1. Pull a new backstage environment with npx
2. set the configuration with the above auth configuration, even with invalid values it'll fail out as if they were valid.

## Context

I can't configure the auth backend as expected.

## Your Environment

- Node 14
- MacOS Big Sur
- Firefox 89.0.2

**Comment by freben** [comment]
I think you linked to the wrong pull request, back in the mists of time when we were experimenting with a golang service instead of node :)

[Here's the code](https://github.com/backstage/backstage/blob/9b743a33b89e7a1b60877a9f1a05de75f700fe13/plugins/auth-backend/src/providers/oidc/provider.ts#L192) that fetches that parameter and it's indeed a string.

You don't explain what goes wrong, what the error message is etc. But could it be that you were bitten by [this problem](https://github.com/backstage/backstage/pull/6228)? If that's the case, an update to the latest version of the backstage libraries should suffice.

**Comment by Erog38** [comment]
Ah my apologies @freben! I updated the backstage libraries, and unfortunately now get the error when configuring the client ID:
```
[1] 2021-07-06T14:27:26.879Z auth info Configuring provider, oidc type=plugin
[1] Backend failed to start up, Error: Failed to initialize oidc auth provider, Invalid type in config for key 'auth.providers.oidc.clientId' in 'app-config.yaml', got string, wanted object
```

I am able to trace the calls into that section of the library, but unfortunately it doesn't drop into the configuration function for me, but [fails out here](https://github.com/backstage/backstage/blob/9b743a33b89e7a1b60877a9f1a05de75f700fe13/plugins/auth-backend/src/lib/oauth/OAuthEnvironmentHandler.ts#L32) before it can even run the anonymous function with the line you linked. 

I would be ecstatic to find out that I'm just being an idiot and misconfigured something 😅

**Comment by freben** [comment]
Haha! OK I think I see something! The format of these sections is supposed to be

```yaml
auth:
  providers:
    <providerId>:
      development:  # <--- i think this is the issue
        clientId: ...
```

this is because each provider may have multiple environments that they work within. I think the error you're seeing may be a misleading effect of how the traversal code reacted to not finding that single key there. It probably thought that `clientId` was the environment ID, and then to have a properties object inside that - but found the string 'XXX' instead.
