### ISSUE TITLE
catalog-backend: discovery on multiple branches causes duplicates, resulting in SQL error

### ISSUE THREAD

**Issue by acuteaura** [backstage/backstage#6469]
When using multiple github-discovery locations in the catalog config that point to different branches on the same organisation, duplicates can occur when the default branch was changed via GitHub UI due to redirect.

## Expected Behavior

Conflicts are resolved by detecting the redirect and either deduplicating objects or not following redirects.

## Current Behavior

An attempt to ingest the same catalog file twice will be made, leading to SQL error on `entitites_unique_full_name` constraint (in Postgres, though SQLite fails too in testing).

## Possible Solution

Do not follow redirects.

## Steps to Reproduce

```yaml
catalog:
  locations:
    - type: github-discovery
      target: https://github.com/backstage/*/blob/main/catalog-info.yaml
    - type: github-discovery
      target: https://github.com/backstage*/blob/master/catalog-info.yaml
```

Ensure one repository has had its default branch renamed from main/master to the other.

## Context

We have mixed use of `main` and `master` as the default branch across our organisations.

## Your Environment

- NodeJS Version (v12): 14
- Operating System and Version (e.g. Ubuntu 14.04): node:14-alpine Container
- Browser Information: N/A
