### ISSUE TITLE
Bitbucket Server - Catalog Registration Action not Registering Entities in Catalog

### ISSUE THREAD

**Issue by regicsolutions** [backstage/backstage#6542]
## Expected Behavior

When a **catalog-info.yaml** file is generated using the `fetch-base` action followed by a `publish` and `register` action, the entity should become available in the catalog. 

Sample steps:

```
    - id: fetch-base
      name: Fetch Base Template
      if: '{{ parameters.generateTemplate }}'
      action: fetch:template
      input:
        url: ./template
        cookiecutterCompat: true
        values:
             name: '{{ parameters.name }}'
             componentOwner: '{{ parameters.componentOwner }}'

    - id: publish
      name: Publish to a New Bitbucket Repository
      action: publish:bitbucket
      input:
        repoUrl: 'my-bitbucket-server.com?owner={{ parameters.projectKey}}&repo={{ parameters.repoName}}'

    - id: register
      name: Register Component in Catalog
      action: catalog:register
      input:
        repoContentsUrl: 'https://my-bitbucket-server.com/projects/{{ parameters.projectKey }}/repos/{{ parameters.repoName }}'
        catalogInfoPath: '/browse/catalog-info.yaml'   
        
  output:
     links:
      - title: Open in Catalog
        icon: 'catalog'
        entityRef: '{{ steps.register.output.entityRef }}'
```

Screenshot showing Success:

![image](https://user-images.githubusercontent.com/6157895/126240281-d4734e2f-1df1-4c4d-a6fc-751c1731293e.png)

## Current Behavior

This did work before the latest update but the entity is no longer showing up in the catalog even though the output shows it was and the catalog-info.yaml file is generated as expected, i also don't see the links as well when using output.links in the template. 

Here is what i see in the logs:

`2021-07-19T23:07:17.387Z catalog warn Unable to read url, NotFoundError: https://my-bitbucket-server.com/projects/MY-PROJECT/repos/MY-REPO/browse/catalog-info.yaml could not be read as https://my-bitbucket-server.com/rest/api/1.0/projects/MY-PROJECT/repos/MY-REPO/raw/catalog-info.yaml?at=, 404 Not Found type=plugin entity=location:default/generated-80a9272e9d90df1fc0abb152730fb9f5b2221490`

When i try hitting `https://my-bitbucket-server.com/rest/api/1.0/projects/MY-PROJECT/repos/MY-REPO/raw/catalog-info.yaml?at=` or just `https://my-bitbucket-server.com/rest/api/1.0/projects/MY-PROJECT/repos/MY-REPO/raw/catalog-info.yaml` i get the following response: 

`{"errors":[{"context":null,"message":"The path \"catalog-info.yaml\" does not exist at revision \"refs/heads/master\"","exceptionName":"com.atlassian.bitbucket.content.NoSuchPathException"}]}`

I also tried adding a `defaultBranch` in the publish step as follows, and get the same result:

```
    - id: publish
      name: Publish to a New Bitbucket Repository
      action: publish:bitbucket
      input:
        repoUrl: 'my-bitbucket-server.com?owner={{ parameters.projectKey}}&repo={{ parameters.repoName}}'
        defaultBranch: master
```

I also have the bitbucket discovery processor enabled both in my app-config.yaml and catalog.ts as follows:

```
// app-config.yaml

  locations: 
      - type: bitbucket-discovery
        target: https://my-bitbucket-server.com/projects/*/repos/*/catalog-info.yaml
        rules:
          - allow: [Location, Component, API, Resource, Domain]
          
// packages/backend/plugins/catalog.ts

  builder.replaceProcessors([
    new FileReaderProcessor(),
    BitbucketDiscoveryProcessor.fromConfig(env.config, { logger: env.logger }),
    LdapOrgReaderProcessor.fromConfig(env.config, { logger: env.logger }),
    new UrlReaderProcessor({ reader: env.reader, logger: env.logger }),
    new LocationEntityProcessor({ integrations }),
    new AnnotateLocationEntityProcessor({ integrations }),
  ]);
```

A similar issue has been reported for GitHub as well: 

https://discord.com/channels/687207715902193673/687235481154617364/866739920340910091

## Your Environment

- NodeJS Version (v12): Node14
- Operating System and Version (e.g. Ubuntu 14.04): Windows 10
- Browser Information: Chrome
- Bitbucket Server 7.12.1
