### ISSUE TITLE
Logs are not displaying while publishing the catalog to GitHub

### ISSUE THREAD

**Issue by mysticmode** [backstage/backstage#6546]
I'm trying to setup Backstage on Ubuntu 20.04 VPS. My problem is that when I try to "Choose" a template and publish it to GitHub, the logs are not getting displayed. I have tried this in both simply `yarn dev` or setting up a multistage `Dockerfile` and running it.

NOTE: The repository is getting published to GitHub fine. In other words, I can see the template that I want to deploy to GitHub fine. It is just that the `/create/task/<task-id>` says "Waiting for logs".

When I opened the Firefox console, it says this error:
`Firefox can’t establish a connection to the server at https://magna5.mysticmo.de/api/scaffolder/v2/tasks/f78f941e-3e05-4967-93b1-77dbd7034b7f/eventstream.`

Docker is installed -> Docker version 20.10.7

## Expected Behavior

The logs should get displayed.

## Current Behavior

Repository is getting deployed on GitHub, logs for that are not working.

<img width="1788" alt="image" src="https://user-images.githubusercontent.com/1125199/126271041-041edbf7-766b-43e2-abe6-8d2ad1d5823d.png">

## Steps to Reproduce

1. Create new app using `npx @backstage/create-app`
2. Write the app-config.local.yaml configuration (shown below)
3. `yarn install && yarn tsc && yarn build`
4. `yarn dev`

## Context

Template - https://github.com/magna5-test/golang-rest-template

1. app-config.yaml
```
app:
  title: Scaffolded Backstage App
  baseUrl: http://localhost:3000

organization:
  name: My Company

backend:
  baseUrl: http://localhost:7000
  listen:
    port: 7000
  csp:
    connect-src: ["'self'", 'http:', 'https:']
    # Content-Security-Policy directives follow the Helmet format: https://helmetjs.github.io/#reference
    # Default Helmet Content-Security-Policy values can be removed by setting the key to false
  cors:
    origin: http://localhost:3000
    methods: [GET, POST, PUT, DELETE]
    credentials: true
  # config options: https://node-postgres.com/api/client
  database:
    client: pg
    connection:
      host: ${POSTGRES_HOST}
      port: ${POSTGRES_PORT}
      user: ${POSTGRES_USER}
      password: ${POSTGRES_PASSWORD}
      # https://node-postgres.com/features/ssl
      #ssl: require # see https://www.postgresql.org/docs/current/libpq-ssl.html Table 33.1. SSL Mode Descriptions (e.g. require)
        #ca: # if you have a CA file and want to verify it you can uncomment this section
        #  $file: <file-path>/ca/server.crt
  cache:
    store: memory
  # workingDirectory: /tmp # Use this to configure a working directory for the scaffolder, defaults to the OS temp-dir

integrations:
  github:
    - host: github.com
      token: ${GITHUB_TOKEN}
    ### Example for how to add your GitHub Enterprise instance using the API:
    # - host: ghe.example.net
    #   apiBaseUrl: https://ghe.example.net/api/v3
    #   token: ${GHE_TOKEN}

proxy:
  '/test':
    target: 'https://example.com'
    changeOrigin: true

# Reference documentation http://backstage.io/docs/features/techdocs/configuration
# Note: After experimenting with basic setup, use CI/CD to generate docs
# and an external cloud storage when deploying TechDocs for production use-case.
# https://backstage.io/docs/features/techdocs/how-to-guides#how-to-migrate-from-techdocs-basic-to-recommended-deployment-approach
techdocs:
  builder: 'local' # Alternatives - 'external'
  generators:
    techdocs: 'docker' # Alternatives - 'local'
  publisher:
    type: 'local' # Alternatives - 'googleGcs' or 'awsS3'. Read documentation for using alternatives.

auth:
  # see https://backstage.io/docs/auth/ to learn about auth providers
  providers: {}

scaffolder:
  github:
    token: ${GITHUB_TOKEN}
    visibility: public # or 'internal' or 'private'

catalog:
  rules:
    - allow: [Component, System, API, Group, User, Resource, Location]
  locations:
    ...
```

2. app-config.local.yaml
```
app:
  title: Magna5 Backstage portal
  baseUrl: https://magna5.mysticmo.de

backend:
  baseUrl: https://magna5.mysticmo.de
  client: pg
  connection:
    host:
      $env: POSTGRES_HOST
    port:
      $env: POSTGRES_PORT
    user:
      $env: POSTGRES_USER
    password: 
      $env: POSTGRES_PASSWORD
    database:
      $env: POSTGRES_DATABASE

organization:
  name: Magna5 Backstage portal

auth:
  providers:
    github:
      development:
        clientId:
          $env: AUTH_GITHUB_CLIENT_ID
        clientSecret:
          $env: AUTH_GITHUB_CLIENT_SECRET

integrations:
  github:
    - host: github.com
      token:
        $env: GITHUB_TOKEN

scaffolder:
  defaultAuthor:
    name: Nirmal Almara
    email: hello@nlmara.com
  github:
    token:
      $env: GITHUB_TOKEN


techdocs:
  builder: 'local'
  publisher:
    type: 'local'
  generators:
    techdocs: local

catalog:
  processors:
    githubOrg:
      providers:
        - target: https://github.com
          token:
            $env: GITHUB_TOKEN
  rules:
    - allow: [Component, System, API, Group, User, Resource, Location]
  locations:
    - type: url
       target: https://github.com/magna5-test/golang-rest-template/blob/master/template.yaml
```

## Your Environment

- NodeJS Version (v12): v14.17.2
- Operating System and Version (e.g. Ubuntu 14.04): Ubuntu 20.04
- Browser Information: Firefox 89.0.2
