### ISSUE TITLE
catalog register action: failing for bitbucket server

### ISSUE THREAD

**Issue by kiranpatel11** [backstage/backstage#6658]
The build-in scaffolder action for catalog register failed with below exception when used with on-prem Bitbucket Server.

## Expected Behavior

The error should not come and scaffolded entity should get registered with backstage catalog.

## Current Behavior

register action is failing with below exception : 

```
2021-07-30T01:43:09.265Z Beginning step Register
2021-07-30T01:43:09.321Z TypeError: Cannot read property 'length' of undefined
    at defaultScmResolveUrl (/usr/src/app/packages/backend/dist/index.cjs.js:39919:91)
    at _BitbucketIntegration.resolveUrl (/usr/src/app/packages/backend/dist/index.cjs.js:40046:22)
    at Object.handler (/usr/src/app/node_modules/@backstage/plugin-scaffolder-backend/dist/index.cjs.js:125:38)
    at TaskWorker.runOneTask (/usr/src/app/node_modules/@backstage/plugin-scaffolder-backend/dist/index.cjs.js:2704:24)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async /usr/src/app/node_modules/@backstage/plugin-scaffolder-backend/dist/index.cjs.js:2606:9
```

## Your Environment

Snippet of the template.yaml
```
  parameters:
    - title: Enter Documentation Details
      required:
        - name
        - description
      properties:
        name:
          title: Name
          type: string
          description: Unique name of the component
          ui:autofocus: true
          ui:options:
            rows: 5
        description:
          title: Description
          type: string
          description: A description for the component
          ui:options:
            rows: 5
        owner:
          title: Owner
          type: string
          description: Owner of the component
          ui:field: OwnerPicker
          ui:options:
            allowedKinds:
              - Group
    - title: Choose a SCM location
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - my-bitbucket.company.com

  steps:
    - id: fetch
      name: Template Docs Skeleton
      action: fetch:cookiecutter
      input:
        url: ./skeleton
        values:
          name: '{{ parameters.name }}'
          description: '{{ parameters.description }}'
          destination: '{{ parseRepoUrl parameters.repoUrl }}'
          owner: '{{ parameters.owner }}'

    - id: publish
      name: Publish
      action: publish:bitbucket
      input:
        allowedHosts: ['my-bitbucket.company.com']
        description: This is {{ parameters.name }}
        repoUrl: '{{ parameters.repoUrl }}'

    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: '{{ steps.publish.output.repoContentsUrl }}'
        catalogInfoPath: '/catalog-info.yaml'

  output:
    remoteUrl: '{{ steps.publish.output.remoteUrl }}'
    entityRef: '{{ steps.register.output.entityRef }}'
```

- NodeJS Version : v14
- Operating System and Version : Alpine Linux 
- Browser Information: Chrome

**Comment by regicsolutions** [comment]
I ran into this error as well in Bitbucket Server 7x and was able to get passed it by just adding `browse `in front of `catalog-info.yaml 
`
```
    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: '{{ steps.publish.output.repoContentsUrl }}'
        catalogInfoPath: 'browse/catalog-info.yaml'
```
