### ISSUE TITLE
Gitlab Techdocs endpoints going bad

### ISSUE THREAD

**Issue by DanArlowski** [backstage/backstage#6700]
When using annotation `backstage.io/techdocs-ref: dir:./relative` the techdocs scaffold for an incorrect path when the 

## Expected Behavior

should look in the correct repository path and not its parent's

## Current Behavior

repositroy have another directory: 
`https://gitlab.com/org/subfolder/repo`
it looks in:
`https://gitlab.com/org/subfolder`

## Possible Solution
tried to add the repository as a relative path prefix, and it still not working

## Steps to Reproduce

1. Gitlab with dir in the org
2. try to attach techdocs-ref to this repository
3. when building in`yarn dev` and moving to the api window you'll get an error

## Your Environment

- NodeJS Version (v12):  14.17.3
- Operating System and Version (e.g. Ubuntu 14.04): MacOs 10.15.7
- Browser Information: brave..

##logs
```
[1] 2021-08-03T13:02:56.363Z techdocs error Failed to build the docs page: Failed to read tree from https://gitlab.com/org/dir/, 404 Not Found Failed to read tree from https://gitlab.com/org/dir/, 404 Not Found type=plugin stack=Error: Failed to read tree from https://gitlab.com/org/dir/, 404 Not Found
[1]     at DocsBuilder.build (${FULL_BACKSTAGE_PATH}/node_modules/@backstage/plugin-techdocs-backend/dist/index.cjs.js:127:13)
[1]     at processTicksAndRejections (internal/process/task_queues.js:95:5)
[1]     at async DocsSynchronizer.doSync (${FULL_BACKSTAGE_PATH}/node_modules/@backstage/plugin-techdocs-backend/dist/index.cjs.js:212:23)
[1]     at async ${FULL_BACKSTAGE_PATH}/node_modules/@backstage/plugin-techdocs-backend/dist/index.cjs.js:302:7
```

**Comment by dhenneke** [comment]
The URL resolution is done by the `@backstage/integrations` library. Currently, the GitLabOntegration uses the default resolver: https://github.com/backstage/backstage/blob/a88073c29afb0f1e9b591f8c5a0f2e1e992075b9/packages/integration/src/gitlab/GitLabIntegration.ts#L54

There aren't any tests for the `resolveUrl` function in GitLab so I wouldn't be surprised if it actually doesn't work yet: https://github.com/backstage/backstage/blob/e013dbb7ace42c28a605c0a6532deb4de507863f/packages/integration/src/gitlab/GitLabIntegration.test.ts

Could you provide some example links for some basic and complex project setups? Interesting are the values of the annotations of the entity in the catalog: `annotations.backstage.io/source-location`, `annotations.backstage.io/managed-by-location`, `annotations.backstage.io/techdocs-ref`. Feel free to anonymize the folder and project names as long as the structure stays intact.

**Comment by DanArlowski** [comment]
so I was doing a quick search in gitlab, getting some public repos for you to enquire
https://gitlab.com/vicmanbrile_group/personal/guides/node-vanila
as you can see, there is a full path over dir with many subfolders (you can infer to it as small orgs inside bigger orgs :) )


I was just trying to do a POC with backstage,
If im allowed to rant a bit - I think the On boarding is super complex for nothing - I want the default configs and short- quick start on to how to on board my own Components and stuff - i think CLI based may be good - will open a Feature request for it in a few.

annotations:

```
backstage.io/edit-url: "https://gitlab.com/org/dir1/repo1/-/edit/master/catalog/components/service-component.yaml"
backstage.io/managed-by-location: "url:https://gitlab.com/org/dir1/repo1/-/blob/master/catalog/components/service-component.yaml"
backstage.io/managed-by-origin-location: "url:https://gitlab.com/org/dir1/repo1/-/blob/master/catalog/all.yaml"
backstage.io/source-location: "url:https://gitlab.com/org/dir2/repo2" #the repo of the component
backstage.io/techdocs-ref: "dir:."
backstage.io/view-url: "https://gitlab.com/org/dir1/repo1/-/blob/master/catalog/components/service-component..yaml"

```

**Comment by dhenneke** [comment]
I tested in an on-premise GitLab (v14.1.x) installation but can't reproduce your error.

Here's what I did:
* I used `yarn dev` at the latest `master` commit of https://github.com/backstage/backstage
* I created two repositories `https://gitlab.<private>.com/a-test-group/repository-1` and `https://gitlab.<private>.com/a-test-group/another-group/another-repository`
* Each repo has a `catalog-info.yaml` with two components. One with a `backstage.io/techdocs-ref: dir:.` and one with a `backstage.io/techdocs-ref: dir:./subfolder`.
* Both use the following directory layout:
```
├── catalog-info.yaml
├── mkdocs.yml
├── docs
    └── index.md
└── subfolder
    └── mkdocs.yml
    └── docs
        └── index.md
```
* I registered `https://gitlab.<private>.com/a-test-group/repository-1/-/blob/master/catalog-info.yaml` and `https://gitlab.<private>.com/a-test-group/another-group/another-repository/-/blob/master/catalog-info.yaml`
* I visited the docs page so Back

<details>
<summary>catalog-info.yaml</summary>

```yaml
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  annotations:
    backstage.io/techdocs-ref: dir:.
  name: repository-2-1
  description: A short description as a display text.
spec:
  type: service
  owner: nobody
  lifecycle: production
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  annotations:
    backstage.io/techdocs-ref: dir:./subfolder
  name: repository-2-2
  description: A short description as a display text.
spec:
  type: service
  owner: nobody
  lifecycle: production
```
</details>

<details>
<summary>Entity from /api/entitites/repository-1-1</summary>

```json
{
    "metadata":
    {
        "namespace": "default",
        "annotations":
        {
            "backstage.io/managed-by-location": "url:https://gitlab.<private>.com/a-test-group/repository-1/-/blob/master/catalog-info.yaml",
            "backstage.io/managed-by-origin-location": "url:https://gitlab.<private>.com/a-test-group/repository-1/-/blob/master/catalog-info.yaml",
            "backstage.io/view-url": "https://gitlab.<private>.com/a-test-group/repository-1/-/blob/master/catalog-info.yaml",
            "backstage.io/edit-url": "https://gitlab.<private>.com/a-test-group/repository-1/-/edit/master/catalog-info.yaml",
            "backstage.io/source-location": "url:https://gitlab.<private>.com/a-test-group/repository-1/-/blob/master/",
            "backstage.io/techdocs-ref": "dir:."
        },
        "name": "repository-1-1",
        "description": "A short description as a display text.",
        "uid": "2906a39b-d5fd-48a2-8692-b11d54f2c58b",
        "generation": 1,
        "etag": "a15d56a620392637059733482dd12f4875629dd9"
    },
    "apiVersion": "backstage.io/v1alpha1",
    "kind": "Component",
    "spec":
    {
        "type": "service",
        "owner": "nobody",
        "lifecycle": "production"
    },
    "relations":
    [
        {
            "type": "ownedBy",
            "target":
            {
                "kind": "group",
                "namespace": "default",
                "name": "nobody"
            }
        }
    ]
}
```
</details>

I would expect that this should also work with the SaaS version at gitlab.com. Could you prove some more information where your repo setup differs from my test?

**Comment by DanArlowski** [comment]
first of all - thanks for your help and time, it does not go unnoticed!

As Im running on a local postgres instance - so to make sure nothing god "cached", I scratched the psql and recreated it.

My Configuration is as follows

a backstage `Location` kind which sits in a general repository `...com/org/dir/repo`
```yaml
apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name:components
  description: A collection of all components

spec:
  targets:
    - https://gitlab.com/org/anotherdir/repo/-/blob/backstage/backstage-catalog.yaml #backstage is the branch for dev purposes as this is a POC
```

the above target have the following configuration:
<details><summary>backstage-catalog.yaml</summary>
<p>

```yaml
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: the-component
  description: this is the component in anotherdir/repo at backstage branch #this is a temp branch for the POC of backstage
  tags:
    - golang
    - deployment
    - cicd
  links:
    - url: https://gitlab.com/org/anotherdir/repo
      title: Gitlab
      icon: dashboard
  annotations:
    backstage.io/techdocs-ref: dir:.
    backstage.io/source-location: url:https://gitlab.com/org/anotherdir/repo
spec:
  type: service
  lifecycle: production
  owner: nobody
  system: general
```
</p>
</details>

then when doing `yarn dev` (I was generating the directory using the CLI -`npx @backstage/create-app` so I kinda guess its the latest master )
the system comes up, and `the-component` is showing up.

but when trying to click on the docs, I get thrown out with the error from above without the full path coming up


another info:

the repository that holds the `backstage-catalog.yaml ` have the following:

<details><summary>backstage-catalog.yaml repo files</summary>
<p>
```bash
$ cat mkdocs.yaml
site_name: 'the-component'
site_description: 'Documentation for the-component'

plugins:
  - techdocs-core

nav:
  - Overview:
      - goal?: 'overview/goal.md'

$ ls #ommited everything unrelevant for our issue
docs 
backstage-catalog.yaml
mkdocs.yml

$ tree docs 
docs
└── overview
    └── goal.md

1 directory, 1 file
```
</p>
</details>

the error that gets thrown out is (as above):

```
[1] 2021-08-04T06:48:57.096Z techdocs error Failed to build the docs page: Failed to read tree from https://gitlab.com/org/anotherdir/, 404 Not Found Failed to read tree from https://gitlab.com/org/anotherdir/, 404 Not Found type=plugin stack=Error: Failed to read tree from https://gitlab.com/org/anotherdir/, 404 Not Found
[1]     at DocsBuilder.build ${FULL_LOCAL_PATH}/node_modules/@backstage/plugin-techdocs-backend/dist/index.cjs.js:127:13)
[1]     at processTicksAndRejections (internal/process/task_queues.js:95:5)
[1]     at async DocsSynchronizer.doSync (${FULL_LOCAL_PATH}/node_modules/@backstage/plugin-techdocs-backend/dist/index.cjs.js:212:23)
[1]     at async ${FULL_LOCAL_PATH}/node_modules/@backstage/plugin-techdocs-backend/dist/index.cjs.js:302:7
```
