### ISSUE TITLE
ECONNRESET error from the proxy inside EKS kubernetes clusters

### ISSUE THREAD

**Issue by josephkurian** [backstage/backstage#6766]
Hi There,

We are developing a backstage.io backed developer portal with a custom backend plugin that invokes Rest API calls to some of our backend services. We have configured the HPM proxy to make the calls to these APIs as advised in the docs : https://backstage.io/docs/plugins/proxying ,
We have deployed the portal in an EKS cluster using the Postgres backend and an nginx ingress based AWS network loadbalancer to serve as the entry point to the portal. 
I am facing an issue where about 30-40 % of the times , the backend API calls made by the proxy loads really slow and from the backstage pod logs I notice that whenever this happens, I get the error 

proxy error [HPM] Error occurred while trying to proxy request </requestpath> from <backstage-dns-url> to <targetbackendurl> (ECONNRESET) (https://nodejs.org/api/errors.html#errors_common_system_errors) type=plugin

One thing I noted is that almost always when I get this error, the time it takes to get the response is exactly one min. 

EKS K8 version: 1.17 

Inside the docker container: 

root@backstage-c7786ddfb-ck7b6:/app# npm --version
6.14.14
root@backstage-c7786ddfb-ck7b6:/app# node --version
v14.17.4
root@backstage-c7786ddfb-ck7b6:/app# npm version
{
 root: '1.0.0',
 npm: '6.14.14',
 ares: '1.17.1',
 brotli: '1.0.9',
 cldr: '39.0',
 icu: '69.1',
 llhttp: '2.1.3',
 modules: '83',
 napi: '8',
 nghttp2: '1.42.0',
 node: '14.17.4',
 openssl: '1.1.1k',
 tz: '2021a',
 unicode: '13.0',
 uv: '1.41.0',
 v8: '8.4.371.23-node.76',
 zlib: '1.2.11'
}

Wondering if anyone has faced similar issues and if I can get some help?

Thank you.

**Comment by freben** [comment]
So from the point of view of the Backstage proxy package, it looks like a request timeout. Only that something intermediate implements that timeout in terms of abruptly killing the connection.

What are the characteristics of the service being called? Can you double check that it does respond promptly (far less than one minute response time at least) from that zone?

If it can be established for sure that the remote service is not at fault, then I guess what remains is the intermediate layers. I am honestly not sure what will be between the node process and the remote; could there be a reverse proxy / load balancer in between that implements that timeout, or even worse, could cause some flakiness?

**Comment by mustafa89** [comment]
struggling with this. Did you figure out what was happening? Our set up is ALB > EKS

**Comment by stephanschielke** [comment]
I'm sporadically running into the same error when a custom search collator is trying to fetch information from an external API through the forwarding proxy:
![image](https://user-images.githubusercontent.com/401815/210881821-b76d8bf0-a3c3-448f-a6fb-b9de9dfad1c8.png)

Ideally, I would like to test if increasing the timeout for the requests is sufficient.
Alternatively, I will test if a simple retry logic helps solve those errors.

@freben is there any chance to set the timeout for requests that go through the forwarding proxy?
```
proxy:
  '/proxy/endpoint':
    target: 'https://external-site.com'
    timeout: 5000
```
I can't find a configuration for this when generating my config (`yarn backstage-cli config:schema`):
```
  proxy:
    description: |-
      A list of forwarding-proxies. Each key is a route to match,
      below the prefix that the proxy plugin is mounted on. It must
      start with a '/'.
    type: object
    additionalProperties:
      anyOf:
        - type: object
          properties:
            target:
              description: Target of the proxy. Url string to be parsed with the url module.
              type: string
            headers:
              description: Object with extra headers to be added to target requests.
              type: object
              additionalProperties:
                type: string
            changeOrigin:
              description: "Changes the origin of the host header to the target URL. Default:
                true."
              type: boolean
            pathRewrite:
              description: >-
                Rewrite target's url path. Object-keys will be used as RegExp to
                match paths.

                If pathRewrite is not specified, it is set to a single rewrite that removes the entire prefix and route.
              type: object
              additionalProperties:
                type: string
            allowedMethods:
              description: "Limit the forwarded HTTP methods, for example allowedMethods:
                ['GET'] to enforce read-only access."
              type: array
              items:
                type: string
            allowedHeaders:
              description: >-
                Limit the forwarded HTTP methods. By default, only the headers that
                are considered safe for CORS

                and headers that are set by the proxy will be forwarded.
              type: array
              items:
                type: string
          required:
            - target
        - type: string
```
