### ISSUE TITLE
Can not use BitBucket Discovery with non-standard TCP port

### ISSUE THREAD

**Issue by DavidZemon** [backstage/backstage#6828]
## Expected Behavior

I expect to be able to utilize BitBucket discovery with a server listening on something other than port 80 or 443, with a config file like so:

```yaml
integrations:
  bitbucket:
    - host: localhost:8081
      username: my_user
      token: some_token
      apiBaseUrl: http://localhost:8081/rest/api/1.0

catalog:
  rules:
    - allow: [Component, System, API, Group, User, Template, Location]
  locations:
    - type: bitbucket-discovery
      target: http://localhost:8081/projects/foo/repos/*/catalog-info.yaml
```

## Current Behavior

BB discovery throws the following warning at app startup:

```txt
2021-08-13T19:05:35.370Z catalog warn Processor BitbucketDiscoveryProcessor threw an error while reading bitbucket-discovery:http://localhost:8081/projects/foo/repos/*/catalog-info.yaml; caused by Error:
 There is no Bitbucket integration that matches http://localhost:8081/projects/foo/repos/*/catalog-info.yaml. Please add a configuration entry for it under integrations.bitbucket type=plugin
```

## Possible Solution

Replace `parsed.hostname` with `parsed.host` in `basicIntegrations.byUrl()`

## Steps to Reproduce

Reproducing requires starting up a BB server on a non-standard port and is probably more trouble than it's worth. Instead, it's easier to look at why `parsed.hostname` is a bug:

```js
const parsed = new URL("http://localhost:8081/rest/api/1.0");
console.log(`Host: ${parsed.host}`); // localhost:8081
console.log(`Hostname: ${parsed.hostname}`); // localhost
```

## Your Environment

Verified on Linux NodeJS v10.19.0 and Windows NodeJS v14.17.4
