### ISSUE TITLE
Gitlab Catalog discovery and scanning

### ISSUE THREAD

**Issue by FlxPeters** [backstage/backstage#6843]
As a Gitlab user i want to discover my `catalog-info.yaml` files on all repositories accessible by a Backstage like it is possible for Bitbucket and Github. The discovery should work with Gitlab.com and self hosted Girtlab instances.

## Feature Suggestion

The discovery could be limited to a specific group or path by using wildcards like it is possible in the other discovery integration:

```
catalog:
  locations:
    - type: gitlab-discovery
      target: https://gitlab.com/group/subgroup/repo/-/blob/master/catalog-info.yaml
```

## Possible Implementation

Gitlab has a REST and GraphQL API which can be used to discover repos: https://docs.gitlab.com/ee/api/

On the REST API it's possible to scrape all repos a user has access to: https://docs.gitlab.com/ee/api/repositories.html
After discovery the file could be read using the existing Gitlab integration and URL reader.

GraphQL is also an option, but i never used it. 

## Context

Catalog scanning is a relevant thing for Backstage adoption because people do not have to register their components manually. Gitlab is a major platform in SCM and CI/CD, so it should have the same level of integration like Github and Bitbucket.
