### ISSUE TITLE
OIDC Auth plugin error - "Authentication failed, done is not a function"

### ISSUE THREAD

**Issue by 4integration** [backstage/backstage#6945]
## Expected Behavior
Working OIDC integration

## Current Behavior

1. Get "Sign In" button in Backstage
2. Opens a popup with our IdP login form
3. Successful login and popup closes
4. An error is shown in Backstage "**Authentication failed, done is not a function**"

Have I missed anything?

## Context
In `app-config.yaml`
```
auth:
  environment: development
  session:
    secret: SomeBackstageSecret
  providers:
    oidc:
      development:
        metadataUrl: https://auth.test.domain.net/token/internal/anonymous/.well-known/openid-configuration 
        clientId: my-backstage-app
        clientSecret: my-top-secret
        authorizationUrl: https://auth.test.domain.net/token/internal/authorize
        tokenUrl: https://auth.test.domain.net/token/internal/token
        # tokenSignedResponseAlg: ${AUTH_OIDC_TOKEN_SIGNED_RESPONSE_ALG} # default='RS256'
        # scope: ${AUTH_OIDC_SCOPE} # default='openid profile email'
        prompt: auto # default=none (allowed values: auto, none, consent, login)
```
and corresponding in `App.tsx`
```
import { oidcAuthApiRef } from '@backstage/core-plugin-api';
import { SignInProviderConfig, SignInPage } from '@backstage/core-components';

const oidcProvider: SignInProviderConfig = {
  id: 'oidc-auth-provider',
  title: 'Curity',
  message: 'Sign in using Curity',
  apiRef: oidcAuthApiRef,
};

const app = createApp({
  apis,
  components: {
    SignInPage: props => (
      <SignInPage
        {...props}
        auto
        provider={oidcProvider}
      />
    ),
  },
... etc
```

## Your Environment

- **NodeJS Version**: v14.17.4
- **Operating System and Version**: Ubuntu 20.04 in WSL + devcontainers
- **Browser Information**: Chrome  92.0.4515.159
- **IdP**: Curity Identity Server
