### ISSUE TITLE
Allow nesting of templates

### ISSUE THREAD

**Issue by jalet-pp** [backstage/backstage#6964]
## Feature Suggestion

Allow actions to call other actions by allowing a new keyword called `template`(?) in a step definition.

## Possible Implementation

```
# foo.yaml
  steps:
    - id: some-id1
      action: fetch:template
      ...
    - id: some-id2
      action: tld:action

# bar.yaml
  steps
    - id: some-id
      template: foo <--- should execute the steps in foo.yaml 
```

## Context

When building for a bigger organization with some amount of legacy and a lot of existing repositories/services/libraries it's almost impossible to not have them diverge from a "golden path" or "standard". By allowing templates to call other templates we can break our actions into smaller pieces and offer them one by one or composed together. T

his could lower the burden of maintaining a "golden path" template for how to scaffold say a microservice. For instance, starting work on a new microservice may contain a GH repo, a DNS name, a k8s or ECS configuration, terraform or CDK for infrastructure, CI/CD pipelines, and configuration.

All of these small parts would then be their own template which can be executed on an already existing microservice, or they can be composed and executed in sequence to create a new microservice.

```
  steps
    - id: some-id1
      template: python-service

    - id: some-id2
      template: container-registry

    - id: some-id3
      template: aws-lambda
      
    - id: some-id4
      template: api-gateway

    - id: some-id
      template: jenkins
```
