### ISSUE TITLE
[kubernetes-backend-plugin] Extend kubernetes backend plugin to provide a dynamic way to supply clusters

### ISSUE THREAD

**Issue by manusant** [backstage/backstage#6967]
## Feature Suggestion
Extend kubernetes backend plugin to provide a dynamic way to supply clusters using kubernetes secrets to import remote service account tokens and watchers to track their lifecycle.  In the end clusters are supplied to Backstage Kubernetes plugin in a dynamic way.

## Possible Implementation
Basically, we can use the a kubernetes client to watch local secrets with specific labels (to identify a remote cluster) and maintain a pool of connected clusters. Then the clusters supplier can be binded to the current plugin and the magic happens:
* If we want to add a new cluster we just create a new secret using kubectl or other devops tool in the cluster where Backstage is deployed.
* Updating a cluster secret will be automatically "watched" and also updated in Backstage
* Deleting a cluster secret will remove the cluster from Backstage

A remote cluster secret should be something like:
---------------------------------------------------
```yaml
apiVersion: v1
data:
  ca.crt: ...
  config: ...
  namespace: ...
  server: ...
  token: ...
kind: Secret
metadata:
  labels:
    backstage.io/remote-cluster-secret: "true"
    backstage.io/remote-cluster-name: cluster-name
  name: cluster-name-mcsa-token-vrv4q
  namespace: chosen-namespace
type: Opaque
```
In this case the label **backstage.io/remote-cluster-secret: "true"** identifies a secret as a remote cluster holder and **backstage.io/remote-cluster-name** label provides the cluster name. Both labels should be configurable when configuring the **clusterLocatorMethods** in **app-config.yaml**.

Configuration
---------------
We propose a new _type_ called "_**auto**_" where we can configure the 2 mentioned labels used to select the secret and extract info.

```yaml
kubernetes:
  serviceLocatorMethod:
    type: 'multiTenant'
  clusterLocatorMethods:
    - type: 'watcher'
      labelSelector: 'backstage.io/remote-cluster-secret=true'
      labelClusterName: 'backstage.io/remote-cluster-name'
```

Code changes
---------------
In terms of code we believe that this can be supported by providing an implementation of **KubernetesClustersSupplier** and providing it to the plugin. The only issue is that the current implementation assumes that clusters info is static and some other components of the plugin should be adapted in order to make the clusters retrieval completely dynamic through the **_getClusters(): Promise<ClusterDetails[]>_** function of the interface (**_No more ClusterDetails[] being passed as arguments of components... should be the supplier itself_**).

## Context
At Mercedes-Benz.io we are using backstage to build a developer portal and we want to integrate the kubernetes plugin and connect it to a huge number of clusters (and growing) and we want to implement an automatic way of supplying the clusters.

We already use kubernetes service account secrets to provide multi-cluster linking for service discovery (used for some internal tools) and we want to use the same approach to load clusters into backstage in an automated way.
