### ISSUE TITLE
LastChecked field to catalog-info.yaml

### ISSUE THREAD

**Issue by nicorikken** [backstage/backstage#7059]
## Feature Suggestion

_**This is mostly a suggestion** I just wanted to test the waters to hear what others think of this and get a discussion going._

Adding a field to the metadata about when the information was last checked **by a human**.
This can be a starting point for checking how current the information is, and if it should be reviewed.

```yaml
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: artist-web
  description: The place to be, for great artists
  lastChecked: "2021-09-03"  # <<== addition
spec:
  ...
```

### Custom annotation

Of course there is no need of integrating it in the spec directly, and it can be added by anyone. But ideally it would be part of the specification so some automation can be build around it.

```yaml
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: artist-web
  description: The place to be, for great artists
  annotations:
  mycompany.com/last-checked: "2021-09-03"
spec:
  ...
```
### Checking the file date

One could also check the version control system for the last time the file was updated. But then there is the risk that the files are updated by different causes like migrations or automated tooling. Adding a field would make it independent from the storage solution.

## Context

We're looking into adopting Backstage. In our requirements, there was the idea of having a `lastChecked` property to explicitly state the last time the information was checked. This idea was taken from OpenStreetMap [wiki:check_date](https://wiki.openstreetmap.org/wiki/Key:check_date) where the tag is added to entities. It is used in automations like the StreetComplete app to ask for a human review if an object hasn't been checked for over a year ("Is this still here?"). A similar automation to ask for review of old information could be done in Backstage to ensure current information.
