### ISSUE TITLE
Software Template Array Form Missing Styling

### ISSUE THREAD

**Issue by asummers** [backstage/backstage#7093]
Originally part of #7090 

## Expected Behavior

The UI should be styled like the other form elements.

## Current Behavior

Consider the following software template:

```yaml
apiVersion: backstage.io/v1beta2
kind: Template
metadata:
  name: add-addon
  title: Addon
  description: Add addon
spec:
  owner: users
  type: website

  parameters:
    - title: Values
      properties:
       should-be-list:
          title: This is a title and is huge
          description: "this is a description you can't see"
          type: array
          items:
            type: string
  steps:
    - id: fetch-repo
      name: Fetch repo
      action: fetch:plain
      input:
        url: 'https://github.com/asummers/backstage/tree/master'

    - id: fetch-template
      name: Fetch Template
      action: fetch:template
      input:
        url: ./template2
        values:
          list: '{{parameters.should-be-list}}'

    - id: publish
      name: Publish
      action: publish:github:pull-request
      input:
        repoUrl: 'github.com?owner=asummers&repo=backstage'
        title: 'feat: Add addon'
        branchName: 'add-addon'
        description: |
          Add addon

  output:
    links:
      - url: '{{steps.publish.output.remoteUrl}}'
        text: 'Go to PR'

```

Styling wise, we have a few issues with the form that gets created. 
![Screen Shot 2021-09-07 at 10 07 10 AM](https://user-images.githubusercontent.com/831648/132370048-040b7185-d5fe-4cc6-b0e9-9d51dff92954.png)
![Screen Shot 2021-09-07 at 10 07 22 AM](https://user-images.githubusercontent.com/831648/132370052-3fb9b634-f58e-4da0-826f-eee9361d37b8.png)
![Screen Shot 2021-09-07 at 10 29 27 AM](https://user-images.githubusercontent.com/831648/132371607-a6cfd76d-dd5e-48c6-b06c-41174193e411.png)

## Possible Solution

Fix CSS for form.

## Steps to Reproduce

See ## Current Behavior

## Your Environment

- NodeJS Version (v12): 14
- Operating System and Version (e.g. Ubuntu 14.04): Ubuntu 18.04
- Browser Information: Chrome
