### ISSUE TITLE
Can't pass number from template to custom action step

### ISSUE THREAD

**Issue by ConnorDY** [backstage/backstage#7105]
## Expected Behavior

Using the `number` type for a custom action's input should work.

## Current Behavior

It appears there is no way to pass a number type from a custom template to a custom action step.

The following error occurs:
```
InputError: Invalid input passed to action uip:argocd-deploy, instance.port is not of a type(s) number
```

## Possible Solution

¯\\\_(ツ)\_/¯

## Steps to Reproduce

1. In the template, define a property like so:

```yaml
port:
  title: Port
  type: integer
  default: 8080
```

2. Pass that property to an action

```yaml
- id: custom-action
  name: Custom Action Name
    action: custom:action
    input:
      port: '{{ json parameters.port }}' # I have also tried '{{ parameters.port }}' with and without quotes
```

3. In the action define the input property with the `number` type:

```typescript
{
  id: 'custom:action',
  schema: {
    input: {
      type: 'object',
      properties: {
        port: {
          type: 'number',
          title: 'Port',
          description: 'The port the service runs on.'
        }
      }
    }
  }
}

4. Try to use the template and see the error.
```

## Context

I can workaround this by using the `string` type and using `Number.parseInt()` so this isn't a blocker.

## Your Environment

N/A
