### ISSUE TITLE
File Modes Getting Lost In Software Templates

### ISSUE THREAD

**Issue by asummers** [backstage/backstage#7144]
## Expected Behavior

Consider the following repo state:

```
$ stat -f %A test.sh
755
```

and the following template

```
apiVersion: backstage.io/v1beta2
kind: Template
metadata:
  name: bug-report
  title: bug-report
  description: Add bug report
spec:
  owner: test
  type: test

  steps:
    - id: fetch-repo
      name: Fetch repo
      action: fetch:plain
      input:
        url: 'https://github.com/asummers/backstage/tree/master'

    - id: publish
      name: Publish
      action: publish:github:pull-request
      input:
        repoUrl: 'github.com?owner=asummers&repo=backstage'
        title: 'This PR has different file permissions'
        branchName: 'script-perms'
        description: |
          This is a bug

  output:
    links:
      - url: '{{steps.publish.output.remoteUrl}}'
        text: 'Go to PR'
```

As I am pulling and pushing to same repo, this should result in no changes to the `asummers/backstage` repo whatsoever.

## Current Behavior

What seems to be happening is `+x` (and possibly other) are being dropped along the way.

![Screen Shot 2021-09-10 at 12 16 05 PM](https://user-images.githubusercontent.com/831648/132892309-0c01cc8a-06d4-42aa-b1c7-592f958b4212.png)

## Possible Solution

Pass along file modes faithfully.

## Steps to Reproduce

See ## Current behavior

## Context

This makes using software templates extremely arduous in repos with scripts with manual correction to files.

## Your Environment

- NodeJS Version (v12): v14
- Operating System and Version (e.g. Ubuntu 14.04): OSX, Ubuntu 18.04
- Browser Information: N/A
