### ISSUE TITLE
Render markdown for description in software templates

### ISSUE THREAD

**Issue by estahn** [backstage/backstage#7151]
## Feature Suggestion

The `description` field in Software Template should be rendered via Markdown.

## Context

We would like to provide as much guidance to users as possible and a formatted description provide good visualisation on the important points. Additionally, we can provide links to more info.

```yaml
      properties:
        entity:
          title: Entity
          description: |
            Select the type of entity to create:

            - Resource (e.g. SQL Database, S3 Bucket, ...)
            - Component (e.g. backend service, data pipeline)
            - API

            Find more details in the (System Model)[https://backstage.io/docs/features/software-catalog/system-model] documentation.
          type: string
          enum:
            - component
            - resource
            - API

```
