### ISSUE TITLE
Software templates not showing "examples" below input field

### ISSUE THREAD

**Issue by estahn** [backstage/backstage#7169]
react-json-form provides a keyword `examples` which does not appear to work in software templates.

## Expected Behavior

Show examples below the input box:
![image](https://user-images.githubusercontent.com/362174/133194323-48a8e3bd-9c31-4864-a0f4-354d62df2988.png)

## Current Behavior

Nothing.

## Possible Solution

N/A

## Steps to Reproduce

Create a software template with the following field:

```
        annotations:
          title: Annotations
          description: Provide annotations add additional functionality.
          type: array
          items:
            type: object
            properties:
              name:
                title: Name
                type: string
                examples:
                  - github.com/project-slug
                  - backstage.io/kubernetes-label-selector
                  - argocd/app-name
              value:
                title: Value
                type: string
          ui:options:
            orderable: false
```
