### ISSUE TITLE
Software Templates should provide entire entity to templates

### ISSUE THREAD

**Issue by estahn** [backstage/backstage#7170]
## Feature Suggestion

The `EntityPicker` allows the selection of various entities. The templates only receive the entity name at the moment. It would be useful to provide the entire entity object to the templates.

## Possible Implementation

`resolveEntity` will populate the entire entity object into `parameters.provides-apis`.

```yaml
        provides-apis:
          title: APIs provided
          type: string
          description: Select the API this component provides.
          ui:field: EntityPicker
          ui:options:
            resolveEntity: true
            allowedKinds:
              - API
```

## Context

We are trying to reduce the number of inputs users have to provide to populate/bootstrap things.

**Comment by freben** [comment]
This is the intended behaviour. It's a pattern we are using in other places throughout: the entity ref is passed to the interested party, and then they turn around and use a catalog client to fetch the actual data they need. Your action can do the same. This turns out to be a pretty good simplicity / flexibility balance, we find.

I'll close as answered for now, but do speak up if this was not the answer you wanted or if we can clarify more.

**Comment by estahn** [comment]
@freben Thinking about it again, I suppose the better solution for this would be to provide a function which can be used in assigning parameters to return the entity object, e.g.

```yaml
my_entity: '{{ resolveEntity parameters.entityRef | json }}'
```

Do you think this could be provided natively by backstage?

**Comment by freben** [comment]
It could, but I'm not sure there's value. The code that reads `my_entity` might just as well do the lookup in typescript land.

**Comment by estahn** [comment]
@freben I'm not sure we're talking about the same thing. I should not have started with the solution ([XY problem](https://en.wikipedia.org/wiki/XY_problem)) but rather explained what we want to achieve.

We started with various templates, e.g. engineer onboarding which for example creates terraform code to create access to databases and other infrastructure. The user is usually already generated from the HR system, but the engineering manager goes to Backstage, selects the template, fills in a couple of things and selects the user entity. Currently, we require to fill out all the details that are already captured in the user entity, because we can't resolve that in the template.

I realise you already have `parseRepoUrl` which is similar to what I'm suggesting:

```
  steps:
    - id: fetch-base
      name: Fetch bootrap engineer template
      action: fetch:template
      input:
        url: templates/bootstrap-engineer/
        values:
          title: '{{ parameters.title }}'
          description: '{{ parameters.description }}'
          destination: '{{ parseRepoUrl parameters.repoUrl }}'
          user: '{{ entityRefResolver parameters.user }}'
```

Hopefull that explains it better and you see the value.
