### ISSUE TITLE
Remove Handlebars templating from `kind: Template` templates

### ISSUE THREAD

**Issue by benjdlambert** [backstage/backstage#7268]
## Feature Suggestion
Following the migration from `cookiecutter` to `nunjucks` with `fetch:template`, we want to deprecate and remove any older templating languages and just have one templater which can share helpers making `kind: Template` definitions easier to write, and also Templates skeletons themselves easier to write and easier to understand.

This ticket is a followup from the RFC which was closed here: #6437.

- We want to remove the `handlebars` templating logic from the `kind: Template` when writing the `spec` part.
- We want it to be easier to write templates
- We want to to have one templating language across Backstage to make it easier and more recognisable when writing templates.
- We want to have better support for more complex values in the templates, which should remove the need the `json` helper in `handlebars` templates which we currently have.

## Possible Implementation

- Create new `apiVersion` for `kind: Template`, `backstage/v1beta3`.
- This will allow us to write an entirely new format for the `spec` field and offer deprecation between the two versions.
- Support the template syntax of `${{ parameters.blah }}` in `spec` which would remove the need for wrapping the template syntax in `''` as `$` at the start will infer string.
- Look at a better solution for handling complex values from the `parameter` input so that we can handle them without having to use weird helpers, they should be treated like first class.

```yaml
parameters:
    - title: Fill in some steps
      properties:
        url:
          title: Url
          type: string
          description: Url to fetch
        options:
          title: Object input
          description: Test Object input
          ui:field: UrlOptionsPicker
          properties:
            isHttps:
              type: boolean

steps:
    - id: test
      name: Test Action
      action: custom:my-action
      input:
        url: ${{ parameters.url }}
        options: ${{ parameters.options }}
```

`options` in the `action` should be an object without any additional treatment, same goes for `number` fields and other types in `json schema`.
