### ISSUE TITLE
Custom fields in scaffolder templates don't work in nested dependencies (dependency of a dependency)

### ISSUE THREAD

**Issue by ConnorDY** [backstage/backstage#7343]
## Expected Behavior

Custom scaffolder fields should work in nested dependencies (for example, a dependency of a dependency).

## Current Behavior

Custom scaffolder fields don't display as expected when used for nested dependencies.

## Possible Solution

Use recursion to check all levels of dependencies instead of just the first level.

## Steps to Reproduce

Example `template.yaml`:

```yaml
- title: Section Title
      properties:
        field_one:
          title: Field One
          type: boolean
          description: Check me
          default: false
      dependencies:
        field_one:
          oneOf:
            - properties:
                field_one:
                  enum:
                    - true
                field_two:
                  title: Field Two
                  type: boolean
                  description: Check me too
                  default: false
              dependencies:
                field_two:
                  oneOf:
                    - properties:
                        field_two:
                          enum:
                            - true
                        field_three:
                          title: Field 3
                          type: string
                          ui:field: CustomField
                    - properties:
                        field_two:
                          enum:
                            - false
            - properties:
                field_one:
                  enum:
                    - false
```

In the above example `ui:field: CustomField` isn't used and instead a normal text input is used because of `type: string`.

## Context

Custom fields work fine in dependencies at the first level but not the second level (dependency of a dependency) or further. 

## Your Environment

N/A

**Comment by ConnorDY** [comment]
It seems this is relating to this piece of code:
https://github.com/backstage/backstage/blob/master/plugins/scaffolder/src/components/MultistepJsonForm/schema.ts#L91

If this could be updated to use recursion to check all levels of dependencies, this should solve the problem, right?

**Comment by timbonicus** [comment]
Another possibility I pointed out in Discord, if `definitions` were also [looked at here](https://github.com/backstage/backstage/blob/master/plugins/scaffolder/src/components/MultistepJsonForm/schema.ts#L29), then you might be able to do:

```yaml
- title: Section Title
    definitions:
      field_two:
        title: Field Two
        type: boolean
        description: Check me too
        default: false
      field_three:
        title: Field 3
        type: string
        ui:field: CustomField
    properties:
      field_one:
        title: Field One
        type: boolean
        description: Check me
        default: false
    dependencies:
      field_one:
        oneOf:
          - properties:
              field_one:
                enum:
                  - true
              "$ref": "#/definitions/field_two"
            dependencies:
              field_two:
                oneOf:
                  - properties:
                      field_two:
                        enum:
                          - true
                      "$ref": "#/definitions/field_three"
```

**Comment by ConnorDY** [comment]
This is something we are still interested in seeing fixed. I'm not sure if we will have the capacity to work on a solution ourselves however.

**Comment by benjdlambert** [comment]
Hey @ConnorDY,

Just noticed that this went stale again and thought I'd have a look at trying to reproduce this.

With this `template.yaml` this seems to render properly for me?

```yaml
apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: test-v1beta3
  title: Test v1beta3
  description: Test V1 Beta 3 Demo Templates
spec:
  type: website
  owner: team-a
  parameters:
    - title: Test
      properties:
        field_one:
          title: Field One
          type: boolean
          description: Check me
          default: false
      dependencies:
        field_one:
          oneOf:
            - properties:
                field_one:
                  enum:
                    - true
                field_two:
                  title: Field Two
                  type: boolean
                  description: Check me too
                  default: false
              dependencies:
                field_two:
                  oneOf:
                    - properties:
                        field_two:
                          enum:
                            - true
                        field_three:
                          title: Field 3
                          type: string
                          ui:field: OwnerPicker
                    - properties:
                        field_two:
                          enum:
                            - false
            - properties:
                field_one:
                  enum:
                    - false
  steps:
    - id: debug
      if: ${{ true === true }}
      name: Debug
      action: debug:log
      input:
        message: ${{ parameters.inputString }}
        extra: ${{ parameters.inputObject }}
```
