### ISSUE TITLE
Location should allow folder path

### ISSUE THREAD

**Issue by tszngai** [backstage/backstage#7403]
## Feature Suggestion
Hi team, currently a `location` type of catalog might look like this:
```yaml
apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: my-targets
  description: A list of catalog targets to be registered
spec:
  targets:
    - https://github.com/backstage/my-app/catalog-folder/target1.yaml
    - https://github.com/backstage/my-app/catalog-folder/target2.yaml
    - https://github.com/backstage/my-app/catalog-folder/target3.yaml
    - ...
```
From what I understand, the items under `spec.targets` must be a file path. In this case, if I want to add more targets, I will need to edit this file and commit to github. If we could allow folder path here, then we could register new targets without the need to commit to this file.

So ideally the file could look like this:
```yaml
apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: my-targets
  description: A list of catalog targets to be registered
spec:
  targets:
    - https://github.com/backstage/my-app/catalog-folder
    - ... # other folders
```
And when we want to register new target, we just need to put its catalog yaml in the `catalog-folder`. I'm sure this will greatly benefit many teams' automation process. Thanks!

## Possible Implementation

Not sure

## Context

Please see above section and let me know of any questions. Thanks!

**Comment by freben** [comment]
Hi! Most sources have support for locations on the form `https://github.com/backstage/my-app/catalog-folder/**/catalog-info.yaml` wherein it supports glob matching. Maybe that's something that helps out with your use case.

**Comment by tszngai** [comment]
@freben Thanks for the tips! Did not know about this at all. It's very helpful. Thanks!

**Comment by CoenWarmer** [comment]
Perhaps I am misunderstanding, but should this work?

```
apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: foo
  description: bar
spec:
  type: url
  target: https://github.com/org/baz/packages/**/*.yml
```
