### ISSUE TITLE
[New Relic Plugin] Support for multi accounts

### ISSUE THREAD

**Issue by tszngai** [backstage/backstage#7406]
## Feature Suggestion
Hi team, our company has about 15 new relic accounts and we would like to see if there's a way for the plugin to connect to all of the accounts.

## Possible Implementation
My thought is we could define proxy in the `app-config.yaml` this way:
```yaml
proxy:
  '/newrelic-account-1/apm/api':
    target: https://api.newrelic.com/v2
    headers:
      X-Api-Key: <my-key-1>
  '/newrelic-account-2/apm/api':
    target: https://api.newrelic.com/v2
    headers:
      X-Api-Key: <my-key-2>
  '/newrelic-account-3/apm/api':
    target: https://api.newrelic.com/v2
    headers:
      X-Api-Key: <my-key-3>
```
And then when using the `<NewRelicPage />` element, there should be a way to provide the `options.proxyPathBase` accordingly.

This is the current implementation: https://github.com/backstage/backstage/blob/9258c54f874b8ba1e5a916caa14bfbe47204322d/plugins/newrelic/src/api/index.ts#L79-L82
`DEFAULT_PROXY_PATH_BASE` is always used and user is not able to provide a custom `proxyPathBase` value.

## Context

Please let me know if anything is unclear. Thanks!
