### ISSUE TITLE
Emitted and renamed Entities is not Stitched and not marked orphan

### ISSUE THREAD

**Issue by kim5566** [backstage/backstage#7563]
Follow up this [issue](https://github.com/backstage/backstage/issues/7199).
I am with `"@backstage/plugin-catalog": "^0.7.0"`

have this in the apiPage
```
     <EntitySwitch>
      <EntitySwitch.Case if={isOrphan}>
        <Grid item xs={12}>
          <EntityOrphanWarning />
        </Grid>
      </EntitySwitch.Case>
    </EntitySwitch>
    <EntitySwitch>
      <EntitySwitch.Case if={hasCatalogProcessingErrors}>
        <Grid item xs={12}>
          <EntityProcessingErrorsPanel />
        </Grid>
      </EntitySwitch.Case>
    </EntitySwitch>
```
and this catalog-info.yaml

```yaml
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  owner: mock-team
  lifecycle: production
  providesApis:
  - API1
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: API1
spec:
  type: grpc
  lifecycle: experimental
  owner:  mock-team
  definition: |
    syntax = "proto3";
    option java_multiple_files = true;
    package helloworld;
    service Greeter {
      rpc SayHello (HelloRequest) returns (HelloReply) {}
    }
---
```

and I renamed an registered api API1 to API2
## Expected Behavior

I would expect either an orphan warning or a process error displayed on API1 page.
## Current Behavior

 But none of them shown. If comment out the [hash comparison block](https://github.com/backstage/backstage/blob/7ab55167d047efb60114cca32af39feacbea89ee/plugins/catalog-backend/src/next/DefaultCatalogProcessingEngine.ts#L174), items are re-stitched and the orphan status is shown up.
## Possible Solution

1. optional hashing 
2. I tried to log the [compared hash string](https://github.com/backstage/backstage/blob/8c754968d9b8d87b19c1b52c00937c33b5cd5dbb/plugins/catalog-backend/src/processing/DefaultCatalogProcessingEngine.ts#L199), and hashing comparison takes it as equal. But shouldn't be? If this renaming behaviour can be treated as Database Processing error, could this be passed to [errorString](https://github.com/backstage/backstage/blob/8c754968d9b8d87b19c1b52c00937c33b5cd5dbb/plugins/catalog-backend/src/processing/DefaultCatalogProcessingEngine.ts#L186) as well?

## Steps to Reproduce

1. config the catalog-info.yaml as above
2. rename API1 name
3. API1 metadata  never set orphan status to true

## Your Environment

- NodeJS Version (v14):
- Operating System and Version (e.g. Ubuntu 14.04):
- Browser Information:
