### ISSUE TITLE
Custom Fields (ui:field) Validation Not Recognized In Software Template Arrays

### ISSUE THREAD

**Issue by ProticM** [backstage/backstage#7577]
## Expected Behavior

The custom field should be picked up in the template and attached validation should be triggered

## Current Behavior

Custom field is ignored and validation is not triggered when moving to the next step or submitting the form in the template

## Possible Solution

Revisit the validation generation code and include `ui:field` attached to array item.

To me, what seems fishy is that in the code where you check if the variable `isObject`, `!Array.isArray()` check is also included which ignores the arrays

Not sure if this is the right spot to look in, but the check is located in the `TemplatePage.tsx` in `createValidator` function.

### Example YAML

```yaml
- title: Step Title
  required:
    - field
    - list
    - list_two
  properties:
    field:
      title: Field
      type: string
      ui:field: EntityNamePicker # Here the field works without issues
      # or
      # ui:field: TagField # Here the custom field works without issues
    list:
      type: array
      title: List title
      items:
        required: # required works fine
          - field_one
          - field_two
        properties:
          field_one:
            title: Field One
            type: string
            ui:field: EntityNamePicker # Built in fields are not working here
            description: Field One Desc
          field_two:
            title: Field Two
            type: string
            ui:field: TagField # Custom fields are not working as well
            description: Field Two Desc
    list_two:
      type: array
      title: List Two Title
      items:
        title: Field Title
        type: string
        ui:field: TagField # Custom fields are not working here neither
        description: Some Desc
```

### Sample custom extension:

```js
export const TagFieldExtension = scaffolderPlugin.provide(
  createScaffolderFieldExtension({
    name: 'TagField',
    component: TextValuePicker,
    validation: (value: string, validation: FieldValidation) => {
      // validate the value
      // this code is never reached even though the field is created
    }
  })
);
```

## Context

I'm building a step to scaffold the component kind YAML file where the user should be able to enter the related links and tags. And, the tags for example have some specific validation rules (`From docs: Each tag must be sequences of [a-z0-9] separated by -, at most 63 characters in total`) that are not supported by default thus I need a custom extension to include the tag validation

## Your Environment

- NodeJS Version (v14): v14.17.5
- Operating System and Version (e.g. Ubuntu 14.04): Windows 10 Pro
- Browser Information: Chrome
