### ISSUE TITLE
Add parent group for organization with GitHub Multi Org Processor 

### ISSUE THREAD

**Issue by morganmspencer** [backstage/backstage#7619]
## Feature Suggestion

When the GitHub Multi Org Processor runs it creates groups for teams. It should also create a parent group for the organization that has the teams and users linked.

## Possible Implementation

An additional step in the [processor](https://github.com/backstage/backstage/blob/74b6b5cfc230e6294d2726d86e453ec4b9596ebb/plugins/catalog-backend/src/ingestion/processors/GithubMultiOrgReaderProcessor.ts) that creates an entity for the entire organization. Something like this:

```yaml
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: org-slug
spec:
  type: organization
  profile:
    displayName: Organization Name
  children: [team-1, team-2, team-3]
  members: [user-1, user-2, user-3]
```

Alternatively, rather than adding all children and members, I believe this should work both ways. So, the org group can be added to a sub group as `parent` and a user's group list.

## Context

Trying to create more of a hierarchy for users and groups, especially when multiple organizations are pulled in. A user would be able to select an organization group to see all users and sub-groups (teams) associated with the entire organization.
