### ISSUE TITLE
Copying github actions workflow file using software templates: Actions with references are not being copied 

### ISSUE THREAD

**Issue by Vijayalakshmi-Yolbhavi** [backstage/backstage#7632]
We are copying the github actions files from one repo to another using **fetch:template** in software template.
The files are getting copied in the destination repo but we see the references in the file are not copied. 
Please refer below.

**## Expected Behavior**

        ```
        - name: Debug
           run: echo ${{ env.BRANCH_NAME }} 

        - name: Checkout
          uses: actions/checkout@v2
          with:
            ref: ${{ env.BRANCH_NAME }}
            fetch-depth: 0
            
        - name: Login via Az module
          uses: azure/login@v1
          with:
            creds: ${{secrets.AZURE_CREDENTIALS}}
            enable-AzPSSession: true 

        - name: Azure CLI script file
          uses: azure/CLI@v1
          env:
            COMMIT_SHA: ${{ steps.getfile.outputs.files }}
```

****

 ```
        - name: Debug
          run: echo  

        - name: Checkout
          uses: actions/checkout@v2
          with:
            ref: 
            fetch-depth: 0
            
        - name: Login via Az module
          uses: azure/login@v1
          with:
            creds: 
            enable-AzPSSession: true 

        - name: Azure CLI script file
          uses: azure/CLI@v1
          env:
            COMMIT_SHA: 
```
