### ISSUE TITLE
scaffolder.backstage.io/v1beta3 - Register Issue using replaceProcessors 

### ISSUE THREAD

**Issue by regicsolutions** [backstage/backstage#7661]
## Expected Behavior

I should be able to register a component using the catalog:register action as such:

```
steps:
    - id: publish
      name: Create a Repo
      action: publish:bitbucket
      input:
        repoUrl: ${{ parameters.repoUrl }}

    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps.publish.output.repoContentsUrl }}
        catalogInfoPath: /catalog-info.yaml
        
  output:
    remoteUrl: ${{ steps.publish.output.remoteUrl }}
    entityRef: ${{ steps.register.output.entityRef }}
      
```

## Current Behavior

When using replaceProcessors as such:

```
import {
    AnnotateLocationEntityProcessor,
    BitbucketDiscoveryProcessor,
    CatalogBuilder,
    FileReaderProcessor,
    LocationEntityProcessor,
    UrlReaderProcessor,
  } from '@backstage/plugin-catalog-backend';
  import { ScaffolderEntitiesProcessor } from '@backstage/plugin-scaffolder-backend';
  import { Router } from 'express';
  import { PluginEnvironment } from '../types';
  import { ScmIntegrations } from '@backstage/integration';
  import { LdapOrgReaderProcessor } from '@backstage/plugin-catalog-backend-module-ldap';
  import { customBitbucketRepositoryParser } from './catalog/customBitbucketRepositoryParser';
  import { customGroupTransformer, customUserTransformer } from './catalog/customLDAPTransformer';
  
  export default async function createPlugin(
    env: PluginEnvironment,
  ): Promise<Router> {
    const integrations = ScmIntegrations.fromConfig(env.config);
    const builder = await CatalogBuilder.create(env);
  
    builder.replaceProcessors([
      new FileReaderProcessor(),
      BitbucketDiscoveryProcessor.fromConfig(env.config, {
        parser: customBitbucketRepositoryParser,
        logger: env.logger,
      }),
      LdapOrgReaderProcessor.fromConfig(env.config, {
        logger: env.logger,
        groupTransformer: customGroupTransformer,
        userTransformer: customUserTransformer,
      }),
      new UrlReaderProcessor({ reader: env.reader, logger: env.logger }),
      new LocationEntityProcessor({ integrations }),
      new AnnotateLocationEntityProcessor({ integrations }),
      new ScaffolderEntitiesProcessor(),
    ]);

    const { processingEngine, router } = await builder.setRefreshIntervalSeconds(600).build();
    await processingEngine.start();
    return router;
  }
```
I am getting the following error: `scaffolder error Failed to parse template string: /catalog-info.yaml with error Unexpected token / in JSON at position 0 type=plugin`

I do not get this error when using `addProcessor`

The reason i am not using addProcessor is because i am not able to get the BitbucketDiscoveryProcessor to run given its only added unless the user replaced them all

https://github.com/backstage/backstage/blob/931ca6686789290751d5a1c58d5a0012f2bba60c/plugins/catalog-backend/src/service/NextCatalogBuilder.ts#L407-L419

## Your Environment

- NodeJS Version (v14): Node14
- Operating System and Version (e.g. Ubuntu 14.04): Window10
- Browser Information: Chrome
