### ISSUE TITLE
[RFC] Ability to use the signed in users oauth credentials in the Scaffolder

### ISSUE THREAD

**Issue by benjdlambert** [backstage/backstage#7684]
**Status:** Open for comments

## Need
Using credentials from a Personal Access Token that is a god token, or Github Apps is some times not enough security and Integrators would like to have the ability to grab a token from the users signed in oauth provider in order to use that with the Scaffolder actions to make requests on the users behalf.

This means it would be possible to request a token from the signed in oauth provider (bitbucket, github, gitlab etc..), and then in the `handler()` of the `action` be able to use this token.

## Proposal
So this is a tricky topic, and would love some feedback on the implementation and maybe we can iterate to find something better.

```yaml
# not sure if this is useful or not, but this could be json schema for declaring the secrets object
secrets:
  oauth:
     type: string

parameters:
  repoUrl:
    type: string
    ui:field: RepoUrlPicker
    ui:options:
     # this tells the RepoUrlPicker to use a new API inside the FieldExtensions to set secrets.oauth as the oauth token
      withCredentials: 
        key: oauth

steps:
    - id: publish
      name: Publish
      action: publish:github
      input:
        repoUrl: ${{ parameters.repoUrl }}
        # this passes through token as an input called token from the secrets
        token: ${{ secrets.oauth }}
```

The part that isn't really defined here would be the api for setting values on the secrets context, but think that it would just another prop that is passed to the frontend component similar to the `onChange` function, could be something like `setSecret({ [props.withCredentials.key]: token })`

## Alternatives
We could of course remove certain parts of this, like the schema validation maybe that's not required and doesn't provide much value when we already have validation for the input of the action.

Open for discussion really and any other ideas welcome.
