### ISSUE TITLE
Include "dependsOn" in the docs Component example

### ISSUE THREAD

**Issue by djamaile** [backstage/backstage#7768]
## Feature Suggestion

I saw couple of times users having trouble setting the relationship between a Resource and a Component. 
I think it would be nice if it was documented here: https://backstage.io/docs/features/software-catalog/descriptor-format#kind-component .  Because if you have no dependencies and click on `No resource is a dependency of this component` it will lead you to there. 

## Possible Implementation

line 487: https://github.com/backstage/backstage/blob/master/docs/features/software-catalog/descriptor-format.md

Change yaml to:

```yaml
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: artist-web
  description: The place to be, for great artists
spec:
  type: website
  lifecycle: production
  owner: artist-relations-team
  system: artist-engagement-portal
  dependsOn:
    - Resource:default/artists-db
  providesApis:
    - artist-api
```
