### ISSUE TITLE
Catalog cleanup job (remove orphaned entities)

### ISSUE THREAD

**Issue by jvilimek** [backstage/backstage#7860]
Backstage should provide out-of-the-box solution for having the database clean (without stale records).

## Feature Suggestion

Let's implement a job or add a step to already existing scaffolder job that will remove stale records from the DB (with opt-in?out? configuration)

## Possible Implementation

enhance scaffolder job

## Context

Sometimes the services are renamed, sometimes the Yaml definitions in various repositories got deleted. But in the catalog those are stil present. 

We could implement our own cleanup pipeline using APIS or adjust the catalog, but who wants to reimplement a wheel for a task, that should be IMHO part of the core components. See also #3750, #5442

## External (PowerShell) job

There is at the moment following script you can use to get all orphaned entities, see [OrphanCleanUp.ps1](https://github.com/backstage/backstage/blob/master/contrib/scripts/orphan-clean-up/OrphanCleanUp.ps1) (thanks @awanlin !).

**Comment by Rugvip** [comment]
We'll likely want to build on top of https://github.com/backstage/backstage/pull/7612 for this to have it be flexible.

I'm a bit confused whether we're talking about the catalog or scaffolder here though 😅, I think we should definitely add this for cleaning up old scaffolder task specs, it makes sense to keep them around for a while to be able to review output after the fact and whatnot, but definitely makes sense to have them be cleaned up after a while.

For the catalog this *should* already be in place in that things either get orphaned or deleted. The missing piece is perhaps automatic deletion of orphaned entities, but it's a bit higher up than the DB level. It's something we discussed as part of the design but left out in the initial implementation. Very much open to suggestions and feedback on how that would work though. I'd say we're a bit torn between automatically deleting things vs providing endpoints and possibly a GUI to browse entities that are orphaned or have errors.

**Comment by jvilimek** [comment]
thanks for the answer.
Let me clarify this. We have following configuration (app-config.yaml):
```yaml
catalog:
  rules:
    - allow: [Component,...]
  locations:
    # Backstage BACKEND catalog index
    - type: url
      target: https://url-for-backend-index.yaml
    # Backstage FRONTEND catalog index
    - type: url
      target: https://url-for-fe-index.yaml
   ...
```

We generate the index based on several already existing sources where the generated index looks like:

```yaml
apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: backend-catalog-index
  description: A collection of all backend components
spec:
  type: url
  targets:
    - ./auto-generated/systemA.yaml
    - ./auto-generated/systemB.yaml
    - https://full-url-to-repo-of-system-C/backstage.yaml
    - ...
 ```

where definitions for systemA, B are autogenerated where system C is imported from the team repository.

So in case someone adds a definition for their system it is automatically included in the catalog instead the generated one. 

Sometimes the generated/manually added locations/component definitions are no longer valid (trest imports from branches, obsolete components deleted, renames...) which leaves garbage in the catalog. Yep, once you navigate to the obsolete component you see the warning "no longer exists" or some similar and you are able to remove it, but...we want to have a job/some solution for this..

Sometimes we even drop the whole database and let it rebuild from the sources.

Automatically delete orphaned definitions (configurable?) would be great for our case.
