### ISSUE TITLE
MS Graph Ingestion uses mail nickname guid instead of displayname 

### ISSUE THREAD

**Issue by timja** [backstage/backstage#7888]
## Expected Behavior

Group display name shown

## Current Behavior

Mail nickname is used which is a guid for security groups

## Possible Solution

roughly:
```
 if securityEnabled == true and mailEnabled == false
  then
      return displayName ?? mailNickname
else
  existing logic
```

## Steps to Reproduce

1. Follow https://github.com/backstage/backstage/blob/master/plugins/catalog-backend-module-msgraph/README.md 

appConfig:
```yaml
catalog:
  rules:
    - allow: [Component, System, API, Group, User, Resource, Location]
  processors:
    microsoftGraphOrg:
      providers:
        - target: https://graph.microsoft.com/v1.0
          authority: https://login.microsoftonline.com
          # If you don't know you tenantId, you can use Microsoft Graph Explorer
          # to query it
          tenantId: ${AUTH_MICROSOFT_TENANT_ID}
          # Client Id and Secret can be created under Certificates & secrets in
          # the App registration in the Microsoft Azure Portal.
          clientId: ${AUTH_MICROSOFT_CLIENT_ID}
          clientSecret: ${AUTH_MICROSOFT_CLIENT_SECRET}
          # Optional filter for user, see Microsoft Graph API for the syntax
          # See https://docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-1.0#properties
          # and for the syntax https://docs.microsoft.com/en-us/graph/query-parameters#filter-parameter
          # This and userGroupMemberFilter are mutually exclusive, only one can be specified
          userFilter: accountEnabled eq true
          # Optional filter for users, use group membership to get users.
          # This and userFilter are mutually exclusive, only one can be specified
          #userGroupMemberFilter: "displayName eq 'Backstage Users'"
          # Optional filter for group, see Microsoft Graph API for the syntax
          # See https://docs.microsoft.com/en-us/graph/api/resources/group?view=graph-rest-1.0#properties
          groupFilter: securityEnabled eq true
```

3. Create a security enabled group via AAD UI
4. ingest the data

## Context

https://discord.com/channels/687207715902193673/687235481154617364/905736393010053181

I'll probably pick this up but just reporting it in case anyone gets to it first or I don't have time to get back to it

## Your Environment

- NodeJS Version (v14):
- Operating System and Version (e.g. Ubuntu 14.04):
- Browser Information:
