### ISSUE TITLE
objects are written to the `final_entities` table not to `entities` table

### ISSUE THREAD

**Issue by erkanzileli** [backstage/backstage#8038]
We used new codes but our objects are written to the `final_entities` table not to `entities` table. This means we can't see our Components or Resources on our UI.

Our plugins versions are the following

```
"@backstage/backend-common": "^0.9.9"
"@backstage/plugin-catalog-backend": "^0.17.3"
```

Here are our configs.

app-config.yaml
```yaml
catalog:
  rules:
    - allow: [Component, API, Group, User, Template, Location, System, Domain, Resource]
  locations:
    - type: url
      target: https://file-url-which-contains-component
```

catalog.js (which tries to run processors)
```ts
import {CatalogBuilder, UrlReaderProcessor,} from '@backstage/plugin-catalog-backend';
import {PluginEnvironment} from './types';

export async function createReader(
    env: PluginEnvironment,
): Promise<any> {
    const builder = await CatalogBuilder.create(env);

    const urlReader = new UrlReaderProcessor({reader: env.reader, logger: env.logger})
    builder.addProcessor(urlReader)

    const {processingEngine, router} = await builder.build();

    await processingEngine.start();

    return router
}
```

types.ts
```ts
import { Logger } from 'winston';
import { Config } from '@backstage/config';
import {
    PluginDatabaseManager,
    UrlReader,
} from '@backstage/backend-common';

export type PluginEnvironment = {
    logger: Logger;
    database: PluginDatabaseManager;
    config: Config;
    reader: UrlReader;
};
```

cc: @yilmazo @previousdeveloper

_Originally posted by @erkanzileli in https://github.com/backstage/backstage/issues/7984#issuecomment-967121816_
