### ISSUE TITLE
Catalog Graph does not always honour max depth

### ISSUE THREAD

**Issue by anisorigin** [backstage/backstage#8081]
The max depth in the catalog graph component goes much further down the tree than the specified depth. This makes the view a lot more cluttered than it needs to be

## Expected Behavior

When I view the graph with depth 2, each node is no more than 2 nodes away from the root of the tree

## Current Behavior

When I view the graph with depth 2, nodes exist that are further than 2 nodes away from the root

<img width="1501" alt="Screen Shot 2021-11-17 at 3 17 50 pm" src="https://user-images.githubusercontent.com/89754895/142139361-ee1eef0e-629d-49da-b3d3-dd3458c31256.png">

## Possible Solution

No clue what could be the root of this issue

## Steps to Reproduce

 1. Add the following catalog-info.yaml to the catalog on the example backstage app on master 
 2. run `yarn run dev`
 2. go to the "component-a" entity
 3. click "view graph" on the relations card
 4. set the max depth to 2 or 3
 5. turn off merge-relations for a cleaner view
 
 Result: the max depth will not be applied correctly

```
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: component-a
spec:
  type: service
  lifecycle: production
  owner: team-d
  system: my-system
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: my-system
spec:
  type: service
  lifecycle: production
  owner: team-d
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: component-b
spec:
  type: service
  lifecycle: production
  owner: team-d
  system: my-system
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: component-c
spec:
  type: service
  lifecycle: production
  owner: team-d
  # system: c
  dependsOn: ['component:component-b', 'component:component-d']
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: component-d
spec:
  type: service
  lifecycle: production
  owner: team-d

```

## Context

This issue is popping up in a backstage app that has ~1000 entities, slowing the graph page to a snails pace with all of those nodes it needs to render and creating a view that is too cluttered to be useful

## Your Environment

OS:   Darwin 20.6.0 - darwin/x64
node: v16.10.0
yarn: 1.22.1
cli:  0.8.2 (local)
branch: master (39a8cbfd33 is the latest commit at time of posting)
