### ISSUE TITLE
Template not found error when file in Cookiecutter skeleton file has an include statement

### ISSUE THREAD

**Issue by henryto-happymoney** [backstage/backstage#8150]
When file in Cookiecutter skeleton uses an include statement, for example in `README.md`:
```
Some readme text...

{% include "Features.md" %}
```

This results in an exception in the `fetch:template` step.
It appears to be searching for `Features.md` in `packages/backend` instead of the Cookiecutter skeleton directory.
No exceptions if `{% include "Features.md" %}` is removed.

## Expected Behavior
`Features.md` is rendered properly in `README.md`.

## Current Behavior
Template not found error occurs in the `fetch:template` step.

## Steps to Reproduce
1. Create a `Features.md` file and add it to the Cookiecutter skeleton directory.
2. Create a `README.md` file with the `{% include "Features.md" %}` statement and add it to the Cookiecutter skeleton directory.
3. Add `fetch:template` step with `cookiecutterCompat: true` to template yaml file.
4. Run task and observe the exception.

## Context
Template YAML: (issue occurs with v1beta2 and v1beta3)
```
apiVersion: scaffolder.backstage.io/v1beta3
...
steps:
  - id: generate
    name: Generate Repository
    action: fetch:template
    input:
      url: ./cookiecutter
      cookiecutterCompat: true
      values:
        service_name: ${{ parameters.service_name }}
        model_name: ${{ parameters.model_name }}
        port: ${{ parameters.port }}
        service_id: ${{ parameters.service_id }}
        java_package: ${{ parameters.java_package }}
        package_dir: ${{ parameters.package_dir }}
        int_package: ${{ parameters.int_package }}
        int_package_dir: ${{ parameters.int_package_dir }}
```

File Structure (Cookiecutter):
```
- root
    ...
    - cookiecutter.json
    - {{cookiecutter.service_id}}
        - README.md
        - Features.md
```

Stack trace:
```
2021-11-18T00:27:13.584Z info: Writing file {{cookiecutter.service_id}}/README.md to template output path with mode 33188. {"timestamp":"2021-11-18T00:27:13.578Z"}
2021-11-18T00:27:13.587Z Template render error: (unknown path)
  Template render error: (unknown path)
  Error: template not found: Features.md
    at Object._prettifyError (/Users/hto/hm-backstage/node_modules/nunjucks/src/lib.js:36:11)
    at /Users/hto/hm-backstage/node_modules/nunjucks/src/environment.js:563:19
    at Template.root [as rootRenderFunc] (eval at _compile (/Users/hto/hm-backstage/node_modules/nunjucks/src/environment.js:633:18), <anonymous>:43:3)
    at Template.render (/Users/hto/hm-backstage/node_modules/nunjucks/src/environment.js:552:10)
    at Environment.renderString (/Users/hto/hm-backstage/node_modules/nunjucks/src/environment.js:380:17)
    at Object.handler (/Users/hto/hm-backstage/node_modules/@backstage/plugin-scaffolder-backend/dist/index.cjs.js:452:92)
    at async DefaultWorkflowRunner.execute (/Users/hto/hm-backstage/node_modules/@backstage/plugin-scaffolder-backend/dist/index.cjs.js:2426:11)
    at async TaskWorker.runOneTask (/Users/hto/hm-backstage/node_modules/@backstage/plugin-scaffolder-backend/dist/index.cjs.js:2094:85)
    at async /Users/hto/hm-backstage/node_modules/@backstage/plugin-scaffolder-backend/dist/index.cjs.js:2088:9
```

## Your Environment
- NodeJS Version (v14): v14.17.6
- Operating System and Version (e.g. Ubuntu 14.04): macOS v11.6 (Big Sur)
- Browser Information: Chrome v95.0.4638.69
