### ISSUE TITLE
Enrich discovered entities

### ISSUE THREAD

**Issue by tanguyantoine** [backstage/backstage#8250]
### Discussed in https://github.com/backstage/backstage/discussions/8227

<div type='discussions-op-text'>

<sup>Originally posted by **tanguyantoine** November 24, 2021</sup>
`github-org` location let Backstage auto discover teams and users from an organization. 
This is very convenient to get Group and User entities ingested within Backstage.

Github does not provide any way to add custom data/link to teams.

Is there a way to enrich/extends discovered entities with custom annotations.

Ex

```yaml
apiVersion: backstage.io/v1alpha1
kind: Extension
metadata:
  reference: my-github-team
  annotations:
    my-custon-annotation: value
```

That would be a very convenient way to enrich entities without the need to maintain 2 declarations</div>
