### ISSUE TITLE
Proxy configuration

### ISSUE THREAD

**Issue by mx-foxtel** [backstage/backstage#8320]
I have my backstage running in a Kubernetes cluster through the helm chart.

I have defined a proxy configuration for newrelic,

```
proxy:
  '/newrelic/apm/api':
    target: https://api.newrelic.com/v2
    headers:
      X-Api-Key: {{ .Values.newrelic.api.key}}
```

However, when I open the page for newrelic, I see it making calls to newrelic directly and not via the proxy. It fails as expected as API key will not be sent.

```
Request URL: https://api.newrelic.com/v2/applications.json
Request Method: GET
Status Code: 401 Unauthorized
Remote Address: x.x.x.x:443
Referrer Policy: strict-origin-when-cross-origin
```

Is there something I am missing. I have followed and done all steps for enabling proxy as mentioned in the docs.
