### ISSUE TITLE
plugin-auth-backend: Okta auth adding base path twice in redirect uri

### ISSUE THREAD

**Issue by sachin-kumar-ik8** [backstage/backstage#8411]
When we configure service discovery then auth callback url include backend baseurl base path + service discovery base path. 

## Expected Behavior

Redirect uri shouldnt include base path twice. It should be for ex:
redirect_uri=http://localhost:7000/backstage-api/auth/okta/handler/frame

## Current Behavior
When we add backend baseUrl with base path in config.yaml and set ServiceDiscovery config option with basePath then okta rediect uri looks like:
redirect_uri=http://localhost:7000/backstage-api/backstage-api/auth/okta/handler/frame

app-config.yaml:
    
```
       backend:
         baseUrl: http://localhost:7000/backstage-api
```
    

packages/backend/src/index.ts:
```
  const discovery = SingleHostDiscovery.fromConfig(config, { 
    basePath: "/backstage-api"
  });
  ```

## Possible Solution

plugin-auth-backend: dist/index.cjs.js -> inside createOktaProvider function callbackurl is
http://localhost:7000/backstage-api/backstage-api/auth/okta/handler/frame

## Steps to Reproduce

1. Add backend baseUrl with basepath something other than : http://localhost:7000/backstage-api
2. Add service discovery with config and basepath option
```
  const discovery = SingleHostDiscovery.fromConfig(config, { 
    basePath: "/backstage-api"
  });
  ```
3. Start express server with basepath in router
```
  const service = createServiceBuilder(module)
    .loadConfig(config)
    .addRouter('/backstage-api', apiRouter);
    ```

## Context

Okta redirect uri is failing with 400

Environment: development
app-config.yaml
```
app:
  title: backstage
  baseUrl: http://localhost:3000/backstage/

backend:
  baseUrl: http://localhost:7000/backstage-api
...

auth:
  environment: development
  providers:
    okta:
      development:
        clientId: test
        clientSecret: test
        audience: https://dev-123354.okta.com
...
...
     ```

- NodeJS Version (v14):
- Operating System and Version (e.g. Ubuntu 14.04): macos
- Browser Information:
