### ISSUE TITLE
Validation not called for custom FieldExtension with type object when using v1beta3 template api

### ISSUE THREAD

**Issue by msamad** [backstage/backstage#8420]
## Expected Behavior

Custom validation should be called for custom FieldExtension with type object

## Current Behavior

Custom validation was not called for custom FieldExtension with type object

## Possible Solution

Not a solution but some investigation

The fields show up ok but validation is never called when I move next on the form, I had a look at the code https://github.com/backstage/backstage/blob/master/plugins/scaffolder/src/components/TemplatePage/TemplatePage.tsx#L81
Seems like it will never reach to the part where it will call the validator for the `ui-field` as the result will be considered object at if `(isObject(propData)) {` on line https://github.com/backstage/backstage/blob/master/plugins/scaffolder/src/components/TemplatePage/TemplatePage.tsx#L81

and then would not go further because of `if (!isObject(schemaProps)) {`  https://github.com/backstage/backstage/blob/master/plugins/scaffolder/src/components/TemplatePage/TemplatePage.tsx#L74, I tried to get around it but providing properties like below but then it tries to do their schema validation instead of the ui-field custom validation
```
  parameters:
    - title: Provide Component Details
      required:
        - repoInfo
        - description
      properties:
        repoInfo:
          title: Unique name of the component
          type: object
          ui:field: RepoUrlPickerCustom
          properties:
            workspace:
              type: string
              title: workspace
              description: The workspace
            project:
              type: string
              title: project
              description: The project
            repo:
              type: string
              title: repo
              description: The repo
```

## Steps to Reproduce
https://backstage.io/docs/features/software-templates/writing-custom-field-extensions

1. Create a custom FieldExtension `RepoUrlPickerCustom`, a copy of `RepoUrlPicker`
Use the object type in FieldProps
```
export const RepoUrlPickerCustom = ({
  onChange,
  rawErrors,
  formData,
}: FieldProps<{ workspace: string, project: string, repo: string }>) => {
```
2. Create a custom validator `RepoUrlPickerCustomValidation`, a copy of `validation` for `RepoUrlPicker`
3. Register the FieldExtension
```
export const RepoUrlPickerCustomFieldExtension = plugin.provide(
    createScaffolderFieldExtension({
        name: 'RepoUrlPickerCustomExtension',
        component: RepoUrlPickerCustom,
        validation: RepoUrlPickerCustomValidation,
    }),
);
```
4. Add parameter with `ui:field` in the template
```
  parameters:
    - title: Provide Component Details
      required:
        - repoInfo
        - description
      properties:
        repoInfo:
          title: Unique name of the component
          type: object
          ui:field: RepoUrlPickerCustom
```

5. In the frontend template form, click next without adding anything for fields in `RepoUrlPickerCustom`. The form moves to next stage instead of calling the `RepoUrlPickerCustomValidation`

## Context
Trying to create a custom UI component in the form which can have multiple fields depend on each other and perform validation accordingly, and be able to use the object for multiple values instead of a single string.

## Your Environment

- NodeJS Version (v14): v14.18.1
- Operating System and Version (e.g. Ubuntu 14.04): Windows 10 20H2 ( OS Build 19042.1288)
- Browser Information: Google Chrome - Version 96.0.4664.45 (Official Build) (64-bit)
