### ISSUE TITLE
Add `projectSlug` filter to scaffolder v1beta3 templates

### ISSUE THREAD

**Issue by OrkoHunter** [backstage/backstage#8444]
## Feature Suggestion

Add the `projectSlug` filter to the Scaffolder plugin so that Software Templates can use them as a filter similar to `parseRepoUrl`. 

An example of the filter in use

https://github.com/backstage/software-templates/blob/a8d26cf8a5e6e0684c66d82928222da80a17c31e/scaffolder-templates/rails-demo/template.yaml#L139

## Possible Implementation

Scaffolder v1beta2 templates has some of these custom filters implemented - `parseRepoUrl`, `projectSlug`, `eq`, `json`, `not`.
https://github.com/backstage/backstage/blob/3e70c671a1fbe2dbda3cf6445f36292a219d7388/plugins/scaffolder-backend/src/scaffolder/tasks/HandlebarsWorkflowRunner.ts#L50-L73

When migrating to a newer apiVersion (which uses nunjucks templating engine over handlebars see https://github.com/backstage/backstage/issues/6437), it seems that `parseRepoUrl` was migrated ([see here](https://github.com/backstage/backstage/blob/3e70c671a1fbe2dbda3cf6445f36292a219d7388/plugins/scaffolder-backend/src/scaffolder/tasks/NunjucksWorkflowRunner.ts#L185-L194)).

The rest of the filters `eq` and `not` can now be done via Jinja2 syntax i.e. `==` and `!=`. And `json` is enabled by default, which means the type of variable is passed as it is. The [migration guide](https://backstage.io/docs/features/software-templates/migrating-from-v1beta2-to-v1beta3) can be a helpful reference.

So, we need to implemented `projectSlug` so that Software Templates like [rails-demo](https://github.com/backstage/software-templates/blob/a8d26cf8a5e6e0684c66d82928222da80a17c31e/scaffolder-templates/rails-demo/template.yaml#L139) can be upgraded. The implementation looks fairly simple and reuses parseRepoUrl. Code from handlebars implementation ->

```
    this.handlebars.registerHelper('projectSlug', repoUrl => {
      const { owner, repo } = parseRepoUrl(repoUrl, this.options.integrations);
      return `${owner}/${repo}`;
    });
```

**Comment by OrkoHunter** [comment]
@benjdlambert @jhaals Do you think this is accurate - or did I miss the filter completely? I noticed it while upgrading the sample templates on [Software Templates](https://github.com/backstage/software-templates).

**Comment by benjdlambert** [comment]
Hmm maybe yeh, but I'd want to deprecate it when `repoUrl` becomes an object so that people can just do `${{ repo.owner }}/${{ repo.name }}` themselves in the template as the `repoSlug` is kindof a hack anyways.

**Comment by benjdlambert** [comment]
Lets add the filter for now.

**Comment by benjdlambert** [comment]
Actually - just thinking about this, didn't we place it with doing the concat ourselves in the templates in our own. Maybe we should just update it to use the `destination` parameter thats passed through to the values already?

**Comment by benjdlambert** [comment]
https://github.com/backstage/software-templates/blob/a8d26cf8a5e6e0684c66d82928222da80a17c31e/scaffolder-templates/react-ssr-template/skeleton/catalog-info.yaml#L7

**Comment by OrkoHunter** [comment]
@benjdlambert Is that `${{values.destination.owner + "/" + values.destination.repo}}` possible in template.yaml as well? Here https://github.com/backstage/software-templates/blob/a8d26cf8a5e6e0684c66d82928222da80a17c31e/scaffolder-templates/rails-demo/template.yaml#L139

**Comment by benjdlambert** [comment]
It's not parsed, but there should be a way to do it with the filters and nunjucks syntax. Thinking it would be better to deprecate it rather than copying just for this use case. See what you can come up with, if you can't do it, maybe we just have to move that logic into the rails templater instead. It's only ever used in the skeleton templates, so there's no need to have this helper in the template manifest is my initial thinking.

**Comment by christophe-tt** [comment]
So, is there an actual solution to this issue? It seems like a fairly common thing to do to get the `owner/repo` in a custom `catalog-info.yaml` file for the various GitHub plugins, I can't believe there isn't already a way to do this. Note that I'm quite new to Backstage though, bu I've been struggling with this for a couple of days now.

**Comment by benjdlambert** [comment]
You can pass through the parsed `repoUrl` like this:
https://github.com/backstage/software-templates/blob/main/scaffolder-templates/react-ssr-template/template.yaml#L57

And then you can build the `repoSlug` yourself in the templates:
https://github.com/backstage/software-templates/blob/main/scaffolder-templates/react-ssr-template/skeleton/catalog-info.yaml#L7

**Comment by christophe-tt** [comment]
@benjdlambert Here's my template file:
```
apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
# some metadata about the template itself
metadata:
  name: some-name
  title: Some Name
  description: Some description
spec:
  owner: my-user
  type: service
  parameters:
    - title: Fill in some steps
      required:
        - name
      properties:
        name:
          title: Name
          type: string
          description: Unique name of the component
          ui:autofocus: true
          ui:options:
            rows: 5
    - title: Choose a location
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com
  steps:
    - id: fetch-base
      name: Fetch Base
      action: fetch:template
      input:
        url: ./template
        values:
          name: ${{ parameters.name }}

    - id: fetch-symfony
      name: Fetch Symfony
      action: fetch:plain
      input:
        targetPath: ./
        url: https://github.com/symfony/symfony

    - id: catalog-write
      name: Write Catalog
      action: catalog:write
      input:
        values:
          destination: ${{ parameters.repoUrl | parseRepoUrl }}
        entity:
          apiVersion: backstage.io/v1alpha1
          kind: Component
          metadata:
            name: ${{ parameters.name }}
            description: ${{ parameters.name }}
            annotations:
              github.com/project-slug: ${{values.destination.owner + "/" + values.destination.repo}}
          spec:
            type: service
            owner: my-user
            lifecycle: experimental

    - id: publish
      name: Publish
      action: publish:github
      input:
        allowedHosts: ['github.com']
        description: This is ${{ parameters.name }}
        repoUrl: ${{ parameters.repoUrl }}

    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps.publish.output.repoContentsUrl }}
        catalogInfoPath: '/catalog-info.yaml'
```
But I'm getting `undefined/undefined` as a result in the file. Did I miss anything?
