### ISSUE TITLE
scaffolder: Default values dependend on owner

### ISSUE THREAD

**Issue by OrKarstoft** [backstage/backstage#8464]
## Feature Suggestion
Have one or more lists of default values to pass to the template when a specific value is set to a property.

## Possible Implementation
Being able to pass `formData` object as in [react-jsonschema-form playground](https://rjsf-team.github.io/react-jsonschema-form/) or have separate definition files.

## Context
We have multiple teams using the same templates. For example spring boot ready Github repos.
Every team is different and every service have it's own demands which makes the template rather large.
We'd like a way to define that if you select a specific team as owner using `OwnerPicker` it would fill in the predefined values that the team specified. If the team selected doesn't have a predefined values list then just be empty.

We'd rather have one template for spring boot to maintain than one template per team using spring boot.

**Comment by benjdlambert** [comment]
hmm - how do you think we could define these autofill examples? What would it look like in practice?

**Comment by OrKarstoft** [comment]
My first thought was if it was possible to pass the `formData` as JSON. Just like in the playground I linked.
You can take this JSON and paste it in the playground and it would fill the fields.
```JSON
{
  "firstName": "Oliver",
  "lastName": "Karstoft",
  "age": 27,
  "bio": "Survival streak of more that 9800 days.",
  "password": "MyR34l$EcuR3P4$5w0rD",
  "telephone": "+4512345678"
}
```

Otherwise a yaml file.
Something like:
```YAML
definedValues:
  ownerPicked:
    - logistics:
        repoName: this-is-a-weird-prefix-something-
        someOtherField: and a value
    - buying
        repoName: default-repo-name
        description: created with Backstage!
```
But handling that in the schema ... I have no idea how to.
