### ISSUE TITLE
Scaffolder stuck and not creating new component task activities when previous component's create task fails

### ISSUE THREAD

**Issue by msamad** [backstage/backstage#8477]
## Expected Behavior
Should be able to create new component using the template

## Current Behavior

Scaffolder stuck and not creating new component task activities when previous component's task fails

## Possible Solution
Not a solution but noticed that the first task remains in `processing` state in `tasks` table. 

## Steps to Reproduce

1. Create a template project
```
|---- template-test
        |---- template-test
                |---- catalog-info.yaml
        |---- template-test-1.yaml
        |---- template-test-2.yaml
```
catalog-info.yaml
```
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "{{cookiecutter.artifact_id}}"
  description: "{{cookiecutter.artifact_id}} Java REST API"
  tags:
    - service
spec:
  type: service
  lifecycle: experimental
  owner: {{cookiecutter.owner}}
```

template-test-1.yaml
```
apiVersion: backstage.io/v1beta2
kind: Template
metadata:
  # unique name per namespace for the template
  name: test-1
  # title of the template
  title: Test 1
  # a description of the template
  description: Test 1
  # some tags to display in the frontend
  tags:
    - test
spec:
  owner: test-team
  type: service

  # these are the steps which are rendered in the frontend with the form input
  parameters:
    - title: Choose name
      required:
        - name
        - product
      properties:
        name:
          title: Name
          type: string
          description: Name
        product:
          title: product
          type: string
          description: Product

  # here's the steps that are executed in series in the scaffolder backend
  steps:

    - id: fetch-base
      name: "Fetch Base"
      action: fetch:cookiecutter
      input:
        url: ./template-test
        values:
          artifact_id: '{{ parameters.name }}'
          # owner is specified before product, this will cause backstage to hang on subsequent scafollding requests
          owner: '\{{ cookiecutter.product|lower }}-team'
          product: '{{ parameters.product }}'

```
**Notice that in template-test-1.yaml, `owner` is specified before product.**

template-test-2.yaml
```
apiVersion: backstage.io/v1beta2
kind: Template
metadata:
  # unique name per namespace for the template
  name: test-2
  # title of the template
  title: Test 2
  # a description of the template
  description: Test 2
  # some tags to display in the frontend
  tags:
    - test
spec:
  owner: test-team
  type: service

  # these are the steps which are rendered in the frontend with the form input
  parameters:
    - title: Choose name
      required:
        - name
        - product
      properties:
        name:
          title: Name
          type: string
          description: Name
        product:
          title: product
          type: string
          description: Product

  # here's the steps that are executed in series in the scaffolder backend
  steps:

    - id: fetch-base
      name: "Fetch Base"
      action: fetch:cookiecutter
      input:
        url: ./template-test
        values:
          artifact_id: '{{ parameters.name }}'
          product: '{{ parameters.product }}'
          # owner is specified after product
          owner: '\{{ cookiecutter.product|lower }}-team'
```

2. Register both `template-test-1.yaml` and `template-test-2.yaml` in backstage.
3. Create a component using `template-test-1.yaml` in backstage, use random values for fields in the form.
The `fetch-base` step will throw the following error
```
5DEBUG cookiecutter.generate: Context generated is OrderedDict([('cookiecutter', OrderedDict([('artifact_id', 'abc'), ('owner', '{{ cookiecutter.product|lower }}-team'), ('product', 'test')]))])62021-12-13T22:19:31.000Z Unable to render variable 'owner'
7Error message: 'collections.OrderedDict object' has no attribute 'product'82021-12-13T22:19:31.000Z Context: {
9    "cookiecutter": {
10        "artifact_id": "abc",
11        "owner": "{{ cookiecutter.product|lower }}-team",
12        "product": "test"
13    }
14}152021-12-13T22:19:31.000Z undefined
```

4. Create component using either `template-test-1.yaml` or `template-test-2.yaml`, use random values for form fields. The scaffolder will hang and not run any task.
![image](https://user-images.githubusercontent.com/24932925/145898536-36b7eac8-b635-4709-9047-8ef1349743e2.png)

Restarting the app, if using external database, gets the tasks going again. 

## Context
Trying to create a project using the template, backstage just hangs and a restart is required.

We have fixed the faulty template i.e. ordered the values properly but raising issue here as backstage should handle this gracefully and not hang.

## Your Environment

**backstage-cli does not work, does not seem to have `info` command**

NodeJS Version (v14): v14.18.1
Operating System and Version (e.g. Ubuntu 14.04): Windows 10 20H2 ( OS Build 19042.1288)
Browser Information: Google Chrome - Version 96.0.4664.45 (Official Build) (64-bit)
