### ISSUE TITLE
Incorrect entityRef output URL for scaffolder register plugin 

### ISSUE THREAD

**Issue by bert-huang** [backstage/backstage#8527]
![image](https://user-images.githubusercontent.com/8079497/146475069-fe562a58-c02d-4308-97b4-c37b59ab4298.png)

## Expected Behavior
After creating a component in backstage, the "Open in catalog" URL should bring the user to the newly registered component page, even if the `catalog-info.yaml` contains multiple different "kind" of entities to be registered.

`http://localhost:3000/catalog/default/component/my-new-component`

## Current Behavior
If the `catalog-info.yaml` contains multiple "kind" of entities to be registered (e.g. both Component and API), the URL can end up pointing to the API instead.

`http://localhost:3000/catalog/default/api/my-new-component`

## Possible Solution

When going through the list of entities, instead of using the first non-generated entity, also attempt to check if the kind is "Component".

In `register.ts`, for this chunk of code
```javascript
if (result.entities.length > 0) {
  const { entities } = result;
  const entity =
    entities.find(e => !e.metadata.name.startsWith('generated-')) ??
    entities[0];
  ctx.output('entityRef', stringifyEntityRef(entity));
}
```
should be
```javascript
if (result.entities.length > 0) {
  const { entities } = result;
  const entity =
    entities.find(e => !e.metadata.name.startsWith('generated-') && e.kind === 'Component') ??
    entities[0];
  ctx.output('entityRef', stringifyEntityRef(entity));
}
```

## Steps to Reproduce

1. Create a java project with the following `catalog-info.yaml` and `template.yaml`

   **catalog-info.yaml**
    ```yaml
    apiVersion: backstage.io/v1alpha1
    kind: Component
    metadata:
      name: "my-project-template"
      description: "my-project-template description"
      tags:
        - java
    spec:
      type: service
      lifecycle: experimental
      owner: noone
      providesApis:
        - "my-project-api"
    ---
    apiVersion: backstage.io/v1alpha1
    kind: API
    metadata:
      name: my-project-api
      description: "my-project-api description"
      tags:
        - rest
    spec:
      type: openapi
      lifecycle: experimental
      owner: noone
      definition:
        $text: ./src/main/resources/openapi/openapi-spec.yaml
    ```
    The openapi-spec.yaml can anything, such as [PetStore](https://github.com/OAI/OpenAPI-Specification/blob/main/examples/v3.0/petstore.yaml)

    **template.yaml**
    ```yaml
    apiVersion: backstage.io/v1beta2
    kind: Template
    metadata:
      name: my-project-template
      title: Test Template
      description: Test Template
      tags:
        - api
        - java
        - rest
    spec:
      owner: noone
      type: service
      steps:
        - id: register
          name: "Register"
          action: catalog:register
          input:
            repoContentsUrl: '<my.git.repo>/blob/master'
            catalogInfoPath: '/catalog-info.yaml'
    
      output:
        entityRef: '{{ steps.register.output.entityRef }}'
    ```

2. Import the catalog into backstage via `/catalog-import`
3. Create a new component
4. The "Open in catalog" URL can randomly be either `catalog/default/api/my-new-component` or `catalog/default/component/my-new-component`.

## Context
The newly created component is pointing users to the API endpoint when it should be bringing the user to the component page.
For us, additional plugins and dashboard like widgets are mostly hooked onto the component page so bringing the user to the API page after the new component is created is not helpful. 

## Environment
- NodeJS Version (v14): v14.18.0
- Operating System: PopOS 20.04
- Browser Information: Chrome 96.0.4664.45
