### ISSUE TITLE
Scaffolder Validator not called on `type: object` custom field

### ISSUE THREAD

**Issue by goenning** [backstage/backstage#8542]
I have a scaffolder custom field that emits an object like `{ name: 'bar', domain: 'foo' }` using the onChange function. 

This custom field has a validation function which is being passed on to `createScaffolderFieldExtension`

During runtime, this function is never called.

## Expected Behavior

I expected the validation function to be called for custom field of type 'object'

## Current Behavior

Validation function for custom field that emits an object are not being called.

## Possible Solution

I was looking at the `validate` function on the `TemplatePage.tsx` and this is where it's skipping the function call:

https://github.com/backstage/backstage/blob/6ae3e64b14b48d19511c5d34d0166fc9e208830a/plugins/scaffolder/src/components/TemplatePage/TemplatePage.tsx#L78-L102

If the value is an object, it recursivelly validations each individual property. But in my case, I don't have a form of different individual props, I just have a single `type: object` field:

```yaml
parameters:
  - title: Fill in some details
    required:
      - serviceName
    properties:
      serviceName:
        title: Service Name
        type: object
        description: Unique name of this service
        ui:field: MySuperExtension
```

## Context

I actually don't know if this is a bug or an unimplemented feature. I'm happy to send a PR to fix/include this, just want to confirm it's it should work like that or not.

The logic i'm thinking is just invert the if condition, so it'll first check if the field has a validation function, if it doesn't, then check if it's an object and recursively validate it.
