### ISSUE TITLE
[Techdocs] Techdocs looks for files in wrong location in Azure Storage

### ISSUE THREAD

**Issue by ArveSystad** [backstage/backstage#8559]
Given this catalog-info:

```
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Foobar-tech-docs
  description: General tech docs for Foobar
  annotations:
    github.com/project-slug: Foobar/developer-docs
    backstage.io/techdocs-ref: dir:.
```

When the Techdocs plugin locates files, it looks for `/api/techdocs/static/docs/default/component/foobar-tech-docs/index.html`, which looks similar to the path in the Azure Storage Container, except that where it says "foobar-tech-docs", the storage provider has _actually_ created a folder named `developer-docs` (which is the repo-name).

When I modified the catalog-info to have `metadata.name: developer-docs`, it started working.

## Expected Behavior

Tech docs documentation should work even when repository name and `metadata.name` mismatch.

## Current Behavior

404: Mic drop when repository name mismatches component name as specified in catalog-info.yaml.

## Possible Solution

Renaming the `metdata.name` to match repository name fixed it. Seems to indicate that the Azure storage provider constructs different paths to read and write.

## Steps to Reproduce

(This is how I did it, at least)

1. Create a repository `foo` to contain techdocs
2. Create `catalog-info.yaml` with name "bar"
3. When this builds and publishes, you should have a path in Azure Storage: `[...]/component/foo/index.html` 
4. When visiting the tech docs site in Backstage, it'll give a console error with 404 on `[...]/component/bar/index.html`  

## Your Environment

- Azure Container Storage
- Azure AAD auth
- Built and published as a container, running as Azure App Service
- Techdocs built externally; built and published from github action.
