### ISSUE TITLE
Scaffolder - Add ui:options to hide actions/tasks that are Skipped

### ISSUE THREAD

**Issue by regicsolutions** [backstage/backstage#8861]
## Feature Suggestion

It would be great to be able to hide actions/tasks that are skipped vs seeing them listed and grayed out: 

![E3975C94-0C75-4033-AC65-B15D7EBE8E1C](https://user-images.githubusercontent.com/6157895/148883476-ae6b03c6-d27e-4bf5-b88c-47fd30bbf9ee.jpeg)

## Possible Implementation

There is a `ui:widget: hidden` that works in the form, maybe `ui:widget`(s) can also be used for actions? 

https://react-jsonschema-form.readthedocs.io/en/latest/advanced-customization/custom-widgets-fields/

  
  ```
steps:
    - id: fetch-base
      name: Fetch Base
      action: fetch:template
      if: ${{ parameters.name }}
      ui:widget: hidden #Skipped by default?
      input:
        url: ./template
        values:
          name: ${{parameters.name}}
```
