### ISSUE TITLE
Supporting `FeatureFlags` in `scaffolder` templates

### ISSUE THREAD

**Issue by benjdlambert** [backstage/backstage#8870]
## Feature Suggestion
When developing templates it would be really nice if we could show and hide certain parts of the form, either on a field level or a section level so that we can turn off experimental things for most users and turn them on to test with in a production environment.

## Possible Implementation
```yaml
apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: test-v1beta3
  title: Test v1beta3
  description: Test V1 Beta 3 Demo Templates
spec:
  type: website
  owner: team-a
  parameters:
    - name: Enter some stuff
      description: Enter some stuff
      backstage:featureFlag: should-show-some-stuff
      properties:
        inputString:
          type: string
          title: string input test
        inputObject:
          type: object
          title: object input test
          description: a little nested thing never hurt anyone right?
          properties:
            first:
              type: string
              title: first
              backstage:featureFlag: should-show-some-stuff-first-option
            second:
              type: number
              title: second
  steps:
    - id: debug
      if: ${{ true === true }}
      name: Debug
      action: debug:log
      input:
        message: ${{ parameters.inputString }}
        extra: ${{ parameters.inputObject }}
```

Open to different options and bikeshedding the name a little more, but the big picture is here.
