### ISSUE TITLE
Provide each: in software templates

### ISSUE THREAD

**Issue by asummers** [backstage/backstage#8890]
## Feature Suggestion

Consider the example of creating virtual machines via a gitops process. If we consider backstage as it currently functions, we can articulate this sort of thing as:

```
spec:
  parameters:
    # ...
steps:
- name: fetch-repo
   action: fetch:plain
- name: fetch-template
   action: fetch:template   
 - name: publish
   action: publish:github:pull-request   
```

Now imagine we want to make more than one of these for some static N. We can obviously fill this out multiple times but there should be a better way!

Consider also the case of collecting user input in an array form and wanting to do things for each of them. In the VM request form, I may be hitting "add item" in an array input to add multiple things, or using a multiselect, or any number of possible inputs to add additional VMs I wish to create, and I want to act across these. This currently is not possible via backstage without making custom actions that call out to specific actions for each permutation of this.

It would be _fantastic_ if each of these were solvable, and would allow all manners of automation possibilities using backstage templates.

## Possible Implementation

If we just consider what we may like to do in some sort of repeating block, we could tell it to do something N times and if we had access to the index, we could coerce backstage to grab that element where it matters. 

```yaml
- name: Fetch Template
   action: fetch:template
   times: 10
   input:
     url: ./template
     targetPath: '...'
     values:
       version: ${{parameters.version}}
       index: ${{index}}
       object: ${{parameters.objects[$index]}}
```

We may also want to iterate over them, so something like:

```yaml
- name: Fetch Template
   action: fetch:template
   each: ${{parameters.objects}}
   input:
     url: ./template
     targetPath: '...'
     values:
       version: ${{parameters.version}}
       index: ${{index}}
       object: ${{object}}
```

We can probably coerce nunjucks to generate 0..n from an n, so we could get by with just the second I think.

I don't think `${{object}}` or `${{index}}` are necessarily good ways to articulate those, but illustrate the idea.

## Context

There are a large number of automations that boil down to "ask user for input and do it a bunch of times" and I think backstage is exceptionally positioned to be able to make these go away with largely the same primitives that make software templates so useful for n=1.

**Comment by benjdlambert** [comment]
Think I'm a bigger fan of the `each` over `times`, although maybe there is a use for both to avoid duplication and repetition.

Thinking that it would also be good to indicate that `index` and `object` are different, and only to be used in the scope of actions with the `each` repeater, so something like `${{ $item }}` or `${{ $index }}` could be nicer.

**Comment by asummers** [comment]
Fine with the additional `$`. Maybe `$item` and `$index` because object carries different connotations? 

I agree about `times` but there should be some way to express that idea somehow. If it can be articulated via nunjucks, that seems reasonable to remove the special casing.

An alternative name to `each` is `across`, as well. In the context of test matrices, this verbiage makes sense. I have no terribly strong feelings about the names here though =)

**Comment by benjdlambert** [comment]
> If it can be articulated via nunjucks, that seems reasonable to remove the special casing.

I think this is pretty hard to do if we want to keep the entire document still valid yaml, which we do. Having `nunjucks` blocks in the middle of the yaml to repeat steps is I think pretty impossible, but I like what you're thinking. It's why I was trying to keep some of the `nunjucks` semantics around

**Comment by Blackbaud-LeoWanderer** [comment]
I think the above implementation of `each` makes sense for repeating one single step multiple times. How would it work when you want to repeat a set of steps? Let's say you want to execute 2 steps and the output of the first one feeds the input of the second one.

It might be worth considering setting the `$stepId` in the template step so we can use outputs as directed [here](https://backstage.io/docs/features/software-templates/writing-templates#outputs).

**Comment by freben** [comment]
I think this all - at least the multiple-steps idea - starts to sound _way_ too complex. Should it really be in scope for the scaffolder? Sounds more like it's better to write custom actions at this point, and having the framework export implementation pieces such that the loops will be trivial to implement for the adopter. What if the implementation of the `fetch:template` action was basically `() => fetchTemplateImplementation()`, such that anybody could make their own loop calling `fetchTemplateImplementation` any way they see fit?

**Comment by Blackbaud-LeoWanderer** [comment]
That implementation also makes sense to me, even more when you need to just tweak actions based on specific requirements.

The multiple-steps can also implemented if outputs for repeated actions work and can be accessed as arrays too. As an example, let's say you want to create code for multiple regions but before creating some code you need to get attributes for each region. I'd expect to have something like this:

```yaml
...

- id: get-config-${{each.key}}
  name: Retrieve ${{each.name}} config 
  action: custom:getRegionConfig # custom code to get the region config
  each: ${{parameters.regions}} # array or object
  input:
    region: ${{each.name}}

- name: Fetch template for ${{each.name}}
  action: fetch:template
  each: ${{parameters.versions}} # array or object
  input:
    url: ./template
    targetPath: versions/${{each.key}}
    values:
      config1: ${{ steps.['get-config-${{each.key}}'].output.config1 }} # notation needs to be reviewed

...
```
