### ISSUE TITLE
Support passing inputs to built-in ci:github-actions-dispatch action

### ISSUE THREAD

**Issue by peimanja** [backstage/backstage#8979]
## Feature Suggestion

`ci:github-actions-dispatch` action currently only accepts `repoUrl`, `workflowId` and `branchOrTagName`. Based on the [API docs](https://docs.github.com/en/rest/reference/actions#create-a-workflow-dispatch-event), it is possible to also pass `inputs` to the workflow
>Input keys and values configured in the workflow file. The maximum number of properties is 10. Any default properties configured in the workflow file will be used when inputs are omitted.

## Possible Implementation

Adding option key like `workflowInputs`  to https://github.com/backstage/backstage/blob/master/plugins/scaffolder-backend/src/scaffolder/actions/builtin/github/githubActionsDispatch.ts#L35

## Context

I want to be able to pass inputs to the workflow using `github:actions:dispatch` action

```yaml
  steps:
    - id: dispatch-action
      name: Dispatch action
      action: github:actions:dispatch
      input:
        repoUrl: github.com?repo=my-repo&owner=myorg
        branchOrTagName: main
        workflowId: .github/workflows/main.yml
        workflowInputs:
           x: foo
           y: bar
```
