### ISSUE TITLE
Azure AD organizational data cannot be imported following the readme guide

### ISSUE THREAD

**Issue by ngeegoh** [backstage/backstage#9044]
I have followed this README guide to install/ configure backstage to integrate Azure AD organizational data.
https://github.com/backstage/backstage/tree/master/plugins/catalog-backend-module-msgraph

It was good until step 4, after I installed the plugin in backstage backend. When I copied the code to packages/backend/src/plugins/catalog.ts, it started complaining and I don't know what should be done which should have been addressed in the guide. 
I have the errors as in the below screenshot:
![image](https://user-images.githubusercontent.com/32254681/150229606-2a414b70-4a52-46e8-a702-68707faf9801.png)

## Expected Behavior
The guide should have exactly what code should be added to the catalog.ts. Is the documentation missing the import lines? 

## Steps to Reproduce
Follow the guide until after installing @backstage/plugin-catalog-backend-module-msgraph to backend, then adding the code to catalog backend file. Then start yarn dev >> it will throw errors 
Before running yarn dev, the VSCode will also highlight errors in the catalog backend file. 

Hope I could get some help here :) Thanks

**Comment by AntPAllen** [comment]
You need to add the code to the `createPlugin` function. There are also some missing imports from the readme. You don't need lines 32-36 either as that is using the processor. You can choose _either_ the entity provider or the processor. 

Full code catalog.ts should look like this:

```typescript
import { CatalogBuilder, runPeriodically } from '@backstage/plugin-catalog-backend';
import { ScaffolderEntitiesProcessor } from '@backstage/plugin-scaffolder-backend';
import { Router } from 'express';
import { useHotCleanup } from '@backstage/backend-common';
import { PluginEnvironment } from '../types';
import { MicrosoftGraphOrgEntityProvider} from '@backstage/plugin-catalog-backend-module-msgraph';

export default async function createPlugin(
  env: PluginEnvironment,
): Promise<Router> {
  const builder = await CatalogBuilder.create(env);
  builder.addProcessor(new ScaffolderEntitiesProcessor());
  builder.setRefreshIntervalSeconds(300);
  const msGraphOrgEntityProvider = MicrosoftGraphOrgEntityProvider.fromConfig(
    env.config,
    {
      id: 'https://graph.microsoft.com/v1.0',
      target: 'https://graph.microsoft.com/v1.0',
      logger: env.logger,
    },
  );
  builder.addEntityProvider(msGraphOrgEntityProvider);

  useHotCleanup(
    module,
    runPeriodically(() => msGraphOrgEntityProvider.read(), 5 * 60 * 1000),
  );


  const { processingEngine, router } = await builder.build();
  await processingEngine.start();
  return router;
}
```

**Comment by Rugvip** [comment]
Thank you @AntPAllen!

Hoping that fixed it so gonna close this issue. Let us know if you run into any more trouble!

**Comment by ngeegoh** [comment]
Thanks for that @AntPAllen , how about MicrosoftGraphOrgReaderProcessor as its still complaining about it, even though I have imported it from the plugin.
```
import { CatalogBuilder, runPeriodically } from '@backstage/plugin-catalog-backend';
import { ScaffolderEntitiesProcessor } from '@backstage/plugin-scaffolder-backend';
import { Router } from 'express';
import { useHotCleanup } from '@backstage/backend-common';
import { PluginEnvironment } from '../types';
import { MicrosoftGraphOrgEntityProvider} from '@backstage/plugin-catalog-backend-module-msgraph';
+import { MicrosoftGraphOrgReaderProcessor} from '@backstage/plugin-catalog-backend-module-msgraph';

export default async function createPlugin(
  env: PluginEnvironment,
): Promise<Router> {
  const builder = await CatalogBuilder.create(env);
  builder.addProcessor(new ScaffolderEntitiesProcessor());
  builder.setRefreshIntervalSeconds(300);
  const msGraphOrgEntityProvider = MicrosoftGraphOrgEntityProvider.fromConfig(
    env.config,
    {
      id: 'https://graph.microsoft.com/v1.0',
      target: 'https://graph.microsoft.com/v1.0',
      logger: env.logger,
    },
  );
  builder.addEntityProvider(msGraphOrgEntityProvider);

  useHotCleanup(
    module,
    runPeriodically(() => msGraphOrgEntityProvider.read(), 5 * 60 * 1000),
  );

  +builder.addProcessor(
  + MicrosoftGraphOrgReaderProcessor.fromConfig(config, {
  +    logger,
  + }),
  );

  const { processingEngine, router } = await builder.build();
  await processingEngine.start();
  return router;
}
``` 
![image](https://user-images.githubusercontent.com/32254681/150439059-e52682a5-8477-4494-9c01-d20004844a83.png)
Would be great if you can update the documentation to address this so other people wont encounter the same issue :D

**Comment by AntPAllen** [comment]
Hi, that code isn't needed. It mentions in the docs that you can choose either the entity provider or the org processor.

**Comment by ngeegoh** [comment]
Hi @AntPAllen, I see, but even with the entity provider, it still throws that error and backstage cant pull users and groups from Azure AD. Hmm do you think that I might miss out on anything that cause the issue? I think I have got everything set up correctly as mentioned in the guide. This is the config I used in app-config.yaml file. 

```
#app-config.yaml
catalog:
  processors:
    microsoftGraphOrg:
      providers:
        - target: https://graph.microsoft.com/v1.0
          authority: https://login.microsoftonline.com
          tenantId: 'xxx'
          clientId: 'xxx'
          clientSecret: 'xxx'
          userFilter: 'accountEnabled eq true'
          groupFilter: 'securityEnabled eq false'
  rules:
    - allow: [Component, System, API, Group, User, Resource, Location, Domain]
  locations:
    - type: microsoft-graph-org
      target: https://graph.microsoft.com/v1.0
      rules:
        - allow: [Group, User]
```

The Azure service principal I used have been granted the following permissions:
![image](https://user-images.githubusercontent.com/32254681/150475627-ac8c3d68-a1c3-4d4d-821c-08b746612d30.png)

In the catalog-info.yaml file, I added spec.owner:azure-ad-group
But when I ran yarn dev and when I click on the owner group, it still couldnt find the group from Azure AD and returns entity not found error. 

```
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: app-test
  description: test
spec:
  type: service
  lifecycle: experimental
  owner: <azure ad group>
```

FYI: I have configured to integrate GitHub organizational data to Backstage as well and it works fine, when I added spec.owner:github-group in catalog-info.yaml. It does return Github group information but doesnt work for Azure AD groups. Hmm since I have configured to get organizational data from both Github and Azure AD, do I need to specify anything in catalog to let Backstage know which source it found look for when pulling organizational data for the owner group in the above case?

**Comment by AntPAllen** [comment]
What errors are you getting?

**Comment by ngeegoh** [comment]
Hi @AntPAllen,  I am having this error: 
`catalog warn No processor was able to handle reading of microsoft-graph-org:https://graph.microsoft.com/v1.0 type=plugin entity=location:default/generated-1bbd0c2eedda38f1c4b213e1484858d10c91f296`
Not sure what I might have missed out in the configuration. The github organizational data works fine though.

**Comment by AntPAllen** [comment]
Can you paste in how your catalog.ts looks now?

**Comment by ngeegoh** [comment]
This is how it looks now. 
```
#backend/src/plugins/catalog.ts
import { CatalogBuilder, runPeriodically } from '@backstage/plugin-catalog-backend';
import { ScaffolderEntitiesProcessor } from '@backstage/plugin-scaffolder-backend';
import { Router } from 'express';
import { useHotCleanup } from '@backstage/backend-common';
import { PluginEnvironment } from '../types';
import { MicrosoftGraphOrgEntityProvider} from '@backstage/plugin-catalog-backend-module-msgraph';
// import { MicrosoftGraphOrgReaderProcessor} from '@backstage/plugin-catalog-backend-module-msgraph';

export default async function createPlugin(
  env: PluginEnvironment,
): Promise<Router> {
  const builder = await CatalogBuilder.create(env);
  builder.addProcessor(new ScaffolderEntitiesProcessor());
  builder.setRefreshIntervalSeconds(300);
  const msGraphOrgEntityProvider = MicrosoftGraphOrgEntityProvider.fromConfig(
    env.config,
    {
      id: 'https://graph.microsoft.com/v1.0',
      target: 'https://graph.microsoft.com/v1.0',
      logger: env.logger,
    },
  );
  builder.addEntityProvider(msGraphOrgEntityProvider);

  useHotCleanup(
    module,
    runPeriodically(() => msGraphOrgEntityProvider.read(), 5 * 60 * 1000),
  );

  const { processingEngine, router } = await builder.build();
  await processingEngine.start();
  return router;
}
```

**Comment by AntPAllen** [comment]
A silly question maybe, but you are waiting at least 5 minutes after starting backstage? It might take a little longer, you as long as you have your log level set to info you should see "Reading msgraph users and groups" in the logs when it starts.

**Comment by ngeegoh** [comment]
Yes I have waited longer than 5 mins after starting backstage, but I still see that error
`atalog warn No processor was able to handle reading of microsoft-graph-org:https://graph.microsoft.com/v1.0 type=plugin entity=location:default/generated-1bbd0c2eedda38f1c4b213e1484858d10c91f296`
and I also can see the info log
`catalog info Reading msgraph users and groups type=plugin target=https://graph.microsoft.com/v1.0`
but the group is still not working correctly, when I clicked on the owner group name, it still says 'Entity not found'

**Comment by AntPAllen** [comment]
Do you have any groups or users from azure ad at all when you change the catalog page view to users or groups?

**Comment by ngeegoh** [comment]
Yes I do have that defined group in azure ad, but it cant be found in backstage. Do we have to specify somewhere in catalog-info spec.owner which source it should pull from either github or azure ad? as i still dont know how backstage can detect and know owner is from either azure ad or github, but the github groups are able to displayed fine though.

**Comment by AntPAllen** [comment]
Sorry, I mean do you see _any_ users or groups from azure ad when you look under users in the backstage catalog:

![image](https://user-images.githubusercontent.com/54019849/150526145-c8a7c077-df51-4859-96f6-4abe4329c9e6.png)

**Comment by ngeegoh** [comment]
I can see all the users and groups in backstage, but they are all from Github not from azure ad.

**Comment by AntPAllen** [comment]
Hmm, I'm at a loss. One thing you can do just to verify that you can list users is use azcli to see if you can list the users when logging in with the service principal

```sh
az login --service-principal -u <client_id> -p <client_secret> -t <tenant_id>
az ad group list --filter "securityEnabled eq true"
```

If that doesn't work then I guess someone from the backstage team needs to get involved. Pinging in @Rugvip

**Comment by Rugvip** [comment]
I see you've set up the `MicrosoftGraphOrgEntityProvider`, which is more or less a new and improved version of the `microsoft-graph-org` location processor. You should be able to safely remove the related configuration under the `catalog:` key.

As for the rest of the issue I'm not sure. I'm also interested in what actual users and groups you are seeing in the catalog. You don't have any GitHub ingestion set up, so it would surprise me if you are actually seeing users from your GitHub organization.

**Comment by ngeegoh** [comment]
Hi @AntPAllen, 

I have ran the 2 AZ commands you suggested and it returned insuffiecient privileges error even though the SPN has been granted all the read permission as told in the guide. 
![image](https://user-images.githubusercontent.com/32254681/150716549-0dbbe7eb-e047-4d17-a177-2b8a78446bf0.png)
This is the list of permissions added for the SPN
![image](https://user-images.githubusercontent.com/32254681/150716595-be0ca5fd-7acf-410e-9cb2-b6931ee1fb55.png)

Hi @Rugvip, hmm what do you mean by removing the related configuratoion under the catalog: ?? you want me to remove this part?
```
#app-config.yaml
catalog:
[removing the whole part ??]
  processors:
    microsoftGraphOrg:
      providers:
        - target: https://graph.microsoft.com/v1.0
          authority: https://login.microsoftonline.com
          tenantId: 'xxx'
          clientId: 'xxx'
          clientSecret: 'xxx'
          userFilter: 'accountEnabled eq true'
          groupFilter: 'securityEnabled eq false'
  rules:
    - allow: [Component, System, API, Group, User, Resource, Location, Domain]
  locations:
    - type: microsoft-graph-org
      target: https://graph.microsoft.com/v1.0
      rules:
        - allow: [Group, User]
[removing this whole part ??]
```
I have github org set up though, thats why backstage can pull Github organizational data with this line under catalog:
```
- type: github-org
      target: https://github.com/woolworthslimited
```
