### ISSUE TITLE
Boolean fields doesn't work properly in scaffolder templates after Start Over

### ISSUE THREAD

**Issue by nikmel2803** [backstage/backstage#9157]
## Expected Behavior

Consider the following piece of scaffolder template:

```yml
spec:
  owner: dx-team
  type: website

  # these are the steps which are rendered in the frontend with the form input
  parameters:
    - title: Docker registry
      properties:
        setup_docker_registry:
          title: Setup Docker registry
          type: boolean
          default: false
```

If we do not select this checkbox (false state), and after creating the project from the template we press the "start over" button, then the checkbox will become active.

<img width="1326" alt="Снимок экрана 2022-01-25 в 08 26 19" src="https://user-images.githubusercontent.com/32655339/150916675-cc92fd9a-c13e-4ebd-9b09-9abb81bff76b.png">

Expected Behavior: checkmark in false state

## Current Behavior

In the picture above, you can see that setup_docker_registry URL param is set to false, but the checkbox is set to true.

## Possible Solution

I think the problem is the wrong typecasting. All parameters from the URL are read as strings, and in this case the string must be converted to boolean.

## Steps to Reproduce

1) Create template from the following manifest

```yml
apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: react
  title: React project template
  description: Template from which you can create a frontend application
  tags:
    - frontend
    - template
spec:
  owner: dx-team
  type: website
  parameters:
    - title: Docker registry
      properties:
        setup_docker_registry:
          title: Setup Docker registry
          type: boolean
          default: false
```

2) Register this template in your backstage app
3) go to the page for creating a project from this template
4) Leave checkbox unchecked (false state)
5) start project creating
6) Press "Start Over" button

## Context

This bug leads to bad UX when using project templates

## Your Environment

```
$ /app/node_modules/.bin/backstage-cli info
OS:   Linux 4.18.0-305.7.1.el8_4.x86_64 - linux/x64
node: v16.13.2
yarn: 1.22.15
cli:  0.11.0 (installed)

Dependencies:
  @backstage/app-defaults                                  0.1.4
  @backstage/backend-common                                0.10.3
  @backstage/backend-tasks                                 0.1.3
  @backstage/catalog-client                                0.5.4
  @backstage/catalog-model                                 0.9.9
  @backstage/cli-common                                    0.1.6
  @backstage/cli                                           0.11.0
  @backstage/config-loader                                 0.9.2
  @backstage/config                                        0.1.12
  @backstage/core-app-api                                  0.4.0
  @backstage/core-components                               0.7.6, 0.8.4
  @backstage/core-plugin-api                               0.1.13, 0.2.2, 0.5.0
  @backstage/dev-utils                                     0.2.17
  @backstage/errors                                        0.1.5, 0.2.0
  @backstage/integration-react                             0.1.18
  @backstage/integration                                   0.7.1
  @backstage/plugin-api-docs                               0.6.22
  @backstage/plugin-app-backend                            0.3.21
  @backstage/plugin-auth-backend                           0.6.2
  @backstage/plugin-catalog-backend                        0.20.0
  @backstage/plugin-catalog-common                         0.1.0
  @backstage/plugin-catalog-import                         0.7.9
  @backstage/plugin-catalog-react                          0.6.11
  @backstage/plugin-catalog                                0.7.8
  @backstage/plugin-github-actions                         0.4.31
  @backstage/plugin-org                                    0.3.34
  @backstage/plugin-permission-common                      0.3.1
  @backstage/plugin-permission-node                        0.3.0
  @backstage/plugin-permission-react                       0.2.2
  @backstage/plugin-proxy-backend                          0.2.15
  @backstage/plugin-scaffolder-backend-module-cookiecutter 0.1.8
  @backstage/plugin-scaffolder-backend                     0.15.20
  @backstage/plugin-scaffolder-common                      0.1.2
  @backstage/plugin-scaffolder                             0.11.18
  @backstage/plugin-search-backend-node                    0.4.4
  @backstage/plugin-search-backend                         0.3.0
  @backstage/plugin-search                                 0.5.5
  @backstage/plugin-sentry                                 0.3.33
  @backstage/plugin-tech-radar                             0.5.2
  @backstage/plugin-techdocs-backend                       0.12.3
  @backstage/plugin-techdocs                               0.12.14
  @backstage/plugin-todo-backend                           0.1.18
  @backstage/plugin-todo                                   0.1.18
  @backstage/plugin-user-settings                          0.3.16
  @backstage/search-common                                 0.2.1
  @backstage/techdocs-common                               0.11.3
  @backstage/test-utils                                    0.2.2
  @backstage/theme                                         0.2.14
  @backstage/types                                         0.1.1
  @backstage/version-bridge                                0.1.1
Done in 1.10s.
```
- Browser Information: Chrome, Safari (last versions)
