### ISSUE TITLE
Failed to connect to Postgres database after running Docker image on local machine

### ISSUE THREAD

**Issue by phamngocthanhtrung** [backstage/backstage#9197]
If I run `yarn dev` on my local machine without dockerizing the app, it works.
Since I want to deploy it on Heroku, I need to dockerize this app. 
Based on your documentation, I want to make a host build.
But when I run this image, it cannot connect to my local Postgres DB, let alone a remote DB. 

yarn install 
yarn tsc
yarn build
yarn build-image --> docker image build . -f packages/backend/Dockerfile --tag backstage 
docker run -it -p 7007:7007 backstage 

Terminal
```sh
2022-01-27T05:29:02.792Z backstage info Loaded config from app-config.yaml 
2022-01-27T05:29:02.797Z backstage info 1 secrets found in the config which will be redacted 
2022-01-27T05:29:02.805Z backstage info Created UrlReader predicateMux{readers=azure{host=dev.azure.com,authed=false},bitbucket{host=bitbucket.org,authed=false},github{host=github.com,authed=false},gitlab{host=gitlab.com,authed=true},awsS3{host=amazonaws.com,authed=false},fetch{} 
Backend failed to start up, Error: Failed to connect to the database to make sure that 'backstage_plugin_catalog' exists, Error: connect ECONNREFUSED 127.0.0.1:5432
```

app-config
```yml
app:
  title: Scaffolded Backstage App
  baseUrl: http://localhost:3000

organization:
  name: My Company

backend:
  # Used for enabling authentication, secret is shared by all backend plugins
  # See backend-to-backend-auth.md in the docs for information on the format
  # auth:
  #   keys:
  #     - secret: ${BACKEND_SECRET}
  baseUrl: http://localhost:7007
  listen:
    port: 7007
  csp:
    connect-src: ["'self'", 'http:', 'https:']
    # Content-Security-Policy directives follow the Helmet format: https://helmetjs.github.io/#reference
    # Default Helmet Content-Security-Policy values can be removed by setting the key to false
  cors:
    origin: http://localhost:3000
    methods: [GET, POST, PUT, DELETE]
    credentials: true
  database:
    # # SQLite
    # client: sqlite3
    # connection: ':memory:'
    # Postgres
    client: pg
    connection:
      host: 127.0.0.1
      port: 5432
      user: postgres
      password: postgres
  cache:
    store: memory
  # workingDirectory: /tmp # Use this to configure a working directory for the scaffolder, defaults to the OS temp-dir

integrations:
  gitlab:
    - host: gitlab.com
      token: ${GITLAB_TOKEN}
      ### Example for how to add your GitHub Enterprise instance using the API:
      # - host: ghe.example.net
      #   apiBaseUrl: https://ghe.example.net/api/v3
      #   token: ${GHE_TOKEN}

proxy:
  '/test':
    target: 'https://example.com'
    changeOrigin: true

# Reference documentation http://backstage.io/docs/features/techdocs/configuration
# Note: After experimenting with basic setup, use CI/CD to generate docs
# and an external cloud storage when deploying TechDocs for production use-case.
# https://backstage.io/docs/features/techdocs/how-to-guides#how-to-migrate-from-techdocs-basic-to-recommended-deployment-approach
techdocs:
  builder: 'local' # Alternatives - 'external'
  generator:
    runIn: 'docker' # Alternatives - 'local'
  publisher:
    type: 'local' # Alternatives - 'googleGcs' or 'awsS3'. Read documentation for using alternatives.

auth:
  # see https://backstage.io/docs/auth/ to learn about auth providers
  providers:
    gitlab:
      development:
        clientId: ${AUTH_GITLAB_CLIENT_ID}
        clientSecret: ${AUTH_GITLAB_CLIENT_SECRET}

scaffolder:
  # see https://backstage.io/docs/features/software-templates/configuration for software template options

catalog:
  rules:
    - allow:
        - Component
        - API
        - Resource
        - Group
        - User
        - Template
        - System
        - Domain
        - Location
  locations:
      # Linking to local repository
    - type: file
      target: ../../../../software-templates/scaffolder-templates/custom-repository/template.yaml
      rules:
        - allow: [Template]
    - type: file
      target: ../../../../software-templates/scaffolder-templates/springboot-grpc-template/template.yaml
      rules:
        - allow: [Template]
```

```dockerfile
FROM node:14-buster-slim

WORKDIR /app

# Copy repo skeleton first, to avoid unnecessary docker cache invalidation.
# The skeleton contains the package.json of each package in the monorepo,
# and along with yarn.lock and the root package.json, that's enough to run yarn install.
COPY yarn.lock package.json packages/backend/dist/skeleton.tar.gz ./
RUN tar xzf skeleton.tar.gz && rm skeleton.tar.gz

RUN yarn install --frozen-lockfile --production --network-timeout 300000 && rm -rf "$(yarn cache dir)"

# Then copy the rest of the backend bundle, along with any other files we might want.
COPY packages/backend/dist/bundle.tar.gz app-config.yaml ./
RUN tar xzf bundle.tar.gz && rm bundle.tar.gz

CMD ["node", "packages/backend", "--config", "app-config.yaml"]
```

local postgres db 
`docker run -p 5432:5432 -e POSTGRES_PASSWORD=postgres postgres:latest`
