### ISSUE TITLE
Helm chart does not let you serve the frontend from the backend

### ISSUE THREAD

**Issue by rcollier-goodrx** [backstage/backstage#9248]
The helm chart in its current form does not allow one to serve the frontend from the backend because the ingress definition expects there to be a `backstage-frontend` service to route traffic from the ingress --> service --> pods. [The documentation](https://backstage.io/docs/deployment/helm) also states that the following app-config will give you a frontend when it does not.

```
appConfig:
  app:
    baseUrl: https://backstage.mydomain.com
    title: Backstage
  backend:
    baseUrl: https://backstage.mydomain.com
    cors:
      origin: https://backstage.mydomain.com
  lighthouse:
    baseUrl: https://backstage.mydomain.com/lighthouse-api
  techdocs:
    storageUrl: https://backstage.mydomain.com/api/techdocs/static/docs
    requestUrl: https://backstage.mydomain.com/api/techdocs
```

When I deploy this as is I get no frontend service or pod deployed to my cluster. The only way to get those resources created is to enable the frontend. 

## Expected Behavior

A successful deployment of the helm chart should at a minimum allow you to serve the frontend from the backend if you do not wish to break the frontend out from the backend. The ingress should be configured in such a way so that it routes traffic for `/` to the corresponding backend-service service in kubernetes.

## Current Behavior

The helm chart does not allow you to serve the frontend from the backend in the current configuration. In the current configuration, the ingress points to a frontend-service that does not exist if you do not enable the frontend.
