### ISSUE TITLE
Is it possible to connect to the Heroku Postgres DB ? 

### ISSUE THREAD

**Issue by phamngocthanhtrung** [backstage/backstage#9250]
I tried to use the Postgres DB with this configuration in app-config.yaml

```yml
database:
    client: pg
    connection:
      postgres://xxxxxxxxx:asdwasdwasdwasdwasdwasdwasdw@ec2-xx-xxx-xxx-xxx.eu-west-1.compute.amazonaws.com:5432/wasdasdd
```

I get this error:

```sh
[1] 2022-01-29T07:06:19.692Z backstage info Loaded config from app-config.yaml 
[1] 2022-01-29T07:06:19.698Z backstage info 0 secrets found in the config which will be redacted 
[1] 2022-01-29T07:06:19.711Z backstage info Created UrlReader predicateMux{readers=azure{host=dev.azure.com,authed=false},bitbucket{host=bitbucket.org,authed=false},github{host=github.com,authed=false},gitlab{host=gitlab.com,authed=false},awsS3{host=amazonaws.com,authed=false},fetch{} 
[1] Backend failed to start up, Error: Failed to connect to the database to make sure that 'backstage_plugin_catalog' exists, error: no pg_hba.conf entry for host "xx.xxx.xxx.xxx", user "xxxxxxxxx", database "postgres", SSL off
```

I thought maybe I should enable ssl. 
when I add    `ssl=true` to the path, I get an error message:

```sh
[1] Backend failed to start up, Error: Failed to connect to the database to make sure that 'backstage_plugin_catalog' exists, Error: self signed certificate
```

**Comment by jhaals** [comment]
The error indicates that the certificate that the server uses is self signed meaning the CA cert is not in the default certificate store. You can tell node to accept the CA cert by supplying it as an environment variable when the backend starts using `NODE_EXTRA_CA_CERTS`. https://nodejs.org/api/cli.html#node_extra_ca_certsfile

**Comment by phamngocthanhtrung** [comment]
> The error indicates that the certificate that the server uses is self signed meaning the CA cert is not in the default certificate store. You can tell node to accept the CA cert by supplying it as an environment variable when the backend starts using `NODE_EXTRA_CA_CERTS`. https://nodejs.org/api/cli.html#node_extra_ca_certsfile

Hi, thank you very much for the answer!

As I understand it, I now need to create an RSA key on my local machine and put the path to the PEM file in the NODE_EXTRA_CA_CERTS variable, right? 
export NODE_EXTRA_CA_CERTS=/path/to/ca_cert.pem 

So the backend should be able to connect to the Postgres DB of Heroku, right ?

**Comment by jhaals** [comment]
The usage of the environment variable is correct but you do not need to create any RSA keys on your machine. The database UI/panel should possibly have a CA certificate that you can use when connecting. I don't know how to connect to your database specifically but there shouldn't be any limitations in Backstage that prevents you from doing it.

**Comment by phamngocthanhtrung** [comment]
> The usage of the environment variable is correct but you do not need to create any RSA keys on your machine. The database UI/panel should possibly have a CA certificate that you can use when connecting. I don't know how to connect to your database specifically but there shouldn't be any limitations in Backstage that prevents you from doing it.

Hi @jhaals 

I downloaded the certificate from the browser data.heroku.com.cer and converted it to certificate.pem and put it in /etc/ssl/certs/certificate.pem.

command:
`openssl x509 -inform der -in data.heroku.com.cer -out certificate.pem`

then I set "export NODE_EXTRA_CA_CERTS=/etc/ssl/certs/certificate.pem"

unfortunately it doesn't work either and I still get the error 
`Backend failed to start up, Error: Failed to connect to the database to make sure that 'backstage_plugin_catalog' exists, Error: self signed certificate`

**Comment by gabriel-dantas98** [comment]
It seems to me to be a characteristic of Heroku itself.
Using the free plans, the databases are shared and we only have access to one database.
Bastage creates several databases (catalog, auth) so if the idea is to test the free Heroku plan, the option is to use the sqlite 
database.

I tried to make several different configurations but several errors happened.
But I was not successful 😞

**Comment by gabriel-dantas98** [comment]
My attempt that I found most promising was this one:

```yaml
  database:
    client: pg
    connection:
      host:
        $env: POSTGRESQL_HOST
      port:
        $env: POSTGRESQL_PORT
      user:
        $env: POSTGRESQL_USER
      password:
        $env: POSTGRESQL_PASSWORD
    knexConfig:
      debug: true
    plugin:
      auth:
        database: 
          $env: POSTGRESQL_DATABASE
      catalog:
        database:
          $env: POSTGRESQL_DATABASE
 ```
 
 _Heroku logs:_ `app[web.1]: Backend failed to start up, Error: Failed to connect to the database to make sure that schema for plugin 'catalog' exists, Error: connect ECONNREFUSED 127.0.0.1:5432`
 
 Then I tried to enable this option  `pluginDivisionMode: 'schema'`
 
 _Heroku logs:_ `Backend failed to start up, Error: Failed to connect to the database to make sure that 'backstage_plugin_catalog' exists, Error: connect ECONNREFUSED 127.0.0.1:5432`

**Comment by freben** [comment]
Oh but for that situation, `pluginDivisionMode: 'schema'` is definitely the right approach. Now we just have to figure out why you aren't even allowed to connect in the first place... I presume you don't have access to db server logs? Something that may hint at WHY the connection was refused.

**Comment by kwent** [comment]
Trying to make it work on heroku as well and hitting a similar issue. I opened a ticket on here https://github.com/backstage/demo/issues/50 so we can fix it AND add a functional heroku configuration file with a persistent database so people doesn't struggle with this anymore.

**Comment by benjdlambert** [comment]
@kwent re: https://github.com/backstage/demo/issues/50 what do you think we need to do to get it working with heroku?

**Comment by kwent** [comment]
@benjdlambert Because some of us are running their business on heroku i believe

**Comment by benjdlambert** [comment]
I think it's a perfectly reasonable to get working, it's just we don't have the time to look at getting that setup now, so just so we can get some information on what is missing and hopefully get someone to contribute a fix for it. 👍

**Comment by kwent** [comment]
I think the documentation is lacking. It works fine for sqlite based but as you might know, dyno's run on an ephemeral filesystem and so redeploying will wipe your data. So

- Improve the documentation to handle a persistent database (postgres is fine)
- Have a `app-config.production.yaml` ready to be copy pasted for heroku.

**Comment by e0d** [comment]
Just to make sure I'm parsing this thread correctly, the current status is that Backstage will not work on Heroku with PostgreSQL?  @kwent is referring to documentation changes rather than code changes, so I wasn't sure whether he'd got this working or not.

I'm facing the same issue with plugin DBs

`Error: Failed to connect to the database to make sure that 'backstage_plugin_catalog' exists, error: permission denied for database "postgres" `

**Comment by e0d** [comment]
To answer my own question, code changes are required.  A separate issue was opened above related to the required changes.

https://github.com/backstage/demo/issues/50

**Comment by kwent** [comment]
@e0d i never got it working but i'm still VERY interested to make it work :) Unsure where to begin tbh

**Comment by gabriel-dantas98** [comment]
Hi folks :D I went to do some tests and managed to progress.

<img width="613" alt="image" src="https://user-images.githubusercontent.com/20074620/176063331-109faf32-8f29-46d0-9c95-17833616f8e7.png">

![image](https://user-images.githubusercontent.com/20074620/176063840-a1691de6-a5e1-4539-8d35-d1b8aa094fc1.png)

```yaml
  database:
    client: pg
    ensureExists: false
    pluginDivisionMode: 'schema'
    connection:
      host: ${POSTGRES_HOST}
      port: ${POSTGRES_PORT}
      user: ${POSTGRES_USER}
      password: ${POSTGRES_PASSWORD}
      database: ${POSTGRESQL_DATABASE}
```
<img width="288" alt="image" src="https://user-images.githubusercontent.com/20074620/176064109-edd7bac5-3567-4a11-806b-283e595cec74.png">


I imagine these are not the best settings, but it might help with troubleshooting.

**Comment by e0d** [comment]
@gabriel-dantas98 I tried something similar a month ago with no luck.  I ended up spinning up a separate AWS RDS PostgreSQL database and connecting to it.  

I'm curious about this setting

`ensureExists: false`

I wonder if the breakage in only when checking if the database exists and the migrations will happen if that check isn't executed.

Without the benefit of stepping through the code it looked to me like [this](https://github.com/backstage/backstage/blob/master/packages/backend-common/src/database/connectors/postgres.ts#L113) is forcing the exists check to use the postgres DB which you won't have available in Heroku where the db is randomly generated.

**Comment by gabriel-dantas98** [comment]
> @gabriel-dantas98 I tried something similar a month ago with no luck. I ended up spinning up a separate AWS RDS PostgreSQL database and connecting to it.
> 
> I'm curious about this setting
> 
> `ensureExists: false`
> 
> I wonder if the breakage in only when checking if the database exists and the migrations will happen if that check isn't executed.
> 
> Without the benefit of stepping through the code it looked to me like [this](https://github.com/backstage/backstage/blob/master/packages/backend-common/src/database/connectors/postgres.ts#L113) is forcing the exists check to use the postgres DB which you won't have available in Heroku where the db is randomly generated.

@e0d I don't know if I understand your question well and if it can happen that you don't run some migration in case you enable this flag?

@kwent Does this configuration help your case?

**Comment by gabriel-dantas98** [comment]
**update:** I noticed that we can use the connection string directly, so we don't need to create the environment variables for each attribute.

So the app-config.yaml would look like:

```yaml
database:
  client: pg
  ensureExists: false
  pluginDivisionMode: 'schema'
  connection: ${DATABASE_URL}
```

**Comment by gabriel-dantas98** [comment]
@jhaals 
Are there any tradeoffs in using this approach?

If it's ok, I can update the documentation with these details :)

**Comment by kwent** [comment]
@gabriel-dantas98 still seeing

with

```yaml
database:
  client: pg
  ensureExists: false
  pluginDivisionMode: 'schema'
  connection: ${DATABASE_URL}
```

```
Backend failed to start up, Error: Failed to connect to the database to make sure that schema for plugin 'catalog' exists, error: no pg_hba.conf entry for host "xx", user "xx", database "xx", no encryption
```

with

```yaml
  database:
    client: pg
    ensureExists: false
    pluginDivisionMode: 'schema'
    connection: ${DATABASE_URL}
    plugin:
      auth:
        database: 
          $env: DATABASE_URL
      catalog:
        database:
          $env: DATABASE_URL
```

```
Backend failed to start up, Error: Failed to connect to the database to make sure that schema for plugin 'catalog' exists, error: no pg_hba.conf entry for host "xx", user "xx", database "xx", no encryption
```

No luck.

**Comment by e0d** [comment]
@gabriel-dantas98 which Heroku PostgresSQL add on are you using I wonder?  There are some third-party add ons so I'm curious if that's the difference here.

**Comment by kwent** [comment]
Default one. `heroku-postgresql` -> `hobby-dev`

**Comment by gabriel-dantas98** [comment]
> @gabriel-dantas98 still seeing
> 
> with
> 
> ```yaml
> database:
>   client: pg
>   ensureExists: false
>   pluginDivisionMode: 'schema'
>   connection: ${DATABASE_URL}
> ```
> 
> ```
> Backend failed to start up, Error: Failed to connect to the database to make sure that schema for plugin 'catalog' exists, error: no pg_hba.conf entry for host "xx", user "xx", database "xx", no encryption
> ```
> 
> with
> 
> ```yaml
>   database:
>     client: pg
>     ensureExists: false
>     pluginDivisionMode: 'schema'
>     connection: ${DATABASE_URL}
>     plugin:
>       auth:
>         database: 
>           $env: DATABASE_URL
>       catalog:
>         database:
>           $env: DATABASE_URL
> ```
> 
> ```
> Backend failed to start up, Error: Failed to connect to the database to make sure that schema for plugin 'catalog' exists, error: no pg_hba.conf entry for host "xx", user "xx", database "xx", no encryption
> ```
> 
> No luck.

Did you set the PGSSLMODE environment variable?
```bash
heroku config:set PGSSLMODE="no-verify" --app <project-name>
```

**Comment by tuler** [comment]
I'm using the suggestions in this post but I'm still getting the following error:

```
Backend failed to start up error: create table "knex_migrations" ("id" serial primary key, "name" varchar(255), "batch" integer, "migration_time" timestamptz) - no schema has been selected to create in
```

**Comment by e0d** [comment]
Hard to guess without seeing your config.

**Comment by tuler** [comment]
This is my config:

```
  database:
    client: pg
    ensureExists: false
    pluginDivisionMode: 'schema'
    connection: ${DATABASE_URL}
    plugin:
      auth:
        database:
          $env: DATABASE_URL
      catalog:
        database:
          $env: DATABASE_URL
```

**Comment by e0d** [comment]
Does the user have permissions to that database?  If you login from psql as that user can you create a trivial table?  

I had initially suspected that database property was not specified.

**Comment by tuler** [comment]
Yes, the user has permission to create a table. Just tested using the psql console.

**Comment by e0d** [comment]
Sorry should have asked this first.  Are you attempting to connect to Postgres on Heroku?  It wasn't clear to me from the thread that that was working for anyone.  I moved on to Postgres hosted elsewhere.

**Comment by freben** [comment]
With the schema division mode it'll try to create a schema too first, per plugin - right?

**Comment by e0d** [comment]
Yes, for example, in my DB.

| Name             |   Owner   | Encoding |   Collate   |    Ctype    |    Access privileges    |
| ------------------ | ------------ | ------------ | ------------ | -------------- | ---------------------------- |
| backstage_plugin_app        | backstage | UTF8     | en_US.UTF-8 | en_US.UTF-8 | 
| backstage_plugin_auth       | backstage | UTF8     | en_US.UTF-8 | en_US.UTF-8 | 
| backstage_plugin_catalog    | backstage | UTF8     | en_US.UTF-8 | en_US.UTF-8 |
| backstage_plugin_scaffolder | backstage | UTF8     | en_US.UTF-8 | en_US.UTF-8 |
| backstage_plugin_search     | backstage | UTF8     | en_US.UTF-8 | en_US.UTF-8 |

**Comment by tuler** [comment]
The following change makes me end up with the error #11218

```diff
  database:
    client: pg
    ensureExists: false
    pluginDivisionMode: 'schema'
    connection: ${DATABASE_URL}
    ssl: true
+    knexConfig:
+      searchPath: ['knex', 'public']
    plugin:
      auth:
        database:
          $env: DATABASE_URL
      catalog:
        database:
          $env: DATABASE_URL
```

**Comment by able8** [comment]
I also got the "no schema has been selected to create in" error with the setting `ensureExists: false`.
Fixed this error by setting `ensureExists: true`.
cc @tuler 
My error log:
```
2022-12-05T06:26:54.202Z catalog info Performing database migration type=plugin
Backend failed to start up, error: create table "knex_migrations" ("id" serial primary key, "name" varchar(255), "batch" integer, "migration_time" timestamptz) - no schema has been selected to create in
```

**Comment by hone** [comment]
You don't want to set:

```YAML
knexConfig:
  searchPath: ['knex', 'public']
```
This will create all the tables into the public schema, which is why you see the corruption error. Each plugin needs to be in its own schema if you're using a single database which is likely on Heroku. I managed to get a version of it working, but I had to run `CREATE SCHEMA` by hand for each plugin's namespace. For the standard scaffold that are these namespaces:

* app
* auth
* catalog
* scaffolder
* search

I haven't dug into the code, but does setting `ensureExists` to false skip the schema creation?

**Comment by chap** [comment]
Trying to fix this with #24577

**Comment by jonico** [comment]
Confirming this is fixed  - thanks @chap 🎉 

Working configuration:

```
backend:
  database:
    client: pg
    ensureExists: false
    ensureSchemaExists: true
    pluginDivisionMode: schema
    connection: ${DATABASE_URL}
```
