### ISSUE TITLE
proposal(TechDocs): Add Theming Support For Tech Docs Pages

### ISSUE THREAD

**Issue by therynamo** [backstage/backstage#9342]
## Feature Suggestion
Currently there is no easy way to provide theming modifications to the Tech Docs pages themselves. Specifically the `Syntax Highlighting` is at a very illegible contrast and renders reading code blocks more difficult than it should be. 

![image](https://user-images.githubusercontent.com/8508556/152392738-32da261a-700d-4e72-bd3a-206b749446a6.png)

The combination of `pink`, `green`, and `blue` makes it difficult for most users to view, and extremely difficult for color blind users like myself. 

## Possible Implementation
Without trying to implement custom theming for all of backstage - I'd likely focus on allowing specific feature sets of Tech Docs to be adjusted. One potential MVP could be to simply allow for Tech Docs pages to be themed differently with a few select values like:

- Sidebar
- Primary Text
- Secondary Text
- Syntax
  - Primary
  - Secondary
  - Tertiary

Another approach could be to allow for these types of things to be pluggable. For instance - there are some issues here where folks don't want to utilize `mkdocs` as their Mark Down processor. These pieces of Tech Docs could be pluggable to allow for users to use, say, [MDX v2](https://mdxjs.com/blog/v2/). Having a pluggable process could allow for other syntax highlighting libraries to be used in place of the one that already exists. The benefit to this approach is once its implemented - anyone can plug and play their own libraries, or even implementations, of the pieces that make up a "Tech Doc". 

 

## Context

We really like the idea of Tech Docs - but the legibility of the docs needs to be there or adoption in our particular use case will be very low.

**Comment by emmaindal** [comment]
Hello @therynamo thanks for opening the issue. Just some clarifying questions

1. Is this mostly when using the dark theme setting or is the color contrast poor when using light theme too? 
2. Do you want to have the possibility to adjust the background color, to increase the color contrast or the actual colors of the code snippet?

**Comment by therynamo** [comment]
> Hello @therynamo thanks for opening the issue. Just some clarifying questions
> 
> 1. Is this mostly when using the dark theme setting or is the color contrast poor when using light theme too?
> 2. Do you want to have the possibility to adjust the background color, to increase the color contrast or the actual colors of the code snippet?

@emmaindal - thanks for the questions! 

1. I haven't tested with the light theme - only the dark one. 
2. It'd be great to be able to adjust the colors themselves - but I don't want to impede progress on accessibility so I'd take either 👍 

As a feature - custom theming would be pretty great and we could leverage brand colors and such. Theming down to the syntax highlighting level, or more ubiquitous options like `Dracula` or `Solarized`, would be spectacular. 

I hope that helps! Let me know if you have any other questions.

**Comment by rmartine-ias** [comment]
This issue came up when searching for how to do this; I didn't find a ready-made solution, here's the hack we're using:

<details>
<summary><code>packages/app/src/components/techdocs/themePlugin.tsx</code></summary>

```tsx
import React from 'react';

import { createPlugin } from '@backstage/core-plugin-api';
import {
  TechDocsAddonLocations,
  createTechDocsAddonExtension,
  useShadowRoot,
} from '@backstage/plugin-techdocs-react';

import { useTheme } from '@material-ui/core/styles';
// Polyfill needed because:
//   - Typescript isn't aware of adoptedStyleSheets or replaceSync, so we need
//     the interface extensions
//   - Node doesn't have support for this, so it breaks the test suite
//   - All modern browsers do support this, though.
//   - We leave it for now because some devs still use older Safari
import 'construct-style-sheets-polyfill';

const StylesAddon = () => {
  const sr = useShadowRoot();
  const theme = useTheme();

  // This is a hack to let us insert styles into the TechDocs shadow root
  const sheet = new CSSStyleSheet();
  const styles = `
  .md-typeset hr { border-bottom: .05rem solid var(--md-default-fg-color--lightest); }
  :host > * { --md-code-bg-color: unset; }
  pre { line-height: 125%; }
  ${(theme as any)?.palette?.codeHighlight || ''}`;
  sheet.replaceSync(styles);

  if (sr && !sr.adoptedStyleSheets.includes(sheet)) {
    sr.adoptedStyleSheets = [...sr.adoptedStyleSheets, sheet];
  }

  return <></>;
};

const techdocsModuleAddonsIASPlugin = createPlugin({
  id: 'techdocsModuleAddonsIAS',
});

export const TechDocsStyles = techdocsModuleAddonsIASPlugin.provide(
  createTechDocsAddonExtension({
    name: 'TechDocsStyles',
    location: TechDocsAddonLocations.Settings,
    component: StylesAddon,
  }),
);
```

</details>

<details>
<summary><code>packages/app/src/theme/create_code_highlight_css.sh</code></summary>

```bash
#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'

# Generate pygments CSS for a theme.
# Themes here: https://pygments.org/styles/
# And here: https://github.com/Quansight-Labs/accessible-pygments/tree/main
THEME="${1:-github-light-colorblind}"

# Determine correct pygments version for techdocs:
publish="$(gh api /repos/<REDACTED_PATH_TO_FILE_SPECIFYING_TECHDOCS_VERSION> -H "Accept: application/vnd.github.v3.raw")"
mkdocsVersion="$(echo "$publish" | grep -oE "mkdocs-techdocs-core==\d.\d.\d" | cut -d'=' -f3)"

TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT
python3 -m venv "$TMP"
# shellcheck disable=SC1091
source "$TMP/bin/activate"
pip install "mkdocs-techdocs-core==$mkdocsVersion" accessible-pygments

# Generate CSS
pygmentize -S "$THEME" -f html -a .highlight > "code-highlight-$THEME.css"
```

</details>

<details>
<summary><code>packages/app/src/theme/iasTheme.ts</code></summary>

```ts
import codeHighlightCss from '!raw-loader!./code-highlight-a11y-high-contrast-light.css';
⋮
export const iasTheme = createUnifiedTheme({
  ...createBaseThemeOptions({
    palette: {
      ...palettes.light,
      codeHighlight: codeHighlightCss,
⋮
```

</details>

<details>
<summary><code>packages/app/src/App.tsx</code></summary>

```tsx
import { TechDocsStyles } from './components/techdocs/themePlugin';
⋮
    <Route
      path="/docs/:namespace/:kind/:name/*"
      element={<TechDocsReaderPage />}
    >
      <TechDocsAddons>
        <LightBox />
        <TextSize />
        <TechDocsStyles />
      </TechDocsAddons>
    </Route>
⋮
```

</details>

<details>
<summary><code>packages/app/src/theme/code-highlight-a11y-high-contrast-light.css</code></summary>

```css
pre { line-height: 125%; }
td.linenos .normal { color: inherit; background-color: transparent; padding-left: 5px; padding-right: 5px; }
span.linenos { color: inherit; background-color: transparent; padding-left: 5px; padding-right: 5px; }
td.linenos .special { color: #000000; background-color: #ffffc0; padding-left: 5px; padding-right: 5px; }
span.linenos.special { color: #000000; background-color: #ffffc0; padding-left: 5px; padding-right: 5px; }
.highlight .hll { background-color: #fae4c2 }
.highlight { background: #fefefe; color: #080808 }
.highlight .c { color: #515151 } /* Comment */
.highlight .err { color: #A12236 } /* Error */
.highlight .k { color: #6730C5 } /* Keyword */
.highlight .l { color: #7F4707 } /* Literal */
.highlight .n { color: #080808 } /* Name */
.highlight .o { color: #00622F } /* Operator */
.highlight .p { color: #080808 } /* Punctuation */
.highlight .ch { color: #515151 } /* Comment.Hashbang */
.highlight .cm { color: #515151 } /* Comment.Multiline */
.highlight .cp { color: #515151 } /* Comment.Preproc */
.highlight .cpf { color: #515151 } /* Comment.PreprocFile */
.highlight .c1 { color: #515151 } /* Comment.Single */
.highlight .cs { color: #515151 } /* Comment.Special */
.highlight .gd { color: #005B82 } /* Generic.Deleted */
.highlight .ge { font-style: italic } /* Generic.Emph */
.highlight .gh { color: #005B82 } /* Generic.Heading */
.highlight .gs { font-weight: bold } /* Generic.Strong */
.highlight .gu { color: #005B82 } /* Generic.Subheading */
.highlight .kc { color: #6730C5 } /* Keyword.Constant */
.highlight .kd { color: #6730C5 } /* Keyword.Declaration */
.highlight .kn { color: #6730C5 } /* Keyword.Namespace */
.highlight .kp { color: #6730C5 } /* Keyword.Pseudo */
.highlight .kr { color: #6730C5 } /* Keyword.Reserved */
.highlight .kt { color: #7F4707 } /* Keyword.Type */
.highlight .ld { color: #7F4707 } /* Literal.Date */
.highlight .m { color: #7F4707 } /* Literal.Number */
.highlight .s { color: #00622F } /* Literal.String */
.highlight .na { color: #912583 } /* Name.Attribute */
.highlight .nb { color: #7F4707 } /* Name.Builtin */
.highlight .nc { color: #005B82 } /* Name.Class */
.highlight .no { color: #005B82 } /* Name.Constant */
.highlight .nd { color: #7F4707 } /* Name.Decorator */
.highlight .ni { color: #00622F } /* Name.Entity */
.highlight .ne { color: #6730C5 } /* Name.Exception */
.highlight .nf { color: #005B82 } /* Name.Function */
.highlight .nl { color: #7F4707 } /* Name.Label */
.highlight .nn { color: #080808 } /* Name.Namespace */
.highlight .nx { color: #080808 } /* Name.Other */
.highlight .py { color: #005B82 } /* Name.Property */
.highlight .nt { color: #005B82 } /* Name.Tag */
.highlight .nv { color: #A12236 } /* Name.Variable */
.highlight .ow { color: #6730C5 } /* Operator.Word */
.highlight .pm { color: #080808 } /* Punctuation.Marker */
.highlight .w { color: #080808 } /* Text.Whitespace */
.highlight .mb { color: #7F4707 } /* Literal.Number.Bin */
.highlight .mf { color: #7F4707 } /* Literal.Number.Float */
.highlight .mh { color: #7F4707 } /* Literal.Number.Hex */
.highlight .mi { color: #7F4707 } /* Literal.Number.Integer */
.highlight .mo { color: #7F4707 } /* Literal.Number.Oct */
.highlight .sa { color: #00622F } /* Literal.String.Affix */
.highlight .sb { color: #00622F } /* Literal.String.Backtick */
.highlight .sc { color: #00622F } /* Literal.String.Char */
.highlight .dl { color: #00622F } /* Literal.String.Delimiter */
.highlight .sd { color: #00622F } /* Literal.String.Doc */
.highlight .s2 { color: #00622F } /* Literal.String.Double */
.highlight .se { color: #00622F } /* Literal.String.Escape */
.highlight .sh { color: #00622F } /* Literal.String.Heredoc */
.highlight .si { color: #00622F } /* Literal.String.Interpol */
.highlight .sx { color: #00622F } /* Literal.String.Other */
.highlight .sr { color: #A12236 } /* Literal.String.Regex */
.highlight .s1 { color: #00622F } /* Literal.String.Single */
.highlight .ss { color: #005B82 } /* Literal.String.Symbol */
.highlight .bp { color: #7F4707 } /* Name.Builtin.Pseudo */
.highlight .fm { color: #005B82 } /* Name.Function.Magic */
.highlight .vc { color: #A12236 } /* Name.Variable.Class */
.highlight .vg { color: #A12236 } /* Name.Variable.Global */
.highlight .vi { color: #A12236 } /* Name.Variable.Instance */
.highlight .vm { color: #7F4707 } /* Name.Variable.Magic */
.highlight .il { color: #7F4707 } /* Literal.Number.Integer.Long */
```

</details>

<details>
<summary><code>.prettierignore</code></summary>

```gitignore 
# autogenerated files:
packages/app/src/theme/code-highlight-*.css
```

</details>

I'm sure there's a better way; I'm sure this could be nicely packaged into a plugin; I'm sure this could be made user-selectable (and overridable, so I can use my [favorite theme](https://github.com/folke/tokyonight.nvim/blob/main/extras/lua/tokyonight_day.lua) without making it the company default) -- feel free to do this. Hopefully this saves someone a bit of time.
