### ISSUE TITLE
Provide some default values + secrets for the Scaffolder context

### ISSUE THREAD

**Issue by benjdlambert** [backstage/backstage#9461]
Following on from the closed #6632, it would be great if we could define some default values that can be used in the template manifest (`template.yaml`) and also in `fetch:template`.

## Feature Suggestion

The aforementioned issue was closed because the solution of having an action that could use `ctx.output('config', configApi.get('scaffolder.environment'));` was enough to satisfy the request.

The template author could use the output of one action to template values into the next using `${{ ctx.outputs.myStep.blah }}` to template that into a succeeding action.

The problem that we have with that solution is there is no first class support for secrets, and how to have some default secrets context that can be used in the templating manifest file or in the actions under `ctx.secrets`.

## Possible Implementation

So first off, I'm contemplating removing the `ctx.secrets` way of accessing secrets in actions, and thinking that it would be better if these things were passed in through `inputs` to the action and are just templated in rather than the action assuming that secrets exist. It's going to make action writing a little less coupled to the context and things that might or might not exist there. Can probably address this issue separately though.

In order to supply some default parameters, and default secrets, we could go two ways. One I think is simpler, and one uses some more of the more known capabilities of config that backstage integrators and plugin developers might be aware of.

### Open Config approach

We could have the option to provide a default environment that would get injected into the nunjucks templating in `app-config.yaml`

```yaml
# app-config.yaml 
...
scaffolder:
  defaultEnvironment:
    parameters:
      region: eu-west-1
    secrets:
      AWS_ACCESS_KEY: ${AWS_ACCESS_KEY}
...
```

The above is a pretty simple config, and pretty clear distinction between secrets and parameters that could provide some defaults at the templating level in `template.yaml`. 

`${{ parameters.region }}` would be resolved to `eu-west-1` unless the `parameters` in the `template.yaml` had an option to override that. And the same for `${{ secrets.AWS_ACCESS_KEY }}`, unless this was overridden when creating the task by using the `SecretsContext` or/and a `CustomFieldExtension`.

### `config.d.ts` approach

It would also be possible for developers to just define a `defaultEnvironment`, and the keys under that object would be subject to `secret` or `backend` visibility part of a `config.d.ts`.

## Usage

The idea here, is that in the `betav3` versions of templates, you could set up your `defaultEnvironment` either way, and be able to do things like this:

```yaml
apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: v1beta3-demo
  title: Test Action template
  description: scaffolder v1beta3 template demo
spec:
  owner: backstage/techdocs-core
  type: service

  parameters:
    ...

    - title: Choose a location
      properties:
        region:
          title: Region
          type: string
    ...

  steps:
    ...

    - id: template
      name: Create Repo
      action: fetch:template
      input:
        region:  ${{ parameters.region }}
    - id: push
      name: Push to S3
      action: publish:s3
      input:
        region:  ${{ parameters.region }}
        accessToken: ${{ secrets.AWS_ACCESS_TOKEN }}
    ...

**Comment by benjdlambert** [comment]
As an aside here also, and maybe this changes the design a little bit, what if we were able to set default values that you could also use as default values in the `parameters` block. Maybe we don't want to store the default values on the `parameters` namespace then, as it's gonna get super confusing for people as to what values they can and can't use in the template schema, only being allowed to use `parameters` in the `parameters` bit if it's a default value etc.

Maybe we could have something like:

```yaml
apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: v1beta3-demo
  title: Test Action template
  description: scaffolder v1beta3 template demo
spec:
  owner: backstage/techdocs-core
  type: service

  parameters:
    ...

    - title: Choose a location
      required: ['region']
      properties:
        region:
          title: Region
          type: string
          default: ${{ environment.region }}
    ...

  steps:
    ...

    - id: template
      name: Create Repo
      action: fetch:template
      input:
        region:  ${{ parameters.region }}
    - id: push
      name: Push to S3
      action: publish:s3
      input:
        region:  ${{ parameters.region }}
        accessToken: ${{ secrets.AWS_ACCESS_TOKEN }}
    ...
    ```
    
    And have the default values under `environment` instead?
