### ISSUE TITLE
Backstage installation : error in yarn packages and CORS error for backend

### ISSUE THREAD

**Issue by 7shivam** [backstage/backstage#9518]
How to configure backstage so it can be used other than "localhost".
Modified origin in app.config.yaml for both frontend and backend but facing the CORS issue.
Please help.

**Comment by Rugvip** [comment]
Hi, could you share some more information about what your environment and configuration is like? Please also share the actual error you are seeing and information about the request that is failing, as it's often the case that CORS is not actually the root cause of the issue.

**Comment by GreenElm** [comment]
I had similar issue, but was able to figured it out.  In my case, I created a docker container with the following:

- Nginx which would listen on port 8080 and proxy pass to port localhost:3000 (front-end app)
- Used the latest version of Backstage.io and followed instructions to build/install the app inside docker container with npm, npx, and yarn
  - Let front-end app run on http://localhost:3000
  - Let back-end app run on http://localhost:7007
    - Within app-config.yaml, I had to modify backend.cors.origin value to the URL which I was using locally in my browser:  http:// backstage-demo.local:8080

On my local system, in order to connect to the container (within the browser), I was using:  https://backstage-demo.local:8080
- To do this, I had to add an entry into my hosts file:  **127.0.0.1 backstage-demo.local**
  - Windows Systems:  C:\Windows\System32\drivers\etc\hosts
  - Linux Systems:  /etc/hosts 

To modify the **app-config.yaml** file (within the container via Dockerfile RUN command):
```
RUN sed -i 's/origin: http:\/\/localhost:3000/origin: http:\/\/backstage-demo.local:8080/' ./app-config.yaml 
```

If you notice, I didn't change the **app.baseUrl** nor the **backend.Url**, only the **backend.cors.origin** value.  Here are some the final code snippets (from app-config.yaml and this is not the entire file):
```
app:
  ## This was the original value and no need to change
  baseUrl: http://localhost:3000

backend:
   ## This was the original value and no need to change
  baseUrl: http://localhost:7007
  cors:
    ## This is what you need to modify.  Change it to the value of "Origin" in header.  You can see this if you use chrome and inspect the network traffic.  The failures will be in red and most likely say "CORS Error".  In my case, I was using URL:  http://backstage-demo.local:8080
    origin: http://backstage-demo.local:8080
    methods: [GET, HEAD, PATCH, POST, PUT, DELETE]
    credentials: true
````

For the curious here is my nginx configuration (within the container):
```
$ cat /etc/nginx/sites-available/default
server {
    listen 8080;
    server_name _;

    location / {
        proxy_pass http://localhost:3000/;
        }
}
```

Also, here is my docker-compose.yaml file:
```
version: "3"

services:
  backstage-demo:
    image: "backstage-demo"
    container_name: backstage-demo
    hostname: "backstage-demo.local"
    privileged: true
    ports:
      - 8080:8080 ## Nginx Poxy Forwards to Front-End (localhost:3000)
      - 3000:3000 ## Backstage.io Front-End (localhost)
      - 7007:7007 ## Backstage.io Back-End (localhost)
    extra_hosts:
      - "backstage-demo.local:127.0.0.1"
```

Not sure if this will fix your issues, but I hope it helps :)
