### ISSUE TITLE
Need help on using MicrosoftGraphClient (Get 401 Error)

### ISSUE THREAD

**Issue by simon-ouyang-rb** [backstage/backstage#9524]
### Discussed in https://github.com/backstage/backstage/discussions/9523

<div type='discussions-op-text'>

<sup>Originally posted by **simon-ouyang-rb** February 14, 2022</sup>
Hi, team, 

happy Monday! Could someone helping me with using MicrosoftGraphClient?

** It seems that the code keep getting 401 error but API works in Postman with the same clientId, tenantId and clientCredential**
Detail info is below.

Step 1: Azure App Registration

1. Create the Azure App Registration and get the clientId, clientSecret and tenentId
2. Add MS Graph API permissions
3. Test in Postman to verify the API is working with the given clientId, clientSecret and tenentId along with the generated token.

Step 2: Add the following in app-config.yaml
```
auth:
  environment: development
  providers:
    microsoft:
      development:
        clientId: ${AUTH_MICROSOFT_CLIENT_ID}
        clientSecret: ${AUTH_MICROSOFT_CLIENT_SECRET}
        tenantId: ${AUTH_MICROSOFT_TENANT_ID}
```

Step 3: Add EntityProvider in backend/src/plugins/catalog.ts

```
const msGraphOrgEntityProvider = MicrosoftGraphOrgEntityProvider.fromConfig(
  env.config,
  {
    id: 'https://graph.microsoft.com/v1.0',
    target: 'https://graph.microsoft.com/v1.0',
    logger: env.logger,
  },
);
builder.addEntityProvider(msGraphOrgEntityProvider);

// Trigger a read every 5 minutes
useHotCleanup(
  module,
  runPeriodically(() => msGraphOrgEntityProvider.read(), 5 * 60 * 1000),
);
```

Step 4: Add code in backeend/plugin/auth.t
```
            const target = "https://graph.microsoft.com/v1.0"
            const c = config.getOptionalConfig('catalog.processors.microsoftGraphOrg');
            const providers = c ? readMicrosoftGraphConfig(c) : [];
            const provider = providers.find(p => p.target === target);
              const client = MicrosoftGraphClient.create(provider)
              const response = await client.requestApi('users');
              const resp = await response.json()
              **console.log('resp', resp) // Keep getting 401 UnAuthorized Error
```
