### ISSUE TITLE
Error when registering a component from a selfhosted gitlab instance with a custom port

### ISSUE THREAD

**Issue by ItzEdgar** [backstage/backstage#9581]
## Expected Behavior

Component successfully imported.

## Actual Behavior

500 error from Backstage's UrlReader
![image](https://user-images.githubusercontent.com/23180135/154306736-0d0acfdc-f00c-44cc-8d38-93538ace4dd8.png)

## Steps to Reproduce

1. Create a local instance of gitlab using a custom port (i.e. anything other than 80 or 8080 so that you need to append the port to the host in order to access it. e.g. 9090)
2. Add it to app-config.yaml in the 'integrations' attribute
3. Create a repo with a catalog-info.yaml file
4. Try to import said repo through the 'Register an existing component' page

e.g. gitlab integration configuration
```yaml
integrations:
  gitlab:
    - host: 123.123.123.123
      baseUrl: http://123.123.123.123:9090
      apiBaseUrl: http://123.123.123.123:9090/api/v4
      token: abcd
```

## Context

Due to this error, I'm not able to use our self-hosted gitlab instance to store the components' repos. Cloning the repo to github and then trying to import it worked, but we would like to keep the code out of github and instead keep it in our private servers.

### app-config.yaml
```yaml
app:
  title: Scaffolded Backstage App
  # Should be the same as backend.baseUrl when using the `app-backend` plugin
  baseUrl: http://123.123.123.123:7007

organization:
  name: My Company

backend:
  baseUrl: http://123.123.123.123:7007
  listen:
    port: 7007
  
  csp:
    connect-src: ["'self'", 'http:', 'https:']
    upgrade-insecure-requests: false
    
  cors:
    origin: http://123.123.123.123:7007
    
  database:
    # client: sqlite3
    # connection: ':memory:'
    client: pg
    connection:
      host: 123.123.123.123
      port: 5438
      user: postgres
      password: Pass2020!

    cache:
      store: memory
    # workingDirectory: /tmp # Use this to configure a working directory for the scaffolder, defaults to the OS temp-dir

integrations:
  gitlab:
    - host: 123.123.123.123
      baseUrl: http://123.123.123.123:9090
      apiBaseUrl: http://123.123.123.123/api/v4
      token: abcdefg
```

### Error shown in the frontend
```json
{"error":{"name":"Error","message":"Error: Unable to read url, NotAllowedError: Reading from 'http://123.123.123.123:9090/org/component-repo/-/blob/master/catalog-info.yaml' is not allowed","level":"error","service":"backstage"},"request":{"method":"POST","url":"/locations?dryRun=true"},"response":{"statusCode":500}}
```

### Stack trace from container's logs
```text
2022-02-16T15:11:41.667Z backstage error Error: Unable to read url, NotAllowedError: Reading from 'http://123.123.123.123:9090/org/component-repo/-/blob/master/catalog-info.yaml' is not allowed type=errorHandler stack=Error: Error: Unable to read url, NotAllowedError: Reading from 'http://123.123.123.123:9090/org/component-repo/-/blob/master/catalog-info.yaml' is not allowed,
    at DefaultLocationService.processEntities (/app/node_modules/@backstage/plugin-catalog-backend/dist/index.cjs.js:3494:15),
    at async DefaultLocationService.dryRunCreateLocation (/app/node_modules/@backstage/plugin-catalog-backend/dist/index.cjs.js:3523:22),
    at async /app/node_modules/@backstage/plugin-catalog-backend/dist/index.cjs.js:2669:22
```

### Error in discovery
If I try to import this file through the gitlab-discovery in the app-config.yaml
**e.g.**
```yaml
catalog:
  rules:
    - allow: [Component, System, API, Group, User, Resource, Location]
  locations:
    # Backstage example components
    - type: gitlab-discovery
      target: http://123.123.123.123:9090/org/component-repo/-/blob/master/catalog-info.yaml
```
I get this error:
```text
catalog warn Processor GitLabDiscoveryProcessor threw an error while reading gitlab-discovery:http://123.123.123.123:9090/org/component-repo/-/blob/master/catalog-info.yaml; caused by Error: There is no GitLab integration that matches 123.123.123:9090. Please add a configuration entry for it under integrations.gitlab type=plugin entity=location:default/generated-abcd
```

Which leads me to believe this may be caused by the lack of a port in the gitlab host attribute. However, at the time being I can't add a port to the host or else I'll get the following error:
```text
Backend failed to start up, Error: Invalid Gitlab integration config, host '123.123.123.123:9090' should be just the host name, (e.g. "github.com"), not a URL
```

## Your Environment

Both backstage and gitlab are running in separate Docker containers in the same machine, and both can be accessed with the same ip (let's assume 123.123.123.123). Backstage is running on port 7007, whereas gitlab on port 9090.

**Browser Information:** 
- Firefox 97.0 

- Output of `yarn backstage-cli info`:
```text
yarn run v1.22.17
$ /app/node_modules/.bin/backstage-cli info
OS:   Linux 3.10.0-1127.el7.x86_64 - linux/x64
node: v16.13.2
yarn: 1.22.17
cli:  0.13.0 (installed)

Dependencies:
  @backstage/backend-common                                0.10.5
  @backstage/backend-tasks                                 0.1.4
  @backstage/catalog-client                                0.5.5
  @backstage/catalog-model                                 0.9.10
  @backstage/cli-common                                    0.1.6
  @backstage/cli                                           0.13.0
  @backstage/config-loader                                 0.9.3
  @backstage/config                                        0.1.13
  @backstage/errors                                        0.2.0
  @backstage/integration                                   0.7.2
  @backstage/plugin-app-backend                            0.3.22
  @backstage/plugin-auth-backend                           0.8.0
  @backstage/plugin-catalog-backend                        0.21.1
  @backstage/plugin-catalog-common                         0.1.1
  @backstage/plugin-permission-common                      0.4.0
  @backstage/plugin-permission-node                        0.4.1
  @backstage/plugin-proxy-backend                          0.2.16
  @backstage/plugin-scaffolder-backend-module-cookiecutter 0.1.9
  @backstage/plugin-scaffolder-backend                     0.15.22
  @backstage/plugin-scaffolder-common                      0.1.3
  @backstage/plugin-search-backend-node                    0.4.5
  @backstage/plugin-search-backend                         0.4.0
  @backstage/plugin-techdocs-backend                       0.13.1
  @backstage/search-common                                 0.2.2
  @backstage/techdocs-common                               0.11.5
  @backstage/types                                         0.1.1
Done in 0.69s.
```
