### ISSUE TITLE
[Plugin] AWS Proton

### ISSUE THREAD

**Issue by clareliguori** [backstage/backstage#9741]
Hello! I'm from the [AWS Proton](https://aws.amazon.com/proton/) service team, and we're exploring use cases for a Proton plugin in Backstage and what that could look like.  At a high-level, this is what I'm thinking right now -- I would love feedback:  With Proton + Backstage, you can use Proton to standardize infrastructure and pipeline configuration, so that your developers don't have to keep things like CloudFormation and Terraform templates up-to-date in their source code repos.  Backstage still acts as your developer portal for creating new applications, cataloging applications, and centralizing your developer tools into a single UI.

I think there are two parts to the Proton+Backstage integration:

**1. Backstage Template Action**:
As part of creating and scaffolding out a new component in Backstage, Backstage Software Templates can create and deploy a Proton service in order to provision the infrastructure and the CI/CD pipeline needed for the application.  For example, instead of having the scaffolder drop a CloudFormation or Terraform template in the developer's source code repo, I would register that CloudFormation/Terraform template in Proton and keep it up-to-date there (freeing up developers from having to deal with keeping it up-to-date themselves).

Snippet of a scaffolder template's steps:
```
    - id: publish
      name: Publish
      action: publish:github
      input:
        allowedHosts: ['github.com']
        description: This is ${{ parameters.name }}
        repoUrl: ${{ parameters.repoUrl }}

    - id: provision
      name: Create Proton Service
      action: aws-proton:create
      input:
        ???
```

The catalog entity can then be annotated with the Proton service ARN, along with any resources that were provisioned in the Proton service, for use by front-end plugins.

Example annotations for a catalog entity:
```
aws.amazon.com/proton-service-arn: "arn:aws:proton:us-west-2:123456789012:service/MyService"
aws.amazon.com/codepipeline-service-arn: "arn:aws:codepipeline:us-west-2:123456789012:MyServicePipeline"
aws.amazon.com/ecs-service-arn: "arn:aws:ecs:us-west-2:111222333444:service/my-http-service"
```

In the example above, the `proton-service-arn` annotation can be used by the proposed Proton plugin (described below) to display the Proton service in the Backstage UI; the `codepipeline-service-arn` annotation can be used by the [proposed CodePipeline plugin](https://github.com/backstage/backstage/issues/2256) to display the pipeline; and the `ecs-service-arn` annotation can be used by the [proposed ECS plugin](https://github.com/backstage/backstage/issues/5355) to display the deployed containers.

**2. Backstage Plugin**: 
The Proton plugin would display information in the Backstage UI about the component's Proton service and its deployed Proton service instances, with a link to the Proton service in the AWS console.  This is an area where I'd love input on what types of information and/or actions you'd like to see/take in the Backstage UI for Proton.
