### ISSUE TITLE
Processing user for `github-org` unable to handle user with `-` postfix

### ISSUE THREAD

**Issue by alileza** [backstage/backstage#9762]
## Expected Behavior

Able to process user with `-` postfix

## Actual Behavior

```
[1] 2022-02-23T14:28:53.749Z catalog warn Policy check failed; caused by Error: "metadata.name" is not valid; expected a string that is sequences of [a-zA-Z0-9] separated by any of [-_.], at most 63 characters in total but found "username-". To learn more about catalog file format, visit: https://github.com/backstage/backstage/blob/master/docs/architecture-decisions/adr002-default-catalog-file-format.md type=plugin entity=user:default/username-
```

## Steps to Reproduce

1. Have a user in your orgs with username like `username-` or `whatever-`
2. Set catalog configuration to

```yaml
catalog:
  rules:
    - allow: [Component, API, Group, User, Location, Template]
  locations:
    - type: github-org
      target: https://github.com/myorgs
```

3. You'd receive those warning unable to process user while doing `[1] 2022-02-23T14:28:53.733Z catalog debug Processing user:default/username- type=plugin`
