### ISSUE TITLE
API's `View Techdocs` urls (/API) do not match the case of the url (/api) to generated docs

### ISSUE THREAD

**Issue by shyamajp** [backstage/backstage#9941]
## Expected Behavior

- Clicking on View Techdocs in AboutCard should navigate to the generated techdocs

## Actual Behavior

- 404 error
```ERROR 404: TypeError: Failed to fetch Looks like someone dropped the mic!```

## Steps to Reproduce

1. Go to APIs
2. Click on `foo`
3. Click on `View Techdocs`
4. Not Found Error

Mysterious behavior - I have multiple API docs guiding to the same techdoc (it's a md file in the same repository), all of which fail to load because of url mismatch inside Docker. However, when I run locally, about half of the docs open with uppercased url (API) although the docs are generated at lowercased api.

## Context

Docs generated at
http://localhost:7000/docs/default/api/foo

View Techdocs navigating to
http://localhost:7000/docs/default/API/foo

foo.yaml
```yaml
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: foo
  description: Foo API
  tags:
    - python
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: openapi
  lifecycle: production
  owner: team-a
  system: system-a
  definition: |
// definition goes here (omitted)
```

mkdocs.yml
```yaml
site_name: 'Foo API'

nav:
  - Getting Started: index.md

plugins:
  - techdocs-core
```

Dockerfile (additionally added lines for techdocs)
```Dockerfile
RUN apt-get update && apt-get install -y python3.7 python3-pip python3-markupsafe
RUN update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.7 2
RUN pip3 install mkdocs-techdocs-core
```

api-config.yaml (related to techdocs)
```yaml
techdocs:
  builder: 'local'
  generator:
    # This avoids running docker inside docker
    runIn: 'local'
  publisher:
    type: 'local'
```

## Your Environment

- Browser Information: Google Chrome Version 98.0.4758.109 (Official Build) (x86_64)
- Output of `yarn backstage-cli info`: 

```text
OS:   Darwin 21.3.0 - darwin/x64
node: v14.18.1
yarn: 1.22.17
cli:  0.13.0 (installed)

Dependencies:
  @backstage/app-defaults                                  0.1.5
  @backstage/backend-common                                0.10.5
  @backstage/backend-tasks                                 0.1.4
  @backstage/catalog-client                                0.5.5
  @backstage/catalog-model                                 0.9.10
  @backstage/cli-common                                    0.1.6
  @backstage/cli                                           0.13.0
  @backstage/config-loader                                 0.9.3
  @backstage/config                                        0.1.13
  @backstage/core-app-api                                  0.5.1
  @backstage/core-components                               0.8.6, 0.8.8
  @backstage/core-plugin-api                               0.6.0
  @backstage/errors                                        0.2.0
  @backstage/integration-react                             0.1.19
  @backstage/integration                                   0.7.2
  @backstage/plugin-analytics-module-ga                    0.1.9
  @backstage/plugin-api-docs                               0.7.0
  @backstage/plugin-app-backend                            0.3.22
  @backstage/plugin-auth-backend                           0.8.0
  @backstage/plugin-catalog-backend                        0.21.1
  @backstage/plugin-catalog-common                         0.1.1
  @backstage/plugin-catalog-graph                          0.2.8
  @backstage/plugin-catalog-import                         0.7.10
  @backstage/plugin-catalog-react                          0.6.12
  @backstage/plugin-catalog                                0.7.10
  @backstage/plugin-github-actions                         0.4.33
  @backstage/plugin-org                                    0.4.0
  @backstage/plugin-permission-common                      0.4.0
  @backstage/plugin-permission-node                        0.4.1
  @backstage/plugin-permission-react                       0.3.0
  @backstage/plugin-proxy-backend                          0.2.16
  @backstage/plugin-scaffolder-backend-module-cookiecutter 0.1.9
  @backstage/plugin-scaffolder-backend                     0.15.22
  @backstage/plugin-scaffolder-common                      0.1.3
  @backstage/plugin-scaffolder                             0.12.0
  @backstage/plugin-search-backend-node                    0.4.5
  @backstage/plugin-search-backend                         0.4.0
  @backstage/plugin-search                                 0.6.0
  @backstage/plugin-tech-radar                             0.5.3
  @backstage/plugin-techdocs-backend                       0.13.1
  @backstage/plugin-techdocs                               0.13.1
  @backstage/plugin-user-settings                          0.3.17
  @backstage/search-common                                 0.2.2
  @backstage/techdocs-common                               0.11.5
  @backstage/test-utils                                    0.2.3
  @backstage/theme                                         0.2.14
  @backstage/types                                         0.1.1
  @backstage/version-bridge                                0.1.1
```
