### ISSUE TITLE
`publish:github` action cannot add users as repository collaborators

### ISSUE THREAD

**Issue by Fs00** [backstage/backstage#9943]
We've discovered that the `collaborators` parameter of the `publish:github` action - which allows adding collaborators when creating a GH repo - works only for  teams and **not for users**.
This is caused by a problem in the current implementation of the action. The given collaborator usernames are always treated as team slugs, as you can see here:

https://github.com/backstage/backstage/blob/733152180739c3230fc13428d5af07c8419ac697/plugins/scaffolder-backend/src/scaffolder/actions/builtin/publish/github.ts#L286-L306

## Expected Behavior

Collaborators should be added to the GitHub project regardless of whether they are teams or users. 

## Actual Behavior

When you try to add a user as a collaborator, you always get the warning:
`Skipping [permission] access for [user], Not Found`
and the user is not added as a collaborator.

## Steps to Reproduce

1. Set up a scaffolding template that uses the `publish:github` action and tries to add a user as a collaborator, like in the following example:
```yaml
    - id: publish
      name: Publish
      action: publish:github
      input:
        allowedHosts: ["github.com"]
        description: ${{ parameters.description }}
        repoUrl: ${{ parameters.repoUrl }}
        collaborators:
          - username: valid_github_username
            access: maintain
```
2. Run the template
3. In the output of the Publish step, observe that the following warning is shown: `Skipping maintain access for valid_github_username, Not Found`

## Context

We have also seen that GitHub provides different APIs for [adding a user](https://octokit.github.io/rest.js/v18#repos-add-collaborator) versus [adding a team as a collaborator](https://octokit.github.io/rest.js/v18#teams-add-or-update-repo-permissions-in-org).
Therefore, in order to fix this issue, the structure of the `collaborators` parameter needs to be changed in order to be able to distinguish whether the given username refers to a user or a team.
