### ISSUE TITLE
Load pre-rendered docs from gh-pages branch 

### ISSUE THREAD

**Issue by aelbozie** [backstage/backstage#9957]
We use `mkdocs gh-deploy`  in our CI pipeline.
This deploys the redered `site/` to the `gh-pages` branch where GitHub serves it.

The issue is we have **rendered html files alongside the markdown files** in `docs/` dir.

so our `mkdocs.yaml` has this:
```yaml
nav:
    - Home: index.md
    - Warehouse Size: warehouse.md
    - Deployment: deployment.md
    - Style Guide: styleguide.md
    - Reporting Issues: issues.md
    - dbt Docs: dbt.html

<omitted>

plugins:
    - techdocs-core

```
This works well on GitHub Pages. But the rendered html page gives a 404 on Backstage.

Is there a way to allow TechDocs to serve from the rendered gh-pages branch as opposed to running `mkdocs` ?
