### ISSUE TITLE
We CANNOT import both Azure and BitBucket Repos in backstage using azure-discovery and bitbucket-discovery.

### ISSUE THREAD

**Issue by simon-ouyang-demo** [backstage/backstage#9960]
## Expected Behavior
We should be able to import both Azure and BitBucket Repos in backstage using azure-discovery and bitbucket-discovery

## Actual Behavior
We CANNOT import both Azure and BitBucket Repos in backstage using azure-discovery and bitbucket-discovery. We have to choose either azure-discovery and bitbucket-discovery to auto-discover either azure and bitbucket repos.

## Steps to Reproduce
1. In app-configm.yaml file, put the Azure DevOps and BitBucket Integration there.
```
integrations:
  azure:
    - host: dev.azure.com
      token: ${AZURE_TOKEN}
  bitbucket:
    - host: <bitbucket-server-name>
      username: <bitbucket-user-name>
      token: ${BITBUCKET_TOKEN}
      apiBaseUrl: https://<bitbucket-server-name>/rest/api/1.0
```
2. In app-configm.yaml file, put the Azure DevOps and BitBucket auto-discovery there.

```
  locations:
    - type: azure-discovery
      target: https://dev.azure.com/<Org_Name>/<Project_Name>
    - type: bitbucket-discovery
      target: https://<bitbucket-server-name>/projects/*/repos/*/catalog-info.yaml
```

3. Run the Application. 
You can only see the azure repos.

4 In app-configm.yaml file, update the Azure DevOps and BitBucket auto-discovery there (Reverse the Order).

```
  locations:
    - type: bitbucket-discovery
     - target: https://<bitbucket-server-name>/projects/*/repos/*/catalog-info.yaml
     - type: azure-discovery
       target: https://dev.azure.com/<Org_Name>/<Project_Name>
```
5. Run the Application. 
You can only see the bitbucket repos.

## Context
In my project, we want to show repos in both bitbucket and azure devops at the same time but we cannot.

## Your Environment

- Browser Information: 
```text
Version 98.0.4758.109 (Official Build) (x86_64)
```
- Output of `yarn backstage-cli info`: 

```text
OS:   Darwin 20.6.0 - darwin/x64
node: v14.17.6
yarn: 1.22.17
cli:  0.9.1 (installed)

Dependencies:
  @backstage/app-defaults                                  0.1.1
  @backstage/backend-common                                0.10.7, 0.9.11
  @backstage/catalog-client                                0.5.2, 0.6.0, 0.7.1
  @backstage/catalog-model                                 0.10.1, 0.9.7, 0.9.10
  @backstage/cli-common                                    0.1.6
  @backstage/cli                                           0.9.1
  @backstage/config-loader                                 0.8.0, 0.9.3
  @backstage/config                                        0.1.11, 0.1.13, 0.1.15
  @backstage/core-app-api                                  0.1.23
  @backstage/core-components                               0.7.5
  @backstage/core-plugin-api                               0.1.13, 0.2.1
  @backstage/errors                                        0.1.5, 0.2.0, 0.2.2
  @backstage/integration-react                             0.1.14
  @backstage/integration                                   0.6.9, 0.7.2
  @backstage/plugin-api-docs                               0.6.15
  @backstage/plugin-app-backend                            0.3.19
  @backstage/plugin-auth-backend                           0.4.9
  @backstage/plugin-auth-node                              0.1.0
  @backstage/plugin-azure-devops-backend                   0.2.2
  @backstage/plugin-azure-devops-common                    0.1.0
  @backstage/plugin-azure-devops                           0.1.4
  @backstage/plugin-catalog-backend-module-msgraph         0.2.15
  @backstage/plugin-catalog-backend                        0.18.0, 0.21.3
  @backstage/plugin-catalog-common                         0.1.2
  @backstage/plugin-catalog-graph                          0.2.2
  @backstage/plugin-catalog-import                         0.7.4
  @backstage/plugin-catalog-react                          0.6.4
  @backstage/plugin-catalog                                0.7.3
  @backstage/plugin-explore-react                          0.0.7
  @backstage/plugin-explore                                0.3.21
  @backstage/plugin-github-actions                         0.4.25
  @backstage/plugin-home                                   0.4.6
  @backstage/plugin-jenkins-backend                        0.1.8
  @backstage/plugin-jenkins                                0.5.13
  @backstage/plugin-org                                    0.3.29
  @backstage/plugin-permission-common                      0.4.0
  @backstage/plugin-permission-node                        0.4.3
  @backstage/plugin-proxy-backend                          0.2.14
  @backstage/plugin-scaffolder-backend-module-cookiecutter 0.1.4
  @backstage/plugin-scaffolder-backend                     0.15.14
  @backstage/plugin-scaffolder-common                      0.1.1
  @backstage/plugin-scaffolder                             0.11.12
  @backstage/plugin-search-backend-node                    0.4.3
  @backstage/plugin-search-backend                         0.2.7
  @backstage/plugin-search                                 0.4.18
  @backstage/plugin-sonarqube                              0.2.7
  @backstage/plugin-tech-radar                             0.4.12
  @backstage/plugin-techdocs-backend                       0.10.9
  @backstage/plugin-techdocs                               0.12.7
  @backstage/plugin-todo-backend                           0.1.13
  @backstage/plugin-todo                                   0.1.15
  @backstage/plugin-user-settings                          0.3.11
  @backstage/search-common                                 0.2.1, 0.2.2
  @backstage/techdocs-common                               0.10.8
  @backstage/test-utils                                    0.1.23
  @backstage/theme                                         0.2.13
  @backstage/types                                         0.1.1, 0.1.3
  @backstage/version-bridge                                0.1.0
```

**Comment by pjungermann** [comment]
@simon-ouyang-rb
The config snippet at (4.) is faulty, but I assume this is just an error here.

> You can only see the azure repos.
> You can only see the bitbucket repos.

What does this mean exactly? Can you describe it a bit more?

How much repos do you have each?

As of my knowledge of the bitbucket-discovery, there is no link between the two at the discovery stage.

**Comment by simon-ouyang-rb** [comment]
@pjungermann Thank you for the response. 

In step 4,  I added an extra dash, sorry for the typo.  Correct config snippet is below

[bitbucket-discovery ](https://backstage.io/docs/integrations/bitbucket/discovery)is used for "auto" discover all the repos in an organization in the bitbucket. 

[azure-discovery](https://backstage.io/docs/integrations/azure/discovery) is used for "auto" discover all the repos in the project created in the azure devops. 

I suppose we use both like below, we can discover the repos hosted in both Azure and BitBucket, but we cannot.  We have more than 30 repos for azure devops and bitbucket respectively. 

```
  locations:
    - type: bitbucket-discovery
       target: https://<bitbucket-server-name>/projects/*/repos/*/catalog-info.yaml
     - type: azure-discovery
        target: https://dev.azure.com/<Org_Name>/<Project_Name>
```
